{"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/initWithNoDocumentFound:scanningProgress:tooDark:tooSmall:badPerspective:"},"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorGuidanceStates(im)initWithNoDocumentFound:scanningProgress:tooDark:tooSmall:badPerspective:","title":"initWithNoDocumentFound:scanningProgress:tooDark:tooSmall:badPerspective:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithNoDocumentFound:scanningProgress:tooDark:tooSmall:badPerspective:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"initWithNoDocumentFound:scanningProgress:tooDark:tooSmall:badPerspective:","kind":"identifier"}],"symbolKind":"method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates\/initwithnodocumentfound:scanningprogress:toodark:toosmall:badperspective:"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithNoDocumentFound:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"noDocumentFound"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanningProgress:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"scanningProgress","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tooDark:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"tooDark","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tooSmall:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"tooSmall","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"badPerspective:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"badPerspective","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorGuidanceStates"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorGuidanceStates"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates","type":"topic","kind":"symbol","title":"SBSDKUI2DocumentDataExtractorGuidanceStates","abstract":[{"type":"text","text":"Configure the captions of the user guidance hints for different scanning states."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates/initWithNoDocumentFound:scanningProgress:tooDark:tooSmall:badPerspective:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/initWithNoDocumentFound:scanningProgress:tooDark:tooSmall:badPerspective:","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates\/initwithnodocumentfound:scanningprogress:toodark:toosmall:badperspective:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNoDocumentFound:scanningProgress:tooDark:tooSmall:badPerspective:"}],"kind":"symbol","role":"symbol","title":"initWithNoDocumentFound:scanningProgress:tooDark:tooSmall:badPerspective:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNoDocumentFound:scanningProgress:tooDark:tooSmall:badPerspective:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates\/title","value":"SBSDKUI2DocumentDataExtractorGuidanceStates"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorGuidanceStates"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentDataExtractorGuidanceStates","kind":"identifier"}]}]}]}