{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscanneruiconfiguration\/finderlinewidth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscanneruiconfiguration\/finderlinewidth"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerUIConfiguration\/finderLineWidth"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"finderLineWidth","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"title":"finderLineWidth","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerUIConfiguration(py)finderLineWidth","navigatorTitle":[{"text":"finderLineWidth","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"sections":[],"abstract":[{"type":"text","text":"Width of the finder frame border."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerUIConfiguration"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finderLineWidth"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to 2."}]}],"kind":"content"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerUIConfiguration":{"abstract":[{"text":"Configuration for user interface of the detector screens for machine-readable zones.","type":"text"}],"title":"SBSDKUIMRZScannerUIConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscanneruiconfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerUIConfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKUIMRZScannerUIConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMRZScannerUIConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerUIConfiguration/finderLineWidth":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerUIConfiguration\/finderLineWidth","abstract":[{"type":"text","text":"Width of the finder frame border."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"finderLineWidth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"type":"topic","navigatorTitle":[{"text":"finderLineWidth","kind":"identifier"}],"title":"finderLineWidth","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscanneruiconfiguration\/finderlinewidth"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"finderLineWidth","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"finderLineWidth","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":" "},{"text":"finderLineWidth","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerUIConfiguration\/title","op":"replace","value":"SBSDKUIMRZScannerUIConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerUIConfiguration\/fragments","value":[{"text":"SBSDKUIMRZScannerUIConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIMRZScannerUIConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerUIConfiguration~1finderLineWidth\/title","value":"finderLineWidth"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerUIConfiguration~1finderLineWidth\/fragments","value":[{"text":"finderLineWidth","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}