{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessByTileConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessbytileconfiguration\/initwithenabled:minprocessedfraction:maxprocessedfraction:minnumberofrequiredsymbols:tilesize:"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"enabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minProcessedFraction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"minProcessedFraction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maxProcessedFraction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"maxProcessedFraction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minNumberOfRequiredSymbols:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"minNumberOfRequiredSymbols","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tileSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"tileSize","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProcessByTileConfiguration(im)initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:","kind":"identifier"}],"title":"initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:","navigatorTitle":[{"text":"initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessByTileConfiguration\/initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProcessByTileConfiguration":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessbytileconfiguration","title":"SBSDKProcessByTileConfiguration","abstract":[{"text":"Configuration for processing image by tiles.","type":"text"},{"text":" ","type":"text"},{"text":"This can be used to make the document quality analyzer processing faster with lower memory consumption,","type":"text"},{"text":" ","type":"text"},{"text":"but prediction can be less accurate.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessByTileConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProcessByTileConfiguration/initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:":{"abstract":[],"title":"initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessbytileconfiguration\/initwithenabled:minprocessedfraction:maxprocessedfraction:minnumberofrequiredsymbols:tilesize:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessByTileConfiguration\/initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKProcessByTileConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessByTileConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessByTileConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessByTileConfiguration\/navigatorTitle","op":"replace"}]}]}