{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"appearanceDuration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"text":" = 0.2, ","kind":"text"},{"text":"displayDuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":" = 0.4, ","kind":"text"},{"kind":"externalParam","text":"disappearanceDuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"text":" = 0.2, ","kind":"text"},{"text":"overlayColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" = .black.withAlphaComponent(0.3), ","kind":"text"},{"kind":"externalParam","text":"imageContentMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIViewContentMode","text":"ContentMode","kind":"typeIdentifier"},{"text":" = .scaleAspectFit, ","kind":"text"},{"text":"finalFrame","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":" = .zero)","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"appearanceDuration","content":[{"type":"paragraph","inlineContent":[{"text":"The amount of time the document takes to appear.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"The display time for the document, before it animates to the provided valid final frame or disappear otherwise.","type":"text"}],"type":"paragraph"}],"name":"displayDuration"},{"name":"disappearanceDuration","content":[{"inlineContent":[{"type":"text","text":"The amount of time the document takes to disappear or animate to the final frame."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The color used to overlay the camera screen during the animation."}]}],"name":"overlayColor"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The content mode for the document’s image view being animated."}]}],"name":"imageContentMode"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The final frame where the animated document should animate to."}]}],"name":"finalFrame"}],"kind":"parameters"}],"metadata":{"title":"init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"init","role":"symbol","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appearanceDuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":", ","kind":"text"},{"text":"displayDuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"text":"disappearanceDuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":", ","kind":"text"},{"text":"overlayColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"imageContentMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIViewContentMode","text":"ContentMode","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"finalFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentAnimationConfiguration(im)initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Creates a new instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentanimationconfiguration\/init(appearanceduration:displayduration:disappearanceduration:overlaycolor:imagecontentmode:finalframe:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentanimationconfiguration\/init(appearanceduration:displayduration:disappearanceduration:overlaycolor:imagecontentmode:finalframe:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentAnimationConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentAnimationConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentanimationconfiguration","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A class to configure the document animation properties."}],"title":"SBSDKDocumentAnimationConfiguration","navigatorTitle":[{"text":"SBSDKDocumentAnimationConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentAnimationConfiguration/init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)":{"abstract":[{"text":"Creates a new instance of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:"}],"kind":"symbol","title":"init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentanimationconfiguration\/init(appearanceduration:displayduration:disappearanceduration:overlaycolor:imagecontentmode:finalframe:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"appearanceDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"displayDuration"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"disappearanceDuration"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"overlayColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"imageContentMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIViewContentMode","kind":"typeIdentifier","text":"ContentMode"},{"kind":"text","text":", "},{"text":"finalFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":")"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"initWithAppearanceDuration:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"appearanceDuration"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayDuration:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") "},{"text":"displayDuration","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disappearanceDuration:"},{"kind":"text","text":"("},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"disappearanceDuration"},{"text":" ","kind":"text"},{"kind":"identifier","text":"overlayColor:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"text":"overlayColor","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageContentMode:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@UIViewContentMode","text":"UIViewContentMode","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"imageContentMode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finalFrame:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"finalFrame"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The amount of time the document takes to appear.","type":"text"}]}],"name":"appearanceDuration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The display time for the document, before it animates to the provided valid final frame or disappear otherwise."}]}],"name":"displayDuration"},{"content":[{"inlineContent":[{"text":"The amount of time the document takes to disappear or animate to the final frame.","type":"text"}],"type":"paragraph"}],"name":"disappearanceDuration"},{"name":"overlayColor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The color used to overlay the camera screen during the animation."}]}]},{"name":"imageContentMode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The content mode for the document’s image view being animated."}]}]},{"name":"finalFrame","content":[{"inlineContent":[{"type":"text","text":"The final frame where the animated document should animate to."}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"SBSDKDocumentAnimationConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentAnimationConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentAnimationConfiguration"}],"op":"replace"},{"value":"initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}