{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkwhiteblackpointfilter\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKWhiteBlackPointFilter\/isEqual:","interfaceLanguage":"occ"},"metadata":{"title":"isEqual:","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKWhiteBlackPointFilter(im)isEqual:","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"roleHeading":"Instance Method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKWhiteBlackPointFilter"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKWhiteBlackPointFilter":{"abstract":[{"type":"text","text":"Maps image value channel so that all the pixels darker than the black point are set to 0,"},{"type":"text","text":" "},{"type":"text","text":"all the pixels brighter than the white point are set to 255, and the pixels in between"},{"type":"text","text":" "},{"type":"text","text":"are linearly scaled."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKWhiteBlackPointFilter"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKWhiteBlackPointFilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKWhiteBlackPointFilter"}],"title":"SBSDKWhiteBlackPointFilter","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkwhiteblackpointfilter"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKWhiteBlackPointFilter/isEqual:":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKWhiteBlackPointFilter\/isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkwhiteblackpointfilter\/isequal:","role":"symbol","kind":"symbol","abstract":[],"title":"isEqual:","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKWhiteBlackPointFilter\/title","value":"SBSDKWhiteBlackPointFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKWhiteBlackPointFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKWhiteBlackPointFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKWhiteBlackPointFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKWhiteBlackPointFilter"}]}]}]}