{"metadata":{"role":"symbol","roleHeading":"Instance Property","title":"fileStorageBaseDirectory","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fileStorageBaseDirectory","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)ScanbotSDKConfiguration(py)fileStorageBaseDirectory","navigatorTitle":[{"kind":"identifier","text":"fileStorageBaseDirectory"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration\/fileStorageBaseDirectory","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The base directory for storing scanned files. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", which uses the application’s documents directory."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fileStorageBaseDirectory"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/filestoragebasedirectory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/filestoragebasedirectory"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotSDKConfiguration":{"url":"\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration","title":"ScanbotSDKConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration","abstract":[{"type":"codeVoice","code":"ScanbotSDKConfiguration"},{"text":" is a configuration class that allows you to customize various settings and behavior of the Scanbot SDK.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotSDKConfiguration/fileStorageBaseDirectory":{"type":"topic","title":"fileStorageBaseDirectory","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fileStorageBaseDirectory","kind":"identifier"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/filestoragebasedirectory","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration\/fileStorageBaseDirectory","navigatorTitle":[{"text":"fileStorageBaseDirectory","kind":"identifier"}],"abstract":[{"text":"The base directory for storing scanned files. Defaults to ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":", which uses the application’s documents directory."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","title":"ScanbotDocumentScannerSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"fileStorageBaseDirectory"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"fileStorageBaseDirectory","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" * "},{"kind":"identifier","text":"fileStorageBaseDirectory"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/title","value":"ScanbotSDKConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/fragments","value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/navigatorTitle","value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration~1fileStorageBaseDirectory\/title","op":"replace","value":"fileStorageBaseDirectory"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration~1fileStorageBaseDirectory\/fragments","value":[{"text":"fileStorageBaseDirectory","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}