{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration"]]},"sections":[],"metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"fromJsonWithJson:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKProcessByTileConfiguration(cm)fromJsonWithJson:","symbolKind":"method","roleHeading":"Type Method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration\/fromJsonWithJson:","interfaceLanguage":"occ"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProcessByTileConfiguration","text":"SBSDKProcessByTileConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessByTileConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration for processing image by tiles."},{"type":"text","text":" "},{"type":"text","text":"This can be used to make the document quality analyzer processing faster with lower memory consumption,"},{"type":"text","text":" "},{"type":"text","text":"but prediction can be less accurate."}],"role":"symbol","title":"SBSDKProcessByTileConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessByTileConfiguration/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration\/fromjsonwithjson:","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration\/fromJsonWithJson:","kind":"symbol","title":"fromJsonWithJson:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKProcessByTileConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/navigatorTitle","op":"replace"}]}]}