{"metadata":{"title":"secondaryMinimumInset","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"secondaryMinimumInset","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"secondaryMinimumInset"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration(py)secondaryMinimumInset","symbolKind":"property","role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewFinderConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"secondaryMinimumInset","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerviewfinderconfiguration\/secondaryminimuminset"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerviewfinderconfiguration\/secondaryminimuminset"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"text":"The minimum space from the primary view finder to the secondary view finder for each edge.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Defaults to {10, 10, 10, 10}."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewFinderConfiguration\/secondaryMinimumInset","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewFinderConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewFinderConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}],"role":"symbol","abstract":[{"type":"text","text":"The view finder configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"text":" ","type":"text"},{"type":"text","text":"Sometimes it is necessary to limit a live video frame detection or recognition to a certain rectangular area with"},{"type":"text","text":" "},{"text":"a specific aspect ratio: the region or rectangle of interest. This is where a view finder comes in.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"It crops the video frame to that region of interest before passing it to any detector or recognizer. Usually"},{"type":"text","text":" "},{"type":"text","text":"the performance of detectors\/recognizers gain a benefit from it because less pixels must be processed."},{"type":"text","text":" "},{"type":"text","text":"Additionally, to guide the user, the view finder visualizes the region of interest by drawing a rectangle around"},{"text":" ","type":"text"},{"type":"text","text":"on the user interface."}],"kind":"symbol","title":"SBSDKBaseScannerViewFinderConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewfinderconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewFinderConfiguration/secondaryMinimumInset":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"secondaryMinimumInset"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"title":"secondaryMinimumInset","navigatorTitle":[{"text":"secondaryMinimumInset","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewfinderconfiguration\/secondaryminimuminset","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewFinderConfiguration\/secondaryMinimumInset","abstract":[{"type":"text","text":"The minimum space from the primary view finder to the secondary view finder for each edge."},{"type":"text","text":" "},{"type":"text","text":"Defaults to {10, 10, 10, 10}."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"secondaryMinimumInset"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"secondaryMinimumInset"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier","text":"UIEdgeInsets"},{"text":" ","kind":"text"},{"text":"secondaryMinimumInset","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"SBSDKBaseScannerViewFinderConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewFinderConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewFinderConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}]},{"value":"secondaryMinimumInset","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewFinderConfiguration~1secondaryMinimumInset\/title"},{"value":[{"kind":"identifier","text":"secondaryMinimumInset"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewFinderConfiguration~1secondaryMinimumInset\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}