{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeZone"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2vcarddocumentformatfieldtype\/timezone"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2vcarddocumentformatfieldtype\/timezone"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2VCardDocumentFormatFieldType\/timeZone","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Time Zone"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeZone"}],"title":"SBSDKUI2VCardDocumentFormatFieldType.timeZone","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2VCardDocumentFormatFieldType@SBSDKUI2VCardDocumentFormatFieldTypeTimeZone","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldTypeTimeZone"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2VCardDocumentFormatFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2VCardDocumentFormatFieldType":{"role":"symbol","title":"SBSDKUI2VCardDocumentFormatFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldType"}],"abstract":[{"type":"text","text":"vCard Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2VCardDocumentFormatFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2vcarddocumentformatfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.2"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2VCardDocumentFormatFieldType/timeZone":{"role":"symbol","title":"SBSDKUI2VCardDocumentFormatFieldType.timeZone","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeZone"}],"abstract":[{"type":"text","text":"Time Zone"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2VCardDocumentFormatFieldType\/timeZone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldTypeTimeZone"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2vcarddocumentformatfieldtype\/timezone"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2VCardDocumentFormatFieldTypeTimeZone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldTypeTimeZone"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldTypeTimeZone"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2VCardDocumentFormatFieldType\/title","value":"SBSDKUI2VCardDocumentFormatFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2VCardDocumentFormatFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2VCardDocumentFormatFieldType~1timeZone\/title","value":"SBSDKUI2VCardDocumentFormatFieldTypeTimeZone"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2VCardDocumentFormatFieldType~1timeZone\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldTypeTimeZone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}