{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorview\/minimumscalefactor(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView\/View-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.minimumScaleFactor(_:)"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"minimumScaleFactor","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"factor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"},{"text":"\n","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView\/minimumScaleFactor(_:)"},"metadata":{"externalID":"s:7SwiftUI4ViewPAAE18minimumScaleFactoryQr14CoreFoundation7CGFloatVF::SYNTHESIZED::s:10ScanbotSDK33SBSDKUI2DocumentDataExtractorViewV","title":"minimumScaleFactor(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumScaleFactor"},{"kind":"text","text":"("},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"extendedModule":"SwiftUICore","roleHeading":"Instance Method","symbolKind":"method","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}],"role":"symbol","platforms":[{"deprecated":false,"beta":false,"name":"iOS","unavailable":false,"introducedAt":"13.0"},{"unavailable":false,"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"13.0"},{"introducedAt":"13.0","deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst"},{"introducedAt":"10.15","deprecated":false,"unavailable":false,"beta":false,"name":"macOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"13.0","name":"tvOS"},{"deprecated":false,"name":"watchOS","introducedAt":"6.0","unavailable":false,"beta":false}]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorView":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorview","abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorViewController"},{"type":"text","text":"."}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorView","kind":"identifier"}],"title":"SBSDKUI2DocumentDataExtractorView","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView","role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorView","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorView/minimumScaleFactor(_:)":{"type":"topic","title":"minimumScaleFactor(_:)","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorview\/minimumscalefactor(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView\/minimumScaleFactor(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"minimumScaleFactor","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorView/View-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorview\/view-implementations","title":"View Implementations","type":"topic","kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView\/View-Implementations","role":"collectionGroup","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorviewcontroller","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to extract data from various documents.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorViewController","kind":"identifier"}],"title":"SBSDKUI2DocumentDataExtractorViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorViewController","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorViewController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2DocumentDataExtractorViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}