{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController\/documentScannerViewControllerDidFailSnappingImage:withError:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"documentScannerViewControllerDidFailSnappingImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"withError:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Instance Method","role":"symbol","title":"documentScannerViewControllerDidFailSnappingImage:withError:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"documentScannerViewControllerDidFailSnappingImage:withError:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"documentScannerViewControllerDidFailSnappingImage:withError:","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerViewController(im)documentScannerViewControllerDidFailSnappingImage:withError:","symbolKind":"method"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerviewcontroller\/documentscannerviewcontrollerdidfailsnappingimage:witherror:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerViewController":{"abstract":[{"text":"A highly customizable camera-based view controller to scan a single documents of a certain aspect ratio.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}],"title":"SBSDKUIFinderDocumentScannerViewController","navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController","deprecated":true,"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerviewcontroller","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerViewController/documentScannerViewControllerDidFailSnappingImage:withError:":{"abstract":[],"title":"documentScannerViewControllerDidFailSnappingImage:withError:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerviewcontroller\/documentscannerviewcontrollerdidfailsnappingimage:witherror:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController\/documentScannerViewControllerDidFailSnappingImage:withError:","kind":"symbol","navigatorTitle":[{"text":"documentScannerViewControllerDidFailSnappingImage:withError:","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"documentScannerViewControllerDidFailSnappingImage:withError:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController":{"abstract":[{"type":"text","text":"A UIViewController subclass to show a camera screen and run a user guiding document scanner."}],"kind":"symbol","title":"SBSDKDocumentScannerViewController","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUIFinderDocumentScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}]},{"value":[{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerViewController\/navigatorTitle"},{"value":"SBSDKDocumentScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"op":"replace"}]}]}