{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/provideKeyForContext(_:keyLength:)"},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"provideKeyForContext:keyLength:error:"}],"symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKVolatileKeyProvider(im)provideKeyForContext:keyLength:error:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"provideKeyForContext(_:keyLength:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"provideKeyForContext"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"keyLength","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKStorageCryptingKeyLength","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider"]]},"abstract":[{"type":"text","text":"Loads or generates the encryption\/decryption key for the given context."}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkvolatilekeyprovider\/providekeyforcontext(_:keylength:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkvolatilekeyprovider\/providekeyforcontext(_:keylength:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"provideKeyForContext","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"keyLength"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKStorageCryptingKeyLength","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The context to generate or load the key for. For most applications in Scanbot SDK the context is derived from the URL of the file to encrypted or decrypted by calling the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Foundation\/URL\/sbsdk_encryptionContext"},{"text":" property on the URL.","type":"text"}]}],"name":"context"},{"content":[{"inlineContent":[{"type":"text","text":"The length of the key to be provided."}],"type":"paragraph"}],"name":"keyLength"}]},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The encryption\/decryption key for the given context."}]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Foundation/URL/sbsdk_encryptionContext":{"title":"sbsdk_encryptionContext","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Foundation\/URL\/sbsdk_encryptionContext","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"sbsdk_encryptionContext","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The encryption context of the URL."}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/foundation\/url\/sbsdk_encryptioncontext"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVolatileKeyProvider":{"title":"SBSDKVolatileKeyProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}],"type":"topic","abstract":[{"type":"text","text":"A volatile key provider that generates and stores keys in memory."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvolatilekeyprovider","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVolatileKeyProvider/provideKeyForContext(_:keyLength:)":{"abstract":[{"text":"Loads or generates the encryption\/decryption key for the given context.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"provideKeyForContext"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keyLength"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvolatilekeyprovider\/providekeyforcontext(_:keylength:)","navigatorTitle":[{"text":"provideKeyForContext:keyLength:error:","kind":"identifier"}],"type":"topic","title":"provideKeyForContext(_:keyLength:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/provideKeyForContext(_:keyLength:)","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyLength":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeylength","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"title":"SBSDKStorageCryptingKeyLength","abstract":[{"type":"text","text":"The length of the encryption key."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"provideKeyForContext:keyLength:error:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"provideKeyForContext:keyLength:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"provideKeyForContext:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"context","kind":"internalParam"},{"kind":"text","text":" "},{"text":"keyLength:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKStorageCryptingKeyLength","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength","kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyLength"},{"kind":"text","text":") "},{"kind":"internalParam","text":"keyLength"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The context to generate or load the key for. For most applications in Scanbot SDK the context is derived from the URL of the file to encrypted or decrypted by calling the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Foundation\/URL\/sbsdk_encryptionContext","type":"reference"},{"text":" property on the URL.","type":"text"}],"type":"paragraph"}],"name":"context"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The length of the key to be provided."}]}],"name":"keyLength"},{"content":[{"type":"paragraph","inlineContent":[{"text":"On output, a pointer to an error object that describes why the method failed, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no error occurred. If you are not interested in the error information, pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" for this parameter.","type":"text"}]}],"name":"error"}]}},{"op":"replace","value":{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The encryption\/decryption key for the given context."},{"text":" On failure, this method returns ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]},"path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider\/title","op":"replace","value":"SBSDKVolatileKeyProvider"},{"value":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider\/navigatorTitle","value":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider~1provideKeyForContext(_:keyLength:)\/title","value":"provideKeyForContext:keyLength:error:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider~1provideKeyForContext(_:keyLength:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"provideKeyForContext:keyLength:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyLength\/title","value":"SBSDKStorageCryptingKeyLength"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyLength\/fragments","value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyLength\/navigatorTitle","op":"replace","value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}