{"sections":[],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2UserGuidanceVisibility@SBSDKUI2UserGuidanceVisibilityAutoCaptureOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCaptureOnly"}],"navigatorTitle":[{"text":"SBSDKUI2UserGuidanceVisibilityAutoCaptureOnly","kind":"identifier"}],"symbolKind":"case","title":"SBSDKUI2UserGuidanceVisibility.autoCaptureOnly","role":"symbol","roleHeading":"Case"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidancevisibility\/autocaptureonly"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidancevisibility\/autocaptureonly"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceVisibility\/autoCaptureOnly"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCaptureOnly","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceVisibility"]]},"abstract":[{"text":"Enabled only for the ‘auto snapping’ mode.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2UserGuidanceVisibility/autoCaptureOnly":{"abstract":[{"type":"text","text":"Enabled only for the ‘auto snapping’ mode."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceVisibility\/autoCaptureOnly","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidancevisibility\/autocaptureonly","title":"SBSDKUI2UserGuidanceVisibility.autoCaptureOnly","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibilityAutoCaptureOnly"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCaptureOnly"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2UserGuidanceVisibility":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidancevisibility","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceVisibility","kind":"symbol","abstract":[{"text":"Determines the visibility mode for the document capturing user guidance labels.","type":"text"}],"title":"SBSDKUI2UserGuidanceVisibility","navigatorTitle":[{"text":"SBSDKUI2UserGuidanceVisibility","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2UserGuidanceVisibility","kind":"identifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2UserGuidanceVisibilityAutoCaptureOnly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2UserGuidanceVisibilityAutoCaptureOnly","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibilityAutoCaptureOnly"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceVisibility~1autoCaptureOnly\/title","value":"SBSDKUI2UserGuidanceVisibilityAutoCaptureOnly"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceVisibility~1autoCaptureOnly\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibilityAutoCaptureOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceVisibility\/title","value":"SBSDKUI2UserGuidanceVisibility"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceVisibility\/fragments","value":[{"text":"SBSDKUI2UserGuidanceVisibility","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceVisibility\/navigatorTitle","value":[{"text":"SBSDKUI2UserGuidanceVisibility","kind":"identifier"}]}]}]}