{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardNoImage\/copyWithZone:","interfaceLanguage":"occ"},"sections":[],"metadata":{"title":"copyWithZone:","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardNoImage(im)copyWithZone:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardNoImage"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"copyWithZone:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@_NSZone","text":"_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardnoimage\/copywithzone:"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardNoImage":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardnoimage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardNoImage"}],"type":"topic","title":"SBSDKUI2CreditCardNoImage","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardNoImage","abstract":[{"text":"No image for the introduction screen.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardNoImage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardNoImage/copyWithZone:":{"title":"copyWithZone:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardNoImage\/copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardnoimage\/copywithzone:","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2CreditCardNoImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardNoImage\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardNoImage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardNoImage\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2CreditCardNoImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardNoImage\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}