{"metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ok"}],"roleHeading":"Case","title":"SBSDKDocumentDetectionStatus.ok","externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectionStatus@SBSDKDocumentDetectionStatusOk","symbolKind":"case","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatusOk","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus"]]},"abstract":[{"text":"An acceptable document was detected.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ok"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/ok"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/ok"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus":{"type":"topic","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"title":"SBSDKDocumentDetectionStatus","kind":"symbol","abstract":[{"type":"text","text":"Status of the document detection."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/ok":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/ok","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk"}],"type":"topic","abstract":[{"text":"An acceptable document was detected.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ok","kind":"identifier"}],"title":"SBSDKDocumentDetectionStatus.ok","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKDocumentDetectionStatusOk"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/title","op":"replace","value":"SBSDKDocumentDetectionStatus"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/navigatorTitle","value":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1ok\/title","value":"SBSDKDocumentDetectionStatusOk"},{"value":[{"text":"SBSDKDocumentDetectionStatusOk","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1ok\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}