{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode2of5configuration\/useiata2of5checksum"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode2of5configuration\/useiata2of5checksum"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCode2Of5Configuration(py)useIATA2OF5Checksum","title":"useIATA2OF5Checksum","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useIATA2OF5Checksum"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"useIATA2OF5Checksum","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useIATA2OF5Checksum","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Default is true"}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode2Of5Configuration"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode2Of5Configuration\/useIATA2OF5Checksum","interfaceLanguage":"swift"},"abstract":[{"text":"If true, return IATA_2_OF_5 barcodes only if they have a valid check digit.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode2Of5Configuration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode2Of5Configuration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode2Of5Configuration"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatCode2Of5Configuration"}],"title":"SBSDKBarcodeFormatCode2Of5Configuration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode2of5configuration","role":"symbol","abstract":[{"text":"Configuration for all 2-of-5 barcode types (except Interleaved 2-of-5, which is handled by ItfConfig).","type":"text"},{"text":" ","type":"text"},{"text":"Add to scanner configuration to scan Code 25, IATA 2-of-5 and Industrial 2-of-5 barcodes.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode2Of5Configuration/useIATA2OF5Checksum":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode2Of5Configuration\/useIATA2OF5Checksum","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useIATA2OF5Checksum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode2of5configuration\/useiata2of5checksum","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"If true, return IATA_2_OF_5 barcodes only if they have a valid check digit."}],"navigatorTitle":[{"kind":"identifier","text":"useIATA2OF5Checksum"}],"title":"useIATA2OF5Checksum"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"useIATA2OF5Checksum"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"useIATA2OF5Checksum","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"useIATA2OF5Checksum","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKBarcodeFormatCode2Of5Configuration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode2Of5Configuration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode2Of5Configuration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode2Of5Configuration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode2Of5Configuration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode2Of5Configuration\/navigatorTitle","op":"replace"},{"value":"useIATA2OF5Checksum","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode2Of5Configuration~1useIATA2OF5Checksum\/title","op":"replace"},{"value":[{"text":"useIATA2OF5Checksum","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode2Of5Configuration~1useIATA2OF5Checksum\/fragments","op":"replace"}]}]}