{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController"]]},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerViewController(im)documentScannerViewControllerWillSnapImage:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","title":"documentScannerViewControllerWillSnapImage:","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentScannerViewControllerWillSnapImage:"}],"navigatorTitle":[{"text":"documentScannerViewControllerWillSnapImage:","kind":"identifier"}],"symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"documentScannerViewControllerWillSnapImage:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerviewcontroller\/documentscannerviewcontrollerwillsnapimage:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController\/documentScannerViewControllerWillSnapImage:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerViewController":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"type":"topic","title":"SBSDKUIFinderDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"abstract":[{"text":"A highly customizable camera-based view controller to scan a single documents of a certain aspect ratio.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"title":"SBSDKDocumentScannerViewController","type":"topic","abstract":[{"text":"A UIViewController subclass to show a camera screen and run a user guiding document detector.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerViewController/documentScannerViewControllerWillSnapImage:":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentScannerViewControllerWillSnapImage:"}],"title":"documentScannerViewControllerWillSnapImage:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController\/documentScannerViewControllerWillSnapImage:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerviewcontroller\/documentscannerviewcontrollerwillsnapimage:","fragments":[{"text":"- ","kind":"text"},{"text":"documentScannerViewControllerWillSnapImage:","kind":"identifier"}],"abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 5.2.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerViewController\/title","value":"SBSDKUIFinderDocumentScannerViewController","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerViewController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/title","value":"SBSDKDocumentScannerViewController"},{"value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/fragments"}]}]}