{"metadata":{"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerViewController(im)willShowEnableCameraView","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"willShowEnableCameraView"}],"roleHeading":"Instance Method","title":"willShowEnableCameraView","fragments":[{"kind":"text","text":"- "},{"text":"willShowEnableCameraView","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"willShowEnableCameraView","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerviewcontroller\/willshowenablecameraview"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController\/willShowEnableCameraView","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerViewController":{"deprecated":true,"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController","title":"SBSDKUIFinderDocumentScannerViewController","kind":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan a single documents of a certain aspect ratio."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerviewcontroller","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerViewController/willShowEnableCameraView":{"navigatorTitle":[{"text":"willShowEnableCameraView","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController\/willShowEnableCameraView","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerviewcontroller\/willshowenablecameraview","title":"willShowEnableCameraView","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willShowEnableCameraView"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerViewController\/title","value":"SBSDKUIFinderDocumentScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerViewController\/fragments","value":[{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}