{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontroller\/polygonstyle"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontroller\/polygonstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController\/polygonStyle","interfaceLanguage":"swift"},"abstract":[{"text":"The default style for the polygon around the barcodes.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"polygonStyle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKScanAndCountPolygonStyle","text":"SBSDKScanAndCountPolygonStyle","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScanAndCountPolygonStyle"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"Defaults to blueish-green style."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"polygonStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKScanAndCountPolygonStyle","text":"SBSDKScanAndCountPolygonStyle"}],"role":"symbol","symbolKind":"property","title":"polygonStyle","navigatorTitle":[{"kind":"identifier","text":"polygonStyle"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanAndCountViewController(py)polygonStyle"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewController/polygonStyle":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"polygonStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKScanAndCountPolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKScanAndCountPolygonStyle"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController\/polygonStyle","title":"polygonStyle","type":"topic","navigatorTitle":[{"text":"polygonStyle","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontroller\/polygonstyle","abstract":[{"text":"The default style for the polygon around the barcodes.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewController":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}],"title":"SBSDKBarcodeScanAndCountViewController","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show a camera screen with the barcode scanner.","type":"text"},{"text":" ","type":"text"},{"text":"Screen also shows snap, scan more and reset buttons.","type":"text"},{"text":" ","type":"text"},{"text":"The snap button starts the scanning when tapped.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The snap button resets the scanning when tapped again."},{"text":" ","type":"text"},{"text":"Instead it is installing itself as a child view controller onto a given parent view controller.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKScanAndCountPolygonStyle":{"kind":"symbol","title":"SBSDKScanAndCountPolygonStyle","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkscanandcountpolygonstyle","role":"symbol","navigatorTitle":[{"text":"SBSDKScanAndCountPolygonStyle","kind":"identifier"}],"abstract":[{"type":"text","text":"A class that represents the style of the polygon rendered around a barcode in "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController","type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScanAndCountPolygonStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScanAndCountPolygonStyle"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"polygonStyle","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"polygonStyle"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKScanAndCountPolygonStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKScanAndCountPolygonStyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScanAndCountPolygonStyle","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"polygonStyle"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController~1polygonStyle\/title","value":"polygonStyle"},{"op":"replace","value":[{"text":"polygonStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController~1polygonStyle\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/title","value":"SBSDKBarcodeScanAndCountViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScanAndCountPolygonStyle\/title","value":"SBSDKScanAndCountPolygonStyle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScanAndCountPolygonStyle\/fragments","op":"replace","value":[{"text":"SBSDKScanAndCountPolygonStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScanAndCountPolygonStyle\/navigatorTitle","value":[{"text":"SBSDKScanAndCountPolygonStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}