{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The string being displayed on the cancel button."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscannertextconfiguration\/cancelbuttontitle"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscannertextconfiguration\/cancelbuttontitle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerTextConfiguration\/cancelButtonTitle"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cancelButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"cancelButtonTitle","symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cancelButtonTitle"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelButtonTitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerTextConfiguration(py)cancelButtonTitle","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerTextConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerTextConfiguration/cancelButtonTitle":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerTextConfiguration\/cancelButtonTitle","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannertextconfiguration\/cancelbuttontitle","kind":"symbol","abstract":[{"text":"The string being displayed on the cancel button.","type":"text"}],"title":"cancelButtonTitle","navigatorTitle":[{"text":"cancelButtonTitle","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cancelButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerTextConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIVINScannerTextConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIVINScannerTextConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"The configuration for the textual contents of the RTU-UI vehicle identification number scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdkuivinscannertextconfiguration","kind":"symbol","title":"SBSDKUIVINScannerTextConfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerTextConfiguration","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"cancelButtonTitle","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"cancelButtonTitle","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"cancelButtonTitle"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerTextConfiguration~1cancelButtonTitle\/title","value":"cancelButtonTitle","op":"replace"},{"value":[{"kind":"identifier","text":"cancelButtonTitle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerTextConfiguration~1cancelButtonTitle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerTextConfiguration\/title","value":"SBSDKUIVINScannerTextConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKUIVINScannerTextConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerTextConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerTextConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIVINScannerTextConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}