{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flatDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"includeEmptyChildren","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"includeEmptyFields","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument"},{"text":"]?","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If set to "},{"code":"True","type":"codeVoice"},{"type":"text","text":", child documents without fields are included, otherwise "},{"code":"False","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"includeEmptyChildren"},{"name":"includeEmptyFields","content":[{"type":"paragraph","inlineContent":[{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":", fields with no values are included, otherwise "},{"type":"codeVoice","code":"False"},{"type":"text","text":"."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"text":"An array of the child documents with the main document in the first position.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Can be used for displaying the documents fields in a table view."}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument\/flatDocument(includeEmptyChildren:includeEmptyFields:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Generates a flat array of the document and its child documents recursively."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocument\/flatdocument(includeemptychildren:includeemptyfields:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocument\/flatdocument(includeemptychildren:includeemptyfields:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"title":"flatDocument(includeEmptyChildren:includeEmptyFields:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"flatDocument","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"includeEmptyChildren"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"includeEmptyFields","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","text":"SBSDKGenericDocument"},{"kind":"text","text":"]?"}],"externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKGenericDocument(im)flatDocumentWithIncludeEmptyChildren:includeEmptyFields:","symbolKind":"method","extendedModule":"ScanbotSDK","navigatorTitle":[{"text":"flatDocumentWithIncludeEmptyChildren:includeEmptyFields:","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","abstract":[{"type":"text","text":"Represents a generic document with fields and sub-documents used for document recognition."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocument"}],"role":"symbol","title":"SBSDKGenericDocument","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument/flatDocument(includeEmptyChildren:includeEmptyFields:)":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument\/flatdocument(includeemptychildren:includeemptyfields:)","title":"flatDocument(includeEmptyChildren:includeEmptyFields:)","abstract":[{"type":"text","text":"Generates a flat array of the document and its child documents recursively."}],"kind":"symbol","navigatorTitle":[{"text":"flatDocumentWithIncludeEmptyChildren:includeEmptyFields:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"flatDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"includeEmptyChildren"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"includeEmptyFields","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> [","kind":"text"},{"text":"SBSDKGenericDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument"},{"kind":"text","text":"]?"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument\/flatDocument(includeEmptyChildren:includeEmptyFields:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"flatDocumentWithIncludeEmptyChildren:includeEmptyFields:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"flatDocumentWithIncludeEmptyChildren:includeEmptyFields:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKGenericDocument *>"},{"kind":"text","text":" *) "},{"text":"flatDocumentWithIncludeEmptyChildren:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"includeEmptyChildren","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeEmptyFields:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"includeEmptyFields"},{"kind":"text","text":";"}]}]}},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":", child documents without fields are included, otherwise "},{"type":"codeVoice","code":"False"},{"type":"text","text":"."}]}],"name":"includeEmptyChildren"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If set to "},{"code":"True","type":"codeVoice"},{"type":"text","text":", fields with no values are included, otherwise "},{"type":"codeVoice","code":"False"},{"type":"text","text":"."}]}],"name":"includeEmptyFields"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","value":{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of the child documents with the main document in the first position."}]}],"kind":"content"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument"},{"value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","op":"replace","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument~1flatDocument(includeEmptyChildren:includeEmptyFields:)\/title","op":"replace","value":"flatDocumentWithIncludeEmptyChildren:includeEmptyFields:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument~1flatDocument(includeEmptyChildren:includeEmptyFields:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"flatDocumentWithIncludeEmptyChildren:includeEmptyFields:"}]}]}]}