{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2twolinemrzfinderlayoutpreset\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TwoLineMRZFinderLayoutPreset"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset\/fromJsonWithJson:"},"metadata":{"symbolKind":"method","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TwoLineMRZFinderLayoutPreset(cm)fromJsonWithJson:","modules":[{"name":"ScanbotSDK"}],"title":"fromJsonWithJson:","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"role":"symbol"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TwoLineMRZFinderLayoutPreset":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset","title":"SBSDKUI2TwoLineMRZFinderLayoutPreset","abstract":[{"type":"text","text":"A ready-to-use preset 2-line text to be displayed."}],"navigatorTitle":[{"text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2twolinemrzfinderlayoutpreset","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TwoLineMRZFinderLayoutPreset/fromJsonWithJson:":{"role":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2twolinemrzfinderlayoutpreset\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset\/fromJsonWithJson:","type":"topic","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TwoLineMRZFinderLayoutPreset\/title","op":"replace","value":"SBSDKUI2TwoLineMRZFinderLayoutPreset"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TwoLineMRZFinderLayoutPreset\/fragments","op":"replace","value":[{"text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TwoLineMRZFinderLayoutPreset\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"identifier"}]}]}]}