{"metadata":{"title":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageProfile(im)initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:"}],"navigatorTitle":[{"text":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProfile"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageprofile\/initwithbitmapmemoryconsumption:hibernationmemoryconsumption:"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProfile\/initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithBitmapMemoryConsumption:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"bitmapMemoryConsumption","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"hibernationMemoryConsumption:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"hibernationMemoryConsumption","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageProfile/initWithBitmapMemoryConsumption:hibernationMemoryConsumption:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProfile\/initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","type":"topic","title":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageprofile\/initwithbitmapmemoryconsumption:hibernationmemoryconsumption:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageProfile":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageProfile","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageProfile","kind":"identifier"}],"abstract":[{"type":"text","text":"ImageRef profile part specific to image information."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageprofile","kind":"symbol","title":"SBSDKImageProfile","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProfile","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProfile\/title","value":"SBSDKImageProfile","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProfile\/fragments","value":[{"kind":"identifier","text":"SBSDKImageProfile"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProfile\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageProfile"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}