{"abstract":[{"text":"Designated initializer.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/init(pagesize:pagefitmode:pageorientation:dpi:resample:jpegquality:ocrconfiguration:pdfattributes:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/init(pagesize:pagefitmode:pageorientation:dpi:resample:jpegquality:ocrconfiguration:pdfattributes:)"]}],"kind":"symbol","metadata":{"title":"init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions(im)initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Initializer","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPDFRendererPageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize"},{"text":", ","kind":"text"},{"text":"pageFitMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPDFRendererPageFitMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode"},{"text":", ","kind":"text"},{"text":"pageOrientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPDFRendererPageOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageOrientation"},{"text":", ","kind":"text"},{"text":"dpi","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"resample","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"jpegQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"ocrConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKOpticalCharacterRecognizerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration"},{"text":"?, ","kind":"text"},{"text":"pdfAttributes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPDFAttributes","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFAttributes"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"pageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPDFRendererPageSize","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize"},{"text":", ","kind":"text"},{"text":"pageFitMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPDFRendererPageFitMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageOrientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageOrientation","text":"SBSDKPDFRendererPageOrientation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageOrientation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dpi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resample"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"jpegQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ocrConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration","text":"SBSDKOpticalCharacterRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"pdfAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes","text":"SBSDKPDFAttributes","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFAttributes"},{"kind":"text","text":"?)"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The page size for each PDF page."}]}],"name":"pageSize"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The page fitting mode for each PDF page."}]}],"name":"pageFitMode"},{"content":[{"inlineContent":[{"type":"text","text":"The page orientation for each PDF page."}],"type":"paragraph"}],"name":"pageOrientation"},{"content":[{"inlineContent":[{"type":"text","text":"The desired resolution (dpi) for each PDF page."}],"type":"paragraph"}],"name":"dpi"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" the input images are resampled before being rendered to a PDF page."}]}],"name":"resample"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The jpeg compression quality (0-100) of each image before being rendered to a PDF page.","type":"text"}]}],"name":"jpegQuality"},{"content":[{"inlineContent":[{"type":"text","text":"The configuration of the OCR engine for the HOCR processing. Set to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if you do not want to perform HOCR."}],"type":"paragraph"}],"name":"ocrConfiguration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The metadata attributes for the generated PDF."}]}],"name":"pdfAttributes"}],"kind":"parameters"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode":{"role":"symbol","navigatorTitle":[{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}],"title":"SBSDKPDFRendererPageFitMode","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode","abstract":[{"text":"An enum describing the mode of how images are fitted into a PDF page.","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageOrientation":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFRendererPageOrientation"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageOrientation"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageOrientation","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpageorientation","type":"topic","abstract":[{"type":"text","text":"An enum describing the orientation of the pages when rendering a PDF document."}],"role":"symbol","title":"SBSDKPDFRendererPageOrientation","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration","type":"topic","role":"symbol","title":"SBSDKOpticalCharacterRecognizerConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"abstract":[{"type":"text","text":"A class describing the configuration of the optical character recognizer (OCR)."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions":{"title":"SBSDKPDFRendererOptions","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRendererOptions","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPDFRendererOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"A class to describe the options being passed to PDF rendering API."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageSize"}],"title":"SBSDKPDFRendererPageSize","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize","type":"topic","kind":"symbol","abstract":[{"text":"Specifies the desired page size (media box size) for PDF rendering operations.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFRendererPageSize"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:)":{"navigatorTitle":[{"text":"initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:","kind":"identifier"}],"title":"init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:)","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/init(pagesize:pagefitmode:pageorientation:dpi:resample:jpegquality:ocrconfiguration:pdfattributes:)","role":"symbol","abstract":[{"type":"text","text":"Designated initializer."}],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPDFRendererPageSize","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pageFitMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode","kind":"typeIdentifier","text":"SBSDKPDFRendererPageFitMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageOrientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageOrientation","kind":"typeIdentifier","text":"SBSDKPDFRendererPageOrientation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dpi"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"text":", ","kind":"text"},{"text":"resample","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"jpegQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ocrConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKOpticalCharacterRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"pdfAttributes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPDFAttributes","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFAttributes"},{"text":"?)","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes":{"role":"symbol","abstract":[{"type":"text","text":"Represents the metadata attributes of PDF files, e.g. author, creator, title etc."}],"navigatorTitle":[{"text":"SBSDKPDFAttributes","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFAttributes","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes","type":"topic","title":"SBSDKPDFAttributes","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithPageSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRendererPageSize","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"pageSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pageFitMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRendererPageFitMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"pageFitMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pageOrientation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRendererPageOrientation","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageOrientation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageOrientation","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"pageOrientation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dpi:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"dpi","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"resample:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"resample","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"jpegQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"jpegQuality","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ocrConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKOpticalCharacterRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"ocrConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pdfAttributes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKPDFAttributes","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFAttributes","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"pdfAttributes","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"pageSize","content":[{"inlineContent":[{"text":"The page size for each PDF page.","type":"text"}],"type":"paragraph"}]},{"name":"pageFitMode","content":[{"inlineContent":[{"type":"text","text":"The page fitting mode for each PDF page."}],"type":"paragraph"}]},{"name":"pageOrientation","content":[{"inlineContent":[{"text":"The page orientation for each PDF page.","type":"text"}],"type":"paragraph"}]},{"name":"dpi","content":[{"type":"paragraph","inlineContent":[{"text":"The desired resolution (dpi) for each PDF page.","type":"text"}]}]},{"name":"resample","content":[{"inlineContent":[{"text":"If set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" the input images are resampled before being rendered to a PDF page.","type":"text"}],"type":"paragraph"}]},{"name":"jpegQuality","content":[{"inlineContent":[{"type":"text","text":"The jpeg compression quality (0-100) of each image before being rendered to a PDF page."}],"type":"paragraph"}]},{"name":"ocrConfiguration","content":[{"inlineContent":[{"type":"text","text":"The configuration of the OCR engine for the HOCR processing. Set to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if you do not want to perform HOCR."}],"type":"paragraph"}]},{"name":"pdfAttributes","content":[{"inlineContent":[{"type":"text","text":"The metadata attributes for the generated PDF."}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode\/title","op":"replace","value":"SBSDKPDFRendererPageFitMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode\/fragments","op":"replace","value":[{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageOrientation\/title","op":"replace","value":"SBSDKPDFRendererPageOrientation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageOrientation\/fragments","op":"replace","value":[{"text":"SBSDKPDFRendererPageOrientation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageOrientation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageOrientation"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration\/title","op":"replace","value":"SBSDKOpticalCharacterRecognizerConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKOpticalCharacterRecognizerConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/title","op":"replace","value":"SBSDKPDFRendererOptions"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/fragments","op":"replace","value":[{"text":"SBSDKPDFRendererOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFRendererOptions"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/title","op":"replace","value":"SBSDKPDFRendererPageSize"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/fragments","op":"replace","value":[{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageSize"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:)\/title","op":"replace","value":"initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/title","op":"replace","value":"SBSDKPDFAttributes"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFAttributes"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFAttributes"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}