{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfimageextractor\/scanneddocument(from:scale:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfimageextractor\/scanneddocument(from:scale:completion:)"]}],"abstract":[{"text":"Asynchronously extracts pages from PDF and returns them as ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","type":"reference"},{"text":" in the completion handler.","type":"text"},{"text":" ","type":"text"},{"text":"Each page of the PDF will be a separate ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage","type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Runs in the same thread, as it is called from.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFImageExtractor\/scannedDocument(from:scale:completion:)"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(scannedDocumentFromPDF:scale:completion:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scannedDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pdfURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":" = 1.0, "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","kind":"typeIdentifier","text":"SBSDKScannedDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> ()) -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","kind":"typeIdentifier","text":"SBSDKProgress","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress"},{"kind":"text","text":"?"}]}],"kind":"declarations"},{"parameters":[{"name":"pdfURL","content":[{"inlineContent":[{"type":"text","text":"The URL of the PDF file."}],"type":"paragraph"}]},{"name":"scale","content":[{"inlineContent":[{"text":"The scale factor for the images. Default is ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"text":"The completion handler that delivers the created ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"A progress object that can be used for cancellation and progress observing. If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", an error occurred.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFImageExtractor"]]},"kind":"symbol","metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"scannedDocumentFromPDF:scale:completion:"}],"externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKPDFImageExtractor(im)scannedDocumentFromPDF:scale:completion:","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scannedDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","kind":"typeIdentifier","text":"SBSDKScannedDocument"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> ()) -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","kind":"typeIdentifier","text":"SBSDKProgress"},{"kind":"text","text":"?"}],"extendedModule":"ScanbotSDK","roleHeading":"Instance Method","title":"scannedDocument(from:scale:completion:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFImageExtractor":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFImageExtractor","type":"topic","role":"symbol","title":"SBSDKPDFImageExtractor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFImageExtractor","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfimageextractor","navigatorTitle":[{"text":"SBSDKPDFImageExtractor","kind":"identifier"}],"abstract":[{"text":"Class used to extract images from a PDF file and returns them in various ways.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress":{"url":"\/documentation\/scanbotsdk\/sbsdkprogress","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","role":"symbol","title":"SBSDKProgress","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProgress"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKProgress"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFImageExtractor/scannedDocument(from:scale:completion:)":{"title":"scannedDocument(from:scale:completion:)","abstract":[{"type":"text","text":"Asynchronously extracts pages from PDF and returns them as "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument"},{"type":"text","text":" in the completion handler."},{"type":"text","text":" "},{"type":"text","text":"Each page of the PDF will be a separate "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Runs in the same thread, as it is called from."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scannedDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"scale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"SBSDKScannedDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ()) -> ","kind":"text"},{"text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfimageextractor\/scanneddocument(from:scale:completion:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFImageExtractor\/scannedDocument(from:scale:completion:)","navigatorTitle":[{"text":"scannedDocumentFromPDF:scale:completion:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage":{"role":"symbol","title":"SBSDKScannedPage","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannedPage"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPage"}],"abstract":[{"type":"text","text":"A scanned page ("},{"type":"codeVoice","code":"SBSDKScannedPage"},{"type":"text","text":") is a representation of a scanned documents page in digital form."},{"type":"text","text":" "},{"type":"text","text":"Each page consists of an original image of the scan, various editing properties like cropping polygon, rotation and filters, some metadata properties like the document detection status and the document quality analyzer result and a number of processed images in different stages."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument":{"url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannedDocument"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedDocument"}],"kind":"symbol","abstract":[{"type":"text","text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages."}],"type":"topic","title":"SBSDKScannedDocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"scannedDocumentFromPDF:scale:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"scannedDocumentFromPDF:scale:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"scannedDocumentFromPDF:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pdfURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"scale:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"scale"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","text":"SBSDKScannedDocument"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The URL of the PDF file.","type":"text"}]}],"name":"pdfURL"},{"name":"scale","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The scale factor for the images. Default is "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The completion handler that delivers the created "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A progress object that can be used for cancellation and progress observing. If "},{"code":"nil","type":"codeVoice"},{"type":"text","text":", an error occurred."}]}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"SBSDKPDFImageExtractor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFImageExtractor\/title"},{"value":[{"kind":"identifier","text":"SBSDKPDFImageExtractor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFImageExtractor\/fragments"},{"value":[{"text":"SBSDKPDFImageExtractor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFImageExtractor\/navigatorTitle"},{"value":"SBSDKProgress","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/title"},{"value":[{"text":"SBSDKProgress","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKProgress"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/navigatorTitle"},{"value":"scannedDocumentFromPDF:scale:completion:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFImageExtractor~1scannedDocument(from:scale:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scannedDocumentFromPDF:scale:completion:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFImageExtractor~1scannedDocument(from:scale:completion:)\/fragments"},{"value":"SBSDKScannedPage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/title"},{"value":[{"text":"SBSDKScannedPage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/fragments"},{"value":[{"text":"SBSDKScannedPage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/navigatorTitle"},{"value":"SBSDKScannedDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/title"},{"value":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKScannedDocument"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/navigatorTitle"}]}]}