{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionCameraTopBarCancelButton","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is “Tap to close scanner screen”"}]}],"kind":"content"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"accessibilityDescriptionCameraTopBarCancelButton","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization(py)accessibilityDescriptionCameraTopBarCancelButton","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionCameraTopBarCancelButton"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"accessibilityDescriptionCameraTopBarCancelButton","roleHeading":"Instance Property","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/accessibilitydescriptioncameratopbarcancelbutton"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/accessibilitydescriptioncameratopbarcancelbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/accessibilityDescriptionCameraTopBarCancelButton","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The accessibility hint for the ‘cancel’ button, located in the top bar of the camera screen."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization","type":"topic","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"abstract":[{"text":"Configuration of all the strings for the standalone cropping screen.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization","kind":"symbol","role":"symbol","title":"SBSDKUI2DocumentScannerTextLocalization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization/accessibilityDescriptionCameraTopBarCancelButton":{"title":"accessibilityDescriptionCameraTopBarCancelButton","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/accessibilitydescriptioncameratopbarcancelbutton","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionCameraTopBarCancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/accessibilityDescriptionCameraTopBarCancelButton","navigatorTitle":[{"kind":"identifier","text":"accessibilityDescriptionCameraTopBarCancelButton"}],"kind":"symbol","abstract":[{"type":"text","text":"The accessibility hint for the ‘cancel’ button, located in the top bar of the camera screen."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"accessibilityDescriptionCameraTopBarCancelButton"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"accessibilityDescriptionCameraTopBarCancelButton","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"accessibilityDescriptionCameraTopBarCancelButton"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/title","value":"SBSDKUI2DocumentScannerTextLocalization","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments","value":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}]},{"op":"replace","value":"accessibilityDescriptionCameraTopBarCancelButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization~1accessibilityDescriptionCameraTopBarCancelButton\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization~1accessibilityDescriptionCameraTopBarCancelButton\/fragments","op":"replace","value":[{"kind":"identifier","text":"accessibilityDescriptionCameraTopBarCancelButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}