{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithCameraTopBarCancelButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraTopBarCancelButtonTitle","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraTopBarTitle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"cameraTopBarTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraTopGuidance:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraTopGuidance"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraUserGuidanceStart:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"cameraUserGuidanceStart","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraUserGuidanceNoDocumentFound:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceNoDocumentFound","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraUserGuidanceBadAspectRatio:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceBadAspectRatio","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraUserGuidanceOrientationMismatch:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraUserGuidanceOrientationMismatch"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceBadAngles:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraUserGuidanceBadAngles"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceTooNoisy:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraUserGuidanceTooNoisy"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraUserGuidanceTextHintOffCenter:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceTextHintOffCenter","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraUserGuidanceTooSmall:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceTooSmall","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraUserGuidanceTooDark:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraUserGuidanceTooDark"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceEnergySaveMode:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceEnergySaveMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceReadyToCapture:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraUserGuidanceReadyToCapture"},{"kind":"text","text":" "},{"text":"cameraUserGuidanceReadyToCaptureManual:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraUserGuidanceReadyToCaptureManual"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraImportButtonTitle:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraImportButtonTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraTorchOnButtonTitle:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraTorchOnButtonTitle","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraTorchOffButtonTitle:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraTorchOffButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraAutoSnapButtonTitle:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraAutoSnapButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraManualSnapButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraManualSnapButtonTitle"},{"text":" ","kind":"text"},{"text":"cameraPreviewButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"cameraPreviewButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraIntroDoneButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"cameraIntroDoneButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraIntroTitle:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraIntroTitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraIntroSubtitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraIntroSubtitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraIntroItem1:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraIntroItem1","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraIntroItem2:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraIntroItem2"},{"text":" ","kind":"text"},{"text":"cameraIntroItem3:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraIntroItem3","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraIntroItem4:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraIntroItem4"},{"text":" ","kind":"text"},{"text":"cameraProgressOverlayTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraProgressOverlayTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraCancelAlertTitle:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraCancelAlertTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraCancelAlertSubtitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraCancelAlertSubtitle"},{"kind":"text","text":" "},{"text":"cameraCancelNoButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraCancelNoButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraCancelYesButtonTitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"cameraCancelYesButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraLimitReachedAlertTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"cameraLimitReachedAlertTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraLimitReachedAlertSubtitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraLimitReachedAlertSubtitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraLimitReachedOkButtonTitle:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraLimitReachedOkButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"acknowledgementScreenBadDocumentHint:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"acknowledgementScreenBadDocumentHint","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"acknowledgementRetakeButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"acknowledgementRetakeButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"acknowledgementAcceptButtonTitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"acknowledgementAcceptButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewScreenTitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reviewScreenTitle"},{"text":" ","kind":"text"},{"text":"reviewTopBarBackButtonTitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"reviewTopBarBackButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewScreenPageCount:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"reviewScreenPageCount","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewScreenAddButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reviewScreenAddButtonTitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewScreenRetakeButtonTitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reviewScreenRetakeButtonTitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewScreenCropButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewScreenCropButtonTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewScreenRotateButtonTitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"reviewScreenRotateButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewScreenDeleteButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewScreenDeleteButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewScreenSubmitButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewScreenSubmitButtonTitle","kind":"internalParam"},{"kind":"text","text":" "},{"text":"reviewScreenDeleteAllButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reviewScreenDeleteAllButtonTitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewScreenReorderPagesButtonTitle:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"reviewScreenReorderPagesButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"zoomOverlayCancelButtonText:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"zoomOverlayCancelButtonText"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewDeletePageAlertTitle:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewDeletePageAlertTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewDeleteAllPagesAlertTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reviewDeleteAllPagesAlertTitle"},{"kind":"text","text":" "},{"text":"reviewDeletePageAlertSubTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reviewDeletePageAlertSubTitle"},{"kind":"text","text":" "},{"text":"reviewDeleteAllPagesAlertSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reviewDeleteAllPagesAlertSubtitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewDeletePageAlertConfirmButtonTitle:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"reviewDeletePageAlertConfirmButtonTitle","kind":"internalParam"},{"kind":"text","text":" "},{"text":"reviewDeleteAllPagesAlertDeleteButtonTitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"reviewDeleteAllPagesAlertDeleteButtonTitle","kind":"internalParam"},{"kind":"text","text":" "},{"text":"reviewDeletePageAlertDeleteRetakeButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"reviewDeletePageAlertDeleteRetakeButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewDeletePageAlertCancelButtonTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reviewDeletePageAlertCancelButtonTitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewDeleteAllPagesAlertCancelButtonTitle:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewDeleteAllPagesAlertCancelButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acknowledgementTitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"acknowledgementTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"reorderPageTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reorderPageTitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reorderPageGuidanceTitle:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reorderPageGuidanceTitle"},{"text":" ","kind":"text"},{"text":"reorderPageText:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"reorderPageText","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"reorderTopBarConfirmButtonTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reorderTopBarConfirmButtonTitle"},{"kind":"text","text":" "},{"text":"reorderTopBarCancelButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reorderTopBarCancelButtonTitle"},{"text":" ","kind":"text"},{"text":"croppingTopBarConfirmButtonTitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"croppingTopBarConfirmButtonTitle"},{"kind":"text","text":" "},{"text":"croppingTopBarCancelButtonTitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"croppingTopBarCancelButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingDetectButtonTitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"croppingDetectButtonTitle"},{"text":" ","kind":"text"},{"text":"croppingRotateButtonTitle:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"croppingRotateButtonTitle"},{"kind":"text","text":" "},{"text":"croppingResetButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"croppingResetButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingScreenTitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"croppingScreenTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraTopBarIntroButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionCameraTopBarIntroButton"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionCameraTopBarCancelButton:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCameraTopBarCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraImportButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionCameraImportButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraTorchOnButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraTorchOnButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraTorchOffButton:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionCameraTorchOffButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraShutterButton:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionCameraShutterButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraAutoSnapButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraAutoSnapButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraManualSnapButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraManualSnapButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionCameraPreviewButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraPreviewButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraIntroDoneButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraIntroDoneButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionAcknowledgementRetakeButton:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionAcknowledgementRetakeButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionAcknowledgementAcceptButton:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionAcknowledgementAcceptButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionCroppingTopBarConfirmButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCroppingTopBarConfirmButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingTopBarCancelButton:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCroppingTopBarCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCroppingDetectButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCroppingDetectButton"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionCroppingRotateButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCroppingRotateButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionCroppingResetButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCroppingResetButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReorderTopBarConfirmButton:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReorderTopBarConfirmButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionReorderTopBarCancelButton:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReorderTopBarCancelButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewNextPageButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewNextPageButton"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionReviewPreviousPageButton:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewPreviousPageButton"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionReviewAddButton:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionReviewAddButton"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionReviewRetakeButton:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionReviewRetakeButton"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionReviewCropButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewCropButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionReviewRotateButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewRotateButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewDeleteButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewDeleteButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionReviewSubmitButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewSubmitButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewMoreButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewMoreButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionReviewDeleteAllButton:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionReviewDeleteAllButton"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionReviewReorderPagesButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionReviewReorderPagesButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionZoomOverlayCancelButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionZoomOverlayCancelButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewZoomButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionReviewZoomButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewTopBarBackButton:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewTopBarBackButton"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionReviewDeletePageAlertConfirmButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionReviewDeletePageAlertConfirmButton"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewDeletePageAlertCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionReviewDeletePageAlertCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionCameraLimitReachedOkButton:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCameraLimitReachedOkButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraCancelYesButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionCameraCancelYesButton"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionCameraCancelNoButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraCancelNoButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionEnableCameraTitle:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionEnableCameraTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermissionEnableCameraExplanation"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPermissionEnableCameraButton:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraPermissionEnableCameraButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionCloseButton:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"cameraPermissionCloseButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionEnableCameraButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/initwithcameratopbarcancelbuttontitle:cameratopbartitle:cameratopguidance:camerauserguidancestart:camerauserguidancenodocumentfound:camerauserguidancebadaspectratio:camerauserguidanceorientationmismatch:camerauserguidancebadangles:camerause-8q6dl"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization(im)initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","symbolKind":"method","roleHeading":"Instance Method","title":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization","type":"topic","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"abstract":[{"text":"Configuration of all the strings for the standalone cropping screen.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization","kind":"symbol","role":"symbol","title":"SBSDKUI2DocumentScannerTextLocalization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization/initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:":{"type":"topic","navigatorTitle":[{"text":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/initwithcameratopbarcancelbuttontitle:cameratopbartitle:cameratopguidance:camerauserguidancestart:camerauserguidancenodocumentfound:camerauserguidancebadaspectratio:camerauserguidanceorientationmismatch:camerauserguidancebadangles:camerause-8q6dl","abstract":[],"title":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/title","op":"replace","value":"SBSDKUI2DocumentScannerTextLocalization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}