{"abstract":[{"type":"text","text":"Configuration of the overlay text inside finder."}],"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"mrzExampleOverlay","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerScreenConfiguration(py)mrzExampleOverlay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzExampleOverlay"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZFinderLayoutPreset","kind":"typeIdentifier","text":"SBSDKUI2MRZFinderLayoutPreset"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"mrzExampleOverlay"}],"role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration\/mrzExampleOverlay"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzExampleOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZFinderLayoutPreset","text":"SBSDKUI2MRZFinderLayoutPreset"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration\/mrzexampleoverlay"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration\/mrzexampleoverlay"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset":{"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MRZFinderLayoutPreset","kind":"identifier"}],"abstract":[{"type":"text","text":"Source of the text for the MRZ finder example overlay."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset","type":"topic","title":"SBSDKUI2MRZFinderLayoutPreset","navigatorTitle":[{"text":"SBSDKUI2MRZFinderLayoutPreset","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerScreenConfiguration/mrzExampleOverlay":{"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration\/mrzexampleoverlay","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration\/mrzExampleOverlay","abstract":[{"text":"Configuration of the overlay text inside finder.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mrzExampleOverlay"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzExampleOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2MRZFinderLayoutPreset","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZFinderLayoutPreset"}],"title":"mrzExampleOverlay"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerScreenConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration","abstract":[{"text":"Configuration of the screen for detecting MRZ (Machine-readable zones) of various documents.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MRZScannerScreenConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MRZScannerScreenConfiguration"}],"title":"SBSDKUI2MRZScannerScreenConfiguration","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mrzExampleOverlay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mrzExampleOverlay"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKUI2MRZFinderLayoutPreset","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZFinderLayoutPreset","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"mrzExampleOverlay","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/title","value":"SBSDKUI2MRZFinderLayoutPreset"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/fragments","value":[{"text":"SBSDKUI2MRZFinderLayoutPreset","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration~1mrzExampleOverlay\/title","value":"mrzExampleOverlay"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration~1mrzExampleOverlay\/fragments","value":[{"kind":"identifier","text":"mrzExampleOverlay"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration\/title","value":"SBSDKUI2MRZScannerScreenConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerScreenConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2MRZScannerScreenConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}