{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The text being displayed on the user-guidance label, when the scanners energy saver is activated."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerStatusTextConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerStatusTextConfiguration\/textHintEnergySavingActive"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"textHintEnergySavingActive","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"]}]}],"sections":[],"metadata":{"title":"textHintEnergySavingActive","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textHintEnergySavingActive"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"textHintEnergySavingActive"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerStatusTextConfiguration(py)textHintEnergySavingActive"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerstatustextconfiguration\/texthintenergysavingactive"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerstatustextconfiguration\/texthintenergysavingactive"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerStatusTextConfiguration":{"abstract":[{"type":"text","text":"Wraps the texts being displayed as the detection status."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerstatustextconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerStatusTextConfiguration","title":"SBSDKDocumentScannerStatusTextConfiguration","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerStatusTextConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentScannerStatusTextConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerStatusTextConfiguration/textHintEnergySavingActive":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textHintEnergySavingActive"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"textHintEnergySavingActive","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerstatustextconfiguration\/texthintenergysavingactive","navigatorTitle":[{"text":"textHintEnergySavingActive","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The text being displayed on the user-guidance label, when the scanners energy saver is activated."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerStatusTextConfiguration\/textHintEnergySavingActive","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"textHintEnergySavingActive"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"textHintEnergySavingActive"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"textHintEnergySavingActive","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration\/title","value":"SBSDKDocumentScannerStatusTextConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentScannerStatusTextConfiguration"}]},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerStatusTextConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration\/navigatorTitle","op":"replace"},{"value":"textHintEnergySavingActive","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration~1textHintEnergySavingActive\/title"},{"op":"replace","value":[{"text":"textHintEnergySavingActive","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration~1textHintEnergySavingActive\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}