{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHKDFKeyGenerator"]]},"metadata":{"title":"generateKey(keyLength:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHKDFKeyGenerator(im)generateKeyWithLength:WithError:","modules":[{"name":"ScanbotSDK"}],"platforms":[{"name":"iOS","introducedAt":"14.0","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","introducedAt":"14.0","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"14.0","beta":false,"deprecated":false,"unavailable":false}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generateKey","kind":"identifier"},{"text":"(","kind":"text"},{"text":"keyLength","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"generateKeyWithLength:WithError:","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"abstract":[{"text":"Generates a new encryption key.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhkdfkeygenerator\/generatekey(keylength:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhkdfkeygenerator\/generatekey(keylength:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHKDFKeyGenerator\/generateKey(keyLength:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateKey"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyLength"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyLength"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"keyLength","content":[{"type":"paragraph","inlineContent":[{"text":"The length of the generated key.","type":"text"}]}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The newly generated encryption key.","type":"text"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHKDFKeyGenerator/generateKey(keyLength:)":{"kind":"symbol","abstract":[{"type":"text","text":"Generates a new encryption key."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHKDFKeyGenerator\/generateKey(keyLength:)","url":"\/documentation\/scanbotsdk\/sbsdkhkdfkeygenerator\/generatekey(keylength:)","role":"symbol","title":"generateKey(keyLength:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"generateKeyWithLength:WithError:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateKey"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHKDFKeyGenerator":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHKDFKeyGenerator","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}],"title":"SBSDKHKDFKeyGenerator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}],"url":"\/documentation\/scanbotsdk\/sbsdkhkdfkeygenerator","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A key generator that uses the HMAC based HKDF algorithm to generate a new encryption key. SHA512 is used as the hash function."},{"type":"text","text":" "},{"type":"text","text":"The key generation consists of two phases: extraction and expansion."},{"type":"text","text":" "},{"type":"text","text":"During the extraction a pseudo random key is generated from the input key material and an optional salt."},{"type":"text","text":" "},{"type":"text","text":"The expansion phase uses the pseudo random key and the info data block to derive the final key."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyLength":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyLength","abstract":[{"type":"text","text":"The length of the encryption key."}],"title":"SBSDKStorageCryptingKeyLength","navigatorTitle":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeylength"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"generateKeyWithLength:WithError:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateKeyWithLength:WithError:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"generateKeyWithLength:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength"},{"kind":"text","text":") "},{"kind":"internalParam","text":"keyLength"},{"kind":"text","text":" "},{"kind":"identifier","text":"WithError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The length of the generated key."}],"type":"paragraph"}],"name":"keyLength"},{"content":[{"type":"paragraph","inlineContent":[{"text":"On output, a pointer to an error object that describes why the method failed, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no error occurred. If you are not interested in the error information, pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" for this parameter.","type":"text"}]}],"name":"error"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"The newly generated encryption key.","type":"text"},{"type":"text","text":" On failure, this method returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]},"path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHKDFKeyGenerator~1generateKey(keyLength:)\/title","value":"generateKeyWithLength:WithError:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHKDFKeyGenerator~1generateKey(keyLength:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"generateKeyWithLength:WithError:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHKDFKeyGenerator\/title","value":"SBSDKHKDFKeyGenerator"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHKDFKeyGenerator\/fragments","value":[{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHKDFKeyGenerator\/navigatorTitle","value":[{"text":"SBSDKHKDFKeyGenerator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength\/title","value":"SBSDKStorageCryptingKeyLength"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength\/fragments","value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength\/navigatorTitle","op":"replace"}]}]}