{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerUIConfiguration\/orientationLockMode","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerUIConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientationLockMode"},{"kind":"text","text":": "},{"text":"SBSDKOrientationLock","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerUIConfiguration(py)orientationLockMode","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"orientationLockMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKOrientationLock","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock","kind":"typeIdentifier"}],"roleHeading":"Instance Property","title":"orientationLockMode","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"orientationLockMode","kind":"identifier"}],"role":"symbol"},"kind":"symbol","abstract":[{"text":"Allowed orientations for automatic interface rotations.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascanneruiconfiguration\/orientationlockmode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascanneruiconfiguration\/orientationlockmode"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOrientationLock":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkorientationlock","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKOrientationLock"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock","abstract":[{"type":"text","text":"This enum describes the available orientation lock modes for the user interface."}],"type":"topic","title":"SBSDKOrientationLock","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKOrientationLock","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerUIConfiguration/orientationLockMode":{"abstract":[{"type":"text","text":"Allowed orientations for automatic interface rotations."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"orientationLockMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKOrientationLock","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock","kind":"typeIdentifier"}],"kind":"symbol","title":"orientationLockMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerUIConfiguration\/orientationLockMode","navigatorTitle":[{"text":"orientationLockMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascanneruiconfiguration\/orientationlockmode","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerUIConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascanneruiconfiguration","abstract":[{"type":"text","text":"Configuration for the user interface of the RTU-UI text data scanner."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextDataScannerUIConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerUIConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUITextDataScannerUIConfiguration"}],"title":"SBSDKUITextDataScannerUIConfiguration","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"orientationLockMode"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"orientationLockMode","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock","text":"SBSDKOrientationLock","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock"},{"kind":"text","text":" "},{"text":"orientationLockMode","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKOrientationLock","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/fragments","value":[{"text":"SBSDKOrientationLock","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerUIConfiguration~1orientationLockMode\/title","value":"orientationLockMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerUIConfiguration~1orientationLockMode\/fragments","value":[{"text":"orientationLockMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerUIConfiguration\/title","op":"replace","value":"SBSDKUITextDataScannerUIConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUITextDataScannerUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerUIConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}