{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroImage"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Method","title":"isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IntroImage(im)isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2introimage\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroImage\/isEqual:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroImage":{"type":"topic","title":"SBSDKUI2IntroImage","abstract":[{"text":"Determines the image for the introduction screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroImage","url":"\/documentation\/scanbotsdk\/sbsdkui2introimage","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IntroImage"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IntroImage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroImage/isEqual:":{"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2introimage\/isequal:","kind":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroImage\/isEqual:","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroImage\/title","op":"replace","value":"SBSDKUI2IntroImage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroImage\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2IntroImage"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroImage\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2IntroImage"}]}]}]}