{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/initWithAccessibilityDescription:text:pageCounter:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textwithbadgebuttonmode\/initwithaccessibilitydescription:text:pagecounter:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithAccessibilityDescription:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescription"},{"kind":"text","text":" "},{"kind":"identifier","text":"text:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"text"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageCounter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2BadgeStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgeStyle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pageCounter"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithAccessibilityDescription:text:pageCounter:"}],"title":"initWithAccessibilityDescription:text:pageCounter:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextWithBadgeButtonMode(im)initWithAccessibilityDescription:text:pageCounter:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAccessibilityDescription:text:pageCounter:"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BadgeStyle":{"title":"SBSDKUI2BadgeStyle","url":"\/documentation\/scanbotsdk\/sbsdkui2badgestyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgeStyle","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2BadgeStyle","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BadgeStyle","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Configuration of the badge."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","title":"SBSDKUI2StyledText","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextWithBadgeButtonMode/initWithAccessibilityDescription:text:pageCounter:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithAccessibilityDescription:text:pageCounter:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/initWithAccessibilityDescription:text:pageCounter:","kind":"symbol","navigatorTitle":[{"text":"initWithAccessibilityDescription:text:pageCounter:","kind":"identifier"}],"abstract":[],"type":"topic","title":"initWithAccessibilityDescription:text:pageCounter:","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2textwithbadgebuttonmode\/initwithaccessibilitydescription:text:pagecounter:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextWithBadgeButtonMode":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode","kind":"symbol","title":"SBSDKUI2TextWithBadgeButtonMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextWithBadgeButtonMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textwithbadgebuttonmode","abstract":[{"type":"text","text":"Configuration of the ‘preview’ button in ‘text with badge button mode’."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextWithBadgeButtonMode"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgeStyle\/title","value":"SBSDKUI2BadgeStyle"},{"value":[{"kind":"identifier","text":"SBSDKUI2BadgeStyle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgeStyle\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2BadgeStyle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgeStyle\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2StyledText","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2TextWithBadgeButtonMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextWithBadgeButtonMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2TextWithBadgeButtonMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextWithBadgeButtonMode\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2TextWithBadgeButtonMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextWithBadgeButtonMode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}