{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode\/initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","interfaceLanguage":"occ"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2singlescanningmode\/initwithconfirmationsheetenabled:barcodeimagevisible:sheetcolor:dividercolor:modaloverlaycolor:barcodetitle:barcodesubtitle:submitbutton:cancelbutton:barcodeinfomapping:aroverlay:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","title":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SingleScanningMode(im)initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfirmationSheetEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"confirmationSheetEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeImageVisible:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"barcodeImageVisible"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheetColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sheetColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"dividerColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dividerColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"modalOverlayColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"modalOverlayColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcodeTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeSubtitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcodeSubtitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"submitButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeInfoMapping:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping","text":"SBSDKUI2BarcodeInfoMapping"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcodeInfoMapping"},{"kind":"text","text":" "},{"kind":"identifier","text":"arOverlay:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration","text":"SBSDKUI2ArOverlayGeneralConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"arOverlay"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SingleScanningMode":{"type":"topic","abstract":[{"type":"text","text":"Configuration of the single barcode scanning mode."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode","url":"\/documentation\/scanbotsdk\/sbsdkui2singlescanningmode","kind":"symbol","title":"SBSDKUI2SingleScanningMode","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SingleScanningMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SingleScanningMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ButtonConfiguration":{"abstract":[{"type":"text","text":"Configuration of the button."}],"title":"SBSDKUI2ButtonConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2color","type":"topic","role":"symbol","kind":"symbol","title":"SBSDKUI2Color","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SingleScanningMode/initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:":{"navigatorTitle":[{"text":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2singlescanningmode\/initwithconfirmationsheetenabled:barcodeimagevisible:sheetcolor:dividercolor:modaloverlaycolor:barcodetitle:barcodesubtitle:submitbutton:cancelbutton:barcodeinfomapping:aroverlay:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode\/initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","title":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeInfoMapping":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeInfoMapping","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeinfomapping","navigatorTitle":[{"text":"SBSDKUI2BarcodeInfoMapping","kind":"identifier"}],"type":"topic","title":"SBSDKUI2BarcodeInfoMapping","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping","role":"symbol","abstract":[{"text":"Configuration of the barcode data mapping.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"title":"SBSDKUI2StyledText","abstract":[{"text":"Configuration of the text field appearance.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayGeneralConfiguration":{"title":"SBSDKUI2ArOverlayGeneralConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration","abstract":[{"type":"text","text":"Configuration of the AR overlay displayed on top of barcodes in the camera preview."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SingleScanningMode\/title","value":"SBSDKUI2SingleScanningMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SingleScanningMode\/fragments","value":[{"text":"SBSDKUI2SingleScanningMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SingleScanningMode\/navigatorTitle","value":[{"text":"SBSDKUI2SingleScanningMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/title","value":"SBSDKUI2ButtonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/fragments","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","value":[{"text":"SBSDKUI2Color","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Color"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/title","value":"SBSDKUI2BarcodeInfoMapping"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","op":"replace","value":"SBSDKUI2StyledText"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/title","op":"replace","value":"SBSDKUI2ArOverlayGeneralConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}]}]}]}