{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldDoubleValue"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldDoubleValue\/hash"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuserfielddoublevalue\/hash"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUserFieldDoubleValue(py)hash","fragments":[{"text":"hash","kind":"identifier"}],"symbolKind":"property","title":"hash","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUserFieldDoubleValue/hash":{"title":"hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldDoubleValue\/hash","abstract":[],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuserfielddoublevalue\/hash","fragments":[{"text":"hash","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUserFieldDoubleValue":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUserFieldDoubleValue","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUserFieldDoubleValue","kind":"identifier"}],"title":"SBSDKUserFieldDoubleValue","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldDoubleValue","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Double value (TIFF_DOUBLE)."}],"url":"\/documentation\/scanbotsdk\/sbsdkuserfielddoublevalue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldDoubleValue\/title","value":"SBSDKUserFieldDoubleValue","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldDoubleValue\/fragments","value":[{"text":"SBSDKUserFieldDoubleValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldDoubleValue\/navigatorTitle","value":[{"text":"SBSDKUserFieldDoubleValue","kind":"identifier"}],"op":"replace"}]}]}