{"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MrzIntroNoImage(im)init","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","role":"symbol"},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroNoImage\/init","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroNoImage"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzintronoimage\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MrzIntroNoImage/init":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzintronoimage\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroNoImage\/init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MrzIntroNoImage":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MrzIntroNoImage"}],"type":"topic","title":"SBSDKUI2MrzIntroNoImage","abstract":[{"text":"No image for the introduction screen.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzintronoimage","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MrzIntroNoImage"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroNoImage"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzIntroNoImage\/title","op":"replace","value":"SBSDKUI2MrzIntroNoImage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzIntroNoImage\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MrzIntroNoImage"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzIntroNoImage\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2MrzIntroNoImage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}