{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorUnknownDocument","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/errorunknowndocument"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/errorunknowndocument"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus"]]},"abstract":[{"text":"A document was detected, but it was not extracted as a supported document.","type":"text"}],"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDataExtractionStatus@SBSDKDocumentDataExtractionStatusErrorUnknownDocument","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusErrorUnknownDocument"}],"roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"errorUnknownDocument","kind":"identifier"}],"title":"SBSDKDocumentDataExtractionStatus.errorUnknownDocument","symbolKind":"case","modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorUnknownDocument","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/errorUnknownDocument":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/errorunknowndocument","role":"symbol","abstract":[{"type":"text","text":"A document was detected, but it was not extracted as a supported document."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorUnknownDocument"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorUnknownDocument","title":"SBSDKDocumentDataExtractionStatus.errorUnknownDocument","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusErrorUnknownDocument"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatus"}],"type":"topic","abstract":[{"text":"The status of the extraction process.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus","title":"SBSDKDocumentDataExtractionStatus","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKDocumentDataExtractionStatusErrorUnknownDocument","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusErrorUnknownDocument"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKDocumentDataExtractionStatusErrorUnknownDocument","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKDocumentDataExtractionStatusErrorUnknownDocument","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1errorUnknownDocument\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1errorUnknownDocument\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusErrorUnknownDocument"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/title","value":"SBSDKDocumentDataExtractionStatus","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/fragments","value":[{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/navigatorTitle","op":"replace"}]}]}