{"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannerview\/accessibilityshowslargecontentviewer(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView\/accessibilityShowsLargeContentViewer(_:)","interfaceLanguage":"swift"},"metadata":{"extendedModule":"SwiftUICore","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityShowsLargeContentViewer"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"V"},{"kind":"text","text":">(() -> "},{"kind":"typeIdentifier","text":"V"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"platforms":[{"introducedAt":"15.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"15.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"15.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"12.0","name":"macOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"15.0","name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"beta":false,"unavailable":false,"introducedAt":"8.0","name":"watchOS","deprecated":false}],"modules":[{"name":"ScanbotSDK","relatedModules":["SwiftUICore"]}],"externalID":"s:7SwiftUI4ViewPAAE36accessibilityShowsLargeContentVieweryQrqd__yXEAaBRd__lF::SYNTHESIZED::s:10ScanbotSDK27SBSDKUI2DocumentScannerViewV","roleHeading":"Instance Method","title":"accessibilityShowsLargeContentViewer(_:)","symbolKind":"method","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView\/View-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"View.accessibilityShowsLargeContentViewer(_:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityShowsLargeContentViewer","kind":"identifier"},{"text":"<","kind":"text"},{"text":"V","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"@","kind":"attribute"},{"text":"ViewBuilder","preciseIdentifier":"s:7SwiftUI11ViewBuilderV","kind":"attribute"},{"text":" ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"largeContentView","kind":"internalParam"},{"text":": () -> ","kind":"text"},{"text":"V","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"V","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"},{"text":"\n","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerView":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerView","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView","abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerController"},{"text":".","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannerview","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerView","kind":"identifier"}],"title":"SBSDKUI2DocumentScannerView"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerView/View-Implementations":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannerview\/view-implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView\/View-Implementations","kind":"article","title":"View Implementations","role":"collectionGroup"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerController":{"title":"SBSDKUI2DocumentScannerController","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerController","abstract":[{"text":"A highly customizable camera-based RTU-UI controller to scan documents.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannercontroller","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerController","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerView/accessibilityShowsLargeContentViewer(_:)":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannerview\/accessibilityshowslargecontentviewer(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView\/accessibilityShowsLargeContentViewer(_:)","role":"symbol","type":"topic","title":"accessibilityShowsLargeContentViewer(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityShowsLargeContentViewer","kind":"identifier"},{"text":"<","kind":"text"},{"text":"V","kind":"genericParameter"},{"text":">(() -> ","kind":"text"},{"text":"V","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2DocumentScannerController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerController\/title"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentScannerController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerController\/navigatorTitle"}]}]}