{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"kind":"identifier","text":"textRectForBounds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"bounds"},{"kind":"text","text":" "},{"kind":"identifier","text":"limitedToNumberOfLines:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"numberOfLines"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkdetectionstatuslabel\/textrectforbounds:limitedtonumberoflines:"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKDetectionStatusLabel(im)textRectForBounds:limitedToNumberOfLines:","symbolKind":"method","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"textRectForBounds:limitedToNumberOfLines:","roleHeading":"Instance Method","navigatorTitle":[{"text":"textRectForBounds:limitedToNumberOfLines:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"textRectForBounds:limitedToNumberOfLines:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDetectionStatusLabel\/textRectForBounds:limitedToNumberOfLines:","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDetectionStatusLabel"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKDetectionStatusLabel/textRectForBounds:limitedToNumberOfLines:":{"kind":"symbol","navigatorTitle":[{"text":"textRectForBounds:limitedToNumberOfLines:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkdetectionstatuslabel\/textrectforbounds:limitedtonumberoflines:","fragments":[{"text":"- ","kind":"text"},{"text":"textRectForBounds:limitedToNumberOfLines:","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDetectionStatusLabel\/textRectForBounds:limitedToNumberOfLines:","abstract":[],"title":"textRectForBounds:limitedToNumberOfLines:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKDetectionStatusLabel":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkdetectionstatuslabel","navigatorTitle":[{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}],"title":"SBSDKDetectionStatusLabel","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDetectionStatusLabel","role":"symbol","type":"topic","abstract":[{"text":"A ","type":"text"},{"code":"UILabel","type":"codeVoice"},{"text":" subclass with rounded corners and content insets to display the status of the current document detection result.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKDetectionStatusLabel","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDetectionStatusLabel\/title"},{"value":[{"kind":"identifier","text":"SBSDKDetectionStatusLabel"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDetectionStatusLabel\/fragments"},{"value":[{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDetectionStatusLabel\/navigatorTitle"}]}]}