{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CaptureFeedback\/initWithCameraBlinkEnabled:snapFeedbackMode:"},"metadata":{"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"text":"initWithCameraBlinkEnabled:snapFeedbackMode:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CaptureFeedback(im)initWithCameraBlinkEnabled:snapFeedbackMode:","navigatorTitle":[{"text":"initWithCameraBlinkEnabled:snapFeedbackMode:","kind":"identifier"}],"role":"symbol","title":"initWithCameraBlinkEnabled:snapFeedbackMode:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CaptureFeedback"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturefeedback\/initwithcamerablinkenabled:snapfeedbackmode:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithCameraBlinkEnabled:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cameraBlinkEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"snapFeedbackMode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PageSnapFeedbackMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackMode","text":"SBSDKUI2PageSnapFeedbackMode"},{"kind":"text","text":" *) "},{"text":"snapFeedbackMode","kind":"internalParam"},{"kind":"text","text":";"}]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CaptureFeedback/initWithCameraBlinkEnabled:snapFeedbackMode:":{"navigatorTitle":[{"text":"initWithCameraBlinkEnabled:snapFeedbackMode:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CaptureFeedback\/initWithCameraBlinkEnabled:snapFeedbackMode:","abstract":[],"kind":"symbol","title":"initWithCameraBlinkEnabled:snapFeedbackMode:","type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCameraBlinkEnabled:snapFeedbackMode:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturefeedback\/initwithcamerablinkenabled:snapfeedbackmode:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CaptureFeedback":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2CaptureFeedback","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CaptureFeedback","abstract":[{"text":"Configuration of the feedback shown after snapping a page.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturefeedback","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CaptureFeedback"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PageSnapFeedbackMode":{"title":"SBSDKUI2PageSnapFeedbackMode","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackMode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PageSnapFeedbackMode","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapfeedbackmode","abstract":[{"text":"The type of animation to display after snapping a page.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2PageSnapFeedbackMode","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CaptureFeedback\/title","value":"SBSDKUI2CaptureFeedback"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CaptureFeedback\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CaptureFeedback"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CaptureFeedback\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CaptureFeedback"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackMode\/title","value":"SBSDKUI2PageSnapFeedbackMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackMode\/fragments","value":[{"text":"SBSDKUI2PageSnapFeedbackMode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}