{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CaptureFeedback\/snapFeedbackMode","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CaptureFeedback"]]},"sections":[],"abstract":[{"text":"The type of animation to display after snapping a page.","type":"text"}],"metadata":{"title":"snapFeedbackMode","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CaptureFeedback(py)snapFeedbackMode","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"snapFeedbackMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2PageSnapFeedbackMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PageSnapFeedbackMode"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"snapFeedbackMode"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"snapFeedbackMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackMode","text":"SBSDKUI2PageSnapFeedbackMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PageSnapFeedbackMode"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturefeedback\/snapfeedbackmode"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturefeedback\/snapfeedbackmode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CaptureFeedback/snapFeedbackMode":{"abstract":[{"type":"text","text":"The type of animation to display after snapping a page."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturefeedback\/snapfeedbackmode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"snapFeedbackMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PageSnapFeedbackMode","text":"SBSDKUI2PageSnapFeedbackMode"}],"navigatorTitle":[{"text":"snapFeedbackMode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CaptureFeedback\/snapFeedbackMode","kind":"symbol","role":"symbol","title":"snapFeedbackMode"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CaptureFeedback":{"kind":"symbol","abstract":[{"text":"Configuration of the feedback shown after snapping a page.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CaptureFeedback","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturefeedback","role":"symbol","title":"SBSDKUI2CaptureFeedback","navigatorTitle":[{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PageSnapFeedbackMode":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapfeedbackmode","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackMode","navigatorTitle":[{"text":"SBSDKUI2PageSnapFeedbackMode","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}],"title":"SBSDKUI2PageSnapFeedbackMode","abstract":[{"type":"text","text":"The type of animation to display after snapping a page."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"snapFeedbackMode","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"snapFeedbackMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackMode","text":"SBSDKUI2PageSnapFeedbackMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PageSnapFeedbackMode"},{"kind":"text","text":" * "},{"kind":"identifier","text":"snapFeedbackMode"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CaptureFeedback~1snapFeedbackMode\/title","value":"snapFeedbackMode"},{"op":"replace","value":[{"text":"snapFeedbackMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CaptureFeedback~1snapFeedbackMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CaptureFeedback\/title","value":"SBSDKUI2CaptureFeedback","op":"replace"},{"value":[{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CaptureFeedback\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CaptureFeedback\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CaptureFeedback"}],"op":"replace"},{"value":"SBSDKUI2PageSnapFeedbackMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackMode\/title"},{"op":"replace","value":[{"text":"SBSDKUI2PageSnapFeedbackMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}],"op":"replace"}]}]}