{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode128Configuration"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcode128configuration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:gs1handling:minimumtextlength:maximumtextlength:"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode128Configuration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:gs1Handling:minimumTextLength:maximumTextLength:"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRegexFilter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"regexFilter"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumSizeScore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumSizeScore"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAdditionalQuietZone:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"addAdditionalQuietZone"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimum1DQuietZoneSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimum1DQuietZoneSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"gs1Handling:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1Handling","text":"SBSDKGS1Handling"},{"kind":"text","text":") "},{"kind":"internalParam","text":"gs1Handling"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumTextLength:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumTextLength"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumTextLength:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maximumTextLength"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:gs1Handling:minimumTextLength:maximumTextLength:"}],"roleHeading":"Instance Method","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:gs1Handling:minimumTextLength:maximumTextLength:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:gs1Handling:minimumTextLength:maximumTextLength:"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatCode128Configuration(im)initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:gs1Handling:minimumTextLength:maximumTextLength:","role":"symbol"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling","type":"topic","abstract":[{"text":"GS1 message handling options.","type":"text"},{"text":" ","type":"text"},{"text":"The GS1 standard defines a key-value format for business-centric data that can be encoded into many 1D and 2D","type":"text"},{"text":" ","type":"text"},{"text":"barcode types.","type":"text"},{"text":" ","type":"text"},{"text":"https:\/\/ref.gs1.org\/standards\/genspecs\/","type":"text"}],"title":"SBSDKGS1Handling","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling","navigatorTitle":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGS1Handling","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatCode128Configuration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:gs1Handling:minimumTextLength:maximumTextLength:":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode128Configuration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:gs1Handling:minimumTextLength:maximumTextLength:","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcode128configuration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:gs1handling:minimumtextlength:maximumtextlength:","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:gs1Handling:minimumTextLength:maximumTextLength:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:gs1Handling:minimumTextLength:maximumTextLength:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:gs1Handling:minimumTextLength:maximumTextLength:"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatCode128Configuration":{"title":"SBSDKBarcodeFormatCode128Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatCode128Configuration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcode128configuration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode128Configuration","type":"topic","kind":"symbol","abstract":[{"text":"Code 128 barcode configuration. Add to scanner configuration to scan Code 128 barcodes.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode128Configuration"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/title","value":"SBSDKGS1Handling"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/fragments","value":[{"text":"SBSDKGS1Handling","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/navigatorTitle","value":[{"text":"SBSDKGS1Handling","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode128Configuration\/title","value":"SBSDKBarcodeFormatCode128Configuration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode128Configuration\/fragments","value":[{"text":"SBSDKBarcodeFormatCode128Configuration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode128Configuration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatCode128Configuration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}