{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcode128configuration\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode128Configuration\/isEqual:"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode128Configuration"]]},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatCode128Configuration(im)isEqual:","symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"roleHeading":"Instance Method","title":"isEqual:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatCode128Configuration":{"title":"SBSDKBarcodeFormatCode128Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatCode128Configuration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcode128configuration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode128Configuration","type":"topic","kind":"symbol","abstract":[{"text":"Code 128 barcode configuration. Add to scanner configuration to scan Code 128 barcodes.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode128Configuration"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatCode128Configuration/isEqual:":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcode128configuration\/isequal:","role":"symbol","type":"topic","title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode128Configuration\/isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode128Configuration\/title","value":"SBSDKBarcodeFormatCode128Configuration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode128Configuration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode128Configuration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode128Configuration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode128Configuration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}