{"abstract":[{"text":"GS1 message handling options.","type":"text"}],"metadata":{"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"gs1Handling","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKGS1Handling","kind":"typeIdentifier","text":"SBSDKGS1Handling"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatQRCodeConfiguration(py)gs1Handling","title":"gs1Handling","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"gs1Handling","kind":"identifier"}]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/gs1handling"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/gs1handling"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/gs1Handling","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"gs1Handling","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling","text":"SBSDKGS1Handling","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKGS1Handling"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"text":"Default is PARSE","type":"text"}],"type":"paragraph"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/gs1Handling":{"abstract":[{"text":"GS1 message handling options.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/gs1handling","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"gs1Handling"},{"kind":"text","text":": "},{"text":"SBSDKGS1Handling","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKGS1Handling"}],"navigatorTitle":[{"text":"gs1Handling","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/gs1Handling","title":"gs1Handling","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatQRCodeConfiguration"}],"abstract":[{"text":"QR Code configuration. Add to scanner configuration to scan QR codes, Micro QR codes and rectangular Micro QR (rMQR)","type":"text"},{"type":"text","text":" "},{"text":"codes.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration","type":"topic","title":"SBSDKBarcodeFormatQRCodeConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling","type":"topic","role":"symbol","abstract":[{"type":"text","text":"GS1 message handling options."},{"type":"text","text":" "},{"text":"The GS1 standard defines a key-value format for business-centric data that can be encoded into many 1D and 2D","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"barcode types."},{"type":"text","text":" "},{"type":"text","text":"https:\/\/ref.gs1.org\/standards\/genspecs\/"}],"kind":"symbol","title":"SBSDKGS1Handling","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGS1Handling"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"url":"\/documentation\/scanbotsdk\/sbsdkgs1handling"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"gs1Handling","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"gs1Handling","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKGS1Handling","text":"SBSDKGS1Handling"},{"kind":"text","text":" "},{"text":"gs1Handling","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1gs1Handling\/title","value":"gs1Handling","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1gs1Handling\/fragments","op":"replace","value":[{"kind":"identifier","text":"gs1Handling"}]},{"op":"replace","value":"SBSDKBarcodeFormatQRCodeConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/title","value":"SBSDKGS1Handling","op":"replace"},{"op":"replace","value":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/navigatorTitle","value":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}