{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult\/init(rawText:wordBoxes:symbolBoxes:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"rawText","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"wordBoxes","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWordBox","kind":"typeIdentifier","text":"SBSDKWordBox","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKWordBox"},{"text":"], ","kind":"text"},{"text":"symbolBoxes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKSymbolBox","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSymbolBox","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSymbolBox"},{"text":"])","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult(im)initWithRawText:wordBoxes:symbolBoxes:","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rawText"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"wordBoxes"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKWordBox","text":"SBSDKWordBox"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"symbolBoxes"},{"text":": [","kind":"text"},{"text":"SBSDKSymbolBox","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSymbolBox","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"initWithRawText:wordBoxes:symbolBoxes:","kind":"identifier"}],"title":"init(rawText:wordBoxes:symbolBoxes:)","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult\/init(rawtext:wordboxes:symbolboxes:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult\/init(rawtext:wordboxes:symbolboxes:)"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSymbolBox":{"url":"\/documentation\/scanbotsdk\/sbsdksymbolbox","title":"SBSDKSymbolBox","abstract":[{"text":"Structure containing recognized symbol text and bounds.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKSymbolBox"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSymbolBox","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKSymbolBox"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerResult":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTextPatternScannerResult"}],"navigatorTitle":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"title":"SBSDKTextPatternScannerResult","type":"topic","kind":"symbol","abstract":[{"text":"The result of the text line recognition.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerResult/init(rawText:wordBoxes:symbolBoxes:)":{"kind":"symbol","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rawText"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"wordBoxes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKWordBox","text":"SBSDKWordBox"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"symbolBoxes"},{"kind":"text","text":": ["},{"text":"SBSDKSymbolBox","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSymbolBox"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult\/init(rawText:wordBoxes:symbolBoxes:)","navigatorTitle":[{"text":"initWithRawText:wordBoxes:symbolBoxes:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult\/init(rawtext:wordboxes:symbolboxes:)","title":"init(rawText:wordBoxes:symbolBoxes:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWordBox":{"type":"topic","navigatorTitle":[{"text":"SBSDKWordBox","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWordBox","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkwordbox","abstract":[{"type":"text","text":"Structure containing recognized word text and bounds."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKWordBox"}],"title":"SBSDKWordBox"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithRawText:wordBoxes:symbolBoxes:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithRawText:wordBoxes:symbolBoxes:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithRawText:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"rawText","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"wordBoxes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKWordBox *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"wordBoxes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"symbolBoxes:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKSymbolBox *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"symbolBoxes","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"SBSDKSymbolBox","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSymbolBox\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSymbolBox\/fragments","value":[{"kind":"identifier","text":"SBSDKSymbolBox"}],"op":"replace"},{"value":[{"text":"SBSDKSymbolBox","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSymbolBox\/navigatorTitle","op":"replace"},{"op":"replace","value":"SBSDKTextPatternScannerResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/fragments","value":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult~1init(rawText:wordBoxes:symbolBoxes:)\/title","value":"initWithRawText:wordBoxes:symbolBoxes:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult~1init(rawText:wordBoxes:symbolBoxes:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithRawText:wordBoxes:symbolBoxes:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWordBox\/title","value":"SBSDKWordBox"},{"value":[{"kind":"identifier","text":"SBSDKWordBox"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWordBox\/fragments"},{"value":[{"text":"SBSDKWordBox","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWordBox\/navigatorTitle","op":"replace"}]}]}