{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult"]]},"sections":[],"abstract":[{"text":"Boxes for each recognized symbol.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult\/symbolBoxes"},"metadata":{"title":"symbolBoxes","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult(py)symbolBoxes","navigatorTitle":[{"text":"symbolBoxes","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"symbolBoxes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKSymbolBox","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSymbolBox"},{"text":"]","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"symbolBoxes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKSymbolBox","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSymbolBox","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSymbolBox","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult\/symbolboxes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult\/symbolboxes"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerResult":{"title":"SBSDKTextPatternScannerResult","type":"topic","abstract":[{"text":"The result of the text line recognition.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult","navigatorTitle":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerResult/symbolBoxes":{"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult\/symbolboxes","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult\/symbolBoxes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"symbolBoxes"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Boxes for each recognized symbol."}],"title":"symbolBoxes","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"symbolBoxes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSymbolBox","text":"SBSDKSymbolBox"},{"kind":"text","text":"]"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSymbolBox":{"navigatorTitle":[{"text":"SBSDKSymbolBox","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Structure containing recognized symbol text and bounds.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSymbolBox","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSymbolBox","title":"SBSDKSymbolBox","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdksymbolbox"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"symbolBoxes","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"symbolBoxes"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKSymbolBox *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"symbolBoxes","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKTextPatternScannerResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/title"},{"op":"replace","value":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/fragments"},{"op":"replace","value":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/navigatorTitle"},{"op":"replace","value":"symbolBoxes","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult~1symbolBoxes\/title"},{"op":"replace","value":[{"kind":"identifier","text":"symbolBoxes"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult~1symbolBoxes\/fragments"},{"op":"replace","value":"SBSDKSymbolBox","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSymbolBox\/title"},{"op":"replace","value":[{"text":"SBSDKSymbolBox","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSymbolBox\/fragments"},{"op":"replace","value":[{"text":"SBSDKSymbolBox","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSymbolBox\/navigatorTitle"}]}]}