{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"dynamic","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumTimeWithoutDeviceMotionBeforeDetection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"To prevent blurred images before the video frame is sent to the scanner, the device must have registered no significant motion for a certain amount of time.","type":"text"},{"text":" ","type":"text"},{"text":"This property defines this amount of time.","type":"text"},{"text":" ","type":"text"},{"text":"By default it is set to 0.0 seconds for the most scanners.","type":"text"}],"kind":"symbol","metadata":{"title":"minimumTimeWithoutDeviceMotionBeforeDetection","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumTimeWithoutDeviceMotionBeforeDetection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"text":"minimumTimeWithoutDeviceMotionBeforeDetection","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration(py)minimumTimeWithoutDeviceMotionBeforeDetection","role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/minimumTimeWithoutDeviceMotionBeforeDetection","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/minimumtimewithoutdevicemotionbeforedetection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/minimumtimewithoutdevicemotionbeforedetection"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration","title":"SBSDKBaseScannerGeneralConfiguration","abstract":[{"type":"text","text":"The general configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/minimumTimeWithoutDeviceMotionBeforeDetection":{"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/minimumtimewithoutdevicemotionbeforedetection","type":"topic","navigatorTitle":[{"text":"minimumTimeWithoutDeviceMotionBeforeDetection","kind":"identifier"}],"role":"symbol","title":"minimumTimeWithoutDeviceMotionBeforeDetection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/minimumTimeWithoutDeviceMotionBeforeDetection","abstract":[{"text":"To prevent blurred images before the video frame is sent to the scanner, the device must have registered no significant motion for a certain amount of time.","type":"text"},{"text":" ","type":"text"},{"text":"This property defines this amount of time.","type":"text"},{"text":" ","type":"text"},{"text":"By default it is set to 0.0 seconds for the most scanners.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumTimeWithoutDeviceMotionBeforeDetection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"minimumTimeWithoutDeviceMotionBeforeDetection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"minimumTimeWithoutDeviceMotionBeforeDetection","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" ","kind":"text"},{"text":"minimumTimeWithoutDeviceMotionBeforeDetection","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/title","value":"SBSDKBaseScannerGeneralConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/fragments","value":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/navigatorTitle","op":"replace"},{"value":"minimumTimeWithoutDeviceMotionBeforeDetection","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1minimumTimeWithoutDeviceMotionBeforeDetection\/title","op":"replace"},{"value":[{"kind":"identifier","text":"minimumTimeWithoutDeviceMotionBeforeDetection"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1minimumTimeWithoutDeviceMotionBeforeDetection\/fragments","op":"replace"}]}]}