{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerview\/init(configuration:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/init(configuration:completion:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView","type":"reference","isActive":true},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerScreenConfiguration","text":"SBSDKUI2CheckScannerScreenConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerUIResult","kind":"typeIdentifier","text":"SBSDKUI2CheckScannerUIResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerUIResult"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> ())"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration to define look and feel of the new scanner view."}]}],"name":"configuration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handler to be called when the scanning is finished, providing the result or an error."}]}],"name":"completion"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView"]]},"metadata":{"externalID":"s:10ScanbotSDK24SBSDKUI2CheckScannerViewV13configuration10completionAcA0cdE19ScreenConfigurationC_yAA0cdE8UIResultCSg_s5Error_pSgtctcfc","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"init(configuration:completion:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CheckScannerScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerScreenConfiguration"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"SBSDKUI2CheckScannerUIResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerUIResult"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ())","kind":"text"}],"roleHeading":"Initializer"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerView/init(configuration:completion:)":{"kind":"symbol","title":"init(configuration:completion:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerview\/init(configuration:completion:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/init(configuration:completion:)","role":"symbol","abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView","isActive":true,"type":"reference"},{"type":"text","text":"."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CheckScannerScreenConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerScreenConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"SBSDKUI2CheckScannerUIResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerUIResult","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ())","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerScreenConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CheckScannerScreenConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CheckScannerScreenConfiguration","kind":"identifier"}],"title":"SBSDKUI2CheckScannerScreenConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreenconfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration of the screen for detecting check data."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerUIResult":{"url":"\/documentation\/scanbotsdk\/sbsdkui2checkscanneruiresult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerUIResult","title":"SBSDKUI2CheckScannerUIResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CheckScannerUIResult"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the check scanner RTU UI result."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckScannerUIResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerView":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CheckScannerView"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckScannerView"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerview","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView","title":"SBSDKUI2CheckScannerView","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerviewcontroller","role":"symbol","type":"topic","title":"SBSDKUI2CheckScannerViewController","kind":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to scan check data."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenConfiguration\/title","value":"SBSDKUI2CheckScannerScreenConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerScreenConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerScreenConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerUIResult\/title","value":"SBSDKUI2CheckScannerUIResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerUIResult\/fragments","value":[{"text":"SBSDKUI2CheckScannerUIResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerUIResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerUIResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/title","value":"SBSDKUI2CheckScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}