{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving\/cameraSession(_:didToggleTorchlight:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","title":"cameraSession(_:didToggleTorchlight:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraSession"},{"kind":"text","text":"("},{"text":"SBSDKCameraSession","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didToggleTorchlight"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"required":true,"role":"symbol","navigatorTitle":[{"text":"cameraSession:didToggleTorchlight:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKCameraSessionObserving(im)cameraSession:didToggleTorchlight:","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasessionobserving\/camerasession(_:didtoggletorchlight:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasessionobserving\/camerasession(_:didtoggletorchlight:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"text":": ","kind":"text"},{"text":"SBSDKCameraSession","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didToggleTorchlight"},{"text":" ","kind":"text"},{"text":"enabled","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The camera session that toggled the torch light."}]}],"name":"session"},{"name":"enabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether the light was turned on or off."}]}]}]}],"abstract":[{"text":"Informs the observer that the torch light has been toggled on or off.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession":{"abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"type":"text","text":" "},{"text":"camera device and the preview layer. Provides functionality to capture still images.","type":"text"}],"title":"SBSDKCameraSession","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSession"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSession"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSessionObserving":{"url":"\/documentation\/scanbotsdk\/sbsdkcamerasessionobserving","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving","role":"symbol","abstract":[{"type":"text","text":"A multicast-observer protocol that informs its observers about state changes of a camera session."}],"navigatorTitle":[{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"kind":"symbol","type":"topic","title":"SBSDKCameraSessionObserving","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKCameraSessionObserving","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSessionObserving/cameraSession(_:didToggleTorchlight:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cameraSession","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession","text":"SBSDKCameraSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didToggleTorchlight","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasessionobserving\/camerasession(_:didtoggletorchlight:)","abstract":[{"type":"text","text":"Informs the observer that the torch light has been toggled on or off."}],"navigatorTitle":[{"kind":"identifier","text":"cameraSession:didToggleTorchlight:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving\/cameraSession(_:didToggleTorchlight:)","required":true,"title":"cameraSession(_:didToggleTorchlight:)","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"cameraSession:didToggleTorchlight:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cameraSession:didToggleTorchlight:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"cameraSession:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","text":"SBSDKCameraSession","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didToggleTorchlight:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"enabled"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"session","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The camera session that toggled the torch light."}]}]},{"name":"enabled","content":[{"type":"paragraph","inlineContent":[{"text":"Whether the light was turned on or off.","type":"text"}]}]}]}},{"op":"replace","value":"SBSDKCameraSession","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraSession"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCameraSession"}]},{"value":"SBSDKCameraSessionObserving","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving\/title"},{"op":"replace","value":[{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraSessionObserving"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving~1cameraSession(_:didToggleTorchlight:)\/title","op":"replace","value":"cameraSession:didToggleTorchlight:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cameraSession:didToggleTorchlight:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving~1cameraSession(_:didToggleTorchlight:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}