{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSProgress"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s8SendableP"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKProgress","kind":"identifier"}]}]}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKProgress"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProgress"}],"roleHeading":"Class","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress","role":"symbol","symbolKind":"class","title":"SBSDKProgress"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress"]}],"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/init(totalUnitCount:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/updateHandler"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/SBSDKProgressKindCreatePages","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/SBSDKProgressKindProcessImage","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/SBSDKProgressKindTextRecognition"],"generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress/updateHandler":{"navigatorTitle":[{"text":"updateHandler","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/updateHandler","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress\/updatehandler","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateHandler"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKProgessUpdateHandler","preciseIdentifier":"s:25ScanbotDocumentScannerSDK25SBSDKProgessUpdateHandlera"},{"kind":"text","text":"?"}],"title":"updateHandler","abstract":[{"type":"text","text":"The standard process for observing a "},{"code":"Progress","type":"codeVoice"},{"text":" progressing is to use KVO on the ","type":"text"},{"code":"Progress","type":"codeVoice"},{"text":" instance.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"SBSDKProgressUpdateHandler","type":"codeVoice"},{"type":"text","text":" simplifies observing the progress largely."},{"type":"text","text":" "},{"text":"It is called on main thread whenever the progress changes. Usually here you update your UI, e.g. ","type":"text"},{"code":"UIProgressView","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress/SBSDKProgressKindCreatePages":{"title":"SBSDKProgressKindCreatePages","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress\/sbsdkprogresskindcreatepages","navigatorTitle":[{"kind":"identifier","text":"SBSDKProgressKindCreatePages"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProgressKindCreatePages"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/SBSDKProgressKindCreatePages","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The progress describes a document\/PDF creation operation."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress/cancelled":{"abstract":[],"fragments":[{"text":"cancelled","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/cancelled","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress\/cancelled","kind":"symbol","type":"topic","title":"cancelled","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress/init(totalUnitCount:)":{"navigatorTitle":[{"text":"initWithTotalUnitCount:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/init(totalUnitCount:)","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress\/init(totalunitcount:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"totalUnitCount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(totalUnitCount:)","abstract":[{"type":"text","text":"A convenience initializer mimicking the behavior of "},{"code":"Progress","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress/SBSDKProgressKindTextRecognition":{"title":"SBSDKProgressKindTextRecognition","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress\/sbsdkprogresskindtextrecognition","navigatorTitle":[{"kind":"identifier","text":"SBSDKProgressKindTextRecognition"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKProgressKindTextRecognition"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/SBSDKProgressKindTextRecognition","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The progress describes a text recognition operation."}]},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress/SBSDKProgressKindProcessImage":{"title":"SBSDKProgressKindProcessImage","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress\/sbsdkprogresskindprocessimage","navigatorTitle":[{"kind":"identifier","text":"SBSDKProgressKindProcessImage"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKProgressKindProcessImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/SBSDKProgressKindProcessImage","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The progress describes an image processing operation."}]},"doc://net.doo.ScanbotDocumentScannerSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s8SendableP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress/initWithParent:userInfo:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithParent:userInfo:"}],"navigatorTitle":[{"text":"initWithParent:userInfo:","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","title":"initWithParent:userInfo:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/initWithParent:userInfo:","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress\/initwithparent:userinfo:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress/observeValueForKeyPath:ofObject:change:context:":{"title":"observeValueForKeyPath:ofObject:change:context:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress\/observevalueforkeypath:ofobject:change:context:","navigatorTitle":[{"text":"observeValueForKeyPath:ofObject:change:context:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeValueForKeyPath:ofObject:change:context:"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/observeValueForKeyPath:ofObject:change:context:","role":"symbol","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProgress"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKProgress"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress","title":"SBSDKProgress","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSProgress":{"title":"NSProgress","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSProgress"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress/localizedDescription":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/localizedDescription","kind":"symbol","role":"symbol","abstract":[],"title":"localizedDescription","fragments":[{"text":"localizedDescription","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress\/localizeddescription"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress/cancel":{"navigatorTitle":[{"text":"cancel","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/cancel","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress\/cancel","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancel"}],"type":"topic","abstract":[],"title":"cancel"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress/localizedAdditionalDescription":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/localizedAdditionalDescription","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress\/localizedadditionaldescription","role":"symbol","fragments":[{"kind":"identifier","text":"localizedAdditionalDescription"}],"title":"localizedAdditionalDescription","abstract":[],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"SBSDKProgress","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKProgress"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKProgress"}],"op":"replace"},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/cancelled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/localizedAdditionalDescription","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/localizedDescription","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/updateHandler"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/cancel","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/init(totalUnitCount:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/initWithParent:userInfo:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/observeValueForKeyPath:ofObject:change:context:"]},{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/SBSDKProgressKindCreatePages","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/SBSDKProgressKindProcessImage","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/SBSDKProgressKindTextRecognition"],"anchor":"Type-Properties"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSProgress"],"kind":"relationships","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProgress"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSProgress","preciseIdentifier":"c:objc(cs)NSProgress"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress~1updateHandler\/title","value":"updateHandler"},{"op":"replace","value":[{"kind":"identifier","text":"updateHandler"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress~1updateHandler\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress~1SBSDKProgressKindCreatePages\/title","value":"SBSDKProgressKindCreatePages","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress~1SBSDKProgressKindCreatePages\/fragments","op":"replace","value":[{"text":"SBSDKProgressKindCreatePages","kind":"identifier"}]},{"value":"initWithTotalUnitCount:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress~1init(totalUnitCount:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress~1init(totalUnitCount:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTotalUnitCount:"}],"op":"replace"},{"value":"SBSDKProgressKindTextRecognition","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress~1SBSDKProgressKindTextRecognition\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress~1SBSDKProgressKindTextRecognition\/fragments","value":[{"kind":"identifier","text":"SBSDKProgressKindTextRecognition"}],"op":"replace"},{"value":"SBSDKProgressKindProcessImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress~1SBSDKProgressKindProcessImage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKProgressKindProcessImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress~1SBSDKProgressKindProcessImage\/fragments"},{"value":"SBSDKProgress","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/fragments","value":[{"text":"SBSDKProgress","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/navigatorTitle","value":[{"text":"SBSDKProgress","kind":"identifier"}],"op":"replace"}]}]}