{"kind":"symbol","abstract":[{"type":"text","text":"Display the bottom bar with a background color or with transparency."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BottomBarMode"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BottomBarModeSolid"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"solid"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2BottomBarMode@SBSDKUI2BottomBarModeSolid","role":"symbol","symbolKind":"case","roleHeading":"Case","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"SBSDKUI2BottomBarMode.solid"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"solid","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BottomBarMode\/solid","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2bottombarmode\/solid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2bottombarmode\/solid"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2BottomBarMode/solid":{"navigatorTitle":[{"text":"SBSDKUI2BottomBarModeSolid","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BottomBarMode\/solid","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"solid","kind":"identifier"}],"abstract":[{"type":"text","text":"Display the bottom bar with a background color or with transparency."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2bottombarmode\/solid","title":"SBSDKUI2BottomBarMode.solid","role":"symbol","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2BottomBarMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BottomBarMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BottomBarMode"}],"abstract":[{"text":"The visual mode used for the bottom bar.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2bottombarmode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BottomBarMode","type":"topic","role":"symbol","title":"SBSDKUI2BottomBarMode","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKUI2BottomBarModeSolid","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BottomBarModeSolid"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKUI2BottomBarModeSolid"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BottomBarMode~1solid\/title","value":"SBSDKUI2BottomBarModeSolid","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BottomBarMode~1solid\/fragments","value":[{"text":"SBSDKUI2BottomBarModeSolid","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKUI2BottomBarMode","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BottomBarMode\/title"},{"op":"replace","value":[{"text":"SBSDKUI2BottomBarMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BottomBarMode\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2BottomBarMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BottomBarMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}