{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"metadata":{"role":"symbol","symbolKind":"property","fragments":[{"text":"hash","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatUSPSIntelligentMailConfiguration(py)hash","roleHeading":"Instance Property"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatuspsintelligentmailconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUSPSIntelligentMailConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUSPSIntelligentMailConfiguration\/hash","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUSPSIntelligentMailConfiguration":{"type":"topic","abstract":[{"text":"USPS Intelligent Mail barcode configuration. Add to scanner configuration to scan USPS Intelligent Mail (a.k.a. USPS","type":"text"},{"text":" ","type":"text"},{"text":"OneCode, USPS-STD-11) barcodes.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatUSPSIntelligentMailConfiguration"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUSPSIntelligentMailConfiguration","title":"SBSDKBarcodeFormatUSPSIntelligentMailConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatUSPSIntelligentMailConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatuspsintelligentmailconfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUSPSIntelligentMailConfiguration/hash":{"type":"topic","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatuspsintelligentmailconfiguration\/hash","role":"symbol","kind":"symbol","title":"hash","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUSPSIntelligentMailConfiguration\/hash","fragments":[{"kind":"identifier","text":"hash"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUSPSIntelligentMailConfiguration\/title","op":"replace","value":"SBSDKBarcodeFormatUSPSIntelligentMailConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUSPSIntelligentMailConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatUSPSIntelligentMailConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUSPSIntelligentMailConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormatUSPSIntelligentMailConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}