{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionCloseButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Default is “Close screen without granting permission”"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreentextlocalization\/accessibilitydescriptioncamerapermissionclosebutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreentextlocalization\/accessibilitydescriptioncamerapermissionclosebutton"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization\/accessibilityDescriptionCameraPermissionCloseButton"},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerScreenTextLocalization(py)accessibilityDescriptionCameraPermissionCloseButton","title":"accessibilityDescriptionCameraPermissionCloseButton","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionCloseButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionCloseButton"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization"]]},"sections":[],"abstract":[{"type":"text","text":"The accessibility hint for the ‘close’ button of the camera permission dialog."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerScreenTextLocalization/accessibilityDescriptionCameraPermissionCloseButton":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization\/accessibilityDescriptionCameraPermissionCloseButton","title":"accessibilityDescriptionCameraPermissionCloseButton","type":"topic","abstract":[{"text":"The accessibility hint for the ‘close’ button of the camera permission dialog.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreentextlocalization\/accessibilitydescriptioncamerapermissionclosebutton","navigatorTitle":[{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerScreenTextLocalization":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CheckScannerScreenTextLocalization","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2CheckScannerScreenTextLocalization","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the all strings for check scanner screen."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreentextlocalization","navigatorTitle":[{"text":"SBSDKUI2CheckScannerScreenTextLocalization","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"accessibilityDescriptionCameraPermissionCloseButton","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"accessibilityDescriptionCameraPermissionCloseButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenTextLocalization~1accessibilityDescriptionCameraPermissionCloseButton\/title"},{"value":[{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionCloseButton"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenTextLocalization~1accessibilityDescriptionCameraPermissionCloseButton\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenTextLocalization\/title","value":"SBSDKUI2CheckScannerScreenTextLocalization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenTextLocalization\/fragments","value":[{"text":"SBSDKUI2CheckScannerScreenTextLocalization","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2CheckScannerScreenTextLocalization","kind":"identifier"}],"op":"replace"}]}]}