{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"title","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"subtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"subtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"barcodeImage","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodemappeddata\/initwithtitle:subtitle:barcodeimage:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeMappedData"]]},"metadata":{"title":"initWithTitle:subtitle:barcodeImage:","role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeMappedData(im)initWithTitle:subtitle:barcodeImage:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTitle:subtitle:barcodeImage:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"initWithTitle:subtitle:barcodeImage:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeMappedData\/initWithTitle:subtitle:barcodeImage:","interfaceLanguage":"occ"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeMappedData/initWithTitle:subtitle:barcodeImage:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithTitle:subtitle:barcodeImage:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodemappeddata\/initwithtitle:subtitle:barcodeimage:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeMappedData\/initWithTitle:subtitle:barcodeImage:","kind":"symbol","navigatorTitle":[{"text":"initWithTitle:subtitle:barcodeImage:","kind":"identifier"}],"title":"initWithTitle:subtitle:barcodeImage:","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeMappedData":{"title":"SBSDKUI2BarcodeMappedData","kind":"symbol","abstract":[{"text":"Format of the mapped barcode data.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeMappedData","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeMappedData","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeMappedData","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodemappeddata","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeMappedData\/title","value":"SBSDKUI2BarcodeMappedData","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeMappedData\/fragments","value":[{"text":"SBSDKUI2BarcodeMappedData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeMappedData\/navigatorTitle","value":[{"text":"SBSDKUI2BarcodeMappedData","kind":"identifier"}],"op":"replace"}]}]}