{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithUIConfiguration:textConfiguration:behaviorConfiguration:"}],"roleHeading":"Initializer","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenConfiguration(im)initWithUIConfiguration:textConfiguration:behaviorConfiguration:","title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:)","platforms":[],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"uiConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUICroppingScreenUIConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenUIConfiguration"},{"kind":"text","text":", "},{"text":"textConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUICroppingScreenTextConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenTextConfiguration"},{"text":", ","kind":"text"},{"text":"behaviorConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenBehaviorConfiguration","text":"SBSDKUICroppingScreenBehaviorConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenConfiguration"]]},"abstract":[{"type":"text","text":"Designated initializer. Creates a new instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenConfiguration"},{"text":".","type":"text"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2CroppingViewController instead."}],"type":"paragraph"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithUIConfiguration:textConfiguration:behaviorConfiguration:) "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"uiConfiguration"},{"kind":"text","text":": "},{"text":"SBSDKUICroppingScreenUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenUIConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textConfiguration"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenTextConfiguration","text":"SBSDKUICroppingScreenTextConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"behaviorConfiguration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenBehaviorConfiguration","text":"SBSDKUICroppingScreenBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenBehaviorConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"uiConfiguration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A configuration for the user interface. Defines colors and sizes."}]}]},{"name":"textConfiguration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A configuration for text being displayed in the page review screen."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A configuration for defining the behavior of the cropping screen."}]}],"name":"behaviorConfiguration"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenUIConfiguration":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration for user interface of the page cropping screen."}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenuiconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICroppingScreenUIConfiguration"}],"title":"SBSDKUICroppingScreenUIConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenUIConfiguration"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenUIConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenConfiguration/init(uiConfiguration:textConfiguration:behaviorConfiguration:)":{"abstract":[{"type":"text","text":"Designated initializer. Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenConfiguration","isActive":true},{"type":"text","text":"."}],"kind":"symbol","title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uiConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUICroppingScreenUIConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenUIConfiguration"},{"text":", ","kind":"text"},{"text":"textConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUICroppingScreenTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenTextConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"behaviorConfiguration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenBehaviorConfiguration","text":"SBSDKUICroppingScreenBehaviorConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithUIConfiguration:textConfiguration:behaviorConfiguration:","kind":"identifier"}],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenTextConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreentextconfiguration","kind":"symbol","role":"symbol","deprecated":true,"title":"SBSDKUICroppingScreenTextConfiguration","navigatorTitle":[{"text":"SBSDKUICroppingScreenTextConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration for the textual content of the page cropping screen.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenBehaviorConfiguration":{"navigatorTitle":[{"text":"SBSDKUICroppingScreenBehaviorConfiguration","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenBehaviorConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration for the behavior of the cropping screen."}],"title":"SBSDKUICroppingScreenBehaviorConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenbehaviorconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingScreenBehaviorConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenConfiguration":{"abstract":[{"text":"This class describes the look and feel, as well as the textual contents of the page cropping screen.","type":"text"}],"kind":"symbol","title":"SBSDKUICroppingScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingScreenConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenConfiguration"}],"deprecated":true}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"initWithUIConfiguration:textConfiguration:behaviorConfiguration:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUIConfiguration:textConfiguration:behaviorConfiguration:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithUIConfiguration:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenUIConfiguration","text":"SBSDKUICroppingScreenUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenUIConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"uiConfiguration","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"textConfiguration:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenTextConfiguration","text":"SBSDKUICroppingScreenTextConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"textConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"behaviorConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUICroppingScreenBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenBehaviorConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"behaviorConfiguration","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUICroppingScreenUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenUIConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenUIConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUICroppingScreenUIConfiguration","kind":"identifier"}]},{"value":"initWithUIConfiguration:textConfiguration:behaviorConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithUIConfiguration:textConfiguration:behaviorConfiguration:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:)\/fragments"},{"value":"SBSDKUICroppingScreenTextConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenTextConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenTextConfiguration\/fragments"},{"value":"SBSDKUICroppingScreenBehaviorConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenBehaviorConfiguration\/title"},{"value":[{"text":"SBSDKUICroppingScreenBehaviorConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenBehaviorConfiguration\/fragments"},{"op":"replace","value":"SBSDKUICroppingScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenConfiguration\/title"},{"value":[{"text":"SBSDKUICroppingScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenConfiguration\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}