{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdksaveimageoptions\/initwithquality:encryptionmode:"]}],"kind":"symbol","metadata":{"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithQuality:encryptionMode:"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKSaveImageOptions(im)initWithQuality:encryptionMode:","title":"initWithQuality:encryptionMode:","navigatorTitle":[{"kind":"identifier","text":"initWithQuality:encryptionMode:"}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"quality","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"encryptionMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode","text":"SBSDKEncryptionMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKEncryptionMode"},{"text":") ","kind":"text"},{"text":"encryptionMode","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSaveImageOptions"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSaveImageOptions\/initWithQuality:encryptionMode:","interfaceLanguage":"occ"},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncryptionMode":{"kind":"symbol","abstract":[{"type":"text","text":"Encryption\/Decryption mode to be used when an image is loaded\/saved."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncryptionMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKEncryptionMode","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode","title":"SBSDKEncryptionMode"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSaveImageOptions":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSaveImageOptions","kind":"symbol","abstract":[{"type":"text","text":"Options for saving image to a path."}],"role":"symbol","title":"SBSDKSaveImageOptions","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksaveimageoptions","navigatorTitle":[{"text":"SBSDKSaveImageOptions","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSaveImageOptions","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSaveImageOptions/initWithQuality:encryptionMode:":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithQuality:encryptionMode:","kind":"identifier"}],"title":"initWithQuality:encryptionMode:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksaveimageoptions\/initwithquality:encryptionmode:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSaveImageOptions\/initWithQuality:encryptionMode:","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithQuality:encryptionMode:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKEncryptionMode","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode\/fragments","value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSaveImageOptions\/title","value":"SBSDKSaveImageOptions","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSaveImageOptions\/fragments","value":[{"kind":"identifier","text":"SBSDKSaveImageOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSaveImageOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKSaveImageOptions"}],"op":"replace"}]}]}