{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkDigits"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigit","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResultCheckDigit","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigit"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/checkdigits"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/checkdigits"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult\/checkDigits","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An array of recognized checkdigits."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkDigits"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigit","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResultCheckDigit"},{"kind":"text","text":"]"}],"title":"checkDigits","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResult(py)checkDigits","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"checkDigits"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResult/checkDigits":{"role":"symbol","title":"checkDigits","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkDigits"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigit","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResultCheckDigit"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"An array of recognized checkdigits."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult\/checkDigits","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"checkDigits"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/checkdigits"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigit":{"role":"symbol","title":"SBSDKMachineReadableZoneRecognizerResultCheckDigit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigit"}],"abstract":[{"type":"text","text":"Contains information about a single check-digit."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigit"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigit"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResult":{"role":"symbol","title":"SBSDKMachineReadableZoneRecognizerResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResult"}],"abstract":[{"type":"text","text":"A class encapsulating a machine-readable-zone recognition result."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResult"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"checkDigits"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"checkDigits"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBSDKMachineReadableZoneRecognizerResultCheckDigit *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"checkDigits"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult~1checkDigits\/title","value":"checkDigits"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult~1checkDigits\/fragments","value":[{"kind":"identifier","text":"checkDigits"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigit\/title","value":"SBSDKMachineReadableZoneRecognizerResultCheckDigit"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigit\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigit"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/title","value":"SBSDKMachineReadableZoneRecognizerResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}