{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"departmentOfIssuanceField","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerField","kind":"typeIdentifier","text":"SBSDKMachineReadableZoneRecognizerField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerField"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult\/departmentOfIssuanceField","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/departmentofissuancefield"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/departmentofissuancefield"]}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResult(py)departmentOfIssuanceField","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"departmentOfIssuanceField"},{"kind":"text","text":": "},{"text":"SBSDKMachineReadableZoneRecognizerField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerField"},{"kind":"text","text":"?"}],"title":"departmentOfIssuanceField","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"departmentOfIssuanceField"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult"]]},"sections":[],"abstract":[{"type":"text","text":"The issuing department."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResult/departmentOfIssuanceField":{"navigatorTitle":[{"text":"departmentOfIssuanceField","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult\/departmentOfIssuanceField","role":"symbol","title":"departmentOfIssuanceField","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/departmentofissuancefield","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"departmentOfIssuanceField"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerField","text":"SBSDKMachineReadableZoneRecognizerField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"The issuing department.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResult":{"abstract":[{"type":"text","text":"A class encapsulating a machine-readable-zone recognition result."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult","role":"symbol","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult","title":"SBSDKMachineReadableZoneRecognizerResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerField":{"abstract":[{"text":"A class representing a single data field in a machine-readable-zone.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfield","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerField"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerField","title":"SBSDKMachineReadableZoneRecognizerField","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerField"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"departmentOfIssuanceField"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"departmentOfIssuanceField"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerField","kind":"typeIdentifier","text":"SBSDKMachineReadableZoneRecognizerField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerField"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"departmentOfIssuanceField"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"departmentOfIssuanceField","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult~1departmentOfIssuanceField\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult~1departmentOfIssuanceField\/fragments","value":[{"text":"departmentOfIssuanceField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/title","value":"SBSDKMachineReadableZoneRecognizerResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerField\/title","value":"SBSDKMachineReadableZoneRecognizerField","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerField"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerField\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}