{"abstract":[{"type":"text","text":"The document code."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult\/documentCodeField","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"documentCodeField","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentCodeField"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerField","kind":"typeIdentifier","text":"SBSDKMachineReadableZoneRecognizerField"},{"kind":"text","text":"?"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResult(py)documentCodeField","symbolKind":"property","navigatorTitle":[{"text":"documentCodeField","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentCodeField","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerField","text":"SBSDKMachineReadableZoneRecognizerField"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/documentcodefield"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/documentcodefield"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerField":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerField","role":"symbol","kind":"symbol","type":"topic","title":"SBSDKMachineReadableZoneRecognizerField","abstract":[{"type":"text","text":"A class representing a single data field in a machine-readable-zone."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerField"}],"navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerField","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfield"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResult/documentCodeField":{"abstract":[{"type":"text","text":"The document code."}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/documentcodefield","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentCodeField","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"documentCodeField"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult\/documentCodeField","kind":"symbol","title":"documentCodeField","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResult":{"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult","abstract":[{"type":"text","text":"A class encapsulating a machine-readable-zone recognition result."}],"navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}],"title":"SBSDKMachineReadableZoneRecognizerResult","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"documentCodeField"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"documentCodeField","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerField","text":"SBSDKMachineReadableZoneRecognizerField"},{"kind":"text","text":" * "},{"kind":"identifier","text":"documentCodeField"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerField\/title","op":"replace","value":"SBSDKMachineReadableZoneRecognizerField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerField\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerField","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerField\/navigatorTitle","op":"replace","value":[{"text":"SBSDKMachineReadableZoneRecognizerField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult~1documentCodeField\/title","value":"documentCodeField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult~1documentCodeField\/fragments","value":[{"kind":"identifier","text":"documentCodeField"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/title","op":"replace","value":"SBSDKMachineReadableZoneRecognizerResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/navigatorTitle","value":[{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}