{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult\/personalNumberField","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/personalnumberfield"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/personalnumberfield"]}],"metadata":{"title":"personalNumberField","navigatorTitle":[{"kind":"identifier","text":"personalNumberField"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"personalNumberField"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerField","text":"SBSDKMachineReadableZoneRecognizerField"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResult(py)personalNumberField"},"abstract":[{"text":"The personal number.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"personalNumberField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerField","text":"SBSDKMachineReadableZoneRecognizerField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerField"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResult/personalNumberField":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"personalNumberField","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The personal number."}],"title":"personalNumberField","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/personalnumberfield","role":"symbol","navigatorTitle":[{"text":"personalNumberField","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult\/personalNumberField"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResult":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResult"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult","kind":"symbol","type":"topic","title":"SBSDKMachineReadableZoneRecognizerResult","abstract":[{"type":"text","text":"A class encapsulating a machine-readable-zone recognition result."}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerField":{"navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerField","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerField"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerField","kind":"symbol","type":"topic","title":"SBSDKMachineReadableZoneRecognizerField","abstract":[{"type":"text","text":"A class representing a single data field in a machine-readable-zone."}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfield"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"personalNumberField"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"personalNumberField","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerField","kind":"typeIdentifier","text":"SBSDKMachineReadableZoneRecognizerField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerField"},{"text":" * ","kind":"text"},{"text":"personalNumberField","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":"personalNumberField","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult~1personalNumberField\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult~1personalNumberField\/fragments","value":[{"text":"personalNumberField","kind":"identifier"}]},{"value":"SBSDKMachineReadableZoneRecognizerResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerField\/title","op":"replace","value":"SBSDKMachineReadableZoneRecognizerField"},{"value":[{"text":"SBSDKMachineReadableZoneRecognizerField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerField\/fragments"}]}]}