{"kind":"symbol","sections":[],"abstract":[{"text":"Number of successfully validated check digits.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult\/validCheckDigitsCount","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"validCheckDigitsCount"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResult(py)validCheckDigitsCount","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"validCheckDigitsCount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"validCheckDigitsCount","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/validcheckdigitscount"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/validcheckdigitscount"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"validCheckDigitsCount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResult":{"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult","abstract":[{"type":"text","text":"A class encapsulating a machine-readable-zone recognition result."}],"navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}],"title":"SBSDKMachineReadableZoneRecognizerResult","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResult/validCheckDigitsCount":{"navigatorTitle":[{"kind":"identifier","text":"validCheckDigitsCount"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"validCheckDigitsCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/validcheckdigitscount","role":"symbol","title":"validCheckDigitsCount","abstract":[{"type":"text","text":"Number of successfully validated check digits."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult\/validCheckDigitsCount","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"validCheckDigitsCount","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"validCheckDigitsCount","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":" "},{"text":"validCheckDigitsCount","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKMachineReadableZoneRecognizerResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/fragments","op":"replace"},{"value":[{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult~1validCheckDigitsCount\/title","value":"validCheckDigitsCount","op":"replace"},{"value":[{"text":"validCheckDigitsCount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult~1validCheckDigitsCount\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}