{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visaOptionalField","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerField","text":"SBSDKMachineReadableZoneRecognizerField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult"]]},"metadata":{"title":"visaOptionalField","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResult(py)visaOptionalField","symbolKind":"property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visaOptionalField","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerField","text":"SBSDKMachineReadableZoneRecognizerField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"visaOptionalField","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/visaoptionalfield"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/visaoptionalfield"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult\/visaOptionalField","interfaceLanguage":"swift"},"abstract":[{"text":"The optional travel visa field.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResult/visaOptionalField":{"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult\/visaoptionalfield","title":"visaOptionalField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult\/visaOptionalField","abstract":[{"text":"The optional travel visa field.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visaOptionalField"},{"kind":"text","text":": "},{"text":"SBSDKMachineReadableZoneRecognizerField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"visaOptionalField","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerField":{"abstract":[{"text":"A class representing a single data field in a machine-readable-zone.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfield","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerField"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerField","title":"SBSDKMachineReadableZoneRecognizerField","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerField"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResult":{"abstract":[{"type":"text","text":"A class encapsulating a machine-readable-zone recognition result."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult","role":"symbol","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult","title":"SBSDKMachineReadableZoneRecognizerResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResult"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"visaOptionalField"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"visaOptionalField","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerField","text":"SBSDKMachineReadableZoneRecognizerField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerField","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"visaOptionalField","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult~1visaOptionalField\/title","value":"visaOptionalField"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult~1visaOptionalField\/fragments","value":[{"kind":"identifier","text":"visaOptionalField"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerField\/title","op":"replace","value":"SBSDKMachineReadableZoneRecognizerField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerField\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/title","value":"SBSDKMachineReadableZoneRecognizerResult"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/fragments"}]}]}