{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatdatabarconfiguration\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarConfiguration"]]},"sections":[],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatDataBarConfiguration(im)copyWithZone:"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarConfiguration\/copyWithZone:"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@_NSZone","text":"_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatDataBarConfiguration":{"abstract":[{"text":"GS1 DataBar barcode configuration. Add to scanner configuration to scan GS1 DataBar-14, GS1 DataBar-14 Truncated,","type":"text"},{"text":" ","type":"text"},{"text":"GS1 DataBar-14 Stacked and GS1 DataBar-14 Stacked Omnidirectional barcodes.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatDataBarConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatDataBarConfiguration"}],"title":"SBSDKBarcodeFormatDataBarConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatdatabarconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatDataBarConfiguration/copyWithZone:":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatdatabarconfiguration\/copywithzone:","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarConfiguration\/copyWithZone:","title":"copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"SBSDKBarcodeFormatDataBarConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatDataBarConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKBarcodeFormatDataBarConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatDataBarConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatDataBarConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatDataBarConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}