{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"quality","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"format:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKEncodingFormat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodingFormat","text":"SBSDKEncodingFormat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"format","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodeImageOptions\/initWithQuality:format:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodeImageOptions"]]},"sections":[],"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithQuality:format:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithQuality:format:"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKEncodeImageOptions(im)initWithQuality:format:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","title":"initWithQuality:format:"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkencodeimageoptions\/initwithquality:format:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncodeImageOptions":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencodeimageoptions","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncodeImageOptions"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEncodeImageOptions"}],"title":"SBSDKEncodeImageOptions","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodeImageOptions","abstract":[{"text":"Options for encoding image.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncodingFormat":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencodingformat","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncodingFormat","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodingFormat","navigatorTitle":[{"text":"SBSDKEncodingFormat","kind":"identifier"}],"title":"SBSDKEncodingFormat","role":"symbol","kind":"symbol","abstract":[{"text":"Image Encoding Format.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncodeImageOptions/initWithQuality:format:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithQuality:format:","kind":"identifier"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithQuality:format:","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencodeimageoptions\/initwithquality:format:","title":"initWithQuality:format:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodeImageOptions\/initWithQuality:format:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodeImageOptions\/title","op":"replace","value":"SBSDKEncodeImageOptions"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodeImageOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKEncodeImageOptions"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodeImageOptions\/navigatorTitle","op":"replace","value":[{"text":"SBSDKEncodeImageOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodingFormat\/title","op":"replace","value":"SBSDKEncodingFormat"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodingFormat\/fragments","op":"replace","value":[{"text":"SBSDKEncodingFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodingFormat\/navigatorTitle","op":"replace","value":[{"text":"SBSDKEncodingFormat","kind":"identifier"}]}]}]}