{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgessUpdateHandler","preciseIdentifier":"s:25ScanbotDocumentScannerSDK25SBSDKProgessUpdateHandlera","text":"SBSDKProgessUpdateHandler"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress\/updatehandler"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress\/updatehandler"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/updateHandler","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The standard process for observing a "},{"type":"codeVoice","code":"Progress"},{"type":"text","text":" progressing is to use KVO on the "},{"type":"codeVoice","code":"Progress"},{"type":"text","text":" instance."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"SBSDKProgressUpdateHandler"},{"type":"text","text":" simplifies observing the progress largely."},{"type":"text","text":" "},{"type":"text","text":"It is called on main thread whenever the progress changes. Usually here you update your UI, e.g. "},{"type":"codeVoice","code":"UIProgressView"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKProgessUpdateHandler","preciseIdentifier":"s:25ScanbotDocumentScannerSDK25SBSDKProgessUpdateHandlera"},{"kind":"text","text":"?"}],"title":"updateHandler","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress(py)updateHandler","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"updateHandler"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress/updateHandler":{"role":"symbol","title":"updateHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKProgessUpdateHandler","preciseIdentifier":"s:25ScanbotDocumentScannerSDK25SBSDKProgessUpdateHandlera"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The standard process for observing a "},{"type":"codeVoice","code":"Progress"},{"type":"text","text":" progressing is to use KVO on the "},{"type":"codeVoice","code":"Progress"},{"type":"text","text":" instance."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"SBSDKProgressUpdateHandler"},{"type":"text","text":" simplifies observing the progress largely."},{"type":"text","text":" "},{"type":"text","text":"It is called on main thread whenever the progress changes. Usually here you update your UI, e.g. "},{"type":"codeVoice","code":"UIProgressView"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/updateHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateHandler"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress\/updatehandler"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress":{"role":"symbol","title":"SBSDKProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProgress"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKProgress"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgessUpdateHandler":{"role":"symbol","title":"SBSDKProgessUpdateHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProgessUpdateHandler"}],"abstract":[{"type":"text","text":"A closure typealias used on informing observers about progress updating."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgessUpdateHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKProgessUpdateHandler"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogessupdatehandler"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"updateHandler"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"updateHandler"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"void (^)(SBSDKProgress *)","preciseIdentifier":"c:BFv(#*$@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress)"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateHandler"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress~1updateHandler\/title","value":"updateHandler"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress~1updateHandler\/fragments","value":[{"kind":"identifier","text":"updateHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/title","value":"SBSDKProgress"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/fragments","value":[{"kind":"identifier","text":"SBSDKProgress"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}