{"kind":"symbol","metadata":{"title":"SBSDKErrorCode.PDFCreation","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFCreation","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKErrorCodePDFCreation","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKErrorCode@SBSDKErrorCodePDFCreation","roleHeading":"Case"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorCode\/PDFCreation","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDFCreation"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkerrorcode\/pdfcreation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkerrorcode\/pdfcreation"]}],"abstract":[{"type":"text","text":"There was an unknown error while generating a PDF page."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorCode"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorCode":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorCode","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrorcode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKErrorCode"}],"type":"topic","abstract":[{"text":"The error codes in the SBSDKErrorDomain.","type":"text"}],"title":"SBSDKErrorCode","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCode"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorCode/PDFCreation":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodePDFCreation"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDFCreation"}],"abstract":[{"type":"text","text":"There was an unknown error while generating a PDF page."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrorcode\/pdfcreation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorCode\/PDFCreation","title":"SBSDKErrorCode.PDFCreation","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKErrorCodePDFCreation","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorCodePDFCreation"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKErrorCodePDFCreation"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKErrorCode","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorCode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorCode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorCode\/fragments"},{"op":"replace","value":[{"text":"SBSDKErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorCode\/navigatorTitle"},{"op":"replace","value":"SBSDKErrorCodePDFCreation","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorCode~1PDFCreation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorCodePDFCreation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorCode~1PDFCreation\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}