{"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatCommonConfiguration(im)initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:"}],"roleHeading":"Instance Method","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcommonconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:minimumnumberofrequiredframeswithequalrecognitionresult:stripcheckdigits:minimumtextlength:maximumtextlength:gs1handling:strictmode:onedconfirmationmode:form-2puin"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithRegexFilter:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"regexFilter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumSizeScore:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"minimumSizeScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"addAdditionalQuietZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"addAdditionalQuietZone","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimum1DQuietZoneSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"minimum1DQuietZoneSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"stripCheckDigits:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"stripCheckDigits","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumTextLength:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"minimumTextLength","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maximumTextLength:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"maximumTextLength","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"gs1Handling:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGS1Handling","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1Handling"},{"text":") ","kind":"text"},{"text":"gs1Handling","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"strictMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"strictMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"oneDConfirmationMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOneDConfirmationMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKOneDConfirmationMode"},{"text":") ","kind":"text"},{"text":"oneDConfirmationMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"formats:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKBarcodeFormat *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"formats","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCommonConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCommonConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatCommonConfiguration":{"role":"symbol","title":"SBSDKBarcodeFormatCommonConfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCommonConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcommonconfiguration","type":"topic","abstract":[{"type":"text","text":"Convenience configuration for enabling the scanning of multiple barcode formats with a common configuration."},{"type":"text","text":" "},{"type":"text","text":"Add to scanner configuration to enable and configure the scanning of multiple barcodes."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatCommonConfiguration"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatCommonConfiguration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcommonconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:minimumnumberofrequiredframeswithequalrecognitionresult:stripcheckdigits:minimumtextlength:maximumtextlength:gs1handling:strictmode:onedconfirmationmode:form-2puin","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:","kind":"identifier"}],"title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCommonConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:","abstract":[],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOneDConfirmationMode":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode","role":"symbol","title":"SBSDKOneDConfirmationMode","abstract":[{"type":"text","text":"Allows to select the balance between result accuracy (precision) and missed barcodes (recall) for linear barcodes."},{"type":"text","text":" "},{"type":"text","text":"Some barcode types are naturally prone to false positives (e.g. MSI Plessey)."},{"text":" ","type":"text"},{"text":"For those barcode types false positives can be drastically reduced (precision can be increased) by requiring that multiple scan-lines in the input scan to the same result.","type":"text"},{"text":" ","type":"text"},{"text":"However, this stronger condition can lead to missed barcodes (lower recall).","type":"text"},{"text":" ","type":"text"},{"text":"Confirmation is avoided for barcode types, which are by design resistant to false positives, (e.g. Code128) to maximize recall.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling":{"abstract":[{"text":"GS1 message handling options.","type":"text"},{"text":" ","type":"text"},{"text":"The GS1 standard defines a key-value format for business-centric data that can be encoded into many 1D and 2D barcode types.","type":"text"},{"text":" ","type":"text"},{"text":"https:\/\/ref.gs1.org\/standards\/genspecs\/","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGS1Handling"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"title":"SBSDKGS1Handling","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKBarcodeFormatCommonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCommonConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCommonConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCommonConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKOneDConfirmationMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOneDConfirmationMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode\/fragments"},{"op":"replace","value":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode\/navigatorTitle"},{"op":"replace","value":"SBSDKGS1Handling","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/title"},{"op":"replace","value":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/fragments"},{"op":"replace","value":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}