{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscanner\/cleanrecognitionqueue()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscanner\/cleanrecognitionqueue()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanRecognitionQueue"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScanner"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScanner(im)cleanRecognitionQueue","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cleanRecognitionQueue","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"cleanRecognitionQueue","kind":"identifier"}],"title":"cleanRecognitionQueue()"},"kind":"symbol","abstract":[{"text":"Clean the queue of recognize text lines.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScanner\/cleanRecognitionQueue()","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScanner/cleanRecognitionQueue()":{"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscanner\/cleanrecognitionqueue()","role":"symbol","title":"cleanRecognitionQueue()","abstract":[{"type":"text","text":"Clean the queue of recognize text lines."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cleanRecognitionQueue","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScanner\/cleanRecognitionQueue()","navigatorTitle":[{"text":"cleanRecognitionQueue","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScanner":{"abstract":[{"type":"text","text":"API for text pattern scanning."}],"role":"symbol","title":"SBSDKTextPatternScanner","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScanner","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScanner"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTextPatternScanner"}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscanner"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"cleanRecognitionQueue"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cleanRecognitionQueue","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"cleanRecognitionQueue","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner~1cleanRecognitionQueue()\/title","op":"replace","value":"cleanRecognitionQueue"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner~1cleanRecognitionQueue()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cleanRecognitionQueue"}]},{"op":"replace","value":"SBSDKTextPatternScanner","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner\/title"},{"op":"replace","value":[{"text":"SBSDKTextPatternScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner\/fragments"},{"op":"replace","value":[{"text":"SBSDKTextPatternScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}