{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerCancelButtonItem(_:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerCancelButtonItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"editingViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageEditingViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBarButtonItem","text":"UIBarButtonItem","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"editingViewController","content":[{"inlineContent":[{"text":"He calling SBSDKImageEditingViewController.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UIBarButtonItem"},{"text":" for cancelling the editing.","type":"text"}]}],"kind":"content"}],"sections":[],"metadata":{"required":true,"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKImageEditingViewControllerDelegate(im)imageEditingViewControllerCancelButtonItem:","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerCancelButtonItem:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"imageEditingViewControllerCancelButtonItem","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"title":"imageEditingViewControllerCancelButtonItem(_:)"},"abstract":[{"type":"text","text":"Asks the delegate for a "},{"type":"codeVoice","code":"UIBarButtonItem"},{"text":" to cancel the actual editing.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollercancelbuttonitem(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollercancelbuttonitem(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","type":"topic","navigatorTitle":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"title":"SBSDKImageEditingViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller","abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to show and edit an image.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate","type":"topic","navigatorTitle":[{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"title":"SBSDKImageEditingViewControllerDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate","abstract":[{"text":"A delegate protocol to inform an object about changes in ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","type":"reference"},{"text":".","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerCancelButtonItem(_:)":{"title":"imageEditingViewControllerCancelButtonItem(_:)","kind":"symbol","required":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerCancelButtonItem(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerCancelButtonItem:"}],"abstract":[{"text":"Asks the delegate for a ","type":"text"},{"code":"UIBarButtonItem","type":"codeVoice"},{"type":"text","text":" to cancel the actual editing."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageEditingViewControllerCancelButtonItem","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UIBarButtonItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollercancelbuttonitem(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"imageEditingViewControllerCancelButtonItem:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageEditingViewControllerCancelButtonItem:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)UIBarButtonItem","text":"UIBarButtonItem","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"imageEditingViewControllerCancelButtonItem:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController"},{"text":" *) ","kind":"text"},{"text":"editingViewController","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"He calling SBSDKImageEditingViewController."}],"type":"paragraph"}],"name":"editingViewController"}]}},{"value":{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UIBarButtonItem"},{"type":"text","text":" for cancelling the editing."}],"type":"paragraph"}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"op":"replace","value":"SBSDKImageEditingViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/title"},{"value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/navigatorTitle","value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}]},{"value":"SBSDKImageEditingViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate\/title","op":"replace"},{"value":[{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerCancelButtonItem(_:)\/title","op":"replace","value":"imageEditingViewControllerCancelButtonItem:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerCancelButtonItem:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerCancelButtonItem(_:)\/fragments","op":"replace"}]}]}