{"abstract":[{"text":"Which mode to use when orientation should be locked to landscape or portrait.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is NONE"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraConfiguration\/orientationLockMode","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraConfiguration"]]},"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientationLockMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2OrientationLockMode","text":"SBSDKUI2OrientationLockMode"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2CameraConfiguration(py)orientationLockMode","role":"symbol","title":"orientationLockMode","navigatorTitle":[{"text":"orientationLockMode","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientationLockMode"},{"kind":"text","text":": "},{"text":"SBSDKUI2OrientationLockMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2OrientationLockMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2OrientationLockMode","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameraconfiguration\/orientationlockmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameraconfiguration\/orientationlockmode"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraConfiguration":{"kind":"symbol","title":"SBSDKUI2CameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraConfiguration","abstract":[{"text":"Configuration of the camera settings to be used while scanning.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameraconfiguration","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2OrientationLockMode":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2orientationlockmode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2OrientationLockMode","title":"SBSDKUI2OrientationLockMode","kind":"symbol","type":"topic","abstract":[{"text":"Configure the orientation of the interface.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraConfiguration/orientationLockMode":{"navigatorTitle":[{"text":"orientationLockMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Which mode to use when orientation should be locked to landscape or portrait."},{"type":"text","text":" "},{"type":"text","text":"Default is NONE"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameraconfiguration\/orientationlockmode","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationLockMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2OrientationLockMode","kind":"typeIdentifier","text":"SBSDKUI2OrientationLockMode"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraConfiguration\/orientationLockMode","title":"orientationLockMode","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"orientationLockMode"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"orientationLockMode"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2OrientationLockMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2OrientationLockMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2OrientationLockMode","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientationLockMode"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"SBSDKUI2CameraConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}]},{"op":"replace","value":"SBSDKUI2OrientationLockMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2OrientationLockMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2OrientationLockMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2OrientationLockMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraConfiguration~1orientationLockMode\/title","value":"orientationLockMode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraConfiguration~1orientationLockMode\/fragments","value":[{"text":"orientationLockMode","kind":"identifier"}]}]}]}