{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEventFactory\/importedImageQualityResult"},"metadata":{"roleHeading":"Type Property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsEventFactory(cpy)importedImageQualityResult","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"importedImageQualityResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsEvent","text":"SBSDKAnalyticsEvent"}],"title":"importedImageQualityResult","navigatorTitle":[{"text":"importedImageQualityResult","kind":"identifier"}],"role":"symbol","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"importedImageQualityResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKAnalyticsEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsEvent","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEvent"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEventFactory"]]},"abstract":[{"type":"text","text":"A predefined analytics event."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkanalyticseventfactory\/importedimagequalityresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkanalyticseventfactory\/importedimagequalityresult"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsEventFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsEventFactory","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEventFactory","abstract":[{"text":"A predefined analytics event.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkanalyticseventfactory","title":"SBSDKAnalyticsEventFactory","navigatorTitle":[{"text":"SBSDKAnalyticsEventFactory","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsEvent":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkanalyticsevent","abstract":[{"text":"The event that is being tracked.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEvent","kind":"symbol","title":"SBSDKAnalyticsEvent","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsEvent","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKAnalyticsEvent","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsEventFactory/importedImageQualityResult":{"type":"topic","abstract":[{"type":"text","text":"A predefined analytics event."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEventFactory\/importedImageQualityResult","title":"importedImageQualityResult","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"importedImageQualityResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsEvent","text":"SBSDKAnalyticsEvent"}],"url":"\/documentation\/scanbotsdk\/sbsdkanalyticseventfactory\/importedimagequalityresult","navigatorTitle":[{"kind":"identifier","text":"importedImageQualityResult"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"importedImageQualityResult","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"importedImageQualityResult"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKAnalyticsEvent","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEvent","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsEvent"},{"text":" * ","kind":"text"},{"text":"importedImageQualityResult","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKAnalyticsEventFactory","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEventFactory\/title"},{"value":[{"text":"SBSDKAnalyticsEventFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEventFactory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEventFactory\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAnalyticsEventFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEvent\/title","value":"SBSDKAnalyticsEvent"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEvent\/fragments","value":[{"kind":"identifier","text":"SBSDKAnalyticsEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEvent\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAnalyticsEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEventFactory~1importedImageQualityResult\/title","value":"importedImageQualityResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEventFactory~1importedImageQualityResult\/fragments","value":[{"text":"importedImageQualityResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}