{"sections":[],"abstract":[{"type":"text","text":"A predefined analytics event."}],"metadata":{"navigatorTitle":[{"text":"retakeImage","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"retakeImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKAnalyticsEvent","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsEvent"}],"roleHeading":"Type Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsEventFactory(cpy)retakeImage","title":"retakeImage"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEventFactory\/retakeImage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEventFactory"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retakeImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKAnalyticsEvent","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEvent","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsEvent","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkanalyticseventfactory\/retakeimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkanalyticseventfactory\/retakeimage"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsEventFactory":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEventFactory","title":"SBSDKAnalyticsEventFactory","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsEventFactory","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKAnalyticsEventFactory","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkanalyticseventfactory","type":"topic","abstract":[{"type":"text","text":"A predefined analytics event."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsEventFactory/retakeImage":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A predefined analytics event."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEventFactory\/retakeImage","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retakeImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKAnalyticsEvent","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsEvent","kind":"typeIdentifier"}],"title":"retakeImage","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkanalyticseventfactory\/retakeimage","navigatorTitle":[{"text":"retakeImage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsEvent":{"abstract":[{"text":"The event that is being tracked.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAnalyticsEvent"}],"url":"\/documentation\/scanbotsdk\/sbsdkanalyticsevent","type":"topic","title":"SBSDKAnalyticsEvent","navigatorTitle":[{"kind":"identifier","text":"SBSDKAnalyticsEvent"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"retakeImage","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"retakeImage","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEvent","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsEvent","text":"SBSDKAnalyticsEvent"},{"kind":"text","text":" * "},{"kind":"identifier","text":"retakeImage"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEventFactory\/title","value":"SBSDKAnalyticsEventFactory","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEventFactory\/fragments","value":[{"text":"SBSDKAnalyticsEventFactory","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAnalyticsEventFactory"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEventFactory\/navigatorTitle"},{"value":"retakeImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEventFactory~1retakeImage\/title"},{"value":[{"text":"retakeImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEventFactory~1retakeImage\/fragments","op":"replace"},{"value":"SBSDKAnalyticsEvent","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEvent\/title","op":"replace"},{"value":[{"text":"SBSDKAnalyticsEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEvent\/fragments","op":"replace"},{"value":[{"text":"SBSDKAnalyticsEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEvent\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}