{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"ok_BadAngles","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectionStatus@SBSDKDocumentDetectionStatusOk_BadAngles","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ok_BadAngles","kind":"identifier"}],"role":"symbol","title":"SBSDKDocumentDetectionStatus.ok_BadAngles","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk_BadAngles"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/ok_badangles"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/ok_badangles"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok_BadAngles","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A polygon was detected, but it has too much perspective distortion."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus","abstract":[{"text":"The status of the latest document detection.","type":"text"}],"title":"SBSDKDocumentDetectionStatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/ok_BadAngles":{"navigatorTitle":[{"text":"SBSDKDocumentDetectionStatusOk_BadAngles","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/ok_badangles","abstract":[{"type":"text","text":"A polygon was detected, but it has too much perspective distortion."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ok_BadAngles","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok_BadAngles","title":"SBSDKDocumentDetectionStatus.ok_BadAngles","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKDocumentDetectionStatusOk_BadAngles"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk_BadAngles"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKDocumentDetectionStatusOk_BadAngles","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/title","value":"SBSDKDocumentDetectionStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}]},{"value":"SBSDKDocumentDetectionStatusOk_BadAngles","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1ok_BadAngles\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1ok_BadAngles\/fragments","value":[{"text":"SBSDKDocumentDetectionStatusOk_BadAngles","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}