{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Case","title":"SBSDKDocumentDetectionStatus.ok_OffCenter","externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectionStatus@SBSDKDocumentDetectionStatusOk_OffCenter","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ok_OffCenter","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatusOk_OffCenter","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case"},"sections":[],"abstract":[{"type":"text","text":"A polygon was detected, but its center is too far away from the image center."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok_OffCenter","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/ok_offcenter"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/ok_offcenter"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ok_OffCenter","kind":"identifier"}]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/ok_OffCenter":{"role":"symbol","abstract":[{"text":"A polygon was detected, but its center is too far away from the image center.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok_OffCenter","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/ok_offcenter","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk_OffCenter"}],"title":"SBSDKDocumentDetectionStatus.ok_OffCenter","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ok_OffCenter","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus":{"navigatorTitle":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus","role":"symbol","title":"SBSDKDocumentDetectionStatus","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus","abstract":[{"type":"text","text":"The status of the latest document detection."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"SBSDKDocumentDetectionStatusOk_OffCenter","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk_OffCenter"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKDocumentDetectionStatusOk_OffCenter","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1ok_OffCenter\/title","value":"SBSDKDocumentDetectionStatusOk_OffCenter"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1ok_OffCenter\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk_OffCenter"}],"op":"replace"},{"value":"SBSDKDocumentDetectionStatus","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}