{"metadata":{"title":"SBSDKDocumentDetectionStatus.okButBadAspectRatio","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectionStatus@SBSDKDocumentDetectionStatusOkButBadAspectRatio","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"okButBadAspectRatio"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButBadAspectRatio"}],"symbolKind":"case"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus"]]},"abstract":[{"type":"text","text":"A document has been detected but it has a bad aspect ratio."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/okbutbadaspectratio"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/okbutbadaspectratio"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButBadAspectRatio","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"okButBadAspectRatio","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"title":"SBSDKDocumentDetectionStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus","abstract":[{"type":"text","text":"The status of the document detection."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/okButBadAspectRatio":{"navigatorTitle":[{"text":"SBSDKDocumentDetectionStatusOkButBadAspectRatio","kind":"identifier"}],"title":"SBSDKDocumentDetectionStatus.okButBadAspectRatio","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"okButBadAspectRatio","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButBadAspectRatio","abstract":[{"text":"A document has been detected but it has a bad aspect ratio.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/okbutbadaspectratio"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"SBSDKDocumentDetectionStatusOkButBadAspectRatio","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"text":"SBSDKDocumentDetectionStatusOkButBadAspectRatio","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButBadAspectRatio"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKDocumentDetectionStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButBadAspectRatio\/title","value":"SBSDKDocumentDetectionStatusOkButBadAspectRatio"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButBadAspectRatio\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButBadAspectRatio"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}