{"metadata":{"role":"symbol","roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZParserConfiguration(cm)fromJsonWithJson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"modules":[{"name":"ScanbotSDK"}],"title":"fromJsonWithJson:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZParserConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmrzparserconfiguration\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZParserConfiguration\/fromJsonWithJson:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZParserConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZParserConfiguration","text":"SBSDKMRZParserConfiguration"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromJsonWithJson:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}]}]}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZParserConfiguration/fromJsonWithJson:":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZParserConfiguration\/fromJsonWithJson:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzparserconfiguration\/fromjsonwithjson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZParserConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZParserConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZParserConfiguration"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZParserConfiguration"}],"title":"SBSDKMRZParserConfiguration","abstract":[{"type":"text","text":"Configuration for MRZ parser."}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzparserconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZParserConfiguration\/title","value":"SBSDKMRZParserConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZParserConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKMRZParserConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZParserConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMRZParserConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}