{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithIncompleteResultHandling:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMRZIncompleteResultHandling","text":"SBSDKMRZIncompleteResultHandling","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"incompleteResultHandling","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmrzparserconfiguration\/initwithincompleteresulthandling:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZParserConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZParserConfiguration\/initWithIncompleteResultHandling:","interfaceLanguage":"occ"},"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithIncompleteResultHandling:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZParserConfiguration(im)initWithIncompleteResultHandling:","symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithIncompleteResultHandling:","kind":"identifier"}],"title":"initWithIncompleteResultHandling:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZIncompleteResultHandling":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzincompleteresulthandling","title":"SBSDKMRZIncompleteResultHandling","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}],"abstract":[{"type":"text","text":"Defines how to handle incomplete MRZ results (e.g. caused by failed validation)."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZParserConfiguration/initWithIncompleteResultHandling:":{"type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithIncompleteResultHandling:"}],"title":"initWithIncompleteResultHandling:","navigatorTitle":[{"kind":"identifier","text":"initWithIncompleteResultHandling:"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzparserconfiguration\/initwithincompleteresulthandling:","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZParserConfiguration\/initWithIncompleteResultHandling:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZParserConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZParserConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZParserConfiguration"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZParserConfiguration"}],"title":"SBSDKMRZParserConfiguration","abstract":[{"type":"text","text":"Configuration for MRZ parser."}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzparserconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/title","value":"SBSDKMRZIncompleteResultHandling"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/fragments","value":[{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/navigatorTitle","value":[{"text":"SBSDKMRZIncompleteResultHandling","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZParserConfiguration\/title","value":"SBSDKMRZParserConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZParserConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKMRZParserConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZParserConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMRZParserConfiguration"}]}]}]}