{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UHD","kind":"identifier"}]}]}],"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKVideoFrameResolution@SBSDKVideoFrameResolutionUHD","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"SBSDKVideoFrameResolution.UHD","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UHD"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionUHD"}],"roleHeading":"Case","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/uhd"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/uhd"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/UHD","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Select a 4k UHD (3840x2160) video resolution."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFrameResolution/UHD":{"title":"SBSDKVideoFrameResolution.UHD","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/uhd","abstract":[{"type":"text","text":"Select a 4k UHD (3840x2160) video resolution."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/UHD","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UHD","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKVideoFrameResolutionUHD","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFrameResolution":{"title":"SBSDKVideoFrameResolution","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution","abstract":[{"type":"text","text":"An enum describing the resolution of a video or camera stream."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKVideoFrameResolutionUHD","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKVideoFrameResolutionUHD","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKVideoFrameResolutionUHD","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution~1UHD\/title","value":"SBSDKVideoFrameResolutionUHD"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution~1UHD\/fragments","value":[{"text":"SBSDKVideoFrameResolutionUHD","kind":"identifier"}]},{"value":"SBSDKVideoFrameResolution","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution\/title"},{"value":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution\/navigatorTitle"}]}]}