{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"init","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorTextConfiguration(im)init","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorTextConfiguration\/init"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorTextConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractortextconfiguration\/init"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorTextConfiguration/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorTextConfiguration\/init","title":"init","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractortextconfiguration\/init"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorTextConfiguration":{"role":"symbol","title":"SBSDKUIDocumentDataExtractorTextConfiguration","abstract":[{"text":"The configuration for the textual contents of the RTU-UI document data extractor screen.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUIDocumentDataExtractorTextConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractortextconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorTextConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentDataExtractorTextConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorTextConfiguration\/title","value":"SBSDKUIDocumentDataExtractorTextConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorTextConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorTextConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorTextConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorTextConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}