{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatdatabarexpandedconfiguration\/new"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"new"},{"kind":"text","text":";"}]}]}],"sections":[],"kind":"symbol","metadata":{"title":"new","navigatorTitle":[{"kind":"identifier","text":"new"}],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"new"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatDataBarExpandedConfiguration(cm)new","roleHeading":"Type Method","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatDataBarExpandedConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatDataBarExpandedConfiguration\/new","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatDataBarExpandedConfiguration/new":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatDataBarExpandedConfiguration\/new","role":"symbol","kind":"symbol","title":"new","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatdatabarexpandedconfiguration\/new","navigatorTitle":[{"text":"new","kind":"identifier"}],"abstract":[],"fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatDataBarExpandedConfiguration":{"type":"topic","abstract":[{"text":"GS1 DataBar Expanded barcode configuration. Add to scanner configuration to scan GS1 DataBar Expanded and GS1","type":"text"},{"text":" ","type":"text"},{"text":"DataBar Expanded Stacked barcodes.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatDataBarExpandedConfiguration","kind":"identifier"}],"title":"SBSDKBarcodeFormatDataBarExpandedConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatdatabarexpandedconfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatDataBarExpandedConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatDataBarExpandedConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatDataBarExpandedConfiguration\/title","op":"replace","value":"SBSDKBarcodeFormatDataBarExpandedConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatDataBarExpandedConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatDataBarExpandedConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatDataBarExpandedConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormatDataBarExpandedConfiguration","kind":"identifier"}]}]}]}