{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconUserGuidanceConfiguration"]]},"kind":"symbol","metadata":{"title":"copyWithZone:","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconUserGuidanceConfiguration(im)copyWithZone:","modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"_NSZone","preciseIdentifier":"c:@S@_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconUserGuidanceConfiguration\/copyWithZone:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2iconuserguidanceconfiguration\/copywithzone:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconUserGuidanceConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconUserGuidanceConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IconUserGuidanceConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IconUserGuidanceConfiguration"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2iconuserguidanceconfiguration","abstract":[{"type":"text","text":"Configuration of the hint (containing an icon) guiding users through the scanning process."}],"title":"SBSDKUI2IconUserGuidanceConfiguration","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconUserGuidanceConfiguration/copyWithZone:":{"abstract":[],"type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2iconuserguidanceconfiguration\/copywithzone:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"title":"copyWithZone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconUserGuidanceConfiguration\/copyWithZone:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2IconUserGuidanceConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconUserGuidanceConfiguration\/title"},{"value":[{"text":"SBSDKUI2IconUserGuidanceConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconUserGuidanceConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2IconUserGuidanceConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconUserGuidanceConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}