{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationConfiguration"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithMinConfirmationsStandaloneEAN:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"minConfirmationsStandaloneEAN","kind":"internalParam"},{"kind":"text","text":" "},{"text":"accumulationTime:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"accumulationTime","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeUnconnectedResults:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"removeUnconnectedResults","kind":"internalParam"},{"kind":"text","text":" "},{"text":"method:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeAccumulationMethod","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeAccumulationMethod","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod"},{"kind":"text","text":") "},{"kind":"internalParam","text":"method"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationConfiguration\/initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationconfiguration\/initwithminconfirmationsstandaloneean:accumulationtime:removeunconnectedresults:method:"]}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeAccumulationConfiguration(im)initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:","kind":"identifier"}],"title":"initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:"}],"modules":[{"name":"ScanbotSDK"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAccumulationConfiguration":{"kind":"symbol","title":"SBSDKBarcodeAccumulationConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeAccumulationConfiguration"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationConfiguration"}],"abstract":[{"text":"Configuration for how to accumulate results.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAccumulationMethod":{"kind":"symbol","title":"SBSDKBarcodeAccumulationMethod","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"}],"abstract":[{"text":"The method how to display barcodes from previous frames.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAccumulationConfiguration/initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationConfiguration\/initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:","navigatorTitle":[{"text":"initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationconfiguration\/initwithminconfirmationsstandaloneean:accumulationtime:removeunconnectedresults:method:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:","kind":"identifier"}],"title":"initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:","abstract":[],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationConfiguration\/title","value":"SBSDKBarcodeAccumulationConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod\/title","value":"SBSDKBarcodeAccumulationMethod"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"}],"op":"replace"},{"value":[{"text":"SBSDKBarcodeAccumulationMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod\/navigatorTitle","op":"replace"}]}]}