{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode\/portrait"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode\/portrait"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2OrientationLockModePortrait"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","title":"SBSDKUI2OrientationLockMode.portrait","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"portrait"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2OrientationLockMode@SBSDKUI2OrientationLockModePortrait","symbolKind":"case","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"portrait","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Lock the orientation to portrait.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/portrait"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2OrientationLockMode/portrait":{"kind":"symbol","abstract":[{"type":"text","text":"Lock the orientation to portrait."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/portrait","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"portrait","kind":"identifier"}],"title":"SBSDKUI2OrientationLockMode.portrait","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2OrientationLockModePortrait"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode\/portrait"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2OrientationLockMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode","title":"SBSDKUI2OrientationLockMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode","abstract":[{"type":"text","text":"Configure the orientation of the interface."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKUI2OrientationLockModePortrait","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"SBSDKUI2OrientationLockModePortrait","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKUI2OrientationLockModePortrait"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode~1portrait\/title","value":"SBSDKUI2OrientationLockModePortrait"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode~1portrait\/fragments","value":[{"text":"SBSDKUI2OrientationLockModePortrait","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2OrientationLockMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}]}]}]}