{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration"]]},"metadata":{"title":"isViewFinderEnabled","roleHeading":"Instance Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"platforms":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isViewFinderEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isViewFinderEnabled"}],"symbolKind":"property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodesBatchScannerBehaviorConfiguration(py)isViewFinderEnabled"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/isViewFinderEnabled"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration\/isviewfinderenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration\/isviewfinderenabled"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isViewFinderEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":" to enable and display the region of interest, to "},{"code":"false","type":"codeVoice"},{"type":"text","text":" otherwise."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerBehaviorConfiguration":{"kind":"symbol","abstract":[{"type":"text","text":"The configuration for the behavior of RTU-UI scanner screens for barcodes."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration","role":"symbol","deprecated":true,"title":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerBehaviorConfiguration/isViewFinderEnabled":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/isViewFinderEnabled","role":"symbol","deprecated":true,"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isViewFinderEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","title":"isViewFinderEnabled","abstract":[{"type":"text","text":"Set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":" to enable and display the region of interest, to "},{"code":"false","type":"codeVoice"},{"type":"text","text":" otherwise."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration\/isviewfinderenabled","navigatorTitle":[{"kind":"identifier","text":"isViewFinderEnabled"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"isViewFinderEnabled"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"isViewFinderEnabled"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isViewFinderEnabled","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/title","op":"replace","value":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration~1isViewFinderEnabled\/title","value":"isViewFinderEnabled"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration~1isViewFinderEnabled\/fragments","value":[{"text":"isViewFinderEnabled","kind":"identifier"}]}]}]}