{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshot\/hash","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshot"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagerefpoolsnapshot\/hash"]}],"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"hash"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot(py)hash","role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"hash"}],"title":"hash"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefPoolSnapshot":{"url":"\/documentation\/scanbotsdk\/sbsdkimagerefpoolsnapshot","title":"SBSDKImageRefPoolSnapshot","kind":"symbol","abstract":[{"type":"text","text":"Snapshot of all alive ImageRefs."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshot"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefPoolSnapshot/hash":{"type":"topic","title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkimagerefpoolsnapshot\/hash","fragments":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshot\/hash","abstract":[],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKImageRefPoolSnapshot","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefPoolSnapshot\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefPoolSnapshot\/fragments","value":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}],"op":"replace"},{"value":[{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefPoolSnapshot\/navigatorTitle"}]}]}