{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerIntroImage(cm)textPatternIntroMeterDevice","navigatorTitle":[{"text":"textPatternIntroMeterDevice","kind":"identifier"}],"role":"symbol","title":"textPatternIntroMeterDevice()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textPatternIntroMeterDevice","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKUI2TextPatternIntroMeterDevice","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternIntroMeterDevice","kind":"typeIdentifier"}],"roleHeading":"Type Method","symbolKind":"method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroImage\/textPatternIntroMeterDevice()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textPatternIntroMeterDevice"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroMeterDevice","text":"SBSDKUI2TextPatternIntroMeterDevice","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternIntroMeterDevice"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroImage"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroimage\/textpatternintrometerdevice()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroimage\/textpatternintrometerdevice()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerIntroImage/textPatternIntroMeterDevice()":{"abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroimage\/textpatternintrometerdevice()","role":"symbol","navigatorTitle":[{"text":"textPatternIntroMeterDevice","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroImage\/textPatternIntroMeterDevice()","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textPatternIntroMeterDevice","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKUI2TextPatternIntroMeterDevice","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternIntroMeterDevice","kind":"typeIdentifier"}],"title":"textPatternIntroMeterDevice()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternIntroMeterDevice":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroMeterDevice","type":"topic","abstract":[{"text":"The image for the introduction screen featuring an electricity meter.","type":"text"}],"title":"SBSDKUI2TextPatternIntroMeterDevice","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternIntroMeterDevice"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextPatternIntroMeterDevice"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternintrometerdevice"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerIntroImage":{"role":"symbol","abstract":[{"type":"text","text":"The image for the introduction screen of a generic text scanner screen."}],"title":"SBSDKUI2TextPatternScannerIntroImage","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextPatternScannerIntroImage"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroimage","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerIntroImage"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroImage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"textPatternIntroMeterDevice"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"textPatternIntroMeterDevice"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2TextPatternIntroMeterDevice","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroMeterDevice","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternIntroMeterDevice"},{"text":" *) ","kind":"text"},{"text":"textPatternIntroMeterDevice","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroImage~1textPatternIntroMeterDevice()\/title","value":"textPatternIntroMeterDevice"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroImage~1textPatternIntroMeterDevice()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"textPatternIntroMeterDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroMeterDevice\/title","value":"SBSDKUI2TextPatternIntroMeterDevice"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroMeterDevice\/fragments","value":[{"text":"SBSDKUI2TextPatternIntroMeterDevice","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroMeterDevice\/navigatorTitle","value":[{"text":"SBSDKUI2TextPatternIntroMeterDevice","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroImage\/title","value":"SBSDKUI2TextPatternScannerIntroImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroImage\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerIntroImage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroImage\/navigatorTitle","value":[{"text":"SBSDKUI2TextPatternScannerIntroImage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}