{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter\/init(mode:keyProvider:authenticationTag:perFileEncryption:)"},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAESEncrypterMode","text":"SBSDKAESEncrypterMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keyProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider","kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationTag"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"perFileEncryption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAESGCMEncrypter(im)initWithKeyProvider:mode:authenticationData:perFileEncryption:","navigatorTitle":[{"kind":"identifier","text":"initWithKeyProvider:mode:authenticationData:perFileEncryption:"}],"roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"title":"init(mode:keyProvider:authenticationTag:perFileEncryption:)","symbolKind":"init","role":"symbol"},"abstract":[{"type":"text","text":"Required initializer."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithKeyProvider:mode:authenticationData:perFileEncryption:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKAESEncrypterMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAESEncrypterMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"keyProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyProvider","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"authenticationTag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"perFileEncryption","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = true)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"mode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The value of  "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode","isActive":true,"type":"reference"},{"type":"text","text":" that specifies the AES encryption mode to be used."}]}]},{"name":"keyProvider","content":[{"type":"paragraph","inlineContent":[{"text":"The key provider that will provide the encryption\/decryption keys.","type":"text"}]}]},{"name":"authenticationTag","content":[{"inlineContent":[{"text":"The data block to be used for GCM authentication. Can be nil, if authentication should not be used.","type":"text"}],"type":"paragraph"}]},{"name":"perFileEncryption","content":[{"inlineContent":[{"type":"text","text":"If "},{"type":"codeVoice","code":"true"},{"type":"text","text":", each file is encrypted with a different key."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Creates a new AES encrypter\/decrypter with either AES128 GCM or AES256 GCM encryption."},{"type":"text","text":" "},{"type":"text","text":"The encryption\/decryption key is derived by the passed "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider","type":"reference","isActive":true},{"type":"text","text":"."}]}],"kind":"content"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter\/init(mode:keyprovider:authenticationtag:perfileencryption:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter\/init(mode:keyprovider:authenticationtag:perfileencryption:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESGCMEncrypter":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"type":"topic","title":"SBSDKAESGCMEncrypter","abstract":[{"text":"A data encrypter implementing the AES128-GCM and AES256-GCM standards, with a configurable encryption key provider.","type":"text"},{"text":" ","type":"text"},{"text":"Supports encryption and decryption of single data blocks as well as streaming data.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter","url":"\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypter":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkaesencrypter","navigatorTitle":[{"kind":"identifier","text":"SBSDKAESEncrypter"}],"title":"SBSDKAESEncrypter","abstract":[{"type":"text","text":"ScanbotSDK’s default data encrypter. Provides AES128 and AES 256 encryption to your data."},{"type":"text","text":" "},{"type":"text","text":"All data is encrypted and decrypted with the same key."},{"type":"text","text":" "},{"type":"text","text":"The context being passed to the encrypt\/decrypt methods is ignored."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAESEncrypter"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypterMode":{"abstract":[{"text":"An enum containing the available encryption modes for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAESEncrypterMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode","title":"SBSDKAESEncrypterMode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKAESEncrypterMode"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkaesencryptermode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESGCMEncrypter/init(mode:keyProvider:authenticationTag:perFileEncryption:)":{"abstract":[{"type":"text","text":"Required initializer."}],"url":"\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter\/init(mode:keyprovider:authenticationtag:perfileencryption:)","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter\/init(mode:keyProvider:authenticationTag:perFileEncryption:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKAESEncrypterMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAESEncrypterMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keyProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyProvider","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationTag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"perFileEncryption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithKeyProvider:mode:authenticationData:perFileEncryption:"}],"title":"init(mode:keyProvider:authenticationTag:perFileEncryption:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyProvider":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider","abstract":[{"text":"Protocol for loading, storing and providing encryption keys.","type":"text"},{"text":" ","type":"text"},{"text":"The context parameter is used to distinguish between different encryption contexts.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeyprovider","title":"SBSDKStorageCryptingKeyProvider","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithKeyProvider:mode:authenticationData:perFileEncryption:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKeyProvider:mode:authenticationData:perFileEncryption:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithKeyProvider:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAESEncrypterMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAESEncrypterMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"mode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SBSDKStorageCryptingKeyProvider>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"keyProvider","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"authenticationData:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"authenticationTag","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"perFileEncryption:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"perFileEncryption","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"mode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The value of  "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode","isActive":true},{"type":"text","text":" that specifies the AES encryption mode to be used."}]}]},{"name":"keyProvider","content":[{"type":"paragraph","inlineContent":[{"text":"The key provider that will provide the encryption\/decryption keys.","type":"text"}]}]},{"name":"authenticationTag","content":[{"type":"paragraph","inlineContent":[{"text":"The data block to be used for GCM authentication. Can be nil, if authentication should not be used.","type":"text"}]}]},{"name":"perFileEncryption","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"type":"codeVoice","code":"true"},{"type":"text","text":", each file is encrypted with a different key."}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"SBSDKAESGCMEncrypter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter\/navigatorTitle","op":"replace"},{"value":"SBSDKAESEncrypter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/title","op":"replace"},{"value":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAESEncrypter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/navigatorTitle","op":"replace"},{"value":"SBSDKAESEncrypterMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypterMode\/title","op":"replace"},{"value":[{"text":"SBSDKAESEncrypterMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypterMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAESEncrypterMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypterMode\/navigatorTitle","op":"replace"},{"value":"initWithKeyProvider:mode:authenticationData:perFileEncryption:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter~1init(mode:keyProvider:authenticationTag:perFileEncryption:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithKeyProvider:mode:authenticationData:perFileEncryption:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter~1init(mode:keyProvider:authenticationTag:perFileEncryption:)\/fragments","op":"replace"},{"value":"SBSDKStorageCryptingKeyProvider","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/fragments","op":"replace"},{"value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/navigatorTitle","op":"replace"}]}]}