{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController"]]},"abstract":[{"type":"text","text":"Designated initializer."}],"metadata":{"roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"init(soundType:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"soundType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKSoundType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKSoundType"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSoundType:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSoundController(im)initWithSoundType:","symbolKind":"init"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdksoundcontroller\/init(soundtype:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdksoundcontroller\/init(soundtype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"soundType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType","text":"SBSDKSoundType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKSoundType"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"soundType","content":[{"inlineContent":[{"text":"The chosen sound type.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/init(soundType:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundController/init(soundType:)":{"navigatorTitle":[{"text":"initWithSoundType:","kind":"identifier"}],"kind":"symbol","title":"init(soundType:)","abstract":[{"type":"text","text":"Designated initializer."}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"soundType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKSoundType","text":"SBSDKSoundType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/init(soundType:)","url":"\/documentation\/scanbotsdk\/sbsdksoundcontroller\/init(soundtype:)","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundController":{"abstract":[{"text":"A class to manage playback of sounds and vibration.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKSoundController"}],"title":"SBSDKSoundController","url":"\/documentation\/scanbotsdk\/sbsdksoundcontroller","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKSoundController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundType":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType","url":"\/documentation\/scanbotsdk\/sbsdksoundtype","type":"topic","kind":"symbol","title":"SBSDKSoundType","navigatorTitle":[{"kind":"identifier","text":"SBSDKSoundType"}],"abstract":[{"type":"text","text":"The sound selection type."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKSoundType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithSoundType:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithSoundType:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSoundType:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKSoundType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKSoundType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"soundType"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"soundType","content":[{"inlineContent":[{"text":"The chosen sound type.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController~1init(soundType:)\/title","value":"initWithSoundType:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController~1init(soundType:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithSoundType:","kind":"identifier"}]},{"value":"SBSDKSoundController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController\/title"},{"op":"replace","value":[{"text":"SBSDKSoundController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKSoundController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundType\/title","value":"SBSDKSoundType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundType\/fragments","value":[{"text":"SBSDKSoundType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundType\/navigatorTitle","op":"replace","value":[{"text":"SBSDKSoundType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}