{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannertextconfiguration\/cameraunavailableexplanationtext"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannertextconfiguration\/cameraunavailableexplanationtext"]}],"metadata":{"platforms":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cameraUnavailableExplanationText","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"cameraUnavailableExplanationText"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerTextConfiguration(py)cameraUnavailableExplanationText","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"cameraUnavailableExplanationText","roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerTextConfiguration\/cameraUnavailableExplanationText","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"String being displayed on the label describing that the app is in split mode and needs to go fullscreen to work with camera.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerTextConfiguration"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2DocumentScannerViewController instead."}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraUnavailableExplanationText","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerTextConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerTextConfiguration"}],"abstract":[{"type":"text","text":"Configuration for the textual contents of the document scanning screen."}],"deprecated":true,"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerTextConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannertextconfiguration","title":"SBSDKUIDocumentScannerTextConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentScannerTextConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerTextConfiguration/cameraUnavailableExplanationText":{"abstract":[{"text":"String being displayed on the label describing that the app is in split mode and needs to go fullscreen to work with camera.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"cameraUnavailableExplanationText","kind":"identifier"}],"kind":"symbol","title":"cameraUnavailableExplanationText","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerTextConfiguration\/cameraUnavailableExplanationText","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannertextconfiguration\/cameraunavailableexplanationtext","deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cameraUnavailableExplanationText","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"cameraUnavailableExplanationText","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"cameraUnavailableExplanationText","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"cameraUnavailableExplanationText"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKUIDocumentScannerTextConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerTextConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerTextConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUIDocumentScannerTextConfiguration","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerTextConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerTextConfiguration\/navigatorTitle"},{"value":"cameraUnavailableExplanationText","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerTextConfiguration~1cameraUnavailableExplanationText\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerTextConfiguration~1cameraUnavailableExplanationText\/fragments","value":[{"kind":"identifier","text":"cameraUnavailableExplanationText"}],"op":"replace"}]}]}