{"metadata":{"title":"recognize(from:)","modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"SBSDKOCRResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult"}],"symbolKind":"method","externalID":"s:10ScanbotSDK14SBSDKOCREngineC9recognize4fromAA14SBSDKOCRResultCAA13SBSDKDocumentC_tYaKF"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngine\/recognize(from:)-21uby","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkocrengine\/recognize(from:)-21uby"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@nonobjc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","text":"SBSDKDocument"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResult","text":"SBSDKOCRResult"}]}]},{"kind":"parameters","parameters":[{"name":"document","content":[{"type":"paragraph","inlineContent":[{"text":"The document containing the pages to run the optical character recognition on.","type":"text"}]}]}]},{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The OCR result object."}]}],"kind":"content"},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"In Swift language it is used with structured concurrency (async\/await).","type":"text"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngine"]]},"abstract":[{"type":"text","text":"Asynchronously recognizes characters on all pages of the document and returns the result, or throws an error otherwise."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResult":{"url":"\/documentation\/scanbotsdk\/sbsdkocrresult","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCRResult"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKOCRResult"}],"type":"topic","abstract":[{"text":"The result of an optical character recognition.","type":"text"}],"title":"SBSDKOCRResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngine":{"url":"\/documentation\/scanbotsdk\/sbsdkocrengine","type":"topic","abstract":[{"type":"text","text":"A class to perform optical character recognition (text) on an image (OCR)."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCREngine"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngine","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCREngine"}],"title":"SBSDKOCREngine"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngine/recognize(from:)-21uby":{"url":"\/documentation\/scanbotsdk\/sbsdkocrengine\/recognize(from:)-21uby","type":"topic","title":"recognize(from:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngine\/recognize(from:)-21uby","abstract":[{"type":"text","text":"Asynchronously recognizes characters on all pages of the document and returns the result, or throws an error otherwise."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"SBSDKOCRResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"}],"title":"SBSDKDocumentPage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocument":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocument"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocument","abstract":[{"text":"A thread-safe, mutable container for scanned pages of type ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","isActive":true},{"text":".","type":"text"}],"title":"SBSDKDocument","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocument"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/title","value":"SBSDKOCRResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/fragments","value":[{"kind":"identifier","text":"SBSDKOCRResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/navigatorTitle","value":[{"text":"SBSDKOCRResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngine\/title","value":"SBSDKOCREngine"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngine\/fragments","value":[{"text":"SBSDKOCREngine","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngine\/navigatorTitle","value":[{"text":"SBSDKOCREngine","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title","value":"SBSDKDocumentPage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/title","value":"SBSDKDocument"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/fragments","value":[{"text":"SBSDKDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocument"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}