{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/polygonconfigurationrejected"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/polygonconfigurationrejected"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/polygonConfigurationRejected"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController"]]},"abstract":[{"type":"text","text":"The configuration for the polygon displayed over the detected document when the document detection status is not "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/ok"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonConfigurationRejected","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKDocumentScannerPolygonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerPolygonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerPolygonConfiguration"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"name":"Note","type":"aside","style":"note","content":[{"inlineContent":[{"text":"The default color of ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerPolygonConfiguration\/strokeColor","isActive":true},{"type":"text","text":" is "},{"type":"codeVoice","code":"UIColor.red"},{"text":" and the default color","type":"text"},{"text":" ","type":"text"},{"text":"of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerPolygonConfiguration\/fillColor"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"UIColor.red"},{"type":"text","text":" with 0.3 alpha."}],"type":"paragraph"}]}],"kind":"content"}],"sections":[],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonConfigurationRejected","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerPolygonConfiguration","text":"SBSDKDocumentScannerPolygonConfiguration"}],"symbolKind":"property","title":"polygonConfigurationRejected","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController(py)polygonConfigurationRejected","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","navigatorTitle":[{"text":"polygonConfigurationRejected","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionStatus/ok":{"abstract":[{"text":"A document has been detected successfully.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ok"}],"title":"SBSDKDocumentDetectionStatus.ok","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/ok","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/ok","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerPolygonConfiguration/fillColor":{"navigatorTitle":[{"text":"fillColor","kind":"identifier"}],"abstract":[{"type":"text","text":"The fill color for the polygon displayed over the detected document."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerPolygonConfiguration\/fillColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"title":"fillColor","type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerpolygonconfiguration\/fillcolor","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerPolygonConfiguration":{"title":"SBSDKDocumentScannerPolygonConfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerPolygonConfiguration","abstract":[{"text":"Configuration for the polygon displayed over the detected document.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerpolygonconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentScannerPolygonConfiguration"}],"navigatorTitle":[{"text":"SBSDKDocumentScannerPolygonConfiguration","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller","abstract":[{"type":"text","text":"A UIViewController subclass to show a camera screen and run a user guiding document detector."}],"navigatorTitle":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"title":"SBSDKDocumentScannerViewController","type":"topic","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/polygonConfigurationRejected":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/polygonconfigurationrejected","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/polygonConfigurationRejected","kind":"symbol","abstract":[{"text":"The configuration for the polygon displayed over the detected document when the document detection status is not ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/ok","isActive":true},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonConfigurationRejected","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerPolygonConfiguration","text":"SBSDKDocumentScannerPolygonConfiguration","kind":"typeIdentifier"}],"title":"polygonConfigurationRejected","role":"symbol","navigatorTitle":[{"text":"polygonConfigurationRejected","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerPolygonConfiguration/strokeColor":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerpolygonconfiguration\/strokecolor","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"strokeColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerPolygonConfiguration\/strokeColor","navigatorTitle":[{"text":"strokeColor","kind":"identifier"}],"title":"strokeColor","abstract":[{"type":"text","text":"The stroke color for the polygon displayed over the detected document."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"polygonConfigurationRejected","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"polygonConfigurationRejected","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerPolygonConfiguration","kind":"typeIdentifier","text":"SBSDKDocumentScannerPolygonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerPolygonConfiguration"},{"kind":"text","text":" * "},{"text":"polygonConfigurationRejected","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentDetectionStatusOk","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus~1ok\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus~1ok\/fragments","value":[{"text":"SBSDKDocumentDetectionStatusOk","kind":"identifier"}],"op":"replace"},{"value":"fillColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerPolygonConfiguration~1fillColor\/title"},{"value":[{"text":"fillColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerPolygonConfiguration~1fillColor\/fragments"},{"op":"replace","value":"SBSDKDocumentScannerPolygonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerPolygonConfiguration\/title"},{"value":[{"text":"SBSDKDocumentScannerPolygonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerPolygonConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/title","value":"SBSDKDocumentScannerViewController"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1polygonConfigurationRejected\/title","value":"polygonConfigurationRejected","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1polygonConfigurationRejected\/fragments","op":"replace","value":[{"kind":"identifier","text":"polygonConfigurationRejected"}]},{"value":"strokeColor","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerPolygonConfiguration~1strokeColor\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerPolygonConfiguration~1strokeColor\/fragments","value":[{"kind":"identifier","text":"strokeColor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}