{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/snapButton","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The default snap button."}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"snapButton","kind":"identifier"}],"symbolKind":"property","title":"snapButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"snapButton","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKShutterButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKShutterButton"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController(py)snapButton"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/snapbutton"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/snapbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"snapButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKShutterButton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton","kind":"typeIdentifier","text":"SBSDKShutterButton"},{"text":" { get }","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.2.1"}],"type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/snapButton":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/snapbutton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/snapButton","abstract":[{"type":"text","text":"The default snap button."}],"kind":"symbol","role":"symbol","title":"snapButton","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"snapButton","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKShutterButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKShutterButton","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"snapButton"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController":{"title":"SBSDKDocumentScannerViewController","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller","type":"topic","abstract":[{"type":"text","text":"A UIViewController subclass to show a camera screen and run a user guiding document detector."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton":{"kind":"symbol","abstract":[{"type":"text","text":"The button class used in the camera view controller to take a snapshot."},{"type":"text","text":" "},{"type":"text","text":"Animates itself depending on its status."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKShutterButton"}],"title":"SBSDKShutterButton","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKShutterButton","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"snapButton"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"snapButton"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBSDKShutterButton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKShutterButton"},{"kind":"text","text":" * "},{"text":"snapButton","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"snapButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1snapButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1snapButton\/fragments","value":[{"kind":"identifier","text":"snapButton"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/title","value":"SBSDKDocumentScannerViewController"},{"value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/fragments","op":"replace"},{"op":"replace","value":"SBSDKShutterButton","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton\/fragments","value":[{"text":"SBSDKShutterButton","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}