{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Tries to load the encryption key for the given context and key length.","type":"text"},{"text":" ","type":"text"},{"text":"If no key is available yet, a new key is generated by the receivers key generator and stored under the given context.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(provideKeyForContext:keyLength:error:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provideKeyForContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"context","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keyLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKStorageCryptingKeyLength"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The context to generate or load the key for. For most applications in Scanbot SDK the context is derived from the URL of the file to encrypted or decrypted by calling the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Foundation\/URL\/sbsdk_encryptionContext"},{"text":" property on the URL.","type":"text"}]}],"name":"context"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The length of the key to be provided.","type":"text"}]}],"name":"keyLength"}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"text":"The encryption\/decryption key for the given context.","type":"text"}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider\/provideKeyForContext(_:keyLength:)"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provideKeyForContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"keyLength","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKStorageCryptingKeyLength","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"required":true,"title":"provideKeyForContext(_:keyLength:)","roleHeading":"Instance Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingKeyProvider(im)provideKeyForContext:keyLength:error:","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"provideKeyForContext:keyLength:error:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeyprovider\/providekeyforcontext(_:keylength:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeyprovider\/providekeyforcontext(_:keylength:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Foundation/URL/sbsdk_encryptionContext":{"title":"sbsdk_encryptionContext","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Foundation\/URL\/sbsdk_encryptionContext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sbsdk_encryptionContext"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/scanbotdocumentscannersdk\/foundation\/url\/sbsdk_encryptioncontext","abstract":[{"type":"text","text":"The encryption context of the URL."}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyProvider/provideKeyForContext(_:keyLength:)":{"kind":"symbol","abstract":[{"type":"text","text":"Tries to load the encryption key for the given context and key length."},{"type":"text","text":" "},{"type":"text","text":"If no key is available yet, a new key is generated by the receivers key generator and stored under the given context."}],"required":true,"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeyprovider\/providekeyforcontext(_:keylength:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider\/provideKeyForContext(_:keyLength:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provideKeyForContext"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keyLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKStorageCryptingKeyLength"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"role":"symbol","title":"provideKeyForContext(_:keyLength:)","navigatorTitle":[{"kind":"identifier","text":"provideKeyForContext:keyLength:error:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyProvider":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider","title":"SBSDKStorageCryptingKeyProvider","type":"topic","navigatorTitle":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"Protocol for loading, storing and providing encryption keys."},{"type":"text","text":" "},{"type":"text","text":"The context parameter is used to distinguish between different encryption contexts."}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeyprovider"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyLength":{"abstract":[{"text":"The length of the encryption key.","type":"text"}],"navigatorTitle":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength","title":"SBSDKStorageCryptingKeyLength","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeylength"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"provideKeyForContext:keyLength:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"provideKeyForContext:keyLength:error:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"provideKeyForContext:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"context","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"keyLength:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKStorageCryptingKeyLength","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength"},{"kind":"text","text":") "},{"kind":"internalParam","text":"keyLength"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"The context to generate or load the key for. For most applications in Scanbot SDK the context is derived from the URL of the file to encrypted or decrypted by calling the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Foundation\/URL\/sbsdk_encryptionContext"},{"text":" property on the URL.","type":"text"}],"type":"paragraph"}],"name":"context"},{"content":[{"inlineContent":[{"type":"text","text":"The length of the key to be provided."}],"type":"paragraph"}],"name":"keyLength"},{"content":[{"inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}],"type":"paragraph"}],"name":"error"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The encryption\/decryption key for the given context."},{"type":"text","text":" On failure, this method returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}]}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"provideKeyForContext:keyLength:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider~1provideKeyForContext(_:keyLength:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"provideKeyForContext:keyLength:error:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider~1provideKeyForContext(_:keyLength:)\/fragments"},{"value":"SBSDKStorageCryptingKeyProvider","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider\/title"},{"value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider\/fragments"},{"value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider\/navigatorTitle"},{"value":"SBSDKStorageCryptingKeyLength","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyLength\/title"},{"value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyLength\/fragments"},{"value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyLength\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}