{"sections":[],"abstract":[{"text":"Color conversion to apply during image loading.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbufferimageloadoptions\/colorconversion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbufferimageloadoptions\/colorconversion"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBufferImageLoadOptions(py)colorConversion","modules":[{"name":"ScanbotSDK"}],"title":"colorConversion","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"colorConversion"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorConversion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKColorConversion","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKColorConversion"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBufferImageLoadOptions\/colorConversion"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorConversion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorConversion","text":"SBSDKColorConversion","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKColorConversion"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"Default is ANY_COLOR"}],"type":"paragraph"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBufferImageLoadOptions"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBufferImageLoadOptions":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBufferImageLoadOptions","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbufferimageloadoptions","role":"symbol","navigatorTitle":[{"text":"SBSDKBufferImageLoadOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Options for loading image from buffer."}],"title":"SBSDKBufferImageLoadOptions","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBufferImageLoadOptions","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBufferImageLoadOptions/colorConversion":{"abstract":[{"type":"text","text":"Color conversion to apply during image loading."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorConversion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKColorConversion","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKColorConversion"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBufferImageLoadOptions\/colorConversion","role":"symbol","title":"colorConversion","url":"\/documentation\/scanbotsdk\/sbsdkbufferimageloadoptions\/colorconversion","type":"topic","navigatorTitle":[{"kind":"identifier","text":"colorConversion"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorConversion":{"abstract":[{"type":"text","text":"Color conversion to apply during image loading."}],"navigatorTitle":[{"text":"SBSDKColorConversion","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKColorConversion","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorConversion","title":"SBSDKColorConversion","url":"\/documentation\/scanbotsdk\/sbsdkcolorconversion"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"colorConversion","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"colorConversion","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKColorConversion","text":"SBSDKColorConversion","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorConversion"},{"text":" ","kind":"text"},{"text":"colorConversion","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBufferImageLoadOptions\/title","value":"SBSDKBufferImageLoadOptions","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBufferImageLoadOptions\/fragments","value":[{"kind":"identifier","text":"SBSDKBufferImageLoadOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBufferImageLoadOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBufferImageLoadOptions"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBufferImageLoadOptions~1colorConversion\/title","op":"replace","value":"colorConversion"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBufferImageLoadOptions~1colorConversion\/fragments","op":"replace","value":[{"text":"colorConversion","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorConversion\/title","op":"replace","value":"SBSDKColorConversion"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorConversion\/fragments","op":"replace","value":[{"text":"SBSDKColorConversion","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorConversion\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKColorConversion"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}