{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeType"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"upcE"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeType","kind":"typeIdentifier","text":"SBSDKBarcodeType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"The barcode type UPC-E."}],"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeType(cpy)upcE","navigatorTitle":[{"kind":"identifier","text":"upcE"}],"roleHeading":"Type Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property","role":"symbol","title":"upcE","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"upcE"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeType","kind":"typeIdentifier","text":"SBSDKBarcodeType"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeType\/upcE"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetype\/upce"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetype\/upce"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeType":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeType","kind":"identifier"}],"title":"SBSDKBarcodeType","kind":"symbol","abstract":[{"type":"text","text":"Class that represents a barcode type."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeType","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetype","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeType","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeType/upcE":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetype\/upce","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"upcE","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeType","text":"SBSDKBarcodeType","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeType\/upcE","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The barcode type UPC-E."}],"navigatorTitle":[{"kind":"identifier","text":"upcE"}],"title":"upcE"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"value":"upcE","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"upcE"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeType","kind":"typeIdentifier","text":"SBSDKBarcodeType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeType"},{"kind":"text","text":" * "},{"kind":"identifier","text":"upcE"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeType\/title","value":"SBSDKBarcodeType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeType\/fragments","value":[{"text":"SBSDKBarcodeType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeType\/navigatorTitle","value":[{"text":"SBSDKBarcodeType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeType~1upcE\/title","value":"upcE","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeType~1upcE\/fragments","value":[{"text":"upcE","kind":"identifier"}]}]}]}