{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithRegexFilter:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"regexFilter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumSizeScore:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimumSizeScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"addAdditionalQuietZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"addAdditionalQuietZone","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimum1DQuietZoneSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimum1DQuietZoneSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"stripCheckDigits:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"stripCheckDigits","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ean8:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"ean8","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ean13:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"ean13","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"upca:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"upca","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"upce:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"upce","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"extensions:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUpcEanExtensionBehavior","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUpcEanExtensionBehavior","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"extensions","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:ean8:ean13:upca:upce:extensions:minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:","kind":"identifier"}],"title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:ean8:ean13:upca:upce:extensions:minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatUpcEanConfiguration(im)initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:ean8:ean13:upca:upce:extensions:minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:","symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:ean8:ean13:upca:upce:extensions:minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatUpcEanConfiguration"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:ean8:ean13:upca:upce:extensions:minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatupceanconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:minimumnumberofrequiredframeswithequalrecognitionresult:stripcheckdigits:ean8:ean13:upca:upce:extensions:minimumnumberofrequiredframeswithequalrecognitionres-5e31f"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatUpcEanConfiguration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:ean8:ean13:upca:upce:extensions:minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:ean8:ean13:upca:upce:extensions:minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:ean8:ean13:upca:upce:extensions:minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatupceanconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:minimumnumberofrequiredframeswithequalrecognitionresult:stripcheckdigits:ean8:ean13:upca:upce:extensions:minimumnumberofrequiredframeswithequalrecognitionres-5e31f","navigatorTitle":[{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:ean8:ean13:upca:upce:extensions:minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:","kind":"identifier"}],"title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:ean8:ean13:upca:upce:extensions:minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:","abstract":[],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUpcEanExtensionBehavior":{"navigatorTitle":[{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"abstract":[{"type":"text","text":"Behavior when scanning UPC\/EAN barcodes with EAN-2 or EAN-5 extensions."}],"title":"SBSDKUpcEanExtensionBehavior","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatUpcEanConfiguration":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatUpcEanConfiguration"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatupceanconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatUpcEanConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatUpcEanConfiguration"}],"abstract":[{"text":"UPC\/EAN barcode configuration. Add to scanner configuration to scan EAN-8, EAN-13, UPC-E and UPC-A barcodes.","type":"text"}],"title":"SBSDKBarcodeFormatUpcEanConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUpcEanExtensionBehavior","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/title"},{"value":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/navigatorTitle"},{"value":"SBSDKBarcodeFormatUpcEanConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatUpcEanConfiguration\/title"},{"value":[{"text":"SBSDKBarcodeFormatUpcEanConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatUpcEanConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatUpcEanConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatUpcEanConfiguration\/navigatorTitle"}]}]}