{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IntroductionScreenConfiguration\/topBarDoneButton","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IntroductionScreenConfiguration"]]},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","title":"topBarDoneButton","navigatorTitle":[{"text":"topBarDoneButton","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IntroductionScreenConfiguration(py)topBarDoneButton","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarDoneButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarDoneButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Configuration of the ‘done’ button, located in the top bar."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2introductionscreenconfiguration\/topbardonebutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2introductionscreenconfiguration\/topbardonebutton"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2IntroductionScreenConfiguration":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IntroductionScreenConfiguration","abstract":[{"type":"text","text":"Configuration of the introduction screen for the document scanner."}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2introductionscreenconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"}],"title":"SBSDKUI2IntroductionScreenConfiguration","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2IntroductionScreenConfiguration/topBarDoneButton":{"title":"topBarDoneButton","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2introductionscreenconfiguration\/topbardonebutton","type":"topic","kind":"symbol","abstract":[{"text":"Configuration of the ‘done’ button, located in the top bar.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IntroductionScreenConfiguration\/topBarDoneButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarDoneButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"topBarDoneButton","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ButtonConfiguration":{"abstract":[{"text":"Configuration of the button.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","title":"SBSDKUI2ButtonConfiguration","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2buttonconfiguration","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"topBarDoneButton","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"topBarDoneButton","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration"},{"text":" * ","kind":"text"},{"text":"topBarDoneButton","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IntroductionScreenConfiguration\/title","value":"SBSDKUI2IntroductionScreenConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IntroductionScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IntroductionScreenConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IntroductionScreenConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"topBarDoneButton","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IntroductionScreenConfiguration~1topBarDoneButton\/title"},{"op":"replace","value":[{"kind":"identifier","text":"topBarDoneButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IntroductionScreenConfiguration~1topBarDoneButton\/fragments"},{"op":"replace","value":"SBSDKUI2ButtonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}