{"sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController\/imageEditingViewControllerDidChangePolygon(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"collectionGroup","roleHeading":"API Collection","title":"SBSDKImageEditingViewControllerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontroller\/sbsdkimageeditingviewcontrollerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontroller\/sbsdkimageeditingviewcontrollerdelegate-implementations"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController\/SBSDKImageEditingViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUICroppingViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingViewController"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController","kind":"symbol","title":"SBSDKUICroppingViewController","type":"topic","abstract":[{"text":"A highly customizable view controller to edit a pages polygon or the page’s orientation.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingViewController/imageEditingViewControllerDidChangePolygon(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController\/imageEditingViewControllerDidChangePolygon(_:)","navigatorTitle":[{"text":"imageEditingViewControllerDidChangePolygon:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"imageEditingViewControllerDidChangePolygon","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","kind":"typeIdentifier","text":"SBSDKImageEditingViewController"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontroller\/imageeditingviewcontrollerdidchangepolygon(_:)","role":"symbol","kind":"symbol","title":"imageEditingViewControllerDidChangePolygon(_:)","abstract":[{"type":"text","text":"Informs the delegate that the image editing view controllers polygon was changed by user interaction."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController\/imageEditingViewControllerDidChangePolygon(_:)"],"anchor":"Instance-Methods","title":"Instance Methods"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":"SBSDKUICroppingViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController\/fragments","value":[{"text":"SBSDKUICroppingViewController","kind":"identifier"}]},{"value":[{"text":"SBSDKUICroppingViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController~1imageEditingViewControllerDidChangePolygon(_:)\/title","op":"replace","value":"imageEditingViewControllerDidChangePolygon:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController~1imageEditingViewControllerDidChangePolygon(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}