{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"SBSDKThreadSafe","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"dynamic","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraMockData","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKSimulatedCameraMockData","text":"SBSDKSimulatedCameraMockData","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Observably via KVO. Thread safe.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}]}],"kind":"content"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraMockData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKSimulatedCameraMockData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKSimulatedCameraMockData"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTestData(py)cameraMockData","navigatorTitle":[{"text":"cameraMockData","kind":"identifier"}],"title":"cameraMockData","role":"symbol","symbolKind":"property"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktestdata\/cameramockdata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktestdata\/cameramockdata"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTestData"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTestData\/cameraMockData","interfaceLanguage":"swift"},"abstract":[{"text":"The test data for a simulated camera. Intended for UI testing, etc.","type":"text"},{"text":" ","type":"text"},{"text":"If set to a non-nil value, any active scanners camera session will immediately switch to simulation mode and simulate a camera stream and captured images using an image source provided in the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData","type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Setting it to ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" will return to the normal camera mode on physical devices and to simulated mode without a video stream on iOS simulators.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTestData/cameraMockData":{"role":"symbol","kind":"symbol","title":"cameraMockData","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTestData\/cameraMockData","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktestdata\/cameramockdata","abstract":[{"text":"The test data for a simulated camera. Intended for UI testing, etc.","type":"text"},{"text":" ","type":"text"},{"text":"If set to a non-nil value, any active scanners camera session will immediately switch to simulation mode and simulate a camera stream and captured images using an image source provided in the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData","type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Setting it to ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" will return to the normal camera mode on physical devices and to simulated mode without a video stream on iOS simulators.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraMockData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKSimulatedCameraMockData","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKSimulatedCameraMockData"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"cameraMockData"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTestData":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktestdata","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTestData","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKTestData","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTestData","abstract":[{"type":"text","text":"A container for test data, e.g. simulated camera mock data."}],"title":"SBSDKTestData","kind":"symbol","type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSimulatedCameraMockData":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksimulatedcameramockdata","title":"SBSDKSimulatedCameraMockData","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A class to describe the mocking data that is fed to a simulated camera device."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"cameraMockData","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"cameraMockData","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKSimulatedCameraMockData","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKSimulatedCameraMockData","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData"},{"text":" * ","kind":"text"},{"text":"cameraMockData","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"cameraMockData","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTestData~1cameraMockData\/title"},{"value":[{"text":"cameraMockData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTestData~1cameraMockData\/fragments"},{"value":"SBSDKTestData","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTestData\/title"},{"value":[{"text":"SBSDKTestData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTestData\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKTestData"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTestData\/navigatorTitle"},{"value":"SBSDKSimulatedCameraMockData","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData\/title"},{"value":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData\/navigatorTitle"}]}]}