{"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerenginemode\/legacy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerenginemode\/legacy"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerEngineMode\/legacy","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeScannerEngineMode@SBSDKBarcodeScannerEngineModeLegacy","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"legacy"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineModeLegacy"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"SBSDKBarcodeScannerEngineMode.legacy","role":"symbol","roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"legacy"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Legacy mode. Very fast, significantly less accurate. Doesn’t support all barcode types."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerEngineMode"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerEngineMode/legacy":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"legacy","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineModeLegacy","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerenginemode\/legacy","kind":"symbol","title":"SBSDKBarcodeScannerEngineMode.legacy","role":"symbol","abstract":[{"text":"Legacy mode. Very fast, significantly less accurate. Doesn’t support all barcode types.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerEngineMode\/legacy"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerEngineMode":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerenginemode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerEngineMode","role":"symbol","title":"SBSDKBarcodeScannerEngineMode","abstract":[{"text":"The engine mode for barcode scanning.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKBarcodeScannerEngineModeLegacy","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineModeLegacy"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"SBSDKBarcodeScannerEngineModeLegacy","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKBarcodeScannerEngineModeLegacy","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerEngineMode~1legacy\/title","op":"replace"},{"value":[{"text":"SBSDKBarcodeScannerEngineModeLegacy","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerEngineMode~1legacy\/fragments","op":"replace"},{"value":"SBSDKBarcodeScannerEngineMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerEngineMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerEngineMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerEngineMode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}