{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"metadata":{"symbolKind":"method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAnalyticsFeature(im)init","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsFeature\/init"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticsfeature\/init"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsFeature"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAnalyticsFeature/init":{"title":"init","kind":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsFeature\/init","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticsfeature\/init","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAnalyticsFeature":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticsfeature","abstract":[{"text":"The feature that is being tracked.","type":"text"}],"title":"SBSDKAnalyticsFeature","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAnalyticsFeature"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsFeature","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKAnalyticsFeature"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsFeature\/title","op":"replace","value":"SBSDKAnalyticsFeature"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsFeature\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKAnalyticsFeature"}]},{"value":[{"kind":"identifier","text":"SBSDKAnalyticsFeature"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsFeature\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}