{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeTextLocalization"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"cameraPermissionEnableCameraTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" = \"Camera permission denied!\", ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" = \"Please allow the usage of the camera to start the scanning process.\", ","kind":"text"},{"kind":"externalParam","text":"cameraPermissionEnableCameraButton"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" = \"Grant permission\", "},{"kind":"externalParam","text":"cameraPermissionCloseButton"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" = \"Close\", ","kind":"text"},{"kind":"externalParam","text":"topBarCancelButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"Cancel\", ","kind":"text"},{"text":"topBarTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" = \"Scan Item\", "},{"kind":"externalParam","text":"userGuidance"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"Move the finder over a barcode\", "},{"kind":"externalParam","text":"barcodeInfoMappingLoadingMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" = \"Loading details...\", ","kind":"text"},{"text":"barcodeInfoMappingErrorStateTitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" = \"Connection Error!\", ","kind":"text"},{"text":"barcodeInfoMappingErrorStateSubtitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" = \"There was an issue and the data requested was not fetched. You could try again or discard this result to start a new scan.\", "},{"kind":"externalParam","text":"barcodeInfoMappingErrorStateRetryButton"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"Retry\", ","kind":"text"},{"kind":"externalParam","text":"barcodeInfoMappingErrorStateCancelButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" = \"Cancel\", ","kind":"text"},{"text":"manualCountEditDialogTitle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" = \"Update count\", "},{"kind":"externalParam","text":"manualCountEditDialogInfo"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"Adjust the number of items you scanned.\", ","kind":"text"},{"text":"manualCountEditDialogUpdateButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" = \"Update\", "},{"kind":"externalParam","text":"manualCountEditDialogCancelButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"Cancel\", "},{"kind":"externalParam","text":"sheetResetButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" = \"Reset\", ","kind":"text"},{"kind":"externalParam","text":"sheetClearAllButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"Clear all\", ","kind":"text"},{"kind":"externalParam","text":"sheetSubmitButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"Submit\", ","kind":"text"},{"text":"sheetStartScanningButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" = \"Start scanning\", ","kind":"text"},{"kind":"externalParam","text":"sheetPlaceholderTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" = \"No barcodes here!\", ","kind":"text"},{"text":"sheetPlaceholderSubtitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"The barcode list is currently empty. Close this sheet and scan your items to add them.\", "},{"kind":"externalParam","text":"singleModeConfirmationCancelButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" = \"Close\", "},{"text":"multipleModeSheetTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" = \"%d items\", ","kind":"text"},{"text":"findAndPickSheetTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" = \"%d\/%d scanned\", ","kind":"text"},{"text":"findAndPickSheetBarcodeItemSubtitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" = \"%d\/%d added\", ","kind":"text"},{"kind":"externalParam","text":"findAndPickPartialAlertTitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" = \"Incomplete scan!\", "},{"text":"findAndPickPartialAlertSubtitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"Some codes are yet to be scanned. Proceed with submission anyway?\", ","kind":"text"},{"kind":"externalParam","text":"findAndPickPartialAlertCancelButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" = \"Cancel\", ","kind":"text"},{"text":"findAndPickPartialAlertSubmitButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" = \"Yes, Submit\", ","kind":"text"},{"kind":"externalParam","text":"findAndPickCompleteAlertTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" = \"All codes found!\", "},{"kind":"externalParam","text":"findAndPickCompleteAlertSubtitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" = \"You have successfully scanned all codes. Proceed with submission?\", "},{"text":"findAndPickCompleteAlertCancelButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" = \"Dismiss\", ","kind":"text"},{"kind":"externalParam","text":"findAndPickCompleteAlertSubmitButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" = \"Submit\", ","kind":"text"},{"text":"accessibilityDescriptionFlashButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" = \"Toggle flash\", "},{"text":"accessibilityDescriptionZoomButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"Toggle camera zoom\", ","kind":"text"},{"text":"accessibilityDescriptionFlipCameraButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" = \"Flip camera\")"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodetextlocalization\/init(camerapermissionenablecameratitle:camerapermissionenablecameraexplanation:camerapermissionenablecamerabutton:camerapermissionclosebutton:topbarcancelbutton:topbartitle:userguidance:barcodeinfomappingloadingmessage:barcodeinfomappingerr-5aao0"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodetextlocalization\/init(camerapermissionenablecameratitle:camerapermissionenablecameraexplanation:camerapermissionenablecamerabutton:camerapermissionclosebutton:topbarcancelbutton:topbartitle:userguidance:barcodeinfomappingloadingmessage:barcodeinfomappingerr-5aao0"]}],"sections":[],"metadata":{"symbolKind":"init","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeTextLocalization(im)initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"cameraPermissionEnableCameraTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"cameraPermissionEnableCameraButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"cameraPermissionCloseButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topBarCancelButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"topBarTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userGuidance"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barcodeInfoMappingLoadingMessage"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodeInfoMappingErrorStateTitle"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"barcodeInfoMappingErrorStateSubtitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barcodeInfoMappingErrorStateRetryButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barcodeInfoMappingErrorStateCancelButton"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"manualCountEditDialogTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"manualCountEditDialogInfo"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"manualCountEditDialogUpdateButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"manualCountEditDialogCancelButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sheetResetButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sheetClearAllButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sheetSubmitButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sheetStartScanningButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"sheetPlaceholderTitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"sheetPlaceholderSubtitle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"singleModeConfirmationCancelButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"multipleModeSheetTitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"findAndPickSheetTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"findAndPickSheetBarcodeItemSubtitle"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"findAndPickPartialAlertTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"findAndPickPartialAlertSubtitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"findAndPickPartialAlertCancelButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"findAndPickPartialAlertSubmitButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"findAndPickCompleteAlertTitle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"findAndPickCompleteAlertSubtitle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"findAndPickCompleteAlertCancelButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"findAndPickCompleteAlertSubmitButton"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"accessibilityDescriptionFlashButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessibilityDescriptionZoomButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"accessibilityDescriptionFlipCameraButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeTextLocalization\/init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeTextLocalization":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodetextlocalization","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"title":"SBSDKUI2BarcodeTextLocalization","type":"topic","abstract":[{"text":"Configuration of the all strings for barcode scanner.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeTextLocalization"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeTextLocalization/init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cameraPermissionEnableCameraTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraPermissionEnableCameraButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPermissionCloseButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"topBarCancelButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topBarTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"userGuidance","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"barcodeInfoMappingLoadingMessage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"barcodeInfoMappingErrorStateTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barcodeInfoMappingErrorStateSubtitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"barcodeInfoMappingErrorStateRetryButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodeInfoMappingErrorStateCancelButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"manualCountEditDialogTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"manualCountEditDialogInfo"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"manualCountEditDialogUpdateButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"manualCountEditDialogCancelButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"sheetResetButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"sheetClearAllButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"sheetSubmitButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"sheetStartScanningButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"sheetPlaceholderTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"sheetPlaceholderSubtitle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"singleModeConfirmationCancelButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"multipleModeSheetTitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"findAndPickSheetTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"findAndPickSheetBarcodeItemSubtitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"findAndPickPartialAlertTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"findAndPickPartialAlertSubtitle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"findAndPickPartialAlertCancelButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"findAndPickPartialAlertSubmitButton"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"findAndPickCompleteAlertTitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"findAndPickCompleteAlertSubtitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"findAndPickCompleteAlertCancelButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"findAndPickCompleteAlertSubmitButton"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"accessibilityDescriptionFlashButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"accessibilityDescriptionZoomButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"accessibilityDescriptionFlipCameraButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:","kind":"identifier"}],"abstract":[],"title":"init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeTextLocalization\/init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodetextlocalization\/init(camerapermissionenablecameratitle:camerapermissionenablecameraexplanation:camerapermissionenablecamerabutton:camerapermissionclosebutton:topbarcancelbutton:topbartitle:userguidance:barcodeinfomappingloadingmessage:barcodeinfomappingerr-5aao0","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 6.2.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCameraPermissionEnableCameraTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionEnableCameraTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraPermissionEnableCameraButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraPermissionEnableCameraButton"},{"kind":"text","text":" "},{"text":"cameraPermissionCloseButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraPermissionCloseButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarCancelButton:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"topBarCancelButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"topBarTitle:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"topBarTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"userGuidance:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"userGuidance","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeInfoMappingLoadingMessage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"barcodeInfoMappingLoadingMessage"},{"kind":"text","text":" "},{"text":"barcodeInfoMappingErrorStateTitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"barcodeInfoMappingErrorStateTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeInfoMappingErrorStateSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"barcodeInfoMappingErrorStateSubtitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeInfoMappingErrorStateRetryButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"barcodeInfoMappingErrorStateRetryButton"},{"text":" ","kind":"text"},{"text":"barcodeInfoMappingErrorStateCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"barcodeInfoMappingErrorStateCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"manualCountEditDialogTitle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"manualCountEditDialogTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"manualCountEditDialogInfo:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"manualCountEditDialogInfo","kind":"internalParam"},{"kind":"text","text":" "},{"text":"manualCountEditDialogUpdateButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"manualCountEditDialogUpdateButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"manualCountEditDialogCancelButton:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"manualCountEditDialogCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheetResetButton:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"sheetResetButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"sheetClearAllButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"sheetClearAllButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheetSubmitButton:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sheetSubmitButton"},{"text":" ","kind":"text"},{"text":"sheetStartScanningButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sheetStartScanningButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sheetPlaceholderTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sheetPlaceholderTitle"},{"text":" ","kind":"text"},{"text":"sheetPlaceholderSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sheetPlaceholderSubtitle"},{"kind":"text","text":" "},{"text":"singleModeConfirmationCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"singleModeConfirmationCancelButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"multipleModeSheetTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"multipleModeSheetTitle"},{"text":" ","kind":"text"},{"text":"findAndPickSheetTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"findAndPickSheetTitle","kind":"internalParam"},{"kind":"text","text":" "},{"text":"findAndPickSheetBarcodeItemSubtitle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"findAndPickSheetBarcodeItemSubtitle"},{"text":" ","kind":"text"},{"text":"findAndPickPartialAlertTitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"findAndPickPartialAlertTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"findAndPickPartialAlertSubtitle:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"findAndPickPartialAlertSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"findAndPickPartialAlertCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"findAndPickPartialAlertCancelButton"},{"text":" ","kind":"text"},{"kind":"identifier","text":"findAndPickPartialAlertSubmitButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"findAndPickPartialAlertSubmitButton"},{"text":" ","kind":"text"},{"text":"findAndPickCompleteAlertTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"findAndPickCompleteAlertTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"findAndPickCompleteAlertSubtitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"findAndPickCompleteAlertSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"findAndPickCompleteAlertCancelButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"findAndPickCompleteAlertCancelButton"},{"kind":"text","text":" "},{"text":"findAndPickCompleteAlertSubmitButton:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"findAndPickCompleteAlertSubmitButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionFlashButton:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionFlashButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionZoomButton:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionZoomButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionFlipCameraButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionFlipCameraButton","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeTextLocalization\/title","value":"SBSDKUI2BarcodeTextLocalization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeTextLocalization\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}]},{"value":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeTextLocalization\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeTextLocalization~1init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:)\/title","value":"initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeTextLocalization~1init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:","kind":"identifier"}]}]}]}