{"abstract":[{"text":"Asynchronously recognizes characters on all images of an image storage and returns the result, or throws an error otherwise.","type":"text"}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@nonobjc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"imageStorage","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","text":"SBSDKImageStoring","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","text":"SBSDKOCRResult","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"imageStorage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image storage containing the images to run the optical character recognition on."}]}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"The OCR result object."}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"In Swift language it is used with structured concurrency (async\/await)."}],"type":"paragraph"}]}],"metadata":{"externalID":"s:10ScanbotSDK21SBSDKOCREngineManagerC9recognize4fromAA14SBSDKOCRResultCAA17SBSDKImageStoring_p_tYaKF","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"recognize(from:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","text":"SBSDKImageStoring","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","text":"SBSDKOCRResult","kind":"typeIdentifier"}],"symbolKind":"method","roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrenginemanager\/recognize(from:)-49pep"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:)-49pep"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCREngineManager","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager","url":"\/documentation\/scanbotsdk\/sbsdkocrenginemanager","type":"topic","title":"SBSDKOCREngineManager","abstract":[{"type":"text","text":"A class to perform optical character recognition (text) on an image (OCR)."}],"navigatorTitle":[{"text":"SBSDKOCREngineManager","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineManager/recognize(from:)-49pep":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:)-49pep","url":"\/documentation\/scanbotsdk\/sbsdkocrenginemanager\/recognize(from:)-49pep","title":"recognize(from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageStoring","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"SBSDKOCRResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult"}],"kind":"symbol","abstract":[{"type":"text","text":"Asynchronously recognizes characters on all images of an image storage and returns the result, or throws an error otherwise."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageStoring":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagestoring","type":"topic","title":"SBSDKImageStoring","abstract":[{"text":"Protocol for an order-aware (array like) image storage.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageStoring"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageStoring"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResult":{"title":"SBSDKOCRResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResult","url":"\/documentation\/scanbotsdk\/sbsdkocrresult","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCRResult","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKOCRResult","kind":"identifier"}],"abstract":[{"type":"text","text":"The result of an optical character recognition."}]}},"variantOverrides":[{"patch":[{"value":"SBSDKOCREngineManager","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager\/title"},{"value":[{"kind":"identifier","text":"SBSDKOCREngineManager"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager\/fragments"},{"value":[{"text":"SBSDKOCREngineManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/title","op":"replace","value":"SBSDKImageStoring"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/fragments","op":"replace","value":[{"text":"SBSDKImageStoring","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageStoring"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/title","op":"replace","value":"SBSDKOCRResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/fragments","op":"replace","value":[{"text":"SBSDKOCRResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/navigatorTitle","op":"replace","value":[{"text":"SBSDKOCRResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}