{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredNumberOfEqualAccumulatedResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This sets the first part of the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController\/requiredNumberOfEqualAccumulatedResults","isActive":true},{"type":"text","text":" of "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController\/maxNumberOfAccumulatedResults","type":"reference"},{"text":" selector,","type":"text"},{"text":" ","type":"text"},{"text":"e.g. 2 of 4 results must be equal.","type":"text"},{"text":" ","type":"text"},{"text":"To get fewer false positive results, make the selector more strict by selecting a higher value, e.g. 3 of 4 or even 4 of 4.","type":"text"},{"text":" ","type":"text"},{"text":"Setting a value higher than ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController\/maxNumberOfAccumulatedResults","type":"reference"},{"text":" will throw an exception.","type":"text"},{"text":" ","type":"text"},{"text":"Values less-than-or-equal to 0, will effectively turn off the result accumulation.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Defaults to 2.","type":"text"}]}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"requiredNumberOfEqualAccumulatedResults"}],"title":"requiredNumberOfEqualAccumulatedResults","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredNumberOfEqualAccumulatedResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController(py)requiredNumberOfEqualAccumulatedResults"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller\/requirednumberofequalaccumulatedresults"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller\/requirednumberofequalaccumulatedresults"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController\/requiredNumberOfEqualAccumulatedResults","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The minimum number of equal results in the accumulator when live-recognizing machine-readable zones on sample buffers."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController/requiredNumberOfEqualAccumulatedResults":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController\/requiredNumberOfEqualAccumulatedResults","title":"requiredNumberOfEqualAccumulatedResults","type":"topic","kind":"symbol","abstract":[{"text":"The minimum number of equal results in the accumulator when live-recognizing machine-readable zones on sample buffers.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller\/requirednumberofequalaccumulatedresults","navigatorTitle":[{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller","title":"SBSDKMRZScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan machine-readable zones."}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController/maxNumberOfAccumulatedResults":{"navigatorTitle":[{"text":"maxNumberOfAccumulatedResults","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController\/maxNumberOfAccumulatedResults","abstract":[{"type":"text","text":"The maximum number of results to be accumulated when live-recognizing machine-readable zones on sample buffers."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxNumberOfAccumulatedResults","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller\/maxnumberofaccumulatedresults","title":"maxNumberOfAccumulatedResults","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"requiredNumberOfEqualAccumulatedResults","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController~1requiredNumberOfEqualAccumulatedResults\/title","value":"requiredNumberOfEqualAccumulatedResults","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController~1requiredNumberOfEqualAccumulatedResults\/fragments","value":[{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/title","value":"SBSDKMRZScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/fragments","value":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController~1maxNumberOfAccumulatedResults\/title","value":"maxNumberOfAccumulatedResults","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController~1maxNumberOfAccumulatedResults\/fragments","value":[{"text":"maxNumberOfAccumulatedResults","kind":"identifier"}],"op":"replace"}]}]}