{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration"]]},"metadata":{"roleHeading":"Instance Property","title":"scannerConfiguration","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"scannerConfiguration","kind":"identifier"}],"symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"scannerConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration","text":"SBSDKMRZScannerConfiguration"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerScreenConfiguration(py)scannerConfiguration"},"abstract":[{"type":"text","text":"Configuration of the MRZ scanner."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration\/scannerconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration\/scannerconfiguration"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration\/scannerConfiguration"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"scannerConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration","text":"SBSDKMRZScannerConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerScreenConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration","navigatorTitle":[{"text":"SBSDKUI2MRZScannerScreenConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration","abstract":[{"text":"Configuration of the screen for detecting MRZ (Machine-readable zones) of various documents.","type":"text"}],"type":"topic","title":"SBSDKUI2MRZScannerScreenConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MRZScannerScreenConfiguration"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerConfiguration":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration for MRZ scanner."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZScannerConfiguration"}],"title":"SBSDKMRZScannerConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKMRZScannerConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerScreenConfiguration/scannerConfiguration":{"type":"topic","kind":"symbol","title":"scannerConfiguration","abstract":[{"type":"text","text":"Configuration of the MRZ scanner."}],"navigatorTitle":[{"text":"scannerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration\/scannerconfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration\/scannerConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scannerConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration","kind":"typeIdentifier","text":"SBSDKMRZScannerConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"scannerConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"scannerConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration","kind":"typeIdentifier","text":"SBSDKMRZScannerConfiguration"},{"kind":"text","text":" * "},{"text":"scannerConfiguration","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKUI2MRZScannerScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration\/fragments","value":[{"text":"SBSDKUI2MRZScannerScreenConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerScreenConfiguration"}]},{"op":"replace","value":"SBSDKMRZScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKMRZScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKMRZScannerConfiguration","kind":"identifier"}]},{"value":"scannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration~1scannerConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration~1scannerConfiguration\/fragments","value":[{"kind":"identifier","text":"scannerConfiguration"}]}]}]}