{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerGeneralConfiguration\/videoFrameResolution"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannergeneralconfiguration\/videoframeresolution"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannergeneralconfiguration\/videoframeresolution"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerGeneralConfiguration"]]},"abstract":[{"type":"text","text":"The video frame resolution of the preview layer."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFrameResolution\/auto","isActive":true,"type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Higher resolutions may improve scanning results but slow down the scanning performance."},{"text":" ","type":"text"},{"type":"text","text":"In some cases a higher resolution may even decrease the scanning quality."},{"type":"text","text":" "},{"type":"text","text":"It is therefore recommended to keep this setting at "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFrameResolution\/auto","type":"reference"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoFrameResolution"},{"kind":"text","text":": "},{"text":"SBSDKVideoFrameResolution","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFrameResolution","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoFrameResolution"}]}]}],"sections":[],"metadata":{"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration(py)videoFrameResolution","navigatorTitle":[{"kind":"identifier","text":"videoFrameResolution"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoFrameResolution","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKVideoFrameResolution","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoFrameResolution"}],"symbolKind":"property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"videoFrameResolution"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerGeneralConfiguration":{"role":"symbol","title":"SBSDKBaseScannerGeneralConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerGeneralConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"abstract":[{"text":"The general configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannergeneralconfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoFrameResolution":{"title":"SBSDKVideoFrameResolution","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"abstract":[{"type":"text","text":"An enum describing the resolution of a video or camera stream."}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoframeresolution","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFrameResolution"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerGeneralConfiguration/videoFrameResolution":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannergeneralconfiguration\/videoframeresolution","title":"videoFrameResolution","abstract":[{"type":"text","text":"The video frame resolution of the preview layer."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFrameResolution\/auto","isActive":true,"type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Higher resolutions may improve scanning results but slow down the scanning performance.","type":"text"},{"text":" ","type":"text"},{"text":"In some cases a higher resolution may even decrease the scanning quality.","type":"text"},{"type":"text","text":" "},{"text":"It is therefore recommended to keep this setting at ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFrameResolution\/auto","isActive":true,"type":"reference"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoFrameResolution","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKVideoFrameResolution","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoFrameResolution","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"videoFrameResolution"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerGeneralConfiguration\/videoFrameResolution","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoFrameResolution/auto":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoframeresolution\/auto","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"auto"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFrameResolution\/auto","kind":"symbol","title":"SBSDKVideoFrameResolution.auto","abstract":[{"type":"text","text":"Select the video resolution automatically based on device specifics."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKVideoFrameResolutionAuto","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"videoFrameResolution","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"videoFrameResolution","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKVideoFrameResolution","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFrameResolution","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoFrameResolution"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoFrameResolution"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerGeneralConfiguration\/title","value":"SBSDKBaseScannerGeneralConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerGeneralConfiguration\/fragments"},{"value":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerGeneralConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKVideoFrameResolution","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFrameResolution\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFrameResolution\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFrameResolution\/navigatorTitle","value":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerGeneralConfiguration~1videoFrameResolution\/title","value":"videoFrameResolution"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerGeneralConfiguration~1videoFrameResolution\/fragments","value":[{"text":"videoFrameResolution","kind":"identifier"}],"op":"replace"},{"value":"SBSDKVideoFrameResolutionAuto","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFrameResolution~1auto\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFrameResolution~1auto\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionAuto"}]}]}]}