{"metadata":{"symbolKind":"property","roleHeading":"Type Property","extendedModule":"ScanbotDocumentScannerSDK","title":"defaultParameters","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"s:25ScanbotDocumentScannerSDK28SBSDKTIFFGeneratorParametersC07defaultF0ACvpZ","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultParameters","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFGeneratorParameters","text":"SBSDKTIFFGeneratorParameters","kind":"typeIdentifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultParameters","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFGeneratorParameters","text":"SBSDKTIFFGeneratorParameters","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGeneratorParameters"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgeneratorparameters\/defaultparameters"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGeneratorParameters"]]},"abstract":[{"type":"text","text":"The default parameters for TIFF generating."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGeneratorParameters\/defaultParameters"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFGeneratorParameters":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"abstract":[{"text":"TIFF generator parameters.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgeneratorparameters","title":"SBSDKTIFFGeneratorParameters","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGeneratorParameters","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFGeneratorParameters/defaultParameters":{"abstract":[{"text":"The default parameters for TIFF generating.","type":"text"}],"role":"symbol","title":"defaultParameters","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgeneratorparameters\/defaultparameters","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKTIFFGeneratorParameters","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFGeneratorParameters"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGeneratorParameters\/defaultParameters","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGeneratorParameters\/title","value":"SBSDKTIFFGeneratorParameters","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGeneratorParameters\/fragments","value":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGeneratorParameters\/navigatorTitle","value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"op":"replace"}]}]}