{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(generateFromScannedDocument:toFile:completion:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scannedDocument"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","text":"SBSDKScannedDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fileURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?) -> ())"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The document to convert to a TIFF file.","type":"text"}]}],"name":"scannedDocument"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The file URL to save the TIFF file at. If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":"the default TIFF location of the scanned document will be used.","type":"text"}]}],"name":"fileURL"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handler that is being called upon completion of the operation and passes the file url or nil otherwise."}]}],"name":"completion"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:to:completion:)-37q5c"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:to:completion:)-37q5c"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator\/generate(from:to:completion:)-37q5c","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator"]]},"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","kind":"typeIdentifier","text":"SBSDKScannedDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?) -> ())"}],"navigatorTitle":[{"text":"generateFromScannedDocument:toFile:completion:","kind":"identifier"}],"title":"generate(from:to:completion:)","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGenerator(im)generateFromScannedDocument:toFile:completion:"},"sections":[],"abstract":[{"type":"text","text":"Asynchronously converts the scanned document to a multipage-TIFF file and saves it to the specified URL."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGenerator":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffgenerator","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator","type":"topic","navigatorTitle":[{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"abstract":[{"text":"A class that converts images to (multipage) TIFF images.","type":"text"},{"text":" ","type":"text"},{"text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc.","type":"text"},{"text":" ","type":"text"},{"text":"When passing an encrypter the generated TIFF images will be encrypted.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"title":"SBSDKTIFFGenerator"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedDocument","kind":"identifier"}],"kind":"symbol","title":"SBSDKScannedDocument","type":"topic","abstract":[{"type":"text","text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages."}],"navigatorTitle":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGenerator/generate(from:to:completion:)-37q5c":{"url":"\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:to:completion:)-37q5c","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator\/generate(from:to:completion:)-37q5c","role":"symbol","title":"generate(from:to:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?) -> ())","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"generateFromScannedDocument:toFile:completion:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Asynchronously converts the scanned document to a multipage-TIFF file and saves it to the specified URL."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"generateFromScannedDocument:toFile:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"generateFromScannedDocument:toFile:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"generateFromScannedDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument"},{"text":" *) ","kind":"text"},{"text":"scannedDocument","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"toFile:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fileURL","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"scannedDocument","content":[{"type":"paragraph","inlineContent":[{"text":"The document to convert to a TIFF file.","type":"text"}]}]},{"name":"fileURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The file URL to save the TIFF file at. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"the default TIFF location of the scanned document will be used."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"The completion handler that is being called upon completion of the operation and passes the file url or nil otherwise.","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/title","value":"SBSDKTIFFGenerator","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/fragments","value":[{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/navigatorTitle","value":[{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/title","value":"SBSDKScannedDocument","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/fragments","value":[{"kind":"identifier","text":"SBSDKScannedDocument"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/navigatorTitle","value":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator~1generate(from:to:completion:)-37q5c\/title","value":"generateFromScannedDocument:toFile:completion:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator~1generate(from:to:completion:)-37q5c\/fragments","value":[{"text":"- ","kind":"text"},{"text":"generateFromScannedDocument:toFile:completion:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}