{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBasicImageLoadOptions(im)copyWithZone:","role":"symbol","symbolKind":"method","title":"copyWithZone:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/copyWithZone:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBasicImageLoadOptions/copyWithZone:":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions\/copywithzone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/copyWithZone:","title":"copyWithZone:","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBasicImageLoadOptions":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBasicImageLoadOptions"}],"abstract":[{"type":"text","text":"Basic options for loading image."}],"title":"SBSDKBasicImageLoadOptions","url":"\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBasicImageLoadOptions"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions\/title","value":"SBSDKBasicImageLoadOptions","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions\/fragments","value":[{"kind":"identifier","text":"SBSDKBasicImageLoadOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions\/navigatorTitle","value":[{"text":"SBSDKBasicImageLoadOptions","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}