{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUserFieldDoubleValue\/hash","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuserfielddoublevalue\/hash"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUserFieldDoubleValue"]]},"sections":[],"metadata":{"fragments":[{"kind":"identifier","text":"hash"}],"roleHeading":"Instance Property","title":"hash","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUserFieldDoubleValue(py)hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"symbolKind":"property"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUserFieldDoubleValue/hash":{"fragments":[{"text":"hash","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","title":"hash","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuserfielddoublevalue\/hash","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUserFieldDoubleValue\/hash"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUserFieldDoubleValue":{"abstract":[{"type":"text","text":"Double value (TIFF_DOUBLE)."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUserFieldDoubleValue"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUserFieldDoubleValue"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuserfielddoublevalue","role":"symbol","type":"topic","kind":"symbol","title":"SBSDKUserFieldDoubleValue","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUserFieldDoubleValue"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUserFieldDoubleValue\/title","op":"replace","value":"SBSDKUserFieldDoubleValue"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUserFieldDoubleValue\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUserFieldDoubleValue"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUserFieldDoubleValue\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUserFieldDoubleValue","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}