{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextButtonMode\/copyWithZone:"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2textbuttonmode\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone","text":"_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextButtonMode(im)copyWithZone:","title":"copyWithZone:","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextButtonMode"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextButtonMode/copyWithZone:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2textbuttonmode\/copywithzone:","abstract":[],"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"title":"copyWithZone:","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextButtonMode\/copyWithZone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextButtonMode":{"url":"\/documentation\/scanbotsdk\/sbsdkui2textbuttonmode","abstract":[{"text":"Configuration of the ‘preview’ button in ‘text button mode’.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextButtonMode","kind":"identifier"}],"title":"SBSDKUI2TextButtonMode","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextButtonMode","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2TextButtonMode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextButtonMode\/title","value":"SBSDKUI2TextButtonMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextButtonMode\/fragments","value":[{"text":"SBSDKUI2TextButtonMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextButtonMode\/navigatorTitle","value":[{"text":"SBSDKUI2TextButtonMode","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}