{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextButtonMode\/toJson(configuration:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextButtonMode"]]},"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"metadata":{"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextButtonMode(im)toJsonWithConfiguration:","symbolKind":"method","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"toJson(configuration:)"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":" = SBSDKToJSONConfiguration()) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textbuttonmode\/tojson(configuration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textbuttonmode\/tojson(configuration:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextButtonMode":{"url":"\/documentation\/scanbotsdk\/sbsdkui2textbuttonmode","abstract":[{"text":"Configuration of the ‘preview’ button in ‘text button mode’.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextButtonMode","kind":"identifier"}],"title":"SBSDKUI2TextButtonMode","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextButtonMode","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2TextButtonMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextButtonMode/toJson(configuration:)":{"navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2textbuttonmode\/tojson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"title":"toJson(configuration:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextButtonMode\/toJson(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKToJSONConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdktojsonconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration used to serialize an object to json."}],"title":"SBSDKToJSONConfiguration","navigatorTitle":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKToJSONConfiguration","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"toJsonWithConfiguration:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUI2TextButtonMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextButtonMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2TextButtonMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextButtonMode\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2TextButtonMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextButtonMode\/navigatorTitle"},{"op":"replace","value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextButtonMode~1toJson(configuration:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextButtonMode~1toJson(configuration:)\/fragments"},{"op":"replace","value":"SBSDKToJSONConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKToJSONConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKToJSONConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKToJSONConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}