{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installedLanguagesFolderURL"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRLanguagesManager(cpy)installedLanguagesFolderURL","navigatorTitle":[{"kind":"identifier","text":"installedLanguagesFolderURL"}],"fragments":[{"kind":"identifier","text":"installedLanguagesFolderURL"}],"roleHeading":"Type Property","title":"installedLanguagesFolderURL","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/installedlanguagesfolderurl"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"installedLanguagesFolderURL","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/installedLanguagesFolderURL":{"url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/installedlanguagesfolderurl","fragments":[{"text":"installedLanguagesFolderURL","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installedLanguagesFolderURL","type":"topic","title":"installedLanguagesFolderURL","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager","abstract":[{"type":"text","text":"Helper class to manage trained data files for the Tesseract OCR engine."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager","role":"symbol","type":"topic","title":"SBSDKOCRLanguagesManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCRLanguagesManager","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKOCRLanguagesManager","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKOCRLanguagesManager","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKOCRLanguagesManager"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager\/fragments","op":"replace"},{"value":[{"text":"SBSDKOCRLanguagesManager","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager\/navigatorTitle","op":"replace"}]}]}