{"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog(py)modalOverlayColor","title":"modalOverlayColor","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"modalOverlayColor","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"modalOverlayColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"}]},"abstract":[{"type":"text","text":"The dialog overlay color."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ScanbotAlertDialog\/modalOverlayColor","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2scanbotalertdialog\/modaloverlaycolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2scanbotalertdialog\/modaloverlaycolor"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ScanbotAlertDialog"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"modalOverlayColor","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Default is “?sbColorModalOverlay”","type":"text"}]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Color":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2color","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","title":"SBSDKUI2Color","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ScanbotAlertDialog":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ScanbotAlertDialog","title":"SBSDKUI2ScanbotAlertDialog","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2scanbotalertdialog","abstract":[{"type":"text","text":"Configuration of the standard alert dialog."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ScanbotAlertDialog/modalOverlayColor":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2scanbotalertdialog\/modaloverlaycolor","navigatorTitle":[{"kind":"identifier","text":"modalOverlayColor"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ScanbotAlertDialog\/modalOverlayColor","abstract":[{"text":"The dialog overlay color.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"modalOverlayColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"}],"type":"topic","title":"modalOverlayColor"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"modalOverlayColor","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"modalOverlayColor"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"modalOverlayColor"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/fragments","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Color"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ScanbotAlertDialog\/title","value":"SBSDKUI2ScanbotAlertDialog"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ScanbotAlertDialog\/fragments","value":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ScanbotAlertDialog\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ScanbotAlertDialog~1modalOverlayColor\/title","value":"modalOverlayColor"},{"value":[{"text":"modalOverlayColor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ScanbotAlertDialog~1modalOverlayColor\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}