{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult\/hash","interfaceLanguage":"occ"},"metadata":{"title":"hash","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult(py)hash","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"hash","kind":"identifier"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanningResult/hash":{"abstract":[],"fragments":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult\/hash","title":"hash","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult\/hash","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanningResult":{"title":"SBSDKMedicalCertificateScanningResult","kind":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The result of the medical certificate scanning."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateScanningResult"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/title","value":"SBSDKMedicalCertificateScanningResult","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/fragments","value":[{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScanningResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/navigatorTitle"}]}]}