{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(medicalCertificateScannerViewController:didFailScanningWithError:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"medicalCertificateScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController","text":"SBSDKMedicalCertificateScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailScanning"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"The medical certificate scanner view controller which failed scanning."}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"text":"The error that occurred during scanning.","type":"text"}],"type":"paragraph"}]}]}],"abstract":[{"type":"text","text":"Informs the delegate, that the medical certificate scanner has failed scanning a medical certificate."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontrollerdelegate\/medicalcertificatescannerviewcontroller(_:didfailscanning:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontrollerdelegate\/medicalcertificatescannerviewcontroller(_:didfailscanning:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewControllerDelegate\/medicalCertificateScannerViewController(_:didFailScanning:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewControllerDelegate"]]},"metadata":{"navigatorTitle":[{"text":"medicalCertificateScannerViewController:didFailScanningWithError:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"required":true,"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKMedicalCertificateScannerViewControllerDelegate(im)medicalCertificateScannerViewController:didFailScanningWithError:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"medicalCertificateScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMedicalCertificateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailScanning","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"medicalCertificateScannerViewController(_:didFailScanning:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewControllerDelegate":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewControllerDelegate","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontrollerdelegate","type":"topic","title":"SBSDKMedicalCertificateScannerViewControllerDelegate","abstract":[{"type":"text","text":"The delegation protocol for the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController"},{"type":"text","text":" class."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerViewControllerDelegate","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewControllerDelegate/medicalCertificateScannerViewController(_:didFailScanning:)":{"required":true,"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontrollerdelegate\/medicalcertificatescannerviewcontroller(_:didfailscanning:)","kind":"symbol","abstract":[{"type":"text","text":"Informs the delegate, that the medical certificate scanner has failed scanning a medical certificate."}],"role":"symbol","navigatorTitle":[{"text":"medicalCertificateScannerViewController:didFailScanningWithError:","kind":"identifier"}],"title":"medicalCertificateScannerViewController(_:didFailScanning:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"medicalCertificateScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMedicalCertificateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailScanning","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewControllerDelegate\/medicalCertificateScannerViewController(_:didFailScanning:)","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController":{"kind":"symbol","abstract":[{"text":"The classic UI view controller that can be used to detect and scan medical certificates. Can be configured to scan on video frames or,","type":"text"},{"text":" ","type":"text"},{"text":"for better accuracy, on high-res photos that are automatically captured.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}],"role":"symbol","title":"SBSDKMedicalCertificateScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"medicalCertificateScannerViewController:didFailScanningWithError:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"medicalCertificateScannerViewController:didFailScanningWithError:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"medicalCertificateScannerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMedicalCertificateScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didFailScanningWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The medical certificate scanner view controller which failed scanning.","type":"text"}],"type":"paragraph"}],"name":"controller"},{"content":[{"inlineContent":[{"type":"text","text":"The error that occurred during scanning."}],"type":"paragraph"}],"name":"error"}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewControllerDelegate\/title","op":"replace","value":"SBSDKMedicalCertificateScannerViewControllerDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewControllerDelegate\/fragments","op":"replace","value":[{"text":"SBSDKMedicalCertificateScannerViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"text":"SBSDKMedicalCertificateScannerViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewControllerDelegate~1medicalCertificateScannerViewController(_:didFailScanning:)\/title","op":"replace","value":"medicalCertificateScannerViewController:didFailScanningWithError:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewControllerDelegate~1medicalCertificateScannerViewController(_:didFailScanning:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"medicalCertificateScannerViewController:didFailScanningWithError:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/title","op":"replace","value":"SBSDKMedicalCertificateScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}