{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize"]]},"sections":[],"abstract":[{"type":"text","text":"176 x 250 (mm)           498.898 x 708.661 (pixels) at 72 DPI."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/b5","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagesize\/b5"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagesize\/b5"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"b5"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSizeB5"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"b5"}],"role":"symbol","title":"SBSDKPageSize.b5","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKPageSize@SBSDKPageSizeB5","symbolKind":"case","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/b5":{"url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/b5","title":"SBSDKPageSize.b5","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/b5","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"b5"}],"abstract":[{"text":"176 x 250 (mm)           498.898 x 708.661 (pixels) at 72 DPI.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSizeB5"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize":{"title":"SBSDKPageSize","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize","url":"\/documentation\/scanbotsdk\/sbsdkpagesize","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageSize","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPageSize","kind":"identifier"}],"abstract":[{"type":"text","text":"Page size."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKPageSizeB5","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKPageSizeB5"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKPageSizeB5","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1b5\/title","value":"SBSDKPageSizeB5","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1b5\/fragments","value":[{"kind":"identifier","text":"SBSDKPageSizeB5"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/title","value":"SBSDKPageSize"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/fragments","value":[{"kind":"identifier","text":"SBSDKPageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/navigatorTitle","value":[{"text":"SBSDKPageSize","kind":"identifier"}]}]}]}