{"metadata":{"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"contains"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"aspectRatio"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio","kind":"typeIdentifier","text":"SBSDKAspectRatio"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"containsAspectRatio:","kind":"identifier"}],"role":"symbol","title":"contains(aspectRatio:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatioRange(im)containsAspectRatio:","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(containsAspectRatio:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contains"},{"kind":"text","text":"("},{"kind":"externalParam","text":"aspectRatio"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio","text":"SBSDKAspectRatio","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"aspectRatio","content":[{"type":"paragraph","inlineContent":[{"text":"The aspect ratio to be checked for containment.","type":"text"}]}]}]},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":""},{"code":"True","type":"codeVoice"},{"text":", if the aspect ration is within the bounds of the receiver. ","type":"text"},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatioRange\/contains(aspectRatio:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Checks whether the given aspect ratio is within the bounds of the receiver"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkaspectratiorange\/contains(aspectratio:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkaspectratiorange\/contains(aspectratio:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatioRange"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAspectRatioRange/contains(aspectRatio:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatioRange\/contains(aspectRatio:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contains"},{"text":"(","kind":"text"},{"text":"aspectRatio","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKAspectRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"containsAspectRatio:"}],"title":"contains(aspectRatio:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkaspectratiorange\/contains(aspectratio:)","abstract":[{"type":"text","text":"Checks whether the given aspect ratio is within the bounds of the receiver"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAspectRatio":{"navigatorTitle":[{"text":"SBSDKAspectRatio","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKAspectRatio","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio","kind":"symbol","type":"topic","title":"SBSDKAspectRatio","abstract":[{"type":"text","text":"A class that describes an aspect ratio for a document page."}],"url":"\/documentation\/scanbotsdk\/sbsdkaspectratio"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAspectRatioRange":{"url":"\/documentation\/scanbotsdk\/sbsdkaspectratiorange","kind":"symbol","abstract":[{"text":"A class that represents a range of aspect ratios.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatioRange","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKAspectRatioRange","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAspectRatioRange"}],"title":"SBSDKAspectRatioRange"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"containsAspectRatio:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"containsAspectRatio:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"containsAspectRatio:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKAspectRatio","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aspectRatio"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"containsAspectRatio:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatioRange~1contains(aspectRatio:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"containsAspectRatio:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatioRange~1contains(aspectRatio:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/title","value":"SBSDKAspectRatio","op":"replace"},{"value":[{"text":"SBSDKAspectRatio","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/fragments","op":"replace"},{"value":"SBSDKAspectRatioRange","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatioRange\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatioRange\/fragments","value":[{"kind":"identifier","text":"SBSDKAspectRatioRange"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}