{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerUIResult"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithItems:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<SBSDKUI2BarcodeScannerUIItem *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"items"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerUIResult\/initWithItems:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescanneruiresult\/initwithitems:"]}],"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerUIResult(im)initWithItems:","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"text":"initWithItems:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithItems:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"title":"initWithItems:","role":"symbol"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerUIResult":{"abstract":[{"type":"text","text":"Results of the barcode scan."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescanneruiresult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeScannerUIResult","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerUIResult","kind":"identifier"}],"title":"SBSDKUI2BarcodeScannerUIResult","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerUIResult","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerUIResult/initWithItems:":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescanneruiresult\/initwithitems:","fragments":[{"kind":"text","text":"- "},{"text":"initWithItems:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithItems:"}],"kind":"symbol","title":"initWithItems:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerUIResult\/initWithItems:","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerUIResult\/title","value":"SBSDKUI2BarcodeScannerUIResult"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerUIResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerUIResult\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerUIResult\/navigatorTitle","value":[{"text":"SBSDKUI2BarcodeScannerUIResult","kind":"identifier"}],"op":"replace"}]}]}