{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBrightnessFilter"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBrightnessFilter\/initWithBrightness:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithBrightness:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"brightness","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbrightnessfilter\/initwithbrightness:"]}],"metadata":{"title":"initWithBrightness:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithBrightness:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"initWithBrightness:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBrightnessFilter(im)initWithBrightness:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBrightnessFilter":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBrightnessFilter","kind":"symbol","abstract":[{"type":"text","text":"Brightness adjustment filter."}],"url":"\/documentation\/scanbotsdk\/sbsdkbrightnessfilter","role":"symbol","title":"SBSDKBrightnessFilter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBrightnessFilter","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBrightnessFilter","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBrightnessFilter/initWithBrightness:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithBrightness:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithBrightness:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBrightnessFilter\/initWithBrightness:","title":"initWithBrightness:","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbrightnessfilter\/initwithbrightness:","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKBrightnessFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBrightnessFilter\/title"},{"op":"replace","value":[{"text":"SBSDKBrightnessFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBrightnessFilter\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBrightnessFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBrightnessFilter\/navigatorTitle"}]}]}