{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration"]]},"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:"}],"symbolKind":"method","title":"initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration(im)initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithAttributes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKPDFAttributes","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFAttributes"},{"text":" *) ","kind":"text"},{"text":"attributes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pageSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageSize","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageSize"},{"text":") ","kind":"text"},{"text":"pageSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pageDirection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageDirection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageDirection"},{"text":") ","kind":"text"},{"text":"pageDirection","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pageFit:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageFit","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageFit"},{"text":") ","kind":"text"},{"text":"pageFit","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dpi:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"dpi","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"jpegQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"jpegQuality","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"resamplingMethod:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKResamplingMethod","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKResamplingMethod"},{"text":") ","kind":"text"},{"text":"resamplingMethod","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/initwithattributes:pagesize:pagedirection:pagefit:dpi:jpegquality:resamplingmethod:"]}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/initwithattributes:pagesize:pagedirection:pagefit:dpi:jpegquality:resamplingmethod:","kind":"symbol","title":"initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:","navigatorTitle":[{"text":"initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes","abstract":[{"type":"text","text":"PDF attributes."}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFAttributes","kind":"identifier"}],"title":"SBSDKPDFAttributes","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKPDFAttributes","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod":{"kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKResamplingMethod","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod","abstract":[{"type":"text","text":"Resampling method."}],"title":"SBSDKResamplingMethod","navigatorTitle":[{"text":"SBSDKResamplingMethod","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize":{"role":"symbol","abstract":[{"type":"text","text":"Page size."}],"navigatorTitle":[{"text":"SBSDKPageSize","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagesize","title":"SBSDKPageSize","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageSize","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageFit":{"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit","kind":"symbol","abstract":[{"type":"text","text":"Page fit."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageFit"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageFit"}],"title":"SBSDKPageFit","url":"\/documentation\/scanbotsdk\/sbsdkpagefit"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}],"title":"SBSDKPDFConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration","abstract":[{"type":"text","text":"The parameters "},{"type":"codeVoice","code":"pageSize"},{"type":"text","text":", "},{"code":"pageFit","type":"codeVoice"},{"text":", ","type":"text"},{"code":"dpi","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"resamplingMethod","type":"codeVoice"},{"text":" interact in a complex way","type":"text"},{"text":" ","type":"text"},{"text":"when adding bitmap images (JPEG, PNG, or raw) to the PDF.","type":"text"},{"text":" ","type":"text"},{"text":"There are three cases to consider:","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageDirection":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageDirection","kind":"identifier"}],"title":"SBSDKPageDirection","url":"\/documentation\/scanbotsdk\/sbsdkpagedirection","navigatorTitle":[{"text":"SBSDKPageDirection","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Page direction."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/title","value":"SBSDKPDFAttributes"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/fragments","value":[{"text":"SBSDKPDFAttributes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/navigatorTitle","value":[{"text":"SBSDKPDFAttributes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/title","value":"SBSDKResamplingMethod"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/fragments","value":[{"text":"SBSDKResamplingMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKResamplingMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/title","value":"SBSDKPageSize"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/fragments","value":[{"text":"SBSDKPageSize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/navigatorTitle","value":[{"text":"SBSDKPageSize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/title","value":"SBSDKPageFit"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/fragments","value":[{"text":"SBSDKPageFit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPageFit"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/title","value":"SBSDKPDFConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection\/title","value":"SBSDKPageDirection"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection\/fragments","value":[{"text":"SBSDKPageDirection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPageDirection"}]}]}]}