{"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration(im)isEqual:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"symbolKind":"method","role":"symbol","title":"isEqual:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/isEqual:","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"object","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/isEqual:":{"abstract":[],"title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/isequal:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration","abstract":[{"text":"The parameters ","type":"text"},{"type":"codeVoice","code":"pageSize"},{"type":"text","text":", "},{"type":"codeVoice","code":"pageFit"},{"type":"text","text":", "},{"type":"codeVoice","code":"dpi"},{"type":"text","text":" and "},{"type":"codeVoice","code":"resamplingMethod"},{"type":"text","text":" interact in a complex way"},{"text":" ","type":"text"},{"text":"when adding bitmap images (JPEG, PNG, or raw) to the PDF.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"There are three cases to consider:"}],"title":"SBSDKPDFConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKPDFConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/navigatorTitle"}]}]}