{"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/init(fpsCount:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/fpsCount","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/frameDuration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/framesSkipped","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/framesTotal","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/throttleRate"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/isReadyForNextFrame()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFrameLimiter"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"For example: a camera device captures video frames with 60 frames per second and passes them to a scanner."},{"type":"text","text":" "},{"type":"text","text":"Use this class to limit the number of scanner runs to a smaller value, like 20 frames per second,"},{"type":"text","text":" "},{"type":"text","text":"ignoring the other 40 frames per second. The frames to be detected are evenly distributed over time."},{"type":"text","text":" "},{"type":"text","text":"As the scanner needs lots of CPU power, this limiter can drastically"},{"type":"text","text":" "},{"type":"text","text":"reduce CPU usage and therefore save battery."}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFrameLimiter","kind":"identifier"}],"title":"SBSDKFrameLimiter","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFrameLimiter","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKFrameLimiter","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkframelimiter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkframelimiter"]}],"abstract":[{"text":"A frame limiter class. An object can use this class to limit the number of events fired per second.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFrameLimiter/isReadyForNextFrame()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isReadyForNextFrame","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/isReadyForNextFrame()","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkframelimiter\/isreadyfornextframe()","abstract":[{"text":"Returns wether the next frame should be processed or not. Call this method consecutively each frame and process the frame if the result was ","type":"text"},{"type":"codeVoice","code":"true"},{"text":". Otherwise skip the frame processing.","type":"text"}],"kind":"symbol","role":"symbol","title":"isReadyForNextFrame()","navigatorTitle":[{"text":"isReadyForNextFrame","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFrameLimiter/throttleRate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/throttleRate","url":"\/documentation\/scanbotsdk\/sbsdkframelimiter\/throttlerate","title":"throttleRate","navigatorTitle":[{"kind":"identifier","text":"throttleRate"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throttleRate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"The percentual ratio of skipped frames to total frames since the receivers start."}],"type":"topic"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFrameLimiter/frameDuration":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frameDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/frameDuration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkframelimiter\/frameduration","abstract":[{"text":"The minimum time in seconds that must pass by before processing the next frame (1.0 \/ fpsCount).","type":"text"}],"kind":"symbol","role":"symbol","title":"frameDuration","navigatorTitle":[{"text":"frameDuration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFrameLimiter/init(fpsCount:)":{"role":"symbol","type":"topic","title":"init(fpsCount:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/init(fpsCount:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fpsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a new instance of the frame limiter."}],"url":"\/documentation\/scanbotsdk\/sbsdkframelimiter\/init(fpscount:)","navigatorTitle":[{"kind":"identifier","text":"initWithFPSCount:"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFrameLimiter":{"type":"topic","abstract":[{"text":"A frame limiter class. An object can use this class to limit the number of events fired per second.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkframelimiter","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFrameLimiter","kind":"identifier"}],"title":"SBSDKFrameLimiter","kind":"symbol","navigatorTitle":[{"text":"SBSDKFrameLimiter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFrameLimiter/fpsCount":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fpsCount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/fpsCount","title":"fpsCount","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkframelimiter\/fpscount","abstract":[{"type":"text","text":"The desired frame rate in frames per second."}],"kind":"symbol","navigatorTitle":[{"text":"fpsCount","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFrameLimiter/framesSkipped":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"framesSkipped"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"url":"\/documentation\/scanbotsdk\/sbsdkframelimiter\/framesskipped","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/framesSkipped","type":"topic","kind":"symbol","abstract":[{"text":"The total number of frames the receiver skipped since it started.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"framesSkipped"}],"role":"symbol","title":"framesSkipped"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFrameLimiter/framesTotal":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"framesTotal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"kind":"symbol","title":"framesTotal","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/framesTotal","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkframelimiter\/framestotal","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"framesTotal"}],"abstract":[{"text":"The total number of frames the receiver registered since it started.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKFrameLimiter","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKFrameLimiter","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFrameLimiter"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/fpsCount","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/frameDuration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/framesSkipped","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/framesTotal","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/throttleRate"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/init(fpsCount:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/isReadyForNextFrame()"],"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFrameLimiter"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1isReadyForNextFrame()\/title","value":"isReadyForNextFrame","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isReadyForNextFrame"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1isReadyForNextFrame()\/fragments"},{"value":"throttleRate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1throttleRate\/title"},{"value":[{"kind":"identifier","text":"throttleRate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1throttleRate\/fragments"},{"value":"frameDuration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1frameDuration\/title"},{"value":[{"text":"frameDuration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1frameDuration\/fragments"},{"value":"initWithFPSCount:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1init(fpsCount:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFPSCount:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1init(fpsCount:)\/fragments"},{"value":"SBSDKFrameLimiter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter\/title"},{"value":[{"kind":"identifier","text":"SBSDKFrameLimiter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter\/fragments"},{"value":[{"text":"SBSDKFrameLimiter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter\/navigatorTitle"},{"value":"fpsCount","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1fpsCount\/title"},{"value":[{"kind":"identifier","text":"fpsCount"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1fpsCount\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1framesSkipped\/title","op":"replace","value":"framesSkipped"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1framesSkipped\/fragments","op":"replace","value":[{"text":"framesSkipped","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1framesTotal\/title","op":"replace","value":"framesTotal"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1framesTotal\/fragments","op":"replace","value":[{"kind":"identifier","text":"framesTotal"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}