{"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/quality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/speed"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"text":"The prioritization of still image quality and capturing speed.","type":"text"}],"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Enumeration","symbolKind":"enum","title":"SBSDKCapturePhotoQualityPrioritization","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKCapturePhotoQualityPrioritization","navigatorTitle":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/RawRepresentable-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization\/rawrepresentable-implementations","type":"topic","role":"collectionGroup","abstract":[],"title":"RawRepresentable Implementations","kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization/quality":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/quality","url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization\/quality","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationQuality"}],"role":"symbol","abstract":[{"text":"Captures a still image with the best possible quality in terms of noise, frozen motion and detail in low light.","type":"text"},{"text":" ","type":"text"},{"text":"The speed of the capturing might be significantly reduced.","type":"text"}],"title":"SBSDKCapturePhotoQualityPrioritization.quality","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization/balanced":{"url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization\/balanced","role":"symbol","title":"SBSDKCapturePhotoQualityPrioritization.balanced","abstract":[{"type":"text","text":"Balances capturing speed and image quality equally. This is the default value."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"balanced"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","navigatorTitle":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationBalanced"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization/speed":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"speed"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationSpeed"}],"url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization\/speed","abstract":[{"type":"text","text":"Captures a still image at the highest possible speed. The quality of the image may be degraded."}],"kind":"symbol","title":"SBSDKCapturePhotoQualityPrioritization.speed","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/speed"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"kind":"symbol","title":"SBSDKCapturePhotoQualityPrioritization","navigatorTitle":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization","abstract":[{"text":"The prioritization of still image quality and capturing speed.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization\/equatable-implementations","title":"Equatable Implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/Equatable-Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization/init(rawValue:)":{"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization\/init(rawvalue:)","title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKCapturePhotoQualityPrioritization"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/quality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/speed"],"anchor":"Enumeration-Cases","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization~1quality\/title","op":"replace","value":"SBSDKCapturePhotoQualityPrioritizationQuality"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization~1quality\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationQuality"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization~1balanced\/title","op":"replace","value":"SBSDKCapturePhotoQualityPrioritizationBalanced"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization~1balanced\/fragments","op":"replace","value":[{"text":"SBSDKCapturePhotoQualityPrioritizationBalanced","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization~1speed\/title","op":"replace","value":"SBSDKCapturePhotoQualityPrioritizationSpeed"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization~1speed\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationSpeed"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization\/title","op":"replace","value":"SBSDKCapturePhotoQualityPrioritization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}