{"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCREngineConfiguration"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/init()"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/languages","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/recognitionMode"]},{"anchor":"Type-Methods","generated":true,"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/scanbotOCR()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/tesseract(with:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/tesseract(withLanguageString:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"text":"A class describing the configuration of the optical character recognizer (OCR) engine.","type":"text"}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCREngineConfiguration"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration","symbolKind":"class","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKOCREngineConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCREngineConfiguration"}],"roleHeading":"Class"},"references":{"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineConfiguration/languages":{"navigatorTitle":[{"kind":"identifier","text":"languages"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"languages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"An array of two-letter ISO 639-1 language code strings that are being used by the character recognizer."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration\/languages","title":"languages","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/languages","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineConfiguration/tesseract(withLanguageString:)":{"navigatorTitle":[{"text":"tesseractWithLanguageString:","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tesseract"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLanguageString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKOCREngineConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration"}],"abstract":[{"type":"text","text":"Creates an OCR configuration using the mode "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/tesseract","type":"reference"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration\/tesseract(withlanguagestring:)","title":"tesseract(withLanguageString:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/tesseract(withLanguageString:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineConfiguration/copyWithZone:":{"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration\/copywithzone:","title":"copyWithZone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/copyWithZone:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineMode/scanbotOCR":{"url":"\/documentation\/scanbotsdk\/sbsdkocrenginemode\/scanbotocr","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/scanbotOCR","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanbotOCR"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCREngineModeScanbotOCR"}],"title":"SBSDKOCREngineMode.scanbotOCR","role":"symbol","abstract":[{"type":"text","text":"The new machine-learning based mode made by Scanbot SDK GmbH. Faster, less errors, but currently only"},{"type":"text","text":" "},{"type":"text","text":"supports languages with latin letters."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineConfiguration/init()":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Designated initializer."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration\/init()","title":"init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/init()","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineMode/tesseract":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKOCREngineModeTesseract"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tesseract"}],"abstract":[{"type":"text","text":"The legacy OCR mode using Tesseract. Slower, more error prone, but it supports more languages."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrenginemode\/tesseract","title":"SBSDKOCREngineMode.tesseract","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/tesseract","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineConfiguration/scanbotOCR()":{"title":"scanbotOCR()","navigatorTitle":[{"kind":"identifier","text":"scanbotOCR"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanbotOCR"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKOCREngineConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/scanbotOCR()","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration\/scanbotocr()","abstract":[{"type":"text","text":"Creates an OCR configuration using the mode "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/scanbotOCR","type":"reference"},{"type":"text","text":"."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineConfiguration/recognitionMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/recognitionMode","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognitionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKOCREngineMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOCREngineMode"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The recognition mode."}],"title":"recognitionMode","url":"\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration\/recognitionmode","navigatorTitle":[{"kind":"identifier","text":"recognitionMode"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineConfiguration/tesseract(with:)":{"url":"\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration\/tesseract(with:)","abstract":[{"type":"text","text":"Creates an OCR configuration using the mode "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/tesseract","type":"reference"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","title":"tesseract(with:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tesseract"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"SBSDKOCREngineConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/tesseract(with:)","navigatorTitle":[{"kind":"identifier","text":"tesseractWith:"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCREngineConfiguration"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A class describing the configuration of the optical character recognizer (OCR) engine."}],"title":"SBSDKOCREngineConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCREngineConfiguration"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKOCREngineConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKOCREngineConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKOCREngineConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/languages","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/recognitionMode"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/init()"],"anchor":"Instance-Methods"},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/scanbotOCR()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/tesseract(with:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/tesseract(withLanguageString:)"],"anchor":"Type-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCREngineConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration~1languages\/title","value":"languages"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration~1languages\/fragments","value":[{"text":"languages","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration~1tesseract(withLanguageString:)\/title","value":"tesseractWithLanguageString:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration~1tesseract(withLanguageString:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"tesseractWithLanguageString:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode~1scanbotOCR\/title","value":"SBSDKOCREngineModeScanbotOCR"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode~1scanbotOCR\/fragments","value":[{"kind":"identifier","text":"SBSDKOCREngineModeScanbotOCR"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration~1init()\/title","value":"init"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration~1init()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode~1tesseract\/title","op":"replace","value":"SBSDKOCREngineModeTesseract"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode~1tesseract\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKOCREngineModeTesseract"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration~1scanbotOCR()\/title","op":"replace","value":"scanbotOCR"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration~1scanbotOCR()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"scanbotOCR"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration~1recognitionMode\/title","op":"replace","value":"recognitionMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration~1recognitionMode\/fragments","op":"replace","value":[{"text":"recognitionMode","kind":"identifier"}]},{"op":"replace","value":"tesseractWith:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration~1tesseract(with:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"tesseractWith:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration~1tesseract(with:)\/fragments"},{"value":"SBSDKOCREngineConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKOCREngineConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration\/fragments"},{"value":[{"text":"SBSDKOCREngineConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration\/navigatorTitle"}]}]}