{"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/aspectRatio","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/minimumInsets","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/overlayColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/preferredHeight","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/style"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/permanentViewFinderConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/viewFinderConfiguration()"],"generated":true,"anchor":"Type-Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BaseViewFinderConfiguration"}],"roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BaseViewFinderConfiguration","role":"symbol","symbolKind":"class","title":"SBSDKUI2BaseViewFinderConfiguration"},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"type":"inheritsFrom","kind":"relationships"},{"title":"Inherited By","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PermanentViewFinderConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration"],"type":"inheritedBy","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"abstract":[{"type":"text","text":"Base configuration of the scanning interface’s viewfinder, serving as guidance to the user."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2BaseViewFinderConfiguration) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration/isEqual:":{"title":"isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/isequal:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/isEqual:","role":"symbol","type":"topic","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration/copyWithZone:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/copyWithZone:","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/copywithzone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration":{"abstract":[{"text":"Base configuration of the scanning interface’s viewfinder, serving as guidance to the user.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration","navigatorTitle":[{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration","title":"SBSDKUI2BaseViewFinderConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration/aspectRatio":{"title":"aspectRatio","type":"topic","abstract":[{"type":"text","text":"The viewfinder’s aspect ratio."}],"navigatorTitle":[{"kind":"identifier","text":"aspectRatio"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/aspectRatio","url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/aspectratio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"aspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio","text":"SBSDKAspectRatio"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration/style":{"title":"style","navigatorTitle":[{"text":"style","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2FinderStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FinderStyle"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/style","abstract":[{"text":"The visual appearance of the viewfinder.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/style","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ViewFinderConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2viewfinderconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ViewFinderConfiguration"}],"abstract":[{"text":"Configuration of the scanning interface’s viewfinder, allowing it to be shown or hidden as guidance to the user.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ViewFinderConfiguration"}],"role":"symbol","type":"topic","title":"SBSDKUI2ViewFinderConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration/preferredHeight":{"navigatorTitle":[{"kind":"identifier","text":"preferredHeight"}],"abstract":[{"type":"text","text":"The preferred height of the viewfinder."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/preferredHeight","title":"preferredHeight","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/preferredheight"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration/hash":{"role":"symbol","title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/hash","abstract":[],"fragments":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/hash","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration/permanentViewFinderConfiguration()":{"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"permanentViewFinderConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/permanentviewfinderconfiguration()","title":"permanentViewFinderConfiguration()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"permanentViewFinderConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PermanentViewFinderConfiguration","text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/permanentViewFinderConfiguration()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PermanentViewFinderConfiguration":{"abstract":[{"type":"text","text":"Configuration of the scanning interface’s viewfinder, which is always visible to guide the user."}],"title":"SBSDKUI2PermanentViewFinderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2PermanentViewFinderConfiguration"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2permanentviewfinderconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PermanentViewFinderConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PermanentViewFinderConfiguration"}],"type":"topic"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration/minimumInsets":{"abstract":[{"text":"The minimum insets of the viewfinder.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumInsets","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2EdgeInsets","text":"SBSDKUI2EdgeInsets","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/minimumInsets","kind":"symbol","title":"minimumInsets","navigatorTitle":[{"text":"minimumInsets","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/minimuminsets"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration/fromJsonWithJson:":{"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/fromJsonWithJson:","abstract":[],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/fromjsonwithjson:","title":"fromJsonWithJson:","kind":"symbol","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration/viewFinderConfiguration()":{"navigatorTitle":[{"text":"viewFinderConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/viewFinderConfiguration()","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewFinderConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ViewFinderConfiguration","text":"SBSDKUI2ViewFinderConfiguration","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/viewfinderconfiguration()","title":"viewFinderConfiguration()","kind":"symbol","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration/toJson(configuration:)":{"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/tojson(configuration:)","title":"toJson(configuration:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/toJson(configuration:)","role":"symbol","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"abstract":[{"text":"Abstract class for all the configurations.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2node","title":"SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Node","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration/overlayColor":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/overlayColor","kind":"symbol","title":"overlayColor","url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/overlaycolor","navigatorTitle":[{"kind":"identifier","text":"overlayColor"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"overlayColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"}],"abstract":[{"text":"The color of the viewfinder overlay.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKUI2BaseViewFinderConfiguration","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/aspectRatio","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/minimumInsets","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/overlayColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/preferredHeight","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/style"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/toJson(configuration:)"],"anchor":"Instance-Methods","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/fromJsonWithJson:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/permanentViewFinderConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/viewFinderConfiguration()"],"anchor":"Type-Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PermanentViewFinderConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node","text":"SBSDKUI2Node","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUI2BaseViewFinderConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2BaseViewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration\/navigatorTitle","op":"replace"},{"value":"aspectRatio","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1aspectRatio\/title","op":"replace"},{"value":[{"kind":"identifier","text":"aspectRatio"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1aspectRatio\/fragments","op":"replace"},{"value":"style","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1style\/title","op":"replace"},{"value":[{"text":"style","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1style\/fragments","op":"replace"},{"value":"SBSDKUI2ViewFinderConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2ViewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration\/navigatorTitle","op":"replace"},{"value":"preferredHeight","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1preferredHeight\/title","op":"replace"},{"value":[{"text":"preferredHeight","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1preferredHeight\/fragments","op":"replace"},{"value":"permanentViewFinderConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1permanentViewFinderConfiguration()\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"permanentViewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1permanentViewFinderConfiguration()\/fragments","op":"replace"},{"value":"SBSDKUI2PermanentViewFinderConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PermanentViewFinderConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2PermanentViewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PermanentViewFinderConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2PermanentViewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PermanentViewFinderConfiguration\/navigatorTitle","op":"replace"},{"value":"minimumInsets","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1minimumInsets\/title","op":"replace"},{"value":[{"text":"minimumInsets","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1minimumInsets\/fragments","op":"replace"},{"value":"viewFinderConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1viewFinderConfiguration()\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"viewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1viewFinderConfiguration()\/fragments","op":"replace"},{"value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1toJson(configuration:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1toJson(configuration:)\/fragments","op":"replace"},{"value":"SBSDKUI2Node","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title","op":"replace"},{"value":[{"text":"SBSDKUI2Node","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Node"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/navigatorTitle","op":"replace"},{"value":"overlayColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1overlayColor\/title","op":"replace"},{"value":[{"text":"overlayColor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1overlayColor\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}