{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"type":"text","text":"Configuration for the VIN scanner."}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKVINScannerConfiguration) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVINScannerConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"class","role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVINScannerConfiguration"}],"title":"SBSDKVINScannerConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKVINScannerConfiguration"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/init()"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/extractVINFromBarcode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/maximumNumberOfAccumulatedFrames","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/minimumNumberOfRequiredFramesWithEqualScanningResult","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/ocrResolutionLimit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/optimizeSingleLine"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration/ocrResolutionLimit":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/ocrResolutionLimit","kind":"symbol","navigatorTitle":[{"text":"ocrResolutionLimit","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ocrResolutionLimit"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[{"text":"Maximum image size (height or width) for OCR process. 0 - do not rescale.","type":"text"}],"title":"ocrResolutionLimit","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/ocrresolutionlimit"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration/initWithOptimizeSingleLine:extractVINFromBarcode:ocrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOptimizeSingleLine:extractVINFromBarcode:ocrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/initwithoptimizesingleline:extractvinfrombarcode:ocrresolutionlimit:maximumnumberofaccumulatedframes:minimumnumberofrequiredframeswithequalscanningresult:","kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/initWithOptimizeSingleLine:extractVINFromBarcode:ocrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","title":"initWithOptimizeSingleLine:extractVINFromBarcode:ocrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithOptimizeSingleLine:extractVINFromBarcode:ocrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration/minimumNumberOfRequiredFramesWithEqualScanningResult":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualScanningResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/minimumnumberofrequiredframeswithequalscanningresult","navigatorTitle":[{"text":"minimumNumberOfRequiredFramesWithEqualScanningResult","kind":"identifier"}],"abstract":[{"type":"text","text":"Minimum number of accumulated frames that have equal result."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/minimumNumberOfRequiredFramesWithEqualScanningResult","type":"topic","kind":"symbol","title":"minimumNumberOfRequiredFramesWithEqualScanningResult","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration/toJson(configuration:)":{"title":"toJson(configuration:)","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/tojson(configuration:)","role":"symbol","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/toJson(configuration:)","kind":"symbol","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration/hash":{"fragments":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/hash","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/hash","type":"topic","kind":"symbol","title":"hash","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINScannerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration","navigatorTitle":[{"text":"SBSDKVINScannerConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Configuration for the VIN scanner."}],"title":"SBSDKVINScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration/copyWithZone:":{"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/copywithzone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/copyWithZone:","type":"topic","kind":"symbol","title":"copyWithZone:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration/init()":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/init()","type":"topic","kind":"symbol","title":"init()","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration/maximumNumberOfAccumulatedFrames":{"type":"topic","abstract":[{"type":"text","text":"Maximum number of accumulated frames to inspect before actual result is returned."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/maximumNumberOfAccumulatedFrames","title":"maximumNumberOfAccumulatedFrames","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/maximumnumberofaccumulatedframes","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration/optimizeSingleLine":{"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/optimizesingleline","kind":"symbol","title":"optimizeSingleLine","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optimizeSingleLine","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"optimizeSingleLine","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/optimizeSingleLine","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Optimize for scanning a single line or a single word. Enable this option when scanning a single line or single word that are hard to scan reliably."}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","role":"symbol","type":"topic","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration/isEqual:":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/isequal:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"abstract":[],"title":"isEqual:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration/extractVINFromBarcode":{"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/extractvinfrombarcode","type":"topic","title":"extractVINFromBarcode","kind":"symbol","abstract":[{"text":"If true, the VIN scanner will also extract VINs from barcodes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Requires a license that allows barcode scanning in addition to VIN scanning."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/extractVINFromBarcode","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extractVINFromBarcode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"extractVINFromBarcode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKVINScannerConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKVINScannerConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKVINScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/extractVINFromBarcode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/maximumNumberOfAccumulatedFrames","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/minimumNumberOfRequiredFramesWithEqualScanningResult","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/ocrResolutionLimit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/optimizeSingleLine"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/initWithOptimizeSingleLine:extractVINFromBarcode:ocrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/fromJsonWithJson:"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVINScannerConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ocrResolutionLimit","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration~1ocrResolutionLimit\/title"},{"value":[{"kind":"identifier","text":"ocrResolutionLimit"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration~1ocrResolutionLimit\/fragments"},{"value":"minimumNumberOfRequiredFramesWithEqualScanningResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration~1minimumNumberOfRequiredFramesWithEqualScanningResult\/title"},{"value":[{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration~1minimumNumberOfRequiredFramesWithEqualScanningResult\/fragments"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration~1toJson(configuration:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration~1toJson(configuration:)\/fragments"},{"value":"SBSDKVINScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKVINScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/fragments"},{"value":[{"text":"SBSDKVINScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/navigatorTitle"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration~1init()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration~1init()\/fragments"},{"value":"maximumNumberOfAccumulatedFrames","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration~1maximumNumberOfAccumulatedFrames\/title"},{"value":[{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration~1maximumNumberOfAccumulatedFrames\/fragments"},{"value":"optimizeSingleLine","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration~1optimizeSingleLine\/title"},{"value":[{"kind":"identifier","text":"optimizeSingleLine"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration~1optimizeSingleLine\/fragments"},{"value":"extractVINFromBarcode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration~1extractVINFromBarcode\/title"},{"value":[{"text":"extractVINFromBarcode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration~1extractVINFromBarcode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}