{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"text":"Field validation status.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKGenericDocumentFieldValidationStatus) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentFieldValidationStatus"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"inlineContent":[{"text":"Optical character recognition (OCR) invariably introduces errors in the recognized text.","type":"text"},{"text":" ","type":"text"},{"text":"There are numerous ways to verify that what has been recognized is, in fact, what was","type":"text"},{"text":" ","type":"text"},{"text":"written in the document.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The best way to validate the value of a field is for it to have a known format or validation"},{"type":"text","text":" "},{"type":"text","text":"logic. For example, an IBAN number has a known format and two check digits that make it"},{"type":"text","text":" "},{"type":"text","text":"very unlikely that a value with OCR errors will pass validation. Fields with known"},{"type":"text","text":" "},{"type":"text","text":"validation rules will have a validation status of either VALID or INVALID."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Fields whose value can be inferred from other fields, or from domain knowledge (for example,"},{"type":"text","text":" "},{"type":"text","text":"the field may have the same value in every instance of this type of document), will have the"},{"type":"text","text":" "},{"type":"text","text":"status INFERRED. Inferring the value of a field is a strong validation method, provided that"},{"type":"text","text":" "},{"type":"text","text":"there are no unexpected changes to the document format."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Fields that do not have validation rules and cannot be inferred can still be validated by checking whether the same"},{"type":"text","text":" "},{"type":"text","text":"value is recognized from multiple attempts, e.g. across multiple frames of a camera stream."},{"type":"text","text":" "},{"type":"text","text":"If the same value is recognized in multiple frames, the value is considered CONFIRMED, otherwise"},{"type":"text","text":" "},{"type":"text","text":"it will have the status NONE. This is the least strict validation method, as it does not protect"},{"type":"text","text":" "},{"type":"text","text":"from systemic OCR errors, but in practice it still provides good results for most fields."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentFieldValidationStatus"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentFieldValidationStatus"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","title":"SBSDKGenericDocumentFieldValidationStatus","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus","role":"symbol","roleHeading":"Class"},"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/rawValue"]},{"generated":true,"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/confirmed","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/ignored","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/inferred","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/invalid","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/none","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/obstructed","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/valid"]},{"generated":true,"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/enumValue(from:)"]}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldValidationStatus/hash":{"fragments":[{"kind":"identifier","text":"hash"}],"title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/hash","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/hash","kind":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldValidationStatus/valid":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/valid","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/valid","title":"valid","abstract":[{"text":"Field value passed validation. This status is used for fields that have validation rules, like","type":"text"},{"text":" ","type":"text"},{"text":"IBAN, date fields, etc. that have check digits or a known format that can be validated.","type":"text"},{"text":" ","type":"text"},{"text":"The VALID status gives the strongest guarantee that the field value has been read out without errors.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"valid"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"valid"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus","kind":"typeIdentifier","text":"SBSDKGenericDocumentFieldValidationStatus"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldValidationStatus/invalid":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/invalid","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/invalid","type":"topic","abstract":[{"type":"text","text":"Field value failed validation. This status is used for fields that have validation rules, like"},{"text":" ","type":"text"},{"text":"IBAN, date fields, etc. that have check digits or a known format that can be validated.","type":"text"}],"role":"symbol","kind":"symbol","title":"invalid","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus","kind":"typeIdentifier","text":"SBSDKGenericDocumentFieldValidationStatus"}],"navigatorTitle":[{"kind":"identifier","text":"invalid"}]},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldValidationStatus/none":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus","kind":"typeIdentifier","text":"SBSDKGenericDocumentFieldValidationStatus"}],"navigatorTitle":[{"kind":"identifier","text":"none"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/none","title":"none","abstract":[{"type":"text","text":"Field value was not validated, typically because the field does not support validation and the value"},{"text":" ","type":"text"},{"text":"has not been seen enough times to confirm it.","type":"text"},{"text":" ","type":"text"},{"text":"If the same value is seen in multiple frames, the validation status will transition to CONFIRMED,","type":"text"},{"text":" ","type":"text"},{"text":"but only if that particular recognizer supports multiple frame accumulation.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/none"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldValidationStatus/ignored":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/ignored","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignored"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus","kind":"typeIdentifier","text":"SBSDKGenericDocumentFieldValidationStatus"}],"navigatorTitle":[{"kind":"identifier","text":"ignored"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The document contains a field of this type, but recognition for this field is disabled."},{"text":" ","type":"text"},{"text":"The value of this field is always empty, although the field may be non-empty in the document.","type":"text"}],"title":"ignored","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/ignored","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldValidationStatus/inferred":{"title":"inferred","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/inferred","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/inferred","navigatorTitle":[{"kind":"identifier","text":"inferred"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"inferred"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus","kind":"typeIdentifier","text":"SBSDKGenericDocumentFieldValidationStatus"}],"abstract":[{"type":"text","text":"Field value was inferred from other fields or from domain knowledge."},{"type":"text","text":" "},{"text":"The field value may differ from what is actually written in the document in unexpected situations.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldValidationStatus/obstructed":{"abstract":[{"type":"text","text":"Field value was not recognized because it was obstructed by e.g. a light reflection or a shadow."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/obstructed","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"obstructed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus","text":"SBSDKGenericDocumentFieldValidationStatus"}],"navigatorTitle":[{"kind":"identifier","text":"obstructed"}],"type":"topic","title":"obstructed","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/obstructed","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldValidationStatus/enumValue(from:)":{"abstract":[{"type":"text","text":"Returns an instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus","isActive":true},{"type":"text","text":" based on the provided raw value."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enumValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentFieldValidationStatus","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus"},{"kind":"text","text":"?"}],"title":"enumValue(from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enumValueFrom:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/enumValue(from:)","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/enumvalue(from:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldValidationStatus/isEqual:":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/isequal:"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldValidationStatus/confirmed":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/confirmed","navigatorTitle":[{"kind":"identifier","text":"confirmed"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/confirmed","kind":"symbol","title":"confirmed","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmed"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus","kind":"typeIdentifier","text":"SBSDKGenericDocumentFieldValidationStatus"}],"abstract":[{"type":"text","text":"The same field value was recognized in multiple frames, thereby confirming the value."},{"text":" ","type":"text"},{"text":"Occurs only for fields that have no validation rules otherwise.","type":"text"},{"text":" ","type":"text"},{"text":"A CONFIRMED value gives a strong guarantee that the field value has been read out without errors,","type":"text"},{"text":" ","type":"text"},{"text":"but not as strong as VALID. The value may still be incorrect, due to systemic OCR errors.","type":"text"},{"text":" ","type":"text"},{"text":"In case of OCR errors, increase the number of frames needed to confirm the value in the","type":"text"},{"text":" ","type":"text"},{"text":"recognizer configuration.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldValidationStatus/rawValue":{"title":"rawValue","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/rawValue","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The raw value integer of the current "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"rawValue","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/rawvalue"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldValidationStatus":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentFieldValidationStatus"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus","title":"SBSDKGenericDocumentFieldValidationStatus","abstract":[{"text":"Field validation status.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentFieldValidationStatus"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKGenericDocumentFieldValidationStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentFieldValidationStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocumentFieldValidationStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/rawValue"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/isEqual:"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/confirmed","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/ignored","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/inferred","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/invalid","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/none","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/obstructed","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/valid"],"title":"Type Properties","anchor":"Type-Properties","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/enumValue(from:)"],"generated":true,"anchor":"Type-Methods"}]},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentFieldValidationStatus"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"valid","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1valid\/title"},{"value":[{"kind":"identifier","text":"valid"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1valid\/fragments","op":"replace"},{"value":"invalid","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1invalid\/title","op":"replace"},{"value":[{"kind":"identifier","text":"invalid"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1invalid\/fragments","op":"replace"},{"value":"none","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1none\/title","op":"replace"},{"value":[{"text":"none","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1none\/fragments","op":"replace"},{"value":"ignored","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1ignored\/title","op":"replace"},{"value":[{"text":"ignored","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1ignored\/fragments","op":"replace"},{"value":"inferred","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1inferred\/title","op":"replace"},{"value":[{"text":"inferred","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1inferred\/fragments","op":"replace"},{"value":"obstructed","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1obstructed\/title","op":"replace"},{"value":[{"text":"obstructed","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1obstructed\/fragments","op":"replace"},{"value":"enumValueFrom:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1enumValue(from:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"enumValueFrom:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1enumValue(from:)\/fragments","op":"replace"},{"value":"confirmed","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1confirmed\/title","op":"replace"},{"value":[{"text":"confirmed","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1confirmed\/fragments","op":"replace"},{"value":"rawValue","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1rawValue\/title","op":"replace"},{"value":[{"kind":"identifier","text":"rawValue"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1rawValue\/fragments","op":"replace"},{"value":"SBSDKGenericDocumentFieldValidationStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus\/title","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentFieldValidationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentFieldValidationStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}