{"sections":[],"abstract":[{"type":"text","text":"A class to generate an ordered collection of images with or without performing HOCR."}],"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/init(configuration:ocrConfiguration:useEncryptionIfAvailable:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:indexSet:output:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:indexSet:output:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:indexSet:output:progress:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:)-7rhbo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:)-8qvdo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:completion:)-2dnqs","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:completion:)-8cljq","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:progress:)-8m4j3","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:progress:)-9eyf"],"generated":true,"anchor":"Instance-Methods"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","title":"SBSDKPDFGenerator","navigatorTitle":[{"text":"SBSDKPDFGenerator","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFGenerator","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFGenerator","roleHeading":"Class"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFGenerator","kind":"identifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"HOCR is the process of adding an invisible text layer on top of each PDF page, containing the text extracted by"},{"type":"text","text":" "},{"type":"text","text":"the optical character recognizer. A PDF with HOCR is searchable and the text can be selected and copy-pasted."}]},{"type":"paragraph","inlineContent":[{"text":"If ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultCryptingProvider","type":"reference"},{"text":" is set, the generated PDF file will be encrypted using the specified crypting provider.","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfgenerator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfgenerator"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator/init(configuration:ocrConfiguration:useEncryptionIfAvailable:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPDFConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ocrConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKOCREngineConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"useEncryptionIfAvailable","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/init(configuration:ocrconfiguration:useencryptionifavailable:)","type":"topic","navigatorTitle":[{"text":"initWithConfiguration:ocrConfiguration:useEncryptionIfAvailable:error:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/init(configuration:ocrConfiguration:useEncryptionIfAvailable:)","role":"symbol","abstract":[{"type":"text","text":"Designated initializer."}],"title":"init(configuration:ocrConfiguration:useEncryptionIfAvailable:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator/generate(from:output:completion:)-2dnqs":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/generate(from:output:completion:)-2dnqs","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","text":"SBSDKScannedDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> ()) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Asynchronously generates the PDF file from the given scanned document"},{"type":"text","text":" "},{"type":"text","text":"with the given page size, saves the PDF to the specified URL and calls the completion handler when finished."}],"kind":"symbol","title":"generate(from:output:completion:)","navigatorTitle":[{"kind":"identifier","text":"generateFromScannedDocument:output:completion:"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:completion:)-2dnqs"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/defaultCryptingProvider":{"navigatorTitle":[{"kind":"identifier","text":"defaultCryptingProvider"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/scanbot\/defaultcryptingprovider","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultCryptingProvider","title":"defaultCryptingProvider","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultCryptingProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingProvider","text":"SBSDKStorageCryptingProvider"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"type":"text","text":"The SDK-wide encryption provider for storing image data to disk. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", no encryption used."}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator/generate(from:output:progress:)-8m4j3":{"navigatorTitle":[{"kind":"identifier","text":"generateFromScannedDocument:output:progress:error:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","text":"SBSDKScannedDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"abstract":[{"text":"Synchronously generates the PDF file from the given scanned document","type":"text"},{"text":" ","type":"text"},{"text":"with the given page size, and saves the PDF to the specified URL.","type":"text"}],"title":"generate(from:output:progress:)","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:progress:)-8m4j3","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/generate(from:output:progress:)-8m4j3"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator/generate(from:output:completion:)-8cljq":{"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"generateFromDocument:output:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Asynchronously generates the PDF file from the given document"},{"type":"text","text":" "},{"text":"with the given page size, saves the PDF to the specified URL and calls the completion handler when finished.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"text":", ","kind":"text"},{"text":"output","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ()) -> ","kind":"text"},{"text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:completion:)-8cljq","url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/generate(from:output:completion:)-8cljq","title":"generate(from:output:completion:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator/generate(from:output:)-7rhbo":{"type":"topic","title":"generate(from:output:)","url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/generate(from:output:)-7rhbo","role":"symbol","kind":"symbol","abstract":[{"text":"Asynchronously generates the PDF file from the given document and saves it to the specified URL.","type":"text"},{"text":" ","type":"text"},{"text":"Each page is made up of one image.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:)-7rhbo","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"output","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator/generate(from:indexSet:output:progress:)":{"navigatorTitle":[{"kind":"identifier","text":"generateFromImageStorage:indexSet:output:progress:error:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","text":"SBSDKImageStoring"},{"kind":"text","text":", "},{"kind":"externalParam","text":"indexSet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Synchronously generates the PDF file from the images at the specified indices from the image storage"},{"type":"text","text":" "},{"type":"text","text":"with the given page size, and saves the PDF to the specified URL."}],"title":"generate(from:indexSet:output:progress:)","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:indexSet:output:progress:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/generate(from:indexset:output:progress:)"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator/generate(from:indexSet:output:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","text":"SBSDKImageStoring"},{"kind":"text","text":", "},{"kind":"externalParam","text":"indexSet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Asynchronously generates the PDF file from the images at the specified indices from the image storage and saves it to the specified URL."},{"type":"text","text":" "},{"type":"text","text":"Each page is made up of one image."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:indexSet:output:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/generate(from:indexset:output:)","type":"topic","kind":"symbol","title":"generate(from:indexSet:output:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator/generate(from:output:)-8qvdo":{"kind":"symbol","abstract":[{"type":"text","text":"Asynchronously generates the PDF file from the given scanned document and saves it to the specified URL"},{"type":"text","text":" "},{"type":"text","text":"Each page is made up of one image."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:)-8qvdo","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","text":"SBSDKScannedDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?"}],"title":"generate(from:output:)","url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/generate(from:output:)-8qvdo","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator/generate(from:output:progress:)-9eyf":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"text":", ","kind":"text"},{"text":"output","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/generate(from:output:progress:)-9eyf","title":"generate(from:output:progress:)","abstract":[{"text":"Synchronously generates the PDF file from the given document","type":"text"},{"text":" ","type":"text"},{"text":"with the given page size, and saves the PDF to the specified URL.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"generateFromDocument:output:progress:error:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:progress:)-9eyf","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFGenerator"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFGenerator"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator","role":"symbol","abstract":[{"type":"text","text":"A class to generate an ordered collection of images with or without performing HOCR."}],"title":"SBSDKPDFGenerator"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator/generate(from:indexSet:output:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"generateFromImageStorage:indexSet:output:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","text":"SBSDKImageStoring"},{"kind":"text","text":", "},{"kind":"externalParam","text":"indexSet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> ()) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Asynchronously generates the PDF file from the images at the specified indices from the image storage"},{"type":"text","text":" "},{"type":"text","text":"with the given page size, saves the PDF to the specified URL and calls the completion handler when finished."}],"title":"generate(from:indexSet:output:completion:)","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:indexSet:output:completion:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/generate(from:indexset:output:completion:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKPDFGenerator","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFGenerator"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFGenerator"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:indexSet:output:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:indexSet:output:progress:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:completion:)-2dnqs","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:completion:)-8cljq","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:progress:)-8m4j3","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:progress:)-9eyf","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/init(configuration:ocrConfiguration:useEncryptionIfAvailable:)"],"generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFGenerator","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithConfiguration:ocrConfiguration:useEncryptionIfAvailable:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1init(configuration:ocrConfiguration:useEncryptionIfAvailable:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:ocrConfiguration:useEncryptionIfAvailable:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1init(configuration:ocrConfiguration:useEncryptionIfAvailable:)\/fragments"},{"value":"generateFromScannedDocument:output:completion:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1generate(from:output:completion:)-2dnqs\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"generateFromScannedDocument:output:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1generate(from:output:completion:)-2dnqs\/fragments"},{"value":"defaultCryptingProvider","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1defaultCryptingProvider\/title"},{"value":[{"text":"defaultCryptingProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1defaultCryptingProvider\/fragments"},{"value":"generateFromScannedDocument:output:progress:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1generate(from:output:progress:)-8m4j3\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateFromScannedDocument:output:progress:error:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1generate(from:output:progress:)-8m4j3\/fragments"},{"value":"generateFromDocument:output:completion:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1generate(from:output:completion:)-8cljq\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateFromDocument:output:completion:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1generate(from:output:completion:)-8cljq\/fragments"},{"value":"generateFromImageStorage:indexSet:output:progress:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1generate(from:indexSet:output:progress:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"generateFromImageStorage:indexSet:output:progress:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1generate(from:indexSet:output:progress:)\/fragments"},{"value":"generateFromDocument:output:progress:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1generate(from:output:progress:)-9eyf\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"generateFromDocument:output:progress:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1generate(from:output:progress:)-9eyf\/fragments"},{"value":"SBSDKPDFGenerator","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/title"},{"value":[{"text":"SBSDKPDFGenerator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKPDFGenerator"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/navigatorTitle"},{"value":"generateFromImageStorage:indexSet:output:completion:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1generate(from:indexSet:output:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateFromImageStorage:indexSet:output:completion:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1generate(from:indexSet:output:completion:)\/fragments"}]}]}