{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKPageBinarization","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageBinarization"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageBinarization"}],"roleHeading":"Enumeration","symbolKind":"enum","title":"SBSDKPageBinarization","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagebinarization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagebinarization"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"type":"text","text":"Binarization behavior to apply when adding a page to a PDF\/TIFF."}],"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/disabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/enabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/enabledIfBinarizationFilterSet"]},{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/init(rawValue:)"]},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKPageBinarization) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageBinarization"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageBinarization/init(rawValue:)":{"title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/init(rawValue:)","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkpagebinarization\/init(rawvalue:)","role":"symbol"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageBinarization/enabled":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/enabled","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpagebinarization\/enabled","role":"symbol","title":"SBSDKPageBinarization.enabled","kind":"symbol","abstract":[{"type":"text","text":"Binarize the image. Image will be stored as a compressed black-and-white image. This will result in a"},{"type":"text","text":" "},{"type":"text","text":"very small file size. If binarizationFilter is set, this binarization filter will be applied."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, a simple thresholding binarization will be applied."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageBinarizationEnabled"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageBinarization":{"abstract":[{"text":"Binarization behavior to apply when adding a page to a PDF\/TIFF.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagebinarization","role":"symbol","navigatorTitle":[{"text":"SBSDKPageBinarization","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageBinarization"}],"title":"SBSDKPageBinarization","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageBinarization/disabled":{"kind":"symbol","title":"SBSDKPageBinarization.disabled","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/disabled","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpagebinarization\/disabled","navigatorTitle":[{"text":"SBSDKPageBinarizationDisabled","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}],"abstract":[{"type":"text","text":"Do not binarize the image."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageBinarization/enabledIfBinarizationFilterSet":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/enabledIfBinarizationFilterSet","abstract":[{"type":"text","text":"Same behavior as ENABLED if a binarizationFilter is set,"},{"type":"text","text":" "},{"type":"text","text":"otherwise same behavior as DISABLED. This is the default."}],"title":"SBSDKPageBinarization.enabledIfBinarizationFilterSet","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpagebinarization\/enabledifbinarizationfilterset","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabledIfBinarizationFilterSet"}]},"doc://net.doo.ScanbotSDK/s12CaseIterableP":{"title":"Swift.CaseIterable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageBinarization/RawRepresentable-Implementations":{"kind":"article","title":"RawRepresentable Implementations","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkpagebinarization\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/RawRepresentable-Implementations"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageBinarization/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/Equatable-Implementations","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpagebinarization\/equatable-implementations","role":"collectionGroup","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKPageBinarization"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKPageBinarization","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKPageBinarization","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/disabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/enabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/enabledIfBinarizationFilterSet"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageBinarization","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization~1enabled\/title","value":"SBSDKPageBinarizationEnabled"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization~1enabled\/fragments","value":[{"text":"SBSDKPageBinarizationEnabled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization\/title","value":"SBSDKPageBinarization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization\/fragments","value":[{"kind":"identifier","text":"SBSDKPageBinarization"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPageBinarization"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization~1disabled\/title","value":"SBSDKPageBinarizationDisabled"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization~1disabled\/fragments","value":[{"kind":"identifier","text":"SBSDKPageBinarizationDisabled"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization~1enabledIfBinarizationFilterSet\/title","value":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization~1enabledIfBinarizationFilterSet\/fragments","value":[{"kind":"identifier","text":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}