{"metadata":{"role":"symbol","title":"SBSDKBarcodeScannerConfiguration","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerConfiguration","navigatorTitle":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}]},"sections":[],"abstract":[{"type":"text","text":"Configuration for the barcode scanner."}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/init(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/accumulationConfig","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/barcodeFormatConfigurations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/engineMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/extractedDocumentFormats","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/onlyAcceptDocuments","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/optimizedForOverlays","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/processingMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/returnBarcodeImage"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/setBarcodeFormats(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/create(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)"],"generated":true,"anchor":"Type-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKBarcodeScannerConfiguration) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/isEqual:":{"role":"symbol","title":"isEqual:","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/isequal:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/returnBarcodeImage":{"role":"symbol","title":"returnBarcodeImage","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/returnbarcodeimage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/returnBarcodeImage","kind":"symbol","abstract":[{"type":"text","text":"If true, the barcode image will be returned in the BarcodeItem."}],"type":"topic","navigatorTitle":[{"text":"returnBarcodeImage","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"returnBarcodeImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/hash":{"type":"topic","title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/hash","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/hash","kind":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/fromJsonWithJson:":{"title":"fromJsonWithJson:","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/fromJsonWithJson:","role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/fromjsonwithjson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/extractedDocumentFormats":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extractedDocumentFormats","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"SBSDKBarcodeDocumentFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat","kind":"typeIdentifier"},{"text":">","kind":"text"}],"type":"topic","title":"extractedDocumentFormats","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/extracteddocumentformats","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/extractedDocumentFormats","navigatorTitle":[{"text":"extractedDocumentFormats","kind":"identifier"}],"role":"symbol","abstract":[{"text":"List of document formats to be extracted.","type":"text"},{"text":" ","type":"text"},{"text":"Barcodes that decode to one of the extracted document formats will have extractedDocument field in BarcodeItem populated with the parsed document.","type":"text"},{"text":" ","type":"text"},{"text":"By default all supported barcode document formats are accepted.","type":"text"},{"text":" ","type":"text"},{"text":"If empty, no barcodes will be parsed into documents.","type":"text"},{"text":" ","type":"text"},{"text":"To only accept the document formats listed in extractedDocumentFormats, the property onlyAcceptDocuments must be true.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/onlyAcceptDocuments":{"role":"symbol","title":"onlyAcceptDocuments","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/onlyacceptdocuments","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onlyAcceptDocuments"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyAcceptDocuments"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"type":"text","text":"If true and extractedDocumentFormats is not empty, then barcodes that don’t decode to one of the extracted document formats will be ignored."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/onlyAcceptDocuments"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/init()":{"title":"init()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/init()","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/init()"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/copyWithZone:":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/copywithzone:","abstract":[],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/copyWithZone:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/toJson(configuration:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/tojson(configuration:)","role":"symbol","kind":"symbol","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/toJson(configuration:)","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"title":"toJson(configuration:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/barcodeFormatConfigurations":{"title":"barcodeFormatConfigurations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/barcodeFormatConfigurations","abstract":[{"text":"Options for barcode decoding.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/barcodeformatconfigurations","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatConfigurations"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatConfigurationBase","text":"SBSDKBarcodeFormatConfigurationBase"},{"kind":"text","text":">"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"barcodeFormatConfigurations"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration","title":"SBSDKBarcodeScannerConfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration","abstract":[{"text":"Configuration for the barcode scanner.","type":"text"}],"navigatorTitle":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/optimizedForOverlays":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"optimizedForOverlays"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/optimizedForOverlays","title":"optimizedForOverlays","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/optimizedforoverlays","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"optimizedForOverlays"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","abstract":[{"text":"If true, the quads of linear (1D) barcodes will be further refined to more closely match the barcode’s outline in the input image.","type":"text"},{"text":" ","type":"text"},{"text":"This will also produce stabler barcode outlines across frames for use cases such as AR.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/init(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)":{"type":"topic","abstract":[{"type":"text","text":"Convenience initializer."}],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barcodeFormats"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"extractedDocumentFormats"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKBarcodeDocumentFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"onlyAcceptDocuments"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/init(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/init(barcodeformats:extracteddocumentformats:onlyacceptdocuments:)","title":"init(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBarcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/engineMode":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/enginemode","type":"topic","title":"engineMode","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/engineMode","abstract":[{"type":"text","text":"The engine mode for barcode scanning."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"engineMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeScannerEngineMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeScannerEngineMode"}],"navigatorTitle":[{"kind":"identifier","text":"engineMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:processingMode:":{"kind":"symbol","title":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:processingMode:","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/initwithbarcodeformatconfigurations:extracteddocumentformats:onlyacceptdocuments:returnbarcodeimage:enginemode:accumulationconfig:optimizedforoverlays:processingmode:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:processingMode:"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:processingMode:","navigatorTitle":[{"kind":"identifier","text":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:processingMode:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/accumulationConfig":{"navigatorTitle":[{"kind":"identifier","text":"accumulationConfig"}],"role":"symbol","title":"accumulationConfig","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/accumulationconfig","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/accumulationConfig","type":"topic","abstract":[{"type":"text","text":"Configuration to accumulate barcodes across multiple frames in live mode."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accumulationConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeAccumulationConfiguration","text":"SBSDKBarcodeAccumulationConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/setBarcodeFormats(_:)":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Overwrites the barcode formats to be scanned. Previously added barcode formats  and barcode format configurations will be removed."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/setbarcodeformats(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/setBarcodeFormats(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setBarcodeFormats","kind":"identifier"},{"text":"([","kind":"text"},{"text":"SBSDKBarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"setBarcodeFormats:","kind":"identifier"}],"title":"setBarcodeFormats(_:)"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/processingMode":{"title":"processingMode","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"processingMode"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"processingMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKProcessingMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKProcessingMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/processingMode","abstract":[{"text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/processingmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/create(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)":{"title":"create(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barcodeFormats"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat","kind":"typeIdentifier","text":"SBSDKBarcodeFormat"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"extractedDocumentFormats"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat","kind":"typeIdentifier","text":"SBSDKBarcodeDocumentFormat"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"onlyAcceptDocuments"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerConfiguration","kind":"typeIdentifier","text":"SBSDKBarcodeScannerConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/create(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/create(barcodeformats:extracteddocumentformats:onlyacceptdocuments:)","type":"topic","abstract":[{"type":"text","text":"Factory method to create a barcode scanner configuration."}],"navigatorTitle":[{"kind":"identifier","text":"createWithBarcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeScannerConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/accumulationConfig","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/barcodeFormatConfigurations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/engineMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/extractedDocumentFormats","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/onlyAcceptDocuments","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/optimizedForOverlays","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/processingMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/returnBarcodeImage"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/init(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:processingMode:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/setBarcodeFormats(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/toJson(configuration:)"],"generated":true},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/create(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/fromJsonWithJson:"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1returnBarcodeImage\/title","value":"returnBarcodeImage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1returnBarcodeImage\/fragments","op":"replace","value":[{"kind":"identifier","text":"returnBarcodeImage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1extractedDocumentFormats\/title","value":"extractedDocumentFormats"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1extractedDocumentFormats\/fragments","value":[{"kind":"identifier","text":"extractedDocumentFormats"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1onlyAcceptDocuments\/title","value":"onlyAcceptDocuments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1onlyAcceptDocuments\/fragments","value":[{"text":"onlyAcceptDocuments","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1toJson(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1barcodeFormatConfigurations\/title","value":"barcodeFormatConfigurations","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1barcodeFormatConfigurations\/fragments","value":[{"kind":"identifier","text":"barcodeFormatConfigurations"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/title","value":"SBSDKBarcodeScannerConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1optimizedForOverlays\/title","value":"optimizedForOverlays","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1optimizedForOverlays\/fragments","value":[{"text":"optimizedForOverlays","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1init(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)\/title","value":"initWithBarcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1init(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBarcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1engineMode\/title","value":"engineMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1engineMode\/fragments","value":[{"text":"engineMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1accumulationConfig\/title","value":"accumulationConfig","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1accumulationConfig\/fragments","value":[{"text":"accumulationConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1setBarcodeFormats(_:)\/title","value":"setBarcodeFormats:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1setBarcodeFormats(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setBarcodeFormats:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1processingMode\/title","value":"processingMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1processingMode\/fragments","value":[{"kind":"identifier","text":"processingMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1create(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)\/title","value":"createWithBarcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1create(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithBarcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}