{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraExposureSettings"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraExposureSettings\/exposureTargetOffset","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exposureTargetOffset","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Usually the camera automatically tries to adapt its exposure parameters to keep the exposure target offset at a"},{"type":"text","text":" "},{"type":"text","text":"value of 0 resulting in a proper exposure of the image."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"If this value is not close to 0 the camera cannot adjust its exposure parameters properly, the image is either"},{"type":"text","text":" "},{"type":"text","text":"way too dark or too bright."}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"The exposure target offset in EV."},{"text":" ","type":"text"},{"text":"Negative values mean the image is too dark, positive values mean the image is too bright.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcameraexposuresettings\/exposuretargetoffset"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcameraexposuresettings\/exposuretargetoffset"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"exposureTargetOffset"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"exposureTargetOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property","title":"exposureTargetOffset","roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCameraExposureSettings(py)exposureTargetOffset"},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraExposureSettings/exposureTargetOffset":{"title":"exposureTargetOffset","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraExposureSettings\/exposureTargetOffset","navigatorTitle":[{"text":"exposureTargetOffset","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameraexposuresettings\/exposuretargetoffset","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exposureTargetOffset","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The exposure target offset in EV."},{"type":"text","text":" "},{"type":"text","text":"Negative values mean the image is too dark, positive values mean the image is too bright."}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraExposureSettings":{"title":"SBSDKCameraExposureSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraExposureSettings"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraExposureSettings","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameraexposuresettings","kind":"symbol","abstract":[{"text":"This class provides information about the current cameras exposure settings.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraExposureSettings"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"exposureTargetOffset","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"exposureTargetOffset"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":" "},{"kind":"identifier","text":"exposureTargetOffset"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"exposureTargetOffset","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraExposureSettings~1exposureTargetOffset\/title","op":"replace"},{"value":[{"text":"exposureTargetOffset","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraExposureSettings~1exposureTargetOffset\/fragments","op":"replace"},{"value":"SBSDKCameraExposureSettings","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraExposureSettings\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCameraExposureSettings"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraExposureSettings\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCameraExposureSettings"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraExposureSettings\/navigatorTitle","op":"replace"}]}]}