{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/makeSnapshot()"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagerefprofiler\/makesnapshot()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimagerefprofiler\/makesnapshot()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeSnapshot"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshot","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot","text":"SBSDKImageRefPoolSnapshot"}],"languages":["swift"]}]},{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"text":"The snapshot of all alive ImageRefs.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefProfiler(cm)makeSnapshot","title":"makeSnapshot()","symbolKind":"method","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeSnapshot","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"makeSnapshot"}]},"abstract":[{"type":"text","text":"Returns a snapshot of all alive ImageRefs. The snapshot contains a list of ImageRefs with information such as in-memory size. If detailed profiling is enabled (by calling enableDetailedProfiling beforehand), the profile will contain additional information such as the source from which each ImageRef has been created."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfiler":{"abstract":[{"text":"ImageRef memory profiler.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","title":"SBSDKImageRefProfiler","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler","url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofiler","navigatorTitle":[{"text":"SBSDKImageRefProfiler","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefProfiler","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefPoolSnapshot":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagerefpoolsnapshot","role":"symbol","title":"SBSDKImageRefPoolSnapshot","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshot","abstract":[{"text":"Snapshot of all alive ImageRefs.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfiler/makeSnapshot()":{"navigatorTitle":[{"text":"makeSnapshot","kind":"identifier"}],"title":"makeSnapshot()","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeSnapshot","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot","text":"SBSDKImageRefPoolSnapshot","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Returns a snapshot of all alive ImageRefs. The snapshot contains a list of ImageRefs with information such as in-memory size. If detailed profiling is enabled (by calling enableDetailedProfiling beforehand), the profile will contain additional information such as the source from which each ImageRef has been created."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/makeSnapshot()","url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofiler\/makesnapshot()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"makeSnapshot","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"makeSnapshot","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot","text":"SBSDKImageRefPoolSnapshot","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshot"},{"text":" *) ","kind":"text"},{"text":"makeSnapshot","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The snapshot of all alive ImageRefs."}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SBSDKImageRefProfiler","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefProfiler"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefProfiler"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler\/navigatorTitle"},{"op":"replace","value":"SBSDKImageRefPoolSnapshot","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefPoolSnapshot\/title"},{"op":"replace","value":[{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefPoolSnapshot\/fragments"},{"op":"replace","value":[{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefPoolSnapshot\/navigatorTitle"},{"op":"replace","value":"makeSnapshot","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler~1makeSnapshot()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"makeSnapshot","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler~1makeSnapshot()\/fragments"}]}]}