{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation"]]},"metadata":{"externalID":"s:10ScanbotSDK21SBSDKVideoOrientationO11isLandscapeSbvp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLandscape"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"isLandscape"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLandscape"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/isLandscape","interfaceLanguage":"swift"},"abstract":[{"text":"Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the receiver is either landscape left or landscape right, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" otherwise.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoorientation\/islandscape"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoOrientation"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation","role":"symbol","navigatorTitle":[{"text":"SBSDKVideoOrientation","kind":"identifier"}],"title":"SBSDKVideoOrientation","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation","type":"topic","abstract":[{"type":"text","text":"An enum describing the orientation of a video frame."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation/isLandscape":{"url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation\/islandscape","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/isLandscape","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLandscape"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the receiver is either landscape left or landscape right, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise."}],"title":"isLandscape","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKVideoOrientation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/title","op":"replace"},{"value":[{"text":"SBSDKVideoOrientation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}