{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPBKDF2KeyGenerator\/init(password:salt:iterations:)","interfaceLanguage":"swift"},"metadata":{"title":"init(password:salt:iterations:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"salt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"iterations"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPBKDF2KeyGenerator(im)initWithPassword:salt:iterations:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPassword:salt:iterations:"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"init"},"abstract":[{"type":"text","text":"Designated initializer."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPBKDF2KeyGenerator"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"password","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"salt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"iterations","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"password","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The password to be used when generating the encryption key."}]}]},{"name":"salt","content":[{"inlineContent":[{"type":"text","text":"The salt to be used when generating the encryption key."}],"type":"paragraph"}]},{"name":"iterations","content":[{"type":"paragraph","inlineContent":[{"text":"The number of iterations to be used when generating the encryption key.","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpbkdf2keygenerator\/init(password:salt:iterations:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpbkdf2keygenerator\/init(password:salt:iterations:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPBKDF2KeyGenerator":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"title":"SBSDKPBKDF2KeyGenerator","url":"\/documentation\/scanbotsdk\/sbsdkpbkdf2keygenerator","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPBKDF2KeyGenerator","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A key generator that uses the PBKDF2 algorithm to derive a key from a password and a salt."},{"type":"text","text":" "},{"type":"text","text":"See https:\/\/en.wikipedia.org\/wiki\/PBKDF2 for more information."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPBKDF2KeyGenerator/init(password:salt:iterations:)":{"kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"password","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"salt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"iterations","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Designated initializer."}],"navigatorTitle":[{"text":"initWithPassword:salt:iterations:","kind":"identifier"}],"title":"init(password:salt:iterations:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPBKDF2KeyGenerator\/init(password:salt:iterations:)","url":"\/documentation\/scanbotsdk\/sbsdkpbkdf2keygenerator\/init(password:salt:iterations:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithPassword:salt:iterations:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPassword:salt:iterations:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithPassword:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"password","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"salt:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"salt","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"iterations:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"iterations","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"value":{"parameters":[{"name":"password","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The password to be used when generating the encryption key."}]}]},{"name":"salt","content":[{"type":"paragraph","inlineContent":[{"text":"The salt to be used when generating the encryption key.","type":"text"}]}]},{"name":"iterations","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The number of iterations to be used when generating the encryption key."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SBSDKPBKDF2KeyGenerator","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPBKDF2KeyGenerator\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPBKDF2KeyGenerator\/fragments","value":[{"kind":"identifier","text":"SBSDKPBKDF2KeyGenerator"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPBKDF2KeyGenerator\/navigatorTitle","value":[{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPBKDF2KeyGenerator~1init(password:salt:iterations:)\/title","value":"initWithPassword:salt:iterations:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPBKDF2KeyGenerator~1init(password:salt:iterations:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPassword:salt:iterations:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}