{"abstract":[{"text":"Asynchronously converts the document to a multipage-TIFF file and writes it to the specified URL.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeTIFFAsync"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toFile"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fileURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The document to convert to a TIFF file."}]}],"name":"document"},{"content":[{"inlineContent":[{"type":"text","text":"The file URL to save the TIFF file at."}],"type":"paragraph"}],"name":"fileURL"}],"kind":"parameters"},{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"text":"The URL the TIFF file has been written to or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the operation failed.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In Swift language it is used with structured concurrency (async\/await)."}]}],"kind":"content"}],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriter(im)writeTIFFAsyncWithDocument:toFile:completionHandler:","navigatorTitle":[{"text":"writeTIFFAsyncWithDocument:toFile:completionHandler:","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeTIFFAsync"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocument","kind":"typeIdentifier","text":"SBSDKDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toFile"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?"}],"symbolKind":"method","title":"writeTIFFAsync(document:toFile:)","roleHeading":"Instance Method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(document:toFile:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiffasync(document:tofile:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiffasync(document:tofile:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocument":{"abstract":[{"text":"A thread-safe, mutable container for scanned pages of type ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocument","kind":"identifier"}],"type":"topic","title":"SBSDKDocument","navigatorTitle":[{"text":"SBSDKDocument","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocument","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPage":{"type":"topic","abstract":[{"text":"This class represents a scanned documents page.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpage","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage","title":"SBSDKDocumentPage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"abstract":[{"text":"A class that converts images to (multipage) TIFF images.","type":"text"},{"text":" ","type":"text"},{"text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc.","type":"text"},{"text":" ","type":"text"},{"text":"When passing an encrypter the generated TIFF images will be encrypted.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter","navigatorTitle":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"type":"topic","title":"SBSDKTIFFImageWriter","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFFAsync(document:toFile:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"writeTIFFAsync","kind":"identifier"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toFile"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"writeTIFFAsyncWithDocument:toFile:completionHandler:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiffasync(document:tofile:)","title":"writeTIFFAsync(document:toFile:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(document:toFile:)","abstract":[{"text":"Asynchronously converts the document to a multipage-TIFF file and writes it to the specified URL.","type":"text"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"writeTIFFAsyncWithDocument:toFile:completionHandler:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writeTIFFAsyncWithDocument:toFile:completionHandler:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"writeTIFFAsyncWithDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocument"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"toFile:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"fileURL","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The document to convert to a TIFF file.","type":"text"}]}],"name":"document"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The file URL to save the TIFF file at.","type":"text"}]}],"name":"fileURL"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":null,"path":"\/primaryContentSections\/2"},{"op":"replace","value":"SBSDKDocument","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocument\/title"},{"op":"replace","value":[{"text":"SBSDKDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocument\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocument\/navigatorTitle"},{"op":"replace","value":"SBSDKDocumentPage","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/navigatorTitle"},{"op":"replace","value":"SBSDKTIFFImageWriter","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/title"},{"op":"replace","value":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/navigatorTitle"},{"op":"replace","value":"writeTIFFAsyncWithDocument:toFile:completionHandler:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(document:toFile:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writeTIFFAsyncWithDocument:toFile:completionHandler:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(document:toFile:)\/fragments"}]}]}