{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"new"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatPDF417Configuration(cm)new","fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"new"}],"title":"new"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatpdf417configuration\/new"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPDF417Configuration\/new"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPDF417Configuration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatPDF417Configuration":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatPDF417Configuration"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatpdf417configuration","abstract":[{"type":"text","text":"PDF417 configuration. Add to scanner configuration to scan PDF417 codes."}],"title":"SBSDKBarcodeFormatPDF417Configuration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPDF417Configuration","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatPDF417Configuration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatPDF417Configuration/new":{"kind":"symbol","title":"new","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatpdf417configuration\/new","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"new"}],"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"new"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPDF417Configuration\/new"}},"variantOverrides":[{"patch":[{"value":"SBSDKBarcodeFormatPDF417Configuration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPDF417Configuration\/title"},{"value":[{"text":"SBSDKBarcodeFormatPDF417Configuration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPDF417Configuration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatPDF417Configuration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPDF417Configuration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}