{"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatPharmaCodeConfiguration(py)allowNarrowBarsOnly","navigatorTitle":[{"text":"allowNarrowBarsOnly","kind":"identifier"}],"roleHeading":"Instance Property","title":"allowNarrowBarsOnly","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowNarrowBarsOnly","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"abstract":[{"type":"text","text":"If true, a result consisting of only narrow bars is accepted as valid. The specification does not recommend such"},{"type":"text","text":" "},{"type":"text","text":"barcodes. Default is false."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodeconfiguration\/allownarrowbarsonly"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodeconfiguration\/allownarrowbarsonly"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowNarrowBarsOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"Default is false","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeConfiguration\/allowNarrowBarsOnly","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatPharmaCodeConfiguration":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodeconfiguration","title":"SBSDKBarcodeFormatPharmaCodeConfiguration","type":"topic","abstract":[{"text":"PharmaCode barcode configuration. Add to scanner configuration to scan linear (1D) Laetus Pharmacode barcodes.","type":"text"},{"text":" ","type":"text"},{"text":"Two-track PharmaCode scanning is configured separately through the PharmaCodeTwoTrackConfig class.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatPharmaCodeConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatPharmaCodeConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatPharmaCodeConfiguration/allowNarrowBarsOnly":{"title":"allowNarrowBarsOnly","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeConfiguration\/allowNarrowBarsOnly","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodeconfiguration\/allownarrowbarsonly","navigatorTitle":[{"text":"allowNarrowBarsOnly","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"If true, a result consisting of only narrow bars is accepted as valid. The specification does not recommend such","type":"text"},{"text":" ","type":"text"},{"text":"barcodes. Default is false.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowNarrowBarsOnly","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"allowNarrowBarsOnly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"allowNarrowBarsOnly","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"allowNarrowBarsOnly","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeConfiguration\/title","value":"SBSDKBarcodeFormatPharmaCodeConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatPharmaCodeConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatPharmaCodeConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeConfiguration~1allowNarrowBarsOnly\/title","value":"allowNarrowBarsOnly"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeConfiguration~1allowNarrowBarsOnly\/fragments","value":[{"kind":"identifier","text":"allowNarrowBarsOnly"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}