{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"If true, a result consisting of only wide bars is accepted as valid. The specification does not recommend such"},{"type":"text","text":" "},{"type":"text","text":"barcodes. Default is false."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowWideBarsOnly","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Default is false"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowWideBarsOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"allowWideBarsOnly","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatPharmaCodeConfiguration(py)allowWideBarsOnly","navigatorTitle":[{"kind":"identifier","text":"allowWideBarsOnly"}],"roleHeading":"Instance Property","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodeconfiguration\/allowwidebarsonly"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodeconfiguration\/allowwidebarsonly"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeConfiguration\/allowWideBarsOnly","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatPharmaCodeConfiguration":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodeconfiguration","title":"SBSDKBarcodeFormatPharmaCodeConfiguration","type":"topic","abstract":[{"text":"PharmaCode barcode configuration. Add to scanner configuration to scan linear (1D) Laetus Pharmacode barcodes.","type":"text"},{"text":" ","type":"text"},{"text":"Two-track PharmaCode scanning is configured separately through the PharmaCodeTwoTrackConfig class.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatPharmaCodeConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatPharmaCodeConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatPharmaCodeConfiguration/allowWideBarsOnly":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeConfiguration\/allowWideBarsOnly","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodeconfiguration\/allowwidebarsonly","type":"topic","abstract":[{"type":"text","text":"If true, a result consisting of only wide bars is accepted as valid. The specification does not recommend such"},{"type":"text","text":" "},{"type":"text","text":"barcodes. Default is false."}],"role":"symbol","navigatorTitle":[{"text":"allowWideBarsOnly","kind":"identifier"}],"title":"allowWideBarsOnly","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowWideBarsOnly","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"allowWideBarsOnly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"allowWideBarsOnly","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowWideBarsOnly"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeConfiguration\/title","value":"SBSDKBarcodeFormatPharmaCodeConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatPharmaCodeConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatPharmaCodeConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeConfiguration~1allowWideBarsOnly\/title","value":"allowWideBarsOnly"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeConfiguration~1allowWideBarsOnly\/fragments","value":[{"text":"allowWideBarsOnly","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}