{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimageserializationmode\/reference"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageserializationmode\/reference"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode\/reference","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reference"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"reference","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKImageSerializationMode@SBSDKImageSerializationModeReference","symbolKind":"case","title":"SBSDKImageSerializationMode.reference","modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKImageSerializationModeReference","kind":"identifier"}],"roleHeading":"Case"},"abstract":[{"type":"text","text":"Images are serialized as references to native resources."}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSerializationMode/reference":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode\/reference","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSerializationModeReference"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageserializationmode\/reference","abstract":[{"text":"Images are serialized as references to native resources.","type":"text"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reference","kind":"identifier"}],"title":"SBSDKImageSerializationMode.reference"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSerializationMode":{"role":"symbol","title":"SBSDKImageSerializationMode","navigatorTitle":[{"text":"SBSDKImageSerializationMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageserializationmode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageSerializationMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode","abstract":[{"type":"text","text":"Image serialization mode. Applicable only when serializeImages is true."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKImageSerializationModeReference","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKImageSerializationModeReference","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKImageSerializationModeReference","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSerializationMode~1reference\/title","value":"SBSDKImageSerializationModeReference","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSerializationMode~1reference\/fragments","value":[{"kind":"identifier","text":"SBSDKImageSerializationModeReference"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSerializationMode\/title","value":"SBSDKImageSerializationMode"},{"value":[{"text":"SBSDKImageSerializationMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSerializationMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageSerializationMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSerializationMode\/navigatorTitle"}]}]}