{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateFormType\/form1D","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"form1D","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificateformtype\/form1d"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificateformtype\/form1d"]}],"metadata":{"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKMedicalCertificateFormType.form1D","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"form1D"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateFormTypeForm1D"}],"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateFormType@SBSDKMedicalCertificateFormTypeForm1D"},"abstract":[{"type":"text","text":"Form 1D."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateFormType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateFormType/form1D":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"form1D"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateFormType\/form1D","kind":"symbol","title":"SBSDKMedicalCertificateFormType.form1D","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificateformtype\/form1d","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateFormTypeForm1D"}],"type":"topic","abstract":[{"type":"text","text":"Form 1D."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateFormType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateFormType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateFormType","kind":"identifier"}],"title":"SBSDKMedicalCertificateFormType","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateFormType","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificateformtype","abstract":[{"text":"Type of the medical certificate form.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKMedicalCertificateFormTypeForm1D","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKMedicalCertificateFormTypeForm1D","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKMedicalCertificateFormTypeForm1D","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateFormType~1form1D\/title","value":"SBSDKMedicalCertificateFormTypeForm1D","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateFormType~1form1D\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateFormTypeForm1D"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateFormType\/title","value":"SBSDKMedicalCertificateFormType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateFormType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateFormType"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateFormType\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificateFormType","kind":"identifier"}],"op":"replace"}]}]}