{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelHIBC"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelHIBC\/hasSecondaryData","interfaceLanguage":"swift"},"abstract":[{"text":"Information whether secondary data is present.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"hasSecondaryData","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelHIBC(py)hasSecondaryData","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasSecondaryData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"title":"hasSecondaryData"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelhibc\/hassecondarydata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelhibc\/hassecondarydata"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasSecondaryData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelHIBC/hasSecondaryData":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelHIBC\/hasSecondaryData","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelhibc\/hassecondarydata","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasSecondaryData","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"hasSecondaryData","abstract":[{"text":"Information whether secondary data is present.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"hasSecondaryData","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelHIBC":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelHIBC","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelhibc","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelHIBC"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelHIBC"}],"abstract":[{"text":"HIBC","type":"text"}],"title":"SBSDKBarcodeDocumentModelHIBC"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"type":"topic","title":"SBSDKGenericDocumentField","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"abstract":[{"type":"text","text":"Generic document field."}],"navigatorTitle":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"hasSecondaryData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"hasSecondaryData"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField"},{"text":" * ","kind":"text"},{"text":"hasSecondaryData","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelHIBC~1hasSecondaryData\/title","value":"hasSecondaryData"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelHIBC~1hasSecondaryData\/fragments","value":[{"text":"hasSecondaryData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelHIBC\/title","value":"SBSDKBarcodeDocumentModelHIBC"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelHIBC\/fragments","value":[{"text":"SBSDKBarcodeDocumentModelHIBC","kind":"identifier"}]},{"value":[{"text":"SBSDKBarcodeDocumentModelHIBC","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelHIBC\/navigatorTitle","op":"replace"},{"value":"SBSDKGenericDocumentField","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle","op":"replace"}]}]}