{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/nolayoutpreset()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/nolayoutpreset()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/noLayoutPreset()"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noLayoutPreset","kind":"identifier"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoLayoutPreset","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2NoLayoutPreset","text":"SBSDKUI2NoLayoutPreset","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Type Method","navigatorTitle":[{"text":"noLayoutPreset","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"noLayoutPreset()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"noLayoutPreset"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2NoLayoutPreset","kind":"typeIdentifier","text":"SBSDKUI2NoLayoutPreset"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZFinderLayoutPreset(cm)noLayoutPreset","symbolKind":"method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset/noLayoutPreset()":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"noLayoutPreset"}],"title":"noLayoutPreset()","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/nolayoutpreset()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/noLayoutPreset()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"noLayoutPreset"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKUI2NoLayoutPreset","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2NoLayoutPreset"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset":{"kind":"symbol","title":"SBSDKUI2MRZFinderLayoutPreset","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset","abstract":[{"text":"Source of the text for the MRZ finder example overlay.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2NoLayoutPreset":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2NoLayoutPreset","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2NoLayoutPreset","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2nolayoutpreset","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoLayoutPreset","role":"symbol","title":"SBSDKUI2NoLayoutPreset","abstract":[{"type":"text","text":"No layout preset."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"noLayoutPreset","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"noLayoutPreset","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2NoLayoutPreset","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoLayoutPreset","text":"SBSDKUI2NoLayoutPreset"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"noLayoutPreset"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset~1noLayoutPreset()\/title","value":"noLayoutPreset","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset~1noLayoutPreset()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"noLayoutPreset"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/title","value":"SBSDKUI2MRZFinderLayoutPreset","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/fragments","value":[{"text":"SBSDKUI2MRZFinderLayoutPreset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/navigatorTitle","value":[{"text":"SBSDKUI2MRZFinderLayoutPreset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoLayoutPreset\/title","value":"SBSDKUI2NoLayoutPreset","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoLayoutPreset\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2NoLayoutPreset"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoLayoutPreset\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2NoLayoutPreset"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}