{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcommonfieldtype\/enumvalue(from:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcommonfieldtype\/enumvalue(from:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enumValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCommonFieldType","text":"SBSDKCommonFieldType","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"An integer representing the raw value of the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"rawValue"}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"text":"An instance of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType"},{"text":" corresponding to the provided raw value, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no match is found.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Returns an instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType"},{"type":"text","text":" based on the provided raw value."}],"kind":"symbol","metadata":{"title":"enumValue(from:)","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enumValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKCommonFieldType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCommonFieldType","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCommonFieldType(cm)enumValueFrom:","symbolKind":"method","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"enumValueFrom:"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType\/enumValue(from:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCommonFieldType":{"abstract":[{"text":"Common field types.","type":"text"}],"kind":"symbol","title":"SBSDKCommonFieldType","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCommonFieldType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCommonFieldType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcommonfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCommonFieldType/enumValue(from:)":{"url":"\/documentation\/scanbotsdk\/sbsdkcommonfieldtype\/enumvalue(from:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enumValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKCommonFieldType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCommonFieldType","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"Returns an instance of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType","type":"reference","isActive":true},{"text":" based on the provided raw value.","type":"text"}],"navigatorTitle":[{"text":"enumValueFrom:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType\/enumValue(from:)","role":"symbol","title":"enumValue(from:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"enumValueFrom:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"enumValueFrom:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKCommonFieldType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCommonFieldType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType"},{"text":" *) ","kind":"text"},{"text":"enumValueFrom:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"rawValue","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"rawValue","content":[{"inlineContent":[{"type":"text","text":"An integer representing the raw value of the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"An instance of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType","type":"reference"},{"text":" corresponding to the provided raw value, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no match is found.","type":"text"}],"type":"paragraph"}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCommonFieldType\/title","op":"replace","value":"SBSDKCommonFieldType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCommonFieldType\/fragments","op":"replace","value":[{"text":"SBSDKCommonFieldType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCommonFieldType\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCommonFieldType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCommonFieldType~1enumValue(from:)\/title","op":"replace","value":"enumValueFrom:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCommonFieldType~1enumValue(from:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"enumValueFrom:"}]}]}]}