{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PopupMenuItem"]]},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithTitle:accessibilityDescription:icon:"}],"symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithTitle:accessibilityDescription:icon:","kind":"identifier"}],"title":"initWithTitle:accessibilityDescription:icon:","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PopupMenuItem(im)initWithTitle:accessibilityDescription:icon:","role":"symbol","roleHeading":"Instance Method"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithTitle:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"title"},{"kind":"text","text":" "},{"text":"accessibilityDescription:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescription","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"icon:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconStyle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconStyle","text":"SBSDKUI2IconStyle","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"icon","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2popupmenuitem\/initwithtitle:accessibilitydescription:icon:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PopupMenuItem\/initWithTitle:accessibilityDescription:icon:"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2IconStyle":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"title":"SBSDKUI2IconStyle","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2IconStyle","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the icon appearance."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2iconstyle","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconStyle"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PopupMenuItem":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2PopupMenuItem"}],"navigatorTitle":[{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PopupMenuItem","title":"SBSDKUI2PopupMenuItem","abstract":[{"type":"text","text":"Configuration for the popup menu items."}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2popupmenuitem"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PopupMenuItem/initWithTitle:accessibilityDescription:icon:":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithTitle:accessibilityDescription:icon:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTitle:accessibilityDescription:icon:"}],"title":"initWithTitle:accessibilityDescription:icon:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PopupMenuItem\/initWithTitle:accessibilityDescription:icon:","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2popupmenuitem\/initwithtitle:accessibilitydescription:icon:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2StyledText":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","title":"SBSDKUI2StyledText","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2styledtext","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"type":"topic","abstract":[{"text":"Configuration of the text field appearance.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IconStyle\/title","value":"SBSDKUI2IconStyle","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IconStyle\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IconStyle\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PopupMenuItem\/title","value":"SBSDKUI2PopupMenuItem"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PopupMenuItem\/fragments","value":[{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PopupMenuItem\/navigatorTitle","value":[{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/title","op":"replace","value":"SBSDKUI2StyledText"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/fragments","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/navigatorTitle"}]}]}