{"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorGlareDetectionConfiguration(py)glareDetectionThreshold","title":"glareDetectionThreshold","role":"symbol","navigatorTitle":[{"text":"glareDetectionThreshold","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"glareDetectionThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorGlareDetectionConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorGlareDetectionConfiguration\/glareDetectionThreshold","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"glareDetectionThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"Default is 0.5","type":"text"}],"type":"paragraph"}]}],"abstract":[{"text":"Glare detection threshold.","type":"text"},{"text":" ","type":"text"},{"text":"The value should be in the range [0.0, 1.0].","type":"text"},{"text":" ","type":"text"},{"text":"Determines how much glare is acceptable relative to the text size. So 0.5 means that the glare can be up to 50% of the text size.","type":"text"},{"text":" ","type":"text"},{"text":"If set to 0.0, the feature is disabled.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorglaredetectionconfiguration\/glaredetectionthreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorglaredetectionconfiguration\/glaredetectionthreshold"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorGlareDetectionConfiguration":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorglaredetectionconfiguration","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorGlareDetectionConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorGlareDetectionConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDataExtractorGlareDetectionConfiguration","kind":"identifier"}],"title":"SBSDKDocumentDataExtractorGlareDetectionConfiguration","abstract":[{"text":"Glare detection configuration.","type":"text"},{"text":" ","type":"text"},{"text":"The recognizer will detect whether fields are obstructed by glare. This feature is enabled by default.","type":"text"},{"text":" ","type":"text"},{"text":"This configuration has no effect in SINGLE_SHOT mode.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorGlareDetectionConfiguration/glareDetectionThreshold":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorGlareDetectionConfiguration\/glareDetectionThreshold","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorglaredetectionconfiguration\/glaredetectionthreshold","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"glareDetectionThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"glareDetectionThreshold"}],"abstract":[{"text":"Glare detection threshold.","type":"text"},{"text":" ","type":"text"},{"text":"The value should be in the range [0.0, 1.0].","type":"text"},{"text":" ","type":"text"},{"text":"Determines how much glare is acceptable relative to the text size. So 0.5 means that the glare can be up to 50% of the text size.","type":"text"},{"text":" ","type":"text"},{"text":"If set to 0.0, the feature is disabled.","type":"text"}],"title":"glareDetectionThreshold","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"glareDetectionThreshold"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"glareDetectionThreshold"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"glareDetectionThreshold"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorGlareDetectionConfiguration\/title","op":"replace","value":"SBSDKDocumentDataExtractorGlareDetectionConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorGlareDetectionConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDataExtractorGlareDetectionConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorGlareDetectionConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorGlareDetectionConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorGlareDetectionConfiguration~1glareDetectionThreshold\/title","op":"replace","value":"glareDetectionThreshold"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorGlareDetectionConfiguration~1glareDetectionThreshold\/fragments","op":"replace","value":[{"text":"glareDetectionThreshold","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}