{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRoi:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"roi"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions\/initwithroi:"]}],"metadata":{"title":"initWithRoi:","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBasicImageLoadOptions(im)initWithRoi:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRoi:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithRoi:"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/initWithRoi:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBasicImageLoadOptions":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBasicImageLoadOptions"}],"navigatorTitle":[{"text":"SBSDKBasicImageLoadOptions","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions","role":"symbol","abstract":[{"type":"text","text":"Basic options for loading image."}],"title":"SBSDKBasicImageLoadOptions","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBasicImageLoadOptions/initWithRoi:":{"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions\/initwithroi:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/initWithRoi:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRoi:","kind":"identifier"}],"type":"topic","title":"initWithRoi:","navigatorTitle":[{"kind":"identifier","text":"initWithRoi:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions\/title","value":"SBSDKBasicImageLoadOptions"},{"value":[{"text":"SBSDKBasicImageLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBasicImageLoadOptions"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}