{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2finderstyle\/finderstrokedstyle()"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2finderstyle\/finderstrokedstyle()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2FinderStyle\/finderStrokedStyle()","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finderStrokedStyle"},{"kind":"text","text":"() -> "},{"text":"SBSDKUI2FinderStrokedStyle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2FinderStrokedStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2FinderStrokedStyle"}]}],"kind":"declarations"}],"metadata":{"title":"finderStrokedStyle()","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2FinderStyle(cm)finderStrokedStyle","navigatorTitle":[{"kind":"identifier","text":"finderStrokedStyle"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finderStrokedStyle"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2FinderStrokedStyle","text":"SBSDKUI2FinderStrokedStyle","kind":"typeIdentifier"}],"symbolKind":"method","roleHeading":"Type Method","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2FinderStyle"]]},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2FinderStyle/finderStrokedStyle()":{"type":"topic","title":"finderStrokedStyle()","navigatorTitle":[{"text":"finderStrokedStyle","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderStrokedStyle","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2FinderStrokedStyle","kind":"typeIdentifier","text":"SBSDKUI2FinderStrokedStyle"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2FinderStyle\/finderStrokedStyle()","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2finderstyle\/finderstrokedstyle()"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2FinderStrokedStyle":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2FinderStrokedStyle","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FinderStrokedStyle"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2finderstrokedstyle","type":"topic","abstract":[{"type":"text","text":"A variant of the viewfinder displaying a full outline of the scanning area."}],"title":"SBSDKUI2FinderStrokedStyle","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FinderStrokedStyle","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2FinderStyle":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2finderstyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FinderStyle","kind":"identifier"}],"abstract":[{"text":"The visual appearance of the viewfinder.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2FinderStyle","title":"SBSDKUI2FinderStyle","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FinderStyle"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"finderStrokedStyle"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"finderStrokedStyle","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2FinderStrokedStyle","text":"SBSDKUI2FinderStrokedStyle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2FinderStrokedStyle"},{"kind":"text","text":" *) "},{"text":"finderStrokedStyle","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2FinderStyle~1finderStrokedStyle()\/title","value":"finderStrokedStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2FinderStyle~1finderStrokedStyle()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"finderStrokedStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2FinderStrokedStyle\/title","value":"SBSDKUI2FinderStrokedStyle"},{"op":"replace","value":[{"text":"SBSDKUI2FinderStrokedStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2FinderStrokedStyle\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2FinderStrokedStyle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2FinderStrokedStyle\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2FinderStyle","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2FinderStyle\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2FinderStyle\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2FinderStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2FinderStyle\/navigatorTitle","value":[{"text":"SBSDKUI2FinderStyle","kind":"identifier"}]}]}]}