{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/hash","interfaceLanguage":"occ"},"metadata":{"title":"hash","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration(py)hash","symbolKind":"property","fragments":[{"text":"hash","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodetwotrackconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration":{"title":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodetwotrackconfiguration","type":"topic","abstract":[{"type":"text","text":"PHARMA_CODE_TWO_TRACK barcode configuration. Add to scanner configuration to scan Laetus two-track PharmaCode"},{"type":"text","text":" "},{"type":"text","text":"barcodes. Linear (i.e. one-track) PharmaCode scanning is configured separately through the PharmaCodeConfig class."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration/hash":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/hash","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodetwotrackconfiguration\/hash","fragments":[{"text":"hash","kind":"identifier"}],"title":"hash","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/title","value":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","kind":"identifier"}],"op":"replace"}]}]}