{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagestoring\/removeall()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagestoring\/removeall()"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Removes all stored images from the image storage."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring\/removeAll()","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAll","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"removeAllImages"}],"roleHeading":"Instance Method","title":"removeAll()","symbolKind":"method","required":true,"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring(im)removeAllImages","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(removeAllImages) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeAll","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageStoring/removeAll()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeAll","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagestoring\/removeall()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring\/removeAll()","navigatorTitle":[{"text":"removeAllImages","kind":"identifier"}],"kind":"symbol","title":"removeAll()","abstract":[{"type":"text","text":"Removes all stored images from the image storage."}],"required":true,"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageStoring":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring","url":"\/documentation\/scanbotsdk\/sbsdkimagestoring","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Protocol for an order-aware (array like) image storage."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageStoring","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKImageStoring","kind":"identifier"}],"title":"SBSDKImageStoring"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"removeAllImages"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"removeAllImages","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"removeAllImages","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring~1removeAll()\/title","value":"removeAllImages"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring~1removeAll()\/fragments","value":[{"kind":"text","text":"- "},{"text":"removeAllImages","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/title","op":"replace","value":"SBSDKImageStoring"},{"value":[{"kind":"identifier","text":"SBSDKImageStoring"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/fragments"},{"value":[{"text":"SBSDKImageStoring","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/navigatorTitle"}]}]}