{"abstract":[{"type":"text","text":"The width of the barcode polygons outline."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScanAndCountPolygonStyle\/lineWidth","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKScanAndCountPolygonStyle(py)lineWidth","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"lineWidth","kind":"identifier"}],"symbolKind":"property","role":"symbol","title":"lineWidth","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lineWidth"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScanAndCountPolygonStyle"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"lineWidth","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscanandcountpolygonstyle\/linewidth"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscanandcountpolygonstyle\/linewidth"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewController":{"type":"topic","title":"SBSDKBarcodeScanAndCountViewController","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode scanner."},{"text":" ","type":"text"},{"text":"Screen also shows snap, scan more and reset buttons.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The snap button starts the scanning when tapped."},{"text":" ","type":"text"},{"type":"text","text":"The snap button resets the scanning when tapped again."},{"type":"text","text":" "},{"type":"text","text":"Instead it is installing itself as a child view controller onto a given parent view controller."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScanAndCountPolygonStyle/lineWidth":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"lineWidth","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The width of the barcode polygons outline."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScanAndCountPolygonStyle\/lineWidth","url":"\/documentation\/scanbotsdk\/sbsdkscanandcountpolygonstyle\/linewidth","type":"topic","role":"symbol","title":"lineWidth","navigatorTitle":[{"text":"lineWidth","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScanAndCountPolygonStyle":{"type":"topic","title":"SBSDKScanAndCountPolygonStyle","abstract":[{"type":"text","text":"A class that represents the style of the polygon rendered around a barcode in "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController"},{"type":"text","text":"."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScanAndCountPolygonStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScanAndCountPolygonStyle"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKScanAndCountPolygonStyle","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkscanandcountpolygonstyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"lineWidth","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"lineWidth"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"lineWidth","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/title","value":"SBSDKBarcodeScanAndCountViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}]},{"op":"replace","value":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/navigatorTitle"},{"op":"replace","value":"lineWidth","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanAndCountPolygonStyle~1lineWidth\/title"},{"value":[{"kind":"identifier","text":"lineWidth"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanAndCountPolygonStyle~1lineWidth\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanAndCountPolygonStyle\/title","value":"SBSDKScanAndCountPolygonStyle"},{"op":"replace","value":[{"text":"SBSDKScanAndCountPolygonStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanAndCountPolygonStyle\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanAndCountPolygonStyle\/navigatorTitle","op":"replace","value":[{"text":"SBSDKScanAndCountPolygonStyle","kind":"identifier"}]}]}]}