{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerViewController"]]},"abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerViewController","isActive":true},{"text":", presents it modally and dismisses it when the user cancelled or finished the scanning.","type":"text"},{"text":" ","type":"text"},{"text":"In Swift language it is used with structured concurrency (async\/await).","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentAsync"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerConfiguration","text":"SBSDKUI2BarcodeScannerConfiguration","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerResult","kind":"typeIdentifier","text":"SBSDKUI2BarcodeScannerResult"},{"text":"?","kind":"text"}],"title":"presentAsync(on:configuration:)","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerViewController(cm)presentAsyncOn:configuration:completionHandler:","symbolKind":"method","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"presentAsyncOn:configuration:completionHandler:"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerviewcontroller\/presentasync(on:configuration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerviewcontroller\/presentasync(on:configuration:)"]}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentAsync","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":" ","kind":"text"},{"text":"presenter","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerConfiguration","text":"SBSDKUI2BarcodeScannerConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerResult","kind":"typeIdentifier","text":"SBSDKUI2BarcodeScannerResult"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The view controller the new instance should be presented on.","type":"text"}]}],"name":"presenter"},{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"text":"The configuration to define look and feel of the new detection view controller.","type":"text"}]}]}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The scanning result or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":", if an error was thrown or the screen has been cancelled."}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerViewController\/presentAsync(on:configuration:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerResult":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerResult","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerresult","title":"SBSDKUI2BarcodeScannerResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeScannerResult","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerResult","kind":"identifier"}],"abstract":[{"text":"Results of the barcode scan.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration","navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}],"title":"SBSDKUI2BarcodeScannerConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration of the barcode scanner screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerViewController":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerViewController","type":"topic","title":"SBSDKUI2BarcodeScannerViewController","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerviewcontroller","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerViewController"}],"abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to detect QR and barcodes."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerViewController/presentAsync(on:configuration:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerViewController\/presentAsync(on:configuration:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerviewcontroller\/presentasync(on:configuration:)","title":"presentAsync(on:configuration:)","kind":"symbol","abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerViewController","type":"reference","isActive":true},{"type":"text","text":", presents it modally and dismisses it when the user cancelled or finished the scanning."},{"type":"text","text":" "},{"type":"text","text":"In Swift language it is used with structured concurrency (async\/await)."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"presentAsync","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerConfiguration","text":"SBSDKUI2BarcodeScannerConfiguration"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerResult"},{"kind":"text","text":"?"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentAsyncOn:configuration:completionHandler:"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"presentAsyncOn:configuration:completionHandler:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"presentAsyncOn:configuration:completionHandler:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"presentAsyncOn:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"presenter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"configuration:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration","text":"SBSDKUI2BarcodeScannerConfiguration"},{"kind":"text","text":" *) "},{"text":"configuration","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerResult","text":"SBSDKUI2BarcodeScannerResult"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"presenter","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller the new instance should be presented on."}]}]},{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration to define look and feel of the new detection view controller."}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/primaryContentSections\/2","value":null},{"value":"SBSDKUI2BarcodeScannerResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerResult\/title"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeScannerResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerResult\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerResult\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration\/title","value":"SBSDKUI2BarcodeScannerConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}]},{"value":"SBSDKUI2BarcodeScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerViewController"}],"op":"replace"},{"op":"replace","value":"presentAsyncOn:configuration:completionHandler:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController~1presentAsync(on:configuration:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"presentAsyncOn:configuration:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController~1presentAsync(on:configuration:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}