{"abstract":[{"type":"text","text":"Clears the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController\/countedBarcodes"},{"text":" property.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"clearCountedBarcodes","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController"]]},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScanAndCountViewController(im)clearCountedBarcodes","role":"symbol","symbolKind":"method","title":"clearCountedBarcodes()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearCountedBarcodes"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"clearCountedBarcodes"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController\/clearCountedBarcodes()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller\/clearcountedbarcodes()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller\/clearcountedbarcodes()"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewController/clearCountedBarcodes()":{"type":"topic","title":"clearCountedBarcodes()","navigatorTitle":[{"text":"clearCountedBarcodes","kind":"identifier"}],"abstract":[{"type":"text","text":"Clears the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController\/countedBarcodes","isActive":true},{"type":"text","text":" property."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearCountedBarcodes"},{"kind":"text","text":"()"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController\/clearCountedBarcodes()","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller\/clearcountedbarcodes()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewController/countedBarcodes":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController\/countedBarcodes","navigatorTitle":[{"text":"countedBarcodes","kind":"identifier"}],"title":"countedBarcodes","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller\/countedbarcodes","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Stores all the scanned barcode results accumulated through multiple scans."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"countedBarcodes"},{"kind":"text","text":": ["},{"text":"SBSDKBarcodeScannerAccumulatingResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerAccumulatingResult","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewController":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController","navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"title":"SBSDKBarcodeScanAndCountViewController","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show a camera screen with the barcode detector.","type":"text"},{"type":"text","text":" "},{"text":"Screen also shows snap, scan more and reset buttons.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The snap button starts the scanning when tapped."},{"type":"text","text":" "},{"text":"The snap button resets the scanning when tapped again.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Instead it is installing itself as a child view controller onto a given parent view controller."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"clearCountedBarcodes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"clearCountedBarcodes"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"clearCountedBarcodes"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController~1clearCountedBarcodes()\/title","value":"clearCountedBarcodes","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"clearCountedBarcodes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController~1clearCountedBarcodes()\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController~1countedBarcodes\/title","value":"countedBarcodes","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController~1countedBarcodes\/fragments","value":[{"kind":"identifier","text":"countedBarcodes"}]},{"op":"replace","value":"SBSDKBarcodeScanAndCountViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/fragments","op":"replace"}]}]}