{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"bits128","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength\/bits128"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeylength\/bits128"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeylength\/bits128"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A key length of 128 bits (16 bytes) ."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength"]]},"kind":"symbol","metadata":{"roleHeading":"Case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKStorageCryptingKeyLength@SBSDKStorageCryptingKeyLengthBits128","title":"SBSDKStorageCryptingKeyLength.bits128","navigatorTitle":[{"text":"SBSDKStorageCryptingKeyLengthBits128","kind":"identifier"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"bits128","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingKeyLength/bits128":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bits128","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeylength\/bits128","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength\/bits128","title":"SBSDKStorageCryptingKeyLength.bits128","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLengthBits128"}],"abstract":[{"type":"text","text":"A key length of 128 bits (16 bytes) ."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingKeyLength":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeylength","title":"SBSDKStorageCryptingKeyLength","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"abstract":[{"type":"text","text":"The length of the encryption key."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKStorageCryptingKeyLengthBits128","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKStorageCryptingKeyLengthBits128","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLengthBits128"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"SBSDKStorageCryptingKeyLengthBits128","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength~1bits128\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength~1bits128\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLengthBits128"}],"op":"replace"},{"value":"SBSDKStorageCryptingKeyLength","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength\/title"},{"value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}