{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"abstract":[{"text":"ANTIALIASED - When the source image is a document photo, this mode","type":"text"},{"type":"text","text":" "},{"text":"will produce nice, smooth, antialiased text in grayscale, which is typically more readable","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"than the text in BINARY mode. Antialiasing requires extra processing,"},{"text":" ","type":"text"},{"type":"text","text":"which makes this mode slower than BINARY mode."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKOutputModeAntialiased"}],"symbolKind":"case","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"SBSDKOutputMode.antialiased","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKOutputMode@SBSDKOutputModeAntialiased","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"antialiased","kind":"identifier"}],"roleHeading":"Case"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"antialiased"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkoutputmode\/antialiased"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkoutputmode\/antialiased"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKOutputMode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKOutputMode\/antialiased"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKOutputMode/antialiased":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkoutputmode\/antialiased","kind":"symbol","title":"SBSDKOutputMode.antialiased","navigatorTitle":[{"text":"SBSDKOutputModeAntialiased","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"ANTIALIASED - When the source image is a document photo, this mode"},{"text":" ","type":"text"},{"type":"text","text":"will produce nice, smooth, antialiased text in grayscale, which is typically more readable"},{"text":" ","type":"text"},{"text":"than the text in BINARY mode. Antialiasing requires extra processing,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"which makes this mode slower than BINARY mode."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"antialiased"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKOutputMode\/antialiased"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKOutputMode":{"title":"SBSDKOutputMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOutputMode","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkoutputmode","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKOutputMode","abstract":[{"type":"text","text":"Output mode of binarization filter."}],"navigatorTitle":[{"text":"SBSDKOutputMode","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKOutputModeAntialiased"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKOutputModeAntialiased"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKOutputModeAntialiased","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKOutputModeAntialiased","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKOutputMode~1antialiased\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOutputModeAntialiased"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKOutputMode~1antialiased\/fragments"},{"value":"SBSDKOutputMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKOutputMode\/title"},{"value":[{"text":"SBSDKOutputMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKOutputMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKOutputMode\/navigatorTitle","value":[{"text":"SBSDKOutputMode","kind":"identifier"}],"op":"replace"}]}]}