{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"To choose between multiple sounds to play."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/type"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKSoundType","text":"SBSDKSoundType","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"Defaults to ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType\/modern","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdksoundcontroller\/type"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdksoundcontroller\/type"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"type"}],"title":"type","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSoundController(py)type","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKSoundType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKSoundType"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController"]]},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundController":{"url":"\/documentation\/scanbotsdk\/sbsdksoundcontroller","title":"SBSDKSoundController","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKSoundController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController","abstract":[{"type":"text","text":"A class to manage playback of sounds and vibration."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSoundController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundType/modern":{"title":"SBSDKSoundType.modern","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"modern"}],"url":"\/documentation\/scanbotsdk\/sbsdksoundtype\/modern","type":"topic","abstract":[{"text":"To choose the modern beep sound.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType\/modern","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKSoundTypeModern"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundType":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSoundType"}],"type":"topic","abstract":[{"text":"The sound selection type.","type":"text"}],"kind":"symbol","title":"SBSDKSoundType","navigatorTitle":[{"text":"SBSDKSoundType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType","url":"\/documentation\/scanbotsdk\/sbsdksoundtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundController/type":{"url":"\/documentation\/scanbotsdk\/sbsdksoundcontroller\/type","navigatorTitle":[{"kind":"identifier","text":"type"}],"type":"topic","title":"type","role":"symbol","abstract":[{"type":"text","text":"To choose between multiple sounds to play."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKSoundType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKSoundType"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/type"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"type","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"type","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKSoundType","kind":"typeIdentifier","text":"SBSDKSoundType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKSoundController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController\/title","op":"replace"},{"value":[{"text":"SBSDKSoundController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKSoundController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController\/navigatorTitle","op":"replace"},{"value":"SBSDKSoundTypeModern","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundType~1modern\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKSoundTypeModern"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundType~1modern\/fragments","op":"replace"},{"value":"SBSDKSoundType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundType\/title","op":"replace"},{"value":[{"text":"SBSDKSoundType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundType\/fragments","op":"replace"},{"value":[{"text":"SBSDKSoundType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundType\/navigatorTitle","op":"replace"},{"value":"type","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController~1type\/title","op":"replace"},{"value":[{"text":"type","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController~1type\/fragments","op":"replace"}]}]}