{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reorderpagesscreenconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReorderPagesScreenConfiguration\/hash"},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"fragments":[{"text":"hash","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","title":"hash","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReorderPagesScreenConfiguration(py)hash","symbolKind":"property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReorderPagesScreenConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReorderPagesScreenConfiguration/hash":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reorderpagesscreenconfiguration\/hash","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReorderPagesScreenConfiguration\/hash","fragments":[{"text":"hash","kind":"identifier"}],"abstract":[],"title":"hash","role":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReorderPagesScreenConfiguration":{"kind":"symbol","title":"SBSDKUI2ReorderPagesScreenConfiguration","navigatorTitle":[{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration of the screen for reordering the scanned pages.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReorderPagesScreenConfiguration","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reorderpagesscreenconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/title","value":"SBSDKUI2ReorderPagesScreenConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ReorderPagesScreenConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}],"op":"replace"}]}]}