{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller\/camerasession:didoutput:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController\/cameraSession:didOutput:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cameraSession:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCameraSession","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCameraSession","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didOutput:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBaseScannerFrame","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerFrame","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerFrame"},{"text":" *) ","kind":"text"},{"text":"frame","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"role":"symbol","symbolKind":"method","title":"cameraSession:didOutput:","roleHeading":"Instance Method","externalID":"c:@CM@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerViewController(im)cameraSession:didOutput:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cameraSession:didOutput:"}],"navigatorTitle":[{"kind":"identifier","text":"cameraSession:didOutput:"}]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewController/cameraSession:didOutput:":{"type":"topic","title":"cameraSession:didOutput:","role":"symbol","navigatorTitle":[{"text":"cameraSession:didOutput:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller\/camerasession:didoutput:","fragments":[{"text":"- ","kind":"text"},{"text":"cameraSession:didOutput:","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController\/cameraSession:didOutput:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraSession":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}],"title":"SBSDKCameraSession","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSession","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession","abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"type":"text","text":" "},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewController":{"abstract":[{"type":"text","text":"A highly customizable camera view controller that delivers a basic camera functionality along with video"},{"type":"text","text":" "},{"type":"text","text":"frame extraction and preprocessing, orientation correction and still image capturing."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller","title":"SBSDKBaseScannerViewController","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerFrame":{"abstract":[{"type":"text","text":"A wrapper class for video frames."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerFrame","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerframe","title":"SBSDKBaseScannerFrame"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/title","value":"SBSDKCameraSession"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraSession"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCameraSession"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/title","value":"SBSDKBaseScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/fragments","value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/navigatorTitle","value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerFrame\/title","value":"SBSDKBaseScannerFrame"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerFrame\/fragments","value":[{"text":"SBSDKBaseScannerFrame","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerFrame\/navigatorTitle","value":[{"text":"SBSDKBaseScannerFrame","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}