{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/us5x7"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/us5x7"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize@SBSDKPDFRendererPageSizeUs5x7","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"us5x7"}],"role":"symbol","symbolKind":"case","roleHeading":"Case","title":"SBSDKPDFRendererPageSize.us5x7","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageSizeUs5x7"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/us5x7","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"us5x7"}],"languages":["swift"]}]}],"abstract":[{"text":"The page has US 5x7 size: 4x6 inches. The image is fitted and centered within the page.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize","navigatorTitle":[{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize","type":"topic","title":"SBSDKPDFRendererPageSize","kind":"symbol","abstract":[{"type":"text","text":"Specifies the desired page size (media box size) for PDF rendering operations."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize/us5x7":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/us5x7","title":"SBSDKPDFRendererPageSize.us5x7","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/us5x7","type":"topic","kind":"symbol","abstract":[{"text":"The page has US 5x7 size: 4x6 inches. The image is fitted and centered within the page.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"us5x7"}],"navigatorTitle":[{"text":"SBSDKPDFRendererPageSizeUs5x7","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKPDFRendererPageSizeUs5x7"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageSizeUs5x7"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKPDFRendererPageSizeUs5x7"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/title","value":"SBSDKPDFRendererPageSize"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/fragments","value":[{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPDFRendererPageSize"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1us5x7\/title","op":"replace","value":"SBSDKPDFRendererPageSizeUs5x7"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1us5x7\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageSizeUs5x7"}]}]}]}