{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpageimagesource\/manualsnap"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpageimagesource\/manualsnap"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageImageSource"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"manualSnap","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageImageSource\/manualSnap"},"metadata":{"roleHeading":"Case","title":"SBSDKPageImageSource.manualSnap","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKPageImageSource@SBSDKPageImageSourceManualSnap","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"manualSnap"}],"symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKPageImageSourceManualSnap","kind":"identifier"}]},"sections":[],"abstract":[{"text":"The image was captured manually.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageImageSource/manualSnap":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageImageSource\/manualSnap","title":"SBSDKPageImageSource.manualSnap","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"manualSnap","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The image was captured manually."}],"url":"\/documentation\/scanbotsdk\/sbsdkpageimagesource\/manualsnap","navigatorTitle":[{"text":"SBSDKPageImageSourceManualSnap","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageImageSource":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageImageSource","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpageimagesource","type":"topic","title":"SBSDKPageImageSource","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageImageSource","kind":"symbol","abstract":[{"type":"text","text":"The source of an image."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKPageImageSource","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKPageImageSourceManualSnap"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPageImageSourceManualSnap"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKPageImageSourceManualSnap"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageImageSource~1manualSnap\/title","op":"replace","value":"SBSDKPageImageSourceManualSnap"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageImageSource~1manualSnap\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPageImageSourceManualSnap"}]},{"value":"SBSDKPageImageSource","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageImageSource\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPageImageSource"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageImageSource\/fragments","op":"replace"},{"value":[{"text":"SBSDKPageImageSource","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageImageSource\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}