{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerTextConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannertextconfiguration\/texthintbadaspectratio"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannertextconfiguration\/texthintbadaspectratio"]}],"sections":[],"abstract":[{"text":"The text being displayed on the user-guidance label, when a document was detected,","type":"text"},{"type":"text","text":" "},{"text":"but the aspect ratio of the document is inverse to the cameras aspect ratio.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textHintBadAspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"textHintBadAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"textHintBadAspectRatio","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"textHintBadAspectRatio"}],"platforms":[],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerTextConfiguration(py)textHintBadAspectRatio","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property"},"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}],"type":"paragraph"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerTextConfiguration\/textHintBadAspectRatio"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerTextConfiguration":{"abstract":[{"type":"text","text":"Configuration for the textual contents of the document scanning screen."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIDocumentScannerTextConfiguration"}],"title":"SBSDKUIDocumentScannerTextConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerTextConfiguration"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannertextconfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerTextConfiguration","deprecated":true,"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerTextConfiguration/textHintBadAspectRatio":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textHintBadAspectRatio","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"textHintBadAspectRatio","abstract":[{"text":"The text being displayed on the user-guidance label, when a document was detected,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"but the aspect ratio of the document is inverse to the cameras aspect ratio."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"textHintBadAspectRatio"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannertextconfiguration\/texthintbadaspectratio","type":"topic","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerTextConfiguration\/textHintBadAspectRatio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"textHintBadAspectRatio","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"textHintBadAspectRatio","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"textHintBadAspectRatio","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUIDocumentScannerTextConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerTextConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerTextConfiguration\/fragments","value":[{"text":"SBSDKUIDocumentScannerTextConfiguration","kind":"identifier"}]},{"op":"replace","value":"textHintBadAspectRatio","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerTextConfiguration~1textHintBadAspectRatio\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerTextConfiguration~1textHintBadAspectRatio\/fragments","op":"replace","value":[{"kind":"identifier","text":"textHintBadAspectRatio"}]}]}]}