{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerConfiguration","text":"SBSDKGenericTextLineRecognizerConfiguration"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerconfiguration\/defaultconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerconfiguration\/defaultconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration\/defaultConfiguration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The default configuration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericTextLineRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerConfiguration"}],"title":"defaultConfiguration","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerConfiguration(cpy)defaultConfiguration","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"defaultConfiguration"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerConfiguration/defaultConfiguration":{"role":"symbol","title":"defaultConfiguration","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericTextLineRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerConfiguration"}],"abstract":[{"type":"text","text":"The default configuration."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration\/defaultConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerconfiguration\/defaultconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizer":{"role":"symbol","title":"SBSDKGenericTextLineRecognizer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericTextLineRecognizer"}],"abstract":[{"type":"text","text":"A class to recognize one line of text in a small area and run validation on the result."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizer"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerConfiguration":{"role":"symbol","title":"SBSDKGenericTextLineRecognizerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerConfiguration"}],"abstract":[{"type":"text","text":"A descriptor class to configure an instance of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.3"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"defaultConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultConfiguration"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerConfiguration","text":"SBSDKGenericTextLineRecognizerConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"defaultConfiguration"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration~1defaultConfiguration\/title","value":"defaultConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration~1defaultConfiguration\/fragments","value":[{"kind":"identifier","text":"defaultConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer\/title","value":"SBSDKGenericTextLineRecognizer"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizer"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration\/title","value":"SBSDKGenericTextLineRecognizerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}