{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerConfiguration(py)validationBlock","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"validationBlock","kind":"identifier"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"))?"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"validationBlock","kind":"identifier"}],"title":"validationBlock","modules":[{"name":"ScanbotSDK"}]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration\/validationBlock","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validationBlock"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"))?"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The recognized string is passed to the block as parameter and the block must return "},{"type":"codeVoice","code":"True"},{"text":", if the result is","type":"text"},{"type":"text","text":" "},{"type":"text","text":"accepted. Return "},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}]},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The validationPattern is ignored if this property is non-nil."}]}],"name":"Note","style":"note"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"A callback block used to validate the recognized text.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerconfiguration\/validationblock"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerconfiguration\/validationblock"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizer":{"kind":"symbol","title":"SBSDKGenericTextLineRecognizer","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}],"abstract":[{"type":"text","text":"A class to recognize one line of text in a small area and run validation on the result."}],"navigatorTitle":[{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizer","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerConfiguration/validationBlock":{"kind":"symbol","title":"validationBlock","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validationBlock"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> ("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":"))?","kind":"text"}],"abstract":[{"type":"text","text":"A callback block used to validate the recognized text."}],"navigatorTitle":[{"text":"validationBlock","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerconfiguration\/validationblock","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration\/validationBlock","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerConfiguration":{"kind":"symbol","title":"SBSDKGenericTextLineRecognizerConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericTextLineRecognizerConfiguration","kind":"identifier"}],"abstract":[{"text":"A descriptor class to configure an instance of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"SBSDKGenericTextLineRecognizerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"validationBlock"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"validationBlock"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" (^","kind":"text"},{"text":"validationBlock","kind":"identifier"},{"kind":"text","text":")("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":");"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer\/title","value":"SBSDKGenericTextLineRecognizer","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizer"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer\/fragments","op":"replace"},{"value":"validationBlock","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration~1validationBlock\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration~1validationBlock\/fragments","op":"replace","value":[{"kind":"identifier","text":"validationBlock"}]},{"value":"SBSDKGenericTextLineRecognizerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKGenericTextLineRecognizerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration\/fragments"}]}]}