{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerconfiguration\/validationpatternsubstringmatchingenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerconfiguration\/validationpatternsubstringmatchingenabled"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration\/validationPatternSubstringMatchingEnabled","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","title":"validationPatternSubstringMatchingEnabled","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerConfiguration(py)validationPatternSubstringMatchingEnabled","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validationPatternSubstringMatchingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"validationPatternSubstringMatchingEnabled"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"If set to "},{"code":"False","type":"codeVoice"},{"type":"text","text":", the whole recognized text must match the pattern in order to validate, otherwise the validation"},{"type":"text","text":" "},{"text":"will be also successful if the recognized text contains a substring that matches the validation pattern.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validationPatternSubstringMatchingEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"False"},{"text":".","type":"text"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizer":{"navigatorTitle":[{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizer","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer","abstract":[{"text":"A class to recognize one line of text in a small area and run validation on the result.","type":"text"}],"title":"SBSDKGenericTextLineRecognizer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerConfiguration":{"navigatorTitle":[{"text":"SBSDKGenericTextLineRecognizerConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericTextLineRecognizerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerconfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration","abstract":[{"type":"text","text":"A descriptor class to configure an instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer","isActive":true},{"type":"text","text":"."}],"title":"SBSDKGenericTextLineRecognizerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerConfiguration/validationPatternSubstringMatchingEnabled":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"validationPatternSubstringMatchingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"False"},{"type":"text","text":", the whole recognized text must match the pattern in order to validate, otherwise the validation"},{"text":" ","type":"text"},{"text":"will be also successful if the recognized text contains a substring that matches the validation pattern.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration\/validationPatternSubstringMatchingEnabled","navigatorTitle":[{"kind":"identifier","text":"validationPatternSubstringMatchingEnabled"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerconfiguration\/validationpatternsubstringmatchingenabled","title":"validationPatternSubstringMatchingEnabled"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"validationPatternSubstringMatchingEnabled","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"validationPatternSubstringMatchingEnabled","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"text":"validationPatternSubstringMatchingEnabled","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer\/title","value":"SBSDKGenericTextLineRecognizer"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizer"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer\/navigatorTitle","value":[{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration\/title","value":"SBSDKGenericTextLineRecognizerConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration\/navigatorTitle","value":[{"text":"SBSDKGenericTextLineRecognizerConfiguration","kind":"identifier"}]},{"value":"validationPatternSubstringMatchingEnabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration~1validationPatternSubstringMatchingEnabled\/title"},{"value":[{"text":"validationPatternSubstringMatchingEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration~1validationPatternSubstringMatchingEnabled\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}