{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod11ibm"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod11ibm"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod11IBM","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mod11IBM","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm"]]},"abstract":[{"type":"text","text":"Mod11IBM."}],"metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11IBM"}],"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mod11IBM"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeMSIPlesseyChecksumAlgorithm@SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11IBM","roleHeading":"Case","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod11IBM"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod11IBM":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mod11IBM","kind":"identifier"}],"abstract":[{"text":"Mod11IBM.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod11ibm","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod11IBM","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod11IBM","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11IBM","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm":{"abstract":[{"text":"The checksum algorithm for MSI-Plessey type barcodes.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11IBM","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11IBM","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11IBM","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11IBM","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod11IBM\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11IBM"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod11IBM\/fragments"},{"op":"replace","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}