{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}]}]}],"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"title":"isEqual:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKColorDocumentFilter(im)isEqual:","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/isEqual:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorDocumentFilter/isEqual:":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter\/isequal:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"role":"symbol","title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/isEqual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorDocumentFilter":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKColorDocumentFilter"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter","abstract":[{"text":"Color document filter. This filter is a good starting point for most use cases.","type":"text"}],"navigatorTitle":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"title":"SBSDKColorDocumentFilter","url":"\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKColorDocumentFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKColorDocumentFilter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKColorDocumentFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/navigatorTitle"}]}]}