{"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress(py)cancelled","fragments":[{"kind":"identifier","text":"cancelled"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"cancelled"}],"roleHeading":"Instance Property","title":"cancelled","role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress\/cancelled"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":", ","kind":"text"},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"text":"isCancelled","kind":"identifier"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"cancelled","kind":"identifier"},{"text":";","kind":"text"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/cancelled","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress":{"role":"symbol","title":"SBSDKProgress","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProgress","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKProgress","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress/cancelled":{"fragments":[{"text":"cancelled","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress\/cancelled","abstract":[],"kind":"symbol","title":"cancelled","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress\/cancelled"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/title","value":"SBSDKProgress"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/fragments","value":[{"text":"SBSDKProgress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/navigatorTitle","value":[{"text":"SBSDKProgress","kind":"identifier"}]}]}]}