{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"title":"barcodeScannerController:didScanBarcodes:","navigatorTitle":[{"text":"barcodeScannerController:didScanBarcodes:","kind":"identifier"}],"externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController(im)barcodeScannerController:didScanBarcodes:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"barcodeScannerController:didScanBarcodes:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeScannerController:didScanBarcodes:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodescannercontroller:didscanbarcodes:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"barcodeScannerController:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","kind":"typeIdentifier","text":"SBSDKBarcodeScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"didScanBarcodes:"},{"kind":"text","text":"("},{"text":"NSArray<SBSDKBarcodeItem *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"codes","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController/barcodeScannerController:didScanBarcodes:":{"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"barcodeScannerController:didScanBarcodes:"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodescannercontroller:didscanbarcodes:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeScannerController:didScanBarcodes:","kind":"symbol","title":"barcodeScannerController:didScanBarcodes:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeScannerController:didScanBarcodes:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"title":"SBSDKUIBarcodesBatchScannerViewController","abstract":[{"text":"A highly customizable camera-based view controller to scan barcodes batches.","type":"text"}],"type":"topic","role":"symbol","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController":{"abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to show a camera screen with the barcode scanner.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","type":"topic","title":"SBSDKBarcodeScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKUIBarcodesBatchScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/navigatorTitle","op":"replace"},{"value":"SBSDKBarcodeScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/title","op":"replace"},{"value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/fragments","op":"replace"},{"value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}