{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter\/colorDocumentFilter()","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"metadata":{"role":"symbol","roleHeading":"Type Method","title":"colorDocumentFilter()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"colorDocumentFilter","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKColorDocumentFilter","text":"SBSDKColorDocumentFilter","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","externalID":"s:10ScanbotSDK21SBSDKParametricFilterC013colorDocumentD0AA010SBSDKColorfD0CyFZ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkparametricfilter\/colordocumentfilter()"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"colorDocumentFilter","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKColorDocumentFilter","text":"SBSDKColorDocumentFilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","title":"SBSDKParametricFilter","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKParametricFilter"}],"url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter","role":"symbol","abstract":[{"text":"Base class for all parametric filters.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter/colorDocumentFilter()":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter\/colordocumentfilter()","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter\/colorDocumentFilter()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorDocumentFilter"},{"text":"() -> ","kind":"text"},{"text":"SBSDKColorDocumentFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKColorDocumentFilter","kind":"typeIdentifier"}],"type":"topic","title":"colorDocumentFilter()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorDocumentFilter":{"type":"topic","abstract":[{"text":"Color document filter. This filter is a good starting point for most use cases.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKColorDocumentFilter"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKColorDocumentFilter"}],"url":"\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter","kind":"symbol","title":"SBSDKColorDocumentFilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKParametricFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title"},{"op":"replace","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments"},{"op":"replace","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/navigatorTitle"},{"op":"replace","value":"SBSDKColorDocumentFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/title"},{"op":"replace","value":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKColorDocumentFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}