{"metadata":{"extendedModule":"SwiftUICore","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}],"symbolKind":"method","title":"preference(key:value:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preference","kind":"identifier"},{"text":"<","kind":"text"},{"text":"K","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"K","kind":"typeIdentifier"},{"text":".Type, ","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"K","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Value","preciseIdentifier":"s:7SwiftUI13PreferenceKeyP5ValueQa","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"roleHeading":"Instance Method","externalID":"s:7SwiftUI4ViewPAAE10preference3key5valueQrqd__m_5ValueQyd__tAA13PreferenceKeyRd__lF::SYNTHESIZED::s:10ScanbotSDK26SBSDKUI2BarcodeScannerViewV","platforms":[{"deprecated":false,"introducedAt":"13.0","unavailable":false,"name":"iOS","beta":false},{"deprecated":false,"introducedAt":"13.0","unavailable":false,"name":"iPadOS","beta":false},{"deprecated":false,"introducedAt":"13.0","unavailable":false,"name":"Mac Catalyst","beta":false},{"deprecated":false,"introducedAt":"10.15","unavailable":false,"name":"macOS","beta":false},{"deprecated":false,"introducedAt":"13.0","unavailable":false,"name":"tvOS","beta":false},{"deprecated":false,"introducedAt":"6.0","unavailable":false,"name":"watchOS","beta":false}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preference","kind":"identifier"},{"text":"<","kind":"text"},{"text":"K","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"K","kind":"typeIdentifier"},{"text":".Type = K.self, ","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"K","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Value","preciseIdentifier":"s:7SwiftUI13PreferenceKeyP5ValueQa","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"K","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"PreferenceKey","preciseIdentifier":"s:7SwiftUI13PreferenceKeyP","kind":"typeIdentifier"},{"text":"\n","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView\/preference(key:value:)","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"View.preference(key:value:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView\/View-Implementations"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview\/preference(key:value:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerView/preference(key:value:)":{"role":"symbol","title":"preference(key:value:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView\/preference(key:value:)","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview\/preference(key:value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preference"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"K"},{"kind":"text","text":">("},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"K"},{"kind":"text","text":".Type, "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"K"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:7SwiftUI13PreferenceKeyP5ValueQa"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerView/View-Implementations":{"title":"View Implementations","kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview\/view-implementations","type":"topic","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView\/View-Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerviewcontroller","navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerViewController","kind":"identifier"}],"title":"SBSDKUI2BarcodeScannerViewController","abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to scan QR and barcodes."}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeScannerViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerView":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview","title":"SBSDKUI2BarcodeScannerView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeScannerView","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerView","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerViewController"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/title","value":"SBSDKUI2BarcodeScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerViewController"}]}]}]}