{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcaptureinfo\/pageimagesource"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcaptureinfo\/pageimagesource"]}],"metadata":{"title":"pageImageSource","symbolKind":"property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCaptureInfo(py)pageImageSource","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageImageSource","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPageImageSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKPageImageSource"}],"navigatorTitle":[{"text":"pageImageSource","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCaptureInfo"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCaptureInfo\/pageImageSource","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The source the image was received from."}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageImageSource","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPageImageSource","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPageImageSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKPageImageSource"},{"text":" { get }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPageImageSource":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPageImageSource","title":"SBSDKPageImageSource","role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpageimagesource","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageImageSource"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageImageSource"}],"abstract":[{"type":"text","text":"The source of an image."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCaptureInfo/pageImageSource":{"abstract":[{"text":"The source the image was received from.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"pageImageSource","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCaptureInfo\/pageImageSource","title":"pageImageSource","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageImageSource","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPageImageSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKPageImageSource"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcaptureinfo\/pageimagesource"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCaptureInfo":{"kind":"symbol","type":"topic","title":"SBSDKCaptureInfo","navigatorTitle":[{"kind":"identifier","text":"SBSDKCaptureInfo"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcaptureinfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCaptureInfo"}],"abstract":[{"text":"Helper class, that gathers the image, camera and detection metadata of a document scan.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCaptureInfo"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"pageImageSource","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"pageImageSource","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKPageImageSource","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPageImageSource","kind":"typeIdentifier","text":"SBSDKPageImageSource"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageImageSource"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKPageImageSource","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPageImageSource\/title"},{"op":"replace","value":[{"text":"SBSDKPageImageSource","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPageImageSource\/fragments"},{"op":"replace","value":[{"text":"SBSDKPageImageSource","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPageImageSource\/navigatorTitle"},{"op":"replace","value":"pageImageSource","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCaptureInfo~1pageImageSource\/title"},{"op":"replace","value":[{"text":"pageImageSource","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCaptureInfo~1pageImageSource\/fragments"},{"op":"replace","value":"SBSDKCaptureInfo","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCaptureInfo\/title"},{"op":"replace","value":[{"text":"SBSDKCaptureInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCaptureInfo\/fragments"},{"op":"replace","value":[{"text":"SBSDKCaptureInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCaptureInfo\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}