{"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2DocumentScannerViewController instead."}],"type":"paragraph"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/bottombarbuttonscolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/bottombarbuttonscolor"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomBarButtonsColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/bottomBarButtonsColor","interfaceLanguage":"swift"},"abstract":[{"text":"Foreground color of the buttons in the bottom bar.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"platforms":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomBarButtonsColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","symbolKind":"property","title":"bottomBarButtonsColor","roleHeading":"Instance Property","navigatorTitle":[{"text":"bottomBarButtonsColor","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerUIConfiguration(py)bottomBarButtonsColor"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/bottomBarButtonsColor":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/bottomBarButtonsColor","title":"bottomBarButtonsColor","deprecated":true,"kind":"symbol","navigatorTitle":[{"text":"bottomBarButtonsColor","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomBarButtonsColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"text":"Foreground color of the buttons in the bottom bar.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/bottombarbuttonscolor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerUIConfiguration"}],"title":"SBSDKUIDocumentScannerUIConfiguration","kind":"symbol","abstract":[{"text":"Configuration for the user interface of the document scanning screen.","type":"text"}],"role":"symbol","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerUIConfiguration"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"bottomBarButtonsColor","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"bottomBarButtonsColor","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"bottomBarButtonsColor","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"bottomBarButtonsColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1bottomBarButtonsColor\/title"},{"op":"replace","value":[{"kind":"identifier","text":"bottomBarButtonsColor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1bottomBarButtonsColor\/fragments"},{"op":"replace","value":"SBSDKUIDocumentScannerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}