{"abstract":[{"text":"The 35mm equivalent focal length of the lens used to capture the image. Measured in millimeters. Readonly.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/focalLength35mm"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagemetadata\/focallength35mm"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagemetadata\/focallength35mm"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"focalLength35mm","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"aside","style":"note","name":"Note","content":[{"inlineContent":[{"text":"Returns -1.0, if the value is not present in the metadata.","type":"text"}],"type":"paragraph"}]}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageMetadata(py)focalLength35mm","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"focalLength35mm","kind":"identifier"}],"roleHeading":"Instance Property","title":"focalLength35mm","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"focalLength35mm","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata":{"url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageMetadata","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Encapsulates image metadata, e.g. EXIF, TIFF, JFIF in a convenient way.","type":"text"},{"text":" ","type":"text"},{"text":"Use ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadataProcessor"},{"text":" to extract metadata from and inject changed metadata into image data.","type":"text"}],"title":"SBSDKImageMetadata","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata","navigatorTitle":[{"text":"SBSDKImageMetadata","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadataProcessor":{"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagemetadataprocessor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageMetadataProcessor"}],"abstract":[{"type":"text","text":"Helper class to extract or inject image metadata, e.g. EXIF, TIFF, JFIF from  image data."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadataProcessor","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageMetadataProcessor"}],"title":"SBSDKImageMetadataProcessor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/focalLength35mm":{"role":"symbol","abstract":[{"text":"The 35mm equivalent focal length of the lens used to capture the image. Measured in millimeters. Readonly.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"focalLength35mm","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/focallength35mm","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/focalLength35mm","title":"focalLength35mm","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"focalLength35mm","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"focalLength35mm","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"focalLength35mm","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"focalLength35mm","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKImageMetadata","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata\/title"},{"value":[{"text":"SBSDKImageMetadata","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata\/navigatorTitle","value":[{"text":"SBSDKImageMetadata","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadataProcessor\/title","value":"SBSDKImageMetadataProcessor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadataProcessor\/fragments","value":[{"kind":"identifier","text":"SBSDKImageMetadataProcessor"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadataProcessor\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageMetadataProcessor"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1focalLength35mm\/title","value":"focalLength35mm"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1focalLength35mm\/fragments","value":[{"text":"focalLength35mm","kind":"identifier"}]}]}]}