{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport\/initWithFieldType:consistency:fieldFullNames:","interfaceLanguage":"occ"},"metadata":{"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithFieldType:consistency:fieldFullNames:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithFieldType:consistency:fieldFullNames:","kind":"identifier"}],"title":"initWithFieldType:consistency:fieldFullNames:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldConsistencyVerificationReport(im)initWithFieldType:consistency:fieldFullNames:"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithFieldType:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKCommonFieldType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCommonFieldType"},{"kind":"text","text":" *) "},{"text":"fieldType","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"consistency:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueConsistency","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency","text":"SBSDKValueConsistency","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"consistency","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fieldFullNames:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"fieldFullNames"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfieldconsistencyverificationreport\/initwithfieldtype:consistency:fieldfullnames:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldConsistencyVerificationReport":{"abstract":[{"type":"text","text":"Report of the field consistency verification."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport","title":"SBSDKFieldConsistencyVerificationReport","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfieldconsistencyverificationreport","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFieldConsistencyVerificationReport"}],"navigatorTitle":[{"text":"SBSDKFieldConsistencyVerificationReport","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency":{"title":"SBSDKValueConsistency","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency","navigatorTitle":[{"text":"SBSDKValueConsistency","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency","type":"topic","abstract":[{"type":"text","text":"The status of the consistency verification."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKValueConsistency"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldConsistencyVerificationReport/initWithFieldType:consistency:fieldFullNames:":{"url":"\/documentation\/scanbotsdk\/sbsdkfieldconsistencyverificationreport\/initwithfieldtype:consistency:fieldfullnames:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithFieldType:consistency:fieldFullNames:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport\/initWithFieldType:consistency:fieldFullNames:","type":"topic","abstract":[],"navigatorTitle":[{"text":"initWithFieldType:consistency:fieldFullNames:","kind":"identifier"}],"kind":"symbol","title":"initWithFieldType:consistency:fieldFullNames:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCommonFieldType":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKCommonFieldType","kind":"identifier"}],"title":"SBSDKCommonFieldType","abstract":[{"text":"Common field types.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcommonfieldtype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType","navigatorTitle":[{"text":"SBSDKCommonFieldType","kind":"identifier"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKFieldConsistencyVerificationReport","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldConsistencyVerificationReport\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldConsistencyVerificationReport\/fragments","value":[{"kind":"identifier","text":"SBSDKFieldConsistencyVerificationReport"}],"op":"replace"},{"value":[{"text":"SBSDKFieldConsistencyVerificationReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldConsistencyVerificationReport\/navigatorTitle"},{"value":"SBSDKValueConsistency","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/fragments","value":[{"text":"SBSDKValueConsistency","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKValueConsistency"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCommonFieldType\/title","value":"SBSDKCommonFieldType"},{"value":[{"text":"SBSDKCommonFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCommonFieldType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCommonFieldType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCommonFieldType"}],"op":"replace"}]}]}