{"kind":"symbol","metadata":{"symbolKind":"case","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateScannerState@SBSDKMedicalCertificateScannerStateSearching","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"searching","kind":"identifier"}],"title":"SBSDKMedicalCertificateScannerState.searching","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerStateSearching","kind":"identifier"}],"roleHeading":"Case"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState"]]},"abstract":[{"type":"text","text":"The medical certificate scanner is searching for medical certificates."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"searching","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/searching"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/searching"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/searching","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerState/searching":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerStateSearching"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/searching","abstract":[{"type":"text","text":"The medical certificate scanner is searching for medical certificates."}],"kind":"symbol","title":"SBSDKMedicalCertificateScannerState.searching","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/searching","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"searching","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerState":{"abstract":[{"type":"text","text":"The live scan state of the medical certificate scanner."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateScannerState"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate","title":"SBSDKMedicalCertificateScannerState","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerState"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificateScannerStateSearching"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"SBSDKMedicalCertificateScannerStateSearching","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKMedicalCertificateScannerStateSearching","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKMedicalCertificateScannerStateSearching","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState~1searching\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState~1searching\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerStateSearching"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState\/title","value":"SBSDKMedicalCertificateScannerState"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerState"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerState"}],"op":"replace"}]}]}