{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCommonConfiguration","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCommonOneDConfiguration","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCommonTwoDConfiguration","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatFourStateConfigurationBase","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatOneDConfigurationBase","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatTwoDConfigurationBase"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"abstract":[{"text":"Base class for all barcode configurations.","type":"text"}],"metadata":{"title":"SBSDKBarcodeFormatConfigurationBase","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatConfigurationBase","roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/addAdditionalQuietZone","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/minimumSizeScore","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/regexFilter"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/toJson(configuration:)"],"title":"Instance Methods","generated":true},{"anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatAustraliaPostConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatAztecConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCodabarConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode11Configuration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode128Configuration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode2Of5Configuration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode39Configuration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode93Configuration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCommonConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCommonFourStateConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCommonOneDConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCommonTwoDConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataBarConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataBarExpandedConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataBarLimitedConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataMatrixConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatGs1CompositeConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatItfConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatJapanPostConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatMaxiCodeConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatMicroPdf417Configuration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatMsiPlesseyConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatPdf417Configuration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatPharmaCodeConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatPharmaCodeTwoTrackConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatQrCodeConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatRoyalMailConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatRoyalTntPostConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatUpcEanConfiguration()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatUspsIntelligentMailConfiguration()"],"title":"Type Methods","generated":true}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKBarcodeFormatConfigurationBase) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatPharmaCodeConfiguration()":{"kind":"symbol","title":"barcodeFormatPharmaCodeConfiguration()","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatpharmacodeconfiguration()","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatPharmaCodeConfiguration()","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatPharmaCodeConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatPharmaCodeConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatPharmaCodeConfiguration"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatMicroPdf417Configuration()":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatmicropdf417configuration()","title":"barcodeFormatMicroPdf417Configuration()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatMicroPdf417Configuration"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatMicroPDF417Configuration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatMicroPDF417Configuration"}],"abstract":[],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatMicroPdf417Configuration()"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/fromJsonWithJson:":{"kind":"symbol","title":"fromJsonWithJson:","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/fromJsonWithJson:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/fromjsonwithjson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatPdf417Configuration()":{"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatPdf417Configuration()","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatpdf417configuration()","title":"barcodeFormatPdf417Configuration()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatPdf417Configuration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatPDF417Configuration","text":"SBSDKBarcodeFormatPDF417Configuration","kind":"typeIdentifier"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/minimumSizeScore":{"type":"topic","title":"minimumSizeScore","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumSizeScore","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/minimumSizeScore","role":"symbol","abstract":[{"type":"text","text":"Minimum acceptable value of a result BarcodeItem’s sizeScore (between 0 and 1)."},{"type":"text","text":" "},{"type":"text","text":"Barcodes with a sizeScore less than this value will not be scanned."},{"text":" ","type":"text"},{"text":"When set to 0, barcodes are returned no matter what their size is.","type":"text"}],"navigatorTitle":[{"text":"minimumSizeScore","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/minimumsizescore"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/hash":{"kind":"symbol","abstract":[],"title":"hash","role":"symbol","fragments":[{"text":"hash","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/hash","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/hash"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCommonFourStateConfiguration()":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcommonfourstateconfiguration()","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCommonFourStateConfiguration()","role":"symbol","type":"topic","title":"barcodeFormatCommonFourStateConfiguration()","abstract":[],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatCommonFourStateConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatCommonFourStateConfiguration"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/addAdditionalQuietZone":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/addadditionalquietzone","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/addAdditionalQuietZone","role":"symbol","navigatorTitle":[{"text":"addAdditionalQuietZone","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"If true, we process the barcode scanning with an artificial quiet zone that we add to the input image."},{"type":"text","text":" "},{"type":"text","text":"This flag should be used to scan sharp crops of a barcode in single-shot mode."}],"type":"topic","title":"addAdditionalQuietZone","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addAdditionalQuietZone","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatDataBarExpandedConfiguration()":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatDataBarExpandedConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatDataBarExpandedConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatDataBarExpandedConfiguration"}],"title":"barcodeFormatDataBarExpandedConfiguration()","type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatdatabarexpandedconfiguration()","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataBarExpandedConfiguration()","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatMsiPlesseyConfiguration()":{"abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatmsiplesseyconfiguration()","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatMsiPlesseyConfiguration()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeFormatMsiPlesseyConfiguration"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatMSIPlesseyConfiguration","kind":"typeIdentifier","text":"SBSDKBarcodeFormatMSIPlesseyConfiguration"}],"type":"topic","role":"symbol","kind":"symbol","title":"barcodeFormatMsiPlesseyConfiguration()"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatCommonTwoDConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCommonTwoDConfiguration","kind":"symbol","role":"symbol","abstract":[{"text":"Convenience configuration for enabling the scanning of multiple 2D codes with a common configuration.","type":"text"},{"text":" ","type":"text"},{"text":"Add to scanner configuration to enable and configure the scanning of multiple 2D codes.","type":"text"}],"title":"SBSDKBarcodeFormatCommonTwoDConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcommontwodconfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatCommonTwoDConfiguration","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCommonTwoDConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatRoyalMailConfiguration()":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatRoyalMailConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatRoyalMailConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatRoyalMailConfiguration","kind":"typeIdentifier"}],"title":"barcodeFormatRoyalMailConfiguration()","type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatroyalmailconfiguration()","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatRoyalMailConfiguration()","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatRoyalTntPostConfiguration()":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatRoyalTntPostConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatRoyalTNTPostConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatRoyalTNTPostConfiguration"}],"title":"barcodeFormatRoyalTntPostConfiguration()","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatroyaltntpostconfiguration()","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatRoyalTntPostConfiguration()"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCode11Configuration()":{"title":"barcodeFormatCode11Configuration()","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatCode11Configuration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatCode11Configuration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatCode11Configuration","kind":"typeIdentifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode11Configuration()","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcode11configuration()"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatAustraliaPostConfiguration()":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatAustraliaPostConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatAustraliaPostConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatAustraliaPostConfiguration"}],"title":"barcodeFormatAustraliaPostConfiguration()","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformataustraliapostconfiguration()","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatAustraliaPostConfiguration()","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatPharmaCodeTwoTrackConfiguration()":{"abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatpharmacodetwotrackconfiguration()","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatPharmaCodeTwoTrackConfiguration()","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatPharmaCodeTwoTrackConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","kind":"typeIdentifier"}],"title":"barcodeFormatPharmaCodeTwoTrackConfiguration()","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatJapanPostConfiguration()":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatJapanPostConfiguration()","role":"symbol","kind":"symbol","title":"barcodeFormatJapanPostConfiguration()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatJapanPostConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatJapanPostConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatJapanPostConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatjapanpostconfiguration()","abstract":[],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatUpcEanConfiguration()":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatUpcEanConfiguration()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatUpcEanConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatUpcEanConfiguration","text":"SBSDKBarcodeFormatUpcEanConfiguration"}],"title":"barcodeFormatUpcEanConfiguration()","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatupceanconfiguration()","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying","type":"unresolvable","title":"NSCopying"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCode39Configuration()":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode39Configuration()","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatCode39Configuration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatCode39Configuration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatCode39Configuration"}],"kind":"symbol","type":"topic","title":"barcodeFormatCode39Configuration()","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcode39configuration()"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase":{"title":"SBSDKBarcodeFormatConfigurationBase","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase","type":"topic","abstract":[{"text":"Base class for all barcode configurations.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatAztecConfiguration()":{"title":"barcodeFormatAztecConfiguration()","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatAztecConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatAztecConfiguration","text":"SBSDKBarcodeFormatAztecConfiguration","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformataztecconfiguration()","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatAztecConfiguration()","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatCommonFourStateConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration","title":"SBSDKBarcodeFormatCommonFourStateConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcommonfourstateconfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Convenience configuration for enabling the scanning of multiple four-state barcode formats with a common"},{"type":"text","text":" "},{"type":"text","text":"configuration."},{"type":"text","text":" "},{"type":"text","text":"Add to scanner configuration to enable and configure the scanning of multiple four-state codes."}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCommonOneDConfiguration()":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcommononedconfiguration()","role":"symbol","type":"topic","title":"barcodeFormatCommonOneDConfiguration()","kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCommonOneDConfiguration()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatCommonOneDConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatCommonOneDConfiguration","text":"SBSDKBarcodeFormatCommonOneDConfiguration","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/toJson(configuration:)":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/toJson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/tojson(configuration:)","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"title":"toJson(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/isEqual:":{"abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/isequal:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","type":"topic","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatCommonOneDConfiguration":{"role":"symbol","title":"SBSDKBarcodeFormatCommonOneDConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCommonOneDConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCommonOneDConfiguration","abstract":[{"text":"Convenience configuration for enabling the scanning of multiple linear (1D) barcode formats with a common","type":"text"},{"text":" ","type":"text"},{"text":"configuration.","type":"text"},{"text":" ","type":"text"},{"text":"Add to scanner configuration to enable and configure the scanning of multiple linear (1D) barcode formats.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcommononedconfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatCommonOneDConfiguration","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatMaxiCodeConfiguration()":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatMaxiCodeConfiguration()","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatmaxicodeconfiguration()","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatMaxiCodeConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatMaxiCodeConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatMaxiCodeConfiguration"}],"title":"barcodeFormatMaxiCodeConfiguration()"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCode2Of5Configuration()":{"title":"barcodeFormatCode2Of5Configuration()","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode2Of5Configuration()","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcode2of5configuration()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatCode2Of5Configuration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatCode2Of5Configuration","text":"SBSDKBarcodeFormatCode2Of5Configuration","kind":"typeIdentifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCommonTwoDConfiguration()":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcommontwodconfiguration()","type":"topic","title":"barcodeFormatCommonTwoDConfiguration()","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatCommonTwoDConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatCommonTwoDConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatCommonTwoDConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCommonTwoDConfiguration()","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatDataBarConfiguration()":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatdatabarconfiguration()","title":"barcodeFormatDataBarConfiguration()","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatDataBarConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatDataBarConfiguration","text":"SBSDKBarcodeFormatDataBarConfiguration","kind":"typeIdentifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataBarConfiguration()","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCodabarConfiguration()":{"role":"symbol","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcodabarconfiguration()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatCodabarConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatCodabarConfiguration","text":"SBSDKBarcodeFormatCodabarConfiguration","kind":"typeIdentifier"}],"type":"topic","title":"barcodeFormatCodabarConfiguration()","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCodabarConfiguration()"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatUspsIntelligentMailConfiguration()":{"abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatuspsintelligentmailconfiguration()","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatUspsIntelligentMailConfiguration()","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatUspsIntelligentMailConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatUSPSIntelligentMailConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatUSPSIntelligentMailConfiguration"}],"title":"barcodeFormatUspsIntelligentMailConfiguration()"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/copyWithZone:":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/copyWithZone:","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/copywithzone:","role":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatTwoDConfigurationBase":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformattwodconfigurationbase","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatTwoDConfigurationBase","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatTwoDConfigurationBase","kind":"identifier"}],"abstract":[{"text":"Base class for all 2D barcode configurations.","type":"text"}],"title":"SBSDKBarcodeFormatTwoDConfigurationBase","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatTwoDConfigurationBase"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/regexFilter":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/regexfilter","abstract":[{"text":"Regular expression filter for barcode text. If the barcode text does not match the regular expression, it will","type":"text"},{"text":" ","type":"text"},{"text":"not be scanned. The default is an empty string (setting is turned off).","type":"text"}],"title":"regexFilter","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/regexFilter","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"regexFilter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"regexFilter","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.3"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCommonConfiguration()":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcommonconfiguration()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatCommonConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatCommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatCommonConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCommonConfiguration()","title":"barcodeFormatCommonConfiguration()","kind":"symbol","abstract":[],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatFourStateConfigurationBase":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatFourStateConfigurationBase","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatFourStateConfigurationBase"}],"title":"SBSDKBarcodeFormatFourStateConfigurationBase","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatfourstateconfigurationbase","abstract":[{"text":"Base class for all four-state barcode configurations.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatFourStateConfigurationBase"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCode93Configuration()":{"type":"topic","role":"symbol","title":"barcodeFormatCode93Configuration()","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcode93configuration()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatCode93Configuration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatCode93Configuration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatCode93Configuration"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode93Configuration()","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatDataMatrixConfiguration()":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatDataMatrixConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatDataMatrixConfiguration","text":"SBSDKBarcodeFormatDataMatrixConfiguration"}],"role":"symbol","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatdatamatrixconfiguration()","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataMatrixConfiguration()","title":"barcodeFormatDataMatrixConfiguration()","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatGS1CompositeConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatgs1compositeconfiguration","kind":"symbol","abstract":[{"type":"text","text":"GS1 Composite configuration. Add to scanner configuration to scan GS1 Composite barcodes."}],"title":"SBSDKBarcodeFormatGS1CompositeConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCode128Configuration()":{"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode128Configuration()","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcode128configuration()","title":"barcodeFormatCode128Configuration()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatCode128Configuration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatCode128Configuration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatCode128Configuration"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatDataBarLimitedConfiguration()":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatdatabarlimitedconfiguration()","role":"symbol","title":"barcodeFormatDataBarLimitedConfiguration()","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatDataBarLimitedConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatDataBarLimitedConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatDataBarLimitedConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataBarLimitedConfiguration()"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatItfConfiguration()":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatItfConfiguration()","title":"barcodeFormatItfConfiguration()","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatitfconfiguration()","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatItfConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatITFConfiguration","text":"SBSDKBarcodeFormatITFConfiguration","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatOneDConfigurationBase":{"role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatOneDConfigurationBase","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatonedconfigurationbase","title":"SBSDKBarcodeFormatOneDConfigurationBase","abstract":[{"text":"Base class for all linear (1D) barcode configurations.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatCommonConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCommonConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcommonconfiguration","type":"topic","role":"symbol","title":"SBSDKBarcodeFormatCommonConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCommonConfiguration","kind":"identifier"}],"abstract":[{"text":"Convenience configuration for enabling the scanning of multiple barcode formats with a common configuration.","type":"text"},{"text":" ","type":"text"},{"text":"Add to scanner configuration to enable and configure the scanning of multiple barcodes.","type":"text"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatCommonConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatGs1CompositeConfiguration()":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatgs1compositeconfiguration()","kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatGs1CompositeConfiguration()","title":"barcodeFormatGs1CompositeConfiguration()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatGs1CompositeConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatGS1CompositeConfiguration"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatQrCodeConfiguration()":{"role":"symbol","abstract":[],"kind":"symbol","type":"topic","title":"barcodeFormatQrCodeConfiguration()","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatQrCodeConfiguration()","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatqrcodeconfiguration()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatQrCodeConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatQRCodeConfiguration"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKBarcodeFormatConfigurationBase","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/addAdditionalQuietZone","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/hash","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/minimumSizeScore","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/regexFilter"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/copyWithZone:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/isEqual:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/toJson(configuration:)"],"generated":true,"title":"Instance Methods"},{"anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/fromJsonWithJson:"],"generated":true,"title":"Type Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"]},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCommonConfiguration","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCommonOneDConfiguration","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCommonTwoDConfiguration","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatFourStateConfigurationBase","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatOneDConfigurationBase","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatTwoDConfigurationBase"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"minimumSizeScore","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase~1minimumSizeScore\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase~1minimumSizeScore\/fragments","value":[{"kind":"identifier","text":"minimumSizeScore"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase~1addAdditionalQuietZone\/title","value":"addAdditionalQuietZone","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase~1addAdditionalQuietZone\/fragments","value":[{"kind":"identifier","text":"addAdditionalQuietZone"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCommonTwoDConfiguration\/title","value":"SBSDKBarcodeFormatCommonTwoDConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCommonTwoDConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatCommonTwoDConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCommonTwoDConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatCommonTwoDConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase\/title","value":"SBSDKBarcodeFormatConfigurationBase","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/title","value":"SBSDKBarcodeFormatCommonFourStateConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonFourStateConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase~1toJson(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCommonOneDConfiguration\/title","value":"SBSDKBarcodeFormatCommonOneDConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCommonOneDConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatCommonOneDConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCommonOneDConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonOneDConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatTwoDConfigurationBase\/title","value":"SBSDKBarcodeFormatTwoDConfigurationBase","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatTwoDConfigurationBase\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatTwoDConfigurationBase"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatTwoDConfigurationBase\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatTwoDConfigurationBase"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase~1regexFilter\/title","value":"regexFilter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase~1regexFilter\/fragments","value":[{"kind":"identifier","text":"regexFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatFourStateConfigurationBase\/title","value":"SBSDKBarcodeFormatFourStateConfigurationBase","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatFourStateConfigurationBase\/fragments","value":[{"text":"SBSDKBarcodeFormatFourStateConfigurationBase","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatFourStateConfigurationBase\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatFourStateConfigurationBase","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/title","value":"SBSDKBarcodeFormatGS1CompositeConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/title","value":"SBSDKBarcodeFormatOneDConfigurationBase","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/fragments","value":[{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCommonConfiguration\/title","value":"SBSDKBarcodeFormatCommonConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCommonConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatCommonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCommonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonConfiguration"}],"op":"replace"}]}]}