{"sections":[],"metadata":{"title":"SBSDKUpcEanExtensionBehavior","roleHeading":"Enumeration","navigatorTitle":[{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUpcEanExtensionBehavior","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/allow2","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/allow5","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/allowAny","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/ignore","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/require2","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/require5","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/requireAny"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUpcEanExtensionBehavior) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"abstract":[{"type":"text","text":"Behavior when scanning UPC\/EAN barcodes with EAN-2 or EAN-5 extensions."}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUpcEanExtensionBehavior/ignore":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior\/ignore","navigatorTitle":[{"text":"SBSDKUpcEanExtensionBehaviorIgnore","kind":"identifier"}],"kind":"symbol","title":"SBSDKUpcEanExtensionBehavior.ignore","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Always ignore the extension."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ignore","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/ignore"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUpcEanExtensionBehavior/require2":{"type":"topic","abstract":[{"text":"Only barcodes with a 2-digit extension are accepted.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/require2","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"require2","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior\/require2","title":"SBSDKUpcEanExtensionBehavior.require2","navigatorTitle":[{"text":"SBSDKUpcEanExtensionBehaviorRequire2","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.3"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUpcEanExtensionBehavior/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/RawRepresentable-Implementations","kind":"article","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior\/rawrepresentable-implementations","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUpcEanExtensionBehavior/init(rawValue:)":{"title":"init(rawValue:)","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/init(rawValue:)","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior\/init(rawvalue:)","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUpcEanExtensionBehavior":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior","abstract":[{"type":"text","text":"Behavior when scanning UPC\/EAN barcodes with EAN-2 or EAN-5 extensions."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior","navigatorTitle":[{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"kind":"symbol","title":"SBSDKUpcEanExtensionBehavior"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUpcEanExtensionBehavior/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/Equatable-Implementations","kind":"article","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior\/equatable-implementations","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUpcEanExtensionBehavior/requireAny":{"title":"SBSDKUpcEanExtensionBehavior.requireAny","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requireAny","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUpcEanExtensionBehaviorRequireAny","kind":"identifier"}],"abstract":[{"type":"text","text":"Only barcodes with either a 2-digit or a 5-digit extension are accepted."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior\/requireany","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/requireAny"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUpcEanExtensionBehavior/allow5":{"abstract":[{"type":"text","text":"Return detected 5-digit extension if present, but do not require it. Ignore the 2-digit extension."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior\/allow5","title":"SBSDKUpcEanExtensionBehavior.allow5","type":"topic","navigatorTitle":[{"text":"SBSDKUpcEanExtensionBehaviorAllow5","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/allow5","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allow5","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUpcEanExtensionBehavior/allowAny":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKUpcEanExtensionBehaviorAllowAny","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowAny","kind":"identifier"}],"title":"SBSDKUpcEanExtensionBehavior.allowAny","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/allowAny","abstract":[{"type":"text","text":"Return any detected extension if present, but do not require it."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior\/allowany","type":"topic","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUpcEanExtensionBehavior/allow2":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/allow2","abstract":[{"type":"text","text":"Return detected 2-digit extension if present, but do not require it. Ignore the 5-digit extension."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior\/allow2","navigatorTitle":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehaviorAllow2"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"allow2"}],"kind":"symbol","title":"SBSDKUpcEanExtensionBehavior.allow2"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUpcEanExtensionBehavior/require5":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/require5","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior\/require5","kind":"symbol","navigatorTitle":[{"text":"SBSDKUpcEanExtensionBehaviorRequire5","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"require5","kind":"identifier"}],"title":"SBSDKUpcEanExtensionBehavior.require5","abstract":[{"type":"text","text":"Only barcodes with a 5-digit extension are accepted."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKUpcEanExtensionBehavior","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/allow2","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/allow5","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/allowAny","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/ignore","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/require2","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/require5","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/requireAny"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1ignore\/title","value":"SBSDKUpcEanExtensionBehaviorIgnore","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1ignore\/fragments","value":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehaviorIgnore"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1require2\/title","value":"SBSDKUpcEanExtensionBehaviorRequire2","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1require2\/fragments","value":[{"text":"SBSDKUpcEanExtensionBehaviorRequire2","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior\/title","value":"SBSDKUpcEanExtensionBehavior","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior\/fragments","value":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1requireAny\/title","value":"SBSDKUpcEanExtensionBehaviorRequireAny","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1requireAny\/fragments","value":[{"text":"SBSDKUpcEanExtensionBehaviorRequireAny","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1allow5\/title","value":"SBSDKUpcEanExtensionBehaviorAllow5","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1allow5\/fragments","value":[{"text":"SBSDKUpcEanExtensionBehaviorAllow5","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1allowAny\/title","value":"SBSDKUpcEanExtensionBehaviorAllowAny","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1allowAny\/fragments","value":[{"text":"SBSDKUpcEanExtensionBehaviorAllowAny","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1allow2\/title","value":"SBSDKUpcEanExtensionBehaviorAllow2","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1allow2\/fragments","value":[{"text":"SBSDKUpcEanExtensionBehaviorAllow2","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1require5\/title","value":"SBSDKUpcEanExtensionBehaviorRequire5","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1require5\/fragments","value":[{"text":"SBSDKUpcEanExtensionBehaviorRequire5","kind":"identifier"}],"op":"replace"}]}]}