{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/IDCardRecognition","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/idcardrecognition"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/idcardrecognition"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","abstract":[{"text":"ID card and passport recognition is enabled in the licence.","type":"text"}],"metadata":{"title":"SBSDKFeature.IDCardRecognition","roleHeading":"Case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKFeature@SBSDKFeatureIDCardRecognition","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDCardRecognition","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKFeatureIDCardRecognition","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"IDCardRecognition","kind":"identifier"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 6.2.0"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature":{"role":"symbol","type":"topic","kind":"symbol","title":"SBSDKFeature","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeature"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFeature","kind":"identifier"}],"abstract":[{"type":"text","text":"The features that are activated in the ScanbotSDK license."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/IDCardRecognition":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/idcardrecognition","role":"symbol","abstract":[{"type":"text","text":"ID card and passport recognition is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/IDCardRecognition","title":"SBSDKFeature.IDCardRecognition","kind":"symbol","navigatorTitle":[{"text":"SBSDKFeatureIDCardRecognition","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"IDCardRecognition","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKFeatureIDCardRecognition"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKFeatureIDCardRecognition"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKFeatureIDCardRecognition"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/title","value":"SBSDKFeature"},{"value":[{"kind":"identifier","text":"SBSDKFeature"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/navigatorTitle","value":[{"text":"SBSDKFeature","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1IDCardRecognition\/title","op":"replace","value":"SBSDKFeatureIDCardRecognition"},{"value":[{"kind":"identifier","text":"SBSDKFeatureIDCardRecognition"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1IDCardRecognition\/fragments","op":"replace"}]}]}