{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelButtonTitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"title":"cancelButtonTitle","roleHeading":"Instance Property","platforms":[],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerTextConfiguration(py)cancelButtonTitle","navigatorTitle":[{"text":"cancelButtonTitle","kind":"identifier"}]},"abstract":[{"text":"String being displayed on the cancel button.","type":"text"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2DocumentScannerViewController instead."}],"type":"paragraph"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerTextConfiguration\/cancelButtonTitle"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannertextconfiguration\/cancelbuttontitle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannertextconfiguration\/cancelbuttontitle"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerTextConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerTextConfiguration/cancelButtonTitle":{"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannertextconfiguration\/cancelbuttontitle","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"cancelButtonTitle","kind":"identifier"}],"deprecated":true,"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerTextConfiguration\/cancelButtonTitle","title":"cancelButtonTitle","abstract":[{"type":"text","text":"String being displayed on the cancel button."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerTextConfiguration":{"abstract":[{"type":"text","text":"Configuration for the textual contents of the document scanning screen."}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannertextconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerTextConfiguration","role":"symbol","deprecated":true,"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerTextConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerTextConfiguration"}],"title":"SBSDKUIDocumentScannerTextConfiguration"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"cancelButtonTitle","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"cancelButtonTitle","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cancelButtonTitle"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerTextConfiguration~1cancelButtonTitle\/title","value":"cancelButtonTitle","op":"replace"},{"value":[{"text":"cancelButtonTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerTextConfiguration~1cancelButtonTitle\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerTextConfiguration\/title","value":"SBSDKUIDocumentScannerTextConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerTextConfiguration\/fragments","value":[{"text":"SBSDKUIDocumentScannerTextConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerTextConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIDocumentScannerTextConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}