{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration\/init","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","symbolKind":"method","title":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerConfiguration(im)init","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerConfiguration/init":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerconfiguration\/init","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"abstract":[],"title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScanner":{"title":"SBSDKVehicleIdentificationNumberScanner","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScanner"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScanner"}],"abstract":[{"text":"A class to scan video frames or still images for vehicle identification numbers and validate it.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscanner","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerconfiguration","type":"topic","title":"SBSDKVehicleIdentificationNumberScannerConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScannerConfiguration"}],"abstract":[{"text":"A descriptor-like class to configure ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner\/title","value":"SBSDKVehicleIdentificationNumberScanner"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner\/fragments","value":[{"text":"SBSDKVehicleIdentificationNumberScanner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration\/title","value":"SBSDKVehicleIdentificationNumberScannerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration\/fragments","value":[{"text":"SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}