{"abstract":[{"type":"text","text":"The maximum number of accumulated video frames before the current scanning result is returned."}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerConfiguration(py)maximumNumberOfAccumulatedFrames","roleHeading":"Instance Property","title":"maximumNumberOfAccumulatedFrames","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Defaults to 3."}],"type":"paragraph"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration\/maximumNumberOfAccumulatedFrames","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerconfiguration\/maximumnumberofaccumulatedframes"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerconfiguration\/maximumnumberofaccumulatedframes"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerConfiguration/maximumNumberOfAccumulatedFrames":{"navigatorTitle":[{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration\/maximumNumberOfAccumulatedFrames","abstract":[{"text":"The maximum number of accumulated video frames before the current scanning result is returned.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerconfiguration\/maximumnumberofaccumulatedframes","title":"maximumNumberOfAccumulatedFrames","role":"symbol","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration","title":"SBSDKVehicleIdentificationNumberScannerConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerconfiguration","abstract":[{"text":"A descriptor-like class to configure ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScannerConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScanner":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner","title":"SBSDKVehicleIdentificationNumberScanner","url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscanner","abstract":[{"type":"text","text":"A class to scan video frames or still images for vehicle identification numbers and validate it."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKVehicleIdentificationNumberScanner","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVehicleIdentificationNumberScanner","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"maximumNumberOfAccumulatedFrames","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration~1maximumNumberOfAccumulatedFrames\/title","value":"maximumNumberOfAccumulatedFrames","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration~1maximumNumberOfAccumulatedFrames\/fragments","value":[{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"}],"op":"replace"},{"value":"SBSDKVehicleIdentificationNumberScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration\/title"},{"value":[{"text":"SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration\/fragments"},{"op":"replace","value":"SBSDKVehicleIdentificationNumberScanner","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner\/title"},{"value":[{"text":"SBSDKVehicleIdentificationNumberScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner\/fragments","op":"replace"}]}]}