{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ocrResolutionLimit","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"inlineContent":[{"text":"If the initial image has longer side - it will be downscaled to the limit.","type":"text"},{"type":"text","text":" "},{"text":"Setting to 0 means no limit.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Using this parameter might be useful for slower devices or to reduce processing load."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Defaults to 0."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerconfiguration\/ocrresolutionlimit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerconfiguration\/ocrresolutionlimit"]}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerConfiguration(py)ocrResolutionLimit","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"ocrResolutionLimit","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ocrResolutionLimit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"ocrResolutionLimit"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration"]]},"kind":"symbol","abstract":[{"text":"The maximum image side length (height or width) for OCR processing.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration\/ocrResolutionLimit"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScanner":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScanner"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner","type":"topic","abstract":[{"type":"text","text":"A class to scan video frames or still images for vehicle identification numbers and validate it."}],"url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscanner","navigatorTitle":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScanner"}],"role":"symbol","title":"SBSDKVehicleIdentificationNumberScanner"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerConfiguration/ocrResolutionLimit":{"navigatorTitle":[{"text":"ocrResolutionLimit","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The maximum image side length (height or width) for OCR processing.","type":"text"}],"title":"ocrResolutionLimit","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration\/ocrResolutionLimit","url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerconfiguration\/ocrresolutionlimit","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ocrResolutionLimit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerConfiguration":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScannerConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerconfiguration","navigatorTitle":[{"text":"SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"identifier"}],"title":"SBSDKVehicleIdentificationNumberScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration","type":"topic","abstract":[{"text":"A descriptor-like class to configure ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner"},{"type":"text","text":"."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"ocrResolutionLimit","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ocrResolutionLimit","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"ocrResolutionLimit"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKVehicleIdentificationNumberScanner","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScanner"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScanner"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration~1ocrResolutionLimit\/title","value":"ocrResolutionLimit"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration~1ocrResolutionLimit\/fragments","op":"replace","value":[{"text":"ocrResolutionLimit","kind":"identifier"}]},{"value":"SBSDKVehicleIdentificationNumberScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration\/fragments","value":[{"text":"SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScannerConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}