{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(scanFromImage:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"text":"image","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","kind":"typeIdentifier","text":"SBSDKTextPatternScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image to be scanned."}]}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The result of the scan."}],"type":"paragraph"}]}],"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScanner(im)scanFromImage:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","kind":"typeIdentifier","text":"SBSDKTextPatternScannerResult"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"scanFromImage:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"title":"scan(from:)","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Scans text information on the given ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScanner"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScanner\/scan(from:)-7ouih"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscanner\/scan(from:)-7ouih"]},{"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscanner\/scan(from:)-7ouih"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScanner/scan(from:)-7ouih":{"abstract":[{"type":"text","text":"Scans text information on the given "},{"code":"UIImage","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScanner\/scan(from:)-7ouih","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":") -> ","kind":"text"},{"text":"SBSDKTextPatternScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"scanFromImage:"}],"kind":"symbol","title":"scan(from:)","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscanner\/scan(from:)-7ouih","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerResult":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerResult"}],"kind":"symbol","title":"SBSDKTextPatternScannerResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"type":"topic","abstract":[{"text":"The result of the text line recognition.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScanner":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscanner","role":"symbol","abstract":[{"type":"text","text":"A class to scan one line of text on various image sources in a small area and run a validation on the result."},{"text":" ","type":"text"},{"text":"The validation is configurable and ranges from string pattern validation, preset based validation (e.g. vehicle identification numbers) to custom validation using functions.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScanner"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScanner","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTextPatternScanner"}],"kind":"symbol","title":"SBSDKTextPatternScanner"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"scanFromImage:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"scanFromImage:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","kind":"typeIdentifier","text":"SBSDKTextPatternScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult"},{"text":" *) ","kind":"text"},{"text":"scanFromImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"image","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"The image to be scanned.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the scan."}]}]},"path":"\/primaryContentSections\/2","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner~1scan(from:)-7ouih\/title","value":"scanFromImage:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"scanFromImage:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner~1scan(from:)-7ouih\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/title","value":"SBSDKTextPatternScannerResult","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/fragments","value":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/navigatorTitle","value":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}]},{"value":"SBSDKTextPatternScanner","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner\/fragments","value":[{"kind":"identifier","text":"SBSDKTextPatternScanner"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner\/navigatorTitle","value":[{"text":"SBSDKTextPatternScanner","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}