{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscanneruiconfiguration\/topbarbuttonscolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscanneruiconfiguration\/topbarbuttonscolor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerUIConfiguration\/topBarButtonsColor","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerUIConfiguration(py)topBarButtonsColor","title":"topBarButtonsColor","roleHeading":"Instance Property","navigatorTitle":[{"text":"topBarButtonsColor","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"topBarButtonsColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"type":"text","text":"Foreground color of the cancel button and when flash button is on."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"topBarButtonsColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerUIConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerUIConfiguration/topBarButtonsColor":{"abstract":[{"type":"text","text":"Foreground color of the cancel button and when flash button is on."}],"title":"topBarButtonsColor","navigatorTitle":[{"text":"topBarButtonsColor","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerUIConfiguration\/topBarButtonsColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topBarButtonsColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscanneruiconfiguration\/topbarbuttonscolor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerUIConfiguration":{"navigatorTitle":[{"text":"SBSDKUICheckScannerUIConfiguration","kind":"identifier"}],"title":"SBSDKUICheckScannerUIConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICheckScannerUIConfiguration"}],"role":"symbol","abstract":[{"type":"text","text":"Configuration for the user interface of the RTU-UI check scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerUIConfiguration","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscanneruiconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"topBarButtonsColor","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"topBarButtonsColor","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"topBarButtonsColor"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration~1topBarButtonsColor\/title","value":"topBarButtonsColor"},{"value":[{"kind":"identifier","text":"topBarButtonsColor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration~1topBarButtonsColor\/fragments","op":"replace"},{"value":"SBSDKUICheckScannerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUICheckScannerUIConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUICheckScannerUIConfiguration"}],"op":"replace"}]}]}