{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingresult\/fromjsonwithjson:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingResult"]]},"metadata":{"roleHeading":"Type Method","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingResult(cm)fromJsonWithJson:","modules":[{"name":"ScanbotSDK"}],"title":"fromJsonWithJson:","role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingResult\/fromJsonWithJson:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2CroppingResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingResult"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingResult/fromJsonWithJson:":{"type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingresult\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingResult\/fromJsonWithJson:","title":"fromJsonWithJson:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingResult":{"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingresult","abstract":[{"type":"text","text":"Configuration of the cropping result."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CroppingResult"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingResult"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingResult","title":"SBSDKUI2CroppingResult"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingResult\/title","op":"replace","value":"SBSDKUI2CroppingResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingResult\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CroppingResult"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingResult\/navigatorTitle","value":[{"text":"SBSDKUI2CroppingResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}