{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate\/mrzScannerControllerShouldDetectMRZ(_:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzScannerControllerShouldDetectMRZ","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController","text":"SBSDKMRZScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"text":"The calling ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","type":"reference"},{"text":".","type":"text"}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"text":"Return ","type":"text"},{"type":"codeVoice","code":"True"},{"text":" if you want to detect machine-readable zones on the next video frame, ","type":"text"},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate\/mrzscannercontrollershoulddetectmrz(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate\/mrzscannercontrollershoulddetectmrz(_:)"]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"mrzScannerControllerShouldDetectMRZ:","kind":"identifier"}],"required":true,"title":"mrzScannerControllerShouldDetectMRZ(_:)","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKMRZScannerViewControllerDelegate(im)mrzScannerControllerShouldDetectMRZ:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzScannerControllerShouldDetectMRZ","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController","text":"SBSDKMRZScannerViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate"]]},"kind":"symbol","abstract":[{"text":"Asks the delegate if the scanner should detect machine-readable zones on the next video frame.","type":"text"},{"text":" ","type":"text"},{"text":"Optional.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewControllerDelegate":{"abstract":[{"type":"text","text":"The delegation protocol for the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","type":"reference","isActive":true},{"type":"text","text":" class."}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate","title":"SBSDKMRZScannerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZScannerViewControllerDelegate"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScannerViewControllerDelegate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller","title":"SBSDKMRZScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan machine-readable zones."}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewControllerDelegate/mrzScannerControllerShouldDetectMRZ(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate\/mrzscannercontrollershoulddetectmrz(_:)","navigatorTitle":[{"text":"mrzScannerControllerShouldDetectMRZ:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate\/mrzScannerControllerShouldDetectMRZ(_:)","type":"topic","required":true,"abstract":[{"text":"Asks the delegate if the scanner should detect machine-readable zones on the next video frame.","type":"text"},{"text":" ","type":"text"},{"text":"Optional.","type":"text"}],"kind":"symbol","role":"symbol","title":"mrzScannerControllerShouldDetectMRZ(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzScannerControllerShouldDetectMRZ","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMRZScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"mrzScannerControllerShouldDetectMRZ:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mrzScannerControllerShouldDetectMRZ:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"mrzScannerControllerShouldDetectMRZ:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMRZScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The calling "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}]}],"name":"controller"}],"kind":"parameters"},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Return "},{"type":"codeVoice","code":"True"},{"type":"text","text":" if you want to detect machine-readable zones on the next video frame, "},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise."}]}],"kind":"content"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/title","value":"SBSDKMRZScannerViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/fragments","value":[{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/title","value":"SBSDKMRZScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/fragments","value":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/navigatorTitle","value":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate~1mrzScannerControllerShouldDetectMRZ(_:)\/title","value":"mrzScannerControllerShouldDetectMRZ:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate~1mrzScannerControllerShouldDetectMRZ(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mrzScannerControllerShouldDetectMRZ:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}