{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMRZ\/officeOfIssuance","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"officeOfIssuance"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"metadata":{"navigatorTitle":[{"text":"officeOfIssuance","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"officeOfIssuance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"title":"officeOfIssuance","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMRZ(py)officeOfIssuance","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","role":"symbol"},"abstract":[{"type":"text","text":"Office of issuance"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmrz\/officeofissuance"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmrz\/officeofissuance"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMRZ"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelMRZ/officeOfIssuance":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMRZ\/officeOfIssuance","abstract":[{"text":"Office of issuance","type":"text"}],"kind":"symbol","title":"officeOfIssuance","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"officeOfIssuance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"officeOfIssuance","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmrz\/officeofissuance"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelMRZ":{"role":"symbol","abstract":[{"text":"MRZ part of the document","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMRZ","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelMRZ","kind":"identifier"}],"title":"SBSDKDocumentsModelMRZ","navigatorTitle":[{"text":"SBSDKDocumentsModelMRZ","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmrz"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"role":"symbol","title":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","abstract":[{"type":"text","text":"Generic document field."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"officeOfIssuance"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"officeOfIssuance"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":" * ","kind":"text"},{"text":"officeOfIssuance","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMRZ~1officeOfIssuance\/title","value":"officeOfIssuance"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMRZ~1officeOfIssuance\/fragments","value":[{"kind":"identifier","text":"officeOfIssuance"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMRZ\/title","value":"SBSDKDocumentsModelMRZ"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMRZ\/fragments","value":[{"text":"SBSDKDocumentsModelMRZ","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMRZ\/navigatorTitle","value":[{"text":"SBSDKDocumentsModelMRZ","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title","value":"SBSDKGenericDocumentField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]}]}]}