{"metadata":{"role":"symbol","navigatorTitle":[{"text":"imageEditingViewControllerDidFail:with:","kind":"identifier"}],"externalID":"c:@CM@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingViewController(im)imageEditingViewControllerDidFail:with:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageEditingViewControllerDidFail","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageEditingViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","extendedModule":"ScanbotDocumentScannerSDK","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"imageEditingViewControllerDidFail(_:with:)","symbolKind":"method"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerDidFail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"editingViewController"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","kind":"typeIdentifier","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"editingViewController","content":[{"inlineContent":[{"text":"The calling ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"The occurred error."}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller\/imageeditingviewcontrollerdidfail(_:with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller\/imageeditingviewcontrollerdidfail(_:with:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/SBSDKImageEditingViewControllerDelegate-Implementations"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/imageEditingViewControllerDidFail(_:with:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Informs the delegate that the image editing view controller failed with an error."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingViewController/imageEditingViewControllerDidFail(_:with:)":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/imageEditingViewControllerDidFail(_:with:)","abstract":[{"type":"text","text":"Informs the delegate that the image editing view controller failed with an error."}],"role":"symbol","navigatorTitle":[{"text":"imageEditingViewControllerDidFail:with:","kind":"identifier"}],"title":"imageEditingViewControllerDidFail(_:with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageEditingViewControllerDidFail","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller\/imageeditingviewcontrollerdidfail(_:with:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingViewController":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController","title":"SBSDKUI2CroppingViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller","abstract":[{"text":"A highly customizable view controller to edit the page polygon or the page orientation.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingViewController"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingViewController/SBSDKImageEditingViewControllerDelegate-Implementations":{"kind":"article","abstract":[],"title":"SBSDKImageEditingViewControllerDelegate Implementations","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/SBSDKImageEditingViewControllerDelegate-Implementations","role":"collectionGroup","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller\/sbsdkimageeditingviewcontrollerdelegate-implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewController":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontroller","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","role":"symbol","type":"topic","title":"SBSDKImageEditingViewController","abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to show and edit an image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewController"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"imageEditingViewControllerDidFail:with:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageEditingViewControllerDidFail:with:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"imageEditingViewControllerDidFail:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"editingViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"with:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"imageEditingViewControllerDidFail:with:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController~1imageEditingViewControllerDidFail(_:with:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerDidFail:with:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController~1imageEditingViewControllerDidFail(_:with:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/title","value":"SBSDKUI2CroppingViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/fragments","value":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/navigatorTitle","value":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/title","op":"replace","value":"SBSDKImageEditingViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}