{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Timeouts\/toJson(configuration:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKToJSONConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKToJSONConfiguration()) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Timeouts(im)toJsonWithConfiguration:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"toJson(configuration:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"symbolKind":"method","role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Timeouts"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2timeouts\/tojson(configuration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2timeouts\/tojson(configuration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Timeouts/toJson(configuration:)":{"navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"role":"symbol","title":"toJson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2timeouts\/tojson(configuration:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Timeouts\/toJson(configuration:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKToJSONConfiguration":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktojsonconfiguration","type":"topic","navigatorTitle":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration used to serialize an object to json."}],"title":"SBSDKToJSONConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKToJSONConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKToJSONConfiguration"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Timeouts":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2Timeouts","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Configuration of timeouts.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Timeouts","title":"SBSDKUI2Timeouts","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2Timeouts","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2timeouts"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"toJsonWithConfiguration:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"toJsonWithConfiguration:"},{"kind":"text","text":"("},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKToJSONConfiguration"},{"kind":"text","text":" *) "},{"text":"configuration","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Timeouts~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Timeouts~1toJson(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"op":"replace"},{"op":"replace","value":"SBSDKToJSONConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKToJSONConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKToJSONConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKToJSONConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKToJSONConfiguration\/navigatorTitle","value":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKUI2Timeouts","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Timeouts\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Timeouts\/fragments","value":[{"text":"SBSDKUI2Timeouts","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2Timeouts","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Timeouts\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}