{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcontentvalidator\/defaultcontentvalidator()"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultContentValidator","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDefaultContentValidator","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDefaultContentValidator","text":"SBSDKDefaultContentValidator","kind":"typeIdentifier"}],"languages":["swift"]}]}],"metadata":{"title":"defaultContentValidator()","symbolKind":"method","roleHeading":"Type Method","role":"symbol","externalID":"s:10ScanbotSDK21SBSDKContentValidatorC014defaultContentD0AA012SBSDKDefaultfD0CyFZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultContentValidator","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKDefaultContentValidator","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDefaultContentValidator","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/defaultContentValidator()"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator/defaultContentValidator()":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/defaultContentValidator()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultContentValidator"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDefaultContentValidator","kind":"typeIdentifier","text":"SBSDKDefaultContentValidator"}],"role":"symbol","type":"topic","title":"defaultContentValidator()","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator\/defaultcontentvalidator()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKContentValidator"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKContentValidator"}],"title":"SBSDKContentValidator","abstract":[{"type":"text","text":"Base class for content validators."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDefaultContentValidator":{"kind":"symbol","title":"SBSDKDefaultContentValidator","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Default content validator. Accepts only non-empty strings."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDefaultContentValidator"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDefaultContentValidator","url":"\/documentation\/scanbotsdk\/sbsdkdefaultcontentvalidator","navigatorTitle":[{"kind":"identifier","text":"SBSDKDefaultContentValidator"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKContentValidator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKContentValidator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKContentValidator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/navigatorTitle"},{"op":"replace","value":"SBSDKDefaultContentValidator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDefaultContentValidator\/title"},{"op":"replace","value":[{"text":"SBSDKDefaultContentValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDefaultContentValidator\/fragments"},{"op":"replace","value":[{"text":"SBSDKDefaultContentValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDefaultContentValidator\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}