{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerascreenconfiguration\/cameraconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerascreenconfiguration\/cameraconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CameraScreenConfiguration(py)cameraConfiguration","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration","text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"cameraConfiguration","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","title":"cameraConfiguration","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraScreenConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraScreenConfiguration\/cameraConfiguration","interfaceLanguage":"swift"},"abstract":[{"text":"Configuration of the camera behavior.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerCameraConfiguration","text":"SBSDKUI2DocumentScannerCameraConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraScreenConfiguration":{"title":"SBSDKUI2CameraScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraScreenConfiguration","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerascreenconfiguration","abstract":[{"type":"text","text":"Configuration of the screen for scanning the pages with the camera."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraScreenConfiguration/cameraConfiguration":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration","kind":"typeIdentifier","text":"SBSDKUI2DocumentScannerCameraConfiguration"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerascreenconfiguration\/cameraconfiguration","abstract":[{"text":"Configuration of the camera behavior.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cameraConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraScreenConfiguration\/cameraConfiguration","title":"cameraConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerCameraConfiguration":{"title":"SBSDKUI2DocumentScannerCameraConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercameraconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerCameraConfiguration"}],"navigatorTitle":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the camera behavior."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerCameraConfiguration","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"cameraConfiguration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"cameraConfiguration"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration","kind":"typeIdentifier","text":"SBSDKUI2DocumentScannerCameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerCameraConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cameraConfiguration"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraScreenConfiguration\/title","op":"replace","value":"SBSDKUI2CameraScreenConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraScreenConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraScreenConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraScreenConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraScreenConfiguration~1cameraConfiguration\/title","op":"replace","value":"cameraConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraScreenConfiguration~1cameraConfiguration\/fragments","op":"replace","value":[{"text":"cameraConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/title","op":"replace","value":"SBSDKUI2DocumentScannerCameraConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerCameraConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerCameraConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}