{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2nointroimage\/fromjsonwithjson:"]}],"metadata":{"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"roleHeading":"Type Method","title":"fromJsonWithJson:","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2NoIntroImage(cm)fromJsonWithJson:","role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoIntroImage\/fromJsonWithJson:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoIntroImage"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2NoIntroImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2NoIntroImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoIntroImage"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2NoIntroImage":{"role":"symbol","kind":"symbol","title":"SBSDKUI2NoIntroImage","url":"\/documentation\/scanbotsdk\/sbsdkui2nointroimage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2NoIntroImage","kind":"identifier"}],"abstract":[{"text":"No image for the introduction screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoIntroImage","navigatorTitle":[{"text":"SBSDKUI2NoIntroImage","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2NoIntroImage/fromJsonWithJson:":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2nointroimage\/fromjsonwithjson:","title":"fromJsonWithJson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoIntroImage\/fromJsonWithJson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2NoIntroImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoIntroImage\/title"},{"value":[{"text":"SBSDKUI2NoIntroImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoIntroImage\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2NoIntroImage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoIntroImage\/navigatorTitle"}]}]}