{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"flashButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2RoundButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2RoundButton","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2RoundButton"},{"text":" = SBSDKUI2RoundButton(visible: true,\n                                                                       backgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                      isArgb: false),\n                                                                       foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                      isArgb: false),\n                                                                       activeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorWarning\",\n                                                                                                            isArgb: false),\n                                                                       activeForegroundColor: SBSDKUI2Color(colorString: \"#1C1B1F\",\n                                                                                                            isArgb: false)), ","kind":"text"},{"text":"zoomButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2RoundButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2RoundButton","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2RoundButton"},{"text":" = SBSDKUI2RoundButton(visible: true,\n                                                                      backgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                     isArgb: false),\n                                                                      foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                     isArgb: false),\n                                                                      activeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                           isArgb: false),\n                                                                      activeForegroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                           isArgb: false)), ","kind":"text"},{"text":"flipCameraButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2RoundButton"},{"text":" = SBSDKUI2RoundButton(visible: true,\n                                                                            backgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                           isArgb: false),\n                                                                            foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                           isArgb: false),\n                                                                            activeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                 isArgb: false),\n                                                                            activeForegroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                 isArgb: false)))","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"initWithFlashButton:zoomButton:flipCameraButton:","kind":"identifier"}],"roleHeading":"Initializer","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ActionBarConfiguration(im)initWithFlashButton:zoomButton:flipCameraButton:","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"flashButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoomButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton"},{"kind":"text","text":", "},{"kind":"externalParam","text":"flipCameraButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton"},{"kind":"text","text":")"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"init(flashButton:zoomButton:flipCameraButton:)","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ActionBarConfiguration\/init(flashButton:zoomButton:flipCameraButton:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ActionBarConfiguration"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2actionbarconfiguration\/init(flashbutton:zoombutton:flipcamerabutton:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2actionbarconfiguration\/init(flashbutton:zoombutton:flipcamerabutton:)"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ActionBarConfiguration":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ActionBarConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2actionbarconfiguration","title":"SBSDKUI2ActionBarConfiguration","abstract":[{"type":"text","text":"Configuration of the buttons available in the action bar."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ActionBarConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2ActionBarConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2RoundButton":{"title":"SBSDKUI2RoundButton","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2roundbutton","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2RoundButton","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the round button."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2RoundButton","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2RoundButton","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ActionBarConfiguration/init(flashButton:zoomButton:flipCameraButton:)":{"abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2actionbarconfiguration\/init(flashbutton:zoombutton:flipcamerabutton:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"flashButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoomButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton"},{"kind":"text","text":", "},{"kind":"externalParam","text":"flipCameraButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithFlashButton:zoomButton:flipCameraButton:","kind":"identifier"}],"title":"init(flashButton:zoomButton:flipCameraButton:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ActionBarConfiguration\/init(flashButton:zoomButton:flipCameraButton:)","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithFlashButton:zoomButton:flipCameraButton:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFlashButton:zoomButton:flipCameraButton:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithFlashButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"flashButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"zoomButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zoomButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"flipCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"flipCameraButton","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2ActionBarConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ActionBarConfiguration\/title"},{"value":[{"text":"SBSDKUI2ActionBarConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ActionBarConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ActionBarConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ActionBarConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2RoundButton\/title","value":"SBSDKUI2RoundButton"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2RoundButton\/fragments","value":[{"text":"SBSDKUI2RoundButton","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2RoundButton\/navigatorTitle","value":[{"text":"SBSDKUI2RoundButton","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ActionBarConfiguration~1init(flashButton:zoomButton:flipCameraButton:)\/title","value":"initWithFlashButton:zoomButton:flipCameraButton:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ActionBarConfiguration~1init(flashButton:zoomButton:flipCameraButton:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFlashButton:zoomButton:flipCameraButton:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}