{"metadata":{"extendedModule":"ScanbotSDK","title":"checkRecognizerViewController(_:didChangeState:)","navigatorTitle":[{"text":"checkRecognizerViewController:didChangeState:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCheckRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController"},{"text":", ","kind":"text"},{"text":"didChangeState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCheckRecognizerState","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckRecognizerState"},{"text":")","kind":"text"}],"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerViewController(im)checkRecognizerViewController:didChangeState:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/SBSDKCheckRecognizerViewControllerDelegate-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/checkRecognizerViewController(_:didChangeState:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller\/checkrecognizerviewcontroller(_:didchangestate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller\/checkrecognizerviewcontroller(_:didchangestate:)"]}],"abstract":[{"text":"Informs the delegate, that the check scanner has changed its detection\/recognition state. Optional.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkRecognizerViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCheckRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeState"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCheckRecognizerState","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckRecognizerState","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The check scanner viewController that changed its state."}]}],"name":"controller"},{"content":[{"inlineContent":[{"text":"The current state of the check scanner.","type":"text"}],"type":"paragraph"}],"name":"state"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerState":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate","abstract":[{"text":"The live recognition state of the check scanner.","type":"text"}],"title":"SBSDKCheckRecognizerState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckRecognizerState","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCheckRecognizerState","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewController/SBSDKCheckRecognizerViewControllerDelegate-Implementations":{"title":"SBSDKCheckRecognizerViewControllerDelegate Implementations","type":"topic","abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/SBSDKCheckRecognizerViewControllerDelegate-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller\/sbsdkcheckrecognizerviewcontrollerdelegate-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Classic UI view controller that can be used to detect and recognize bank checks."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}],"title":"SBSDKCheckRecognizerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewController/checkRecognizerViewController(_:didChangeState:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkRecognizerViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController","text":"SBSDKCheckRecognizerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckRecognizerState","text":"SBSDKCheckRecognizerState"},{"kind":"text","text":")"}],"kind":"symbol","title":"checkRecognizerViewController(_:didChangeState:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/checkRecognizerViewController(_:didChangeState:)","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller\/checkrecognizerviewcontroller(_:didchangestate:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"checkRecognizerViewController:didChangeState:"}],"abstract":[{"type":"text","text":"Informs the delegate, that the check scanner has changed its detection\/recognition state. Optional."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewController":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller","title":"SBSDKUICheckRecognizerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController","role":"symbol","navigatorTitle":[{"text":"SBSDKUICheckRecognizerViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckRecognizerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A Ready-To-Use viewController to recognize checks using the camera."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"checkRecognizerViewController:didChangeState:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"checkRecognizerViewController:didChangeState:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"checkRecognizerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController","text":"SBSDKCheckRecognizerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didChangeState:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckRecognizerState","text":"SBSDKCheckRecognizerState","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"state","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState\/title","value":"SBSDKCheckRecognizerState","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckRecognizerState"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCheckRecognizerState"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/title","value":"SBSDKCheckRecognizerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/fragments","value":[{"text":"SBSDKCheckRecognizerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController~1checkRecognizerViewController(_:didChangeState:)\/title","value":"checkRecognizerViewController:didChangeState:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController~1checkRecognizerViewController(_:didChangeState:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"checkRecognizerViewController:didChangeState:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController\/title","value":"SBSDKUICheckRecognizerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController\/fragments","value":[{"text":"SBSDKUICheckRecognizerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUICheckRecognizerViewController"}],"op":"replace"}]}]}