{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/!=(_:_:)"],"anchor":"Operators","title":"Operators","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/equatable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode"]]},"kind":"article","metadata":{"role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"ScanbotSDK"}],"title":"Equatable Implementations"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognitionMode"}],"abstract":[{"type":"text","text":"An enum describing the modes of the optical character recognition."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOpticalCharacterRecognitionMode"}],"title":"SBSDKOpticalCharacterRecognitionMode","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode/!=(_:_:)":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/!=(_:_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/!=(_:_:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"!=(_:_:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKOpticalCharacterRecognitionMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode\/title","op":"replace"},{"value":[{"text":"SBSDKOpticalCharacterRecognitionMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognitionMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode\/navigatorTitle","op":"replace"}]}]}