{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityValue"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"valueDescription","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Text","preciseIdentifier":"s:7SwiftUI4TextV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"text":"ModifiedContent","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI15ModifiedContentV"},{"text":"<","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","text":"AccessibilityAttachmentModifier","kind":"typeIdentifier"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView\/View-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.accessibilityValue(_:isEnabled:)"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityValue"},{"kind":"text","text":"("},{"preciseIdentifier":"s:7SwiftUI4TextV","kind":"typeIdentifier","text":"Text"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI15ModifiedContentV","text":"ModifiedContent"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"AccessibilityAttachmentModifier","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV"},{"kind":"text","text":">"}],"modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}],"title":"accessibilityValue(_:isEnabled:)","extendedModule":"SwiftUICore","platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"18.0","beta":false,"name":"iOS"},{"deprecated":false,"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"18.0"},{"deprecated":false,"unavailable":false,"introducedAt":"18.0","name":"Mac Catalyst","beta":false},{"introducedAt":"15.0","name":"macOS","unavailable":false,"beta":false,"deprecated":false},{"deprecated":false,"introducedAt":"18.0","unavailable":false,"name":"tvOS","beta":false},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"2.0"},{"introducedAt":"11.0","unavailable":false,"beta":false,"deprecated":false,"name":"watchOS"}],"symbolKind":"method","externalID":"s:7SwiftUI4ViewPAAE18accessibilityValue_9isEnabledAA15ModifiedContentVyxAA31AccessibilityAttachmentModifierVGAA4TextV_SbtF::SYNTHESIZED::s:10ScanbotSDK30SBSDKUI2TextPatternScannerViewV"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView\/accessibilityValue(_:isEnabled:)-4yky8"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerview\/accessibilityvalue(_:isenabled:)-4yky8"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerView/View-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView\/View-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerview\/view-implementations","type":"topic","abstract":[],"role":"collectionGroup","title":"View Implementations","kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerView":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerview","type":"topic","abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController"},{"type":"text","text":"."}],"role":"symbol","title":"SBSDKUI2TextPatternScannerView","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2TextPatternScannerView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerView"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController","kind":"symbol","type":"topic","title":"SBSDKUI2TextPatternScannerViewController","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextPatternScannerViewController","kind":"identifier"}],"abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan generic text data.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerView/accessibilityValue(_:isEnabled:)-4yky8":{"title":"accessibilityValue(_:isEnabled:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityValue"},{"kind":"text","text":"("},{"text":"Text","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4TextV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI15ModifiedContentV","text":"ModifiedContent","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","kind":"typeIdentifier","text":"AccessibilityAttachmentModifier"},{"kind":"text","text":">"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerview\/accessibilityvalue(_:isenabled:)-4yky8","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView\/accessibilityValue(_:isEnabled:)-4yky8","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2TextPatternScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerViewController\/title","op":"replace"},{"value":[{"text":"SBSDKUI2TextPatternScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerViewController\/fragments"},{"value":[{"text":"SBSDKUI2TextPatternScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerViewController\/navigatorTitle"}]}]}