{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView\/View-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"View.lineLimit(_:reservesSpace:)","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerview\/linelimit(_:reservesspace:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineLimit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"limit","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"reservesSpace","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"},{"text":"\n","kind":"text"}]}]}],"kind":"symbol","sections":[],"metadata":{"platforms":[{"beta":false,"name":"iOS","introducedAt":"16.0","unavailable":false,"deprecated":false},{"unavailable":false,"introducedAt":"16.0","name":"iPadOS","beta":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"16.0","deprecated":false,"unavailable":false},{"name":"macOS","deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false},{"introducedAt":"16.0","beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"name":"watchOS","introducedAt":"9.0","unavailable":false,"beta":false,"deprecated":false}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"lineLimit","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"reservesSpace","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"title":"lineLimit(_:reservesSpace:)","externalID":"s:7SwiftUI4ViewPAAE9lineLimit_13reservesSpaceQrSi_SbtF::SYNTHESIZED::s:10ScanbotSDK30SBSDKUI2TextPatternScannerViewV","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK","relatedModules":["SwiftUICore"]}],"symbolKind":"method","role":"symbol","extendedModule":"SwiftUICore"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView\/lineLimit(_:reservesSpace:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerView/lineLimit(_:reservesSpace:)":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerview\/linelimit(_:reservesspace:)","title":"lineLimit(_:reservesSpace:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lineLimit","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reservesSpace"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView\/lineLimit(_:reservesSpace:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerView":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerview","type":"topic","abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController"},{"type":"text","text":"."}],"role":"symbol","title":"SBSDKUI2TextPatternScannerView","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2TextPatternScannerView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerView"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerView/View-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView\/View-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerview\/view-implementations","type":"topic","abstract":[],"role":"collectionGroup","title":"View Implementations","kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController","kind":"symbol","type":"topic","title":"SBSDKUI2TextPatternScannerViewController","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextPatternScannerViewController","kind":"identifier"}],"abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan generic text data.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerViewController\/title","value":"SBSDKUI2TextPatternScannerViewController"},{"value":[{"text":"SBSDKUI2TextPatternScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerViewController\/fragments"},{"value":[{"text":"SBSDKUI2TextPatternScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}