{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"metadata":{"symbolKind":"enum","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKErrorCode","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKErrorCode","kind":"identifier"}],"title":"SBSDKErrorCode","role":"symbol","roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCode"}]},"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/OCRLanguageMissing","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/PDFCreation","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/PDFMetadataCreation","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/cancelled","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/imageStorageCopyingFailed","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/invalidFileURL","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/invalidImageData","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/invalidImageStorage","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/pageAnalysis","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/textRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/unknown"]},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/init(rawValue:)"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKErrorCode"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The error codes in the SBSDKErrorDomain."}],"sections":[],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"kind":"relationships","title":"Conforms To"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorCode":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKErrorCode"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode","role":"symbol","abstract":[{"type":"text","text":"The error codes in the SBSDKErrorDomain."}],"navigatorTitle":[{"text":"SBSDKErrorCode","kind":"identifier"}],"title":"SBSDKErrorCode","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorCode/invalidImageStorage":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"invalidImageStorage","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodeInvalidImageStorage"}],"title":"SBSDKErrorCode.invalidImageStorage","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode\/invalidimagestorage","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/invalidImageStorage","kind":"symbol","abstract":[{"text":"The image storage was invalid or nil.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorCode/init(rawValue:)":{"abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorCode/imageStorageCopyingFailed":{"abstract":[{"text":"The image storage was invalid or nil.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode\/imagestoragecopyingfailed","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/imageStorageCopyingFailed","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageStorageCopyingFailed","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKErrorCodeImageStorageCopyingFailed","kind":"identifier"}],"title":"SBSDKErrorCode.imageStorageCopyingFailed","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorCode/PDFMetadataCreation":{"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PDFMetadataCreation","kind":"identifier"}],"abstract":[{"type":"text","text":"There was an unknown error while rendering pdf metadata.*\/"}],"title":"SBSDKErrorCode.PDFMetadataCreation","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/PDFMetadataCreation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodePDFMetadataCreation"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode\/pdfmetadatacreation"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorCode/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode\/equatable-implementations","title":"Equatable Implementations","kind":"article","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/Equatable-Implementations","role":"collectionGroup","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorCode/textRecognition":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textRecognition"}],"abstract":[{"text":"Optical text recognition failed.","type":"text"}],"title":"SBSDKErrorCode.textRecognition","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/textRecognition","role":"symbol","navigatorTitle":[{"text":"SBSDKErrorCodeTextRecognition","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode\/textrecognition"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorCode/invalidFileURL":{"abstract":[{"text":"The file does not exist.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode\/invalidfileurl","title":"SBSDKErrorCode.invalidFileURL","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/invalidFileURL","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"invalidFileURL","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodeInvalidFileURL"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorCode/invalidImageData":{"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidImageData"}],"abstract":[{"type":"text","text":"The image file did not contain valid image data."}],"title":"SBSDKErrorCode.invalidImageData","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/invalidImageData","role":"symbol","navigatorTitle":[{"text":"SBSDKErrorCodeInvalidImageData","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode\/invalidimagedata"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorCode/PDFCreation":{"type":"topic","title":"SBSDKErrorCode.PDFCreation","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/PDFCreation","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFCreation","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode\/pdfcreation","navigatorTitle":[{"text":"SBSDKErrorCodePDFCreation","kind":"identifier"}],"abstract":[{"type":"text","text":"There was an unknown error while rendering a PDF page."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorCode/pageAnalysis":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageAnalysis"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode\/pageanalysis","kind":"symbol","role":"symbol","type":"topic","title":"SBSDKErrorCode.pageAnalysis","abstract":[{"text":"Page analysis failed.","type":"text"}],"navigatorTitle":[{"text":"SBSDKErrorCodePageAnalysis","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/pageAnalysis"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorCode/OCRLanguageMissing":{"abstract":[{"text":"Language data for text recognition is missing.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode\/ocrlanguagemissing","title":"SBSDKErrorCode.OCRLanguageMissing","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/OCRLanguageMissing","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCRLanguageMissing"}],"type":"topic","navigatorTitle":[{"text":"SBSDKErrorCodeOCRLanguageMissing","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorCode/RawRepresentable-Implementations":{"kind":"article","type":"topic","abstract":[],"title":"RawRepresentable Implementations","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/RawRepresentable-Implementations","role":"collectionGroup","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode\/rawrepresentable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorCode/unknown":{"abstract":[{"text":"Some other error.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode\/unknown","title":"SBSDKErrorCode.unknown","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/unknown","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"type":"topic","navigatorTitle":[{"text":"SBSDKErrorCodeUnknown","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorCode/cancelled":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"abstract":[{"text":"The operation was cancelled.","type":"text"}],"title":"SBSDKErrorCode.cancelled","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/cancelled","role":"symbol","navigatorTitle":[{"text":"SBSDKErrorCodeCancelled","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrorcode\/cancelled"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKErrorCode","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKErrorCode"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorCode"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/OCRLanguageMissing","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/PDFCreation","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/PDFMetadataCreation","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/cancelled","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/imageStorageCopyingFailed","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/invalidFileURL","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/invalidImageData","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/invalidImageStorage","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/pageAnalysis","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/textRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorCode\/unknown"],"generated":true}]},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKErrorCode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode\/title","value":"SBSDKErrorCode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode\/fragments","value":[{"kind":"identifier","text":"SBSDKErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode\/navigatorTitle","value":[{"text":"SBSDKErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1invalidImageStorage\/title","op":"replace","value":"SBSDKErrorCodeInvalidImageStorage"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorCodeInvalidImageStorage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1invalidImageStorage\/fragments"},{"value":"SBSDKErrorCodeImageStorageCopyingFailed","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1imageStorageCopyingFailed\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorCodeImageStorageCopyingFailed"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1imageStorageCopyingFailed\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1PDFMetadataCreation\/title","value":"SBSDKErrorCodePDFMetadataCreation","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1PDFMetadataCreation\/fragments","value":[{"kind":"identifier","text":"SBSDKErrorCodePDFMetadataCreation"}],"op":"replace"},{"op":"replace","value":"SBSDKErrorCodeTextRecognition","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1textRecognition\/title"},{"value":[{"text":"SBSDKErrorCodeTextRecognition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1textRecognition\/fragments"},{"value":"SBSDKErrorCodeInvalidFileURL","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1invalidFileURL\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1invalidFileURL\/fragments","value":[{"kind":"identifier","text":"SBSDKErrorCodeInvalidFileURL"}]},{"value":"SBSDKErrorCodeInvalidImageData","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1invalidImageData\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorCodeInvalidImageData"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1invalidImageData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1PDFCreation\/title","value":"SBSDKErrorCodePDFCreation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1PDFCreation\/fragments","value":[{"text":"SBSDKErrorCodePDFCreation","kind":"identifier"}]},{"op":"replace","value":"SBSDKErrorCodePageAnalysis","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1pageAnalysis\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorCodePageAnalysis"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1pageAnalysis\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1OCRLanguageMissing\/title","value":"SBSDKErrorCodeOCRLanguageMissing"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1OCRLanguageMissing\/fragments","value":[{"kind":"identifier","text":"SBSDKErrorCodeOCRLanguageMissing"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1unknown\/title","value":"SBSDKErrorCodeUnknown"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorCodeUnknown"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1unknown\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1cancelled\/title","value":"SBSDKErrorCodeCancelled","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorCode~1cancelled\/fragments","op":"replace","value":[{"text":"SBSDKErrorCodeCancelled","kind":"identifier"}]}]}]}