{"abstract":[{"text":"A class to describe the mocking data that is fed to a simulated camera device.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"inlineContent":[{"type":"text","text":"A simulated camera device loops a single image and provides the frames to the ScanbotSDK scanner UI components."},{"type":"text","text":" "},{"type":"text","text":"Along with the frame image you can optionally specify an image that is passed to the ScanbotSDK scanner UI components when capturing a still image."}],"type":"paragraph"},{"inlineContent":[{"text":"Intended to be used with UI tests.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageName:capturedImageName:refreshOnEachFrame:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/label","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/refreshOnEachFrame"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKSimulatedCameraMockData","roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"title":"SBSDKSimulatedCameraMockData","navigatorTitle":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSimulatedCameraMockData/init(label:imageName:capturedImageName:refreshOnEachFrame:)":{"role":"symbol","title":"init(label:imageName:capturedImageName:refreshOnEachFrame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageName"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"capturedImageName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"refreshOnEachFrame"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes mock data for a simulated camera device from ressource names of the application bundle."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageName:capturedImageName:refreshOnEachFrame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata\/init(label:imagename:capturedimagename:refreshoneachframe:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSimulatedCameraMockData/refreshOnEachFrame":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata\/refreshoneachframe","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refreshOnEachFrame","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"type":"text","text":"If set to "},{"code":"True","type":"codeVoice"},{"text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/refreshOnEachFrame","role":"symbol","navigatorTitle":[{"text":"refreshOnEachFrame","kind":"identifier"}],"title":"refreshOnEachFrame"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSimulatedCameraMockData/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)":{"abstract":[{"type":"text","text":"Initializes mock data for a simulated camera device from URLs."}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata\/init(label:imageurl:capturedimageurl:refreshoneachframe:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"imageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"capturedImageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"refreshOnEachFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"init(label:imageURL:capturedImageURL:refreshOnEachFrame:)","role":"symbol","navigatorTitle":[{"text":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSimulatedCameraMockData/label":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"label"}],"abstract":[{"text":"The label of the mock data. Can be used to identify the mock data.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata\/label","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/label","title":"label"},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSimulatedCameraMockData":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata","role":"symbol","abstract":[{"type":"text","text":"A class to describe the mocking data that is fed to a simulated camera device."}],"title":"SBSDKSimulatedCameraMockData","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKSimulatedCameraMockData","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/label","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/refreshOnEachFrame"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageName:capturedImageName:refreshOnEachFrame:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData~1init(label:imageName:capturedImageName:refreshOnEachFrame:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData~1init(label:imageName:capturedImageName:refreshOnEachFrame:)\/fragments"},{"value":"refreshOnEachFrame","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData~1refreshOnEachFrame\/title"},{"value":[{"text":"refreshOnEachFrame","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData~1refreshOnEachFrame\/fragments"},{"value":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData~1init(label:imageURL:capturedImageURL:refreshOnEachFrame:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData~1init(label:imageURL:capturedImageURL:refreshOnEachFrame:)\/fragments"},{"value":"label","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData~1label\/title"},{"value":[{"text":"label","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData~1label\/fragments"},{"value":"SBSDKSimulatedCameraMockData","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData\/title"},{"value":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData\/fragments"},{"value":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData\/navigatorTitle"}]}]}