{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Enumeration","symbolKind":"enum","role":"symbol","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm"},"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod10","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod1010","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod1110Ibm","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod1110Ncr","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod11Ibm","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod11Ncr","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/none"],"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"title":"Conforms To","kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(SBSDKUI2MSIPlesseyChecksumAlgorithm) "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"abstract":[{"text":"Type of MSI plessey checksum algorithm used.","type":"text"}],"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm/mod1010":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm\/mod1010","kind":"symbol","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.mod1010","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod1010","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mod1010","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod1010","kind":"identifier"}],"abstract":[{"text":"Mod1010 checksum algorithm","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm/mod1110Ncr":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Mod1110NCR checksum algorithm"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm\/mod1110ncr","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.mod1110Ncr","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod1110Ncr","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mod1110Ncr"}],"navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod1110Ncr","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm/mod11Ncr":{"navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod11Ncr","kind":"identifier"}],"abstract":[{"text":"Mod11NCR checksum algorithm","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm\/mod11ncr","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.mod11Ncr","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod11Ncr","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mod11Ncr","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm/mod10":{"navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}],"abstract":[{"text":"Mod10 checksum algorithm","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm\/mod10","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.mod10","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod10","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mod10"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm":{"abstract":[{"text":"Type of MSI plessey checksum algorithm used.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"title":"SBSDKUI2MSIPlesseyChecksumAlgorithm","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm/none":{"navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmNone","kind":"identifier"}],"abstract":[{"text":"No checksum algorithm used.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm\/none","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.none","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/Equatable-Implementations","type":"topic","role":"collectionGroup","kind":"article","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm\/equatable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm/init(rawValue:)":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm\/rawrepresentable-implementations","title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/RawRepresentable-Implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm/mod1110Ibm":{"navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod1110Ibm","kind":"identifier"}],"abstract":[{"type":"text","text":"Mod1110IBM checksum algorithm"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm\/mod1110ibm","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.mod1110Ibm","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod1110Ibm","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mod1110Ibm","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm/mod11Ibm":{"kind":"symbol","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.mod11Ibm","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mod11Ibm"}],"abstract":[{"text":"Mod11IBM checksum algorithm","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod11Ibm","navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod11Ibm","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm\/mod11ibm"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod10","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod1010","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod1110Ibm","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod1110Ncr","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod11Ibm","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod11Ncr","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/none"],"anchor":"Enumeration-Cases"}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod1010\/title","value":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod1010"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod1010\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod1010"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod1110Ncr\/title","op":"replace","value":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod1110Ncr"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod1110Ncr\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod1110Ncr"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod11Ncr\/title","value":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod11Ncr"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod11Ncr\/fragments","value":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod11Ncr","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod10\/title","op":"replace","value":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10"},{"op":"replace","value":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod10\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/title","value":"SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"value":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1none\/title","value":"SBSDKUI2MSIPlesseyChecksumAlgorithmNone","op":"replace"},{"value":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmNone","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1none\/fragments","op":"replace"},{"value":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod1110Ibm","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod1110Ibm\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod1110Ibm\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod1110Ibm"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod11Ibm\/title","op":"replace","value":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod11Ibm"},{"value":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod11Ibm","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod11Ibm\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}