{"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Protocol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyGenerator"}],"title":"SBSDKStorageCryptingKeyGenerator","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCryptingKeyGenerator","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStorageCryptingKeyGenerator"}],"symbolKind":"protocol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyGenerator","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyGenerator\/generateKey(keyLength:)"],"anchor":"Instance-Methods"}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKHKDFKeyGenerator","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPBKDF2KeyGenerator","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRandomKeyGenerator"],"type":"conformingTypes"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeygenerator"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeygenerator"]}],"abstract":[{"type":"text","text":"Protocol for generating encryption keys."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPBKDF2KeyGenerator":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPBKDF2KeyGenerator","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"title":"SBSDKPBKDF2KeyGenerator","abstract":[{"text":"A key generator that uses the PBKDF2 algorithm to derive a key from a password and a salt.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"See https:\/\/en.wikipedia.org\/wiki\/PBKDF2 for more information."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpbkdf2keygenerator","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingKeyGenerator":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyGenerator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Protocol for generating encryption keys.","type":"text"}],"title":"SBSDKStorageCryptingKeyGenerator","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeygenerator","type":"topic","navigatorTitle":[{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKHKDFKeyGenerator":{"title":"SBSDKHKDFKeyGenerator","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkhkdfkeygenerator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKHKDFKeyGenerator","navigatorTitle":[{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}],"abstract":[{"text":"A key generator that uses the HMAC based HKDF algorithm to generate a new encryption key. SHA512 is used as the hash function.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The key generation consists of two phases: extraction and expansion."},{"type":"text","text":" "},{"text":"During the extraction a pseudo random key is generated from the input key material and an optional salt.","type":"text"},{"text":" ","type":"text"},{"text":"The expansion phase uses the pseudo random key and the info data block to derive the final key.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKRandomKeyGenerator":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRandomKeyGenerator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKRandomKeyGenerator"}],"kind":"symbol","abstract":[{"text":"A class that generates secure, random keys for storage encryption.","type":"text"},{"text":" ","type":"text"},{"text":"They keys are generated using the ","type":"text"},{"code":"SecRandomCopyBytes","type":"codeVoice"},{"type":"text","text":" function."}],"title":"SBSDKRandomKeyGenerator","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkrandomkeygenerator","navigatorTitle":[{"text":"SBSDKRandomKeyGenerator","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingKeyGenerator/generateKey(keyLength:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"generateKey","kind":"identifier"},{"text":"(","kind":"text"},{"text":"keyLength","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKStorageCryptingKeyLength"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"generateKeyWithLength:WithError:","kind":"identifier"}],"required":true,"title":"generateKey(keyLength:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyGenerator\/generateKey(keyLength:)","abstract":[{"type":"text","text":"Generates a new encryption key."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeygenerator\/generatekey(keylength:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKStorageCryptingKeyGenerator","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyGenerator"}],"op":"replace"},{"op":"replace","value":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyGenerator\/generateKey(keyLength:)"]}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Conforming Types","type":"conformingTypes","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKHKDFKeyGenerator","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPBKDF2KeyGenerator","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRandomKeyGenerator"]}],"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCryptingKeyGenerator"}]}]}},{"op":"replace","value":"SBSDKPBKDF2KeyGenerator","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPBKDF2KeyGenerator\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPBKDF2KeyGenerator\/fragments","value":[{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPBKDF2KeyGenerator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPBKDF2KeyGenerator"}]},{"value":"SBSDKStorageCryptingKeyGenerator","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyGenerator\/title"},{"value":[{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyGenerator\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyGenerator\/navigatorTitle","value":[{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKHKDFKeyGenerator\/title","value":"SBSDKHKDFKeyGenerator","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKHKDFKeyGenerator\/fragments","value":[{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKHKDFKeyGenerator\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRandomKeyGenerator\/title","value":"SBSDKRandomKeyGenerator","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRandomKeyGenerator\/fragments","value":[{"text":"SBSDKRandomKeyGenerator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRandomKeyGenerator\/navigatorTitle","value":[{"text":"SBSDKRandomKeyGenerator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyGenerator~1generateKey(keyLength:)\/title","op":"replace","value":"generateKeyWithLength:WithError:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyGenerator~1generateKey(keyLength:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"generateKeyWithLength:WithError:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}