{"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoFlipMode"}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKVideoFlipMode"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"enum","title":"SBSDKVideoFlipMode","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKVideoFlipMode","role":"symbol","navigatorTitle":[{"text":"SBSDKVideoFlipMode","kind":"identifier"}],"roleHeading":"Enumeration"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode"},"abstract":[{"text":"An enum describing how images can be flipped.","type":"text"}],"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/both","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/horizontal","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/none","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/vertical"],"title":"Enumeration Cases"},{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoflipmode"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoflipmode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFlipMode/init(rawValue:)":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","title":"init(rawValue:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoflipmode\/init(rawvalue:)","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFlipMode/RawRepresentable-Implementations":{"type":"topic","kind":"article","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/RawRepresentable-Implementations","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoflipmode\/rawrepresentable-implementations","role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFlipMode/vertical":{"type":"topic","title":"SBSDKVideoFlipMode.vertical","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFlipModeVertical"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/vertical","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoflipmode\/vertical","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"vertical","kind":"identifier"}],"abstract":[{"type":"text","text":"Flip the image vertically."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFlipMode/both":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/both","abstract":[{"type":"text","text":"Flip the image both, horizontally and vertically."}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoflipmode\/both","title":"SBSDKVideoFlipMode.both","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"both"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFlipModeBoth"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 6.2.0"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFlipMode/horizontal":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/horizontal","title":"SBSDKVideoFlipMode.horizontal","role":"symbol","abstract":[{"type":"text","text":"Flip the image horizontally."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoflipmode\/horizontal","type":"topic","navigatorTitle":[{"text":"SBSDKVideoFlipModeHorizontal","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"horizontal","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFlipMode":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFlipMode"}],"abstract":[{"text":"An enum describing how images can be flipped.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoFlipMode","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoflipmode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode","title":"SBSDKVideoFlipMode"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFlipMode/none":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoflipmode\/none","abstract":[{"text":"Do not flip the image.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFlipModeNone"}],"title":"SBSDKVideoFlipMode.none","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/none"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFlipMode/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoflipmode\/equatable-implementations","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKVideoFlipMode"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFlipMode"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKVideoFlipMode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/both","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/horizontal","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/none","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/vertical"],"generated":true,"title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKVideoFlipMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"SBSDKVideoFlipModeVertical","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFlipMode~1vertical\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKVideoFlipModeVertical"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFlipMode~1vertical\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFlipMode~1both\/title","op":"replace","value":"SBSDKVideoFlipModeBoth"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFlipMode~1both\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoFlipModeBoth"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFlipMode~1horizontal\/title","value":"SBSDKVideoFlipModeHorizontal","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKVideoFlipModeHorizontal"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFlipMode~1horizontal\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFlipMode\/title","value":"SBSDKVideoFlipMode"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFlipMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFlipMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFlipMode\/navigatorTitle","value":[{"text":"SBSDKVideoFlipMode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFlipMode~1none\/title","value":"SBSDKVideoFlipModeNone"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFlipMode~1none\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoFlipModeNone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}