{"abstract":[{"text":"Subheading.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/generalNotes","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/keyWords","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/medicines","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/prescriptions","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/requiredDocumentType","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/subheadingFreeText"],"title":"Instance Properties"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentWrapper"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"],"title":"Conforms To"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheading"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheading"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentDEMedicalPlanSubheading","title":"SBSDKBarcodeDocumentDEMedicalPlanSubheading","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheading"}],"roleHeading":"Class","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheading"}],"symbolKind":"class"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheading"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlanSubheading/generalNotes":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheading\/generalnotes","title":"generalNotes","navigatorTitle":[{"text":"generalNotes","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generalNotes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"]?","kind":"text"}],"abstract":[{"text":"General Note.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/generalNotes"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentWrapper":{"title":"SBSDKGenericDocumentWrapper","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentWrapper","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentwrapper","navigatorTitle":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"abstract":[{"type":"text","text":"Base class for strongly-typed "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocument"},{"type":"text","text":" wrappers."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlanSubheading/requiredDocumentType":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheading\/requireddocumenttype","title":"requiredDocumentType","navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":"The name of the wrapped document type.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/requiredDocumentType"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlanSubheading/subheadingFreeText":{"title":"subheadingFreeText","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheading\/subheadingfreetext","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/subheadingFreeText","type":"topic","abstract":[{"text":"Subheading Free Text.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subheadingFreeText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"subheadingFreeText","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlanSubheading/keyWords":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyWords","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"text":"Key Words.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheading\/keywords","title":"keyWords","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/keyWords","navigatorTitle":[{"text":"keyWords","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocument":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocument","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"type":"topic","title":"SBSDKGenericDocument","abstract":[{"text":"Represents a generic document with fields and sub-documents used for document recognition.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocument","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlanSubheading":{"title":"SBSDKBarcodeDocumentDEMedicalPlanSubheading","abstract":[{"type":"text","text":"Subheading."}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentDEMedicalPlanSubheading","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheading","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentDEMedicalPlanSubheading","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlanSubheading/prescriptions":{"abstract":[{"text":"Prescription.","type":"text"}],"navigatorTitle":[{"text":"prescriptions","kind":"identifier"}],"title":"prescriptions","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prescriptions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription"},{"text":"]?","kind":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheading\/prescriptions","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/prescriptions"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlanSubheading/medicines":{"abstract":[{"text":"Medicine.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"medicines"}],"title":"medicines","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"medicines"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine","kind":"typeIdentifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine"},{"kind":"text","text":"]?"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheading\/medicines","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/medicines"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlanSubheading/initWithGenericDocument:":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheading\/initwithgenericdocument:","title":"initWithGenericDocument:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGenericDocument:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithGenericDocument:"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/initWithGenericDocument:"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeDocumentDEMedicalPlanSubheading"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheading"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheading"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/generalNotes","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/keyWords","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/medicines","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/prescriptions","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/requiredDocumentType","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/subheadingFreeText"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/initWithGenericDocument:"],"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentWrapper"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentDEMedicalPlanSubheading","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentWrapper","text":"SBSDKGenericDocumentWrapper","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentWrapper","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading~1generalNotes\/title","value":"generalNotes"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading~1generalNotes\/fragments","value":[{"kind":"identifier","text":"generalNotes"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentWrapper\/title","value":"SBSDKGenericDocumentWrapper"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentWrapper\/fragments","value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading~1requiredDocumentType\/title","value":"requiredDocumentType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading~1requiredDocumentType\/fragments","value":[{"text":"requiredDocumentType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading~1subheadingFreeText\/title","value":"subheadingFreeText"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading~1subheadingFreeText\/fragments","value":[{"kind":"identifier","text":"subheadingFreeText"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading~1keyWords\/title","value":"keyWords"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading~1keyWords\/fragments","value":[{"text":"keyWords","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/fragments","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading\/title","value":"SBSDKBarcodeDocumentDEMedicalPlanSubheading"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheading"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentDEMedicalPlanSubheading","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading~1prescriptions\/title","value":"prescriptions"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading~1prescriptions\/fragments","value":[{"kind":"identifier","text":"prescriptions"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading~1medicines\/title","value":"medicines"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading~1medicines\/fragments","value":[{"text":"medicines","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}