{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"alphaNumeric","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AustraliaPostCustomerFormat"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2australiapostcustomerformat\/alphanumeric"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2australiapostcustomerformat\/alphanumeric"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The alphanumeric format."}],"metadata":{"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2AustraliaPostCustomerFormat@SBSDKUI2AustraliaPostCustomerFormatAlphaNumeric","title":"SBSDKUI2AustraliaPostCustomerFormat.alphaNumeric","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"alphaNumeric","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2AustraliaPostCustomerFormatAlphaNumeric","kind":"identifier"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AustraliaPostCustomerFormat\/alphaNumeric"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AustraliaPostCustomerFormat":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2AustraliaPostCustomerFormat","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2AustraliaPostCustomerFormat","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2australiapostcustomerformat","title":"SBSDKUI2AustraliaPostCustomerFormat","type":"topic","abstract":[{"text":"The customer format used in AUSTRALIA_POST codes. Only relevant for format codes 59 and 62.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AustraliaPostCustomerFormat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AustraliaPostCustomerFormat/alphaNumeric":{"type":"topic","abstract":[{"text":"The alphanumeric format.","type":"text"}],"title":"SBSDKUI2AustraliaPostCustomerFormat.alphaNumeric","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alphaNumeric","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AustraliaPostCustomerFormatAlphaNumeric"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2australiapostcustomerformat\/alphanumeric","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AustraliaPostCustomerFormat\/alphaNumeric","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2AustraliaPostCustomerFormatAlphaNumeric"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2AustraliaPostCustomerFormatAlphaNumeric"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKUI2AustraliaPostCustomerFormatAlphaNumeric","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AustraliaPostCustomerFormat\/title","op":"replace","value":"SBSDKUI2AustraliaPostCustomerFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AustraliaPostCustomerFormat\/fragments","value":[{"text":"SBSDKUI2AustraliaPostCustomerFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AustraliaPostCustomerFormat~1alphaNumeric\/title","op":"replace","value":"SBSDKUI2AustraliaPostCustomerFormatAlphaNumeric"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AustraliaPostCustomerFormat~1alphaNumeric\/fragments","value":[{"text":"SBSDKUI2AustraliaPostCustomerFormatAlphaNumeric","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}