{"abstract":[{"text":"Whether auto-snapping is enabled or not.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/isautosnappingenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/isautosnappingenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration"]]},"metadata":{"platforms":[],"role":"symbol","navigatorTitle":[{"text":"isAutoSnappingEnabled","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerBehaviorConfiguration(py)isAutoSnappingEnabled","symbolKind":"property","title":"isAutoSnappingEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAutoSnappingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}],"type":"paragraph"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAutoSnappingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"True"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/isAutoSnappingEnabled","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/isAutoSnappingEnabled":{"type":"topic","title":"isAutoSnappingEnabled","role":"symbol","deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAutoSnappingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/isAutoSnappingEnabled","kind":"symbol","abstract":[{"type":"text","text":"Whether auto-snapping is enabled or not."}],"navigatorTitle":[{"text":"isAutoSnappingEnabled","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/isautosnappingenabled"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration"}],"type":"topic","abstract":[{"type":"text","text":"Configuration for the behavior of the document scanning screen."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration","title":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isAutoSnappingEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isAutoSnappingEnabled"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAutoSnappingEnabled"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1isAutoSnappingEnabled\/title","value":"isAutoSnappingEnabled"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1isAutoSnappingEnabled\/fragments","value":[{"kind":"identifier","text":"isAutoSnappingEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/title","value":"SBSDKUIFinderDocumentScannerBehaviorConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration"}]}]}]}