{"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}]}],"abstract":[{"text":"Whether the flash button is hidden or not.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerUIConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscanneruiconfiguration\/isflashbuttonhidden"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscanneruiconfiguration\/isflashbuttonhidden"]}],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFlashButtonHidden","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isFlashButtonHidden","kind":"identifier"}],"title":"isFlashButtonHidden","platforms":[],"roleHeading":"Instance Property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerUIConfiguration(py)isFlashButtonHidden","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerUIConfiguration\/isFlashButtonHidden"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFlashButtonHidden","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"False"},{"text":".","type":"text"}]}],"kind":"content"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerUIConfiguration/isFlashButtonHidden":{"navigatorTitle":[{"text":"isFlashButtonHidden","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Whether the flash button is hidden or not.","type":"text"}],"title":"isFlashButtonHidden","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscanneruiconfiguration\/isflashbuttonhidden","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerUIConfiguration\/isFlashButtonHidden","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFlashButtonHidden","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"deprecated":true},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerUIConfiguration":{"deprecated":true,"title":"SBSDKUIFinderDocumentScannerUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerUIConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerUIConfiguration"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration for the user interface of the document scanning screen."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerUIConfiguration"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscanneruiconfiguration"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"isFlashButtonHidden","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"isFlashButtonHidden","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFlashButtonHidden"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerUIConfiguration~1isFlashButtonHidden\/title","value":"isFlashButtonHidden","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerUIConfiguration~1isFlashButtonHidden\/fragments","value":[{"kind":"identifier","text":"isFlashButtonHidden"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerUIConfiguration\/title","value":"SBSDKUIFinderDocumentScannerUIConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerUIConfiguration\/fragments","value":[{"text":"SBSDKUIFinderDocumentScannerUIConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIFinderDocumentScannerUIConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}