{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeSnapshot","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshot","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"text":"The snapshot of all alive ImageRefs.","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefProfiler\/makeSnapshot()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefProfiler"]]},"metadata":{"roleHeading":"Type Method","symbolKind":"method","title":"makeSnapshot()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeSnapshot","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","text":"SBSDKImageRefPoolSnapshot","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefProfiler(cm)makeSnapshot","role":"symbol","navigatorTitle":[{"text":"makeSnapshot","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"type":"text","text":"Returns a snapshot of all alive ImageRefs. The snapshot contains a list of ImageRefs with information such as"},{"type":"text","text":" "},{"type":"text","text":"in-memory size. If detailed profiling is enabled (by calling enableDetailedProfiling beforehand), the profile"},{"type":"text","text":" "},{"type":"text","text":"will contain additional information such as the source from which each ImageRef has been created."}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefprofiler\/makesnapshot()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefprofiler\/makesnapshot()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRefProfiler":{"kind":"symbol","type":"topic","abstract":[{"text":"ImageRef memory profiler.","type":"text"}],"title":"SBSDKImageRefProfiler","role":"symbol","navigatorTitle":[{"text":"SBSDKImageRefProfiler","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRefProfiler"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefprofiler","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefProfiler"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRefProfiler/makeSnapshot()":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeSnapshot"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","text":"SBSDKImageRefPoolSnapshot"}],"navigatorTitle":[{"kind":"identifier","text":"makeSnapshot"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefProfiler\/makeSnapshot()","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefprofiler\/makesnapshot()","abstract":[{"type":"text","text":"Returns a snapshot of all alive ImageRefs. The snapshot contains a list of ImageRefs with information such as"},{"type":"text","text":" "},{"type":"text","text":"in-memory size. If detailed profiling is enabled (by calling enableDetailedProfiling beforehand), the profile"},{"type":"text","text":" "},{"type":"text","text":"will contain additional information such as the source from which each ImageRef has been created."}],"type":"topic","role":"symbol","title":"makeSnapshot()"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRefPoolSnapshot":{"kind":"symbol","abstract":[{"text":"Snapshot of all alive ImageRefs.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefpoolsnapshot","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshot","title":"SBSDKImageRefPoolSnapshot","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"makeSnapshot","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"makeSnapshot"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshot","text":"SBSDKImageRefPoolSnapshot","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"makeSnapshot","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"The snapshot of all alive ImageRefs.","type":"text"}],"type":"paragraph"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SBSDKImageRefProfiler","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefProfiler\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefProfiler"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefProfiler\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefProfiler"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefProfiler\/navigatorTitle"},{"op":"replace","value":"makeSnapshot","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefProfiler~1makeSnapshot()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"makeSnapshot"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefProfiler~1makeSnapshot()\/fragments"},{"op":"replace","value":"SBSDKImageRefPoolSnapshot","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshot\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshot\/fragments"},{"op":"replace","value":[{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshot\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}