{"sections":[],"abstract":[{"type":"text","text":"Asks the delegate if the scanner should scan credit cards on the next video frame."},{"type":"text","text":" "},{"type":"text","text":"Optional."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewControllerDelegate\/creditCardScannerViewControllerShouldScanCreditCard(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"creditCardScannerViewControllerShouldScanCreditCard"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerViewController","kind":"typeIdentifier","text":"SBSDKCreditCardScannerViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"controller","content":[{"inlineContent":[{"text":"The calling ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Return "},{"type":"codeVoice","code":"True"},{"type":"text","text":" if you want to scan credit cards on the next video frame, "},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKCreditCardScannerViewControllerDelegate(im)creditCardScannerViewControllerShouldScanCreditCard:","required":true,"modules":[{"name":"ScanbotSDK"}],"title":"creditCardScannerViewControllerShouldScanCreditCard(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardScannerViewControllerShouldScanCreditCard","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCreditCardScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"creditCardScannerViewControllerShouldScanCreditCard:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewControllerDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontrollerdelegate\/creditcardscannerviewcontrollershouldscancreditcard(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontrollerdelegate\/creditcardscannerviewcontrollershouldscancreditcard(_:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerViewControllerDelegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardScannerViewControllerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCreditCardScannerViewControllerDelegate"}],"kind":"symbol","title":"SBSDKCreditCardScannerViewControllerDelegate","abstract":[{"text":"The delegate protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontrollerdelegate","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerViewController":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontroller","title":"SBSDKCreditCardScannerViewController","type":"topic","abstract":[{"text":"Classic UI view controller that can be used to scan credit cards.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerViewControllerDelegate/creditCardScannerViewControllerShouldScanCreditCard(_:)":{"kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"creditCardScannerViewControllerShouldScanCreditCard:"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewControllerDelegate\/creditCardScannerViewControllerShouldScanCreditCard(_:)","abstract":[{"text":"Asks the delegate if the scanner should scan credit cards on the next video frame.","type":"text"},{"text":" ","type":"text"},{"text":"Optional.","type":"text"}],"title":"creditCardScannerViewControllerShouldScanCreditCard(_:)","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontrollerdelegate\/creditcardscannerviewcontrollershouldscancreditcard(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"creditCardScannerViewControllerShouldScanCreditCard"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerViewController","kind":"typeIdentifier","text":"SBSDKCreditCardScannerViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"creditCardScannerViewControllerShouldScanCreditCard:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"creditCardScannerViewControllerShouldScanCreditCard:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"creditCardScannerViewControllerShouldScanCreditCard:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","text":"SBSDKCreditCardScannerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The calling ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"controller"}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Return "},{"code":"True","type":"codeVoice"},{"type":"text","text":" if you want to scan credit cards on the next video frame, "},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise."}]}],"kind":"content"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate\/title","value":"SBSDKCreditCardScannerViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate\/fragments","value":[{"text":"SBSDKCreditCardScannerViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKCreditCardScannerViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/title","value":"SBSDKCreditCardScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/fragments","value":[{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/navigatorTitle","value":[{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate~1creditCardScannerViewControllerShouldScanCreditCard(_:)\/title","value":"creditCardScannerViewControllerShouldScanCreditCard:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate~1creditCardScannerViewControllerShouldScanCreditCard(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"creditCardScannerViewControllerShouldScanCreditCard:"}],"op":"replace"}]}]}