{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfpagesextractor\/images(from:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfpagesextractor\/images(from:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFPagesExtractor"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","metadata":{"symbolKind":"method","navigatorTitle":[{"text":"imagesFromPDF:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"images","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPDFPagesExtractor(im)imagesFromPDF:","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"images(from:)"},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFPagesExtractor\/images(from:)","interfaceLanguage":"swift"},"abstract":[{"text":"Extracts pages from PDF and converts them to an array of ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":". Nothing is written to disk during this operation. Runs in the same thread, as it is called from."},{"text":" ","type":"text"},{"type":"text","text":"The scaling of the media box is set to 2."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(imagesFromPDF:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"images"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"pdfURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":") -> [","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"]"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"pdfURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL of the PDF file."}]}]}]},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"An array of ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" with extracted pages. The array will be empty if something is wrong."}]}],"kind":"content"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPDFPagesExtractor/images(from:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"images","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"]"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfpagesextractor\/images(from:)","type":"topic","navigatorTitle":[{"text":"imagesFromPDF:","kind":"identifier"}],"abstract":[{"type":"text","text":"Extracts pages from PDF and converts them to an array of "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":". Nothing is written to disk during this operation. Runs in the same thread, as it is called from."},{"text":" ","type":"text"},{"type":"text","text":"The scaling of the media box is set to 2."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFPagesExtractor\/images(from:)","title":"images(from:)","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPDFPagesExtractor":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfpagesextractor","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}],"type":"topic","navigatorTitle":[{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}],"abstract":[{"type":"text","text":"Class used to extract pages from a PDF file and returns them in various ways."}],"title":"SBSDKPDFPagesExtractor","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFPagesExtractor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"imagesFromPDF:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"imagesFromPDF:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<UIImage *>"},{"kind":"text","text":" *) "},{"text":"imagesFromPDF:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"text":"pdfURL","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"pdfURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL of the PDF file."}]}]}],"kind":"parameters"}},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" with extracted pages. The array will be empty if something is wrong."}]}]},"op":"replace"},{"value":"imagesFromPDF:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFPagesExtractor~1images(from:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFPagesExtractor~1images(from:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"imagesFromPDF:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFPagesExtractor\/title","value":"SBSDKPDFPagesExtractor"},{"value":[{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFPagesExtractor\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFPagesExtractor\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}]}]}]}