{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices(for:position:)"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"availableDevicesForType:andPosition:"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableDevices"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCameraDeviceType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDeviceType"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCameraDevicePosition","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDevicePosition","kind":"typeIdentifier"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice","text":"SBSDKCameraDevice"},{"kind":"text","text":"]"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice(cm)availableDevicesForType:andPosition:","title":"availableDevices(for:position:)","role":"symbol","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(availableDevicesForType:andPosition:) ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableDevices","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCameraDeviceType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDeviceType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"position"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDevicePosition","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevicePosition","kind":"typeIdentifier","text":"SBSDKCameraDevicePosition"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"SBSDKCameraDevice","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice"},{"kind":"text","text":"]"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"type","content":[{"inlineContent":[{"type":"text","text":"The type of the requested cameras: wide, ultra-wide, tele, etc."}],"type":"paragraph"}]},{"name":"position","content":[{"type":"paragraph","inlineContent":[{"text":"The position of the requested cameras: front or back.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"A list of the supported available cameras of the current device for the given type and position.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Returns a list of all available and supported cameras of the device of the given type and position.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevice\/availabledevices(for:position:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevice\/availabledevices(for:position:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice":{"title":"SBSDKCameraDevice","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCameraDevice"}],"url":"\/documentation\/scanbotsdk\/sbsdkcameradevice","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice","abstract":[{"text":"The camera device to be used with a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"SBSDKCameraDevice","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype","title":"SBSDKCameraDeviceType","abstract":[{"type":"text","text":"An enum to describe the different types of camera lenses\/devices."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCameraSession"}],"type":"topic","abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"text":" ","type":"text"},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSession"}],"title":"SBSDKCameraSession","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevicePosition":{"navigatorTitle":[{"text":"SBSDKCameraDevicePosition","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum to describe the physical position of a camera device."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcameradeviceposition","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraDevicePosition","kind":"identifier"}],"title":"SBSDKCameraDevicePosition","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevicePosition","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice/availableDevices(for:position:)":{"url":"\/documentation\/scanbotsdk\/sbsdkcameradevice\/availabledevices(for:position:)","title":"availableDevices(for:position:)","abstract":[{"text":"Returns a list of all available and supported cameras of the device of the given type and position.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"availableDevicesForType:andPosition:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices(for:position:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"availableDevices","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDeviceType","kind":"typeIdentifier","text":"SBSDKCameraDeviceType"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKCameraDevicePosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDevicePosition"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice","text":"SBSDKCameraDevice"},{"text":"]","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"availableDevicesForType:andPosition:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"availableDevicesForType:andPosition:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSArray<SBSDKCameraDevice *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"availableDevicesForType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKCameraDeviceType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDeviceType"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"andPosition:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraDevicePosition","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevicePosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDevicePosition"},{"text":") ","kind":"text"},{"text":"position","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The type of the requested cameras: wide, ultra-wide, tele, etc."}],"type":"paragraph"}],"name":"type"},{"name":"position","content":[{"inlineContent":[{"type":"text","text":"The position of the requested cameras: front or back."}],"type":"paragraph"}]}]},"op":"replace"},{"value":{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"A list of the supported available cameras of the current device for the given type and position.","type":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice\/title","value":"SBSDKCameraDevice","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice\/fragments","value":[{"text":"SBSDKCameraDevice","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCameraDevice","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/title","value":"SBSDKCameraDeviceType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/title","value":"SBSDKCameraSession"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraSession"}]},{"value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/navigatorTitle","op":"replace"},{"value":"SBSDKCameraDevicePosition","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevicePosition\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevicePosition\/fragments","value":[{"text":"SBSDKCameraDevicePosition","kind":"identifier"}]},{"value":[{"text":"SBSDKCameraDevicePosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevicePosition\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1availableDevices(for:position:)\/title","value":"availableDevicesForType:andPosition:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"availableDevicesForType:andPosition:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1availableDevices(for:position:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}