{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedField\/init(fieldName:fieldTag:stringValue:)"},"metadata":{"navigatorTitle":[{"text":"initWithFieldName:fieldTag:stringValue:","kind":"identifier"}],"roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterUserDefinedField(im)initWithFieldName:fieldTag:stringValue:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"fieldName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fieldTag","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"stringValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","symbolKind":"init","title":"init(fieldName:fieldTag:stringValue:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedField"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Creates a new user-defined TIFF field with a string-type value."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"fieldName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fieldTag"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stringValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"fieldName","content":[{"inlineContent":[{"type":"text","text":"The name of the field."}],"type":"paragraph"}]},{"name":"fieldTag","content":[{"inlineContent":[{"text":"The tag of the field.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The string value of the field.","type":"text"}],"type":"paragraph"}],"name":"stringValue"}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfield\/init(fieldname:fieldtag:stringvalue:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfield\/init(fieldname:fieldtag:stringvalue:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterUserDefinedField/init(fieldName:fieldTag:stringValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"fieldName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"fieldTag","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stringValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedField\/init(fieldName:fieldTag:stringValue:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfield\/init(fieldname:fieldtag:stringvalue:)","navigatorTitle":[{"text":"initWithFieldName:fieldTag:stringValue:","kind":"identifier"}],"title":"init(fieldName:fieldTag:stringValue:)","role":"symbol","kind":"symbol","abstract":[{"text":"Creates a new user-defined TIFF field with a string-type value.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterUserDefinedField":{"abstract":[{"type":"text","text":"A class used to describe a user-defined TIFF field."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTIFFImageWriterUserDefinedField"}],"type":"topic","title":"SBSDKTIFFImageWriterUserDefinedField","navigatorTitle":[{"text":"SBSDKTIFFImageWriterUserDefinedField","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedField","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfield"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithFieldName:fieldTag:stringValue:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFieldName:fieldTag:stringValue:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFieldName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fieldName"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fieldTag:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"fieldTag"},{"text":" ","kind":"text"},{"text":"stringValue:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"stringValue"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithFieldName:fieldTag:stringValue:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedField~1init(fieldName:fieldTag:stringValue:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithFieldName:fieldTag:stringValue:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedField~1init(fieldName:fieldTag:stringValue:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedField\/title","value":"SBSDKTIFFImageWriterUserDefinedField","op":"replace"},{"value":[{"text":"SBSDKTIFFImageWriterUserDefinedField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedField\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}