{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"barcodeTrackingOverlay:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKBarcodeTrackingOverlayController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController"},{"kind":"text","text":" *) "},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didTapOnBarcode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult","text":"SBSDKBarcodeScannerResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"barcode"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodetrackingoverlay:didtaponbarcode:"]}],"kind":"symbol","metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"barcodeTrackingOverlay:didTapOnBarcode:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"barcodeTrackingOverlay:didTapOnBarcode:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController(im)barcodeTrackingOverlay:didTapOnBarcode:","title":"barcodeTrackingOverlay:didTapOnBarcode:","role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeTrackingOverlay:didTapOnBarcode:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller","role":"symbol","deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"title":"SBSDKUIBarcodesBatchScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","type":"topic","abstract":[{"text":"A highly customizable camera-based view controller to detect barcodes batches.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult","title":"SBSDKBarcodeScannerResult","type":"topic","abstract":[{"type":"text","text":"This class encapsulates the result of a barcode detection."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController/barcodeTrackingOverlay:didTapOnBarcode:":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodetrackingoverlay:didtaponbarcode:","fragments":[{"kind":"text","text":"- "},{"text":"barcodeTrackingOverlay:didTapOnBarcode:","kind":"identifier"}],"type":"topic","title":"barcodeTrackingOverlay:didTapOnBarcode:","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeTrackingOverlay:didTapOnBarcode:","navigatorTitle":[{"text":"barcodeTrackingOverlay:didTapOnBarcode:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayController":{"title":"SBSDKBarcodeTrackingOverlayController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","abstract":[{"type":"text","text":"A class that represents an overlay used for visualizing detected barcodes."},{"type":"text","text":" "},{"text":"It provides a customizable user interface for displaying barcodes and supports interaction with them.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The overlay can be used to highlight and select barcodes based on user input."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUIBarcodesBatchScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"op":"replace"},{"value":"SBSDKBarcodeScannerResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/fragments","value":[{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/title","op":"replace","value":"SBSDKBarcodeTrackingOverlayController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}]}]}]}