{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodescannercontroller:diddetectbarcodes:"]}],"metadata":{"externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController(im)barcodeScannerController:didDetectBarcodes:","navigatorTitle":[{"kind":"identifier","text":"barcodeScannerController:didDetectBarcodes:"}],"role":"symbol","title":"barcodeScannerController:didDetectBarcodes:","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"text":"barcodeScannerController:didDetectBarcodes:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeScannerController:didDetectBarcodes:","interfaceLanguage":"occ"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"barcodeScannerController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"text":"didDetectBarcodes:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<SBSDKBarcodeScannerResult *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"codes","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to detect barcodes batches."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller","type":"topic","role":"symbol","title":"SBSDKUIBarcodesBatchScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller","title":"SBSDKBarcodeScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show a camera screen with the barcode detector."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController/barcodeScannerController:didDetectBarcodes:":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"barcodeScannerController:didDetectBarcodes:"}],"kind":"symbol","navigatorTitle":[{"text":"barcodeScannerController:didDetectBarcodes:","kind":"identifier"}],"title":"barcodeScannerController:didDetectBarcodes:","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodescannercontroller:diddetectbarcodes:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeScannerController:didDetectBarcodes:","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUIBarcodesBatchScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/title"},{"op":"replace","value":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/fragments"},{"value":"SBSDKBarcodeScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/title"},{"value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/fragments","op":"replace"}]}]}