{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataMapper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerMapping","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIBarcodesBatchScannerMapping","text":"SBSDKUIBarcodesBatchScannerMapping"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller\/datamapper"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller\/datamapper"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController\/dataMapper","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The mapper object, that conforms to the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerMapping"},{"type":"text","text":" protocol. Used to get additional info for barcodes."},{"type":"text","text":" "},{"type":"text","text":"Does not hold strong reference to the object. Can be "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"dataMapper"}],"role":"symbol","title":"dataMapper","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataMapper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIBarcodesBatchScannerMapping","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIBarcodesBatchScannerMapping"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController(py)dataMapper","modules":[{"name":"ScanbotSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController/dataMapper":{"deprecated":true,"role":"symbol","title":"dataMapper","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataMapper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIBarcodesBatchScannerMapping","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIBarcodesBatchScannerMapping"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The mapper object, that conforms to the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerMapping"},{"type":"text","text":" protocol. Used to get additional info for barcodes."},{"type":"text","text":" "},{"type":"text","text":"Does not hold strong reference to the object. Can be "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController\/dataMapper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dataMapper"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller\/datamapper"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController":{"deprecated":true,"role":"symbol","title":"SBSDKUIBarcodesBatchScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to detect barcodes batches."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerMapping":{"deprecated":true,"role":"symbol","title":"SBSDKUIBarcodesBatchScannerMapping","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerMapping"}],"abstract":[{"type":"text","text":"Protocol for the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController"},{"type":"text","text":" barcode results mapping."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerMapping","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerMapping"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannermapping"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"dataMapper"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dataMapper"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<SBSDKUIBarcodesBatchScannerMapping>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKUIBarcodesBatchScannerMapping"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dataMapper"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController~1dataMapper\/title","value":"dataMapper"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController~1dataMapper\/fragments","value":[{"kind":"identifier","text":"dataMapper"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/title","value":"SBSDKUIBarcodesBatchScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerMapping\/title","value":"SBSDKUIBarcodesBatchScannerMapping"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerMapping\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerMapping"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}