{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller\/unfreezecamera()"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller\/unfreezecamera()"],"traits":[{"interfaceLanguage":"occ"}]}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}],"type":"paragraph"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController\/unfreezeCamera()","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"unfreezeCamera()","roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController(im)unfreezeCamera","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unfreezeCamera"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"unfreezeCamera","kind":"identifier"}],"symbolKind":"method","platforms":[]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Unfreezes the previously frozen cameras preview layer by restarting the camera session.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unfreezeCamera"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController/unfreezeCamera()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unfreezeCamera"},{"kind":"text","text":"()"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller\/unfreezecamera()","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController\/unfreezeCamera()","title":"unfreezeCamera()","abstract":[{"type":"text","text":"Unfreezes the previously frozen cameras preview layer by restarting the camera session."}],"navigatorTitle":[{"kind":"identifier","text":"unfreezeCamera"}],"deprecated":true,"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController":{"deprecated":true,"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to detect barcodes batches."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller","title":"SBSDKUIBarcodesBatchScannerViewController","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"unfreezeCamera","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unfreezeCamera"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"unfreezeCamera"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController~1unfreezeCamera()\/title","op":"replace","value":"unfreezeCamera"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController~1unfreezeCamera()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unfreezeCamera"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/title","value":"SBSDKUIBarcodesBatchScannerViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/fragments","value":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}