{"metadata":{"roleHeading":"Type Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingConfiguration(cm)fromJsonWithJson:","title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"symbolKind":"method","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingConfiguration\/fromJsonWithJson:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingConfiguration","text":"SBSDKUI2CroppingConfiguration"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromJsonWithJson:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingconfiguration\/fromjsonwithjson:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingConfiguration":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the standalone cropping screen."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingConfiguration","navigatorTitle":[{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2CroppingConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingConfiguration/fromJsonWithJson:":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingconfiguration\/fromjsonwithjson:","title":"fromJsonWithJson:","abstract":[],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingConfiguration\/fromJsonWithJson:","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingConfiguration\/title","op":"replace","value":"SBSDKUI2CroppingConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}]}]}]}