{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementScreenConfiguration"]]},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2AcknowledgementScreenConfiguration(py)bottomBar","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"bottomBar","kind":"identifier"}],"title":"bottomBar","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bottomBar","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2AcknowledgementBottomBar","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"abstract":[{"text":"Configuration of the bottom bar for the acknowledgement screen.","type":"text"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomBar"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementBottomBar","text":"SBSDKUI2AcknowledgementBottomBar"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementScreenConfiguration\/bottomBar","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2acknowledgementscreenconfiguration\/bottombar"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2acknowledgementscreenconfiguration\/bottombar"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2AcknowledgementScreenConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementScreenConfiguration","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2acknowledgementscreenconfiguration","title":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AcknowledgementScreenConfiguration"}],"navigatorTitle":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the acknowledgement screen."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2AcknowledgementBottomBar":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2acknowledgementbottombar","title":"SBSDKUI2AcknowledgementBottomBar","abstract":[{"text":"Configuration of the bottom bar for the acknowledgement screen.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementBottomBar","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementBottomBar"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2AcknowledgementScreenConfiguration/bottomBar":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementScreenConfiguration\/bottomBar","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2acknowledgementscreenconfiguration\/bottombar","title":"bottomBar","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bottomBar","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar","text":"SBSDKUI2AcknowledgementBottomBar"}],"navigatorTitle":[{"kind":"identifier","text":"bottomBar"}],"abstract":[{"type":"text","text":"Configuration of the bottom bar for the acknowledgement screen."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"bottomBar"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"bottomBar"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementBottomBar","text":"SBSDKUI2AcknowledgementBottomBar"},{"text":" * ","kind":"text"},{"text":"bottomBar","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/title","op":"replace","value":"SBSDKUI2AcknowledgementScreenConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/fragments","value":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/navigatorTitle"},{"value":"SBSDKUI2AcknowledgementBottomBar","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementBottomBar\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementBottomBar"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementBottomBar\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementBottomBar\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementBottomBar"}]},{"value":"bottomBar","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementScreenConfiguration~1bottomBar\/title"},{"value":[{"text":"bottomBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementScreenConfiguration~1bottomBar\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}