{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/reviewScreenRetakeButtonTitle","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The ‘retake’ button title, located in the bottom bar of the review screen."}],"metadata":{"title":"reviewScreenRetakeButtonTitle","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reviewScreenRetakeButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization(py)reviewScreenRetakeButtonTitle","roleHeading":"Instance Property","navigatorTitle":[{"text":"reviewScreenRetakeButtonTitle","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/reviewscreenretakebuttontitle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/reviewscreenretakebuttontitle"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewScreenRetakeButtonTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Default is “Retake”"}],"type":"paragraph"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization":{"navigatorTitle":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization","title":"SBSDKUI2DocumentScannerTextLocalization","abstract":[{"type":"text","text":"Configuration of all the strings for the standalone cropping screen."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization/reviewScreenRetakeButtonTitle":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/reviewScreenRetakeButtonTitle","type":"topic","abstract":[{"type":"text","text":"The ‘retake’ button title, located in the bottom bar of the review screen."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reviewScreenRetakeButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"reviewScreenRetakeButtonTitle","kind":"identifier"}],"title":"reviewScreenRetakeButtonTitle","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/reviewscreenretakebuttontitle"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"reviewScreenRetakeButtonTitle","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"reviewScreenRetakeButtonTitle"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"reviewScreenRetakeButtonTitle","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2DocumentScannerTextLocalization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization~1reviewScreenRetakeButtonTitle\/title","value":"reviewScreenRetakeButtonTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization~1reviewScreenRetakeButtonTitle\/fragments","value":[{"text":"reviewScreenRetakeButtonTitle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}