{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithConfiguration:ocrConfiguration:useEncryptionIfAvailable:error:) "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration","text":"SBSDKPDFConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ocrConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration","text":"SBSDKOCREngineConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"useEncryptionIfAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The PDF generation configuration."}],"type":"paragraph"}],"name":"configuration"},{"content":[{"inlineContent":[{"type":"text","text":"The HOCR configuration. If ‘nil’ is passed, no HOCR will be performed."}],"type":"paragraph"}],"name":"ocrConfiguration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"type":"codeVoice","code":"true"},{"type":"text","text":" and a crypting provider is set in "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultCryptingProvider","type":"reference","isActive":true},{"type":"text","text":", the generated PDF will be encrypted."}]}],"name":"useEncryptionIfAvailable"}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"Creates a new instance of the PDF generator and configures it according to the specified configuration.","type":"text"}],"type":"paragraph"},{"name":"Throws","type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKError"},{"type":"text","text":" in case of an error."}]}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator"]]},"metadata":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration","kind":"typeIdentifier","text":"SBSDKPDFConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ocrConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration","kind":"typeIdentifier","text":"SBSDKOCREngineConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"useEncryptionIfAvailable"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:ocrConfiguration:useEncryptionIfAvailable:error:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFGenerator(im)initWithConfiguration:ocrConfiguration:useEncryptionIfAvailable:error:","symbolKind":"init","title":"init(configuration:ocrConfiguration:useEncryptionIfAvailable:)","roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/init(configuration:ocrConfiguration:useEncryptionIfAvailable:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Designated initializer.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/init(configuration:ocrconfiguration:useencryptionifavailable:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/init(configuration:ocrconfiguration:useencryptionifavailable:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFGenerator"}],"abstract":[{"text":"A class to generate an ordered collection of images with or without performing HOCR.","type":"text"}],"title":"SBSDKPDFGenerator","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFGenerator"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration","title":"SBSDKPDFConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The parameters "},{"code":"pageSize","type":"codeVoice"},{"type":"text","text":", "},{"code":"pageFit","type":"codeVoice"},{"type":"text","text":", "},{"code":"dpi","type":"codeVoice"},{"type":"text","text":" and "},{"code":"resamplingMethod","type":"codeVoice"},{"type":"text","text":" interact in a complex way"},{"type":"text","text":" "},{"type":"text","text":"when adding bitmap images (JPEG, PNG, or raw) to the PDF."},{"type":"text","text":" "},{"type":"text","text":"There are three cases to consider:"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/defaultCryptingProvider":{"type":"topic","title":"defaultCryptingProvider","abstract":[{"type":"text","text":"The SDK-wide encryption provider for storing image data to disk. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", no encryption used."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultCryptingProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingProvider","kind":"typeIdentifier","text":"SBSDKStorageCryptingProvider"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotsdk\/scanbot\/defaultcryptingprovider","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultCryptingProvider","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultCryptingProvider"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator/init(configuration:ocrConfiguration:useEncryptionIfAvailable:)":{"abstract":[{"text":"Designated initializer.","type":"text"}],"role":"symbol","type":"topic","title":"init(configuration:ocrConfiguration:useEncryptionIfAvailable:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPDFConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration"},{"text":", ","kind":"text"},{"text":"ocrConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKOCREngineConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration"},{"text":"?, ","kind":"text"},{"text":"useEncryptionIfAvailable","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"initWithConfiguration:ocrConfiguration:useEncryptionIfAvailable:error:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/init(configuration:ocrconfiguration:useencryptionifavailable:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/init(configuration:ocrConfiguration:useEncryptionIfAvailable:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration","kind":"symbol","title":"SBSDKOCREngineConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKOCREngineConfiguration","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCREngineConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"A class describing the configuration of the optical character recognizer (OCR) engine."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKError":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKError"}],"title":"SBSDKError","url":"\/documentation\/scanbotsdk\/sbsdkerror","abstract":[{"type":"text","text":"Represents errors that can occur within the Scanbot SDK."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKError","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKError"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithConfiguration:ocrConfiguration:useEncryptionIfAvailable:error:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:ocrConfiguration:useEncryptionIfAvailable:error:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration","text":"SBSDKPDFConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ocrConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration","text":"SBSDKOCREngineConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"ocrConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"useEncryptionIfAvailable:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"useEncryptionIfAvailable","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The PDF generation configuration.","type":"text"}]}],"name":"configuration"},{"content":[{"inlineContent":[{"text":"The HOCR configuration. If ‘nil’ is passed, no HOCR will be performed.","type":"text"}],"type":"paragraph"}],"name":"ocrConfiguration"},{"content":[{"type":"paragraph","inlineContent":[{"text":"If ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" and a crypting provider is set in ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultCryptingProvider"},{"text":", the generated PDF will be encrypted.","type":"text"}]}],"name":"useEncryptionIfAvailable"},{"content":[{"inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}],"type":"paragraph"}],"name":"error"}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/title","value":"SBSDKPDFGenerator","op":"replace"},{"op":"replace","value":[{"text":"SBSDKPDFGenerator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/fragments"},{"op":"replace","value":[{"text":"SBSDKPDFGenerator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/navigatorTitle"},{"op":"replace","value":"SBSDKPDFConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/navigatorTitle"},{"op":"replace","value":"defaultCryptingProvider","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1defaultCryptingProvider\/title"},{"op":"replace","value":[{"kind":"identifier","text":"defaultCryptingProvider"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1defaultCryptingProvider\/fragments"},{"op":"replace","value":"initWithConfiguration:ocrConfiguration:useEncryptionIfAvailable:error:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1init(configuration:ocrConfiguration:useEncryptionIfAvailable:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:ocrConfiguration:useEncryptionIfAvailable:error:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1init(configuration:ocrConfiguration:useEncryptionIfAvailable:)\/fragments"},{"op":"replace","value":"SBSDKOCREngineConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOCREngineConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOCREngineConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration\/navigatorTitle"}]}]}