{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/hash"]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/hash"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters(py)hash","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"hash","symbolKind":"property","role":"symbol","fragments":[{"kind":"identifier","text":"hash"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/hash":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/hash","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/hash","abstract":[],"title":"hash","kind":"symbol","fragments":[{"kind":"identifier","text":"hash"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters","abstract":[{"text":"TIFF generator parameters.","type":"text"}],"title":"SBSDKTIFFGeneratorParameters","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKTIFFGeneratorParameters","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/fragments"},{"op":"replace","value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/navigatorTitle"}]}]}