{"kind":"symbol","abstract":[{"text":"Detect the document contour in the given image.","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"runWithImage:error:"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScanner(im)runWithImage:error:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"run"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRef"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectionResult","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult"}],"symbolKind":"method","roleHeading":"Instance Method","title":"run(image:)","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"run","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult","text":"SBSDKDocumentDetectionResult"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"The image to detect the document contour in.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The detection result."}]}],"kind":"content"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKError","isActive":true},{"type":"text","text":" in case of an error."}],"type":"paragraph"}],"type":"aside","style":"note","name":"Throws"}],"kind":"content"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScanner\/run(image:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScanner"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscanner\/run(image:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscanner\/run(image:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScanner/run(image:)":{"abstract":[{"type":"text","text":"Detect the document contour in the given image."}],"title":"run(image:)","navigatorTitle":[{"text":"runWithImage:error:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"run","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRef","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScanner\/run(image:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscanner\/run(image:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRef":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRef"}],"kind":"symbol","abstract":[{"text":"Image ref class.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRef","title":"SBSDKImageRef","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRef"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageref"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScanner":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScanner"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscanner","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScanner","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScanner"}],"title":"SBSDKDocumentScanner","type":"topic","abstract":[{"type":"text","text":"API for document detection and scanning."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKError":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKError","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKError"}],"abstract":[{"type":"text","text":"Represents errors that can occur within the Scanbot SDK."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKError"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerror","title":"SBSDKError"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionResult":{"navigatorTitle":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult","abstract":[{"text":"Result of the document contour detection.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"title":"SBSDKDocumentDetectionResult","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"runWithImage:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"runWithImage:error:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult","kind":"typeIdentifier","text":"SBSDKDocumentDetectionResult","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"runWithImage:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRef","kind":"typeIdentifier","text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRef"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The image to detect the document contour in.","type":"text"}]}],"name":"image"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" for this parameter."}]}],"name":"error"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The detection result."},{"type":"text","text":" On failure, this method returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"runWithImage:error:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScanner~1run(image:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"runWithImage:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScanner~1run(image:)\/fragments"},{"op":"replace","value":"SBSDKImageRef","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRef\/title"},{"op":"replace","value":[{"text":"SBSDKImageRef","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRef\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRef"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRef\/navigatorTitle"},{"op":"replace","value":"SBSDKDocumentScanner","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScanner\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentScanner"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScanner\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScanner\/navigatorTitle"},{"op":"replace","value":"SBSDKDocumentDetectionResult","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/navigatorTitle"}]}]}