{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/totalscore"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/totalscore"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/totalScore","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalScore"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"totalScore"}],"roleHeading":"Instance Property","title":"totalScore","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionMetrics(py)totalScore"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"totalScore"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"The total score of the detected polygon (0 - 100).","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionMetrics"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDetectionMetrics"}],"type":"topic","abstract":[{"text":"The metrics and additional properties returned by ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"Can be used to make decisions on polygon acceptance, automatic capturing and user guidance."}],"title":"SBSDKDocumentDetectionMetrics","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 5.0.2","type":"text"}],"role":"collection","type":"topic","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics/totalScore":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/totalScore","title":"totalScore","kind":"symbol","navigatorTitle":[{"text":"totalScore","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"totalScore","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/totalscore","abstract":[{"text":"The total score of the detected polygon (0 - 100).","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetector":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"title":"SBSDKDocumentDetector","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetector"}],"abstract":[{"type":"text","text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"totalScore","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"totalScore","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"totalScore","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics\/title","value":"SBSDKDocumentDetectionMetrics"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDetectionMetrics","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1totalScore\/title","value":"totalScore"},{"op":"replace","value":[{"text":"totalScore","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1totalScore\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/title","op":"replace","value":"SBSDKDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/fragments","value":[{"text":"SBSDKDocumentDetector","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}