{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastName"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkidcardpdf417documentfieldtype\/lastname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkidcardpdf417documentfieldtype\/lastname"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIDCardPDF417DocumentFieldType\/lastName","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The last name."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastName"}],"title":"SBSDKIDCardPDF417DocumentFieldType.lastName","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKIDCardPDF417DocumentFieldType@SBSDKIDCardPDF417DocumentFieldTypeLastName","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeLastName"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIDCardPDF417DocumentFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIDCardPDF417DocumentFieldType":{"role":"symbol","title":"SBSDKIDCardPDF417DocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}],"abstract":[{"type":"text","text":"The ID card field types."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIDCardPDF417DocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkidcardpdf417documentfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.2"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIDCardPDF417DocumentFieldType/lastName":{"role":"symbol","title":"SBSDKIDCardPDF417DocumentFieldType.lastName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastName"}],"abstract":[{"type":"text","text":"The last name."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIDCardPDF417DocumentFieldType\/lastName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeLastName"}],"url":"\/documentation\/scanbotsdk\/sbsdkidcardpdf417documentfieldtype\/lastname"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKIDCardPDF417DocumentFieldTypeLastName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeLastName"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeLastName"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIDCardPDF417DocumentFieldType\/title","value":"SBSDKIDCardPDF417DocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIDCardPDF417DocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIDCardPDF417DocumentFieldType~1lastName\/title","value":"SBSDKIDCardPDF417DocumentFieldTypeLastName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIDCardPDF417DocumentFieldType~1lastName\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFieldTypeLastName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}