{"kind":"symbol","abstract":[{"text":"Defines how video frames, still images and the camera previer layer are flipped.","type":"text"}],"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration(py)videoFlipMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoFlipMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoFlipMode","kind":"typeIdentifier","text":"SBSDKVideoFlipMode"}],"navigatorTitle":[{"text":"videoFlipMode","kind":"identifier"}],"role":"symbol","title":"videoFlipMode","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","symbolKind":"property"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/videoFlipMode","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/videoflipmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/videoflipmode"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoFlipMode","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoFlipMode","text":"SBSDKVideoFlipMode","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode\/none","isActive":true,"type":"reference"},{"type":"text","text":"."}]}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"abstract":[{"text":"The general configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"}],"type":"topic","kind":"symbol","title":"SBSDKBaseScannerGeneralConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/videoFlipMode":{"abstract":[{"text":"Defines how video frames, still images and the camera previer layer are flipped.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/videoflipmode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoFlipMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoFlipMode","text":"SBSDKVideoFlipMode","kind":"typeIdentifier"}],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"videoFlipMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/videoFlipMode","title":"videoFlipMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFlipMode/none":{"url":"\/documentation\/scanbotsdk\/sbsdkvideoflipmode\/none","navigatorTitle":[{"text":"SBSDKVideoFlipModeNone","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode\/none","role":"symbol","kind":"symbol","title":"SBSDKVideoFlipMode.none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Do not flip the image."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFlipMode":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvideoflipmode","title":"SBSDKVideoFlipMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode","role":"symbol","navigatorTitle":[{"text":"SBSDKVideoFlipMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoFlipMode","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum describing how images can be flipped."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"videoFlipMode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"videoFlipMode","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoFlipMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoFlipMode","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"videoFlipMode","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/title","op":"replace","value":"SBSDKBaseScannerGeneralConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1videoFlipMode\/title","op":"replace","value":"videoFlipMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1videoFlipMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"videoFlipMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode~1none\/title","op":"replace","value":"SBSDKVideoFlipModeNone"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode~1none\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFlipModeNone"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode\/title","op":"replace","value":"SBSDKVideoFlipMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode\/fragments","op":"replace","value":[{"text":"SBSDKVideoFlipMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFlipMode"}]}]}]}