{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller\/attach(parentviewcontroller:parentview:)"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller\/attach(parentviewcontroller:parentview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"attach","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentViewController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"parentView"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The UIViewController that the receiver will be embedded into."}]}],"name":"parentViewController"},{"name":"parentView","content":[{"type":"paragraph","inlineContent":[{"text":"The UIView that holds and layouts the receivers view.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"True","type":"codeVoice"},{"text":", if embedding the receiver was successful, ","type":"text"},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise."}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController\/attach(parentViewController:parentView:)"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"attachWithParentViewController:parentView:"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"attach(parentViewController:parentView:)","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerViewController(im)attachWithParentViewController:parentView:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attach","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parentViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"text":"parentView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"abstract":[{"type":"text","text":"Embeds the receiver as a child view controller of the parent view controller."},{"type":"text","text":" "},{"type":"text","text":"The scanner controller view is added to the parent view, which must be an adjacent view of the receivers view."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewController":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"title":"SBSDKBaseScannerViewController","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"abstract":[{"type":"text","text":"A highly customizable camera view controller that delivers a basic camera functionality along with video"},{"type":"text","text":" "},{"type":"text","text":"frame extraction and preprocessing, orientation correction and still image capturing."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewController/attach(parentViewController:parentView:)":{"title":"attach(parentViewController:parentView:)","abstract":[{"type":"text","text":"Embeds the receiver as a child view controller of the parent view controller."},{"type":"text","text":" "},{"type":"text","text":"The scanner controller view is added to the parent view, which must be an adjacent view of the receivers view."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller\/attach(parentviewcontroller:parentview:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController\/attach(parentViewController:parentView:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attach","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parentViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"parentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"attachWithParentViewController:parentView:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"attachWithParentViewController:parentView:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"attachWithParentViewController:parentView:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"attachWithParentViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":" *) ","kind":"text"},{"text":"parentViewController","kind":"internalParam"},{"kind":"text","text":" "},{"text":"parentView:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"parentView"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"parentViewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The UIViewController that the receiver will be embedded into."}]}]},{"name":"parentView","content":[{"type":"paragraph","inlineContent":[{"text":"The UIView that holds and layouts the receivers view.","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":""},{"code":"True","type":"codeVoice"},{"text":", if embedding the receiver was successful, ","type":"text"},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/title","op":"replace","value":"SBSDKBaseScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController~1attach(parentViewController:parentView:)\/title","value":"attachWithParentViewController:parentView:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController~1attach(parentViewController:parentView:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"attachWithParentViewController:parentView:","kind":"identifier"}],"op":"replace"}]}]}