{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController\/captureStillImageWithCompletionHandler(completion:)","interfaceLanguage":"swift"},"abstract":[{"text":"Captures a still image asynchronously and passes either the UIImage or an error to the completion handler.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller\/capturestillimagewithcompletionhandler(completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller\/capturestillimagewithcompletionhandler(completion:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"metadata":{"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerViewController(im)captureStillImageWithCompletionHandler:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"captureStillImageWithCompletionHandler","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> ())?)"}],"roleHeading":"Instance Method","title":"captureStillImageWithCompletionHandler(completion:)","navigatorTitle":[{"text":"captureStillImageWithCompletionHandler:","kind":"identifier"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(captureStillImageWithCompletionHandler:) ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"captureStillImageWithCompletionHandler"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ())?)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handler that is called when the still image has been captured."}]}],"name":"completion"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewController":{"abstract":[{"type":"text","text":"A highly customizable camera view controller that delivers a basic camera functionality along with video"},{"type":"text","text":" "},{"type":"text","text":"frame extraction and preprocessing, orientation correction and still image capturing."}],"navigatorTitle":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"title":"SBSDKBaseScannerViewController","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.1"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewController/captureStillImageWithCompletionHandler(completion:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController\/captureStillImageWithCompletionHandler(completion:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"captureStillImageWithCompletionHandler:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller\/capturestillimagewithcompletionhandler(completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureStillImageWithCompletionHandler"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ())?)","kind":"text"}],"kind":"symbol","abstract":[{"text":"Captures a still image asynchronously and passes either the UIImage or an error to the completion handler.","type":"text"}],"title":"captureStillImageWithCompletionHandler(completion:)","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"captureStillImageWithCompletionHandler:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"captureStillImageWithCompletionHandler:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"captureStillImageWithCompletionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"The completion handler that is called when the still image has been captured.","type":"text"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/title","value":"SBSDKBaseScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/navigatorTitle","value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController~1captureStillImageWithCompletionHandler(completion:)\/title","value":"captureStillImageWithCompletionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController~1captureStillImageWithCompletionHandler(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureStillImageWithCompletionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}