{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller\/energyconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller\/energyconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The energy configuration of the receiver. Lets you enable and customize the energy management."},{"text":" ","type":"text"},{"type":"text","text":"It is copied on setting, so mutating the configuration after setting will not change the behavior."},{"text":" ","type":"text"},{"type":"text","text":"Instead, re-configure your instance and set it again."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController"]]},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerViewController(py)energyConfiguration","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"energyConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration","text":"SBSDKBaseScannerEnergyConfiguration"}],"navigatorTitle":[{"text":"energyConfiguration","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Property","title":"energyConfiguration"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"energyConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKBaseScannerEnergyConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerEnergyConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController\/energyConfiguration"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewController/energyConfiguration":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The energy configuration of the receiver. Lets you enable and customize the energy management."},{"type":"text","text":" "},{"text":"It is copied on setting, so mutating the configuration after setting will not change the behavior.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Instead, re-configure your instance and set it again."}],"title":"energyConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController\/energyConfiguration","navigatorTitle":[{"kind":"identifier","text":"energyConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller\/energyconfiguration","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"energyConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration","text":"SBSDKBaseScannerEnergyConfiguration","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"abstract":[{"text":"A highly customizable camera view controller that delivers a basic camera functionality along with video","type":"text"},{"text":" ","type":"text"},{"text":"frame extraction and preprocessing, orientation correction and still image capturing.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController","title":"SBSDKBaseScannerViewController"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerEnergyConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerEnergyConfiguration","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The energy management configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"type":"text","text":" "},{"type":"text","text":"‘SBSDKBaseScannerViewController’ and subclasses sport a customizable energy management system."},{"type":"text","text":" "},{"text":"Since detectors and recognizers running on a live video feed can put a lot of load onto the CPU and\/or GPU","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"of the device, causing the battery to drain quickly and running the device hot, you can customize the energy"},{"text":" ","type":"text"},{"text":"consumption using this class by configuring the rate of detections\/recognitions per second in performance mode as","type":"text"},{"type":"text","text":" "},{"type":"text","text":"well as in energy saving mode."},{"type":"text","text":" "},{"type":"text","text":"In performance mode the detectors\/recognizers will be fed with a higher, configurable rate of"},{"text":" ","type":"text"},{"type":"text","text":"video frames per second."},{"type":"text","text":" "},{"type":"text","text":"After a certain, configurable period of inactivity the energy save mode will be engaged and the rate"},{"type":"text","text":" "},{"type":"text","text":"of detections\/recognitions will be reduced to a lower (configurable) rate."},{"text":" ","type":"text"},{"type":"text","text":"You can also configure the time of inactivity before the automatic mode switches from performance to energy save mode."},{"type":"text","text":" "},{"text":"Inactivity here means that both of the following conditions are met:","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerenergyconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"title":"SBSDKBaseScannerEnergyConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"energyConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"energyConfiguration","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerEnergyConfiguration","text":"SBSDKBaseScannerEnergyConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"energyConfiguration"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"energyConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController~1energyConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController~1energyConfiguration\/fragments","value":[{"text":"energyConfiguration","kind":"identifier"}]},{"value":"SBSDKBaseScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/fragments","value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/title","value":"SBSDKBaseScannerEnergyConfiguration","op":"replace"},{"value":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}