{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"title":"frameDidProcessHandler","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerViewController(py)frameDidProcessHandler","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"frameDidProcessHandler","kind":"identifier"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPerformanceMetrics","text":"SBSDKPerformanceMetrics","kind":"typeIdentifier"},{"kind":"text","text":") -> ())?"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"frameDidProcessHandler"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController\/frameDidProcessHandler","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A block being called after a frame has been processed. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Is called on the main thread.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller\/framedidprocesshandler"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller\/framedidprocesshandler"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"frameDidProcessHandler","kind":"identifier"},{"kind":"text","text":": (("},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPerformanceMetrics","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPerformanceMetrics","kind":"typeIdentifier","text":"SBSDKPerformanceMetrics"},{"kind":"text","text":") -> ())?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPerformanceMetrics":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPerformanceMetrics","navigatorTitle":[{"text":"SBSDKPerformanceMetrics","kind":"identifier"}],"abstract":[{"type":"text","text":"A class that provides performance metrics for a frame processing operation."}],"title":"SBSDKPerformanceMetrics","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkperformancemetrics","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPerformanceMetrics"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewController/frameDidProcessHandler":{"abstract":[{"type":"text","text":"A block being called after a frame has been processed. Defaults to "},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Is called on the main thread."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"frameDidProcessHandler","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"SBSDKPerformanceMetrics","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPerformanceMetrics","kind":"typeIdentifier"},{"kind":"text","text":") -> ())?"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController\/frameDidProcessHandler","type":"topic","title":"frameDidProcessHandler","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller\/framedidprocesshandler","kind":"symbol","navigatorTitle":[{"text":"frameDidProcessHandler","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewController":{"abstract":[{"type":"text","text":"A highly customizable camera view controller that delivers a basic camera functionality along with video"},{"text":" ","type":"text"},{"type":"text","text":"frame extraction and preprocessing, orientation correction and still image capturing."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewcontroller","title":"SBSDKBaseScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewController","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"frameDidProcessHandler","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"frameDidProcessHandler"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^"},{"kind":"identifier","text":"frameDidProcessHandler"},{"kind":"text","text":")("},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPerformanceMetrics","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPerformanceMetrics","kind":"typeIdentifier","text":"SBSDKPerformanceMetrics"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":");","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPerformanceMetrics\/title","op":"replace","value":"SBSDKPerformanceMetrics"},{"value":[{"kind":"identifier","text":"SBSDKPerformanceMetrics"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPerformanceMetrics\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPerformanceMetrics\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPerformanceMetrics","kind":"identifier"}]},{"value":"frameDidProcessHandler","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController~1frameDidProcessHandler\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController~1frameDidProcessHandler\/fragments","value":[{"kind":"identifier","text":"frameDidProcessHandler"}]},{"value":"SBSDKBaseScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}]},{"value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewController\/navigatorTitle"}]}]}