{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotateButtonAccessibilityLabel"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenAccessibilityConfiguration(py)rotateButtonAccessibilityLabel","navigatorTitle":[{"text":"rotateButtonAccessibilityLabel","kind":"identifier"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"rotateButtonAccessibilityLabel","modules":[{"name":"ScanbotDocumentScannerSDK"}],"platforms":[]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotateButtonAccessibilityLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Defaults to “Rotate”."}],"type":"paragraph"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/rotateButtonAccessibilityLabel","interfaceLanguage":"swift"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2CroppingViewController instead."}]}],"kind":"symbol","abstract":[{"type":"text","text":"Text, that is used as an accessibility label for the rotate button."}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/rotatebuttonaccessibilitylabel"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/rotatebuttonaccessibilitylabel"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenAccessibilityConfiguration"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.1.1","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenAccessibilityConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenAccessibilityConfiguration","navigatorTitle":[{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration for the accessibility labels and hints."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenaccessibilityconfiguration","deprecated":true,"role":"symbol","title":"SBSDKUICroppingScreenAccessibilityConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenAccessibilityConfiguration/rotateButtonAccessibilityLabel":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rotateButtonAccessibilityLabel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/rotateButtonAccessibilityLabel","navigatorTitle":[{"text":"rotateButtonAccessibilityLabel","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Text, that is used as an accessibility label for the rotate button.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/rotatebuttonaccessibilitylabel","deprecated":true,"role":"symbol","title":"rotateButtonAccessibilityLabel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"rotateButtonAccessibilityLabel","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"rotateButtonAccessibilityLabel","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"rotateButtonAccessibilityLabel"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":"SBSDKUICroppingScreenAccessibilityConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenAccessibilityConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenAccessibilityConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenAccessibilityConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1rotateButtonAccessibilityLabel\/title","op":"replace","value":"rotateButtonAccessibilityLabel"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1rotateButtonAccessibilityLabel\/fragments","value":[{"text":"rotateButtonAccessibilityLabel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}