{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView"]]},"abstract":[{"text":"The current rect of the finders viewport in the local coordinate system.","type":"text"}],"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"finderRect"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"finderRect","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"roleHeading":"Instance Property","title":"finderRect","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView(py)finderRect"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/finderRect"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderRect","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Returns ","type":"text"},{"code":"CGRect.zero","type":"codeVoice"},{"text":" if the viewport is disabled.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfinderview\/finderrect"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkfinderview\/finderrect"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/finderRect":{"title":"finderRect","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"finderRect","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"}],"navigatorTitle":[{"text":"finderRect","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/finderRect","kind":"symbol","abstract":[{"type":"text","text":"The current rect of the finders viewport in the local coordinate system."}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/finderrect","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKFinderView"}],"kind":"symbol","title":"SBSDKFinderView","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","abstract":[{"text":"A ","type":"text"},{"code":"UIView","type":"codeVoice"},{"type":"text","text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio."}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"finderRect"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"finderRect"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":" ","kind":"text"},{"text":"finderRect","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"finderRect","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1finderRect\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1finderRect\/fragments","value":[{"text":"finderRect","kind":"identifier"}]},{"op":"replace","value":"SBSDKFinderView","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/fragments","op":"replace","value":[{"text":"SBSDKFinderView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFinderView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}