{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanner\/scan(from:orientation:parameters:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanner(im)scanFromSampleBuffer:orientation:parameters:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"scanFromSampleBuffer:orientation:parameters:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKVideoOrientation","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation"},{"text":", ","kind":"text"},{"text":"parameters","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningParameters","text":"SBSDKMedicalCertificateScanningParameters"},{"kind":"text","text":") -> "},{"text":"SBSDKMedicalCertificateScanningResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult"},{"text":"?","kind":"text"}],"title":"scan(from:orientation:parameters:)","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(scanFromSampleBuffer:orientation:parameters:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sampleBuffer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"kind":"text","text":", "},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKVideoOrientation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation"},{"text":", ","kind":"text"},{"text":"parameters","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningParameters","kind":"typeIdentifier","text":"SBSDKMedicalCertificateScanningParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningParameters"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult","text":"SBSDKMedicalCertificateScanningResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"sampleBuffer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The sample buffer to scan from."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The orientation of the sample buffer."}],"type":"paragraph"}],"name":"orientation"},{"name":"parameters","content":[{"inlineContent":[{"text":"The parameters to perform the scan with.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The scan result."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanner\/scan(from:orientation:parameters:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanner\/scan(from:orientation:parameters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Scans medical certificates on a "},{"code":"CMSampleBuffer","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanner"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoOrientation"}],"role":"symbol","abstract":[{"type":"text","text":"An enum describing the orientation of a video frame."}],"title":"SBSDKVideoOrientation","navigatorTitle":[{"text":"SBSDKVideoOrientation","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanner":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanner","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanner","role":"symbol","abstract":[{"type":"text","text":"A class to scan medical certificates on various image sources."}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateScanner","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateScanner"}],"type":"topic","title":"SBSDKMedicalCertificateScanner"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanningParameters":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningParameters","abstract":[{"text":"Parameters for the medical certificate scanning. The scanner supports","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Form 1 (Arbeitsunfähigkeitsbescheinigung) and"},{"type":"text","text":" "},{"type":"text","text":"Form 21a (Ärztliche Bescheinigung für den Bezug von Krankengeld bei Erkrankung eines Kindes)"},{"type":"text","text":" "},{"type":"text","text":"from the KBV (Kassenärztliche Bundesvereinigung) list of forms."}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningparameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKMedicalCertificateScanningParameters","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateScanningParameters","kind":"identifier"}],"type":"topic","title":"SBSDKMedicalCertificateScanningParameters"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanningResult":{"title":"SBSDKMedicalCertificateScanningResult","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}],"abstract":[{"text":"The result of the medical certificate scanning.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanner/scan(from:orientation:parameters:)":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanner\/scan(from:orientation:parameters:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scan"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation","text":"SBSDKVideoOrientation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"parameters"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningParameters","text":"SBSDKMedicalCertificateScanningParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKMedicalCertificateScanningResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"scanFromSampleBuffer:orientation:parameters:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanner\/scan(from:orientation:parameters:)","abstract":[{"text":"Scans medical certificates on a ","type":"text"},{"code":"CMSampleBuffer","type":"codeVoice"},{"text":".","type":"text"}],"title":"scan(from:orientation:parameters:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"scanFromSampleBuffer:orientation:parameters:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scanFromSampleBuffer:orientation:parameters:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"SBSDKMedicalCertificateScanningResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"scanFromSampleBuffer:"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@opaqueCMSampleBuffer","text":"opaqueCMSampleBuffer"},{"kind":"text","text":" *) "},{"text":"sampleBuffer","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation"},{"kind":"text","text":") "},{"text":"orientation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"parameters:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKMedicalCertificateScanningParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningParameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningParameters"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"parameters"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The sample buffer to scan from."}],"type":"paragraph"}],"name":"sampleBuffer"},{"content":[{"inlineContent":[{"type":"text","text":"The orientation of the sample buffer."}],"type":"paragraph"}],"name":"orientation"},{"name":"parameters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The parameters to perform the scan with."}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/primaryContentSections\/2","value":{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The scan result."}]}],"kind":"content"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/title","value":"SBSDKVideoOrientation","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}]},{"op":"replace","value":"SBSDKMedicalCertificateScanner","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanner\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanner\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScanner"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanner\/navigatorTitle","op":"replace","value":[{"text":"SBSDKMedicalCertificateScanner","kind":"identifier"}]},{"value":"SBSDKMedicalCertificateScanningParameters","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningParameters\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningParameters\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScanningParameters"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningParameters\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScanningParameters"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/title","op":"replace","value":"SBSDKMedicalCertificateScanningResult"},{"value":[{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScanningResult"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanner~1scan(from:orientation:parameters:)\/title","value":"scanFromSampleBuffer:orientation:parameters:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"scanFromSampleBuffer:orientation:parameters:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanner~1scan(from:orientation:parameters:)\/fragments","op":"replace"}]}]}