{"abstract":[{"text":"Determines the prioritization of still image quality and capturing speed.","type":"text"},{"text":" ","type":"text"},{"text":"Default is BALANCED","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerCameraConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercameraconfiguration\/capturequalityprioritization"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercameraconfiguration\/capturequalityprioritization"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureQualityPrioritization","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"captureQualityPrioritization","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","title":"captureQualityPrioritization","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration(py)captureQualityPrioritization"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureQualityPrioritization","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CapturePhotoQualityPrioritization"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerCameraConfiguration\/captureQualityPrioritization","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerCameraConfiguration/captureQualityPrioritization":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerCameraConfiguration\/captureQualityPrioritization","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureQualityPrioritization","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Determines the prioritization of still image quality and capturing speed."},{"type":"text","text":" "},{"type":"text","text":"Default is BALANCED"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercameraconfiguration\/capturequalityprioritization","title":"captureQualityPrioritization","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"captureQualityPrioritization","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CapturePhotoQualityPrioritization":{"role":"symbol","title":"SBSDKUI2CapturePhotoQualityPrioritization","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturephotoqualityprioritization","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"abstract":[{"type":"text","text":"Determines the prioritization of still image quality and capturing speed."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerCameraConfiguration":{"abstract":[{"text":"Configuration of the camera behavior.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerCameraConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerCameraConfiguration"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercameraconfiguration","role":"symbol","title":"SBSDKUI2DocumentScannerCameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerCameraConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"captureQualityPrioritization"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"captureQualityPrioritization","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization","text":"SBSDKUI2CapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CapturePhotoQualityPrioritization"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureQualityPrioritization"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerCameraConfiguration~1captureQualityPrioritization\/title","value":"captureQualityPrioritization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerCameraConfiguration~1captureQualityPrioritization\/fragments","value":[{"text":"captureQualityPrioritization","kind":"identifier"}]},{"op":"replace","value":"SBSDKUI2CapturePhotoQualityPrioritization","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/title"},{"op":"replace","value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2DocumentScannerCameraConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerCameraConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}