{"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"dateRecordType"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerDateResult(py)dateRecordType","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dateRecordType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerDateResultType","text":"SBSDKMedicalCertificateRecognizerDateResultType","kind":"typeIdentifier"}],"title":"dateRecordType"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateRecordType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType","text":"SBSDKMedicalCertificateRecognizerDateResultType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerDateResultType"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResult\/dateRecordType","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResult"]]},"abstract":[{"text":"The type of the date record.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresult\/daterecordtype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresult\/daterecordtype"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResult/dateRecordType":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateRecordType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerDateResultType","text":"SBSDKMedicalCertificateRecognizerDateResultType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResult\/dateRecordType","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresult\/daterecordtype","navigatorTitle":[{"text":"dateRecordType","kind":"identifier"}],"abstract":[{"text":"The type of the date record.","type":"text"}],"title":"dateRecordType","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResult":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResult"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResult","kind":"symbol","abstract":[{"text":"Class contains date information retrieved by medical certificates recognizer.","type":"text"}],"title":"SBSDKMedicalCertificateRecognizerDateResult","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerDateResult","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultType"}],"abstract":[{"text":"Type classifiers for dates recognized on medical certificates.","type":"text"}],"type":"topic","kind":"symbol","title":"SBSDKMedicalCertificateRecognizerDateResultType","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerDateResultType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"dateRecordType","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dateRecordType"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType","text":"SBSDKMedicalCertificateRecognizerDateResultType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerDateResultType"},{"kind":"text","text":" "},{"text":"dateRecordType","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResult~1dateRecordType\/title","value":"dateRecordType"},{"op":"replace","value":[{"text":"dateRecordType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResult~1dateRecordType\/fragments"},{"value":"SBSDKMedicalCertificateRecognizerDateResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResult\/title","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateRecognizerDateResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResult\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType\/title","op":"replace","value":"SBSDKMedicalCertificateRecognizerDateResultType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultType"}]}]}]}