{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraBottomBar\/init(importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"importButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2BarButtonConfiguration(title: SBSDKUI2StyledText(visible: false,\n                                                                 text: \"?cameraImportButtonTitle\",\n                                                                 color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                      isArgb: false)),\n                                       accessibilityDescription: \"?accessibilityDescriptionCameraImportButton\",\n                                       background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                      isArgb: false),\n                                                                           fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                    isArgb: false),\n                                                                           strokeWidth: 0.0),\n                                       icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                    isArgb: false))), "},{"kind":"externalParam","text":"autoSnappingModeButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" = SBSDKUI2BarButtonConfiguration(title: SBSDKUI2StyledText(visible: false, text: \"?cameraAutoSnapButtonTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)),\n                                           accessibilityDescription: \"?accessibilityDescriptionCameraAutoSnapButton\",\n                                           background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                          isArgb: false),\n                                                                               fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                        isArgb: false),\n                                                                               strokeWidth: 0.0),\n                                           icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                        isArgb: false))), ","kind":"text"},{"text":"manualSnappingModeButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":" = SBSDKUI2BarButtonConfiguration(title: SBSDKUI2StyledText(visible: false,\n                                                                     text: \"?cameraManualSnapButtonTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)),\n                                           accessibilityDescription: \"?accessibilityDescriptionCameraManualSnapButton\",\n                                           background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                          isArgb: false),\n                                                                               fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                        isArgb: false),\n                                                                               strokeWidth: 0.0),\n                                           icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                        isArgb: false))), "},{"text":"shutterButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ShutterButton","text":"SBSDKUI2ShutterButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ShutterButton"},{"kind":"text","text":" = SBSDKUI2ShutterButton(accessibilityDescription: \"?accessibilityDescriptionCameraShutterButton\"), "},{"text":"torchOnButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":" = SBSDKUI2BarButtonConfiguration(title: SBSDKUI2StyledText(visible: false, text: \"?cameraTorchOnButtonTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)),\n                                           accessibilityDescription: \"?accessibilityDescriptionCameraTorchOnButton\",\n                                           background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                          isArgb: false),\n                                                                               fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                        isArgb: false),\n                                                                               strokeWidth: 0.0),\n                                           icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                        isArgb: false))), "},{"text":"torchOffButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"text":" = SBSDKUI2BarButtonConfiguration(title: SBSDKUI2StyledText(visible: false, text: \"?cameraTorchOffButtonTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)),\n                                           accessibilityDescription: \"?accessibilityDescriptionCameraTorchOffButton\",\n                                           background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                          isArgb: false),\n                                                                               fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                        isArgb: false),\n                                                                               strokeWidth: 0.0),\n                                           icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                        isArgb: false))), ","kind":"text"},{"text":"previewButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PreviewButton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PreviewButton","text":"SBSDKUI2PreviewButton","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2PagePreviewMode())"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraBottomBar"]]},"metadata":{"symbolKind":"init","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CameraBottomBar(im)initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","roleHeading":"Initializer","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","kind":"identifier"}],"title":"init(importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"importButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":", "},{"text":"autoSnappingModeButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":", "},{"text":"manualSnappingModeButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration"},{"text":", ","kind":"text"},{"text":"shutterButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ShutterButton","kind":"typeIdentifier","text":"SBSDKUI2ShutterButton"},{"kind":"text","text":", "},{"text":"torchOnButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":", "},{"text":"torchOffButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":", "},{"text":"previewButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PreviewButton","text":"SBSDKUI2PreviewButton"},{"kind":"text","text":")"}]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerabottombar\/init(importbutton:autosnappingmodebutton:manualsnappingmodebutton:shutterbutton:torchonbutton:torchoffbutton:previewbutton:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerabottombar\/init(importbutton:autosnappingmodebutton:manualsnappingmodebutton:shutterbutton:torchonbutton:torchoffbutton:previewbutton:)"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PreviewButton":{"type":"topic","title":"SBSDKUI2PreviewButton","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2previewbutton","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PreviewButton","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2PreviewButton"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PreviewButton"}],"abstract":[{"type":"text","text":"Configuration of the ‘preview’ button."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraBottomBar/init(importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"importButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"autoSnappingModeButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":", "},{"text":"manualSnappingModeButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":", "},{"text":"shutterButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2ShutterButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ShutterButton","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"torchOnButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":", ","kind":"text"},{"text":"torchOffButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":", "},{"text":"previewButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2PreviewButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PreviewButton"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraBottomBar\/init(importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:)","role":"symbol","navigatorTitle":[{"text":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","kind":"identifier"}],"type":"topic","title":"init(importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:)","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerabottombar\/init(importbutton:autosnappingmodebutton:manualsnappingmodebutton:shutterbutton:torchonbutton:torchoffbutton:previewbutton:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraBottomBar":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the bottom bar for the camera screen."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerabottombar","title":"SBSDKUI2CameraBottomBar","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraBottomBar"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2BarButtonConfiguration":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2barbuttonconfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"role":"symbol","title":"SBSDKUI2BarButtonConfiguration","kind":"symbol","abstract":[{"text":"Button configuration.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ShutterButton":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2ShutterButton","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the ‘shutter’ button."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ShutterButton","title":"SBSDKUI2ShutterButton","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2shutterbutton","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ShutterButton"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithImportButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"importButton"},{"text":" ","kind":"text"},{"text":"autoSnappingModeButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"autoSnappingModeButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"manualSnappingModeButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"manualSnappingModeButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutterButton:"},{"kind":"text","text":"("},{"text":"SBSDKUI2ShutterButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ShutterButton","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ShutterButton"},{"text":" *) ","kind":"text"},{"text":"shutterButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"torchOnButton:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"torchOnButton"},{"text":" ","kind":"text"},{"kind":"identifier","text":"torchOffButton:"},{"kind":"text","text":"("},{"text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"torchOffButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"previewButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2PreviewButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PreviewButton","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PreviewButton"},{"kind":"text","text":" *) "},{"text":"previewButton","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKUI2PreviewButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PreviewButton\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PreviewButton\/fragments","op":"replace","value":[{"text":"SBSDKUI2PreviewButton","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2PreviewButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PreviewButton\/navigatorTitle"},{"value":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraBottomBar~1init(importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraBottomBar~1init(importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraBottomBar\/title","value":"SBSDKUI2CameraBottomBar"},{"value":[{"text":"SBSDKUI2CameraBottomBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraBottomBar\/fragments"},{"value":[{"text":"SBSDKUI2CameraBottomBar","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraBottomBar\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BarButtonConfiguration\/title","op":"replace","value":"SBSDKUI2BarButtonConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BarButtonConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BarButtonConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2ShutterButton","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ShutterButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ShutterButton\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ShutterButton"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ShutterButton\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ShutterButton"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}