{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraBottomBar\/isEqual:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerabottombar\/isequal:"]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"isEqual:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraBottomBar"]]},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CameraBottomBar(im)isEqual:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual:","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraBottomBar/isEqual:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraBottomBar\/isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerabottombar\/isequal:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraBottomBar":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerabottombar","type":"topic","abstract":[{"text":"Configuration of the bottom bar for the camera screen.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"title":"SBSDKUI2CameraBottomBar","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraBottomBar","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraBottomBar\/title","op":"replace","value":"SBSDKUI2CameraBottomBar"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraBottomBar\/fragments","op":"replace","value":[{"text":"SBSDKUI2CameraBottomBar","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2CameraBottomBar","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraBottomBar\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}