{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod10"},"sections":[],"kind":"symbol","metadata":{"title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod10","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mod10","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeMSIPlesseyChecksumAlgorithm@SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10"}],"role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm"]]},"abstract":[{"text":"Mod10.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mod10","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod10"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod10"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The checksum algorithm for MSI-Plessey type barcodes."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod10":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mod10","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Mod10."}],"type":"topic","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod10","url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod10","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod10","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/title","op":"replace","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"},{"value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod10\/title","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10","op":"replace"},{"value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod10\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}