{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerparameters\/aspectratios"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerparameters\/aspectratios"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"aspectRatios"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio","kind":"typeIdentifier","text":"SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"The possible desired aspect ratios for the detected document.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"A document matches if its aspect ratio matches any of the given aspect ratios."},{"type":"text","text":" "},{"type":"text","text":"If acceptedAspectRatioScore is more than 0, then the document is only accepted if the aspect ratio"},{"type":"text","text":" "},{"type":"text","text":"matches one of the given aspect ratios, otherwise OK_BUT_BAD_ASPECT_RATIO is returned."},{"type":"text","text":" "},{"type":"text","text":"If empty, no aspect ratio is preferred."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerParameters"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerParameters\/aspectRatios","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"aspectRatios","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aspectRatios","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio","text":"SBSDKAspectRatio","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"aspectRatios","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerParameters(py)aspectRatios"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerParameters/aspectRatios":{"abstract":[{"type":"text","text":"The possible desired aspect ratios for the detected document."},{"type":"text","text":" "},{"type":"text","text":"A document matches if its aspect ratio matches any of the given aspect ratios."},{"type":"text","text":" "},{"type":"text","text":"If acceptedAspectRatioScore is more than 0, then the document is only accepted if the aspect ratio"},{"type":"text","text":" "},{"type":"text","text":"matches one of the given aspect ratios, otherwise OK_BUT_BAD_ASPECT_RATIO is returned."},{"type":"text","text":" "},{"type":"text","text":"If empty, no aspect ratio is preferred."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"aspectRatios"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio"},{"kind":"text","text":">"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"aspectRatios"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerParameters\/aspectRatios","title":"aspectRatios","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerparameters\/aspectratios"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerParameters":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerParameters","type":"topic","title":"SBSDKDocumentScannerParameters","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerparameters","navigatorTitle":[{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"abstract":[{"type":"text","text":"Parameters for the document scanner."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAspectRatio":{"abstract":[{"text":"Aspect ratio is the ratio of the width to the height of an image or screen.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaspectratio","title":"SBSDKAspectRatio","navigatorTitle":[{"text":"SBSDKAspectRatio","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAspectRatio","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"aspectRatios","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"aspectRatios"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<SBSDKAspectRatio *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"aspectRatios","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerParameters~1aspectRatios\/title","value":"aspectRatios","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerParameters~1aspectRatios\/fragments","value":[{"kind":"identifier","text":"aspectRatios"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerParameters\/title","value":"SBSDKDocumentScannerParameters","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerParameters\/fragments","value":[{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerParameters\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentScannerParameters"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio\/title","value":"SBSDKAspectRatio"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKAspectRatio"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKAspectRatio"}]}]}]}