{"metadata":{"title":"outputMode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"outputMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKOutputMode","text":"SBSDKOutputMode","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"outputMode","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScanbotBinarizationFilter(py)outputMode","symbolKind":"property","role":"symbol","roleHeading":"Instance Property"},"abstract":[{"text":"Output mode of the filter. BINARY will return a black and white image, GRAYSCALE will return an antialiased","type":"text"},{"text":" ","type":"text"},{"text":"grayscale image.","type":"text"},{"text":" ","type":"text"},{"text":"Default is BINARY","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscanbotbinarizationfilter\/outputmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscanbotbinarizationfilter\/outputmode"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/outputMode","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKOutputMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKOutputMode","text":"SBSDKOutputMode"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScanbotBinarizationFilter":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScanbotBinarizationFilter"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKScanbotBinarizationFilter"}],"title":"SBSDKScanbotBinarizationFilter","abstract":[{"text":"Automatic binarization filter. This filter is a good starting point for most use cases.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanbotbinarizationfilter","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKOutputMode":{"type":"topic","kind":"symbol","abstract":[{"text":"Output mode of binarization filter.","type":"text"}],"title":"SBSDKOutputMode","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKOutputMode","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkoutputmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOutputMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKOutputMode"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScanbotBinarizationFilter/outputMode":{"title":"outputMode","type":"topic","kind":"symbol","abstract":[{"text":"Output mode of the filter. BINARY will return a black and white image, GRAYSCALE will return an antialiased","type":"text"},{"text":" ","type":"text"},{"text":"grayscale image.","type":"text"},{"text":" ","type":"text"},{"text":"Default is BINARY","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKOutputMode","kind":"typeIdentifier","text":"SBSDKOutputMode"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/outputMode","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanbotbinarizationfilter\/outputmode","navigatorTitle":[{"kind":"identifier","text":"outputMode"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"outputMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"outputMode","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOutputMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKOutputMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKOutputMode","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"outputMode","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter\/title","op":"replace","value":"SBSDKScanbotBinarizationFilter"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter\/fragments","op":"replace","value":[{"text":"SBSDKScanbotBinarizationFilter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKScanbotBinarizationFilter"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKOutputMode\/title","op":"replace","value":"SBSDKOutputMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKOutputMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKOutputMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKOutputMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKOutputMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter~1outputMode\/title","op":"replace","value":"outputMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter~1outputMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"outputMode"}]}]}]}