{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod\/lastVisible","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastVisible"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod\/lastvisible"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod\/lastvisible"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeAccumulationMethod@SBSDKBarcodeAccumulationMethodLastVisible","title":"SBSDKBarcodeAccumulationMethod.lastVisible","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"lastVisible","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeAccumulationMethodLastVisible","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod"]]},"abstract":[{"type":"text","text":"The quad of a barcode is simply given as the last quad when it was detected."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAccumulationMethod/lastVisible":{"title":"SBSDKBarcodeAccumulationMethod.lastVisible","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod\/lastVisible","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeAccumulationMethodLastVisible","kind":"identifier"}],"abstract":[{"text":"The quad of a barcode is simply given as the last quad when it was detected.","type":"text"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastVisible","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod\/lastvisible","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAccumulationMethod":{"title":"SBSDKBarcodeAccumulationMethod","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"}],"abstract":[{"type":"text","text":"The method how to display barcodes from previous frames."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeAccumulationMethodLastVisible"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethodLastVisible"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKBarcodeAccumulationMethodLastVisible","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod~1lastVisible\/title","value":"SBSDKBarcodeAccumulationMethodLastVisible"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod~1lastVisible\/fragments","value":[{"text":"SBSDKBarcodeAccumulationMethodLastVisible","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod\/title","value":"SBSDKBarcodeAccumulationMethod"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}