{"sections":[],"abstract":[{"type":"text","text":"The confidence value describes how confident the OCR engine was when detecting the letters and words."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock"]]},"metadata":{"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"confidenceValue"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock(py)confidenceValue","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confidenceValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"title":"confidenceValue"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock\/confidenceValue"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"confidenceValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"Ranges from 0.0 (not confident) to 100.0 (very confident)."}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkocrresultblock\/confidencevalue"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrresultblock\/confidencevalue"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlock/confidenceValue":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confidenceValue"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"kind":"symbol","navigatorTitle":[{"text":"confidenceValue","kind":"identifier"}],"title":"confidenceValue","abstract":[{"type":"text","text":"The confidence value describes how confident the OCR engine was when detecting the letters and words."}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock\/confidenceValue","url":"\/documentation\/scanbotsdk\/sbsdkocrresultblock\/confidencevalue"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlock":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock","url":"\/documentation\/scanbotsdk\/sbsdkocrresultblock","title":"SBSDKOCRResultBlock","navigatorTitle":[{"text":"SBSDKOCRResultBlock","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCRResultBlock","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The partial result of an optical character recognition."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"confidenceValue","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"confidenceValue","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":" "},{"text":"confidenceValue","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock~1confidenceValue\/title","value":"confidenceValue"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock~1confidenceValue\/fragments","value":[{"text":"confidenceValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock\/title","op":"replace","value":"SBSDKOCRResultBlock"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock\/fragments","value":[{"text":"SBSDKOCRResultBlock","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKOCRResultBlock"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}