{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController"]]},"abstract":[{"text":"Initializes an instance of this class with the default configuration.","type":"text"}],"metadata":{"symbolKind":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","title":"init()","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerViewController(im)init"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"name":"Note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"It’s recommended to use the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController\/init(parentViewController:parentView:configuration:delegate:)","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"style":"note"}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontroller\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontroller\/init()"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController\/init()"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerViewController/init()":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Initializes an instance of this class with the default configuration."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","title":"init()","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontroller\/init()","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerViewController":{"title":"SBSDKCreditCardScannerViewController","role":"symbol","navigatorTitle":[{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontroller","abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan credit cards."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerViewController/init(parentViewController:parentView:configuration:delegate:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"parentViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"parentView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerConfiguration","text":"SBSDKCreditCardScannerConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKCreditCardScannerViewControllerDelegate","text":"SBSDKCreditCardScannerViewControllerDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithParentViewController:parentView:configuration:delegate:","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontroller\/init(parentviewcontroller:parentview:configuration:delegate:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController\/init(parentViewController:parentView:configuration:delegate:)","abstract":[{"text":"Installs the receiver as child view controller onto the parent view controller’s view using its entire bounds area.","type":"text"}],"title":"init(parentViewController:parentView:configuration:delegate:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/title","value":"SBSDKCreditCardScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKCreditCardScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/navigatorTitle","value":[{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController~1init(parentViewController:parentView:configuration:delegate:)\/title","value":"initWithParentViewController:parentView:configuration:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController~1init(parentViewController:parentView:configuration:delegate:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithParentViewController:parentView:configuration:delegate:","kind":"identifier"}]}]}]}