{"abstract":[{"text":"Returns the color space of the image as a CGColorSpace.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"colorSpace","kind":"identifier"}],"externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKImageRef(py)colorSpace","extendedModule":"ScanbotSDK","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"colorSpace","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CGColorSpaceRef","text":"CGColorSpace","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","title":"colorSpace","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/colorSpace"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorSpace"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CGColorSpaceRef","kind":"typeIdentifier","text":"CGColorSpace"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimageref\/colorspace"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimageref\/colorspace"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/colorSpace":{"url":"\/documentation\/scanbotsdk\/sbsdkimageref\/colorspace","navigatorTitle":[{"text":"colorSpace","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"colorSpace","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGColorSpace","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGColorSpaceRef"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/colorSpace","abstract":[{"text":"Returns the color space of the image as a CGColorSpace.","type":"text"}],"title":"colorSpace"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef":{"kind":"symbol","role":"symbol","abstract":[{"text":"Image ref class.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRef"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageref","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRef"}],"title":"SBSDKImageRef"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"colorSpace","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"colorSpace"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"CGColorSpace","preciseIdentifier":"c:@S@CGColorSpace"},{"kind":"text","text":" * "},{"kind":"identifier","text":"colorSpace"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"colorSpace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1colorSpace\/title","op":"replace"},{"value":[{"text":"colorSpace","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1colorSpace\/fragments","op":"replace"},{"value":"SBSDKImageRef","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/title","op":"replace"},{"value":[{"text":"SBSDKImageRef","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageRef"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/navigatorTitle","op":"replace"}]}]}