{"metadata":{"roleHeading":"Type Method","title":"fromSampleBuffer(sampleBuffer:options:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef(cm)fromSampleBufferWithSampleBuffer:options:","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromSampleBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sampleBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKRawImageLoadOptions","text":"SBSDKRawImageLoadOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"fromSampleBufferWithSampleBuffer:options:","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimageref\/fromsamplebuffer(samplebuffer:options:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimageref\/fromsamplebuffer(samplebuffer:options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromSampleBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sampleBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKRawImageLoadOptions","text":"SBSDKRawImageLoadOptions","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRawImageLoadOptions"},{"text":" = SBSDKRawImageLoadOptions()) -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/fromSampleBuffer(sampleBuffer:options:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef":{"kind":"symbol","role":"symbol","abstract":[{"text":"Image ref class.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRef"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageref","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRef"}],"title":"SBSDKImageRef"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRawImageLoadOptions":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkrawimageloadoptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRawImageLoadOptions","abstract":[{"type":"text","text":"Options for loading images that come from sensor."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKRawImageLoadOptions","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKRawImageLoadOptions","kind":"identifier"}],"title":"SBSDKRawImageLoadOptions","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/fromSampleBuffer(sampleBuffer:options:)":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/fromSampleBuffer(sampleBuffer:options:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromSampleBufferWithSampleBuffer:options:"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromSampleBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sampleBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKRawImageLoadOptions","text":"SBSDKRawImageLoadOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef","kind":"typeIdentifier"}],"title":"fromSampleBuffer(sampleBuffer:options:)","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/fromsamplebuffer(samplebuffer:options:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"fromSampleBufferWithSampleBuffer:options:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromSampleBufferWithSampleBuffer:options:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","kind":"typeIdentifier","text":"SBSDKImageRef","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromSampleBufferWithSampleBuffer:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@opaqueCMSampleBuffer","kind":"typeIdentifier","text":"opaqueCMSampleBuffer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sampleBuffer"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKRawImageLoadOptions","kind":"typeIdentifier","text":"SBSDKRawImageLoadOptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRawImageLoadOptions"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"options"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/title","value":"SBSDKImageRef","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/fragments","value":[{"text":"SBSDKImageRef","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/navigatorTitle","value":[{"text":"SBSDKImageRef","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRawImageLoadOptions\/title","value":"SBSDKRawImageLoadOptions","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRawImageLoadOptions\/fragments","value":[{"text":"SBSDKRawImageLoadOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRawImageLoadOptions\/navigatorTitle","value":[{"text":"SBSDKRawImageLoadOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1fromSampleBuffer(sampleBuffer:options:)\/title","value":"fromSampleBufferWithSampleBuffer:options:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1fromSampleBuffer(sampleBuffer:options:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromSampleBufferWithSampleBuffer:options:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}