{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/new","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"new","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"new","kind":"identifier"}],"roleHeading":"Type Method","fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatRoyalMailConfiguration(cm)new","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatroyalmailconfiguration\/new"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatRoyalMailConfiguration"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"new"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.3"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatRoyalMailConfiguration/new":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/new","title":"new","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"navigatorTitle":[{"text":"new","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatroyalmailconfiguration\/new","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatRoyalMailConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatRoyalMailConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalMailConfiguration"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalMailConfiguration"}],"abstract":[{"type":"text","text":"Royal Mail barcode configuration. Add to scanner configuration to scan Royal Mail (a.k.a. RM4SCC, CBC, BPO 4-State)"},{"type":"text","text":" "},{"type":"text","text":"barcodes."}],"type":"topic","title":"SBSDKBarcodeFormatRoyalMailConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatroyalmailconfiguration"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatRoyalMailConfiguration\/title","op":"replace","value":"SBSDKBarcodeFormatRoyalMailConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatRoyalMailConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatRoyalMailConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatRoyalMailConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalMailConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}