{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBufferLoadMode"]]},"metadata":{"symbolKind":"case","title":"SBSDKBufferLoadMode.lazy","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBufferLoadMode@SBSDKBufferLoadModeLazy","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lazy"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBufferLoadModeLazy"}],"roleHeading":"Case"},"abstract":[{"type":"text","text":"Image is decoded the first time it’s requested."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbufferloadmode\/lazy"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbufferloadmode\/lazy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBufferLoadMode\/lazy","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lazy"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBufferLoadMode":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBufferLoadMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbufferloadmode","title":"SBSDKBufferLoadMode","abstract":[{"text":"Image Ref Buffer Load Mode.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBufferLoadMode"}],"navigatorTitle":[{"text":"SBSDKBufferLoadMode","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBufferLoadMode/lazy":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbufferloadmode\/lazy","title":"SBSDKBufferLoadMode.lazy","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"lazy","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBufferLoadMode\/lazy","abstract":[{"type":"text","text":"Image is decoded the first time it’s requested."}],"navigatorTitle":[{"text":"SBSDKBufferLoadModeLazy","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKBufferLoadModeLazy","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBufferLoadModeLazy"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKBufferLoadModeLazy"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKBufferLoadMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBufferLoadMode\/title"},{"value":[{"text":"SBSDKBufferLoadMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBufferLoadMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBufferLoadMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBufferLoadMode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBufferLoadMode~1lazy\/title","value":"SBSDKBufferLoadModeLazy"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBufferLoadMode~1lazy\/fragments","op":"replace","value":[{"text":"SBSDKBufferLoadModeLazy","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}