{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompressionMode"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCompressionMode(im)isEqual:","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:"},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompressionMode\/isEqual:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcompressionmode\/isequal:"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCompressionMode/isEqual:":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompressionMode\/isEqual:","type":"topic","title":"isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkcompressionmode\/isequal:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCompressionMode":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"identifier"}],"abstract":[{"type":"text","text":"TIFF compression type."}],"type":"topic","navigatorTitle":[{"text":"SBSDKCompressionMode","kind":"identifier"}],"title":"SBSDKCompressionMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompressionMode","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcompressionmode","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKCompressionMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompressionMode\/title"},{"op":"replace","value":[{"text":"SBSDKCompressionMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompressionMode\/fragments"},{"op":"replace","value":[{"text":"SBSDKCompressionMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompressionMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}