{"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeTrackingOverlay"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackingOverlayController","text":"SBSDKBarcodeTrackingOverlayController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapOnBarcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem","text":"SBSDKBarcodeItem"},{"kind":"text","text":")"}],"title":"barcodeTrackingOverlay(_:didTapOnBarcode:)","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKBarcodeTrackingOverlayControllerDelegate(im)barcodeTrackingOverlay:didTapOnBarcode:","symbolKind":"method","navigatorTitle":[{"text":"barcodeTrackingOverlay:didTapOnBarcode:","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate"]]},"abstract":[{"text":"Called when a barcode is being tapped on.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:didTapOnBarcode:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeTrackingOverlay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackingOverlayController","text":"SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController"},{"text":", ","kind":"text"},{"text":"didTapOnBarcode","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"barcode","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem","text":"SBSDKBarcodeItem","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The barcode tracking overlay controller that the tracked barcode view belongs to."}],"type":"paragraph"}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The barcode the user tapped on.","type":"text"}]}],"name":"barcode"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:didtaponbarcode:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:didtaponbarcode:)"]}],"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeItem":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeitem","title":"SBSDKBarcodeItem","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeItem"}],"abstract":[{"text":"A single barcode found in the input image. Barcodes with the same content but different locations in the image are","type":"text"},{"text":" ","type":"text"},{"text":"considered separate barcodes.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeItem"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayControllerDelegate/barcodeTrackingOverlay(_:didTapOnBarcode:)":{"title":"barcodeTrackingOverlay(_:didTapOnBarcode:)","abstract":[{"text":"Called when a barcode is being tapped on.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:didtaponbarcode:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeTrackingOverlay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didTapOnBarcode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:didTapOnBarcode:)","navigatorTitle":[{"text":"barcodeTrackingOverlay:didTapOnBarcode:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayControllerDelegate":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The delegation protocol for the barcode tracking overlay controller."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate","title":"SBSDKBarcodeTrackingOverlayControllerDelegate","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayController":{"role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController","title":"SBSDKBarcodeTrackingOverlayController","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"abstract":[{"type":"text","text":"A class that represents an overlay used for visualizing scanned barcodes."},{"type":"text","text":" "},{"type":"text","text":"It provides a customizable user interface for displaying barcodes and supports interaction with them."},{"type":"text","text":" "},{"type":"text","text":"The overlay can be used to highlight and select barcodes based on user input."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"barcodeTrackingOverlay:didTapOnBarcode:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeTrackingOverlay:didTapOnBarcode:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"barcodeTrackingOverlay:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackingOverlayController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didTapOnBarcode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeItem","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem"},{"text":" *) ","kind":"text"},{"text":"barcode","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"controller","content":[{"inlineContent":[{"text":"The barcode tracking overlay controller that the tracked barcode view belongs to.","type":"text"}],"type":"paragraph"}]},{"name":"barcode","content":[{"inlineContent":[{"type":"text","text":"The barcode the user tapped on."}],"type":"paragraph"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/title","op":"replace","value":"SBSDKBarcodeItem"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:didTapOnBarcode:)\/title","op":"replace","value":"barcodeTrackingOverlay:didTapOnBarcode:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:didTapOnBarcode:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeTrackingOverlay:didTapOnBarcode:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/title","op":"replace","value":"SBSDKBarcodeTrackingOverlayControllerDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayControllerDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/title","op":"replace","value":"SBSDKBarcodeTrackingOverlayController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}]}]}]}