{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScanningProgressConfiguration(py)hash","title":"hash","fragments":[{"kind":"identifier","text":"hash"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScanningProgressConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScanningProgressConfiguration\/hash"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscanningprogressconfiguration\/hash"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScanningProgressConfiguration/hash":{"role":"symbol","fragments":[{"kind":"identifier","text":"hash"}],"kind":"symbol","title":"hash","abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscanningprogressconfiguration\/hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScanningProgressConfiguration\/hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScanningProgressConfiguration":{"kind":"symbol","type":"topic","title":"SBSDKUI2CheckScanningProgressConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscanningprogressconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScanningProgressConfiguration","navigatorTitle":[{"text":"SBSDKUI2CheckScanningProgressConfiguration","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Configuration of visualization of the scanning progress - indeterminate progress.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CheckScanningProgressConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2CheckScanningProgressConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScanningProgressConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScanningProgressConfiguration\/fragments","value":[{"text":"SBSDKUI2CheckScanningProgressConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScanningProgressConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CheckScanningProgressConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}