{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight\/large"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight"]]},"abstract":[{"type":"text","text":"Result sheet is not completely collapsed, revealing more information."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2collapsedvisibleheight\/large"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2collapsedvisibleheight\/large"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"large","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"SBSDKUI2CollapsedVisibleHeight.large","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2CollapsedVisibleHeight@SBSDKUI2CollapsedVisibleHeightLarge","roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"large"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeightLarge"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CollapsedVisibleHeight/large":{"role":"symbol","abstract":[{"type":"text","text":"Result sheet is not completely collapsed, revealing more information."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight\/large","kind":"symbol","type":"topic","title":"SBSDKUI2CollapsedVisibleHeight.large","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeightLarge"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2collapsedvisibleheight\/large","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"large"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CollapsedVisibleHeight":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeight"}],"abstract":[{"type":"text","text":"Configuration of the barcodes result sheet’s height while collapsed."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2collapsedvisibleheight","title":"SBSDKUI2CollapsedVisibleHeight","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeight"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2CollapsedVisibleHeightLarge"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeightLarge"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"SBSDKUI2CollapsedVisibleHeightLarge","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight~1large\/title","value":"SBSDKUI2CollapsedVisibleHeightLarge"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight~1large\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeightLarge"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight\/title","value":"SBSDKUI2CollapsedVisibleHeight"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeight"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeight"}]}]}]}