{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFPagesExtractor"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfpagesextractor\/imageurls(from:scaling:compression:encrypter:outputdirectory:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfpagesextractor\/imageurls(from:scaling:compression:encrypter:outputdirectory:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL. Runs in the same thread that it is called from."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageURLs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pdfURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scaling"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compression"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encrypter"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting","kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"outputDirectory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]"}]}],"kind":"declarations"},{"parameters":[{"name":"pdfURL","content":[{"type":"paragraph","inlineContent":[{"text":"The URL of the PDF file.","type":"text"}]}]},{"name":"scaling","content":[{"inlineContent":[{"type":"text","text":"Scaling applied to the PDF media box frame while extracting. Affects the output image quality. In most cases the recommended value is 2 and higher."}],"type":"paragraph"}]},{"name":"compression","content":[{"inlineContent":[{"text":"Compression of the output image file. The range is from 0 to 1, where 1 - lossless conversion, 0 - maximum compression is used.","type":"text"}],"type":"paragraph"}]},{"name":"encrypter","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The encrypter used to encrypt output image files. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", no encryption is used."}]}]},{"name":"outputDirectory","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The output folder where images will be stored. If the folder does not exist, it will be created."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of URLs with extracted pages as JPEG files. The array will be empty if something is wrong."}]}]}],"kind":"symbol","metadata":{"title":"imageURLs(from:scaling:compression:encrypter:outputDirectory:)","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPDFPagesExtractor(im)imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageURLs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scaling","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compression"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encrypter"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier","text":"SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"outputDirectory"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"]"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:"}]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPDFPagesExtractor":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFPagesExtractor","kind":"symbol","type":"topic","abstract":[{"text":"Class used to extract pages from a PDF file and returns them in various ways.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfpagesextractor","title":"SBSDKPDFPagesExtractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCrypting":{"navigatorTitle":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Protocol for implementing encryption and decryption of (streamed) data.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecrypting","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting","title":"SBSDKStorageCrypting","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPDFPagesExtractor/imageURLs(from:scaling:compression:encrypter:outputDirectory:)":{"abstract":[{"text":"Extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL. Runs in the same thread that it is called from.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageURLs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scaling","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"compression","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"outputDirectory","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"imageURLs(from:scaling:compression:encrypter:outputDirectory:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfpagesextractor\/imageurls(from:scaling:compression:encrypter:outputdirectory:)","navigatorTitle":[{"text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSURL *>"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"imageURLsFromPDF:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pdfURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaling:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"scaling"},{"kind":"text","text":" "},{"kind":"identifier","text":"compression:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"compression"},{"kind":"text","text":" "},{"kind":"identifier","text":"encrypter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","text":"id<SBSDKStorageCrypting>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"encrypter"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputDirectory:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"outputDirectory"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL of the PDF file."}]}],"name":"pdfURL"},{"content":[{"inlineContent":[{"type":"text","text":"Scaling applied to the PDF media box frame while extracting. Affects the output image quality. In most cases the recommended value is 2 and higher."}],"type":"paragraph"}],"name":"scaling"},{"content":[{"inlineContent":[{"type":"text","text":"Compression of the output image file. The range is from 0 to 1, where 1 - lossless conversion, 0 - maximum compression is used."}],"type":"paragraph"}],"name":"compression"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The encrypter used to encrypt output image files. If "},{"code":"nil","type":"codeVoice"},{"type":"text","text":", no encryption is used."}]}],"name":"encrypter"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The output folder where images will be stored. If the folder does not exist, it will be created.","type":"text"}]}],"name":"outputDirectory"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of URLs with extracted pages as JPEG files. The array will be empty if something is wrong."}]}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"SBSDKPDFPagesExtractor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFPagesExtractor\/title"},{"value":[{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFPagesExtractor\/fragments"},{"value":[{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFPagesExtractor\/navigatorTitle"},{"value":"SBSDKStorageCrypting","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/title"},{"value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/navigatorTitle"},{"value":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:scaling:compression:encrypter:outputDirectory:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:scaling:compression:encrypter:outputDirectory:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}