{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewControllerDelegate\/documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewControllerDelegate"]]},"metadata":{"symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKDocumentScannerViewControllerDelegate(im)documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"documentScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configureStatusDetectionLabel"},{"text":": ","kind":"text"},{"text":"SBSDKDetectionStatusLabel","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDetectionStatusLabel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forDetectionResult"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult"},{"kind":"text","text":"?)"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","kind":"identifier"}],"title":"documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)","role":"symbol"},"abstract":[{"type":"text","text":"Optional."},{"type":"text","text":" "},{"type":"text","text":"Lets you configure the document detections status label, depending on the document detection status."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:configurestatusdetectionlabel:fordetectionresult:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:configurestatusdetectionlabel:fordetectionresult:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"documentScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configureStatusDetectionLabel"},{"kind":"text","text":" "},{"kind":"internalParam","text":"label"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDetectionStatusLabel","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDetectionStatusLabel","text":"SBSDKDetectionStatusLabel"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forDetectionResult"},{"text":" ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult"},{"text":"?)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The document scanner controller that called this function."}],"type":"paragraph"}],"name":"controller"},{"name":"label","content":[{"type":"paragraph","inlineContent":[{"text":"The label to be configured.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"The result of the current document detection.","type":"text"}],"type":"paragraph"}],"name":"result"}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"You can change the visibility, colors, font, and text of the label here.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewControllerDelegate":{"navigatorTitle":[{"text":"SBSDKDocumentScannerViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerViewControllerDelegate","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The delegate protocol of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","isActive":true},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","title":"SBSDKDocumentScannerViewControllerDelegate"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController":{"navigatorTitle":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","title":"SBSDKDocumentScannerViewController","abstract":[{"type":"text","text":"A UIViewController subclass to show a camera screen and run a user guiding document detector."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewControllerDelegate/documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)":{"type":"topic","abstract":[{"text":"Optional.","type":"text"},{"text":" ","type":"text"},{"text":"Lets you configure the document detections status label, depending on the document detection status.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewControllerDelegate\/documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentScannerViewController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController"},{"kind":"text","text":", "},{"text":"configureStatusDetectionLabel","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDetectionStatusLabel","text":"SBSDKDetectionStatusLabel","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"forDetectionResult","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult"},{"kind":"text","text":"?)"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:configurestatusdetectionlabel:fordetectionresult:)","kind":"symbol","title":"documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)","role":"symbol","navigatorTitle":[{"text":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectorResult":{"title":"SBSDKDocumentDetectorResult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectorresult","abstract":[{"type":"text","text":"This class represents the result of a document detection"},{"type":"text","text":" "},{"type":"text","text":"on an image."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDetectionStatusLabel":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDetectionStatusLabel","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdetectionstatuslabel","title":"SBSDKDetectionStatusLabel","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UILabel"},{"type":"text","text":" subclass with rounded corners and content insets to display the status of the current document detection result."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"documentScannerViewController:"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"configureStatusDetectionLabel:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDetectionStatusLabel","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDetectionStatusLabel","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDetectionStatusLabel"},{"text":" *) ","kind":"text"},{"text":"label","kind":"internalParam"},{"kind":"text","text":" "},{"text":"forDetectionResult:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectorResult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":{"kind":"parameters","parameters":[{"name":"controller","content":[{"inlineContent":[{"text":"The document scanner controller that called this function.","type":"text"}],"type":"paragraph"}]},{"name":"label","content":[{"inlineContent":[{"type":"text","text":"The label to be configured."}],"type":"paragraph"}]},{"name":"result","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the current document detection."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate\/title","value":"SBSDKDocumentScannerViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/title","value":"SBSDKDocumentScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate~1documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)\/title","value":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate~1documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","kind":"identifier"}]},{"op":"replace","value":"SBSDKDocumentDetectorResult","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectorResult\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectorResult\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectorResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"op":"replace"},{"value":"SBSDKDetectionStatusLabel","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDetectionStatusLabel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDetectionStatusLabel"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDetectionStatusLabel\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDetectionStatusLabel"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDetectionStatusLabel\/navigatorTitle","op":"replace"}]}]}