{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType"]]},"abstract":[{"text":"Passport.","type":"text"}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"passport","kind":"identifier"}],"title":"passport","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"passport"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKMRZDocumentType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType(cpy)passport","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Property","symbolKind":"property"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passport","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKMRZDocumentType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/passport","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype\/passport"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype\/passport"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZDocumentType":{"abstract":[{"text":"Type of document containing the MRZ.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZDocumentType"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType","kind":"symbol","title":"SBSDKMRZDocumentType","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZDocumentType"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZDocumentType/passport":{"title":"passport","url":"\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype\/passport","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"passport"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType","kind":"typeIdentifier","text":"SBSDKMRZDocumentType"}],"type":"topic","abstract":[{"type":"text","text":"Passport."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/passport","navigatorTitle":[{"kind":"identifier","text":"passport"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"value":"passport","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"passport","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType","text":"SBSDKMRZDocumentType"},{"text":" * ","kind":"text"},{"text":"passport","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType\/title","op":"replace","value":"SBSDKMRZDocumentType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMRZDocumentType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMRZDocumentType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1passport\/title","value":"passport"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1passport\/fragments","value":[{"kind":"identifier","text":"passport"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}