{"abstract":[{"type":"text","text":"Designated initializer. Creates a new instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerConfiguration"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uiConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerUIConfiguration","text":"SBSDKUIDocumentScannerUIConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"textConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerTextConfiguration","text":"SBSDKUIDocumentScannerTextConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"behaviorConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerBehaviorConfiguration","text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","text":"SBSDKUICameraConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":[],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"init","role":"symbol","roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerConfiguration(im)initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","navigatorTitle":[{"text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"uiConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerUIConfiguration"},{"text":", ","kind":"text"},{"text":"textConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUIDocumentScannerTextConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerTextConfiguration"},{"text":", ","kind":"text"},{"text":"behaviorConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerBehaviorConfiguration"},{"text":", ","kind":"text"},{"text":"cameraConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUICameraConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"uiConfiguration","content":[{"type":"paragraph","inlineContent":[{"text":"A configuration for the user interface. Defines colors and sizes.","type":"text"}]}]},{"name":"textConfiguration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A configuration for text being displayed in the document scanning screen."}]}]},{"name":"behaviorConfiguration","content":[{"type":"paragraph","inlineContent":[{"text":"A configuration for defining the behavior of the document scanning screen.","type":"text"}]}]},{"name":"cameraConfiguration","content":[{"type":"paragraph","inlineContent":[{"text":"A configuration object for defining the camera of the document scanning screen.","type":"text"}]}]}],"kind":"parameters"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2DocumentScannerViewController instead."}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraConfiguration":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICameraConfiguration"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicameraconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration","abstract":[{"type":"text","text":"Configuration for the camera of all RTU-UI components."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICameraConfiguration"}],"title":"SBSDKUICameraConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerConfiguration/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)":{"title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Designated initializer. Creates a new instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerConfiguration"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uiConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerUIConfiguration","text":"SBSDKUIDocumentScannerUIConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"textConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerTextConfiguration","text":"SBSDKUIDocumentScannerTextConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"behaviorConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerBehaviorConfiguration","text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","text":"SBSDKUICameraConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","navigatorTitle":[{"text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerBehaviorConfiguration":{"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}],"type":"topic","abstract":[{"type":"text","text":"Configuration for the behavior of the document scanning screen."}],"title":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerConfiguration":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerconfiguration","navigatorTitle":[{"text":"SBSDKUIDocumentScannerConfiguration","kind":"identifier"}],"title":"SBSDKUIDocumentScannerConfiguration","abstract":[{"type":"text","text":"This class describes the look and feel, the behavior, as well as the textual contents of the detection screen for documents."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerConfiguration","deprecated":true,"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentScannerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerUIConfiguration"}],"title":"SBSDKUIDocumentScannerUIConfiguration","kind":"symbol","abstract":[{"text":"Configuration for the user interface of the document scanning screen.","type":"text"}],"role":"symbol","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerUIConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerTextConfiguration":{"abstract":[{"type":"text","text":"Configuration for the textual contents of the document scanning screen."}],"title":"SBSDKUIDocumentScannerTextConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerTextConfiguration"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannertextconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerTextConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerTextConfiguration","role":"symbol","deprecated":true,"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithUiConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerUIConfiguration","text":"SBSDKUIDocumentScannerUIConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"uiConfiguration"},{"kind":"text","text":" "},{"kind":"identifier","text":"textConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerTextConfiguration","text":"SBSDKUIDocumentScannerTextConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textConfiguration"},{"kind":"text","text":" "},{"kind":"identifier","text":"behaviorConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerBehaviorConfiguration","text":"SBSDKUIDocumentScannerBehaviorConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"behaviorConfiguration"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","text":"SBSDKUICameraConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraConfiguration"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A configuration for the user interface. Defines colors and sizes.","type":"text"}]}],"name":"uiConfiguration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A configuration for text being displayed in the document scanning screen."}]}],"name":"textConfiguration"},{"content":[{"inlineContent":[{"type":"text","text":"A configuration for defining the behavior of the document scanning screen."}],"type":"paragraph"}],"name":"behaviorConfiguration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A configuration object for defining the camera of the document scanning screen."}]}],"name":"cameraConfiguration"}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration\/title","value":"SBSDKUICameraConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUICameraConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration\/navigatorTitle","value":[{"text":"SBSDKUICameraConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)\/title","value":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/title","value":"SBSDKUIDocumentScannerBehaviorConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerConfiguration\/title","value":"SBSDKUIDocumentScannerConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration\/title","value":"SBSDKUIDocumentScannerUIConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration\/fragments","value":[{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerTextConfiguration\/title","value":"SBSDKUIDocumentScannerTextConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerTextConfiguration\/fragments","value":[{"text":"SBSDKUIDocumentScannerTextConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerTextConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerTextConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}