{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferLoadMode"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lazy","kind":"identifier"}]}]}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKBufferLoadMode@SBSDKBufferLoadModeLazy","symbolKind":"case","navigatorTitle":[{"text":"SBSDKBufferLoadModeLazy","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"lazy","kind":"identifier"}],"role":"symbol","roleHeading":"Case","title":"SBSDKBufferLoadMode.lazy"},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferLoadMode\/lazy","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferloadmode\/lazy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferloadmode\/lazy"]}],"kind":"symbol","abstract":[{"type":"text","text":"Image is decoded the first time it’s requested."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBufferLoadMode/lazy":{"abstract":[{"text":"Image is decoded the first time it’s requested.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"lazy","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBufferLoadModeLazy","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferloadmode\/lazy","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferLoadMode\/lazy","title":"SBSDKBufferLoadMode.lazy"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBufferLoadMode":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferLoadMode","type":"topic","title":"SBSDKBufferLoadMode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBufferLoadMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKBufferLoadMode","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferloadmode","abstract":[{"type":"text","text":"Image Ref Buffer Load Mode."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKBufferLoadModeLazy","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"SBSDKBufferLoadModeLazy","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKBufferLoadModeLazy"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferLoadMode~1lazy\/title","value":"SBSDKBufferLoadModeLazy","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferLoadMode~1lazy\/fragments","op":"replace","value":[{"text":"SBSDKBufferLoadModeLazy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferLoadMode\/title","op":"replace","value":"SBSDKBufferLoadMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferLoadMode\/fragments","op":"replace","value":[{"text":"SBSDKBufferLoadMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferLoadMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBufferLoadMode"}],"op":"replace"}]}]}