{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/cnentryandexitpermitbackmacaovalidfromfieldname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/cnentryandexitpermitbackmacaovalidfromfieldname"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"cnEntryAndExitPermitBackMacaoValidFromFieldName","kind":"identifier"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cnEntryAndExitPermitBackMacaoValidFromFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"symbolKind":"property","title":"cnEntryAndExitPermitBackMacaoValidFromFieldName","roleHeading":"Type Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelConstants(cpy)cnEntryAndExitPermitBackMacaoValidFromFieldName","modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/cnEntryAndExitPermitBackMacaoValidFromFieldName","interfaceLanguage":"swift"},"abstract":[{"text":"Name of the “MacaoValidFrom” field type in document type “CnEntryAndExitPermitBack”.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cnEntryAndExitPermitBackMacaoValidFromFieldName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants","navigatorTitle":[{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}],"title":"SBSDKDocumentsModelConstants","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants/cnEntryAndExitPermitBackMacaoValidFromFieldName":{"title":"cnEntryAndExitPermitBackMacaoValidFromFieldName","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cnEntryAndExitPermitBackMacaoValidFromFieldName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"type":"text","text":"Name of the “MacaoValidFrom” field type in document type “CnEntryAndExitPermitBack”."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/cnEntryAndExitPermitBackMacaoValidFromFieldName","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/cnentryandexitpermitbackmacaovalidfromfieldname","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cnEntryAndExitPermitBackMacaoValidFromFieldName"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"cnEntryAndExitPermitBackMacaoValidFromFieldName"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"cnEntryAndExitPermitBackMacaoValidFromFieldName","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"cnEntryAndExitPermitBackMacaoValidFromFieldName","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/title","op":"replace","value":"SBSDKDocumentsModelConstants"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/fragments","op":"replace","value":[{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/navigatorTitle","op":"replace"},{"value":"cnEntryAndExitPermitBackMacaoValidFromFieldName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1cnEntryAndExitPermitBackMacaoValidFromFieldName\/title","op":"replace"},{"value":[{"text":"cnEntryAndExitPermitBackMacaoValidFromFieldName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1cnEntryAndExitPermitBackMacaoValidFromFieldName\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}