{"metadata":{"symbolKind":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanner(im)initWithConfiguration:acceptedCheckTypes:","role":"symbol","title":"init(configuration:acceptedCheckTypes:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCheckScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"acceptedCheckTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKCheckDocumentModelRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelRootType","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"initWithConfiguration:acceptedCheckTypes:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Initializer"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithConfiguration:acceptedCheckTypes:) "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration","text":"SBSDKCheckScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"acceptedCheckTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelRootType","text":"SBSDKCheckDocumentModelRootType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelRootType"},{"kind":"text","text":"])"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"inlineContent":[{"text":"The configuration of the check scanner.","type":"text"}],"type":"paragraph"}]},{"name":"acceptedCheckTypes","content":[{"inlineContent":[{"type":"text","text":"The accepted check types."}],"type":"paragraph"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanner"]]},"abstract":[{"text":"Designated initializer.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscanner\/init(configuration:acceptedchecktypes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscanner\/init(configuration:acceptedchecktypes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanner\/init(configuration:acceptedCheckTypes:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScanner":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanner","navigatorTitle":[{"text":"SBSDKCheckScanner","kind":"identifier"}],"title":"SBSDKCheckScanner","abstract":[{"type":"text","text":"A scanner to scan bank checks on various image sources."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscanner","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScanner","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckScannerConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration","abstract":[{"text":"Configuration of the check scanner.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration","title":"SBSDKCheckScannerConfiguration","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckScannerConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelRootType":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentModelRootType"}],"title":"SBSDKCheckDocumentModelRootType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelRootType","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Root document type.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckDocumentModelRootType"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelroottype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScanner/init(configuration:acceptedCheckTypes:)":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanner\/init(configuration:acceptedCheckTypes:)","role":"symbol","navigatorTitle":[{"text":"initWithConfiguration:acceptedCheckTypes:","kind":"identifier"}],"title":"init(configuration:acceptedCheckTypes:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCheckScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"acceptedCheckTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKCheckDocumentModelRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelRootType","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckscanner\/init(configuration:acceptedchecktypes:)","abstract":[{"type":"text","text":"Designated initializer."}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithConfiguration:acceptedCheckTypes:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:acceptedCheckTypes:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCheckScannerConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"acceptedCheckTypes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKCheckDocumentModelRootType *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"acceptedCheckTypes","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"text":"The configuration of the check scanner.","type":"text"}]}]},{"name":"acceptedCheckTypes","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The accepted check types."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SBSDKCheckScanner","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner\/title"},{"value":[{"kind":"identifier","text":"SBSDKCheckScanner"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKCheckScanner"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner\/navigatorTitle"},{"value":"SBSDKCheckScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKCheckScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/fragments"},{"value":[{"text":"SBSDKCheckScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/navigatorTitle"},{"value":"SBSDKCheckDocumentModelRootType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelRootType\/title"},{"value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelRootType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelRootType\/fragments"},{"value":[{"text":"SBSDKCheckDocumentModelRootType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelRootType\/navigatorTitle"},{"value":"initWithConfiguration:acceptedCheckTypes:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner~1init(configuration:acceptedCheckTypes:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:acceptedCheckTypes:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner~1init(configuration:acceptedCheckTypes:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}