{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate\/vinScannerViewController(_:didScanValidResult:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"vinScannerViewController:didScanValidResult:"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKVINScannerViewControllerDelegate(im)vinScannerViewController:didScanValidResult:","roleHeading":"Instance Method","symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"vinScannerViewController(_:didScanValidResult:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vinScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerViewController","text":"SBSDKVINScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didScanValidResult","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKVehicleIdentificationNumberScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerResult"},{"kind":"text","text":")"}],"required":true},"abstract":[{"text":"Informs the delegate that a vehicle identification number has been scanned and validated, and passes the result.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(vinScannerViewController:didScanValidResult:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vinScannerViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerViewController","text":"SBSDKVINScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didScanValidResult","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerResult","text":"SBSDKVehicleIdentificationNumberScannerResult"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","isActive":true},{"type":"text","text":" that has scanned and validated the vehicle identification number."}]}]},{"name":"result","content":[{"type":"paragraph","inlineContent":[{"text":"The result of the scan.","type":"text"}]}]}],"kind":"parameters"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate\/vinscannerviewcontroller(_:didscanvalidresult:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate\/vinscannerviewcontroller(_:didscanvalidresult:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewControllerDelegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKVINScannerViewControllerDelegate","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate","navigatorTitle":[{"text":"SBSDKVINScannerViewControllerDelegate","kind":"identifier"}],"abstract":[{"text":"The delegation protocol for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController"},{"type":"text","text":"."}],"kind":"symbol","title":"SBSDKVINScannerViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewControllerDelegate/vinScannerViewController(_:didScanValidResult:)":{"type":"topic","required":true,"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"vinScannerViewController","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerViewController","kind":"typeIdentifier","text":"SBSDKVINScannerViewController"},{"kind":"text","text":", "},{"text":"didScanValidResult","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerResult","text":"SBSDKVehicleIdentificationNumberScannerResult"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate\/vinScannerViewController(_:didScanValidResult:)","navigatorTitle":[{"kind":"identifier","text":"vinScannerViewController:didScanValidResult:"}],"title":"vinScannerViewController(_:didScanValidResult:)","abstract":[{"type":"text","text":"Informs the delegate that a vehicle identification number has been scanned and validated, and passes the result."}],"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate\/vinscannerviewcontroller(_:didscanvalidresult:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller","title":"SBSDKVINScannerViewController","role":"symbol","navigatorTitle":[{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show a camera screen with the vehicle identification number scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerResult":{"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A class describing the result of the vehicle identification number scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"identifier"}],"title":"SBSDKVehicleIdentificationNumberScannerResult","navigatorTitle":[{"text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"vinScannerViewController:didScanValidResult:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"vinScannerViewController:didScanValidResult:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"vinScannerViewController:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerViewController","text":"SBSDKVINScannerViewController"},{"kind":"text","text":" *) "},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didScanValidResult:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult","text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"result"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"SBSDKVINScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate\/title"},{"value":[{"kind":"identifier","text":"SBSDKVINScannerViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate~1vinScannerViewController(_:didScanValidResult:)\/title","value":"vinScannerViewController:didScanValidResult:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"vinScannerViewController:didScanValidResult:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate~1vinScannerViewController(_:didScanValidResult:)\/fragments"},{"op":"replace","value":"SBSDKVINScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKVINScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult\/title","value":"SBSDKVehicleIdentificationNumberScannerResult","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult\/fragments","value":[{"text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}