{"metadata":{"role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKConsistencyVerificationReport(im)copyWithZone:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"title":"copyWithZone:"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"_NSZone","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"zone"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport"]]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport\/copyWithZone:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConsistencyVerificationReport":{"title":"SBSDKConsistencyVerificationReport","kind":"symbol","navigatorTitle":[{"text":"SBSDKConsistencyVerificationReport","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"Report of the document consistency verification. Shows whether information in the fields that correspond to the same","type":"text"},{"type":"text","text":" "},{"text":"logical field is consistent.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKConsistencyVerificationReport"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport","url":"\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConsistencyVerificationReport/copyWithZone:":{"role":"symbol","kind":"symbol","title":"copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport\/copywithzone:","fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport\/copyWithZone:","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKConsistencyVerificationReport","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKConsistencyVerificationReport"}]},{"op":"replace","value":[{"text":"SBSDKConsistencyVerificationReport","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/navigatorTitle"}]}]}