{"metadata":{"symbolKind":"method","title":"fromJsonWithJson:","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKConsistencyVerificationReport(cm)fromJsonWithJson:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"roleHeading":"Type Method","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport\/fromJsonWithJson:"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKConsistencyVerificationReport","kind":"typeIdentifier","text":"SBSDKConsistencyVerificationReport"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport\/fromjsonwithjson:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConsistencyVerificationReport/fromJsonWithJson:":{"title":"fromJsonWithJson:","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport\/fromJsonWithJson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport\/fromjsonwithjson:","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConsistencyVerificationReport":{"title":"SBSDKConsistencyVerificationReport","kind":"symbol","navigatorTitle":[{"text":"SBSDKConsistencyVerificationReport","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"Report of the document consistency verification. Shows whether information in the fields that correspond to the same","type":"text"},{"type":"text","text":" "},{"text":"logical field is consistent.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKConsistencyVerificationReport"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport","url":"\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/title","value":"SBSDKConsistencyVerificationReport","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/fragments","value":[{"kind":"identifier","text":"SBSDKConsistencyVerificationReport"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKConsistencyVerificationReport"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}