{"abstract":[{"type":"text","text":"Same behavior as ENABLED if a binarizationFilter is set,"},{"type":"text","text":" "},{"type":"text","text":"otherwise same behavior as DISABLED. This is the default."}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKPageBinarization@SBSDKPageBinarizationEnabledIfBinarizationFilterSet","navigatorTitle":[{"text":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet","kind":"identifier"}],"title":"SBSDKPageBinarization.enabledIfBinarizationFilterSet","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabledIfBinarizationFilterSet","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/enabledIfBinarizationFilterSet","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabledIfBinarizationFilterSet"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagebinarization\/enabledifbinarizationfilterset"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagebinarization\/enabledifbinarizationfilterset"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageBinarization/enabledIfBinarizationFilterSet":{"url":"\/documentation\/scanbotsdk\/sbsdkpagebinarization\/enabledifbinarizationfilterset","title":"SBSDKPageBinarization.enabledIfBinarizationFilterSet","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabledIfBinarizationFilterSet"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/enabledIfBinarizationFilterSet","abstract":[{"text":"Same behavior as ENABLED if a binarizationFilter is set,","type":"text"},{"text":" ","type":"text"},{"text":"otherwise same behavior as DISABLED. This is the default.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageBinarization":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization","navigatorTitle":[{"text":"SBSDKPageBinarization","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Binarization behavior to apply when adding a page to a PDF\/TIFF.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagebinarization","title":"SBSDKPageBinarization","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageBinarization","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization~1enabledIfBinarizationFilterSet\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization~1enabledIfBinarizationFilterSet\/fragments"},{"op":"replace","value":"SBSDKPageBinarization","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization\/title"},{"op":"replace","value":[{"text":"SBSDKPageBinarization","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPageBinarization"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}