{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Bi-linear interpolation. Better quality than nearest-neighbor, slower. Okay when the"},{"text":" ","type":"text"},{"type":"text","text":"target size is not too different from the source size."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"linear"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/linear"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/linear"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/linear","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod"]]},"metadata":{"title":"SBSDKResamplingMethod.linear","navigatorTitle":[{"kind":"identifier","text":"SBSDKResamplingMethodLinear"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"linear","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKResamplingMethod@SBSDKResamplingMethodLinear","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod","title":"SBSDKResamplingMethod","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod","abstract":[{"text":"Resampling method.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKResamplingMethod"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKResamplingMethod"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod/linear":{"title":"SBSDKResamplingMethod.linear","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/linear","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/linear","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"linear","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKResamplingMethodLinear","kind":"identifier"}],"abstract":[{"type":"text","text":"Bi-linear interpolation. Better quality than nearest-neighbor, slower. Okay when the"},{"text":" ","type":"text"},{"text":"target size is not too different from the source size.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SBSDKResamplingMethodLinear","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKResamplingMethodLinear","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKResamplingMethodLinear"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SBSDKResamplingMethod","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/title"},{"value":[{"kind":"identifier","text":"SBSDKResamplingMethod"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/navigatorTitle","value":[{"text":"SBSDKResamplingMethod","kind":"identifier"}]},{"op":"replace","value":"SBSDKResamplingMethodLinear","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1linear\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1linear\/fragments","value":[{"text":"SBSDKResamplingMethodLinear","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}