{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUserFieldValue\/userFieldIntValue(value:)"},"sections":[],"metadata":{"title":"userFieldIntValue(value:)","role":"symbol","roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"s:25ScanbotDocumentScannerSDK19SBSDKUserFieldValueC04userf3IntG05valueAA0efiG0CSi_tFZ","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userFieldIntValue"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUserFieldIntValue","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUserFieldIntValue"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuserfieldvalue\/userfieldintvalue(value:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUserFieldValue"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userFieldIntValue"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUserFieldIntValue","text":"SBSDKUserFieldIntValue","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUserFieldIntValue"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUserFieldValue":{"kind":"symbol","abstract":[{"type":"text","text":"User-defined TIFF field value."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUserFieldValue","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUserFieldValue","kind":"identifier"}],"role":"symbol","title":"SBSDKUserFieldValue","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUserFieldValue","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuserfieldvalue"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUserFieldIntValue":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuserfieldintvalue","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUserFieldIntValue","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUserFieldIntValue"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUserFieldIntValue","kind":"identifier"}],"role":"symbol","title":"SBSDKUserFieldIntValue","abstract":[{"type":"text","text":"32-bit int value (TIFF_LONG)."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUserFieldValue/userFieldIntValue(value:)":{"title":"userFieldIntValue(value:)","role":"symbol","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuserfieldvalue\/userfieldintvalue(value:)","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUserFieldValue\/userFieldIntValue(value:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userFieldIntValue"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUserFieldIntValue","text":"SBSDKUserFieldIntValue","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUserFieldValue","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUserFieldValue\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUserFieldValue\/fragments","value":[{"text":"SBSDKUserFieldValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUserFieldValue\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUserFieldValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUserFieldIntValue\/title","op":"replace","value":"SBSDKUserFieldIntValue"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUserFieldIntValue\/fragments","value":[{"text":"SBSDKUserFieldIntValue","kind":"identifier"}]},{"value":[{"text":"SBSDKUserFieldIntValue","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUserFieldIntValue\/navigatorTitle","op":"replace"}]}]}