{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration\/initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:processingMode:","interfaceLanguage":"occ"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerconfiguration\/initwithframeaccumulationconfiguration:enabledetection:incompleteresulthandling:returncrops:processingmode:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFrameAccumulationConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAccumulatedResultsVerifierConfiguration","text":"SBSDKAccumulatedResultsVerifierConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"frameAccumulationConfiguration"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableDetection:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enableDetection"},{"kind":"text","text":" "},{"kind":"identifier","text":"incompleteResultHandling:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMRZIncompleteResultHandling","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling","kind":"typeIdentifier","text":"SBSDKMRZIncompleteResultHandling"},{"kind":"text","text":") "},{"kind":"internalParam","text":"incompleteResultHandling"},{"text":" ","kind":"text"},{"text":"returnCrops:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"returnCrops","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"processingMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKProcessingMode","text":"SBSDKProcessingMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"processingMode","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration(im)initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:processingMode:","title":"initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:processingMode:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:processingMode:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:processingMode:"}]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAccumulatedResultsVerifierConfiguration":{"title":"SBSDKAccumulatedResultsVerifierConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAccumulatedResultsVerifierConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkaccumulatedresultsverifierconfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configure the frame accumulation process."}],"navigatorTitle":[{"text":"SBSDKAccumulatedResultsVerifierConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZIncompleteResultHandling":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMRZIncompleteResultHandling","kind":"identifier"}],"type":"topic","title":"SBSDKMRZIncompleteResultHandling","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling","abstract":[{"type":"text","text":"Defines how to handle incomplete MRZ results (e.g. caused by failed validation)."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzincompleteresulthandling","navigatorTitle":[{"text":"SBSDKMRZIncompleteResultHandling","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProcessingMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkprocessingmode","title":"SBSDKProcessingMode","type":"topic","abstract":[{"text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it.","type":"text"},{"text":" ","type":"text"},{"text":"On the other hand, scanners can produce even better results if they can analyze multiple images of the same subject and cross-check and combine the results.","type":"text"},{"text":" ","type":"text"},{"text":"The processing mode tells the scanner whether to optimize for single or multiple images of a subject.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessingMode"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerconfiguration","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKMRZScannerConfiguration","kind":"identifier"}],"title":"SBSDKMRZScannerConfiguration","navigatorTitle":[{"text":"SBSDKMRZScannerConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for MRZ scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerConfiguration/initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:processingMode:":{"navigatorTitle":[{"text":"initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:processingMode:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration\/initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:processingMode:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:processingMode:","kind":"identifier"}],"abstract":[],"title":"initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:processingMode:","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerconfiguration\/initwithframeaccumulationconfiguration:enabledetection:incompleteresulthandling:returncrops:processingmode:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKAccumulatedResultsVerifierConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/navigatorTitle"},{"value":"SBSDKMRZIncompleteResultHandling","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/title"},{"value":[{"text":"SBSDKMRZIncompleteResultHandling","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/navigatorTitle"},{"value":"SBSDKProcessingMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/title"},{"value":[{"text":"SBSDKProcessingMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKProcessingMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/navigatorTitle"},{"value":"SBSDKMRZScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKMRZScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKMRZScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerConfiguration\/navigatorTitle"}]}]}