{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategories\/am"},"metadata":{"roleHeading":"Instance Property","title":"am","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelEuropeanDriverLicenseBackCategories(py)am","symbolKind":"property","navigatorTitle":[{"text":"am","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"am","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM"},{"text":"?","kind":"text"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"am"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM","text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"sections":[],"abstract":[{"type":"text","text":"The child document of type “AM”."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategories"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategories\/am"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategories\/am"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanDriverLicenseBackCategories/am":{"abstract":[{"type":"text","text":"The child document of type “AM”."}],"title":"am","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategories\/am","role":"symbol","navigatorTitle":[{"text":"am","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"am","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategories\/am"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM","type":"topic","abstract":[{"text":"EuropeanDriverLicenseBack.Categories.AM","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategoriesam","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM","kind":"identifier"}],"kind":"symbol","title":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanDriverLicenseBackCategories":{"type":"topic","navigatorTitle":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategories","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategories","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategories","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategories","abstract":[{"type":"text","text":"Categories table row container"}],"title":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategories"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"am"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"am"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM"},{"text":" * ","kind":"text"},{"text":"am","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategories~1am\/title","value":"am"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategories~1am\/fragments","value":[{"text":"am","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM\/title","value":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM\/fragments","value":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesAM"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategories\/title","value":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategories"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategories\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategories"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategories\/navigatorTitle","value":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategories","kind":"identifier"}]}]}]}