{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"topBarTitle","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"}],"platforms":["iOS"]}]}],"abstract":[{"text":"Configuration of the title, located in the top bar.","type":"text"}],"metadata":{"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"topBarTitle","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraScreenConfiguration(py)topBarTitle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"topBarTitle"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarTitle"},{"text":": ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/topbartitle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/topbartitle"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration\/topBarTitle","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraScreenConfiguration":{"type":"topic","title":"SBSDKUI2CameraScreenConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration","navigatorTitle":[{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration","abstract":[{"type":"text","text":"Configuration of the screen for scanning the pages with the camera."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraScreenConfiguration/topBarTitle":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"topBarTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/topbartitle","role":"symbol","title":"topBarTitle","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the title, located in the top bar."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration\/topBarTitle","navigatorTitle":[{"text":"topBarTitle","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"title":"SBSDKUI2StyledText","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"topBarTitle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"topBarTitle","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":" * "},{"text":"topBarTitle","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/title","value":"SBSDKUI2CameraScreenConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraScreenConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CameraScreenConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration~1topBarTitle\/title","value":"topBarTitle","op":"replace"},{"value":[{"kind":"identifier","text":"topBarTitle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration~1topBarTitle\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","op":"replace","value":"SBSDKUI2StyledText"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/navigatorTitle"}]}]}