{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraConfiguration\/init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2cameraconfiguration\/init(cameramodule:zoomsteps:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:orientationlockmode:camerapreviewmode:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2cameraconfiguration\/init(cameramodule:zoomsteps:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:orientationlockmode:camerapreviewmode:)"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraConfiguration"]]},"metadata":{"roleHeading":"Initializer","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CameraConfiguration(im)initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"cameraModule","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraModule","kind":"typeIdentifier","text":"SBSDKUI2CameraModule"},{"kind":"text","text":", "},{"text":"zoomSteps","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"defaultZoomFactor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"flashEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"minFocusDistanceLock","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"pinchToZoomEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientationLockMode"},{"text":": ","kind":"text"},{"text":"SBSDKUI2OrientationLockMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2OrientationLockMode"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraPreviewMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraPreviewMode"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:"}],"symbolKind":"init","title":"init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"cameraModule","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraModule","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraModule","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraModule"},{"text":" = SBSDKUI2CameraModule.back, ","kind":"text"},{"kind":"externalParam","text":"zoomSteps"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":"] = [1.0, 2.0, 5.0], "},{"kind":"externalParam","text":"defaultZoomFactor"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":" = 1.0, ","kind":"text"},{"kind":"externalParam","text":"flashEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"minFocusDistanceLock","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"pinchToZoomEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"orientationLockMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2OrientationLockMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2OrientationLockMode","text":"SBSDKUI2OrientationLockMode"},{"text":" = SBSDKUI2OrientationLockMode.none, ","kind":"text"},{"text":"cameraPreviewMode","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode","kind":"typeIdentifier","text":"SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraPreviewMode"},{"text":" = SBSDKUI2CameraPreviewMode.fillIn)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2cameraconfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration of the camera settings to be used while scanning."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}],"title":"SBSDKUI2CameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraConfiguration","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraModule":{"navigatorTitle":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraModule","role":"symbol","type":"topic","title":"SBSDKUI2CameraModule","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CameraModule"}],"abstract":[{"type":"text","text":"Determines which camera module to use on start-up."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2cameramodule"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2OrientationLockMode":{"title":"SBSDKUI2OrientationLockMode","abstract":[{"text":"Configure the orientation of the interface.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2OrientationLockMode","type":"topic","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2orientationlockmode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraConfiguration/init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)":{"title":"init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cameraModule","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraModule","text":"SBSDKUI2CameraModule","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"zoomSteps","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"defaultZoomFactor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"flashEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minFocusDistanceLock"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"pinchToZoomEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientationLockMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2OrientationLockMode","text":"SBSDKUI2OrientationLockMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewMode"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraPreviewMode","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraConfiguration\/init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2cameraconfiguration\/init(cameramodule:zoomsteps:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:orientationlockmode:camerapreviewmode:)","abstract":[],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraPreviewMode":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}],"abstract":[{"text":"Configuration of the camera preview mode.","type":"text"}],"title":"SBSDKUI2CameraPreviewMode","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapreviewmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCameraModule:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraModule","kind":"typeIdentifier","text":"SBSDKUI2CameraModule","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraModule"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraModule"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomSteps:"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"zoomSteps","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultZoomFactor:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"text":"defaultZoomFactor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"flashEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"flashEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minFocusDistanceLock:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"minFocusDistanceLock","kind":"internalParam"},{"kind":"text","text":" "},{"text":"pinchToZoomEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"pinchToZoomEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"orientationLockMode:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2OrientationLockMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2OrientationLockMode","text":"SBSDKUI2OrientationLockMode"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"orientationLockMode"},{"kind":"text","text":" "},{"text":"cameraPreviewMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraPreviewMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode"},{"text":") ","kind":"text"},{"text":"cameraPreviewMode","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraConfiguration\/title","value":"SBSDKUI2CameraConfiguration","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraConfiguration\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraModule\/title","op":"replace","value":"SBSDKUI2CameraModule"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraModule\/fragments","op":"replace","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraModule\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CameraModule"}],"op":"replace"},{"value":"SBSDKUI2OrientationLockMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2OrientationLockMode\/title"},{"value":[{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2OrientationLockMode\/fragments"},{"value":[{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2OrientationLockMode\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraConfiguration~1init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)\/title","op":"replace","value":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraConfiguration~1init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:","kind":"identifier"}]},{"value":"SBSDKUI2CameraPreviewMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPreviewMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPreviewMode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}]},{"value":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPreviewMode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}