{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone","text":"_NSZone"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"zone"},{"text":";","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormats"]]},"metadata":{"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormats(im)copyWithZone:","title":"copyWithZone:","fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformats\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormats\/copyWithZone:","interfaceLanguage":"occ"},"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormats/copyWithZone:":{"title":"copyWithZone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformats\/copywithzone:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormats\/copyWithZone:","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormats":{"kind":"symbol","abstract":[{"text":"Lists of barcode formats to decode.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormats","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormats","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformats","title":"SBSDKBarcodeFormats","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormats"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKBarcodeFormats","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormats\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormats\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormats","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormats\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormats","kind":"identifier"}]}]}]}