{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerUserGuidance\/fromJsonWithJson:"},"kind":"symbol","metadata":{"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerUserGuidance(cm)fromJsonWithJson:","title":"fromJsonWithJson:","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerUserGuidance"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneruserguidance\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2DocumentScannerUserGuidance","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerUserGuidance","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerUserGuidance"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerUserGuidance/fromJsonWithJson:":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneruserguidance\/fromjsonwithjson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"type":"topic","abstract":[],"title":"fromJsonWithJson:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerUserGuidance\/fromJsonWithJson:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerUserGuidance":{"abstract":[{"type":"text","text":"Configuration of the hints guiding users through the scanning process."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerUserGuidance"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerUserGuidance","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneruserguidance","type":"topic","title":"SBSDKUI2DocumentScannerUserGuidance","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerUserGuidance"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerUserGuidance\/title","value":"SBSDKUI2DocumentScannerUserGuidance"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerUserGuidance\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerUserGuidance"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerUserGuidance\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentScannerUserGuidance","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}