{"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Description of source from which the ImageRef was created. Non-null only if detailed profiling has been"},{"type":"text","text":" "},{"type":"text","text":"previously enabled by a call to enableDetailedProfiling."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfile\/imageSource"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofile\/imagesource"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofile\/imagesource"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfile"]]},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"imageSource","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageSource","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKImageSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageSource"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefProfile(py)imageSource","role":"symbol","navigatorTitle":[{"text":"imageSource","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageSource"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSource","text":"SBSDKImageSource","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageSource","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageSource":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageSource"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagesource","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSource"}],"title":"SBSDKImageSource","kind":"symbol","abstract":[{"type":"text","text":"Description of source from which the ImageRef was created."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSource","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefProfile":{"kind":"symbol","abstract":[{"type":"text","text":"ImageRef profile which provides detailed information about stored object."}],"type":"topic","title":"SBSDKImageRefProfile","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfile","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKImageRefProfile","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRefProfile"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofile"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefProfile/imageSource":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageSource","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageSource","kind":"typeIdentifier","text":"SBSDKImageSource"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Description of source from which the ImageRef was created. Non-null only if detailed profiling has been"},{"text":" ","type":"text"},{"text":"previously enabled by a call to enableDetailedProfiling.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"imageSource","kind":"identifier"}],"title":"imageSource","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfile\/imageSource","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofile\/imagesource"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"imageSource"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"imageSource","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSource","text":"SBSDKImageSource","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageSource","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"imageSource"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSource\/title","value":"SBSDKImageSource","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSource\/fragments","op":"replace","value":[{"text":"SBSDKImageSource","kind":"identifier"}]},{"value":[{"text":"SBSDKImageSource","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSource\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfile\/title","value":"SBSDKImageRefProfile"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfile\/fragments","op":"replace","value":[{"text":"SBSDKImageRefProfile","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfile\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefProfile"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfile~1imageSource\/title","op":"replace","value":"imageSource"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfile~1imageSource\/fragments","op":"replace","value":[{"kind":"identifier","text":"imageSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}