{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerBehaviorConfiguration\/init","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerBehaviorConfiguration"]]},"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"init","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerBehaviorConfiguration(im)init","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerbehaviorconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerBehaviorConfiguration/init":{"type":"topic","title":"init","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerbehaviorconfiguration\/init","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerBehaviorConfiguration\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerBehaviorConfiguration":{"title":"SBSDKUIDocumentScannerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerBehaviorConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerbehaviorconfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration for the behavior of the document scanning screen."}],"navigatorTitle":[{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"identifier"}],"deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/title","op":"replace","value":"SBSDKUIDocumentScannerBehaviorConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}]},{"value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/navigatorTitle"}]}]}