{"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration(im)init","symbolKind":"method","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerenergyconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerEnergyConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/init"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerEnergyConfiguration/init":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerenergyconfiguration\/init","abstract":[],"kind":"symbol","title":"init","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/init"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerEnergyConfiguration":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerenergyconfiguration","kind":"symbol","abstract":[{"text":"The energy management configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"‘SBSDKBaseScannerViewController’ and subclasses sport a customizable energy management system."},{"type":"text","text":" "},{"text":"Since scanners running on a live video feed can put a lot of load onto the CPU and\/or GPU","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"of the device, causing the battery to drain quickly and running the device hot, you can customize the energy"},{"text":" ","type":"text"},{"type":"text","text":"consumption using this class by configuring the rate of detections\/recognitions per second in performance mode as"},{"type":"text","text":" "},{"text":"well as in energy saving mode.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"In performance mode the scanners will be fed with a higher, configurable rate of"},{"type":"text","text":" "},{"type":"text","text":"video frames per second."},{"type":"text","text":" "},{"type":"text","text":"After a certain, configurable period of inactivity the energy save mode will be engaged and the rate"},{"text":" ","type":"text"},{"type":"text","text":"of scans will be reduced to a lower (configurable) rate."},{"type":"text","text":" "},{"type":"text","text":"You can also configure the time of inactivity before the automatic mode switches from performance to energy save mode."},{"type":"text","text":" "},{"text":"Inactivity here means that both of the following conditions are met:","type":"text"}],"title":"SBSDKBaseScannerEnergyConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerEnergyConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKBaseScannerEnergyConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/navigatorTitle","value":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}