{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:to:)-1cqke"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Asynchronously converts the document to a multipage-TIFF file and saves it to the specified URL."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator\/generate(from:to:)-1cqke"},"metadata":{"symbolKind":"method","title":"generate(from:to:)","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"text":"SBSDKDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"s:10ScanbotSDK18SBSDKTIFFGeneratorC8generate4from2to10Foundation3URLVSgAA13SBSDKDocumentC_AItYaF"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@nonobjc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"document"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fileURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"document","content":[{"inlineContent":[{"type":"text","text":"The document to convert to a TIFF file."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The file URL to save the TIFF file at.","type":"text"}]}],"name":"fileURL"}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"text":"The URL the TIFF file has been written to or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the operation failed."}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"In Swift language it is used with structured concurrency (async\/await)."}],"type":"paragraph"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGenerator":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"abstract":[{"type":"text","text":"A class that converts images to (multipage) TIFF images."},{"type":"text","text":" "},{"type":"text","text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc."},{"text":" ","type":"text"},{"text":"When passing an encrypter the generated TIFF images will be encrypted.","type":"text"}],"title":"SBSDKTIFFGenerator","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffgenerator","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator","navigatorTitle":[{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGenerator/generate(from:to:)-1cqke":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator\/generate(from:to:)-1cqke","title":"generate(from:to:)","abstract":[{"text":"Asynchronously converts the document to a multipage-TIFF file and saves it to the specified URL.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"generate","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:to:)-1cqke"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","title":"SBSDKDocumentPage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","abstract":[{"text":"This class represents a scanned documents page.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentPage","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentPage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocument":{"title":"SBSDKDocument","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocument","kind":"identifier"}],"abstract":[{"text":"A thread-safe, mutable container for scanned pages of type ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","type":"reference"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocument","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocument"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/title","op":"replace","value":"SBSDKTIFFGenerator"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/fragments","value":[{"text":"SBSDKTIFFGenerator","kind":"identifier"}]},{"value":[{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title","value":"SBSDKDocumentPage"},{"value":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments"},{"value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/navigatorTitle"},{"op":"replace","value":"SBSDKDocument","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/title"},{"value":[{"text":"SBSDKDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/fragments"},{"value":[{"text":"SBSDKDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}