{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentintroimage\/copywithzone:"]}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"title":"copyWithZone:","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentIntroImage(im)copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentIntroImage"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentIntroImage\/copyWithZone:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentIntroImage/copyWithZone:":{"title":"copyWithZone:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentintroimage\/copywithzone:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentIntroImage\/copyWithZone:","abstract":[],"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentIntroImage":{"kind":"symbol","title":"SBSDKUI2DocumentIntroImage","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentIntroImage"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentIntroImage"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentintroimage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentIntroImage","abstract":[{"text":"The image for the introduction screen with a document template.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentIntroImage\/title","value":"SBSDKUI2DocumentIntroImage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentIntroImage\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentIntroImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentIntroImage\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentIntroImage","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}