{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"binaryDocumentOptimizedCompression","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompressionMode","text":"SBSDKCompressionMode","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompressionMode","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Default is CCITT_T6"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/binarydocumentoptimizedcompression"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/binarydocumentoptimizedcompression"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","roleHeading":"Type Property","symbolKind":"property","navigatorTitle":[{"text":"binaryDocumentOptimizedCompression","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters(cpy)binaryDocumentOptimizedCompression","title":"binaryDocumentOptimizedCompression","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"binaryDocumentOptimizedCompression","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompressionMode","text":"SBSDKCompressionMode","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}]},"abstract":[{"type":"text","text":"Compression mode typically producing the smallest file sizes for binary (1-bit) document images."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/binaryDocumentOptimizedCompression"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/binaryDocumentOptimizedCompression":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/binaryDocumentOptimizedCompression","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/binarydocumentoptimizedcompression","navigatorTitle":[{"text":"binaryDocumentOptimizedCompression","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Compression mode typically producing the smallest file sizes for binary (1-bit) document images.","type":"text"}],"title":"binaryDocumentOptimizedCompression","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"binaryDocumentOptimizedCompression","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompressionMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters":{"kind":"symbol","abstract":[{"type":"text","text":"TIFF generator parameters."}],"title":"SBSDKTIFFGeneratorParameters","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCompressionMode":{"kind":"symbol","title":"SBSDKCompressionMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompressionMode","abstract":[{"type":"text","text":"TIFF compression type."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCompressionMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcompressionmode","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"binaryDocumentOptimizedCompression","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"binaryDocumentOptimizedCompression"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBSDKCompressionMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompressionMode","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompressionMode"},{"kind":"text","text":" * "},{"kind":"identifier","text":"binaryDocumentOptimizedCompression"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1binaryDocumentOptimizedCompression\/title","value":"binaryDocumentOptimizedCompression","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1binaryDocumentOptimizedCompression\/fragments","value":[{"kind":"identifier","text":"binaryDocumentOptimizedCompression"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/title","value":"SBSDKTIFFGeneratorParameters","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/fragments","value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/navigatorTitle","value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompressionMode\/title","value":"SBSDKCompressionMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompressionMode\/fragments","value":[{"text":"SBSDKCompressionMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompressionMode\/navigatorTitle","value":[{"text":"SBSDKCompressionMode","kind":"identifier"}],"op":"replace"}]}]}