{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"DPI value."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/dpi"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/dpi"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/dpi"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dpi","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters(py)dpi","role":"symbol","navigatorTitle":[{"text":"dpi","kind":"identifier"}],"roleHeading":"Instance Property","title":"dpi","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dpi","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is 72"}]}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters":{"kind":"symbol","abstract":[{"type":"text","text":"TIFF generator parameters."}],"title":"SBSDKTIFFGeneratorParameters","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/dpi":{"title":"dpi","navigatorTitle":[{"text":"dpi","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/dpi","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dpi","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","abstract":[{"type":"text","text":"DPI value."}],"url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/dpi"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"dpi","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"dpi","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"dpi","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKTIFFGeneratorParameters","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/title"},{"value":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/fragments"},{"value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/navigatorTitle"},{"value":"dpi","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1dpi\/title"},{"value":[{"text":"dpi","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1dpi\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}