{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subfiles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVADocumentSubfile","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AAMVADocumentSubfile","text":"SBSDKUI2AAMVADocumentSubfile"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2aamvadocumentformat\/subfiles"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2aamvadocumentformat\/subfiles"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVADocumentFormat\/subfiles","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sub-files"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subfiles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2AAMVADocumentSubfile","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AAMVADocumentSubfile"},{"kind":"text","text":"]"}],"title":"subfiles","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AAMVADocumentFormat(py)subfiles","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"subfiles"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVADocumentFormat"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AAMVADocumentSubfile":{"role":"symbol","title":"SBSDKUI2AAMVADocumentSubfile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AAMVADocumentSubfile"}],"abstract":[{"type":"text","text":"AAMVA Document Sub-File"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVADocumentSubfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AAMVADocumentSubfile"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aamvadocumentsubfile"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AAMVADocumentFormat":{"role":"symbol","title":"SBSDKUI2AAMVADocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AAMVADocumentFormat"}],"abstract":[{"type":"text","text":"AAMVA Document Format"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVADocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AAMVADocumentFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aamvadocumentformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AAMVADocumentFormat/subfiles":{"role":"symbol","title":"subfiles","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subfiles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2AAMVADocumentSubfile","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AAMVADocumentSubfile"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Sub-files"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVADocumentFormat\/subfiles","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subfiles"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aamvadocumentformat\/subfiles"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"subfiles"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"subfiles"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBSDKUI2AAMVADocumentSubfile *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"subfiles"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVADocumentSubfile\/title","value":"SBSDKUI2AAMVADocumentSubfile"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVADocumentSubfile\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AAMVADocumentSubfile"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVADocumentFormat\/title","value":"SBSDKUI2AAMVADocumentFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVADocumentFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AAMVADocumentFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVADocumentFormat~1subfiles\/title","value":"subfiles"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVADocumentFormat~1subfiles\/fragments","value":[{"kind":"identifier","text":"subfiles"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}