{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/cameraAccessDidChange:","interfaceLanguage":"occ"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"cameraAccessDidChange:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"granted","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/cameraaccessdidchange:"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerViewController(im)cameraAccessDidChange:","role":"symbol","symbolKind":"method","title":"cameraAccessDidChange:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cameraAccessDidChange:"}],"navigatorTitle":[{"kind":"identifier","text":"cameraAccessDidChange:"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController","role":"symbol","deprecated":true,"title":"SBSDKUIFinderDocumentScannerViewController","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan a single documents of a certain aspect ratio."}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/cameraAccessDidChange:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/cameraAccessDidChange:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cameraAccessDidChange:"}],"title":"cameraAccessDidChange:","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/cameraaccessdidchange:","navigatorTitle":[{"text":"cameraAccessDidChange:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUIFinderDocumentScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}],"op":"replace"}]}]}