{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/enableCameraUIConfiguration"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraUIConfiguration","text":"SBSDKUIEnableCameraUIConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraUIConfiguration"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"enableCameraUIConfiguration"},{"kind":"text","text":";"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/enablecamerauiconfiguration"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController"]]},"metadata":{"fragments":[{"text":"enableCameraUIConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"enableCameraUIConfiguration","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerViewController(py)enableCameraUIConfiguration","title":"enableCameraUIConfiguration"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraUIConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraUIConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuienablecamerauiconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIEnableCameraUIConfiguration"}],"kind":"symbol","title":"SBSDKUIEnableCameraUIConfiguration","abstract":[{"type":"text","text":"Configuration for the user interface of camera based view controllers."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"A highly customizable camera-based view controller to scan a single documents of a certain aspect ratio.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller","title":"SBSDKUIFinderDocumentScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/enableCameraUIConfiguration":{"type":"topic","abstract":[],"kind":"symbol","title":"enableCameraUIConfiguration","fragments":[{"kind":"identifier","text":"enableCameraUIConfiguration"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/enablecamerauiconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/enableCameraUIConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUIEnableCameraUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraUIConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraUIConfiguration\/fragments","value":[{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController\/title","value":"SBSDKUIFinderDocumentScannerViewController"},{"value":[{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}