{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"SBSDKThreadSafe"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"dynamic"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraMockData"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSimulatedCameraMockData","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData","kind":"typeIdentifier","text":"SBSDKSimulatedCameraMockData"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Observably via KVO. Thread safe."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}]}]}],"abstract":[{"type":"text","text":"The test data for a simulated camera. Intended for UI testing, etc."},{"type":"text","text":" "},{"type":"text","text":"If set to a non-nil value, any active scanners camera session will immediately switch to simulation mode and simulate a camera stream and captured images using an image source provided in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Setting it to ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" will return to the normal camera mode on physical devices and to simulated mode without a video stream on iOS simulators.","type":"text"}],"metadata":{"title":"cameraMockData","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTestData(py)cameraMockData","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraMockData","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSimulatedCameraMockData","text":"SBSDKSimulatedCameraMockData","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"cameraMockData","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTestData\/cameraMockData"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktestdata\/cameramockdata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktestdata\/cameramockdata"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTestData"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTestData/cameraMockData":{"url":"\/documentation\/scanbotsdk\/sbsdktestdata\/cameramockdata","title":"cameraMockData","navigatorTitle":[{"text":"cameraMockData","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cameraMockData","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKSimulatedCameraMockData","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSimulatedCameraMockData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The test data for a simulated camera. Intended for UI testing, etc."},{"type":"text","text":" "},{"type":"text","text":"If set to a non-nil value, any active scanners camera session will immediately switch to simulation mode and simulate a camera stream and captured images using an image source provided in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Setting it to ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" will return to the normal camera mode on physical devices and to simulated mode without a video stream on iOS simulators.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTestData\/cameraMockData"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSimulatedCameraMockData":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"title":"SBSDKSimulatedCameraMockData","kind":"symbol","abstract":[{"type":"text","text":"A class to describe the mocking data that is fed to a simulated camera device."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdksimulatedcameramockdata","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTestData":{"navigatorTitle":[{"text":"SBSDKTestData","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktestdata","title":"SBSDKTestData","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTestData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKTestData","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A container for test data, e.g. simulated camera mock data.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"cameraMockData"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"cameraMockData"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSimulatedCameraMockData","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData","text":"SBSDKSimulatedCameraMockData"},{"kind":"text","text":" * "},{"text":"cameraMockData","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTestData~1cameraMockData\/title","value":"cameraMockData"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTestData~1cameraMockData\/fragments","value":[{"kind":"identifier","text":"cameraMockData"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData\/title","value":"SBSDKSimulatedCameraMockData"},{"value":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTestData\/title","op":"replace","value":"SBSDKTestData"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKTestData"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTestData\/fragments"}]}]}