{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Background color of the bottom bar."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/bottombarbackgroundcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/bottombarbackgroundcolor"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration"]]},"metadata":{"title":"bottomBarBackgroundColor","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerUIConfiguration(py)bottomBarBackgroundColor","navigatorTitle":[{"text":"bottomBarBackgroundColor","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomBarBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/bottomBarBackgroundColor","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBarBackgroundColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/bottomBarBackgroundColor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomBarBackgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","title":"bottomBarBackgroundColor","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/bottombarbackgroundcolor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/bottomBarBackgroundColor","abstract":[{"text":"Background color of the bottom bar.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"bottomBarBackgroundColor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration","abstract":[{"text":"Configuration for the user interface of the document scanning screen.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration","navigatorTitle":[{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"identifier"}],"title":"SBSDKUIDocumentScannerUIConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerUIConfiguration"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"bottomBarBackgroundColor","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bottomBarBackgroundColor"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"bottomBarBackgroundColor"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"bottomBarBackgroundColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1bottomBarBackgroundColor\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1bottomBarBackgroundColor\/fragments","value":[{"kind":"identifier","text":"bottomBarBackgroundColor"}]},{"op":"replace","value":"SBSDKUIDocumentScannerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration\/title"},{"value":[{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}