{"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelAAMVATitleData\/initWithGenericDocument:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelAAMVATitleData"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithGenericDocument:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","kind":"typeIdentifier","text":"SBSDKGenericDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"document"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"text":"initWithGenericDocument:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelAAMVATitleData(im)initWithGenericDocument:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"title":"initWithGenericDocument:","role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelaamvatitledata\/initwithgenericdocument:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelAAMVATitleData/initWithGenericDocument:":{"navigatorTitle":[{"kind":"identifier","text":"initWithGenericDocument:"}],"kind":"symbol","title":"initWithGenericDocument:","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithGenericDocument:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelAAMVATitleData\/initWithGenericDocument:","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelaamvatitledata\/initwithgenericdocument:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelAAMVATitleData":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelAAMVATitleData","abstract":[{"type":"text","text":"Title Data. File type “TD”."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentModelAAMVATitleData","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelAAMVATitleData","kind":"identifier"}],"title":"SBSDKBarcodeDocumentModelAAMVATitleData","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelaamvatitledata","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"abstract":[{"type":"text","text":"Generic document."}],"kind":"symbol","role":"symbol","title":"SBSDKGenericDocument","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelAAMVATitleData\/title","value":"SBSDKBarcodeDocumentModelAAMVATitleData"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelAAMVATitleData\/fragments","value":[{"text":"SBSDKBarcodeDocumentModelAAMVATitleData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelAAMVATitleData\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelAAMVATitleData"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}]}]}]}