{"metadata":{"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bezierPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"AVCaptureVideoPreviewLayer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath","kind":"typeIdentifier"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPolygon(im)bezierPathForPreviewLayer:","navigatorTitle":[{"text":"bezierPathForPreviewLayer:","kind":"identifier"}],"symbolKind":"method","title":"bezierPath(for:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygon\/bezierpath(for:)-7l13"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygon\/bezierpath(for:)-7l13"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Creates a UIBezierPath instance of the receiver for drawing purposes.","type":"text"}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(bezierPathForPreviewLayer:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bezierPath","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"previewLayer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","text":"AVCaptureVideoPreviewLayer"},{"text":") -> ","kind":"text"},{"text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier"}]}],"kind":"declarations"},{"parameters":[{"name":"previewLayer","content":[{"inlineContent":[{"type":"text","text":"The preview layer the path is going to be presented on."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An UIBezierPath instance representing the polygon.","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygon"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygon\/bezierPath(for:)-7l13"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygon":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPolygon","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygon","role":"symbol","navigatorTitle":[{"text":"SBSDKPolygon","kind":"identifier"}],"title":"SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygon","abstract":[{"text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}.","type":"text"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygon/bezierPath(for:)-7l13":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygon\/bezierpath(for:)-7l13","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bezierPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","text":"AVCaptureVideoPreviewLayer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier","text":"UIBezierPath"}],"title":"bezierPath(for:)","abstract":[{"type":"text","text":"Creates a UIBezierPath instance of the receiver for drawing purposes."}],"navigatorTitle":[{"text":"bezierPathForPreviewLayer:","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygon\/bezierPath(for:)-7l13"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 5.2.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"bezierPathForPreviewLayer:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bezierPathForPreviewLayer:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"bezierPathForPreviewLayer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","text":"AVCaptureVideoPreviewLayer"},{"kind":"text","text":" *) "},{"text":"previewLayer","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"SBSDKPolygon","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygon\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygon\/fragments","value":[{"text":"SBSDKPolygon","kind":"identifier"}]},{"op":"replace","value":"bezierPathForPreviewLayer:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygon~1bezierPath(for:)-7l13\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bezierPathForPreviewLayer:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygon~1bezierPath(for:)-7l13\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}