{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rotate180"},{"kind":"text","text":"("},{"kind":"externalParam","text":"oldSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"newSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":")"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPolygon(im)rotate180WithOldSize:newSize:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"rotate180(oldSize:newSize:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rotate180WithOldSize:newSize:"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(rotate180WithOldSize:newSize:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rotate180","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"oldSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"name":"oldSize","content":[{"inlineContent":[{"type":"text","text":"The size of the absolute coordinate system before rotating it."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The size of the absolute coordinate system after rotating it.","type":"text"}],"type":"paragraph"}],"name":"newSize"}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygon\/rotate180(oldSize:newSize:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygon\/rotate180(oldsize:newsize:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygon\/rotate180(oldsize:newsize:)"]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Rotates the points of the receiver 180 degrees, transforming it from one absolute space to another."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygon"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygon":{"title":"SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygon","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygon","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"}],"role":"symbol","abstract":[{"text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygon/rotate180(oldSize:newSize:)":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygon\/rotate180(oldSize:newSize:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rotate180WithOldSize:newSize:"}],"title":"rotate180(oldSize:newSize:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rotate180","kind":"identifier"},{"kind":"text","text":"("},{"text":"oldSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":")","kind":"text"}],"abstract":[{"text":"Rotates the points of the receiver 180 degrees, transforming it from one absolute space to another.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygon\/rotate180(oldsize:newsize:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 6.2.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"rotate180WithOldSize:newSize:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rotate180WithOldSize:newSize:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"rotate180WithOldSize:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"oldSize"},{"kind":"text","text":" "},{"text":"newSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"newSize","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":{"kind":"parameters","parameters":[{"name":"oldSize","content":[{"inlineContent":[{"type":"text","text":"The size of the absolute coordinate system before rotating it."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The size of the absolute coordinate system after rotating it.","type":"text"}],"type":"paragraph"}],"name":"newSize"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"SBSDKPolygon","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygon\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPolygon"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygon\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygon\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPolygon","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygon~1rotate180(oldSize:newSize:)\/title","value":"rotate180WithOldSize:newSize:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygon~1rotate180(oldSize:newSize:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rotate180WithOldSize:newSize:","kind":"identifier"}]}]}]}