{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MedicalCertificateDocumentFieldType","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfield\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfield\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentField\/type","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Medical Certificate Document Field Type"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MedicalCertificateDocumentFieldType"}],"title":"type","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalCertificateDocumentField(py)type","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"type"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentField"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.2"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentField":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentField"}],"abstract":[{"type":"text","text":"Medical Certificate Document Field"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentField"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfield"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentField/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MedicalCertificateDocumentFieldType"}],"abstract":[{"type":"text","text":"Medical Certificate Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentField\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfield\/type"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}],"abstract":[{"type":"text","text":"Medical Certificate Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MedicalCertificateDocumentFieldType","text":"SBSDKUI2MedicalCertificateDocumentFieldType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentField\/title","value":"SBSDKUI2MedicalCertificateDocumentField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentField\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentField"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentField~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentField~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}