{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorBehaviorConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorbehaviorconfiguration\/documenttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorbehaviorconfiguration\/documenttype"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorBehaviorConfiguration\/documentType","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentType","text":"SBSDKUIDocumentType","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"documentType"}],"title":"documentType","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorBehaviorConfiguration(py)documentType","symbolKind":"property"},"abstract":[{"text":"The recognizable document type.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentType","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentType","text":"SBSDKUIDocumentType","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorBehaviorConfiguration/documentType":{"abstract":[{"text":"The recognizable document type.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorBehaviorConfiguration\/documentType","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"documentType","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUIDocumentType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentType"}],"navigatorTitle":[{"kind":"identifier","text":"documentType"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorbehaviorconfiguration\/documenttype","title":"documentType","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController":{"role":"symbol","navigatorTitle":[{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"title":"SBSDKUIDocumentDataExtractorViewController","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to extract generic documents data."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorBehaviorConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentDataExtractorBehaviorConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorBehaviorConfiguration","type":"topic","abstract":[{"type":"text","text":"The configuration for the behavior of the RTU-UI document data extractor screen."}],"navigatorTitle":[{"text":"SBSDKUIDocumentDataExtractorBehaviorConfiguration","kind":"identifier"}],"title":"SBSDKUIDocumentDataExtractorBehaviorConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorbehaviorconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentType":{"role":"symbol","navigatorTitle":[{"text":"SBSDKUIDocumentType","kind":"identifier"}],"title":"SBSDKUIDocumentType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentType","url":"\/documentation\/scanbotsdk\/sbsdkuidocumenttype","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIDocumentType"}],"abstract":[{"type":"text","text":"The type of the document that should be extracted with "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It is a composition of the data extractor document types."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"documentType"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"documentType"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"text":"SBSDKUIDocumentType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentType","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"documentType","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"documentType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorBehaviorConfiguration~1documentType\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorBehaviorConfiguration~1documentType\/fragments","value":[{"text":"documentType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/title","value":"SBSDKUIDocumentDataExtractorViewController","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/navigatorTitle","value":[{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUIDocumentDataExtractorBehaviorConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorBehaviorConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUIDocumentDataExtractorBehaviorConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorBehaviorConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorBehaviorConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentType\/title","value":"SBSDKUIDocumentType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentType\/fragments","value":[{"text":"SBSDKUIDocumentType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIDocumentType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}