{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannerview\/accessibilitytextcontenttype(_:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView\/accessibilityTextContentType(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityTextContentType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AccessibilityTextContentType","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI28AccessibilityTextContentTypeV"},{"text":") -> ","kind":"text"},{"text":"ModifiedContent","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI15ModifiedContentV"},{"text":"<","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"AccessibilityAttachmentModifier","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV"},{"text":">","kind":"text"}],"extendedModule":"SwiftUICore","externalID":"s:7SwiftUI4ViewPAAE28accessibilityTextContentTypeyAA08ModifiedF0VyxAA31AccessibilityAttachmentModifierVGAA0iefG0VF::SYNTHESIZED::s:10ScanbotSDK27SBSDKUI2DocumentScannerViewV","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"15.0","name":"iOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"15.0","name":"iPadOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"15.0","name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"12.0","name":"macOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"15.0","name":"tvOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"8.0","name":"watchOS"}],"title":"accessibilityTextContentType(_:)","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"View.accessibilityTextContentType(_:)","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView\/View-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityTextContentType"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"value"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI28AccessibilityTextContentTypeV","kind":"typeIdentifier","text":"AccessibilityTextContentType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:7SwiftUI15ModifiedContentV","kind":"typeIdentifier","text":"ModifiedContent"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","kind":"typeIdentifier","text":"AccessibilityAttachmentModifier"},{"kind":"text","text":">"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerView/View-Implementations":{"abstract":[],"type":"topic","title":"View Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannerview\/view-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView\/View-Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerView":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannerview","abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerController","isActive":true},{"text":".","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2DocumentScannerView","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerView","kind":"identifier"}],"title":"SBSDKUI2DocumentScannerView","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerView/accessibilityTextContentType(_:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView\/accessibilityTextContentType(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityTextContentType","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:7SwiftUI28AccessibilityTextContentTypeV","text":"AccessibilityTextContentType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI15ModifiedContentV","text":"ModifiedContent","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","text":"AccessibilityAttachmentModifier","kind":"typeIdentifier"},{"text":">","kind":"text"}],"abstract":[],"title":"accessibilityTextContentType(_:)","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannerview\/accessibilitytextcontenttype(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerController":{"role":"symbol","title":"SBSDKUI2DocumentScannerController","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerController","kind":"identifier"}],"abstract":[{"text":"A highly customizable camera-based RTU-UI controller to scan documents.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerController","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannercontroller","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerController\/title","op":"replace","value":"SBSDKUI2DocumentScannerController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerController\/fragments","op":"replace","value":[{"text":"SBSDKUI2DocumentScannerController","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2DocumentScannerController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerController\/navigatorTitle","op":"replace"}]}]}