{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKContentValidator(im)copyWithZone:","modules":[{"name":"ScanbotSDK"}],"title":"copyWithZone:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/copyWithZone:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcontentvalidator\/copywithzone:"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@_NSZone","text":"_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator/copyWithZone:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/copyWithZone:","title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator\/copywithzone:","abstract":[],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator":{"url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator","navigatorTitle":[{"text":"SBSDKContentValidator","kind":"identifier"}],"abstract":[{"text":"Base class for content validators.","type":"text"}],"type":"topic","role":"symbol","title":"SBSDKContentValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKContentValidator","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKContentValidator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/fragments","value":[{"kind":"identifier","text":"SBSDKContentValidator"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKContentValidator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}