{"abstract":[{"text":"Informs the delegate, that the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","type":"reference"},{"text":" wants to finish.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate\/viewControllerShouldFinish(_:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate"]]},"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewControllerShouldFinish","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIViewController"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"viewControllerShouldFinish:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIViewControllerDelegate(im)viewControllerShouldFinish:","required":true,"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","title":"viewControllerShouldFinish(_:)","symbolKind":"method"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuiviewcontrollerdelegate\/viewcontrollershouldfinish(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuiviewcontrollerdelegate\/viewcontrollershouldfinish(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewControllerShouldFinish"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","kind":"typeIdentifier","text":"SBSDKUIViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller that wants to finish."}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"True"},{"text":", if you want to automatically dismiss the view controller. ","type":"text"},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"}]}],"kind":"content"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"If you implement this method and return ","type":"text"},{"type":"codeVoice","code":"False"},{"text":", you will be responsible for dismissing the view controller.","type":"text"}]}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIViewController","kind":"identifier"}],"title":"SBSDKUIViewController","abstract":[{"type":"text","text":"An abstract base class for RTU-UI view controllers."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewControllerDelegate":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIViewControllerDelegate"}],"url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIViewControllerDelegate"}],"role":"symbol","abstract":[{"type":"text","text":"The general delegate protocol for "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","isActive":true},{"type":"text","text":"-based classes."}],"title":"SBSDKUIViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewControllerDelegate/viewControllerShouldFinish(_:)":{"abstract":[{"text":"Informs the delegate, that the ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","isActive":true},{"text":" wants to finish.","type":"text"}],"title":"viewControllerShouldFinish(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate\/viewControllerShouldFinish(_:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewControllerShouldFinish","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"viewControllerShouldFinish:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontrollerdelegate\/viewcontrollershouldfinish(_:)","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"viewControllerShouldFinish:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewControllerShouldFinish:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"viewControllerShouldFinish:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The view controller that wants to finish."}],"type":"paragraph"}],"name":"viewController"}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"True"},{"type":"text","text":", if you want to automatically dismiss the view controller. "},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise."}],"type":"paragraph"}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/title","op":"replace","value":"SBSDKUIViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/fragments","op":"replace","value":[{"text":"SBSDKUIViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewControllerDelegate\/title","op":"replace","value":"SBSDKUIViewControllerDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewControllerDelegate\/fragments","op":"replace","value":[{"text":"SBSDKUIViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewControllerDelegate~1viewControllerShouldFinish(_:)\/title","op":"replace","value":"viewControllerShouldFinish:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewControllerDelegate~1viewControllerShouldFinish(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewControllerShouldFinish:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}