{"kind":"symbol","metadata":{"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"photoQualityPrioritization"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerBehaviorConfiguration(py)photoQualityPrioritization","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"photoQualityPrioritization","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCapturePhotoQualityPrioritization","text":"SBSDKCapturePhotoQualityPrioritization"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"platforms":[],"title":"photoQualityPrioritization"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration"]]},"abstract":[{"text":"The prioritization of still image quality and capturing speed.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/photoQualityPrioritization"},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2DocumentScannerViewController instead."}],"type":"paragraph"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/photoqualityprioritization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/photoqualityprioritization"]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"photoQualityPrioritization","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization","kind":"typeIdentifier","text":"SBSDKCapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCapturePhotoQualityPrioritization"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"If you experience lots of blurry still images try to set this property to ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/quality","isActive":true},{"type":"text","text":"."}]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCapturePhotoQualityPrioritization/balanced":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","type":"topic","navigatorTitle":[{"text":"SBSDKCapturePhotoQualityPrioritizationBalanced","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization\/balanced","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"balanced"}],"kind":"symbol","abstract":[{"text":"Balances capturing speed and image quality equally. This is the default value.","type":"text"}],"title":"SBSDKCapturePhotoQualityPrioritization.balanced"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCapturePhotoQualityPrioritization":{"role":"symbol","abstract":[{"text":"The prioritization of still image quality and capturing speed.","type":"text"}],"navigatorTitle":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization","title":"SBSDKCapturePhotoQualityPrioritization","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCapturePhotoQualityPrioritization/quality":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization\/quality","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"quality"}],"kind":"symbol","abstract":[{"text":"Captures a still image with the best possible quality in terms of noise, frozen motion and detail in low light.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The speed of the capturing might be significantly reduced."}],"title":"SBSDKCapturePhotoQualityPrioritization.quality","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/quality","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationQuality"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration":{"deprecated":true,"type":"topic","title":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration for the behavior of the document scanning screen.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration","navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/photoQualityPrioritization":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"photoQualityPrioritization"},{"text":": ","kind":"text"},{"text":"SBSDKCapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCapturePhotoQualityPrioritization","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/photoqualityprioritization","navigatorTitle":[{"text":"photoQualityPrioritization","kind":"identifier"}],"deprecated":true,"abstract":[{"type":"text","text":"The prioritization of still image quality and capturing speed."}],"title":"photoQualityPrioritization","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/photoQualityPrioritization","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"photoQualityPrioritization","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"photoQualityPrioritization"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCapturePhotoQualityPrioritization","text":"SBSDKCapturePhotoQualityPrioritization"},{"kind":"text","text":" "},{"text":"photoQualityPrioritization","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKCapturePhotoQualityPrioritizationBalanced","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization~1balanced\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization~1balanced\/fragments","value":[{"text":"SBSDKCapturePhotoQualityPrioritizationBalanced","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization\/title","op":"replace","value":"SBSDKCapturePhotoQualityPrioritization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization\/fragments","value":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization\/navigatorTitle","value":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKCapturePhotoQualityPrioritizationQuality","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization~1quality\/title"},{"value":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationQuality"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization~1quality\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/title","op":"replace","value":"SBSDKUIFinderDocumentScannerBehaviorConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1photoQualityPrioritization\/title","value":"photoQualityPrioritization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1photoQualityPrioritization\/fragments","value":[{"kind":"identifier","text":"photoQualityPrioritization"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}