{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelHkIdentityCardFront\/id"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelHkIdentityCardFront"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"id","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"id","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelHkIdentityCardFront(py)id"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelhkidentitycardfront\/id"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelhkidentitycardfront\/id"]}],"abstract":[{"text":"Identity Document Number","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"title":"SBSDKGenericDocumentField","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"abstract":[{"type":"text","text":"Generic document field."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelHkIdentityCardFront":{"type":"topic","title":"SBSDKDocumentsModelHkIdentityCardFront","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelhkidentitycardfront","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentsModelHkIdentityCardFront","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelHkIdentityCardFront","kind":"identifier"}],"abstract":[{"text":"HkIdentityCardFront","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelHkIdentityCardFront"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelHkIdentityCardFront/id":{"title":"id","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelhkidentitycardfront\/id","type":"topic","navigatorTitle":[{"text":"id","kind":"identifier"}],"abstract":[{"type":"text","text":"Identity Document Number"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelHkIdentityCardFront\/id","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"id","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"id","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":" * "},{"kind":"identifier","text":"id"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKGenericDocumentField","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle"},{"op":"replace","value":"SBSDKDocumentsModelHkIdentityCardFront","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelHkIdentityCardFront\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentsModelHkIdentityCardFront","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelHkIdentityCardFront\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentsModelHkIdentityCardFront"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelHkIdentityCardFront\/navigatorTitle"},{"op":"replace","value":"id","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelHkIdentityCardFront~1id\/title"},{"op":"replace","value":[{"text":"id","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelHkIdentityCardFront~1id\/fragments"}]}]}