{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithGenericDocument:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","text":"SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},{"kind":"text","text":" *) "},{"text":"document","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"kind":"symbol","metadata":{"title":"initWithGenericDocument:","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelHkIdentityCardFront(im)initWithGenericDocument:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelHkIdentityCardFront"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelHkIdentityCardFront\/initWithGenericDocument:"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelhkidentitycardfront\/initwithgenericdocument:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"abstract":[{"text":"Generic document.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","title":"SBSDKGenericDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelHkIdentityCardFront":{"type":"topic","title":"SBSDKDocumentsModelHkIdentityCardFront","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelhkidentitycardfront","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentsModelHkIdentityCardFront","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelHkIdentityCardFront","kind":"identifier"}],"abstract":[{"text":"HkIdentityCardFront","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelHkIdentityCardFront"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelHkIdentityCardFront/initWithGenericDocument:":{"navigatorTitle":[{"kind":"identifier","text":"initWithGenericDocument:"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelhkidentitycardfront\/initwithgenericdocument:","type":"topic","title":"initWithGenericDocument:","kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelHkIdentityCardFront\/initWithGenericDocument:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGenericDocument:"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","op":"replace","value":"SBSDKGenericDocument"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelHkIdentityCardFront\/title","op":"replace","value":"SBSDKDocumentsModelHkIdentityCardFront"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelHkIdentityCardFront\/fragments","op":"replace","value":[{"text":"SBSDKDocumentsModelHkIdentityCardFront","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelHkIdentityCardFront\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentsModelHkIdentityCardFront"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}