{"abstract":[{"text":"Shows whether the data in the field is semantically invalid, e.g. the date of birth is in the future.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfieldvaluesemantics\/invalidsemantics"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfieldvaluesemantics\/invalidsemantics"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidSemantics","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"]}]}],"metadata":{"title":"invalidSemantics","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidSemantics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"invalidSemantics"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldValueSemantics(py)invalidSemantics","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldValueSemantics\/invalidSemantics","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldValueSemantics"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldValueSemantics/invalidSemantics":{"title":"invalidSemantics","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldValueSemantics\/invalidSemantics","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfieldvaluesemantics\/invalidsemantics","abstract":[{"type":"text","text":"Shows whether the data in the field is semantically invalid, e.g. the date of birth is in the future."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"invalidSemantics"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidSemantics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldValueSemantics":{"role":"symbol","navigatorTitle":[{"text":"SBSDKFieldValueSemantics","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFieldValueSemantics","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldValueSemantics","abstract":[{"type":"text","text":"Report of the field value semantics verification."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfieldvaluesemantics","title":"SBSDKFieldValueSemantics","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"invalidSemantics"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"invalidSemantics"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidSemantics"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"invalidSemantics","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldValueSemantics~1invalidSemantics\/title","op":"replace"},{"value":[{"text":"invalidSemantics","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldValueSemantics~1invalidSemantics\/fragments","op":"replace"},{"value":"SBSDKFieldValueSemantics","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldValueSemantics\/title","op":"replace"},{"value":[{"text":"SBSDKFieldValueSemantics","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldValueSemantics\/fragments","op":"replace"},{"value":[{"text":"SBSDKFieldValueSemantics","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldValueSemantics\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}