{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageprocessor\/applyrotation(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageprocessor\/applyrotation(_:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProcessor\/applyRotation(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProcessor"]]},"metadata":{"title":"applyRotation(_:)","navigatorTitle":[{"kind":"identifier","text":"applyRotation:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"applyRotation"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageRotation","text":"SBSDKImageRotation"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageProcessor(im)applyRotation:","symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"abstract":[{"type":"text","text":"Rotates the input image in the given direction."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applyRotation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"rotation","kind":"internalParam"},{"kind":"text","text":": "},{"text":"SBSDKImageRotation","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRotation","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageRotation"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The rotation to be applied."}],"type":"paragraph"}],"name":"rotation"}]}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageProcessor":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageprocessor","role":"symbol","abstract":[{"type":"text","text":"A class to process images."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageProcessor"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageProcessor","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProcessor","kind":"symbol","type":"topic","title":"SBSDKImageProcessor"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRotation":{"abstract":[{"text":"Image rotation.","type":"text"}],"title":"SBSDKImageRotation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKImageRotation","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerotation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRotation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRotation"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageProcessor/applyRotation(_:)":{"kind":"symbol","navigatorTitle":[{"text":"applyRotation:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProcessor\/applyRotation(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"applyRotation","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageRotation","kind":"typeIdentifier","text":"SBSDKImageRotation"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageprocessor\/applyrotation(_:)","abstract":[{"type":"text","text":"Rotates the input image in the given direction."}],"type":"topic","title":"applyRotation(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"applyRotation:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyRotation:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"applyRotation:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageRotation","text":"SBSDKImageRotation","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRotation"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"rotation"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"rotation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The rotation to be applied."}]}]}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProcessor\/title","value":"SBSDKImageProcessor"},{"value":[{"kind":"identifier","text":"SBSDKImageProcessor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProcessor\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageProcessor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProcessor\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRotation\/title","value":"SBSDKImageRotation","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRotation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRotation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRotation\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageRotation"}]},{"value":"applyRotation:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProcessor~1applyRotation(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProcessor~1applyRotation(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"applyRotation:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}