{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult\/initWithRawText:wordBoxes:symbolBoxes:confidence:validationSuccessful:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRawText:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rawText"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wordBoxes:"},{"kind":"text","text":"("},{"text":"NSArray<SBSDKWordBox *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"wordBoxes","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"symbolBoxes:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKSymbolBox *>"},{"text":" *) ","kind":"text"},{"text":"symbolBoxes","kind":"internalParam"},{"kind":"text","text":" "},{"text":"confidence:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"confidence"},{"kind":"text","text":" "},{"text":"validationSuccessful:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"validationSuccessful","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult\/initwithrawtext:wordboxes:symbolboxes:confidence:validationsuccessful:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult(im)initWithRawText:wordBoxes:symbolBoxes:confidence:validationSuccessful:","title":"initWithRawText:wordBoxes:symbolBoxes:confidence:validationSuccessful:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"text":"initWithRawText:wordBoxes:symbolBoxes:confidence:validationSuccessful:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithRawText:wordBoxes:symbolBoxes:confidence:validationSuccessful:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerResult/initWithRawText:wordBoxes:symbolBoxes:confidence:validationSuccessful:":{"navigatorTitle":[{"text":"initWithRawText:wordBoxes:symbolBoxes:confidence:validationSuccessful:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult\/initWithRawText:wordBoxes:symbolBoxes:confidence:validationSuccessful:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRawText:wordBoxes:symbolBoxes:confidence:validationSuccessful:","kind":"identifier"}],"title":"initWithRawText:wordBoxes:symbolBoxes:confidence:validationSuccessful:","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult\/initwithrawtext:wordboxes:symbolboxes:confidence:validationsuccessful:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerResult":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","title":"SBSDKTextPatternScannerResult","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerResult"}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult","abstract":[{"type":"text","text":"The result of the text line recognition."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/title","value":"SBSDKTextPatternScannerResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerResult"}],"op":"replace"},{"value":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/navigatorTitle"}]}]}