{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimageprocessor\/init(imageurl:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageprocessor\/init(imageurl:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/init(imageURL:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"init","title":"init(imageURL:)","roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageProcessor(im)initWithImageFromURL:","navigatorTitle":[{"kind":"identifier","text":"initWithImageFromURL:"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"imageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(initWithImageFromURL:) ","kind":"text"},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"text":"imageURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"imageURL","content":[{"inlineContent":[{"type":"text","text":"The URL of the image to be loaded and processed."}],"type":"paragraph"}]}]}],"abstract":[{"text":"Initializes a new image processor with the image at the given URL. Returns nil, if the image could not be loaded.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/init(imageURL:)":{"kind":"symbol","type":"topic","title":"init(imageURL:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/init(imageurl:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"imageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"abstract":[{"text":"Initializes a new image processor with the image at the given URL. Returns nil, if the image could not be loaded.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/init(imageURL:)","navigatorTitle":[{"text":"initWithImageFromURL:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor":{"title":"SBSDKImageProcessor","abstract":[{"type":"text","text":"A class to process images."}],"navigatorTitle":[{"text":"SBSDKImageProcessor","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKImageProcessor","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithImageFromURL:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageFromURL:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithImageFromURL:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"imageURL","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The URL of the image to be loaded and processed.","type":"text"}],"type":"paragraph"}],"name":"imageURL"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1init(imageURL:)\/title","op":"replace","value":"initWithImageFromURL:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithImageFromURL:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1init(imageURL:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/title","value":"SBSDKImageProcessor","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/fragments","value":[{"text":"SBSDKImageProcessor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageProcessor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}