{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"JPEG encoding."}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat\/jpeg","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat"]]},"sections":[],"metadata":{"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"case","roleHeading":"Case","title":"SBSDKEncodingFormat.jpeg","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncodingFormatJpeg"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKEncodingFormat@SBSDKEncodingFormatJpeg","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"jpeg","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jpeg"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkencodingformat\/jpeg"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkencodingformat\/jpeg"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncodingFormat":{"title":"SBSDKEncodingFormat","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencodingformat","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncodingFormat"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncodingFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"Image Encoding Format."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncodingFormat/jpeg":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"jpeg","kind":"identifier"}],"role":"symbol","abstract":[{"text":"JPEG encoding.","type":"text"}],"title":"SBSDKEncodingFormat.jpeg","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat\/jpeg","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencodingformat\/jpeg","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncodingFormatJpeg"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKEncodingFormatJpeg"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKEncodingFormatJpeg"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKEncodingFormatJpeg","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKEncodingFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodingFormat\/title"},{"value":[{"text":"SBSDKEncodingFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodingFormat\/fragments"},{"op":"replace","value":[{"text":"SBSDKEncodingFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodingFormat\/navigatorTitle"},{"op":"replace","value":"SBSDKEncodingFormatJpeg","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodingFormat~1jpeg\/title"},{"value":[{"kind":"identifier","text":"SBSDKEncodingFormatJpeg"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodingFormat~1jpeg\/fragments","op":"replace"}]}]}