{"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon\/bezierpath(for:cornerradius:with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon\/bezierpath(for:cornerradius:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(bezierPathForSize:cornerRadius:withTransform:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bezierPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"transform","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGAffineTransform","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGAffineTransform"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"size","content":[{"inlineContent":[{"text":"The size to use to convert the normalized points of the receiver to absolute coordinates.","type":"text"}],"type":"paragraph"}]},{"name":"cornerRadius","content":[{"inlineContent":[{"type":"text","text":"The corner radius of the bezier path."}],"type":"paragraph"}]},{"name":"transform","content":[{"type":"paragraph","inlineContent":[{"text":"The transform to apply to the bezier path.","type":"text"}]}]}]},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An UIBezierPath instance representing the polygon converted to absolute space."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon"]]},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"bezierPathForSize:cornerRadius:withTransform:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bezierPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGAffineTransform","preciseIdentifier":"c:@S@CGAffineTransform"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon(im)bezierPathForSize:cornerRadius:withTransform:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","title":"bezierPath(for:cornerRadius:with:)","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(for:cornerRadius:with:)","interfaceLanguage":"swift"},"abstract":[{"text":"Creates a UIBezierPath instance of the receiver for drawing purposes.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/bezierPath(for:cornerRadius:with:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bezierPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGAffineTransform","kind":"typeIdentifier","text":"CGAffineTransform"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier","text":"UIBezierPath"}],"navigatorTitle":[{"kind":"identifier","text":"bezierPathForSize:cornerRadius:withTransform:"}],"kind":"symbol","title":"bezierPath(for:cornerRadius:with:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(for:cornerRadius:with:)","abstract":[{"type":"text","text":"Creates a UIBezierPath instance of the receiver for drawing purposes."}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/bezierpath(for:cornerradius:with:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"role":"symbol","title":"SBSDKPolygon","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPolygon"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"bezierPathForSize:cornerRadius:withTransform:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bezierPathForSize:cornerRadius:withTransform:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"UIBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath"},{"text":" *) ","kind":"text"},{"text":"bezierPathForSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cornerRadius:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":") ","kind":"text"},{"text":"cornerRadius","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withTransform:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGAffineTransform","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGAffineTransform"},{"text":") ","kind":"text"},{"text":"transform","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"size","content":[{"inlineContent":[{"type":"text","text":"The size to use to convert the normalized points of the receiver to absolute coordinates."}],"type":"paragraph"}]},{"name":"cornerRadius","content":[{"inlineContent":[{"type":"text","text":"The corner radius of the bezier path."}],"type":"paragraph"}]},{"name":"transform","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The transform to apply to the bezier path."}]}]}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"An UIBezierPath instance representing the polygon converted to absolute space.","type":"text"}],"type":"paragraph"}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1bezierPath(for:cornerRadius:with:)\/title","value":"bezierPathForSize:cornerRadius:withTransform:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1bezierPath(for:cornerRadius:with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bezierPathForSize:cornerRadius:withTransform:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","value":"SBSDKPolygon"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","value":[{"kind":"identifier","text":"SBSDKPolygon"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPolygon"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}