{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(with:for:orientation:isFrontCamera:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Creates a UIBezierPath instance of the receiver for drawing purposes."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bezierPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"cornerRadius","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"previewLayer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","kind":"typeIdentifier","text":"AVCaptureVideoPreviewLayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIDeviceOrientation","kind":"typeIdentifier","text":"UIDeviceOrientation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isFrontCamera"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier","text":"UIBezierPath"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The radius to use when drawing rounded corners."}],"type":"paragraph"}],"name":"cornerRadius"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The preview layer the path is going to be presented on.","type":"text"}]}],"name":"previewLayer"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The device orientation. Used to calculate starting point.","type":"text"}]}],"name":"orientation"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Currently used camera - front camera. Used to calculate starting point."}]}],"name":"isFrontCamera"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"An UIBezierPath instance representing the polygon."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon"]]},"metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bezierPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","text":"AVCaptureVideoPreviewLayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIDeviceOrientation","text":"UIDeviceOrientation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isFrontCamera","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath","kind":"typeIdentifier"}],"title":"bezierPath(with:for:orientation:isFrontCamera:)","symbolKind":"method","navigatorTitle":[{"text":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon(im)bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:","modules":[{"name":"ScanbotSDK"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon\/bezierpath(with:for:orientation:isfrontcamera:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon\/bezierpath(with:for:orientation:isfrontcamera:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/bezierPath(with:for:orientation:isFrontCamera:)":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bezierPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVCaptureVideoPreviewLayer","preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIDeviceOrientation","kind":"typeIdentifier","text":"UIDeviceOrientation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isFrontCamera"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier","text":"UIBezierPath"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(with:for:orientation:isFrontCamera:)","abstract":[{"text":"Creates a UIBezierPath instance of the receiver for drawing purposes.","type":"text"}],"title":"bezierPath(with:for:orientation:isFrontCamera:)","navigatorTitle":[{"kind":"identifier","text":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/bezierpath(with:for:orientation:isfrontcamera:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"role":"symbol","title":"SBSDKPolygon","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPolygon"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"bezierPathWithCornerRadius:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cornerRadius"},{"kind":"text","text":" "},{"kind":"identifier","text":"forPreviewLayer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCaptureVideoPreviewLayer","preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"previewLayer"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIDeviceOrientation","preciseIdentifier":"c:@E@UIDeviceOrientation"},{"kind":"text","text":") "},{"kind":"internalParam","text":"orientation"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFrontCamera:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isFrontCamera"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"cornerRadius","content":[{"inlineContent":[{"type":"text","text":"The radius to use when drawing rounded corners."}],"type":"paragraph"}]},{"name":"previewLayer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The preview layer the path is going to be presented on."}]}]},{"name":"orientation","content":[{"inlineContent":[{"text":"The device orientation. Used to calculate starting point.","type":"text"}],"type":"paragraph"}]},{"name":"isFrontCamera","content":[{"inlineContent":[{"type":"text","text":"Currently used camera - front camera. Used to calculate starting point."}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"An UIBezierPath instance representing the polygon.","type":"text"}]}],"kind":"content"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1bezierPath(with:for:orientation:isFrontCamera:)\/title","op":"replace","value":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1bezierPath(with:for:orientation:isFrontCamera:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","op":"replace","value":"SBSDKPolygon"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPolygon"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPolygon"}]}]}]}