{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/init(pdfURL:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes"]]},"abstract":[{"text":"Reads the metadata attributes from an existing PDF file. Returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the file could not be found or contains other than PDF data.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"pdfURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"pdfURL","content":[{"type":"paragraph","inlineContent":[{"text":"A valid and existing file URL of a PDF file.","type":"text"}]}]}]}],"sections":[],"metadata":{"role":"symbol","symbolKind":"init","extendedModule":"ScanbotSDK","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKPDFAttributes(im)initWithPdfURL:","navigatorTitle":[{"text":"initWithPdfURL:","kind":"identifier"}],"title":"init(pdfURL:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"pdfURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":")","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Initializer"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfattributes\/init(pdfurl:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfattributes\/init(pdfurl:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes/init(pdfURL:)":{"type":"topic","kind":"symbol","abstract":[{"text":"Reads the metadata attributes from an existing PDF file. Returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the file could not be found or contains other than PDF data."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/init(pdfURL:)","url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes\/init(pdfurl:)","navigatorTitle":[{"kind":"identifier","text":"initWithPdfURL:"}],"title":"init(pdfURL:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"pdfURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":")"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes":{"role":"symbol","abstract":[{"text":"PDF attributes.","type":"text"}],"title":"SBSDKPDFAttributes","url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFAttributes","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPDFAttributes","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithPdfURL:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPdfURL:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithPdfURL:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"pdfURL","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"pdfURL","content":[{"inlineContent":[{"text":"A valid and existing file URL of a PDF file.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1init(pdfURL:)\/title","op":"replace","value":"initWithPdfURL:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1init(pdfURL:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPdfURL:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/title","op":"replace","value":"SBSDKPDFAttributes"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFAttributes"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFAttributes"}]}]}]}