{"abstract":[{"text":"Rectangle of the barcode in the image.","type":"text"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"rectangle"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rectangle","kind":"identifier"},{"text":": [","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVINBarcodeResult(py)rectangle","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","title":"rectangle"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinbarcoderesult\/rectangle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinbarcoderesult\/rectangle"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rectangle"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":"]"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult\/rectangle","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeResult":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINBarcodeResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult","title":"SBSDKVINBarcodeResult","url":"\/documentation\/scanbotsdk\/sbsdkvinbarcoderesult","navigatorTitle":[{"text":"SBSDKVINBarcodeResult","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Result of the barcode scanner.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeResult/rectangle":{"url":"\/documentation\/scanbotsdk\/sbsdkvinbarcoderesult\/rectangle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult\/rectangle","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rectangle","kind":"identifier"},{"text":": [","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[{"text":"Rectangle of the barcode in the image.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"rectangle","kind":"identifier"}],"title":"rectangle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"rectangle","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"rectangle"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSValue *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"rectangle"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/title","value":"SBSDKVINBarcodeResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/fragments","value":[{"text":"SBSDKVINBarcodeResult","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKVINBarcodeResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/navigatorTitle","op":"replace"},{"value":"rectangle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult~1rectangle\/title","op":"replace"},{"value":[{"kind":"identifier","text":"rectangle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult~1rectangle\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}