{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPermissionScreen"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2camerapermissionscreen\/initwithstatusbarmode:background:iconbackground:icon:enablecamerabutton:closebutton:enablecameratitle:enablecameraexplanation:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2CameraPermissionScreen(im)initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","title":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPermissionScreen\/initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithStatusBarMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2StatusBarMode","text":"SBSDKUI2StatusBarMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StatusBarMode"},{"text":") ","kind":"text"},{"text":"statusBarMode","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"background:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"background"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconBackground:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" *) "},{"text":"iconBackground","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"icon:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2IconStyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconStyle","text":"SBSDKUI2IconStyle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"icon","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"enableCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"enableCameraButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"closeButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"closeButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"enableCameraTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"enableCameraTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"enableCameraExplanation:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"enableCameraExplanation","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2StatusBarMode":{"navigatorTitle":[{"text":"SBSDKUI2StatusBarMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StatusBarMode","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2statusbarmode","type":"topic","title":"SBSDKUI2StatusBarMode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StatusBarMode","kind":"identifier"}],"abstract":[{"text":"The visual mode used for the status bar icons.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraPermissionScreen":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPermissionScreen","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2camerapermissionscreen","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Configuration of the camera permission request view.","type":"text"}],"title":"SBSDKUI2CameraPermissionScreen","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2StyledText":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","title":"SBSDKUI2StyledText","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2styledtext","abstract":[{"text":"Configuration of the text field appearance.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2StyledText"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraPermissionScreen/initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:":{"kind":"symbol","navigatorTitle":[{"text":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","kind":"identifier"}],"role":"symbol","title":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPermissionScreen\/initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2camerapermissionscreen\/initwithstatusbarmode:background:iconbackground:icon:enablecamerabutton:closebutton:enablecameratitle:enablecameraexplanation:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Color":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2color","title":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","type":"topic","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"abstract":[],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ButtonConfiguration":{"type":"topic","title":"SBSDKUI2ButtonConfiguration","abstract":[{"text":"Configuration of the button.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2buttonconfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ButtonConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IconStyle":{"abstract":[{"type":"text","text":"Configuration of the icon appearance."}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2iconstyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"title":"SBSDKUI2IconStyle","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconStyle","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StatusBarMode\/title","value":"SBSDKUI2StatusBarMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StatusBarMode\/fragments","value":[{"text":"SBSDKUI2StatusBarMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StatusBarMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2StatusBarMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPermissionScreen\/title","value":"SBSDKUI2CameraPermissionScreen","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPermissionScreen\/fragments","value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPermissionScreen\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/title","value":"SBSDKUI2StyledText","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/fragments","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/navigatorTitle","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/fragments","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ButtonConfiguration\/title","value":"SBSDKUI2ButtonConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ButtonConfiguration\/fragments","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconStyle\/title","value":"SBSDKUI2IconStyle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconStyle\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconStyle\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}