{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode\/untrusted","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The extracted document is not trusted, i.e. its authenticity cannot be assumed. All fields will be read out"},{"type":"text","text":" "},{"type":"text","text":"independently and can be further verified. Extracting untrusted documents takes slightly longer, as the"},{"type":"text","text":" "},{"type":"text","text":"extractor is not allowed to employ certain time-saving optimizations."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumenttrustmode\/untrusted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumenttrustmode\/untrusted"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"untrusted"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Case","title":"SBSDKDocumentTrustMode.untrusted","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentTrustModeUntrusted"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"untrusted"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentTrustMode@SBSDKDocumentTrustModeUntrusted","symbolKind":"case","role":"symbol"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentTrustMode/untrusted":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumenttrustmode\/untrusted","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentTrustModeUntrusted"}],"title":"SBSDKDocumentTrustMode.untrusted","abstract":[{"type":"text","text":"The extracted document is not trusted, i.e. its authenticity cannot be assumed. All fields will be read out"},{"type":"text","text":" "},{"text":"independently and can be further verified. Extracting untrusted documents takes slightly longer, as the","type":"text"},{"text":" ","type":"text"},{"text":"extractor is not allowed to employ certain time-saving optimizations.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"untrusted"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode\/untrusted","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentTrustMode":{"kind":"symbol","abstract":[{"type":"text","text":"Level of trust in the authenticity of the extracted document."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentTrustMode"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentTrustMode"}],"title":"SBSDKDocumentTrustMode","url":"\/documentation\/scanbotsdk\/sbsdkdocumenttrustmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKDocumentTrustModeUntrusted","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKDocumentTrustModeUntrusted"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKDocumentTrustModeUntrusted"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentTrustModeUntrusted","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentTrustMode~1untrusted\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentTrustModeUntrusted"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentTrustMode~1untrusted\/fragments"},{"value":"SBSDKDocumentTrustMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentTrustMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentTrustMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentTrustMode\/fragments"},{"value":[{"text":"SBSDKDocumentTrustMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentTrustMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}