{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mod1110NCR"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1110NCR"},"abstract":[{"type":"text","text":"Mod1110NCR."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod1110ncr"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod1110ncr"]}],"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeMSIPlesseyChecksumAlgorithm@SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110NCR","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110NCR"}],"title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod1110NCR","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mod1110NCR","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm","navigatorTitle":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}],"abstract":[{"text":"The checksum algorithm for MSI-Plessey type barcodes.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod1110NCR":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1110NCR","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod1110NCR","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110NCR","kind":"identifier"}],"abstract":[{"text":"Mod1110NCR.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod1110ncr","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mod1110NCR"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110NCR"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110NCR"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110NCR"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/title","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/fragments","value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/navigatorTitle","value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod1110NCR\/title","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110NCR","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110NCR"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod1110NCR\/fragments"}]}]}