{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController\/cameraSession:didChangeDevice:"},"metadata":{"roleHeading":"Instance Method","title":"cameraSession:didChangeDevice:","role":"symbol","externalID":"c:@CM@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerViewController(im)cameraSession:didChangeDevice:","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"text":"cameraSession:didChangeDevice:","kind":"identifier"}],"navigatorTitle":[{"text":"cameraSession:didChangeDevice:","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"cameraSession:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession","text":"SBSDKCameraSession","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraSession"},{"kind":"text","text":" *) "},{"text":"session","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didChangeDevice:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKCameraDevice","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevice","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraDevice","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"device","kind":"internalParam"},{"kind":"text","text":";"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/camerasession:didchangedevice:"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewController":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A highly customizable camera view controller that delivers a basic camera functionality along with video"},{"type":"text","text":" "},{"text":"frame extraction and preprocessing, orientation correction and still image capturing.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"title":"SBSDKBaseScannerViewController","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession":{"role":"symbol","abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"text":" ","type":"text"},{"text":"camera device and the preview layer. Provides functionality to capture still images.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCameraSession"}],"title":"SBSDKCameraSession","navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDevice":{"kind":"symbol","title":"SBSDKCameraDevice","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevice","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKCameraDevice","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevice","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDevice"}],"abstract":[{"text":"The camera device to be used with a ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewController/cameraSession:didChangeDevice:":{"fragments":[{"text":"- ","kind":"text"},{"text":"cameraSession:didChangeDevice:","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraSession:didChangeDevice:"}],"title":"cameraSession:didChangeDevice:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController\/cameraSession:didChangeDevice:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/camerasession:didchangedevice:","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","title":"ScanbotDocumentScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKBaseScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/navigatorTitle","value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"op":"replace"},{"value":"SBSDKCameraSession","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraSession"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCameraSession"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevice\/title","value":"SBSDKCameraDevice","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevice\/fragments","op":"replace","value":[{"text":"SBSDKCameraDevice","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevice\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCameraDevice"}]}]}]}