{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:didFailScanning:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontrollerdelegate\/barcodescanandcount(_:didfailscanning:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontrollerdelegate\/barcodescanandcount(_:didfailscanning:)"]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(barcodeScanAndCountController:didFailScanningWithError:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeScanAndCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController","text":"SBSDKBarcodeScanAndCountViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanAndCountViewController"},{"text":", ","kind":"text"},{"text":"didFailScanning","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The calling ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController","type":"reference"},{"text":".","type":"text"}]}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error that occurred during scanning."}]}],"name":"error"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"barcodeScanAndCountController:didFailScanningWithError:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeScanAndCount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKBarcodeScanAndCountViewController","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanAndCountViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailScanning"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"title":"barcodeScanAndCount(_:didFailScanning:)","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKBarcodeScanAndCountViewControllerDelegate(im)barcodeScanAndCountController:didFailScanningWithError:","required":true,"roleHeading":"Instance Method","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method"},"abstract":[{"text":"Informs the delegate that the receiver has scanned some barcodes or failed scanning with an error.","type":"text"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewControllerDelegate":{"type":"topic","role":"symbol","title":"SBSDKBarcodeScanAndCountViewControllerDelegate","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A delegate protocol to handle the barcode results from ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewControllerDelegate/barcodeScanAndCount(_:didFailScanning:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:didFailScanning:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeScanAndCount","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanAndCountViewController","text":"SBSDKBarcodeScanAndCountViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailScanning","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","required":true,"type":"topic","role":"symbol","navigatorTitle":[{"text":"barcodeScanAndCountController:didFailScanningWithError:","kind":"identifier"}],"title":"barcodeScanAndCount(_:didFailScanning:)","abstract":[{"text":"Informs the delegate that the receiver has scanned some barcodes or failed scanning with an error.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontrollerdelegate\/barcodescanandcount(_:didfailscanning:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewController":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontroller","kind":"symbol","title":"SBSDKBarcodeScanAndCountViewController","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode scanner."},{"type":"text","text":" "},{"type":"text","text":"Screen also shows snap, scan more and reset buttons."},{"type":"text","text":" "},{"type":"text","text":"The snap button starts the scanning when tapped."},{"type":"text","text":" "},{"type":"text","text":"The snap button resets the scanning when tapped again."},{"type":"text","text":" "},{"type":"text","text":"Instead it is installing itself as a child view controller onto a given parent view controller."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"barcodeScanAndCountController:didFailScanningWithError:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"barcodeScanAndCountController:didFailScanningWithError:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"barcodeScanAndCountController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeScanAndCountViewController","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanAndCountViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didFailScanningWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"The calling "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"text":"The error that occurred during scanning.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate\/title","value":"SBSDKBarcodeScanAndCountViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate\/fragments","value":[{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:didFailScanning:)\/title","value":"barcodeScanAndCountController:didFailScanningWithError:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:didFailScanning:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeScanAndCountController:didFailScanningWithError:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/title","value":"SBSDKBarcodeScanAndCountViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}],"op":"replace"}]}]}