{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Analytics manager for tracking events.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/analytics","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"analytics","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKAnalyticsManager","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsManager","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAnalyticsManager"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbot\/analytics"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbot\/analytics"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"analytics","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)Scanbot(cpy)analytics","roleHeading":"Type Property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"analytics","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKAnalyticsManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAnalyticsManager"}],"title":"analytics","symbolKind":"property"},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Scanbot/analytics":{"role":"symbol","abstract":[{"type":"text","text":"Analytics manager for tracking events."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"analytics","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKAnalyticsManager","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAnalyticsManager","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/scanbot\/analytics","type":"topic","title":"analytics","navigatorTitle":[{"text":"analytics","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/analytics","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAnalyticsManager":{"role":"symbol","abstract":[{"type":"codeVoice","code":"SBSDKAnalyticsManager"},{"type":"text","text":" is a singleton class that manages analytics events within the Scanbot SDK."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsManager","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkanalyticsmanager","type":"topic","title":"SBSDKAnalyticsManager","navigatorTitle":[{"text":"SBSDKAnalyticsManager","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsManager","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Scanbot":{"url":"\/documentation\/scanbotdocumentscannersdk\/scanbot","title":"Scanbot","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot","navigatorTitle":[{"kind":"identifier","text":"Scanbot"}],"abstract":[{"text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Scanbot"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"analytics","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"analytics","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKAnalyticsManager","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAnalyticsManager","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsManager"},{"kind":"text","text":" * "},{"kind":"identifier","text":"analytics"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot~1analytics\/title","value":"analytics","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot~1analytics\/fragments","value":[{"kind":"identifier","text":"analytics"}],"op":"replace"},{"value":"SBSDKAnalyticsManager","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsManager\/title"},{"value":[{"text":"SBSDKAnalyticsManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsManager\/fragments"},{"value":[{"text":"SBSDKAnalyticsManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsManager\/navigatorTitle"},{"value":"Scanbot","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/title"},{"value":[{"kind":"identifier","text":"Scanbot"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/fragments"},{"value":[{"text":"Scanbot","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/navigatorTitle"}]}]}