{"abstract":[{"type":"text","text":"Found dates."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult\/dates","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult"]]},"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dates","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"SBSDKMedicalCertificateDateRecord","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateDateRecord"},{"text":">","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"text":"dates","kind":"identifier"}],"roleHeading":"Instance Property","title":"dates","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult(py)dates"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult\/dates"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult\/dates"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dates","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"SBSDKMedicalCertificateDateRecord","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateDateRecord","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord"},{"text":">","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanningResult/dates":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult\/dates","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dates"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateDateRecord","kind":"typeIdentifier","text":"SBSDKMedicalCertificateDateRecord"},{"kind":"text","text":">"}],"navigatorTitle":[{"kind":"identifier","text":"dates"}],"kind":"symbol","role":"symbol","title":"dates","type":"topic","abstract":[{"type":"text","text":"Found dates."}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult\/dates"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanningResult":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult","role":"symbol","abstract":[{"type":"text","text":"The result of the medical certificate scanning."}],"title":"SBSDKMedicalCertificateScanningResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord":{"type":"topic","title":"SBSDKMedicalCertificateDateRecord","kind":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateDateRecord","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateDateRecord","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord","abstract":[{"type":"text","text":"Structure to contain date record information."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"dates","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"dates"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKMedicalCertificateDateRecord *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dates"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"dates","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult~1dates\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult~1dates\/fragments","value":[{"text":"dates","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/title","value":"SBSDKMedicalCertificateScanningResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/fragments","value":[{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord\/title","value":"SBSDKMedicalCertificateDateRecord"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecord"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecord"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}