{"abstract":[{"type":"text","text":"Language data for text recognition is missing."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"OCRLanguageMissing","kind":"identifier"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrorcode\/ocrlanguagemissing"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrorcode\/ocrlanguagemissing"]}],"metadata":{"title":"SBSDKErrorCode.OCRLanguageMissing","externalID":"c:@M@ScanbotSDK@E@SBSDKErrorCode@SBSDKErrorCodeOCRLanguageMissing","roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCRLanguageMissing"}],"navigatorTitle":[{"text":"SBSDKErrorCodeOCRLanguageMissing","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/OCRLanguageMissing","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/OCRLanguageMissing":{"title":"SBSDKErrorCode.OCRLanguageMissing","url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/ocrlanguagemissing","role":"symbol","abstract":[{"type":"text","text":"Language data for text recognition is missing."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/OCRLanguageMissing","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodeOCRLanguageMissing"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OCRLanguageMissing","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKErrorCode","kind":"identifier"}],"abstract":[{"text":"The error codes in the SBSDKErrorDomain.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkerrorcode","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode","title":"SBSDKErrorCode","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCode"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKErrorCodeOCRLanguageMissing","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"SBSDKErrorCodeOCRLanguageMissing","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKErrorCodeOCRLanguageMissing","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1OCRLanguageMissing\/title","value":"SBSDKErrorCodeOCRLanguageMissing"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1OCRLanguageMissing\/fragments","value":[{"text":"SBSDKErrorCodeOCRLanguageMissing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/title","value":"SBSDKErrorCode"},{"value":[{"kind":"identifier","text":"SBSDKErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/fragments"},{"value":[{"text":"SBSDKErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}