{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen\/tojson(configuration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen\/tojson(configuration:)"]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen(im)toJsonWithConfiguration:","title":"toJson(configuration:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen"]]},"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen\/toJson(configuration:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":" = SBSDKToJSONConfiguration()) -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPermissionScreen/toJson(configuration:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen\/toJson(configuration:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen\/tojson(configuration:)","title":"toJson(configuration:)","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKToJSONConfiguration":{"abstract":[{"type":"text","text":"Configuration used to serialize an object to json."}],"title":"SBSDKToJSONConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKToJSONConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKToJSONConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdktojsonconfiguration","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKToJSONConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPermissionScreen":{"abstract":[{"type":"text","text":"Configuration of the camera permission request view."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen","title":"SBSDKUI2CameraPermissionScreen","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKToJSONConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen~1toJson(configuration:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen~1toJson(configuration:)\/fragments"},{"value":"SBSDKToJSONConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKToJSONConfiguration\/title"},{"value":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKToJSONConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKToJSONConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKToJSONConfiguration\/navigatorTitle"},{"value":"SBSDKUI2CameraPermissionScreen","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/title"},{"value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/fragments"},{"value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}