{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorType\/invalidImageRef"},"metadata":{"role":"symbol","title":"SBSDKErrorType.invalidImageRef","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKErrorType@SBSDKErrorTypeInvalidImageRef","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidImageRef"}],"roleHeading":"Case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeInvalidImageRef"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkerrortype\/invalidimageref"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkerrortype\/invalidimageref"]}],"abstract":[{"type":"text","text":"An invalid image reference was provided or the image data is corrupted."}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidImageRef"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorType":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrortype","abstract":[{"text":"An Objective-C compatible enum representing the types of errors that can occur within the Scanbot SDK.","type":"text"},{"text":" ","type":"text"},{"text":"Each case corresponds to a specific error code.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorType","kind":"symbol","title":"SBSDKErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKErrorType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKErrorType","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorType/invalidImageRef":{"abstract":[{"text":"An invalid image reference was provided or the image data is corrupted.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeInvalidImageRef"}],"title":"SBSDKErrorType.invalidImageRef","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorType\/invalidImageRef","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrortype\/invalidimageref","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidImageRef"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKErrorTypeInvalidImageRef","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKErrorTypeInvalidImageRef","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKErrorTypeInvalidImageRef"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKErrorType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorType\/title"},{"value":[{"text":"SBSDKErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorType\/fragments"},{"op":"replace","value":[{"text":"SBSDKErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorType\/navigatorTitle"},{"op":"replace","value":"SBSDKErrorTypeInvalidImageRef","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorType~1invalidImageRef\/title"},{"op":"replace","value":[{"text":"SBSDKErrorTypeInvalidImageRef","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorType~1invalidImageRef\/fragments"}]}]}