{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"appIDMismatch"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklicensestatus\/appidmismatch"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdklicensestatus\/appidmismatch"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/appIDMismatch","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Invalid license. The license is not valid for this application."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"appIDMismatch"}],"title":"SBSDKLicenseStatus.appIDMismatch","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKLicenseStatus@SBSDKLicenseStatusAppIDMismatch","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusAppIDMismatch"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus":{"role":"symbol","title":"SBSDKLicenseStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseStatus"}],"abstract":[{"type":"text","text":"The status of the ScanbotSDK license."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"url":"\/documentation\/scanbotsdk\/sbsdklicensestatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/appIDMismatch":{"role":"symbol","title":"SBSDKLicenseStatus.appIDMismatch","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"appIDMismatch"}],"abstract":[{"type":"text","text":"Invalid license. The license is not valid for this application."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/appIDMismatch","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusAppIDMismatch"}],"url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/appidmismatch"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKLicenseStatusAppIDMismatch"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKLicenseStatusAppIDMismatch"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKLicenseStatusAppIDMismatch"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/title","value":"SBSDKLicenseStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKLicenseStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1appIDMismatch\/title","value":"SBSDKLicenseStatusAppIDMismatch"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1appIDMismatch\/fragments","value":[{"kind":"identifier","text":"SBSDKLicenseStatusAppIDMismatch"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}