{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"corrupted"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/corrupted","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklicensestatus\/corrupted"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicensestatus\/corrupted"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Invalid license. License contains corrupted data."}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"corrupted"}],"symbolKind":"case","title":"SBSDKLicenseStatus.corrupted","externalID":"c:@M@ScanbotSDK@E@SBSDKLicenseStatus@SBSDKLicenseStatusCorrupted","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusCorrupted"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/corrupted":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/corrupted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"corrupted","kind":"identifier"}],"title":"SBSDKLicenseStatus.corrupted","url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/corrupted","abstract":[{"type":"text","text":"Invalid license. License contains corrupted data."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKLicenseStatusCorrupted","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus":{"abstract":[{"type":"text","text":"The status of the ScanbotSDK license."}],"url":"\/documentation\/scanbotsdk\/sbsdklicensestatus","title":"SBSDKLicenseStatus","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicenseStatus"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatus"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKLicenseStatusCorrupted"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKLicenseStatusCorrupted"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKLicenseStatusCorrupted"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1corrupted\/title","op":"replace","value":"SBSDKLicenseStatusCorrupted"},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatusCorrupted"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1corrupted\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/title","value":"SBSDKLicenseStatus"},{"op":"replace","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}