{"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/hashValue"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/hash(into:)"]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklicensestatus\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus"]]},"sections":[],"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"ScanbotSDK"}],"title":"RawRepresentable Implementations"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/RawRepresentable-Implementations"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/hashValue":{"url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/hashvalue","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/hashValue","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"title":"hashValue"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus":{"kind":"symbol","title":"SBSDKLicenseStatus","navigatorTitle":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklicensestatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseStatus","kind":"identifier"}],"abstract":[{"text":"The status of the ScanbotSDK license.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/hash(into:)":{"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"kind":"text","text":")"}],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"title":"hash(into:)","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/hash(into:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/hash(into:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/title","value":"SBSDKLicenseStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/fragments","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/navigatorTitle","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}]}]}]}