{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession\/maxopticalzoom"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession\/maxopticalzoom"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCameraSession(py)maxOpticalZoom","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxOpticalZoom"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"maxOpticalZoom"}],"roleHeading":"Instance Property","title":"maxOpticalZoom","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"The camera devices maximum optical zoom factor. Readonly.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession\/maxOpticalZoom","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxOpticalZoom","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":" { get }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Setting higher zoom factor will result in digital zooming and degraded image quality."}]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraSession":{"abstract":[{"text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"title":"SBSDKCameraSession","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSession"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSession"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraSession/maxOpticalZoom":{"kind":"symbol","title":"maxOpticalZoom","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession\/maxOpticalZoom","abstract":[{"text":"The camera devices maximum optical zoom factor. Readonly.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession\/maxopticalzoom","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"maxOpticalZoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"maxOpticalZoom","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"maxOpticalZoom"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"maxOpticalZoom","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxOpticalZoom"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/title","value":"SBSDKCameraSession","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/fragments","value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraSession"}]},{"value":"maxOpticalZoom","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession~1maxOpticalZoom\/title"},{"value":[{"text":"maxOpticalZoom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession~1maxOpticalZoom\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}