{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession\/removeSessionObserver(_:)","interfaceLanguage":"swift"},"metadata":{"title":"removeSessionObserver(_:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"removeSessionObserver:"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeSessionObserver"},{"text":"(","kind":"text"},{"text":"SBSDKCameraSessionObserving","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKCameraSessionObserving","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCameraSession(im)removeSessionObserver:","roleHeading":"Instance Method","role":"symbol"},"abstract":[{"type":"text","text":"Removes an observer from the list of observers."}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession\/removesessionobserver(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession\/removesessionobserver(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeSessionObserver"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"observer","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSessionObserving","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKCameraSessionObserving","kind":"typeIdentifier","text":"SBSDKCameraSessionObserving"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The observer that should no longer listen to state changes.","type":"text"}]}],"name":"observer"}],"kind":"parameters"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession"]]},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraSession":{"abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"type":"text","text":" "},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"title":"SBSDKCameraSession","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSession"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraSession/removeSessionObserver(_:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession\/removeSessionObserver(_:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession\/removesessionobserver(_:)","navigatorTitle":[{"kind":"identifier","text":"removeSessionObserver:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeSessionObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKCameraSessionObserving","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKCameraSessionObserving"},{"kind":"text","text":")"}],"abstract":[{"text":"Removes an observer from the list of observers.","type":"text"}],"role":"symbol","title":"removeSessionObserver(_:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraSessionObserving":{"abstract":[{"type":"text","text":"A multicast-observer protocol that informs its observers about state changes of a camera session."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSessionObserving"}],"title":"SBSDKCameraSessionObserving","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSessionObserving"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasessionobserving","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSessionObserving","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"removeSessionObserver:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeSessionObserver:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"removeSessionObserver:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SBSDKCameraSessionObserving>","preciseIdentifier":"c:Qo@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKCameraSessionObserving"},{"text":") ","kind":"text"},{"text":"observer","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The observer that should no longer listen to state changes."}]}],"name":"observer"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/title","value":"SBSDKCameraSession"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraSession"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCameraSession"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession~1removeSessionObserver(_:)\/title","value":"removeSessionObserver:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession~1removeSessionObserver(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"removeSessionObserver:","kind":"identifier"}],"op":"replace"},{"value":"SBSDKCameraSessionObserving","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSessionObserving\/title"},{"value":[{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSessionObserving\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSessionObserving\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraSessionObserving"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}