{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The color of the barcode polygon when selected."}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonSelectedColor","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonSelectedColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle\/polygonselectedcolor"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle\/polygonselectedcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle"]]},"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle(py)polygonSelectedColor","roleHeading":"Instance Property","navigatorTitle":[{"text":"polygonSelectedColor","kind":"identifier"}],"title":"polygonSelectedColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"polygonSelectedColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewPolygonStyle":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}],"kind":"symbol","title":"SBSDKBarcodeTrackedViewPolygonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle","abstract":[{"text":"A class that represents the style of the polygon rendered around a barcode in ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayController":{"navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"kind":"symbol","title":"SBSDKBarcodeTrackingOverlayController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontroller","abstract":[{"text":"A class that represents an overlay used for visualizing detected barcodes.","type":"text"},{"type":"text","text":" "},{"text":"It provides a customizable user interface for displaying barcodes and supports interaction with them.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The overlay can be used to highlight and select barcodes based on user input."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewPolygonStyle/polygonSelectedColor":{"navigatorTitle":[{"text":"polygonSelectedColor","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle\/polygonselectedcolor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonSelectedColor","title":"polygonSelectedColor","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonSelectedColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"kind":"symbol","abstract":[{"text":"The color of the barcode polygon when selected.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"polygonSelectedColor"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"polygonSelectedColor","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"polygonSelectedColor"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle\/title","op":"replace","value":"SBSDKBarcodeTrackedViewPolygonStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle\/fragments","value":[{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"identifier"}]},{"value":"SBSDKBarcodeTrackingOverlayController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1polygonSelectedColor\/title","value":"polygonSelectedColor","op":"replace"},{"value":[{"kind":"identifier","text":"polygonSelectedColor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1polygonSelectedColor\/fragments"}]}]}