{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldInvalidDataVerificationReport"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithFieldFullName:isInvalid:"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldInvalidDataVerificationReport(im)initWithFieldFullName:isInvalid:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFieldFullName:isInvalid:"}],"modules":[{"name":"ScanbotSDK"}],"title":"initWithFieldFullName:isInvalid:","symbolKind":"method","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfieldinvaliddataverificationreport\/initwithfieldfullname:isinvalid:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFieldFullName:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fieldFullName"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInvalid:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isInvalid","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldInvalidDataVerificationReport\/initWithFieldFullName:isInvalid:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldInvalidDataVerificationReport/initWithFieldFullName:isInvalid:":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkfieldinvaliddataverificationreport\/initwithfieldfullname:isinvalid:","title":"initWithFieldFullName:isInvalid:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldInvalidDataVerificationReport\/initWithFieldFullName:isInvalid:","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithFieldFullName:isInvalid:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFieldFullName:isInvalid:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldInvalidDataVerificationReport":{"abstract":[{"type":"text","text":"Report which shows whether the data in the field that can be validated is valid."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldInvalidDataVerificationReport","url":"\/documentation\/scanbotsdk\/sbsdkfieldinvaliddataverificationreport","title":"SBSDKFieldInvalidDataVerificationReport","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFieldInvalidDataVerificationReport"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKFieldInvalidDataVerificationReport"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKFieldInvalidDataVerificationReport","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldInvalidDataVerificationReport\/title"},{"value":[{"text":"SBSDKFieldInvalidDataVerificationReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldInvalidDataVerificationReport\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKFieldInvalidDataVerificationReport"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldInvalidDataVerificationReport\/navigatorTitle"}]}]}