{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/enableCameraUIConfiguration","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/enablecamerauiconfiguration"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraUIConfiguration","text":"SBSDKUIEnableCameraUIConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"enableCameraUIConfiguration"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"enableCameraUIConfiguration","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerViewController(py)enableCameraUIConfiguration","roleHeading":"Instance Property","fragments":[{"text":"enableCameraUIConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"enableCameraUIConfiguration","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraUIConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuienablecamerauiconfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration for the user interface of camera based view controllers.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraUIConfiguration","title":"SBSDKUIEnableCameraUIConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller","role":"symbol","title":"SBSDKUICheckScannerViewController","abstract":[{"text":"A Ready-To-Use viewController to scan checks using the camera.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController/enableCameraUIConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/enableCameraUIConfiguration","title":"enableCameraUIConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/enablecamerauiconfiguration","fragments":[{"text":"enableCameraUIConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUIEnableCameraUIConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraUIConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIEnableCameraUIConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraUIConfiguration\/fragments"},{"value":[{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraUIConfiguration\/navigatorTitle"},{"value":"SBSDKUICheckScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/navigatorTitle"}]}]}