{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleScanningMode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleScanningMode\/init(countingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplescanningmode\/init(countingrepeatdelay:mode:sheet:sheetcontent:manualcounteditdialog:barcodeinfomapping:aroverlay:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplescanningmode\/init(countingrepeatdelay:mode:sheet:sheetcontent:manualcounteditdialog:barcodeinfomapping:aroverlay:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2MultipleScanningMode(im)initWithCountingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"init(countingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithCountingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","kind":"identifier"}],"symbolKind":"init","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"countingRepeatDelay"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"text":"SBSDKUI2MultipleBarcodesScanningMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MultipleBarcodesScanningMode","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"sheet","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Sheet","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Sheet"},{"kind":"text","text":", "},{"text":"sheetContent","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2SheetContent","text":"SBSDKUI2SheetContent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"manualCountEditDialog"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ManualCountEditDialog","text":"SBSDKUI2ManualCountEditDialog"},{"kind":"text","text":", "},{"text":"barcodeInfoMapping","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeInfoMapping"},{"kind":"text","text":", "},{"text":"arOverlay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration","text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"countingRepeatDelay","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = 1000, ","kind":"text"},{"text":"mode","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MultipleBarcodesScanningMode","text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"typeIdentifier"},{"text":" = SBSDKUI2MultipleBarcodesScanningMode.counting, ","kind":"text"},{"kind":"externalParam","text":"sheet"},{"kind":"text","text":": "},{"text":"SBSDKUI2Sheet","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Sheet","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet"},{"text":" = SBSDKUI2Sheet(mode: SBSDKUI2SheetMode.collapsedSheet,\n                                                     collapsedVisibleHeight: SBSDKUI2CollapsedVisibleHeight.small,\n                                                     listButton: SBSDKUI2BadgedButton(badgeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                          isArgb: false),\n                                                                                      badgeForegroundColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                          isArgb: false),\n                                                                                      visible: true,\n                                                                                      backgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                     isArgb: false),\n                                                                                      foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                     isArgb: false),\n                                                                                      activeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                           isArgb: false),\n                                                                                      activeForegroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                           isArgb: false))), ","kind":"text"},{"kind":"externalParam","text":"sheetContent"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2SheetContent","text":"SBSDKUI2SheetContent","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2SheetContent(sheetColor: SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false),\n                                         dividerColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                     isArgb: false),\n                                         manualCountChangeEnabled: true,\n                                         manualCountOutlineColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                                isArgb: false),\n                                         manualCountChangeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                               isArgb: false),\n                                         title: SBSDKUI2StyledText(text: \"?multipleModeSheetTitle\",\n                                                                   color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                        isArgb: false)),\n                                         clearAllButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                     text: \"?sheetClearAllButton\",\n                                                                                     background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                    isArgb: false),\n                                                                                                                         fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                  isArgb: false),\n                                                                                                                         strokeWidth: 1.0),\n                                                                                     foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                              isArgb: false),\n                                                                                                                         useShadow: false)),\n                                         barcodeItemTitle: SBSDKUI2StyledText(visible: true,\n                                                                              text: \"BARCODE_TITLE\",\n                                                                              color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                   isArgb: false),\n                                                                              useShadow: false),\n                                         barcodeItemSubtitle: SBSDKUI2StyledText(visible: true,\n                                                                                 text: \"BARCODE_SUBTITLE\",\n                                                                                 color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                      isArgb: false),\n                                                                                 useShadow: false),\n                                         barcodeItemImageVisible: true,\n                                         submitButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                   text: \"?sheetSubmitButton\",\n                                                                                   background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                  isArgb: false),\n                                                                                                                       fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                isArgb: false),\n                                                                                                                       strokeWidth: 1.0),\n                                                                                   foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                       color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                            isArgb: false),\n                                                                                                                       useShadow: false)),\n                                         startScanningButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                          text: \"?sheetStartScanningButton\",\n                                                                                          background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                              fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                       isArgb: false),\n                                                                                                                              strokeWidth: 1.0),\n                                                                                          foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                              color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                   isArgb: false),\n                                                                                                                              useShadow: false)),\n                                         placeholderTitle: SBSDKUI2StyledText(visible: true,\n                                                                              text: \"?sheetPlaceholderTitle\",\n                                                                              color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                   isArgb: false),\n                                                                              useShadow: false),\n                                         placeholderSubtitle: SBSDKUI2StyledText(visible: true,\n                                                                                 text: \"?sheetPlaceholderSubtitle\",\n                                                                                 color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                      isArgb: false),\n                                                                                 useShadow: false),\n                                         placeholderIconBackground: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                                  isArgb: false),\n                                         placeholderIcon: SBSDKUI2IconStyle(visible: true,\n                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                 isArgb: false)),\n                                         swipeToDelete: SBSDKUI2SwipeToDelete(enabled: true,\n                                                                              backgroundColor: SBSDKUI2Color(colorString: \"?sbColorNegative\",\n                                                                                                             isArgb: false),\n                                                                              iconColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                       isArgb: false))), "},{"text":"manualCountEditDialog","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ManualCountEditDialog","text":"SBSDKUI2ManualCountEditDialog","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ManualCountEditDialog"},{"text":" = SBSDKUI2ManualCountEditDialog(sheetColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                            isArgb: false),\n                                                  dividerColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                              isArgb: false),\n                                                  modalOverlayColor: SBSDKUI2Color(colorString: \"?sbColorModalOverlay\",\n                                                                                   isArgb: false),\n                                                  title: SBSDKUI2StyledText(text: \"?manualCountEditDialogTitle\",\n                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                 isArgb: false)),\n                                                  info: SBSDKUI2StyledText(text: \"?manualCountEditDialogInfo\",\n                                                                           color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                isArgb: false)),\n                                                  updateButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                            text: \"?manualCountEditDialogUpdateButton\",\n                                                                                            background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                           isArgb: false),\n                                                                                                                                fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                                strokeWidth: 1.0),\n                                                                                            foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                                color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                                useShadow: false)),\n                                                  cancelButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                            text: \"?manualCountEditDialogCancelButton\",\n                                                                                            background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                           isArgb: false),\n                                                                                                                                fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                                strokeWidth: 1.0),\n                                                                                            foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                                color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                                useShadow: false)),\n                                                  clearTextButton: SBSDKUI2IconStyle(visible: true,\n                                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                          isArgb: false))), ","kind":"text"},{"text":"barcodeInfoMapping","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier","text":"SBSDKUI2BarcodeInfoMapping","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeInfoMapping"},{"kind":"text","text":" = SBSDKUI2BarcodeInfoMapping(sheetColor: SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false),\n                                               dividerColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                           isArgb: false),\n                                               modalOverlayColor: SBSDKUI2Color(colorString: \"?sbColorModalOverlay\",\n                                                                                isArgb: false),\n                                               loadingMessage: SBSDKUI2StyledText(text: \"?barcodeInfoMappingLoadingMessage\",\n                                                                                  color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                       isArgb: false)),\n                                               errorState: SBSDKUI2BarcodeItemErrorState(title: SBSDKUI2StyledText(text: \"?barcodeInfoMappingErrorStateTitle\",\n                                                                                                                   color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                        isArgb: false)),\n                                                                                         subtitle: SBSDKUI2StyledText(text: \"?barcodeInfoMappingErrorStateSubtitle\",\n                                                                                                                      color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                                                           isArgb: false)),\n                                                                                         retryButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                                                                  text: \"?barcodeInfoMappingErrorStateRetryButton\",\n                                                                                                                                  background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                                                                 isArgb: false),\n                                                                                                                                                                      fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                                                               isArgb: false),\n                                                                                                                                                                      strokeWidth: 1.0),\n                                                                                                                                  foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                                                                      color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                                                           isArgb: false),\n                                                                                                                                                                      useShadow: false)),\n                                                                                         cancelButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                                                                   text: \"?barcodeInfoMappingErrorStateCancelButton\",\n                                                                                                                                   background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                                  isArgb: false),\n                                                                                                                                                                       fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                                isArgb: false),\n                                                                                                                                                                       strokeWidth: 1.0),\n                                                                                                                                   foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                                                                       color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                                                            isArgb: false),\n                                                                                                                                                                       useShadow: false)))), "},{"kind":"externalParam","text":"arOverlay"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration","text":"SBSDKUI2ArOverlayGeneralConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier"},{"text":" = SBSDKUI2ArOverlayGeneralConfiguration(visible: false,\n                                                                                                         counterBadge: SBSDKUI2BadgeStyle(visible: true,\n                                                                                                                                          background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#FF000000\",\n                                                                                                                                                                                                         isArgb: false),\n                                                                                                                                                                              fillColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                       isArgb: false),\n                                                                                                                                                                              strokeWidth: 0.0),\n                                                                                                                                          foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                                                         isArgb: false)),\n                                                                                                         automaticSelectionEnabled: false,\n                                                                                                         barcodeItemInfoPosition: SBSDKUI2BarcodeItemInfoPosition\n                                                                                                             .below,\n                                                                                                         polygon: SBSDKUI2ArOverlayPolygonConfiguration(visible: true,\n                                                                                                                                                        deselected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                                                                                                                    isArgb: false),\n                                                                                                                                                                                         fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                                                  isArgb: false),\n                                                                                                                                                                                         strokeWidth: 3.0,\n                                                                                                                                                                                         cornerRadius: 5.0),\n                                                                                                                                                        selected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                                  isArgb: false),\n                                                                                                                                                                                       fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                                                isArgb: false),\n                                                                                                                                                                                       strokeWidth: 3.0,\n                                                                                                                                                                                       cornerRadius: 5.0)),\n                                                                                                         barcodeItemConfiguration: SBSDKUI2BarcodeItemConfiguration(imageVisible: true,\n                                                                                                                                                                    titleSelected: SBSDKUI2StyledText(text: \"BARCODE_TITLE\",\n                                                                                                                                                                                                      color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                                                                                                           isArgb: false)),\n                                                                                                                                                                    subtitleSelected: SBSDKUI2StyledText(visible: true,\n                                                                                                                                                                                                         text: \"BARCODE_SUBTITLE\",\n                                                                                                                                                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                                                                                                                                              isArgb: false),\n                                                                                                                                                                                                         useShadow: false),\n                                                                                                                                                                    titleDeselected: SBSDKUI2StyledText(visible: true,\n                                                                                                                                                                                                        text: \"BARCODE_TITLE\",\n                                                                                                                                                                                                        color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                                                                                                             isArgb: false),\n                                                                                                                                                                                                        useShadow: false),\n                                                                                                                                                                    subtitleDeselected: SBSDKUI2StyledText(text: \"BARCODE_SUBTITLE\",\n                                                                                                                                                                                                           color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                                                                                                                                                isArgb: false)),\n                                                                                                                                                                    backgroundSelected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                                                        isArgb: false),\n                                                                                                                                                                                                             fillColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                                                      isArgb: false),\n                                                                                                                                                                                                             strokeWidth: 1.0,\n                                                                                                                                                                                                             cornerRadius: 5.0),\n                                                                                                                                                                    backgroundDeselected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                                                                                                                                          isArgb: false),\n                                                                                                                                                                                                               fillColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                                                                                                                                        isArgb: false),\n                                                                                                                                                                                                               strokeWidth: 1.0,\n                                                                                                                                                                                                               cornerRadius: 5.0))))","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Sheet":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Sheet"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheet","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet","type":"topic","title":"SBSDKUI2Sheet","role":"symbol","abstract":[{"type":"text","text":"Configuration of the preview mode for scanning multiple barcodes."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2Sheet","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MultipleScanningMode":{"navigatorTitle":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplescanningmode","title":"SBSDKUI2MultipleScanningMode","abstract":[{"text":"Configuration of the mode for scanning multiple barcodes.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MultipleScanningMode"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleScanningMode"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MultipleBarcodesScanningMode":{"title":"SBSDKUI2MultipleBarcodesScanningMode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplebarcodesscanningmode","abstract":[{"text":"Configuration of the mode used for scanning multiple barcodes.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeInfoMapping":{"navigatorTitle":[{"text":"SBSDKUI2BarcodeInfoMapping","kind":"identifier"}],"abstract":[{"text":"Configuration of the barcode data mapping.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}],"title":"SBSDKUI2BarcodeInfoMapping","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeInfoMapping","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeinfomapping","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayGeneralConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"title":"SBSDKUI2ArOverlayGeneralConfiguration","abstract":[{"text":"Configuration of the AR overlay displayed on top of barcodes in the camera preview.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaygeneralconfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayGeneralConfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 5.2.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ManualCountEditDialog":{"abstract":[{"text":"Configuration of the dialog to manually edit the barcode count.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ManualCountEditDialog","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}],"title":"SBSDKUI2ManualCountEditDialog","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2manualcounteditdialog"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MultipleScanningMode/init(countingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleScanningMode\/init(countingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplescanningmode\/init(countingrepeatdelay:mode:sheet:sheetcontent:manualcounteditdialog:barcodeinfomapping:aroverlay:)","title":"init(countingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"countingRepeatDelay"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MultipleBarcodesScanningMode","text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sheet"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Sheet","kind":"typeIdentifier","text":"SBSDKUI2Sheet"},{"text":", ","kind":"text"},{"text":"sheetContent","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2SheetContent","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2SheetContent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"manualCountEditDialog"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ManualCountEditDialog","text":"SBSDKUI2ManualCountEditDialog","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"barcodeInfoMapping","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeInfoMapping","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"arOverlay"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ArOverlayGeneralConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithCountingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SheetContent":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"title":"SBSDKUI2SheetContent","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheetcontent","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Configuration of the list containing the barcodes that have already been scanned.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithCountingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCountingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithCountingRepeatDelay:"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"countingRepeatDelay","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mode:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MultipleBarcodesScanningMode","text":"SBSDKUI2MultipleBarcodesScanningMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mode"},{"text":" ","kind":"text"},{"text":"sheet:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2Sheet","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Sheet"},{"text":" *) ","kind":"text"},{"text":"sheet","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheetContent:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent","text":"SBSDKUI2SheetContent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2SheetContent"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sheetContent"},{"text":" ","kind":"text"},{"kind":"identifier","text":"manualCountEditDialog:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ManualCountEditDialog","text":"SBSDKUI2ManualCountEditDialog","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ManualCountEditDialog","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"manualCountEditDialog"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeInfoMapping:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeInfoMapping","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeInfoMapping"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"barcodeInfoMapping"},{"kind":"text","text":" "},{"kind":"identifier","text":"arOverlay:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayGeneralConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration","text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"arOverlay","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/title","op":"replace","value":"SBSDKUI2Sheet"},{"value":[{"text":"SBSDKUI2Sheet","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/fragments"},{"value":"SBSDKUI2MultipleScanningMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleScanningMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2MultipleScanningMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleScanningMode\/fragments","op":"replace"},{"value":"SBSDKUI2MultipleBarcodesScanningMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleBarcodesScanningMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleBarcodesScanningMode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeInfoMapping\/title","op":"replace","value":"SBSDKUI2BarcodeInfoMapping"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeInfoMapping\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/title","op":"replace","value":"SBSDKUI2ArOverlayGeneralConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"op":"replace"},{"value":"SBSDKUI2ManualCountEditDialog","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ManualCountEditDialog\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ManualCountEditDialog"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ManualCountEditDialog\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleScanningMode~1init(countingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)\/title","value":"initWithCountingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleScanningMode~1init(countingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCountingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/title","value":"SBSDKUI2SheetContent","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}