{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2popupmenuitem\/title"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2popupmenuitem\/title"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PopupMenuItem"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"}]}]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"}],"navigatorTitle":[{"kind":"identifier","text":"title"}],"title":"title","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PopupMenuItem(py)title","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PopupMenuItem\/title"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The text to be displayed on the button."}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PopupMenuItem":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2PopupMenuItem"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PopupMenuItem"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2popupmenuitem","title":"SBSDKUI2PopupMenuItem","type":"topic","abstract":[{"type":"text","text":"Button configuration."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PopupMenuItem"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"kind":"symbol","title":"SBSDKUI2StyledText"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PopupMenuItem/title":{"role":"symbol","abstract":[{"type":"text","text":"The text to be displayed on the button."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2popupmenuitem\/title","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PopupMenuItem\/title","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"}],"navigatorTitle":[{"text":"title","kind":"identifier"}],"title":"title","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"title"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":" * "},{"kind":"identifier","text":"title"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PopupMenuItem\/title","op":"replace","value":"SBSDKUI2PopupMenuItem"},{"op":"replace","value":[{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PopupMenuItem\/fragments"},{"value":"SBSDKUI2StyledText","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title"},{"value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PopupMenuItem~1title\/title","op":"replace","value":"title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PopupMenuItem~1title\/fragments","value":[{"kind":"identifier","text":"title"}],"op":"replace"}]}]}