{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseInfo"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdklicenseinfo\/initwithstatus:isvalid:licensestatusmessage:expirationtimestamp:expirationdatestring:errormessage:onlinelicensecheckinprogress:license:devices:nextonlinelicensecheckinms:devicederegistationerrors:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithStatus:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKLicenseStatus","text":"SBSDKLicenseStatus"},{"kind":"text","text":") "},{"kind":"internalParam","text":"status"},{"kind":"text","text":" "},{"kind":"identifier","text":"isValid:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isValid"},{"kind":"text","text":" "},{"kind":"identifier","text":"licenseStatusMessage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"licenseStatusMessage"},{"kind":"text","text":" "},{"kind":"identifier","text":"expirationTimestamp:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"expirationTimestamp"},{"kind":"text","text":" "},{"kind":"identifier","text":"expirationDateString:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"expirationDateString"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"errorMessage"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlineLicenseCheckInProgress:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"onlineLicenseCheckInProgress"},{"kind":"text","text":" "},{"kind":"identifier","text":"license:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"license"},{"kind":"text","text":" "},{"kind":"identifier","text":"devices:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"devices"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextOnlineLicenseCheckInMs:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"nextOnlineLicenseCheckInMs"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceDeregistationErrors:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKDeviceDeregistrationError *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"deviceDeregistationErrors"},{"kind":"text","text":";"}]}]}],"metadata":{"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:"}],"title":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKLicenseInfo(im)initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseInfo\/initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKLicenseInfo":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdklicenseinfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"Information about the SDK license."}],"title":"SBSDKLicenseInfo","navigatorTitle":[{"text":"SBSDKLicenseInfo","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseInfo"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKLicenseStatus":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseStatus","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdklicensestatus","title":"SBSDKLicenseStatus","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseStatus"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"type":"topic","abstract":[{"type":"text","text":"Status of the license plate scanner."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKLicenseInfo/initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdklicenseinfo\/initwithstatus:isvalid:licensestatusmessage:expirationtimestamp:expirationdatestring:errormessage:onlinelicensecheckinprogress:license:devices:nextonlinelicensecheckinms:devicederegistationerrors:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","kind":"identifier"}],"title":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseInfo\/initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","type":"topic","navigatorTitle":[{"text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKLicenseInfo","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseInfo\/title"},{"op":"replace","value":[{"text":"SBSDKLicenseInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseInfo\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseInfo"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseInfo\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus\/title","value":"SBSDKLicenseStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus\/fragments","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus\/navigatorTitle","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}]}]}]}