{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraExposureSettings"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraExposureSettings\/exposureTargetOffset","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcameraexposuresettings\/exposuretargetoffset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcameraexposuresettings\/exposuretargetoffset"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exposureTargetOffset","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"Usually the camera automatically tries to adapt its exposure parameters to keep the exposure target offset at a","type":"text"},{"text":" ","type":"text"},{"text":"value of 0 resulting in a proper exposure of the image.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"If this value is not close to 0 the camera cannot adjust its exposure parameters properly, the image is either"},{"type":"text","text":" "},{"type":"text","text":"way too dark or too bright."}],"type":"paragraph"}]}],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"exposureTargetOffset","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraExposureSettings(py)exposureTargetOffset","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"exposureTargetOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"exposureTargetOffset"}]},"abstract":[{"type":"text","text":"The exposure target offset in EV."},{"type":"text","text":" "},{"type":"text","text":"Negative values mean the image is too dark, positive values mean the image is too bright."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraExposureSettings/exposureTargetOffset":{"url":"\/documentation\/scanbotsdk\/sbsdkcameraexposuresettings\/exposuretargetoffset","abstract":[{"text":"The exposure target offset in EV.","type":"text"},{"text":" ","type":"text"},{"text":"Negative values mean the image is too dark, positive values mean the image is too bright.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraExposureSettings\/exposureTargetOffset","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"exposureTargetOffset"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"exposureTargetOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"title":"exposureTargetOffset","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraExposureSettings":{"title":"SBSDKCameraExposureSettings","abstract":[{"type":"text","text":"This class provides information about the current cameras exposure settings."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraExposureSettings"}],"url":"\/documentation\/scanbotsdk\/sbsdkcameraexposuresettings","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraExposureSettings"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraExposureSettings","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"exposureTargetOffset","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"exposureTargetOffset"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"kind":"text","text":" "},{"kind":"identifier","text":"exposureTargetOffset"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"exposureTargetOffset","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraExposureSettings~1exposureTargetOffset\/title"},{"op":"replace","value":[{"kind":"identifier","text":"exposureTargetOffset"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraExposureSettings~1exposureTargetOffset\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraExposureSettings\/title","value":"SBSDKCameraExposureSettings"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraExposureSettings\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraExposureSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraExposureSettings\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCameraExposureSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}