{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingViewController","text":"SBSDKUICroppingViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinish"},{"kind":"text","text":" "},{"kind":"internalParam","text":"changedPage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage","text":"SBSDKDocumentPage"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The editing crop view controller that initiated the change and that did dismiss."}]}]},{"name":"changedPage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The page that was changed."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontrollerdelegate\/croppingviewcontroller(_:didfinish:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontrollerdelegate\/croppingviewcontroller(_:didfinish:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewControllerDelegate\/croppingViewController(_:didFinish:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Informs the delegate that the polygon or orientation of the edited page was changed and the cropping view controller did dismiss."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"croppingViewController:didFinish:"}],"role":"symbol","title":"croppingViewController(_:didFinish:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUICroppingViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinish"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentPage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUICroppingViewControllerDelegate(im)croppingViewController:didFinish:","required":true,"modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewControllerDelegate"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingViewControllerDelegate":{"role":"symbol","title":"SBSDKUICroppingViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICroppingViewControllerDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingViewControllerDelegate"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontrollerdelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingViewController":{"role":"symbol","title":"SBSDKUICroppingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICroppingViewController"}],"abstract":[{"type":"text","text":"A highly customizable view controller to edit a pages polygon or the page’s orientation."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingViewControllerDelegate/croppingViewController(_:didFinish:)":{"navigatorTitle":[{"kind":"identifier","text":"croppingViewController:didFinish:"}],"role":"symbol","title":"croppingViewController(_:didFinish:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUICroppingViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinish"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentPage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Informs the delegate that the polygon or orientation of the edited page was changed and the cropping view controller did dismiss."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewControllerDelegate\/croppingViewController(_:didFinish:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontrollerdelegate\/croppingviewcontroller(_:didfinish:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"role":"symbol","title":"SBSDKDocumentPage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"}],"abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"croppingViewController:didFinish:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"croppingViewController:didFinish:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"croppingViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingViewController","text":"SBSDKUICroppingViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinish:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage","text":"SBSDKDocumentPage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"changedPage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewControllerDelegate\/title","value":"SBSDKUICroppingViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUICroppingViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController\/title","value":"SBSDKUICroppingViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUICroppingViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewControllerDelegate~1croppingViewController(_:didFinish:)\/title","value":"croppingViewController:didFinish:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewControllerDelegate~1croppingViewController(_:didFinish:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"croppingViewController:didFinish:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title","value":"SBSDKDocumentPage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}