{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackMode\/pageSnapFunnelAnimation()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageSnapFunnelAnimation","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKUI2PageSnapFunnelAnimation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PageSnapFunnelAnimation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFunnelAnimation"}],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackMode"]]},"metadata":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageSnapFunnelAnimation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PageSnapFunnelAnimation","text":"SBSDKUI2PageSnapFunnelAnimation","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","title":"pageSnapFunnelAnimation()","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PageSnapFeedbackMode(cm)pageSnapFunnelAnimation","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"pageSnapFunnelAnimation"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2pagesnapfeedbackmode\/pagesnapfunnelanimation()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2pagesnapfeedbackmode\/pagesnapfunnelanimation()"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PageSnapFeedbackMode/pageSnapFunnelAnimation()":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageSnapFunnelAnimation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PageSnapFunnelAnimation","text":"SBSDKUI2PageSnapFunnelAnimation","kind":"typeIdentifier"}],"title":"pageSnapFunnelAnimation()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackMode\/pageSnapFunnelAnimation()","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2pagesnapfeedbackmode\/pagesnapfunnelanimation()","navigatorTitle":[{"text":"pageSnapFunnelAnimation","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PageSnapFeedbackMode":{"url":"\/documentation\/scanbotsdk\/sbsdkui2pagesnapfeedbackmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackMode","abstract":[{"text":"The type of animation to display after snapping a page.","type":"text"}],"title":"SBSDKUI2PageSnapFeedbackMode","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PageSnapFeedbackMode","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2PageSnapFeedbackMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PageSnapFunnelAnimation":{"url":"\/documentation\/scanbotsdk\/sbsdkui2pagesnapfunnelanimation","title":"SBSDKUI2PageSnapFunnelAnimation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PageSnapFunnelAnimation","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2PageSnapFunnelAnimation","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFunnelAnimation","abstract":[{"text":"Configuration of the funnel animation.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"pageSnapFunnelAnimation"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"pageSnapFunnelAnimation","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFunnelAnimation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PageSnapFunnelAnimation","text":"SBSDKUI2PageSnapFunnelAnimation"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"pageSnapFunnelAnimation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode~1pageSnapFunnelAnimation()\/title","op":"replace","value":"pageSnapFunnelAnimation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode~1pageSnapFunnelAnimation()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pageSnapFunnelAnimation"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode\/title","op":"replace","value":"SBSDKUI2PageSnapFeedbackMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode\/fragments","op":"replace","value":[{"text":"SBSDKUI2PageSnapFeedbackMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFunnelAnimation\/title","op":"replace","value":"SBSDKUI2PageSnapFunnelAnimation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFunnelAnimation\/fragments","op":"replace","value":[{"text":"SBSDKUI2PageSnapFunnelAnimation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFunnelAnimation\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2PageSnapFunnelAnimation","kind":"identifier"}]}]}]}