{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jurisdictionSpecificVehicleClassificationDescription"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2aamvarecordfieldtype\/jurisdictionspecificvehicleclassificationdescription"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2aamvarecordfieldtype\/jurisdictionspecificvehicleclassificationdescription"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVARecordFieldType\/jurisdictionSpecificVehicleClassificationDescription","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Jurisdiction-specific vehicle classification description"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jurisdictionSpecificVehicleClassificationDescription"}],"title":"SBSDKUI2AAMVARecordFieldType.jurisdictionSpecificVehicleClassificationDescription","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2AAMVARecordFieldType@SBSDKUI2AAMVARecordFieldTypeJurisdictionSpecificVehicleClassificationDescription","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldTypeJurisdictionSpecificVehicleClassificationDescription"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVARecordFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AAMVARecordFieldType/jurisdictionSpecificVehicleClassificationDescription":{"role":"symbol","title":"SBSDKUI2AAMVARecordFieldType.jurisdictionSpecificVehicleClassificationDescription","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jurisdictionSpecificVehicleClassificationDescription"}],"abstract":[{"type":"text","text":"Jurisdiction-specific vehicle classification description"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVARecordFieldType\/jurisdictionSpecificVehicleClassificationDescription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldTypeJurisdictionSpecificVehicleClassificationDescription"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aamvarecordfieldtype\/jurisdictionspecificvehicleclassificationdescription"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AAMVARecordFieldType":{"role":"symbol","title":"SBSDKUI2AAMVARecordFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldType"}],"abstract":[{"type":"text","text":"AAMVA Record Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVARecordFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aamvarecordfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2AAMVARecordFieldTypeJurisdictionSpecificVehicleClassificationDescription"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldTypeJurisdictionSpecificVehicleClassificationDescription"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldTypeJurisdictionSpecificVehicleClassificationDescription"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVARecordFieldType~1jurisdictionSpecificVehicleClassificationDescription\/title","value":"SBSDKUI2AAMVARecordFieldTypeJurisdictionSpecificVehicleClassificationDescription"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVARecordFieldType~1jurisdictionSpecificVehicleClassificationDescription\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldTypeJurisdictionSpecificVehicleClassificationDescription"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVARecordFieldType\/title","value":"SBSDKUI2AAMVARecordFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVARecordFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}