{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"permitRestrictionCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2aamvarecordfieldtype\/permitrestrictioncode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2aamvarecordfieldtype\/permitrestrictioncode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVARecordFieldType\/permitRestrictionCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Permit restriction code"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"permitRestrictionCode"}],"title":"SBSDKUI2AAMVARecordFieldType.permitRestrictionCode","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2AAMVARecordFieldType@SBSDKUI2AAMVARecordFieldTypePermitRestrictionCode","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldTypePermitRestrictionCode"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVARecordFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AAMVARecordFieldType/permitRestrictionCode":{"role":"symbol","title":"SBSDKUI2AAMVARecordFieldType.permitRestrictionCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"permitRestrictionCode"}],"abstract":[{"type":"text","text":"Permit restriction code"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVARecordFieldType\/permitRestrictionCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldTypePermitRestrictionCode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aamvarecordfieldtype\/permitrestrictioncode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AAMVARecordFieldType":{"role":"symbol","title":"SBSDKUI2AAMVARecordFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldType"}],"abstract":[{"type":"text","text":"AAMVA Record Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVARecordFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aamvarecordfieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2AAMVARecordFieldTypePermitRestrictionCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldTypePermitRestrictionCode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldTypePermitRestrictionCode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVARecordFieldType~1permitRestrictionCode\/title","value":"SBSDKUI2AAMVARecordFieldTypePermitRestrictionCode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVARecordFieldType~1permitRestrictionCode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldTypePermitRestrictionCode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVARecordFieldType\/title","value":"SBSDKUI2AAMVARecordFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVARecordFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}