{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDataExtractorCommonConfiguration"},{"text":"() -> ","kind":"text"},{"text":"SBSDKDocumentDataExtractorCommonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorCommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationelement\/documentdataextractorcommonconfiguration()"]}],"metadata":{"title":"documentDataExtractorCommonConfiguration()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataExtractorCommonConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorCommonConfiguration","kind":"typeIdentifier","text":"SBSDKDocumentDataExtractorCommonConfiguration"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"s:10ScanbotSDK46SBSDKDocumentDataExtractorConfigurationElementC08documentde6CommonF0AA0cdeiF0CyFZ","role":"symbol","roleHeading":"Type Method","symbolKind":"method"},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement\/documentDataExtractorCommonConfiguration()","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorCommonConfiguration":{"abstract":[{"type":"text","text":"Convenience configuration element for enabling the scanning of multiple document types with a common configuration."},{"text":" ","type":"text"},{"text":"Add to extractor configuration to enable the scanning of multiple document types.","type":"text"}],"kind":"symbol","type":"topic","title":"SBSDKDocumentDataExtractorCommonConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorcommonconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorCommonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDataExtractorCommonConfiguration","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationElement/documentDataExtractorCommonConfiguration()":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationelement\/documentdataextractorcommonconfiguration()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataExtractorCommonConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorCommonConfiguration","text":"SBSDKDocumentDataExtractorCommonConfiguration","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement\/documentDataExtractorCommonConfiguration()","abstract":[],"title":"documentDataExtractorCommonConfiguration()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationElement":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDataExtractorConfigurationElement","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationelement","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfigurationElement","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement","abstract":[{"type":"text","text":"Base class for all generic document configuration elements."}],"title":"SBSDKDocumentDataExtractorConfigurationElement"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorCommonConfiguration\/title","value":"SBSDKDocumentDataExtractorCommonConfiguration"},{"value":[{"text":"SBSDKDocumentDataExtractorCommonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorCommonConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentDataExtractorCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorCommonConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKDocumentDataExtractorConfigurationElement","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}