{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithFieldFullName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"fieldFullName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isSuspicious:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isSuspicious","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/initWithFieldFullName:isSuspicious:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport\/initwithfieldfullname:issuspicious:"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldSuspiciousDataVerificationReport(im)initWithFieldFullName:isSuspicious:","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFieldFullName:isSuspicious:"}],"navigatorTitle":[{"text":"initWithFieldFullName:isSuspicious:","kind":"identifier"}],"title":"initWithFieldFullName:isSuspicious:","symbolKind":"method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldSuspiciousDataVerificationReport":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFieldSuspiciousDataVerificationReport"}],"title":"SBSDKFieldSuspiciousDataVerificationReport","navigatorTitle":[{"kind":"identifier","text":"SBSDKFieldSuspiciousDataVerificationReport"}],"type":"topic","abstract":[{"type":"text","text":"Report of the suspicious data field verification."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldSuspiciousDataVerificationReport/initWithFieldFullName:isSuspicious:":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFieldFullName:isSuspicious:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/initWithFieldFullName:isSuspicious:","type":"topic","title":"initWithFieldFullName:isSuspicious:","url":"\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport\/initwithfieldfullname:issuspicious:","abstract":[],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFieldFullName:isSuspicious:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport\/title","op":"replace","value":"SBSDKFieldSuspiciousDataVerificationReport"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKFieldSuspiciousDataVerificationReport"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport\/navigatorTitle","op":"replace","value":[{"text":"SBSDKFieldSuspiciousDataVerificationReport","kind":"identifier"}]}]}]}