{"kind":"symbol","metadata":{"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCommonTwoDConfiguration(im)initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:formats:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:formats:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:formats:","kind":"identifier"}],"title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:formats:"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommontwodconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:gs1handling:strictmode:formats:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonTwoDConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:formats:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonTwoDConfiguration"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithRegexFilter:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"regexFilter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumSizeScore:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimumSizeScore","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addAdditionalQuietZone:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"addAdditionalQuietZone"},{"kind":"text","text":" "},{"kind":"identifier","text":"gs1Handling:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKGS1Handling","text":"SBSDKGS1Handling","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling"},{"kind":"text","text":") "},{"kind":"internalParam","text":"gs1Handling"},{"kind":"text","text":" "},{"kind":"identifier","text":"strictMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"strictMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"formats:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBarcodeFormat *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"formats"},{"kind":"text","text":";"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonTwoDConfiguration":{"type":"topic","title":"SBSDKBarcodeFormatCommonTwoDConfiguration","abstract":[{"type":"text","text":"Convenience configuration for enabling the scanning of multiple 2D codes with a common configuration."},{"type":"text","text":" "},{"type":"text","text":"Add to scanner configuration to enable and configure the scanning of multiple 2D codes."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonTwoDConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCommonTwoDConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommontwodconfiguration","kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatCommonTwoDConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonTwoDConfiguration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:formats:":{"role":"symbol","type":"topic","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:formats:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommontwodconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:gs1handling:strictmode:formats:","navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:formats:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonTwoDConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:formats:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:formats:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGS1Handling","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgs1handling","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling","title":"SBSDKGS1Handling","abstract":[{"text":"GS1 message handling options.","type":"text"},{"text":" ","type":"text"},{"text":"The GS1 standard defines a key-value format for business-centric data that can be encoded into many 1D and 2D","type":"text"},{"text":" ","type":"text"},{"text":"barcode types.","type":"text"},{"text":" ","type":"text"},{"text":"https:\/\/ref.gs1.org\/standards\/genspecs\/","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonTwoDConfiguration\/title","value":"SBSDKBarcodeFormatCommonTwoDConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonTwoDConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonTwoDConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonTwoDConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatCommonTwoDConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/title","value":"SBSDKGS1Handling","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/fragments","value":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"op":"replace"}]}]}