{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectorresult\/isdetectionstatusok"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectorresult\/isdetectionstatusok"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult"]]},"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult(py)isDetectionStatusOK","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isDetectionStatusOK","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Property","title":"isDetectionStatusOK","symbolKind":"property","navigatorTitle":[{"text":"isDetectionStatusOK","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult\/isDetectionStatusOK","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"is ","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":", if the receiver has one of the following states:"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok","isActive":true},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButTooSmall"},{"type":"text","text":","},{"text":" ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButBadAngles"},{"type":"text","text":", "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButBadAspectRatio","isActive":true,"type":"reference"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Otherwise it is "},{"type":"codeVoice","code":"False"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDetectionStatusOK"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/okButBadAspectRatio":{"abstract":[{"type":"text","text":"A document has been detected but it has a bad aspect ratio."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okButBadAspectRatio"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/okbutbadaspectratio","kind":"symbol","role":"symbol","title":"SBSDKDocumentDetectionStatus.okButBadAspectRatio","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButBadAspectRatio","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatusOkButBadAspectRatio","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/okButBadAngles":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/okbutbadangles","role":"symbol","title":"SBSDKDocumentDetectionStatus.okButBadAngles","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A document has been detected but it has bad angles."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"okButBadAngles"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButBadAngles"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButBadAngles"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/ok":{"title":"SBSDKDocumentDetectionStatus.ok","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/ok","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ok","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk"}],"type":"topic","abstract":[{"type":"text","text":"A document has been detected successfully."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorResult":{"abstract":[{"type":"text","text":"This class represents the result of a document detection"},{"type":"text","text":" "},{"type":"text","text":"on an image."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectorresult","title":"SBSDKDocumentDetectorResult","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorResult/isDetectionStatusOK":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectorresult\/isdetectionstatusok","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDetectionStatusOK"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult\/isDetectionStatusOK","title":"isDetectionStatusOK","navigatorTitle":[{"text":"isDetectionStatusOK","kind":"identifier"}],"abstract":[{"type":"text","text":"is "},{"code":"True","type":"codeVoice"},{"type":"text","text":", if the receiver has one of the following states:"},{"type":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButTooSmall"},{"type":"text","text":","},{"text":" ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButBadAngles","isActive":true},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButBadAspectRatio"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Otherwise it is ","type":"text"},{"code":"False","type":"codeVoice"},{"type":"text","text":"."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/okButTooSmall":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/okbuttoosmall","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatusOkButTooSmall","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"okButTooSmall","kind":"identifier"}],"title":"SBSDKDocumentDetectionStatus.okButTooSmall","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButTooSmall","abstract":[{"type":"text","text":"A document has been detected but it is too small."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"isDetectionStatusOK","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"isDetectionStatusOK","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDetectionStatusOK"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"SBSDKDocumentDetectionStatusOkButBadAspectRatio","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButBadAspectRatio\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButBadAspectRatio"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButBadAspectRatio\/fragments"},{"value":"SBSDKDocumentDetectionStatusOkButBadAngles","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButBadAngles\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButBadAngles"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButBadAngles\/fragments","op":"replace"},{"value":"SBSDKDocumentDetectionStatusOk","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1ok\/title"},{"value":[{"text":"SBSDKDocumentDetectionStatusOk","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1ok\/fragments","op":"replace"},{"value":"SBSDKDocumentDetectorResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/fragments","value":[{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult~1isDetectionStatusOK\/title","value":"isDetectionStatusOK","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult~1isDetectionStatusOK\/fragments","op":"replace","value":[{"kind":"identifier","text":"isDetectionStatusOK"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButTooSmall\/title","value":"SBSDKDocumentDetectionStatusOkButTooSmall","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButTooSmall\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDetectionStatusOkButTooSmall","kind":"identifier"}]}]}]}