{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration\/detectorientation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration\/detectorientation"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration"]]},"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectOrientation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"text":"detectOrientation","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"detectOrientation","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQualityAnalyzerConfiguration(py)detectOrientation"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/detectOrientation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enable orientation detection. Document orientation will be returned in"},{"type":"text","text":" "},{"type":"codeVoice","code":"DocumentQualityAnalyzerResult.orientation"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectOrientation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Default is false"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzerConfiguration":{"abstract":[{"type":"text","text":"Document Quality Analyzer configuration."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"title":"SBSDKDocumentQualityAnalyzerConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzerConfiguration/detectOrientation":{"abstract":[{"text":"Enable orientation detection. Document orientation will be returned in","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"DocumentQualityAnalyzerResult.orientation"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectOrientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"detectOrientation"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration\/detectorientation","title":"detectOrientation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/detectOrientation"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"detectOrientation","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"detectOrientation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"detectOrientation","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentQualityAnalyzerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/navigatorTitle","value":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1detectOrientation\/title","value":"detectOrientation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1detectOrientation\/fragments","value":[{"text":"detectOrientation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}