{"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerConfiguration(py)behaviorConfiguration","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"behaviorConfiguration","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"behaviorConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerBehaviorConfiguration","text":"SBSDKUICheckRecognizerBehaviorConfiguration"}],"title":"behaviorConfiguration"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"behaviorConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerBehaviorConfiguration","text":"SBSDKUICheckRecognizerBehaviorConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerBehaviorConfiguration"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/behaviorConfiguration","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration\/behaviorconfiguration"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration\/behaviorconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration"]]},"kind":"symbol","abstract":[{"type":"text","text":"The configuration controlling the scanning screens behavior."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerConfiguration/behaviorConfiguration":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"behaviorConfiguration","kind":"identifier"}],"abstract":[{"text":"The configuration controlling the scanning screens behavior.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"behaviorConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerBehaviorConfiguration","text":"SBSDKUICheckRecognizerBehaviorConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration\/behaviorconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/behaviorConfiguration","title":"behaviorConfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerConfiguration":{"type":"topic","abstract":[{"text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI check scanner.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICheckRecognizerConfiguration"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUICheckRecognizerConfiguration","kind":"identifier"}],"title":"SBSDKUICheckRecognizerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerBehaviorConfiguration":{"title":"SBSDKUICheckRecognizerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerBehaviorConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerbehaviorconfiguration","abstract":[{"type":"text","text":"Configuration for the behavior of the RTU-UI check scanner."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUICheckRecognizerBehaviorConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckRecognizerBehaviorConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"behaviorConfiguration","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"behaviorConfiguration"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerBehaviorConfiguration","text":"SBSDKUICheckRecognizerBehaviorConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerBehaviorConfiguration"},{"text":" * ","kind":"text"},{"text":"behaviorConfiguration","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"behaviorConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration~1behaviorConfiguration\/title"},{"value":[{"text":"behaviorConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration~1behaviorConfiguration\/fragments","op":"replace"},{"value":"SBSDKUICheckRecognizerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUICheckRecognizerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUICheckRecognizerConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerBehaviorConfiguration\/title","value":"SBSDKUICheckRecognizerBehaviorConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerBehaviorConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUICheckRecognizerBehaviorConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerBehaviorConfiguration\/navigatorTitle","value":[{"text":"SBSDKUICheckRecognizerBehaviorConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}