{"abstract":[{"type":"text","text":"The default parametric filters for new documents pages."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultParametricPageFilter"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier","text":"SBSDKParametricFilter"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"Defaults to ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/defaultparametricpagefilter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/defaultparametricpagefilter"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerBehaviorConfiguration(py)defaultParametricPageFilter","modules":[{"name":"ScanbotSDK"}],"title":"defaultParametricPageFilter","symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultParametricPageFilter"}],"platforms":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultParametricPageFilter","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier","text":"SBSDKParametricFilter"},{"kind":"text","text":"]?"}],"roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/defaultParametricPageFilter"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"abstract":[{"text":"Base class for all parametric filters.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKParametricFilter"}],"title":"SBSDKParametricFilter","navigatorTitle":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/defaultParametricPageFilter":{"type":"topic","role":"symbol","deprecated":true,"kind":"symbol","title":"defaultParametricPageFilter","abstract":[{"type":"text","text":"The default parametric filters for new documents pages."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/defaultParametricPageFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultParametricPageFilter"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"text":"defaultParametricPageFilter","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/defaultparametricpagefilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration","title":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration","type":"topic","deprecated":true,"role":"symbol","abstract":[{"type":"text","text":"Configuration for the behavior of the document scanning screen."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"defaultParametricPageFilter","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultParametricPageFilter"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<SBSDKParametricFilter *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"defaultParametricPageFilter","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title","op":"replace","value":"SBSDKParametricFilter"},{"value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1defaultParametricPageFilter\/title","value":"defaultParametricPageFilter","op":"replace"},{"value":[{"text":"defaultParametricPageFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1defaultParametricPageFilter\/fragments","op":"replace"},{"value":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}]}]}]}