{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerBehaviorConfiguration(py)defaultPageFilter","title":"defaultPageFilter","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultPageFilter"},{"text":": ","kind":"text"},{"text":"SBSDKImageFilterType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFilterType"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"defaultPageFilter","kind":"identifier"}],"platforms":[]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration"]]},"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}],"type":"paragraph"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/defaultPageFilter"},"abstract":[{"text":"The default image filter type for new documents pages.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultPageFilter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFilterType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","text":"SBSDKImageFilterType"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"Has no effect, if "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/defaultParametricPageFilter","type":"reference"},{"type":"text","text":" is non-nil."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/none","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/defaultpagefilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/defaultpagefilter"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType":{"navigatorTitle":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"title":"SBSDKImageFilterType","url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype","kind":"symbol","role":"symbol","type":"topic","deprecated":true,"abstract":[{"text":"The ScanbotSDK image filter types.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageFilterType","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/none":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/none","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/none","deprecated":true,"title":"SBSDKImageFilterType.none","abstract":[{"text":"Passthrough filter. Does not alter the image.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKImageFilterTypeNone","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/defaultPageFilter":{"role":"symbol","navigatorTitle":[{"text":"defaultPageFilter","kind":"identifier"}],"title":"defaultPageFilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/defaultPageFilter","kind":"symbol","abstract":[{"type":"text","text":"The default image filter type for new documents pages."}],"deprecated":true,"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/defaultpagefilter","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultPageFilter","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageFilterType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFilterType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration","title":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration","type":"topic","deprecated":true,"role":"symbol","abstract":[{"type":"text","text":"Configuration for the behavior of the document scanning screen."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/defaultParametricPageFilter":{"type":"topic","role":"symbol","deprecated":true,"kind":"symbol","title":"defaultParametricPageFilter","abstract":[{"type":"text","text":"The default parametric filters for new documents pages."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/defaultParametricPageFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultParametricPageFilter"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"text":"defaultParametricPageFilter","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/defaultparametricpagefilter"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"defaultPageFilter","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"defaultPageFilter","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFilterType","kind":"typeIdentifier","text":"SBSDKImageFilterType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultPageFilter"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/title","value":"SBSDKImageFilterType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageFilterType"}]},{"value":"SBSDKImageFilterTypeNone","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1none\/title"},{"value":[{"text":"SBSDKImageFilterTypeNone","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1none\/fragments","op":"replace"},{"value":"defaultPageFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1defaultPageFilter\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1defaultPageFilter\/fragments","value":[{"text":"defaultPageFilter","kind":"identifier"}]},{"value":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}]},{"value":"defaultParametricPageFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1defaultParametricPageFilter\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1defaultParametricPageFilter\/fragments","value":[{"text":"defaultParametricPageFilter","kind":"identifier"}]}]}]}