{"abstract":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":" a high-resolution photo of the medical certificate is captured to run the recognition on."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureHighResolutionImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"Upon successful recognition the recognition result also contains a high-resolution image of the medical certificate."},{"type":"text","text":" "},{"type":"text","text":"If set to "},{"code":"False","type":"codeVoice"},{"type":"text","text":", the video frames will be used for recognition and result image delivery."}],"type":"paragraph"},{"inlineContent":[{"text":"Defaults to ","type":"text"},{"code":"True","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/captureHighResolutionImage","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller\/capturehighresolutionimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller\/capturehighresolutionimage"]}],"metadata":{"role":"symbol","title":"captureHighResolutionImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureHighResolutionImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"captureHighResolutionImage","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController(py)captureHighResolutionImage"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController":{"kind":"symbol","role":"symbol","title":"SBSDKMedicalCertificateScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}],"type":"topic","abstract":[{"text":"The classic UI view controller that can be used to detect and recognize medical certificates. Can be configured to recognize on video frames or,","type":"text"},{"text":" ","type":"text"},{"text":"for better accuracy, on high-res photos that are automatically captured.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController/captureHighResolutionImage":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureHighResolutionImage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"captureHighResolutionImage","abstract":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":" a high-resolution photo of the medical certificate is captured to run the recognition on."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"captureHighResolutionImage"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller\/capturehighresolutionimage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/captureHighResolutionImage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"captureHighResolutionImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"captureHighResolutionImage","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"captureHighResolutionImage","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/title","value":"SBSDKMedicalCertificateScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1captureHighResolutionImage\/title","value":"captureHighResolutionImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1captureHighResolutionImage\/fragments","value":[{"kind":"identifier","text":"captureHighResolutionImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}