{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBufferImageLoadOptions\/hash","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBufferImageLoadOptions"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"identifier","text":"hash"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}],"title":"hash","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBufferImageLoadOptions(py)hash"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbufferimageloadoptions\/hash"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBufferImageLoadOptions":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbufferimageloadoptions","role":"symbol","abstract":[{"type":"text","text":"Options for loading image from buffer."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBufferImageLoadOptions","title":"SBSDKBufferImageLoadOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBufferImageLoadOptions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBufferImageLoadOptions"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBufferImageLoadOptions/hash":{"fragments":[{"kind":"identifier","text":"hash"}],"type":"topic","title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkbufferimageloadoptions\/hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBufferImageLoadOptions\/hash","abstract":[],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKBufferImageLoadOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBufferImageLoadOptions\/title"},{"value":[{"kind":"identifier","text":"SBSDKBufferImageLoadOptions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBufferImageLoadOptions\/fragments"},{"op":"replace","value":[{"text":"SBSDKBufferImageLoadOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBufferImageLoadOptions\/navigatorTitle"}]}]}