{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithRoi:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":") ","kind":"text"},{"text":"roi","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"loadMode:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBufferLoadMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBufferLoadMode","kind":"typeIdentifier","text":"SBSDKBufferLoadMode"},{"kind":"text","text":") "},{"text":"loadMode","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbufferimageloadoptions\/initwithroi:loadmode:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBufferImageLoadOptions"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBufferImageLoadOptions\/initWithRoi:loadMode:","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithRoi:loadMode:"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBufferImageLoadOptions(im)initWithRoi:loadMode:","title":"initWithRoi:loadMode:","navigatorTitle":[{"text":"initWithRoi:loadMode:","kind":"identifier"}]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBufferImageLoadOptions":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbufferimageloadoptions","role":"symbol","abstract":[{"type":"text","text":"Options for loading image from buffer."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBufferImageLoadOptions","title":"SBSDKBufferImageLoadOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBufferImageLoadOptions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBufferImageLoadOptions"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBufferLoadMode":{"url":"\/documentation\/scanbotsdk\/sbsdkbufferloadmode","role":"symbol","abstract":[{"text":"Image Ref Buffer Load Mode.","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBufferLoadMode","kind":"identifier"}],"title":"SBSDKBufferLoadMode","navigatorTitle":[{"text":"SBSDKBufferLoadMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBufferLoadMode","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBufferImageLoadOptions/initWithRoi:loadMode:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBufferImageLoadOptions\/initWithRoi:loadMode:","url":"\/documentation\/scanbotsdk\/sbsdkbufferimageloadoptions\/initwithroi:loadmode:","fragments":[{"kind":"text","text":"- "},{"text":"initWithRoi:loadMode:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithRoi:loadMode:","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[],"title":"initWithRoi:loadMode:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBufferImageLoadOptions\/title","value":"SBSDKBufferImageLoadOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBufferImageLoadOptions\/fragments","value":[{"kind":"identifier","text":"SBSDKBufferImageLoadOptions"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBufferImageLoadOptions\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBufferImageLoadOptions","kind":"identifier"}]},{"value":"SBSDKBufferLoadMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBufferLoadMode\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKBufferLoadMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBufferLoadMode\/fragments"},{"value":[{"text":"SBSDKBufferLoadMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBufferLoadMode\/navigatorTitle","op":"replace"}]}]}