{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration\/copyWithZone:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatGS1CompositeConfiguration(im)copyWithZone:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","roleHeading":"Instance Method"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"_NSZone","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatgs1compositeconfiguration\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatGS1CompositeConfiguration/copyWithZone:":{"kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration\/copyWithZone:","title":"copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatgs1compositeconfiguration\/copywithzone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatGS1CompositeConfiguration":{"abstract":[{"type":"text","text":"GS1 Composite configuration. Add to scanner configuration to scan GS1 Composite barcodes."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"identifier"}],"type":"topic","title":"SBSDKBarcodeFormatGS1CompositeConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatgs1compositeconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKBarcodeFormatGS1CompositeConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"identifier"}]}]}]}