{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraExposureSettings\/exposureTargetOffset"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraExposureSettings"]]},"sections":[],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"exposureTargetOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"property","title":"exposureTargetOffset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"exposureTargetOffset"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraExposureSettings(py)exposureTargetOffset"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcameraexposuresettings\/exposuretargetoffset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcameraexposuresettings\/exposuretargetoffset"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"The exposure target offset in EV."},{"type":"text","text":" "},{"type":"text","text":"Negative values mean the image is too dark, positive values mean the image is too bright."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exposureTargetOffset","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Usually the camera automatically tries to adapt its exposure parameters to keep the exposure target offset at a","type":"text"},{"text":" ","type":"text"},{"text":"value of 0 resulting in a proper exposure of the image.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"If this value is not close to 0 the camera cannot adjust its exposure parameters properly, the image is either","type":"text"},{"text":" ","type":"text"},{"text":"way too dark or too bright.","type":"text"}]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraExposureSettings/exposureTargetOffset":{"title":"exposureTargetOffset","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraExposureSettings\/exposureTargetOffset","navigatorTitle":[{"kind":"identifier","text":"exposureTargetOffset"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"exposureTargetOffset"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameraexposuresettings\/exposuretargetoffset","abstract":[{"type":"text","text":"The exposure target offset in EV."},{"type":"text","text":" "},{"type":"text","text":"Negative values mean the image is too dark, positive values mean the image is too bright."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraExposureSettings":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraExposureSettings"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraExposureSettings"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraExposureSettings","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameraexposuresettings","title":"SBSDKCameraExposureSettings","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This class provides information about the current cameras exposure settings."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"exposureTargetOffset","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"exposureTargetOffset"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":" ","kind":"text"},{"text":"exposureTargetOffset","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"exposureTargetOffset","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraExposureSettings~1exposureTargetOffset\/title"},{"op":"replace","value":[{"text":"exposureTargetOffset","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraExposureSettings~1exposureTargetOffset\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraExposureSettings\/title","op":"replace","value":"SBSDKCameraExposureSettings"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraExposureSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraExposureSettings"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraExposureSettings\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCameraExposureSettings","kind":"identifier"}]}]}]}