{"abstract":[{"text":"Designated initializer.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSoundController\/init(soundType:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"soundType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKSoundType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSoundType","text":"SBSDKSoundType"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The chosen sound type."}]}],"name":"soundType"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSoundController"]]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdksoundcontroller\/init(soundtype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdksoundcontroller\/init(soundtype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"soundType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKSoundType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKSoundType"},{"text":")","kind":"text"}],"title":"init(soundType:)","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKSoundController(im)initWithSoundType:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Initializer","symbolKind":"init","navigatorTitle":[{"text":"initWithSoundType:","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSoundController/init(soundType:)":{"abstract":[{"type":"text","text":"Designated initializer."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithSoundType:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksoundcontroller\/init(soundtype:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"soundType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKSoundType","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKSoundType"},{"kind":"text","text":")"}],"kind":"symbol","title":"init(soundType:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSoundController\/init(soundType:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSoundController":{"title":"SBSDKSoundController","abstract":[{"type":"text","text":"A class to manage playback of sounds and vibration."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKSoundController"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksoundcontroller","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSoundController"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSoundController"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSoundType":{"title":"SBSDKSoundType","navigatorTitle":[{"text":"SBSDKSoundType","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSoundType","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksoundtype","abstract":[{"text":"The sound selection type.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSoundType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithSoundType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSoundType:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSoundType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKSoundType","kind":"typeIdentifier","text":"SBSDKSoundType","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSoundType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"soundType"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"soundType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The chosen sound type."}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSoundController~1init(soundType:)\/title","value":"initWithSoundType:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSoundController~1init(soundType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSoundType:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSoundController\/title","value":"SBSDKSoundController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSoundController\/fragments","value":[{"text":"SBSDKSoundController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSoundController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKSoundController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSoundType\/title","value":"SBSDKSoundType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSoundType\/fragments","value":[{"kind":"identifier","text":"SBSDKSoundType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSoundType\/navigatorTitle","value":[{"text":"SBSDKSoundType","kind":"identifier"}]}]}]}