{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"This is the default configuration with the properties initialized as mentioned in their description."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultConfiguration"},{"text":": ","kind":"text"},{"text":"SBSDKBaseScannerZoomConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerZoomConfiguration"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration\/defaultConfiguration","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerZoomConfiguration(cpy)defaultConfiguration","role":"symbol","title":"defaultConfiguration","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerZoomConfiguration","text":"SBSDKBaseScannerZoomConfiguration","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"defaultConfiguration","kind":"identifier"}],"roleHeading":"Type Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerzoomconfiguration\/defaultconfiguration"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerzoomconfiguration\/defaultconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerZoomConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerZoomConfiguration"}],"navigatorTitle":[{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration","title":"SBSDKBaseScannerZoomConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerzoomconfiguration","kind":"symbol","abstract":[{"type":"text","text":"The zoom configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"text":" ","type":"text"},{"text":"‘SBSDKBaseScannerViewController’ and subclasses allow the user to zoom the camera.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This class lets you customize the zooming user experience."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerZoomConfiguration/defaultConfiguration":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerZoomConfiguration","kind":"typeIdentifier","text":"SBSDKBaseScannerZoomConfiguration"}],"type":"topic","role":"symbol","title":"defaultConfiguration","navigatorTitle":[{"kind":"identifier","text":"defaultConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerzoomconfiguration\/defaultconfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration\/defaultConfiguration","abstract":[{"type":"text","text":"This is the default configuration with the properties initialized as mentioned in their description."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"defaultConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"defaultConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKBaseScannerZoomConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerZoomConfiguration"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"defaultConfiguration"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKBaseScannerZoomConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerZoomConfiguration"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerZoomConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration~1defaultConfiguration\/title","value":"defaultConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration~1defaultConfiguration\/fragments","value":[{"text":"defaultConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}