{"metadata":{"roleHeading":"Instance Property","title":"hash","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerScreenConfiguration(py)hash","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"identifier","text":"hash"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreenconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenConfiguration\/hash"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenConfiguration"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenConfiguration":{"title":"SBSDKUI2VINScannerScreenConfiguration","abstract":[{"type":"text","text":"Configuration of the screen for detecting VIN data."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VINScannerScreenConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreenconfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VINScannerScreenConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenConfiguration/hash":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenConfiguration\/hash","fragments":[{"text":"hash","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreenconfiguration\/hash","title":"hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenConfiguration\/title","op":"replace","value":"SBSDKUI2VINScannerScreenConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerScreenConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerScreenConfiguration"}]}]}]}