{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"screen","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"Default is “VINScanner”","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"screen","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"screen","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerScreenConfiguration(py)screen","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"screen","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreenconfiguration\/screen"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreenconfiguration\/screen"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenConfiguration\/screen"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"The configuration object should be applied for this screen.","type":"text"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenConfiguration":{"title":"SBSDKUI2VINScannerScreenConfiguration","abstract":[{"type":"text","text":"Configuration of the screen for detecting VIN data."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VINScannerScreenConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreenconfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VINScannerScreenConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenConfiguration/screen":{"type":"topic","navigatorTitle":[{"text":"screen","kind":"identifier"}],"title":"screen","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"screen","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The configuration object should be applied for this screen."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreenconfiguration\/screen","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenConfiguration\/screen"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"screen","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"screen","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"screen","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenConfiguration\/title","value":"SBSDKUI2VINScannerScreenConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerScreenConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerScreenConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenConfiguration~1screen\/title","value":"screen","op":"replace"},{"op":"replace","value":[{"text":"screen","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenConfiguration~1screen\/fragments"}]}]}