{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/us4X8","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"us4X8"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize"]]},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"us4X8","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKPageSize@SBSDKPageSizeUs4X8","roleHeading":"Case","role":"symbol","title":"SBSDKPageSize.us4X8","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSizeUs4X8"}]},"abstract":[{"type":"text","text":"4 x 8 (inches)           288 x 576 (pixels) at 72 DPI."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpagesize\/us4x8"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagesize\/us4x8"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize":{"kind":"symbol","abstract":[{"text":"Page size.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKPageSize","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagesize","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSize"}],"title":"SBSDKPageSize"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/us4X8":{"role":"symbol","type":"topic","kind":"symbol","title":"SBSDKPageSize.us4X8","url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/us4x8","abstract":[{"text":"4 x 8 (inches)           288 x 576 (pixels) at 72 DPI.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"us4X8"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/us4X8","navigatorTitle":[{"text":"SBSDKPageSizeUs4X8","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKPageSizeUs4X8"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKPageSizeUs4X8"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKPageSizeUs4X8"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKPageSize","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/fragments","value":[{"text":"SBSDKPageSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPageSize","kind":"identifier"}]},{"value":"SBSDKPageSizeUs4X8","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1us4X8\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1us4X8\/fragments","value":[{"kind":"identifier","text":"SBSDKPageSizeUs4X8"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}