{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkRecognizerViewController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"text":"SBSDKCheckRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didRecognizeCheck","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerResult","text":"SBSDKCheckRecognizerResult"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"text":"The check scanner viewController which recognized the check.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The check scanner result that have been recognized."}],"type":"paragraph"}],"name":"result"}],"kind":"parameters"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController","text":"SBSDKCheckRecognizerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didRecognizeCheck","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerResult","kind":"typeIdentifier","text":"SBSDKCheckRecognizerResult"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"checkRecognizerViewController:didRecognizeCheck:","kind":"identifier"}],"required":true,"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKCheckRecognizerViewControllerDelegate(im)checkRecognizerViewController:didRecognizeCheck:","title":"checkRecognizerViewController(_:didRecognizeCheck:)","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"text":"Informs the delegate, that the check scanner has successfully detected and recognized a check.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate\/checkrecognizerviewcontroller(_:didrecognizecheck:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate\/checkrecognizerviewcontroller(_:didrecognizecheck:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate\/checkRecognizerViewController(_:didRecognizeCheck:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}],"abstract":[{"type":"text","text":"Classic UI view controller that can be used to detect and recognize bank checks."}],"title":"SBSDKCheckRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckRecognizerViewController","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewControllerDelegate/checkRecognizerViewController(_:didRecognizeCheck:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkRecognizerViewController"},{"text":"(","kind":"text"},{"text":"SBSDKCheckRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didRecognizeCheck"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerResult","text":"SBSDKCheckRecognizerResult"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate\/checkrecognizerviewcontroller(_:didrecognizecheck:)","abstract":[{"text":"Informs the delegate, that the check scanner has successfully detected and recognized a check.","type":"text"}],"navigatorTitle":[{"text":"checkRecognizerViewController:didRecognizeCheck:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate\/checkRecognizerViewController(_:didRecognizeCheck:)","type":"topic","title":"checkRecognizerViewController(_:didRecognizeCheck:)","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewControllerDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckRecognizerViewControllerDelegate"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate","abstract":[{"type":"text","text":"The delegation protocol for the "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","type":"reference"},{"type":"text","text":" class."}],"navigatorTitle":[{"text":"SBSDKCheckRecognizerViewControllerDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate","type":"topic","title":"SBSDKCheckRecognizerViewControllerDelegate","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerResult":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCheckRecognizerResult"}],"type":"topic","navigatorTitle":[{"text":"SBSDKCheckRecognizerResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerResult","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerresult","role":"symbol","title":"SBSDKCheckRecognizerResult","kind":"symbol","abstract":[{"text":"The result object of a check recognition.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"checkRecognizerViewController:didRecognizeCheck:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkRecognizerViewController:didRecognizeCheck:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"checkRecognizerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController","text":"SBSDKCheckRecognizerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didRecognizeCheck:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKCheckRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/title","value":"SBSDKCheckRecognizerViewController"},{"value":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/fragments","op":"replace"},{"value":"checkRecognizerViewController:didRecognizeCheck:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate~1checkRecognizerViewController(_:didRecognizeCheck:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"checkRecognizerViewController:didRecognizeCheck:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate~1checkRecognizerViewController(_:didRecognizeCheck:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate\/title","value":"SBSDKCheckRecognizerViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerResult\/title","value":"SBSDKCheckRecognizerResult","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckRecognizerResult"}]}]}]}