{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"checkRecognizerViewControllerShouldRecognize","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","kind":"typeIdentifier","text":"SBSDKCheckRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The calling SBSDKCheckRecognizerViewController.","type":"text"}]}],"name":"controller"}]},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Return True to run the recognition on the next video frame, False otherwise. Can be used to pause the detection."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"title":"checkRecognizerViewControllerShouldRecognize(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkRecognizerViewControllerShouldRecognize"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController","text":"SBSDKCheckRecognizerViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKCheckRecognizerViewControllerDelegate(im)checkRecognizerViewControllerShouldRecognize:","roleHeading":"Instance Method","navigatorTitle":[{"text":"checkRecognizerViewControllerShouldRecognize:","kind":"identifier"}],"required":true,"symbolKind":"method","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Asks the delegate if the check recognizer should scan the next video frame. Optional."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate\/checkrecognizerviewcontrollershouldrecognize(_:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate\/checkrecognizerviewcontrollershouldrecognize(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate\/checkRecognizerViewControllerShouldRecognize(_:)"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewControllerDelegate/checkRecognizerViewControllerShouldRecognize(_:)":{"title":"checkRecognizerViewControllerShouldRecognize(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate\/checkRecognizerViewControllerShouldRecognize(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkRecognizerViewControllerShouldRecognize"},{"text":"(","kind":"text"},{"text":"SBSDKCheckRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate\/checkrecognizerviewcontrollershouldrecognize(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"checkRecognizerViewControllerShouldRecognize:","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Asks the delegate if the check recognizer should scan the next video frame. Optional."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewControllerDelegate":{"title":"SBSDKCheckRecognizerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckRecognizerViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewControllerDelegate"}],"abstract":[{"text":"The delegation protocol for the ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","isActive":true},{"type":"text","text":" class."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewController":{"title":"SBSDKCheckRecognizerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKCheckRecognizerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Classic UI view controller that can be used to detect and recognize bank checks."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"checkRecognizerViewControllerShouldRecognize:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"checkRecognizerViewControllerShouldRecognize:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"checkRecognizerViewControllerShouldRecognize:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","kind":"typeIdentifier","text":"SBSDKCheckRecognizerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"checkRecognizerViewControllerShouldRecognize:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate~1checkRecognizerViewControllerShouldRecognize(_:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate~1checkRecognizerViewControllerShouldRecognize(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"checkRecognizerViewControllerShouldRecognize:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKCheckRecognizerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate\/fragments","value":[{"text":"SBSDKCheckRecognizerViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/title","value":"SBSDKCheckRecognizerViewController","op":"replace"},{"op":"replace","value":[{"text":"SBSDKCheckRecognizerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/fragments"}]}]}