{"metadata":{"title":"checkRecognizerViewController(_:didChangeState:)","navigatorTitle":[{"text":"checkRecognizerViewController:didChangeState:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkRecognizerViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKCheckRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController"},{"text":", ","kind":"text"},{"text":"didChangeState","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckRecognizerState","text":"SBSDKCheckRecognizerState"},{"kind":"text","text":")"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKCheckRecognizerViewControllerDelegate(im)checkRecognizerViewController:didChangeState:","roleHeading":"Instance Method","symbolKind":"method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate\/checkrecognizerviewcontroller(_:didchangestate:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate\/checkrecognizerviewcontroller(_:didchangestate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate\/checkRecognizerViewController(_:didChangeState:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Informs the delegate, that the check scanner has changed its detection\/recognition state. Optional."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkRecognizerViewController"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"text":"SBSDKCheckRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didChangeState"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckRecognizerState","kind":"typeIdentifier","text":"SBSDKCheckRecognizerState"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The check scanner viewController that changed its state."}],"type":"paragraph"}],"name":"controller"},{"name":"state","content":[{"inlineContent":[{"type":"text","text":"The current state of the check scanner."}],"type":"paragraph"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewControllerDelegate":{"type":"topic","kind":"symbol","title":"SBSDKCheckRecognizerViewControllerDelegate","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCheckRecognizerViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewControllerDelegate"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate","abstract":[{"text":"The delegation protocol for the ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","isActive":true},{"text":" class.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerState":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerState"}],"title":"SBSDKCheckRecognizerState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckRecognizerState","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The live recognition state of the check scanner."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","role":"symbol","title":"SBSDKCheckRecognizerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller","abstract":[{"type":"text","text":"Classic UI view controller that can be used to detect and recognize bank checks."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewControllerDelegate/checkRecognizerViewController(_:didChangeState:)":{"type":"topic","title":"checkRecognizerViewController(_:didChangeState:)","abstract":[{"type":"text","text":"Informs the delegate, that the check scanner has changed its detection\/recognition state. Optional."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"checkRecognizerViewController:didChangeState:"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate\/checkrecognizerviewcontroller(_:didchangestate:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate\/checkRecognizerViewController(_:didChangeState:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCheckRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didChangeState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCheckRecognizerState","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckRecognizerState","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"checkRecognizerViewController:didChangeState:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"checkRecognizerViewController:didChangeState:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"checkRecognizerViewController:"},{"text":"(","kind":"text"},{"text":"SBSDKCheckRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"text":"didChangeState:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckRecognizerState","kind":"typeIdentifier","text":"SBSDKCheckRecognizerState"},{"text":") ","kind":"text"},{"text":"state","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKCheckRecognizerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate\/title"},{"value":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate\/fragments"},{"value":"SBSDKCheckRecognizerState","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckRecognizerState"}]},{"op":"replace","value":"SBSDKCheckRecognizerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/fragments","op":"replace","value":[{"text":"SBSDKCheckRecognizerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate~1checkRecognizerViewController(_:didChangeState:)\/title","value":"checkRecognizerViewController:didChangeState:"},{"value":[{"text":"- ","kind":"text"},{"text":"checkRecognizerViewController:didChangeState:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate~1checkRecognizerViewController(_:didChangeState:)\/fragments","op":"replace"}]}]}