{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"outputMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOutputMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOutputMode","text":"SBSDKOutputMode"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkscanbotbinarizationfilter\/init(outputmode:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkscanbotbinarizationfilter\/init(outputmode:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScanbotBinarizationFilter\/init(outputMode:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"outputMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKOutputMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOutputMode"},{"kind":"text","text":")"}],"title":"init(outputMode:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKScanbotBinarizationFilter(im)initWithOutputMode:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithOutputMode:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScanbotBinarizationFilter"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScanbotBinarizationFilter":{"role":"symbol","title":"SBSDKScanbotBinarizationFilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScanbotBinarizationFilter"}],"abstract":[{"type":"text","text":"Automatic binarization filter. This filter is a good starting point for most use cases."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScanbotBinarizationFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKScanbotBinarizationFilter"}],"url":"\/documentation\/scanbotsdk\/sbsdkscanbotbinarizationfilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.2"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScanbotBinarizationFilter/init(outputMode:)":{"role":"symbol","title":"init(outputMode:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"outputMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKOutputMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOutputMode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScanbotBinarizationFilter\/init(outputMode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithOutputMode:"}],"url":"\/documentation\/scanbotsdk\/sbsdkscanbotbinarizationfilter\/init(outputmode:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOutputMode":{"role":"symbol","title":"SBSDKOutputMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOutputMode"}],"abstract":[{"type":"text","text":"Output mode of binarization filter."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOutputMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKOutputMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkoutputmode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithOutputMode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOutputMode:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithOutputMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOutputMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOutputMode","text":"SBSDKOutputMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"outputMode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanbotBinarizationFilter\/title","value":"SBSDKScanbotBinarizationFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanbotBinarizationFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKScanbotBinarizationFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanbotBinarizationFilter~1init(outputMode:)\/title","value":"initWithOutputMode:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanbotBinarizationFilter~1init(outputMode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOutputMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOutputMode\/title","value":"SBSDKOutputMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOutputMode\/fragments","value":[{"kind":"identifier","text":"SBSDKOutputMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}