{"metadata":{"roleHeading":"Instance Property","title":"outputMode","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"outputMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOutputMode","text":"SBSDKOutputMode","kind":"typeIdentifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKScanbotBinarizationFilter(py)outputMode","symbolKind":"property","navigatorTitle":[{"text":"outputMode","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscanbotbinarizationfilter\/outputmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscanbotbinarizationfilter\/outputmode"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScanbotBinarizationFilter"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScanbotBinarizationFilter\/outputMode"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"outputMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKOutputMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOutputMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOutputMode"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Output mode of the filter. BINARY will return a black and white image, GRAYSCALE will return an antialiased"},{"text":" ","type":"text"},{"type":"text","text":"grayscale image."},{"text":" ","type":"text"},{"text":"Default is BINARY","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScanbotBinarizationFilter":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKScanbotBinarizationFilter"}],"abstract":[{"text":"Automatic binarization filter. This filter is a good starting point for most use cases.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScanbotBinarizationFilter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScanbotBinarizationFilter","kind":"identifier"}],"title":"SBSDKScanbotBinarizationFilter","url":"\/documentation\/scanbotsdk\/sbsdkscanbotbinarizationfilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScanbotBinarizationFilter/outputMode":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"outputMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOutputMode","text":"SBSDKOutputMode"}],"navigatorTitle":[{"text":"outputMode","kind":"identifier"}],"title":"outputMode","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscanbotbinarizationfilter\/outputmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScanbotBinarizationFilter\/outputMode","abstract":[{"text":"Output mode of the filter. BINARY will return a black and white image, GRAYSCALE will return an antialiased","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"grayscale image."},{"text":" ","type":"text"},{"type":"text","text":"Default is BINARY"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOutputMode":{"url":"\/documentation\/scanbotsdk\/sbsdkoutputmode","title":"SBSDKOutputMode","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOutputMode","kind":"symbol","abstract":[{"type":"text","text":"Output mode of binarization filter."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKOutputMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKOutputMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"outputMode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"outputMode","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKOutputMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOutputMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOutputMode"},{"text":" ","kind":"text"},{"text":"outputMode","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanbotBinarizationFilter\/title","op":"replace","value":"SBSDKScanbotBinarizationFilter"},{"value":[{"kind":"identifier","text":"SBSDKScanbotBinarizationFilter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanbotBinarizationFilter\/fragments"},{"op":"replace","value":[{"text":"SBSDKScanbotBinarizationFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanbotBinarizationFilter\/navigatorTitle"},{"value":"outputMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanbotBinarizationFilter~1outputMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanbotBinarizationFilter~1outputMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"outputMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOutputMode\/title","value":"SBSDKOutputMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOutputMode\/fragments","value":[{"text":"SBSDKOutputMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOutputMode\/navigatorTitle","value":[{"text":"SBSDKOutputMode","kind":"identifier"}],"op":"replace"}]}]}