{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration"]]},"metadata":{"platforms":[],"navigatorTitle":[{"text":"additionalDetectionParameters","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerBehaviorConfiguration(py)additionalDetectionParameters","title":"additionalDetectionParameters","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"additionalDetectionParameters"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeAdditionalParameters","text":"SBSDKBarcodeAdditionalParameters"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"Additional parameters for tweaking the detection of barcodes."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration\/additionaldetectionparameters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration\/additionaldetectionparameters"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/additionalDetectionParameters","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"additionalDetectionParameters","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAdditionalParameters","text":"SBSDKBarcodeAdditionalParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeAdditionalParameters"}],"languages":["swift"]}]}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}],"type":"paragraph"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAdditionalParameters":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeAdditionalParameters"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeadditionalparameters","abstract":[{"text":"A class that contains additional parameters for barcodes detection and filtering.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAdditionalParameters","title":"SBSDKBarcodeAdditionalParameters","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeAdditionalParameters"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerBehaviorConfiguration/additionalDetectionParameters":{"role":"symbol","type":"topic","title":"additionalDetectionParameters","navigatorTitle":[{"kind":"identifier","text":"additionalDetectionParameters"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration\/additionaldetectionparameters","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"additionalDetectionParameters","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKBarcodeAdditionalParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeAdditionalParameters","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/additionalDetectionParameters","abstract":[{"text":"Additional parameters for tweaking the detection of barcodes.","type":"text"}],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerBehaviorConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration"}],"title":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration"}],"deprecated":true,"kind":"symbol","abstract":[{"type":"text","text":"The configuration for the behavior of RTU-UI detector screens for barcodes."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"additionalDetectionParameters","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"additionalDetectionParameters","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBSDKBarcodeAdditionalParameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAdditionalParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeAdditionalParameters"},{"text":" * ","kind":"text"},{"text":"additionalDetectionParameters","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAdditionalParameters\/title","value":"SBSDKBarcodeAdditionalParameters"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAdditionalParameters\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeAdditionalParameters"}],"op":"replace"},{"value":"additionalDetectionParameters","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration~1additionalDetectionParameters\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration~1additionalDetectionParameters\/fragments","value":[{"text":"additionalDetectionParameters","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/title","value":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}