{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cameraZoomFactor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"The minimum value is 0.0 (zoomed out), the maximum value is 1.0 (zoomed in)."},{"text":" ","type":"text"},{"text":"You can use this value to zoom the camera programmatically but also to set an initial zoom factor.","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The relative zoom level of the camera relative to ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/cameraZoomRange","isActive":true},{"type":"text","text":"."}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/cameraZoomFactor","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration\/camerazoomfactor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration\/camerazoomfactor"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerBehaviorConfiguration(py)cameraZoomFactor","platforms":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraZoomFactor"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"title":"cameraZoomFactor","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"cameraZoomFactor","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerBehaviorConfiguration/cameraZoomFactor":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/cameraZoomFactor","navigatorTitle":[{"text":"cameraZoomFactor","kind":"identifier"}],"abstract":[{"type":"text","text":"The relative zoom level of the camera relative to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/cameraZoomRange"},{"type":"text","text":"."}],"title":"cameraZoomFactor","deprecated":true,"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration\/camerazoomfactor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraZoomFactor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerBehaviorConfiguration/cameraZoomRange":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraZoomRange","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKZoomRange","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKZoomRange"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration\/camerazoomrange","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/cameraZoomRange","title":"cameraZoomRange","abstract":[{"type":"text","text":"The range of valid camera zoom factors."}],"deprecated":true,"navigatorTitle":[{"text":"cameraZoomRange","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerBehaviorConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration","navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"The configuration for the behavior of RTU-UI detector screens for barcodes."}],"role":"symbol","deprecated":true,"kind":"symbol","type":"topic","title":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"cameraZoomFactor"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"cameraZoomFactor","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":" "},{"text":"cameraZoomFactor","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"cameraZoomFactor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration~1cameraZoomFactor\/title","op":"replace"},{"value":[{"text":"cameraZoomFactor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration~1cameraZoomFactor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration~1cameraZoomRange\/title","value":"cameraZoomRange"},{"op":"replace","value":[{"kind":"identifier","text":"cameraZoomRange"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration~1cameraZoomRange\/fragments"},{"value":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}