{"abstract":[{"text":"Set to ","type":"text"},{"code":"True","type":"codeVoice"},{"type":"text","text":" to enable and display the region of interest, to "},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isViewFinderEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/isViewFinderEnabled"},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerBehaviorConfiguration(py)isViewFinderEnabled","role":"symbol","symbolKind":"property","title":"isViewFinderEnabled","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isViewFinderEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":[],"navigatorTitle":[{"text":"isViewFinderEnabled","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration\/isviewfinderenabled"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration\/isviewfinderenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerBehaviorConfiguration/isViewFinderEnabled":{"navigatorTitle":[{"kind":"identifier","text":"isViewFinderEnabled"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isViewFinderEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":" to enable and display the region of interest, to "},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration\/isviewfinderenabled","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/isViewFinderEnabled","deprecated":true,"title":"isViewFinderEnabled","role":"symbol","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerBehaviorConfiguration":{"type":"topic","kind":"symbol","role":"symbol","title":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration","abstract":[{"type":"text","text":"The configuration for the behavior of RTU-UI detector screens for barcodes."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"isViewFinderEnabled","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isViewFinderEnabled","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isViewFinderEnabled"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration~1isViewFinderEnabled\/title","value":"isViewFinderEnabled","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration~1isViewFinderEnabled\/fragments","value":[{"text":"isViewFinderEnabled","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/title","op":"replace","value":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","kind":"identifier"}]}]}]}