{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration\/imageScale","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageScale"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"platforms":["iOS"]}]}],"abstract":[{"text":"The scaling factor for captured images. Values are clamped to the range 0.0 - 1.0.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2DocumentScannerViewController instead."}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration\/imagescale"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration\/imagescale"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"platforms":[],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerBehaviorConfiguration(py)imageScale","title":"imageScale","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"imageScale","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"imageScale","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerBehaviorConfiguration/imageScale":{"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration\/imageScale","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"imageScale","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"imageScale","navigatorTitle":[{"text":"imageScale","kind":"identifier"}],"abstract":[{"text":"The scaling factor for captured images. Values are clamped to the range 0.0 - 1.0.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration\/imagescale","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerBehaviorConfiguration":{"title":"SBSDKUIDocumentScannerBehaviorConfiguration","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration for the behavior of the document scanning screen."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"imageScale","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"imageScale","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier","text":"CGFloat"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageScale"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration~1imageScale\/title","value":"imageScale","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration~1imageScale\/fragments","value":[{"kind":"identifier","text":"imageScale"}],"op":"replace"},{"value":"SBSDKUIDocumentScannerBehaviorConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/fragments"},{"value":[{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}