{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithOverallFieldValueSemantics:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKValueSemantics","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueSemantics","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics"},{"text":") ","kind":"text"},{"text":"overallFieldValueSemantics","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fieldDetails:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKFieldValueSemantics *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fieldDetails"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Instance Method","title":"initWithOverallFieldValueSemantics:fieldDetails:","symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCompositeFieldValueSemantics(im)initWithOverallFieldValueSemantics:fieldDetails:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithOverallFieldValueSemantics:fieldDetails:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithOverallFieldValueSemantics:fieldDetails:"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcompositefieldvaluesemantics\/initwithoverallfieldvaluesemantics:fielddetails:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics\/initWithOverallFieldValueSemantics:fieldDetails:","interfaceLanguage":"occ"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCompositeFieldValueSemantics/initWithOverallFieldValueSemantics:fieldDetails:":{"url":"\/documentation\/scanbotsdk\/sbsdkcompositefieldvaluesemantics\/initwithoverallfieldvaluesemantics:fielddetails:","navigatorTitle":[{"text":"initWithOverallFieldValueSemantics:fieldDetails:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"initWithOverallFieldValueSemantics:fieldDetails:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics\/initWithOverallFieldValueSemantics:fieldDetails:","role":"symbol","title":"initWithOverallFieldValueSemantics:fieldDetails:","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCompositeFieldValueSemantics":{"kind":"symbol","abstract":[{"type":"text","text":"Report of a logical field value semantics verification. If some logical field, e.g. expiry date is present in"},{"type":"text","text":" "},{"type":"text","text":"multiple places in the document, it can occur that some entries are semantically correct and some are semantically"},{"text":" ","type":"text"},{"text":"incorrect. This report shows the overall status of the logical field value semantics verification and details for","type":"text"},{"type":"text","text":" "},{"text":"each field that was verified.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCompositeFieldValueSemantics"}],"url":"\/documentation\/scanbotsdk\/sbsdkcompositefieldvaluesemantics","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics","title":"SBSDKCompositeFieldValueSemantics","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKCompositeFieldValueSemantics","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueSemantics":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics","abstract":[{"text":"The result of the value semantics verification.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkvaluesemantics","role":"symbol","title":"SBSDKValueSemantics","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKValueSemantics","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKValueSemantics","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKCompositeFieldValueSemantics","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompositeFieldValueSemantics\/title","op":"replace"},{"value":[{"text":"SBSDKCompositeFieldValueSemantics","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompositeFieldValueSemantics\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompositeFieldValueSemantics\/navigatorTitle","value":[{"text":"SBSDKCompositeFieldValueSemantics","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/title","op":"replace","value":"SBSDKValueSemantics"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKValueSemantics"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/navigatorTitle","value":[{"text":"SBSDKValueSemantics","kind":"identifier"}]}]}]}