{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureHighResolutionImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"Default is false","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreenconfiguration\/capturehighresolutionimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreenconfiguration\/capturehighresolutionimage"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenConfiguration\/captureHighResolutionImage","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerScreenConfiguration(py)captureHighResolutionImage","navigatorTitle":[{"kind":"identifier","text":"captureHighResolutionImage"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureHighResolutionImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"captureHighResolutionImage","symbolKind":"property","roleHeading":"Instance Property"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenConfiguration"]]},"abstract":[{"type":"text","text":"Flag to capture high resolution image."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerScreenConfiguration/captureHighResolutionImage":{"url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreenconfiguration\/capturehighresolutionimage","kind":"symbol","navigatorTitle":[{"text":"captureHighResolutionImage","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenConfiguration\/captureHighResolutionImage","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureHighResolutionImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"Flag to capture high resolution image.","type":"text"}],"type":"topic","title":"captureHighResolutionImage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerScreenConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2CheckScannerScreenConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the screen for detecting check data."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreenconfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CheckScannerScreenConfiguration","kind":"identifier"}],"title":"SBSDKUI2CheckScannerScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"captureHighResolutionImage","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"captureHighResolutionImage"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"captureHighResolutionImage","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenConfiguration~1captureHighResolutionImage\/title","value":"captureHighResolutionImage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenConfiguration~1captureHighResolutionImage\/fragments","value":[{"text":"captureHighResolutionImage","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2CheckScannerScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerScreenConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2CheckScannerScreenConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}