{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentroottype\/supportedbarcodetypes(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentroottype\/supportedbarcodetypes(for:)"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentRootType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentRootType\/supportedBarcodeTypes(for:)"},"kind":"symbol","metadata":{"externalID":"c:@CM@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentRootType(cm)supportedBarcodeTypesFor:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method","extendedModule":"ScanbotBarcodeScannerSDK","title":"supportedBarcodeTypes(for:)","navigatorTitle":[{"kind":"identifier","text":"supportedBarcodeTypesFor:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedBarcodeTypes","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentRootType","kind":"typeIdentifier","text":"SBSDKBarcodeDocumentRootType"},{"text":"]) -> [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeType","kind":"typeIdentifier","text":"SBSDKBarcodeType"},{"text":"]","kind":"text"}],"roleHeading":"Type Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedBarcodeTypes"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"documentFormats"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKBarcodeDocumentRootType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentRootType","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentRootType"},{"kind":"text","text":"]) -> ["},{"text":"SBSDKBarcodeType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeType"},{"text":"]","kind":"text"}]}]},{"parameters":[{"name":"documentFormats","content":[{"inlineContent":[{"text":"An array of barcode document formats.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"An array of supported barcode types."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Retrieves the supported barcode types for a given array of barcode document formats."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentRootType/supportedBarcodeTypes(for:)":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentroottype\/supportedbarcodetypes(for:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentRootType\/supportedBarcodeTypes(for:)","kind":"symbol","title":"supportedBarcodeTypes(for:)","type":"topic","abstract":[{"type":"text","text":"Retrieves the supported barcode types for a given array of barcode document formats."}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedBarcodeTypes","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentRootType","text":"SBSDKBarcodeDocumentRootType","kind":"typeIdentifier"},{"text":"]) -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeType","text":"SBSDKBarcodeType"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"supportedBarcodeTypesFor:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 6.1.0"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentRootType":{"role":"symbol","title":"SBSDKBarcodeDocumentRootType","abstract":[{"text":"Root document type.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentRootType","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentroottype","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentRootType"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentRootType"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeType":{"title":"SBSDKBarcodeType","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetype","kind":"symbol","type":"topic","abstract":[{"text":"Class that represents a barcode type.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeType"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"supportedBarcodeTypesFor:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"supportedBarcodeTypesFor:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"NSArray<SBSDKBarcodeType *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"supportedBarcodeTypesFor:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBarcodeDocumentRootType *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentFormats"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"documentFormats","content":[{"type":"paragraph","inlineContent":[{"text":"An array of barcode document formats.","type":"text"}]}]}]},"op":"replace"},{"op":"replace","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"An array of supported barcode types."}],"type":"paragraph"}]},"path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentRootType~1supportedBarcodeTypes(for:)\/title","value":"supportedBarcodeTypesFor:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"supportedBarcodeTypesFor:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentRootType~1supportedBarcodeTypes(for:)\/fragments"},{"value":"SBSDKBarcodeDocumentRootType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentRootType\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentRootType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentRootType"}]},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentRootType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentRootType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeType\/title","value":"SBSDKBarcodeType"},{"value":[{"text":"SBSDKBarcodeType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeType"}]}]}]}