{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRegexFilter:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"regexFilter"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumSizeScore:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumSizeScore"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAdditionalQuietZone:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"addAdditionalQuietZone"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimum1DQuietZoneSize:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimum1DQuietZoneSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"stripCheckDigits:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"stripCheckDigits"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumTextLength:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumTextLength"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumTextLength:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maximumTextLength"},{"kind":"text","text":" "},{"kind":"identifier","text":"checksumAlgorithms:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKMSIPlesseyChecksumAlgorithm *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"checksumAlgorithms"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:checksumAlgorithms:","navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:checksumAlgorithms:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:checksumAlgorithms:"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatMSIPlesseyConfiguration(im)initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:checksumAlgorithms:","role":"symbol","symbolKind":"method","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:checksumAlgorithms:"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:stripcheckdigits:minimumtextlength:maximumtextlength:checksumalgorithms:"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration":{"role":"symbol","title":"SBSDKBarcodeFormatMSIPlesseyConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatMSIPlesseyConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatMSIPlesseyConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatmsiplesseyconfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration","abstract":[{"text":"MSI Plessey barcode configuration. Add to scanner configuration to scan MSI Plessey barcodes.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:checksumAlgorithms:":{"kind":"symbol","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:checksumAlgorithms:","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:checksumAlgorithms:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:stripcheckdigits:minimumtextlength:maximumtextlength:checksumalgorithms:","abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:checksumAlgorithms:","navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:checksumAlgorithms:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKBarcodeFormatMSIPlesseyConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatMSIPlesseyConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKBarcodeFormatMSIPlesseyConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration\/navigatorTitle","op":"replace"}]}]}