{"metadata":{"navigatorTitle":[{"text":"applicationCachesFolderURL","kind":"identifier"}],"title":"applicationCachesFolderURL","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation(cpy)applicationCachesFolderURL","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationCachesFolderURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"}],"symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationCachesFolderURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkstoragelocation\/applicationcachesfolderurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkstoragelocation\/applicationcachesfolderurl"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The URL of the applications caches folder.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation\/applicationCachesFolderURL","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageLocation/applicationCachesFolderURL":{"kind":"symbol","title":"applicationCachesFolderURL","url":"\/documentation\/scanbotsdk\/sbsdkstoragelocation\/applicationcachesfolderurl","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationCachesFolderURL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"}],"abstract":[{"text":"The URL of the applications caches folder.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation\/applicationCachesFolderURL","navigatorTitle":[{"text":"applicationCachesFolderURL","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageLocation":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation","abstract":[{"type":"text","text":"Descriptor and helper class for describing and creating a directory on the file system."}],"url":"\/documentation\/scanbotsdk\/sbsdkstoragelocation","kind":"symbol","title":"SBSDKStorageLocation","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageLocation"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageLocation"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"applicationCachesFolderURL","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"applicationCachesFolderURL","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"applicationCachesFolderURL","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"applicationCachesFolderURL","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation~1applicationCachesFolderURL\/title"},{"value":[{"text":"applicationCachesFolderURL","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation~1applicationCachesFolderURL\/fragments"},{"value":"SBSDKStorageLocation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/title"},{"value":[{"kind":"identifier","text":"SBSDKStorageLocation"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/fragments"},{"value":[{"text":"SBSDKStorageLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/navigatorTitle"}]}]}