{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenUIConfiguration\/topBarBackgroundColor","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Background color of the top bar."}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2CroppingViewController instead.","type":"text"}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenuiconfiguration\/topbarbackgroundcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenuiconfiguration\/topbarbackgroundcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarBackgroundColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"UIColor.black"},{"type":"text","text":"."}]}]}],"metadata":{"title":"topBarBackgroundColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topBarBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"topBarBackgroundColor","kind":"identifier"}],"platforms":[],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenUIConfiguration(py)topBarBackgroundColor"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenUIConfiguration"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenUIConfiguration/topBarBackgroundColor":{"navigatorTitle":[{"kind":"identifier","text":"topBarBackgroundColor"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenuiconfiguration\/topbarbackgroundcolor","kind":"symbol","title":"topBarBackgroundColor","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenUIConfiguration\/topBarBackgroundColor","role":"symbol","abstract":[{"type":"text","text":"Background color of the top bar."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"topBarBackgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"deprecated":true},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenUIConfiguration":{"kind":"symbol","title":"SBSDKUICroppingScreenUIConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICroppingScreenUIConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenUIConfiguration"}],"abstract":[{"type":"text","text":"Configuration for user interface of the page cropping screen."}],"deprecated":true,"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenuiconfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenUIConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"topBarBackgroundColor","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"topBarBackgroundColor","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"topBarBackgroundColor"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenUIConfiguration~1topBarBackgroundColor\/title","value":"topBarBackgroundColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenUIConfiguration~1topBarBackgroundColor\/fragments","op":"replace","value":[{"text":"topBarBackgroundColor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenUIConfiguration\/title","op":"replace","value":"SBSDKUICroppingScreenUIConfiguration"},{"op":"replace","value":[{"text":"SBSDKUICroppingScreenUIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenUIConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUICroppingScreenUIConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}