{"sections":[],"abstract":[{"type":"text","text":"Select a 4k UHD (3840x2160) video resolution."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution\/UHD","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoframeresolution\/uhd"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoframeresolution\/uhd"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKVideoFrameResolution@SBSDKVideoFrameResolutionUHD","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UHD","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"SBSDKVideoFrameResolution.UHD","navigatorTitle":[{"text":"SBSDKVideoFrameResolutionUHD","kind":"identifier"}],"symbolKind":"case"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UHD"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFrameResolution":{"abstract":[{"text":"An enum describing the resolution of a video or camera stream.","type":"text"}],"title":"SBSDKVideoFrameResolution","url":"\/documentation\/scanbotsdk\/sbsdkvideoframeresolution","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFrameResolution/UHD":{"title":"SBSDKVideoFrameResolution.UHD","abstract":[{"type":"text","text":"Select a 4k UHD (3840x2160) video resolution."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionUHD"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UHD"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvideoframeresolution\/uhd","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution\/UHD","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKVideoFrameResolutionUHD"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionUHD"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKVideoFrameResolutionUHD","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution\/title","op":"replace","value":"SBSDKVideoFrameResolution"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution\/fragments","op":"replace","value":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution\/navigatorTitle","op":"replace","value":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution~1UHD\/title","op":"replace","value":"SBSDKVideoFrameResolutionUHD"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution~1UHD\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionUHD"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}