{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2capturefeedback\/hash"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"hash","symbolKind":"property","role":"symbol","fragments":[{"kind":"identifier","text":"hash"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CaptureFeedback(py)hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback\/hash"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CaptureFeedback":{"role":"symbol","title":"SBSDKUI2CaptureFeedback","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2capturefeedback","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback","abstract":[{"type":"text","text":"Configuration of the feedback shown after snapping a page."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CaptureFeedback/hash":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback\/hash","kind":"symbol","fragments":[{"text":"hash","kind":"identifier"}],"title":"hash","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2capturefeedback\/hash"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2CaptureFeedback","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CaptureFeedback\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CaptureFeedback"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CaptureFeedback\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CaptureFeedback"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CaptureFeedback\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}