{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"binarizationFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"binarizationFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"kind":"text","text":"?"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"binarizationFilter"}],"title":"binarizationFilter","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration(py)binarizationFilter"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/binarizationfilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/binarizationfilter"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/binarizationFilter","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Filter to apply to the input image when adding pages with binarization."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"abstract":[{"type":"text","text":"Base class for all parametric filters."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKParametricFilter"}],"type":"topic","kind":"symbol","title":"SBSDKParametricFilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/binarizationFilter":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"binarizationFilter"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/binarizationFilter","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"binarizationFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Filter to apply to the input image when adding pages with binarization."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/binarizationfilter","title":"binarizationFilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration":{"abstract":[{"type":"text","text":"The parameters "},{"type":"codeVoice","code":"pageSize"},{"type":"text","text":", "},{"type":"codeVoice","code":"pageFit"},{"type":"text","text":", "},{"type":"codeVoice","code":"dpi"},{"type":"text","text":" and "},{"type":"codeVoice","code":"resamplingMethod"},{"type":"text","text":" interact in a complex way"},{"type":"text","text":" "},{"type":"text","text":"when adding bitmap images (JPEG, PNG, or raw) to the PDF."},{"type":"text","text":" "},{"type":"text","text":"There are three cases to consider:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration","role":"symbol","type":"topic","title":"SBSDKPDFConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"binarizationFilter","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"binarizationFilter"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"text":" * ","kind":"text"},{"text":"binarizationFilter","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title","op":"replace","value":"SBSDKParametricFilter"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments","op":"replace","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}]},{"value":"binarizationFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1binarizationFilter\/title"},{"value":[{"kind":"identifier","text":"binarizationFilter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1binarizationFilter\/fragments"},{"value":"SBSDKPDFConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/fragments"},{"value":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}