{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/initwithattributes:pagesize:pagedirection:pagefit:dpi:jpegquality:resamplingmethod:binarizationfilter:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration"]]},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:binarizationFilter:"}],"title":"initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:binarizationFilter:","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration(im)initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:binarizationFilter:","navigatorTitle":[{"kind":"identifier","text":"initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:binarizationFilter:"}],"role":"symbol"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:binarizationFilter:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAttributes:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFAttributes","kind":"typeIdentifier","text":"SBSDKPDFAttributes"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"attributes"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageSize:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageSize","kind":"typeIdentifier","text":"SBSDKPageSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pageSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageDirection:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageDirection","kind":"typeIdentifier","text":"SBSDKPageDirection"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pageDirection"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageFit:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageFit","kind":"typeIdentifier","text":"SBSDKPageFit"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pageFit"},{"kind":"text","text":" "},{"kind":"identifier","text":"dpi:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"dpi"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpegQuality:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"jpegQuality"},{"kind":"text","text":" "},{"kind":"identifier","text":"resamplingMethod:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKResamplingMethod","kind":"typeIdentifier","text":"SBSDKResamplingMethod"},{"kind":"text","text":") "},{"kind":"internalParam","text":"resamplingMethod"},{"kind":"text","text":" "},{"kind":"identifier","text":"binarizationFilter:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier","text":"SBSDKParametricFilter"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"binarizationFilter"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration":{"abstract":[{"type":"text","text":"The parameters "},{"type":"codeVoice","code":"pageSize"},{"type":"text","text":", "},{"type":"codeVoice","code":"pageFit"},{"type":"text","text":", "},{"type":"codeVoice","code":"dpi"},{"type":"text","text":" and "},{"type":"codeVoice","code":"resamplingMethod"},{"type":"text","text":" interact in a complex way"},{"type":"text","text":" "},{"type":"text","text":"when adding bitmap images (JPEG, PNG, or raw) to the PDF."},{"type":"text","text":" "},{"type":"text","text":"There are three cases to consider:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration","role":"symbol","type":"topic","title":"SBSDKPDFConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes","abstract":[{"type":"text","text":"PDF attributes."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFAttributes"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFAttributes"}],"title":"SBSDKPDFAttributes"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:binarizationFilter:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:binarizationFilter:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:binarizationFilter:","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/initwithattributes:pagesize:pagedirection:pagefit:dpi:jpegquality:resamplingmethod:binarizationfilter:","role":"symbol","navigatorTitle":[{"text":"initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:binarizationFilter:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:binarizationFilter:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod","type":"topic","navigatorTitle":[{"text":"SBSDKResamplingMethod","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKResamplingMethod","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Resampling method.","type":"text"}],"title":"SBSDKResamplingMethod"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize":{"title":"SBSDKPageSize","type":"topic","abstract":[{"text":"Page size.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagesize","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSize"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageSize"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"abstract":[{"type":"text","text":"Base class for all parametric filters."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKParametricFilter"}],"type":"topic","kind":"symbol","title":"SBSDKParametricFilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageDirection":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpagedirection","abstract":[{"type":"text","text":"Page direction."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageDirection"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageDirection"}],"title":"SBSDKPageDirection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageFit":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageFit"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagefit","title":"SBSDKPageFit","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit","kind":"symbol","abstract":[{"type":"text","text":"Page fit."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageFit"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKPDFConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKPDFAttributes","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/title"},{"op":"replace","value":[{"text":"SBSDKPDFAttributes","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFAttributes"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/navigatorTitle"},{"op":"replace","value":"SBSDKResamplingMethod","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/title"},{"op":"replace","value":[{"text":"SBSDKResamplingMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/fragments"},{"op":"replace","value":[{"text":"SBSDKResamplingMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/navigatorTitle"},{"op":"replace","value":"SBSDKPageSize","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPageSize"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/fragments"},{"op":"replace","value":[{"text":"SBSDKPageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/navigatorTitle"},{"op":"replace","value":"SBSDKParametricFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/navigatorTitle"},{"op":"replace","value":"SBSDKPageDirection","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection\/title"},{"op":"replace","value":[{"text":"SBSDKPageDirection","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPageDirection"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection\/navigatorTitle"},{"op":"replace","value":"SBSDKPageFit","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/title"},{"op":"replace","value":[{"text":"SBSDKPageFit","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/fragments"},{"op":"replace","value":[{"text":"SBSDKPageFit","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}