{"metadata":{"symbolKind":"property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"jpegQuality","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpegQuality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"jpegQuality","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration(py)jpegQuality"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"JPEG quality for images."},{"type":"text","text":" "},{"type":"text","text":"Applies if an image is added as a cv::Mat and therefore needs to be encoded."},{"type":"text","text":" "},{"type":"text","text":"Also applies if "},{"type":"codeVoice","code":"resamplingMethod"},{"type":"text","text":" not NONE and the image being added needs to be"},{"type":"text","text":" "},{"type":"text","text":"downscaled. Otherwise, when adding JPEG files to the PDF, the files are copied directly into"},{"type":"text","text":" "},{"type":"text","text":"the PDF and not re-encoded, which is many times faster and also preserves the quality of the"},{"type":"text","text":" "},{"type":"text","text":"original."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/jpegquality"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/jpegquality"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/jpegQuality"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpegQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is 80"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration":{"abstract":[{"type":"text","text":"The parameters "},{"type":"codeVoice","code":"pageSize"},{"type":"text","text":", "},{"type":"codeVoice","code":"pageFit"},{"type":"text","text":", "},{"type":"codeVoice","code":"dpi"},{"type":"text","text":" and "},{"type":"codeVoice","code":"resamplingMethod"},{"type":"text","text":" interact in a complex way"},{"type":"text","text":" "},{"type":"text","text":"when adding bitmap images (JPEG, PNG, or raw) to the PDF."},{"type":"text","text":" "},{"type":"text","text":"There are three cases to consider:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration","role":"symbol","type":"topic","title":"SBSDKPDFConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/jpegQuality":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpegQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"jpegQuality"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/jpegQuality","type":"topic","title":"jpegQuality","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/jpegquality","abstract":[{"type":"text","text":"JPEG quality for images."},{"type":"text","text":" "},{"type":"text","text":"Applies if an image is added as a cv::Mat and therefore needs to be encoded."},{"type":"text","text":" "},{"type":"text","text":"Also applies if "},{"code":"resamplingMethod","type":"codeVoice"},{"type":"text","text":" not NONE and the image being added needs to be"},{"type":"text","text":" "},{"type":"text","text":"downscaled. Otherwise, when adding JPEG files to the PDF, the files are copied directly into"},{"type":"text","text":" "},{"type":"text","text":"the PDF and not re-encoded, which is many times faster and also preserves the quality of the"},{"type":"text","text":" "},{"type":"text","text":"original."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"jpegQuality","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"jpegQuality","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpegQuality"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKPDFConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/navigatorTitle"},{"op":"replace","value":"jpegQuality","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1jpegQuality\/title"},{"op":"replace","value":[{"kind":"identifier","text":"jpegQuality"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1jpegQuality\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}