{"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"title":"pageFit","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageFit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageFit","text":"SBSDKPageFit","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"pageFit","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration(py)pageFit"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/pageFit","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageFit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKPageFit","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageFit"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is FIT_IN"}]}],"kind":"content"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/pagefit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/pagefit"]}],"abstract":[{"text":"How to fit the image into the page. Only used if ","type":"text"},{"code":"pageSize","type":"codeVoice"},{"text":" is not ","type":"text"},{"code":"CUSTOM","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The image can either be stretched to fill the page,","type":"text"},{"text":" ","type":"text"},{"text":"in one of three ways, or centered on the page without stretching.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration","abstract":[{"text":"The parameters ","type":"text"},{"code":"pageSize","type":"codeVoice"},{"text":", ","type":"text"},{"code":"pageFit","type":"codeVoice"},{"text":", ","type":"text"},{"code":"dpi","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"resamplingMethod","type":"codeVoice"},{"text":" interact in a complex way","type":"text"},{"text":" ","type":"text"},{"text":"when adding bitmap images (JPEG, PNG, or raw) to the PDF.","type":"text"},{"text":" ","type":"text"},{"text":"There are three cases to consider:","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"role":"symbol","title":"SBSDKPDFConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageFit":{"type":"topic","navigatorTitle":[{"text":"SBSDKPageFit","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpagefit","abstract":[{"type":"text","text":"Page fit."}],"title":"SBSDKPageFit","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageFit","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/pageFit":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/pageFit","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/pagefit","type":"topic","title":"pageFit","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageFit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPageFit","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageFit"}],"role":"symbol","navigatorTitle":[{"text":"pageFit","kind":"identifier"}],"abstract":[{"text":"How to fit the image into the page. Only used if ","type":"text"},{"code":"pageSize","type":"codeVoice"},{"text":" is not ","type":"text"},{"code":"CUSTOM","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The image can either be stretched to fill the page,","type":"text"},{"text":" ","type":"text"},{"text":"in one of three ways, or centered on the page without stretching.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"pageFit","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"pageFit"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageFit","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit","kind":"typeIdentifier","text":"SBSDKPageFit"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageFit"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKPDFConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/navigatorTitle","op":"replace"},{"value":"SBSDKPageFit","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/title","op":"replace"},{"value":[{"text":"SBSDKPageFit","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPageFit"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/navigatorTitle","op":"replace"},{"value":"pageFit","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1pageFit\/title","op":"replace"},{"value":[{"kind":"identifier","text":"pageFit"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1pageFit\/fragments","op":"replace"}]}]}