{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"detectDocumentPolygon","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"kind":"text","text":" "},{"kind":"internalParam","text":"image"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"text":"visibleImageRect","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"smoothingEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"useLiveDetectionParameters","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult"},{"kind":"text","text":"?"}]}]},{"kind":"parameters","parameters":[{"name":"image","content":[{"inlineContent":[{"text":"The image to analyze.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The unified image rectangle that should be analyzed.","type":"text"},{"type":"text","text":" "},{"text":"(0, 0)-(1, 1) or an empty rect means the whole image is being analyzed.","type":"text"}]}],"name":"visibleImageRect"},{"name":"smoothingEnabled","content":[{"inlineContent":[{"text":"Set to YES if you want the polygon output to be smoothed with latest frames. If you choose to use smoothing","type":"text"},{"type":"text","text":" "},{"type":"text","text":"you should call resetSmoothingData regularly."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set YES if you want to use faster live detection. Live detection is less reliable than normal detection."}]}],"name":"useLiveDetectionParameters"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The detection result containing the status and a polygon."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector\/detectdocumentpolygon(on:visibleimagerect:smoothingenabled:uselivedetectionparameters:)-65h53"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector\/detectdocumentpolygon(on:visibleimagerect:smoothingenabled:uselivedetectionparameters:)-65h53"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector"]]},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetector(im)detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"detectDocumentPolygon","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"text":"visibleImageRect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"smoothingEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"useLiveDetectionParameters","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult"},{"text":"?","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector\/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-65h53"},"abstract":[{"text":"Executes an edge detection algorithm on the given image and returns","type":"text"},{"type":"text","text":" "},{"text":"a polygon describing the extends of the detected documents box.","type":"text"},{"type":"text","text":" "},{"text":"For a short period of time the uncompressed image data is hold twice in memory. Use with attention.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetector":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector","type":"topic","abstract":[{"text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDetector"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"kind":"symbol","title":"SBSDKDocumentDetector","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetector/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-65h53":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector\/detectdocumentpolygon(on:visibleimagerect:smoothingenabled:uselivedetectionparameters:)-65h53","title":"detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Executes an edge detection algorithm on the given image and returns"},{"type":"text","text":" "},{"text":"a polygon describing the extends of the detected documents box.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For a short period of time the uncompressed image data is hold twice in memory. Use with attention."}],"navigatorTitle":[{"kind":"identifier","text":"detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector\/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-65h53","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"detectDocumentPolygon","kind":"identifier"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":", ","kind":"text"},{"text":"visibleImageRect","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"smoothingEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"useLiveDetectionParameters"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectorResult":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"title":"SBSDKDocumentDetectorResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectorresult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"This class represents the result of a document detection","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"on an image."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult","kind":"typeIdentifier","text":"SBSDKDocumentDetectorResult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult"},{"kind":"text","text":" *) "},{"text":"detectDocumentPolygonOnImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"text":" ","kind":"text"},{"text":"visibleImageRect:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"visibleImageRect","kind":"internalParam"},{"kind":"text","text":" "},{"text":"smoothingEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"smoothingEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"useLiveDetectionParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"useLiveDetectionParameters"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/title","value":"SBSDKDocumentDetector","op":"replace"},{"op":"replace","value":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/fragments"},{"op":"replace","value":"detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector~1detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-65h53\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector~1detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-65h53\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:","kind":"identifier"}]},{"op":"replace","value":"SBSDKDocumentDetectorResult","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectorResult\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectorResult\/fragments"}]}]}