{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(detectDocumentPolygonOnSampleBuffer:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectDocumentPolygon"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sampleBuffer"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"visibleImageRect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"smoothingEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"useLiveDetectionParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") -> ","kind":"text"},{"text":"SBSDKDocumentDetectorResult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult"},{"kind":"text","text":"?"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The CMSampleBufferRef to analyze."}],"type":"paragraph"}],"name":"sampleBuffer"},{"name":"visibleImageRect","content":[{"type":"paragraph","inlineContent":[{"text":"The unified image rectangle that should be analyzed.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"(0, 0)-(1, 1) or an empty rect means the whole image is being analyzed."}]}]},{"name":"smoothingEnabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set to YES if you want the polygon output to be smoothed with latest frames. If you choose to use smoothing"},{"text":" ","type":"text"},{"text":"you should call resetSmoothingData regularly.","type":"text"}]}]},{"name":"useLiveDetectionParameters","content":[{"inlineContent":[{"type":"text","text":"Set YES if you want to use faster live detection. Live detection is less reliable than normal detection."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The detection result containing the status and a polygon."}]}]}],"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"detectDocumentPolygonOnSampleBuffer:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:"}],"roleHeading":"Instance Method","title":"detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)","symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetector(im)detectDocumentPolygonOnSampleBuffer:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectDocumentPolygon"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"kind":"text","text":", "},{"text":"visibleImageRect","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"text":"smoothingEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"useLiveDetectionParameters","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult"},{"text":"?","kind":"text"}]},"abstract":[{"type":"text","text":"Executes an edge detection algorithm on the given sample buffer and returns"},{"text":" ","type":"text"},{"text":"a polygon describing the extends of the detected documents box.","type":"text"},{"text":" ","type":"text"},{"text":"For a short period of time the uncompressed image data is hold twice in memory. Use with attention.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector\/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-1re5b","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector\/detectdocumentpolygon(on:visibleimagerect:smoothingenabled:uselivedetectionparameters:)-1re5b"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector\/detectdocumentpolygon(on:visibleimagerect:smoothingenabled:uselivedetectionparameters:)-1re5b"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetector":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"title":"SBSDKDocumentDetector","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetector"}],"abstract":[{"type":"text","text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 5.0.2","type":"text"}],"role":"collection","type":"topic","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetector/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-1re5b":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector\/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-1re5b","navigatorTitle":[{"text":"detectDocumentPolygonOnSampleBuffer:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:","kind":"identifier"}],"title":"detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector\/detectdocumentpolygon(on:visibleimagerect:smoothingenabled:uselivedetectionparameters:)-1re5b","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"detectDocumentPolygon","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"visibleImageRect"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"smoothingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useLiveDetectionParameters"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"type":"text","text":"Executes an edge detection algorithm on the given sample buffer and returns"},{"type":"text","text":" "},{"type":"text","text":"a polygon describing the extends of the detected documents box."},{"text":" ","type":"text"},{"text":"For a short period of time the uncompressed image data is hold twice in memory. Use with attention.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectorResult":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"abstract":[{"text":"This class represents the result of a document detection","type":"text"},{"text":" ","type":"text"},{"text":"on an image.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"kind":"symbol","title":"SBSDKDocumentDetectorResult","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectorresult"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"detectDocumentPolygonOnSampleBuffer:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detectDocumentPolygonOnSampleBuffer:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"detectDocumentPolygonOnSampleBuffer:"},{"kind":"text","text":"("},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"opaqueCMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@opaqueCMSampleBuffer"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sampleBuffer"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibleImageRect:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") "},{"text":"visibleImageRect","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"smoothingEnabled:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"smoothingEnabled"},{"text":" ","kind":"text"},{"text":"useLiveDetectionParameters:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"useLiveDetectionParameters","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/title","value":"SBSDKDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetector"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector~1detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-1re5b\/title","value":"detectDocumentPolygonOnSampleBuffer:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"detectDocumentPolygonOnSampleBuffer:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector~1detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-1re5b\/fragments"},{"value":"SBSDKDocumentDetectorResult","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectorResult\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectorResult\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}