{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector"]]},"kind":"symbol","abstract":[{"type":"text","text":"Array of all detected horizontal edges during last detection. Can be used for manual magnetic cropping."}],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"detectedHorizontalEdges","kind":"identifier"},{"kind":"text","text":": ["},{"text":"SBSDKPolygonEdge","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygonEdge","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetector(py)detectedHorizontalEdges","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","title":"detectedHorizontalEdges","navigatorTitle":[{"text":"detectedHorizontalEdges","kind":"identifier"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector\/detectedhorizontaledges"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector\/detectedhorizontaledges"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectedHorizontalEdges","kind":"identifier"},{"kind":"text","text":": ["},{"text":"SBSDKPolygonEdge","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygonEdge","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygonEdge"},{"text":"]? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector\/detectedHorizontalEdges","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetector":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetector","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector","abstract":[{"text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector","title":"SBSDKDocumentDetector"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetector/detectedHorizontalEdges":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector\/detectedhorizontaledges","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Array of all detected horizontal edges during last detection. Can be used for manual magnetic cropping."}],"title":"detectedHorizontalEdges","type":"topic","navigatorTitle":[{"kind":"identifier","text":"detectedHorizontalEdges"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"detectedHorizontalEdges","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygonEdge","text":"SBSDKPolygonEdge","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector\/detectedHorizontalEdges"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygonEdge":{"abstract":[{"text":"Helper class that encapsulates an edge of a polygon and provides geometric helper methods.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKPolygonEdge","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygonedge","title":"SBSDKPolygonEdge","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygonEdge","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygonEdge","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"detectedHorizontalEdges","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"detectedHorizontalEdges"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSArray<SBSDKPolygonEdge *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detectedHorizontalEdges"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/title","op":"replace","value":"SBSDKDocumentDetector"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetector"}]},{"value":"detectedHorizontalEdges","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector~1detectedHorizontalEdges\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"detectedHorizontalEdges"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector~1detectedHorizontalEdges\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygonEdge\/title","op":"replace","value":"SBSDKPolygonEdge"},{"op":"replace","value":[{"text":"SBSDKPolygonEdge","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygonEdge\/fragments"}]}]}