{"abstract":[{"text":"Executes an edge detection algorithm on the given image and returns","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"a polygon describing the extends of the detected photos box."},{"text":" ","type":"text"},{"type":"text","text":"For a short period of time the uncompressed image data is hold twice in memory. Use with attention."}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector\/detectphotopolygon(on:visibleimagerect:smoothingenabled:)-9jg0t"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector\/detectphotopolygon(on:visibleimagerect:smoothingenabled:)-9jg0t"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector\/detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-9jg0t"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectPhotoPolygon"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"kind":"text","text":" "},{"text":"image","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"visibleImageRect"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"text":"smoothingEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"text":"SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image to analyze."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The unified image rectangle that should be analyzed."},{"text":" ","type":"text"},{"type":"text","text":"(0, 0)-(1, 1) or an empty rect means the whole image is being analyzed."}],"type":"paragraph"}],"name":"visibleImageRect"},{"name":"smoothingEnabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set to YES if you want the polygon output to be smoothed with latest frames. If you choose to use smoothing"},{"type":"text","text":" "},{"type":"text","text":"you should call resetSmoothingData regularly."}]}]}]},{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The detection result containing the status and a polygon."}]}]}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetector(im)detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectPhotoPolygon"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"visibleImageRect"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"smoothingEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"text":"SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetector/detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-9jg0t":{"abstract":[{"type":"text","text":"Executes an edge detection algorithm on the given image and returns"},{"type":"text","text":" "},{"type":"text","text":"a polygon describing the extends of the detected photos box."},{"text":" ","type":"text"},{"text":"For a short period of time the uncompressed image data is hold twice in memory. Use with attention.","type":"text"}],"navigatorTitle":[{"text":"detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector\/detectphotopolygon(on:visibleimagerect:smoothingenabled:)-9jg0t","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectPhotoPolygon"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"visibleImageRect"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"smoothingEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector\/detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-9jg0t","title":"detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectorResult":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectorresult","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult","abstract":[{"type":"text","text":"This class represents the result of a document detection"},{"text":" ","type":"text"},{"text":"on an image.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"title":"SBSDKDocumentDetectorResult"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetector":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetector","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector","abstract":[{"text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector","title":"SBSDKDocumentDetector"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult"},{"kind":"text","text":" *) "},{"text":"detectPhotoPolygonOnImage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"visibleImageRect:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") "},{"text":"visibleImageRect","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"smoothingEnabled:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"smoothingEnabled","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector~1detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-9jg0t\/title","value":"detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector~1detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-9jg0t\/fragments","value":[{"text":"- ","kind":"text"},{"text":"detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectorResult\/title","value":"SBSDKDocumentDetectorResult","op":"replace"},{"value":[{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectorResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/title","value":"SBSDKDocumentDetector"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}