{"kind":"symbol","abstract":[{"text":"Set default detector mode. Unless the new instance of detector is initialized with ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector\/init(mode:)","isActive":true},{"text":" initializer, this new instance will have this mode set.","type":"text"}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"setDefaultDetectorMode:"}],"title":"setDefaultDetectorMode(_:)","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetector(cm)setDefaultDetectorMode:","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDefaultDetectorMode"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentDetectorMode","kind":"typeIdentifier","text":"SBSDKDocumentDetectorMode"},{"text":")","kind":"text"}],"symbolKind":"method"},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector\/setDefaultDetectorMode(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector\/setdefaultdetectormode(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector\/setdefaultdetectormode(_:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setDefaultDetectorMode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"newDefaultDetectorMode","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectorMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentDetectorMode"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The desired detector mode."}]}],"name":"newDefaultDetectorMode"}],"kind":"parameters"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetector":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"title":"SBSDKDocumentDetector","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetector"}],"abstract":[{"type":"text","text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 5.0.2","type":"text"}],"role":"collection","type":"topic","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetector/setDefaultDetectorMode(_:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setDefaultDetectorMode:"}],"title":"setDefaultDetectorMode(_:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDefaultDetectorMode"},{"kind":"text","text":"("},{"text":"SBSDKDocumentDetectorMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentDetectorMode","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Set default detector mode. Unless the new instance of detector is initialized with "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector\/init(mode:)","isActive":true,"type":"reference"},{"type":"text","text":" initializer, this new instance will have this mode set."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector\/setdefaultdetectormode(_:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector\/setDefaultDetectorMode(_:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectorMode":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectorMode"}],"title":"SBSDKDocumentDetectorMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectorMode"}],"abstract":[{"text":"The mode of the document detector: standard or machine-learning-based.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectormode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorMode"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetector/init(mode:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithMode:"}],"title":"init(mode:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mode"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectorMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentDetectorMode"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Designated initialiizer."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector\/init(mode:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector\/init(mode:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"setDefaultDetectorMode:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setDefaultDetectorMode:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setDefaultDetectorMode:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectorMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentDetectorMode"},{"text":") ","kind":"text"},{"text":"newDefaultDetectorMode","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/title","value":"SBSDKDocumentDetector","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDetector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector~1setDefaultDetectorMode(_:)\/title","value":"setDefaultDetectorMode:"},{"value":[{"text":"+ ","kind":"text"},{"text":"setDefaultDetectorMode:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector~1setDefaultDetectorMode(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectorMode\/title","value":"SBSDKDocumentDetectorMode"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectorMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectorMode\/fragments"},{"value":"initWithMode:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector~1init(mode:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector~1init(mode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMode:"}]}]}]}