{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration\/copywithzone:"]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKProcessByTileConfiguration(im)copyWithZone:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration\/copyWithZone:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessByTileConfiguration/copyWithZone:":{"abstract":[],"title":"copyWithZone:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration\/copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration\/copywithzone:","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessByTileConfiguration":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration","title":"SBSDKProcessByTileConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for processing image by tiles."},{"type":"text","text":" "},{"type":"text","text":"This can be used to make the document quality analyzer processing faster with lower memory consumption,"},{"type":"text","text":" "},{"type":"text","text":"but prediction can be less accurate."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/title","value":"SBSDKProcessByTileConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/fragments","value":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/navigatorTitle","value":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}]}]}]}