{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKProcessByTileConfiguration(py)minNumberOfRequiredSymbols","symbolKind":"property","navigatorTitle":[{"text":"minNumberOfRequiredSymbols","kind":"identifier"}],"title":"minNumberOfRequiredSymbols","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minNumberOfRequiredSymbols"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration\/minnumberofrequiredsymbols"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration\/minnumberofrequiredsymbols"]}],"abstract":[{"text":"If this number of symbols is found and minProcessedFraction of the image is processed, the processing stops.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minNumberOfRequiredSymbols"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"text":"Default is 100","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration\/minNumberOfRequiredSymbols","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessByTileConfiguration/minNumberOfRequiredSymbols":{"navigatorTitle":[{"kind":"identifier","text":"minNumberOfRequiredSymbols"}],"role":"symbol","title":"minNumberOfRequiredSymbols","abstract":[{"text":"If this number of symbols is found and minProcessedFraction of the image is processed, the processing stops.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration\/minNumberOfRequiredSymbols","url":"\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration\/minnumberofrequiredsymbols","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minNumberOfRequiredSymbols"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessByTileConfiguration":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration","title":"SBSDKProcessByTileConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for processing image by tiles."},{"type":"text","text":" "},{"type":"text","text":"This can be used to make the document quality analyzer processing faster with lower memory consumption,"},{"type":"text","text":" "},{"type":"text","text":"but prediction can be less accurate."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"minNumberOfRequiredSymbols","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"minNumberOfRequiredSymbols"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"minNumberOfRequiredSymbols","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"minNumberOfRequiredSymbols","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration~1minNumberOfRequiredSymbols\/title","op":"replace"},{"value":[{"kind":"identifier","text":"minNumberOfRequiredSymbols"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration~1minNumberOfRequiredSymbols\/fragments","op":"replace"},{"value":"SBSDKProcessByTileConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}