{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController(im)init","role":"symbol","title":"init()","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"init"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/init()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"()"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"name":"Note","type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"It’s recommended to use the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init(parentViewController:parentView:configuration:delegate:)","type":"reference","isActive":true},{"text":".","type":"text"}]}]}]}],"abstract":[{"text":"Initializes an instance of this class with the default configuration.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/init()":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/init()","abstract":[{"text":"Initializes an instance of this class with the default configuration.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController":{"kind":"symbol","title":"SBSDKBarcodeScannerViewController","abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to show a camera screen with the barcode scanner.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/init(parentViewController:parentView:configuration:delegate:)":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/init(parentviewcontroller:parentview:configuration:delegate:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"parentViewController","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"parentView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKBarcodeScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeScannerViewControllerDelegate"},{"kind":"text","text":"?)"}],"title":"init(parentViewController:parentView:configuration:delegate:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init(parentViewController:parentView:configuration:delegate:)","navigatorTitle":[{"text":"initWithParentViewController:parentView:configuration:delegate:","kind":"identifier"}],"abstract":[{"text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1init()\/title","op":"replace","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"value":"SBSDKBarcodeScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}]},{"value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle"},{"value":"initWithParentViewController:parentView:configuration:delegate:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1init(parentViewController:parentView:configuration:delegate:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1init(parentViewController:parentView:configuration:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithParentViewController:parentView:configuration:delegate:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}