{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerGeneralConfiguration"]]},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"stopsCameraSessionWhenDisappeared","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"stopsCameraSessionWhenDisappeared","kind":"identifier"}],"title":"stopsCameraSessionWhenDisappeared","roleHeading":"Instance Property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration(py)stopsCameraSessionWhenDisappeared","symbolKind":"property"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerGeneralConfiguration\/stopsCameraSessionWhenDisappeared"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopsCameraSessionWhenDisappeared"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":", the camera session will be stopped entirely, when the base scanner view controller disappears and restarts when it reappears."},{"type":"text","text":" "},{"text":"The base scanner view controller will cause no CPU load after it disappeared.","type":"text"},{"text":" ","type":"text"},{"text":"Setting it to ","type":"text"},{"type":"codeVoice","code":"False"},{"text":" will NOT stop the camera session, but pauses the delivery of video frames from the camera session to the base scanner view controller.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"There is some low CPU activity while the base scanner view controller is not on screen, but there is also no delay when the receiver returns to the screen."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannergeneralconfiguration\/stopscamerasessionwhendisappeared"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannergeneralconfiguration\/stopscamerasessionwhendisappeared"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerGeneralConfiguration":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannergeneralconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"abstract":[{"text":"The general configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerGeneralConfiguration","title":"SBSDKBaseScannerGeneralConfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerGeneralConfiguration/stopsCameraSessionWhenDisappeared":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"stopsCameraSessionWhenDisappeared"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannergeneralconfiguration\/stopscamerasessionwhendisappeared","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerGeneralConfiguration\/stopsCameraSessionWhenDisappeared","title":"stopsCameraSessionWhenDisappeared","type":"topic","abstract":[{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"True"},{"text":", the camera session will be stopped entirely, when the base scanner view controller disappears and restarts when it reappears.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The base scanner view controller will cause no CPU load after it disappeared."},{"type":"text","text":" "},{"type":"text","text":"Setting it to "},{"type":"codeVoice","code":"False"},{"text":" will NOT stop the camera session, but pauses the delivery of video frames from the camera session to the base scanner view controller.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"There is some low CPU activity while the base scanner view controller is not on screen, but there is also no delay when the receiver returns to the screen."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopsCameraSessionWhenDisappeared","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"stopsCameraSessionWhenDisappeared"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"stopsCameraSessionWhenDisappeared"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopsCameraSessionWhenDisappeared"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"SBSDKBaseScannerGeneralConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerGeneralConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerGeneralConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerGeneralConfiguration\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerGeneralConfiguration~1stopsCameraSessionWhenDisappeared\/title","value":"stopsCameraSessionWhenDisappeared"},{"value":[{"kind":"identifier","text":"stopsCameraSessionWhenDisappeared"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerGeneralConfiguration~1stopsCameraSessionWhenDisappeared\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}