{"abstract":[{"type":"text","text":"The configuration for the tracked barcodes overlay."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerConfiguration\/trackingOverlayConfiguration"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"trackingOverlayConfiguration"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerConfiguration(py)trackingOverlayConfiguration","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"trackingOverlayConfiguration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackingOverlayConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeTrackingOverlayConfiguration"}],"platforms":[],"roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerconfiguration\/trackingoverlayconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerconfiguration\/trackingoverlayconfiguration"]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackingOverlayConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeTrackingOverlayConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerConfiguration":{"role":"symbol","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerConfiguration","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerConfiguration","kind":"identifier"}],"title":"SBSDKUIBarcodesBatchScannerConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerconfiguration","abstract":[{"type":"text","text":"This class describes the look and feel, as well as the textual contents of the RTU-UI batch barcode scanner."}],"navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeTrackingOverlayConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"symbol","title":"SBSDKUIBarcodeTrackingOverlayConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodetrackingoverlayconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}],"abstract":[{"text":"The configuration object for the RTU-UI barcode tracking overlay.","type":"text"}],"deprecated":true,"type":"topic","navigatorTitle":[{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerConfiguration/trackingOverlayConfiguration":{"navigatorTitle":[{"text":"trackingOverlayConfiguration","kind":"identifier"}],"abstract":[{"text":"The configuration for the tracked barcodes overlay.","type":"text"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerConfiguration\/trackingOverlayConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerconfiguration\/trackingoverlayconfiguration","title":"trackingOverlayConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"trackingOverlayConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeTrackingOverlayConfiguration","text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"trackingOverlayConfiguration","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"trackingOverlayConfiguration","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeTrackingOverlayConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration"},{"kind":"text","text":" * "},{"text":"trackingOverlayConfiguration","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerConfiguration\/title","value":"SBSDKUIBarcodesBatchScannerConfiguration","op":"replace"},{"value":[{"text":"SBSDKUIBarcodesBatchScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration\/title","op":"replace","value":"SBSDKUIBarcodeTrackingOverlayConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration\/navigatorTitle","op":"replace"},{"value":"trackingOverlayConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerConfiguration~1trackingOverlayConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"trackingOverlayConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerConfiguration~1trackingOverlayConfiguration\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}