{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport","kind":"typeIdentifier","text":"SBSDKFieldSuspiciousDataVerificationReport","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldSuspiciousDataVerificationReport"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromJsonWithJson:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport"]]},"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldSuspiciousDataVerificationReport(cm)fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/fromJsonWithJson:"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldSuspiciousDataVerificationReport/fromJsonWithJson:":{"title":"fromJsonWithJson:","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldSuspiciousDataVerificationReport":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFieldSuspiciousDataVerificationReport"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKFieldSuspiciousDataVerificationReport"}],"url":"\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport","abstract":[{"text":"Report of the suspicious data field verification.","type":"text"}],"type":"topic","title":"SBSDKFieldSuspiciousDataVerificationReport","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport\/title","value":"SBSDKFieldSuspiciousDataVerificationReport","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport\/fragments","value":[{"kind":"identifier","text":"SBSDKFieldSuspiciousDataVerificationReport"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport\/navigatorTitle","value":[{"text":"SBSDKFieldSuspiciousDataVerificationReport","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}