{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingTextLocalization"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingRotateButtonTitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingtextlocalization\/croppingrotatebuttontitle"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingtextlocalization\/croppingrotatebuttontitle"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The ‘rotate page’ button title, located in the bottom bar of the cropping screen."},{"type":"text","text":" "},{"type":"text","text":"Default is “Rotate”"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingTextLocalization\/croppingRotateButtonTitle"},"metadata":{"title":"croppingRotateButtonTitle","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"croppingRotateButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingTextLocalization(py)croppingRotateButtonTitle","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"croppingRotateButtonTitle","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingTextLocalization":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingtextlocalization","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CroppingTextLocalization"}],"abstract":[{"text":"Configuration of all the strings for the standalone cropping screen.","type":"text"}],"title":"SBSDKUI2CroppingTextLocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingTextLocalization","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingTextLocalization"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingTextLocalization/croppingRotateButtonTitle":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"croppingRotateButtonTitle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"croppingRotateButtonTitle","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingtextlocalization\/croppingrotatebuttontitle","title":"croppingRotateButtonTitle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingTextLocalization\/croppingRotateButtonTitle","type":"topic","abstract":[{"text":"The ‘rotate page’ button title, located in the bottom bar of the cropping screen.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is “Rotate”"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"croppingRotateButtonTitle","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"croppingRotateButtonTitle","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"croppingRotateButtonTitle"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKUI2CroppingTextLocalization","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingTextLocalization\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingTextLocalization\/fragments","op":"replace","value":[{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingTextLocalization~1croppingRotateButtonTitle\/title","op":"replace","value":"croppingRotateButtonTitle"},{"value":[{"kind":"identifier","text":"croppingRotateButtonTitle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingTextLocalization~1croppingRotateButtonTitle\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}