{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode"]]},"metadata":{"title":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FindAndPickScanningMode(im)initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","kind":"identifier"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithScanningCompletedColor:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"scanningCompletedColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"scanningPartiallyColor:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"scanningPartiallyColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"scanningNotScannedColor:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"scanningNotScannedColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"allowPartialScan:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"allowPartialScan","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"expectedBarcodes:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKUI2ExpectedBarcode *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"expectedBarcodes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"countingRepeatDelay:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"countingRepeatDelay","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sheet:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet","text":"SBSDKUI2Sheet","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sheet","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sheetContent:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent","text":"SBSDKUI2SheetContent","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sheetContent","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"manualCountEditDialog:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ManualCountEditDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ManualCountEditDialog","text":"SBSDKUI2ManualCountEditDialog","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"manualCountEditDialog","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"arOverlay:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayFindAndPickConfiguration","text":"SBSDKUI2ArOverlayFindAndPickConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"arOverlay","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"partialScannedAlertDialogEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"partialScannedAlertDialogEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"partialScannedAlertDialog:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"partialScannedAlertDialog","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"confirmationAlertDialogEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"confirmationAlertDialogEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"confirmationAlertDialog:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"confirmationAlertDialog","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/initwithscanningcompletedcolor:scanningpartiallycolor:scanningnotscannedcolor:allowpartialscan:expectedbarcodes:countingrepeatdelay:sheet:sheetcontent:manualcounteditdialog:aroverlay:partialscannedalertdialogenabled:partialscannedalertdialo-cgvt"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"title":"SBSDKUI2SheetContent","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the list containing the barcodes that have already been scanned."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanbotAlertDialog":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2scanbotalertdialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","title":"SBSDKUI2ScanbotAlertDialog","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the standard alert dialog."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the Find and Pick barcode scanning mode."}],"navigatorTitle":[{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}],"title":"SBSDKUI2FindAndPickScanningMode","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ManualCountEditDialog":{"title":"SBSDKUI2ManualCountEditDialog","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the dialog to manually edit the barcode count."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2manualcounteditdialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ManualCountEditDialog","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/initwithscanningcompletedcolor:scanningpartiallycolor:scanningnotscannedcolor:allowpartialscan:expectedbarcodes:countingrepeatdelay:sheet:sheetcontent:manualcounteditdialog:aroverlay:partialscannedalertdialogenabled:partialscannedalertdialo-cgvt","role":"symbol","navigatorTitle":[{"text":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","kind":"identifier"}],"title":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"role":"symbol","title":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2color","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayFindAndPickConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}],"title":"SBSDKUI2ArOverlayFindAndPickConfiguration","abstract":[{"type":"text","text":"Configuration of the AR overlay."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlayfindandpickconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sheet":{"url":"\/documentation\/scanbotsdk\/sbsdkui2sheet","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Sheet"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Configuration of the preview mode for scanning multiple barcodes."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Sheet"}],"type":"topic","title":"SBSDKUI2Sheet"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2SheetContent","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/fragments","value":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/navigatorTitle","value":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/title","value":"SBSDKUI2ScanbotAlertDialog","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/navigatorTitle","value":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode\/title","value":"SBSDKUI2FindAndPickScanningMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode\/fragments","value":[{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode\/navigatorTitle","value":[{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ManualCountEditDialog\/title","value":"SBSDKUI2ManualCountEditDialog","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ManualCountEditDialog\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ManualCountEditDialog"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ManualCountEditDialog\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ManualCountEditDialog"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/title","value":"SBSDKUI2ArOverlayFindAndPickConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/title","value":"SBSDKUI2Sheet","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Sheet"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/navigatorTitle","value":[{"text":"SBSDKUI2Sheet","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}