{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Enables or disables rotation functionality.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenbehaviorconfiguration\/isrotationenabled"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenbehaviorconfiguration\/isrotationenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRotationEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"True"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenBehaviorConfiguration\/isRotationEnabled"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenBehaviorConfiguration"]]},"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isRotationEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","title":"isRotationEnabled","platforms":[],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenBehaviorConfiguration(py)isRotationEnabled","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"isRotationEnabled"}],"role":"symbol"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2CroppingViewController instead.","type":"text"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenBehaviorConfiguration":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenBehaviorConfiguration","navigatorTitle":[{"text":"SBSDKUICroppingScreenBehaviorConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for the behavior of the cropping screen."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingScreenBehaviorConfiguration","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenbehaviorconfiguration","title":"SBSDKUICroppingScreenBehaviorConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenBehaviorConfiguration/isRotationEnabled":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenbehaviorconfiguration\/isrotationenabled","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenBehaviorConfiguration\/isRotationEnabled","abstract":[{"type":"text","text":"Enables or disables rotation functionality."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isRotationEnabled"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isRotationEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isRotationEnabled"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"isRotationEnabled","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"isRotationEnabled","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isRotationEnabled"},{"text":";","kind":"text"}]}]}},{"value":"SBSDKUICroppingScreenBehaviorConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenBehaviorConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUICroppingScreenBehaviorConfiguration","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUICroppingScreenBehaviorConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenBehaviorConfiguration\/navigatorTitle"},{"value":"isRotationEnabled","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenBehaviorConfiguration~1isRotationEnabled\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenBehaviorConfiguration~1isRotationEnabled\/fragments","value":[{"kind":"identifier","text":"isRotationEnabled"}],"op":"replace"}]}]}