{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:minimumnumberofrequiredframeswithequalrecognitionresult:stripcheckdigits:minimumtextlength:maximumtextlength:gs1handling:strictmode:onedconfirmationmode:form-2puin"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:","interfaceLanguage":"occ"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonConfiguration"]]},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCommonConfiguration(im)initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:","kind":"identifier"}],"title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRegexFilter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"regexFilter"},{"text":" ","kind":"text"},{"text":"minimumSizeScore:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimumSizeScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"addAdditionalQuietZone:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"addAdditionalQuietZone","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimum1DQuietZoneSize:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimum1DQuietZoneSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"stripCheckDigits:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"stripCheckDigits","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumTextLength:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimumTextLength","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maximumTextLength:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"maximumTextLength","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"gs1Handling:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKGS1Handling","text":"SBSDKGS1Handling","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling"},{"text":") ","kind":"text"},{"text":"gs1Handling","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"strictMode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"strictMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"oneDConfirmationMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOneDConfirmationMode","text":"SBSDKOneDConfirmationMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOneDConfirmationMode"},{"text":") ","kind":"text"},{"text":"oneDConfirmationMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"formats:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBarcodeFormat *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"formats","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonConfiguration":{"title":"SBSDKBarcodeFormatCommonConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCommonConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonConfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatCommonConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonconfiguration","abstract":[{"text":"Convenience configuration for enabling the scanning of multiple barcode formats with a common configuration.","type":"text"},{"text":" ","type":"text"},{"text":"Add to scanner configuration to enable and configure the scanning of multiple barcodes.","type":"text"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGS1Handling","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling","role":"symbol","title":"SBSDKGS1Handling","url":"\/documentation\/scanbotsdk\/sbsdkgs1handling","abstract":[{"type":"text","text":"GS1 message handling options."},{"type":"text","text":" "},{"type":"text","text":"The GS1 standard defines a key-value format for business-centric data that can be encoded into many 1D and 2D barcode types."},{"type":"text","text":" "},{"type":"text","text":"https:\/\/ref.gs1.org\/standards\/genspecs\/"}],"navigatorTitle":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonConfiguration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:minimumnumberofrequiredframeswithequalrecognitionresult:stripcheckdigits:minimumtextlength:maximumtextlength:gs1handling:strictmode:onedconfirmationmode:form-2puin","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:gs1Handling:strictMode:oneDConfirmationMode:formats:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOneDConfirmationMode":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkonedconfirmationmode","type":"topic","title":"SBSDKOneDConfirmationMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKOneDConfirmationMode"}],"abstract":[{"text":"Allows to select the balance between result accuracy (precision) and missed barcodes (recall) for linear barcodes.","type":"text"},{"text":" ","type":"text"},{"text":"Some barcode types are naturally prone to false positives (e.g. MSI Plessey).","type":"text"},{"text":" ","type":"text"},{"text":"For those barcode types false positives can be drastically reduced (precision can be increased) by requiring that multiple scan-lines in the input scan to the same result.","type":"text"},{"text":" ","type":"text"},{"text":"However, this stronger condition can lead to missed barcodes (lower recall).","type":"text"},{"text":" ","type":"text"},{"text":"Confirmation is avoided for barcode types, which are by design resistant to false positives, (e.g. Code128) to maximize recall.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOneDConfirmationMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOneDConfirmationMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKBarcodeFormatCommonConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatCommonConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/title","op":"replace","value":"SBSDKGS1Handling"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/fragments","op":"replace","value":[{"text":"SBSDKGS1Handling","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKGS1Handling"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOneDConfirmationMode\/title","op":"replace","value":"SBSDKOneDConfirmationMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOneDConfirmationMode\/fragments","op":"replace","value":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOneDConfirmationMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}]}]}]}