{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeAddressParserConfiguration\/initWithDocumentTypes:binaryFileAddressDatabase:","interfaceLanguage":"occ"},"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithDocumentTypes:binaryFileAddressDatabase:","kind":"identifier"}],"title":"initWithDocumentTypes:binaryFileAddressDatabase:","navigatorTitle":[{"text":"initWithDocumentTypes:binaryFileAddressDatabase:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDeAddressParserConfiguration(im)initWithDocumentTypes:binaryFileAddressDatabase:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdeaddressparserconfiguration\/initwithdocumenttypes:binaryfileaddressdatabase:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeAddressParserConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"initWithDocumentTypes:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"documentTypes","kind":"internalParam"},{"kind":"text","text":" "},{"text":"binaryFileAddressDatabase:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"binaryFileAddressDatabase"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeAddressParserConfiguration/initWithDocumentTypes:binaryFileAddressDatabase:":{"abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocumentTypes:binaryFileAddressDatabase:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeAddressParserConfiguration\/initWithDocumentTypes:binaryFileAddressDatabase:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdeaddressparserconfiguration\/initwithdocumenttypes:binaryfileaddressdatabase:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDocumentTypes:binaryFileAddressDatabase:"}],"title":"initWithDocumentTypes:binaryFileAddressDatabase:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeAddressParserConfiguration":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeAddressParserConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdeaddressparserconfiguration","kind":"symbol","title":"SBSDKDeAddressParserConfiguration","abstract":[{"type":"text","text":"German Address Field validation configuration."},{"text":" ","type":"text"},{"text":"This configuration does not enable the scanning of any document types by itself.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Add to recognizer configuration to require German Address validation checks for specific document types."}],"navigatorTitle":[{"text":"SBSDKDeAddressParserConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDeAddressParserConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKDeAddressParserConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeAddressParserConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeAddressParserConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDeAddressParserConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeAddressParserConfiguration\/navigatorTitle","value":[{"text":"SBSDKDeAddressParserConfiguration","kind":"identifier"}]}]}]}