{"kind":"symbol","abstract":[{"type":"text","text":"All fields were extracted, but some of them failed validation."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/incompleteValidation"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/incompletevalidation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/incompletevalidation"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusIncompleteValidation"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDataExtractionStatus@SBSDKDocumentDataExtractionStatusIncompleteValidation","title":"SBSDKDocumentDataExtractionStatus.incompleteValidation","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"incompleteValidation"}],"roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"incompleteValidation"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatus"}],"kind":"symbol","abstract":[{"text":"The status of the extraction process.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatus"}],"title":"SBSDKDocumentDataExtractionStatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/incompleteValidation":{"abstract":[{"text":"All fields were extracted, but some of them failed validation.","type":"text"}],"title":"SBSDKDocumentDataExtractionStatus.incompleteValidation","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/incompletevalidation","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"incompleteValidation","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDataExtractionStatusIncompleteValidation","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/incompleteValidation","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKDocumentDataExtractionStatusIncompleteValidation"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusIncompleteValidation"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKDocumentDataExtractionStatusIncompleteValidation","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKDocumentDataExtractionStatus","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatus"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/navigatorTitle","value":[{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1incompleteValidation\/title","op":"replace","value":"SBSDKDocumentDataExtractionStatusIncompleteValidation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1incompleteValidation\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDataExtractionStatusIncompleteValidation","kind":"identifier"}]}]}]}