{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/isRecognitionEnabled"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isRecognitionEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"abstract":[{"type":"text","text":"Enables or disables the recognition."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isRecognitionEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"isRecognitionEnabled","navigatorTitle":[{"text":"isRecognitionEnabled","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerViewController(py)isRecognitionEnabled"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/isrecognitionenabled"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/isrecognitionenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","title":"SBSDKUITextDataScannerViewController","abstract":[{"text":"A highly customizable camera-based view controller to recognize and validate a small rectangular text area in realtime.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/isRecognitionEnabled":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/isRecognitionEnabled","abstract":[{"text":"Enables or disables the recognition.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isRecognitionEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","title":"isRecognitionEnabled","role":"symbol","type":"topic","navigatorTitle":[{"text":"isRecognitionEnabled","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/isrecognitionenabled"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"isRecognitionEnabled"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isRecognitionEnabled"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRecognitionEnabled"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/title","value":"SBSDKUITextDataScannerViewController","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1isRecognitionEnabled\/title","value":"isRecognitionEnabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1isRecognitionEnabled\/fragments","op":"replace","value":[{"text":"isRecognitionEnabled","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}