{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"viewDidLoad","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/viewDidLoad"},"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"title":"viewDidLoad","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerViewController(im)viewDidLoad"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/viewdidload"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/viewDidLoad":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/viewDidLoad","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"kind":"symbol","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"abstract":[],"title":"viewDidLoad","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/viewdidload","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","title":"SBSDKUITextDataScannerViewController","abstract":[{"text":"A highly customizable camera-based view controller to recognize and validate a small rectangular text area in realtime.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/title","op":"replace","value":"SBSDKUITextDataScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/navigatorTitle"}]}]}