{"abstract":[{"text":"A scrollable and zoomable ","type":"text"},{"code":"UIScrollView","type":"codeVoice"},{"text":" subclass that displays images and an overlay view.","type":"text"}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"symbolKind":"class","role":"symbol","navigatorTitle":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKZoomingImageScrollView","title":"SBSDKZoomingImageScrollView"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","level":2,"text":"Overview","type":"heading"},{"inlineContent":[{"type":"text","text":"Zooming and scrolling can be controlled using the standard UIScrollView properties."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/didEndZoomHandler","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/image","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/margins","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/overlayView"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/UIScrollViewDelegate-Implementations"],"generated":true}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)UIScrollView"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)CALayerDelegate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s8CopyableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s8SendableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIAppearance","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UICoordinateSpace","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIDynamicItem","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIFocusItem","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIFocusItemContainer","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIFocusItemScrollableContainer","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIScrollViewDelegate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIUserActivityRestoring"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCoding"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UICoordinateSpace"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIUserActivityRestoring"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKZoomingImageScrollView/didEndZoomHandler":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didEndZoomHandler","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":") -> ())?","kind":"text"}],"abstract":[{"text":"An optional handler that will be called when the zooming ends. The current zoom scale is passed as a parameter.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/didEndZoomHandler","kind":"symbol","navigatorTitle":[{"text":"didEndZoomHandler","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/didendzoomhandler","title":"didEndZoomHandler","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIScrollViewDelegate":{"title":"UIScrollViewDelegate","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIScrollViewDelegate"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)CALayerDelegate"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(cs)UIScrollView":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)UIScrollView","title":"UIScrollView"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIFocusItemScrollableContainer":{"title":"UIKit.UIFocusItemScrollableContainer","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIFocusItemScrollableContainer"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://net.doo.ScanbotBarcodeScannerSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/5UIKit23UITraitChangeObservableP"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://net.doo.ScanbotBarcodeScannerSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s8SendableP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKZoomingImageScrollView/UIScrollViewDelegate-Implementations":{"abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/uiscrollviewdelegate-implementations","title":"UIScrollViewDelegate Implementations","role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/UIScrollViewDelegate-Implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKZoomingImageScrollView":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"role":"symbol","title":"SBSDKZoomingImageScrollView","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"kind":"symbol","abstract":[{"text":"A scrollable and zoomable ","type":"text"},{"code":"UIScrollView","type":"codeVoice"},{"text":" subclass that displays images and an overlay view.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKZoomingImageScrollView/margins":{"abstract":[{"type":"text","text":"The margins of the displayed image to the bounds of the receiver. Defaults to (20.0, 20.0, 20.0, 20.0)."}],"title":"margins","navigatorTitle":[{"kind":"identifier","text":"margins"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"margins"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier","text":"UIEdgeInsets"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/margins","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/margins","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKZoomingImageScrollView/overlayView":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/overlayView","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/overlayview","title":"overlayView","abstract":[{"type":"text","text":"Pass a transparent view here to display it as a HUD style view above the image view."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"overlayView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"overlayView"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIAccessibilityIdentification"},"doc://net.doo.ScanbotBarcodeScannerSDK/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s8CopyableP","title":"Swift.Copyable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKZoomingImageScrollView/image":{"abstract":[{"text":"The image to be displayed. Can be zoomed and scrolled. If the image is zoomed out, it will be automatically centred.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/image","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/image","title":"image","navigatorTitle":[{"text":"image","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKZoomingImageScrollView/layoutSubviews":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/layoutsubviews","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/layoutSubviews","role":"symbol","title":"layoutSubviews"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIFocusItemContainer"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKZoomingImageScrollView/init":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/init","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","title":"init","type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIFocusItem"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKZoomingImageScrollView/initWithFrame:":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/initwithframe:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/initWithFrame:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"abstract":[],"type":"topic","title":"initWithFrame:","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKZoomingImageScrollView","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/didEndZoomHandler","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/image","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/margins","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/overlayView"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/init","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/initWithFrame:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/layoutSubviews"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/UIScrollViewDelegate-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)UIScrollView"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIScrollViewDelegate"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKZoomingImageScrollView","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView~1didEndZoomHandler\/title","value":"didEndZoomHandler","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView~1didEndZoomHandler\/fragments","value":[{"kind":"identifier","text":"didEndZoomHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView\/title","value":"SBSDKZoomingImageScrollView","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView\/fragments","value":[{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView\/navigatorTitle","value":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView~1margins\/title","value":"margins","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView~1margins\/fragments","value":[{"text":"margins","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView~1overlayView\/title","value":"overlayView","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView~1overlayView\/fragments","value":[{"kind":"identifier","text":"overlayView"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView~1image\/title","value":"image","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView~1image\/fragments","value":[{"text":"image","kind":"identifier"}],"op":"replace"}]}]}