{"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"symbolKind":"class","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKIndexedImageStorage","role":"symbol","navigatorTitle":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"roleHeading":"Class","title":"SBSDKIndexedImageStorage"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageStoring","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/init(storageLocation:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/encrypter","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/fileFormat","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/imageCount","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/imageURLs","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/jpegCompressionQuality"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/add(_:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/addImage(from:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/image(at:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/imageURL(at:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/insert(_:at:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/moveImage(from:to:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/removeAll()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/removeImage(at:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/replaceImage(at:with:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/replaceImage(at:withImageAtURL:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/waitUntilWritingCompleted()"]},{"generated":true,"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/temporary"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage"},"abstract":[{"type":"text","text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class."},{"type":"text","text":" "},{"type":"text","text":"Manages images in an array-like fashion."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/removeAll()":{"title":"removeAll()","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/removeall()","navigatorTitle":[{"text":"removeAllImages","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAll","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/removeAll()","abstract":[{"type":"text","text":"Removes all stored images from the image storage."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/replaceImage(at:with:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replaceImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/replaceImage(at:with:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/replaceimage(at:with:)","title":"replaceImage(at:with:)","abstract":[{"type":"text","text":"Replaces the receivers image at index with the given image."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"replaceImageAtIndex:withImage:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/temporary":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/temporary","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/temporary","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"temporary","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKIndexedImageStorage","text":"SBSDKIndexedImageStorage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"temporary","kind":"identifier"}],"type":"topic","title":"temporary","abstract":[{"text":"A new ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage","isActive":true,"type":"reference"},{"text":" at a temporary location (application caches folder).","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/replaceImage(at:withImageAtURL:)":{"navigatorTitle":[{"text":"replaceImageAtIndex:withImageAtURL:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/replaceimage(at:withimageaturl:)","type":"topic","abstract":[{"text":"Replaces the receivers image at index with the image stored at the given URL.","type":"text"}],"title":"replaceImage(at:withImageAtURL:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replaceImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withImageAtURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/replaceImage(at:withImageAtURL:)","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/imageCount":{"kind":"symbol","navigatorTitle":[{"text":"imageCount","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Number of images in the receiver."}],"title":"imageCount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/imageCount","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/imagecount"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/jpegCompressionQuality":{"kind":"symbol","title":"jpegCompressionQuality","abstract":[{"text":"The JPEG compression if JPEG file format is used. Range: 0.0 - 1.0.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"jpegCompressionQuality","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpegCompressionQuality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/jpegcompressionquality","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/jpegCompressionQuality"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/init(storageLocation:)":{"navigatorTitle":[{"text":"initWithStorageLocation:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/init(storageLocation:)","abstract":[{"type":"text","text":"Initializes a new "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage","isActive":true},{"type":"text","text":" at the given storage location."}],"title":"init(storageLocation:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/init(storagelocation:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"storageLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKStorageLocation","text":"SBSDKStorageLocation","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/add(_:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/add(_:)","kind":"symbol","abstract":[{"text":"Adds a ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"text":" into the storage.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/add(_:)","title":"add(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addImage:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/imageURLs":{"abstract":[{"type":"text","text":"Array of all stored images URLs."}],"title":"imageURLs","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/imageURLs","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/imageurls","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageURLs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"imageURLs"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageStoring":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageStoring"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagestoring","kind":"symbol","abstract":[{"text":"Protocol for an order-aware (array like) image storage.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageStoring"}],"title":"SBSDKImageStoring","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageStoring"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying","title":"Foundation.NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/moveImage(from:to:)":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/moveimage(from:to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic","title":"moveImage(from:to:)","navigatorTitle":[{"kind":"identifier","text":"moveImageFromIndex:toIndex:"}],"abstract":[{"type":"text","text":"Moves the image at the source index to the destination index."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/moveImage(from:to:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/copyWithZone:":{"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/copyWithZone:","role":"symbol","title":"copyWithZone:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/copywithzone:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/image(at:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/image(at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"title":"image(at:)","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/image(at:)","navigatorTitle":[{"text":"imageAtIndex:","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Returns the stored UIImage at the specified index.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/fileFormat":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fileFormat"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKImageFileFormat"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/fileFormat","title":"fileFormat","abstract":[{"type":"text","text":"Image file format to be used to store the managed images."}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/fileformat","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStorageLocation:fileFormat:encrypter:encryptedImagesURLs:"}],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage"},{"type":"text","text":" at the given storage location with given image file format."}],"title":"init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/init(storagelocation:fileformat:encrypter:encryptedimagesurls:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"storageLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKStorageLocation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fileFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKImageFileFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encrypter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"encryptedImagesURLs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"])"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/imageURL(at:)":{"navigatorTitle":[{"text":"imageURLAtIndex:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/imageURL(at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/imageurl(at:)","abstract":[{"type":"text","text":"Returns the URL of the stored image at the specified index."}],"title":"imageURL(at:)","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/waitUntilWritingCompleted()":{"title":"waitUntilWritingCompleted()","navigatorTitle":[{"kind":"identifier","text":"waitUntilWritingCompleted"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/waituntilwritingcompleted()","abstract":[{"type":"text","text":"Blocks the current thread until all enqueued writing operations have been finished."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/waitUntilWritingCompleted()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitUntilWritingCompleted"},{"kind":"text","text":"()"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/encrypter":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/encrypter","abstract":[{"type":"text","text":"Encrypter used to encrypt and decrypt the image data. If "},{"code":"nil","type":"codeVoice"},{"type":"text","text":", no encryption\/decryption is used."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/encrypter","navigatorTitle":[{"text":"encrypter","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encrypter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting"},{"text":"?","kind":"text"}],"title":"encrypter","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/addImage(from:)":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/addImage(from:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"text":"Adds an image from a file into the storage.","type":"text"}],"navigatorTitle":[{"text":"addImageFromURL:","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/addimage(from:)","title":"addImage(from:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage":{"title":"SBSDKIndexedImageStorage","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage","abstract":[{"text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class.","type":"text"},{"text":" ","type":"text"},{"text":"Manages images in an array-like fashion.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage","navigatorTitle":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/init(storageLocation:fileFormat:encrypter:)":{"abstract":[{"type":"text","text":"Initializes a new "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage"},{"type":"text","text":" at the given storage location with given image file format."}],"navigatorTitle":[{"kind":"identifier","text":"initWithStorageLocation:fileFormat:encrypter:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/init(storagelocation:fileformat:encrypter:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:)","title":"init(storageLocation:fileFormat:encrypter:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"storageLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKStorageLocation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fileFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKImageFileFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encrypter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?)"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/insert(_:at:)":{"kind":"symbol","abstract":[{"text":"Inserts a new image into the receiver at the given index.","type":"text"}],"title":"insert(_:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insert"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"insertImage:atIndex:"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/insert(_:at:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/insert(_:at:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/removeImage(at:)":{"title":"removeImage(at:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/removeimage(at:)","abstract":[{"text":"Removes the stored image at the given index from the image storage.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/removeImage(at:)","navigatorTitle":[{"text":"removeImageAtIndex:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKIndexedImageStorage"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/encrypter","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/fileFormat","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/imageCount","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/imageURLs","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/jpegCompressionQuality"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/add(_:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/addImage(from:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/copyWithZone:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/image(at:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/imageURL(at:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/init(storageLocation:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/insert(_:at:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/moveImage(from:to:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/removeAll()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/removeImage(at:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/replaceImage(at:with:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/replaceImage(at:withImageAtURL:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/waitUntilWritingCompleted()"],"title":"Instance Methods","anchor":"Instance-Methods"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/temporary"],"title":"Type Properties","anchor":"Type-Properties"}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageStoring"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKIndexedImageStorage","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1removeAll()\/title","value":"removeAllImages","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1removeAll()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeAllImages","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1replaceImage(at:with:)\/title","value":"replaceImageAtIndex:withImage:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1replaceImage(at:with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"replaceImageAtIndex:withImage:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1temporary\/title","value":"temporary"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1temporary\/fragments","value":[{"kind":"identifier","text":"temporary"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1replaceImage(at:withImageAtURL:)\/title","value":"replaceImageAtIndex:withImageAtURL:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1replaceImage(at:withImageAtURL:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"replaceImageAtIndex:withImageAtURL:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1imageCount\/title","value":"imageCount"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1imageCount\/fragments","value":[{"text":"imageCount","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1jpegCompressionQuality\/title","value":"jpegCompressionQuality"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1jpegCompressionQuality\/fragments","value":[{"kind":"identifier","text":"jpegCompressionQuality"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1init(storageLocation:)\/title","value":"initWithStorageLocation:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1init(storageLocation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStorageLocation:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1add(_:)\/title","value":"addImage:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1add(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addImage:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1imageURLs\/title","value":"imageURLs","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1imageURLs\/fragments","value":[{"text":"imageURLs","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageStoring\/title","value":"SBSDKImageStoring","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageStoring\/fragments","value":[{"text":"SBSDKImageStoring","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageStoring\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageStoring"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1moveImage(from:to:)\/title","value":"moveImageFromIndex:toIndex:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1moveImage(from:to:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"moveImageFromIndex:toIndex:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1image(at:)\/title","value":"imageAtIndex:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1image(at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageAtIndex:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1fileFormat\/title","value":"fileFormat","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1fileFormat\/fragments","value":[{"kind":"identifier","text":"fileFormat"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)\/title","value":"initWithStorageLocation:fileFormat:encrypter:encryptedImagesURLs:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithStorageLocation:fileFormat:encrypter:encryptedImagesURLs:","kind":"identifier"}],"op":"replace"},{"value":"imageURLAtIndex:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1imageURL(at:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"imageURLAtIndex:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1imageURL(at:)\/fragments"},{"value":"waitUntilWritingCompleted","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1waitUntilWritingCompleted()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"waitUntilWritingCompleted"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1waitUntilWritingCompleted()\/fragments"},{"value":"encrypter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1encrypter\/title"},{"value":[{"text":"encrypter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1encrypter\/fragments"},{"value":"addImageFromURL:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1addImage(from:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addImageFromURL:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1addImage(from:)\/fragments"},{"value":"SBSDKIndexedImageStorage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage\/title"},{"value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage\/fragments"},{"value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage\/navigatorTitle"},{"value":"initWithStorageLocation:fileFormat:encrypter:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1init(storageLocation:fileFormat:encrypter:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStorageLocation:fileFormat:encrypter:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1init(storageLocation:fileFormat:encrypter:)\/fragments"},{"value":"insertImage:atIndex:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1insert(_:at:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"insertImage:atIndex:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1insert(_:at:)\/fragments"},{"value":"removeImageAtIndex:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1removeImage(at:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeImageAtIndex:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1removeImage(at:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}