{"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/eager","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/lazy","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/lazyWithCopy"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpathloadmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpathloadmode"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Enumeration","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKPathLoadMode","role":"symbol","navigatorTitle":[{"text":"SBSDKPathLoadMode","kind":"identifier"}],"symbolKind":"enum","title":"SBSDKPathLoadMode","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPathLoadMode"}]},"sections":[],"abstract":[{"type":"text","text":"Image Ref Path Load Mode."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKPathLoadMode) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPathLoadMode","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"type":"conformsTo","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPathLoadMode/eager":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpathloadmode\/eager","title":"SBSDKPathLoadMode.eager","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eager"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPathLoadModeEager"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Image is immediately loaded into memory."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/eager"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPathLoadMode":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpathloadmode","abstract":[{"type":"text","text":"Image Ref Path Load Mode."}],"title":"SBSDKPathLoadMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPathLoadMode"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKPathLoadMode"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPathLoadMode/init(rawValue:)":{"type":"topic","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpathloadmode\/init(rawvalue:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/init(rawValue:)","title":"init(rawValue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPathLoadMode/Equatable-Implementations":{"abstract":[],"kind":"article","title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/Equatable-Implementations","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpathloadmode\/equatable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPathLoadMode/lazy":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/lazy","title":"SBSDKPathLoadMode.lazy","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lazy","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPathLoadModeLazy","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpathloadmode\/lazy","abstract":[{"text":"Image is loaded into memory the first time it’s requested. Specified path must exist at the time of loading.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPathLoadMode/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/RawRepresentable-Implementations","type":"topic","abstract":[],"role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpathloadmode\/rawrepresentable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPathLoadMode/lazyWithCopy":{"role":"symbol","abstract":[{"type":"text","text":"Image is loaded into memory the first time it’s requested. Specified path is copied into internal directory and"},{"type":"text","text":" "},{"type":"text","text":"so isn’t required to exist at the time of loading."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/lazyWithCopy","navigatorTitle":[{"kind":"identifier","text":"SBSDKPathLoadModeLazyWithCopy"}],"title":"SBSDKPathLoadMode.lazyWithCopy","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpathloadmode\/lazywithcopy","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lazyWithCopy"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","title":"Swift.RawRepresentable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKPathLoadMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKPathLoadMode","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPathLoadMode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/eager","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/lazy","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/lazyWithCopy"],"generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPathLoadMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode~1eager\/title","value":"SBSDKPathLoadModeEager"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode~1eager\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPathLoadModeEager"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode\/title","op":"replace","value":"SBSDKPathLoadMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPathLoadMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPathLoadMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode~1lazy\/title","op":"replace","value":"SBSDKPathLoadModeLazy"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode~1lazy\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPathLoadModeLazy"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode~1lazyWithCopy\/title","op":"replace","value":"SBSDKPathLoadModeLazyWithCopy"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode~1lazyWithCopy\/fragments","op":"replace","value":[{"text":"SBSDKPathLoadModeLazyWithCopy","kind":"identifier"}]}]}]}