{"sections":[],"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/init()"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/ean13","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/ean8","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/extensions","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/stripCheckDigits","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/upca","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/upce"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/toJson(configuration:)"],"anchor":"Instance-Methods"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"abstract":[{"type":"text","text":"UPC\/EAN barcode configuration. Add to scanner configuration to scan EAN-8, EAN-13, UPC-E and UPC-A barcodes."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"class","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Class","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatUpcEanConfiguration","title":"SBSDKBarcodeFormatUpcEanConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatUpcEanConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatUpcEanConfiguration"}]},"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatOneDConfigurationBase"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKBarcodeFormatUpcEanConfiguration) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatUpcEanConfiguration","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatOneDConfigurationBase":{"abstract":[{"type":"text","text":"Base class for all linear (1D) barcode configurations."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatOneDConfigurationBase","title":"SBSDKBarcodeFormatOneDConfigurationBase","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatonedconfigurationbase","navigatorTitle":[{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUpcEanConfiguration/upca":{"abstract":[{"text":"If true, scan and return valid UPC-A barcodes. If false, but ean13 is true, then UPC-A barcodes will be returned","type":"text"},{"text":" ","type":"text"},{"text":"as EAN-13 barcodes.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration\/upca","title":"upca","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/upca","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"upca","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"upca","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUpcEanConfiguration/extensions":{"navigatorTitle":[{"kind":"identifier","text":"extensions"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration\/extensions","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensions"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUpcEanExtensionBehavior","kind":"typeIdentifier","text":"SBSDKUpcEanExtensionBehavior"}],"type":"topic","title":"extensions","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/extensions","abstract":[{"type":"text","text":"Behavior when scanning UPC\/EAN barcodes with EAN-2 or EAN-5 extensions."}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUpcEanConfiguration/copyWithZone:":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/copyWithZone:","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration\/copywithzone:","kind":"symbol","title":"copyWithZone:","abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUpcEanConfiguration/hash":{"fragments":[{"text":"hash","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/hash","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration\/hash","title":"hash","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUpcEanConfiguration/stripCheckDigits":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration\/stripcheckdigits","kind":"symbol","title":"stripCheckDigits","abstract":[{"type":"text","text":"If true, the check digits are stripped from the result."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stripCheckDigits"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"stripCheckDigits"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/stripCheckDigits"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUpcEanConfiguration/init()":{"abstract":[],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration\/init()","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/init()","type":"topic","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUpcEanConfiguration/upce":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"upce","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"If true, scan and return valid UPC-E barcodes."}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/upce","navigatorTitle":[{"text":"upce","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration\/upce","title":"upce","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUpcEanConfiguration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:ean8:ean13:upca:upce:extensions:minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:ean8:ean13:upca:upce:extensions:minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:"}],"kind":"symbol","type":"topic","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:ean8:ean13:upca:upce:extensions:minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:","navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:ean8:ean13:upca:upce:extensions:minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:ean8:ean13:upca:upce:extensions:minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:minimumnumberofrequiredframeswithequalrecognitionresult:stripcheckdigits:ean8:ean13:upca:upce:extensions:minimumnumberofrequiredframeswithequalrecognitionres-5e31f","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying","title":"Foundation.NSCopying"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUpcEanConfiguration/toJson(configuration:)":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration\/tojson(configuration:)","kind":"symbol","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"title":"toJson(configuration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/toJson(configuration:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUpcEanConfiguration/new":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/new","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"new"}],"kind":"symbol","title":"new","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration\/new","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"new"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUpcEanConfiguration/minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless":{"navigatorTitle":[{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless","kind":"identifier"}],"title":"minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless","kind":"symbol","abstract":[{"text":"In case that EAN\/UPC barcodes both with and without extensions are allowed,","type":"text"},{"text":" ","type":"text"},{"text":"we require this number of frames on which the standalone EAN or UPC (i.e. without extension) has to be detected","type":"text"},{"text":" ","type":"text"},{"text":"to be considered as valid (live scanning only).","type":"text"},{"text":" ","type":"text"},{"text":"EAN\/UPC barcodes with extensions are more prone to slicing (incomplete decoding).","type":"text"},{"text":" ","type":"text"},{"text":"Increasing the number of frames on which a barcode has to decode to the same content reduces the probability","type":"text"},{"text":" ","type":"text"},{"text":"that an extension is accidentally missed.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration\/minimumnumberofrequiredframeswithequalrecognitionresultextensionless","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUpcEanConfiguration/ean8":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration\/ean8","kind":"symbol","title":"ean8","abstract":[{"type":"text","text":"If true, scan and return valid EAN-8 barcodes."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ean8"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"ean8"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/ean8"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUpcEanConfiguration/isEqual:":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration\/isequal:","title":"isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUpcEanConfiguration/fromJsonWithJson:":{"title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/fromJsonWithJson:","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration\/fromjsonwithjson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUpcEanConfiguration":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatUpcEanConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration","abstract":[{"text":"UPC\/EAN barcode configuration. Add to scanner configuration to scan EAN-8, EAN-13, UPC-E and UPC-A barcodes.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatUpcEanConfiguration","kind":"identifier"}],"title":"SBSDKBarcodeFormatUpcEanConfiguration","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatUpcEanConfiguration/ean13":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/ean13","navigatorTitle":[{"kind":"identifier","text":"ean13"}],"type":"topic","role":"symbol","abstract":[{"text":"If true, scan and return valid EAN-13 barcodes.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatupceanconfiguration\/ean13","title":"ean13","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ean13"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKBarcodeFormatUpcEanConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKBarcodeFormatUpcEanConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatUpcEanConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/ean13","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/ean8","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/extensions","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/hash","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/stripCheckDigits","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/upca","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/upce"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/init()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:ean8:ean13:upca:upce:extensions:minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/toJson(configuration:)"],"anchor":"Instance-Methods","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/fromJsonWithJson:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/new"],"anchor":"Type-Methods","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatOneDConfigurationBase"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatUpcEanConfiguration"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatOneDConfigurationBase","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatOneDConfigurationBase","kind":"typeIdentifier","text":"SBSDKBarcodeFormatOneDConfigurationBase"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/title","value":"SBSDKBarcodeFormatOneDConfigurationBase"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/fragments","value":[{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1upca\/title","value":"upca"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1upca\/fragments","value":[{"kind":"identifier","text":"upca"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1extensions\/title","value":"extensions"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1extensions\/fragments","value":[{"text":"extensions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1stripCheckDigits\/title","value":"stripCheckDigits"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1stripCheckDigits\/fragments","value":[{"kind":"identifier","text":"stripCheckDigits"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1upce\/title","value":"upce"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1upce\/fragments","value":[{"text":"upce","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1toJson(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless\/title","value":"minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless\/fragments","value":[{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualRecognitionResultExtensionless"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1ean8\/title","value":"ean8"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1ean8\/fragments","value":[{"kind":"identifier","text":"ean8"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration\/title","value":"SBSDKBarcodeFormatUpcEanConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatUpcEanConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatUpcEanConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1ean13\/title","value":"ean13"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1ean13\/fragments","value":[{"kind":"identifier","text":"ean13"}]}]}]}