{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/copyWithZone:","interfaceLanguage":"occ"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/copywithzone:"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCodabarConfiguration(im)copyWithZone:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@_NSZone","text":"_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCodabarConfiguration"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration","abstract":[{"type":"text","text":"Codabar barcode configuration. Add to scanner configuration to scan Codabar barcodes."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormatCodabarConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration","title":"SBSDKBarcodeFormatCodabarConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration/copyWithZone:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/copyWithZone:","kind":"symbol","title":"copyWithZone:","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/copywithzone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration\/title","value":"SBSDKBarcodeFormatCodabarConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatCodabarConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormatCodabarConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}