{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/initwithversion:screen:localization:palette:backgroundcolor:cameraconfiguration:camerapermission:topuserguidance:scanstatususerguidance:topbar:topbaropenintroscreenbutton:introscreen:actionbar:viewfinder:scannerconfiguration:exampleoverlayv-12ncx"]}],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:scanStatusUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:exampleOverlayVisible:scanningProgress:scanIncompleteDataTimeout:successOverlay:incompleteDataOverlay:sound:vibration:"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerScreenConfiguration(im)initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:scanStatusUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:exampleOverlayVisible:scanningProgress:scanIncompleteDataTimeout:successOverlay:incompleteDataOverlay:sound:vibration:","fragments":[{"kind":"text","text":"- "},{"text":"initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:scanStatusUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:exampleOverlayVisible:scanningProgress:scanIncompleteDataTimeout:successOverlay:incompleteDataOverlay:sound:vibration:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:scanStatusUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:exampleOverlayVisible:scanningProgress:scanIncompleteDataTimeout:successOverlay:incompleteDataOverlay:sound:vibration:","kind":"identifier"}],"role":"symbol","title":"initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:scanStatusUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:exampleOverlayVisible:scanningProgress:scanIncompleteDataTimeout:successOverlay:incompleteDataOverlay:sound:vibration:","symbolKind":"method","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithVersion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"version","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"screen:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"screen"},{"text":" ","kind":"text"},{"text":"localization:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerScreenTextLocalization","text":"SBSDKUI2CreditCardScannerScreenTextLocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"localization"},{"kind":"text","text":" "},{"kind":"identifier","text":"palette:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Palette","text":"SBSDKUI2Palette","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Palette"},{"text":" *) ","kind":"text"},{"text":"palette","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"kind":"text","text":" *) "},{"text":"backgroundColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2CameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraConfiguration"},{"kind":"text","text":" *) "},{"text":"cameraConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPermission:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen","text":"SBSDKUI2CameraPermissionScreen","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermission"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topUserGuidance:"},{"kind":"text","text":"("},{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration"},{"text":" *) ","kind":"text"},{"text":"topUserGuidance","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scanStatusUserGuidance:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScanGuidanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration","text":"SBSDKUI2CreditCardScanGuidanceConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"scanStatusUserGuidance","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"topBar:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TopBarConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration","kind":"typeIdentifier","text":"SBSDKUI2TopBarConfiguration"},{"text":" *) ","kind":"text"},{"text":"topBar","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarOpenIntroScreenButton:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton","kind":"typeIdentifier","text":"SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton"},{"text":" *) ","kind":"text"},{"text":"topBarOpenIntroScreenButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"introScreen:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2CreditCardScannerIntroScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerIntroScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerIntroScreenConfiguration"},{"text":" *) ","kind":"text"},{"text":"introScreen","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"actionBar:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2ActionBarConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ActionBarConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration"},{"kind":"text","text":" *) "},{"text":"actionBar","kind":"internalParam"},{"kind":"text","text":" "},{"text":"viewFinder:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2PermanentViewFinderConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PermanentViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PermanentViewFinderConfiguration"},{"kind":"text","text":" *) "},{"text":"viewFinder","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"scannerConfiguration:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerConfiguration","text":"SBSDKCreditCardScannerConfiguration"},{"text":" *) ","kind":"text"},{"text":"scannerConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"exampleOverlayVisible:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"exampleOverlayVisible"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scanningProgress:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScanningProgressConfiguration","kind":"typeIdentifier","text":"SBSDKUI2CreditCardScanningProgressConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanningProgressConfiguration"},{"kind":"text","text":" *) "},{"text":"scanningProgress","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scanIncompleteDataTimeout:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"scanIncompleteDataTimeout"},{"text":" ","kind":"text"},{"text":"successOverlay:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanCompletionOverlay","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanCompletionOverlay","text":"SBSDKUI2ScanCompletionOverlay","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"successOverlay","kind":"internalParam"},{"kind":"text","text":" "},{"text":"incompleteDataOverlay:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanCompletionOverlay","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanCompletionOverlay","text":"SBSDKUI2ScanCompletionOverlay","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"incompleteDataOverlay"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sound:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound","text":"SBSDKUI2Sound","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sound"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sound"},{"kind":"text","text":" "},{"text":"vibration:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Vibration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Vibration","text":"SBSDKUI2Vibration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"vibration","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerConfiguration":{"title":"SBSDKCreditCardScannerConfiguration","role":"symbol","abstract":[{"text":"Configuration for the credit card scanner.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPermissionScreen":{"navigatorTitle":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the camera permission request view."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen","title":"SBSDKUI2CameraPermissionScreen","url":"\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration","title":"SBSDKUI2CreditCardScannerScreenConfiguration","navigatorTitle":[{"text":"SBSDKUI2CreditCardScannerScreenConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration","abstract":[{"type":"text","text":"Configuration of the screen for detecting credit card data."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerIntroScreenConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerIntroScreenConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the introduction screen for the credit card scanner."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerintroscreenconfiguration","title":"SBSDKUI2CreditCardScannerIntroScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerIntroScreenConfiguration","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerIntroScreenConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PermanentViewFinderConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PermanentViewFinderConfiguration"}],"role":"symbol","title":"SBSDKUI2PermanentViewFinderConfiguration","type":"topic","abstract":[{"text":"Configuration of the scanning interface’s viewfinder, which is always visible to guide the user.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PermanentViewFinderConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2permanentviewfinderconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Vibration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Vibration"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configure the vibration."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2Vibration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Vibration","title":"SBSDKUI2Vibration","url":"\/documentation\/scanbotsdk\/sbsdkui2vibration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenTextLocalization":{"type":"topic","role":"symbol","abstract":[{"text":"Configuration of the all strings for credit card scanner screen.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreentextlocalization","kind":"symbol","title":"SBSDKUI2CreditCardScannerScreenTextLocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the hint guiding users through the scanning process."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","title":"SBSDKUI2UserGuidanceConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidanceconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sound":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration for the sound."}],"navigatorTitle":[{"text":"SBSDKUI2Sound","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sound","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2Sound"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound","title":"SBSDKUI2Sound","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconButton":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the icon appearance on a button."}],"navigatorTitle":[{"text":"SBSDKUI2IconButton","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2iconbutton","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2IconButton"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton","title":"SBSDKUI2IconButton","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TopBarConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2topbarconfiguration","kind":"symbol","type":"topic","abstract":[{"text":"Configuration of the top bar’s appearance.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration","title":"SBSDKUI2TopBarConfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanGuidanceConfiguration":{"abstract":[{"type":"text","text":"Configuration of the hints guiding users through the credit card scanning process."}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2CreditCardScanGuidanceConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2CreditCardScanGuidanceConfiguration","kind":"identifier"}],"title":"SBSDKUI2CreditCardScanGuidanceConfiguration","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Palette":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Palette","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Palette","title":"SBSDKUI2Palette","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2palette","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Palette"}],"abstract":[{"text":"Value palette describing the colors of the scanner screens.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2color","title":"SBSDKUI2Color","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Configuration of the camera settings to be used while scanning.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration","title":"SBSDKUI2CameraConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2cameraconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanningProgressConfiguration":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScanningProgressConfiguration"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CreditCardScanningProgressConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanningProgressConfiguration","title":"SBSDKUI2CreditCardScanningProgressConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanningprogressconfiguration","abstract":[{"type":"text","text":"Configuration of visualization of the scanning progress - indeterminate progress."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanCompletionOverlay":{"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2ScanCompletionOverlay","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanCompletionOverlay","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ScanCompletionOverlay","kind":"identifier"}],"type":"topic","title":"SBSDKUI2ScanCompletionOverlay","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2scancompletionoverlay","abstract":[{"type":"text","text":"Configuration of the overlay to be shown after the successful scan."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ActionBarConfiguration":{"kind":"symbol","abstract":[{"text":"Configuration of the buttons available in the action bar.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ActionBarConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2actionbarconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ActionBarConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration","title":"SBSDKUI2ActionBarConfiguration","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:scanStatusUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:exampleOverlayVisible:scanningProgress:scanIncompleteDataTimeout:successOverlay:incompleteDataOverlay:sound:vibration:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/initwithversion:screen:localization:palette:backgroundcolor:cameraconfiguration:camerapermission:topuserguidance:scanstatususerguidance:topbar:topbaropenintroscreenbutton:introscreen:actionbar:viewfinder:scannerconfiguration:exampleoverlayv-12ncx","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:scanStatusUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:exampleOverlayVisible:scanningProgress:scanIncompleteDataTimeout:successOverlay:incompleteDataOverlay:sound:vibration:"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:scanStatusUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:exampleOverlayVisible:scanningProgress:scanIncompleteDataTimeout:successOverlay:incompleteDataOverlay:sound:vibration:","type":"topic","kind":"symbol","title":"initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:scanStatusUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:exampleOverlayVisible:scanningProgress:scanIncompleteDataTimeout:successOverlay:incompleteDataOverlay:sound:vibration:","navigatorTitle":[{"text":"initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:scanStatusUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:exampleOverlayVisible:scanningProgress:scanIncompleteDataTimeout:successOverlay:incompleteDataOverlay:sound:vibration:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKCreditCardScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/title"},{"value":[{"text":"SBSDKCreditCardScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2CameraPermissionScreen","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2CreditCardScannerScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2CreditCardScannerScreenConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerIntroScreenConfiguration\/title","value":"SBSDKUI2CreditCardScannerIntroScreenConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerIntroScreenConfiguration\/fragments","value":[{"text":"SBSDKUI2CreditCardScannerIntroScreenConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerIntroScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerIntroScreenConfiguration"}]},{"value":"SBSDKUI2PermanentViewFinderConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PermanentViewFinderConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2PermanentViewFinderConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PermanentViewFinderConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PermanentViewFinderConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/title","value":"SBSDKUI2Vibration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Vibration"}]},{"value":[{"text":"SBSDKUI2Vibration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization\/title","value":"SBSDKUI2CreditCardScannerScreenTextLocalization","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization\/fragments","value":[{"text":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization\/navigatorTitle"},{"value":"SBSDKUI2UserGuidanceConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/fragments","value":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/title","value":"SBSDKUI2Sound"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Sound"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Sound"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/title","op":"replace","value":"SBSDKUI2IconButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/fragments","op":"replace","value":[{"text":"SBSDKUI2IconButton","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2IconButton"}]},{"value":"SBSDKUI2TopBarConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration\/fragments","value":[{"text":"SBSDKUI2TopBarConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration\/navigatorTitle"},{"value":"SBSDKUI2CreditCardScanGuidanceConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScanGuidanceConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScanGuidanceConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette\/title","value":"SBSDKUI2Palette"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Palette"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Palette"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKUI2CameraConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanningProgressConfiguration\/title","value":"SBSDKUI2CreditCardScanningProgressConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanningProgressConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScanningProgressConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanningProgressConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2CreditCardScanningProgressConfiguration","kind":"identifier"}]},{"value":"SBSDKUI2ScanCompletionOverlay","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanCompletionOverlay\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanCompletionOverlay\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ScanCompletionOverlay"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanCompletionOverlay\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ScanCompletionOverlay"}],"op":"replace"},{"value":"SBSDKUI2ActionBarConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ActionBarConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2ActionBarConfiguration","kind":"identifier"}]}]}]}