{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerMapping"]]},"abstract":[{"type":"text","text":"Method in which you should load and return information about barcode. The info is returned in block, so async loading is possible."}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerMapping\/loadMappedData(for:completion:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannermapping\/loadmappeddata(for:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannermapping\/loadmappeddata(for:completion:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(loadMappedDataForBarcode:completion:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadMappedData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":" ","kind":"text"},{"text":"barcode","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult","text":"SBSDKBarcodeScannerResult","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"SBSDKUIBarcodeMappedData","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeMappedData","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeMappedData"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Barcode, for which the info should be returned."}]}],"name":"barcode"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Block, where you should return mapped info about barcode."}]}],"name":"completion"}],"kind":"parameters"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}],"type":"paragraph"}],"metadata":{"required":true,"platforms":[],"title":"loadMappedData(for:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadMappedData","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"SBSDKBarcodeScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeMappedData","kind":"typeIdentifier","text":"SBSDKUIBarcodeMappedData"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIBarcodesBatchScannerMapping(im)loadMappedDataForBarcode:completion:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"loadMappedDataForBarcode:completion:"}],"modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerMapping":{"type":"topic","title":"SBSDKUIBarcodesBatchScannerMapping","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerMapping"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannermapping","abstract":[{"text":"Protocol for the ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","isActive":true},{"text":" barcode results mapping.","type":"text"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerMapping","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerMapping"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult","title":"SBSDKBarcodeScannerResult","type":"topic","abstract":[{"type":"text","text":"This class encapsulates the result of a barcode detection."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerMapping/loadMappedData(for:completion:)":{"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannermapping\/loadmappeddata(for:completion:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerMapping\/loadMappedData(for:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadMappedData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKBarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeMappedData","text":"SBSDKUIBarcodeMappedData","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"loadMappedDataForBarcode:completion:"}],"deprecated":true,"kind":"symbol","type":"topic","required":true,"role":"symbol","title":"loadMappedData(for:completion:)","abstract":[{"type":"text","text":"Method in which you should load and return information about barcode. The info is returned in block, so async loading is possible."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller","role":"symbol","deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"title":"SBSDKUIBarcodesBatchScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","type":"topic","abstract":[{"text":"A highly customizable camera-based view controller to detect barcodes batches.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeMappedData":{"type":"topic","title":"SBSDKUIBarcodeMappedData","navigatorTitle":[{"text":"SBSDKUIBarcodeMappedData","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodemappeddata","abstract":[{"text":"Class that contains barcode name and description.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeMappedData","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeMappedData"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"loadMappedDataForBarcode:completion:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadMappedDataForBarcode:completion:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"loadMappedDataForBarcode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeScannerResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"barcode"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeMappedData","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeMappedData","text":"SBSDKUIBarcodeMappedData","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerMapping\/title","op":"replace","value":"SBSDKUIBarcodesBatchScannerMapping"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerMapping\/fragments","value":[{"text":"SBSDKUIBarcodesBatchScannerMapping","kind":"identifier"}],"op":"replace"},{"value":"SBSDKBarcodeScannerResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/fragments"},{"value":"loadMappedDataForBarcode:completion:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerMapping~1loadMappedData(for:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadMappedDataForBarcode:completion:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerMapping~1loadMappedData(for:completion:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/title","value":"SBSDKUIBarcodesBatchScannerViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/fragments","value":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeMappedData\/title","op":"replace","value":"SBSDKUIBarcodeMappedData"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeMappedData\/fragments","op":"replace","value":[{"text":"SBSDKUIBarcodeMappedData","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}