{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData"]]},"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData(py)requiredDocumentType","symbolKind":"property","navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}],"roleHeading":"Instance Property","title":"requiredDocumentType","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredDocumentType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"abstract":[{"type":"text","text":"The name of the wrapped document type."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/requiredDocumentType","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/requireddocumenttype"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/requireddocumenttype"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData/requiredDocumentType":{"title":"requiredDocumentType","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/requireddocumenttype","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredDocumentType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}],"abstract":[{"type":"text","text":"The name of the wrapped document type."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/requiredDocumentType"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData":{"role":"symbol","title":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","abstract":[{"type":"text","text":"Vehicle Safety Inspection Data. File type “VS”."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData"}],"type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"requiredDocumentType","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"requiredDocumentType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"requiredDocumentType"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1requiredDocumentType\/title","value":"requiredDocumentType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1requiredDocumentType\/fragments","value":[{"kind":"identifier","text":"requiredDocumentType"}],"op":"replace"},{"op":"replace","value":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"identifier"}]}]}]}