{"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"case","title":"SBSDKProcessingMode.live","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"live"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessingModeLive"}],"roleHeading":"Case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKProcessingMode@SBSDKProcessingModeLive"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkprocessingmode\/live"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkprocessingmode\/live"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"live"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/live","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"In live mode input images are expected to come from a video source like a camera."},{"type":"text","text":" "},{"type":"text","text":"Scanners in live mode typically spend little time on each image and are able to quickly analyze multiple images and combine the individual image results into a final result."},{"type":"text","text":" "},{"type":"text","text":"Individual results from a particular image may be less accurate than running the scanner in single-shot mode on that frame, but after aggregating a few images of the same subject, the final result becomes much more accurate."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKProcessingMode":{"title":"SBSDKProcessingMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkprocessingmode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProcessingMode"}],"abstract":[{"text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it.","type":"text"},{"text":" ","type":"text"},{"text":"On the other hand, scanners can produce even better results if they can analyze multiple images of the same subject and cross-check and combine the results.","type":"text"},{"text":" ","type":"text"},{"text":"The processing mode tells the scanner whether to optimize for single or multiple images of a subject.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessingMode"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKProcessingMode/live":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkprocessingmode\/live","title":"SBSDKProcessingMode.live","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/live","navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessingModeLive"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"live"}],"abstract":[{"text":"In live mode input images are expected to come from a video source like a camera.","type":"text"},{"text":" ","type":"text"},{"text":"Scanners in live mode typically spend little time on each image and are able to quickly analyze multiple images and combine the individual image results into a final result.","type":"text"},{"text":" ","type":"text"},{"text":"Individual results from a particular image may be less accurate than running the scanner in single-shot mode on that frame, but after aggregating a few images of the same subject, the final result becomes much more accurate.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKProcessingModeLive","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKProcessingModeLive","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKProcessingModeLive","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKProcessingMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKProcessingMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode\/fragments","op":"replace"},{"value":[{"text":"SBSDKProcessingMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode\/navigatorTitle","op":"replace"},{"value":"SBSDKProcessingModeLive","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode~1live\/title","op":"replace"},{"value":[{"text":"SBSDKProcessingModeLive","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode~1live\/fragments","op":"replace"}]}]}