{"kind":"symbol","metadata":{"title":"copyWithZone:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardIntroCustomImage(im)copyWithZone:"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroCustomImage"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroCustomImage\/copyWithZone:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone","text":"_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardintrocustomimage\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroCustomImage":{"type":"topic","role":"symbol","title":"SBSDKUI2CreditCardIntroCustomImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroCustomImage","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintrocustomimage","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2CreditCardIntroCustomImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardIntroCustomImage","kind":"identifier"}],"abstract":[{"type":"text","text":"A custom image for the introduction screen."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroCustomImage/copyWithZone:":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"kind":"symbol","title":"copyWithZone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroCustomImage\/copyWithZone:","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintrocustomimage\/copywithzone:","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2CreditCardIntroCustomImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroCustomImage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardIntroCustomImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroCustomImage\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardIntroCustomImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroCustomImage\/navigatorTitle"}]}]}