{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting\/decryptDataFromURL(_:)-41buv"]]},"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"extendedModule":"ScanbotSDK","roleHeading":"Instance Method","symbolKind":"method","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" inherits ","type":"text"},{"type":"codeVoice","code":"NSObject"},{"type":"text","text":"."}]},"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"decryptDataFromURL","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"externalID":"s:10ScanbotSDK20SBSDKStorageCryptingPAASo8NSObjectCRbzrlE18decryptDataFromURLy10Foundation0G0VAG0I0VKF","title":"decryptDataFromURL(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decryptDataFromURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"url","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"url","content":[{"inlineContent":[{"type":"text","text":"The URL that contains the data to be decrypted."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The decrypted data."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting\/decryptDataFromURL(_:)-2qxtm","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Decrypts the data at the given URL and returns it."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkstoragecrypting\/decryptdatafromurl(_:)-2qxtm"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCrypting":{"title":"SBSDKStorageCrypting","type":"topic","abstract":[{"type":"text","text":"Protocol for implementing encryption and decryption of (streamed) data."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstoragecrypting","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCrypting/decryptDataFromURL(_:)-2qxtm":{"title":"decryptDataFromURL(_:)","abstract":[{"type":"text","text":"Decrypts the data at the given URL and returns it."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting\/decryptDataFromURL(_:)-2qxtm","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"decryptDataFromURL","kind":"identifier"},{"kind":"text","text":"("},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"url":"\/documentation\/scanbotsdk\/sbsdkstoragecrypting\/decryptdatafromurl(_:)-2qxtm","kind":"symbol","type":"topic","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" inherits ","type":"text"},{"type":"codeVoice","code":"NSObject"},{"type":"text","text":"."}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCrypting/decryptDataFromURL(_:)-41buv":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting\/decryptDataFromURL(_:)-41buv","title":"decryptDataFromURL(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"decryptDataFromURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"defaultImplementations":1,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"decryptDataFromURL:error:"}],"abstract":[{"type":"text","text":"Decrypts the data at the given URL and returns it."}],"required":true,"url":"\/documentation\/scanbotsdk\/sbsdkstoragecrypting\/decryptdatafromurl(_:)-41buv","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/title","value":"SBSDKStorageCrypting"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting~1decryptDataFromURL(_:)-41buv\/title","value":"decryptDataFromURL:error:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting~1decryptDataFromURL(_:)-41buv\/fragments","value":[{"kind":"text","text":"- "},{"text":"decryptDataFromURL:error:","kind":"identifier"}]}]}]}