{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"code","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult","text":"SBSDKBarcodeScannerResult","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Instance Property","title":"code","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"code","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerAccumulatingResult(py)code"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerAccumulatingResult"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerAccumulatingResult\/code","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The detected barcode."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"code"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult","text":"SBSDKBarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescanneraccumulatingresult\/code"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescanneraccumulatingresult\/code"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"title":"SBSDKBarcodeScannerResult","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult","abstract":[{"type":"text","text":"This class encapsulates the result of a barcode detection."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerAccumulatingResult":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerAccumulatingResult"}],"title":"SBSDKBarcodeScannerAccumulatingResult","role":"symbol","abstract":[{"type":"text","text":"A class to keep track of a detected barcode and the number of times it is scanned."}],"navigatorTitle":[{"text":"SBSDKBarcodeScannerAccumulatingResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerAccumulatingResult","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanneraccumulatingresult","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerAccumulatingResult/code":{"navigatorTitle":[{"text":"code","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanneraccumulatingresult\/code","abstract":[{"text":"The detected barcode.","type":"text"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"code"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult","text":"SBSDKBarcodeScannerResult","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerAccumulatingResult\/code","type":"topic","title":"code","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"code","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"code"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult","text":"SBSDKBarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult"},{"kind":"text","text":" * "},{"kind":"identifier","text":"code"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/title","value":"SBSDKBarcodeScannerResult"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerAccumulatingResult\/title","value":"SBSDKBarcodeScannerAccumulatingResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerAccumulatingResult\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerAccumulatingResult"}]},{"value":[{"text":"SBSDKBarcodeScannerAccumulatingResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerAccumulatingResult\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerAccumulatingResult~1code\/title","op":"replace","value":"code"},{"op":"replace","value":[{"text":"code","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerAccumulatingResult~1code\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}