{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/cubic","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Bi-cubic interpolation. Better quality than bi-linear, slower. Produces high-quality"},{"type":"text","text":" "},{"type":"text","text":"results in a larger range than that of bi-linear."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cubic","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/cubic"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/cubic"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"SBSDKResamplingMethod.cubic","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cubic"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKResamplingMethodCubic"}],"symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKResamplingMethod@SBSDKResamplingMethodCubic"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod/cubic":{"role":"symbol","navigatorTitle":[{"text":"SBSDKResamplingMethodCubic","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cubic","kind":"identifier"}],"kind":"symbol","title":"SBSDKResamplingMethod.cubic","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/cubic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/cubic","abstract":[{"text":"Bi-cubic interpolation. Better quality than bi-linear, slower. Produces high-quality","type":"text"},{"text":" ","type":"text"},{"text":"results in a larger range than that of bi-linear.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod":{"type":"topic","abstract":[{"type":"text","text":"Resampling method."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKResamplingMethod"}],"title":"SBSDKResamplingMethod","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKResamplingMethod"}],"url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKResamplingMethodCubic","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKResamplingMethodCubic","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"SBSDKResamplingMethodCubic","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1cubic\/title","value":"SBSDKResamplingMethodCubic","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1cubic\/fragments","value":[{"kind":"identifier","text":"SBSDKResamplingMethodCubic"}],"op":"replace"},{"value":"SBSDKResamplingMethod","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/title"},{"value":[{"text":"SBSDKResamplingMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKResamplingMethod"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/navigatorTitle"}]}]}