{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MrzIntroNoImage(cm)fromJsonWithJson:","roleHeading":"Type Method","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2MrzIntroNoImage","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroNoImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MrzIntroNoImage"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroNoImage"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzintronoimage\/fromjsonwithjson:"]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroNoImage\/fromJsonWithJson:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MrzIntroNoImage/fromJsonWithJson:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroNoImage\/fromJsonWithJson:","title":"fromJsonWithJson:","kind":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzintronoimage\/fromjsonwithjson:","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MrzIntroNoImage":{"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroNoImage","title":"SBSDKUI2MrzIntroNoImage","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2MrzIntroNoImage","kind":"identifier"}],"abstract":[{"text":"No image for the introduction screen.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MrzIntroNoImage","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzintronoimage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2MrzIntroNoImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzIntroNoImage\/title"},{"value":[{"text":"SBSDKUI2MrzIntroNoImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzIntroNoImage\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2MrzIntroNoImage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzIntroNoImage\/navigatorTitle"}]}]}