{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionMode\/live","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","title":"SBSDKDocumentDataExtractionMode.live","role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDataExtractionMode@SBSDKDocumentDataExtractionModeLive","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"live","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"SBSDKDocumentDataExtractionModeLive","kind":"identifier"}]},"abstract":[{"text":"The extractor will attempt to accumulate results over multiple frames.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionMode"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"live","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionmode\/live"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionmode\/live"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionMode/live":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"live","kind":"identifier"}],"abstract":[{"type":"text","text":"The extractor will attempt to accumulate results over multiple frames."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionMode\/live","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionmode\/live","title":"SBSDKDocumentDataExtractionMode.live","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDataExtractionModeLive","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionMode","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDataExtractionMode","kind":"identifier"}],"title":"SBSDKDocumentDataExtractionMode","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionmode","abstract":[{"type":"text","text":"The extraction mode."}],"kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractionMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKDocumentDataExtractionModeLive","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKDocumentDataExtractionModeLive","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionModeLive"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentDataExtractionModeLive","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionMode~1live\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionModeLive"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionMode~1live\/fragments"},{"value":"SBSDKDocumentDataExtractionMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionMode\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}