{"metadata":{"role":"symbol","title":"additionalParameters","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"additionalParameters","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeAdditionalParameters","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeAdditionalParameters"}],"navigatorTitle":[{"kind":"identifier","text":"additionalParameters"}],"roleHeading":"Instance Property","platforms":[],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeScannerBehaviorConfiguration(py)additionalParameters"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerbehaviorconfiguration\/additionalparameters"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerbehaviorconfiguration\/additionalparameters"]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration\/additionalParameters"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"additionalParameters"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAdditionalParameters","text":"SBSDKBarcodeAdditionalParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeAdditionalParameters"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Additional parameters for tweaking the detection of barcodes.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration"]]},"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeAdditionalParameters":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeAdditionalParameters"}],"abstract":[{"text":"A class that contains additional parameters for barcodes detection and filtering.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeAdditionalParameters"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeadditionalparameters","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAdditionalParameters","kind":"symbol","title":"SBSDKBarcodeAdditionalParameters"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","kind":"symbol","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerBehaviorConfiguration/additionalParameters":{"deprecated":true,"abstract":[{"text":"Additional parameters for tweaking the detection of barcodes.","type":"text"}],"title":"additionalParameters","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration\/additionalParameters","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"additionalParameters","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKBarcodeAdditionalParameters","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeAdditionalParameters","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"additionalParameters","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerbehaviorconfiguration\/additionalparameters","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerBehaviorConfiguration":{"abstract":[{"type":"text","text":"The configuration for the behavior of the RTU-UI barcode scanner."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerbehaviorconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"identifier"}],"deprecated":true,"title":"SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"additionalParameters","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"additionalParameters","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAdditionalParameters","text":"SBSDKBarcodeAdditionalParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeAdditionalParameters"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"additionalParameters"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKBarcodeAdditionalParameters","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAdditionalParameters\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAdditionalParameters\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeAdditionalParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAdditionalParameters\/navigatorTitle","value":[{"text":"SBSDKBarcodeAdditionalParameters","kind":"identifier"}]},{"value":"additionalParameters","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration~1additionalParameters\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration~1additionalParameters\/fragments","value":[{"kind":"identifier","text":"additionalParameters"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration\/title","value":"SBSDKUIBarcodeScannerBehaviorConfiguration","op":"replace"},{"value":[{"text":"SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration\/fragments"},{"value":[{"text":"SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration\/navigatorTitle","op":"replace"}]}]}