{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerbehaviorconfiguration\/isviewfinderenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerbehaviorconfiguration\/isviewfinderenabled"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"isViewFinderEnabled"}],"platforms":[],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isViewFinderEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeScannerBehaviorConfiguration(py)isViewFinderEnabled","title":"isViewFinderEnabled"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isViewFinderEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration\/isViewFinderEnabled","interfaceLanguage":"swift"},"kind":"symbol","deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}]}],"abstract":[{"text":"Set to ","type":"text"},{"code":"True","type":"codeVoice"},{"text":" to enable and display the region of interest, to ","type":"text"},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerBehaviorConfiguration":{"type":"topic","title":"SBSDKUIBarcodeScannerBehaviorConfiguration","abstract":[{"type":"text","text":"The configuration for the behavior of the RTU-UI barcode scanner."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"identifier"}],"role":"symbol","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerbehaviorconfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerBehaviorConfiguration/isViewFinderEnabled":{"kind":"symbol","abstract":[{"text":"Set to ","type":"text"},{"code":"True","type":"codeVoice"},{"text":" to enable and display the region of interest, to ","type":"text"},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise."}],"title":"isViewFinderEnabled","navigatorTitle":[{"text":"isViewFinderEnabled","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration\/isViewFinderEnabled","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isViewFinderEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerbehaviorconfiguration\/isviewfinderenabled"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"isViewFinderEnabled","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isViewFinderEnabled"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isViewFinderEnabled","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"SBSDKUIBarcodeScannerBehaviorConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerBehaviorConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration~1isViewFinderEnabled\/title","value":"isViewFinderEnabled","op":"replace"},{"value":[{"text":"isViewFinderEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration~1isViewFinderEnabled\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}