{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"kind":"text","text":";"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController\/viewDidLayoutSubviews","interfaceLanguage":"occ"},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController(im)viewDidLayoutSubviews","symbolKind":"method","title":"viewDidLayoutSubviews","roleHeading":"Instance Method","navigatorTitle":[{"text":"viewDidLayoutSubviews","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontroller\/viewdidlayoutsubviews"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewController/viewDidLayoutSubviews":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController\/viewDidLayoutSubviews","role":"symbol","type":"topic","abstract":[],"title":"viewDidLayoutSubviews","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontroller\/viewdidlayoutsubviews","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"viewDidLayoutSubviews","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewController":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontroller","title":"SBSDKImageEditingViewController","abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to show and edit an image.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","role":"collection"}},"variantOverrides":[{"patch":[{"value":"SBSDKImageEditingViewController","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/title","op":"replace"},{"value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}