{"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlayfindandpickconfiguration\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration\/isEqual:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayFindAndPickConfiguration(im)isEqual:","title":"isEqual:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayFindAndPickConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration","title":"SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlayfindandpickconfiguration","abstract":[{"text":"Configuration of the AR overlay.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayFindAndPickConfiguration/isEqual:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlayfindandpickconfiguration\/isequal:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration\/isEqual:","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2ArOverlayFindAndPickConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/title"},{"value":[{"text":"SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}