{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"zone"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle(im)copyWithZone:","symbolKind":"method","title":"copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle\/copywithzone:"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/copyWithZone:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewPolygonStyle/copyWithZone:":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"kind":"symbol","title":"copyWithZone:","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle\/copywithzone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/copyWithZone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontroller","abstract":[{"text":"A class that represents an overlay used for visualizing scanned barcodes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It provides a customizable user interface for displaying barcodes and supports interaction with them."},{"text":" ","type":"text"},{"type":"text","text":"The overlay can be used to highlight and select barcodes based on user input."}],"type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","title":"SBSDKBarcodeTrackingOverlayController","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewPolygonStyle":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle","title":"SBSDKBarcodeTrackedViewPolygonStyle","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle","abstract":[{"type":"text","text":"A class that represents the style of the polygon rendered around a barcode in "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKBarcodeTrackingOverlayController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/fragments","value":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}]},{"value":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle\/title","value":"SBSDKBarcodeTrackedViewPolygonStyle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle\/fragments","value":[{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}]}]}]}