{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpatterncontentvalidator\/patterngrammar"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpatterncontentvalidator\/patterngrammar"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator"]]},"sections":[],"metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPatternContentValidator(py)patternGrammar","navigatorTitle":[{"text":"patternGrammar","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"title":"patternGrammar","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"patternGrammar","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPatternGrammar","text":"SBSDKPatternGrammar"}],"role":"symbol"},"abstract":[{"text":"Grammar of pattern matching.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator\/patternGrammar"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"patternGrammar"},{"text":": ","kind":"text"},{"text":"SBSDKPatternGrammar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPatternGrammar","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternGrammar"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Default is WILDCARD","type":"text"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPatternContentValidator/patternGrammar":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"patternGrammar"},{"text":": ","kind":"text"},{"text":"SBSDKPatternGrammar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPatternGrammar"}],"role":"symbol","type":"topic","title":"patternGrammar","navigatorTitle":[{"kind":"identifier","text":"patternGrammar"}],"url":"\/documentation\/scanbotsdk\/sbsdkpatterncontentvalidator\/patterngrammar","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator\/patternGrammar","abstract":[{"type":"text","text":"Grammar of pattern matching."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPatternGrammar":{"abstract":[{"type":"text","text":"Grammar of pattern matching."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternGrammar","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPatternGrammar","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpatterngrammar","title":"SBSDKPatternGrammar","type":"topic","navigatorTitle":[{"text":"SBSDKPatternGrammar","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPatternContentValidator":{"type":"topic","abstract":[{"text":"Pattern content validator.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkpatterncontentvalidator","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPatternContentValidator","kind":"identifier"}],"title":"SBSDKPatternContentValidator","navigatorTitle":[{"kind":"identifier","text":"SBSDKPatternContentValidator"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"patternGrammar","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"patternGrammar","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPatternGrammar","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPatternGrammar","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternGrammar"},{"text":" ","kind":"text"},{"text":"patternGrammar","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"patternGrammar","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator~1patternGrammar\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator~1patternGrammar\/fragments","value":[{"kind":"identifier","text":"patternGrammar"}],"op":"replace"},{"value":"SBSDKPatternGrammar","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternGrammar\/title"},{"value":[{"text":"SBSDKPatternGrammar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternGrammar\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternGrammar\/navigatorTitle","value":[{"text":"SBSDKPatternGrammar","kind":"identifier"}],"op":"replace"},{"value":"SBSDKPatternContentValidator","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator\/fragments","value":[{"text":"SBSDKPatternContentValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPatternContentValidator"}]}]}]}