{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView\/autoStartAnimation","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"autoStartAnimation"}],"title":"autoStartAnimation","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"autoStartAnimation","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGradientPolygonView(py)autoStartAnimation"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"autoStartAnimation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","abstract":[{"text":"If ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":" the animation starts automatically when the view is visible and stops when hidden."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgradientpolygonview\/autostartanimation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgradientpolygonview\/autostartanimation"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonView/autoStartAnimation":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"autoStartAnimation","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"If "},{"type":"codeVoice","code":"true"},{"type":"text","text":" the animation starts automatically when the view is visible and stops when hidden."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"autoStartAnimation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"autoStartAnimation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView\/autoStartAnimation","url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonview\/autostartanimation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonView":{"type":"topic","title":"SBSDKGradientPolygonView","navigatorTitle":[{"text":"SBSDKGradientPolygonView","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonview","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView","role":"symbol","abstract":[{"text":"A view that displays a polygon (bezier path) stroked with a gradient. The gradient can be animated and the drawing style is customizable.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGradientPolygonView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"autoStartAnimation","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"autoStartAnimation","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoStartAnimation"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView~1autoStartAnimation\/title","value":"autoStartAnimation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView~1autoStartAnimation\/fragments","value":[{"text":"autoStartAnimation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView\/title","value":"SBSDKGradientPolygonView"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView\/fragments","value":[{"kind":"identifier","text":"SBSDKGradientPolygonView"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView\/navigatorTitle","op":"replace","value":[{"text":"SBSDKGradientPolygonView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}