{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopAnimation","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView\/stopAnimation()","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGradientPolygonView(im)stopAnimation","navigatorTitle":[{"text":"stopAnimation","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stopAnimation","kind":"identifier"},{"kind":"text","text":"()"}],"title":"stopAnimation()","symbolKind":"method","modules":[{"name":"ScanbotSDK"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgradientpolygonview\/stopanimation()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgradientpolygonview\/stopanimation()"]}],"abstract":[{"type":"text","text":"Stops the animation and resets the animation progress."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonView":{"type":"topic","title":"SBSDKGradientPolygonView","navigatorTitle":[{"text":"SBSDKGradientPolygonView","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonview","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView","role":"symbol","abstract":[{"text":"A view that displays a polygon (bezier path) stroked with a gradient. The gradient can be animated and the drawing style is customizable.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGradientPolygonView","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonView/stopAnimation()":{"title":"stopAnimation()","kind":"symbol","abstract":[{"text":"Stops the animation and resets the animation progress.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonview\/stopanimation()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopAnimation"},{"text":"()","kind":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView\/stopAnimation()","navigatorTitle":[{"text":"stopAnimation","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"stopAnimation","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"stopAnimation","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"stopAnimation"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView\/title","value":"SBSDKGradientPolygonView"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView\/fragments","value":[{"kind":"identifier","text":"SBSDKGradientPolygonView"}],"op":"replace"},{"value":[{"text":"SBSDKGradientPolygonView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView~1stopAnimation()\/title","value":"stopAnimation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView~1stopAnimation()\/fragments","value":[{"kind":"text","text":"- "},{"text":"stopAnimation","kind":"identifier"}]}]}]}