{"sections":[],"metadata":{"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IntroImage(cm)idCardIntroImage","title":"idCardIntroImage()","navigatorTitle":[{"text":"idCardIntroImage","kind":"identifier"}],"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"idCardIntroImage","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"SBSDKUI2IdCardIntroImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IdCardIntroImage"}],"role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroImage\/idCardIntroImage()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"idCardIntroImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IdCardIntroImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IdCardIntroImage","text":"SBSDKUI2IdCardIntroImage"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2introimage\/idcardintroimage()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2introimage\/idcardintroimage()"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroImage"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroImage/idCardIntroImage()":{"role":"symbol","title":"idCardIntroImage()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroImage\/idCardIntroImage()","kind":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"idCardIntroImage","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IdCardIntroImage","kind":"typeIdentifier","text":"SBSDKUI2IdCardIntroImage"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2introimage\/idcardintroimage()","navigatorTitle":[{"text":"idCardIntroImage","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroImage":{"abstract":[{"type":"text","text":"Determines the image for the introduction screen."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2introimage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroImage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IntroImage"}],"kind":"symbol","type":"topic","title":"SBSDKUI2IntroImage","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2IntroImage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IdCardIntroImage":{"kind":"symbol","role":"symbol","abstract":[{"text":"The image for the introduction screen with an ID card template.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IdCardIntroImage","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IdCardIntroImage"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2IdCardIntroImage"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2idcardintroimage","title":"SBSDKUI2IdCardIntroImage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"idCardIntroImage"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"idCardIntroImage","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IdCardIntroImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IdCardIntroImage","kind":"typeIdentifier","text":"SBSDKUI2IdCardIntroImage"},{"kind":"text","text":" *) "},{"text":"idCardIntroImage","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroImage~1idCardIntroImage()\/title","value":"idCardIntroImage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroImage~1idCardIntroImage()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"idCardIntroImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroImage\/title","value":"SBSDKUI2IntroImage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroImage\/fragments","value":[{"text":"SBSDKUI2IntroImage","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2IntroImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroImage\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IdCardIntroImage\/title","value":"SBSDKUI2IdCardIntroImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IdCardIntroImage\/fragments","value":[{"text":"SBSDKUI2IdCardIntroImage","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUI2IdCardIntroImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IdCardIntroImage\/navigatorTitle"}]}]}