{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVARecordFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAAMVARecordFieldType","text":"SBSDKAAMVARecordFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkaamvadocumentsubfilefield\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkaamvadocumentsubfilefield\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVADocumentSubfileField\/type","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The field type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKAAMVARecordFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAAMVARecordFieldType"}],"title":"type","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAAMVADocumentSubfileField(py)type","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"type"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVADocumentSubfileField"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAAMVADocumentSubfileField":{"role":"symbol","title":"SBSDKAAMVADocumentSubfileField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAAMVADocumentSubfileField"}],"abstract":[{"type":"text","text":"The AAMVA document subfile field."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVADocumentSubfileField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKAAMVADocumentSubfileField"}],"url":"\/documentation\/scanbotsdk\/sbsdkaamvadocumentsubfilefield"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAAMVADocumentSubfileField/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKAAMVARecordFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAAMVARecordFieldType"}],"abstract":[{"type":"text","text":"The field type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVADocumentSubfileField\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/scanbotsdk\/sbsdkaamvadocumentsubfilefield\/type"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAAMVARecordFieldType":{"role":"symbol","title":"SBSDKAAMVARecordFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAAMVARecordFieldType"}],"abstract":[{"type":"text","text":"The known values for AAMVA fields."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVARecordFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkaamvarecordfieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVARecordFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAAMVARecordFieldType","text":"SBSDKAAMVARecordFieldType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVADocumentSubfileField\/title","value":"SBSDKAAMVADocumentSubfileField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVADocumentSubfileField\/fragments","value":[{"kind":"identifier","text":"SBSDKAAMVADocumentSubfileField"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVADocumentSubfileField~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVADocumentSubfileField~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVARecordFieldType\/title","value":"SBSDKAAMVARecordFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVARecordFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}