{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScanningFlow\/documentUuid","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"The UUID of the existing document to be edited.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentUuid","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentUuid"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"documentUuid","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScanningFlow(py)documentUuid","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"documentUuid","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanningflow\/documentuuid"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanningflow\/documentuuid"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScanningFlow"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScanningFlow/documentUuid":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanningflow\/documentuuid","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentUuid"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"The UUID of the existing document to be edited."}],"title":"documentUuid","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScanningFlow\/documentUuid","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentUuid"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScanningFlow":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScanningFlow","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2DocumentScanningFlow","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanningflow","title":"SBSDKUI2DocumentScanningFlow","abstract":[{"type":"text","text":"Configuration of the document scanner screen."}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScanningFlow"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"documentUuid","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"documentUuid","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"documentUuid","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScanningFlow~1documentUuid\/title","value":"documentUuid"},{"value":[{"text":"documentUuid","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScanningFlow~1documentUuid\/fragments"},{"value":"SBSDKUI2DocumentScanningFlow","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScanningFlow\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScanningFlow\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScanningFlow"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentScanningFlow","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScanningFlow\/navigatorTitle"}]}]}