{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScanningFlow\/init(version:screen:palette:localization:appearance:outputSettings:screens:documentUuid:cleanScanningSession:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"version"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"1.0\", "},{"text":"screen","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" = \"DocumentScanner\", ","kind":"text"},{"kind":"externalParam","text":"palette"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Palette","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Palette","text":"SBSDKUI2Palette"},{"kind":"text","text":" = SBSDKUI2Palette(sbColorPrimary: SBSDKUI2Color(colorString: \"#C8193C\", isArgb: false),\n                                    sbColorPrimaryDisabled: SBSDKUI2Color(colorString: \"#F5F5F5\",\n                                                                          isArgb: false),\n                                    sbColorNegative: SBSDKUI2Color(colorString: \"#FF3737\",\n                                                                   isArgb: false),\n                                    sbColorPositive: SBSDKUI2Color(colorString: \"#4EFFB4\",\n                                                                   isArgb: false),\n                                    sbColorWarning: SBSDKUI2Color(colorString: \"#FFCE5C\",\n                                                                  isArgb: false),\n                                    sbColorSecondary: SBSDKUI2Color(colorString: \"#FFEDEE\",\n                                                                    isArgb: false),\n                                    sbColorSecondaryDisabled: SBSDKUI2Color(colorString: \"#F5F5F5\",\n                                                                            isArgb: false),\n                                    sbColorOnPrimary: SBSDKUI2Color(colorString: \"#FFFFFF\",\n                                                                    isArgb: false),\n                                    sbColorOnSecondary: SBSDKUI2Color(colorString: \"#C8193C\",\n                                                                      isArgb: false),\n                                    sbColorSurface: SBSDKUI2Color(colorString: \"#FFFFFF\",\n                                                                  isArgb: false),\n                                    sbColorOutline: SBSDKUI2Color(colorString: \"#EFEFEF\",\n                                                                  isArgb: false),\n                                    sbColorOnSurfaceVariant: SBSDKUI2Color(colorString: \"#707070\",\n                                                                           isArgb: false),\n                                    sbColorOnSurface: SBSDKUI2Color(colorString: \"#000000\",\n                                                                    isArgb: false),\n                                    sbColorSurfaceLow: SBSDKUI2Color(colorString: \"#00000026\",\n                                                                     isArgb: false),\n                                    sbColorSurfaceHigh: SBSDKUI2Color(colorString: \"#0000007A\",\n                                                                      isArgb: false),\n                                    sbColorModalOverlay: SBSDKUI2Color(colorString: \"#000000A3\",\n                                                                       isArgb: false)), "},{"text":"localization","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization","text":"SBSDKUI2DocumentScannerTextLocalization"},{"kind":"text","text":" = SBSDKUI2DocumentScannerTextLocalization(), "},{"text":"appearance","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2DocumentFlowAppearanceConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentFlowAppearanceConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration"},{"kind":"text","text":" = SBSDKUI2DocumentFlowAppearanceConfiguration(), "},{"kind":"externalParam","text":"outputSettings"},{"kind":"text","text":": "},{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerOutputSettings","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings"},{"kind":"text","text":" = SBSDKUI2DocumentScannerOutputSettings(), "},{"text":"screens","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerScreens","text":"SBSDKUI2DocumentScannerScreens","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerScreens"},{"text":" = SBSDKUI2DocumentScannerScreens(), ","kind":"text"},{"text":"documentUuid","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"cleanScanningSession"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = true)","kind":"text"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"version"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"screen"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"palette"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Palette","kind":"typeIdentifier","text":"SBSDKUI2Palette"},{"kind":"text","text":", "},{"kind":"externalParam","text":"localization"},{"kind":"text","text":": "},{"text":"SBSDKUI2DocumentScannerTextLocalization","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"appearance","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentFlowAppearanceConfiguration","text":"SBSDKUI2DocumentFlowAppearanceConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputSettings"},{"text":": ","kind":"text"},{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerOutputSettings"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"screens"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerScreens","text":"SBSDKUI2DocumentScannerScreens","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"documentUuid","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"cleanScanningSession","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"roleHeading":"Initializer","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScanningFlow(im)initWithVersion:screen:palette:localization:appearance:outputSettings:screens:documentUuid:cleanScanningSession:","title":"init(version:screen:palette:localization:appearance:outputSettings:screens:documentUuid:cleanScanningSession:)","navigatorTitle":[{"kind":"identifier","text":"initWithVersion:screen:palette:localization:appearance:outputSettings:screens:documentUuid:cleanScanningSession:"}],"symbolKind":"init"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanningflow\/init(version:screen:palette:localization:appearance:outputsettings:screens:documentuuid:cleanscanningsession:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanningflow\/init(version:screen:palette:localization:appearance:outputsettings:screens:documentuuid:cleanscanningsession:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScanningFlow"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerScreens":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerScreens","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannerscreens","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentScannerScreens","kind":"identifier"}],"title":"SBSDKUI2DocumentScannerScreens","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerScreens","kind":"identifier"}],"abstract":[{"text":"Configuration of the document scanner sub-screens.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Palette":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Palette","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Palette"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Palette","role":"symbol","abstract":[{"type":"text","text":"Value palette describing the colors of the scanner screens."}],"title":"SBSDKUI2Palette","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2palette"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScanningFlow/init(version:screen:palette:localization:appearance:outputSettings:screens:documentUuid:cleanScanningSession:)":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanningflow\/init(version:screen:palette:localization:appearance:outputsettings:screens:documentuuid:cleanscanningsession:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"version","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"screen"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"palette","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Palette","text":"SBSDKUI2Palette"},{"kind":"text","text":", "},{"kind":"externalParam","text":"localization"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization","text":"SBSDKUI2DocumentScannerTextLocalization","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"appearance","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentFlowAppearanceConfiguration","text":"SBSDKUI2DocumentFlowAppearanceConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"outputSettings"},{"kind":"text","text":": "},{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerOutputSettings"},{"kind":"text","text":", "},{"text":"screens","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2DocumentScannerScreens","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerScreens"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentUuid"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"cleanScanningSession"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"title":"init(version:screen:palette:localization:appearance:outputSettings:screens:documentUuid:cleanScanningSession:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScanningFlow\/init(version:screen:palette:localization:appearance:outputSettings:screens:documentUuid:cleanScanningSession:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithVersion:screen:palette:localization:appearance:outputSettings:screens:documentUuid:cleanScanningSession:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerOutputSettings":{"type":"topic","title":"SBSDKUI2DocumentScannerOutputSettings","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings","abstract":[{"text":"Configuration of the output settings.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScanningFlow":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScanningFlow","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2DocumentScanningFlow","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanningflow","title":"SBSDKUI2DocumentScanningFlow","abstract":[{"type":"text","text":"Configuration of the document scanner screen."}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScanningFlow"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentFlowAppearanceConfiguration":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentflowappearanceconfiguration","title":"SBSDKUI2DocumentFlowAppearanceConfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2DocumentFlowAppearanceConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentFlowAppearanceConfiguration"}],"abstract":[{"text":"Configuration of the general appearance.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerTextLocalization":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization","title":"SBSDKUI2DocumentScannerTextLocalization","kind":"symbol","abstract":[{"type":"text","text":"Configuration of all the strings for the standalone cropping screen."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithVersion:screen:palette:localization:appearance:outputSettings:screens:documentUuid:cleanScanningSession:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithVersion:screen:palette:localization:appearance:outputSettings:screens:documentUuid:cleanScanningSession:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"initWithVersion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"version"},{"kind":"text","text":" "},{"text":"screen:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"screen","kind":"internalParam"},{"kind":"text","text":" "},{"text":"palette:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Palette","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Palette","text":"SBSDKUI2Palette"},{"text":" *) ","kind":"text"},{"text":"palette","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localization:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2DocumentScannerTextLocalization","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"localization"},{"kind":"text","text":" "},{"kind":"identifier","text":"appearance:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentFlowAppearanceConfiguration","text":"SBSDKUI2DocumentFlowAppearanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"appearance","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"outputSettings:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerOutputSettings","text":"SBSDKUI2DocumentScannerOutputSettings"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"outputSettings"},{"text":" ","kind":"text"},{"kind":"identifier","text":"screens:"},{"kind":"text","text":"("},{"text":"SBSDKUI2DocumentScannerScreens","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerScreens","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerScreens"},{"kind":"text","text":" *) "},{"text":"screens","kind":"internalParam"},{"kind":"text","text":" "},{"text":"documentUuid:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentUuid"},{"text":" ","kind":"text"},{"text":"cleanScanningSession:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"cleanScanningSession","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2DocumentScannerScreens","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerScreens\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerScreens\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerScreens"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerScreens\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerScreens"}]},{"value":"SBSDKUI2Palette","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Palette\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Palette\/fragments","op":"replace","value":[{"text":"SBSDKUI2Palette","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Palette\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2Palette","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScanningFlow~1init(version:screen:palette:localization:appearance:outputSettings:screens:documentUuid:cleanScanningSession:)\/title","op":"replace","value":"initWithVersion:screen:palette:localization:appearance:outputSettings:screens:documentUuid:cleanScanningSession:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScanningFlow~1init(version:screen:palette:localization:appearance:outputSettings:screens:documentUuid:cleanScanningSession:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVersion:screen:palette:localization:appearance:outputSettings:screens:documentUuid:cleanScanningSession:"}]},{"op":"replace","value":"SBSDKUI2DocumentScannerOutputSettings","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}]},{"value":"SBSDKUI2DocumentScanningFlow","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScanningFlow\/title"},{"value":[{"text":"SBSDKUI2DocumentScanningFlow","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScanningFlow\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScanningFlow\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentScanningFlow","kind":"identifier"}]},{"op":"replace","value":"SBSDKUI2DocumentFlowAppearanceConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration\/fragments","value":[{"text":"SBSDKUI2DocumentFlowAppearanceConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2DocumentFlowAppearanceConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/title","value":"SBSDKUI2DocumentScannerTextLocalization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}