{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","navigatorTitle":[{"text":"initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerParameters(im)initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:","symbolKind":"method"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithAcceptedAngleScore:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"acceptedAngleScore","kind":"internalParam"},{"kind":"text","text":" "},{"text":"acceptedSizeScore:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"text":"acceptedSizeScore","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedBrightnessThreshold:"},{"kind":"text","text":"("},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"acceptedBrightnessThreshold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"acceptedAspectRatioScore:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"acceptedAspectRatioScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"aspectRatios:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKAspectRatio *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"aspectRatios","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignoreOrientationMismatch:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"ignoreOrientationMismatch","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerparameters\/initwithacceptedanglescore:acceptedsizescore:acceptedbrightnessthreshold:acceptedaspectratioscore:aspectratios:ignoreorientationmismatch:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerParameters"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerParameters\/initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:","interfaceLanguage":"occ"},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerParameters/initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerparameters\/initwithacceptedanglescore:acceptedsizescore:acceptedbrightnessthreshold:acceptedaspectratioscore:aspectratios:ignoreorientationmismatch:","title":"initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerParameters\/initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:","role":"symbol","abstract":[],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerParameters":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerparameters","navigatorTitle":[{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"title":"SBSDKDocumentScannerParameters","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerParameters","abstract":[{"text":"Parameters for the document scanner.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerParameters\/title","value":"SBSDKDocumentScannerParameters","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerParameters\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentScannerParameters"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerParameters\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}