{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult\/confidence"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult\/confidence"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/confidence","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The text recognition confidence."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"confidence","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult(py)confidence","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"confidence"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerResult/confidence":{"role":"symbol","title":"confidence","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The text recognition confidence."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/confidence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"confidence"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult\/confidence"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerResult":{"role":"symbol","title":"SBSDKLicensePlateScannerResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicensePlateScannerResult"}],"abstract":[{"type":"text","text":"A class describing the result of a license plate scan."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicensePlateScannerResult"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.3"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"confidence"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"confidence"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidence"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult~1confidence\/title","value":"confidence"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult~1confidence\/fragments","value":[{"kind":"identifier","text":"confidence"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult\/title","value":"SBSDKLicensePlateScannerResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}