{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants\/aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName","interfaceLanguage":"swift"},"abstract":[{"text":"Normalized full name of the “ResidenceZipCode” field type in document type “AAMVA.VehicleOwnerData”.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants"]]},"metadata":{"title":"aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"symbolKind":"property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentConstants(cpy)aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Type Property","navigatorTitle":[{"text":"aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/aamvavehicleownerdataresidencezipcodefieldnormalizedname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/aamvavehicleownerdataresidencezipcodefieldnormalizedname"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentConstants/aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/aamvavehicleownerdataresidencezipcodefieldnormalizedname","abstract":[{"type":"text","text":"Normalized full name of the “ResidenceZipCode” field type in document type “AAMVA.VehicleOwnerData”."}],"role":"symbol","navigatorTitle":[{"text":"aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName","kind":"identifier"}],"title":"aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants\/aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 6.1.0"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentConstants":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"title":"SBSDKBarcodeDocumentConstants"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants~1aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants~1aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName\/fragments","value":[{"kind":"identifier","text":"aamvaVehicleOwnerDataResidenceZipCodeFieldNormalizedName"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/title","value":"SBSDKBarcodeDocumentConstants"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/fragments","value":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}]},{"value":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/navigatorTitle","op":"replace"}]}]}