{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants\/aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentConstants(cpy)aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/aamvavehicleownerdatafirstownernamefieldnormalizedname"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/aamvavehicleownerdatafirstownernamefieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Normalized full name of the “FirstOwnerName” field type in document type “AAMVA.VehicleOwnerData”.","type":"text"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentConstants/aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/aamvavehicleownerdatafirstownernamefieldnormalizedname","role":"symbol","abstract":[{"text":"Normalized full name of the “FirstOwnerName” field type in document type “AAMVA.VehicleOwnerData”.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants\/aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName","navigatorTitle":[{"text":"aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName","kind":"identifier"}],"kind":"symbol","type":"topic","title":"aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","kind":"symbol","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentConstants":{"type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants","abstract":[],"role":"symbol","title":"SBSDKBarcodeDocumentConstants","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants~1aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants~1aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName\/fragments","op":"replace","value":[{"kind":"identifier","text":"aamvaVehicleOwnerDataFirstOwnerNameFieldNormalizedName"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/title","op":"replace","value":"SBSDKBarcodeDocumentConstants"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}