{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/aamvavehicledatabodystylefieldnormalizedname"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/aamvavehicledatabodystylefieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants"]]},"kind":"symbol","sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"aamvaVehicleDataBodyStyleFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"aamvaVehicleDataBodyStyleFieldNormalizedName","roleHeading":"Type Property","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentConstants(cpy)aamvaVehicleDataBodyStyleFieldNormalizedName","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"aamvaVehicleDataBodyStyleFieldNormalizedName"}]},"abstract":[{"type":"text","text":"Normalized full name of the “BodyStyle” field type in document type “AAMVA.VehicleData”."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants\/aamvaVehicleDataBodyStyleFieldNormalizedName","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaVehicleDataBodyStyleFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentConstants":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants","title":"SBSDKBarcodeDocumentConstants","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentConstants/aamvaVehicleDataBodyStyleFieldNormalizedName":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaVehicleDataBodyStyleFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/aamvavehicledatabodystylefieldnormalizedname","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants\/aamvaVehicleDataBodyStyleFieldNormalizedName","title":"aamvaVehicleDataBodyStyleFieldNormalizedName","role":"symbol","type":"topic","abstract":[{"text":"Normalized full name of the “BodyStyle” field type in document type “AAMVA.VehicleData”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"aamvaVehicleDataBodyStyleFieldNormalizedName"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"op":"replace","value":"aamvaVehicleDataBodyStyleFieldNormalizedName","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"aamvaVehicleDataBodyStyleFieldNormalizedName","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"aamvaVehicleDataBodyStyleFieldNormalizedName"},{"text":";","kind":"text"}]}]}},{"value":"SBSDKBarcodeDocumentConstants","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/fragments","value":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants~1aamvaVehicleDataBodyStyleFieldNormalizedName\/title","value":"aamvaVehicleDataBodyStyleFieldNormalizedName"},{"value":[{"text":"aamvaVehicleDataBodyStyleFieldNormalizedName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants~1aamvaVehicleDataBodyStyleFieldNormalizedName\/fragments"}]}]}