{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Normalized full name of the “FirstNonConsecutiveBaggageTagLicensePlateNumber” field type in document type “BoardingPass.Leg”.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants"]]},"metadata":{"navigatorTitle":[{"text":"boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","kind":"identifier"}],"title":"boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentConstants(cpy)boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/boardingpasslegfirstnonconsecutivebaggagetaglicenseplatenumberfieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/boardingpasslegfirstnonconsecutivebaggagetaglicenseplatenumberfieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants\/boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName"},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentConstants":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants","title":"SBSDKBarcodeDocumentConstants","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentConstants/boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName":{"role":"symbol","type":"topic","title":"boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","kind":"symbol","abstract":[{"type":"text","text":"Normalized full name of the “FirstNonConsecutiveBaggageTagLicensePlateNumber” field type in document type “BoardingPass.Leg”."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/boardingpasslegfirstnonconsecutivebaggagetaglicenseplatenumberfieldnormalizedname","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants\/boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/title","value":"SBSDKBarcodeDocumentConstants"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants~1boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName\/title","value":"boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants~1boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName\/fragments","value":[{"kind":"identifier","text":"boardingPassLegFirstNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName"}]}]}]}