{"abstract":[{"text":"Normalized full name of the “FinalPayeeCountry” field type in document type “SwissQR”.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/swissqrfinalpayeecountryfieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/swissqrfinalpayeecountryfieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"swissQRFinalPayeeCountryFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants\/swissQRFinalPayeeCountryFieldNormalizedName"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants"]]},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentConstants(cpy)swissQRFinalPayeeCountryFieldNormalizedName","roleHeading":"Type Property","symbolKind":"property","title":"swissQRFinalPayeeCountryFieldNormalizedName","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"swissQRFinalPayeeCountryFieldNormalizedName"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"swissQRFinalPayeeCountryFieldNormalizedName","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentConstants":{"navigatorTitle":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants","kind":"symbol","abstract":[],"title":"SBSDKBarcodeDocumentConstants","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentConstants/swissQRFinalPayeeCountryFieldNormalizedName":{"navigatorTitle":[{"text":"swissQRFinalPayeeCountryFieldNormalizedName","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/swissqrfinalpayeecountryfieldnormalizedname","abstract":[{"type":"text","text":"Normalized full name of the “FinalPayeeCountry” field type in document type “SwissQR”."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"swissQRFinalPayeeCountryFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants\/swissQRFinalPayeeCountryFieldNormalizedName","title":"swissQRFinalPayeeCountryFieldNormalizedName","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"swissQRFinalPayeeCountryFieldNormalizedName"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"swissQRFinalPayeeCountryFieldNormalizedName","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"swissQRFinalPayeeCountryFieldNormalizedName"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/title","op":"replace","value":"SBSDKBarcodeDocumentConstants"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}]},{"value":"swissQRFinalPayeeCountryFieldNormalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants~1swissQRFinalPayeeCountryFieldNormalizedName\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants~1swissQRFinalPayeeCountryFieldNormalizedName\/fragments","value":[{"kind":"identifier","text":"swissQRFinalPayeeCountryFieldNormalizedName"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}