{"sections":[],"abstract":[{"type":"text","text":"Legacy mode. Very fast, significantly less accurate. Doesn’t support all barcode types."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/legacy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/legacy"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"legacy","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineModeLegacy"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeScannerEngineMode@SBSDKBarcodeScannerEngineModeLegacy","roleHeading":"Case","role":"symbol","title":"SBSDKBarcodeScannerEngineMode.legacy","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"legacy","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/legacy","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode/legacy":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/legacy","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineModeLegacy"}],"abstract":[{"type":"text","text":"Legacy mode. Very fast, significantly less accurate. Doesn’t support all barcode types."}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"legacy"}],"role":"symbol","title":"SBSDKBarcodeScannerEngineMode.legacy","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/legacy","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode":{"title":"SBSDKBarcodeScannerEngineMode","role":"symbol","abstract":[{"text":"The engine mode for barcode scanning.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKBarcodeScannerEngineModeLegacy"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineModeLegacy"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineModeLegacy"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1legacy\/title","op":"replace","value":"SBSDKBarcodeScannerEngineModeLegacy"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1legacy\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineModeLegacy"}]},{"op":"replace","value":"SBSDKBarcodeScannerEngineMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}