{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerForm"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerForm\/type1c","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerform\/type1c"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerform\/type1c"]}],"abstract":[{"type":"text","text":"Type 1C."}],"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type1c","kind":"identifier"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerFormType1c","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerForm@SBSDKMedicalCertificateRecognizerFormType1c","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKMedicalCertificateRecognizerForm.type1c"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"type1c"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerForm/type1c":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"type1c"}],"title":"SBSDKMedicalCertificateRecognizerForm.type1c","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerForm\/type1c","abstract":[{"type":"text","text":"Type 1C."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerFormType1c"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerform\/type1c","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerForm":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerForm","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerform","kind":"symbol","title":"SBSDKMedicalCertificateRecognizerForm","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerForm","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The form type of a recognized medical certificate.","type":"text"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerForm","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKMedicalCertificateRecognizerFormType1c","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateRecognizerFormType1c","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerFormType1c"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKMedicalCertificateRecognizerFormType1c","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm~1type1c\/title","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateRecognizerFormType1c","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm~1type1c\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateRecognizerForm","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm\/title"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerForm"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerForm"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm\/navigatorTitle"}]}]}