{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescanner\/detectbarcodes(on:orientation:in:)-ab0w"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescanner\/detectbarcodes(on:orientation:in:)-ab0w"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Search and decode specified types of barcodes on given image."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanner\/detectBarCodes(on:orientation:in:)-ab0w"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(detectBarCodesOnImage:orientation:inRect:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectBarCodes"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"image"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":" "},{"text":"videoOrientation","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AVCaptureVideoOrientation","kind":"typeIdentifier","text":"AVCaptureVideoOrientation"},{"kind":"text","text":", "},{"text":"in","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"rect"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult","kind":"typeIdentifier","text":"SBSDKBarcodeScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult"},{"kind":"text","text":"]?"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The image where search is to be done.","type":"text"}],"type":"paragraph"}],"name":"image"},{"name":"videoOrientation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Video frame orientation. Should be the orientation that the device currently has, not actual image orientation."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Rectangle in image coordinates in which to perform the search. Must be within the image frame."}]}],"name":"rect"}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"List of found barcodes."}],"type":"paragraph"}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This function is intended to be used use with live detection."},{"type":"text","text":" "},{"type":"text","text":"Video stream from device returns a rotated image, so for example for portrait device orientation, every frame returned will be in landscape left orientation."},{"type":"text","text":" "},{"text":"This function handles these orientation differences, so you shouldn’t fix or rotate the input image.","type":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanner"]]},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"title":"detectBarCodes(on:orientation:in:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"detectBarCodes","kind":"identifier"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"SBSDKBarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult"},{"text":"]?","kind":"text"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScanner(im)detectBarCodesOnImage:orientation:inRect:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"detectBarCodesOnImage:orientation:inRect:"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult":{"abstract":[{"text":"This class encapsulates the result of a barcode detection.","type":"text"}],"kind":"symbol","title":"SBSDKBarcodeScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult","navigatorTitle":[{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanner":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanner","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScanner"}],"title":"SBSDKBarcodeScanner","type":"topic","abstract":[{"text":"Creates an ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanner","isActive":true},{"text":" with no frame accumulator for detecting all supported barcode types.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanner","kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeScanner","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanner/detectBarCodes(on:orientation:in:)-ab0w":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanner\/detectBarCodes(on:orientation:in:)-ab0w","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectBarCodes","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> ["},{"text":"SBSDKBarcodeScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult"},{"text":"]?","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"detectBarCodesOnImage:orientation:inRect:"}],"title":"detectBarCodes(on:orientation:in:)","abstract":[{"type":"text","text":"Search and decode specified types of barcodes on given image."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanner\/detectbarcodes(on:orientation:in:)-ab0w"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"detectBarCodesOnImage:orientation:inRect:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"detectBarCodesOnImage:orientation:inRect:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBarcodeScannerResult *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"detectBarCodesOnImage:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":" "},{"text":"orientation:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@AVCaptureVideoOrientation","kind":"typeIdentifier","text":"AVCaptureVideoOrientation"},{"text":") ","kind":"text"},{"text":"videoOrientation","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"inRect:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"rect"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The image where search is to be done.","type":"text"}]}],"name":"image"},{"name":"videoOrientation","content":[{"inlineContent":[{"text":"Video frame orientation. Should be the orientation that the device currently has, not actual image orientation.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Rectangle in image coordinates in which to perform the search. Must be within the image frame.","type":"text"}]}],"name":"rect"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"List of found barcodes."}]}],"kind":"content"}},{"value":"SBSDKBarcodeScannerResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}]},{"op":"replace","value":"SBSDKBarcodeScanner","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanner\/title"},{"value":[{"text":"SBSDKBarcodeScanner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanner\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScanner"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanner\/navigatorTitle"},{"value":"detectBarCodesOnImage:orientation:inRect:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanner~1detectBarCodes(on:orientation:in:)-ab0w\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanner~1detectBarCodes(on:orientation:in:)-ab0w\/fragments","value":[{"kind":"text","text":"- "},{"text":"detectBarCodesOnImage:orientation:inRect:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}