{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate\/licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Informs the delegate that a license plate has been recognized successfully.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"licensePlateScannerViewController"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController","kind":"typeIdentifier","text":"SBSDKLicensePlateScannerViewController"},{"kind":"text","text":", "},{"text":"didRecognizeLicensePlate","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"licensePlateResult"},{"kind":"text","text":": "},{"text":"SBSDKLicensePlateScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"image"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","isActive":true,"type":"reference"},{"text":" instance that detected\/recognized the license plate.","type":"text"}]}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The result of the detection or recognition.","type":"text"}]}],"name":"licensePlateResult"},{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The original image where the license plate has been detected on."}]}]}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"licensePlateScannerViewController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController","text":"SBSDKLicensePlateScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didRecognizeLicensePlate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKLicensePlateScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":")"}],"required":true,"navigatorTitle":[{"text":"licensePlateScannerViewController:didRecognizeLicensePlate:on:","kind":"identifier"}],"symbolKind":"method","title":"licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKLicensePlateScannerViewControllerDelegate(im)licensePlateScannerViewController:didRecognizeLicensePlate:on:","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontrollerdelegate\/licenseplatescannerviewcontroller(_:didrecognizelicenseplate:on:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontrollerdelegate\/licenseplatescannerviewcontroller(_:didrecognizelicenseplate:on:)"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewController":{"kind":"symbol","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to scan for license plates with the camera.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKLicensePlateScannerViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKLicensePlateScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","title":"SBSDKLicensePlateScannerViewController","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewControllerDelegate/licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)":{"abstract":[{"text":"Informs the delegate that a license plate has been recognized successfully.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate\/licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)","navigatorTitle":[{"kind":"identifier","text":"licensePlateScannerViewController:didRecognizeLicensePlate:on:"}],"required":true,"title":"licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"licensePlateScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKLicensePlateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRecognizeLicensePlate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult","text":"SBSDKLicensePlateScannerResult"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontrollerdelegate\/licenseplatescannerviewcontroller(_:didrecognizelicenseplate:on:)","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewControllerDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicensePlateScannerViewControllerDelegate"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontrollerdelegate","navigatorTitle":[{"text":"SBSDKLicensePlateScannerViewControllerDelegate","kind":"identifier"}],"abstract":[{"text":"The delegate protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","title":"SBSDKLicensePlateScannerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerResult":{"role":"symbol","title":"SBSDKLicensePlateScannerResult","abstract":[{"text":"A class describing the result of a license plate scan.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicensePlateScannerResult"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicensePlateScannerResult"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"licensePlateScannerViewController:didRecognizeLicensePlate:on:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"licensePlateScannerViewController:didRecognizeLicensePlate:on:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"licensePlateScannerViewController:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController","kind":"typeIdentifier","text":"SBSDKLicensePlateScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didRecognizeLicensePlate:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult","text":"SBSDKLicensePlateScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"licensePlateResult","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"on:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"image"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"controller","content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","isActive":true},{"type":"text","text":" instance that detected\/recognized the license plate."}],"type":"paragraph"}]},{"name":"licensePlateResult","content":[{"inlineContent":[{"type":"text","text":"The result of the detection or recognition."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The original image where the license plate has been detected on."}],"type":"paragraph"}],"name":"image"}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/title","value":"SBSDKLicensePlateScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerViewController"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKLicensePlateScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate~1licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)\/title","value":"licensePlateScannerViewController:didRecognizeLicensePlate:on:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate~1licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"licensePlateScannerViewController:didRecognizeLicensePlate:on:","kind":"identifier"}]},{"value":"SBSDKLicensePlateScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerViewControllerDelegate"}]},{"value":[{"text":"SBSDKLicensePlateScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate\/navigatorTitle","op":"replace"},{"op":"replace","value":"SBSDKLicensePlateScannerResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult\/title"},{"value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult\/navigatorTitle","value":[{"text":"SBSDKLicensePlateScannerResult","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}