{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontrollerdelegate\/licenseplatescannerviewcontrollershouldrecognize(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontrollerdelegate\/licenseplatescannerviewcontrollershouldrecognize(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate\/licensePlateScannerViewControllerShouldRecognize(_:)"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKLicensePlateScannerViewControllerDelegate(im)licensePlateScannerViewControllerShouldRecognize:","title":"licensePlateScannerViewControllerShouldRecognize(_:)","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"licensePlateScannerViewControllerShouldRecognize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKLicensePlateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"licensePlateScannerViewControllerShouldRecognize:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","required":true},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate"]]},"abstract":[{"type":"text","text":"Asks the delegate whether the next video frame should be scanned or not."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licensePlateScannerViewControllerShouldRecognize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController","text":"SBSDKLicensePlateScannerViewController"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}]},{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","type":"reference"},{"type":"text","text":" that wants to scan the video frame."}]}]}]},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":", if you want to scan the next video frame, "},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise."}]}],"kind":"content"},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Use to skip frames or pause scanning for a while."},{"type":"text","text":" "},{"type":"text","text":"Optional."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewControllerDelegate":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicensePlateScannerViewControllerDelegate"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicensePlateScannerViewControllerDelegate"}],"title":"SBSDKLicensePlateScannerViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontrollerdelegate","abstract":[{"text":"The delegate protocol for the ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","isActive":true},{"type":"text","text":"."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewControllerDelegate/licensePlateScannerViewControllerShouldRecognize(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontrollerdelegate\/licenseplatescannerviewcontrollershouldrecognize(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"licensePlateScannerViewControllerShouldRecognize"},{"kind":"text","text":"("},{"text":"SBSDKLicensePlateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"licensePlateScannerViewControllerShouldRecognize(_:)","navigatorTitle":[{"text":"licensePlateScannerViewControllerShouldRecognize:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate\/licensePlateScannerViewControllerShouldRecognize(_:)","required":true,"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Asks the delegate whether the next video frame should be scanned or not."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewController":{"title":"SBSDKLicensePlateScannerViewController","navigatorTitle":[{"text":"SBSDKLicensePlateScannerViewController","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicensePlateScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to scan for license plates with the camera.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"licensePlateScannerViewControllerShouldRecognize:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"licensePlateScannerViewControllerShouldRecognize:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"licensePlateScannerViewControllerShouldRecognize:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","text":"SBSDKLicensePlateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","isActive":true,"type":"reference"},{"type":"text","text":" that wants to scan the video frame."}],"type":"paragraph"}],"name":"controller"}]}},{"op":"replace","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"True"},{"text":", if you want to scan the next video frame, ","type":"text"},{"code":"False","type":"codeVoice"},{"text":" otherwise.","type":"text"}]}]},"path":"\/primaryContentSections\/2"},{"value":"SBSDKLicensePlateScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerViewControllerDelegate"}],"op":"replace"},{"value":[{"text":"SBSDKLicensePlateScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate~1licensePlateScannerViewControllerShouldRecognize(_:)\/title","op":"replace","value":"licensePlateScannerViewControllerShouldRecognize:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate~1licensePlateScannerViewControllerShouldRecognize(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"licensePlateScannerViewControllerShouldRecognize:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/title","value":"SBSDKLicensePlateScannerViewController"},{"value":[{"text":"SBSDKLicensePlateScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/navigatorTitle"}]}]}