{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scannedImageQualityResult","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsEvent","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAnalyticsEvent","text":"SBSDKAnalyticsEvent","kind":"typeIdentifier"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsEventFactory\/scannedImageQualityResult"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsEventFactory"]]},"sections":[],"metadata":{"symbolKind":"property","role":"symbol","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scannedImageQualityResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKAnalyticsEvent","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAnalyticsEvent","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAnalyticsEventFactory(cpy)scannedImageQualityResult","title":"scannedImageQualityResult","navigatorTitle":[{"text":"scannedImageQualityResult","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticseventfactory\/scannedimagequalityresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticseventfactory\/scannedimagequalityresult"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A predefined analytics event."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAnalyticsEvent":{"title":"SBSDKAnalyticsEvent","abstract":[{"text":"The event that is being tracked.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsEvent","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticsevent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAnalyticsEvent"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAnalyticsEvent"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.3"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAnalyticsEventFactory/scannedImageQualityResult":{"title":"scannedImageQualityResult","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsEventFactory\/scannedImageQualityResult","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scannedImageQualityResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKAnalyticsEvent","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAnalyticsEvent","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"scannedImageQualityResult","kind":"identifier"}],"abstract":[{"type":"text","text":"A predefined analytics event."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticseventfactory\/scannedimagequalityresult"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAnalyticsEventFactory":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticseventfactory","abstract":[{"type":"text","text":"A predefined analytics event."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAnalyticsEventFactory"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKAnalyticsEventFactory"}],"title":"SBSDKAnalyticsEventFactory","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsEventFactory"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"scannedImageQualityResult","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"scannedImageQualityResult","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAnalyticsEvent","text":"SBSDKAnalyticsEvent","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsEvent"},{"text":" * ","kind":"text"},{"text":"scannedImageQualityResult","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKAnalyticsEvent","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsEvent\/title","op":"replace"},{"value":[{"text":"SBSDKAnalyticsEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsEvent\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAnalyticsEvent"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsEvent\/navigatorTitle","op":"replace"},{"value":"scannedImageQualityResult","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsEventFactory~1scannedImageQualityResult\/title","op":"replace"},{"value":[{"text":"scannedImageQualityResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsEventFactory~1scannedImageQualityResult\/fragments","op":"replace"},{"value":"SBSDKAnalyticsEventFactory","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsEventFactory\/title","op":"replace"},{"value":[{"text":"SBSDKAnalyticsEventFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsEventFactory\/fragments","op":"replace"},{"value":[{"text":"SBSDKAnalyticsEventFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsEventFactory\/navigatorTitle","op":"replace"}]}]}