{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfobox\/init(quad:fields:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfobox\/init(quad:fields:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoBox\/init(quad:fields:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoBox"]]},"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificatePatientInfoBox(im)initWithQuad:fields:","symbolKind":"init","navigatorTitle":[{"text":"initWithQuad:fields:","kind":"identifier"}],"roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"title":"init(quad:fields:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"quad","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"fields"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificatePatientInfoField","text":"SBSDKMedicalCertificatePatientInfoField"},{"text":"])","kind":"text"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"quad","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"fields","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SBSDKMedicalCertificatePatientInfoField","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificatePatientInfoField"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoBox":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfobox","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoBox","navigatorTitle":[{"text":"SBSDKMedicalCertificatePatientInfoBox","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Patient information box."}],"role":"symbol","title":"SBSDKMedicalCertificatePatientInfoBox","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoBox"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoBox/init(quad:fields:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"quad"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"fields"},{"text":": [","kind":"text"},{"text":"SBSDKMedicalCertificatePatientInfoField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificatePatientInfoField"},{"text":"])","kind":"text"}],"role":"symbol","type":"topic","title":"init(quad:fields:)","navigatorTitle":[{"kind":"identifier","text":"initWithQuad:fields:"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfobox\/init(quad:fields:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoBox\/init(quad:fields:)","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoField":{"kind":"symbol","title":"SBSDKMedicalCertificatePatientInfoField","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoField"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificatePatientInfoField","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoField","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofield","abstract":[{"type":"text","text":"Patient information field."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithQuad:fields:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithQuad:fields:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"text":"initWithQuad:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"quad","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fields:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<SBSDKMedicalCertificatePatientInfoField *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"fields","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoBox\/title","value":"SBSDKMedicalCertificatePatientInfoBox"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificatePatientInfoBox","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoBox\/fragments"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificatePatientInfoBox","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoBox\/navigatorTitle"},{"op":"replace","value":"initWithQuad:fields:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoBox~1init(quad:fields:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoBox~1init(quad:fields:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithQuad:fields:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoField\/title","op":"replace","value":"SBSDKMedicalCertificatePatientInfoField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoField\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoField"}]},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoField"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoField\/navigatorTitle","op":"replace"}]}]}