{"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"ScanbotSDK"}],"title":"Equatable Implementations"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningMode"]]},"sections":[],"kind":"article","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanningmode\/equatable-implementations"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningMode\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningMode\/!=(_:_:)"],"anchor":"Operators","generated":true}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningMode":{"kind":"symbol","title":"SBSDKCreditCardScanningMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKCreditCardScanningMode","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKCreditCardScanningMode","kind":"identifier"}],"abstract":[{"text":"The scanning mode.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningMode/!=(_:_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningMode\/!=(_:_:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningmode\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"!=(_:_:)","abstract":[],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningMode\/title","value":"SBSDKCreditCardScanningMode"},{"value":[{"kind":"identifier","text":"SBSDKCreditCardScanningMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKCreditCardScanningMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}