{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureCorrupted","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/failureCorrupted"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"No license active. The set license was unreadable or has an invalid format."}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus\/failurecorrupted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus\/failurecorrupted"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureCorrupted"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKLicenseStatus@SBSDKLicenseStatusFailureCorrupted","roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureCorrupted","kind":"identifier"}],"title":"SBSDKLicenseStatus.failureCorrupted"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus/failureCorrupted":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/failureCorrupted","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus\/failurecorrupted","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureCorrupted"}],"role":"symbol","title":"SBSDKLicenseStatus.failureCorrupted","type":"topic","abstract":[{"text":"No license active. The set license was unreadable or has an invalid format.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureCorrupted"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus","navigatorTitle":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"type":"topic","abstract":[{"text":"Status of the license plate scanner.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseStatus","kind":"identifier"}],"title":"SBSDKLicenseStatus","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKLicenseStatusFailureCorrupted"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureCorrupted"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKLicenseStatusFailureCorrupted","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1failureCorrupted\/title","op":"replace","value":"SBSDKLicenseStatusFailureCorrupted"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1failureCorrupted\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureCorrupted"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus\/title","op":"replace","value":"SBSDKLicenseStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatus"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus\/navigatorTitle","op":"replace","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}]}]}]}