{"metadata":{"platforms":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelButtonTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"modules":[{"name":"ScanbotSDK"}],"title":"cancelButtonTitle","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerTextConfiguration(py)cancelButtonTitle","navigatorTitle":[{"kind":"identifier","text":"cancelButtonTitle"}],"symbolKind":"property","roleHeading":"Instance Property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerTextConfiguration\/cancelButtonTitle"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerTextConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannertextconfiguration\/cancelbuttontitle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannertextconfiguration\/cancelbuttontitle"]}],"abstract":[{"text":"String being displayed on the cancel button.","type":"text"}],"kind":"symbol","deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}],"type":"paragraph"}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerTextConfiguration/cancelButtonTitle":{"role":"symbol","title":"cancelButtonTitle","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerTextConfiguration\/cancelButtonTitle","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannertextconfiguration\/cancelbuttontitle","navigatorTitle":[{"kind":"identifier","text":"cancelButtonTitle"}],"abstract":[{"text":"String being displayed on the cancel button.","type":"text"}],"deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelButtonTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerTextConfiguration":{"type":"topic","deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerTextConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannertextconfiguration","title":"SBSDKUIBarcodesBatchScannerTextConfiguration","abstract":[{"type":"text","text":"The configuration for the textual contents of the RTU-UI batch barcode scanner."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerTextConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerTextConfiguration","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"cancelButtonTitle","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"cancelButtonTitle","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"cancelButtonTitle","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"cancelButtonTitle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerTextConfiguration~1cancelButtonTitle\/title"},{"value":[{"text":"cancelButtonTitle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerTextConfiguration~1cancelButtonTitle\/fragments"},{"value":"SBSDKUIBarcodesBatchScannerTextConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerTextConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerTextConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerTextConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerTextConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerTextConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}