{"abstract":[{"type":"text","text":"Sets the quality of JPEG compression used to encode images when hibernating. The default is 80."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setHibernationJpegQuality"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"quality"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/setHibernationJpegQuality(quality:)"},"metadata":{"title":"setHibernationJpegQuality(quality:)","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","navigatorTitle":[{"text":"setHibernationJpegQualityWithQuality:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef(cm)setHibernationJpegQualityWithQuality:","role":"symbol","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setHibernationJpegQuality"},{"text":"(","kind":"text"},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimageref\/sethibernationjpegquality(quality:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimageref\/sethibernationjpegquality(quality:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/setHibernationJpegQuality(quality:)":{"navigatorTitle":[{"kind":"identifier","text":"setHibernationJpegQualityWithQuality:"}],"kind":"symbol","title":"setHibernationJpegQuality(quality:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setHibernationJpegQuality","kind":"identifier"},{"text":"(","kind":"text"},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/sethibernationjpegquality(quality:)","abstract":[{"type":"text","text":"Sets the quality of JPEG compression used to encode images when hibernating. The default is 80."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/setHibernationJpegQuality(quality:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef":{"kind":"symbol","type":"topic","title":"SBSDKImageRef","url":"\/documentation\/scanbotsdk\/sbsdkimageref","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","role":"symbol","abstract":[{"text":"Image ref class.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKImageRef","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRef"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"setHibernationJpegQualityWithQuality:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setHibernationJpegQualityWithQuality:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setHibernationJpegQualityWithQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"quality"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"setHibernationJpegQualityWithQuality:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1setHibernationJpegQuality(quality:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1setHibernationJpegQuality(quality:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"setHibernationJpegQualityWithQuality:","kind":"identifier"}]},{"value":"SBSDKImageRef","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/fragments","op":"replace","value":[{"text":"SBSDKImageRef","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/navigatorTitle","value":[{"text":"SBSDKImageRef","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}