{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName\/dateOfIssuance"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName"]]},"kind":"symbol","abstract":[{"text":"The field describes the issuing date.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/dateofissuance"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/dateofissuance"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"dateOfIssuance","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"title":"SBSDKMachineReadableZoneRecognizerFieldName.dateOfIssuance","externalID":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerFieldName@SBSDKMachineReadableZoneRecognizerFieldNameDateOfIssuance","symbolKind":"case","role":"symbol","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"dateOfIssuance","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldNameDateOfIssuance"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerFieldName/dateOfIssuance":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName\/dateOfIssuance","type":"topic","title":"SBSDKMachineReadableZoneRecognizerFieldName.dateOfIssuance","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/dateofissuance","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateOfIssuance"}],"abstract":[{"text":"The field describes the issuing date.","type":"text"}],"navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerFieldNameDateOfIssuance","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerFieldName":{"title":"SBSDKMachineReadableZoneRecognizerFieldName","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerFieldName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerFieldName","kind":"identifier"}],"abstract":[{"text":"Type classifiers for machine-readable-zone fields.","type":"text"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKMachineReadableZoneRecognizerFieldNameDateOfIssuance","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"SBSDKMachineReadableZoneRecognizerFieldNameDateOfIssuance","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"SBSDKMachineReadableZoneRecognizerFieldNameDateOfIssuance","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName~1dateOfIssuance\/title","value":"SBSDKMachineReadableZoneRecognizerFieldNameDateOfIssuance"},{"value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldNameDateOfIssuance"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName~1dateOfIssuance\/fragments"},{"value":"SBSDKMachineReadableZoneRecognizerFieldName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName\/title"},{"value":[{"text":"SBSDKMachineReadableZoneRecognizerFieldName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}