{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldNameIssuingStateOrOrganization"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerFieldName@SBSDKMachineReadableZoneRecognizerFieldNameIssuingStateOrOrganization","role":"symbol","roleHeading":"Case","symbolKind":"case","title":"SBSDKMachineReadableZoneRecognizerFieldName.issuingStateOrOrganization"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName\/issuingStateOrOrganization"},"kind":"symbol","abstract":[{"type":"text","text":"The field describes the issuing state or organization."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/issuingstateororganization"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/issuingstateororganization"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingStateOrOrganization"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerFieldName":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMachineReadableZoneRecognizerFieldName","kind":"identifier"}],"title":"SBSDKMachineReadableZoneRecognizerFieldName","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname","abstract":[{"type":"text","text":"Type classifiers for machine-readable-zone fields."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerFieldName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerFieldName/issuingStateOrOrganization":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName\/issuingStateOrOrganization","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"issuingStateOrOrganization","kind":"identifier"}],"type":"topic","abstract":[{"text":"The field describes the issuing state or organization.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldNameIssuingStateOrOrganization"}],"role":"symbol","kind":"symbol","title":"SBSDKMachineReadableZoneRecognizerFieldName.issuingStateOrOrganization","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/issuingstateororganization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMachineReadableZoneRecognizerFieldNameIssuingStateOrOrganization"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldNameIssuingStateOrOrganization"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldNameIssuingStateOrOrganization"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"SBSDKMachineReadableZoneRecognizerFieldName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldName"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName~1issuingStateOrOrganization\/title","value":"SBSDKMachineReadableZoneRecognizerFieldNameIssuingStateOrOrganization"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldNameIssuingStateOrOrganization"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName~1issuingStateOrOrganization\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}