{"kind":"symbol","abstract":[{"text":"The field describes the nationality.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName\/nationality"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"nationality","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/nationality"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/nationality"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerFieldName@SBSDKMachineReadableZoneRecognizerFieldNameNationality","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"nationality","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerFieldNameNationality","kind":"identifier"}],"roleHeading":"Case","title":"SBSDKMachineReadableZoneRecognizerFieldName.nationality","symbolKind":"case"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerFieldName/nationality":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/nationality","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName\/nationality","abstract":[{"type":"text","text":"The field describes the nationality."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"nationality","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerFieldNameNationality","kind":"identifier"}],"title":"SBSDKMachineReadableZoneRecognizerFieldName.nationality"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerFieldName":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMachineReadableZoneRecognizerFieldName","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerFieldName","kind":"identifier"}],"title":"SBSDKMachineReadableZoneRecognizerFieldName","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname","role":"symbol","abstract":[{"text":"Type classifiers for machine-readable-zone fields.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKMachineReadableZoneRecognizerFieldNameNationality","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldNameNationality"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldNameNationality"}]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKMachineReadableZoneRecognizerFieldNameNationality","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName~1nationality\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName~1nationality\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerFieldNameNationality","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName\/title","value":"SBSDKMachineReadableZoneRecognizerFieldName"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldName"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName\/fragments"}]}]}