{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName\/pinCode"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The field describes the PIN number in Swiss driver license."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinCode"}],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerFieldNamePinCode","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinCode"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerFieldName@SBSDKMachineReadableZoneRecognizerFieldNamePinCode","symbolKind":"case","title":"SBSDKMachineReadableZoneRecognizerFieldName.pinCode","roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/pincode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/pincode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerFieldName":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldName"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldName"}],"abstract":[{"text":"Type classifiers for machine-readable-zone fields.","type":"text"}],"title":"SBSDKMachineReadableZoneRecognizerFieldName","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerFieldName/pinCode":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName\/pinCode","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pinCode","kind":"identifier"}],"abstract":[{"text":"The field describes the PIN number in Swiss driver license.","type":"text"}],"type":"topic","title":"SBSDKMachineReadableZoneRecognizerFieldName.pinCode","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldNamePinCode"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/pincode","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SBSDKMachineReadableZoneRecognizerFieldNamePinCode","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKMachineReadableZoneRecognizerFieldNamePinCode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKMachineReadableZoneRecognizerFieldNamePinCode","kind":"identifier"}]}]},"op":"replace"},{"op":"replace","value":"SBSDKMachineReadableZoneRecognizerFieldName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldName"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldName"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName~1pinCode\/title","op":"replace","value":"SBSDKMachineReadableZoneRecognizerFieldNamePinCode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName~1pinCode\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerFieldNamePinCode","kind":"identifier"}],"op":"replace"}]}]}