{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldNameUnknown"}],"title":"SBSDKMachineReadableZoneRecognizerFieldName.unknown","externalID":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerFieldName@SBSDKMachineReadableZoneRecognizerFieldNameUnknown","symbolKind":"case","role":"symbol","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/unknown"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName\/unknown"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName"]]},"abstract":[{"text":"Unclassified field.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerFieldName/unknown":{"abstract":[{"type":"text","text":"Unclassified field."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName\/unknown","role":"symbol","title":"SBSDKMachineReadableZoneRecognizerFieldName.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/unknown","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldNameUnknown"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerFieldName":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMachineReadableZoneRecognizerFieldName","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerFieldName","kind":"identifier"}],"title":"SBSDKMachineReadableZoneRecognizerFieldName","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname","role":"symbol","abstract":[{"text":"Type classifiers for machine-readable-zone fields.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMachineReadableZoneRecognizerFieldNameUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldNameUnknown"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKMachineReadableZoneRecognizerFieldNameUnknown","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName~1unknown\/title","op":"replace","value":"SBSDKMachineReadableZoneRecognizerFieldNameUnknown"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName~1unknown\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldNameUnknown"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName\/title","value":"SBSDKMachineReadableZoneRecognizerFieldName","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerFieldName","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}