{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MultipleScanningMode(py)countingRepeatDelay","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"countingRepeatDelay","kind":"identifier"}],"title":"countingRepeatDelay","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"countingRepeatDelay","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/countingrepeatdelay"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/countingrepeatdelay"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode"]]},"abstract":[{"type":"text","text":"Time interval in milliseconds before a barcode is counted again. 0 = no delay. The default value is 1000."},{"text":" ","type":"text"},{"text":"Default is 1000","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"countingRepeatDelay","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/countingRepeatDelay","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/countingRepeatDelay":{"role":"symbol","abstract":[{"text":"Time interval in milliseconds before a barcode is counted again. 0 = no delay. The default value is 1000.","type":"text"},{"type":"text","text":" "},{"text":"Default is 1000","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/countingrepeatdelay","title":"countingRepeatDelay","type":"topic","navigatorTitle":[{"text":"countingRepeatDelay","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/countingRepeatDelay","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"countingRepeatDelay","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode":{"type":"topic","title":"SBSDKUI2MultipleScanningMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2MultipleScanningMode"}],"abstract":[{"text":"Configuration of the mode for scanning multiple barcodes.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"countingRepeatDelay"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"countingRepeatDelay","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"countingRepeatDelay"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1countingRepeatDelay\/title","value":"countingRepeatDelay","op":"replace"},{"op":"replace","value":[{"text":"countingRepeatDelay","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1countingRepeatDelay\/fragments"},{"value":"SBSDKUI2MultipleScanningMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/fragments","value":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}