{"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:"}],"symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"countingRepeatDelay","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowEmptySubmission"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"mode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MultipleBarcodesScanningMode","text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sheet","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Sheet","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet"},{"kind":"text","text":", "},{"text":"sheetContent","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent","kind":"typeIdentifier","text":"SBSDKUI2SheetContent"},{"kind":"text","text":", "},{"text":"manualCountEditDialog","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ManualCountEditDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ManualCountEditDialog"},{"kind":"text","text":", "},{"text":"barcodeInfoMapping","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeInfoMapping","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"arOverlay"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"},{"text":")","kind":"text"}],"title":"init(countingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MultipleScanningMode(im)initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"countingRepeatDelay"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = 1000, ","kind":"text"},{"text":"allowEmptySubmission","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleBarcodesScanningMode","text":"SBSDKUI2MultipleBarcodesScanningMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MultipleBarcodesScanningMode","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2MultipleBarcodesScanningMode.counting, "},{"kind":"externalParam","text":"sheet"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet","kind":"typeIdentifier","text":"SBSDKUI2Sheet"},{"kind":"text","text":" = SBSDKUI2Sheet(mode: SBSDKUI2SheetMode.collapsedSheet,\n                                                     collapsedVisibleHeight: SBSDKUI2CollapsedVisibleHeight.small,\n                                                     listButton: SBSDKUI2BadgedButton(badgeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                          isArgb: false),\n                                                                                      badgeForegroundColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                          isArgb: false),\n                                                                                      visible: true,\n                                                                                      backgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                     isArgb: false),\n                                                                                      foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                     isArgb: false),\n                                                                                      activeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                           isArgb: false),\n                                                                                      activeForegroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                           isArgb: false))), "},{"kind":"externalParam","text":"sheetContent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent","text":"SBSDKUI2SheetContent","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent"},{"kind":"text","text":" = SBSDKUI2SheetContent(sheetColor: SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false),\n                                         dividerColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                     isArgb: false),\n                                         manualCountChangeEnabled: true,\n                                         manualCountOutlineColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                                isArgb: false),\n                                         manualCountChangeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                               isArgb: false),\n                                         title: SBSDKUI2StyledText(text: \"?multipleModeSheetTitle\",\n                                                                   color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                        isArgb: false)),\n                                         clearAllButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                     text: \"?sheetClearAllButton\",\n                                                                                     background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                    isArgb: false),\n                                                                                                                         fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                  isArgb: false),\n                                                                                                                         strokeWidth: 1.0),\n                                                                                     foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                              isArgb: false),\n                                                                                                                         useShadow: false)),\n                                         barcodeItemTitle: SBSDKUI2StyledText(visible: true,\n                                                                              text: \"BARCODE_TITLE\",\n                                                                              color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                   isArgb: false),\n                                                                              useShadow: false),\n                                         barcodeItemSubtitle: SBSDKUI2StyledText(visible: true,\n                                                                                 text: \"BARCODE_SUBTITLE\",\n                                                                                 color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                      isArgb: false),\n                                                                                 useShadow: false),\n                                         barcodeItemImageVisible: true,\n                                         submitButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                   text: \"?sheetSubmitButton\",\n                                                                                   background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                  isArgb: false),\n                                                                                                                       fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                isArgb: false),\n                                                                                                                       strokeWidth: 1.0),\n                                                                                   foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                       color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                            isArgb: false),\n                                                                                                                       useShadow: false)),\n                                         startScanningButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                          text: \"?sheetStartScanningButton\",\n                                                                                          background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                              fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                       isArgb: false),\n                                                                                                                              strokeWidth: 1.0),\n                                                                                          foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                              color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                   isArgb: false),\n                                                                                                                              useShadow: false)),\n                                         placeholderTitle: SBSDKUI2StyledText(visible: true,\n                                                                              text: \"?sheetPlaceholderTitle\",\n                                                                              color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                   isArgb: false),\n                                                                              useShadow: false),\n                                         placeholderSubtitle: SBSDKUI2StyledText(visible: true,\n                                                                                 text: \"?sheetPlaceholderSubtitle\",\n                                                                                 color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                      isArgb: false),\n                                                                                 useShadow: false),\n                                         placeholderIconBackground: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                                  isArgb: false),\n                                         placeholderIcon: SBSDKUI2IconStyle(visible: true,\n                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                 isArgb: false)),\n                                         swipeToDelete: SBSDKUI2SwipeToDelete(enabled: true,\n                                                                              backgroundColor: SBSDKUI2Color(colorString: \"?sbColorNegative\",\n                                                                                                             isArgb: false),\n                                                                              iconColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                       isArgb: false))), "},{"kind":"externalParam","text":"manualCountEditDialog"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ManualCountEditDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ManualCountEditDialog","text":"SBSDKUI2ManualCountEditDialog","kind":"typeIdentifier"},{"text":" = SBSDKUI2ManualCountEditDialog(sheetColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                            isArgb: false),\n                                                  dividerColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                              isArgb: false),\n                                                  modalOverlayColor: SBSDKUI2Color(colorString: \"?sbColorModalOverlay\",\n                                                                                   isArgb: false),\n                                                  title: SBSDKUI2StyledText(text: \"?manualCountEditDialogTitle\",\n                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                 isArgb: false)),\n                                                  info: SBSDKUI2StyledText(text: \"?manualCountEditDialogInfo\",\n                                                                           color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                isArgb: false)),\n                                                  updateButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                            text: \"?manualCountEditDialogUpdateButton\",\n                                                                                            background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                           isArgb: false),\n                                                                                                                                fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                                strokeWidth: 1.0),\n                                                                                            foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                                color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                                useShadow: false)),\n                                                  cancelButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                            text: \"?manualCountEditDialogCancelButton\",\n                                                                                            background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                           isArgb: false),\n                                                                                                                                fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                                strokeWidth: 1.0),\n                                                                                            foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                                color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                                useShadow: false)),\n                                                  clearTextButton: SBSDKUI2IconStyle(visible: true,\n                                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                          isArgb: false))), ","kind":"text"},{"kind":"externalParam","text":"barcodeInfoMapping"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping","text":"SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping"},{"text":" = SBSDKUI2BarcodeInfoMapping(sheetColor: SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false),\n                                               dividerColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                           isArgb: false),\n                                               modalOverlayColor: SBSDKUI2Color(colorString: \"?sbColorModalOverlay\",\n                                                                                isArgb: false),\n                                               loadingMessage: SBSDKUI2StyledText(text: \"?barcodeInfoMappingLoadingMessage\",\n                                                                                  color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                       isArgb: false)),\n                                               errorState: SBSDKUI2BarcodeItemErrorState(title: SBSDKUI2StyledText(text: \"?barcodeInfoMappingErrorStateTitle\",\n                                                                                                                   color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                        isArgb: false)),\n                                                                                         subtitle: SBSDKUI2StyledText(text: \"?barcodeInfoMappingErrorStateSubtitle\",\n                                                                                                                      color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                                                           isArgb: false)),\n                                                                                         retryButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                                                                  text: \"?barcodeInfoMappingErrorStateRetryButton\",\n                                                                                                                                  background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                                                                 isArgb: false),\n                                                                                                                                                                      fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                                                               isArgb: false),\n                                                                                                                                                                      strokeWidth: 1.0),\n                                                                                                                                  foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                                                                      color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                                                           isArgb: false),\n                                                                                                                                                                      useShadow: false)),\n                                                                                         cancelButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                                                                   text: \"?barcodeInfoMappingErrorStateCancelButton\",\n                                                                                                                                   background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                                  isArgb: false),\n                                                                                                                                                                       fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                                isArgb: false),\n                                                                                                                                                                       strokeWidth: 1.0),\n                                                                                                                                   foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                                                                       color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                                                            isArgb: false),\n                                                                                                                                                                       useShadow: false)))), ","kind":"text"},{"text":"arOverlay","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration","text":"SBSDKUI2ArOverlayGeneralConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration"},{"text":" = SBSDKUI2ArOverlayGeneralConfiguration(visible: false,\n                                                                                                         counterBadge: SBSDKUI2BadgeStyle(visible: true,\n                                                                                                                                          background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#FF000000\",\n                                                                                                                                                                                                         isArgb: false),\n                                                                                                                                                                              fillColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                       isArgb: false),\n                                                                                                                                                                              strokeWidth: 0.0),\n                                                                                                                                          foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                                                         isArgb: false)),\n                                                                                                         automaticSelectionEnabled: false,\n                                                                                                         barcodeItemInfoPosition: SBSDKUI2BarcodeItemInfoPosition\n                                                                                                             .below,\n                                                                                                         polygon: SBSDKUI2ArOverlayPolygonConfiguration(visible: true,\n                                                                                                                                                        deselected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                                                                                                                    isArgb: false),\n                                                                                                                                                                                         fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                                                  isArgb: false),\n                                                                                                                                                                                         strokeWidth: 3.0,\n                                                                                                                                                                                         cornerRadius: 5.0),\n                                                                                                                                                        selected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                                  isArgb: false),\n                                                                                                                                                                                       fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                                                isArgb: false),\n                                                                                                                                                                                       strokeWidth: 3.0,\n                                                                                                                                                                                       cornerRadius: 5.0)),\n                                                                                                         barcodeItemConfiguration: SBSDKUI2BarcodeItemConfiguration(imageVisible: true,\n                                                                                                                                                                    titleSelected: SBSDKUI2StyledText(text: \"BARCODE_TITLE\",\n                                                                                                                                                                                                      color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                                                                                                           isArgb: false)),\n                                                                                                                                                                    subtitleSelected: SBSDKUI2StyledText(visible: true,\n                                                                                                                                                                                                         text: \"BARCODE_SUBTITLE\",\n                                                                                                                                                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                                                                                                                                              isArgb: false),\n                                                                                                                                                                                                         useShadow: false),\n                                                                                                                                                                    titleDeselected: SBSDKUI2StyledText(visible: true,\n                                                                                                                                                                                                        text: \"BARCODE_TITLE\",\n                                                                                                                                                                                                        color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                                                                                                             isArgb: false),\n                                                                                                                                                                                                        useShadow: false),\n                                                                                                                                                                    subtitleDeselected: SBSDKUI2StyledText(text: \"BARCODE_SUBTITLE\",\n                                                                                                                                                                                                           color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                                                                                                                                                isArgb: false)),\n                                                                                                                                                                    backgroundSelected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                                                        isArgb: false),\n                                                                                                                                                                                                             fillColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                                                      isArgb: false),\n                                                                                                                                                                                                             strokeWidth: 1.0,\n                                                                                                                                                                                                             cornerRadius: 5.0),\n                                                                                                                                                                    backgroundDeselected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                                                                                                                                          isArgb: false),\n                                                                                                                                                                                                               fillColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                                                                                                                                        isArgb: false),\n                                                                                                                                                                                                               strokeWidth: 1.0,\n                                                                                                                                                                                                               cornerRadius: 5.0))))","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/init(countingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/init(countingrepeatdelay:allowemptysubmission:mode:sheet:sheetcontent:manualcounteditdialog:barcodeinfomapping:aroverlay:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/init(countingrepeatdelay:allowemptysubmission:mode:sheet:sheetcontent:manualcounteditdialog:barcodeinfomapping:aroverlay:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent","navigatorTitle":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Configuration of the list containing the barcodes that have already been scanned."}],"title":"SBSDKUI2SheetContent","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode":{"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode","title":"SBSDKUI2MultipleScanningMode","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Configuration of the mode for scanning multiple barcodes."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sheet":{"title":"SBSDKUI2Sheet","abstract":[{"type":"text","text":"Configuration of the preview mode for scanning multiple barcodes."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Sheet"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2Sheet","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet","url":"\/documentation\/scanbotsdk\/sbsdkui2sheet","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/init(countingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/init(countingrepeatdelay:allowemptysubmission:mode:sheet:sheetcontent:manualcounteditdialog:barcodeinfomapping:aroverlay:)","title":"init(countingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/init(countingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)","navigatorTitle":[{"text":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"countingRepeatDelay"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"allowEmptySubmission","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MultipleBarcodesScanningMode","text":"SBSDKUI2MultipleBarcodesScanningMode"},{"kind":"text","text":", "},{"text":"sheet","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet","text":"SBSDKUI2Sheet"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sheetContent"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent","text":"SBSDKUI2SheetContent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"manualCountEditDialog","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ManualCountEditDialog","text":"SBSDKUI2ManualCountEditDialog","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodeInfoMapping"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping"},{"kind":"text","text":", "},{"kind":"externalParam","text":"arOverlay"},{"kind":"text","text":": "},{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayGeneralConfiguration":{"kind":"symbol","title":"SBSDKUI2ArOverlayGeneralConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration","abstract":[{"text":"Configuration of the AR overlay displayed on top of barcodes in the camera preview.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleBarcodesScanningMode":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}],"abstract":[{"type":"text","text":"Configuration of the mode used for scanning multiple barcodes."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}],"kind":"symbol","title":"SBSDKUI2MultipleBarcodesScanningMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleBarcodesScanningMode","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplebarcodesscanningmode","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeInfoMapping":{"role":"symbol","title":"SBSDKUI2BarcodeInfoMapping","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeinfomapping","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the barcode data mapping."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ManualCountEditDialog":{"url":"\/documentation\/scanbotsdk\/sbsdkui2manualcounteditdialog","title":"SBSDKUI2ManualCountEditDialog","abstract":[{"type":"text","text":"Configuration of the dialog to manually edit the barcode count."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ManualCountEditDialog","navigatorTitle":[{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithCountingRepeatDelay:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"countingRepeatDelay"},{"text":" ","kind":"text"},{"text":"allowEmptySubmission:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"allowEmptySubmission","kind":"internalParam"},{"kind":"text","text":" "},{"text":"mode:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleBarcodesScanningMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MultipleBarcodesScanningMode","text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"mode","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sheet:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet","text":"SBSDKUI2Sheet","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sheet"},{"text":" ","kind":"text"},{"text":"sheetContent:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent","text":"SBSDKUI2SheetContent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sheetContent"},{"text":" ","kind":"text"},{"kind":"identifier","text":"manualCountEditDialog:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ManualCountEditDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ManualCountEditDialog","text":"SBSDKUI2ManualCountEditDialog"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"manualCountEditDialog"},{"text":" ","kind":"text"},{"text":"barcodeInfoMapping:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping","text":"SBSDKUI2BarcodeInfoMapping","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcodeInfoMapping"},{"text":" ","kind":"text"},{"text":"arOverlay:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration","text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"arOverlay","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/title","op":"replace","value":"SBSDKUI2SheetContent"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"op":"replace"},{"op":"replace","value":"SBSDKUI2MultipleScanningMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2MultipleScanningMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/navigatorTitle","value":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/title","value":"SBSDKUI2Sheet"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/fragments","value":[{"text":"SBSDKUI2Sheet","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Sheet"}]},{"value":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1init(countingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1init(countingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/title","value":"SBSDKUI2ArOverlayGeneralConfiguration","op":"replace"},{"value":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode\/title","op":"replace","value":"SBSDKUI2MultipleBarcodesScanningMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode\/fragments","value":[{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode\/navigatorTitle"},{"value":"SBSDKUI2BarcodeInfoMapping","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ManualCountEditDialog\/title","op":"replace","value":"SBSDKUI2ManualCountEditDialog"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ManualCountEditDialog\/fragments","value":[{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ManualCountEditDialog\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ManualCountEditDialog"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}