{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"countingRepeatDelay"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = 1000, ","kind":"text"},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2MultipleBarcodesScanningMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleBarcodesScanningMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MultipleBarcodesScanningMode"},{"text":" = SBSDKUI2MultipleBarcodesScanningMode.counting, ","kind":"text"},{"kind":"externalParam","text":"sheet"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet","text":"SBSDKUI2Sheet"},{"kind":"text","text":" = SBSDKUI2Sheet(mode: SBSDKUI2SheetMode.collapsedSheet,\n                                                     collapsedVisibleHeight: SBSDKUI2CollapsedVisibleHeight.small,\n                                                     listButton: SBSDKUI2BadgedButton(badgeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                          isArgb: false),\n                                                                                      badgeForegroundColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                          isArgb: false),\n                                                                                      visible: true,\n                                                                                      backgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                     isArgb: false),\n                                                                                      foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                     isArgb: false),\n                                                                                      activeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                           isArgb: false),\n                                                                                      activeForegroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                           isArgb: false))), "},{"text":"sheetContent","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2SheetContent","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent"},{"text":" = SBSDKUI2SheetContent(sheetColor: SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false),\n                                         dividerColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                     isArgb: false),\n                                         manualCountChangeEnabled: true,\n                                         manualCountOutlineColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                                isArgb: false),\n                                         manualCountChangeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                               isArgb: false),\n                                         title: SBSDKUI2StyledText(text: \"?multipleModeSheetTitle\",\n                                                                   color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                        isArgb: false)),\n                                         clearAllButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                     text: \"?sheetClearAllButton\",\n                                                                                     background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                    isArgb: false),\n                                                                                                                         fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                  isArgb: false),\n                                                                                                                         strokeWidth: 1.0),\n                                                                                     foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                              isArgb: false),\n                                                                                                                         useShadow: false)),\n                                         barcodeItemTitle: SBSDKUI2StyledText(visible: true,\n                                                                              text: \"BARCODE_TITLE\",\n                                                                              color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                   isArgb: false),\n                                                                              useShadow: false),\n                                         barcodeItemSubtitle: SBSDKUI2StyledText(visible: true,\n                                                                                 text: \"BARCODE_SUBTITLE\",\n                                                                                 color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                      isArgb: false),\n                                                                                 useShadow: false),\n                                         barcodeItemImageVisible: true,\n                                         submitButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                   text: \"?sheetSubmitButton\",\n                                                                                   background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                  isArgb: false),\n                                                                                                                       fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                isArgb: false),\n                                                                                                                       strokeWidth: 1.0),\n                                                                                   foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                       color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                            isArgb: false),\n                                                                                                                       useShadow: false)),\n                                         startScanningButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                          text: \"?sheetStartScanningButton\",\n                                                                                          background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                              fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                       isArgb: false),\n                                                                                                                              strokeWidth: 1.0),\n                                                                                          foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                              color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                   isArgb: false),\n                                                                                                                              useShadow: false)),\n                                         placeholderTitle: SBSDKUI2StyledText(visible: true,\n                                                                              text: \"?sheetPlaceholderTitle\",\n                                                                              color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                   isArgb: false),\n                                                                              useShadow: false),\n                                         placeholderSubtitle: SBSDKUI2StyledText(visible: true,\n                                                                                 text: \"?sheetPlaceholderSubtitle\",\n                                                                                 color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                      isArgb: false),\n                                                                                 useShadow: false),\n                                         placeholderIconBackground: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                                  isArgb: false),\n                                         placeholderIcon: SBSDKUI2IconStyle(visible: true,\n                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                 isArgb: false)),\n                                         swipeToDelete: SBSDKUI2SwipeToDelete(enabled: true,\n                                                                              backgroundColor: SBSDKUI2Color(colorString: \"?sbColorNegative\",\n                                                                                                             isArgb: false),\n                                                                              iconColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                       isArgb: false))), ","kind":"text"},{"text":"manualCountEditDialog","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ManualCountEditDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ManualCountEditDialog","text":"SBSDKUI2ManualCountEditDialog","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2ManualCountEditDialog(sheetColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                            isArgb: false),\n                                                  dividerColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                              isArgb: false),\n                                                  modalOverlayColor: SBSDKUI2Color(colorString: \"?sbColorModalOverlay\",\n                                                                                   isArgb: false),\n                                                  title: SBSDKUI2StyledText(text: \"?manualCountEditDialogTitle\",\n                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                 isArgb: false)),\n                                                  info: SBSDKUI2StyledText(text: \"?manualCountEditDialogInfo\",\n                                                                           color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                isArgb: false)),\n                                                  updateButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                            text: \"?manualCountEditDialogUpdateButton\",\n                                                                                            background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                           isArgb: false),\n                                                                                                                                fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                                strokeWidth: 1.0),\n                                                                                            foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                                color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                                useShadow: false)),\n                                                  cancelButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                            text: \"?manualCountEditDialogCancelButton\",\n                                                                                            background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                           isArgb: false),\n                                                                                                                                fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                                strokeWidth: 1.0),\n                                                                                            foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                                color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                                useShadow: false)),\n                                                  clearTextButton: SBSDKUI2IconStyle(visible: true,\n                                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                          isArgb: false))), "},{"text":"barcodeInfoMapping","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping","text":"SBSDKUI2BarcodeInfoMapping"},{"kind":"text","text":" = SBSDKUI2BarcodeInfoMapping(sheetColor: SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false),\n                                               dividerColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                           isArgb: false),\n                                               modalOverlayColor: SBSDKUI2Color(colorString: \"?sbColorModalOverlay\",\n                                                                                isArgb: false),\n                                               loadingMessage: SBSDKUI2StyledText(text: \"?barcodeInfoMappingLoadingMessage\",\n                                                                                  color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                       isArgb: false)),\n                                               errorState: SBSDKUI2BarcodeItemErrorState(title: SBSDKUI2StyledText(text: \"?barcodeInfoMappingErrorStateTitle\",\n                                                                                                                   color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                        isArgb: false)),\n                                                                                         subtitle: SBSDKUI2StyledText(text: \"?barcodeInfoMappingErrorStateSubtitle\",\n                                                                                                                      color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                                                           isArgb: false)),\n                                                                                         retryButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                                                                  text: \"?barcodeInfoMappingErrorStateRetryButton\",\n                                                                                                                                  background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                                                                 isArgb: false),\n                                                                                                                                                                      fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                                                               isArgb: false),\n                                                                                                                                                                      strokeWidth: 1.0),\n                                                                                                                                  foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                                                                      color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                                                           isArgb: false),\n                                                                                                                                                                      useShadow: false)),\n                                                                                         cancelButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                                                                   text: \"?barcodeInfoMappingErrorStateCancelButton\",\n                                                                                                                                   background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                                  isArgb: false),\n                                                                                                                                                                       fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                                isArgb: false),\n                                                                                                                                                                       strokeWidth: 1.0),\n                                                                                                                                   foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                                                                       color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                                                            isArgb: false),\n                                                                                                                                                                       useShadow: false)))), "},{"kind":"externalParam","text":"arOverlay"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ArOverlayGeneralConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration"},{"kind":"text","text":" = SBSDKUI2ArOverlayGeneralConfiguration(visible: false,\n                                                                                                         counterBadge: SBSDKUI2BadgeStyle(visible: true,\n                                                                                                                                          background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#FF000000\",\n                                                                                                                                                                                                         isArgb: false),\n                                                                                                                                                                              fillColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                       isArgb: false),\n                                                                                                                                                                              strokeWidth: 0.0),\n                                                                                                                                          foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                                                         isArgb: false)),\n                                                                                                         automaticSelectionEnabled: false,\n                                                                                                         barcodeItemInfoPosition: SBSDKUI2BarcodeItemInfoPosition\n                                                                                                             .below,\n                                                                                                         polygon: SBSDKUI2ArOverlayPolygonConfiguration(visible: true,\n                                                                                                                                                        deselected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                                                                                                                    isArgb: false),\n                                                                                                                                                                                         fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                                                  isArgb: false),\n                                                                                                                                                                                         strokeWidth: 3.0,\n                                                                                                                                                                                         cornerRadius: 5.0),\n                                                                                                                                                        selected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                                  isArgb: false),\n                                                                                                                                                                                       fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                                                isArgb: false),\n                                                                                                                                                                                       strokeWidth: 3.0,\n                                                                                                                                                                                       cornerRadius: 5.0)),\n                                                                                                         barcodeItemConfiguration: SBSDKUI2BarcodeItemConfiguration(imageVisible: true,\n                                                                                                                                                                    titleSelected: SBSDKUI2StyledText(text: \"BARCODE_TITLE\",\n                                                                                                                                                                                                      color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                                                                                                           isArgb: false)),\n                                                                                                                                                                    subtitleSelected: SBSDKUI2StyledText(visible: true,\n                                                                                                                                                                                                         text: \"BARCODE_SUBTITLE\",\n                                                                                                                                                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                                                                                                                                              isArgb: false),\n                                                                                                                                                                                                         useShadow: false),\n                                                                                                                                                                    titleDeselected: SBSDKUI2StyledText(visible: true,\n                                                                                                                                                                                                        text: \"BARCODE_TITLE\",\n                                                                                                                                                                                                        color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                                                                                                             isArgb: false),\n                                                                                                                                                                                                        useShadow: false),\n                                                                                                                                                                    subtitleDeselected: SBSDKUI2StyledText(text: \"BARCODE_SUBTITLE\",\n                                                                                                                                                                                                           color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                                                                                                                                                isArgb: false)),\n                                                                                                                                                                    backgroundSelected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                                                        isArgb: false),\n                                                                                                                                                                                                             fillColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                                                      isArgb: false),\n                                                                                                                                                                                                             strokeWidth: 1.0,\n                                                                                                                                                                                                             cornerRadius: 5.0),\n                                                                                                                                                                    backgroundDeselected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                                                                                                                                          isArgb: false),\n                                                                                                                                                                                                               fillColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                                                                                                                                        isArgb: false),\n                                                                                                                                                                                                               strokeWidth: 1.0,\n                                                                                                                                                                                                               cornerRadius: 5.0))))"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"init","role":"symbol","navigatorTitle":[{"text":"initWithCountingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MultipleScanningMode(im)initWithCountingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"countingRepeatDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"mode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MultipleBarcodesScanningMode","text":"SBSDKUI2MultipleBarcodesScanningMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sheet"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet","text":"SBSDKUI2Sheet"},{"text":", ","kind":"text"},{"text":"sheetContent","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2SheetContent","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"manualCountEditDialog"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ManualCountEditDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ManualCountEditDialog"},{"kind":"text","text":", "},{"text":"barcodeInfoMapping","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping","text":"SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"arOverlay"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration","text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(countingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/init(countingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/init(countingrepeatdelay:mode:sheet:sheetcontent:manualcounteditdialog:barcodeinfomapping:aroverlay:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/init(countingrepeatdelay:mode:sheet:sheetcontent:manualcounteditdialog:barcodeinfomapping:aroverlay:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleBarcodesScanningMode":{"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplebarcodesscanningmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleBarcodesScanningMode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}],"role":"symbol","type":"topic","title":"SBSDKUI2MultipleBarcodesScanningMode","abstract":[{"text":"Configuration of the mode used for scanning multiple barcodes.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode":{"type":"topic","abstract":[{"text":"Configuration of the mode for scanning multiple barcodes.","type":"text"}],"title":"SBSDKUI2MultipleScanningMode","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2MultipleScanningMode"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeInfoMapping":{"title":"SBSDKUI2BarcodeInfoMapping","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeinfomapping","abstract":[{"type":"text","text":"Configuration of the barcode data mapping."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeInfoMapping","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ManualCountEditDialog":{"type":"topic","abstract":[{"text":"Configuration of the dialog to manually edit the barcode count.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ManualCountEditDialog","title":"SBSDKUI2ManualCountEditDialog","navigatorTitle":[{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2manualcounteditdialog"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sheet":{"abstract":[{"text":"Configuration of the preview mode for scanning multiple barcodes.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2Sheet","kind":"identifier"}],"type":"topic","title":"SBSDKUI2Sheet","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet","url":"\/documentation\/scanbotsdk\/sbsdkui2sheet","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Sheet"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent":{"abstract":[{"type":"text","text":"Configuration of the list containing the barcodes that have already been scanned."}],"kind":"symbol","title":"SBSDKUI2SheetContent","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/init(countingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCountingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/init(countingrepeatdelay:mode:sheet:sheetcontent:manualcounteditdialog:barcodeinfomapping:aroverlay:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/init(countingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)","title":"init(countingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)","role":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"countingRepeatDelay","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MultipleBarcodesScanningMode","text":"SBSDKUI2MultipleBarcodesScanningMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sheet"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet","text":"SBSDKUI2Sheet"},{"kind":"text","text":", "},{"text":"sheetContent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2SheetContent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"manualCountEditDialog"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ManualCountEditDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ManualCountEditDialog"},{"text":", ","kind":"text"},{"text":"barcodeInfoMapping","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping","text":"SBSDKUI2BarcodeInfoMapping"},{"text":", ","kind":"text"},{"text":"arOverlay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration","text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayGeneralConfiguration":{"title":"SBSDKUI2ArOverlayGeneralConfiguration","abstract":[{"type":"text","text":"Configuration of the AR overlay displayed on top of barcodes in the camera preview."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithCountingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCountingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithCountingRepeatDelay:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"countingRepeatDelay"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleBarcodesScanningMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MultipleBarcodesScanningMode","text":"SBSDKUI2MultipleBarcodesScanningMode"},{"text":") ","kind":"text"},{"text":"mode","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sheet:"},{"kind":"text","text":"("},{"text":"SBSDKUI2Sheet","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sheet"},{"kind":"text","text":" "},{"text":"sheetContent:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent","text":"SBSDKUI2SheetContent","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sheetContent"},{"text":" ","kind":"text"},{"text":"manualCountEditDialog:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ManualCountEditDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ManualCountEditDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ManualCountEditDialog"},{"text":" *) ","kind":"text"},{"text":"manualCountEditDialog","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeInfoMapping:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier","text":"SBSDKUI2BarcodeInfoMapping"},{"text":" *) ","kind":"text"},{"text":"barcodeInfoMapping","kind":"internalParam"},{"kind":"text","text":" "},{"text":"arOverlay:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration","text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"arOverlay","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode\/title","value":"SBSDKUI2MultipleBarcodesScanningMode","op":"replace"},{"value":[{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/title","op":"replace","value":"SBSDKUI2MultipleScanningMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/fragments","value":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2BarcodeInfoMapping","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/title","op":"replace"},{"value":[{"text":"SBSDKUI2BarcodeInfoMapping","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ManualCountEditDialog\/title","op":"replace","value":"SBSDKUI2ManualCountEditDialog"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ManualCountEditDialog\/fragments","op":"replace","value":[{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}]},{"value":"SBSDKUI2Sheet","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2Sheet","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/fragments"},{"op":"replace","value":"SBSDKUI2SheetContent","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/fragments","op":"replace","value":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1init(countingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)\/title","value":"initWithCountingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCountingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1init(countingRepeatDelay:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)\/fragments"},{"op":"replace","value":"SBSDKUI2ArOverlayGeneralConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/fragments","value":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}