{"metadata":{"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerBehaviorConfiguration(py)acceptedSizeScore","navigatorTitle":[{"kind":"identifier","text":"acceptedSizeScore"}],"modules":[{"name":"ScanbotSDK"}],"title":"acceptedSizeScore","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedSizeScore"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedSizeScore"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"It is sufficient that height or width match the score. Defaults to 80.0."}]},{"name":"Important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Lower values result in low resolution document images."}]}],"type":"aside","style":"important"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/acceptedSizeScore"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/acceptedsizescore"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/acceptedsizescore"]}],"abstract":[{"text":"The minimum size in percent (0 - 100) of the screen size to accept a detected document.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","abstract":[{"text":"Configuration for the behavior of the document scanning screen.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/acceptedSizeScore":{"type":"topic","kind":"symbol","abstract":[{"text":"The minimum size in percent (0 - 100) of the screen size to accept a detected document.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"acceptedSizeScore"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/acceptedsizescore","title":"acceptedSizeScore","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"acceptedSizeScore","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/acceptedSizeScore"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"acceptedSizeScore","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"acceptedSizeScore"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedSizeScore"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/title","value":"SBSDKUIFinderDocumentScannerBehaviorConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}]},{"value":"acceptedSizeScore","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1acceptedSizeScore\/title","op":"replace"},{"value":[{"kind":"identifier","text":"acceptedSizeScore"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1acceptedSizeScore\/fragments","op":"replace"}]}]}