{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/init","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerBehaviorConfiguration(im)init","title":"init","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/init":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"title":"init","role":"symbol","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/init"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration":{"title":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration","abstract":[{"type":"text","text":"Configuration for the behavior of the document scanning screen."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/title","value":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","op":"replace"},{"value":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace"}]}]}