{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklinesegmentfloat\/end"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdklinesegmentfloat\/end"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentFloat(py)end","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"end","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"}],"navigatorTitle":[{"text":"end","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"end"},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentFloat\/end","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentFloat"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"end"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"}]}]}],"abstract":[{"text":"End point of the segment.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentFloat/end":{"kind":"symbol","abstract":[{"text":"End point of the segment.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklinesegmentfloat\/end","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"end"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"end"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"}],"title":"end","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentFloat\/end"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentFloat":{"url":"\/documentation\/scanbotsdk\/sbsdklinesegmentfloat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentFloat","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Represents a line segment in 2D space."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLineSegmentFloat"}],"role":"symbol","title":"SBSDKLineSegmentFloat","navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegmentFloat"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"end"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"end"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":" "},{"kind":"identifier","text":"end"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"end","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentFloat~1end\/title"},{"value":[{"kind":"identifier","text":"end"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentFloat~1end\/fragments"},{"value":"SBSDKLineSegmentFloat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentFloat\/title"},{"value":[{"kind":"identifier","text":"SBSDKLineSegmentFloat"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentFloat\/fragments"},{"value":[{"text":"SBSDKLineSegmentFloat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentFloat\/navigatorTitle"}]}]}