{"metadata":{"title":"extractedDocumentFormats","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"extractedDocumentFormats","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerConfiguration(py)extractedDocumentFormats","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extractedDocumentFormats","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat","text":"SBSDKBarcodeDocumentFormat","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extractedDocumentFormats","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentFormat","text":"SBSDKBarcodeDocumentFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat"},{"text":"]","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/extractedDocumentFormats"},"abstract":[{"text":"List of document formats to be extracted.","type":"text"},{"text":" ","type":"text"},{"text":"Barcodes that decode to one of the extracted document formats will have extractedDocument field in BarcodeItem","type":"text"},{"text":" ","type":"text"},{"text":"populated with the parsed document.","type":"text"},{"text":" ","type":"text"},{"text":"By default all supported barcode document formats are accepted.","type":"text"},{"text":" ","type":"text"},{"text":"If empty, no barcodes will be parsed into documents.","type":"text"},{"text":" ","type":"text"},{"text":"To only accept the document formats listed in extractedDocumentFormats, the property onlyAcceptDocuments must be","type":"text"},{"text":" ","type":"text"},{"text":"true.","type":"text"}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/extracteddocumentformats"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/extracteddocumentformats"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration":{"title":"SBSDKBarcodeScannerConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"abstract":[{"type":"text","text":"Configuration for the barcode scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/extractedDocumentFormats":{"navigatorTitle":[{"text":"extractedDocumentFormats","kind":"identifier"}],"title":"extractedDocumentFormats","abstract":[{"type":"text","text":"List of document formats to be extracted."},{"type":"text","text":" "},{"type":"text","text":"Barcodes that decode to one of the extracted document formats will have extractedDocument field in BarcodeItem"},{"type":"text","text":" "},{"type":"text","text":"populated with the parsed document."},{"type":"text","text":" "},{"type":"text","text":"By default all supported barcode document formats are accepted."},{"type":"text","text":" "},{"type":"text","text":"If empty, no barcodes will be parsed into documents."},{"type":"text","text":" "},{"type":"text","text":"To only accept the document formats listed in extractedDocumentFormats, the property onlyAcceptDocuments must be"},{"type":"text","text":" "},{"type":"text","text":"true."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extractedDocumentFormats","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat","text":"SBSDKBarcodeDocumentFormat","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/extracteddocumentformats","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/extractedDocumentFormats"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentFormat":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentFormat","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentFormat","kind":"identifier"}],"title":"SBSDKBarcodeDocumentFormat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentFormat","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentformat","abstract":[{"text":"Type of barcode document format used.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"extractedDocumentFormats","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"extractedDocumentFormats","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBarcodeDocumentFormat *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"extractedDocumentFormats","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKBarcodeScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/title"},{"value":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/navigatorTitle"},{"value":"extractedDocumentFormats","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1extractedDocumentFormats\/title"},{"value":[{"kind":"identifier","text":"extractedDocumentFormats"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1extractedDocumentFormats\/fragments"},{"value":"SBSDKBarcodeDocumentFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentFormat\/title"},{"value":[{"text":"SBSDKBarcodeDocumentFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentFormat\/fragments"},{"value":[{"text":"SBSDKBarcodeDocumentFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentFormat\/navigatorTitle"}]}]}