{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetectionStatus:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus","text":"SBSDKDocumentDetectionStatus","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectionStatus"},{"kind":"text","text":") "},{"kind":"internalParam","text":"detectionStatus"},{"kind":"text","text":" "},{"text":"scanningStatus:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCreditCardScanningStatus","text":"SBSDKCreditCardScanningStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningStatus","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"scanningStatus","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"creditCard:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","text":"SBSDKGenericDocument"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"creditCard"},{"kind":"text","text":" "},{"kind":"identifier","text":"quad:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSValue *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"quad"},{"kind":"text","text":" "},{"kind":"identifier","text":"quadNormalized:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSValue *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"quadNormalized"},{"kind":"text","text":";"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult\/initwithdetectionstatus:scanningstatus:creditcard:quad:quadnormalized:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/initWithDetectionStatus:scanningStatus:creditCard:quad:quadNormalized:","interfaceLanguage":"occ"},"metadata":{"title":"initWithDetectionStatus:scanningStatus:creditCard:quad:quadNormalized:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScanningResult(im)initWithDetectionStatus:scanningStatus:creditCard:quad:quadNormalized:","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithDetectionStatus:scanningStatus:creditCard:quad:quadNormalized:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetectionStatus:scanningStatus:creditCard:quad:quadNormalized:"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningStatus":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningstatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardScanningStatus","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCreditCardScanningStatus","kind":"identifier"}],"title":"SBSDKCreditCardScanningStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningStatus","abstract":[{"text":"The status of the scanning process.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult/initWithDetectionStatus:scanningStatus:creditCard:quad:quadNormalized:":{"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetectionStatus:scanningStatus:creditCard:quad:quadNormalized:"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult\/initwithdetectionstatus:scanningstatus:creditcard:quad:quadnormalized:","navigatorTitle":[{"kind":"identifier","text":"initWithDetectionStatus:scanningStatus:creditCard:quad:quadNormalized:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/initWithDetectionStatus:scanningStatus:creditCard:quad:quadNormalized:","title":"initWithDetectionStatus:scanningStatus:creditCard:quad:quadNormalized:","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Status of the document detection.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus","title":"SBSDKDocumentDetectionStatus","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult":{"kind":"symbol","abstract":[{"type":"text","text":"Contains the result of running the credit card scanner."}],"title":"SBSDKCreditCardScanningResult","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardScanningResult","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCreditCardScanningResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"title":"SBSDKGenericDocument","kind":"symbol","abstract":[{"type":"text","text":"Generic document."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocument"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"SBSDKCreditCardScanningStatus","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningStatus\/title"},{"value":[{"text":"SBSDKCreditCardScanningStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningStatus\/fragments"},{"value":[{"text":"SBSDKCreditCardScanningStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningStatus\/navigatorTitle"},{"value":"SBSDKDocumentDetectionStatus","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/navigatorTitle"},{"value":"SBSDKCreditCardScanningResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult\/title"},{"value":[{"text":"SBSDKCreditCardScanningResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKCreditCardScanningResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult\/navigatorTitle"},{"value":"SBSDKGenericDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title"},{"value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}