{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanmedicinefieldtype\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanmedicinefieldtype\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanMedicineFieldType\/unknown","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Unknown"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"title":"SBSDKUI2MedicalPlanMedicineFieldType.unknown","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MedicalPlanMedicineFieldType@SBSDKUI2MedicalPlanMedicineFieldTypeUnknown","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicineFieldTypeUnknown"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanMedicineFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanMedicineFieldType/unknown":{"role":"symbol","title":"SBSDKUI2MedicalPlanMedicineFieldType.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"Unknown"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanMedicineFieldType\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicineFieldTypeUnknown"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanmedicinefieldtype\/unknown"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanMedicineFieldType":{"role":"symbol","title":"SBSDKUI2MedicalPlanMedicineFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicineFieldType"}],"abstract":[{"type":"text","text":"Medical Plan Medicine Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanMedicineFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicineFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanmedicinefieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2MedicalPlanMedicineFieldTypeUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicineFieldTypeUnknown"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicineFieldTypeUnknown"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanMedicineFieldType~1unknown\/title","value":"SBSDKUI2MedicalPlanMedicineFieldTypeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanMedicineFieldType~1unknown\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicineFieldTypeUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanMedicineFieldType\/title","value":"SBSDKUI2MedicalPlanMedicineFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanMedicineFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicineFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}