{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatupceanconfiguration()"]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatUpcEanConfiguration()"},"metadata":{"symbolKind":"method","externalID":"s:10ScanbotSDK35SBSDKBarcodeFormatConfigurationBaseC07barcoded6UpcEanE0AA0cdhiE0CyFZ","title":"barcodeFormatUpcEanConfiguration()","role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatUpcEanConfiguration"},{"kind":"text","text":"() -> "},{"text":"SBSDKBarcodeFormatUpcEanConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatUpcEanConfiguration"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"barcodeFormatUpcEanConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatUpcEanConfiguration","text":"SBSDKBarcodeFormatUpcEanConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatUpcEanConfiguration","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatUpcEanConfiguration()":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatupceanconfiguration()","abstract":[],"title":"barcodeFormatUpcEanConfiguration()","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatUpcEanConfiguration()","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatUpcEanConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatUpcEanConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatUpcEanConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatUpcEanConfiguration":{"abstract":[{"text":"UPC\/EAN barcode configuration. Add to scanner configuration to scan EAN-8, EAN-13, UPC-E and UPC-A barcodes.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeFormatUpcEanConfiguration"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatUpcEanConfiguration","kind":"identifier"}],"title":"SBSDKBarcodeFormatUpcEanConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatupceanconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatUpcEanConfiguration","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase","title":"SBSDKBarcodeFormatConfigurationBase","abstract":[{"type":"text","text":"Base class for all barcode configurations."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKBarcodeFormatUpcEanConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatUpcEanConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatUpcEanConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatUpcEanConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKBarcodeFormatUpcEanConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatUpcEanConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/title","value":"SBSDKBarcodeFormatConfigurationBase"},{"value":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"op":"replace"}]}]}