{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimagemetadataprocessor\/imagedatabyinjecting(metadata:into:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimagemetadataprocessor\/imagedatabyinjecting(metadata:into:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(imageDataByInjectingMetadata:intoImageData:) ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageDataByInjecting","kind":"identifier"},{"kind":"text","text":"("},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKImageMetadata","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageMetadata","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageMetadata"},{"kind":"text","text":", "},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"imageData"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"metadata","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The (modified) metadata object to be used for the new image data object."}]}]},{"name":"imageData","content":[{"type":"paragraph","inlineContent":[{"text":"The image data of the image to inject the metadata into.","type":"text"}]}]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An ","type":"text"},{"code":"Data","type":"codeVoice"},{"type":"text","text":" object containing the given image data and metadata, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the image data is invalid. Can be used to create a new "},{"type":"codeVoice","code":"UIImage"},{"text":".","type":"text"}]}],"kind":"content"}],"sections":[],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"imageDataByInjectingMetadata:intoImageData:"}],"symbolKind":"method","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageDataByInjecting","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"metadata"},{"text":": ","kind":"text"},{"text":"SBSDKImageMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageMetadata"},{"kind":"text","text":", "},{"text":"into","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":") -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Type Method","title":"imageDataByInjecting(metadata:into:)","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageMetadataProcessor(cm)imageDataByInjectingMetadata:intoImageData:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageMetadataProcessor"]]},"abstract":[{"text":"Merges image data and (modified) image metadata and creates a new ","type":"text"},{"type":"codeVoice","code":"Data"},{"type":"text","text":" object that can be used to create a new image."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageMetadataProcessor\/imageDataByInjecting(metadata:into:)"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageMetadataProcessor/imageDataByInjecting(metadata:into:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageMetadataProcessor\/imageDataByInjecting(metadata:into:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageDataByInjecting"},{"text":"(","kind":"text"},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageMetadata","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageMetadata"},{"text":", ","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagemetadataprocessor\/imagedatabyinjecting(metadata:into:)","abstract":[{"type":"text","text":"Merges image data and (modified) image metadata and creates a new "},{"type":"codeVoice","code":"Data"},{"text":" object that can be used to create a new image.","type":"text"}],"kind":"symbol","title":"imageDataByInjecting(metadata:into:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"imageDataByInjectingMetadata:intoImageData:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageMetadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageMetadata","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"SBSDKImageMetadata","navigatorTitle":[{"text":"SBSDKImageMetadata","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageMetadata","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagemetadata","abstract":[{"text":"Encapsulates image metadata, e.g. EXIF, TIFF, JFIF in a convenient way.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Use "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageMetadataProcessor"},{"text":" to extract metadata from and inject changed metadata into image data.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageMetadataProcessor":{"abstract":[{"text":"Helper class to extract or inject image metadata, e.g. EXIF, TIFF, JFIF from  image data.","type":"text"}],"title":"SBSDKImageMetadataProcessor","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageMetadataProcessor","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagemetadataprocessor","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageMetadataProcessor"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"imageDataByInjectingMetadata:intoImageData:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"imageDataByInjectingMetadata:intoImageData:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":" *) ","kind":"text"},{"text":"imageDataByInjectingMetadata:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKImageMetadata","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageMetadata","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageMetadata","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"metadata"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intoImageData:"},{"kind":"text","text":"("},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"imageData"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"metadata","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The (modified) metadata object to be used for the new image data object."}]}]},{"name":"imageData","content":[{"type":"paragraph","inlineContent":[{"text":"The image data of the image to inject the metadata into.","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An "},{"code":"Data","type":"codeVoice"},{"text":" object containing the given image data and metadata, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the image data is invalid. Can be used to create a new "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":"."}]}]},"path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageMetadataProcessor~1imageDataByInjecting(metadata:into:)\/title","value":"imageDataByInjectingMetadata:intoImageData:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageMetadataProcessor~1imageDataByInjecting(metadata:into:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"imageDataByInjectingMetadata:intoImageData:","kind":"identifier"}]},{"value":"SBSDKImageMetadata","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageMetadata\/title","op":"replace"},{"value":[{"text":"SBSDKImageMetadata","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageMetadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKImageMetadata"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageMetadata\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageMetadataProcessor\/title","value":"SBSDKImageMetadataProcessor","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageMetadataProcessor\/fragments","value":[{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageMetadataProcessor\/navigatorTitle","value":[{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}