{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewBottomBarConfiguration\/initWithAddButton:retakeButton:cropButton:rotateButton:deleteButton:submitButton:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"text":"initWithAddButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"addButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"retakeButton:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"retakeButton"},{"text":" ","kind":"text"},{"text":"cropButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"cropButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"rotateButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rotateButton"},{"text":" ","kind":"text"},{"text":"deleteButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"deleteButton"},{"kind":"text","text":" "},{"text":"submitButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" *) "},{"text":"submitButton","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReviewBottomBarConfiguration(im)initWithAddButton:retakeButton:cropButton:rotateButton:deleteButton:submitButton:","title":"initWithAddButton:retakeButton:cropButton:rotateButton:deleteButton:submitButton:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAddButton:retakeButton:cropButton:rotateButton:deleteButton:submitButton:"}],"navigatorTitle":[{"text":"initWithAddButton:retakeButton:cropButton:rotateButton:deleteButton:submitButton:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewBottomBarConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2reviewbottombarconfiguration\/initwithaddbutton:retakebutton:cropbutton:rotatebutton:deletebutton:submitbutton:"]}],"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReviewBottomBarConfiguration/initWithAddButton:retakeButton:cropButton:rotateButton:deleteButton:submitButton:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewBottomBarConfiguration\/initWithAddButton:retakeButton:cropButton:rotateButton:deleteButton:submitButton:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAddButton:retakeButton:cropButton:rotateButton:deleteButton:submitButton:"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2reviewbottombarconfiguration\/initwithaddbutton:retakebutton:cropbutton:rotatebutton:deletebutton:submitbutton:","navigatorTitle":[{"text":"initWithAddButton:retakeButton:cropButton:rotateButton:deleteButton:submitButton:","kind":"identifier"}],"role":"symbol","title":"initWithAddButton:retakeButton:cropButton:rotateButton:deleteButton:submitButton:","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReviewBottomBarConfiguration":{"title":"SBSDKUI2ReviewBottomBarConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Configuration of the bottom bar for the review screen."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewBottomBarConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2reviewbottombarconfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarButtonConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barbuttonconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","kind":"symbol","type":"topic","role":"symbol","title":"SBSDKUI2BarButtonConfiguration","abstract":[{"type":"text","text":"Configuration of the button located on a bar."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ButtonConfiguration":{"type":"topic","navigatorTitle":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","title":"SBSDKUI2ButtonConfiguration","abstract":[{"type":"text","text":"Configuration of the button."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2ReviewBottomBarConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewBottomBarConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewBottomBarConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewBottomBarConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"identifier"}]},{"value":"SBSDKUI2BarButtonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/fragments","value":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/title","op":"replace","value":"SBSDKUI2ButtonConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}]},{"op":"replace","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle"}]}]}