{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontrollerdelegate\/textpatternscannerviewcontrollershouldscan(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontrollerdelegate\/textpatternscannerviewcontrollershouldscan(_:)"]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","title":"textPatternScannerViewControllerShouldScan(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textPatternScannerViewControllerShouldScan","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController","text":"SBSDKTextPatternScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","navigatorTitle":[{"text":"textPatternScannerViewControllerShouldScan:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKTextPatternScannerViewControllerDelegate(im)textPatternScannerViewControllerShouldScan:","roleHeading":"Instance Method","required":true},"sections":[],"abstract":[{"text":"Asks the delegate whether the next video frame should be scanned or not.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewControllerDelegate"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textPatternScannerViewControllerShouldScan"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController","text":"SBSDKTextPatternScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController"},{"text":" that wants to scan the next video frame.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":""},{"code":"true","type":"codeVoice"},{"text":", if you want to scan the next video frame, ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" otherwise.","type":"text"}],"type":"paragraph"}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Optional.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Use to skip frames or pause the scanner for a while."}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewControllerDelegate\/textPatternScannerViewControllerShouldScan(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewControllerDelegate/textPatternScannerViewControllerShouldScan(_:)":{"required":true,"title":"textPatternScannerViewControllerShouldScan(_:)","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontrollerdelegate\/textpatternscannerviewcontrollershouldscan(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"textPatternScannerViewControllerShouldScan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKTextPatternScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Asks the delegate whether the next video frame should be scanned or not.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewControllerDelegate\/textPatternScannerViewControllerShouldScan(_:)","role":"symbol","navigatorTitle":[{"text":"textPatternScannerViewControllerShouldScan:","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewControllerDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTextPatternScannerViewControllerDelegate"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewControllerDelegate","abstract":[{"type":"text","text":"The delegation protocol for "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewControllerDelegate"}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontrollerdelegate","title":"SBSDKTextPatternScannerViewControllerDelegate","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewController":{"navigatorTitle":[{"text":"SBSDKTextPatternScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show a camera screen with the text pattern scanner."}],"title":"SBSDKTextPatternScannerViewController","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"textPatternScannerViewControllerShouldScan:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textPatternScannerViewControllerShouldScan:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"textPatternScannerViewControllerShouldScan:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","kind":"typeIdentifier","text":"SBSDKTextPatternScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","isActive":true},{"text":" that wants to scan the next video frame.","type":"text"}],"type":"paragraph"}]}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":", if you want to scan the next video frame, "},{"type":"codeVoice","code":"false"},{"text":" otherwise.","type":"text"}],"type":"paragraph"}]}},{"op":"replace","value":"textPatternScannerViewControllerShouldScan:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewControllerDelegate~1textPatternScannerViewControllerShouldScan(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewControllerDelegate~1textPatternScannerViewControllerShouldScan(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textPatternScannerViewControllerShouldScan:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewControllerDelegate\/title","value":"SBSDKTextPatternScannerViewControllerDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/title","op":"replace","value":"SBSDKTextPatternScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/fragments","value":[{"text":"SBSDKTextPatternScannerViewController","kind":"identifier"}]},{"value":[{"text":"SBSDKTextPatternScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/navigatorTitle"}]}]}