{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoFrameResolution","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKVideoFrameResolution","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKVideoFrameResolution","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerGeneralConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannergeneralconfiguration\/videoframeresolution"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannergeneralconfiguration\/videoframeresolution"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"videoFrameResolution"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration(py)videoFrameResolution","title":"videoFrameResolution","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoFrameResolution","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKVideoFrameResolution","text":"SBSDKVideoFrameResolution","kind":"typeIdentifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerGeneralConfiguration\/videoFrameResolution","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The video frame resolution of the preview layer."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/auto","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Higher resolutions may improve scanning results but slow down the scanning performance."},{"type":"text","text":" "},{"type":"text","text":"In some cases a higher resolution may even decrease the scanning quality."},{"type":"text","text":" "},{"type":"text","text":"It is therefore recommended to keep this setting at "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/auto","isActive":true,"type":"reference"},{"type":"text","text":"."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFrameResolution/auto":{"kind":"symbol","abstract":[{"text":"Select the video resolution automatically based on device specifics.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/auto","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"auto"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionAuto"}],"title":"SBSDKVideoFrameResolution.auto","type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/auto"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerGeneralConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerGeneralConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannergeneralconfiguration","kind":"symbol","title":"SBSDKBaseScannerGeneralConfiguration","type":"topic","abstract":[{"text":"The general configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerGeneralConfiguration/videoFrameResolution":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannergeneralconfiguration\/videoframeresolution","title":"videoFrameResolution","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoFrameResolution","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKVideoFrameResolution","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKVideoFrameResolution","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"videoFrameResolution","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerGeneralConfiguration\/videoFrameResolution","kind":"symbol","abstract":[{"type":"text","text":"The video frame resolution of the preview layer."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/auto","isActive":true},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Higher resolutions may improve scanning results but slow down the scanning performance.","type":"text"},{"text":" ","type":"text"},{"text":"In some cases a higher resolution may even decrease the scanning quality.","type":"text"},{"text":" ","type":"text"},{"text":"It is therefore recommended to keep this setting at ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/auto"},{"text":".","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFrameResolution":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"kind":"symbol","title":"SBSDKVideoFrameResolution","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution","abstract":[{"type":"text","text":"An enum describing the resolution of a video or camera stream."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"videoFrameResolution","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"videoFrameResolution"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKVideoFrameResolution","text":"SBSDKVideoFrameResolution","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"videoFrameResolution","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution~1auto\/title","value":"SBSDKVideoFrameResolutionAuto"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution~1auto\/fragments","value":[{"text":"SBSDKVideoFrameResolutionAuto","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerGeneralConfiguration\/title","value":"SBSDKBaseScannerGeneralConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerGeneralConfiguration\/fragments","value":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerGeneralConfiguration\/navigatorTitle","value":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerGeneralConfiguration~1videoFrameResolution\/title","value":"videoFrameResolution"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerGeneralConfiguration~1videoFrameResolution\/fragments","value":[{"kind":"identifier","text":"videoFrameResolution"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution\/title","value":"SBSDKVideoFrameResolution"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution\/fragments","value":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}