{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/timeout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/timeout"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The operation timed out before completion.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType"]]},"metadata":{"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKErrorType@SBSDKErrorTypeTimeout","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeTimeout"}],"title":"SBSDKErrorType.timeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeout"}],"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/timeout","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeout","kind":"identifier"}]}]}],"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType/timeout":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeout","kind":"identifier"}],"title":"SBSDKErrorType.timeout","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/timeout","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/timeout","type":"topic","role":"symbol","abstract":[{"text":"The operation timed out before completion.","type":"text"}],"navigatorTitle":[{"text":"SBSDKErrorTypeTimeout","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKErrorType"}],"kind":"symbol","title":"SBSDKErrorType","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType","abstract":[{"type":"text","text":"An Objective-C compatible enum representing the types of errors that can occur within the Scanbot SDK."},{"type":"text","text":" "},{"type":"text","text":"Each case corresponds to a specific error code."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorType"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKErrorTypeTimeout"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorTypeTimeout"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKErrorTypeTimeout"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1timeout\/title","op":"replace","value":"SBSDKErrorTypeTimeout"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1timeout\/fragments","op":"replace","value":[{"text":"SBSDKErrorTypeTimeout","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType\/title","op":"replace","value":"SBSDKErrorType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType\/fragments","op":"replace","value":[{"text":"SBSDKErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}