{"abstract":[{"type":"text","text":"Applies a polygon and a filter to the receiver. Faster than two sequential operations."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(sbsdk_imageWarpedByPolygon:andFilteredBy:lensCameraProperties:imageScale:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sbsdk_imageWarped"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"text":" ","kind":"text"},{"text":"polygon","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"filters"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","text":"SBSDKParametricFilter"},{"kind":"text","text":"], "},{"text":"lensCameraProperties","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLensCameraProperties","text":"SBSDKLensCameraProperties","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLensCameraProperties"},{"text":"?, ","kind":"text"},{"text":"imageScale","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The polygon used to crop and perspective correct the image."}]}],"name":"polygon"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The types of the filters to be applied."}]}],"name":"filters"},{"name":"lensCameraProperties","content":[{"type":"paragraph","inlineContent":[{"text":"Properties of the camera which captured the image or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]},{"name":"imageScale","content":[{"type":"paragraph","inlineContent":[{"text":"If the image has been scaled, compared to how it was captured from the camera, you must set the scaling factor here for proper cropping. Otherwise the resulting aspect ratio will be wrong. Set to 1.0 if the image must retain its original size.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The cropped, perspective corrected and filtered ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the operation failed."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/uikit\/uiimage\/sbsdk_imagewarped(by:filters:lenscameraproperties:imagescale:)"]}],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbsdk_imageWarped","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"by"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filters"},{"text":": [","kind":"text"},{"text":"SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"lensCameraProperties","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLensCameraProperties","text":"SBSDKLensCameraProperties","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"imageScale","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"title":"sbsdk_imageWarped(by:filters:lensCameraProperties:imageScale:)","externalID":"c:@CM@ScanbotSDK@@objc(cs)UIImage(im)sbsdk_imageWarpedByPolygon:andFilteredBy:lensCameraProperties:imageScale:","modules":[{"name":"ScanbotSDK","relatedModules":["UIKit"]}],"extendedModule":"UIKit","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage\/sbsdk_imageWarped(by:filters:lensCameraProperties:imageScale:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKParametricFilter","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"abstract":[{"type":"text","text":"Base class for all parametric filters."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter","title":"SBSDKParametricFilter","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLensCameraProperties":{"type":"topic","abstract":[{"type":"text","text":"Encapsulates lens and camera properties. Can be used with polygonal image cropping to achieve a very accurate aspect ratio of the resulting image."},{"text":" ","type":"text"},{"text":"If created from image image metadata, uses a dictionary of some known devices to lookup the values.","type":"text"}],"title":"SBSDKLensCameraProperties","navigatorTitle":[{"text":"SBSDKLensCameraProperties","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdklenscameraproperties","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLensCameraProperties","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKLensCameraProperties","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit/UIImage/sbsdk_imageWarped(by:filters:lensCameraProperties:imageScale:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage\/sbsdk_imageWarped(by:filters:lensCameraProperties:imageScale:)","kind":"symbol","title":"sbsdk_imageWarped(by:filters:lensCameraProperties:imageScale:)","abstract":[{"type":"text","text":"Applies a polygon and a filter to the receiver. Faster than two sequential operations."}],"url":"\/documentation\/scanbotsdk\/uikit\/uiimage\/sbsdk_imagewarped(by:filters:lenscameraproperties:imagescale:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sbsdk_imageWarped","kind":"identifier"},{"text":"(","kind":"text"},{"text":"by","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filters"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"lensCameraProperties"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLensCameraProperties","text":"SBSDKLensCameraProperties"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageScale"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit/UIImage":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage","kind":"symbol","role":"symbol","abstract":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" class extension to perform basic image processing operations."},{"text":" ","type":"text"},{"type":"text","text":"Direct usage is not recommended for large images."},{"type":"text","text":" "},{"text":"queues and proper memory management.","type":"text"}],"url":"\/documentation\/scanbotsdk\/uikit\/uiimage","title":"UIImage","type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"navigatorTitle":[{"kind":"identifier","text":"UIImage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"}],"abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"type":"topic","title":"SBSDKPolygon","url":"\/documentation\/scanbotsdk\/sbsdkpolygon","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit":{"url":"\/documentation\/scanbotsdk\/uikit","role":"collection","abstract":[],"title":"UIKit","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKParametricFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/navigatorTitle","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLensCameraProperties\/title","value":"SBSDKLensCameraProperties"},{"op":"replace","value":[{"text":"SBSDKLensCameraProperties","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLensCameraProperties\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKLensCameraProperties"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLensCameraProperties\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","value":"SBSDKPolygon"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","value":[{"kind":"identifier","text":"SBSDKPolygon"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPolygon"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/navigatorTitle"}]}]}