{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(sbsdk_imageByProcessingWithRotations:polygon:filters:compression:lensCameraProperties:imageScale:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbsdk_imageByProcessing","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rotations"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"polygon"},{"kind":"text","text":": "},{"text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon"},{"text":"?, ","kind":"text"},{"text":"filters","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"compression"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lensCameraProperties"},{"text":": ","kind":"text"},{"text":"SBSDKLensCameraProperties","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLensCameraProperties","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLensCameraProperties"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageScale"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Number of 90 degree rotations to apply. Can be negative. Uses modulo arithmetics."}],"type":"paragraph"}],"name":"rotations"},{"name":"polygon","content":[{"inlineContent":[{"text":"The polygon used to crop and perspective correct the image.","type":"text"}],"type":"paragraph"}]},{"name":"filters","content":[{"inlineContent":[{"text":"The types of the filters to be applied.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The JPEG compression\/quality setting. The range is 0.0 (low quality, small file) to 1.0 (high quality, large file).","type":"text"}]}],"name":"compression"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Properties of the camera which captured the image or "},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"lensCameraProperties"},{"name":"imageScale","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If the image has been scaled, compared to how it was captured from the camera, you must set the scaling factor here for proper cropping. Otherwise the resulting aspect ratio will be wrong. Set to 1.0 if the image must retain its original size."}]}]}],"kind":"parameters"},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The processed "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the operation failed."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage\/sbsdk_imageByProcessing(rotations:polygon:filters:compression:lensCameraProperties:imageScale:)","interfaceLanguage":"swift"},"abstract":[{"text":"Applies counter-clockwise 90 degree rotations, polygon warping and filtering to the receiver and returns a JPEG ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"text":" of the given compression\/quality.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/uikit\/uiimage\/sbsdk_imagebyprocessing(rotations:polygon:filters:compression:lenscameraproperties:imagescale:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sbsdk_imageByProcessing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rotations","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"filters"},{"kind":"text","text":": ["},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"kind":"text","text":"]?, "},{"text":"compression","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"lensCameraProperties"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKLensCameraProperties","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLensCameraProperties"},{"text":"?, ","kind":"text"},{"text":"imageScale","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"role":"symbol","symbolKind":"method","externalID":"c:@CM@ScanbotSDK@@objc(cs)UIImage(im)sbsdk_imageByProcessingWithRotations:polygon:filters:compression:lensCameraProperties:imageScale:","extendedModule":"UIKit","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK","relatedModules":["UIKit"]}],"title":"sbsdk_imageByProcessing(rotations:polygon:filters:compression:lensCameraProperties:imageScale:)"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","url":"\/documentation\/scanbotsdk\/sbsdkpolygon","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPolygon"}],"title":"SBSDKPolygon","type":"topic","abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}],"navigatorTitle":[{"text":"SBSDKPolygon","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLensCameraProperties":{"title":"SBSDKLensCameraProperties","role":"symbol","abstract":[{"text":"Encapsulates lens and camera properties. Can be used with polygonal image cropping to achieve a very accurate aspect ratio of the resulting image.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If created from image image metadata, uses a dictionary of some known devices to lookup the values."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLensCameraProperties","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLensCameraProperties","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdklenscameraproperties","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKLensCameraProperties"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"type":"topic","title":"SBSDKParametricFilter","url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKParametricFilter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","role":"symbol","abstract":[{"text":"Base class for all parametric filters.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit/UIImage":{"kind":"symbol","abstract":[{"text":"An ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" class extension to perform basic image processing operations."},{"type":"text","text":" "},{"type":"text","text":"Direct usage is not recommended for large images."},{"type":"text","text":" "},{"type":"text","text":"queues and proper memory management."}],"fragments":[{"text":"extension","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIImage","kind":"identifier","preciseIdentifier":"c:objc(cs)UIImage"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIImage"}],"title":"UIImage","url":"\/documentation\/scanbotsdk\/uikit\/uiimage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit","role":"collection","type":"topic","title":"UIKit","url":"\/documentation\/scanbotsdk\/uikit"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit/UIImage/sbsdk_imageByProcessing(rotations:polygon:filters:compression:lensCameraProperties:imageScale:)":{"abstract":[{"text":"Applies counter-clockwise 90 degree rotations, polygon warping and filtering to the receiver and returns a JPEG ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"text":" of the given compression\/quality.","type":"text"}],"url":"\/documentation\/scanbotsdk\/uikit\/uiimage\/sbsdk_imagebyprocessing(rotations:polygon:filters:compression:lenscameraproperties:imagescale:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage\/sbsdk_imageByProcessing(rotations:polygon:filters:compression:lensCameraProperties:imageScale:)","type":"topic","title":"sbsdk_imageByProcessing(rotations:polygon:filters:compression:lensCameraProperties:imageScale:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbsdk_imageByProcessing","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rotations"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier","text":"SBSDKPolygon"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"filters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter"},{"text":"]?, ","kind":"text"},{"text":"compression","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lensCameraProperties"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLensCameraProperties","text":"SBSDKLensCameraProperties"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageScale"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":") -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","op":"replace","value":"SBSDKPolygon"},{"value":[{"text":"SBSDKPolygon","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLensCameraProperties\/title","value":"SBSDKLensCameraProperties","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLensCameraProperties\/fragments","value":[{"text":"SBSDKLensCameraProperties","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title","op":"replace","value":"SBSDKParametricFilter"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}