{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage\/sbsdk_imageWarped(by:filters:imageScale:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage"]]},"metadata":{"modules":[{"name":"ScanbotSDK","relatedModules":["UIKit"]}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sbsdk_imageWarped","kind":"identifier"},{"kind":"text","text":"("},{"text":"by","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"filters"},{"kind":"text","text":": ["},{"text":"SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"imageScale"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}],"role":"symbol","roleHeading":"Instance Method","title":"sbsdk_imageWarped(by:filters:imageScale:)","externalID":"c:@CM@ScanbotSDK@@objc(cs)UIImage(im)sbsdk_imageWarpedByPolygon:andFilteredBy:imageScale:","extendedModule":"UIKit","symbolKind":"method"},"abstract":[{"text":"Applies a polygon and a filter to the receiver. Faster than two sequential operations.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/uikit\/uiimage\/sbsdk_imagewarped(by:filters:imagescale:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(sbsdk_imageWarpedByPolygon:andFilteredBy:imageScale:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbsdk_imageWarped","kind":"identifier"},{"text":"(","kind":"text"},{"text":"by","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"polygon"},{"kind":"text","text":": "},{"text":"SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filters"},{"text":": [","kind":"text"},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"text":"], ","kind":"text"},{"text":"imageScale","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"polygon","content":[{"type":"paragraph","inlineContent":[{"text":"The polygon used to crop and perspective correct the image.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The types of the filters to be applied."}],"type":"paragraph"}],"name":"filters"},{"name":"imageScale","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If the image has been scaled, compared to how it was captured from the camera, you must set the scaling factor here for proper cropping. Otherwise the resulting aspect ratio will be wrong. Set to 1.0 if the image must retain its original size."}]}]}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The cropped, perspective corrected and filtered "},{"type":"codeVoice","code":"UIImage"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the operation failed."}]}],"kind":"content"}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit/UIImage/sbsdk_imageWarped(by:filters:imageScale:)":{"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sbsdk_imageWarped"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"kind":"text","text":"?, "},{"text":"filters","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"imageScale"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotsdk\/uikit\/uiimage\/sbsdk_imagewarped(by:filters:imagescale:)","title":"sbsdk_imageWarped(by:filters:imageScale:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage\/sbsdk_imageWarped(by:filters:imageScale:)","type":"topic","abstract":[{"text":"Applies a polygon and a filter to the receiver. Faster than two sequential operations.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","url":"\/documentation\/scanbotsdk\/uikit","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit","title":"UIKit"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"kind":"symbol","title":"SBSDKParametricFilter","url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter","navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKParametricFilter","kind":"identifier"}],"abstract":[{"text":"Base class for all parametric filters.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPolygon","kind":"identifier"}],"role":"symbol","title":"SBSDKPolygon","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"abstract":[{"text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit/UIImage":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"An "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" class extension to perform basic image processing operations."},{"type":"text","text":" "},{"text":"Direct usage is not recommended for large images.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"queues and proper memory management."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/uikit\/uiimage","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKParametricFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}]},{"value":"SBSDKPolygon","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title"},{"value":[{"text":"SBSDKPolygon","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","op":"replace"}]}]}