{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemErrorState\/copyWithZone:","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemErrorState"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeitemerrorstate\/copywithzone:"]}],"metadata":{"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"copyWithZone:","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItemErrorState(im)copyWithZone:","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemErrorState":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemErrorState","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitemerrorstate","abstract":[{"type":"text","text":"Configuration of the mapper’s error dialog."}],"role":"symbol","title":"SBSDKUI2BarcodeItemErrorState","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeItemErrorState","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeItemErrorState","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemErrorState/copyWithZone:":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemErrorState\/copyWithZone:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitemerrorstate\/copywithzone:","abstract":[],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2BarcodeItemErrorState","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemErrorState\/title"},{"value":[{"text":"SBSDKUI2BarcodeItemErrorState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemErrorState\/fragments"},{"value":[{"text":"SBSDKUI2BarcodeItemErrorState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemErrorState\/navigatorTitle"}]}]}