{"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKImageSourceType@SBSDKImageSourceTypeFile","roleHeading":"Case","role":"symbol","title":"SBSDKImageSourceType.file","symbolKind":"case","navigatorTitle":[{"text":"SBSDKImageSourceTypeFile","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"file","kind":"identifier"}]},"abstract":[{"text":"ImageRef was created from a file.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"file","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSourceType\/file"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSourceType"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagesourcetype\/file"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimagesourcetype\/file"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSourceType/file":{"url":"\/documentation\/scanbotsdk\/sbsdkimagesourcetype\/file","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"file","kind":"identifier"}],"abstract":[{"text":"ImageRef was created from a file.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSourceType\/file","navigatorTitle":[{"text":"SBSDKImageSourceTypeFile","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"SBSDKImageSourceType.file"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSourceType":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSourceType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageSourceType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageSourceType","kind":"identifier"}],"abstract":[{"type":"text","text":"The type of source which originated the underlying image."}],"url":"\/documentation\/scanbotsdk\/sbsdkimagesourcetype","type":"topic","title":"SBSDKImageSourceType","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKImageSourceTypeFile","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKImageSourceTypeFile","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKImageSourceTypeFile","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKImageSourceTypeFile","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSourceType~1file\/title","op":"replace"},{"value":[{"text":"SBSDKImageSourceTypeFile","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSourceType~1file\/fragments","op":"replace"},{"value":"SBSDKImageSourceType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSourceType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageSourceType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSourceType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageSourceType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSourceType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}