{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone","text":"_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraConfiguration"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameraconfiguration\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2CameraConfiguration(im)copyWithZone:","title":"copyWithZone:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"roleHeading":"Instance Method"},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraConfiguration\/copyWithZone:"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraConfiguration":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Configuration of the camera settings to be used while scanning.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameraconfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraConfiguration","title":"SBSDKUI2CameraConfiguration","navigatorTitle":[{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraConfiguration/copyWithZone:":{"title":"copyWithZone:","type":"topic","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameraconfiguration\/copywithzone:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraConfiguration\/copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2CameraConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraConfiguration\/title"},{"value":[{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}