{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/checkscannerviewcontroller(_:didscancheck:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/checkscannerviewcontroller(_:didscancheck:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/SBSDKCheckScannerViewControllerDelegate-Implementations"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/checkScannerViewController(_:didScanCheck:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Informs the delegate, that the check scanner has successfully scanned a check."}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"checkScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController","kind":"typeIdentifier","text":"SBSDKCheckScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanCheck"},{"text":": ","kind":"text"},{"text":"SBSDKCheckScanningResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanningResult"},{"kind":"text","text":")"}],"extendedModule":"ScanbotSDK","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUICheckScannerViewController(im)checkScannerViewController:didScanCheck:","navigatorTitle":[{"text":"checkScannerViewController:didScanCheck:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"checkScannerViewController(_:didScanCheck:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkScannerViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCheckScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didScanCheck"},{"text":" ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanningResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult","kind":"typeIdentifier","text":"SBSDKCheckScanningResult"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"text":"The check scanner viewController that scanned the check.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The check scanner result that have been recognized."}],"type":"paragraph"}],"name":"result"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController":{"type":"topic","title":"SBSDKUICheckScannerViewController","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"navigatorTitle":[{"text":"SBSDKUICheckScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A Ready-To-Use viewController to scan checks using the camera."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontroller","navigatorTitle":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"title":"SBSDKCheckScannerViewController","type":"topic","abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan bank checks."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController/SBSDKCheckScannerViewControllerDelegate-Implementations":{"kind":"article","abstract":[],"title":"SBSDKCheckScannerViewControllerDelegate Implementations","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/sbsdkcheckscannerviewcontrollerdelegate-implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/SBSDKCheckScannerViewControllerDelegate-Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController/checkScannerViewController(_:didScanCheck:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/checkScannerViewController(_:didScanCheck:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController","text":"SBSDKCheckScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didScanCheck","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCheckScanningResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanningResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"checkScannerViewController:didScanCheck:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/checkscannerviewcontroller(_:didscancheck:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Informs the delegate, that the check scanner has successfully scanned a check."}],"title":"checkScannerViewController(_:didScanCheck:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScanningResult":{"abstract":[{"type":"text","text":"The result of check scanning."}],"navigatorTitle":[{"text":"SBSDKCheckScanningResult","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscanningresult","type":"topic","role":"symbol","title":"SBSDKCheckScanningResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCheckScanningResult"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"checkScannerViewController:didScanCheck:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"checkScannerViewController:didScanCheck:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"checkScannerViewController:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","text":"SBSDKCheckScannerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"controller"},{"text":" ","kind":"text"},{"text":"didScanCheck:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKCheckScanningResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanningResult"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"result"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/title","value":"SBSDKUICheckScannerViewController"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/title","value":"SBSDKCheckScannerViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/fragments","value":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/navigatorTitle","value":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController~1checkScannerViewController(_:didScanCheck:)\/title","value":"checkScannerViewController:didScanCheck:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController~1checkScannerViewController(_:didScanCheck:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"checkScannerViewController:didScanCheck:"}],"op":"replace"},{"value":"SBSDKCheckScanningResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult\/fragments","value":[{"text":"SBSDKCheckScanningResult","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKCheckScanningResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult\/navigatorTitle"}]}]}