{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"coder"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/initwithcoder:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/initWithCoder:","interfaceLanguage":"occ"},"kind":"symbol","sections":[],"metadata":{"title":"initWithCoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerViewController(im)initWithCoder:","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController":{"type":"topic","title":"SBSDKUICheckScannerViewController","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"navigatorTitle":[{"text":"SBSDKUICheckScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A Ready-To-Use viewController to scan checks using the camera."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController/initWithCoder:":{"title":"initWithCoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/initWithCoder:","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/initwithcoder:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/title","value":"SBSDKUICheckScannerViewController","op":"replace"},{"value":[{"text":"SBSDKUICheckScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"op":"replace"}]}]}