{"abstract":[{"text":"Informs the delegate that one or multiple generic documents have been extracted and the view controller has been dismissed.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewControllerDelegate\/documentDataExtractorViewController(_:didFinishWith:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"documentDataExtractorViewController:didFinishWithResults:"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIDocumentDataExtractorViewControllerDelegate(im)documentDataExtractorViewController:didFinishWithResults:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentDataExtractorViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUIDocumentDataExtractorViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorViewController"},{"text":", ","kind":"text"},{"text":"didFinishWith","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractionResult","text":"SBSDKDocumentDataExtractionResult","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"title":"documentDataExtractorViewController(_:didFinishWith:)","required":true,"roleHeading":"Instance Method","role":"symbol","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontrollerdelegate\/documentdataextractorviewcontroller(_:didfinishwith:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontrollerdelegate\/documentdataextractorviewcontroller(_:didfinishwith:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(documentDataExtractorViewController:didFinishWithResults:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataExtractorViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"text":"SBSDKUIDocumentDataExtractorViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinishWith"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"results"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocumentDataExtractionResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractionResult"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"viewController","content":[{"inlineContent":[{"text":"The view controller that extracted the documents.","type":"text"}],"type":"paragraph"}]},{"name":"results","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The array of the extraction results."}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewControllerDelegate"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller","abstract":[{"text":"A highly customizable camera-based view controller to extract generic documents data.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","kind":"symbol","title":"SBSDKUIDocumentDataExtractorViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewControllerDelegate/documentDataExtractorViewController(_:didFinishWith:)":{"role":"symbol","title":"documentDataExtractorViewController(_:didFinishWith:)","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentDataExtractorViewController:didFinishWithResults:"}],"abstract":[{"type":"text","text":"Informs the delegate that one or multiple generic documents have been extracted and the view controller has been dismissed."}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontrollerdelegate\/documentdataextractorviewcontroller(_:didfinishwith:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewControllerDelegate\/documentDataExtractorViewController(_:didFinishWith:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentDataExtractorViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorViewController","kind":"typeIdentifier","text":"SBSDKUIDocumentDataExtractorViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocumentDataExtractionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractionResult"},{"kind":"text","text":"])"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewControllerDelegate":{"role":"symbol","type":"topic","abstract":[{"text":"The delegate protocol for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"SBSDKUIDocumentDataExtractorViewControllerDelegate","kind":"identifier"}],"title":"SBSDKUIDocumentDataExtractorViewControllerDelegate","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentDataExtractorViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionResult":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionResult"}],"title":"SBSDKDocumentDataExtractionResult","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionresult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionResult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDataExtractionResult"}],"abstract":[{"type":"text","text":"Contains the result of running the generic document extractor."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"documentDataExtractorViewController:didFinishWithResults:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"documentDataExtractorViewController:didFinishWithResults:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"documentDataExtractorViewController:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUIDocumentDataExtractorViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"text":" ","kind":"text"},{"text":"didFinishWithResults:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<SBSDKDocumentDataExtractionResult *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"results"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"viewController","content":[{"inlineContent":[{"type":"text","text":"The view controller that extracted the documents."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The array of the extraction results.","type":"text"}]}],"name":"results"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/title","value":"SBSDKUIDocumentDataExtractorViewController","op":"replace"},{"value":[{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/fragments"},{"value":[{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewControllerDelegate~1documentDataExtractorViewController(_:didFinishWith:)\/title","value":"documentDataExtractorViewController:didFinishWithResults:"},{"value":[{"text":"- ","kind":"text"},{"text":"documentDataExtractorViewController:didFinishWithResults:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewControllerDelegate~1documentDataExtractorViewController(_:didFinishWith:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewControllerDelegate\/title","op":"replace","value":"SBSDKUIDocumentDataExtractorViewControllerDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewControllerDelegate\/fragments","op":"replace","value":[{"text":"SBSDKUIDocumentDataExtractorViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewControllerDelegate"}],"op":"replace"},{"value":"SBSDKDocumentDataExtractionResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult\/fragments","value":[{"text":"SBSDKDocumentDataExtractionResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult\/navigatorTitle","value":[{"text":"SBSDKDocumentDataExtractionResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}