{"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"s:10ScanbotSDK32SBSDKUI2DataCaptureAccessibilityC9actionBarC4zoomSSvpZ","role":"symbol","roleHeading":"Type Property","symbolKind":"property","title":"zoom","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"zoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/actionBar"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/actionbar\/zoom"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/actionBar\/zoom","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility/actionBar":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/actionBar","role":"symbol","navigatorTitle":[{"text":"actionBar","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionBar","kind":"identifier"}],"title":"SBSDKUI2DataCaptureAccessibility.actionBar","url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/actionbar"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility/actionBar/zoom":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"zoom","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/actionBar\/zoom","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/actionbar\/zoom","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2DataCaptureAccessibility","kind":"identifier"}],"abstract":[{"text":"Accessibility identifiers to be used in UI tests for the data capture scanner RTU-UI V2 (MRZ, credit card, text pattern)..","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DataCaptureAccessibility","kind":"identifier"}],"title":"SBSDKUI2DataCaptureAccessibility","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/title","value":"SBSDKUI2DataCaptureAccessibility"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/fragments","value":[{"text":"SBSDKUI2DataCaptureAccessibility","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DataCaptureAccessibility"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}