{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCropRect:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cropRect"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageOrigin","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageOrigin","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageOrigin"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"origin"},{"kind":"text","text":" "},{"kind":"identifier","text":"canvasColor:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKCanvasColor","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCanvasColor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCanvasColor"},{"kind":"text","text":") "},{"kind":"internalParam","text":"canvasColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageRotation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRotation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"orientation"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRawImageLoadOptions"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkrawimageloadoptions\/initwithcroprect:origin:canvascolor:orientation:"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRawImageLoadOptions\/initWithCropRect:origin:canvasColor:orientation:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithCropRect:origin:canvasColor:orientation:"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKRawImageLoadOptions(im)initWithCropRect:origin:canvasColor:orientation:","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCropRect:origin:canvasColor:orientation:","kind":"identifier"}],"role":"symbol","title":"initWithCropRect:origin:canvasColor:orientation:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageOrigin":{"type":"topic","abstract":[{"type":"text","text":"Location of the image origin in the image coordinate system."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageOrigin"}],"title":"SBSDKImageOrigin","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageOrigin"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageorigin","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageOrigin"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCanvasColor":{"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcanvascolor","navigatorTitle":[{"kind":"identifier","text":"SBSDKCanvasColor"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCanvasColor","title":"SBSDKCanvasColor","abstract":[{"type":"text","text":"Canvas color to use when converting images with alpha channel to images without alpha channel."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCanvasColor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRotation":{"abstract":[{"text":"Image rotation.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRotation","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagerotation","kind":"symbol","title":"SBSDKImageRotation","role":"symbol","navigatorTitle":[{"text":"SBSDKImageRotation","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRawImageLoadOptions":{"role":"symbol","abstract":[{"text":"Options for loading images that come from sensor.","type":"text"}],"kind":"symbol","title":"SBSDKRawImageLoadOptions","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKRawImageLoadOptions"}],"url":"\/documentation\/scanbotsdk\/sbsdkrawimageloadoptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRawImageLoadOptions","navigatorTitle":[{"kind":"identifier","text":"SBSDKRawImageLoadOptions"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRawImageLoadOptions/initWithCropRect:origin:canvasColor:orientation:":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCropRect:origin:canvasColor:orientation:"}],"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCropRect:origin:canvasColor:orientation:"}],"title":"initWithCropRect:origin:canvasColor:orientation:","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkrawimageloadoptions\/initwithcroprect:origin:canvascolor:orientation:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRawImageLoadOptions\/initWithCropRect:origin:canvasColor:orientation:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKImageOrigin","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageOrigin\/title","op":"replace"},{"value":[{"text":"SBSDKImageOrigin","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageOrigin\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageOrigin"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageOrigin\/navigatorTitle","op":"replace"},{"value":"SBSDKCanvasColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCanvasColor\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCanvasColor\/fragments","op":"replace","value":[{"text":"SBSDKCanvasColor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCanvasColor\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCanvasColor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/title","op":"replace","value":"SBSDKImageRotation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRotation"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageRotation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRawImageLoadOptions\/title","op":"replace","value":"SBSDKRawImageLoadOptions"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRawImageLoadOptions\/fragments","op":"replace","value":[{"text":"SBSDKRawImageLoadOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRawImageLoadOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKRawImageLoadOptions"}]}]}]}