{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/aamvadlidfamilynametruncationfieldnormalizedname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/aamvadlidfamilynametruncationfieldnormalizedname"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants"]]},"sections":[],"abstract":[{"text":"Normalized full name of the “FamilyNameTruncation” field type in document type “AAMVA.DLID”.","type":"text"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","roleHeading":"Type Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentConstants(cpy)aamvadlidFamilyNameTruncationFieldNormalizedName","role":"symbol","title":"aamvadlidFamilyNameTruncationFieldNormalizedName","navigatorTitle":[{"kind":"identifier","text":"aamvadlidFamilyNameTruncationFieldNormalizedName"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvadlidFamilyNameTruncationFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants\/aamvadlidFamilyNameTruncationFieldNormalizedName"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvadlidFamilyNameTruncationFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentConstants/aamvadlidFamilyNameTruncationFieldNormalizedName":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/aamvadlidfamilynametruncationfieldnormalizedname","title":"aamvadlidFamilyNameTruncationFieldNormalizedName","navigatorTitle":[{"kind":"identifier","text":"aamvadlidFamilyNameTruncationFieldNormalizedName"}],"abstract":[{"type":"text","text":"Normalized full name of the “FamilyNameTruncation” field type in document type “AAMVA.DLID”."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvadlidFamilyNameTruncationFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants\/aamvadlidFamilyNameTruncationFieldNormalizedName","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentConstants":{"type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants","role":"symbol","title":"SBSDKBarcodeDocumentConstants","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"aamvadlidFamilyNameTruncationFieldNormalizedName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"aamvadlidFamilyNameTruncationFieldNormalizedName"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"aamvadlidFamilyNameTruncationFieldNormalizedName","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants~1aamvadlidFamilyNameTruncationFieldNormalizedName\/title","value":"aamvadlidFamilyNameTruncationFieldNormalizedName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants~1aamvadlidFamilyNameTruncationFieldNormalizedName\/fragments","value":[{"kind":"identifier","text":"aamvadlidFamilyNameTruncationFieldNormalizedName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/title","value":"SBSDKBarcodeDocumentConstants"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}