{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration\/init(visible:automaticSelectionEnabled:polygon:badge:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"visible"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"text":"automaticSelectionEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = true, "},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickArOverlayPolygonConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickArOverlayPolygonConfiguration"},{"text":" = SBSDKUI2FindAndPickArOverlayPolygonConfiguration(), ","kind":"text"},{"kind":"externalParam","text":"badge"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickBadgeConfiguration","text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"typeIdentifier"},{"text":" = SBSDKUI2FindAndPickBadgeConfiguration())","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlayfindandpickconfiguration\/init(visible:automaticselectionenabled:polygon:badge:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlayfindandpickconfiguration\/init(visible:automaticselectionenabled:polygon:badge:)"]}],"metadata":{"title":"init(visible:automaticSelectionEnabled:polygon:badge:)","symbolKind":"init","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayFindAndPickConfiguration(im)initWithVisible:automaticSelectionEnabled:polygon:badge:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"visible","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"automaticSelectionEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"polygon"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickArOverlayPolygonConfiguration","text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"badge"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickBadgeConfiguration","text":"SBSDKUI2FindAndPickBadgeConfiguration"},{"text":")","kind":"text"}],"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithVisible:automaticSelectionEnabled:polygon:badge:","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayFindAndPickConfiguration":{"kind":"symbol","type":"topic","title":"SBSDKUI2ArOverlayFindAndPickConfiguration","navigatorTitle":[{"text":"SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlayfindandpickconfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration of the AR overlay."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickBadgeConfiguration":{"title":"SBSDKUI2FindAndPickBadgeConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickbadgeconfiguration","navigatorTitle":[{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the round badge on find and pick ar layer."}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayFindAndPickConfiguration/init(visible:automaticSelectionEnabled:polygon:badge:)":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithVisible:automaticSelectionEnabled:polygon:badge:"}],"title":"init(visible:automaticSelectionEnabled:polygon:badge:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlayfindandpickconfiguration\/init(visible:automaticselectionenabled:polygon:badge:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"visible"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"automaticSelectionEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"polygon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickArOverlayPolygonConfiguration","text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"badge"},{"text":": ","kind":"text"},{"text":"SBSDKUI2FindAndPickBadgeConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickBadgeConfiguration","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration\/init(visible:automaticSelectionEnabled:polygon:badge:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickArOverlayPolygonConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickArOverlayPolygonConfiguration","title":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","abstract":[{"type":"text","text":"Configuration of the overlay polygon displayed on top of a barcode in the camera preview."}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickaroverlaypolygonconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithVisible:automaticSelectionEnabled:polygon:badge:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVisible:automaticSelectionEnabled:polygon:badge:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"text":"initWithVisible:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"visible"},{"kind":"text","text":" "},{"text":"automaticSelectionEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"automaticSelectionEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"text":"polygon:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickArOverlayPolygonConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickArOverlayPolygonConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"polygon"},{"text":" ","kind":"text"},{"text":"badge:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2FindAndPickBadgeConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickBadgeConfiguration"},{"kind":"text","text":" *) "},{"text":"badge","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"SBSDKUI2ArOverlayFindAndPickConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}]},{"op":"replace","value":"SBSDKUI2FindAndPickBadgeConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration~1init(visible:automaticSelectionEnabled:polygon:badge:)\/title","value":"initWithVisible:automaticSelectionEnabled:polygon:badge:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration~1init(visible:automaticSelectionEnabled:polygon:badge:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVisible:automaticSelectionEnabled:polygon:badge:"}]},{"op":"replace","value":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}