{"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscanner\/scan(from:uselivemode:)-3wtad"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscanner\/scan(from:uselivemode:)-3wtad"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanner\/scan(from:useLiveMode:)-3wtad","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanner"]]},"abstract":[{"type":"text","text":"Scans a bank check from the given "},{"code":"UIImage","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanner(im)scanFromImage:useLiveMode:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"scanFromImage:useLiveMode:","kind":"identifier"}],"title":"scan(from:useLiveMode:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useLiveMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanningResult","text":"SBSDKCheckScanningResult","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(scanFromImage:useLiveMode:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"text":"useLiveMode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false) -> "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult","text":"SBSDKCheckScanningResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanningResult","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"image","content":[{"inlineContent":[{"type":"text","text":"The image to scan from."}],"type":"paragraph"}]},{"name":"useLiveMode","content":[{"inlineContent":[{"text":"Whether to use live or single shot mode.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The result of the scanning.","type":"text"}]}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScanner/scan(from:useLiveMode:)-3wtad":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscanner\/scan(from:uselivemode:)-3wtad","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"text":"useLiveMode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanningResult","text":"SBSDKCheckScanningResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanner\/scan(from:useLiveMode:)-3wtad","abstract":[{"text":"Scans a bank check from the given ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"scanFromImage:useLiveMode:","kind":"identifier"}],"title":"scan(from:useLiveMode:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScanner":{"title":"SBSDKCheckScanner","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckScanner"}],"role":"symbol","type":"topic","abstract":[{"text":"A scanner to scan bank checks on various image sources.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCheckScanner"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanner","url":"\/documentation\/scanbotsdk\/sbsdkcheckscanner"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScanningResult":{"abstract":[{"type":"text","text":"The result of check scanning."}],"navigatorTitle":[{"text":"SBSDKCheckScanningResult","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscanningresult","type":"topic","role":"symbol","title":"SBSDKCheckScanningResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCheckScanningResult"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"scanFromImage:useLiveMode:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"scanFromImage:useLiveMode:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanningResult","kind":"typeIdentifier","text":"SBSDKCheckScanningResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult"},{"kind":"text","text":" *) "},{"text":"scanFromImage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"image"},{"kind":"text","text":" "},{"kind":"identifier","text":"useLiveMode:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"useLiveMode","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The image to scan from.","type":"text"}]}],"name":"image"},{"content":[{"inlineContent":[{"type":"text","text":"Whether to use live or single shot mode."}],"type":"paragraph"}],"name":"useLiveMode"}]}},{"value":{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the scanning."}]}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner~1scan(from:useLiveMode:)-3wtad\/title","op":"replace","value":"scanFromImage:useLiveMode:"},{"value":[{"kind":"text","text":"- "},{"text":"scanFromImage:useLiveMode:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner~1scan(from:useLiveMode:)-3wtad\/fragments","op":"replace"},{"value":"SBSDKCheckScanner","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner\/title"},{"value":[{"text":"SBSDKCheckScanner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner\/fragments"},{"value":[{"text":"SBSDKCheckScanner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner\/navigatorTitle"},{"value":"SBSDKCheckScanningResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckScanningResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCheckScanningResult"}]}]}]}