{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKContentValidationCallback(im)cleanWithRawText:","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clean"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"clean(rawText:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cleanWithRawText:"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidationCallback"]]},"abstract":[{"type":"text","text":"Cleaning callback"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcontentvalidationcallback\/clean(rawtext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcontentvalidationcallback\/clean(rawtext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clean","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidationCallback\/clean(rawText:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidationCallback":{"abstract":[{"type":"text","text":"Content validation callback."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidationcallback","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKContentValidationCallback","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidationCallback","navigatorTitle":[{"text":"SBSDKContentValidationCallback","kind":"identifier"}],"kind":"symbol","title":"SBSDKContentValidationCallback"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidationCallback/clean(rawText:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clean"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"required":true,"url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidationcallback\/clean(rawtext:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidationCallback\/clean(rawText:)","title":"clean(rawText:)","type":"topic","role":"symbol","abstract":[{"text":"Cleaning callback","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"cleanWithRawText:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"cleanWithRawText:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cleanWithRawText:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"cleanWithRawText:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rawText"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidationCallback\/title","value":"SBSDKContentValidationCallback"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidationCallback\/fragments","value":[{"text":"SBSDKContentValidationCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidationCallback\/navigatorTitle","value":[{"text":"SBSDKContentValidationCallback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidationCallback~1clean(rawText:)\/title","value":"cleanWithRawText:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidationCallback~1clean(rawText:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cleanWithRawText:"}]}]}]}