{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/lanczos4"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/lanczos4"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"SBSDKResamplingMethod.lanczos4","navigatorTitle":[{"kind":"identifier","text":"SBSDKResamplingMethodLanczos4"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lanczos4"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKResamplingMethod@SBSDKResamplingMethodLanczos4","symbolKind":"case","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lanczos4","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Lanczos (Sinc) interpolation over 8x8 neighborhood. Produces very high quality results,"},{"type":"text","text":" "},{"type":"text","text":"but slower than bi-cubic. Retains sharp edges like those of text when downsampling."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/lanczos4"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod":{"title":"SBSDKResamplingMethod","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKResamplingMethod","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKResamplingMethod","kind":"identifier"}],"abstract":[{"text":"Resampling method.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod/lanczos4":{"title":"SBSDKResamplingMethod.lanczos4","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/lanczos4","abstract":[{"text":"Lanczos (Sinc) interpolation over 8x8 neighborhood. Produces very high quality results,","type":"text"},{"text":" ","type":"text"},{"text":"but slower than bi-cubic. Retains sharp edges like those of text when downsampling.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/lanczos4","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lanczos4","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKResamplingMethodLanczos4","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKResamplingMethodLanczos4","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKResamplingMethodLanczos4","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKResamplingMethodLanczos4"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKResamplingMethod","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/title"},{"op":"replace","value":[{"text":"SBSDKResamplingMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/fragments"},{"op":"replace","value":[{"text":"SBSDKResamplingMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/navigatorTitle"},{"op":"replace","value":"SBSDKResamplingMethodLanczos4","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1lanczos4\/title"},{"op":"replace","value":[{"text":"SBSDKResamplingMethodLanczos4","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1lanczos4\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}