{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController\/setConfiguration(_:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController"]]},"abstract":[{"text":"Sets the configuration of the receiver.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontroller\/setconfiguration(_:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontroller\/setconfiguration(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCheckScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The new configuration.","type":"text"}],"type":"paragraph"}],"name":"configuration"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController(im)setConfiguration:","modules":[{"name":"ScanbotSDK"}],"title":"setConfiguration(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConfiguration"},{"kind":"text","text":"("},{"text":"SBSDKCheckScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setConfiguration:","kind":"identifier"}],"role":"symbol"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScannerConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration","title":"SBSDKCheckScannerConfiguration","navigatorTitle":[{"text":"SBSDKCheckScannerConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the check scanner."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewController/setConfiguration(_:)":{"type":"topic","navigatorTitle":[{"text":"setConfiguration:","kind":"identifier"}],"title":"setConfiguration(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKCheckScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController\/setConfiguration(_:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontroller\/setconfiguration(_:)","abstract":[{"type":"text","text":"Sets the configuration of the receiver."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewController":{"title":"SBSDKCheckScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontroller","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"abstract":[{"text":"Classic UI view controller that can be used to scan bank checks.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"setConfiguration:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setConfiguration:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setConfiguration:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKCheckScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration"},{"kind":"text","text":" *) "},{"text":"configuration","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"text":"The new configuration.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/title","value":"SBSDKCheckScannerConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckScannerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCheckScannerConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController~1setConfiguration(_:)\/title","value":"setConfiguration:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController~1setConfiguration(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setConfiguration:"}]},{"value":"SBSDKCheckScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/fragments"},{"op":"replace","value":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/navigatorTitle"}]}]}