{"kind":"symbol","abstract":[{"type":"text","text":"Recognizes text information on the given sample buffer. Intended for usage with live detection."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizer\/recognize(on:orientation:in:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizer\/recognize(on:orientation:in:)"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(recognizeOnSampleBuffer:orientation:inRect:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"text":" ","kind":"text"},{"text":"sampleBuffer","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVCaptureVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureVideoOrientation"},{"kind":"text","text":", "},{"text":"in","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"rect"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult","text":"SBSDKGenericTextLineRecognizerResult"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The sample buffer to run the recognition on."}],"type":"paragraph"}],"name":"sampleBuffer"},{"name":"orientation","content":[{"inlineContent":[{"text":"The orientation of the sample buffer.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Rectangle in image coordinates in which to perform the recognition.","type":"text"}],"type":"paragraph"}],"name":"rect"}]},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the recognition."}]}],"kind":"content"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"kind":"text","text":", "},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AVCaptureVideoOrientation","preciseIdentifier":"c:@E@AVCaptureVideoOrientation"},{"kind":"text","text":", "},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"SBSDKGenericTextLineRecognizerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult"},{"kind":"text","text":"?"}],"title":"recognize(on:orientation:in:)","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"recognizeOnSampleBuffer:orientation:inRect:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizer(im)recognizeOnSampleBuffer:orientation:inRect:","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/recognize(on:orientation:in:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerResult":{"title":"SBSDKGenericTextLineRecognizerResult","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerResult"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerresult","abstract":[{"text":"A class describing the result of the generic text line recognizer.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericTextLineRecognizerResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResult","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizer/recognize(on:orientation:in:)":{"abstract":[{"type":"text","text":"Recognizes text information on the given sample buffer. Intended for usage with live detection."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/recognize(on:orientation:in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"text":"AVCaptureVideoOrientation","preciseIdentifier":"c:@E@AVCaptureVideoOrientation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"SBSDKGenericTextLineRecognizerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"recognizeOnSampleBuffer:orientation:inRect:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizer\/recognize(on:orientation:in:)","kind":"symbol","title":"recognize(on:orientation:in:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizer":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizer"}],"abstract":[{"type":"text","text":"A class to recognize one line of text in a small area and run validation on the result."}],"title":"SBSDKGenericTextLineRecognizer"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"recognizeOnSampleBuffer:orientation:inRect:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recognizeOnSampleBuffer:orientation:inRect:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult","text":"SBSDKGenericTextLineRecognizerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResult","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"recognizeOnSampleBuffer:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@opaqueCMSampleBuffer","kind":"typeIdentifier","text":"opaqueCMSampleBuffer"},{"kind":"text","text":" *) "},{"text":"sampleBuffer","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"orientation:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation"},{"kind":"text","text":") "},{"kind":"internalParam","text":"orientation"},{"kind":"text","text":" "},{"text":"inRect:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rect"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResult\/title","op":"replace","value":"SBSDKGenericTextLineRecognizerResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer~1recognize(on:orientation:in:)\/title","value":"recognizeOnSampleBuffer:orientation:inRect:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer~1recognize(on:orientation:in:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recognizeOnSampleBuffer:orientation:inRect:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer\/title","value":"SBSDKGenericTextLineRecognizer","op":"replace"},{"value":[{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}