{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"],"title":"Conforms To","type":"conformsTo"}],"abstract":[{"type":"text","text":"Image Encoding Format."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKEncodingFormat) ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEncodingFormat"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKEncodingFormat","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKEncodingFormat"}],"symbolKind":"enum","title":"SBSDKEncodingFormat","navigatorTitle":[{"text":"SBSDKEncodingFormat","kind":"identifier"}],"roleHeading":"Enumeration","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkencodingformat"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkencodingformat"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat\/jpeg","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat\/png"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncodingFormat/jpeg":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat\/jpeg","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"jpeg","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKEncodingFormatJpeg","kind":"identifier"}],"abstract":[{"text":"JPEG encoding.","type":"text"}],"title":"SBSDKEncodingFormat.jpeg","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencodingformat\/jpeg","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncodingFormat/RawRepresentable-Implementations":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencodingformat\/rawrepresentable-implementations","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","abstract":[],"type":"topic","kind":"article","role":"collectionGroup"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncodingFormat/png":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat\/png","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencodingformat\/png","navigatorTitle":[{"text":"SBSDKEncodingFormatPng","kind":"identifier"}],"type":"topic","title":"SBSDKEncodingFormat.png","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"png","kind":"identifier"}],"abstract":[{"type":"text","text":"PNG encoding."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncodingFormat":{"type":"topic","abstract":[{"type":"text","text":"Image Encoding Format."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencodingformat","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKEncodingFormat"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEncodingFormat"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat","title":"SBSDKEncodingFormat","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncodingFormat/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat\/Equatable-Implementations","abstract":[],"kind":"article","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencodingformat\/equatable-implementations","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE"},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncodingFormat/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(rawValue:)","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat\/init(rawValue:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencodingformat\/init(rawvalue:)","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKEncodingFormat"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKEncodingFormat"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKEncodingFormat","kind":"identifier"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat\/jpeg","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat\/png"],"anchor":"Enumeration-Cases","generated":true}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKEncodingFormat","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKEncodingFormatJpeg","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodingFormat~1jpeg\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodingFormat~1jpeg\/fragments","op":"replace","value":[{"text":"SBSDKEncodingFormatJpeg","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodingFormat~1png\/title","op":"replace","value":"SBSDKEncodingFormatPng"},{"op":"replace","value":[{"text":"SBSDKEncodingFormatPng","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodingFormat~1png\/fragments"},{"value":"SBSDKEncodingFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodingFormat\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodingFormat\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKEncodingFormat"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodingFormat\/navigatorTitle","op":"replace","value":[{"text":"SBSDKEncodingFormat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}