{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"SBSDKImageStoring","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKImageStoring","navigatorTitle":[{"text":"SBSDKImageStoring","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKImageStoring","kind":"identifier"}],"roleHeading":"Protocol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"abstract":[{"type":"text","text":"Protocol for an order-aware (array like) image storage."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageStoring","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSCopying","text":"NSCopying"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagestoring"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagestoring"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/imageCount"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/add(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/addImage(from:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/copy()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/image(at:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/imageURL(at:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/removeAll()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/removeImage(at:)"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying"],"type":"inheritsFrom","title":"Inherits From"},{"type":"conformingTypes","kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageStoring/image(at:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/image(at:)","title":"image(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"kind":"symbol","required":true,"type":"topic","abstract":[{"type":"text","text":"Returns the stored UIImage at the specified index."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageAtIndex:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagestoring\/image(at:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageStoring/removeAll()":{"role":"symbol","title":"removeAll()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAll"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"removeAllImages","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/removeAll()","abstract":[{"type":"text","text":"Removes all stored images from the image storage."}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagestoring\/removeall()","required":true,"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageStoring/imageCount":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"imageCount"}],"title":"imageCount","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/imageCount","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagestoring\/imagecount","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Number of images in the receiver."}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageStoring/add(_:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/add(_:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"add","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagestoring\/add(_:)","title":"add(_:)","abstract":[{"type":"text","text":"Adds a "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" into the storage."}],"navigatorTitle":[{"text":"addImage:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying","title":"NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageStoring/copy()":{"title":"copy()","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"copy","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/copy()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"copy"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"Any"}],"required":true,"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagestoring\/copy()","abstract":[{"text":"Creates a copy of the storage.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageStoring/imageURL(at:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/imageURL(at:)","kind":"symbol","role":"symbol","required":true,"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagestoring\/imageurl(at:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?"}],"title":"imageURL(at:)","type":"topic","navigatorTitle":[{"text":"imageURLAtIndex:","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the URL of the stored image at the specified index."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKIndexedImageStorage":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"abstract":[{"text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Manages images in an array-like fashion."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"title":"SBSDKIndexedImageStorage"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageStoring":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageStoring"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageStoring"}],"title":"SBSDKImageStoring","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagestoring","type":"topic","abstract":[{"type":"text","text":"Protocol for an order-aware (array like) image storage."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageStoring/addImage(from:)":{"kind":"symbol","required":true,"title":"addImage(from:)","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagestoring\/addimage(from:)","abstract":[{"type":"text","text":"Adds an image from a file into the storage."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/addImage(from:)","navigatorTitle":[{"text":"addImageFromURL:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageStoring/removeImage(at:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/removeImage(at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagestoring\/removeimage(at:)","kind":"symbol","abstract":[{"type":"text","text":"Removes the stored image at the given index from the image storage."}],"role":"symbol","title":"removeImage(at:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"removeImageAtIndex:"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","value":"SBSDKImageStoring","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageStoring"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageStoring"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/imageCount"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/add(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/addImage(from:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/copy()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/image(at:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/imageURL(at:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/removeAll()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageStoring\/removeImage(at:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage"],"type":"conformingTypes","title":"Conforming Types"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageStoring"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSCopying","text":"NSCopying"},{"text":">","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring~1image(at:)\/title","op":"replace","value":"imageAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring~1image(at:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"imageAtIndex:","kind":"identifier"}]},{"value":"removeAllImages","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring~1removeAll()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeAllImages"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring~1removeAll()\/fragments"},{"value":"imageCount","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring~1imageCount\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring~1imageCount\/fragments","value":[{"text":"imageCount","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring~1add(_:)\/title","value":"addImage:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring~1add(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addImage:"}]},{"value":"copy","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring~1copy()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copy"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring~1copy()\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring~1imageURL(at:)\/title","value":"imageURLAtIndex:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring~1imageURL(at:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"imageURLAtIndex:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/title","op":"replace","value":"SBSDKIndexedImageStorage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/fragments","op":"replace","value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/navigatorTitle","value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring\/title","op":"replace","value":"SBSDKImageStoring"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring\/fragments","value":[{"text":"SBSDKImageStoring","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageStoring","kind":"identifier"}]},{"value":"addImageFromURL:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring~1addImage(from:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addImageFromURL:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring~1addImage(from:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring~1removeImage(at:)\/title","value":"removeImageAtIndex:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeImageAtIndex:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageStoring~1removeImage(at:)\/fragments"}]}]}