{"abstract":[{"text":"A list of all children of type “ClientPIDMap”.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientPIDMaps"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCardClientPIDMap","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardClientPIDMap","text":"SBSDKBarcodeDocumentModelVCardClientPIDMap"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"property","title":"clientPIDMaps","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCard(py)clientPIDMaps","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientPIDMaps","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKBarcodeDocumentModelVCardClientPIDMap","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCardClientPIDMap","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"clientPIDMaps","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcard\/clientpidmaps"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcard\/clientpidmaps"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCard\/clientPIDMaps"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCard"]]},"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCard/clientPIDMaps":{"navigatorTitle":[{"text":"clientPIDMaps","kind":"identifier"}],"kind":"symbol","title":"clientPIDMaps","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCard\/clientPIDMaps","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcard\/clientpidmaps","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientPIDMaps","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKBarcodeDocumentModelVCardClientPIDMap","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCardClientPIDMap"},{"text":"]","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"A list of all children of type “ClientPIDMap”."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCardClientPIDMap":{"title":"SBSDKBarcodeDocumentModelVCardClientPIDMap","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelVCardClientPIDMap","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelVCardClientPIDMap","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardclientpidmap","type":"topic","abstract":[{"type":"text","text":"Client PID Map"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardClientPIDMap","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCard":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelVCard","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCard","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcard","abstract":[{"type":"text","text":"VCard"}],"title":"SBSDKBarcodeDocumentModelVCard","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelVCard","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"clientPIDMaps","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"clientPIDMaps","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBarcodeDocumentModelVCardClientPIDMap *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"clientPIDMaps"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"clientPIDMaps","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCard~1clientPIDMaps\/title","op":"replace"},{"value":[{"kind":"identifier","text":"clientPIDMaps"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCard~1clientPIDMaps\/fragments","op":"replace"},{"value":"SBSDKBarcodeDocumentModelVCardClientPIDMap","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardClientPIDMap\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardClientPIDMap"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardClientPIDMap\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardClientPIDMap"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardClientPIDMap\/navigatorTitle","op":"replace"},{"value":"SBSDKBarcodeDocumentModelVCard","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCard\/title","op":"replace"},{"value":[{"text":"SBSDKBarcodeDocumentModelVCard","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCard\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCard"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCard\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}