{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"version","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelVCardVersion","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardVersion","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCardVersion"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCard\/version","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"version","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelVCardVersion","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCardVersion","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"version","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCard(py)version","navigatorTitle":[{"text":"version","kind":"identifier"}],"symbolKind":"property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCard"]]},"abstract":[{"text":"The child document of type “Version”.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcard\/version"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcard\/version"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCard/version":{"title":"version","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCard\/version","abstract":[{"type":"text","text":"The child document of type “Version”."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCardVersion","text":"SBSDKBarcodeDocumentModelVCardVersion","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"version","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcard\/version","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCard":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelVCard","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCard","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcard","abstract":[{"type":"text","text":"VCard"}],"title":"SBSDKBarcodeDocumentModelVCard","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelVCard","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCardVersion":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardversion","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardVersion"}],"kind":"symbol","title":"SBSDKBarcodeDocumentModelVCardVersion","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardVersion","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardVersion"}],"abstract":[{"type":"text","text":"Version"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"version","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"version","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardVersion","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCardVersion","text":"SBSDKBarcodeDocumentModelVCardVersion"},{"kind":"text","text":" * "},{"kind":"identifier","text":"version"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"version","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCard~1version\/title"},{"op":"replace","value":[{"text":"version","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCard~1version\/fragments"},{"value":"SBSDKBarcodeDocumentModelVCard","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCard\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCard"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCard\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCard\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCard"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardVersion\/title","op":"replace","value":"SBSDKBarcodeDocumentModelVCardVersion"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardVersion\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeDocumentModelVCardVersion","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardVersion\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardVersion"}]}]}]}