{"kind":"symbol","deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2CheckScannerViewController instead.","type":"text"}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontrollerdelegate\/checkscannerviewcontrollerdidcancel(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontrollerdelegate\/checkscannerviewcontrollerdidcancel(_:)"]}],"abstract":[{"type":"text","text":"Informs the delegate that the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","type":"reference","isActive":true},{"type":"text","text":" has been cancelled. Optional."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewControllerDelegate"]]},"metadata":{"required":true,"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUICheckScannerViewControllerDelegate(im)checkScannerViewControllerDidCancel:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkScannerViewControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerViewController","text":"SBSDKUICheckScannerViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"title":"checkScannerViewControllerDidCancel(_:)","platforms":[],"navigatorTitle":[{"kind":"identifier","text":"checkScannerViewControllerDidCancel:"}],"role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkScannerViewControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUICheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The check scanner viewController that cancelled scanning.","type":"text"}],"type":"paragraph"}],"name":"viewController"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewControllerDelegate\/checkScannerViewControllerDidCancel(_:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewControllerDelegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckScannerViewControllerDelegate","kind":"identifier"}],"role":"symbol","deprecated":true,"kind":"symbol","abstract":[{"text":"The delegation protocol for ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"SBSDKUICheckScannerViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontrollerdelegate","type":"topic","title":"SBSDKUICheckScannerViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewControllerDelegate/checkScannerViewControllerDidCancel(_:)":{"title":"checkScannerViewControllerDidCancel(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"checkScannerViewControllerDidCancel:"}],"abstract":[{"text":"Informs the delegate that the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","type":"reference","isActive":true},{"text":" has been cancelled. Optional.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkScannerViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerViewController","text":"SBSDKUICheckScannerViewController"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontrollerdelegate\/checkscannerviewcontrollerdidcancel(_:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewControllerDelegate\/checkScannerViewControllerDidCancel(_:)","required":true,"kind":"symbol","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","role":"symbol","abstract":[{"type":"text","text":"A Ready-To-Use viewController to scan checks using the camera."}],"title":"SBSDKUICheckScannerViewController","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"checkScannerViewControllerDidCancel:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"checkScannerViewControllerDidCancel:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"checkScannerViewControllerDidCancel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUICheckScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"viewController","content":[{"inlineContent":[{"text":"The check scanner viewController that cancelled scanning.","type":"text"}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewControllerDelegate\/title","value":"SBSDKUICheckScannerViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUICheckScannerViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKUICheckScannerViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewControllerDelegate~1checkScannerViewControllerDidCancel(_:)\/title","value":"checkScannerViewControllerDidCancel:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewControllerDelegate~1checkScannerViewControllerDidCancel(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"checkScannerViewControllerDidCancel:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/title","value":"SBSDKUICheckScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/fragments","value":[{"text":"SBSDKUICheckScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}