{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningMode\/live"},"metadata":{"symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKCreditCardScanningMode@SBSDKCreditCardScanningModeLive","roleHeading":"Case","title":"SBSDKCreditCardScanningMode.live","navigatorTitle":[{"text":"SBSDKCreditCardScanningModeLive","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"live"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanningmode\/live"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanningmode\/live"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningMode"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"live"}]}]}],"abstract":[{"type":"text","text":"The scanner will merge all information from multiple frames to provide the best possible result."},{"type":"text","text":" "},{"type":"text","text":"Use this mode when the input is a video or camera stream."}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningMode":{"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningMode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCreditCardScanningMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardScanningMode"}],"kind":"symbol","abstract":[{"type":"text","text":"The scanning mode."}],"title":"SBSDKCreditCardScanningMode","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningMode/live":{"navigatorTitle":[{"text":"SBSDKCreditCardScanningModeLive","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningmode\/live","title":"SBSDKCreditCardScanningMode.live","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningMode\/live","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"live","kind":"identifier"}],"abstract":[{"type":"text","text":"The scanner will merge all information from multiple frames to provide the best possible result."},{"type":"text","text":" "},{"type":"text","text":"Use this mode when the input is a video or camera stream."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKCreditCardScanningModeLive","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKCreditCardScanningModeLive","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKCreditCardScanningModeLive","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningMode\/title","value":"SBSDKCreditCardScanningMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningMode\/fragments","value":[{"text":"SBSDKCreditCardScanningMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningMode\/navigatorTitle","value":[{"text":"SBSDKCreditCardScanningMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningMode~1live\/title","value":"SBSDKCreditCardScanningModeLive","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningMode~1live\/fragments","value":[{"kind":"identifier","text":"SBSDKCreditCardScanningModeLive"}],"op":"replace"}]}]}