{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"energySaveDetectionRate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration\/energysavedetectionrate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration\/energysavedetectionrate"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The rate of detections\/recognitions per second in energy save mode."},{"type":"text","text":" "},{"text":"Defaults to 1, meaning that 1 frame per second is detected\/recognized.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"When the video frame rate is 30, 29 frames will be skipped, 1 frame is detected\/recognized."},{"text":" ","type":"text"},{"type":"text","text":"Note: if you set the detection rate greater to or equal to the video frame rate, no frames will be skipped,"},{"text":" ","type":"text"},{"type":"text","text":"the actual detection rate is limited by the video frame rate."},{"type":"text","text":" "},{"type":"text","text":"Note: Usually you set a much lower value here as for the detectionRate property to save energy."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/energySaveDetectionRate"},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"energySaveDetectionRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"energySaveDetectionRate","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration(py)energySaveDetectionRate","title":"energySaveDetectionRate","role":"symbol","symbolKind":"property"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerEnergyConfiguration/energySaveDetectionRate":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration\/energysavedetectionrate","type":"topic","abstract":[{"text":"The rate of detections\/recognitions per second in energy save mode.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to 1, meaning that 1 frame per second is detected\/recognized.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"When the video frame rate is 30, 29 frames will be skipped, 1 frame is detected\/recognized."},{"text":" ","type":"text"},{"text":"Note: if you set the detection rate greater to or equal to the video frame rate, no frames will be skipped,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the actual detection rate is limited by the video frame rate."},{"text":" ","type":"text"},{"text":"Note: Usually you set a much lower value here as for the detectionRate property to save energy.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/energySaveDetectionRate","title":"energySaveDetectionRate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"energySaveDetectionRate"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"energySaveDetectionRate"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerEnergyConfiguration":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"title":"SBSDKBaseScannerEnergyConfiguration","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"The energy management configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"type":"text","text":" "},{"type":"text","text":"‘SBSDKBaseScannerViewController’ and subclasses sport a customizable energy management system."},{"type":"text","text":" "},{"type":"text","text":"Since scanners running on a live video feed can put a lot of load onto the CPU and\/or GPU"},{"text":" ","type":"text"},{"text":"of the device, causing the battery to drain quickly and running the device hot, you can customize the energy","type":"text"},{"type":"text","text":" "},{"text":"consumption using this class by configuring the rate of detections\/recognitions per second in performance mode as","type":"text"},{"type":"text","text":" "},{"text":"well as in energy saving mode.","type":"text"},{"text":" ","type":"text"},{"text":"In performance mode the scanners will be fed with a higher, configurable rate of","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"video frames per second."},{"type":"text","text":" "},{"text":"After a certain, configurable period of inactivity the energy save mode will be engaged and the rate","type":"text"},{"type":"text","text":" "},{"type":"text","text":"of scans will be reduced to a lower (configurable) rate."},{"text":" ","type":"text"},{"type":"text","text":"You can also configure the time of inactivity before the automatic mode switches from performance to energy save mode."},{"type":"text","text":" "},{"text":"Inactivity here means that both of the following conditions are met:","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"energySaveDetectionRate","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"energySaveDetectionRate"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"energySaveDetectionRate"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"energySaveDetectionRate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1energySaveDetectionRate\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1energySaveDetectionRate\/fragments","value":[{"text":"energySaveDetectionRate","kind":"identifier"}]},{"value":"SBSDKBaseScannerEnergyConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/fragments","value":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}