{"sections":[],"abstract":[{"type":"text","text":"Allows to select the balance between result accuracy (precision) and missed barcodes (recall) for linear barcodes."}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatonedconfigurationbase\/onedconfirmationmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatonedconfigurationbase\/onedconfirmationmode"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatOneDConfigurationBase"]]},"metadata":{"title":"oneDConfirmationMode","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"oneDConfirmationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKOneDConfirmationMode","text":"SBSDKOneDConfirmationMode"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatOneDConfigurationBase(py)oneDConfirmationMode","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"oneDConfirmationMode"}]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatOneDConfigurationBase\/oneDConfirmationMode","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"oneDConfirmationMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKOneDConfirmationMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKOneDConfirmationMode"}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is THOROUGH","type":"text"}]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatOneDConfigurationBase":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatOneDConfigurationBase","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatOneDConfigurationBase"}],"abstract":[{"text":"Base class for all linear (1D) barcode configurations.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatonedconfigurationbase","role":"symbol","type":"topic","title":"SBSDKBarcodeFormatOneDConfigurationBase","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatOneDConfigurationBase"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatOneDConfigurationBase/oneDConfirmationMode":{"title":"oneDConfirmationMode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"oneDConfirmationMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKOneDConfirmationMode","text":"SBSDKOneDConfirmationMode","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"oneDConfirmationMode","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatonedconfigurationbase\/onedconfirmationmode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatOneDConfigurationBase\/oneDConfirmationMode","abstract":[{"type":"text","text":"Allows to select the balance between result accuracy (precision) and missed barcodes (recall) for linear barcodes."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOneDConfirmationMode":{"abstract":[{"type":"text","text":"Allows to select the balance between result accuracy (precision) and missed barcodes (recall) for linear barcodes."},{"type":"text","text":" "},{"type":"text","text":"Some barcode types are naturally prone to false positives (e.g. MSI Plessey)."},{"type":"text","text":" "},{"type":"text","text":"For those barcode types false positives can be drastically reduced (precision can be increased) by requiring that multiple scan-lines in the input scan to the same result."},{"type":"text","text":" "},{"type":"text","text":"However, this stronger condition can lead to missed barcodes (lower recall)."},{"type":"text","text":" "},{"type":"text","text":"Confirmation is avoided for barcode types, which are by design resistant to false positives, (e.g. Code128) to maximize recall."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode","title":"SBSDKOneDConfirmationMode","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"oneDConfirmationMode","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"oneDConfirmationMode"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode","text":"SBSDKOneDConfirmationMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKOneDConfirmationMode","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"oneDConfirmationMode","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKBarcodeFormatOneDConfigurationBase","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatOneDConfigurationBase"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/fragments","op":"replace"},{"value":[{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/navigatorTitle","op":"replace"},{"value":"oneDConfirmationMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatOneDConfigurationBase~1oneDConfirmationMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"oneDConfirmationMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatOneDConfigurationBase~1oneDConfirmationMode\/fragments","op":"replace"},{"value":"SBSDKOneDConfirmationMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode\/title","op":"replace"},{"value":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKOneDConfirmationMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode\/navigatorTitle","op":"replace"}]}]}