{"kind":"symbol","abstract":[{"type":"text","text":"A string (list) of accepted characters during text recognition."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowedSymbols"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If empty or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", all characters are accepted."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"allowedSymbols","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowedSymbols"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerStep(py)allowedSymbols","role":"symbol","navigatorTitle":[{"text":"allowedSymbols","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStep"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStep\/allowedSymbols","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerstep\/allowedsymbols"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerstep\/allowedsymbols"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerStep":{"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerstep","navigatorTitle":[{"text":"SBSDKUITextDataScannerStep","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStep","abstract":[{"type":"text","text":"Defines a single workflow step of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","isActive":true},{"type":"text","text":" flow."}],"role":"symbol","title":"SBSDKUITextDataScannerStep","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUITextDataScannerStep","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController":{"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize and validate a small rectangular text area in realtime."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller","title":"SBSDKUITextDataScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerStep/allowedSymbols":{"title":"allowedSymbols","abstract":[{"type":"text","text":"A string (list) of accepted characters during text recognition."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStep\/allowedSymbols","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerstep\/allowedsymbols","navigatorTitle":[{"kind":"identifier","text":"allowedSymbols"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowedSymbols"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"allowedSymbols","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"allowedSymbols"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"allowedSymbols","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUITextDataScannerStep","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStep\/title"},{"value":[{"kind":"identifier","text":"SBSDKUITextDataScannerStep"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStep\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUITextDataScannerStep"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStep\/navigatorTitle"},{"value":"SBSDKUITextDataScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/title"},{"value":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/navigatorTitle"},{"value":"allowedSymbols","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStep~1allowedSymbols\/title"},{"value":[{"kind":"identifier","text":"allowedSymbols"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStep~1allowedSymbols\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}