{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAnimating"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgradientpolygonview\/isanimating"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgradientpolygonview\/isanimating"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the view is currently animating, ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" otherwise."}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGradientPolygonView(py)isAnimating","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAnimating"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isAnimating","kind":"identifier"}],"title":"isAnimating","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView\/isAnimating"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonView/isAnimating":{"navigatorTitle":[{"kind":"identifier","text":"isAnimating"}],"url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonview\/isanimating","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isAnimating","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","abstract":[{"type":"text","text":"Returns "},{"code":"true","type":"codeVoice"},{"text":" if the view is currently animating, ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView\/isAnimating","title":"isAnimating","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonView":{"navigatorTitle":[{"text":"SBSDKGradientPolygonView","kind":"identifier"}],"abstract":[{"text":"A view that displays a polygon (bezier path) stroked with a gradient. The gradient can be animated and the drawing style is customizable.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGradientPolygonView"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonview","title":"SBSDKGradientPolygonView","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isAnimating"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"isAnimating","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isAnimating","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView~1isAnimating\/title","value":"isAnimating"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView~1isAnimating\/fragments","op":"replace","value":[{"text":"isAnimating","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView\/title","value":"SBSDKGradientPolygonView"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView\/fragments","op":"replace","value":[{"text":"SBSDKGradientPolygonView","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKGradientPolygonView"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView\/navigatorTitle","op":"replace"}]}]}