{"kind":"symbol","metadata":{"title":"init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerZoomConfiguration(im)init","roleHeading":"Instance Method","navigatorTitle":[{"text":"init","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration\/init","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerzoomconfiguration\/init"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerZoomConfiguration":{"type":"topic","title":"SBSDKBaseScannerZoomConfiguration","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration","abstract":[{"text":"The zoom configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"},{"text":" ","type":"text"},{"text":"‘SBSDKBaseScannerViewController’ and subclasses allow the user to zoom the camera.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This class lets you customize the zooming user experience."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerzoomconfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerZoomConfiguration/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration\/init","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerzoomconfiguration\/init","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration\/title","value":"SBSDKBaseScannerZoomConfiguration","op":"replace"},{"value":[{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerZoomConfiguration"}]}]}]}