{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prescriptions"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription","kind":"typeIdentifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription"},{"kind":"text","text":"]? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Prescription."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/prescriptions","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheading\/prescriptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheading\/prescriptions"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"prescriptions","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription"},{"text":"]?","kind":"text"}],"symbolKind":"property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentDEMedicalPlanSubheading(py)prescriptions","navigatorTitle":[{"kind":"identifier","text":"prescriptions"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Property","role":"symbol","title":"prescriptions"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.1"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlanSubheading":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheading"}],"title":"SBSDKBarcodeDocumentDEMedicalPlanSubheading","type":"topic","abstract":[{"type":"text","text":"Subheading."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheading"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheading","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription":{"title":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Prescription."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheadingprescription","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlanSubheading/prescriptions":{"title":"prescriptions","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheading\/prescriptions","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"prescriptions","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"prescriptions","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheading\/prescriptions","abstract":[{"type":"text","text":"Prescription."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"prescriptions","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"prescriptions"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"prescriptions"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading\/title","value":"SBSDKBarcodeDocumentDEMedicalPlanSubheading","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheading"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeDocumentDEMedicalPlanSubheading","kind":"identifier"}]},{"value":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription"}]},{"value":[{"text":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription\/navigatorTitle"},{"value":"prescriptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading~1prescriptions\/title"},{"op":"replace","value":[{"text":"prescriptions","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheading~1prescriptions\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}