{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/review","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/review\/alerts"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/review\/alerts\/delete","interfaceLanguage":"swift"},"metadata":{"symbolKind":"class","title":"SBSDKUI2DocumentScannerAccessibility.review.alerts.delete","roleHeading":"Class","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"s:25ScanbotDocumentScannerSDK08SBSDKUI2bC13AccessibilityC6reviewC6alertsC6deleteC","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delete","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"delete"}]},"topicSections":[{"generated":true,"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/review\/alerts\/delete\/cancel","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/review\/alerts\/delete\/delete","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/review\/alerts\/delete\/deleteAndRetake"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"delete"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneraccessibility\/review\/alerts\/delete"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerAccessibility/review":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/review","title":"SBSDKUI2DocumentScannerAccessibility.review","navigatorTitle":[{"kind":"identifier","text":"review"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"review","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneraccessibility\/review"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerAccessibility":{"kind":"symbol","abstract":[{"type":"text","text":"Accessibility identifiers to be used in UI tests for the document scanner RTU-UI V2."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility","title":"SBSDKUI2DocumentScannerAccessibility","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerAccessibility"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerAccessibility"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneraccessibility"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerAccessibility/review/alerts/delete/cancel":{"title":"cancel","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/review\/alerts\/delete\/cancel","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneraccessibility\/review\/alerts\/delete\/cancel","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancel"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerAccessibility/review/alerts/delete/deleteAndRetake":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/review\/alerts\/delete\/deleteAndRetake","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deleteAndRetake"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneraccessibility\/review\/alerts\/delete\/deleteandretake","type":"topic","role":"symbol","title":"deleteAndRetake","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerAccessibility/review/alerts":{"title":"SBSDKUI2DocumentScannerAccessibility.review.alerts","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/review\/alerts","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneraccessibility\/review\/alerts","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alerts"}],"type":"topic","navigatorTitle":[{"text":"alerts","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerAccessibility/review/alerts/delete/delete":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"delete","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"delete","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneraccessibility\/review\/alerts\/delete\/delete","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/review\/alerts\/delete\/delete"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerAccessibility/review/alerts/delete":{"navigatorTitle":[{"text":"delete","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delete"}],"abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneraccessibility\/review\/alerts\/delete","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/review\/alerts\/delete","title":"SBSDKUI2DocumentScannerAccessibility.review.alerts.delete"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2DocumentScannerAccessibility","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerAccessibility\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerAccessibility"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerAccessibility\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerAccessibility\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2DocumentScannerAccessibility","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}