{"metadata":{"title":"traitCollectionDidChange:","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUICameraViewController(im)traitCollectionDidChange:","navigatorTitle":[{"text":"traitCollectionDidChange:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"traitCollectionDidChange:","kind":"identifier"}],"roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuicameraviewcontroller\/traitcollectiondidchange:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController\/traitCollectionDidChange:"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"traitCollectionDidChange:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"previousTraitCollection"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUICameraViewController/traitCollectionDidChange:":{"navigatorTitle":[{"text":"traitCollectionDidChange:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"traitCollectionDidChange:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController\/traitCollectionDidChange:","abstract":[],"kind":"symbol","title":"traitCollectionDidChange:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuicameraviewcontroller\/traitcollectiondidchange:","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","kind":"symbol","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIViewController":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewController","type":"topic","role":"symbol","abstract":[{"text":"An abstract base class for RTU-UI view controllers.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIViewController","kind":"identifier"}],"title":"SBSDKUIViewController","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuiviewcontroller"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUICameraViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICameraViewController"}],"role":"symbol","abstract":[{"type":"text","text":"A "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewController","isActive":true,"type":"reference"},{"type":"text","text":" subclass which adds support for enabled and disabled camera permission."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController","title":"SBSDKUICameraViewController","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuicameraviewcontroller","navigatorTitle":[{"text":"SBSDKUICameraViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUIViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIViewController"}]},{"value":[{"text":"SBSDKUIViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/navigatorTitle"},{"op":"replace","value":"SBSDKUICameraViewController","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController\/title"},{"value":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController\/fragments","op":"replace"},{"value":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController\/navigatorTitle"}]}]}