{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalBillingInformation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2swissqrcodedocumentfieldtype\/additionalbillinginformation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2swissqrcodedocumentfieldtype\/additionalbillinginformation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/additionalBillingInformation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Additional Billing Information"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalBillingInformation"}],"title":"SBSDKUI2SwissQRCodeDocumentFieldType.additionalBillingInformation","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2SwissQRCodeDocumentFieldType@SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalBillingInformation","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalBillingInformation"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SwissQRCodeDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SwissQRCodeDocumentFieldType/additionalBillingInformation":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.additionalBillingInformation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalBillingInformation"}],"abstract":[{"type":"text","text":"Additional Billing Information"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/additionalBillingInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalBillingInformation"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2swissqrcodedocumentfieldtype\/additionalbillinginformation"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SwissQRCodeDocumentFieldType":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}],"abstract":[{"type":"text","text":"Swiss QR Code Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SwissQRCodeDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2swissqrcodedocumentfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalBillingInformation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalBillingInformation"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalBillingInformation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1additionalBillingInformation\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalBillingInformation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1additionalBillingInformation\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalBillingInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SwissQRCodeDocumentFieldType\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SwissQRCodeDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}