{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debtorPlace"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2swissqrcodedocumentfieldtype\/debtorplace"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2swissqrcodedocumentfieldtype\/debtorplace"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorPlace","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Debtor Place"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debtorPlace"}],"title":"SBSDKUI2SwissQRCodeDocumentFieldType.debtorPlace","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2SwissQRCodeDocumentFieldType@SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPlace","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPlace"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SwissQRCodeDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SwissQRCodeDocumentFieldType/debtorPlace":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.debtorPlace","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debtorPlace"}],"abstract":[{"type":"text","text":"Debtor Place"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorPlace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPlace"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2swissqrcodedocumentfieldtype\/debtorplace"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SwissQRCodeDocumentFieldType":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}],"abstract":[{"type":"text","text":"Swiss QR Code Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SwissQRCodeDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2swissqrcodedocumentfieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPlace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPlace"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPlace"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorPlace\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPlace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorPlace\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPlace"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SwissQRCodeDocumentFieldType\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SwissQRCodeDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}