{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"15.0","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"15.0","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"15.0","deprecated":false},{"unavailable":false,"beta":false,"name":"macOS","introducedAt":"12.0","deprecated":false},{"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"15.0","deprecated":false},{"unavailable":false,"beta":false,"name":"watchOS","introducedAt":"8.0","deprecated":false}],"title":"confirmationDialog(_:isPresented:titleVisibility:presenting:actions:)","symbolKind":"method","externalID":"s:7SwiftUI4ViewPAAE18confirmationDialog_11isPresented15titleVisibility10presenting7actionsQrAA18LocalizedStringKeyV_AA7BindingVySbGAA0I0Oqd_0_Sgqd__qd_0_XEtAaBRd__r0_lF::SYNTHESIZED::s:25ScanbotDocumentScannerSDK20SBSDKUI2CroppingViewV","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmationDialog"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"A"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"preciseIdentifier":"s:7SwiftUI18LocalizedStringKeyV","kind":"typeIdentifier","text":"LocalizedStringKey"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isPresented"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI7BindingV","kind":"typeIdentifier","text":"Binding"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"titleVisibility"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI10VisibilityO","kind":"typeIdentifier","text":"Visibility"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presenting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"actions"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"A"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier","text":"View"}],"role":"symbol","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Method","extendedModule":"SwiftUICore"},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingView\/confirmationDialog(_:isPresented:titleVisibility:presenting:actions:)-4p8e3","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmationDialog","kind":"identifier"},{"text":"<","kind":"text"},{"text":"A","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"titleKey","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI18LocalizedStringKeyV","text":"LocalizedStringKey","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isPresented","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"titleVisibility","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI10VisibilityO","text":"Visibility","kind":"typeIdentifier"},{"text":" = .automatic, ","kind":"text"},{"text":"presenting","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:7SwiftUI11ViewBuilderV","text":"ViewBuilder","kind":"attribute"},{"text":" ","kind":"text"},{"text":"actions","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"A","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"A","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"},{"text":"\n","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingview\/confirmationdialog(_:ispresented:titlevisibility:presenting:actions:)-4p8e3"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingView","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingView\/View-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.confirmationDialog(_:isPresented:titleVisibility:presenting:actions:)"},{"type":"text","text":"."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingView/View-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingview\/view-implementations","abstract":[],"title":"View Implementations","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingView\/View-Implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingView/confirmationDialog(_:isPresented:titleVisibility:presenting:actions:)-4p8e3":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmationDialog","kind":"identifier"},{"text":"<","kind":"text"},{"text":"A","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"LocalizedStringKey","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI18LocalizedStringKeyV"},{"text":", ","kind":"text"},{"text":"isPresented","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Binding","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV"},{"text":"<","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":">, ","kind":"text"},{"text":"titleVisibility","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Visibility","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI10VisibilityO"},{"text":", ","kind":"text"},{"text":"presenting","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"actions","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"A","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingView\/confirmationDialog(_:isPresented:titleVisibility:presenting:actions:)-4p8e3","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingview\/confirmationdialog(_:ispresented:titlevisibility:presenting:actions:)-4p8e3","title":"confirmationDialog(_:isPresented:titleVisibility:presenting:actions:)","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingViewController":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CroppingViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingViewController"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller","abstract":[{"text":"A highly customizable view controller to edit the page polygon or the page orientation.","type":"text"}],"title":"SBSDKUI2CroppingViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingView":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingview","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingView","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingView","kind":"identifier"}],"title":"SBSDKUI2CroppingView","navigatorTitle":[{"text":"SBSDKUI2CroppingView","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/title","value":"SBSDKUI2CroppingViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CroppingViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/navigatorTitle","value":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}