{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonEdge"]]},"sections":[],"abstract":[{"text":"The axis-aligned bounding box of the receiver.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonEdge\/boundingBox"},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"boundingBox","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"boundingBox","navigatorTitle":[{"text":"boundingBox","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygonEdge(py)boundingBox"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"boundingBox"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpolygonedge\/boundingbox"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpolygonedge\/boundingbox"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygonEdge":{"title":"SBSDKPolygonEdge","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Helper class that encapsulates an edge of a polygon and provides geometric helper methods."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonEdge","url":"\/documentation\/scanbotsdk\/sbsdkpolygonedge","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygonEdge"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPolygonEdge"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygonEdge/boundingBox":{"abstract":[{"type":"text","text":"The axis-aligned bounding box of the receiver."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"boundingBox"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonEdge\/boundingBox","title":"boundingBox","url":"\/documentation\/scanbotsdk\/sbsdkpolygonedge\/boundingbox","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"boundingBox","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"boundingBox","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"boundingBox","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":" "},{"text":"boundingBox","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKPolygonEdge","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonEdge\/title"},{"value":[{"text":"SBSDKPolygonEdge","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonEdge\/fragments"},{"value":"boundingBox","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonEdge~1boundingBox\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonEdge~1boundingBox\/fragments","value":[{"kind":"identifier","text":"boundingBox"}]}]}]}