{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fileDialogConfirmationLabel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"label","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4TextV","kind":"typeIdentifier","text":"Text"},{"text":"?) -> ","kind":"text"},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"},{"text":"\n","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"platforms":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"17.0"},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"17.0"},{"introducedAt":"17.0","deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"},{"deprecated":false,"beta":false,"name":"macOS","unavailable":false,"introducedAt":"14.0"}],"extendedModule":"SwiftUICore","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fileDialogConfirmationLabel","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:7SwiftUI4TextV","kind":"typeIdentifier","text":"Text"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"title":"fileDialogConfirmationLabel(_:)","externalID":"s:7SwiftUI4ViewPAAE27fileDialogConfirmationLabelyQrAA4TextVSgF::SYNTHESIZED::s:10ScanbotSDK29SBSDKUI2CreditCardScannerViewV","roleHeading":"Instance Method","symbolKind":"method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView\/fileDialogConfirmationLabel(_:)-6fzpe","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView\/View-Implementations"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerview\/filedialogconfirmationlabel(_:)-6fzpe"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"View.fileDialogConfirmationLabel(_:)"},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerView/fileDialogConfirmationLabel(_:)-6fzpe":{"title":"fileDialogConfirmationLabel(_:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerview\/filedialogconfirmationlabel(_:)-6fzpe","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView\/fileDialogConfirmationLabel(_:)-6fzpe","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fileDialogConfirmationLabel","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4TextV","text":"Text"},{"kind":"text","text":"?) -> "},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"type":"topic","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardScannerViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2CreditCardScannerViewController","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerviewcontroller","title":"SBSDKUI2CreditCardScannerViewController","abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to scan credit card data."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerView":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CreditCardScannerView","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerView"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerview","abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerViewController"},{"text":".","type":"text"}],"title":"SBSDKUI2CreditCardScannerView","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerView/View-Implementations":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerview\/view-implementations","role":"collectionGroup","title":"View Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView\/View-Implementations","kind":"article","abstract":[]}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2CreditCardScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerViewController\/fragments","value":[{"text":"SBSDKUI2CreditCardScannerViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}