{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"style"},{"kind":"text","text":": some "},{"preciseIdentifier":"s:7SwiftUI20NavigationTransitionP","kind":"typeIdentifier","text":"NavigationTransition"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier","text":"View"},{"kind":"text","text":"\n"}]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"View.navigationTransition(_:)","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerview\/navigationtransition(_:)"]}],"sections":[],"metadata":{"role":"symbol","platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","beta":false,"introducedAt":"18.0"},{"deprecated":false,"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"18.0"},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"18.0"},{"deprecated":false,"unavailable":false,"name":"macOS","beta":false,"introducedAt":"15.0"},{"deprecated":false,"unavailable":false,"name":"tvOS","beta":false,"introducedAt":"18.0"},{"deprecated":false,"unavailable":false,"name":"visionOS","beta":false,"introducedAt":"2.0"},{"deprecated":false,"unavailable":false,"name":"watchOS","beta":false,"introducedAt":"11.0"}],"modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}],"roleHeading":"Instance Method","externalID":"s:7SwiftUI4ViewPAAE20navigationTransitionyQrqd__AA010NavigationE0Rd__lF::SYNTHESIZED::s:10ScanbotSDK29SBSDKUI2CreditCardScannerViewV","extendedModule":"SwiftUICore","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navigationTransition","kind":"identifier"},{"text":"(some ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI20NavigationTransitionP","text":"NavigationTransition","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"symbolKind":"method","title":"navigationTransition(_:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView\/View-Implementations"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView\/navigationTransition(_:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerView":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView","role":"symbol","title":"SBSDKUI2CreditCardScannerView","abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerViewController"},{"type":"text","text":"."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardScannerView","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2CreditCardScannerView","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerview"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerViewController":{"navigatorTitle":[{"text":"SBSDKUI2CreditCardScannerViewController","kind":"identifier"}],"title":"SBSDKUI2CreditCardScannerViewController","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to scan credit card data."}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerView/navigationTransition(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView\/navigationTransition(_:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerview\/navigationtransition(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationTransition"},{"kind":"text","text":"(some "},{"kind":"typeIdentifier","text":"NavigationTransition","preciseIdentifier":"s:7SwiftUI20NavigationTransitionP"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"title":"navigationTransition(_:)","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerView/View-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerview\/view-implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView\/View-Implementations","kind":"article","title":"View Implementations","abstract":[],"role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2CreditCardScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerViewController\/title","op":"replace"},{"value":[{"text":"SBSDKUI2CreditCardScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerViewController\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2CreditCardScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerViewController\/navigatorTitle","op":"replace"}]}]}