{"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Determines whether a landscape document will be detected when the camera is in portrait mode (and vice versa) or"},{"text":" ","type":"text"},{"text":"not. This parameter will be ignored if required aspect ratios have been explicitly defined.","type":"text"},{"text":" ","type":"text"},{"text":"Default is true","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration\/ignoreBadAspectRatio","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignoreBadAspectRatio"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration"]]},"metadata":{"navigatorTitle":[{"text":"ignoreBadAspectRatio","kind":"identifier"}],"title":"ignoreBadAspectRatio","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration(py)ignoreBadAspectRatio","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ignoreBadAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration\/ignorebadaspectratio"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration\/ignorebadaspectratio"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerCameraConfiguration/ignoreBadAspectRatio":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ignoreBadAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"ignoreBadAspectRatio"}],"title":"ignoreBadAspectRatio","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration\/ignorebadaspectratio","abstract":[{"text":"Determines whether a landscape document will be detected when the camera is in portrait mode (and vice versa) or","type":"text"},{"type":"text","text":" "},{"type":"text","text":"not. This parameter will be ignored if required aspect ratios have been explicitly defined."},{"type":"text","text":" "},{"text":"Default is true","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration\/ignoreBadAspectRatio","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerCameraConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the camera behavior."}],"title":"SBSDKUI2DocumentScannerCameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ignoreBadAspectRatio"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ignoreBadAspectRatio"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ignoreBadAspectRatio"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration~1ignoreBadAspectRatio\/title","value":"ignoreBadAspectRatio"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration~1ignoreBadAspectRatio\/fragments","op":"replace","value":[{"text":"ignoreBadAspectRatio","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/title","op":"replace","value":"SBSDKUI2DocumentScannerCameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerCameraConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerCameraConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}