{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration\/init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration"]]},"metadata":{"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cameraModule"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule","text":"SBSDKUI2CameraModule"},{"text":", ","kind":"text"},{"text":"defaultZoomFactor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"flashEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minFocusDistanceLock"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"pinchToZoomEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode","text":"SBSDKUI2CameraPreviewMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"captureQualityPrioritization","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization"},{"kind":"text","text":", "},{"kind":"externalParam","text":"acceptedAngleScore"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"acceptedSizeScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoSnappingSensitivity"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"autoSnappingDelay","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"acceptedBrightnessThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoSnappingEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"requiredAspectRatios","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AspectRatio","kind":"typeIdentifier","text":"SBSDKUI2AspectRatio"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"ignoreBadAspectRatio"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration(im)initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:","roleHeading":"Initializer","role":"symbol","title":"init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration\/init(cameramodule:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:camerapreviewmode:capturequalityprioritization:acceptedanglescore:acceptedsizescore:autosnappingsensitivity:autosnappingdelay:acceptedbrightnessthresho-9mj0u"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration\/init(cameramodule:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:camerapreviewmode:capturequalityprioritization:acceptedanglescore:acceptedsizescore:autosnappingsensitivity:autosnappingdelay:acceptedbrightnessthresho-9mj0u"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"cameraModule","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraModule","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule"},{"kind":"text","text":" = SBSDKUI2CameraModule.back, "},{"text":"defaultZoomFactor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = 1.0, "},{"text":"flashEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"minFocusDistanceLock","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"text":"pinchToZoomEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = true, ","kind":"text"},{"text":"cameraPreviewMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode","kind":"typeIdentifier","text":"SBSDKUI2CameraPreviewMode"},{"text":" = SBSDKUI2CameraPreviewMode.fillIn, ","kind":"text"},{"kind":"externalParam","text":"captureQualityPrioritization"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization"},{"text":" = SBSDKUI2CapturePhotoQualityPrioritization.balanced, ","kind":"text"},{"kind":"externalParam","text":"acceptedAngleScore"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":" = 0.75, ","kind":"text"},{"text":"acceptedSizeScore","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":" = 0.75, ","kind":"text"},{"text":"autoSnappingSensitivity","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = 0.66, "},{"kind":"externalParam","text":"autoSnappingDelay"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":" = 200, ","kind":"text"},{"text":"acceptedBrightnessThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":" = 50, ","kind":"text"},{"kind":"externalParam","text":"autoSnappingEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = true, ","kind":"text"},{"text":"requiredAspectRatios","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AspectRatio","text":"SBSDKUI2AspectRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AspectRatio"},{"text":"] = [], ","kind":"text"},{"kind":"externalParam","text":"ignoreBadAspectRatio"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = true)"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraModule":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule","title":"SBSDKUI2CameraModule","url":"\/documentation\/scanbotsdk\/sbsdkui2cameramodule","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraModule"}],"role":"symbol","abstract":[{"type":"text","text":"Determine which camera module to use on start-up."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization":{"title":"SBSDKUI2CapturePhotoQualityPrioritization","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization","kind":"symbol","type":"topic","abstract":[{"text":"Determines the prioritization of still image quality and capturing speed. iOS only.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerCameraConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerCameraConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration","type":"topic","title":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerCameraConfiguration"}],"abstract":[{"text":"Configuration of the camera behavior.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPreviewMode":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerapreviewmode","title":"SBSDKUI2CameraPreviewMode","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the camera preview mode."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerCameraConfiguration/init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:)":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration\/init(cameramodule:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:camerapreviewmode:capturequalityprioritization:acceptedanglescore:acceptedsizescore:autosnappingsensitivity:autosnappingdelay:acceptedbrightnessthresho-9mj0u","navigatorTitle":[{"text":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration\/init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cameraModule"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule"},{"kind":"text","text":", "},{"text":"defaultZoomFactor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"flashEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minFocusDistanceLock"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pinchToZoomEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewMode"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"captureQualityPrioritization"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"acceptedAngleScore","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"text":"acceptedSizeScore","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"autoSnappingSensitivity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"text":"autoSnappingDelay","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"acceptedBrightnessThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"autoSnappingEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"requiredAspectRatios","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SBSDKUI2AspectRatio","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AspectRatio","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"ignoreBadAspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"title":"init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AspectRatio":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AspectRatio","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AspectRatio"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aspectratio","type":"topic","title":"SBSDKUI2AspectRatio","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AspectRatio"}],"abstract":[{"text":"Configuration of the finder’s aspect ratio.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCameraModule:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2CameraModule","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule"},{"kind":"text","text":") "},{"text":"cameraModule","kind":"internalParam"},{"kind":"text","text":" "},{"text":"defaultZoomFactor:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"defaultZoomFactor"},{"text":" ","kind":"text"},{"text":"flashEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"flashEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"text":"minFocusDistanceLock:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"minFocusDistanceLock","kind":"internalParam"},{"kind":"text","text":" "},{"text":"pinchToZoomEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"pinchToZoomEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPreviewMode:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode","kind":"typeIdentifier","text":"SBSDKUI2CameraPreviewMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode"},{"kind":"text","text":") "},{"text":"cameraPreviewMode","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"captureQualityPrioritization:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization"},{"text":") ","kind":"text"},{"text":"captureQualityPrioritization","kind":"internalParam"},{"kind":"text","text":" "},{"text":"acceptedAngleScore:","kind":"identifier"},{"kind":"text","text":"("},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"acceptedAngleScore"},{"kind":"text","text":" "},{"text":"acceptedSizeScore:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":") ","kind":"text"},{"text":"acceptedSizeScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"autoSnappingSensitivity:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"text":"autoSnappingSensitivity","kind":"internalParam"},{"kind":"text","text":" "},{"text":"autoSnappingDelay:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"autoSnappingDelay"},{"text":" ","kind":"text"},{"text":"acceptedBrightnessThreshold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"acceptedBrightnessThreshold"},{"text":" ","kind":"text"},{"text":"autoSnappingEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"autoSnappingEnabled"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredAspectRatios:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKUI2AspectRatio *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"requiredAspectRatios","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ignoreBadAspectRatio:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"ignoreBadAspectRatio"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUI2CameraModule","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/fragments","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2CapturePhotoQualityPrioritization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/title"},{"op":"replace","value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/title","value":"SBSDKUI2DocumentScannerCameraConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/fragments","value":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2CameraPreviewMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/title"},{"value":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/fragments"},{"value":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration~1init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration~1init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AspectRatio\/title","value":"SBSDKUI2AspectRatio","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AspectRatio\/fragments","value":[{"text":"SBSDKUI2AspectRatio","kind":"identifier"}],"op":"replace"}]}]}