{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration(im)initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"cameraModule","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule","kind":"typeIdentifier","text":"SBSDKUI2CameraModule"},{"text":", ","kind":"text"},{"text":"defaultZoomFactor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"flashEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"minFocusDistanceLock","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"pinchToZoomEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"cameraPreviewMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode","text":"SBSDKUI2CameraPreviewMode"},{"kind":"text","text":", "},{"text":"captureQualityPrioritization","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"acceptedAngleScore"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"acceptedSizeScore","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"autoSnappingSensitivity","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"autoSnappingDelay","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"acceptedBrightnessThreshold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"autoSnappingEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"requiredAspectRatios","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AspectRatio","text":"SBSDKUI2AspectRatio"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"ignoreBadAspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"captureWithHardwareButtonsEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init","roleHeading":"Initializer","title":"init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)","navigatorTitle":[{"text":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"cameraModule","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2CameraModule","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule"},{"kind":"text","text":" = SBSDKUI2CameraModule.back, "},{"kind":"externalParam","text":"defaultZoomFactor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = 1.0, "},{"kind":"externalParam","text":"flashEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"text":"minFocusDistanceLock","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"text":"pinchToZoomEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = true, ","kind":"text"},{"text":"cameraPreviewMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode","text":"SBSDKUI2CameraPreviewMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode"},{"text":" = SBSDKUI2CameraPreviewMode.fillIn, ","kind":"text"},{"kind":"externalParam","text":"captureQualityPrioritization"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization","kind":"typeIdentifier"},{"text":" = SBSDKUI2CapturePhotoQualityPrioritization.balanced, ","kind":"text"},{"kind":"externalParam","text":"acceptedAngleScore"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":" = 0.75, ","kind":"text"},{"text":"acceptedSizeScore","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":" = 0.75, "},{"text":"autoSnappingSensitivity","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":" = 0.66, ","kind":"text"},{"text":"autoSnappingDelay","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":" = 200, ","kind":"text"},{"text":"acceptedBrightnessThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" = 50, ","kind":"text"},{"text":"autoSnappingEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"requiredAspectRatios"},{"kind":"text","text":": ["},{"text":"SBSDKUI2AspectRatio","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AspectRatio","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AspectRatio","kind":"typeIdentifier"},{"text":"] = [], ","kind":"text"},{"text":"ignoreBadAspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"captureWithHardwareButtonsEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = true)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration\/init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration\/init(cameramodule:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:camerapreviewmode:capturequalityprioritization:acceptedanglescore:acceptedsizescore:autosnappingsensitivity:autosnappingdelay:acceptedbrightnessthresho-buha"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration\/init(cameramodule:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:camerapreviewmode:capturequalityprioritization:acceptedanglescore:acceptedsizescore:autosnappingsensitivity:autosnappingdelay:acceptedbrightnessthresho-buha"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerCameraConfiguration/init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:"}],"abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cameraModule"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule"},{"kind":"text","text":", "},{"text":"defaultZoomFactor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"flashEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minFocusDistanceLock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"pinchToZoomEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraPreviewMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode"},{"text":", ","kind":"text"},{"text":"captureQualityPrioritization","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"acceptedAngleScore","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"acceptedSizeScore","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"autoSnappingSensitivity"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"autoSnappingDelay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"acceptedBrightnessThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoSnappingEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requiredAspectRatios"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AspectRatio","kind":"typeIdentifier","text":"SBSDKUI2AspectRatio"},{"kind":"text","text":"], "},{"text":"ignoreBadAspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"captureWithHardwareButtonsEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration\/init(cameramodule:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:camerapreviewmode:capturequalityprioritization:acceptedanglescore:acceptedsizescore:autosnappingsensitivity:autosnappingdelay:acceptedbrightnessthresho-buha","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration\/init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)","title":"init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization":{"url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"title":"SBSDKUI2CapturePhotoQualityPrioritization","abstract":[{"text":"Determines the prioritization of still image quality and capturing speed.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPreviewMode":{"type":"topic","abstract":[{"type":"text","text":"Configuration of the camera preview mode."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode","title":"SBSDKUI2CameraPreviewMode","url":"\/documentation\/scanbotsdk\/sbsdkui2camerapreviewmode","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraModule":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2cameramodule","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule","title":"SBSDKUI2CameraModule","abstract":[{"text":"Determine which camera module to use on start-up.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraModule"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerCameraConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the camera behavior."}],"title":"SBSDKUI2DocumentScannerCameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AspectRatio":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2AspectRatio","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aspectratio","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AspectRatio"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AspectRatio","abstract":[{"text":"Configuration of the finder’s aspect ratio.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","title":"SBSDKUI2AspectRatio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCameraModule:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule","text":"SBSDKUI2CameraModule","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cameraModule","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"defaultZoomFactor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"defaultZoomFactor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"flashEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"flashEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minFocusDistanceLock:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"minFocusDistanceLock"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pinchToZoomEnabled:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"pinchToZoomEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPreviewMode:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraPreviewMode"},{"text":" ","kind":"text"},{"text":"captureQualityPrioritization:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2CapturePhotoQualityPrioritization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization"},{"kind":"text","text":") "},{"kind":"internalParam","text":"captureQualityPrioritization"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptedAngleScore:"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"acceptedAngleScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"acceptedSizeScore:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"acceptedSizeScore"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSnappingSensitivity:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"autoSnappingSensitivity","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"autoSnappingDelay:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"autoSnappingDelay","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptedBrightnessThreshold:"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"acceptedBrightnessThreshold"},{"text":" ","kind":"text"},{"text":"autoSnappingEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"autoSnappingEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredAspectRatios:"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKUI2AspectRatio *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"requiredAspectRatios","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ignoreBadAspectRatio:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"ignoreBadAspectRatio"},{"text":" ","kind":"text"},{"kind":"identifier","text":"captureWithHardwareButtonsEnabled:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"captureWithHardwareButtonsEnabled","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration~1init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration~1init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)\/fragments"},{"op":"replace","value":"SBSDKUI2CapturePhotoQualityPrioritization","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/navigatorTitle","value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/title","value":"SBSDKUI2CameraPreviewMode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/navigatorTitle"},{"value":"SBSDKUI2CameraModule","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/title","op":"replace"},{"value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraModule"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/title","value":"SBSDKUI2DocumentScannerCameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerCameraConfiguration"}]},{"value":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AspectRatio\/title","value":"SBSDKUI2AspectRatio","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2AspectRatio"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AspectRatio\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AspectRatio\/navigatorTitle","value":[{"text":"SBSDKUI2AspectRatio","kind":"identifier"}],"op":"replace"}]}]}