{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"text":"Same as ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/decodeStructure"},{"type":"text","text":", but with full validation."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgs1handling\/decodefull"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgs1handling\/decodefull"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/decodeFull","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodeFull"}]}],"kind":"declarations"}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"SBSDKGS1HandlingDecodeFull","kind":"identifier"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodeFull"}],"role":"symbol","title":"SBSDKGS1Handling.decodeFull","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKGS1Handling@SBSDKGS1HandlingDecodeFull"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGS1Handling"}],"url":"\/documentation\/scanbotsdk\/sbsdkgs1handling","abstract":[{"text":"GS1 message handling options. The GS1 standard defines a","type":"text"},{"type":"text","text":" "},{"text":"a key-value format for business-centric data","type":"text"},{"text":" ","type":"text"},{"text":"that can be encoded into many 1D and 2D barcode types.","type":"text"},{"text":" ","type":"text"},{"text":"https:\/\/ref.gs1.org\/standards\/genspecs\/","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"title":"SBSDKGS1Handling"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling/decodeFull":{"url":"\/documentation\/scanbotsdk\/sbsdkgs1handling\/decodefull","title":"SBSDKGS1Handling.decodeFull","type":"topic","navigatorTitle":[{"text":"SBSDKGS1HandlingDecodeFull","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeFull"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/decodeFull","abstract":[{"type":"text","text":"Same as "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/decodeStructure","isActive":true},{"text":", but with full validation.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling/decodeStructure":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgs1handling\/decodestructure","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/decodeStructure","kind":"symbol","role":"symbol","title":"SBSDKGS1Handling.decodeStructure","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeStructure"}],"navigatorTitle":[{"text":"SBSDKGS1HandlingDecodeStructure","kind":"identifier"}],"abstract":[{"text":"Same as ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/validateStructure","isActive":true,"type":"reference"},{"type":"text","text":", except that GS1 strings are converted to the human-readable"},{"type":"text","text":" "},{"text":"format, instead (with parentheses used to wrap AI keys, e.g. “(01)123456789”).","type":"text"},{"type":"text","text":" "},{"text":"The \\x1D character is never used in this representation.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling/validateStructure":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/validateStructure","abstract":[{"text":"Same as ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/parse"},{"text":". Additionally, messages containing unknown AI keys, or containing values","type":"text"},{"type":"text","text":" "},{"type":"text","text":"of incorrect format for known keys, are not returned."}],"title":"SBSDKGS1Handling.validateStructure","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgs1handling\/validatestructure","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"validateStructure","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1HandlingValidateStructure"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKGS1HandlingDecodeFull"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKGS1HandlingDecodeFull"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKGS1HandlingDecodeFull","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/title","value":"SBSDKGS1Handling"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/fragments","value":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/navigatorTitle","value":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1decodeFull\/title","value":"SBSDKGS1HandlingDecodeFull","op":"replace"},{"value":[{"text":"SBSDKGS1HandlingDecodeFull","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1decodeFull\/fragments"},{"value":"SBSDKGS1HandlingDecodeStructure","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1decodeStructure\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1decodeStructure\/fragments","value":[{"text":"SBSDKGS1HandlingDecodeStructure","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1validateStructure\/title","value":"SBSDKGS1HandlingValidateStructure"},{"value":[{"kind":"identifier","text":"SBSDKGS1HandlingValidateStructure"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1validateStructure\/fragments"}]}]}