{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"languages"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vcarddocumentformatfieldtype\/languages"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vcarddocumentformatfieldtype\/languages"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VCardDocumentFormatFieldType\/languages","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Languages"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"languages"}],"title":"SBSDKUI2VCardDocumentFormatFieldType.languages","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2VCardDocumentFormatFieldType@SBSDKUI2VCardDocumentFormatFieldTypeLanguages","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldTypeLanguages"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VCardDocumentFormatFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VCardDocumentFormatFieldType/languages":{"role":"symbol","title":"SBSDKUI2VCardDocumentFormatFieldType.languages","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"languages"}],"abstract":[{"type":"text","text":"Languages"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VCardDocumentFormatFieldType\/languages","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldTypeLanguages"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vcarddocumentformatfieldtype\/languages"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VCardDocumentFormatFieldType":{"role":"symbol","title":"SBSDKUI2VCardDocumentFormatFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldType"}],"abstract":[{"type":"text","text":"vCard Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VCardDocumentFormatFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vcarddocumentformatfieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2VCardDocumentFormatFieldTypeLanguages"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldTypeLanguages"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldTypeLanguages"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VCardDocumentFormatFieldType~1languages\/title","value":"SBSDKUI2VCardDocumentFormatFieldTypeLanguages"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VCardDocumentFormatFieldType~1languages\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldTypeLanguages"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VCardDocumentFormatFieldType\/title","value":"SBSDKUI2VCardDocumentFormatFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VCardDocumentFormatFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}