{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"telephoneNumber"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vcarddocumentformatfieldtype\/telephonenumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vcarddocumentformatfieldtype\/telephonenumber"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VCardDocumentFormatFieldType\/telephoneNumber","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Telephone Number"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"telephoneNumber"}],"title":"SBSDKUI2VCardDocumentFormatFieldType.telephoneNumber","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2VCardDocumentFormatFieldType@SBSDKUI2VCardDocumentFormatFieldTypeTelephoneNumber","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldTypeTelephoneNumber"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VCardDocumentFormatFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VCardDocumentFormatFieldType/telephoneNumber":{"role":"symbol","title":"SBSDKUI2VCardDocumentFormatFieldType.telephoneNumber","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"telephoneNumber"}],"abstract":[{"type":"text","text":"Telephone Number"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VCardDocumentFormatFieldType\/telephoneNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldTypeTelephoneNumber"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vcarddocumentformatfieldtype\/telephonenumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.2"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VCardDocumentFormatFieldType":{"role":"symbol","title":"SBSDKUI2VCardDocumentFormatFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldType"}],"abstract":[{"type":"text","text":"vCard Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VCardDocumentFormatFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vcarddocumentformatfieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2VCardDocumentFormatFieldTypeTelephoneNumber"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldTypeTelephoneNumber"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldTypeTelephoneNumber"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VCardDocumentFormatFieldType~1telephoneNumber\/title","value":"SBSDKUI2VCardDocumentFormatFieldTypeTelephoneNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VCardDocumentFormatFieldType~1telephoneNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldTypeTelephoneNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VCardDocumentFormatFieldType\/title","value":"SBSDKUI2VCardDocumentFormatFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VCardDocumentFormatFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2VCardDocumentFormatFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}