{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"uiConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerUIConfiguration","text":"SBSDKUIDocumentScannerUIConfiguration"}]}]}],"abstract":[{"text":"The user interface subconfiguration.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerConfiguration\/uiConfiguration"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerconfiguration\/uiconfiguration"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerconfiguration\/uiconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerConfiguration"]]},"metadata":{"role":"symbol","navigatorTitle":[{"text":"uiConfiguration","kind":"identifier"}],"title":"uiConfiguration","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"uiConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerUIConfiguration"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerConfiguration(py)uiConfiguration"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerUIConfiguration"}],"title":"SBSDKUIDocumentScannerUIConfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration for the user interface of the document scanning screen."}],"navigatorTitle":[{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerConfiguration"}],"type":"topic","title":"SBSDKUIDocumentScannerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerconfiguration","role":"symbol","abstract":[{"type":"text","text":"This class describes the look and feel, the behavior, as well as the textual contents of the detection screen for documents."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerConfiguration/uiConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerConfiguration\/uiConfiguration","navigatorTitle":[{"text":"uiConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","title":"uiConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"uiConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUIDocumentScannerUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerUIConfiguration","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerconfiguration\/uiconfiguration","abstract":[{"text":"The user interface subconfiguration.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"uiConfiguration","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"uiConfiguration"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration","kind":"typeIdentifier","text":"SBSDKUIDocumentScannerUIConfiguration"},{"kind":"text","text":" * "},{"text":"uiConfiguration","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"SBSDKUIDocumentScannerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerUIConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerConfiguration\/title","value":"SBSDKUIDocumentScannerConfiguration","op":"replace"},{"value":[{"text":"SBSDKUIDocumentScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerConfiguration\/fragments","op":"replace"},{"value":"uiConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerConfiguration~1uiConfiguration\/title"},{"value":[{"kind":"identifier","text":"uiConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerConfiguration~1uiConfiguration\/fragments","op":"replace"}]}]}