{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderStyle"]]},"metadata":{"roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderCorneredStyle","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FinderCorneredStyle","text":"SBSDKUI2FinderCorneredStyle"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FinderStyle(cm)finderCorneredStyle","title":"finderCorneredStyle()","navigatorTitle":[{"text":"finderCorneredStyle","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"method"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderCorneredStyle","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKUI2FinderCorneredStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FinderCorneredStyle","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderCorneredStyle"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderStyle\/finderCorneredStyle()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2finderstyle\/findercorneredstyle()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2finderstyle\/findercorneredstyle()"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FinderStyle":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderStyle","type":"topic","abstract":[{"type":"text","text":"Visual appearance of the viewfinder."}],"title":"SBSDKUI2FinderStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2FinderStyle","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2finderstyle","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FinderStyle"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FinderCorneredStyle":{"type":"topic","abstract":[{"type":"text","text":"Variant of the viewfinder displaying only the four corners of the scanning area as user guidance."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2FinderCorneredStyle","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderCorneredStyle","url":"\/documentation\/scanbotsdk\/sbsdkui2findercorneredstyle","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FinderCorneredStyle","kind":"identifier"}],"title":"SBSDKUI2FinderCorneredStyle","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FinderStyle/finderCorneredStyle()":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finderCorneredStyle"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2FinderCorneredStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FinderCorneredStyle"}],"role":"symbol","title":"finderCorneredStyle()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderStyle\/finderCorneredStyle()","navigatorTitle":[{"kind":"identifier","text":"finderCorneredStyle"}],"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2finderstyle\/findercorneredstyle()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"finderCorneredStyle"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"finderCorneredStyle","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2FinderCorneredStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FinderCorneredStyle","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderCorneredStyle"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"finderCorneredStyle"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FinderStyle\/title","value":"SBSDKUI2FinderStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FinderStyle\/fragments","value":[{"text":"SBSDKUI2FinderStyle","kind":"identifier"}]},{"value":"SBSDKUI2FinderCorneredStyle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FinderCorneredStyle\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FinderCorneredStyle\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2FinderCorneredStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FinderStyle~1finderCorneredStyle()\/title","value":"finderCorneredStyle"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"finderCorneredStyle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FinderStyle~1finderCorneredStyle()\/fragments"}]}]}