{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2finderstyle\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderStyle\/isEqual:"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"isEqual:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FinderStyle(im)isEqual:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderStyle"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FinderStyle":{"url":"\/documentation\/scanbotsdk\/sbsdkui2finderstyle","type":"topic","role":"symbol","abstract":[{"text":"The visual appearance of the viewfinder.","type":"text"}],"kind":"symbol","title":"SBSDKUI2FinderStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FinderStyle","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2FinderStyle","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderStyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FinderStyle/isEqual:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2finderstyle\/isequal:","type":"topic","role":"symbol","abstract":[],"kind":"symbol","title":"isEqual:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderStyle\/isEqual:"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FinderStyle\/title","value":"SBSDKUI2FinderStyle","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2FinderStyle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FinderStyle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FinderStyle\/navigatorTitle","value":[{"text":"SBSDKUI2FinderStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}