{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/tiffData(from:completion:)"},"metadata":{"roleHeading":"Instance Method","role":"symbol","title":"tiffData(from:completion:)","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tiffData","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?) -> ())","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"tiffDataFrom:completion:"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriter(im)tiffDataFrom:completion:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tiffData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"text":"images","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?) -> ())"}],"languages":["swift"]}]},{"parameters":[{"name":"images","content":[{"type":"paragraph","inlineContent":[{"text":"The array of images to write into the multipage-TIFF data.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The completion handler that is being called upon completion of the operation and passes the Data or nil otherwise.","type":"text"}]}],"name":"completion"}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"content":[{"inlineContent":[{"type":"text","text":"The encrypter on the receiver is ignored here."}],"type":"paragraph"}],"style":"important","type":"aside","name":"Important"}],"kind":"content"}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/tiffdata(from:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/tiffdata(from:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Asynchronously converts the given images into multipage-TIFF data and returns it.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/tiffData(from:completion:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/tiffdata(from:completion:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/tiffData(from:completion:)","abstract":[{"text":"Asynchronously converts the given images into multipage-TIFF data and returns it.","type":"text"}],"kind":"symbol","role":"symbol","title":"tiffData(from:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tiffData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"], "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?) -> ())","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"tiffDataFrom:completion:"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter":{"type":"topic","title":"SBSDKTIFFImageWriter","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriter"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter","abstract":[{"text":"A class that converts images to (multipage) TIFF images.","type":"text"},{"text":" ","type":"text"},{"text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"When passing an encrypter the generated TIFF images will be encrypted."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKTIFFImageWriter","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.2.1"}],"type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"tiffDataFrom:completion:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tiffDataFrom:completion:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"tiffDataFrom:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<UIImage *>"},{"kind":"text","text":" *) "},{"text":"images","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1tiffData(from:completion:)\/title","op":"replace","value":"tiffDataFrom:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tiffDataFrom:completion:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1tiffData(from:completion:)\/fragments","op":"replace"},{"value":"SBSDKTIFFImageWriter","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}