{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"writeTIFF","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"images"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"], "},{"text":"toFile","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fileURL"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The array of images to write into the multipage-TIFF.","type":"text"}],"type":"paragraph"}],"name":"images"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The file URL to save the TIFF file at.","type":"text"}]}],"name":"fileURL"}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"True"},{"text":" if the operation was successful, ","type":"text"},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise."}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(with:toFile:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Synchronously converts the given images to a multipage-TIFF file and writes it to the specified URL."}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriter(im)writeTIFFWith:toFile:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"writeTIFF","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"method","title":"writeTIFF(with:toFile:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"writeTIFFWith:toFile:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiff(with:tofile:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiff(with:tofile:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFF(with:toFile:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(with:toFile:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiff(with:tofile:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Synchronously converts the given images to a multipage-TIFF file and writes it to the specified URL."}],"title":"writeTIFF(with:toFile:)","navigatorTitle":[{"kind":"identifier","text":"writeTIFFWith:toFile:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeTIFF"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"toFile"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter":{"abstract":[{"type":"text","text":"A class that converts images to (multipage) TIFF images."},{"type":"text","text":" "},{"type":"text","text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc."},{"type":"text","text":" "},{"text":"When passing an encrypter the generated TIFF images will be encrypted.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriter"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTIFFImageWriter"}],"title":"SBSDKTIFFImageWriter"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"writeTIFFWith:toFile:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"writeTIFFWith:toFile:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"writeTIFFWith:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<UIImage *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"images"},{"kind":"text","text":" "},{"kind":"identifier","text":"toFile:"},{"kind":"text","text":"("},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"fileURL"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The array of images to write into the multipage-TIFF.","type":"text"}]}],"name":"images"},{"content":[{"inlineContent":[{"text":"The file URL to save the TIFF file at.","type":"text"}],"type":"paragraph"}],"name":"fileURL"}]}},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"True","type":"codeVoice"},{"type":"text","text":" if the operation was successful, "},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"}]}]},"op":"replace"},{"op":"replace","value":"writeTIFFWith:toFile:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(with:toFile:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writeTIFFWith:toFile:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(with:toFile:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/title","value":"SBSDKTIFFImageWriter","op":"replace"},{"value":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKTIFFImageWriter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/navigatorTitle","op":"replace"}]}]}