{"abstract":[{"type":"text","text":"Asynchronously converts the given images to a multipage-TIFF file and writes it to the specified URL."}],"sections":[],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"writeTIFFWith:toFile:completion:","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriter(im)writeTIFFWith:toFile:completion:","title":"writeTIFF(with:toFile:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeTIFF"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"toFile"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?) -> ())","kind":"text"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method","role":"symbol"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"writeTIFF","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"images"},{"text":": [","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"toFile"},{"kind":"text","text":" "},{"text":"fileURL","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?) -> ())","kind":"text"}]}]},{"parameters":[{"name":"images","content":[{"inlineContent":[{"text":"The array of images to write into the multipage-TIFF.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The file URL to save the TIFF file at.","type":"text"}],"type":"paragraph"}],"name":"fileURL"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The completion handler that is being called upon completion of the operation and passes the file url or nil otherwise.","type":"text"}]}],"name":"completion"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiff(with:tofile:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiff(with:tofile:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(with:toFile:completion:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFF(with:toFile:completion:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiff(with:tofile:completion:)","navigatorTitle":[{"text":"writeTIFFWith:toFile:completion:","kind":"identifier"}],"title":"writeTIFF(with:toFile:completion:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(with:toFile:completion:)","abstract":[{"type":"text","text":"Asynchronously converts the given images to a multipage-TIFF file and writes it to the specified URL."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeTIFF"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"toFile"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?) -> ())","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter","title":"SBSDKTIFFImageWriter","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A class that converts images to (multipage) TIFF images."},{"text":" ","type":"text"},{"text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"When passing an encrypter the generated TIFF images will be encrypted."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"writeTIFFWith:toFile:completion:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"writeTIFFWith:toFile:completion:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"writeTIFFWith:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<UIImage *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"images","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"toFile:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"fileURL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"images","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The array of images to write into the multipage-TIFF."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The file URL to save the TIFF file at."}]}],"name":"fileURL"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handler that is being called upon completion of the operation and passes the file url or nil otherwise."}]}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(with:toFile:completion:)\/title","value":"writeTIFFWith:toFile:completion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"writeTIFFWith:toFile:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(with:toFile:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/title","value":"SBSDKTIFFImageWriter"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/fragments","op":"replace","value":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/navigatorTitle","op":"replace","value":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}]}]}]}