{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagesource\/initwithtype:filepath:"]}],"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:filePath:"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"initWithType:filePath:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageSource(im)initWithType:filePath:","title":"initWithType:filePath:"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSource\/initWithType:filePath:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSource"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithType:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSourceType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageSourceType","kind":"typeIdentifier","text":"SBSDKImageSourceType"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"filePath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"filePath","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSource/initWithType:filePath:":{"navigatorTitle":[{"text":"initWithType:filePath:","kind":"identifier"}],"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithType:filePath:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagesource\/initwithtype:filepath:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSource\/initWithType:filePath:","type":"topic","title":"initWithType:filePath:","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSource":{"kind":"symbol","title":"SBSDKImageSource","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageSource"}],"navigatorTitle":[{"text":"SBSDKImageSource","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagesource","abstract":[{"text":"Description of source from which the ImageRef was created.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSource"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSourceType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageSourceType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSourceType","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSourceType"}],"abstract":[{"type":"text","text":"The type of source which originated the underlying image."}],"url":"\/documentation\/scanbotsdk\/sbsdkimagesourcetype","type":"topic","title":"SBSDKImageSourceType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKImageSource","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSource\/title","op":"replace"},{"value":[{"text":"SBSDKImageSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSource\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSource\/navigatorTitle","value":[{"text":"SBSDKImageSource","kind":"identifier"}]},{"value":"SBSDKImageSourceType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSourceType\/title"},{"value":[{"text":"SBSDKImageSourceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSourceType\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKImageSourceType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSourceType\/navigatorTitle"}]}]}