{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPageImageType"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPageImageType\/documentPreview","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentPreview"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPageImageTypeDocumentPreview"}],"title":"SBSDKScannedPageImageType.documentPreview","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKScannedPageImageType@SBSDKScannedPageImageTypeDocumentPreview","roleHeading":"Case","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPreview","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"A screen-sized preview of the fully processed, rotated, cropped and filtered image."}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpageimagetype\/documentpreview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpageimagetype\/documentpreview"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedPageImageType/documentPreview":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKScannedPageImageTypeDocumentPreview","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpageimagetype\/documentpreview","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPreview","kind":"identifier"}],"title":"SBSDKScannedPageImageType.documentPreview","abstract":[{"text":"A screen-sized preview of the fully processed, rotated, cropped and filtered image.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPageImageType\/documentPreview"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedPageImageType":{"title":"SBSDKScannedPageImageType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedPageImageType","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum representing the different types of images a scanned page has."}],"navigatorTitle":[{"text":"SBSDKScannedPageImageType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPageImageType","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpageimagetype","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKScannedPageImageTypeDocumentPreview"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKScannedPageImageTypeDocumentPreview","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKScannedPageImageTypeDocumentPreview"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPageImageType~1documentPreview\/title","value":"SBSDKScannedPageImageTypeDocumentPreview"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPageImageType~1documentPreview\/fragments","value":[{"kind":"identifier","text":"SBSDKScannedPageImageTypeDocumentPreview"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPageImageType\/title","value":"SBSDKScannedPageImageType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPageImageType\/fragments","value":[{"text":"SBSDKScannedPageImageType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPageImageType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKScannedPageImageType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}