{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewModeFitIn"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"SBSDKUI2CameraPreviewMode.fitIn","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CameraPreviewMode@SBSDKUI2CameraPreviewModeFitIn","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fitIn"}],"role":"symbol","roleHeading":"Case"},"kind":"symbol","abstract":[{"text":"In this mode, the camera preview frames will be scaled to fit inside the layout view size - the full preview","type":"text"},{"text":" ","type":"text"},{"text":"frame content will be visible, but unused edges might appear in the preview layout.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"fitIn","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2camerapreviewmode\/fitin"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2camerapreviewmode\/fitin"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPreviewMode"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPreviewMode\/fitIn","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraPreviewMode":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPreviewMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}],"kind":"symbol","abstract":[{"text":"Configuration of the camera preview mode.","type":"text"}],"title":"SBSDKUI2CameraPreviewMode","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2camerapreviewmode","navigatorTitle":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraPreviewMode/fitIn":{"role":"symbol","abstract":[{"text":"In this mode, the camera preview frames will be scaled to fit inside the layout view size - the full preview","type":"text"},{"text":" ","type":"text"},{"text":"frame content will be visible, but unused edges might appear in the preview layout.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2CameraPreviewModeFitIn","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPreviewMode\/fitIn","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2camerapreviewmode\/fitin","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fitIn"}],"title":"SBSDKUI2CameraPreviewMode.fitIn"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKUI2CameraPreviewModeFitIn","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewModeFitIn"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewModeFitIn"}]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKUI2CameraPreviewMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPreviewMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPreviewMode\/fragments","value":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPreviewMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}],"op":"replace"},{"value":"SBSDKUI2CameraPreviewModeFitIn","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPreviewMode~1fitIn\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPreviewMode~1fitIn\/fragments","value":[{"text":"SBSDKUI2CameraPreviewModeFitIn","kind":"identifier"}],"op":"replace"}]}]}