{"metadata":{"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKDocumentScannerViewControllerDelegate(im)documentScannerViewController:polygonFillColorForStatus:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentScannerViewController"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"polygonFillColorFor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"navigatorTitle":[{"kind":"identifier","text":"documentScannerViewController:polygonFillColorForStatus:"}],"title":"documentScannerViewController(_:polygonFillColorFor:)","symbolKind":"method"},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate\/documentScannerViewController(_:polygonFillColorFor:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(documentScannerViewController:polygonFillColorForStatus:) "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentScannerViewController"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController"},{"text":", ","kind":"text"},{"text":"polygonFillColorFor","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"status","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"controller","content":[{"inlineContent":[{"text":"The document scanner controller that called this function.","type":"text"}],"type":"paragraph"}]},{"name":"status","content":[{"type":"paragraph","inlineContent":[{"text":"The status of the current document detection.","type":"text"}]}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"The fill color for the displayed polygon.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:polygonfillcolorfor:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:polygonfillcolorfor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Optional.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Asks the delegate for the fill color of the polygon that surrounds the detected polygon on the screen, depending on the document detection status."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewControllerDelegate":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}],"abstract":[{"type":"text","text":"The delegate protocol of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}],"title":"SBSDKDocumentScannerViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"title":"SBSDKDocumentScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"abstract":[{"type":"text","text":"A UIViewController subclass to show a camera screen and run a user guiding document detector."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewControllerDelegate/documentScannerViewController(_:polygonFillColorFor:)":{"abstract":[{"text":"Optional.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Asks the delegate for the fill color of the polygon that surrounds the detected polygon on the screen, depending on the document detection status."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:polygonfillcolorfor:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController"},{"text":", ","kind":"text"},{"text":"polygonFillColorFor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"documentScannerViewController:polygonFillColorForStatus:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate\/documentScannerViewController(_:polygonFillColorFor:)","title":"documentScannerViewController(_:polygonFillColorFor:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"documentScannerViewController:polygonFillColorForStatus:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentScannerViewController:polygonFillColorForStatus:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"documentScannerViewController:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":" "},{"text":"polygonFillColorForStatus:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"status"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title","value":"SBSDKDocumentScannerViewController"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments"},{"value":"documentScannerViewController:polygonFillColorForStatus:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate~1documentScannerViewController(_:polygonFillColorFor:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"documentScannerViewController:polygonFillColorForStatus:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate~1documentScannerViewController(_:polygonFillColorFor:)\/fragments"}]}]}