{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:didsamplevideoframe:detectionresult:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:didsamplevideoframe:detectionresult:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentScannerViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController"},{"text":", ","kind":"text"},{"text":"didSampleVideoFrame","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"videoFrameImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"detectionResult","kind":"externalParam"},{"kind":"text","text":" "},{"text":"result","kind":"internalParam"},{"kind":"text","text":": "},{"text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The document scanner controller that called this function."}]}]},{"name":"videoFrameImage","content":[{"inlineContent":[{"type":"text","text":"An UIImage with the contents of the video frame."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The result of the document detection done on this video frame."}],"type":"paragraph"}],"name":"result"}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate\/documentScannerViewController(_:didSampleVideoFrame:detectionResult:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate"]]},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"documentScannerViewController:didSampleVideoFrame:detectionResult:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKDocumentScannerViewControllerDelegate(im)documentScannerViewController:didSampleVideoFrame:detectionResult:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"documentScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSampleVideoFrame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":", ","kind":"text"},{"text":"detectionResult","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"role":"symbol","required":true,"title":"documentScannerViewController(_:didSampleVideoFrame:detectionResult:)","roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Optional."},{"text":" ","type":"text"},{"type":"text","text":"Informs the delegate that the document scanner has processed a video frame. Called on main thread."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorResult":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This class represents the result of a document detection","type":"text"},{"type":"text","text":" "},{"text":"on an image.","type":"text"}],"type":"topic","title":"SBSDKDocumentDetectorResult","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectorresult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewControllerDelegate/documentScannerViewController(_:didSampleVideoFrame:detectionResult:)":{"abstract":[{"text":"Optional.","type":"text"},{"type":"text","text":" "},{"text":"Informs the delegate that the document scanner has processed a video frame. Called on main thread.","type":"text"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentScannerViewController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSampleVideoFrame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"detectionResult","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"documentScannerViewController:didSampleVideoFrame:detectionResult:"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate\/documentScannerViewController(_:didSampleVideoFrame:detectionResult:)","kind":"symbol","title":"documentScannerViewController(_:didSampleVideoFrame:detectionResult:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:didsamplevideoframe:detectionresult:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewControllerDelegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentScannerViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate","type":"topic","abstract":[{"type":"text","text":"The delegate protocol of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"title":"SBSDKDocumentScannerViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"type":"topic","title":"SBSDKDocumentScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller","navigatorTitle":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"abstract":[{"text":"A UIViewController subclass to show a camera screen and run a user guiding document detector.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"documentScannerViewController:didSampleVideoFrame:detectionResult:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentScannerViewController:didSampleVideoFrame:detectionResult:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"documentScannerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"controller"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didSampleVideoFrame:"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"videoFrameImage","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectionResult:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"result"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/title","value":"SBSDKDocumentDetectorResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/fragments","value":[{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate~1documentScannerViewController(_:didSampleVideoFrame:detectionResult:)\/title","value":"documentScannerViewController:didSampleVideoFrame:detectionResult:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate~1documentScannerViewController(_:didSampleVideoFrame:detectionResult:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"documentScannerViewController:didSampleVideoFrame:detectionResult:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate\/title","op":"replace","value":"SBSDKDocumentScannerViewControllerDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title","op":"replace","value":"SBSDKDocumentScannerViewController"},{"value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}