{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate\/documentScannerViewControllerCaptureAnimationConfiguration(_:)"},"abstract":[{"type":"text","text":"Optional."},{"type":"text","text":" "},{"type":"text","text":"Asks the delegate for the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration","isActive":true},{"text":" object if the","type":"text"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/shouldAnimateDocument"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":"."}],"metadata":{"title":"documentScannerViewControllerCaptureAnimationConfiguration(_:)","symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKDocumentScannerViewControllerDelegate(im)documentScannerViewControllerCaptureAnimationConfiguration:","navigatorTitle":[{"text":"documentScannerViewControllerCaptureAnimationConfiguration:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"documentScannerViewControllerCaptureAnimationConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","kind":"typeIdentifier","text":"SBSDKDocumentScannerViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentAnimationConfiguration","text":"SBSDKDocumentAnimationConfiguration"},{"kind":"text","text":"?"}],"required":true,"roleHeading":"Instance Method"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentScannerViewControllerCaptureAnimationConfiguration"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKDocumentAnimationConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentAnimationConfiguration"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The document scanner controller that called this function."}]}],"name":"controller"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration","isActive":true,"type":"reference"},{"type":"text","text":" or "},{"code":"nil","type":"codeVoice"},{"text":" to skip the animation.","type":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontrollercaptureanimationconfiguration(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontrollercaptureanimationconfiguration(_:)"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewControllerDelegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}],"title":"SBSDKDocumentScannerViewControllerDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentScannerViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate","role":"symbol","abstract":[{"text":"The delegate protocol of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController"},{"type":"text","text":"."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentAnimationConfiguration":{"abstract":[{"text":"A class to configure the document animation properties.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentanimationconfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentAnimationConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentAnimationConfiguration","kind":"identifier"}],"title":"SBSDKDocumentAnimationConfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController/shouldAnimateDocument":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/shouldAnimateDocument","navigatorTitle":[{"text":"shouldAnimateDocument","kind":"identifier"}],"kind":"symbol","title":"shouldAnimateDocument","abstract":[{"type":"text","text":"Whether the document capturing is animated or not."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shouldAnimateDocument","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/shouldanimatedocument","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewControllerDelegate/documentScannerViewControllerCaptureAnimationConfiguration(_:)":{"required":true,"title":"documentScannerViewControllerCaptureAnimationConfiguration(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentScannerViewControllerCaptureAnimationConfiguration:"}],"abstract":[{"type":"text","text":"Optional."},{"text":" ","type":"text"},{"text":"Asks the delegate for the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration"},{"type":"text","text":" object if the"},{"text":" ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/shouldAnimateDocument","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"documentScannerViewControllerCaptureAnimationConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentAnimationConfiguration","text":"SBSDKDocumentAnimationConfiguration"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate\/documentScannerViewControllerCaptureAnimationConfiguration(_:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontrollercaptureanimationconfiguration(_:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","navigatorTitle":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"title":"SBSDKDocumentScannerViewController","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller","role":"symbol","abstract":[{"text":"A UIViewController subclass to show a camera screen and run a user guiding document scanner.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"documentScannerViewControllerCaptureAnimationConfiguration:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"documentScannerViewControllerCaptureAnimationConfiguration:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentAnimationConfiguration","text":"SBSDKDocumentAnimationConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"documentScannerViewControllerCaptureAnimationConfiguration:"},{"kind":"text","text":"("},{"text":"SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"controller","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The document scanner controller that called this function.","type":"text"}]}],"name":"controller"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"An instance of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration"},{"type":"text","text":" or "},{"code":"nil","type":"codeVoice"},{"text":" to skip the animation.","type":"text"}]}],"kind":"content"}},{"value":"SBSDKDocumentScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate\/fragments","value":[{"text":"SBSDKDocumentScannerViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentAnimationConfiguration\/title","value":"SBSDKDocumentAnimationConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentAnimationConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentAnimationConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentAnimationConfiguration\/navigatorTitle","value":[{"text":"SBSDKDocumentAnimationConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController~1shouldAnimateDocument\/title","value":"shouldAnimateDocument"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController~1shouldAnimateDocument\/fragments","value":[{"text":"shouldAnimateDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate~1documentScannerViewControllerCaptureAnimationConfiguration(_:)\/title","value":"documentScannerViewControllerCaptureAnimationConfiguration:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"documentScannerViewControllerCaptureAnimationConfiguration:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate~1documentScannerViewControllerCaptureAnimationConfiguration(_:)\/fragments","op":"replace"},{"op":"replace","value":"SBSDKDocumentScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title"},{"value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"op":"replace"}]}]}