{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate"]]},"metadata":{"title":"documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"documentScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didSnapDocumentImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"autoSnapped"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKDocumentScannerViewControllerDelegate(im)documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:","symbolKind":"method","navigatorTitle":[{"text":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:","kind":"identifier"}],"role":"symbol","required":true},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Informs the delegate that the document scanner detected and captured a document and provides the original image, the cropped document image"},{"text":" ","type":"text"},{"type":"text","text":"and the result of the detection."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:didsnapdocumentimage:on:with:autosnapped:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:didsnapdocumentimage:on:with:autosnapped:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate\/documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"documentScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didSnapDocumentImage","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"documentImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":" "},{"text":"originalImage","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"text":"result","kind":"internalParam"},{"kind":"text","text":": "},{"text":"SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult"},{"kind":"text","text":"?, "},{"text":"autoSnapped","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The document scanner controller that called this function."}]}]},{"name":"documentImage","content":[{"inlineContent":[{"text":"The image of the document: cropped, filtered and perspective corrected.","type":"text"}],"type":"paragraph"}]},{"name":"originalImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The original image the document was detected on."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The result of the document detection."}],"type":"paragraph"}],"name":"result"},{"name":"autoSnapped","content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"True"},{"text":", if the result was automatically snapped, ","type":"text"},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise."}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewControllerDelegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentScannerViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate","type":"topic","abstract":[{"type":"text","text":"The delegate protocol of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"title":"SBSDKDocumentScannerViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"type":"topic","title":"SBSDKDocumentScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller","navigatorTitle":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"abstract":[{"text":"A UIViewController subclass to show a camera screen and run a user guiding document detector.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewControllerDelegate/documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)":{"title":"documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"documentScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSnapDocumentImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"autoSnapped"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate\/documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)","abstract":[{"text":"Informs the delegate that the document scanner detected and captured a document and provides the original image, the cropped document image","type":"text"},{"type":"text","text":" "},{"text":"and the result of the detection.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:didsnapdocumentimage:on:with:autosnapped:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorResult":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This class represents the result of a document detection","type":"text"},{"type":"text","text":" "},{"text":"on an image.","type":"text"}],"type":"topic","title":"SBSDKDocumentDetectorResult","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectorresult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"documentScannerViewController:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"controller"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didSnapDocumentImage:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentImage"},{"kind":"text","text":" "},{"text":"onImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"originalImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withResult:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"kind":"text","text":" "},{"text":"autoSnapped:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"autoSnapped","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title","value":"SBSDKDocumentScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}]},{"value":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate~1documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate~1documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/title","value":"SBSDKDocumentDetectorResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}