{"abstract":[{"type":"text","text":"Display all icons in the navigation bar in white."}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","title":"SBSDKUI2NavigationBarMode.light","symbolKind":"case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2NavigationBarMode@SBSDKUI2NavigationBarModeLight","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"light","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"SBSDKUI2NavigationBarModeLight","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2NavigationBarMode"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2NavigationBarMode\/light","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"light","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2navigationbarmode\/light"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2navigationbarmode\/light"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2NavigationBarMode/light":{"kind":"symbol","abstract":[{"type":"text","text":"Display all icons in the navigation bar in white."}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"light"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2NavigationBarMode\/light","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2navigationbarmode\/light","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2NavigationBarModeLight"}],"title":"SBSDKUI2NavigationBarMode.light"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2NavigationBarMode":{"abstract":[{"text":"The visual mode used for the navigation bar icons. Android only.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2navigationbarmode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2NavigationBarMode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2NavigationBarMode","kind":"identifier"}],"type":"topic","role":"symbol","title":"SBSDKUI2NavigationBarMode","navigatorTitle":[{"text":"SBSDKUI2NavigationBarMode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKUI2NavigationBarModeLight","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2NavigationBarModeLight"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKUI2NavigationBarModeLight"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2NavigationBarMode~1light\/title","value":"SBSDKUI2NavigationBarModeLight"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2NavigationBarMode~1light\/fragments","value":[{"text":"SBSDKUI2NavigationBarModeLight","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2NavigationBarMode\/title","value":"SBSDKUI2NavigationBarMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2NavigationBarMode\/fragments","value":[{"text":"SBSDKUI2NavigationBarMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2NavigationBarMode\/navigatorTitle","value":[{"text":"SBSDKUI2NavigationBarMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}