{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage"]]},"abstract":[{"text":"Adds an image of page file type original to the receiver, generates a page file identifier and returns it.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/add(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/add(_:)"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/add(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"The UIImage instance to manage.","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"The page file identifier of the added image that can be used to reference the image, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the image could not be stored.","type":"text"}],"type":"paragraph"}]}],"sections":[],"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"},{"text":"?","kind":"text"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentPageFileStorage(im)add:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"add(_:)","navigatorTitle":[{"kind":"identifier","text":"add:"}]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage","abstract":[{"text":"A class to store and restore images of different types in a memory-efficient way.","type":"text"}],"role":"symbol","title":"SBSDKDocumentPageFileStorage","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/add(_:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/add(_:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/add(_:)","abstract":[{"type":"text","text":"Adds an image of page file type original to the receiver, generates a page file identifier and returns it."}],"kind":"symbol","title":"add(_:)","role":"symbol","navigatorTitle":[{"text":"add:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"add","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"add:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"add:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"NSUUID","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSUUID"},{"kind":"text","text":" *) "},{"text":"add:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"image","content":[{"inlineContent":[{"text":"The UIImage instance to manage.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"value":{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"The page file identifier of the added image that can be used to reference the image, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the image could not be stored."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage\/title","op":"replace","value":"SBSDKDocumentPageFileStorage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage\/fragments","value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage\/navigatorTitle"},{"value":"add:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1add(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"add:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1add(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}