{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmationDialogStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogStyle","text":"SBSDKUIDialogStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescanneruiconfiguration\/confirmationdialogstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescanneruiconfiguration\/confirmationdialogstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerUIConfiguration\/confirmationDialogStyle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The style of the confirmation dialog."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmationDialogStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIDialogStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogStyle"}],"title":"confirmationDialogStyle","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerUIConfiguration(py)confirmationDialogStyle","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"confirmationDialogStyle"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerUIConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.2.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDialogStyle":{"role":"symbol","title":"SBSDKUIDialogStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDialogStyle"}],"abstract":[{"type":"text","text":"The general style for a dialog in ScanbotSDK. Used to customize certain result dialogs in SBSDKUI components."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDialogStyle"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidialogstyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerUIConfiguration/confirmationDialogStyle":{"role":"symbol","title":"confirmationDialogStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmationDialogStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIDialogStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogStyle"}],"abstract":[{"type":"text","text":"The style of the confirmation dialog."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerUIConfiguration\/confirmationDialogStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"confirmationDialogStyle"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescanneruiconfiguration\/confirmationdialogstyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerUIConfiguration":{"role":"symbol","title":"SBSDKUILicensePlateScannerUIConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUILicensePlateScannerUIConfiguration"}],"abstract":[{"type":"text","text":"Configuration for the user interface look and feel of the RTU-UI license plate scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerUIConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerUIConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescanneruiconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"confirmationDialogStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"confirmationDialogStyle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogStyle","text":"SBSDKUIDialogStyle"},{"kind":"text","text":" * "},{"kind":"identifier","text":"confirmationDialogStyle"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogStyle\/title","value":"SBSDKUIDialogStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogStyle\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDialogStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerUIConfiguration~1confirmationDialogStyle\/title","value":"confirmationDialogStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerUIConfiguration~1confirmationDialogStyle\/fragments","value":[{"kind":"identifier","text":"confirmationDialogStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerUIConfiguration\/title","value":"SBSDKUILicensePlateScannerUIConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerUIConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerUIConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}