{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewControllerDelegate"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"textLineRecognizerViewController:didFinishStep:withResult:"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUITextDataScannerViewControllerDelegate(im)textLineRecognizerViewController:didFinishStep:withResult:","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textLineRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerViewController","text":"SBSDKUITextDataScannerViewController"},{"text":", ","kind":"text"},{"text":"didFinish","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerStep","text":"SBSDKUITextDataScannerStep","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUITextDataScannerStepResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerStepResult","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","symbolKind":"method","title":"textLineRecognizerViewController(_:didFinish:with:)"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewControllerDelegate\/textLineRecognizerViewController(_:didFinish:with:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontrollerdelegate\/textlinerecognizerviewcontroller(_:didfinish:with:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontrollerdelegate\/textlinerecognizerviewcontroller(_:didfinish:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"Informs the delegate that the text has been recognized and validated.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(textLineRecognizerViewController:didFinishStep:withResult:) ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"textLineRecognizerViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerViewController","text":"SBSDKUITextDataScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinish"},{"kind":"text","text":" "},{"kind":"internalParam","text":"step"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStep","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerStep","text":"SBSDKUITextDataScannerStep","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"text":"result","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStepResult","text":"SBSDKUITextDataScannerStepResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerStepResult"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The text data scanner view controller instance."}]}],"name":"controller"},{"content":[{"inlineContent":[{"type":"text","text":"The step that this result was recognized for."}],"type":"paragraph"}],"name":"step"},{"name":"result","content":[{"inlineContent":[{"text":"The validated recognition result.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewControllerDelegate/textLineRecognizerViewController(_:didFinish:with:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewControllerDelegate\/textLineRecognizerViewController(_:didFinish:with:)","navigatorTitle":[{"text":"textLineRecognizerViewController:didFinishStep:withResult:","kind":"identifier"}],"abstract":[{"type":"text","text":"Informs the delegate that the text has been recognized and validated."}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontrollerdelegate\/textlinerecognizerviewcontroller(_:didfinish:with:)","title":"textLineRecognizerViewController(_:didFinish:with:)","role":"symbol","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textLineRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUITextDataScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinish"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerStep","text":"SBSDKUITextDataScannerStep","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUITextDataScannerStepResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerStepResult"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewControllerDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontrollerdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKUITextDataScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUITextDataScannerViewControllerDelegate","kind":"identifier"}],"title":"SBSDKUITextDataScannerViewControllerDelegate","type":"topic","abstract":[{"text":"Delegate protocol for ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewControllerDelegate","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController":{"type":"topic","navigatorTitle":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","abstract":[{"text":"A highly customizable camera-based view controller to recognize and validate a small rectangular text area in realtime.","type":"text"}],"title":"SBSDKUITextDataScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerStepResult":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUITextDataScannerStepResult"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUITextDataScannerStepResult","kind":"identifier"}],"title":"SBSDKUITextDataScannerStepResult","kind":"symbol","abstract":[{"type":"text","text":"Encapsulates the result of the text recognition of a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController"},{"type":"text","text":"s workflow step."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerstepresult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStepResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerStep":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerstep","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUITextDataScannerStep","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUITextDataScannerStep","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStep","abstract":[{"type":"text","text":"Defines a single workflow step of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","type":"reference","isActive":true},{"type":"text","text":" flow."}],"title":"SBSDKUITextDataScannerStep","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"textLineRecognizerViewController:didFinishStep:withResult:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textLineRecognizerViewController:didFinishStep:withResult:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"textLineRecognizerViewController:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","text":"SBSDKUITextDataScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishStep:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStep","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerStep","text":"SBSDKUITextDataScannerStep","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"step"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withResult:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerStepResult","text":"SBSDKUITextDataScannerStepResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStepResult"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"result"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewControllerDelegate~1textLineRecognizerViewController(_:didFinish:with:)\/title","value":"textLineRecognizerViewController:didFinishStep:withResult:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewControllerDelegate~1textLineRecognizerViewController(_:didFinish:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textLineRecognizerViewController:didFinishStep:withResult:"}]},{"value":"SBSDKUITextDataScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewControllerDelegate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUITextDataScannerViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/title","value":"SBSDKUITextDataScannerViewController","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStepResult\/title","op":"replace","value":"SBSDKUITextDataScannerStepResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStepResult\/fragments","value":[{"kind":"identifier","text":"SBSDKUITextDataScannerStepResult"}]},{"value":"SBSDKUITextDataScannerStep","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStep\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStep\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUITextDataScannerStep"}]}]}]}