{"abstract":[{"type":"text","text":"Informs the delegate that the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController"},{"type":"text","text":" has been cancelled and dismissed."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontrollerdelegate\/textlinerecognizerviewcontrollerdidcancel(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontrollerdelegate\/textlinerecognizerviewcontrollerdidcancel(_:)"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewControllerDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textLineRecognizerViewControllerDidCancel","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","text":"SBSDKUITextDataScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerViewController"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The text data scanner view controller instance."}],"type":"paragraph"}],"name":"controller"}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Optional.","type":"text"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewControllerDelegate\/textLineRecognizerViewControllerDidCancel(_:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textLineRecognizerViewControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerViewController","text":"SBSDKUITextDataScannerViewController"},{"kind":"text","text":")"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUITextDataScannerViewControllerDelegate(im)textLineRecognizerViewControllerDidCancel:","symbolKind":"method","navigatorTitle":[{"text":"textLineRecognizerViewControllerDidCancel:","kind":"identifier"}],"title":"textLineRecognizerViewControllerDidCancel(_:)","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController":{"type":"topic","navigatorTitle":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","abstract":[{"text":"A highly customizable camera-based view controller to recognize and validate a small rectangular text area in realtime.","type":"text"}],"title":"SBSDKUITextDataScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewControllerDelegate/textLineRecognizerViewControllerDidCancel(_:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewControllerDelegate\/textLineRecognizerViewControllerDidCancel(_:)","navigatorTitle":[{"text":"textLineRecognizerViewControllerDidCancel:","kind":"identifier"}],"abstract":[{"text":"Informs the delegate that the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","type":"reference"},{"type":"text","text":" has been cancelled and dismissed."}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontrollerdelegate\/textlinerecognizerviewcontrollerdidcancel(_:)","title":"textLineRecognizerViewControllerDidCancel(_:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textLineRecognizerViewControllerDidCancel","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUITextDataScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerViewController"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewControllerDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontrollerdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKUITextDataScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUITextDataScannerViewControllerDelegate","kind":"identifier"}],"title":"SBSDKUITextDataScannerViewControllerDelegate","type":"topic","abstract":[{"text":"Delegate protocol for ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewControllerDelegate","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"textLineRecognizerViewControllerDidCancel:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"textLineRecognizerViewControllerDidCancel:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"textLineRecognizerViewControllerDidCancel:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerViewController","text":"SBSDKUITextDataScannerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUITextDataScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/title"},{"op":"replace","value":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/fragments"},{"value":"textLineRecognizerViewControllerDidCancel:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewControllerDelegate~1textLineRecognizerViewControllerDidCancel(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewControllerDelegate~1textLineRecognizerViewControllerDidCancel(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"textLineRecognizerViewControllerDidCancel:","kind":"identifier"}]},{"op":"replace","value":"SBSDKUITextDataScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewControllerDelegate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewControllerDelegate\/fragments","value":[{"text":"SBSDKUITextDataScannerViewControllerDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}