{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemMapper"]]},"sections":[],"metadata":{"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUI2BarcodeItemMapper(im)mapBarcodeItemWithItem:onResult:onError:","role":"symbol","title":"mapBarcodeItem(item:onResult:onError:)","required":true,"navigatorTitle":[{"text":"mapBarcodeItemWithItem:onResult:onError:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapBarcodeItem"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"item"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarcodeItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItem"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onResult"},{"text":": (","kind":"text"},{"text":"SBSDKUI2BarcodeMappedData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeMappedData"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeitemmapper\/mapbarcodeitem(item:onresult:onerror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeitemmapper\/mapbarcodeitem(item:onresult:onerror:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemMapper\/mapBarcodeItem(item:onResult:onError:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"mapBarcodeItem","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeItem","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItem"},{"text":", ","kind":"text"},{"text":"onResult","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"SBSDKUI2BarcodeMappedData","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeMappedData","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeMappedData"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" () -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"item","content":[{"inlineContent":[{"type":"text","text":"The barcode data to be mapped."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Function that returns the result on the screen.","type":"text"}]}],"name":"onResult"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Function that returns an error on the screen in case of a timeout or other issue."}]}],"name":"onError"}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Function that maps a barcode’s data to the data of the corresponding product."}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemMapper":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemMapper","kind":"symbol","abstract":[{"text":"Maps a barcode’s data to the data of the corresponding product.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeItemMapper","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitemmapper","type":"topic","title":"SBSDKUI2BarcodeItemMapper","navigatorTitle":[{"text":"SBSDKUI2BarcodeItemMapper","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItem":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitem","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeItem","kind":"identifier"}],"type":"topic","abstract":[{"text":"Data about the scanned barcode.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItem"}],"title":"SBSDKUI2BarcodeItem","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemMapper/mapBarcodeItem(item:onResult:onError:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitemmapper\/mapbarcodeitem(item:onresult:onerror:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemMapper\/mapBarcodeItem(item:onResult:onError:)","abstract":[{"type":"text","text":"Function that maps a barcode’s data to the data of the corresponding product."}],"role":"symbol","title":"mapBarcodeItem(item:onResult:onError:)","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mapBarcodeItem","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItem","text":"SBSDKUI2BarcodeItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onResult"},{"kind":"text","text":": ("},{"text":"SBSDKUI2BarcodeMappedData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeMappedData"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"mapBarcodeItemWithItem:onResult:onError:"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeMappedData":{"navigatorTitle":[{"text":"SBSDKUI2BarcodeMappedData","kind":"identifier"}],"title":"SBSDKUI2BarcodeMappedData","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeMappedData"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeMappedData","abstract":[{"type":"text","text":"Format of the mapped barcode data."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodemappeddata"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"mapBarcodeItemWithItem:onResult:onError:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapBarcodeItemWithItem:onResult:onError:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"mapBarcodeItemWithItem:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2BarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItem","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItem"},{"text":" *) ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onResult:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeMappedData","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeMappedData","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeMappedData"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"onResult","kind":"internalParam"},{"kind":"text","text":" "},{"text":"onError:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"text":")()) ","kind":"text"},{"kind":"internalParam","text":"onError"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The barcode data to be mapped."}],"type":"paragraph"}],"name":"item"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Function that returns the result on the screen.","type":"text"}]}],"name":"onResult"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Function that returns an error on the screen in case of a timeout or other issue.","type":"text"}]}],"name":"onError"}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemMapper\/title","value":"SBSDKUI2BarcodeItemMapper"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemMapper\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemMapper"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemMapper\/navigatorTitle","value":[{"text":"SBSDKUI2BarcodeItemMapper","kind":"identifier"}]},{"value":"SBSDKUI2BarcodeItem","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItem\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItem\/fragments","value":[{"text":"SBSDKUI2BarcodeItem","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItem"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItem\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemMapper~1mapBarcodeItem(item:onResult:onError:)\/title","value":"mapBarcodeItemWithItem:onResult:onError:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemMapper~1mapBarcodeItem(item:onResult:onError:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"mapBarcodeItemWithItem:onResult:onError:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeMappedData\/title","op":"replace","value":"SBSDKUI2BarcodeMappedData"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeMappedData\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeMappedData"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeMappedData\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeMappedData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}