{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKBarcodeScanAndCountViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate","text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The delegate of the receiver. Weak."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontroller\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontroller\/delegate"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController\/delegate","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanAndCountViewController(py)delegate","title":"delegate","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKBarcodeScanAndCountViewControllerDelegate"},{"text":"?","kind":"text"}]},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewController":{"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show a camera screen with the barcode scanner.","type":"text"},{"text":" ","type":"text"},{"text":"Screen also shows snap, scan more and reset buttons.","type":"text"},{"text":" ","type":"text"},{"text":"The snap button starts the scanning when tapped.","type":"text"},{"text":" ","type":"text"},{"text":"The snap button resets the scanning when tapped again.","type":"text"},{"text":" ","type":"text"},{"text":"Instead it is installing itself as a child view controller onto a given parent view controller.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontroller","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController","title":"SBSDKBarcodeScanAndCountViewController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewControllerDelegate":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"A delegate protocol to handle the barcode results from ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController","type":"reference","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate","title":"SBSDKBarcodeScanAndCountViewControllerDelegate","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontrollerdelegate"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewController/delegate":{"title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"typeIdentifier","text":"SBSDKBarcodeScanAndCountViewControllerDelegate"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontroller\/delegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"abstract":[{"text":"The delegate of the receiver. Weak.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController\/delegate"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<SBSDKBarcodeScanAndCountViewControllerDelegate>","preciseIdentifier":"c:Qo@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKBarcodeScanAndCountViewControllerDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/title","value":"SBSDKBarcodeScanAndCountViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/fragments","value":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}]},{"value":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/navigatorTitle"},{"value":"SBSDKBarcodeScanAndCountViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate\/title"},{"value":[{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate\/fragments"},{"value":[{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate\/navigatorTitle"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController~1delegate\/title"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController~1delegate\/fragments"}]}]}