{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus\/Equatable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","metadata":{"title":"Equatable Implementations","modules":[{"name":"ScanbotSDK"}],"role":"collectionGroup","roleHeading":"API Collection"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscannerstatus\/equatable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus"]]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus\/!=(_:_:)"],"generated":true,"anchor":"Operators","title":"Operators"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannerStatus":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannerStatus"}],"title":"SBSDKScannerStatus","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkscannerstatus","abstract":[{"text":"This enum describes the possible scanning states of any scanner.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKScannerStatus","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannerStatus/!=(_:_:)":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus\/!=(_:_:)","title":"!=(_:_:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscannerstatus\/!=(_:_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKScannerStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannerStatus\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannerStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKScannerStatus"}]},{"value":[{"text":"SBSDKScannerStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannerStatus\/navigatorTitle"}]}]}