{"sections":[],"metadata":{"extendedModule":"UIKit","role":"symbol","externalID":"c:@CM@ScanbotSDK@@objc(cs)UIImage(im)sbsdk_imageFilteredWithFilters:","title":"sbsdk_imageFiltered(by:)","modules":[{"name":"ScanbotSDK","relatedModules":["UIKit"]}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbsdk_imageFiltered","kind":"identifier"},{"text":"(","kind":"text"},{"text":"by","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Applies a filter to the receiver and returns the filtered image."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage\/sbsdk_imageFiltered(by:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(sbsdk_imageFilteredWithFilters:) ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sbsdk_imageFiltered","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"text":" ","kind":"text"},{"text":"filters","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKParametricFilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The types of the filters to be applied.","type":"text"}]}],"name":"filters"}]},{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"The filtered ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the operation failed."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/uikit\/uiimage\/sbsdk_imagefiltered(by:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"title":"SBSDKParametricFilter","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","role":"symbol","abstract":[{"text":"Base class for all parametric filters.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKParametricFilter"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit/UIImage/sbsdk_imageFiltered(by:)":{"role":"symbol","abstract":[{"text":"Applies a filter to the receiver and returns the filtered image.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage\/sbsdk_imageFiltered(by:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sbsdk_imageFiltered"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"sbsdk_imageFiltered(by:)","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/uikit\/uiimage\/sbsdk_imagefiltered(by:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit","role":"collection","title":"UIKit","type":"topic","url":"\/documentation\/scanbotsdk\/uikit","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit/UIImage":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage","role":"symbol","title":"UIImage","type":"topic","url":"\/documentation\/scanbotsdk\/uikit\/uiimage","navigatorTitle":[{"kind":"identifier","text":"UIImage"}],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}],"kind":"symbol","abstract":[{"text":"An ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" class extension to perform basic image processing operations."},{"type":"text","text":" "},{"type":"text","text":"Direct usage is not recommended for large images."},{"text":" ","type":"text"},{"text":"queues and proper memory management.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title","value":"SBSDKParametricFilter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments","op":"replace","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/navigatorTitle","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"op":"replace"}]}]}