{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/uikit\/uiimage\/sbsdk_imagewarped(by:filters:imagescale:sizelimit:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Applies a polygon and a filter to the receiver. Faster than two sequential operations.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(sbsdk_imageWarpedByPolygon:andFilteredBy:imageScale:sizeLimit:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sbsdk_imageWarped"},{"kind":"text","text":"("},{"kind":"externalParam","text":"by"},{"kind":"text","text":" "},{"kind":"internalParam","text":"polygon"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"text":"?, ","kind":"text"},{"text":"filters","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter"},{"text":"], ","kind":"text"},{"text":"imageScale","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"text":"sizeLimit","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":" = .zero) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The polygon used to crop and perspective correct the image.","type":"text"}],"type":"paragraph"}],"name":"polygon"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The types of the filters to be applied.","type":"text"}]}],"name":"filters"},{"content":[{"inlineContent":[{"type":"text","text":"If the image has been scaled, compared to how it was captured from the camera, you must set the scaling factor here for proper cropping. Otherwise the resulting aspect ratio will be wrong. Set to 1.0 if the image must retain its original size."}],"type":"paragraph"}],"name":"imageScale"},{"content":[{"inlineContent":[{"type":"text","text":"The maximum size of the resulting image. If the image exceeds this size, it will be scaled down to fit within the specified dimensions. Default is "},{"type":"codeVoice","code":".zero"},{"type":"text","text":", which means no size limit."}],"type":"paragraph"}],"name":"sizeLimit"}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"The cropped, perspective corrected and filtered "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the operation failed."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"extendedModule":"UIKit","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sbsdk_imageWarped"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"filters","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"text":"], ","kind":"text"},{"text":"imageScale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"sizeLimit","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@CM@ScanbotSDK@@objc(cs)UIImage(im)sbsdk_imageWarpedByPolygon:andFilteredBy:imageScale:sizeLimit:","title":"sbsdk_imageWarped(by:filters:imageScale:sizeLimit:)","role":"symbol","modules":[{"relatedModules":["UIKit"],"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage\/sbsdk_imageWarped(by:filters:imageScale:sizeLimit:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"title":"SBSDKParametricFilter","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","role":"symbol","abstract":[{"text":"Base class for all parametric filters.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKParametricFilter"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit","role":"collection","title":"UIKit","type":"topic","url":"\/documentation\/scanbotsdk\/uikit","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit/UIImage":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage","role":"symbol","title":"UIImage","type":"topic","url":"\/documentation\/scanbotsdk\/uikit\/uiimage","navigatorTitle":[{"kind":"identifier","text":"UIImage"}],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}],"kind":"symbol","abstract":[{"text":"An ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" class extension to perform basic image processing operations."},{"type":"text","text":" "},{"type":"text","text":"Direct usage is not recommended for large images."},{"text":" ","type":"text"},{"text":"queues and proper memory management.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpolygon","title":"SBSDKPolygon","navigatorTitle":[{"text":"SBSDKPolygon","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPolygon"}],"kind":"symbol","abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit/UIImage/sbsdk_imageWarped(by:filters:imageScale:sizeLimit:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sbsdk_imageWarped","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"by"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"filters","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"imageScale"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sizeLimit"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"text":"Applies a polygon and a filter to the receiver. Faster than two sequential operations.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage\/sbsdk_imageWarped(by:filters:imageScale:sizeLimit:)","url":"\/documentation\/scanbotsdk\/uikit\/uiimage\/sbsdk_imagewarped(by:filters:imagescale:sizelimit:)","kind":"symbol","title":"sbsdk_imageWarped(by:filters:imageScale:sizeLimit:)"}},"variantOverrides":[{"patch":[{"value":"SBSDKParametricFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/navigatorTitle"},{"op":"replace","value":"SBSDKPolygon","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","value":[{"text":"SBSDKPolygon","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPolygon"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}