{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodetrackingoverlayconfiguration"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodetrackingoverlayconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}]}],"metadata":{"platforms":[],"role":"symbol","roleHeading":"Class","title":"SBSDKUIBarcodeTrackingOverlayConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeTrackingOverlayConfiguration","navigatorTitle":[{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"class"},"sections":[],"abstract":[{"type":"text","text":"The configuration object for the RTU-UI barcode tracking overlay."}],"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/automaticSelectionEnabled","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedPolygonColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedTextColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedTextContainerColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/overlayEnabled","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/overlayTextFormat","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/polygonColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/textColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/textContainerColor"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeTrackingOverlayConfiguration":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodetrackingoverlayconfiguration","title":"SBSDKUIBarcodeTrackingOverlayConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"symbol","abstract":[{"type":"text","text":"The configuration object for the RTU-UI barcode tracking overlay."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}],"role":"symbol","deprecated":true,"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/textContainerColor":{"title":"textContainerColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textContainerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"deprecated":true,"type":"topic","abstract":[{"type":"text","text":"The text background color for the results overlays."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"textContainerColor"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodetrackingoverlayconfiguration\/textcontainercolor","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/textContainerColor"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/overlayTextFormat":{"title":"overlayTextFormat","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"overlayTextFormat"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeOverlayFormat","text":"SBSDKBarcodeOverlayFormat","kind":"typeIdentifier"}],"deprecated":true,"type":"topic","abstract":[{"text":"The text format for the results overlays.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"overlayTextFormat","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodetrackingoverlayconfiguration\/overlaytextformat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/overlayTextFormat"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/highlightedTextContainerColor":{"title":"highlightedTextContainerColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"highlightedTextContainerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"deprecated":true,"type":"topic","abstract":[{"text":"The text background color for the results overlays.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"highlightedTextContainerColor"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodetrackingoverlayconfiguration\/highlightedtextcontainercolor","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedTextContainerColor"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/highlightedPolygonColor":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodetrackingoverlayconfiguration\/highlightedpolygoncolor","title":"highlightedPolygonColor","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedPolygonColor","kind":"symbol","abstract":[{"type":"text","text":"The color for the results overlays polygons."}],"navigatorTitle":[{"kind":"identifier","text":"highlightedPolygonColor"}],"role":"symbol","deprecated":true,"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightedPolygonColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/polygonColor":{"title":"polygonColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"deprecated":true,"type":"topic","abstract":[{"type":"text","text":"The color for the results overlays polygons."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"polygonColor"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodetrackingoverlayconfiguration\/polygoncolor","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/polygonColor"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/overlayEnabled":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodetrackingoverlayconfiguration\/overlayenabled","title":"overlayEnabled","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/overlayEnabled","kind":"symbol","abstract":[{"type":"text","text":"Displays an augmented reality view that draws the frames, content and type text of the found barcodes when it finds them."}],"navigatorTitle":[{"kind":"identifier","text":"overlayEnabled"}],"role":"symbol","deprecated":true,"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"overlayEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/init":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodetrackingoverlayconfiguration\/init","title":"init","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/init","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/automaticSelectionEnabled":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"automaticSelectionEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"automaticSelectionEnabled","kind":"identifier"}],"title":"automaticSelectionEnabled","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/automaticSelectionEnabled","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"If enabled, newly scanned barcodes will be automatically selected.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Otherwise the user has to tap on a barcode on the selection overlay to select it."},{"type":"text","text":" "},{"type":"text","text":"Has no effect with disabled overlay."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodetrackingoverlayconfiguration\/automaticselectionenabled","deprecated":true},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/highlightedTextColor":{"navigatorTitle":[{"kind":"identifier","text":"highlightedTextColor"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodetrackingoverlayconfiguration\/highlightedtextcolor","title":"highlightedTextColor","deprecated":true,"abstract":[{"text":"The text color for the results overlays.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedTextColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightedTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/textColor":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"navigatorTitle":[{"text":"textColor","kind":"identifier"}],"kind":"symbol","deprecated":true,"role":"symbol","type":"topic","abstract":[{"text":"The text color for the results overlays.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodetrackingoverlayconfiguration\/textcolor","title":"textColor","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/textColor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKUIBarcodeTrackingOverlayConfiguration","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/automaticSelectionEnabled","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedPolygonColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedTextColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedTextContainerColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/overlayEnabled","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/overlayTextFormat","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/polygonColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/textColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/textContainerColor"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/init"],"generated":true}]},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration\/title","value":"SBSDKUIBarcodeTrackingOverlayConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1textContainerColor\/title","op":"replace","value":"textContainerColor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1textContainerColor\/fragments","value":[{"kind":"identifier","text":"textContainerColor"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1overlayTextFormat\/title","value":"overlayTextFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1overlayTextFormat\/fragments","value":[{"kind":"identifier","text":"overlayTextFormat"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1highlightedTextContainerColor\/title","value":"highlightedTextContainerColor","op":"replace"},{"op":"replace","value":[{"text":"highlightedTextContainerColor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1highlightedTextContainerColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1highlightedPolygonColor\/title","value":"highlightedPolygonColor"},{"value":[{"text":"highlightedPolygonColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1highlightedPolygonColor\/fragments"},{"value":"polygonColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1polygonColor\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1polygonColor\/fragments","value":[{"text":"polygonColor","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1overlayEnabled\/title","value":"overlayEnabled"},{"value":[{"text":"overlayEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1overlayEnabled\/fragments"},{"value":"automaticSelectionEnabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1automaticSelectionEnabled\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1automaticSelectionEnabled\/fragments","value":[{"kind":"identifier","text":"automaticSelectionEnabled"}],"op":"replace"},{"value":"highlightedTextColor","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1highlightedTextColor\/title","op":"replace"},{"value":[{"text":"highlightedTextColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1highlightedTextColor\/fragments"},{"value":"textColor","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1textColor\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1textColor\/fragments","value":[{"text":"textColor","kind":"identifier"}]}]}]}