{"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKOrientationLock","symbolKind":"enum","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOrientationLock"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKOrientationLock","kind":"identifier"}],"title":"SBSDKOrientationLock"},"sections":[],"abstract":[{"type":"text","text":"This enum describes the available orientation lock modes for the user interface."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock\/landscape","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock\/none","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock\/portrait"],"anchor":"Enumeration-Cases"},{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOrientationLock","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Captured images are always top-oriented to the status bar."}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkorientationlock"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkorientationlock"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOrientationLock/landscape":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkorientationlock\/landscape","type":"topic","title":"SBSDKOrientationLock.landscape","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock\/landscape","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape"}],"abstract":[{"type":"text","text":"The orientation is locked to the landscape modes. The captured image is orientated so that the upper area of the image is directed towards the status bar."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKOrientationLockLandscape"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOrientationLock/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock\/Equatable-Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkorientationlock\/equatable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOrientationLock":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkorientationlock","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock","role":"symbol","navigatorTitle":[{"text":"SBSDKOrientationLock","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This enum describes the available orientation lock modes for the user interface.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKOrientationLock"}],"title":"SBSDKOrientationLock"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOrientationLock/init(rawValue:)":{"abstract":[],"title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock\/init(rawValue:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkorientationlock\/init(rawvalue:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOrientationLock/portrait":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkorientationlock\/portrait","type":"topic","title":"SBSDKOrientationLock.portrait","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock\/portrait","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait"}],"abstract":[{"type":"text","text":"The orientation is locked to the portrait modes. The captured image is orientated so that the upper area of the image is directed towards the status bar."}],"navigatorTitle":[{"text":"SBSDKOrientationLockPortrait","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOrientationLock/none":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock\/none","abstract":[{"text":"The orientation is not locked. The captured image is orientated so that the upper area of the image is directed towards the status bar.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkorientationlock\/none","title":"SBSDKOrientationLock.none","navigatorTitle":[{"text":"SBSDKOrientationLockNone","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOrientationLock/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","kind":"article","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkorientationlock\/rawrepresentable-implementations","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock\/RawRepresentable-Implementations","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"value":"SBSDKOrientationLock","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKOrientationLock"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKOrientationLock"}],"op":"replace"},{"value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock\/landscape","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock\/none","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock\/portrait"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKOrientationLock"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOrientationLock~1landscape\/title","op":"replace","value":"SBSDKOrientationLockLandscape"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOrientationLockLandscape"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOrientationLock~1landscape\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOrientationLock\/title","value":"SBSDKOrientationLock"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOrientationLock\/fragments","value":[{"kind":"identifier","text":"SBSDKOrientationLock"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOrientationLock\/navigatorTitle","op":"replace","value":[{"text":"SBSDKOrientationLock","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOrientationLock~1portrait\/title","op":"replace","value":"SBSDKOrientationLockPortrait"},{"value":[{"kind":"identifier","text":"SBSDKOrientationLockPortrait"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOrientationLock~1portrait\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOrientationLock~1none\/title","value":"SBSDKOrientationLockNone","op":"replace"},{"op":"replace","value":[{"text":"SBSDKOrientationLockNone","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOrientationLock~1none\/fragments"}]}]}