{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Node"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","roleHeading":"Class","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayPolygonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}],"title":"SBSDKUI2ArOverlayPolygonConfiguration","symbolKind":"class","navigatorTitle":[{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}]},"abstract":[{"type":"text","text":"Configuration of the overlay polygon displayed on top of a barcode in the camera preview."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2ArOverlayPolygonConfiguration) ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/init()"]},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/deselected","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/selected","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/visible"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/toJson(configuration:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaypolygonconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaypolygonconfiguration"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Node":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Node","kind":"identifier"}],"abstract":[{"text":"Abstract class for all the configurations.","type":"text"}],"title":"SBSDKUI2Node","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Node","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2node"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying","type":"unresolvable","title":"NSCopying"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayPolygonConfiguration/initWithVisible:deselected:selected:":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/initWithVisible:deselected:selected:","navigatorTitle":[{"kind":"identifier","text":"initWithVisible:deselected:selected:"}],"role":"symbol","kind":"symbol","type":"topic","title":"initWithVisible:deselected:selected:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaypolygonconfiguration\/initwithvisible:deselected:selected:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"initWithVisible:deselected:selected:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayPolygonConfiguration/deselected":{"abstract":[{"type":"text","text":"Appearance of the overlay polygon when a barcode is not selected."}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaypolygonconfiguration\/deselected","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/deselected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"deselected","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2PolygonStyle","text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier"}],"title":"deselected","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deselected"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayPolygonConfiguration/init()":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","title":"init()","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaypolygonconfiguration\/init()","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayPolygonConfiguration/hash":{"abstract":[],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaypolygonconfiguration\/hash","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/hash","fragments":[{"text":"hash","kind":"identifier"}],"title":"hash","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayPolygonConfiguration/fromJsonWithJson:":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","title":"fromJsonWithJson:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaypolygonconfiguration\/fromjsonwithjson:","abstract":[],"fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayPolygonConfiguration/copyWithZone:":{"abstract":[],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaypolygonconfiguration\/copywithzone:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/copyWithZone:","fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","type":"topic","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayPolygonConfiguration/isEqual:":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","kind":"symbol","type":"topic","title":"isEqual:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaypolygonconfiguration\/isequal:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayPolygonConfiguration":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaypolygonconfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration","role":"symbol","abstract":[{"text":"Configuration of the overlay polygon displayed on top of a barcode in the camera preview.","type":"text"}],"title":"SBSDKUI2ArOverlayPolygonConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayPolygonConfiguration"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayPolygonConfiguration/visible":{"abstract":[{"type":"text","text":"Control the visibility of the overlay polygon."}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaypolygonconfiguration\/visible","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/visible","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"visible","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"visible","type":"topic","navigatorTitle":[{"text":"visible","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayPolygonConfiguration/toJson(configuration:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/toJson(configuration:)","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","title":"toJson(configuration:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaypolygonconfiguration\/tojson(configuration:)","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"toJson","kind":"identifier"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayPolygonConfiguration/selected":{"abstract":[{"text":"Appearance of the overlay polygon after a barcode has been selected.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaypolygonconfiguration\/selected","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/selected","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selected","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2PolygonStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2PolygonStyle"}],"title":"selected","type":"topic","navigatorTitle":[{"text":"selected","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKUI2ArOverlayPolygonConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayPolygonConfiguration"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/deselected","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/hash","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/selected","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/visible"],"anchor":"Instance-Properties","generated":true},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/init()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/initWithVisible:deselected:selected:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/toJson(configuration:)"],"anchor":"Instance-Methods"},{"generated":true,"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/fromJsonWithJson:"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Node"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Node","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Node","text":"SBSDKUI2Node"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Node\/title","op":"replace","value":"SBSDKUI2Node"},{"value":[{"text":"SBSDKUI2Node","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Node\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Node\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Node"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1deselected\/title","value":"deselected"},{"op":"replace","value":[{"text":"deselected","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1deselected\/fragments"},{"value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1init()\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1init()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/title","value":"SBSDKUI2ArOverlayPolygonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayPolygonConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}]},{"value":"visible","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1visible\/title"},{"op":"replace","value":[{"text":"visible","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1visible\/fragments"},{"op":"replace","value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1toJson(configuration:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1toJson(configuration:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}]},{"value":"selected","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1selected\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1selected\/fragments","op":"replace","value":[{"kind":"identifier","text":"selected"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}