{"abstract":[{"type":"text","text":"A key generator that uses the PBKDF2 algorithm to derive a key from a password and a salt."},{"text":" ","type":"text"},{"text":"See https:\/\/en.wikipedia.org\/wiki\/PBKDF2 for more information.","type":"text"}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpbkdf2keygenerator"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpbkdf2keygenerator"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPBKDF2KeyGenerator\/init(password:salt:iterations:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPBKDF2KeyGenerator\/generateKey(keyLength:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"metadata":{"roleHeading":"Class","title":"SBSDKPBKDF2KeyGenerator","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPBKDF2KeyGenerator","navigatorTitle":[{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"symbolKind":"class","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPBKDF2KeyGenerator"},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyGenerator","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPBKDF2KeyGenerator"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","text":"Overview","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"This key generator has no randomization component. The key is solely derived from the password, the salt using the specified number of iterations.","type":"text"},{"type":"text","text":" "},{"text":"Passing the identical password, salt and iterations will always result in the same key.","type":"text"}]},{"name":"Note","content":[{"inlineContent":[{"type":"text","text":"Use this key generator if you want to derive a key that is used to encrypt and decrypt your data in the same way every time,"},{"text":" ","type":"text"},{"type":"text","text":"regardless of the device, user or app session."}],"type":"paragraph"}],"type":"aside","style":"note"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPBKDF2KeyGenerator/generateKey(keyLength:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateKey"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKStorageCryptingKeyLength"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"type":"topic","abstract":[{"text":"Generates a new encryption key.","type":"text"}],"title":"generateKey(keyLength:)","navigatorTitle":[{"text":"generateKeyWithLength:WithError:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpbkdf2keygenerator\/generatekey(keylength:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPBKDF2KeyGenerator\/generateKey(keyLength:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPBKDF2KeyGenerator":{"role":"symbol","title":"SBSDKPBKDF2KeyGenerator","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpbkdf2keygenerator","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPBKDF2KeyGenerator","navigatorTitle":[{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"abstract":[{"type":"text","text":"A key generator that uses the PBKDF2 algorithm to derive a key from a password and a salt."},{"text":" ","type":"text"},{"type":"text","text":"See https:\/\/en.wikipedia.org\/wiki\/PBKDF2 for more information."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingKeyGenerator":{"abstract":[{"text":"Protocol for generating encryption keys.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyGenerator","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeygenerator","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"title":"SBSDKStorageCryptingKeyGenerator"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPBKDF2KeyGenerator/init(password:salt:iterations:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithPassword:salt:iterations:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"password","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"salt"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"iterations","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Designated initializer."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpbkdf2keygenerator\/init(password:salt:iterations:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPBKDF2KeyGenerator\/init(password:salt:iterations:)","role":"symbol","type":"topic","kind":"symbol","title":"init(password:salt:iterations:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKPBKDF2KeyGenerator","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPBKDF2KeyGenerator"}],"op":"replace"},{"op":"replace","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPBKDF2KeyGenerator\/generateKey(keyLength:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPBKDF2KeyGenerator\/init(password:salt:iterations:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyGenerator"],"kind":"relationships","title":"Conforms To"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPBKDF2KeyGenerator"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPBKDF2KeyGenerator~1generateKey(keyLength:)\/title","value":"generateKeyWithLength:WithError:"},{"value":[{"kind":"text","text":"- "},{"text":"generateKeyWithLength:WithError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPBKDF2KeyGenerator~1generateKey(keyLength:)\/fragments"},{"value":"SBSDKPBKDF2KeyGenerator","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPBKDF2KeyGenerator\/title"},{"value":[{"kind":"identifier","text":"SBSDKPBKDF2KeyGenerator"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPBKDF2KeyGenerator\/fragments"},{"op":"replace","value":[{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPBKDF2KeyGenerator\/navigatorTitle"},{"value":"SBSDKStorageCryptingKeyGenerator","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyGenerator\/title"},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyGenerator"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyGenerator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyGenerator\/navigatorTitle","value":[{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}]},{"value":"initWithPassword:salt:iterations:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPBKDF2KeyGenerator~1init(password:salt:iterations:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPBKDF2KeyGenerator~1init(password:salt:iterations:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithPassword:salt:iterations:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}