{"metadata":{"title":"fromJsonWithJson:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"roleHeading":"Type Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardIntroOneSideImage(cm)fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"text":"fromJsonWithJson:","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage\/fromJsonWithJson:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardintroonesideimage\/fromjsonwithjson:"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardIntroOneSideImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage","kind":"typeIdentifier","text":"SBSDKUI2CreditCardIntroOneSideImage"},{"kind":"text","text":" *) "},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroOneSideImage/fromJsonWithJson:":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroonesideimage\/fromjsonwithjson:","title":"fromJsonWithJson:","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"fragments":[{"kind":"text","text":"+ "},{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage\/fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroOneSideImage":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroonesideimage","title":"SBSDKUI2CreditCardIntroOneSideImage","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2CreditCardIntroOneSideImage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardIntroOneSideImage","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The image for the introduction screen with one side of a credit card.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroOneSideImage\/title","value":"SBSDKUI2CreditCardIntroOneSideImage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroOneSideImage\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardIntroOneSideImage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroOneSideImage\/navigatorTitle","value":[{"text":"SBSDKUI2CreditCardIntroOneSideImage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}