{"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration\/defaultConfiguration"},"abstract":[{"text":"This is the default configuration with the properties initialized as mentioned in their description.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerzoomconfiguration\/defaultconfiguration"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerzoomconfiguration\/defaultconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerZoomConfiguration(cpy)defaultConfiguration","title":"defaultConfiguration","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerZoomConfiguration","text":"SBSDKBaseScannerZoomConfiguration"}],"roleHeading":"Type Property","navigatorTitle":[{"text":"defaultConfiguration","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBaseScannerZoomConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerZoomConfiguration","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerZoomConfiguration/defaultConfiguration":{"kind":"symbol","abstract":[{"type":"text","text":"This is the default configuration with the properties initialized as mentioned in their description."}],"title":"defaultConfiguration","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerZoomConfiguration","text":"SBSDKBaseScannerZoomConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerzoomconfiguration\/defaultconfiguration","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration\/defaultConfiguration","navigatorTitle":[{"kind":"identifier","text":"defaultConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerZoomConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerzoomconfiguration","title":"SBSDKBaseScannerZoomConfiguration","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"abstract":[{"text":"The zoom configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"‘SBSDKBaseScannerViewController’ and subclasses allow the user to zoom the camera."},{"type":"text","text":" "},{"type":"text","text":"This class lets you customize the zooming user experience."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"defaultConfiguration"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"defaultConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerZoomConfiguration","kind":"typeIdentifier","text":"SBSDKBaseScannerZoomConfiguration"},{"kind":"text","text":" * "},{"text":"defaultConfiguration","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration~1defaultConfiguration\/title","op":"replace","value":"defaultConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration~1defaultConfiguration\/fragments","value":[{"kind":"identifier","text":"defaultConfiguration"}]},{"value":"SBSDKBaseScannerZoomConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerZoomConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration\/navigatorTitle"}]}]}