{"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"isDoubleTapToZoomEnabled","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDoubleTapToZoomEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isDoubleTapToZoomEnabled","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerZoomConfiguration(py)isDoubleTapToZoomEnabled"},"abstract":[{"type":"text","text":"When this property is set to YES, the zoom can be toggled between the minimum and maximum zoom factor, defined in the zoomRange property, by just double-tapping anywhere in the base scanner view controllers view."},{"type":"text","text":" "},{"type":"text","text":"If set to "},{"code":"False","type":"codeVoice"},{"type":"text","text":", zooming by double-tapping will be disabled."},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"code":"True","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerzoomconfiguration\/isdoubletaptozoomenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerzoomconfiguration\/isdoubletaptozoomenabled"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDoubleTapToZoomEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration\/isDoubleTapToZoomEnabled","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerZoomConfiguration":{"abstract":[{"type":"text","text":"The zoom configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"type":"text","text":" "},{"text":"‘SBSDKBaseScannerViewController’ and subclasses allow the user to zoom the camera.","type":"text"},{"type":"text","text":" "},{"text":"This class lets you customize the zooming user experience.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerzoomconfiguration","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerZoomConfiguration"}],"title":"SBSDKBaseScannerZoomConfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerZoomConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerZoomConfiguration/isDoubleTapToZoomEnabled":{"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isDoubleTapToZoomEnabled"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDoubleTapToZoomEnabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration\/isDoubleTapToZoomEnabled","abstract":[{"text":"When this property is set to YES, the zoom can be toggled between the minimum and maximum zoom factor, defined in the zoomRange property, by just double-tapping anywhere in the base scanner view controllers view.","type":"text"},{"type":"text","text":" "},{"text":"If set to ","type":"text"},{"code":"False","type":"codeVoice"},{"type":"text","text":", zooming by double-tapping will be disabled."},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"code":"True","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerzoomconfiguration\/isdoubletaptozoomenabled","title":"isDoubleTapToZoomEnabled"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"isDoubleTapToZoomEnabled","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"isDoubleTapToZoomEnabled","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDoubleTapToZoomEnabled"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration\/title","value":"SBSDKBaseScannerZoomConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration\/fragments","value":[{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration~1isDoubleTapToZoomEnabled\/title","value":"isDoubleTapToZoomEnabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration~1isDoubleTapToZoomEnabled\/fragments","value":[{"text":"isDoubleTapToZoomEnabled","kind":"identifier"}],"op":"replace"}]}]}