{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPinchToZoomEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration\/isPinchToZoomEnabled","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"isPinchToZoomEnabled"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isPinchToZoomEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isPinchToZoomEnabled","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerZoomConfiguration(py)isPinchToZoomEnabled"},"abstract":[{"type":"text","text":"When this property is set to YES, the camera zoom can be controlled by a pinch gesture anywhere in the base scannner view controllers view."},{"text":" ","type":"text"},{"type":"text","text":"If set to "},{"type":"codeVoice","code":"False"},{"type":"text","text":", zooming by pinching will be disabled."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"True"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerzoomconfiguration\/ispinchtozoomenabled"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerzoomconfiguration\/ispinchtozoomenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerZoomConfiguration/isPinchToZoomEnabled":{"title":"isPinchToZoomEnabled","abstract":[{"type":"text","text":"When this property is set to YES, the camera zoom can be controlled by a pinch gesture anywhere in the base scannner view controllers view."},{"text":" ","type":"text"},{"type":"text","text":"If set to "},{"type":"codeVoice","code":"False"},{"type":"text","text":", zooming by pinching will be disabled."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"True"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration\/isPinchToZoomEnabled","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPinchToZoomEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isPinchToZoomEnabled"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerzoomconfiguration\/ispinchtozoomenabled","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerZoomConfiguration":{"title":"SBSDKBaseScannerZoomConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The zoom configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"‘SBSDKBaseScannerViewController’ and subclasses allow the user to zoom the camera."},{"type":"text","text":" "},{"text":"This class lets you customize the zooming user experience.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerzoomconfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerZoomConfiguration"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"isPinchToZoomEnabled"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"isPinchToZoomEnabled","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPinchToZoomEnabled"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration~1isPinchToZoomEnabled\/title","value":"isPinchToZoomEnabled","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration~1isPinchToZoomEnabled\/fragments","value":[{"kind":"identifier","text":"isPinchToZoomEnabled"}]},{"op":"replace","value":"SBSDKBaseScannerZoomConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBaseScannerZoomConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}