{"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldConsistencyVerificationReport(py)hash","roleHeading":"Instance Property","symbolKind":"property","title":"hash","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"fragments":[{"text":"hash","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfieldconsistencyverificationreport\/hash"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport\/hash","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldConsistencyVerificationReport/hash":{"type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport\/hash","fragments":[{"kind":"identifier","text":"hash"}],"title":"hash","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfieldconsistencyverificationreport\/hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldConsistencyVerificationReport":{"type":"topic","abstract":[{"type":"text","text":"Report of the field consistency verification."}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKFieldConsistencyVerificationReport","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFieldConsistencyVerificationReport","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfieldconsistencyverificationreport","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport","title":"SBSDKFieldConsistencyVerificationReport","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldConsistencyVerificationReport\/title","value":"SBSDKFieldConsistencyVerificationReport","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldConsistencyVerificationReport\/fragments","value":[{"kind":"identifier","text":"SBSDKFieldConsistencyVerificationReport"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldConsistencyVerificationReport\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFieldConsistencyVerificationReport"}],"op":"replace"}]}]}