{"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeMappedResult\/barcode"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeMappedResult"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodemappedresult\/barcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodemappedresult\/barcode"]}],"abstract":[{"type":"text","text":"Barcode result."}],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"barcode","platforms":[],"symbolKind":"property","navigatorTitle":[{"text":"barcode","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeMappedResult(py)barcode","roleHeading":"Instance Property"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeMappedResult/barcode":{"title":"barcode","type":"topic","navigatorTitle":[{"text":"barcode","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodemappedresult\/barcode","deprecated":true,"abstract":[{"text":"Barcode result.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeMappedResult\/barcode"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeItem":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeItem","kind":"identifier"}],"abstract":[{"text":"A single barcode found in the input image. Barcodes with the same content but different locations in the image are","type":"text"},{"text":" ","type":"text"},{"text":"considered separate barcodes.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeitem","title":"SBSDKBarcodeItem","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeItem","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeMappedResult":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeMappedResult","deprecated":true,"abstract":[{"text":"Class that contains barcode result and mapped data.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeMappedResult","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIBarcodeMappedResult","kind":"identifier"}],"title":"SBSDKUIBarcodeMappedResult","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodemappedresult","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.3"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"barcode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"barcode","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem","text":"SBSDKBarcodeItem","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"barcode","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeMappedResult~1barcode\/title","value":"barcode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeMappedResult~1barcode\/fragments","value":[{"kind":"identifier","text":"barcode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/title","value":"SBSDKBarcodeItem"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/fragments","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/navigatorTitle","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeMappedResult\/title","value":"SBSDKUIBarcodeMappedResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeMappedResult\/fragments","value":[{"text":"SBSDKUIBarcodeMappedResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeMappedResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIBarcodeMappedResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}