{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2sheet\/init(mode:collapsedvisibleheight:listbutton:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2sheet\/init(mode:collapsedvisibleheight:listbutton:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"mode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2SheetMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2SheetMode","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2SheetMode.collapsedSheet, "},{"text":"collapsedVisibleHeight","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CollapsedVisibleHeight","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight","text":"SBSDKUI2CollapsedVisibleHeight"},{"text":" = SBSDKUI2CollapsedVisibleHeight.small, ","kind":"text"},{"text":"listButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BadgedButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgedButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgedButton"},{"kind":"text","text":" = SBSDKUI2BadgedButton())"}]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"init(mode:collapsedVisibleHeight:listButton:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"mode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2SheetMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2SheetMode"},{"text":", ","kind":"text"},{"text":"collapsedVisibleHeight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CollapsedVisibleHeight","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CollapsedVisibleHeight","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"listButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgedButton","text":"SBSDKUI2BadgedButton"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithMode:collapsedVisibleHeight:listButton:","kind":"identifier"}],"roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet(im)initWithMode:collapsedVisibleHeight:listButton:","symbolKind":"init"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet\/init(mode:collapsedVisibleHeight:listButton:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CollapsedVisibleHeight":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2collapsedvisibleheight","abstract":[{"type":"text","text":"Configuration of the barcodes result sheet’s height while collapsed."}],"title":"SBSDKUI2CollapsedVisibleHeight","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sheet/init(mode:collapsedVisibleHeight:listButton:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"mode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2SheetMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2SheetMode"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"collapsedVisibleHeight"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CollapsedVisibleHeight"},{"text":", ","kind":"text"},{"text":"listButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2BadgedButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgedButton"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithMode:collapsedVisibleHeight:listButton:","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2sheet\/init(mode:collapsedvisibleheight:listbutton:)","abstract":[],"type":"topic","title":"init(mode:collapsedVisibleHeight:listButton:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet\/init(mode:collapsedVisibleHeight:listButton:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetMode":{"title":"SBSDKUI2SheetMode","type":"topic","abstract":[{"text":"Configuration of the barcode result sheet’s default visibility state.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2SheetMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sheetmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SheetMode"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BadgedButton":{"navigatorTitle":[{"text":"SBSDKUI2BadgedButton","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2badgedbutton","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BadgedButton","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"SBSDKUI2BadgedButton","abstract":[{"type":"text","text":"Configuration of the round button with badge."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgedButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sheet":{"abstract":[{"text":"Configuration of the preview mode for scanning multiple barcodes.","type":"text"}],"type":"topic","title":"SBSDKUI2Sheet","url":"\/documentation\/scanbotsdk\/sbsdkui2sheet","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2Sheet"}],"navigatorTitle":[{"text":"SBSDKUI2Sheet","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithMode:collapsedVisibleHeight:listButton:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithMode:collapsedVisibleHeight:listButton:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2SheetMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetMode","kind":"typeIdentifier","text":"SBSDKUI2SheetMode"},{"kind":"text","text":") "},{"text":"mode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"collapsedVisibleHeight:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CollapsedVisibleHeight","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight","text":"SBSDKUI2CollapsedVisibleHeight"},{"kind":"text","text":") "},{"text":"collapsedVisibleHeight","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"listButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2BadgedButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgedButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgedButton","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"listButton","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKUI2CollapsedVisibleHeight","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeight"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet~1init(mode:collapsedVisibleHeight:listButton:)\/title","op":"replace","value":"initWithMode:collapsedVisibleHeight:listButton:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet~1init(mode:collapsedVisibleHeight:listButton:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMode:collapsedVisibleHeight:listButton:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetMode\/title","value":"SBSDKUI2SheetMode"},{"value":[{"kind":"identifier","text":"SBSDKUI2SheetMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgedButton\/title","value":"SBSDKUI2BadgedButton"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BadgedButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgedButton\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/title","value":"SBSDKUI2Sheet","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Sheet"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/fragments","op":"replace"}]}]}