{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage"]]},"abstract":[{"type":"text","text":"Returns the URL of the stored image at the specified index."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"index","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]},{"parameters":[{"name":"index","content":[{"inlineContent":[{"type":"text","text":"A valid index of the image."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The images "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" at the given index, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the image file does not exist."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/imageurl(at:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/imageurl(at:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/imageURL(at:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKIndexedImageStorage(im)imageURLAtIndex:","navigatorTitle":[{"kind":"identifier","text":"imageURLAtIndex:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"title":"imageURL(at:)","symbolKind":"method"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage","navigatorTitle":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class."},{"type":"text","text":" "},{"type":"text","text":"Manages images in an array-like fashion."}],"kind":"symbol","title":"SBSDKIndexedImageStorage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKIndexedImageStorage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/imageURL(at:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/imageURL(at:)","abstract":[{"text":"Returns the URL of the stored image at the specified index.","type":"text"}],"navigatorTitle":[{"text":"imageURLAtIndex:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/imageurl(at:)","type":"topic","kind":"symbol","role":"symbol","title":"imageURL(at:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"imageURLAtIndex:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageURLAtIndex:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"imageURLAtIndex:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"index"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKIndexedImageStorage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/title","op":"replace"},{"value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/fragments","op":"replace"},{"value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/navigatorTitle","op":"replace"},{"value":"imageURLAtIndex:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1imageURL(at:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"imageURLAtIndex:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1imageURL(at:)\/fragments","op":"replace"}]}]}