{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/waitUntilWritingCompleted()"},"metadata":{"title":"waitUntilWritingCompleted()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitUntilWritingCompleted","kind":"identifier"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"waitUntilWritingCompleted","kind":"identifier"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKIndexedImageStorage(im)waitUntilWritingCompleted","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"type":"text","text":"Blocks the current thread until all enqueued writing operations have been finished."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitUntilWritingCompleted"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/waituntilwritingcompleted()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/waituntilwritingcompleted()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/waitUntilWritingCompleted()":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/waitUntilWritingCompleted()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitUntilWritingCompleted","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"waitUntilWritingCompleted","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/waituntilwritingcompleted()","abstract":[{"text":"Blocks the current thread until all enqueued writing operations have been finished.","type":"text"}],"title":"waitUntilWritingCompleted()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage","navigatorTitle":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class."},{"type":"text","text":" "},{"type":"text","text":"Manages images in an array-like fashion."}],"kind":"symbol","title":"SBSDKIndexedImageStorage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKIndexedImageStorage","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"waitUntilWritingCompleted"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"waitUntilWritingCompleted","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"waitUntilWritingCompleted"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1waitUntilWritingCompleted()\/title","op":"replace","value":"waitUntilWritingCompleted"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1waitUntilWritingCompleted()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"waitUntilWritingCompleted","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/title","op":"replace","value":"SBSDKIndexedImageStorage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/navigatorTitle","op":"replace","value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}]}]}]}