{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController\/setCameraZoom(factor:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller\/setcamerazoom(factor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller\/setcamerazoom(factor:)"]}],"sections":[],"abstract":[{"type":"text","text":"Sets the zoom factor to the specified value."},{"type":"text","text":" "},{"text":"The zoom range must be specified in the receivers zoomConfigurations zoomRange property.","type":"text"},{"type":"text","text":" "},{"text":"A zoom animation will be played if the receivers zoomConfigurations shouldAnimateZooming property is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(setCameraZoomFactor:) ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCameraZoom"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"factor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A value between 0.0 (the minimum value of the zoom range) and 1.0","type":"text"},{"type":"text","text":" "},{"type":"text","text":"(the maximum value of the zoom range). Values outside the (0.0 - 1.0) range will be clipped."}]}],"name":"factor"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"setCameraZoom(factor:)","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setCameraZoom","kind":"identifier"},{"kind":"text","text":"("},{"text":"factor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setCameraZoomFactor:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerViewController(im)setCameraZoomFactor:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"type":"topic","title":"SBSDKBaseScannerViewController","abstract":[{"text":"A highly customizable camera view controller that delivers a basic camera functionality along with video","type":"text"},{"text":" ","type":"text"},{"text":"frame extraction and preprocessing, orientation correction and still image capturing.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewController/setCameraZoom(factor:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setCameraZoom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"factor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller\/setcamerazoom(factor:)","abstract":[{"text":"Sets the zoom factor to the specified value.","type":"text"},{"text":" ","type":"text"},{"text":"The zoom range must be specified in the receivers zoomConfigurations zoomRange property.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"A zoom animation will be played if the receivers zoomConfigurations shouldAnimateZooming property is set to "},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","role":"symbol","title":"setCameraZoom(factor:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController\/setCameraZoom(factor:)","kind":"symbol","navigatorTitle":[{"text":"setCameraZoomFactor:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"setCameraZoomFactor:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"setCameraZoomFactor:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setCameraZoomFactor:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"text":"factor","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"factor","content":[{"type":"paragraph","inlineContent":[{"text":"A value between 0.0 (the minimum value of the zoom range) and 1.0","type":"text"},{"type":"text","text":" "},{"text":"(the maximum value of the zoom range). Values outside the (0.0 - 1.0) range will be clipped.","type":"text"}]}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/title","value":"SBSDKBaseScannerViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/fragments","value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/navigatorTitle"},{"value":"setCameraZoomFactor:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController~1setCameraZoom(factor:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setCameraZoomFactor:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController~1setCameraZoom(factor:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}