{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithNoDocumentFound:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"noDocumentFound"},{"kind":"text","text":" "},{"kind":"identifier","text":"badAspectRatio:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"badAspectRatio"},{"kind":"text","text":" "},{"kind":"identifier","text":"badAngles:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"badAngles"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationMismatch:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"orientationMismatch"},{"kind":"text","text":" "},{"kind":"identifier","text":"textHintOffCenter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textHintOffCenter"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooSmall:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tooSmall"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooNoisy:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tooNoisy"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooDark:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tooDark"},{"kind":"text","text":" "},{"kind":"identifier","text":"energySaveMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"energySaveMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"readyToCapture:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"readyToCapture"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturing:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"capturing"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureManual:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"captureManual"},{"kind":"text","text":";"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceStates(im)initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","roleHeading":"Instance Method","title":"initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","kind":"identifier"}],"symbolKind":"method"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/initwithnodocumentfound:badaspectratio:badangles:orientationmismatch:texthintoffcenter:toosmall:toonoisy:toodark:energysavemode:readytocapture:capturing:capturemanual:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2UserGuidanceStates"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceStates"}],"title":"SBSDKUI2UserGuidanceStates","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates","abstract":[{"text":"Configure the titles of the user guidance hints for different states.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/initwithnodocumentfound:badaspectratio:badangles:orientationmismatch:texthintoffcenter:toosmall:toonoisy:toodark:energysavemode:readytocapture:capturing:capturemanual:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:"}],"kind":"symbol","abstract":[],"title":"initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates\/title","value":"SBSDKUI2UserGuidanceStates"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates\/fragments","value":[{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates\/navigatorTitle","value":[{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}]}]}]}