{"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPDFPagesExtractor(im)imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:","role":"symbol","navigatorTitle":[{"text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"imageURLs","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scaling"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"compression","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"encrypter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"outputDirectory"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKProgress"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfpagesextractor\/imageurls(from:scaling:compression:encrypter:outputdirectory:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfpagesextractor\/imageurls(from:scaling:compression:encrypter:outputdirectory:completion:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageURLs","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"text":"pdfURL","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scaling","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compression"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encrypter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"outputDirectory"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" ([","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"text":"SBSDKProgress","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKProgress","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProgress"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"pdfURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL of the PDF file."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Scaling applied to the PDF media box frame while extracting. Affects the output image quality. In most cases the recommended value is 2 and higher."}],"type":"paragraph"}],"name":"scaling"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Compression of the output image file. The range is from 0 to 1, where 1 - lossless conversion, 0 - maximum compression is used."}]}],"name":"compression"},{"name":"encrypter","content":[{"inlineContent":[{"type":"text","text":"The encrypter used to encrypt output image files. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", no encryption is used."}],"type":"paragraph"}]},{"name":"outputDirectory","content":[{"type":"paragraph","inlineContent":[{"text":"The output folder where images will be stored. If the folder does not exist, it will be created.","type":"text"}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The completion handler that delivers the created array of image file URLs."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A progress object that can be used for cancellation and progress observing. If "},{"type":"codeVoice","code":"nil"},{"text":", an error occurred.","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Asynchronously extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL."},{"text":" ","type":"text"},{"type":"text","text":"The array of URLs is passed within the completion handler."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPDFPagesExtractor/imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)":{"abstract":[{"type":"text","text":"Asynchronously extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL."},{"type":"text","text":" "},{"text":"The array of URLs is passed within the completion handler.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"imageURLs","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"text":"scaling","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"text":"compression","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"text":"outputDirectory","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ([","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":") -> ","kind":"text"},{"text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKProgress"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfpagesextractor\/imageurls(from:scaling:compression:encrypter:outputdirectory:completion:)","kind":"symbol","navigatorTitle":[{"text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:","kind":"identifier"}],"role":"symbol","type":"topic","title":"imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPDFPagesExtractor":{"kind":"symbol","title":"SBSDKPDFPagesExtractor","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}],"abstract":[{"text":"Class used to extract pages from a PDF file and returns them in various ways.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFPagesExtractor","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfpagesextractor"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","kind":"symbol","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCrypting":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Protocol for implementing encryption and decryption of (streamed) data."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKStorageCrypting","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecrypting","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"title":"SBSDKStorageCrypting","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKProgress":{"navigatorTitle":[{"text":"SBSDKProgress","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkprogress","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProgress","title":"SBSDKProgress","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKProgress"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProgress","text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKProgress"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"imageURLsFromPDF:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"text":" *) ","kind":"text"},{"text":"pdfURL","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scaling:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"scaling","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"compression:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"compression","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encrypter:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting","text":"id<SBSDKStorageCrypting>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"encrypter","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputDirectory:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"outputDirectory"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"text":"NSArray<NSURL *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"pdfURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL of the PDF file."}]}]},{"name":"scaling","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Scaling applied to the PDF media box frame while extracting. Affects the output image quality. In most cases the recommended value is 2 and higher."}]}]},{"name":"compression","content":[{"type":"paragraph","inlineContent":[{"text":"Compression of the output image file. The range is from 0 to 1, where 1 - lossless conversion, 0 - maximum compression is used.","type":"text"}]}]},{"name":"encrypter","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The encrypter used to encrypt output image files. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", no encryption is used."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The output folder where images will be stored. If the folder does not exist, it will be created."}],"type":"paragraph"}],"name":"outputDirectory"},{"content":[{"inlineContent":[{"text":"The completion handler that delivers the created array of image file URLs.","type":"text"}],"type":"paragraph"}],"name":"completion"}]},"path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"A progress object that can be used for cancellation and progress observing. If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", an error occurred.","type":"text"}]}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)\/title","value":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor\/title","op":"replace","value":"SBSDKPDFPagesExtractor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}],"op":"replace"},{"value":[{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFPagesExtractor\/navigatorTitle"},{"value":"SBSDKStorageCrypting","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProgress\/title","value":"SBSDKProgress"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProgress\/fragments","value":[{"text":"SBSDKProgress","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProgress\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKProgress"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}