{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfieldtype\/insuredpersonnumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfieldtype\/insuredpersonnumber"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"insuredPersonNumber"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insuredPersonNumber","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerResultPatientFieldType@SBSDKMedicalCertificateRecognizerResultPatientFieldTypeInsuredPersonNumber","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeInsuredPersonNumber"}],"title":"SBSDKMedicalCertificateRecognizerResultPatientFieldType.insuredPersonNumber","symbolKind":"case","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientFieldType\/insuredPersonNumber"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientFieldType"]]},"abstract":[{"type":"text","text":"The patient’s insured person number."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResultPatientFieldType/insuredPersonNumber":{"type":"topic","role":"symbol","kind":"symbol","title":"SBSDKMedicalCertificateRecognizerResultPatientFieldType.insuredPersonNumber","abstract":[{"type":"text","text":"The patient’s insured person number."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientFieldType\/insuredPersonNumber","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"insuredPersonNumber"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeInsuredPersonNumber"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfieldtype\/insuredpersonnumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResultPatientFieldType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientFieldType","title":"SBSDKMedicalCertificateRecognizerResultPatientFieldType","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerResultPatientFieldType","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfieldtype","role":"symbol","abstract":[{"type":"text","text":"The various types of fields inside the patient information field of a medical certificate."}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeInsuredPersonNumber","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeInsuredPersonNumber","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeInsuredPersonNumber"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType~1insuredPersonNumber\/title","op":"replace","value":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeInsuredPersonNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType~1insuredPersonNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeInsuredPersonNumber"}]},{"value":"SBSDKMedicalCertificateRecognizerResultPatientFieldType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldType"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificateRecognizerResultPatientFieldType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}