{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkocrenginemode\/scanbotocr"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkocrenginemode\/scanbotocr"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/scanbotOCR","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanbotOCR"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanbotOCR","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKOCREngineModeScanbotOCR","kind":"identifier"}],"title":"SBSDKOCREngineMode.scanbotOCR","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKOCREngineMode@SBSDKOCREngineModeScanbotOCR","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The new machine-learning based mode made by Scanbot SDK GmbH. Faster, less errors, but currently only","type":"text"},{"text":" ","type":"text"},{"text":"supports languages with latin letters.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineMode":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCREngineMode"}],"abstract":[{"type":"text","text":"An enum describing the modes of the optical character recognition engine."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCREngineMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrenginemode","type":"topic","title":"SBSDKOCREngineMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineMode/scanbotOCR":{"abstract":[{"text":"The new machine-learning based mode made by Scanbot SDK GmbH. Faster, less errors, but currently only","type":"text"},{"type":"text","text":" "},{"type":"text","text":"supports languages with latin letters."}],"url":"\/documentation\/scanbotsdk\/sbsdkocrenginemode\/scanbotocr","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanbotOCR","kind":"identifier"}],"title":"SBSDKOCREngineMode.scanbotOCR","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/scanbotOCR","navigatorTitle":[{"text":"SBSDKOCREngineModeScanbotOCR","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKOCREngineModeScanbotOCR"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKOCREngineModeScanbotOCR","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKOCREngineModeScanbotOCR","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode\/title","op":"replace","value":"SBSDKOCREngineMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKOCREngineMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKOCREngineMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode~1scanbotOCR\/title","op":"replace","value":"SBSDKOCREngineModeScanbotOCR"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode~1scanbotOCR\/fragments","op":"replace","value":[{"text":"SBSDKOCREngineModeScanbotOCR","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}