{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingconfiguration\/tojson()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingconfiguration\/tojson()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"method","navigatorTitle":[{"text":"toJson","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingConfiguration(im)toJson","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"toJson()","role":"symbol"},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingConfiguration\/toJson()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}]}],"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingConfiguration"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingConfiguration/toJson()":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingConfiguration\/toJson()","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"role":"symbol","type":"topic","title":"toJson()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingconfiguration\/tojson()","navigatorTitle":[{"kind":"identifier","text":"toJson"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingConfiguration":{"abstract":[{"text":"Configuration of the standalone cropping screen.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingConfiguration","title":"SBSDKUI2CroppingConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"toJson"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"toJson","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"toJson","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"toJson","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingConfiguration~1toJson()\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingConfiguration~1toJson()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJson","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingConfiguration\/title","value":"SBSDKUI2CroppingConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingConfiguration\/navigatorTitle"}]}]}