{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/manualSnap"},"metadata":{"roleHeading":"Case","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"SBSDKDocumentPageImageSource.manualSnap","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceManualSnap"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentPageImageSource@SBSDKDocumentPageImageSourceManualSnap","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"manualSnap"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource\/manualsnap"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource\/manualsnap"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"If the source image was captured manually. For example, when the user pressed a snap button.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"manualSnap","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageImageSource/manualSnap":{"abstract":[{"type":"text","text":"If the source image was captured manually. For example, when the user pressed a snap button."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/manualSnap","title":"SBSDKDocumentPageImageSource.manualSnap","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceManualSnap"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"manualSnap","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource\/manualsnap","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageImageSource":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageImageSource"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"abstract":[{"text":"The source from where the image of the page originated from.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource","role":"symbol","title":"SBSDKDocumentPageImageSource"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 5.0.2","type":"text"}],"role":"collection","type":"topic","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKDocumentPageImageSourceManualSnap"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKDocumentPageImageSourceManualSnap","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceManualSnap"}]}]}},{"op":"replace","value":"SBSDKDocumentPageImageSourceManualSnap","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource~1manualSnap\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceManualSnap"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource~1manualSnap\/fragments"},{"value":"SBSDKDocumentPageImageSource","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource\/fragments","value":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}