{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource\/videoframe"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource\/videoframe"]}],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentPageImageSource@SBSDKDocumentPageImageSourceVideoFrame","symbolKind":"case","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","title":"SBSDKDocumentPageImageSource.videoFrame","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoFrame"}],"navigatorTitle":[{"text":"SBSDKDocumentPageImageSourceVideoFrame","kind":"identifier"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/videoFrame"},"abstract":[{"type":"text","text":"If the source image was taken from the video frame."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoFrame","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageImageSource/videoFrame":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource\/videoframe","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/videoFrame","abstract":[{"text":"If the source image was taken from the video frame.","type":"text"}],"kind":"symbol","role":"symbol","title":"SBSDKDocumentPageImageSource.videoFrame","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"videoFrame","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentPageImageSourceVideoFrame","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageImageSource":{"kind":"symbol","abstract":[{"type":"text","text":"The source from where the image of the page originated from."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentPageImageSource"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"title":"SBSDKDocumentPageImageSource","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.2.1"}],"type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"SBSDKDocumentPageImageSourceVideoFrame","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"SBSDKDocumentPageImageSourceVideoFrame","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceVideoFrame"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource~1videoFrame\/title","op":"replace","value":"SBSDKDocumentPageImageSourceVideoFrame"},{"value":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceVideoFrame"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource~1videoFrame\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource\/title","op":"replace","value":"SBSDKDocumentPageImageSource"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource\/fragments","value":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"op":"replace"}]}]}