{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat\/code128"},"abstract":[{"text":"Code 128 barcode type","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeformat\/code128"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeformat\/code128"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"code128","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"code128"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat(cpy)code128","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"code128"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat"}],"title":"code128"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeFormat":{"role":"symbol","abstract":[{"text":"Barcode symbology used.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat","title":"SBSDKUI2BarcodeFormat","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeFormat","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeFormat","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeFormat/code128":{"abstract":[{"type":"text","text":"Code 128 barcode type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat\/code128","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeformat\/code128","navigatorTitle":[{"text":"code128","kind":"identifier"}],"title":"code128","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"code128","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"value":"code128","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"code128"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","text":"SBSDKUI2BarcodeFormat","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"code128","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/title","value":"SBSDKUI2BarcodeFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeFormat"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeFormat"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/navigatorTitle","op":"replace"},{"value":"code128","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat~1code128\/title"},{"value":[{"kind":"identifier","text":"code128"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat~1code128\/fragments","op":"replace"}]}]}