{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceInformation"]]},"metadata":{"roleHeading":"Type Method","title":"freeDiskSpaceInBytes()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"freeDiskSpaceInBytes","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"}],"symbolKind":"method","navigatorTitle":[{"text":"freeDiskSpaceInBytes","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKDeviceInformation(cm)freeDiskSpaceInBytes"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkdeviceinformation\/freediskspaceinbytes()"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkdeviceinformation\/freediskspaceinbytes()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The amount of unused disk space of the device in bytes.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"freeDiskSpaceInBytes","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The amount of unused disk space of the device in bytes. In case of error the return value is -1."}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceInformation\/freeDiskSpaceInBytes()"},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKDeviceInformation":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceInformation","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkdeviceinformation","kind":"symbol","abstract":[{"text":"Helper class that delivers information about the used iOS device.","type":"text"}],"title":"SBSDKDeviceInformation","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDeviceInformation","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDeviceInformation","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKDeviceInformation/freeDiskSpaceInBytes()":{"kind":"symbol","title":"freeDiskSpaceInBytes()","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceInformation\/freeDiskSpaceInBytes()","abstract":[{"type":"text","text":"The amount of unused disk space of the device in bytes."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkdeviceinformation\/freediskspaceinbytes()","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"freeDiskSpaceInBytes"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"freeDiskSpaceInBytes","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"freeDiskSpaceInBytes"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"freeDiskSpaceInBytes"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":") "},{"text":"freeDiskSpaceInBytes","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The amount of unused disk space of the device in bytes. In case of error the return value is -1."}]}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceInformation\/title","value":"SBSDKDeviceInformation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceInformation\/fragments","value":[{"text":"SBSDKDeviceInformation","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKDeviceInformation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceInformation\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceInformation~1freeDiskSpaceInBytes()\/title","value":"freeDiskSpaceInBytes"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceInformation~1freeDiskSpaceInBytes()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"freeDiskSpaceInBytes","kind":"identifier"}],"op":"replace"}]}]}