{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceInformation\/totalDiskSpaceInBytes()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceInformation"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalDiskSpaceInBytes"},{"text":"() -> ","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The total amount of disk space of the device in bytes. In case of error the return value is -1."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkdeviceinformation\/totaldiskspaceinbytes()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkdeviceinformation\/totaldiskspaceinbytes()"]}],"abstract":[{"type":"text","text":"The total amount of disk space of the device in bytes."}],"sections":[],"metadata":{"title":"totalDiskSpaceInBytes()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalDiskSpaceInBytes"},{"text":"() -> ","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"}],"symbolKind":"method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKDeviceInformation(cm)totalDiskSpaceInBytes","roleHeading":"Type Method","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"totalDiskSpaceInBytes","kind":"identifier"}],"role":"symbol"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKDeviceInformation/totalDiskSpaceInBytes()":{"navigatorTitle":[{"text":"totalDiskSpaceInBytes","kind":"identifier"}],"kind":"symbol","title":"totalDiskSpaceInBytes()","type":"topic","abstract":[{"text":"The total amount of disk space of the device in bytes.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceInformation\/totalDiskSpaceInBytes()","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkdeviceinformation\/totaldiskspaceinbytes()","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"totalDiskSpaceInBytes","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKDeviceInformation":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceInformation","navigatorTitle":[{"kind":"identifier","text":"SBSDKDeviceInformation"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkdeviceinformation","type":"topic","title":"SBSDKDeviceInformation","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDeviceInformation"}],"abstract":[{"text":"Helper class that delivers information about the used iOS device.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"totalDiskSpaceInBytes"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"totalDiskSpaceInBytes","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@T@int64_t","kind":"typeIdentifier","text":"int64_t"},{"kind":"text","text":") "},{"text":"totalDiskSpaceInBytes","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The total amount of disk space of the device in bytes. In case of error the return value is -1."}]}],"kind":"content"},"op":"replace"},{"value":"totalDiskSpaceInBytes","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceInformation~1totalDiskSpaceInBytes()\/title","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"totalDiskSpaceInBytes"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceInformation~1totalDiskSpaceInBytes()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceInformation\/title","value":"SBSDKDeviceInformation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceInformation\/fragments","value":[{"kind":"identifier","text":"SBSDKDeviceInformation"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceInformation\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDeviceInformation"}]}]}]}