{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2topbarmode\/gradient"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2topbarmode\/gradient"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarMode"]]},"kind":"symbol","metadata":{"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2TopBarMode@SBSDKUI2TopBarModeGradient","title":"SBSDKUI2TopBarMode.gradient","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gradient","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TopBarModeGradient"}],"symbolKind":"case","role":"symbol"},"abstract":[{"type":"text","text":"Display the top bar with a gradient background color or a transparent gradient. The buttons will still be"},{"type":"text","text":" "},{"type":"text","text":"visible."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gradient"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarMode\/gradient","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TopBarMode/gradient":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarMode\/gradient","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TopBarModeGradient"}],"title":"SBSDKUI2TopBarMode.gradient","url":"\/documentation\/scanbotsdk\/sbsdkui2topbarmode\/gradient","abstract":[{"type":"text","text":"Display the top bar with a gradient background color or a transparent gradient. The buttons will still be"},{"text":" ","type":"text"},{"text":"visible.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"gradient","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TopBarMode":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2topbarmode","type":"topic","abstract":[{"type":"text","text":"Visual mode used for the top bar."}],"role":"symbol","title":"SBSDKUI2TopBarMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TopBarMode"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TopBarMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2TopBarModeGradient"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2TopBarModeGradient","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKUI2TopBarModeGradient","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarMode~1gradient\/title","value":"SBSDKUI2TopBarModeGradient","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarMode~1gradient\/fragments","value":[{"text":"SBSDKUI2TopBarModeGradient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarMode\/title","value":"SBSDKUI2TopBarMode"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2TopBarMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarMode\/fragments"},{"value":[{"text":"SBSDKUI2TopBarMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarMode\/navigatorTitle"}]}]}