{"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"minimumNumberOfRequiredFramesWithEqualRecognitionResult","navigatorTitle":[{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCommonOneDConfiguration(py)minimumNumberOfRequiredFramesWithEqualRecognitionResult","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"]}]},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"Default is 1"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonOneDConfiguration\/minimumNumberOfRequiredFramesWithEqualRecognitionResult"},"sections":[],"abstract":[{"text":"Minimum number of frames on which a linear (1D) barcode has to be detected to be considered valid (live scanning","type":"text"},{"text":" ","type":"text"},{"text":"only).","type":"text"},{"text":" ","type":"text"},{"text":"Linear barcodes are more prone to false positives.","type":"text"},{"text":" ","type":"text"},{"text":"Increasing the number of frames on which a barcode has to decode to the same content reduces the probability of","type":"text"},{"text":" ","type":"text"},{"text":"a false positive.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommononedconfiguration\/minimumnumberofrequiredframeswithequalrecognitionresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommononedconfiguration\/minimumnumberofrequiredframeswithequalrecognitionresult"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonOneDConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonOneDConfiguration":{"role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatCommonOneDConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonOneDConfiguration","title":"SBSDKBarcodeFormatCommonOneDConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommononedconfiguration","abstract":[{"text":"Convenience configuration for enabling the scanning of multiple linear (1D) barcode formats with a common","type":"text"},{"type":"text","text":" "},{"type":"text","text":"configuration."},{"type":"text","text":" "},{"type":"text","text":"Add to scanner configuration to enable and configure the scanning of multiple linear (1D) barcode formats."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCommonOneDConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonOneDConfiguration/minimumNumberOfRequiredFramesWithEqualRecognitionResult":{"title":"minimumNumberOfRequiredFramesWithEqualRecognitionResult","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommononedconfiguration\/minimumnumberofrequiredframeswithequalrecognitionresult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonOneDConfiguration\/minimumNumberOfRequiredFramesWithEqualRecognitionResult","abstract":[{"text":"Minimum number of frames on which a linear (1D) barcode has to be detected to be considered valid (live scanning","type":"text"},{"text":" ","type":"text"},{"text":"only).","type":"text"},{"text":" ","type":"text"},{"text":"Linear barcodes are more prone to false positives.","type":"text"},{"text":" ","type":"text"},{"text":"Increasing the number of frames on which a barcode has to decode to the same content reduces the probability of","type":"text"},{"text":" ","type":"text"},{"text":"a false positive.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"minimumNumberOfRequiredFramesWithEqualRecognitionResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonOneDConfiguration\/title","value":"SBSDKBarcodeFormatCommonOneDConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonOneDConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonOneDConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonOneDConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonOneDConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonOneDConfiguration~1minimumNumberOfRequiredFramesWithEqualRecognitionResult\/title","value":"minimumNumberOfRequiredFramesWithEqualRecognitionResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonOneDConfiguration~1minimumNumberOfRequiredFramesWithEqualRecognitionResult\/fragments","value":[{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}