{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ThreeLineMRZFinderLayoutPreset(im)isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","title":"isEqual:","modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2threelinemrzfinderlayoutpreset\/isequal:"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset\/isEqual:"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ThreeLineMRZFinderLayoutPreset/isEqual:":{"title":"isEqual:","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2threelinemrzfinderlayoutpreset\/isequal:","abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset\/isEqual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ThreeLineMRZFinderLayoutPreset":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A ready-to-use preset 3-line text to be displayed."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2threelinemrzfinderlayoutpreset","navigatorTitle":[{"text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","kind":"identifier"}],"title":"SBSDKUI2ThreeLineMRZFinderLayoutPreset"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset\/title","value":"SBSDKUI2ThreeLineMRZFinderLayoutPreset"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset\/fragments","value":[{"text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset\/navigatorTitle","value":[{"text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}