{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/accumulationDuration"},"abstract":[{"type":"text","text":"Duration in milliseconds over which the document has to be detected as partially visible. If on any frame the"},{"type":"text","text":" "},{"type":"text","text":"document is not detected as partially visible, or detected as having a completely different Displacement, the"},{"type":"text","text":" "},{"type":"text","text":"accumulation will be reset. During the accumulation, the document scanner will return a status of"},{"type":"text","text":" "},{"type":"text","text":"ERROR_NOTHING_DETECTED instead of one of the partially visible statuses. Set to 0 to disable this behavior."}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accumulationDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"accumulationDuration","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"accumulationDuration","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPartiallyVisibleDocumentConfiguration(py)accumulationDuration","symbolKind":"property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accumulationDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is 700"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/accumulationduration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/accumulationduration"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration/accumulationDuration":{"url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/accumulationduration","title":"accumulationDuration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accumulationDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"accumulationDuration","kind":"identifier"}],"type":"topic","abstract":[{"text":"Duration in milliseconds over which the document has to be detected as partially visible. If on any frame the","type":"text"},{"text":" ","type":"text"},{"text":"document is not detected as partially visible, or detected as having a completely different Displacement, the","type":"text"},{"text":" ","type":"text"},{"text":"accumulation will be reset. During the accumulation, the document scanner will return a status of","type":"text"},{"text":" ","type":"text"},{"text":"ERROR_NOTHING_DETECTED instead of one of the partially visible statuses. Set to 0 to disable this behavior.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/accumulationDuration","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration","navigatorTitle":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration","abstract":[{"type":"text","text":"Configuration for handling partially visible documents."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"title":"SBSDKPartiallyVisibleDocumentConfiguration","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"accumulationDuration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"accumulationDuration"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"accumulationDuration","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1accumulationDuration\/title","op":"replace","value":"accumulationDuration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1accumulationDuration\/fragments","op":"replace","value":[{"text":"accumulationDuration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/title","op":"replace","value":"SBSDKPartiallyVisibleDocumentConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}