{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","title":"fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPartiallyVisibleDocumentConfiguration(cm)fromJsonWithJson:"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/fromJsonWithJson:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/fromjsonwithjson:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"SBSDKPartiallyVisibleDocumentConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPartiallyVisibleDocumentConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromJsonWithJson:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/fromjsonwithjson:","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/fromJsonWithJson:","title":"fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration","navigatorTitle":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration","abstract":[{"type":"text","text":"Configuration for handling partially visible documents."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"title":"SBSDKPartiallyVisibleDocumentConfiguration","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKPartiallyVisibleDocumentConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/title"},{"value":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/fragments"},{"value":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}