{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"acceptedFormats","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentFormat","text":"SBSDKBarcodeDocumentFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat"},{"kind":"text","text":"> = SBSDKBarcodeDocumentFormats.all) "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The configuration to use for the barcode document parser.","type":"text"}]}],"name":"acceptedFormats"}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"aside","style":"note","name":"Throws","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKError","isActive":true,"type":"reference"},{"type":"text","text":" in case of an error."}]}]}]}],"sections":[],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"setConfigurationWithAcceptedFormats:error:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentParser(im)setConfigurationWithAcceptedFormats:error:","role":"symbol","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"title":"setConfiguration(acceptedFormats:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConfiguration"},{"kind":"text","text":"("},{"kind":"externalParam","text":"acceptedFormats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SBSDKBarcodeDocumentFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat"},{"kind":"text","text":">) "},{"kind":"keyword","text":"throws"}]},"abstract":[{"type":"text","text":"Inplace reconfigures the API instance with new settings."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentParser"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentParser\/setConfiguration(acceptedFormats:)"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentparser\/setconfiguration(acceptedformats:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentparser\/setconfiguration(acceptedformats:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentFormat":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentformat","abstract":[{"type":"text","text":"Type of barcode document format used."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentFormat"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentFormat"}],"title":"SBSDKBarcodeDocumentFormat","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentFormat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentParser":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentParser","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentparser","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentParser","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentParser","kind":"identifier"}],"type":"topic","title":"SBSDKBarcodeDocumentParser","abstract":[{"text":"API for parsing barcode documents.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKError":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKError","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkerror","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKError","kind":"identifier"}],"type":"topic","title":"SBSDKError","abstract":[{"type":"text","text":"Represents errors that can occur within the Scanbot SDK."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentParser/setConfiguration(acceptedFormats:)":{"title":"setConfiguration(acceptedFormats:)","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentparser\/setconfiguration(acceptedformats:)","type":"topic","abstract":[{"type":"text","text":"Inplace reconfigures the API instance with new settings."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"acceptedFormats","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"SBSDKBarcodeDocumentFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat"},{"text":">) ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","navigatorTitle":[{"text":"setConfigurationWithAcceptedFormats:error:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentParser\/setConfiguration(acceptedFormats:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"setConfigurationWithAcceptedFormats:error:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setConfigurationWithAcceptedFormats:error:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setConfigurationWithAcceptedFormats:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKBarcodeDocumentFormat *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"acceptedFormats","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration to use for the barcode document parser."}]}],"name":"acceptedFormats"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}]}],"name":"error"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"add","value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"code":"YES","type":"codeVoice"},{"text":" if the method succeeded, otherwise ","type":"text"},{"code":"NO","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"SBSDKBarcodeDocumentFormat","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentFormat\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentFormat"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentFormat\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentFormat"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentFormat\/navigatorTitle"},{"op":"replace","value":"SBSDKBarcodeDocumentParser","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentParser\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeDocumentParser","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentParser\/fragments"},{"op":"replace","value":[{"text":"SBSDKBarcodeDocumentParser","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentParser\/navigatorTitle"},{"op":"replace","value":"setConfigurationWithAcceptedFormats:error:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentParser~1setConfiguration(acceptedFormats:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setConfigurationWithAcceptedFormats:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentParser~1setConfiguration(acceptedFormats:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}