{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"View.navigationDocument(_:preview:)","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"externalID":"s:7SwiftUI4ViewPAAE18navigationDocument_7previewQrqd___AA12SharePreviewVyqd_0_s5NeverOGt16CoreTransferable0K0Rd__AkLRd_0_r0_lF::SYNTHESIZED::s:10ScanbotSDK30SBSDKUI2TextPatternScannerViewV","role":"symbol","extendedModule":"SwiftUICore","modules":[{"name":"ScanbotSDK","relatedModules":["SwiftUICore"]}],"platforms":[{"introducedAt":"16.0","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"},{"introducedAt":"16.0","beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"16.0","beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"introducedAt":"13.0","beta":false,"unavailable":false,"deprecated":false,"name":"macOS"},{"introducedAt":"9.0","beta":false,"unavailable":false,"deprecated":false,"name":"watchOS"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navigationDocument","kind":"identifier"},{"text":"<","kind":"text"},{"text":"D","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"I","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"preview","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SharePreview","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI12SharePreviewV"},{"text":"<","kind":"text"},{"text":"I","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"},{"text":">) -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"title":"navigationDocument(_:preview:)"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navigationDocument","kind":"identifier"},{"text":"<","kind":"text"},{"text":"D","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"I","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"preview","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SharePreview","preciseIdentifier":"s:7SwiftUI12SharePreviewV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"I","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Never","preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"D","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Transferable","preciseIdentifier":"s:16CoreTransferable0B0P","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"I","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Transferable","preciseIdentifier":"s:16CoreTransferable0B0P","kind":"typeIdentifier"},{"text":"\n","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView\/navigationDocument(_:preview:)-74wfg","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView\/View-Implementations"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerview\/navigationdocument(_:preview:)-74wfg"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerView/navigationDocument(_:preview:)-74wfg":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationDocument"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"D"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"I"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI12SharePreviewV","text":"SharePreview"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"I"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO","text":"Never"},{"kind":"text","text":">) -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView\/navigationDocument(_:preview:)-74wfg","title":"navigationDocument(_:preview:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerview\/navigationdocument(_:preview:)-74wfg","kind":"symbol","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerView":{"type":"topic","title":"SBSDKUI2TextPatternScannerView","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerView"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextPatternScannerView"}],"abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerview"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerView/View-Implementations":{"abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerView\/View-Implementations","title":"View Implementations","kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerview\/view-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerviewcontroller","role":"symbol","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan generic text data.","type":"text"}],"title":"SBSDKUI2TextPatternScannerViewController","navigatorTitle":[{"text":"SBSDKUI2TextPatternScannerViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextPatternScannerViewController","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerViewController\/title","value":"SBSDKUI2TextPatternScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerViewController\/fragments","value":[{"text":"SBSDKUI2TextPatternScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUI2TextPatternScannerViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}