{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"init(json:partial:)","role":"symbol","extendedModule":"ScanbotSDK","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"initWithJson:partial:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"json","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"partial","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"symbolKind":"init","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUIVINScannerConfiguration(im)initWithJson:partial:","roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/init(json:partial:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"json"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"partial","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = true)","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscannerconfiguration\/init(json:partial:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscannerconfiguration\/init(json:partial:)"]}],"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerConfiguration/init(json:partial:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"json","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"partial"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithJson:partial:","kind":"identifier"}],"type":"topic","title":"init(json:partial:)","role":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerconfiguration\/init(json:partial:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/init(json:partial:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerConfiguration":{"role":"symbol","title":"SBSDKUIVINScannerConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIVINScannerConfiguration"}],"navigatorTitle":[{"text":"SBSDKUIVINScannerConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI vehicle identification number scanner."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithJson:partial:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithJson:partial:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithJson:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"json"},{"text":" ","kind":"text"},{"kind":"identifier","text":"partial:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"partial"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"initWithJson:partial:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration~1init(json:partial:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration~1init(json:partial:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithJson:partial:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration\/title","value":"SBSDKUIVINScannerConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration\/fragments","value":[{"text":"SBSDKUIVINScannerConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIVINScannerConfiguration","kind":"identifier"}]}]}]}