{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscanneruiresult\/textresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscanneruiresult\/textresult"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKTextPatternScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","kind":"typeIdentifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerUIResult"]]},"abstract":[{"type":"text","text":"Text result of the VIN scanner."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerUIResult\/textResult"},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerUIResult(py)textResult","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"textResult","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textResult","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","text":"SBSDKTextPatternScannerResult","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"textResult","kind":"identifier"}],"roleHeading":"Instance Property"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerUIResult":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the generic text scanner RTU UI result."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerUIResult","navigatorTitle":[{"text":"SBSDKUI2VINScannerUIResult","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2VINScannerUIResult","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscanneruiresult","title":"SBSDKUI2VINScannerUIResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerUIResult/textResult":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"textResult"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","kind":"typeIdentifier","text":"SBSDKTextPatternScannerResult"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscanneruiresult\/textresult","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerUIResult\/textResult","title":"textResult","type":"topic","abstract":[{"type":"text","text":"Text result of the VIN scanner."}],"navigatorTitle":[{"kind":"identifier","text":"textResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerResult":{"title":"SBSDKTextPatternScannerResult","role":"symbol","navigatorTitle":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","abstract":[{"text":"The result of the text line recognition.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"textResult","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"textResult"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKTextPatternScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult"},{"text":" * ","kind":"text"},{"text":"textResult","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerUIResult\/title","value":"SBSDKUI2VINScannerUIResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerUIResult\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerUIResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerUIResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerUIResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerUIResult~1textResult\/title","value":"textResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerUIResult~1textResult\/fragments","value":[{"text":"textResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/title","value":"SBSDKTextPatternScannerResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/fragments","value":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerResult"}],"op":"replace"}]}]}