{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatpharmacodetwotrackconfiguration\/minimumvalue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatpharmacodetwotrackconfiguration\/minimumvalue"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration(py)minimumValue","navigatorTitle":[{"text":"minimumValue","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"symbolKind":"property","title":"minimumValue"},"abstract":[{"text":"Minimum value for PHARMA_CODE_TWO_TRACK. Very low values are likely to produce more false positives.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/minimumValue","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Default is 364"}],"type":"paragraph"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatpharmacodetwotrackconfiguration","title":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","kind":"symbol","abstract":[{"type":"text","text":"PHARMA_CODE_TWO_TRACK barcode configuration. Add to scanner configuration to scan Laetus two-track PharmaCode barcodes. Linear (i.e. one-track) PharmaCode scanning is configured separately through the PharmaCodeConfig class."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration/minimumValue":{"navigatorTitle":[{"text":"minimumValue","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Minimum value for PHARMA_CODE_TWO_TRACK. Very low values are likely to produce more false positives.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatpharmacodetwotrackconfiguration\/minimumvalue","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/minimumValue","title":"minimumValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"minimumValue"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"minimumValue"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumValue"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/title","op":"replace","value":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration~1minimumValue\/title","op":"replace","value":"minimumValue"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration~1minimumValue\/fragments","op":"replace","value":[{"text":"minimumValue","kind":"identifier"}]}]}]}