{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncodingFormat\/jpeg"},"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKEncodingFormat@SBSDKEncodingFormatJpeg","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKEncodingFormat.jpeg","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncodingFormatJpeg"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jpeg"}],"symbolKind":"case","roleHeading":"Case"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"JPEG encoding.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncodingFormat"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkencodingformat\/jpeg"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkencodingformat\/jpeg"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jpeg"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEncodingFormat/jpeg":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKEncodingFormatJpeg","kind":"identifier"}],"abstract":[{"type":"text","text":"JPEG encoding."}],"title":"SBSDKEncodingFormat.jpeg","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkencodingformat\/jpeg","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncodingFormat\/jpeg","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEncodingFormat":{"navigatorTitle":[{"text":"SBSDKEncodingFormat","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkencodingformat","type":"topic","title":"SBSDKEncodingFormat","abstract":[{"text":"Image Encoding Format.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncodingFormat","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKEncodingFormat"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKEncodingFormatJpeg","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKEncodingFormatJpeg","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKEncodingFormatJpeg"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKEncodingFormatJpeg","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncodingFormat~1jpeg\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncodingFormat~1jpeg\/fragments","value":[{"text":"SBSDKEncodingFormatJpeg","kind":"identifier"}]},{"value":"SBSDKEncodingFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncodingFormat\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKEncodingFormat"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncodingFormat\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncodingFormat\/navigatorTitle","op":"replace","value":[{"text":"SBSDKEncodingFormat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}