{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorGlareDetectionConfiguration"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorGlareDetectionConfiguration(im)copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"symbolKind":"method","title":"copyWithZone:","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorglaredetectionconfiguration\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorGlareDetectionConfiguration\/copyWithZone:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorGlareDetectionConfiguration/copyWithZone:":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorglaredetectionconfiguration\/copywithzone:","kind":"symbol","abstract":[],"title":"copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorGlareDetectionConfiguration\/copyWithZone:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorGlareDetectionConfiguration":{"abstract":[{"type":"text","text":"Glare detection configuration."},{"type":"text","text":" "},{"type":"text","text":"The recognizer will detect whether fields are obstructed by glare. This feature is enabled by default."},{"type":"text","text":" "},{"type":"text","text":"This configuration has no effect in SINGLE_SHOT mode."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorGlareDetectionConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorglaredetectionconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractorGlareDetectionConfiguration"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorGlareDetectionConfiguration"}],"title":"SBSDKDocumentDataExtractorGlareDetectionConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorGlareDetectionConfiguration\/title","op":"replace","value":"SBSDKDocumentDataExtractorGlareDetectionConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorGlareDetectionConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDataExtractorGlareDetectionConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorGlareDetectionConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentDataExtractorGlareDetectionConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}