{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerintroimage\/creditcardintroonesideimage()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerintroimage\/creditcardintroonesideimage()"]}],"metadata":{"roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"creditCardIntroOneSideImage"}],"symbolKind":"method","title":"creditCardIntroOneSideImage()","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerIntroImage(cm)creditCardIntroOneSideImage","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"creditCardIntroOneSideImage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKUI2CreditCardIntroOneSideImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardIntroOneSideImage"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerIntroImage\/creditCardIntroOneSideImage()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerIntroImage"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardIntroOneSideImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKUI2CreditCardIntroOneSideImage","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardIntroOneSideImage"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerIntroImage":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerintroimage","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerIntroImage","role":"symbol","abstract":[{"text":"The image for the introduction screen of a credit card scanner screen.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerIntroImage"}],"title":"SBSDKUI2CreditCardScannerIntroImage","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerIntroImage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerIntroImage/creditCardIntroOneSideImage()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerIntroImage\/creditCardIntroOneSideImage()","navigatorTitle":[{"kind":"identifier","text":"creditCardIntroOneSideImage"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerintroimage\/creditcardintroonesideimage()","kind":"symbol","abstract":[],"role":"symbol","title":"creditCardIntroOneSideImage()","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"creditCardIntroOneSideImage"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardIntroOneSideImage","text":"SBSDKUI2CreditCardIntroOneSideImage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroOneSideImage":{"kind":"symbol","role":"symbol","title":"SBSDKUI2CreditCardIntroOneSideImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroonesideimage","abstract":[{"text":"The image for the introduction screen with one side of a credit card.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardIntroOneSideImage","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CreditCardIntroOneSideImage","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"creditCardIntroOneSideImage","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"creditCardIntroOneSideImage"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardIntroOneSideImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage","text":"SBSDKUI2CreditCardIntroOneSideImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"creditCardIntroOneSideImage","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2CreditCardScannerIntroImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerIntroImage\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerIntroImage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerIntroImage\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerIntroImage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerIntroImage\/navigatorTitle"},{"value":"creditCardIntroOneSideImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerIntroImage~1creditCardIntroOneSideImage()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"creditCardIntroOneSideImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerIntroImage~1creditCardIntroOneSideImage()\/fragments"},{"value":"SBSDKUI2CreditCardIntroOneSideImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroOneSideImage\/title"},{"value":[{"text":"SBSDKUI2CreditCardIntroOneSideImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroOneSideImage\/fragments"},{"value":[{"text":"SBSDKUI2CreditCardIntroOneSideImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroOneSideImage\/navigatorTitle"}]}]}