{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SoundType\/modernBeep","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"A modern beep sound.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"modernBeep"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"SBSDKUI2SoundTypeModernBeep","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2SoundType.modernBeep","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modernBeep","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2SoundType@SBSDKUI2SoundTypeModernBeep","roleHeading":"Case"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SoundType"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2soundtype\/modernbeep"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2soundtype\/modernbeep"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SoundType":{"type":"topic","abstract":[{"type":"text","text":"Determines the successful detection sound."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2soundtype","role":"symbol","title":"SBSDKUI2SoundType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SoundType"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SoundType"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SoundType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SoundType/modernBeep":{"type":"topic","abstract":[{"type":"text","text":"A modern beep sound."}],"title":"SBSDKUI2SoundType.modernBeep","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"modernBeep"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SoundTypeModernBeep"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SoundType\/modernBeep","url":"\/documentation\/scanbotsdk\/sbsdkui2soundtype\/modernbeep","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKUI2SoundTypeModernBeep","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2SoundTypeModernBeep"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKUI2SoundTypeModernBeep","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUI2SoundType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SoundType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2SoundType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SoundType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2SoundType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SoundType\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2SoundTypeModernBeep","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SoundType~1modernBeep\/title"},{"op":"replace","value":[{"text":"SBSDKUI2SoundTypeModernBeep","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SoundType~1modernBeep\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}