{"abstract":[{"type":"text","text":"The maximum number of results to be accumulated when live-recognizing machine-readable zones on sample buffers."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"maxNumberOfAccumulatedResults","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This sets the second part of the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer\/requiredNumberOfEqualAccumulatedResults","isActive":true,"type":"reference"},{"type":"text","text":" of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer\/maxNumberOfAccumulatedResults"},{"type":"text","text":" selector,"},{"text":" ","type":"text"},{"type":"text","text":"e.g. 2 of 4 results must be equal."},{"type":"text","text":" "},{"type":"text","text":"To make the selector less strict, select a higher value, e.g. 2 of 5 or even 2 of 6."},{"text":" ","type":"text"},{"type":"text","text":"Setting a value lower than the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer\/requiredNumberOfEqualAccumulatedResults","type":"reference","isActive":true},{"text":" will throw an exception.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Values less-than-or-equal to 0, will effectively turn off the result accumulation."}]},{"type":"paragraph","inlineContent":[{"text":"Defaults to 4.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizer\/maxnumberofaccumulatedresults"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizer\/maxnumberofaccumulatedresults"]}],"metadata":{"role":"symbol","symbolKind":"property","title":"maxNumberOfAccumulatedResults","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizer(py)maxNumberOfAccumulatedResults","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxNumberOfAccumulatedResults"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"kind":"identifier","text":"maxNumberOfAccumulatedResults"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer\/maxNumberOfAccumulatedResults","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizer/maxNumberOfAccumulatedResults":{"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizer\/maxnumberofaccumulatedresults","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxNumberOfAccumulatedResults","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"The maximum number of results to be accumulated when live-recognizing machine-readable zones on sample buffers."}],"kind":"symbol","title":"maxNumberOfAccumulatedResults","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxNumberOfAccumulatedResults"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer\/maxNumberOfAccumulatedResults"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizer":{"type":"topic","kind":"symbol","title":"SBSDKMachineReadableZoneRecognizer","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizer"}],"navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizer","kind":"identifier"}],"abstract":[{"text":"A class to recognize machine-readable zones in a ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"text":" or ","type":"text"},{"code":"CMSampleBuffer","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizer/requiredNumberOfEqualAccumulatedResults":{"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizer\/requirednumberofequalaccumulatedresults","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"The minimum number of equal results in the accumulator when live-recognizing machine-readable zones on sample buffers.","type":"text"}],"title":"requiredNumberOfEqualAccumulatedResults","type":"topic","navigatorTitle":[{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer\/requiredNumberOfEqualAccumulatedResults"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"maxNumberOfAccumulatedResults"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"maxNumberOfAccumulatedResults"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxNumberOfAccumulatedResults"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":"maxNumberOfAccumulatedResults","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer~1maxNumberOfAccumulatedResults\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer~1maxNumberOfAccumulatedResults\/fragments","value":[{"kind":"identifier","text":"maxNumberOfAccumulatedResults"}],"op":"replace"},{"value":"SBSDKMachineReadableZoneRecognizer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer\/title","op":"replace"},{"value":[{"text":"SBSDKMachineReadableZoneRecognizer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer~1requiredNumberOfEqualAccumulatedResults\/title","value":"requiredNumberOfEqualAccumulatedResults","op":"replace"},{"value":[{"kind":"identifier","text":"requiredNumberOfEqualAccumulatedResults"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer~1requiredNumberOfEqualAccumulatedResults\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}