{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer\/recognizePersonalIdentity(from:orientation:machineReadableZoneRect:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(recognizePersonalIdentityFromSampleBuffer:orientation:machineReadableZoneRect:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recognizePersonalIdentity"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sampleBuffer","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"kind":"text","text":", "},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"videoOrientation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation"},{"kind":"text","text":", "},{"text":"machineReadableZoneRect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> "},{"text":"SBSDKMachineReadableZoneRecognizerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The sample buffer containing the machine-readable zone.","type":"text"}]}],"name":"sampleBuffer"},{"name":"videoOrientation","content":[{"inlineContent":[{"type":"text","text":"The video frame orientation."}],"type":"paragraph"}]},{"name":"machineReadableZoneRect","content":[{"type":"paragraph","inlineContent":[{"text":"The rectangle in frame containing machine-readable zone. Pass an empty rectangle if no frame is used.","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The recognizer result or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}]}]}],"sections":[],"abstract":[{"type":"text","text":"Acquire all available information from sample buffer reference containing machine-readable zone."}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizer(im)recognizePersonalIdentityFromSampleBuffer:orientation:machineReadableZoneRect:","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"recognizePersonalIdentityFromSampleBuffer:orientation:machineReadableZoneRect:","kind":"identifier"}],"title":"recognizePersonalIdentity(from:orientation:machineReadableZoneRect:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"recognizePersonalIdentity","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"kind":"text","text":", "},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation"},{"kind":"text","text":", "},{"text":"machineReadableZoneRect","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResult","text":"SBSDKMachineReadableZoneRecognizerResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizer\/recognizepersonalidentity(from:orientation:machinereadablezonerect:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizer\/recognizepersonalidentity(from:orientation:machinereadablezonerect:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizer/recognizePersonalIdentity(from:orientation:machineReadableZoneRect:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recognizePersonalIdentity"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"text":"AVCaptureVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureVideoOrientation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"machineReadableZoneRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":") -> ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResult"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer\/recognizePersonalIdentity(from:orientation:machineReadableZoneRect:)","navigatorTitle":[{"text":"recognizePersonalIdentityFromSampleBuffer:orientation:machineReadableZoneRect:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Acquire all available information from sample buffer reference containing machine-readable zone.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizer\/recognizepersonalidentity(from:orientation:machinereadablezonerect:)","title":"recognizePersonalIdentity(from:orientation:machineReadableZoneRect:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResult":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}],"type":"topic","title":"SBSDKMachineReadableZoneRecognizerResult","abstract":[{"type":"text","text":"A class encapsulating a machine-readable-zone recognition result."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult","role":"symbol","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizer":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizer","kind":"identifier"}],"title":"SBSDKMachineReadableZoneRecognizer","abstract":[{"text":"A class to recognize machine-readable zones in a ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"CMSampleBuffer"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizer"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"recognizePersonalIdentityFromSampleBuffer:orientation:machineReadableZoneRect:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recognizePersonalIdentityFromSampleBuffer:orientation:machineReadableZoneRect:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResult","text":"SBSDKMachineReadableZoneRecognizerResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"recognizePersonalIdentityFromSampleBuffer:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"opaqueCMSampleBuffer","preciseIdentifier":"c:@S@opaqueCMSampleBuffer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sampleBuffer"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientation:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@AVCaptureVideoOrientation","kind":"typeIdentifier","text":"AVCaptureVideoOrientation"},{"text":") ","kind":"text"},{"text":"videoOrientation","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"machineReadableZoneRect:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"machineReadableZoneRect","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer~1recognizePersonalIdentity(from:orientation:machineReadableZoneRect:)\/title","op":"replace","value":"recognizePersonalIdentityFromSampleBuffer:orientation:machineReadableZoneRect:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer~1recognizePersonalIdentity(from:orientation:machineReadableZoneRect:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"recognizePersonalIdentityFromSampleBuffer:orientation:machineReadableZoneRect:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/title","value":"SBSDKMachineReadableZoneRecognizerResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer\/title","value":"SBSDKMachineReadableZoneRecognizer"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizer","kind":"identifier"}],"op":"replace"}]}]}