{"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCaptureInfo(py)imageMetadata","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageMetadata","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageMetadata","text":"SBSDKImageMetadata","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"imageMetadata","navigatorTitle":[{"text":"imageMetadata","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata","kind":"typeIdentifier","text":"SBSDKImageMetadata","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageMetadata"},{"text":" { get }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcaptureinfo\/imagemetadata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcaptureinfo\/imagemetadata"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCaptureInfo\/imageMetadata","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCaptureInfo"]]},"abstract":[{"type":"text","text":"The image metadata of the captured image."}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCaptureInfo":{"abstract":[{"text":"Helper class, that gathers the image, camera and detection metadata of a document scan.","type":"text"}],"kind":"symbol","title":"SBSDKCaptureInfo","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCaptureInfo","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcaptureinfo","role":"symbol","navigatorTitle":[{"text":"SBSDKCaptureInfo","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCaptureInfo"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadataProcessor":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadataprocessor","abstract":[{"type":"text","text":"Helper class to extract or inject image metadata, e.g. EXIF, TIFF, JFIF from  image data."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadataProcessor","role":"symbol","title":"SBSDKImageMetadataProcessor","kind":"symbol","navigatorTitle":[{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageMetadataProcessor"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCaptureInfo/imageMetadata":{"abstract":[{"text":"The image metadata of the captured image.","type":"text"}],"kind":"symbol","title":"imageMetadata","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageMetadata","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKImageMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageMetadata"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcaptureinfo\/imagemetadata","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageMetadata"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCaptureInfo\/imageMetadata"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageMetadata","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageMetadata"}],"title":"SBSDKImageMetadata","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Encapsulates image metadata, e.g. EXIF, TIFF, JFIF in a convenient way."},{"type":"text","text":" "},{"text":"Use ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadataProcessor","isActive":true,"type":"reference"},{"type":"text","text":" to extract metadata from and inject changed metadata into image data."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"imageMetadata","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"imageMetadata","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata","kind":"typeIdentifier","text":"SBSDKImageMetadata","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageMetadata"},{"kind":"text","text":" * "},{"text":"imageMetadata","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCaptureInfo\/title","value":"SBSDKCaptureInfo"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCaptureInfo\/fragments","op":"replace","value":[{"text":"SBSDKCaptureInfo","kind":"identifier"}]},{"op":"replace","value":"SBSDKImageMetadataProcessor","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadataProcessor\/title"},{"value":[{"kind":"identifier","text":"SBSDKImageMetadataProcessor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadataProcessor\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCaptureInfo~1imageMetadata\/title","value":"imageMetadata","op":"replace"},{"value":[{"kind":"identifier","text":"imageMetadata"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCaptureInfo~1imageMetadata\/fragments"},{"value":"SBSDKImageMetadata","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageMetadata"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}