{"abstract":[{"text":"Mod10 checksum algorithm","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mod10","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod10","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm@SBSDKUI2MSIPlesseyChecksumAlgorithmMod10","modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mod10"}],"navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}],"title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.mod10"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm\/mod10"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm\/mod10"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm","url":"\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm","type":"topic","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}],"abstract":[{"text":"Type of MSI plessey checksum algorithm used.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm/mod10":{"abstract":[{"type":"text","text":"Mod10 checksum algorithm"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm\/mod10","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mod10"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod10","type":"topic","navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}],"title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.mod10"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}]}]}},{"value":"SBSDKUI2MSIPlesseyChecksumAlgorithm","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}]},{"value":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod10\/title","value":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10"},{"value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod10\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}