{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus"]]},"sections":[],"abstract":[{"type":"text","text":"No document found or the document doesn’t look like the back of an EHIC."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedDetection"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultrecognitionstatus\/faileddetection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultrecognitionstatus\/faileddetection"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus.failedDetection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedDetection","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus@SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatusFailedDetection","role":"symbol","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatusFailedDetection","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus\/failedDetection","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus/failedDetection":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus\/failedDetection","type":"topic","role":"symbol","title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus.failedDetection","navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatusFailedDetection","kind":"identifier"}],"abstract":[{"text":"No document found or the document doesn’t look like the back of an EHIC.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultrecognitionstatus\/faileddetection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedDetection","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultrecognitionstatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus","kind":"identifier"}],"abstract":[{"text":"Card recognition status.","type":"text"}],"title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatusFailedDetection","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatusFailedDetection","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatusFailedDetection"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatusFailedDetection","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus~1failedDetection\/title"},{"value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatusFailedDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus~1failedDetection\/fragments"},{"value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus\/title"},{"value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus\/fragments"},{"value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultRecognitionStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}