{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdeviceinformation\/useddiskspaceinbytes()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdeviceinformation\/useddiskspaceinbytes()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"usedDiskSpaceInBytes"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"The amount of used disk space of the device in bytes. In case of error the return value is -1."}],"type":"paragraph"}]}],"sections":[],"abstract":[{"text":"The amount of used disk space of the device in bytes.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDeviceInformation\/usedDiskSpaceInBytes()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDeviceInformation"]]},"metadata":{"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"usedDiskSpaceInBytes"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"usedDiskSpaceInBytes"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","title":"usedDiskSpaceInBytes()","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDeviceInformation(cm)usedDiskSpaceInBytes"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDeviceInformation":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDeviceInformation"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDeviceInformation"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdeviceinformation","kind":"symbol","title":"SBSDKDeviceInformation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDeviceInformation","abstract":[{"type":"text","text":"Helper class that delivers information about the used iOS device."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDeviceInformation/usedDiskSpaceInBytes()":{"role":"symbol","abstract":[{"type":"text","text":"The amount of used disk space of the device in bytes."}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"usedDiskSpaceInBytes"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"kind":"symbol","title":"usedDiskSpaceInBytes()","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdeviceinformation\/useddiskspaceinbytes()","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDeviceInformation\/usedDiskSpaceInBytes()","navigatorTitle":[{"kind":"identifier","text":"usedDiskSpaceInBytes"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"usedDiskSpaceInBytes","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"usedDiskSpaceInBytes","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":") "},{"kind":"identifier","text":"usedDiskSpaceInBytes"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The amount of used disk space of the device in bytes. In case of error the return value is -1."}],"type":"paragraph"}],"kind":"content"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDeviceInformation\/title","value":"SBSDKDeviceInformation","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDeviceInformation\/fragments","value":[{"kind":"identifier","text":"SBSDKDeviceInformation"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDeviceInformation\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDeviceInformation"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDeviceInformation~1usedDiskSpaceInBytes()\/title","value":"usedDiskSpaceInBytes","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDeviceInformation~1usedDiskSpaceInBytes()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"usedDiskSpaceInBytes"}],"op":"replace"}]}]}