{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/copywithzone:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/copyWithZone:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"_NSZone","preciseIdentifier":"c:@S@_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSemanticsVerificationReport(im)copyWithZone:","roleHeading":"Instance Method","title":"copyWithZone:","symbolKind":"method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/copyWithZone:":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/copywithzone:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/copyWithZone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport":{"type":"topic","title":"SBSDKSemanticsVerificationReport","url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"abstract":[{"type":"text","text":"Report of the document value semantics verification."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport","navigatorTitle":[{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/title","value":"SBSDKSemanticsVerificationReport"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/fragments","value":[{"kind":"identifier","text":"SBSDKSemanticsVerificationReport"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKSemanticsVerificationReport"}]}]}]}