{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mrz","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentMRZ","text":"SBSDKGenericDocumentMRZ"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"mrz","kind":"identifier"}],"title":"mrz","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentDePassport(py)mrz","modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDePassport"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"MRZ."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mrz","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentMRZ","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentMRZ","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDePassport\/mrz","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentdepassport\/mrz"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentdepassport\/mrz"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ","abstract":[{"type":"text","text":"MRZ part of the document."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentMRZ","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz","navigatorTitle":[{"text":"SBSDKGenericDocumentMRZ","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SBSDKGenericDocumentMRZ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentDePassport/mrz":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDePassport\/mrz","type":"topic","title":"mrz","abstract":[{"type":"text","text":"MRZ."}],"navigatorTitle":[{"text":"mrz","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentdepassport\/mrz","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrz","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentMRZ","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentMRZ"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentDePassport":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDePassport","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentDePassport","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentdepassport","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentDePassport"}],"title":"SBSDKGenericDocumentDePassport","kind":"symbol","role":"symbol","abstract":[{"text":"German travel passport (Reisepass)","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mrz"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"mrz","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ","kind":"typeIdentifier","text":"SBSDKGenericDocumentMRZ","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentMRZ"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"mrz"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ\/title","op":"replace","value":"SBSDKGenericDocumentMRZ"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ\/fragments","value":[{"text":"SBSDKGenericDocumentMRZ","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDePassport~1mrz\/title","op":"replace","value":"mrz"},{"value":[{"kind":"identifier","text":"mrz"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDePassport~1mrz\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDePassport\/title","op":"replace","value":"SBSDKGenericDocumentDePassport"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentDePassport"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDePassport\/fragments"}]}]}