{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkgrayscalefilter\/init(borderwidthfraction:blackoutliersfraction:whiteoutliersfraction:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkgrayscalefilter\/init(borderwidthfraction:blackoutliersfraction:whiteoutliersfraction:)"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"borderWidthFraction","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"blackOutliersFraction"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"whiteOutliersFraction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter\/init(borderWidthFraction:blackOutliersFraction:whiteOutliersFraction:)"},"metadata":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"borderWidthFraction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"blackOutliersFraction"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"whiteOutliersFraction"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","kind":"identifier"}],"title":"init(borderWidthFraction:blackOutliersFraction:whiteOutliersFraction:)","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Initializer","symbolKind":"init","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKGrayscaleFilter(im)initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKGrayscaleFilter":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGrayscaleFilter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter","role":"symbol","navigatorTitle":[{"text":"SBSDKGrayscaleFilter","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Converts color images to grayscale, optionally applying autocontrast.","type":"text"}],"title":"SBSDKGrayscaleFilter","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkgrayscalefilter"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKGrayscaleFilter/init(borderWidthFraction:blackOutliersFraction:whiteOutliersFraction:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkgrayscalefilter\/init(borderwidthfraction:blackoutliersfraction:whiteoutliersfraction:)","title":"init(borderWidthFraction:blackOutliersFraction:whiteOutliersFraction:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"borderWidthFraction"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"blackOutliersFraction","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"whiteOutliersFraction"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter\/init(borderWidthFraction:blackOutliersFraction:whiteOutliersFraction:)","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithBorderWidthFraction:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"kind":"text","text":") "},{"kind":"internalParam","text":"borderWidthFraction"},{"kind":"text","text":" "},{"kind":"identifier","text":"blackOutliersFraction:"},{"kind":"text","text":"("},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":") ","kind":"text"},{"text":"blackOutliersFraction","kind":"internalParam"},{"kind":"text","text":" "},{"text":"whiteOutliersFraction:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"whiteOutliersFraction","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter\/title","value":"SBSDKGrayscaleFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter\/fragments","value":[{"text":"SBSDKGrayscaleFilter","kind":"identifier"}]},{"value":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter~1init(borderWidthFraction:blackOutliersFraction:whiteOutliersFraction:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter~1init(borderWidthFraction:blackOutliersFraction:whiteOutliersFraction:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}