{"sections":[],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewFinder","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PermanentViewFinderConfiguration","text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"viewFinder","kind":"identifier"}],"title":"viewFinder","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerScreenConfiguration(py)viewFinder","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/viewfinder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/viewfinder"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewFinder","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PermanentViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PermanentViewFinderConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/viewFinder","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration"]]},"abstract":[{"text":"Configuration of the view finder.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenConfiguration"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration","role":"symbol","kind":"symbol","abstract":[{"text":"Configuration of the screen for detecting credit card data.","type":"text"}],"title":"SBSDKUI2CreditCardScannerScreenConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/viewFinder":{"navigatorTitle":[{"kind":"identifier","text":"viewFinder"}],"title":"viewFinder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewFinder"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PermanentViewFinderConfiguration","kind":"typeIdentifier","text":"SBSDKUI2PermanentViewFinderConfiguration"}],"abstract":[{"text":"Configuration of the view finder.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/viewFinder","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/viewfinder","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PermanentViewFinderConfiguration":{"title":"SBSDKUI2PermanentViewFinderConfiguration","navigatorTitle":[{"text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Configuration of the scanning interface’s viewfinder, which is always visible to guide the user."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PermanentViewFinderConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2permanentviewfinderconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"viewFinder","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"viewFinder"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKUI2PermanentViewFinderConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PermanentViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PermanentViewFinderConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"viewFinder","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUI2CreditCardScannerScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2CreditCardScannerScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/navigatorTitle","op":"replace"},{"value":"viewFinder","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1viewFinder\/title","op":"replace"},{"value":[{"text":"viewFinder","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1viewFinder\/fragments","op":"replace"},{"value":"SBSDKUI2PermanentViewFinderConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PermanentViewFinderConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2PermanentViewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PermanentViewFinderConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PermanentViewFinderConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}