{"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingViewController(cm)createWith:error:completion:performDismiss:","roleHeading":"Type Method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"create(with:completion:performDismiss:)","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"createWith:error:completion:performDismiss:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CroppingConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"SBSDKUI2CroppingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"SBSDKUI2CroppingResult","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingResult","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> (), ","kind":"text"},{"text":"performDismiss","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"SBSDKUI2CroppingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingViewController","kind":"typeIdentifier"},{"text":", () -> ()) -> ())?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"SBSDKUI2CroppingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingViewController","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CroppingConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"SBSDKUI2CroppingViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingViewController"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"SBSDKUI2CroppingResult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingResult","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingResult"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> (), "},{"kind":"externalParam","text":"performDismiss"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"SBSDKUI2CroppingViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingViewController"},{"kind":"text","text":", "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" () -> ()) -> ())? = nil) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"SBSDKUI2CroppingViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingViewController"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The cropping screen configuration."}],"type":"paragraph"}],"name":"configuration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional block being executed when the screen is dismissed."}]}],"name":"completion"},{"content":[{"inlineContent":[{"type":"text","text":"An optional custom dismiss handler. If not provided, the dismissal will be handled automatically."}],"type":"paragraph"}],"name":"performDismiss"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The instance of "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController","type":"reference","isActive":true},{"type":"text","text":" or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the document or page was not found."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller\/create(with:completion:performdismiss:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller\/create(with:completion:performdismiss:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Creates a new instance of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController","type":"reference","isActive":true},{"text":" and returns it.","type":"text"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/create(with:completion:performDismiss:)"},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration of the standalone cropping screen.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingconfiguration","title":"SBSDKUI2CroppingConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingConfiguration","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingViewController/create(with:completion:performDismiss:)":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController","isActive":true},{"type":"text","text":" and returns it."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/create(with:completion:performDismiss:)","title":"create(with:completion:performDismiss:)","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller\/create(with:completion:performdismiss:)","navigatorTitle":[{"text":"createWith:error:completion:performDismiss:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CroppingConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingConfiguration"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingViewController","text":"SBSDKUI2CroppingViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingResult","text":"SBSDKUI2CroppingResult","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> (), ","kind":"text"},{"text":"performDismiss","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingViewController","text":"SBSDKUI2CroppingViewController","kind":"typeIdentifier"},{"text":", () -> ()) -> ())?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingViewController","text":"SBSDKUI2CroppingViewController","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingViewController":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"title":"SBSDKUI2CroppingViewController","abstract":[{"text":"A highly customizable view controller to edit the page polygon or the page orientation.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingResult":{"abstract":[{"text":"Configuration of the cropping result.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CroppingResult"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingResult"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingResult","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingresult","title":"SBSDKUI2CroppingResult","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"createWith:error:completion:performDismiss:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWith:error:completion:performDismiss:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingViewController","text":"SBSDKUI2CroppingViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController"},{"text":" *) ","kind":"text"},{"text":"createWith:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingConfiguration","text":"SBSDKUI2CroppingConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingViewController","text":"SBSDKUI2CroppingViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingResult","text":"SBSDKUI2CroppingResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingResult"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"performDismiss:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingViewController","text":"SBSDKUI2CroppingViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":"","kind":"internalParam"},{"text":")())) ","kind":"text"},{"text":"performDismiss","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"text":"The cropping screen configuration.","type":"text"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"An optional block being executed when the screen is dismissed.","type":"text"}]}]},{"name":"performDismiss","content":[{"inlineContent":[{"text":"An optional custom dismiss handler. If not provided, the dismissal will be handled automatically.","type":"text"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"The instance of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController"},{"type":"text","text":" or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the document or page was not found."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"SBSDKUI2CroppingConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CroppingConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingConfiguration\/navigatorTitle","op":"replace"},{"value":"createWith:error:completion:performDismiss:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController~1create(with:completion:performDismiss:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"createWith:error:completion:performDismiss:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController~1create(with:completion:performDismiss:)\/fragments","op":"replace"},{"value":"SBSDKUI2CroppingViewController","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CroppingViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2CroppingResult","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingResult\/title","op":"replace"},{"value":[{"text":"SBSDKUI2CroppingResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingResult\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CroppingResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingResult\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}