{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeExtensionsFilter"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeExtensionsFilter(im)init","navigatorTitle":[{"text":"init","kind":"identifier"}],"symbolKind":"method","title":"init","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodeextensionsfilter\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeExtensionsFilter\/init","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeFilter":{"title":"SBSDKUIBarcodeFilter","abstract":[{"text":"A class for a barcode filtering that can be used in barcode scanning RTU-UI components.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeFilter"}],"deprecated":true,"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodefilter","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeFilter","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeFilter"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeExtensionsFilter/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeExtensionsFilter\/init","type":"topic","kind":"symbol","role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeextensionsfilter\/init"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeExtensionsFilter":{"type":"topic","abstract":[{"type":"text","text":"Subclass of "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeFilter","type":"reference"},{"text":" that only accepts barcodes with extensions.","type":"text"}],"role":"symbol","deprecated":true,"navigatorTitle":[{"text":"SBSDKUIBarcodeExtensionsFilter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeExtensionsFilter","title":"SBSDKUIBarcodeExtensionsFilter","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeextensionsfilter","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeExtensionsFilter","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUIBarcodeFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeFilter\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeFilter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeFilter\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeFilter\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeExtensionsFilter\/title","value":"SBSDKUIBarcodeExtensionsFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeExtensionsFilter\/fragments","value":[{"text":"SBSDKUIBarcodeExtensionsFilter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeExtensionsFilter\/navigatorTitle","value":[{"text":"SBSDKUIBarcodeExtensionsFilter","kind":"identifier"}]}]}]}