{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(detectDocumentAndApplyPolygonIfOkay:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"applyPolygonIfOkay"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","text":"SBSDKDocumentDetectionResult"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"applyPolygonIfOkay","content":[{"inlineContent":[{"type":"text","text":"If set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":", the detected polygon will be applied to the receiver if its detection status is "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The document scanner result describing the location of the detected document in the image and the status of the detection, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", if no document was detected."}]}]}],"metadata":{"navigatorTitle":[{"text":"detectDocumentAndApplyPolygonIfOkay:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"applyPolygonIfOkay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"detectDocument(applyPolygonIfOkay:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage(im)detectDocumentAndApplyPolygonIfOkay:","symbolKind":"method"},"abstract":[{"text":"Detects the documents polygon on the original image of the receiver.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/detectdocument(applypolygonifokay:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/detectdocument(applypolygonifokay:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/detectDocument(applyPolygonIfOkay:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/detectDocument(applyPolygonIfOkay:)":{"title":"detectDocument(applyPolygonIfOkay:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/detectdocument(applypolygonifokay:)","navigatorTitle":[{"kind":"identifier","text":"detectDocumentAndApplyPolygonIfOkay:"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"applyPolygonIfOkay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/detectDocument(applyPolygonIfOkay:)","abstract":[{"text":"Detects the documents polygon on the original image of the receiver.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"role":"symbol","title":"SBSDKDocumentPage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","abstract":[{"text":"This class represents a scanned documents page.","type":"text"}],"navigatorTitle":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","kind":"symbol","abstract":[{"type":"text","text":"Result of the document contour detection."}],"role":"symbol","title":"SBSDKDocumentDetectionResult","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/ok":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/ok","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok","abstract":[{"type":"text","text":"An acceptable document was detected."}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ok","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDetectionStatusOk","kind":"identifier"}],"title":"SBSDKDocumentDetectionStatus.ok"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"detectDocumentAndApplyPolygonIfOkay:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"detectDocumentAndApplyPolygonIfOkay:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"detectDocumentAndApplyPolygonIfOkay:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"applyPolygonIfOkay","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"applyPolygonIfOkay","content":[{"inlineContent":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":", the detected polygon will be applied to the receiver if its detection status is "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The document scanner result describing the location of the detected document in the image and the status of the detection, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", if no document was detected.","type":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"detectDocumentAndApplyPolygonIfOkay:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1detectDocument(applyPolygonIfOkay:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detectDocumentAndApplyPolygonIfOkay:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1detectDocument(applyPolygonIfOkay:)\/fragments"},{"value":"SBSDKDocumentPage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title"},{"value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments"},{"value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/navigatorTitle"},{"value":"SBSDKDocumentDetectionResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/title"},{"value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/fragments"},{"value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/navigatorTitle"},{"value":"SBSDKDocumentDetectionStatusOk","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1ok\/title"},{"value":[{"text":"SBSDKDocumentDetectionStatusOk","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1ok\/fragments"}]}]}