{"sections":[],"metadata":{"fragments":[{"text":"hash","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVINBarcodeResult(py)hash","symbolKind":"property","title":"hash","roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult\/hash"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvinbarcoderesult\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeResult":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVINBarcodeResult"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult","type":"topic","abstract":[{"type":"text","text":"Result of the barcode scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdkvinbarcoderesult","kind":"symbol","title":"SBSDKVINBarcodeResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKVINBarcodeResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeResult/hash":{"fragments":[{"text":"hash","kind":"identifier"}],"title":"hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult\/hash","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvinbarcoderesult\/hash","role":"symbol","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"SBSDKVINBarcodeResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/title","op":"replace"},{"value":[{"text":"SBSDKVINBarcodeResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/fragments","op":"replace"},{"value":[{"text":"SBSDKVINBarcodeResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}