{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerTextConfiguration\/cancelButtonTitle"},"sections":[],"abstract":[{"text":"String being displayed on the cancel button.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerTextConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2TextPatternScannerViewController instead.","type":"text"}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannertextconfiguration\/cancelbuttontitle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannertextconfiguration\/cancelbuttontitle"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelButtonTitle","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextPatternScannerTextConfiguration(py)cancelButtonTitle","roleHeading":"Instance Property","title":"cancelButtonTitle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancelButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"cancelButtonTitle","kind":"identifier"}],"platforms":[]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerTextConfiguration":{"type":"topic","title":"SBSDKUITextPatternScannerTextConfiguration","abstract":[{"text":"Configuration for the textual contents of the RTU-UI text pattern scanner.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerTextConfiguration","deprecated":true,"navigatorTitle":[{"text":"SBSDKUITextPatternScannerTextConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUITextPatternScannerTextConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannertextconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerTextConfiguration/cancelButtonTitle":{"navigatorTitle":[{"kind":"identifier","text":"cancelButtonTitle"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerTextConfiguration\/cancelButtonTitle","abstract":[{"type":"text","text":"String being displayed on the cancel button."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannertextconfiguration\/cancelbuttontitle","title":"cancelButtonTitle","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancelButtonTitle","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"cancelButtonTitle","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"cancelButtonTitle","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"cancelButtonTitle","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerTextConfiguration\/title","value":"SBSDKUITextPatternScannerTextConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerTextConfiguration\/fragments","value":[{"text":"SBSDKUITextPatternScannerTextConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKUITextPatternScannerTextConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerTextConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerTextConfiguration~1cancelButtonTitle\/title","value":"cancelButtonTitle"},{"value":[{"text":"cancelButtonTitle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerTextConfiguration~1cancelButtonTitle\/fragments"}]}]}