{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalPlanSubheadingPrescriptionFieldType","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalplansubheadingprescriptionfield\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalplansubheadingprescriptionfield\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionField\/type","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The field type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalPlanSubheadingPrescriptionFieldType"}],"title":"type","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalPlanSubheadingPrescriptionField(py)type","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"type"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionField"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanSubheadingPrescriptionField/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalPlanSubheadingPrescriptionFieldType"}],"abstract":[{"type":"text","text":"The field type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionField\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalplansubheadingprescriptionfield\/type"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanSubheadingPrescriptionFieldType":{"role":"symbol","title":"SBSDKMedicalPlanSubheadingPrescriptionFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"}],"abstract":[{"type":"text","text":"The german medical plan document subheading prescription information description field type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalplansubheadingprescriptionfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanSubheadingPrescriptionField":{"role":"symbol","title":"SBSDKMedicalPlanSubheadingPrescriptionField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionField"}],"abstract":[{"type":"text","text":"The german medical plan document subheading prescription information description field."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionField"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalplansubheadingprescriptionfield"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.2"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalPlanSubheadingPrescriptionFieldType","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanSubheadingPrescriptionField~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanSubheadingPrescriptionField~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanSubheadingPrescriptionFieldType\/title","value":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanSubheadingPrescriptionFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanSubheadingPrescriptionField\/title","value":"SBSDKMedicalPlanSubheadingPrescriptionField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanSubheadingPrescriptionField\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}