{"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickScanningMode\/initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickScanningMode"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithScanningCompletedColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"scanningCompletedColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanningPartiallyColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"scanningPartiallyColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanningNotScannedColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"scanningNotScannedColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowPartialScan:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"allowPartialScan"},{"kind":"text","text":" "},{"kind":"identifier","text":"expectedBarcodes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKUI2ExpectedBarcode *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"expectedBarcodes"},{"kind":"text","text":" "},{"kind":"identifier","text":"countingRepeatDelay:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"countingRepeatDelay"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheet:"},{"kind":"text","text":"("},{"text":"SBSDKUI2Sheet","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Sheet"},{"text":" *) ","kind":"text"},{"text":"sheet","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sheetContent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2SheetContent","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2SheetContent","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sheetContent","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"manualCountEditDialog:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ManualCountEditDialog","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ManualCountEditDialog","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ManualCountEditDialog","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"manualCountEditDialog","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"arOverlay:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ArOverlayFindAndPickConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayFindAndPickConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"arOverlay","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"partialScannedAlertDialogEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"partialScannedAlertDialogEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"partialScannedAlertDialog:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"partialScannedAlertDialog","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"confirmationAlertDialogEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"confirmationAlertDialogEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"confirmationAlertDialog:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"confirmationAlertDialog","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:"}],"title":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickScanningMode(im)initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","kind":"identifier"}],"roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickscanningmode\/initwithscanningcompletedcolor:scanningpartiallycolor:scanningnotscannedcolor:allowpartialscan:expectedbarcodes:countingrepeatdelay:sheet:sheetcontent:manualcounteditdialog:aroverlay:partialscannedalertdialogenabled:partialscannedalertdialo-cgvt"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickScanningMode":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}],"title":"SBSDKUI2FindAndPickScanningMode","role":"symbol","abstract":[{"text":"Configuration of the Find and Pick barcode scanning mode.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickScanningMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickscanningmode","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Color":{"type":"topic","kind":"symbol","title":"SBSDKUI2Color","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2color"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ManualCountEditDialog":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ManualCountEditDialog"}],"abstract":[{"text":"Configuration of the dialog to manually edit the barcode count.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ManualCountEditDialog","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2manualcounteditdialog","title":"SBSDKUI2ManualCountEditDialog","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ManualCountEditDialog"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickScanningMode/initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:":{"title":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickscanningmode\/initwithscanningcompletedcolor:scanningpartiallycolor:scanningnotscannedcolor:allowpartialscan:expectedbarcodes:countingrepeatdelay:sheet:sheetcontent:manualcounteditdialog:aroverlay:partialscannedalertdialogenabled:partialscannedalertdialo-cgvt","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickScanningMode\/initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Sheet":{"title":"SBSDKUI2Sheet","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheet","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Sheet"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Sheet"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet","type":"topic","kind":"symbol","abstract":[{"text":"Configuration of the preview mode for scanning multiple barcodes.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayFindAndPickConfiguration":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlayfindandpickconfiguration","kind":"symbol","title":"SBSDKUI2ArOverlayFindAndPickConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}],"abstract":[{"text":"Configuration of the AR overlay.","type":"text"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SheetContent":{"abstract":[{"text":"Configuration of the list containing the barcodes that have already been scanned.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2SheetContent","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheetcontent","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent","type":"topic","navigatorTitle":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ScanbotAlertDialog":{"abstract":[{"type":"text","text":"Configuration of the standard alert dialog."}],"navigatorTitle":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","title":"SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ScanbotAlertDialog","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2scanbotalertdialog","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2FindAndPickScanningMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickScanningMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickScanningMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickScanningMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickScanningMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/title","op":"replace","value":"SBSDKUI2Color"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/fragments","op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Color"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ManualCountEditDialog\/title","op":"replace","value":"SBSDKUI2ManualCountEditDialog"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ManualCountEditDialog\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ManualCountEditDialog"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ManualCountEditDialog\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ManualCountEditDialog"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/title","op":"replace","value":"SBSDKUI2Sheet"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/fragments","op":"replace","value":[{"text":"SBSDKUI2Sheet","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Sheet"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/title","op":"replace","value":"SBSDKUI2ArOverlayFindAndPickConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/title","op":"replace","value":"SBSDKUI2SheetContent"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/fragments","op":"replace","value":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ScanbotAlertDialog\/title","op":"replace","value":"SBSDKUI2ScanbotAlertDialog"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ScanbotAlertDialog\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ScanbotAlertDialog\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}]}]}]}