{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller\/sbsdkimageeditingviewcontrollerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller\/sbsdkimageeditingviewcontrollerdelegate-implementations"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController"]]},"metadata":{"title":"SBSDKImageEditingViewControllerDelegate Implementations","roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/SBSDKImageEditingViewControllerDelegate-Implementations"},"topicSections":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/imageEditingViewController(_:didDetectPolygon:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/imageEditingViewControllerDidChangePolygon(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/imageEditingViewControllerDidFail(_:with:)"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingViewController/imageEditingViewControllerDidFail(_:with:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerDidFail"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerDidFail:with:"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/imageEditingViewControllerDidFail(_:with:)","title":"imageEditingViewControllerDidFail(_:with:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller\/imageeditingviewcontrollerdidfail(_:with:)","abstract":[{"type":"text","text":"Informs the delegate that the image editing view controller failed with an error."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingViewController":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController","title":"SBSDKUI2CroppingViewController","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A highly customizable view controller to edit the page polygon or the page orientation."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingViewController/imageEditingViewControllerDidChangePolygon(_:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller\/imageeditingviewcontrollerdidchangepolygon(_:)","kind":"symbol","title":"imageEditingViewControllerDidChangePolygon(_:)","abstract":[{"type":"text","text":"Informs the delegate that the image editing view controllers polygon was changed by user interaction."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/imageEditingViewControllerDidChangePolygon(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingViewController/imageEditingViewController(_:didDetectPolygon:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller\/imageeditingviewcontroller(_:diddetectpolygon:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/imageEditingViewController(_:didDetectPolygon:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDetectPolygon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"imageEditingViewController:didDetectPolygon:"}],"kind":"symbol","abstract":[{"type":"text","text":"Informs the delegate that the image editing view controller detected a polygon."}],"title":"imageEditingViewController(_:didDetectPolygon:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/imageEditingViewController(_:didDetectPolygon:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/imageEditingViewControllerDidChangePolygon(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/imageEditingViewControllerDidFail(_:with:)"],"anchor":"Instance-Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"imageEditingViewControllerDidFail:with:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController~1imageEditingViewControllerDidFail(_:with:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"imageEditingViewControllerDidFail:with:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController~1imageEditingViewControllerDidFail(_:with:)\/fragments","op":"replace"},{"value":"SBSDKUI2CroppingViewController","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CroppingViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/navigatorTitle","op":"replace"},{"value":"imageEditingViewControllerDidChangePolygon:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController~1imageEditingViewControllerDidChangePolygon(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController~1imageEditingViewControllerDidChangePolygon(_:)\/fragments","op":"replace"},{"value":"imageEditingViewController:didDetectPolygon:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController~1imageEditingViewController(_:didDetectPolygon:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController~1imageEditingViewController(_:didDetectPolygon:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageEditingViewController:didDetectPolygon:","kind":"identifier"}]}]}]}