{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescanneraccessibility\/dialog"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Class","title":"SBSDKUI2BarcodeScannerAccessibility.dialog","symbolKind":"class","externalID":"s:10ScanbotSDK35SBSDKUI2BarcodeScannerAccessibilityC6dialogC","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialog"}],"navigatorTitle":[{"kind":"identifier","text":"dialog"}],"modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialog"}]}],"kind":"declarations"}],"kind":"symbol","topicSections":[{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerAccessibility\/dialog\/left","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerAccessibility\/dialog\/right"],"generated":true}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerAccessibility\/dialog","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerAccessibility"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerAccessibility/dialog/left":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerAccessibility\/dialog\/left","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescanneraccessibility\/dialog\/left","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","title":"left","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerAccessibility/dialog":{"role":"symbol","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescanneraccessibility\/dialog","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialog"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerAccessibility\/dialog","navigatorTitle":[{"kind":"identifier","text":"dialog"}],"title":"SBSDKUI2BarcodeScannerAccessibility.dialog"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerAccessibility/dialog/right":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescanneraccessibility\/dialog\/right","title":"right","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerAccessibility\/dialog\/right"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerAccessibility":{"title":"SBSDKUI2BarcodeScannerAccessibility","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeScannerAccessibility"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerAccessibility"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Accessibility identifiers to be used in UI tests for the barcode scanner RTU-UI V2.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescanneraccessibility","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerAccessibility","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerAccessibility\/title","value":"SBSDKUI2BarcodeScannerAccessibility"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerAccessibility\/fragments","value":[{"text":"SBSDKUI2BarcodeScannerAccessibility","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerAccessibility\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerAccessibility"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}