{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithResultAccumulationConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKResultAccumulationConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration","text":"SBSDKResultAccumulationConfiguration"},{"kind":"text","text":" *) "},{"text":"resultAccumulationConfig","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fieldExcludeList:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"fieldExcludeList","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configurations:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<SBSDKDocumentDataExtractorConfigurationElement *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"configurations","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"returnCrops:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"returnCrops"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentTrustMode:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentTrustMode","kind":"typeIdentifier","text":"SBSDKDocumentTrustMode"},{"text":") ","kind":"text"},{"text":"documentTrustMode","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfiguration\/initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:documentTrustMode:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfiguration\/initwithresultaccumulationconfig:fieldexcludelist:configurations:returncrops:documenttrustmode:"]}],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:documentTrustMode:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfiguration(im)initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:documentTrustMode:","navigatorTitle":[{"kind":"identifier","text":"initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:documentTrustMode:"}],"title":"initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:documentTrustMode:"},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfiguration":{"title":"SBSDKDocumentDataExtractorConfiguration","abstract":[{"type":"text","text":"Configuration for the document data extractor."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfiguration"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResultAccumulationConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkresultaccumulationconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}],"role":"symbol","title":"SBSDKResultAccumulationConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration","abstract":[{"type":"text","text":"Configuration for how to accumulate results."}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentTrustMode":{"abstract":[{"type":"text","text":"Level of trust in the authenticity of the extracted document."}],"title":"SBSDKDocumentTrustMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentTrustMode","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentTrustMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumenttrustmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfiguration/initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:documentTrustMode:":{"fragments":[{"kind":"text","text":"- "},{"text":"initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:documentTrustMode:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfiguration\/initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:documentTrustMode:","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:documentTrustMode:"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfiguration\/initwithresultaccumulationconfig:fieldexcludelist:configurations:returncrops:documenttrustmode:","title":"initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:documentTrustMode:","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfiguration\/title","value":"SBSDKDocumentDataExtractorConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfiguration\/fragments","value":[{"text":"SBSDKDocumentDataExtractorConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentDataExtractorConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/title","value":"SBSDKResultAccumulationConfiguration"},{"value":[{"text":"SBSDKResultAccumulationConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/navigatorTitle","value":[{"text":"SBSDKResultAccumulationConfiguration","kind":"identifier"}]},{"value":"SBSDKDocumentTrustMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentTrustMode\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentTrustMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentTrustMode\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentTrustMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentTrustMode\/navigatorTitle","op":"replace"}]}]}