{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration\/copywithzone:"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/copyWithZone:","interfaceLanguage":"occ"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration"]]},"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"copyWithZone:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQualityAnalyzerConfiguration(im)copyWithZone:","symbolKind":"method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzerConfiguration/copyWithZone:":{"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration\/copywithzone:","role":"symbol","title":"copyWithZone:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/copyWithZone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzerConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration","type":"topic","navigatorTitle":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"title":"SBSDKDocumentQualityAnalyzerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration","abstract":[{"type":"text","text":"Document Quality Analyzer configuration."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKDocumentQualityAnalyzerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/navigatorTitle","op":"replace"}]}]}