{"metadata":{"navigatorTitle":[{"text":"initWithBarcode:count:","kind":"identifier"}],"roleHeading":"Instance Method","title":"initWithBarcode:count:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithBarcode:count:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerUIItem(im)initWithBarcode:count:","symbolKind":"method","modules":[{"name":"ScanbotSDK"}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBarcode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem","text":"SBSDKBarcodeItem"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcode"},{"text":" ","kind":"text"},{"text":"count:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"count"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerUIItem\/initWithBarcode:count:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerUIItem"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescanneruiitem\/initwithbarcode:count:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeItem":{"title":"SBSDKBarcodeItem","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeitem","type":"topic","abstract":[{"text":"A single barcode found in the input image. Barcodes with the same content but different locations in the image are","type":"text"},{"type":"text","text":" "},{"type":"text","text":"considered separate barcodes."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeItem","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem","navigatorTitle":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerUIItem/initWithBarcode:count:":{"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBarcode:count:"}],"role":"symbol","title":"initWithBarcode:count:","kind":"symbol","type":"topic","navigatorTitle":[{"text":"initWithBarcode:count:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescanneruiitem\/initwithbarcode:count:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerUIItem\/initWithBarcode:count:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerUIItem":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescanneruiitem","title":"SBSDKUI2BarcodeScannerUIItem","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerUIItem","kind":"symbol","abstract":[{"text":"Data about the scanned barcode.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeScannerUIItem","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerUIItem"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/title","value":"SBSDKBarcodeItem","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeItem"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeItem"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/navigatorTitle"},{"value":"SBSDKUI2BarcodeScannerUIItem","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerUIItem\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerUIItem\/fragments","value":[{"text":"SBSDKUI2BarcodeScannerUIItem","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerUIItem\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerUIItem"}]}]}]}