{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration\/autoSnappingButtonAccessibilityLabel","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscanneraccessibilityconfiguration\/autosnappingbuttonaccessibilitylabel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscanneraccessibilityconfiguration\/autosnappingbuttonaccessibilitylabel"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSnappingButtonAccessibilityLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to “Auto scan”."}]}]}],"metadata":{"title":"autoSnappingButtonAccessibilityLabel","navigatorTitle":[{"text":"autoSnappingButtonAccessibilityLabel","kind":"identifier"}],"role":"symbol","platforms":[],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerAccessibilityConfiguration(py)autoSnappingButtonAccessibilityLabel","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoSnappingButtonAccessibilityLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"text":"Text, that is used as an accessibility label for the auto-snapping button.","type":"text"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerAccessibilityConfiguration/autoSnappingButtonAccessibilityLabel":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSnappingButtonAccessibilityLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneraccessibilityconfiguration\/autosnappingbuttonaccessibilitylabel","abstract":[{"text":"Text, that is used as an accessibility label for the auto-snapping button.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"autoSnappingButtonAccessibilityLabel"}],"deprecated":true,"title":"autoSnappingButtonAccessibilityLabel","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration\/autoSnappingButtonAccessibilityLabel"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerAccessibilityConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration","deprecated":true,"title":"SBSDKUIDocumentScannerAccessibilityConfiguration","navigatorTitle":[{"text":"SBSDKUIDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneraccessibilityconfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"autoSnappingButtonAccessibilityLabel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"autoSnappingButtonAccessibilityLabel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"autoSnappingButtonAccessibilityLabel","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration~1autoSnappingButtonAccessibilityLabel\/title","value":"autoSnappingButtonAccessibilityLabel"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration~1autoSnappingButtonAccessibilityLabel\/fragments","value":[{"kind":"identifier","text":"autoSnappingButtonAccessibilityLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration\/title","value":"SBSDKUIDocumentScannerAccessibilityConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerAccessibilityConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerAccessibilityConfiguration"}]}]}]}