{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientationMask","text":"UIInterfaceOrientationMask"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supportedInterfaceOrientations"},{"text":";","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/supportedinterfaceorientations"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/supportedInterfaceOrientations"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"supportedInterfaceOrientations","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerViewController(py)supportedInterfaceOrientations","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"supportedInterfaceOrientations"}],"title":"supportedInterfaceOrientations"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController/supportedInterfaceOrientations":{"title":"supportedInterfaceOrientations","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/supportedinterfaceorientations","fragments":[{"text":"supportedInterfaceOrientations","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/supportedInterfaceOrientations","role":"symbol","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController":{"title":"SBSDKUICheckScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","abstract":[{"type":"text","text":"A Ready-To-Use viewController to scan checks using the camera."}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/title","value":"SBSDKUICheckScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKUICheckScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}