{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/multipleObjectsDetection","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature"]]},"kind":"symbol","abstract":[{"type":"text","text":"Multiple objects detection is enabled in the license. Currently unused."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfeature\/multipleobjectsdetection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfeature\/multipleobjectsdetection"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multipleObjectsDetection"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Case","title":"SBSDKFeature.multipleObjectsDetection","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multipleObjectsDetection"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKFeature@SBSDKFeatureMultipleObjectsDetection","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureMultipleObjectsDetection"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/multipleObjectsDetection":{"title":"SBSDKFeature.multipleObjectsDetection","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"multipleObjectsDetection","kind":"identifier"}],"abstract":[{"type":"text","text":"Multiple objects detection is enabled in the license. Currently unused."}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/multipleobjectsdetection","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/multipleObjectsDetection","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKFeatureMultipleObjectsDetection","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature":{"kind":"symbol","abstract":[{"text":"The features that are activated in the ScanbotSDK license.","type":"text"}],"navigatorTitle":[{"text":"SBSDKFeature","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature","title":"SBSDKFeature","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFeature","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKFeatureMultipleObjectsDetection"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureMultipleObjectsDetection"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKFeatureMultipleObjectsDetection"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1multipleObjectsDetection\/title","value":"SBSDKFeatureMultipleObjectsDetection"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1multipleObjectsDetection\/fragments","value":[{"text":"SBSDKFeatureMultipleObjectsDetection","kind":"identifier"}]},{"value":"SBSDKFeature","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/fragments","value":[{"text":"SBSDKFeature","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/navigatorTitle","value":[{"text":"SBSDKFeature","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}