{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType"]]},"metadata":{"roleHeading":"Case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentPageFileType@SBSDKDocumentPageFileTypeDocumentUnfiltered","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentUnfiltered","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentPageFileTypeDocumentUnfiltered","kind":"identifier"}],"title":"SBSDKDocumentPageFileType.documentUnfiltered","symbolKind":"case"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentUnfiltered","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefiletype\/documentunfiltered"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefiletype\/documentunfiltered"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/documentUnfiltered"},"abstract":[{"text":"The image only contains the cropped and perspective-corrected document portion of the original camera image.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileType/documentUnfiltered":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentUnfiltered"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefiletype\/documentunfiltered","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageFileTypeDocumentUnfiltered"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/documentUnfiltered","role":"symbol","title":"SBSDKDocumentPageFileType.documentUnfiltered","abstract":[{"type":"text","text":"The image only contains the cropped and perspective-corrected document portion of the original camera image."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileType":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefiletype","abstract":[{"type":"text","text":"Enumeration of image type classifiers."}],"title":"SBSDKDocumentPageFileType","navigatorTitle":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKDocumentPageFileTypeDocumentUnfiltered","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKDocumentPageFileTypeDocumentUnfiltered","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKDocumentPageFileTypeDocumentUnfiltered","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType~1documentUnfiltered\/title","value":"SBSDKDocumentPageFileTypeDocumentUnfiltered","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType~1documentUnfiltered\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPageFileTypeDocumentUnfiltered"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType\/title","value":"SBSDKDocumentPageFileType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType\/fragments","value":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentPageFileType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}