{"metadata":{"title":"SBSDKCheckRecognizerState.capturing","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"capturing","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKCheckRecognizerState@SBSDKCheckRecognizerStateCapturing","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKCheckRecognizerStateCapturing","kind":"identifier"}],"symbolKind":"case","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/capturing"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate\/capturing"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate\/capturing"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The check scanner is capturing a high-res photo of a check."}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"capturing","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerState/capturing":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/capturing","role":"symbol","title":"SBSDKCheckRecognizerState.capturing","navigatorTitle":[{"text":"SBSDKCheckRecognizerStateCapturing","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate\/capturing","abstract":[{"type":"text","text":"The check scanner is capturing a high-res photo of a check."}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"capturing","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerState":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckRecognizerState"}],"title":"SBSDKCheckRecognizerState","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState","role":"symbol","abstract":[{"type":"text","text":"The live recognition state of the check scanner."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerState"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKCheckRecognizerStateCapturing"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckRecognizerStateCapturing"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"SBSDKCheckRecognizerStateCapturing","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState~1capturing\/title","op":"replace","value":"SBSDKCheckRecognizerStateCapturing"},{"value":[{"kind":"identifier","text":"SBSDKCheckRecognizerStateCapturing"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState~1capturing\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState\/title","op":"replace","value":"SBSDKCheckRecognizerState"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState\/fragments","op":"replace","value":[{"text":"SBSDKCheckRecognizerState","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}