{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerStateRecognizing"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","title":"SBSDKCheckRecognizerState.recognizing","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recognizing"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKCheckRecognizerState@SBSDKCheckRecognizerStateRecognizing"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate\/recognizing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate\/recognizing"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/recognizing"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState"]]},"abstract":[{"text":"The check scanner is recognizing a check.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognizing","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerState/recognizing":{"navigatorTitle":[{"text":"SBSDKCheckRecognizerStateRecognizing","kind":"identifier"}],"title":"SBSDKCheckRecognizerState.recognizing","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/recognizing","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The check scanner is recognizing a check."}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate\/recognizing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"recognizing","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerState":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerState"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState","abstract":[{"text":"The live recognition state of the check scanner.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckRecognizerState"}],"title":"SBSDKCheckRecognizerState"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKCheckRecognizerStateRecognizing"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKCheckRecognizerStateRecognizing","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKCheckRecognizerStateRecognizing"}]}],"kind":"declarations"}},{"value":"SBSDKCheckRecognizerStateRecognizing","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState~1recognizing\/title"},{"value":[{"kind":"identifier","text":"SBSDKCheckRecognizerStateRecognizing"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState~1recognizing\/fragments"},{"value":"SBSDKCheckRecognizerState","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState\/title"},{"value":[{"kind":"identifier","text":"SBSDKCheckRecognizerState"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState\/fragments"}]}]}