{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommononedconfiguration\/onedconfirmationmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommononedconfiguration\/onedconfirmationmode"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonOneDConfiguration"]]},"metadata":{"navigatorTitle":[{"text":"oneDConfirmationMode","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCommonOneDConfiguration(py)oneDConfirmationMode","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"oneDConfirmationMode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"oneDConfirmationMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKOneDConfirmationMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOneDConfirmationMode"}]},"abstract":[{"text":"Allows to select the balance between result accuracy (precision) and missed barcodes (recall) for linear barcodes.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonOneDConfiguration\/oneDConfirmationMode","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"oneDConfirmationMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKOneDConfirmationMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOneDConfirmationMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOneDConfirmationMode"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is THOROUGH","type":"text"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonOneDConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonOneDConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonOneDConfiguration"}],"title":"SBSDKBarcodeFormatCommonOneDConfiguration","type":"topic","abstract":[{"type":"text","text":"Convenience configuration for enabling the scanning of multiple linear (1D) barcode formats with a common configuration."},{"type":"text","text":" "},{"type":"text","text":"Add to scanner configuration to enable and configure the scanning of multiple linear (1D) barcode formats."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommononedconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatCommonOneDConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonOneDConfiguration/oneDConfirmationMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonOneDConfiguration\/oneDConfirmationMode","abstract":[{"type":"text","text":"Allows to select the balance between result accuracy (precision) and missed barcodes (recall) for linear barcodes."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"oneDConfirmationMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOneDConfirmationMode","kind":"typeIdentifier","text":"SBSDKOneDConfirmationMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommononedconfiguration\/onedconfirmationmode","title":"oneDConfirmationMode","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"oneDConfirmationMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOneDConfirmationMode":{"url":"\/documentation\/scanbotsdk\/sbsdkonedconfirmationmode","abstract":[{"text":"Allows to select the balance between result accuracy (precision) and missed barcodes (recall) for linear barcodes.","type":"text"},{"text":" ","type":"text"},{"text":"Some barcode types are naturally prone to false positives (e.g. MSI Plessey).","type":"text"},{"text":" ","type":"text"},{"text":"For those barcode types false positives can be drastically reduced (precision can be increased) by requiring that multiple scan-lines in the input scan to the same result.","type":"text"},{"text":" ","type":"text"},{"text":"However, this stronger condition can lead to missed barcodes (lower recall).","type":"text"},{"text":" ","type":"text"},{"text":"Confirmation is avoided for barcode types, which are by design resistant to false positives, (e.g. Code128) to maximize recall.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"type":"topic","title":"SBSDKOneDConfirmationMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOneDConfirmationMode","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"oneDConfirmationMode","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"oneDConfirmationMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKOneDConfirmationMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOneDConfirmationMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOneDConfirmationMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"oneDConfirmationMode"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonOneDConfiguration\/title","value":"SBSDKBarcodeFormatCommonOneDConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonOneDConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatCommonOneDConfiguration","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatCommonOneDConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonOneDConfiguration\/navigatorTitle"},{"op":"replace","value":"oneDConfirmationMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonOneDConfiguration~1oneDConfirmationMode\/title"},{"op":"replace","value":[{"text":"oneDConfirmationMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonOneDConfiguration~1oneDConfirmationMode\/fragments"},{"op":"replace","value":"SBSDKOneDConfirmationMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOneDConfirmationMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOneDConfirmationMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOneDConfirmationMode\/fragments"},{"op":"replace","value":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOneDConfirmationMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}