{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFlipMode"]]},"abstract":[{"text":"Flip the image horizontally.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoflipmode\/horizontal"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoflipmode\/horizontal"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFlipMode\/horizontal","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontal"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoFlipMode@SBSDKVideoFlipModeHorizontal","roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFlipModeHorizontal"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"horizontal","kind":"identifier"}],"title":"SBSDKVideoFlipMode.horizontal"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoFlipMode/horizontal":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"horizontal","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKVideoFlipModeHorizontal","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFlipMode\/horizontal","abstract":[{"type":"text","text":"Flip the image horizontally."}],"title":"SBSDKVideoFlipMode.horizontal","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoflipmode\/horizontal"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoFlipMode":{"abstract":[{"type":"text","text":"An enum describing how images can be flipped."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFlipMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoFlipMode"}],"navigatorTitle":[{"text":"SBSDKVideoFlipMode","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"SBSDKVideoFlipMode","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoflipmode"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKVideoFlipModeHorizontal"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKVideoFlipModeHorizontal","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKVideoFlipModeHorizontal"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFlipMode~1horizontal\/title","value":"SBSDKVideoFlipModeHorizontal"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFlipMode~1horizontal\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoFlipModeHorizontal"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFlipMode\/title","value":"SBSDKVideoFlipMode","op":"replace"},{"value":[{"text":"SBSDKVideoFlipMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFlipMode\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}