{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id<CAAction>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)CAAction"},{"text":") ","kind":"text"},{"text":"actionForKey:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonLayer"]]},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPolygonLayer(im)actionForKey:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"actionForKey:","kind":"identifier"}],"navigatorTitle":[{"text":"actionForKey:","kind":"identifier"}],"role":"symbol","title":"actionForKey:","roleHeading":"Instance Method","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonlayer\/actionforkey:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonLayer\/actionForKey:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.3"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygonLayer/actionForKey:":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"actionForKey:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonlayer\/actionforkey:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonLayer\/actionForKey:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"actionForKey:"}],"role":"symbol","type":"topic","title":"actionForKey:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygonLayer":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonLayer","title":"SBSDKPolygonLayer","abstract":[{"text":"A ","type":"text"},{"code":"CAShapeLayer","type":"codeVoice"},{"text":" subclass that is used to draw bezier paths with fluid animation.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPolygonLayer"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygonLayer"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonlayer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKPolygonLayer","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonLayer\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPolygonLayer"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonLayer\/fragments","op":"replace"},{"value":[{"text":"SBSDKPolygonLayer","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonLayer\/navigatorTitle","op":"replace"}]}]}