{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/isEqual:","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorAutoFocusConfiguration(im)isEqual:","role":"symbol","title":"isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorAutoFocusConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorAutoFocusConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDataExtractorAutoFocusConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Auto-focus configuration.","type":"text"},{"text":" ","type":"text"},{"text":"The recognizer will ignore frames that are not focused. This option is enabled by default.","type":"text"},{"text":" ","type":"text"},{"text":"This configuration has no effect in SINGLE_SHOT mode.","type":"text"}],"title":"SBSDKDocumentDataExtractorAutoFocusConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorAutoFocusConfiguration/isEqual:":{"title":"isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration\/isequal:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/isEqual:","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration\/title","value":"SBSDKDocumentDataExtractorAutoFocusConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorAutoFocusConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorAutoFocusConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}