{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/sensitivityThreshold","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration\/sensitivitythreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration\/sensitivitythreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorAutoFocusConfiguration(py)sensitivityThreshold","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sensitivityThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"sensitivityThreshold"}],"title":"sensitivityThreshold","symbolKind":"property","role":"symbol","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sensitivityThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Default is 0.02"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","abstract":[{"type":"text","text":"Sensitivity threshold for detecting that autofocus is in progress."},{"type":"text","text":" "},{"type":"text","text":"The value should be in the range [0.0, 1.0]."},{"type":"text","text":" "},{"type":"text","text":"The lower the value, the more frames might be discarded as not focused."},{"type":"text","text":" "},{"type":"text","text":"The higher the value, the earlier the focus might be considered as focused."},{"type":"text","text":" "},{"type":"text","text":"If set to 0.0, the feature is disabled."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorAutoFocusConfiguration/sensitivityThreshold":{"navigatorTitle":[{"kind":"identifier","text":"sensitivityThreshold"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/sensitivityThreshold","role":"symbol","title":"sensitivityThreshold","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration\/sensitivitythreshold","abstract":[{"type":"text","text":"Sensitivity threshold for detecting that autofocus is in progress."},{"type":"text","text":" "},{"type":"text","text":"The value should be in the range [0.0, 1.0]."},{"type":"text","text":" "},{"type":"text","text":"The lower the value, the more frames might be discarded as not focused."},{"type":"text","text":" "},{"type":"text","text":"The higher the value, the earlier the focus might be considered as focused."},{"type":"text","text":" "},{"type":"text","text":"If set to 0.0, the feature is disabled."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sensitivityThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorAutoFocusConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorAutoFocusConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDataExtractorAutoFocusConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Auto-focus configuration.","type":"text"},{"text":" ","type":"text"},{"text":"The recognizer will ignore frames that are not focused. This option is enabled by default.","type":"text"},{"text":" ","type":"text"},{"text":"This configuration has no effect in SINGLE_SHOT mode.","type":"text"}],"title":"SBSDKDocumentDataExtractorAutoFocusConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"sensitivityThreshold"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sensitivityThreshold"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"sensitivityThreshold"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration~1sensitivityThreshold\/title","value":"sensitivityThreshold"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration~1sensitivityThreshold\/fragments","value":[{"kind":"identifier","text":"sensitivityThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration\/title","value":"SBSDKDocumentDataExtractorAutoFocusConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorAutoFocusConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorAutoFocusConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}