{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode"]]},"kind":"symbol","abstract":[{"text":"Moderate confirmation is performed. Compared to minimal confirmation, it provides an additional decrease in false positives, at the cost of a slight decrease in recall.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/moderate"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode\/moderate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode\/moderate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moderate","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKOneDConfirmationMode@SBSDKOneDConfirmationModeModerate","title":"SBSDKOneDConfirmationMode.moderate","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"SBSDKOneDConfirmationModeModerate","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moderate","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOneDConfirmationMode/moderate":{"role":"symbol","title":"SBSDKOneDConfirmationMode.moderate","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/moderate","navigatorTitle":[{"text":"SBSDKOneDConfirmationModeModerate","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moderate","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Moderate confirmation is performed. Compared to minimal confirmation, it provides an additional decrease in false positives, at the cost of a slight decrease in recall."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode\/moderate","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOneDConfirmationMode":{"abstract":[{"type":"text","text":"Allows to select the balance between result accuracy (precision) and missed barcodes (recall) for linear barcodes."},{"type":"text","text":" "},{"type":"text","text":"Some barcode types are naturally prone to false positives (e.g. MSI Plessey)."},{"type":"text","text":" "},{"type":"text","text":"For those barcode types false positives can be drastically reduced (precision can be increased) by requiring that multiple scan-lines in the input scan to the same result."},{"type":"text","text":" "},{"type":"text","text":"However, this stronger condition can lead to missed barcodes (lower recall)."},{"type":"text","text":" "},{"type":"text","text":"Confirmation is avoided for barcode types, which are by design resistant to false positives, (e.g. Code128) to maximize recall."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode","title":"SBSDKOneDConfirmationMode","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKOneDConfirmationModeModerate","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKOneDConfirmationModeModerate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKOneDConfirmationModeModerate"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode~1moderate\/title","op":"replace","value":"SBSDKOneDConfirmationModeModerate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode~1moderate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKOneDConfirmationModeModerate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode\/title","op":"replace","value":"SBSDKOneDConfirmationMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode\/fragments","op":"replace","value":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKOneDConfirmationMode"}]}]}]}