{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController"]]},"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetDocumentAccumulation","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","role":"symbol","title":"resetDocumentAccumulation()","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerViewController(im)resetDocumentAccumulation","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"resetDocumentAccumulation"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetDocumentAccumulation","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontroller\/resetdocumentaccumulation()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontroller\/resetdocumentaccumulation()"]}],"abstract":[{"text":"Resets the recognized-documents-accumulator.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController\/resetDocumentAccumulation()"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewController/resetDocumentAccumulation()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetDocumentAccumulation"},{"kind":"text","text":"()"}],"type":"topic","abstract":[{"type":"text","text":"Resets the recognized-documents-accumulator."}],"navigatorTitle":[{"kind":"identifier","text":"resetDocumentAccumulation"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController\/resetDocumentAccumulation()","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontroller\/resetdocumentaccumulation()","kind":"symbol","title":"resetDocumentAccumulation()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewController":{"role":"symbol","title":"SBSDKGenericDocumentRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentRecognizerViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentRecognizerViewController","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to recognize documents, e.g. German passports, ID cards and driver’s licenses on video frames.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"resetDocumentAccumulation","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"resetDocumentAccumulation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"resetDocumentAccumulation"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController~1resetDocumentAccumulation()\/title","value":"resetDocumentAccumulation","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController~1resetDocumentAccumulation()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"resetDocumentAccumulation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController\/title","value":"SBSDKGenericDocumentRecognizerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentRecognizerViewController","kind":"identifier"}],"op":"replace"}]}]}