{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReorderPagesScreenConfiguration(im)toJsonWithConfiguration:","title":"toJson(configuration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReorderPagesScreenConfiguration"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration"},{"text":" = SBSDKToJSONConfiguration()) -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2reorderpagesscreenconfiguration\/tojson(configuration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2reorderpagesscreenconfiguration\/tojson(configuration:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReorderPagesScreenConfiguration\/toJson(configuration:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKToJSONConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKToJSONConfiguration","role":"symbol","kind":"symbol","abstract":[{"text":"Configuration used to serialize an object to json.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktojsonconfiguration","title":"SBSDKToJSONConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKToJSONConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReorderPagesScreenConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReorderPagesScreenConfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the screen for reordering the scanned pages."}],"title":"SBSDKUI2ReorderPagesScreenConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2reorderpagesscreenconfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReorderPagesScreenConfiguration/toJson(configuration:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2reorderpagesscreenconfiguration\/tojson(configuration:)","kind":"symbol","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"type":"topic","title":"toJson(configuration:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReorderPagesScreenConfiguration\/toJson(configuration:)","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"toJsonWithConfiguration:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"toJsonWithConfiguration:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKToJSONConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"value":"SBSDKToJSONConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKToJSONConfiguration\/title"},{"value":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKToJSONConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKToJSONConfiguration\/navigatorTitle","value":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/title","value":"SBSDKUI2ReorderPagesScreenConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/navigatorTitle"},{"op":"replace","value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReorderPagesScreenConfiguration~1toJson(configuration:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReorderPagesScreenConfiguration~1toJson(configuration:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}