{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotUI\/defaultStatusBarStyle","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"The default status bar style of all ScanbotSDK RTU-UI components upon their initialization. Defaults to "},{"code":".lightContent","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultStatusBarStyle"},{"kind":"text","text":": "},{"text":"UIStatusBarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotui\/defaultstatusbarstyle"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotui\/defaultstatusbarstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotUI"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Type Property","symbolKind":"property","title":"defaultStatusBarStyle","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultStatusBarStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIStatusBarStyle","text":"UIStatusBarStyle","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)ScanbotUI(cpy)defaultStatusBarStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultStatusBarStyle"}]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotUI/defaultStatusBarStyle":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultStatusBarStyle"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotUI\/defaultStatusBarStyle","url":"\/documentation\/scanbotdocumentscannersdk\/scanbotui\/defaultstatusbarstyle","abstract":[{"type":"text","text":"The default status bar style of all ScanbotSDK RTU-UI components upon their initialization. Defaults to "},{"type":"codeVoice","code":".lightContent"},{"text":".","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"defaultStatusBarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIStatusBarStyle","text":"UIStatusBarStyle","kind":"typeIdentifier"}],"title":"defaultStatusBarStyle"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotUI":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ScanbotUI","kind":"identifier"}],"navigatorTitle":[{"text":"ScanbotUI","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/scanbotui","abstract":[{"text":"Helper class to configure the properties of the ScanbotSDK RTU-UI (SBSDKUI) components.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotUI","title":"ScanbotUI"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"defaultStatusBarStyle"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultStatusBarStyle"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"UIStatusBarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle"},{"kind":"text","text":" "},{"text":"defaultStatusBarStyle","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"defaultStatusBarStyle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotUI~1defaultStatusBarStyle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotUI~1defaultStatusBarStyle\/fragments","value":[{"kind":"identifier","text":"defaultStatusBarStyle"}],"op":"replace"},{"value":"ScanbotUI","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotUI\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotUI\/fragments","value":[{"text":"ScanbotUI","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotUI\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ScanbotUI"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}