{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"cameraModule","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2CameraModule","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CameraModule","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraModule","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2CameraModule.back, "},{"text":"zoomSteps","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":"] = [1.0, 2.0, 5.0], "},{"text":"defaultZoomFactor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":" = 1.0, ","kind":"text"},{"text":"flashEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"minFocusDistanceLock","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"pinchToZoomEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"orientationLockMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2OrientationLockMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2OrientationLockMode","text":"SBSDKUI2OrientationLockMode"},{"text":" = SBSDKUI2OrientationLockMode.none, ","kind":"text"},{"kind":"externalParam","text":"cameraPreviewMode"},{"kind":"text","text":": "},{"text":"SBSDKUI2CameraPreviewMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CameraPreviewMode","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2CameraPreviewMode.fillIn)"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameraconfiguration\/init(cameramodule:zoomsteps:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:orientationlockmode:camerapreviewmode:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameraconfiguration\/init(cameramodule:zoomsteps:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:orientationlockmode:camerapreviewmode:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","title":"init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cameraModule"},{"kind":"text","text":": "},{"text":"SBSDKUI2CameraModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CameraModule"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"zoomSteps"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"defaultZoomFactor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"flashEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minFocusDistanceLock","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pinchToZoomEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"orientationLockMode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2OrientationLockMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2OrientationLockMode"},{"kind":"text","text":", "},{"text":"cameraPreviewMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CameraPreviewMode","text":"SBSDKUI2CameraPreviewMode","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2CameraConfiguration(im)initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:","navigatorTitle":[{"text":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraConfiguration\/init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraConfiguration":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameraconfiguration","title":"SBSDKUI2CameraConfiguration","kind":"symbol","abstract":[{"text":"Configuration of the camera settings to be used while scanning.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraConfiguration/init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)":{"type":"topic","title":"init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"cameraModule","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CameraModule"},{"kind":"text","text":", "},{"text":"zoomSteps","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"defaultZoomFactor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"flashEnabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minFocusDistanceLock","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pinchToZoomEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"orientationLockMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2OrientationLockMode","text":"SBSDKUI2OrientationLockMode"},{"kind":"text","text":", "},{"text":"cameraPreviewMode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CameraPreviewMode"},{"kind":"text","text":")"}],"abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameraconfiguration\/init(cameramodule:zoomsteps:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:orientationlockmode:camerapreviewmode:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraConfiguration\/init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraModule":{"abstract":[{"type":"text","text":"Determines which camera module to use on start-up."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraModule"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameramodule","title":"SBSDKUI2CameraModule","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraModule","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2OrientationLockMode":{"type":"topic","title":"SBSDKUI2OrientationLockMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2OrientationLockMode","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2orientationlockmode","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}],"abstract":[{"type":"text","text":"Configure the orientation of the interface."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraPreviewMode":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPreviewMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}],"kind":"symbol","abstract":[{"text":"Configuration of the camera preview mode.","type":"text"}],"title":"SBSDKUI2CameraPreviewMode","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2camerapreviewmode","navigatorTitle":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithCameraModule:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraModule","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CameraModule","text":"SBSDKUI2CameraModule","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraModule"},{"text":" ","kind":"text"},{"kind":"identifier","text":"zoomSteps:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"text":"zoomSteps","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultZoomFactor:"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"defaultZoomFactor","kind":"internalParam"},{"kind":"text","text":" "},{"text":"flashEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"flashEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"minFocusDistanceLock:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"minFocusDistanceLock"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinchToZoomEnabled:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pinchToZoomEnabled"},{"text":" ","kind":"text"},{"text":"orientationLockMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2OrientationLockMode","text":"SBSDKUI2OrientationLockMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2OrientationLockMode","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"orientationLockMode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewMode:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPreviewMode","kind":"typeIdentifier","text":"SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CameraPreviewMode"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraPreviewMode"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraConfiguration\/title","value":"SBSDKUI2CameraConfiguration","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraConfiguration\/navigatorTitle"},{"value":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraConfiguration~1init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraConfiguration~1init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraModule\/title","value":"SBSDKUI2CameraModule","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraModule\/fragments","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraModule"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraModule\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2OrientationLockMode\/title","value":"SBSDKUI2OrientationLockMode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2OrientationLockMode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2OrientationLockMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPreviewMode\/title","value":"SBSDKUI2CameraPreviewMode","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPreviewMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPreviewMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}