{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkfeature\/medicalcertscanning"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkfeature\/medicalcertscanning"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/medicalCertScanning"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Medical certificate scanning is enabled in the license."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature"]]},"metadata":{"roleHeading":"Case","role":"symbol","title":"SBSDKFeature.medicalCertScanning","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"medicalCertScanning"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKFeature@SBSDKFeatureMedicalCertScanning","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKFeatureMedicalCertScanning","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"medicalCertScanning"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature","url":"\/documentation\/scanbotsdk\/sbsdkfeature","title":"SBSDKFeature","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFeature","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKFeature","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"The features that are activated in the ScanbotSDK license.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/medicalCertScanning":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKFeatureMedicalCertScanning","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/medicalCertScanning","type":"topic","title":"SBSDKFeature.medicalCertScanning","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"medicalCertScanning","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/medicalcertscanning","abstract":[{"text":"Medical certificate scanning is enabled in the license.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKFeatureMedicalCertScanning","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKFeatureMedicalCertScanning","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKFeatureMedicalCertScanning"}]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKFeature","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/fragments","op":"replace","value":[{"text":"SBSDKFeature","kind":"identifier"}]},{"value":[{"text":"SBSDKFeature","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1medicalCertScanning\/title","op":"replace","value":"SBSDKFeatureMedicalCertScanning"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1medicalCertScanning\/fragments","value":[{"text":"SBSDKFeatureMedicalCertScanning","kind":"identifier"}]}]}]}