{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmsiplesseychecksumalgorithm\/isequal:"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm\/isEqual:","interfaceLanguage":"occ"},"metadata":{"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","title":"isEqual:","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm(im)isEqual:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMSIPlesseyChecksumAlgorithm":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"type":"topic","abstract":[{"text":"Checksum algorithm for MSI_PLESSEY.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm","navigatorTitle":[{"kind":"identifier","text":"SBSDKMSIPlesseyChecksumAlgorithm"}],"url":"\/documentation\/scanbotsdk\/sbsdkmsiplesseychecksumalgorithm","title":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMSIPlesseyChecksumAlgorithm/isEqual:":{"role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm\/isEqual:","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkmsiplesseychecksumalgorithm\/isequal:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/title","op":"replace","value":"SBSDKMSIPlesseyChecksumAlgorithm"},{"value":[{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMSIPlesseyChecksumAlgorithm"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}