{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod\/interpolateByCamera","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeAccumulationMethod@SBSDKBarcodeAccumulationMethodInterpolateByCamera","navigatorTitle":[{"text":"SBSDKBarcodeAccumulationMethodInterpolateByCamera","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interpolateByCamera","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","title":"SBSDKBarcodeAccumulationMethod.interpolateByCamera"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod\/interpolatebycamera"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod\/interpolatebycamera"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod"]]},"sections":[],"kind":"symbol","abstract":[{"text":"The quad of barcode is interpolated by the camera movement. This option is recommended when the camera is","type":"text"},{"text":" ","type":"text"},{"text":"moving, but the scanned object is not.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"interpolateByCamera"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAccumulationMethod/interpolateByCamera":{"abstract":[{"type":"text","text":"The quad of barcode is interpolated by the camera movement. This option is recommended when the camera is"},{"type":"text","text":" "},{"type":"text","text":"moving, but the scanned object is not."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interpolateByCamera","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod\/interpolatebycamera","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod\/interpolateByCamera","type":"topic","title":"SBSDKBarcodeAccumulationMethod.interpolateByCamera","navigatorTitle":[{"text":"SBSDKBarcodeAccumulationMethodInterpolateByCamera","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAccumulationMethod":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod","title":"SBSDKBarcodeAccumulationMethod","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The method how to display barcodes from previous frames."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKBarcodeAccumulationMethodInterpolateByCamera","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKBarcodeAccumulationMethodInterpolateByCamera","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKBarcodeAccumulationMethodInterpolateByCamera","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKBarcodeAccumulationMethodInterpolateByCamera","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod~1interpolateByCamera\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethodInterpolateByCamera"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod~1interpolateByCamera\/fragments"},{"op":"replace","value":"SBSDKBarcodeAccumulationMethod","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod\/fragments"},{"op":"replace","value":[{"text":"SBSDKBarcodeAccumulationMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod\/navigatorTitle"}]}]}