{"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ok","kind":"identifier"}],"symbolKind":"case","title":"SBSDKDocumentVerificationStatus.ok","navigatorTitle":[{"text":"SBSDKDocumentVerificationStatusOk","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentVerificationStatus@SBSDKDocumentVerificationStatusOk","roleHeading":"Case"},"abstract":[{"type":"text","text":"All the verifications passed successfully."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationStatus"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentverificationstatus\/ok"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentverificationstatus\/ok"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ok"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationStatus\/ok"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentVerificationStatus":{"kind":"symbol","type":"topic","title":"SBSDKDocumentVerificationStatus","abstract":[{"text":"Overall status of the document verification.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentverificationstatus","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationStatus","navigatorTitle":[{"text":"SBSDKDocumentVerificationStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentVerificationStatus","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentVerificationStatus/ok":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentverificationstatus\/ok","abstract":[{"type":"text","text":"All the verifications passed successfully."}],"type":"topic","title":"SBSDKDocumentVerificationStatus.ok","navigatorTitle":[{"text":"SBSDKDocumentVerificationStatusOk","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationStatus\/ok","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ok","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKDocumentVerificationStatusOk","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentVerificationStatusOk"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKDocumentVerificationStatusOk"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKDocumentVerificationStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentVerificationStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentVerificationStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationStatus\/navigatorTitle"},{"op":"replace","value":"SBSDKDocumentVerificationStatusOk","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationStatus~1ok\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentVerificationStatusOk","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationStatus~1ok\/fragments"}]}]}