{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormat"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"japanPost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformat\/japanpost"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformat\/japanpost"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Japan Post Four-State Barcode.","type":"text"}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat(cpy)japanPost","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"japanPost","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat"}],"title":"japanPost","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"japanPost"}],"role":"symbol","symbolKind":"property","roleHeading":"Type Property"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormat\/japanPost","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormat/japanPost":{"abstract":[{"text":"Japan Post Four-State Barcode.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"japanPost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat"}],"navigatorTitle":[{"kind":"identifier","text":"japanPost"}],"title":"japanPost","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormat\/japanPost","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformat\/japanpost"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormat":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformat","title":"SBSDKBarcodeFormat","abstract":[{"type":"text","text":"Enumerates barcode formats."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormat"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormat","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormat"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"japanPost"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"japanPost","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormat","text":"SBSDKBarcodeFormat"},{"kind":"text","text":" * "},{"kind":"identifier","text":"japanPost"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat~1japanPost\/title","value":"japanPost"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat~1japanPost\/fragments","value":[{"text":"japanPost","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/title","value":"SBSDKBarcodeFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/fragments","value":[{"text":"SBSDKBarcodeFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}