{"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/mrzscanning"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/mrzscanning"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MRZScanning"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Machine-readable-zone scanning is enabled in the license."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKFeature@SBSDKFeatureMRZScanning","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"MRZScanning","kind":"identifier"}],"title":"SBSDKFeature.MRZScanning","roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"SBSDKFeatureMRZScanning","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/MRZScanning","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFeature"}],"title":"SBSDKFeature","type":"topic","abstract":[{"type":"text","text":"The features that are activated in the ScanbotSDK license."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature","navigatorTitle":[{"text":"SBSDKFeature","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/MRZScanning":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/mrzscanning","type":"topic","navigatorTitle":[{"text":"SBSDKFeatureMRZScanning","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MRZScanning","kind":"identifier"}],"title":"SBSDKFeature.MRZScanning","abstract":[{"type":"text","text":"Machine-readable-zone scanning is enabled in the license."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/MRZScanning"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKFeatureMRZScanning","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKFeatureMRZScanning","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKFeatureMRZScanning","kind":"identifier"}]}]}},{"value":"SBSDKFeature","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature\/fragments","value":[{"kind":"identifier","text":"SBSDKFeature"}],"op":"replace"},{"value":[{"text":"SBSDKFeature","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature\/navigatorTitle","op":"replace"},{"value":"SBSDKFeatureMRZScanning","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1MRZScanning\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1MRZScanning\/fragments","op":"replace","value":[{"text":"SBSDKFeatureMRZScanning","kind":"identifier"}]}]}]}