{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage\/fileformat"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage\/fileformat"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileFormat"},{"text":": ","kind":"text"},{"text":"SBSDKImageFileFormat","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Image file format to be used to store the managed images."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage\/fileFormat","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKIndexedImageStorage(py)fileFormat","navigatorTitle":[{"text":"fileFormat","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileFormat"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat"}],"role":"symbol","title":"fileFormat","symbolKind":"property"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKIndexedImageStorage/fileFormat":{"navigatorTitle":[{"text":"fileFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"Image file format to be used to store the managed images."}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"fileFormat","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat","kind":"typeIdentifier","text":"SBSDKImageFileFormat"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage\/fileformat","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage\/fileFormat","title":"fileFormat"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFileFormat":{"navigatorTitle":[{"text":"SBSDKImageFileFormat","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefileformat","title":"SBSDKImageFileFormat","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFileFormat"}],"type":"topic","kind":"symbol","abstract":[{"text":"Enumeration of supported image file types.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFileFormat"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKIndexedImageStorage":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"abstract":[{"text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Manages images in an array-like fashion."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"title":"SBSDKIndexedImageStorage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"fileFormat"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"fileFormat","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageFileFormat","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileFormat"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"fileFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage~1fileFormat\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage~1fileFormat\/fragments","value":[{"text":"fileFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFileFormat\/title","value":"SBSDKImageFileFormat"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFileFormat\/fragments","value":[{"text":"SBSDKImageFileFormat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFileFormat\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageFileFormat"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/title","op":"replace","value":"SBSDKIndexedImageStorage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}]},{"op":"replace","value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/navigatorTitle"}]}]}