{"metadata":{"title":"copyWithZone:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPartiallyVisibleDocumentConfiguration(im)copyWithZone:","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/copyWithZone:"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier","text":"_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/copywithzone:"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration/copyWithZone:":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"type":"topic","title":"copyWithZone:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/copywithzone:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/copyWithZone:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration","title":"SBSDKPartiallyVisibleDocumentConfiguration","navigatorTitle":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration","abstract":[{"text":"Configuration for handling partially visible documents.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/title","op":"replace","value":"SBSDKPartiallyVisibleDocumentConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}]}]}]}