{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseFront\/metadata"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseFront"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensefront\/metadata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensefront\/metadata"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMetadata","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMetadata","kind":"typeIdentifier","text":"SBSDKDocumentsModelMetadata"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelEuropeanDriverLicenseFront(py)metadata","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"metadata"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMetadata","kind":"typeIdentifier","text":"SBSDKDocumentsModelMetadata"},{"kind":"text","text":"?"}],"title":"metadata","symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"text":"The child document of type “Metadata”.","type":"text"}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanDriverLicenseFront":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensefront","title":"SBSDKDocumentsModelEuropeanDriverLicenseFront","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"European driver license, front side","type":"text"}],"navigatorTitle":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseFront","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseFront","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseFront","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelMetadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelMetadata"}],"title":"SBSDKDocumentsModelMetadata","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMetadata","type":"topic","abstract":[{"type":"text","text":"Metadata for the document"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelMetadata"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmetadata","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanDriverLicenseFront/metadata":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensefront\/metadata","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMetadata","kind":"typeIdentifier","text":"SBSDKDocumentsModelMetadata"},{"kind":"text","text":"?"}],"kind":"symbol","title":"metadata","abstract":[{"type":"text","text":"The child document of type “Metadata”."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseFront\/metadata","navigatorTitle":[{"kind":"identifier","text":"metadata"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"metadata"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"metadata"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBSDKDocumentsModelMetadata","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMetadata","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMetadata"},{"kind":"text","text":" * "},{"kind":"identifier","text":"metadata"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseFront\/title","value":"SBSDKDocumentsModelEuropeanDriverLicenseFront"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseFront\/fragments","value":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseFront","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseFront\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentsModelEuropeanDriverLicenseFront"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMetadata\/title","value":"SBSDKDocumentsModelMetadata"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMetadata\/fragments","value":[{"text":"SBSDKDocumentsModelMetadata","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMetadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentsModelMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseFront~1metadata\/title","value":"metadata"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseFront~1metadata\/fragments","value":[{"text":"metadata","kind":"identifier"}]}]}]}