{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType\/original"},"kind":"symbol","abstract":[{"type":"text","text":"The rotated original image."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype\/original"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype\/original"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKScannedPageImageType@SBSDKScannedPageImageTypeOriginal","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPageImageTypeOriginal"}],"title":"SBSDKScannedPageImageType.original","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"original"}],"symbolKind":"case"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"original","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPageImageType/original":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType\/original","kind":"symbol","title":"SBSDKScannedPageImageType.original","abstract":[{"type":"text","text":"The rotated original image."}],"url":"\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype\/original","navigatorTitle":[{"text":"SBSDKScannedPageImageTypeOriginal","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"original","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPageImageType":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPageImageType"}],"type":"topic","title":"SBSDKScannedPageImageType","url":"\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType","abstract":[{"type":"text","text":"An enum representing the different types of images a scanned page has."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKScannedPageImageType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKScannedPageImageTypeOriginal"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKScannedPageImageTypeOriginal"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKScannedPageImageTypeOriginal"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType~1original\/title","op":"replace","value":"SBSDKScannedPageImageTypeOriginal"},{"value":[{"text":"SBSDKScannedPageImageTypeOriginal","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType~1original\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/title","op":"replace","value":"SBSDKScannedPageImageType"},{"value":[{"kind":"identifier","text":"SBSDKScannedPageImageType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/navigatorTitle","op":"replace","value":[{"text":"SBSDKScannedPageImageType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}