{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unfilteredDocument","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKScannedPageImageTypeUnfilteredDocument","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKScannedPageImageType@SBSDKScannedPageImageTypeUnfilteredDocument","roleHeading":"Case","title":"SBSDKScannedPageImageType.unfilteredDocument"},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType\/unfilteredDocument","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype\/unfiltereddocument"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype\/unfiltereddocument"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The rotated and cropped image, without any filters applied.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unfilteredDocument","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPageImageType/unfilteredDocument":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType\/unfilteredDocument","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unfilteredDocument","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKScannedPageImageTypeUnfilteredDocument","kind":"identifier"}],"abstract":[{"type":"text","text":"The rotated and cropped image, without any filters applied."}],"url":"\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype\/unfiltereddocument","role":"symbol","kind":"symbol","title":"SBSDKScannedPageImageType.unfilteredDocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPageImageType":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPageImageType"}],"type":"topic","title":"SBSDKScannedPageImageType","url":"\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType","abstract":[{"type":"text","text":"An enum representing the different types of images a scanned page has."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKScannedPageImageType","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKScannedPageImageTypeUnfilteredDocument"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"SBSDKScannedPageImageTypeUnfilteredDocument","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKScannedPageImageTypeUnfilteredDocument","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType~1unfilteredDocument\/title","value":"SBSDKScannedPageImageTypeUnfilteredDocument"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType~1unfilteredDocument\/fragments","value":[{"text":"SBSDKScannedPageImageTypeUnfilteredDocument","kind":"identifier"}],"op":"replace"},{"value":"SBSDKScannedPageImageType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/title","op":"replace"},{"value":[{"text":"SBSDKScannedPageImageType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/fragments","op":"replace"},{"value":[{"text":"SBSDKScannedPageImageType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/navigatorTitle"}]}]}