{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"preset5"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarizationFilterPreset"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKBinarizationFilterPreset@SBSDKBinarizationFilterPresetPreset5","navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset5"}],"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKBinarizationFilterPreset.preset5","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"preset5"}],"role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"Performs well even if there are shadows."},{"type":"text","text":" "},{"text":"The preset is an upgrade to PRESET_4 that adds special treatment for high contrast objects such as barcodes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Binarized barcodes typically remain readable."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbinarizationfilterpreset\/preset5"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbinarizationfilterpreset\/preset5"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarizationFilterPreset\/preset5"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBinarizationFilterPreset/preset5":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preset5"}],"role":"symbol","kind":"symbol","title":"SBSDKBinarizationFilterPreset.preset5","abstract":[{"type":"text","text":"Performs well even if there are shadows."},{"text":" ","type":"text"},{"text":"The preset is an upgrade to PRESET_4 that adds special treatment for high contrast objects such as barcodes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Binarized barcodes typically remain readable."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset5"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarizationFilterPreset\/preset5","url":"\/documentation\/scanbotsdk\/sbsdkbinarizationfilterpreset\/preset5","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBinarizationFilterPreset":{"kind":"symbol","title":"SBSDKBinarizationFilterPreset","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarizationFilterPreset","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}],"abstract":[{"type":"text","text":"Preset of parameters for custom binarization filter."}],"url":"\/documentation\/scanbotsdk\/sbsdkbinarizationfilterpreset"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"SBSDKBinarizationFilterPresetPreset5","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"SBSDKBinarizationFilterPresetPreset5","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKBinarizationFilterPresetPreset5","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"SBSDKBinarizationFilterPresetPreset5","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarizationFilterPreset~1preset5\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarizationFilterPreset~1preset5\/fragments","value":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset5"}],"op":"replace"},{"value":"SBSDKBinarizationFilterPreset","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarizationFilterPreset\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarizationFilterPreset\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBinarizationFilterPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarizationFilterPreset\/navigatorTitle","value":[{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}