{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preset3"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarizationFilterPreset"]]},"abstract":[{"text":"Performs well even if there are shadows.","type":"text"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset3"}],"title":"SBSDKBinarizationFilterPreset.preset3","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKBinarizationFilterPreset@SBSDKBinarizationFilterPresetPreset3","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preset3"}],"roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbinarizationfilterpreset\/preset3"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbinarizationfilterpreset\/preset3"]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarizationFilterPreset\/preset3","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBinarizationFilterPreset":{"kind":"symbol","title":"SBSDKBinarizationFilterPreset","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarizationFilterPreset","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}],"abstract":[{"type":"text","text":"Preset of parameters for custom binarization filter."}],"url":"\/documentation\/scanbotsdk\/sbsdkbinarizationfilterpreset"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBinarizationFilterPreset/preset3":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset3"}],"type":"topic","abstract":[{"type":"text","text":"Performs well even if there are shadows."}],"title":"SBSDKBinarizationFilterPreset.preset3","url":"\/documentation\/scanbotsdk\/sbsdkbinarizationfilterpreset\/preset3","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preset3","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarizationFilterPreset\/preset3","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"SBSDKBinarizationFilterPresetPreset3","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKBinarizationFilterPresetPreset3","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKBinarizationFilterPresetPreset3","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKBinarizationFilterPreset","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarizationFilterPreset\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarizationFilterPreset\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBinarizationFilterPreset"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarizationFilterPreset\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBinarizationFilterPreset"}]},{"op":"replace","value":"SBSDKBinarizationFilterPresetPreset3","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarizationFilterPreset~1preset3\/title"},{"value":[{"text":"SBSDKBinarizationFilterPresetPreset3","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarizationFilterPreset~1preset3\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}