{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"decoder"},{"kind":"text","text":": any "},{"text":"Decoder","preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/RawRepresentable-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/init(from:)"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/init(from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"init(from:)","externalID":"s:SYsSeRzSi8RawValueSYRtzrlE4fromxs7Decoder_p_tKcfc::SYNTHESIZED::c:@M@ScanbotSDK@E@SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"extendedModule":"Swift","modules":[{"relatedModules":["Swift"],"name":"ScanbotSDK"}],"roleHeading":"Initializer","role":"symbol","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Decodable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"Int"},{"type":"text","text":"."}]},"symbolKind":"init"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(from:)"},{"type":"text","text":"."}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus","kind":"symbol","abstract":[{"type":"text","text":"Health insurance card field validation status."}],"title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/RawRepresentable-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/rawrepresentable-implementations","kind":"article","type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus/init(from:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/init(from:)","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Decodable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"Int"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/init(from:)","title":"init(from:)","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/title","value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","op":"replace"},{"value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/navigatorTitle"}]}]}