{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2sound\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Sound\/hash"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Sound"]]},"metadata":{"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Sound(py)hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"roleHeading":"Instance Property","title":"hash","symbolKind":"property","fragments":[{"kind":"identifier","text":"hash"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Sound/hash":{"abstract":[],"type":"topic","kind":"symbol","title":"hash","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2sound\/hash","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Sound\/hash","fragments":[{"kind":"identifier","text":"hash"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Sound":{"title":"SBSDKUI2Sound","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Sound","type":"topic","navigatorTitle":[{"text":"SBSDKUI2Sound","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2Sound","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2sound","abstract":[{"text":"Sound configuration.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2Sound","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Sound\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Sound\/fragments","op":"replace","value":[{"text":"SBSDKUI2Sound","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2Sound"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Sound\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}