{"kind":"symbol","metadata":{"symbolKind":"method","role":"symbol","title":"animationController(forPresented:presenting:source:)","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController(im)animationControllerForPresentedController:presentingController:sourceController:","navigatorTitle":[{"kind":"identifier","text":"animationControllerForPresentedController:presentingController:sourceController:"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"animationController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forPresented","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"presenting","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":", ","kind":"text"},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":") -> "},{"text":"UIViewControllerAnimatedTransitioning","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning"},{"text":"?","kind":"text"}],"extendedModule":"ScanbotSDK","roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/animationcontroller(forpresented:presenting:source:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/animationcontroller(forpresented:presenting:source:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"animationController","kind":"identifier"},{"kind":"text","text":"("},{"text":"forPresented","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"presented","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presenting"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":", ","kind":"text"},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning","kind":"typeIdentifier","text":"UIViewControllerAnimatedTransitioning"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/UIViewControllerTransitioningDelegate-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIViewControllerTransitioningDelegate.animationController(forPresented:presenting:source:)","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/animationController(forPresented:presenting:source:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController/animationController(forPresented:presenting:source:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/animationController(forPresented:presenting:source:)","title":"animationController(forPresented:presenting:source:)","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"animationControllerForPresentedController:presentingController:sourceController:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/animationcontroller(forpresented:presenting:source:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animationController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forPresented"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"presenting","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":") -> ","kind":"text"},{"text":"UIViewControllerAnimatedTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController":{"navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"abstract":[{"text":"A highly customizable camera-based view controller to recognize generic documents.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller","title":"SBSDKUIGenericDocumentRecognizerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","type":"topic","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController/UIViewControllerTransitioningDelegate-Implementations":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/UIViewControllerTransitioningDelegate-Implementations","abstract":[],"role":"collectionGroup","title":"UIViewControllerTransitioningDelegate Implementations","kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/uiviewcontrollertransitioningdelegate-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"animationControllerForPresentedController:presentingController:sourceController:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"animationControllerForPresentedController:presentingController:sourceController:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id<UIViewControllerAnimatedTransitioning>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerAnimatedTransitioning"},{"text":") ","kind":"text"},{"text":"animationControllerForPresentedController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"presented","kind":"internalParam"},{"kind":"text","text":" "},{"text":"presentingController:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"presenting"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sourceController:"},{"text":"(","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"text":"source","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController~1animationController(forPresented:presenting:source:)\/title","value":"animationControllerForPresentedController:presentingController:sourceController:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController~1animationController(forPresented:presenting:source:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"animationControllerForPresentedController:presentingController:sourceController:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/title","value":"SBSDKUIGenericDocumentRecognizerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewController"}]}]}]}