{"sections":[],"abstract":[{"text":"Creates a new instance of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/create(configuration:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/create(configuration:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Type Method","symbolKind":"method","title":"create(configuration:delegate:)","navigatorTitle":[{"kind":"identifier","text":"createWithConfiguration:andDelegate:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController(cm)createWithConfiguration:andDelegate:","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIGenericDocumentRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerConfiguration"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIGenericDocumentRecognizerViewControllerDelegate","text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController","text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"typeIdentifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(createWithConfiguration:andDelegate:) "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"text":"SBSDKUIGenericDocumentRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerConfiguration"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIGenericDocumentRecognizerViewControllerDelegate"},{"text":"?) -> ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController","text":"SBSDKUIGenericDocumentRecognizerViewController"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"text":"The configuration to define look and feel of the new detection view controller.","type":"text"}]}]},{"name":"delegate","content":[{"inlineContent":[{"type":"text","text":"The delegate of the new detection view controller."}],"type":"paragraph"}]}]},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController"},{"type":"text","text":"."}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/create(configuration:delegate:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController/create(configuration:delegate:)":{"role":"symbol","navigatorTitle":[{"text":"createWithConfiguration:andDelegate:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/create(configuration:delegate:)","abstract":[{"text":"Creates a new instance of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"title":"create(configuration:delegate:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIGenericDocumentRecognizerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/create(configuration:delegate:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller","kind":"symbol","title":"SBSDKUIGenericDocumentRecognizerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewController"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize generic documents."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewControllerDelegate":{"title":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","role":"symbol","navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate"}],"abstract":[{"type":"text","text":"The delegate protocol for "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","type":"reference"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontrollerdelegate","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerConfiguration":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerconfiguration","navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerConfiguration","title":"SBSDKUIGenericDocumentRecognizerConfiguration","role":"symbol","abstract":[{"type":"text","text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI generic document recognizers screen."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"createWithConfiguration:andDelegate:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createWithConfiguration:andDelegate:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController","text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController"},{"text":" *) ","kind":"text"},{"text":"createWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerConfiguration","text":"SBSDKUIGenericDocumentRecognizerConfiguration"},{"kind":"text","text":" *) "},{"text":"configuration","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"andDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SBSDKUIGenericDocumentRecognizerViewControllerDelegate>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKUIGenericDocumentRecognizerViewControllerDelegate"},{"kind":"text","text":") "},{"text":"delegate","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"createWithConfiguration:andDelegate:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController~1create(configuration:delegate:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController~1create(configuration:delegate:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithConfiguration:andDelegate:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/title","value":"SBSDKUIGenericDocumentRecognizerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewControllerDelegate\/title","value":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerConfiguration\/title","value":"SBSDKUIGenericDocumentRecognizerConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerConfiguration\/fragments"}]}]}