{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The receivers delegate."}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/delegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIGenericDocumentRecognizerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewControllerDelegate"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"delegate","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIGenericDocumentRecognizerViewControllerDelegate","kind":"typeIdentifier","text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate"},{"text":"?","kind":"text"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController(py)delegate","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/delegate"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize generic documents."}],"title":"SBSDKUIGenericDocumentRecognizerViewController","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewControllerDelegate":{"title":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate"}],"navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontrollerdelegate","role":"symbol","abstract":[{"type":"text","text":"The delegate protocol for "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController/delegate":{"role":"symbol","kind":"symbol","title":"delegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/delegate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIGenericDocumentRecognizerViewControllerDelegate","text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The receivers delegate."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"delegate"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"delegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKUIGenericDocumentRecognizerViewControllerDelegate","text":"id<SBSDKUIGenericDocumentRecognizerViewControllerDelegate>"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKUIGenericDocumentRecognizerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/fragments","value":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}]},{"value":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/navigatorTitle"},{"op":"replace","value":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewControllerDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewControllerDelegate\/fragments"},{"op":"replace","value":[{"text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewControllerDelegate\/navigatorTitle"},{"value":"delegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController~1delegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController~1delegate\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}