{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraTextConfiguration","text":"SBSDKUIEnableCameraTextConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"enableCameraTextConfiguration"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/enablecameratextconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/enableCameraTextConfiguration","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"enableCameraTextConfiguration"}],"title":"enableCameraTextConfiguration","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController(py)enableCameraTextConfiguration","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"enableCameraTextConfiguration"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController":{"role":"symbol","title":"SBSDKUIGenericDocumentRecognizerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewController"}],"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize generic documents."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraTextConfiguration":{"role":"symbol","title":"SBSDKUIEnableCameraTextConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"abstract":[{"type":"text","text":"Configuration for the textual contents of camera based view controllers."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuienablecameratextconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController/enableCameraTextConfiguration":{"role":"symbol","title":"enableCameraTextConfiguration","fragments":[{"kind":"identifier","text":"enableCameraTextConfiguration"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/enableCameraTextConfiguration","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/enablecameratextconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.2.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/title","value":"SBSDKUIGenericDocumentRecognizerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/title","value":"SBSDKUIEnableCameraTextConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}