{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/interactioncontrollerfordismissal(using:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/interactioncontrollerfordismissal(using:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/interactionControllerForDismissal(using:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/UIViewControllerTransitioningDelegate-Implementations"]]},"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interactionControllerForDismissal"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning","text":"UIViewControllerAnimatedTransitioning"},{"kind":"text","text":") -> "},{"text":"UIViewControllerInteractiveTransitioning","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerInteractiveTransitioning"},{"text":"?","kind":"text"}],"symbolKind":"method","role":"symbol","title":"interactionControllerForDismissal(using:)","navigatorTitle":[{"text":"interactionControllerForDismissal:","kind":"identifier"}],"extendedModule":"ScanbotSDK","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController(im)interactionControllerForDismissal:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interactionControllerForDismissal"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"using"},{"text":" ","kind":"text"},{"text":"animator","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIViewControllerAnimatedTransitioning","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerInteractiveTransitioning","text":"UIViewControllerInteractiveTransitioning"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIViewControllerTransitioningDelegate.interactionControllerForDismissal(using:)","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController/interactionControllerForDismissal(using:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/interactionControllerForDismissal(using:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interactionControllerForDismissal"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning","text":"UIViewControllerAnimatedTransitioning","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerInteractiveTransitioning","text":"UIViewControllerInteractiveTransitioning"},{"kind":"text","text":"?"}],"kind":"symbol","title":"interactionControllerForDismissal(using:)","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/interactioncontrollerfordismissal(using:)","role":"symbol","navigatorTitle":[{"text":"interactionControllerForDismissal:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize generic documents."}],"title":"SBSDKUIGenericDocumentRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController/UIViewControllerTransitioningDelegate-Implementations":{"abstract":[],"kind":"article","title":"UIViewControllerTransitioningDelegate Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/UIViewControllerTransitioningDelegate-Implementations","role":"collectionGroup","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/uiviewcontrollertransitioningdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"interactionControllerForDismissal:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interactionControllerForDismissal:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)UIViewControllerInteractiveTransitioning","text":"id<UIViewControllerInteractiveTransitioning>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"interactionControllerForDismissal:"},{"text":"(","kind":"text"},{"text":"id<UIViewControllerAnimatedTransitioning>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerAnimatedTransitioning"},{"text":") ","kind":"text"},{"text":"animator","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"interactionControllerForDismissal:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController~1interactionControllerForDismissal(using:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController~1interactionControllerForDismissal(using:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"interactionControllerForDismissal:","kind":"identifier"}]},{"value":"SBSDKUIGenericDocumentRecognizerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/title"},{"op":"replace","value":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}