{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController"]]},"abstract":[{"text":"Creates a new instance of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","type":"reference"},{"type":"text","text":" and presents it modally."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/present(on:configuration:delegate:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(presentOn:configuration:delegate:) "},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":" ","kind":"text"},{"text":"presenter","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerConfiguration","text":"SBSDKUIGenericDocumentRecognizerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIGenericDocumentRecognizerViewControllerDelegate","kind":"typeIdentifier","text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","kind":"typeIdentifier","text":"SBSDKUIGenericDocumentRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller the new instance should be presented on."}]}],"name":"presenter"},{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"text":"The configuration to define look and feel of the new detection view controller.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"The delegate of the new detection view controller.","type":"text"}],"type":"paragraph"}],"name":"delegate"}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A new instance of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","type":"reference"},{"text":".","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/present(on:configuration:delegate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/present(on:configuration:delegate:)"]}],"metadata":{"navigatorTitle":[{"text":"presentOn:configuration:delegate:","kind":"identifier"}],"symbolKind":"method","title":"present(on:configuration:delegate:)","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIGenericDocumentRecognizerViewControllerDelegate","text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController","text":"SBSDKUIGenericDocumentRecognizerViewController"}],"roleHeading":"Type Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController(cm)presentOn:configuration:delegate:"},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewControllerDelegate":{"title":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate"}],"navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontrollerdelegate","role":"symbol","abstract":[{"type":"text","text":"The delegate protocol for "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerConfiguration":{"title":"SBSDKUIGenericDocumentRecognizerConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerconfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIGenericDocumentRecognizerConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerConfiguration"}],"kind":"symbol","abstract":[{"text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI generic document recognizers screen.","type":"text"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize generic documents."}],"title":"SBSDKUIGenericDocumentRecognizerViewController","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController/present(on:configuration:delegate:)":{"navigatorTitle":[{"kind":"identifier","text":"presentOn:configuration:delegate:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/present(on:configuration:delegate:)","title":"present(on:configuration:delegate:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIGenericDocumentRecognizerViewControllerDelegate","text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SBSDKUIGenericDocumentRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController"}],"abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","isActive":true,"type":"reference"},{"type":"text","text":" and presents it modally."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/present(on:configuration:delegate:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"presentOn:configuration:delegate:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"presentOn:configuration:delegate:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"SBSDKUIGenericDocumentRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"presentOn:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"presenter","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuration:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerConfiguration","text":"SBSDKUIGenericDocumentRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SBSDKUIGenericDocumentRecognizerViewControllerDelegate>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKUIGenericDocumentRecognizerViewControllerDelegate"},{"kind":"text","text":") "},{"kind":"internalParam","text":"delegate"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"presenter","content":[{"inlineContent":[{"text":"The view controller the new instance should be presented on.","type":"text"}],"type":"paragraph"}]},{"name":"configuration","content":[{"inlineContent":[{"type":"text","text":"The configuration to define look and feel of the new detection view controller."}],"type":"paragraph"}]},{"name":"delegate","content":[{"inlineContent":[{"text":"The delegate of the new detection view controller.","type":"text"}],"type":"paragraph"}]}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"A new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewControllerDelegate\/title","value":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewControllerDelegate\/fragments","op":"replace","value":[{"text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}]},{"value":[{"text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewControllerDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerConfiguration\/title","op":"replace","value":"SBSDKUIGenericDocumentRecognizerConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerConfiguration\/fragments","value":[{"text":"SBSDKUIGenericDocumentRecognizerConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIGenericDocumentRecognizerConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/title","value":"SBSDKUIGenericDocumentRecognizerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewController"}]},{"op":"replace","value":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController~1present(on:configuration:delegate:)\/title","value":"presentOn:configuration:delegate:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController~1present(on:configuration:delegate:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"presentOn:configuration:delegate:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}