{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/sbsdkgenericdocumentrecognizerviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/sbsdkgenericdocumentrecognizerviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"API Collection","title":"SBSDKGenericDocumentRecognizerViewControllerDelegate Implementations","role":"collectionGroup","modules":[{"name":"ScanbotSDK"}]},"sections":[],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/SBSDKGenericDocumentRecognizerViewControllerDelegate-Implementations"},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/documentRecognizerViewController(_:didRecognize:on:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","title":"SBSDKUIGenericDocumentRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller","kind":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize generic documents."}],"navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewController"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController/documentRecognizerViewController(_:didRecognize:on:)":{"abstract":[{"text":"Informs the delegate that a document has been recognized successfully.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"documentRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKGenericDocumentRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerViewController"},{"kind":"text","text":", "},{"text":"didRecognize","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognitionResult","text":"SBSDKGenericDocumentRecognitionResult","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":")"}],"title":"documentRecognizerViewController(_:didRecognize:on:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller\/documentrecognizerviewcontroller(_:didrecognize:on:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/documentRecognizerViewController(_:didRecognize:on:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentRecognizerViewController:didRecognizeResult:onImage:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController\/documentRecognizerViewController(_:didRecognize:on:)"],"generated":true,"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":"SBSDKUIGenericDocumentRecognizerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/fragments","value":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}]},{"value":"documentRecognizerViewController:didRecognizeResult:onImage:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController~1documentRecognizerViewController(_:didRecognize:on:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"documentRecognizerViewController:didRecognizeResult:onImage:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController~1documentRecognizerViewController(_:didRecognize:on:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}