{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/viewDidAppear:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/viewdidappear:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"viewDidAppear:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"viewDidAppear:","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController(im)viewDidAppear:","role":"symbol"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewDidAppear:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController/viewDidAppear:":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/viewdidappear:","fragments":[{"text":"- ","kind":"text"},{"text":"viewDidAppear:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/viewDidAppear:","kind":"symbol","title":"viewDidAppear:","type":"topic","role":"symbol","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"title":"SBSDKDocumentScannerViewController","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller","abstract":[{"type":"text","text":"A UIViewController subclass to show a camera screen and run a user guiding document scanner."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title","value":"SBSDKDocumentScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments","value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}