{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKBarcodeFormatCode39Configuration) ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCode39Configuration","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/init()"],"anchor":"Initializers"},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/code32","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/code39","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/maximumTextLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/minimumTextLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/pzn7","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/pzn8","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/stripCheckDigits","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/tryCode39ExtendedMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/useCode39CheckDigit"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/toJson(configuration:)"],"generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"metadata":{"roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKBarcodeFormatCode39Configuration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode39Configuration"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCode39Configuration","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCode39Configuration","role":"symbol","symbolKind":"class"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration"]}],"abstract":[{"text":"Code 39 barcode and derivatives configuration. Add to scanner configuration to scan Code 39, Code 32 (Italian","type":"text"},{"type":"text","text":" "},{"text":"Pharmacode), PZN7 and PZN8 (Pharmazentralnummer) barcodes.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/hash":{"abstract":[],"title":"hash","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/hash","fragments":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/hash","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/pzn7":{"role":"symbol","title":"pzn7","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/pzn7","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"pzn7","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"pzn7","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/pzn7","kind":"symbol","abstract":[{"text":"If true, scan PZN7 (legacy Pharmazentralnummer) barcodes. If false, PZN7 barcodes are not decoded and are","type":"text"},{"type":"text","text":" "},{"text":"returned as CODE_39 instead.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:code32:code39:pzn7:pzn8:tryCode39ExtendedMode:useCode39CheckDigit:":{"type":"topic","role":"symbol","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:code32:code39:pzn7:pzn8:tryCode39ExtendedMode:useCode39CheckDigit:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:code32:code39:pzn7:pzn8:tryCode39ExtendedMode:useCode39CheckDigit:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:code32:code39:pzn7:pzn8:tryCode39ExtendedMode:useCode39CheckDigit:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:stripcheckdigits:minimumtextlength:maximumtextlength:code32:code39:pzn7:pzn8:trycode39extendedmode:usecode39checkdigit:","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:code32:code39:pzn7:pzn8:tryCode39ExtendedMode:useCode39CheckDigit:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/maximumTextLength":{"abstract":[{"text":"Maximum text length. 0 implies no maximum. Applied only to linear barcode formats that allow variable length.","type":"text"}],"title":"maximumTextLength","navigatorTitle":[{"text":"maximumTextLength","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/maximumtextlength","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumTextLength","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/maximumTextLength","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/new":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"new"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/new","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/new","title":"new","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"new"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/copyWithZone:":{"role":"symbol","title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/copywithzone:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/copyWithZone:","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"Foundation.NSCopying","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/minimumTextLength":{"role":"symbol","title":"minimumTextLength","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/minimumtextlength","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumTextLength","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"minimumTextLength","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/minimumTextLength","kind":"symbol","abstract":[{"text":"Minimum text length. Applied only to linear barcode formats that allow variable length.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/fromJsonWithJson:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/fromJsonWithJson:","title":"fromJsonWithJson:","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/fromjsonwithjson:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"kind":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatOneDConfigurationBase":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatonedconfigurationbase","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}],"abstract":[{"type":"text","text":"Base class for all linear (1D) barcode configurations."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}],"type":"topic","title":"SBSDKBarcodeFormatOneDConfigurationBase"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/tryCode39ExtendedMode":{"navigatorTitle":[{"text":"tryCode39ExtendedMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/trycode39extendedmode","abstract":[{"type":"text","text":"If true, try to scan CODE_39 in extended mode."}],"title":"tryCode39ExtendedMode","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/tryCode39ExtendedMode","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tryCode39ExtendedMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/isEqual:":{"abstract":[],"title":"isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/isequal:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/isEqual:","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/stripCheckDigits":{"kind":"symbol","navigatorTitle":[{"text":"stripCheckDigits","kind":"identifier"}],"abstract":[{"type":"text","text":"If true, the check digits are stripped from the result."}],"title":"stripCheckDigits","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"stripCheckDigits","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/stripcheckdigits","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/stripCheckDigits"},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/useCode39CheckDigit":{"abstract":[{"text":"If true, return CODE_39 barcodes only if they have a valid check digit.","type":"text"}],"title":"useCode39CheckDigit","navigatorTitle":[{"text":"useCode39CheckDigit","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/usecode39checkdigit","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useCode39CheckDigit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/useCode39CheckDigit","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/pzn8":{"kind":"symbol","title":"pzn8","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/pzn8","abstract":[{"type":"text","text":"If true, scan PZN8 (Pharmazentralnummer) barcodes. If false, PZN8 barcodes are not decoded and are returned as"},{"type":"text","text":" "},{"type":"text","text":"CODE_39 instead."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"pzn8","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/pzn8","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pzn8"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/code32":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/code32","kind":"symbol","type":"topic","navigatorTitle":[{"text":"code32","kind":"identifier"}],"title":"code32","abstract":[{"text":"If true, scan and return valid CODE_32 (Italian Pharmacode) barcodes. If false, CODE_32 barcodes are not decoded","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and are returned as CODE_39 instead."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/code32","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"code32"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/code39":{"role":"symbol","type":"topic","title":"code39","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"code39"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"code39"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/code39","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/code39","abstract":[{"text":"If true, scan CODE_39 barcodes.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/init()":{"title":"init()","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration","title":"SBSDKBarcodeFormatCode39Configuration","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Code 39 barcode and derivatives configuration. Add to scanner configuration to scan Code 39, Code 32 (Italian"},{"type":"text","text":" "},{"text":"Pharmacode), PZN7 and PZN8 (Pharmazentralnummer) barcodes.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatCode39Configuration"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration","navigatorTitle":[{"text":"SBSDKBarcodeFormatCode39Configuration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/toJson(configuration:)":{"title":"toJson(configuration:)","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/tojson(configuration:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/toJson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"toJson","kind":"identifier"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKBarcodeFormatCode39Configuration"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKBarcodeFormatCode39Configuration","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode39Configuration"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/code32","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/code39","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/maximumTextLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/minimumTextLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/pzn7","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/pzn8","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/stripCheckDigits","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/tryCode39ExtendedMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/useCode39CheckDigit"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:code32:code39:pzn7:pzn8:tryCode39ExtendedMode:useCode39CheckDigit:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/toJson(configuration:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/fromJsonWithJson:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/new"],"anchor":"Type-Methods","title":"Type Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormatCode39Configuration","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase","text":"SBSDKBarcodeFormatOneDConfigurationBase","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatOneDConfigurationBase"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1pzn7\/title","value":"pzn7"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1pzn7\/fragments","value":[{"kind":"identifier","text":"pzn7"}]},{"op":"replace","value":"maximumTextLength","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1maximumTextLength\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1maximumTextLength\/fragments","op":"replace","value":[{"text":"maximumTextLength","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1minimumTextLength\/title","op":"replace","value":"minimumTextLength"},{"op":"replace","value":[{"kind":"identifier","text":"minimumTextLength"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1minimumTextLength\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/title","value":"SBSDKBarcodeFormatOneDConfigurationBase"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatOneDConfigurationBase"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1tryCode39ExtendedMode\/title","value":"tryCode39ExtendedMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1tryCode39ExtendedMode\/fragments","value":[{"text":"tryCode39ExtendedMode","kind":"identifier"}],"op":"replace"},{"value":"stripCheckDigits","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1stripCheckDigits\/title","op":"replace"},{"value":[{"kind":"identifier","text":"stripCheckDigits"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1stripCheckDigits\/fragments","op":"replace"},{"value":"useCode39CheckDigit","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1useCode39CheckDigit\/title"},{"op":"replace","value":[{"kind":"identifier","text":"useCode39CheckDigit"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1useCode39CheckDigit\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1pzn8\/title","value":"pzn8","op":"replace"},{"value":[{"text":"pzn8","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1pzn8\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1code32\/title","value":"code32"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1code32\/fragments","value":[{"kind":"identifier","text":"code32"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1code39\/title","value":"code39"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1code39\/fragments","value":[{"text":"code39","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1init()\/title","value":"init","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration\/title","value":"SBSDKBarcodeFormatCode39Configuration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration\/fragments","value":[{"text":"SBSDKBarcodeFormatCode39Configuration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormatCode39Configuration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration~1toJson(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}]}]}]}