{"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)UIViewController"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/s8SendableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring","doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2TextPatternScannerViewController","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/create(with:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/present(on:configuration:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/present(on:configuration:completion:)"],"anchor":"Type-Methods","generated":true}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerviewcontroller"]}],"kind":"symbol","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan generic text data.","type":"text"}],"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextPatternScannerViewController","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKUI2TextPatternScannerViewController","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerViewController","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerViewController"}]},"references":{"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s8SendableP","title":"Swift.Sendable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerViewController/create(with:completion:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"text":"SBSDKUI2TextPatternScannerScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerScreenConfiguration"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"SBSDKUI2TextPatternScannerUIResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerUIResult"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerViewController","text":"SBSDKUI2TextPatternScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"createWith:completion:"}],"title":"create(with:completion:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/create(with:completion:)","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerviewcontroller\/create(with:completion:)","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Creates a new instance of the Text Pattern scanner and returns it to be presented modally."}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://net.doo.ScanbotSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerViewController/initWithCoder:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"title":"initWithCoder:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/initWithCoder:","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerviewcontroller\/initwithcoder:","type":"topic","role":"symbol","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://net.doo.ScanbotSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerViewController/present(on:configuration:completion:)":{"navigatorTitle":[{"text":"presentOn:configuration:completion:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2TextPatternScannerScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerScreenConfiguration"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerUIResult","text":"SBSDKUI2TextPatternScannerUIResult"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerViewController","kind":"typeIdentifier","text":"SBSDKUI2TextPatternScannerViewController"},{"text":"?","kind":"text"}],"title":"present(on:configuration:completion:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/present(on:configuration:completion:)","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerviewcontroller\/present(on:configuration:completion:)","abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController","isActive":true,"type":"reference"},{"type":"text","text":" and presents it modally."}]},"doc://net.doo.ScanbotSDK/objc(cs)UIViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)UIViewController","type":"unresolvable","title":"UIViewController"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerViewController/initWithNibName:bundle:":{"type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerviewcontroller\/initwithnibname:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"role":"symbol","title":"initWithNibName:bundle:","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/initWithNibName:bundle:"},"doc://net.doo.ScanbotSDK/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerViewController/viewDidLoad":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerviewcontroller\/viewdidload","title":"viewDidLoad","abstract":[],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/viewDidLoad"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerViewController/present(on:configuration:)":{"title":"present(on:configuration:)","abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController","isActive":true},{"type":"text","text":" and presents it modally."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerviewcontroller\/present(on:configuration:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/present(on:configuration:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2TextPatternScannerScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerScreenConfiguration"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerUIResult","text":"SBSDKUI2TextPatternScannerUIResult"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerViewController/childViewControllerForStatusBarStyle":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerviewcontroller\/childviewcontrollerforstatusbarstyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/childViewControllerForStatusBarStyle","fragments":[{"text":"childViewControllerForStatusBarStyle","kind":"identifier"}],"role":"symbol","title":"childViewControllerForStatusBarStyle","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerviewcontroller","abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to scan generic text data."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerViewController"}],"title":"SBSDKUI2TextPatternScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextPatternScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerViewController/supportedInterfaceOrientations":{"kind":"symbol","abstract":[],"title":"supportedInterfaceOrientations","fragments":[{"kind":"identifier","text":"supportedInterfaceOrientations"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerviewcontroller\/supportedinterfaceorientations","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/supportedInterfaceOrientations"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerViewController/childViewControllerForStatusBarHidden":{"fragments":[{"kind":"identifier","text":"childViewControllerForStatusBarHidden"}],"title":"childViewControllerForStatusBarHidden","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/childViewControllerForStatusBarHidden","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerviewcontroller\/childviewcontrollerforstatusbarhidden","type":"topic","role":"symbol","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"SBSDKUI2TextPatternScannerViewController","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2TextPatternScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/childViewControllerForStatusBarHidden","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/childViewControllerForStatusBarStyle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/supportedInterfaceOrientations"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/initWithCoder:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/initWithNibName:bundle:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/viewDidLoad"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"generated":true,"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/create(with:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerViewController\/present(on:configuration:completion:)"]}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)UIViewController"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKUI2TextPatternScannerViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerViewController~1create(with:completion:)\/title","value":"createWith:completion:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerViewController~1create(with:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWith:completion:"}],"op":"replace"},{"value":"presentOn:configuration:completion:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerViewController~1present(on:configuration:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerViewController~1present(on:configuration:completion:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"presentOn:configuration:completion:","kind":"identifier"}]},{"value":"SBSDKUI2TextPatternScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerViewController\/fragments","value":[{"text":"SBSDKUI2TextPatternScannerViewController","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2TextPatternScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}