{"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatTwoDConfigurationBase"],"title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration"]}],"abstract":[{"type":"text","text":"QR Code configuration. Add to scanner configuration to scan QR codes, Micro QR codes and rectangular Micro QR (rMQR)"},{"text":" ","type":"text"},{"type":"text","text":"codes."}],"kind":"symbol","metadata":{"title":"SBSDKBarcodeFormatQRCodeConfiguration","roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatQRCodeConfiguration","modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","navigatorTitle":[{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(SBSDKBarcodeFormatQRCodeConfiguration) ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/init()"],"anchor":"Initializers","title":"Initializers","generated":true},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/gs1Handling","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/microQr","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/qr","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/rmqr","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/strictMode"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/toJson(configuration:)"],"anchor":"Instance-Methods"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:qr:microQr:rmqr:":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:qr:microQr:rmqr:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:qr:microQr:rmqr:","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:qr:microQr:rmqr:","kind":"identifier"}],"title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:qr:microQr:rmqr:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:gs1handling:strictmode:qr:microqr:rmqr:","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/init()":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/init()","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"title":"init()","type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/new":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/new","title":"new","abstract":[],"navigatorTitle":[{"text":"new","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/new"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/fromjsonwithjson:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/fromJsonWithJson:","abstract":[],"type":"topic","title":"fromJsonWithJson:","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/gs1Handling":{"title":"gs1Handling","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/gs1Handling","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/gs1handling","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gs1Handling"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gs1Handling","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGS1Handling","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKGS1Handling"}],"role":"symbol","abstract":[{"type":"text","text":"GS1 message handling options."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/rmqr":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/rmqr","title":"rmqr","abstract":[{"type":"text","text":"If true, scan and return rectangular Micro QR (rMQR) codes."}],"navigatorTitle":[{"kind":"identifier","text":"rmqr"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rmqr","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/rmqr"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/toJson(configuration:)":{"navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/toJson(configuration:)","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/tojson(configuration:)","title":"toJson(configuration:)"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/strictMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/strictMode","title":"strictMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"strictMode"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/strictmode","type":"topic","navigatorTitle":[{"text":"strictMode","kind":"identifier"}],"abstract":[{"type":"text","text":"If true, the barcode scanner will only return barcodes that pass the strict validation checks according to"},{"type":"text","text":" "},{"text":"standards to avoid false positives.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/copyWithZone:":{"title":"copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/copywithzone:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/copyWithZone:","kind":"symbol","type":"topic","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/isEqual:":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/isequal:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/isEqual:","kind":"symbol","title":"isEqual:","type":"topic","abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatTwoDConfigurationBase":{"title":"SBSDKBarcodeFormatTwoDConfigurationBase","abstract":[{"type":"text","text":"Base class for all 2D barcode configurations."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormatTwoDConfigurationBase","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformattwodconfigurationbase","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatTwoDConfigurationBase"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatTwoDConfigurationBase","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/hash":{"abstract":[],"title":"hash","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/hash","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/hash","type":"topic","fragments":[{"text":"hash","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"identifier"}],"kind":"symbol","title":"SBSDKBarcodeFormatQRCodeConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration","abstract":[{"text":"QR Code configuration. Add to scanner configuration to scan QR codes, Micro QR codes and rectangular Micro QR (rMQR)","type":"text"},{"type":"text","text":" "},{"type":"text","text":"codes."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/qr":{"role":"symbol","abstract":[{"type":"text","text":"If true, scan and return QR codes."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/qr","title":"qr","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"qr"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/qr","kind":"symbol","navigatorTitle":[{"text":"qr","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/microQr":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"microQr","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"microQr","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/microqr","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/microQr","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"microQr"}],"abstract":[{"type":"text","text":"If true, scan and return Micro QR codes."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeFormatQRCodeConfiguration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatQRCodeConfiguration"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/gs1Handling","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/microQr","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/qr","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/rmqr","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/strictMode"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:qr:microQr:rmqr:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/toJson(configuration:)"],"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/fromJsonWithJson:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/new"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"}],"path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatTwoDConfigurationBase"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatTwoDConfigurationBase","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatTwoDConfigurationBase","text":"SBSDKBarcodeFormatTwoDConfigurationBase"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1init()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1gs1Handling\/title","value":"gs1Handling"},{"value":[{"text":"gs1Handling","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1gs1Handling\/fragments","op":"replace"},{"value":"rmqr","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1rmqr\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1rmqr\/fragments","op":"replace","value":[{"text":"rmqr","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1toJson(configuration:)\/title","op":"replace","value":"toJsonWithConfiguration:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1toJson(configuration:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}]},{"value":"strictMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1strictMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1strictMode\/fragments","op":"replace","value":[{"text":"strictMode","kind":"identifier"}]},{"op":"replace","value":"SBSDKBarcodeFormatTwoDConfigurationBase","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatTwoDConfigurationBase\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatTwoDConfigurationBase\/fragments","value":[{"text":"SBSDKBarcodeFormatTwoDConfigurationBase","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatTwoDConfigurationBase","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatTwoDConfigurationBase\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration\/title","value":"SBSDKBarcodeFormatQRCodeConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatQRCodeConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1qr\/title","value":"qr"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1qr\/fragments","value":[{"text":"qr","kind":"identifier"}],"op":"replace"},{"value":"microQr","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1microQr\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1microQr\/fragments","op":"replace","value":[{"text":"microQr","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}