{"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"enum","externalID":"c:@M@ScanbotSDK@E@SBSDKFeature","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKFeature"}],"title":"SBSDKFeature","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeature"}],"roleHeading":"Enumeration","role":"symbol"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"type":"text","text":"The features that are activated in the ScanbotSDK license."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/EHICScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/IDCardScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/MRZScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/NFCScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/OCR","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/PDFCreation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/barcodeScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/checkScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/cloudUpload","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/creditCardScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/dataIntelligence","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/driverLicenseScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/edgeDetection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/edgeDetectionUI","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/imageProcessing","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/invoiceDetection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/licensePlateScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/medicalCertScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/multipleObjectsDetection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/payformDetection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/textOrientationDetection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/textPatternScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/w2Detection"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKFeature","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkfeature"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkfeature"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/checkScanning":{"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/checkscanning","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKFeatureCheckScanning","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkScanning"}],"title":"SBSDKFeature.checkScanning","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/checkScanning","abstract":[{"type":"text","text":"Check scanning is enabled in the license."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/barcodeScanning":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/barcodeScanning","type":"topic","abstract":[{"type":"text","text":"Barcode scanning is enabled in the license."}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/barcodescanning","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"barcodeScanning","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureBarcodeScanning"}],"title":"SBSDKFeature.barcodeScanning"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/IDCardScanning":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IDCardScanning"}],"title":"SBSDKFeature.IDCardScanning","navigatorTitle":[{"text":"SBSDKFeatureIDCardScanning","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/IDCardScanning","abstract":[{"text":"ID card and passport scanning is enabled in the license.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfeature\/idcardscanning"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/creditCardScanning":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"creditCardScanning","kind":"identifier"}],"abstract":[{"text":"Credit card scanning is enabled in the license.","type":"text"}],"title":"SBSDKFeature.creditCardScanning","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureCreditCardScanning"}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/creditcardscanning","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/creditCardScanning","role":"symbol","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/NFCScanning":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureNFCScanning"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/NFCScanning","type":"topic","abstract":[{"type":"text","text":"NFC scanning is enabled in the license. Currently unused."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"NFCScanning","kind":"identifier"}],"title":"SBSDKFeature.NFCScanning","url":"\/documentation\/scanbotsdk\/sbsdkfeature\/nfcscanning"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/edgeDetectionUI":{"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/edgedetectionui","kind":"symbol","abstract":[{"text":"Document detection user interface is enabled in the license.","type":"text"}],"navigatorTitle":[{"text":"SBSDKFeatureEdgeDetectionUI","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/edgeDetectionUI","type":"topic","role":"symbol","title":"SBSDKFeature.edgeDetectionUI","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"edgeDetectionUI","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/w2Detection":{"abstract":[{"type":"text","text":"W2 document detection is enabled in the license. Currently unused."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/w2Detection","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"w2Detection"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureW2Detection"}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/w2detection","title":"SBSDKFeature.w2Detection","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/SBSDKFeatureNone":{"fragments":[{"kind":"identifier","text":"SBSDKFeatureNone"}],"title":"SBSDKFeatureNone","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/SBSDKFeatureNone","abstract":[{"type":"text","text":"Driver license scanning is enabled in the license. Currently unused."}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfeature\/sbsdkfeaturenone"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/dataIntelligence":{"abstract":[{"type":"text","text":"Data intelligence is enabled in the license. Currently unused."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/dataIntelligence","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataIntelligence","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKFeatureDataIntelligence","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkfeature\/dataintelligence","title":"SBSDKFeature.dataIntelligence"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/edgeDetection":{"type":"topic","abstract":[{"text":"Document detection is enabled in the license.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/edgedetection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"edgeDetection","kind":"identifier"}],"role":"symbol","title":"SBSDKFeature.edgeDetection","navigatorTitle":[{"text":"SBSDKFeatureEdgeDetection","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/edgeDetection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/textPatternScanning":{"role":"symbol","title":"SBSDKFeature.textPatternScanning","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureTextPatternScanning"}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/textpatternscanning","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"textPatternScanning","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/textPatternScanning","abstract":[{"type":"text","text":"Text pattern scanning is enabled in the license."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/cloudUpload":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cloudUpload"}],"abstract":[{"type":"text","text":"Cloud upload is enabled in the license. Currently unused."}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/cloudupload","title":"SBSDKFeature.cloudUpload","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/cloudUpload","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureCloudUpload"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/RawRepresentable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/RawRepresentable-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkfeature\/rawrepresentable-implementations","abstract":[],"kind":"article","title":"RawRepresentable Implementations","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/multipleObjectsDetection":{"title":"SBSDKFeature.multipleObjectsDetection","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"multipleObjectsDetection","kind":"identifier"}],"abstract":[{"type":"text","text":"Multiple objects detection is enabled in the license. Currently unused."}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/multipleobjectsdetection","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/multipleObjectsDetection","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKFeatureMultipleObjectsDetection","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature":{"kind":"symbol","abstract":[{"text":"The features that are activated in the ScanbotSDK license.","type":"text"}],"navigatorTitle":[{"text":"SBSDKFeature","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature","title":"SBSDKFeature","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFeature","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/MRZScanning":{"role":"symbol","abstract":[{"text":"Machine-readable-zone scanning is enabled in the license.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/MRZScanning","title":"SBSDKFeature.MRZScanning","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MRZScanning"}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/mrzscanning","kind":"symbol","navigatorTitle":[{"text":"SBSDKFeatureMRZScanning","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/textOrientationDetection":{"role":"symbol","abstract":[{"text":"Text layout recognition is enabled in the license.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/textOrientationDetection","title":"SBSDKFeature.textOrientationDetection","url":"\/documentation\/scanbotsdk\/sbsdkfeature\/textorientationdetection","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textOrientationDetection"}],"navigatorTitle":[{"text":"SBSDKFeatureTextOrientationDetection","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/payformDetection":{"title":"SBSDKFeature.payformDetection","role":"symbol","abstract":[{"text":"Payform detection is enabled in the license. Currently unused.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKFeaturePayformDetection"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/payformDetection","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"payformDetection"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkfeature\/payformdetection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/imageProcessing":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/imageProcessing","kind":"symbol","navigatorTitle":[{"text":"SBSDKFeatureImageProcessing","kind":"identifier"}],"abstract":[{"text":"Image processing is enabled in the license.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/imageprocessing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"imageProcessing","kind":"identifier"}],"type":"topic","title":"SBSDKFeature.imageProcessing"},"doc://net.doo.ScanbotSDK/s12CaseIterableP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","type":"unresolvable","title":"Swift.CaseIterable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","url":"\/documentation\/scanbotsdk\/sbsdkfeature\/init(rawvalue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/init(rawValue:)","abstract":[],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/OCR":{"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/ocr","navigatorTitle":[{"text":"SBSDKFeatureOCR","kind":"identifier"}],"abstract":[{"text":"Optical character recognition is enabled in the license.","type":"text"}],"title":"SBSDKFeature.OCR","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OCR","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/OCR"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/driverLicenseScanning":{"kind":"symbol","abstract":[{"text":"Driver license scanning is enabled in the license. Currently unused.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"driverLicenseScanning","kind":"identifier"}],"title":"SBSDKFeature.driverLicenseScanning","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/driverLicenseScanning","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkfeature\/driverlicensescanning","role":"symbol","navigatorTitle":[{"text":"SBSDKFeatureDriverLicenseScanning","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/PDFCreation":{"navigatorTitle":[{"text":"SBSDKFeaturePDFCreation","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PDFCreation"}],"kind":"symbol","title":"SBSDKFeature.PDFCreation","url":"\/documentation\/scanbotsdk\/sbsdkfeature\/pdfcreation","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/PDFCreation","type":"topic","abstract":[{"type":"text","text":"PDF creation is enabled in the license."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/medicalCertScanning":{"kind":"symbol","title":"SBSDKFeature.medicalCertScanning","navigatorTitle":[{"text":"SBSDKFeatureMedicalCertScanning","kind":"identifier"}],"abstract":[{"text":"Medical certificate scanning is enabled in the license.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"medicalCertScanning"}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/medicalcertscanning","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/medicalCertScanning"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/licensePlateScanning":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/licensePlateScanning","title":"SBSDKFeature.licensePlateScanning","kind":"symbol","abstract":[{"text":"License plate scanning is enabled in the license.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/licenseplatescanning","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureLicensePlateScanning"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licensePlateScanning","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/EHICScanning":{"title":"SBSDKFeature.EHICScanning","abstract":[{"text":"European health insurance card scanning is enabled in the license.","type":"text"}],"navigatorTitle":[{"text":"SBSDKFeatureEHICScanning","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/ehicscanning","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/EHICScanning","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EHICScanning"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/invoiceDetection":{"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/invoicedetection","title":"SBSDKFeature.invoiceDetection","navigatorTitle":[{"text":"SBSDKFeatureInvoiceDetection","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/invoiceDetection","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invoiceDetection","kind":"identifier"}],"abstract":[{"type":"text","text":"Invoice recognition is enabled in the license. Currently unused."}]},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/Equatable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/Equatable-Implementations","kind":"article","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/equatable-implementations","type":"topic","title":"Equatable Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKFeature","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKFeature"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKFeature","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/EHICScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/IDCardScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/MRZScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/NFCScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/OCR","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/PDFCreation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/SBSDKFeatureNone","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/barcodeScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/checkScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/cloudUpload","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/creditCardScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/dataIntelligence","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/driverLicenseScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/edgeDetection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/edgeDetectionUI","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/imageProcessing","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/invoiceDetection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/licensePlateScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/medicalCertScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/multipleObjectsDetection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/payformDetection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/textOrientationDetection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/textPatternScanning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/w2Detection"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKFeature","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1checkScanning\/title","value":"SBSDKFeatureCheckScanning","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKFeatureCheckScanning"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1checkScanning\/fragments"},{"value":"SBSDKFeatureBarcodeScanning","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1barcodeScanning\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1barcodeScanning\/fragments","value":[{"text":"SBSDKFeatureBarcodeScanning","kind":"identifier"}]},{"value":"SBSDKFeatureIDCardScanning","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1IDCardScanning\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1IDCardScanning\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureIDCardScanning"}]},{"value":"SBSDKFeatureCreditCardScanning","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1creditCardScanning\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1creditCardScanning\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKFeatureCreditCardScanning"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1NFCScanning\/title","value":"SBSDKFeatureNFCScanning"},{"value":[{"text":"SBSDKFeatureNFCScanning","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1NFCScanning\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1edgeDetectionUI\/title","value":"SBSDKFeatureEdgeDetectionUI"},{"value":[{"text":"SBSDKFeatureEdgeDetectionUI","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1edgeDetectionUI\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1w2Detection\/title","op":"replace","value":"SBSDKFeatureW2Detection"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1w2Detection\/fragments","op":"replace","value":[{"text":"SBSDKFeatureW2Detection","kind":"identifier"}]},{"value":"SBSDKFeatureDataIntelligence","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1dataIntelligence\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1dataIntelligence\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureDataIntelligence"}]},{"op":"replace","value":"SBSDKFeatureEdgeDetection","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1edgeDetection\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1edgeDetection\/fragments","op":"replace","value":[{"text":"SBSDKFeatureEdgeDetection","kind":"identifier"}]},{"op":"replace","value":"SBSDKFeatureTextPatternScanning","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1textPatternScanning\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1textPatternScanning\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKFeatureTextPatternScanning"}]},{"op":"replace","value":"SBSDKFeatureCloudUpload","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1cloudUpload\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1cloudUpload\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureCloudUpload"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1multipleObjectsDetection\/title","value":"SBSDKFeatureMultipleObjectsDetection","op":"replace"},{"value":[{"text":"SBSDKFeatureMultipleObjectsDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1multipleObjectsDetection\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/title","op":"replace","value":"SBSDKFeature"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/fragments","op":"replace","value":[{"text":"SBSDKFeature","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFeature"}]},{"value":"SBSDKFeatureMRZScanning","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1MRZScanning\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1MRZScanning\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureMRZScanning"}],"op":"replace"},{"op":"replace","value":"SBSDKFeatureTextOrientationDetection","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1textOrientationDetection\/title"},{"value":[{"text":"SBSDKFeatureTextOrientationDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1textOrientationDetection\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1payformDetection\/title","value":"SBSDKFeaturePayformDetection"},{"value":[{"text":"SBSDKFeaturePayformDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1payformDetection\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1imageProcessing\/title","value":"SBSDKFeatureImageProcessing","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1imageProcessing\/fragments","op":"replace","value":[{"text":"SBSDKFeatureImageProcessing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1OCR\/title","value":"SBSDKFeatureOCR","op":"replace"},{"value":[{"text":"SBSDKFeatureOCR","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1OCR\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1driverLicenseScanning\/title","op":"replace","value":"SBSDKFeatureDriverLicenseScanning"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1driverLicenseScanning\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureDriverLicenseScanning"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1PDFCreation\/title","value":"SBSDKFeaturePDFCreation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1PDFCreation\/fragments","value":[{"text":"SBSDKFeaturePDFCreation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1medicalCertScanning\/title","value":"SBSDKFeatureMedicalCertScanning","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1medicalCertScanning\/fragments","value":[{"text":"SBSDKFeatureMedicalCertScanning","kind":"identifier"}],"op":"replace"},{"value":"SBSDKFeatureLicensePlateScanning","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1licensePlateScanning\/title"},{"value":[{"text":"SBSDKFeatureLicensePlateScanning","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1licensePlateScanning\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1EHICScanning\/title","value":"SBSDKFeatureEHICScanning"},{"value":[{"kind":"identifier","text":"SBSDKFeatureEHICScanning"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1EHICScanning\/fragments"},{"value":"SBSDKFeatureInvoiceDetection","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1invoiceDetection\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1invoiceDetection\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureInvoiceDetection"}]}]}]}