{"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrorcode"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKErrorCode","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/OCRLanguageMissing","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/PDFCreation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/PDFMetadataCreation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/cancelled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/imageProcessingError","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/imageStorageCopyingFailed","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/invalidFileURL","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/invalidImageData","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/invalidImageStorage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/pageAnalysis","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/textRecognition","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/unknown"],"generated":true,"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKErrorCode"}],"symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCode"}],"title":"SBSDKErrorCode","externalID":"c:@M@ScanbotSDK@E@SBSDKErrorCode","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Enumeration"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"type":"text","text":"The error codes in the SBSDKErrorDomain."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/unknown":{"url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/unknown","title":"SBSDKErrorCode.unknown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodeUnknown"}],"abstract":[{"type":"text","text":"Some other error."}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/unknown"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/PDFCreation":{"url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/pdfcreation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/PDFCreation","type":"topic","title":"SBSDKErrorCode.PDFCreation","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"PDFCreation","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKErrorCodePDFCreation","kind":"identifier"}],"abstract":[{"type":"text","text":"There was an unknown error while generating a PDF page."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKErrorCode","kind":"identifier"}],"abstract":[{"type":"text","text":"The error codes in the SBSDKErrorDomain."}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkerrorcode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode","title":"SBSDKErrorCode","navigatorTitle":[{"text":"SBSDKErrorCode","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/RawRepresentable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/rawrepresentable-implementations","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/textRecognition":{"url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/textrecognition","title":"SBSDKErrorCode.textRecognition","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"textRecognition","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKErrorCodeTextRecognition","kind":"identifier"}],"abstract":[{"type":"text","text":"Optical text recognition failed."}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/textRecognition"},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/OCRLanguageMissing":{"url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/ocrlanguagemissing","title":"SBSDKErrorCode.OCRLanguageMissing","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OCRLanguageMissing","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodeOCRLanguageMissing"}],"abstract":[{"type":"text","text":"Language data for text recognition is missing."}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/OCRLanguageMissing"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/imageStorageCopyingFailed":{"url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/imagestoragecopyingfailed","type":"topic","abstract":[{"type":"text","text":"The image storage was invalid or nil."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/imageStorageCopyingFailed","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"imageStorageCopyingFailed","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKErrorCodeImageStorageCopyingFailed","kind":"identifier"}],"title":"SBSDKErrorCode.imageStorageCopyingFailed"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/cancelled":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/cancelled","abstract":[{"type":"text","text":"The operation was cancelled."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/cancelled","type":"topic","title":"SBSDKErrorCode.cancelled","navigatorTitle":[{"text":"SBSDKErrorCodeCancelled","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/invalidFileURL":{"navigatorTitle":[{"text":"SBSDKErrorCodeInvalidFileURL","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/invalidFileURL","role":"symbol","abstract":[{"type":"text","text":"The file does not exist."}],"type":"topic","title":"SBSDKErrorCode.invalidFileURL","url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/invalidfileurl","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidFileURL"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/imageProcessingError":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"imageProcessingError","kind":"identifier"}],"abstract":[{"type":"text","text":"There was an unknown error while processing the image.*\/"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/imageprocessingerror","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/imageProcessingError","title":"SBSDKErrorCode.imageProcessingError","navigatorTitle":[{"text":"SBSDKErrorCodeImageProcessingError","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/init(rawValue:)":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/init(rawValue:)","role":"symbol","abstract":[],"type":"topic","title":"init(rawValue:)","url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/PDFMetadataCreation":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"PDFMetadataCreation","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/PDFMetadataCreation","type":"topic","abstract":[{"text":"There was an unknown error while generating pdf metadata.*\/","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/pdfmetadatacreation","kind":"symbol","title":"SBSDKErrorCode.PDFMetadataCreation","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodePDFMetadataCreation"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/invalidImageData":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodeInvalidImageData"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/invalidImageData","role":"symbol","abstract":[{"type":"text","text":"The image file did not contain valid image data."}],"type":"topic","title":"SBSDKErrorCode.invalidImageData","url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/invalidimagedata","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidImageData","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/pageAnalysis":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageAnalysis"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/pageAnalysis","abstract":[{"type":"text","text":"Page analysis failed."}],"url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/pageanalysis","kind":"symbol","title":"SBSDKErrorCode.pageAnalysis","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodePageAnalysis"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/Equatable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/equatable-implementations","abstract":[],"kind":"article","title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/Equatable-Implementations","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/invalidImageStorage":{"navigatorTitle":[{"text":"SBSDKErrorCodeInvalidImageStorage","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/invalidImageStorage","role":"symbol","abstract":[{"type":"text","text":"The image storage was invalid or nil."}],"type":"topic","title":"SBSDKErrorCode.invalidImageStorage","url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/invalidimagestorage","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidImageStorage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKErrorCode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKErrorCode"}]},{"path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/OCRLanguageMissing","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/PDFCreation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/PDFMetadataCreation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/cancelled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/imageProcessingError","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/imageStorageCopyingFailed","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/invalidFileURL","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/invalidImageData","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/invalidImageStorage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/pageAnalysis","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/textRecognition","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/unknown"],"title":"Enumeration Cases"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKErrorCode"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1unknown\/title","value":"SBSDKErrorCodeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1unknown\/fragments","value":[{"text":"SBSDKErrorCodeUnknown","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1PDFCreation\/title","value":"SBSDKErrorCodePDFCreation","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1PDFCreation\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorCodePDFCreation"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/title","value":"SBSDKErrorCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/fragments","value":[{"text":"SBSDKErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/navigatorTitle","value":[{"text":"SBSDKErrorCode","kind":"identifier"}]},{"value":"SBSDKErrorCodeTextRecognition","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1textRecognition\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1textRecognition\/fragments","value":[{"text":"SBSDKErrorCodeTextRecognition","kind":"identifier"}]},{"value":"SBSDKErrorCodeOCRLanguageMissing","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1OCRLanguageMissing\/title"},{"op":"replace","value":[{"text":"SBSDKErrorCodeOCRLanguageMissing","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1OCRLanguageMissing\/fragments"},{"op":"replace","value":"SBSDKErrorCodeImageStorageCopyingFailed","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1imageStorageCopyingFailed\/title"},{"value":[{"text":"SBSDKErrorCodeImageStorageCopyingFailed","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1imageStorageCopyingFailed\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1cancelled\/title","op":"replace","value":"SBSDKErrorCodeCancelled"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1cancelled\/fragments","value":[{"kind":"identifier","text":"SBSDKErrorCodeCancelled"}]},{"value":"SBSDKErrorCodeInvalidFileURL","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1invalidFileURL\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1invalidFileURL\/fragments","value":[{"kind":"identifier","text":"SBSDKErrorCodeInvalidFileURL"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1imageProcessingError\/title","value":"SBSDKErrorCodeImageProcessingError","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1imageProcessingError\/fragments","op":"replace","value":[{"text":"SBSDKErrorCodeImageProcessingError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1PDFMetadataCreation\/title","op":"replace","value":"SBSDKErrorCodePDFMetadataCreation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1PDFMetadataCreation\/fragments","value":[{"text":"SBSDKErrorCodePDFMetadataCreation","kind":"identifier"}]},{"value":"SBSDKErrorCodeInvalidImageData","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1invalidImageData\/title"},{"value":[{"kind":"identifier","text":"SBSDKErrorCodeInvalidImageData"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1invalidImageData\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1pageAnalysis\/title","op":"replace","value":"SBSDKErrorCodePageAnalysis"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorCodePageAnalysis"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1pageAnalysis\/fragments"},{"value":"SBSDKErrorCodeInvalidImageStorage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1invalidImageStorage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorCodeInvalidImageStorage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1invalidImageStorage\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}