{"abstract":[{"type":"text","text":"European Health Insurance Card (EHIC) issuing country."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKEuropeanHealthInsuranceCardIssuingCountry) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"symbolKind":"class","role":"symbol","navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"identifier"}],"title":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","roleHeading":"Class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry"},"kind":"symbol","topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/rawValue"],"title":"Instance Properties"},{"anchor":"Type-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/austria","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/belgium","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/bulgaria","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/croatia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/cyprus","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/czechRepublic","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/denmark","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/estonia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/finland","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/france","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/germany","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/greece","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/hungary","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/ireland","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/italy","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/latvia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/lithuania","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/luxembourg","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/malta","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/netherlands","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/poland","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/portugal","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/romania","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/slovakia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/slovenia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/spain","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/sweden","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/switzerland"],"generated":true,"title":"Type Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/enumValue(from:)"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/estonia":{"title":"estonia","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/estonia","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"estonia"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"estonia"},{"text":": ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"abstract":[{"type":"text","text":"Estonia."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/estonia"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/bulgaria":{"abstract":[{"type":"text","text":"Bulgaria."}],"title":"bulgaria","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/bulgaria","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bulgaria","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/bulgaria","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"bulgaria"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/ireland":{"title":"ireland","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/ireland","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ireland"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ireland"},{"text":": ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"abstract":[{"type":"text","text":"Ireland."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/ireland"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/hungary":{"abstract":[{"type":"text","text":"Hungary."}],"title":"hungary","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/hungary","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"hungary","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/hungary","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"hungary"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/spain":{"title":"spain","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/spain","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"spain"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"spain"},{"text":": ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"abstract":[{"type":"text","text":"Spain."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/spain"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/enumValue(from:)":{"abstract":[{"type":"text","text":"Returns an instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry","isActive":true},{"text":" based on the provided raw value.","type":"text"}],"title":"enumValue(from:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/enumValue(from:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enumValue","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/enumvalue(from:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"enumValueFrom:"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/denmark":{"title":"denmark","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/denmark","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"denmark","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"denmark","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"abstract":[{"text":"Denmark.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/denmark"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/switzerland":{"abstract":[{"text":"Switzerland.","type":"text"}],"title":"switzerland","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/switzerland","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"switzerland","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/switzerland","kind":"symbol","navigatorTitle":[{"text":"switzerland","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/romania":{"title":"romania","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/romania","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"romania"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"romania","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"abstract":[{"type":"text","text":"Romania."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/romania"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/hash":{"abstract":[],"title":"hash","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/hash","fragments":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/hash","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/cyprus":{"title":"cyprus","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/cyprus","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cyprus"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cyprus","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"abstract":[{"type":"text","text":"Cyprus."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/cyprus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/rawValue":{"abstract":[{"type":"text","text":"The raw value integer of the current "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry","isActive":true},{"type":"text","text":"."}],"title":"rawValue","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/rawValue","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/rawvalue","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"rawValue"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/germany":{"title":"germany","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/germany","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"germany","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"germany"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier"}],"abstract":[{"text":"Germany (Validation performed according to “Spezifikation für Musterkarten und Testkarten (eGK, HBA, SMC),","type":"text"},{"type":"text","text":" "},{"text":"Anhang A” and “GS1 Struktur der Kenn-Nummer (ICCSN) der elektronischen Gesundheitskarte”).","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/germany"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/czechRepublic":{"title":"czechRepublic","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/czechrepublic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"czechRepublic"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"czechRepublic","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"abstract":[{"text":"Czech Republic.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/czechRepublic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/portugal":{"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/portugal","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"portugal","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/portugal","navigatorTitle":[{"text":"portugal","kind":"identifier"}],"type":"topic","role":"symbol","title":"portugal","abstract":[{"text":"Portugal.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/poland":{"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/poland","abstract":[{"text":"Poland.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/poland","title":"poland","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"poland","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"navigatorTitle":[{"text":"poland","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"title":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","abstract":[{"type":"text","text":"European Health Insurance Card (EHIC) issuing country."}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/belgium":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"belgium"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/belgium","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/belgium","navigatorTitle":[{"text":"belgium","kind":"identifier"}],"abstract":[{"text":"Belgium.","type":"text"}],"title":"belgium"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/malta":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/malta","abstract":[{"type":"text","text":"Malta."}],"navigatorTitle":[{"kind":"identifier","text":"malta"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/malta","role":"symbol","kind":"symbol","title":"malta","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"malta","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/italy":{"type":"topic","role":"symbol","title":"italy","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/italy","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"italy","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/italy","navigatorTitle":[{"text":"italy","kind":"identifier"}],"abstract":[{"type":"text","text":"Italy."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/greece":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/greece","abstract":[{"type":"text","text":"Greece."}],"navigatorTitle":[{"text":"greece","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/greece","role":"symbol","kind":"symbol","title":"greece","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"greece"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/luxembourg":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/luxembourg","abstract":[{"type":"text","text":"Luxembourg."}],"navigatorTitle":[{"text":"luxembourg","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/luxembourg","role":"symbol","kind":"symbol","title":"luxembourg","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"luxembourg"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/sweden":{"type":"topic","role":"symbol","title":"sweden","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/sweden","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sweden"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/sweden","navigatorTitle":[{"text":"sweden","kind":"identifier"}],"abstract":[{"text":"Sweden.","type":"text"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/isEqual:":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/isEqual:","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/isequal:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[],"title":"isEqual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/netherlands":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/netherlands","title":"netherlands","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"netherlands"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"netherlands","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier"}],"abstract":[{"text":"Netherlands.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/netherlands"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/finland":{"abstract":[{"type":"text","text":"Finland."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finland","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/finland","navigatorTitle":[{"text":"finland","kind":"identifier"}],"title":"finland","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/finland"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/lithuania":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/lithuania","title":"lithuania","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"lithuania"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"lithuania","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"abstract":[{"type":"text","text":"Lithuania."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/lithuania"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/slovakia":{"abstract":[{"type":"text","text":"Slovakia."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"slovakia"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/slovakia","navigatorTitle":[{"kind":"identifier","text":"slovakia"}],"title":"slovakia","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/slovakia"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/slovenia":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/slovenia","title":"slovenia","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"slovenia"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"slovenia"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"abstract":[{"type":"text","text":"Slovenia."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/slovenia"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/croatia":{"abstract":[{"type":"text","text":"Croatia."}],"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"croatia"},{"text":": ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/croatia","navigatorTitle":[{"text":"croatia","kind":"identifier"}],"title":"croatia","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/croatia"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/latvia":{"abstract":[{"text":"Latvia.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"latvia"},{"kind":"text","text":": "},{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/latvia","navigatorTitle":[{"kind":"identifier","text":"latvia"}],"title":"latvia","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/latvia"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/austria":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/austria","title":"austria","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"austria"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"austria","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"abstract":[{"type":"text","text":"Austria (Validation on the personal identification number is performed as described in"},{"type":"text","text":" "},{"text":"“site:www.sozialversicherung.at Was ist die Versicherungsnummer?”).","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/austria"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry/france":{"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry\/france","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"france","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"france"}],"role":"symbol","kind":"symbol","title":"france","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/france","type":"topic","abstract":[{"text":"France.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"}]},{"op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/rawValue"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/isEqual:"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/austria","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/belgium","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/bulgaria","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/croatia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/cyprus","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/czechRepublic","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/denmark","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/estonia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/finland","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/france","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/germany","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/greece","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/hungary","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/ireland","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/italy","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/latvia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/lithuania","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/luxembourg","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/malta","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/netherlands","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/poland","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/portugal","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/romania","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/slovakia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/slovenia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/spain","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/sweden","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/switzerland"],"generated":true,"title":"Type Properties","anchor":"Type-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry\/enumValue(from:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1estonia\/title","value":"estonia","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1estonia\/fragments","value":[{"text":"estonia","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1bulgaria\/title","value":"bulgaria"},{"op":"replace","value":[{"kind":"identifier","text":"bulgaria"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1bulgaria\/fragments"},{"value":"ireland","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1ireland\/title","op":"replace"},{"op":"replace","value":[{"text":"ireland","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1ireland\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1hungary\/title","value":"hungary","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1hungary\/fragments","op":"replace","value":[{"text":"hungary","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1spain\/title","value":"spain","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1spain\/fragments","value":[{"kind":"identifier","text":"spain"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1enumValue(from:)\/title","value":"enumValueFrom:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1enumValue(from:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"enumValueFrom:"}],"op":"replace"},{"value":"denmark","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1denmark\/title"},{"op":"replace","value":[{"text":"denmark","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1denmark\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1switzerland\/title","value":"switzerland","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1switzerland\/fragments","value":[{"kind":"identifier","text":"switzerland"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1romania\/title","value":"romania"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1romania\/fragments","op":"replace","value":[{"kind":"identifier","text":"romania"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1cyprus\/title","value":"cyprus","op":"replace"},{"op":"replace","value":[{"text":"cyprus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1cyprus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1rawValue\/title","value":"rawValue"},{"op":"replace","value":[{"text":"rawValue","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1rawValue\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1germany\/title","value":"germany"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1germany\/fragments","op":"replace","value":[{"text":"germany","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1czechRepublic\/title","value":"czechRepublic"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1czechRepublic\/fragments","op":"replace","value":[{"text":"czechRepublic","kind":"identifier"}]},{"value":"portugal","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1portugal\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1portugal\/fragments","value":[{"kind":"identifier","text":"portugal"}],"op":"replace"},{"value":"poland","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1poland\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1poland\/fragments","value":[{"kind":"identifier","text":"poland"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry\/title","op":"replace","value":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"},{"value":[{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1belgium\/title","op":"replace","value":"belgium"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1belgium\/fragments","value":[{"kind":"identifier","text":"belgium"}]},{"value":"malta","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1malta\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1malta\/fragments","op":"replace","value":[{"text":"malta","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1italy\/title","value":"italy"},{"op":"replace","value":[{"text":"italy","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1italy\/fragments"},{"op":"replace","value":"greece","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1greece\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1greece\/fragments","value":[{"kind":"identifier","text":"greece"}]},{"value":"luxembourg","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1luxembourg\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1luxembourg\/fragments","op":"replace","value":[{"kind":"identifier","text":"luxembourg"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1sweden\/title","value":"sweden"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1sweden\/fragments","value":[{"text":"sweden","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"netherlands","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1netherlands\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1netherlands\/fragments","value":[{"kind":"identifier","text":"netherlands"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1finland\/title","value":"finland","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1finland\/fragments","value":[{"text":"finland","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1lithuania\/title","value":"lithuania"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1lithuania\/fragments","value":[{"text":"lithuania","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1slovakia\/title","value":"slovakia","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1slovakia\/fragments","value":[{"text":"slovakia","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1slovenia\/title","value":"slovenia"},{"value":[{"kind":"identifier","text":"slovenia"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1slovenia\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1croatia\/title","op":"replace","value":"croatia"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1croatia\/fragments","value":[{"kind":"identifier","text":"croatia"}],"op":"replace"},{"op":"replace","value":"latvia","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1latvia\/title"},{"value":[{"text":"latvia","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1latvia\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1austria\/title","value":"austria"},{"value":[{"text":"austria","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1austria\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1france\/title","value":"france","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry~1france\/fragments","op":"replace","value":[{"text":"france","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}