{"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)ScanbotUI(cpy)defaultImageStoreEncrypter","title":"defaultImageStoreEncrypter","navigatorTitle":[{"text":"defaultImageStoreEncrypter","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultImageStoreEncrypter","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?"}],"symbolKind":"property","roleHeading":"Type Property","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"abstract":[{"type":"text","text":"The SBSDKUI-component-wide encrypter for storing image data to disk. Defaults to "},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"defaultImageStoreEncrypter","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting","text":"SBSDKStorageCrypting","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"nil"},{"text":" no encryption is used at all.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You can use the built-in encrypter "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESEncrypter","isActive":true},{"type":"text","text":" to encrypt your sensitive image data"},{"text":" ","type":"text"},{"text":"using AES128 or AES256 before storing it to disk.","type":"text"},{"type":"text","text":" "},{"text":"When using encryption you still can access the unencrypted images in the image storage.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Of course, encrypted storages cannot be read without the proper encrypter being set here."},{"text":" ","type":"text"},{"type":"text","text":"You are responsible for migrating image storages."}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"text":"If you wish to use the ScanbotSDK RTU-UI-wide encryption setup your encrypter before using any of the ScanbotSDK RTU-UI API.","type":"text"}]}],"style":"important","type":"aside","name":"Important"},{"inlineContent":[{"text":"A good place to configure it, is your ","type":"text"},{"code":"AppDelegate","type":"codeVoice"},{"text":"’s entry point, right where the license is set.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Once ScanbotSDK RTU-UI API is used the storages are created and any change to the default encrypter is of no effect."}],"type":"paragraph"},{"name":"Note","type":"aside","style":"note","content":[{"inlineContent":[{"text":"For standard components, prefixed with SBSDK (without UI) the default encrypter has no effect, since there is","type":"text"},{"type":"text","text":" "},{"type":"text","text":"no image storage by default. You can, of course, create instances of "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage","isActive":true,"type":"reference"},{"type":"text","text":" "},{"type":"text","text":"and "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage","type":"reference"},{"type":"text","text":" and initialize them with an encrypter of your choice."}],"type":"paragraph"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotui\/defaultimagestoreencrypter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotui\/defaultimagestoreencrypter"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotUI"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotUI\/defaultImageStoreEncrypter","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotUI":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/scanbotui","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ScanbotUI","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotUI","type":"topic","title":"ScanbotUI","navigatorTitle":[{"text":"ScanbotUI","kind":"identifier"}],"abstract":[{"type":"text","text":"Helper class to configure the properties of the ScanbotSDK RTU-UI (SBSDKUI) components."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage":{"navigatorTitle":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage","title":"SBSDKKeyedImageStorage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"abstract":[{"type":"text","text":"A simple thread-safe multiple-reader-single-writer key-value fashioned disk image cache class."},{"text":" ","type":"text"},{"type":"text","text":"Manages images in a dictionary-like fashion."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCrypting":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecrypting","navigatorTitle":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting","abstract":[{"text":"Protocol for implementing encryption and decryption of (streamed) data.","type":"text"}],"kind":"symbol","title":"SBSDKStorageCrypting","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotUI/defaultImageStoreEncrypter":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/scanbotui\/defaultimagestoreencrypter","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultImageStoreEncrypter"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotUI\/defaultImageStoreEncrypter","title":"defaultImageStoreEncrypter","type":"topic","navigatorTitle":[{"text":"defaultImageStoreEncrypter","kind":"identifier"}],"abstract":[{"type":"text","text":"The SBSDKUI-component-wide encrypter for storing image data to disk. Defaults to "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKIndexedImageStorage":{"abstract":[{"type":"text","text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class."},{"type":"text","text":" "},{"text":"Manages images in an array-like fashion.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"title":"SBSDKIndexedImageStorage","navigatorTitle":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAESEncrypter":{"type":"topic","kind":"symbol","title":"SBSDKAESEncrypter","navigatorTitle":[{"kind":"identifier","text":"SBSDKAESEncrypter"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESEncrypter","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaesencrypter","abstract":[{"text":"ScanbotSDK’s default data encrypter. Provides AES128 and AES 256 encryption to your data.","type":"text"},{"type":"text","text":" "},{"text":"All data is encrypted and decrypted with the same key.","type":"text"},{"text":" ","type":"text"},{"text":"The context being passed to the encrypt\/decrypt methods is ignored.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKAESEncrypter"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","value":"defaultImageStoreEncrypter","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"defaultImageStoreEncrypter","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","text":"id<SBSDKStorageCrypting>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"defaultImageStoreEncrypter","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotUI\/title","op":"replace","value":"ScanbotUI"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotUI\/fragments","value":[{"kind":"identifier","text":"ScanbotUI"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotUI\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ScanbotUI"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage\/title","value":"SBSDKKeyedImageStorage","op":"replace"},{"value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage\/fragments"},{"value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/title","value":"SBSDKStorageCrypting"},{"value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}]},{"value":"defaultImageStoreEncrypter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotUI~1defaultImageStoreEncrypter\/title"},{"value":[{"kind":"identifier","text":"defaultImageStoreEncrypter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotUI~1defaultImageStoreEncrypter\/fragments"},{"value":"SBSDKIndexedImageStorage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/title"},{"value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/navigatorTitle","value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}]},{"value":"SBSDKAESEncrypter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESEncrypter\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESEncrypter\/fragments","value":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESEncrypter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAESEncrypter"}]}]}]}