{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration\/detailsSectionHeaderTextColor"},"abstract":[{"type":"text","text":"The text color for section headers on the details screen."}],"metadata":{"role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerUIConfiguration(py)detailsSectionHeaderTextColor","roleHeading":"Instance Property","title":"detailsSectionHeaderTextColor","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"detailsSectionHeaderTextColor"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"detailsSectionHeaderTextColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detailsSectionHeaderTextColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration\/detailssectionheadertextcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration\/detailssectionheadertextcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerUIConfiguration/detailsSectionHeaderTextColor":{"title":"detailsSectionHeaderTextColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"detailsSectionHeaderTextColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"detailsSectionHeaderTextColor","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The text color for section headers on the details screen."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration\/detailsSectionHeaderTextColor","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration\/detailssectionheadertextcolor","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerUIConfiguration":{"title":"SBSDKUIGenericDocumentRecognizerUIConfiguration","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerUIConfiguration"}],"abstract":[{"type":"text","text":"The configuration for the user interface of the RTU-UI generic document recognizer screens."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration","navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerUIConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"detailsSectionHeaderTextColor"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"detailsSectionHeaderTextColor"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detailsSectionHeaderTextColor"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"detailsSectionHeaderTextColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration~1detailsSectionHeaderTextColor\/title"},{"value":[{"kind":"identifier","text":"detailsSectionHeaderTextColor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration~1detailsSectionHeaderTextColor\/fragments","op":"replace"},{"value":"SBSDKUIGenericDocumentRecognizerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerUIConfiguration"}],"op":"replace"}]}]}