{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"fieldConfidenceLowColor"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Instance Property","title":"fieldConfidenceLowColor","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerUIConfiguration(py)fieldConfidenceLowColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fieldConfidenceLowColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration\/fieldConfidenceLowColor"},"abstract":[{"text":"The confidence value label background color in the details screen, when the field confidence level is low.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration\/fieldconfidencelowcolor"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration\/fieldconfidencelowcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fieldConfidenceLowColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerUIConfiguration":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIGenericDocumentRecognizerUIConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration","title":"SBSDKUIGenericDocumentRecognizerUIConfiguration","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration","abstract":[{"type":"text","text":"The configuration for the user interface of the RTU-UI generic document recognizer screens."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerUIConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerUIConfiguration/fieldConfidenceLowColor":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"fieldConfidenceLowColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration\/fieldConfidenceLowColor","title":"fieldConfidenceLowColor","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration\/fieldconfidencelowcolor","abstract":[{"text":"The confidence value label background color in the details screen, when the field confidence level is low.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"fieldConfidenceLowColor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"fieldConfidenceLowColor","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"fieldConfidenceLowColor","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" * ","kind":"text"},{"text":"fieldConfidenceLowColor","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUIGenericDocumentRecognizerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUIGenericDocumentRecognizerUIConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration~1fieldConfidenceLowColor\/title","value":"fieldConfidenceLowColor","op":"replace"},{"value":[{"text":"fieldConfidenceLowColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration~1fieldConfidenceLowColor\/fragments"}]}]}