{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldsCountTextColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration\/fieldsCountTextColor","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration\/fieldscounttextcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration\/fieldscounttextcolor"]}],"metadata":{"role":"symbol","title":"fieldsCountTextColor","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fieldsCountTextColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"fieldsCountTextColor","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerUIConfiguration(py)fieldsCountTextColor","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property"},"kind":"symbol","abstract":[{"type":"text","text":"The text color of the fields count label."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerUIConfiguration/fieldsCountTextColor":{"title":"fieldsCountTextColor","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration\/fieldscounttextcolor","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration\/fieldsCountTextColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fieldsCountTextColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"fieldsCountTextColor","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The text color of the fields count label."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerUIConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerUIConfiguration"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerUIConfiguration"}],"abstract":[{"text":"The configuration for the user interface of the RTU-UI generic document recognizer screens.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration","title":"SBSDKUIGenericDocumentRecognizerUIConfiguration","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"fieldsCountTextColor","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"fieldsCountTextColor","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":" * "},{"text":"fieldsCountTextColor","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"fieldsCountTextColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration~1fieldsCountTextColor\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration~1fieldsCountTextColor\/fragments","op":"replace","value":[{"text":"fieldsCountTextColor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration\/title","op":"replace","value":"SBSDKUIGenericDocumentRecognizerUIConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerUIConfiguration"}],"op":"replace"}]}]}