{"abstract":[{"text":"The foreground color of the top bar buttons on the scanning screen.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration\/topBarButtonsColor","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration"]]},"sections":[],"metadata":{"title":"topBarButtonsColor","navigatorTitle":[{"kind":"identifier","text":"topBarButtonsColor"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerUIConfiguration(py)topBarButtonsColor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarButtonsColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarButtonsColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration\/topbarbuttonscolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration\/topbarbuttonscolor"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerUIConfiguration/topBarButtonsColor":{"navigatorTitle":[{"text":"topBarButtonsColor","kind":"identifier"}],"abstract":[{"text":"The foreground color of the top bar buttons on the scanning screen.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration\/topbarbuttonscolor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration\/topBarButtonsColor","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarButtonsColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","type":"topic","title":"topBarButtonsColor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerUIConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerUIConfiguration"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerUIConfiguration"}],"abstract":[{"text":"The configuration for the user interface of the RTU-UI generic document recognizer screens.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration","title":"SBSDKUIGenericDocumentRecognizerUIConfiguration","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"topBarButtonsColor","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"topBarButtonsColor","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"topBarButtonsColor"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"topBarButtonsColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration~1topBarButtonsColor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"topBarButtonsColor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration~1topBarButtonsColor\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration\/title","value":"SBSDKUIGenericDocumentRecognizerUIConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerUIConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration\/fragments"}]}]}