{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKCameraSession","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCameraSession"}],"navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s8CopyableP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSession","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"kind":"symbol","topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/init(feature:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/init(feature:device:)"],"generated":true},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/captureSession","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/device","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/exposureSettings","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isCameraAdjusting","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isCapturingStillImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isFocusLockEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isFrontCameraUsed","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isMirrored","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isScanningPaused","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isSessionRunning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isTorchLightAvailable","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isTorchLightEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isZoomAvailable","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isZooming","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/keepAliveTimeout","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/maxOpticalZoom","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/maxZoom","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/minZoom","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/photoQualityPrioritization","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/previewLayer","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/updateTorchlightBlock","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/updateZoomBlock","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoContentMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoFrameResolution","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoOrientation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoResolution","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/zoomValue"],"title":"Instance Properties","anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/addSessionObserver(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/beginFocusLock(at:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/captureStillImage(completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/endFocusLock()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/freezeSession()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/observeValue(forKeyPath:of:change:context:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/pauseScanning()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/removeSessionObserver(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/resetZoom(animated:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/resumeScanning()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/setPreviewLayerVisible(_:animated:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/setZoom(_:animated:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/start()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/stop(keepAlive:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/unfreezeSession()"],"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasession"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasession"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/isFrontCameraUsed":{"title":"isFrontCameraUsed","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/isfrontcameraused","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isFrontCameraUsed","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFrontCameraUsed"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isFrontCameraUsed","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"True"},{"text":", if the front side camera is used, ","type":"text"},{"type":"codeVoice","code":"False"},{"text":" otherwise. Readonly.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/videoResolution":{"abstract":[{"type":"text","text":"Returns the video resolution of the current video output. Orientation is taken into account."},{"type":"text","text":" "},{"text":"Returns CGSizeZero, if the capture session is not running.","type":"text"}],"role":"symbol","type":"topic","title":"videoResolution","navigatorTitle":[{"text":"videoResolution","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoResolution","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/videoresolution","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoResolution","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/init(feature:)":{"title":"init(feature:)","type":"topic","abstract":[{"text":"The designated initializer of the class. Does not start the capture session.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/init(feature:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"feature","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKFeature","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKFeature"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/init(feature:)","navigatorTitle":[{"text":"initWithFeature:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/pauseScanning()":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/pauseScanning()","navigatorTitle":[{"text":"pauseScanning","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pauseScanning"},{"text":"()","kind":"text"}],"kind":"symbol","title":"pauseScanning()","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/pausescanning()","abstract":[{"text":"Pauses the delivery of frames to the delegate.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/minZoom":{"title":"minZoom","type":"topic","abstract":[{"text":"The camera devices minimum zoom factor. Readonly.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/minZoom","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minZoom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/minzoom","navigatorTitle":[{"kind":"identifier","text":"minZoom"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/freezeSession()":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/freezeSession()","navigatorTitle":[{"text":"freezeSession","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"freezeSession","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","title":"freezeSession()","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/freezesession()","abstract":[{"type":"text","text":"Freezes the camera session."}],"type":"topic"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/maxOpticalZoom":{"title":"maxOpticalZoom","type":"topic","abstract":[{"type":"text","text":"The camera devices maximum optical zoom factor. Readonly."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/maxOpticalZoom","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"maxOpticalZoom","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/maxopticalzoom","navigatorTitle":[{"text":"maxOpticalZoom","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/isFocusLockEnabled":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isFocusLockEnabled","navigatorTitle":[{"text":"isFocusLockEnabled","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFocusLockEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","title":"isFocusLockEnabled","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/isfocuslockenabled","abstract":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"True"},{"text":", if the cameras focus is locked, ","type":"text"},{"type":"codeVoice","code":"False"},{"text":" otherwise. Readonly.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/init(feature:device:)":{"title":"init(feature:device:)","type":"topic","abstract":[{"text":"Convenience initializer of the class. Does not start the capture session.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/init(feature:device:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"feature","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKFeature","text":"SBSDKFeature","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"device","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCameraDevice","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/init(feature:device:)","navigatorTitle":[{"kind":"identifier","text":"initWithFeature:device:"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/isCameraAdjusting":{"title":"isCameraAdjusting","type":"topic","abstract":[{"type":"text","text":"Returns "},{"code":"True","type":"codeVoice"},{"type":"text","text":", if the camera is currently adjusting autofocus, exposure or white balance,"},{"type":"text","text":" "},{"text":"false otherwise. Readonly.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isCameraAdjusting","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isCameraAdjusting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/iscameraadjusting","navigatorTitle":[{"text":"isCameraAdjusting","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/start()":{"navigatorTitle":[{"kind":"identifier","text":"startSession"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/start()","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/start()","kind":"symbol","abstract":[{"type":"text","text":"Starts the camera capture session asynchronously."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}],"role":"symbol","title":"start()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoContentMode/fillIn":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"fillIn","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode\/fillIn","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoContentModeFillIn"}],"abstract":[{"type":"text","text":"The video layers content is filled into the video layer."},{"text":" ","type":"text"},{"text":"No visible borders. Video may be cropped to the visible screen area.","type":"text"}],"title":"SBSDKVideoContentMode.fillIn","url":"\/documentation\/scanbotsdk\/sbsdkvideocontentmode\/fillin"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations","kind":"article","title":"AVCaptureVideoDataOutputSampleBufferDelegate Implementations","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/avcapturevideodataoutputsamplebufferdelegate-implementations","abstract":[],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/previewLayer":{"title":"previewLayer","type":"topic","abstract":[{"type":"text","text":"The preview layer that the camera device uses to output the current video frames."},{"text":" ","type":"text"},{"type":"text","text":"Can be added to any superlayer."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/previewLayer","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"previewLayer"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","kind":"typeIdentifier","text":"AVCaptureVideoPreviewLayer"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/previewlayer","navigatorTitle":[{"kind":"identifier","text":"previewLayer"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/isCapturingStillImage":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isCapturingStillImage","navigatorTitle":[{"kind":"identifier","text":"isCapturingStillImage"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCapturingStillImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","title":"isCapturingStillImage","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/iscapturingstillimage","abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"True"},{"text":" if the camera is currently in the process of taking a still image, ","type":"text"},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/keepAliveTimeout":{"title":"keepAliveTimeout","type":"topic","abstract":[{"type":"text","text":"The time the session is kept alive after stopping it."},{"type":"text","text":" "},{"text":"If the session is stopped and then re-started while it is still alive it will be much faster ready than when being completely restarted.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The default value is 1 second."},{"text":" ","type":"text"},{"type":"text","text":"Negative values will result in a fatal error. Values close to 0 may lead to issues when starting and stopping the session multiple times quickly."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/keepAliveTimeout","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keepAliveTimeout","kind":"identifier"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/keepalivetimeout","navigatorTitle":[{"text":"keepAliveTimeout","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/resumeScanning()":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/resumescanning()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resumeScanning"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"resumeScanning","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/resumeScanning()","abstract":[{"type":"text","text":"Resumes the delivery of frames to the delegate."}],"title":"resumeScanning()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/device":{"title":"device","type":"topic","abstract":[{"type":"text","text":"The camera device to be used."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/device","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"device","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCameraDevice","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/device","navigatorTitle":[{"text":"device","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/observeValue(forKeyPath:of:change:context:)":{"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/observevalue(forkeypath:of:change:context:)","title":"observeValue(forKeyPath:of:change:context:)","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"observeValueForKeyPath:ofObject:change:context:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/observeValue(forKeyPath:of:change:context:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"observeValue","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forKeyPath"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?, "},{"text":"change","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"NSKeyValueChangeKey","preciseIdentifier":"c:@T@NSKeyValueChangeKey"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"context"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sv","kind":"typeIdentifier","text":"UnsafeMutableRawPointer"},{"kind":"text","text":"?)"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/updateTorchlightBlock":{"title":"updateTorchlightBlock","type":"topic","abstract":[{"type":"text","text":"A block being executed when the torch light status changes (mode or availability)."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/updateTorchlightBlock","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateTorchlightBlock"},{"kind":"text","text":": (() -> ())?"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/updatetorchlightblock","navigatorTitle":[{"text":"updateTorchlightBlock","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/captureStillImage(completion:)":{"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/capturestillimage(completion:)","title":"captureStillImage(completion:)","type":"topic","abstract":[{"text":"Captures a still image asynchronously and passes the image data or an error to the completion handler.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"captureStillImageWithCompletionHandler:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/captureStillImage(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"captureStillImage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> ())"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/stop(keepAlive:)":{"title":"stop(keepAlive:)","type":"topic","abstract":[{"type":"text","text":"Stops the camera capture session. Does nothing if the session is already stopped."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/stop(keepAlive:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stop"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"keepAlive"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/stop(keepalive:)","navigatorTitle":[{"kind":"identifier","text":"stopSession:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/isTorchLightEnabled":{"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/istorchlightenabled","title":"isTorchLightEnabled","type":"topic","abstract":[{"type":"text","text":"Turns the torch light on or off."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isTorchLightEnabled"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isTorchLightEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isTorchLightEnabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/isZoomAvailable":{"title":"isZoomAvailable","type":"topic","abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"True"},{"text":", if the camera zoom is available, ","type":"text"},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise. Readonly."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isZoomAvailable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isZoomAvailable","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/iszoomavailable","navigatorTitle":[{"text":"isZoomAvailable","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/captureSession":{"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/capturesession","title":"captureSession","type":"topic","abstract":[{"text":"The AVCaptureSession object.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"captureSession","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/captureSession","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"captureSession","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureSession","preciseIdentifier":"c:objc(cs)AVCaptureSession"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/exposureSettings":{"title":"exposureSettings","type":"topic","abstract":[{"type":"text","text":"Returns the current cameras exposure settings."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/exposureSettings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"exposureSettings","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraExposureSettings","kind":"typeIdentifier","text":"SBSDKCameraExposureSettings"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/exposuresettings","navigatorTitle":[{"text":"exposureSettings","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/isTorchLightAvailable":{"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/istorchlightavailable","title":"isTorchLightAvailable","type":"topic","abstract":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":" if the camera device has a torch light and the torch light is available, "},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise."}],"role":"symbol","navigatorTitle":[{"text":"isTorchLightAvailable","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isTorchLightAvailable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTorchLightAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/unfreezeSession()":{"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/unfreezesession()","title":"unfreezeSession()","type":"topic","abstract":[{"type":"text","text":"Unfreezes the camera session."}],"role":"symbol","navigatorTitle":[{"text":"unfreezeSession","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/unfreezeSession()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unfreezeSession"},{"kind":"text","text":"()"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/beginFocusLock(at:)":{"title":"beginFocusLock(at:)","type":"topic","abstract":[{"type":"text","text":"Disables auto-focus and locks the lens at the specified lens position."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/beginFocusLock(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"beginFocusLock"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"at"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/beginfocuslock(at:)","navigatorTitle":[{"text":"beginFocusLockAtLensPosition:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/videoContentMode":{"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/videocontentmode","title":"videoContentMode","type":"topic","abstract":[{"text":"The content mode of the video preview layer: fit-in or fill-in. Defaults to ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode\/fillIn","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"videoContentMode"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoContentMode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoContentMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoContentMode","kind":"typeIdentifier","text":"SBSDKVideoContentMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/isMirrored":{"title":"isMirrored","type":"topic","abstract":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":" if the camera session mirrors its video, "},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isMirrored","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isMirrored","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/ismirrored","navigatorTitle":[{"kind":"identifier","text":"isMirrored"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/isSessionRunning":{"role":"symbol","abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"True"},{"type":"text","text":" if the camera session is running, "},{"type":"codeVoice","code":"False"},{"text":" otherwise. Readonly.","type":"text"}],"title":"isSessionRunning","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isSessionRunning","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isSessionRunning","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/issessionrunning","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isSessionRunning"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/isScanningPaused":{"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/isscanningpaused","title":"isScanningPaused","type":"topic","abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"True"},{"text":", if the live scanning is paused, ","type":"text"},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise. Readonly."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isScanningPaused"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isScanningPaused","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isScanningPaused","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization/balanced":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization\/balanced","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Balances capturing speed and image quality equally. This is the default value."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationBalanced"}],"title":"SBSDKCapturePhotoQualityPrioritization.balanced","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"balanced"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/isZooming":{"title":"isZooming","type":"topic","abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"True"},{"type":"text","text":", if the camera currently is zooming, "},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise. Readonly."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isZooming","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isZooming","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/iszooming","navigatorTitle":[{"kind":"identifier","text":"isZooming"}]},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/photoQualityPrioritization":{"title":"photoQualityPrioritization","type":"topic","abstract":[{"type":"text","text":"The prioritization of still image quality and capturing speed."},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/photoQualityPrioritization","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"photoQualityPrioritization","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCapturePhotoQualityPrioritization","text":"SBSDKCapturePhotoQualityPrioritization"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/photoqualityprioritization","navigatorTitle":[{"text":"photoQualityPrioritization","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/videoFrameResolution":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/videoframeresolution","title":"videoFrameResolution","role":"symbol","navigatorTitle":[{"text":"videoFrameResolution","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"videoFrameResolution","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoFrameResolution","text":"SBSDKVideoFrameResolution"}],"abstract":[{"type":"text","text":"Sets or gets the current video frame resolution."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoFrameResolution"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/resetZoom(animated:)":{"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/resetzoom(animated:)","title":"resetZoom(animated:)","type":"topic","abstract":[{"type":"text","text":"Resets the zoom factor to the minimum zoom value."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"resetZoomAnimated:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/resetZoom(animated:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resetZoom","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/setZoom(_:animated:)":{"title":"setZoom(_:animated:)","type":"topic","abstract":[{"text":"Sets the camera devices current zoom factor.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the new value exceeds the minimum or maximum value for zooming it is clamped."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/setZoom(_:animated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setZoom","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/setzoom(_:animated:)","navigatorTitle":[{"kind":"identifier","text":"setZoomValue:animated:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/removeSessionObserver(_:)":{"navigatorTitle":[{"text":"removeSessionObserver:","kind":"identifier"}],"role":"symbol","title":"removeSessionObserver(_:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/removeSessionObserver(_:)","abstract":[{"type":"text","text":"Removes an observer from the list of observers."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/removesessionobserver(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeSessionObserver"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKCameraSessionObserving","kind":"typeIdentifier","text":"SBSDKCameraSessionObserving"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/loggingContext":{"type":"topic","title":"loggingContext","role":"symbol","fragments":[{"text":"loggingContext","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/loggingContext","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/loggingcontext"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/updateZoomBlock":{"title":"updateZoomBlock","type":"topic","abstract":[{"type":"text","text":"A block being executed when the zoom factor has changed. The new zoom factor is provided as parameter."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/updateZoomBlock","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateZoomBlock"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> ())?"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/updatezoomblock","navigatorTitle":[{"text":"updateZoomBlock","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/videoOrientation":{"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/videoorientation","title":"videoOrientation","type":"topic","abstract":[{"type":"text","text":"Sets or gets the current video orientation."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"videoOrientation"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoOrientation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"videoOrientation","kind":"identifier"},{"kind":"text","text":": "},{"text":"AVCaptureVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureVideoOrientation"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/endFocusLock()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"endFocusLock"},{"kind":"text","text":"()"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/endfocuslock()","kind":"symbol","title":"endFocusLock()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"endFocusLock"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/endFocusLock()","abstract":[{"type":"text","text":"Ends the focus lock and returns to standard continous auto-focus."}]},"doc://net.doo.ScanbotSDK/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate","title":"AVCaptureVideoDataOutputSampleBufferDelegate","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSession"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession","title":"SBSDKCameraSession","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSession"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","type":"topic","abstract":[{"text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/maxZoom":{"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/maxzoom","title":"maxZoom","type":"topic","abstract":[{"text":"The camera devices maximum zoom factor. Readonly.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"maxZoom","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/maxZoom","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxZoom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/zoomValue":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"zoomValue"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"zoomValue","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/zoomValue","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/zoomvalue","navigatorTitle":[{"kind":"identifier","text":"zoomValue"}],"abstract":[{"type":"text","text":"Sets or gets the camera devices current zoom factor. Zooming is done without animation."},{"type":"text","text":" "},{"text":"If the new value exceeds the minimum or maximum value for zooming it is clamped.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/addSessionObserver(_:)":{"title":"addSessionObserver(_:)","type":"topic","abstract":[{"type":"text","text":"Adds a new observer to the list of observers."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/addSessionObserver(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addSessionObserver","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKCameraSessionObserving","text":"SBSDKCameraSessionObserving","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/addsessionobserver(_:)","navigatorTitle":[{"kind":"identifier","text":"addSessionObserver:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/setPreviewLayerVisible(_:animated:)":{"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/setpreviewlayervisible(_:animated:)","title":"setPreviewLayerVisible(_:animated:)","type":"topic","abstract":[{"type":"text","text":"Toggles the visibility of the camera preview."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setPreviewLayerVisible:animated:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/setPreviewLayerVisible(_:animated:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPreviewLayerVisible"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/videoDelegate":{"title":"videoDelegate","type":"topic","abstract":[{"text":"The delegate object for camera output.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Its receives the video frames and does still image captures."},{"type":"text","text":" "},{"type":"text","text":"Delegates can implement all functions from "},{"type":"codeVoice","code":"AVCaptureVideoDataOutputSampleBufferDelegate"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoDelegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"videoDelegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCameraSessionDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKCameraSessionDelegate"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/videodelegate","navigatorTitle":[{"text":"videoDelegate","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s8CopyableP","title":"Swift.Copyable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKCameraSession"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/captureSession","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/device","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/exposureSettings","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isCameraAdjusting","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isCapturingStillImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isFocusLockEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isFrontCameraUsed","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isMirrored","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isScanningPaused","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isSessionRunning","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isTorchLightAvailable","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isTorchLightEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isZoomAvailable","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isZooming","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/keepAliveTimeout","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/loggingContext","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/maxOpticalZoom","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/maxZoom","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/minZoom","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/photoQualityPrioritization","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/previewLayer","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/updateTorchlightBlock","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/updateZoomBlock","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoContentMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoFrameResolution","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoOrientation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoResolution","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/zoomValue"],"generated":true},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/addSessionObserver(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/beginFocusLock(at:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/captureStillImage(completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/endFocusLock()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/freezeSession()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/init(feature:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/init(feature:device:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/observeValue(forKeyPath:of:change:context:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/pauseScanning()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/removeSessionObserver(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/resetZoom(animated:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/resumeScanning()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/setPreviewLayerVisible(_:animated:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/setZoom(_:animated:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/start()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/stop(keepAlive:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/unfreezeSession()"],"anchor":"Instance-Methods"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations"],"title":"Default Implementations"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate"],"kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKCameraSession","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isFrontCameraUsed\/title","value":"isFrontCameraUsed"},{"value":[{"text":"isFrontCameraUsed","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isFrontCameraUsed\/fragments","op":"replace"},{"value":"videoResolution","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1videoResolution\/title","op":"replace"},{"value":[{"kind":"identifier","text":"videoResolution"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1videoResolution\/fragments","op":"replace"},{"value":"initWithFeature:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1init(feature:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFeature:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1init(feature:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1pauseScanning()\/title","op":"replace","value":"pauseScanning"},{"value":[{"text":"- ","kind":"text"},{"text":"pauseScanning","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1pauseScanning()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1minZoom\/title","value":"minZoom"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1minZoom\/fragments","value":[{"kind":"identifier","text":"minZoom"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1freezeSession()\/title","value":"freezeSession"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"freezeSession"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1freezeSession()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1maxOpticalZoom\/title","value":"maxOpticalZoom","op":"replace"},{"op":"replace","value":[{"text":"maxOpticalZoom","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1maxOpticalZoom\/fragments"},{"value":"isFocusLockEnabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isFocusLockEnabled\/title"},{"value":[{"text":"isFocusLockEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isFocusLockEnabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1init(feature:device:)\/title","value":"initWithFeature:device:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1init(feature:device:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithFeature:device:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isCameraAdjusting\/title","value":"isCameraAdjusting"},{"op":"replace","value":[{"text":"isCameraAdjusting","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isCameraAdjusting\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1start()\/title","value":"startSession"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1start()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"startSession","kind":"identifier"}]},{"value":"SBSDKVideoContentModeFillIn","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode~1fillIn\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKVideoContentModeFillIn","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode~1fillIn\/fragments"},{"op":"replace","value":"previewLayer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1previewLayer\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1previewLayer\/fragments","value":[{"kind":"identifier","text":"previewLayer"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isCapturingStillImage\/title","value":"isCapturingStillImage","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"isCapturingStillImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isCapturingStillImage\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1keepAliveTimeout\/title","value":"keepAliveTimeout","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1keepAliveTimeout\/fragments","value":[{"text":"keepAliveTimeout","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1resumeScanning()\/title","value":"resumeScanning"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1resumeScanning()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resumeScanning"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1device\/title","value":"device","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1device\/fragments","value":[{"kind":"identifier","text":"device"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1observeValue(forKeyPath:of:change:context:)\/title","value":"observeValueForKeyPath:ofObject:change:context:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1observeValue(forKeyPath:of:change:context:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeValueForKeyPath:ofObject:change:context:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1updateTorchlightBlock\/title","op":"replace","value":"updateTorchlightBlock"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1updateTorchlightBlock\/fragments","value":[{"kind":"identifier","text":"updateTorchlightBlock"}]},{"value":"captureStillImageWithCompletionHandler:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1captureStillImage(completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1captureStillImage(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"captureStillImageWithCompletionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1stop(keepAlive:)\/title","value":"stopSession:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stopSession:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1stop(keepAlive:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isTorchLightEnabled\/title","op":"replace","value":"isTorchLightEnabled"},{"op":"replace","value":[{"text":"isTorchLightEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isTorchLightEnabled\/fragments"},{"value":"isZoomAvailable","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isZoomAvailable\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isZoomAvailable"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isZoomAvailable\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1captureSession\/title","op":"replace","value":"captureSession"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1captureSession\/fragments","value":[{"text":"captureSession","kind":"identifier"}]},{"value":"exposureSettings","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1exposureSettings\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1exposureSettings\/fragments","value":[{"text":"exposureSettings","kind":"identifier"}]},{"value":"isTorchLightAvailable","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isTorchLightAvailable\/title"},{"op":"replace","value":[{"text":"isTorchLightAvailable","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isTorchLightAvailable\/fragments"},{"op":"replace","value":"unfreezeSession","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1unfreezeSession()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"unfreezeSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1unfreezeSession()\/fragments"},{"value":"beginFocusLockAtLensPosition:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1beginFocusLock(at:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1beginFocusLock(at:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"beginFocusLockAtLensPosition:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1videoContentMode\/title","value":"videoContentMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1videoContentMode\/fragments","value":[{"text":"videoContentMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isMirrored\/title","value":"isMirrored","op":"replace"},{"value":[{"text":"isMirrored","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isMirrored\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isSessionRunning\/title","op":"replace","value":"isSessionRunning"},{"value":[{"text":"isSessionRunning","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isSessionRunning\/fragments"},{"value":"isScanningPaused","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isScanningPaused\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isScanningPaused\/fragments","value":[{"kind":"identifier","text":"isScanningPaused"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization~1balanced\/title","value":"SBSDKCapturePhotoQualityPrioritizationBalanced"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization~1balanced\/fragments","value":[{"text":"SBSDKCapturePhotoQualityPrioritizationBalanced","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isZooming\/title","value":"isZooming"},{"value":[{"kind":"identifier","text":"isZooming"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isZooming\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1photoQualityPrioritization\/title","op":"replace","value":"photoQualityPrioritization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1photoQualityPrioritization\/fragments","value":[{"kind":"identifier","text":"photoQualityPrioritization"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1videoFrameResolution\/title","value":"videoFrameResolution","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1videoFrameResolution\/fragments","op":"replace","value":[{"kind":"identifier","text":"videoFrameResolution"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1resetZoom(animated:)\/title","value":"resetZoomAnimated:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1resetZoom(animated:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"resetZoomAnimated:","kind":"identifier"}]},{"value":"setZoomValue:animated:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1setZoom(_:animated:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setZoomValue:animated:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1setZoom(_:animated:)\/fragments"},{"value":"removeSessionObserver:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1removeSessionObserver(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1removeSessionObserver(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeSessionObserver:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1updateZoomBlock\/title","value":"updateZoomBlock"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1updateZoomBlock\/fragments","value":[{"kind":"identifier","text":"updateZoomBlock"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1videoOrientation\/title","op":"replace","value":"videoOrientation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1videoOrientation\/fragments","value":[{"kind":"identifier","text":"videoOrientation"}],"op":"replace"},{"value":"endFocusLock","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1endFocusLock()\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1endFocusLock()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"endFocusLock"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/title","value":"SBSDKCameraSession","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraSession"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/navigatorTitle","value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"op":"replace"},{"value":"maxZoom","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1maxZoom\/title"},{"value":[{"kind":"identifier","text":"maxZoom"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1maxZoom\/fragments","op":"replace"},{"value":"zoomValue","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1zoomValue\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1zoomValue\/fragments","op":"replace","value":[{"text":"zoomValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1addSessionObserver(_:)\/title","op":"replace","value":"addSessionObserver:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1addSessionObserver(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"addSessionObserver:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1setPreviewLayerVisible(_:animated:)\/title","value":"setPreviewLayerVisible:animated:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1setPreviewLayerVisible(_:animated:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setPreviewLayerVisible:animated:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1videoDelegate\/title","value":"videoDelegate","op":"replace"},{"value":[{"text":"videoDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1videoDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}