{"abstract":[{"text":"Page direction.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagedirection"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpagedirection"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/auto","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/landscape","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/portrait"],"generated":true},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKPageDirection) ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKPageDirection","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Enumeration","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageDirection","kind":"identifier"}],"role":"symbol","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageDirection"}],"title":"SBSDKPageDirection","externalID":"c:@M@ScanbotSDK@E@SBSDKPageDirection"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection"},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageDirection/auto":{"abstract":[{"text":"Decides based on image aspect ratio.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpagedirection\/auto","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"auto","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKPageDirectionAuto","kind":"identifier"}],"kind":"symbol","title":"SBSDKPageDirection.auto","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/auto"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageDirection/Equatable-Implementations":{"type":"topic","title":"Equatable Implementations","url":"\/documentation\/scanbotsdk\/sbsdkpagedirection\/equatable-implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/Equatable-Implementations","role":"collectionGroup","kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageDirection/landscape":{"abstract":[{"type":"text","text":"Landscape."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpagedirection\/landscape","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageDirectionLandscape"}],"kind":"symbol","title":"SBSDKPageDirection.landscape","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/landscape"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageDirection/portrait":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/portrait","url":"\/documentation\/scanbotsdk\/sbsdkpagedirection\/portrait","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKPageDirectionPortrait","kind":"identifier"}],"abstract":[{"text":"Portrait.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"portrait","kind":"identifier"}],"title":"SBSDKPageDirection.portrait"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageDirection/init(rawValue:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/init(rawValue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(rawValue:)","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkpagedirection\/init(rawvalue:)","role":"symbol"},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageDirection":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection","url":"\/documentation\/scanbotsdk\/sbsdkpagedirection","kind":"symbol","type":"topic","title":"SBSDKPageDirection","abstract":[{"text":"Page direction.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPageDirection"}],"navigatorTitle":[{"text":"SBSDKPageDirection","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageDirection/RawRepresentable-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpagedirection\/rawrepresentable-implementations","role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/RawRepresentable-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKPageDirection","op":"replace"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKPageDirection","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKPageDirection","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/auto","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/landscape","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/portrait"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"}]},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageDirection"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKPageDirectionAuto","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection~1auto\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection~1auto\/fragments","value":[{"text":"SBSDKPageDirectionAuto","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection~1landscape\/title","value":"SBSDKPageDirectionLandscape"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection~1landscape\/fragments","op":"replace","value":[{"text":"SBSDKPageDirectionLandscape","kind":"identifier"}]},{"op":"replace","value":"SBSDKPageDirectionPortrait","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection~1portrait\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection~1portrait\/fragments","value":[{"kind":"identifier","text":"SBSDKPageDirectionPortrait"}],"op":"replace"},{"value":"SBSDKPageDirection","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection\/fragments","value":[{"text":"SBSDKPageDirection","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKPageDirection","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection\/navigatorTitle"}]}]}