{"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/automaticSelectionEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedPolygonColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedTextColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedTextContainerColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/overlayEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/overlayTextFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/polygonColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/textColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/textContainerColor"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration"},"sections":[],"abstract":[{"text":"The configuration object for the RTU-UI barcode tracking overlay.","type":"text"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodetrackingoverlayconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodetrackingoverlayconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"platforms":[],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeTrackingOverlayConfiguration","title":"SBSDKUIBarcodeTrackingOverlayConfiguration","modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}],"role":"symbol","roleHeading":"Class"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/textColor":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"navigatorTitle":[{"text":"textColor","kind":"identifier"}],"title":"textColor","kind":"symbol","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodetrackingoverlayconfiguration\/textcolor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/textColor","abstract":[{"type":"text","text":"The text color for the results overlays."}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/polygonColor":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/polygonColor","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodetrackingoverlayconfiguration\/polygoncolor","abstract":[{"text":"The color for the results overlays polygons.","type":"text"}],"kind":"symbol","title":"polygonColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"polygonColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"polygonColor","kind":"identifier"}],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/overlayEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"overlayEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Displays an augmented reality view that draws the frames, content and type text of the found barcodes when it finds them.","type":"text"}],"title":"overlayEnabled","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/overlayEnabled","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodetrackingoverlayconfiguration\/overlayenabled","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"overlayEnabled","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","title":"init","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodetrackingoverlayconfiguration\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/init","abstract":[],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/textContainerColor":{"navigatorTitle":[{"text":"textContainerColor","kind":"identifier"}],"type":"topic","title":"textContainerColor","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodetrackingoverlayconfiguration\/textcontainercolor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"textContainerColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/textContainerColor","abstract":[{"type":"text","text":"The text background color for the results overlays."}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/overlayTextFormat":{"deprecated":true,"kind":"symbol","role":"symbol","title":"overlayTextFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/overlayTextFormat","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodetrackingoverlayconfiguration\/overlaytextformat","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"overlayTextFormat"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeOverlayFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeOverlayFormat"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"overlayTextFormat"}],"abstract":[{"text":"The text format for the results overlays.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/highlightedPolygonColor":{"navigatorTitle":[{"text":"highlightedPolygonColor","kind":"identifier"}],"type":"topic","title":"highlightedPolygonColor","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodetrackingoverlayconfiguration\/highlightedpolygoncolor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"highlightedPolygonColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedPolygonColor","abstract":[{"type":"text","text":"The color for the results overlays polygons."}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/highlightedTextContainerColor":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedTextContainerColor","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodetrackingoverlayconfiguration\/highlightedtextcontainercolor","abstract":[{"type":"text","text":"The text background color for the results overlays."}],"kind":"symbol","title":"highlightedTextContainerColor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"highlightedTextContainerColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","navigatorTitle":[{"text":"highlightedTextContainerColor","kind":"identifier"}],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/highlightedTextColor":{"navigatorTitle":[{"text":"highlightedTextColor","kind":"identifier"}],"type":"topic","title":"highlightedTextColor","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodetrackingoverlayconfiguration\/highlightedtextcolor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"highlightedTextColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedTextColor","abstract":[{"text":"The text color for the results overlays.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeTrackingOverlayConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"symbol","title":"SBSDKUIBarcodeTrackingOverlayConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodetrackingoverlayconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}],"abstract":[{"text":"The configuration object for the RTU-UI barcode tracking overlay.","type":"text"}],"deprecated":true,"type":"topic","navigatorTitle":[{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeTrackingOverlayConfiguration/automaticSelectionEnabled":{"deprecated":true,"kind":"symbol","abstract":[{"type":"text","text":"If enabled, newly scanned barcodes will be automatically selected."},{"text":" ","type":"text"},{"type":"text","text":"Otherwise the user has to tap on a barcode on the selection overlay to select it."},{"text":" ","type":"text"},{"text":"Has no effect with disabled overlay.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automaticSelectionEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodetrackingoverlayconfiguration\/automaticselectionenabled","navigatorTitle":[{"text":"automaticSelectionEnabled","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/automaticSelectionEnabled","role":"symbol","title":"automaticSelectionEnabled"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[],"op":"replace","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"SBSDKUIBarcodeTrackingOverlayConfiguration","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/automaticSelectionEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedPolygonColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedTextColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/highlightedTextContainerColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/overlayEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/overlayTextFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/polygonColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/textColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/textContainerColor"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration\/init"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1textColor\/title","op":"replace","value":"textColor"},{"value":[{"text":"textColor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1textColor\/fragments","op":"replace"},{"op":"replace","value":"polygonColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1polygonColor\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1polygonColor\/fragments","value":[{"text":"polygonColor","kind":"identifier"}]},{"value":"overlayEnabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1overlayEnabled\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1overlayEnabled\/fragments","op":"replace","value":[{"text":"overlayEnabled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1textContainerColor\/title","value":"textContainerColor"},{"value":[{"kind":"identifier","text":"textContainerColor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1textContainerColor\/fragments"},{"value":"overlayTextFormat","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1overlayTextFormat\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1overlayTextFormat\/fragments","value":[{"kind":"identifier","text":"overlayTextFormat"}]},{"value":"highlightedPolygonColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1highlightedPolygonColor\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1highlightedPolygonColor\/fragments","op":"replace","value":[{"text":"highlightedPolygonColor","kind":"identifier"}]},{"value":"highlightedTextContainerColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1highlightedTextContainerColor\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1highlightedTextContainerColor\/fragments","value":[{"text":"highlightedTextContainerColor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1highlightedTextColor\/title","value":"highlightedTextColor","op":"replace"},{"value":[{"text":"highlightedTextColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1highlightedTextColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration\/title","value":"SBSDKUIBarcodeTrackingOverlayConfiguration"},{"value":[{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration\/navigatorTitle"},{"value":"automaticSelectionEnabled","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1automaticSelectionEnabled\/title","op":"replace"},{"value":[{"text":"automaticSelectionEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration~1automaticSelectionEnabled\/fragments"}]}]}