{"abstract":[{"type":"text","text":"Languages"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelVCardLanguages","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","role":"symbol","title":"SBSDKBarcodeDocumentModelVCardLanguages","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardLanguages"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCardLanguages"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardlanguages"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardlanguages"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentModelVCardLanguages","kind":"identifier"}]}],"kind":"declarations"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardEntry"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardLanguages\/requiredDocumentType"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardLanguages"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCardLanguages/initWithGenericDocument:":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardLanguages\/initWithGenericDocument:","navigatorTitle":[{"kind":"identifier","text":"initWithGenericDocument:"}],"title":"initWithGenericDocument:","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardlanguages\/initwithgenericdocument:"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCardLanguages/requiredDocumentType":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardlanguages\/requireddocumenttype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardLanguages\/requiredDocumentType","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"The name of the wrapped document type.","type":"text"}],"role":"symbol","title":"requiredDocumentType","navigatorTitle":[{"kind":"identifier","text":"requiredDocumentType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCardLanguages":{"role":"symbol","title":"SBSDKBarcodeDocumentModelVCardLanguages","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelVCardLanguages","kind":"identifier"}],"type":"topic","abstract":[{"text":"Languages","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardLanguages"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardLanguages","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardlanguages"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCardEntry":{"type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelVCardEntry","kind":"identifier"}],"title":"SBSDKBarcodeDocumentModelVCardEntry","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardEntry"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardEntry","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardentry","abstract":[{"type":"text","text":"VCard Entry"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"SBSDKBarcodeDocumentModelVCardLanguages","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardLanguages"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardLanguages"}]},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardLanguages\/requiredDocumentType"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardLanguages\/initWithGenericDocument:"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardEntry"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelVCardLanguages","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelVCardEntry","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardEntry","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCardEntry"}]}],"kind":"declarations"}},{"value":"requiredDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardLanguages~1requiredDocumentType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardLanguages~1requiredDocumentType\/fragments","value":[{"text":"requiredDocumentType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardLanguages\/title","value":"SBSDKBarcodeDocumentModelVCardLanguages"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardLanguages\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardLanguages"}]},{"op":"replace","value":[{"text":"SBSDKBarcodeDocumentModelVCardLanguages","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardLanguages\/navigatorTitle"},{"op":"replace","value":"SBSDKBarcodeDocumentModelVCardEntry","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardEntry\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardEntry"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardEntry\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardEntry"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardEntry\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}