{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagesize"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpagesize"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageSize","kind":"identifier"}],"roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKPageSize","title":"SBSDKPageSize","navigatorTitle":[{"text":"SBSDKPageSize","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"Page size.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize"},"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/a3","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/a4","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/a5","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/b4","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/b5","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/comm10","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/custom","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/executive","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/legal","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/letter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/us4X6","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/us4X8","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/us5X7"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(SBSDKPageSize) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageSize"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/comm10":{"url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/comm10","role":"symbol","abstract":[{"text":"4.125 x 9.5 (inches)     297 x 684 (pixels) at 72 DPI.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"comm10","kind":"identifier"}],"title":"SBSDKPageSize.comm10","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSizeComm10"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/comm10","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/rawrepresentable-implementations","type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/RawRepresentable-Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/a5":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSizeA5"}],"type":"topic","title":"SBSDKPageSize.a5","url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/a5","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"a5","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/a5","abstract":[{"type":"text","text":"148 x 210 (mm)           419.528 x 595.276 (pixels) at 72 DPI."}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/legal":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSizeLegal"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/legal","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/legal","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"legal"}],"title":"SBSDKPageSize.legal","abstract":[{"text":"8.5 x 14 (inches)        612 x 1008 (pixels) at 72 DPI.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/init(rawValue:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/init(rawValue:)","url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/us4X8":{"role":"symbol","abstract":[{"type":"text","text":"4 x 8 (inches)           288 x 576 (pixels) at 72 DPI."}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"us4X8","kind":"identifier"}],"title":"SBSDKPageSize.us4X8","url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/us4x8","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/us4X8","type":"topic","navigatorTitle":[{"text":"SBSDKPageSizeUs4X8","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/a3":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/a3","type":"topic","abstract":[{"type":"text","text":"297 x 420 (mm)           841.89 x 1199.551 (pixels) at 72 DPI."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSizeA3"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"a3","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/a3","title":"SBSDKPageSize.a3","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/letter":{"title":"SBSDKPageSize.letter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/letter","abstract":[{"type":"text","text":"8.5 x 11 (inches)        612 x 792 (pixels) at 72 DPI."}],"navigatorTitle":[{"text":"SBSDKPageSizeLetter","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"letter","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/letter","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/us4X6":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/us4X6","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/us4x6","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"us4X6","kind":"identifier"}],"type":"topic","title":"SBSDKPageSize.us4X6","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSizeUs4X6"}],"abstract":[{"text":"4 x 6 (inches)           288 x 432 (pixels) at 72 DPI.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/executive":{"type":"topic","role":"symbol","title":"SBSDKPageSize.executive","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/executive","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"executive"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/executive","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSizeExecutive"}],"abstract":[{"type":"text","text":"7.25 x 10.5 (inches)     522 x 756 (pixels) at 72 DPI."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize":{"abstract":[{"type":"text","text":"Page size."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpagesize","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSize"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPageSize"}],"title":"SBSDKPageSize","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/us5X7":{"title":"SBSDKPageSize.us5X7","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/us5X7","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"us5X7"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/us5x7","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKPageSizeUs5X7","kind":"identifier"}],"abstract":[{"text":"5 x 7 (inches)           360 x 504 (pixels) at 72 DPI.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/b5":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/b5","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSizeB5"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/b5","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"b5","kind":"identifier"}],"title":"SBSDKPageSize.b5","type":"topic","abstract":[{"text":"176 x 250 (mm)           498.898 x 708.661 (pixels) at 72 DPI.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/b4":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSizeB4"}],"type":"topic","title":"SBSDKPageSize.b4","url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/b4","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"b4"}],"abstract":[{"type":"text","text":"250 x 353 (mm)           708.661 x 1000.63 (pixels) at 72 DPI."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/b4","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/custom":{"url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/custom","title":"SBSDKPageSize.custom","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"}],"abstract":[{"text":"Physical size will be calculated from the image dimensions and the ","type":"text"},{"code":"dpi","type":"codeVoice"},{"type":"text","text":" parameter."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/custom","navigatorTitle":[{"text":"SBSDKPageSizeCustom","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","kind":"article","type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/Equatable-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/equatable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/a4":{"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"a4"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/a4","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/a4","title":"SBSDKPageSize.a4","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSizeA4"}],"abstract":[{"text":"210 x 297 (mm)           595.276 x 841.89 (pixels) at 72 DPI.","type":"text"}]},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKPageSize"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKPageSize"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SBSDKPageSize","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/a3","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/a4","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/a5","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/b4","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/b5","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/comm10","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/custom","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/executive","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/legal","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/letter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/us4X6","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/us4X8","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/us5X7"],"title":"Enumeration Cases"}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1comm10\/title","op":"replace","value":"SBSDKPageSizeComm10"},{"value":[{"text":"SBSDKPageSizeComm10","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1comm10\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1a5\/title","op":"replace","value":"SBSDKPageSizeA5"},{"value":[{"text":"SBSDKPageSizeA5","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1a5\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1legal\/title","op":"replace","value":"SBSDKPageSizeLegal"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1legal\/fragments","value":[{"text":"SBSDKPageSizeLegal","kind":"identifier"}]},{"value":"SBSDKPageSizeUs4X8","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1us4X8\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1us4X8\/fragments","value":[{"text":"SBSDKPageSizeUs4X8","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1a3\/title","op":"replace","value":"SBSDKPageSizeA3"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1a3\/fragments","value":[{"text":"SBSDKPageSizeA3","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1letter\/title","value":"SBSDKPageSizeLetter","op":"replace"},{"value":[{"text":"SBSDKPageSizeLetter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1letter\/fragments"},{"op":"replace","value":"SBSDKPageSizeUs4X6","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1us4X6\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1us4X6\/fragments","value":[{"text":"SBSDKPageSizeUs4X6","kind":"identifier"}],"op":"replace"},{"value":"SBSDKPageSizeExecutive","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1executive\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1executive\/fragments","value":[{"kind":"identifier","text":"SBSDKPageSizeExecutive"}]},{"value":"SBSDKPageSize","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/fragments","value":[{"kind":"identifier","text":"SBSDKPageSize"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPageSize"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1us5X7\/title","value":"SBSDKPageSizeUs5X7","op":"replace"},{"op":"replace","value":[{"text":"SBSDKPageSizeUs5X7","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1us5X7\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1b5\/title","op":"replace","value":"SBSDKPageSizeB5"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1b5\/fragments","value":[{"kind":"identifier","text":"SBSDKPageSizeB5"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1b4\/title","op":"replace","value":"SBSDKPageSizeB4"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1b4\/fragments","value":[{"kind":"identifier","text":"SBSDKPageSizeB4"}]},{"value":"SBSDKPageSizeCustom","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1custom\/title"},{"op":"replace","value":[{"text":"SBSDKPageSizeCustom","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1custom\/fragments"},{"value":"SBSDKPageSizeA4","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1a4\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1a4\/fragments","value":[{"kind":"identifier","text":"SBSDKPageSizeA4"}]}]}]}