{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult"},"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/creditCard","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/detectionStatus","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/quad","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/quadNormalized","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/scanningStatus"]},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/close()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/toJson(configuration:)"],"title":"Instance Methods"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"role":"symbol","symbolKind":"class","title":"SBSDKCreditCardScanningResult","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScanningResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCreditCardScanningResult"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardScanningResult"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(SBSDKCreditCardScanningResult) ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardScanningResult","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Contains the result of running the credit card scanner."}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To"}],"references":{"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult/creditCard":{"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult\/creditcard","navigatorTitle":[{"kind":"identifier","text":"creditCard"}],"title":"creditCard","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"creditCard","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/creditCard","abstract":[{"type":"text","text":"Generic document containing credit card data. Not present, if status is FAIL."}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult/quad":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult\/quad","type":"topic","abstract":[{"type":"text","text":"Coordinates of the detected credit card in the input image (clockwise from top-left)."}],"navigatorTitle":[{"text":"quad","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"quad"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":"]"}],"role":"symbol","title":"quad","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/quad"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult/isEqual:":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","title":"isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult\/isequal:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/isEqual:","abstract":[],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult/fromJsonWithJson:":{"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/fromJsonWithJson:","type":"topic","abstract":[],"role":"symbol","title":"fromJsonWithJson:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult\/fromjsonwithjson:","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}]},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult/quadNormalized":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult\/quadnormalized","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/quadNormalized","abstract":[{"text":"Coordinates of the detected credit card in the input image (clockwise from top-left), normalized to the range","type":"text"},{"text":" ","type":"text"},{"text":"[0, 1].","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"quadNormalized"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"quadNormalized","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"text":"]","kind":"text"}],"title":"quadNormalized"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult/initWithDetectionStatus:scanningStatus:creditCard:quad:quadNormalized:":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult\/initwithdetectionstatus:scanningstatus:creditcard:quad:quadnormalized:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/initWithDetectionStatus:scanningStatus:creditCard:quad:quadNormalized:","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDetectionStatus:scanningStatus:creditCard:quad:quadNormalized:"}],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDetectionStatus:scanningStatus:creditCard:quad:quadNormalized:"}],"title":"initWithDetectionStatus:scanningStatus:creditCard:quad:quadNormalized:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult":{"navigatorTitle":[{"text":"SBSDKCreditCardScanningResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult","abstract":[{"text":"Contains the result of running the credit card scanner.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCreditCardScanningResult"}],"type":"topic","role":"symbol","title":"SBSDKCreditCardScanningResult","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult/detectionStatus":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/detectionStatus","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult\/detectionstatus","type":"topic","kind":"symbol","title":"detectionStatus","role":"symbol","abstract":[{"type":"text","text":"The status of the credit card detection step."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionStatus","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKDocumentDetectionStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectionStatus"}],"navigatorTitle":[{"text":"detectionStatus","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult/copyWithZone:":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/copyWithZone:","title":"copyWithZone:","type":"topic","role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult\/copywithzone:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult/hash":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/hash","kind":"symbol","title":"hash","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult\/hash","fragments":[{"kind":"identifier","text":"hash"}]},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult/close()":{"title":"close()","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"close","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","navigatorTitle":[{"text":"close","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/close()","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult\/close()"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"NSCopying","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult/toJson(configuration:)":{"title":"toJson(configuration:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/toJson(configuration:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult\/tojson(configuration:)","kind":"symbol","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult/scanningStatus":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/scanningStatus","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult\/scanningstatus","title":"scanningStatus","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"The status of the credit card scanning step.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scanningStatus"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCreditCardScanningStatus","text":"SBSDKCreditCardScanningStatus"}],"navigatorTitle":[{"text":"scanningStatus","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKCreditCardScanningResult","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKCreditCardScanningResult","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCreditCardScanningResult"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/creditCard","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/detectionStatus","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/quad","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/quadNormalized","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/scanningStatus"]},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/close()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/initWithDetectionStatus:scanningStatus:creditCard:quad:quadNormalized:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/toJson(configuration:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult\/fromJsonWithJson:"],"title":"Type Methods","anchor":"Type-Methods","generated":true}]},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"type":"conformsTo"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKCreditCardScanningResult","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult~1creditCard\/title","value":"creditCard"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult~1creditCard\/fragments","value":[{"text":"creditCard","kind":"identifier"}],"op":"replace"},{"value":"quad","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult~1quad\/title"},{"value":[{"kind":"identifier","text":"quad"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult~1quad\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult~1quadNormalized\/title","value":"quadNormalized"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult~1quadNormalized\/fragments","value":[{"text":"quadNormalized","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult\/title","value":"SBSDKCreditCardScanningResult","op":"replace"},{"value":[{"text":"SBSDKCreditCardScanningResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult\/navigatorTitle","value":[{"text":"SBSDKCreditCardScanningResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult~1detectionStatus\/title","value":"detectionStatus","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult~1detectionStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"detectionStatus"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult~1close()\/title","value":"close","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult~1close()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"close","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult~1toJson(configuration:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult~1scanningStatus\/title","value":"scanningStatus","op":"replace"},{"value":[{"kind":"identifier","text":"scanningStatus"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult~1scanningStatus\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}