{"abstract":[{"type":"text","text":"The parameters "},{"type":"codeVoice","code":"pageSize"},{"type":"text","text":", "},{"type":"codeVoice","code":"pageFit"},{"type":"text","text":", "},{"code":"dpi","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"resamplingMethod"},{"text":" interact in a complex way","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"when adding bitmap images (JPEG, PNG, or raw) to the PDF."},{"type":"text","text":" "},{"text":"There are three cases to consider:","type":"text"}],"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/init()"],"anchor":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/attributes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/dpi","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/jpegQuality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/pageDirection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/pageFit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/pageSize","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/resamplingMethod"],"title":"Instance Properties","generated":true},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/toJson(configuration:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(SBSDKPDFConfiguration) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKPDFConfiguration","kind":"identifier"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"pageSize","type":"codeVoice"},{"type":"text","text":" is "},{"type":"codeVoice","code":"CUSTOM"},{"text":":","type":"text"},{"type":"text","text":" "},{"type":"text","text":"in this case "},{"code":"dpi","type":"codeVoice"},{"type":"text","text":" is used as the conversion ratio to calculate both the physical page and"},{"type":"text","text":" "},{"type":"text","text":"image sizes in inches from the bitmap dimensions. "},{"type":"codeVoice","code":"resamplingMethod"},{"text":" is ignored.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"pageSize"},{"type":"text","text":" is not "},{"type":"codeVoice","code":"CUSTOM"},{"type":"text","text":" AND "},{"code":"pageFit","type":"codeVoice"},{"type":"text","text":" is "},{"type":"codeVoice","code":"NONE"},{"text":":","type":"text"},{"type":"text","text":" "},{"text":"in this case ","type":"text"},{"code":"dpi","type":"codeVoice"},{"type":"text","text":" is used as the conversion ratio to calculate only the physical image"},{"type":"text","text":" "},{"text":"size in inches from the bitmap dimensions. The image is centered onto the page.","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"resamplingMethod"},{"type":"text","text":" is ignored."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"pageSize","type":"codeVoice"},{"text":" is not ","type":"text"},{"type":"codeVoice","code":"CUSTOM"},{"text":" AND ","type":"text"},{"type":"codeVoice","code":"pageFit"},{"text":" is not ","type":"text"},{"type":"codeVoice","code":"NONE"},{"type":"text","text":":"},{"text":" ","type":"text"},{"text":"in this case the page has a pre-determined physical size and we want to stretch the image to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"fit the page in one of the ways described by "},{"code":"pageFit","type":"codeVoice"},{"text":". The image DPI is automatically","type":"text"},{"type":"text","text":" "},{"type":"text","text":"calculated for each image from the given physical page size, page fit setting and image"},{"type":"text","text":" "},{"type":"text","text":"dimensions. There are two sub-cases to consider:"},{"text":" ","type":"text"},{"type":"text","text":"a. "},{"code":"resamplingMethod","type":"codeVoice"},{"type":"text","text":" is NONE OR the calculated DPI is less than or equal to "},{"code":"dpi","type":"codeVoice"},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"in this case the image is added to the PDF without resampling, which means that the image"},{"text":" ","type":"text"},{"text":"rectangle is simply rescaled to fit into the page as specified by ","type":"text"},{"type":"codeVoice","code":"pageFit"},{"text":" and","type":"text"},{"type":"text","text":" "},{"code":"pageSize","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"b. "},{"code":"resamplingMethod","type":"codeVoice"},{"text":" is not NONE AND the calculated DPI is greater than ","type":"text"},{"code":"dpi","type":"codeVoice"},{"type":"text","text":":"},{"type":"text","text":" "},{"text":"in this case the bitmap of the image is resampled to match ","type":"text"},{"code":"dpi","type":"codeVoice"},{"text":" using the selected method","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"before adding it to the PDF. This will result in a bitmap that is smaller than the"},{"type":"text","text":" "},{"type":"text","text":"original image and hence, the resulting PDF will be smaller in size."}]}]}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"SBSDKPDFConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKPDFConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","roleHeading":"Class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/pageFit":{"abstract":[{"type":"text","text":"How to fit the image into the page. Only used if "},{"code":"pageSize","type":"codeVoice"},{"text":" is not ","type":"text"},{"code":"CUSTOM","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The image can either be stretched to fill the page,"},{"type":"text","text":" "},{"text":"in one of three ways, or centered on the page without stretching.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/pagefit","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageFit"},{"kind":"text","text":": "},{"text":"SBSDKPageFit","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageFit","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"pageFit","kind":"identifier"}],"kind":"symbol","title":"pageFit","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/pageFit"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/toJson(configuration:)":{"navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/tojson(configuration:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/toJson(configuration:)","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"toJson(configuration:)"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/pageDirection":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"pageDirection","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKPageDirection","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageDirection"}],"navigatorTitle":[{"kind":"identifier","text":"pageDirection"}],"title":"pageDirection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/pageDirection","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/pagedirection","abstract":[{"text":"Page direction.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/attributes":{"title":"attributes","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/attributes","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/attributes","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"attributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKPDFAttributes","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFAttributes"}],"navigatorTitle":[{"kind":"identifier","text":"attributes"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Attributes."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/hash":{"title":"hash","type":"topic","abstract":[],"fragments":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/hash","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/dpi":{"navigatorTitle":[{"kind":"identifier","text":"dpi"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/dpi","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dpi"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"dpi","type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"dpi","type":"codeVoice"},{"text":" parameter has two different meanings depending on the value of ","type":"text"},{"type":"codeVoice","code":"pageSize"},{"type":"text","text":" and"},{"type":"text","text":" "},{"code":"pageFit","type":"codeVoice"},{"type":"text","text":". If pageSize is CUSTOM or pageFit is NONE, then "},{"code":"dpi","type":"codeVoice"},{"text":" is the conversion ratio used","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"to convert from units of pixels to physical inches when adding bitmap images (JPEG, PNG, or"},{"text":" ","type":"text"},{"text":"raw) to the PDF. Otherwise, if ","type":"text"},{"type":"codeVoice","code":"resamplingMethod"},{"text":" is not NONE, then the image is downscaled","type":"text"},{"type":"text","text":" "},{"type":"text","text":"if necessary (if the image after being fit to the page has a higher calculated DPI than"},{"type":"text","text":" "},{"code":"dpi","type":"codeVoice"},{"type":"text","text":") to match "},{"code":"dpi","type":"codeVoice"},{"text":" before adding it to the PDF. Otherwise, the setting is ignored and the","type":"text"},{"type":"text","text":" "},{"text":"calculated image DPI is used instead.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/dpi","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/isEqual:":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/isequal:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/isEqual:","abstract":[],"kind":"symbol","type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/resamplingMethod":{"title":"resamplingMethod","abstract":[{"text":"Resampling method.","type":"text"}],"navigatorTitle":[{"text":"resamplingMethod","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/resamplingmethod","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/resamplingMethod","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resamplingMethod"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKResamplingMethod","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKResamplingMethod"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/pageSize":{"navigatorTitle":[{"text":"pageSize","kind":"identifier"}],"type":"topic","title":"pageSize","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/pagesize","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pageSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKPageSize","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageSize","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/pageSize","abstract":[{"text":"Physical size of the page. If CUSTOM, the page size will be set as the image size at given dpi.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/init()":{"role":"symbol","title":"init()","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/init()","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/fromJsonWithJson:":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/fromJsonWithJson:","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"type":"topic","title":"fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/fromjsonwithjson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/copyWithZone:":{"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/copyWithZone:","type":"topic","abstract":[],"role":"symbol","title":"copyWithZone:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/copywithzone:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:","title":"initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/initwithattributes:pagesize:pagedirection:pagefit:dpi:jpegquality:resamplingmethod:","type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration":{"role":"symbol","title":"SBSDKPDFConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration","abstract":[{"text":"The parameters ","type":"text"},{"code":"pageSize","type":"codeVoice"},{"text":", ","type":"text"},{"code":"pageFit","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"dpi"},{"text":" and ","type":"text"},{"code":"resamplingMethod","type":"codeVoice"},{"text":" interact in a complex way","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"when adding bitmap images (JPEG, PNG, or raw) to the PDF."},{"type":"text","text":" "},{"text":"There are three cases to consider:","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/jpegQuality":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/jpegquality","title":"jpegQuality","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/jpegQuality","abstract":[{"type":"text","text":"JPEG quality for images."},{"type":"text","text":" "},{"type":"text","text":"Applies if an image is added as a cv::Mat and therefore needs to be encoded."},{"text":" ","type":"text"},{"text":"Also applies if ","type":"text"},{"type":"codeVoice","code":"resamplingMethod"},{"text":" not NONE and the image being added needs to be","type":"text"},{"type":"text","text":" "},{"text":"downscaled. Otherwise, when adding JPEG files to the PDF, the files are copied directly into","type":"text"},{"type":"text","text":" "},{"text":"the PDF and not re-encoded, which is many times faster and also preserves the quality of the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"original."}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"jpegQuality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"jpegQuality","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKPDFConfiguration"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/attributes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/dpi","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/jpegQuality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/pageDirection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/pageFit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/pageSize","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/resamplingMethod"],"generated":true,"anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/initWithAttributes:pageSize:pageDirection:pageFit:dpi:jpegQuality:resamplingMethod:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/toJson(configuration:)"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/fromJsonWithJson:"],"anchor":"Type-Methods","title":"Type Methods"}],"path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFConfiguration"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"}},{"value":"pageFit","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1pageFit\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1pageFit\/fragments","value":[{"text":"pageFit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1toJson(configuration:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"op":"replace"},{"value":"pageDirection","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1pageDirection\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1pageDirection\/fragments","op":"replace","value":[{"text":"pageDirection","kind":"identifier"}]},{"value":"attributes","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1attributes\/title"},{"value":[{"text":"attributes","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1attributes\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1dpi\/title","value":"dpi","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1dpi\/fragments","op":"replace","value":[{"text":"dpi","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1resamplingMethod\/title","value":"resamplingMethod"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1resamplingMethod\/fragments","op":"replace","value":[{"text":"resamplingMethod","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1pageSize\/title","op":"replace","value":"pageSize"},{"value":[{"kind":"identifier","text":"pageSize"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1pageSize\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1init()\/title","value":"init","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/title","value":"SBSDKPDFConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/navigatorTitle","value":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}]},{"value":"jpegQuality","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1jpegQuality\/title"},{"op":"replace","value":[{"kind":"identifier","text":"jpegQuality"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1jpegQuality\/fragments"}]}]}