{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(SBSDKGenericDocumentFieldDataFormat) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentFieldDataFormat","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddataformat"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddataformat"]}],"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"SBSDKGenericDocumentFieldDataFormat","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDataFormat","role":"symbol","title":"SBSDKGenericDocumentFieldDataFormat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentFieldDataFormat","kind":"identifier"}],"roleHeading":"Class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/rawValue"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/gender","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isoCountryAlpha2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isoCountryAlpha3","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isoCountryName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isoCountryNumeric","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isoDate"],"title":"Type Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/enumValue(from:)"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"kind":"symbol","abstract":[{"text":"Type of parsing applied to field.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDataFormat":{"type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocumentFieldDataFormat","kind":"identifier"}],"title":"SBSDKGenericDocumentFieldDataFormat","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentFieldDataFormat"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddataformat","abstract":[{"text":"Type of parsing applied to field.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDataFormat/isoCountryAlpha3":{"navigatorTitle":[{"text":"isoCountryAlpha3","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isoCountryAlpha3","type":"topic","abstract":[{"text":"Field value is parsed as ISO 3166-1 alpha-3 country code. E.g. “DEU” for Germany.","type":"text"}],"role":"symbol","title":"isoCountryAlpha3","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddataformat\/isocountryalpha3","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isoCountryAlpha3","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentFieldDataFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDataFormat"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDataFormat/isoCountryNumeric":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isoCountryNumeric","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentFieldDataFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDataFormat","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isoCountryNumeric","navigatorTitle":[{"kind":"identifier","text":"isoCountryNumeric"}],"title":"isoCountryNumeric","abstract":[{"type":"text","text":"Field value is parsed as ISO 3166-1 numeric country code. E.g. “276” for Germany."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddataformat\/isocountrynumeric"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDataFormat/isoDate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isoDate","abstract":[{"text":"Field value is parsed as ISO 8601 date in format YYYY-MM-DD.","type":"text"}],"title":"isoDate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isoDate"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddataformat\/isodate","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"isoDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentFieldDataFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDataFormat"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDataFormat/gender":{"abstract":[{"type":"text","text":"Field value is parsed as “Male”, “Female”."}],"navigatorTitle":[{"text":"gender","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"gender","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDataFormat","text":"SBSDKGenericDocumentFieldDataFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddataformat\/gender","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/gender","type":"topic","kind":"symbol","role":"symbol","title":"gender"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDataFormat/isoCountryName":{"navigatorTitle":[{"kind":"identifier","text":"isoCountryName"}],"abstract":[{"text":"Field value is parsed as ISO 3166-1 country name. E.g. “Germany”.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddataformat\/isocountryname","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isoCountryName","title":"isoCountryName","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isoCountryName"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentFieldDataFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDataFormat"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDataFormat/rawValue":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddataformat\/rawvalue","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"title":"rawValue","abstract":[{"type":"text","text":"The raw value integer of the current "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat","type":"reference","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/rawValue","navigatorTitle":[{"text":"rawValue","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDataFormat/hash":{"title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddataformat\/hash","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/hash","fragments":[{"text":"hash","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDataFormat/isEqual:":{"abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddataformat\/isequal:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isEqual:","title":"isEqual:","role":"symbol","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDataFormat/isoCountryAlpha2":{"navigatorTitle":[{"text":"isoCountryAlpha2","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isoCountryAlpha2","type":"topic","abstract":[{"text":"Field value is parsed as ISO 3166-1 alpha-2 country code. E.g. “DE” for Germany.","type":"text"}],"role":"symbol","title":"isoCountryAlpha2","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddataformat\/isocountryalpha2","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isoCountryAlpha2","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDataFormat","text":"SBSDKGenericDocumentFieldDataFormat","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDataFormat/enumValue(from:)":{"navigatorTitle":[{"kind":"identifier","text":"enumValueFrom:"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enumValue","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"text":"SBSDKGenericDocumentFieldDataFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDataFormat"},{"text":"?","kind":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddataformat\/enumvalue(from:)","abstract":[{"type":"text","text":"Returns an instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat","isActive":true,"type":"reference"},{"type":"text","text":" based on the provided raw value."}],"kind":"symbol","type":"topic","title":"enumValue(from:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/enumValue(from:)"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKGenericDocumentFieldDataFormat"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentFieldDataFormat","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentFieldDataFormat","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/rawValue"],"generated":true},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isEqual:"]},{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/gender","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isoCountryAlpha2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isoCountryAlpha3","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isoCountryName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isoCountryNumeric","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/isoDate"],"generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDataFormat\/enumValue(from:)"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentFieldDataFormat"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"SBSDKGenericDocumentFieldDataFormat","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentFieldDataFormat"}]},{"value":[{"text":"SBSDKGenericDocumentFieldDataFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat\/navigatorTitle"},{"value":"isoCountryAlpha3","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat~1isoCountryAlpha3\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat~1isoCountryAlpha3\/fragments","value":[{"text":"isoCountryAlpha3","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat~1isoCountryNumeric\/title","op":"replace","value":"isoCountryNumeric"},{"value":[{"kind":"identifier","text":"isoCountryNumeric"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat~1isoCountryNumeric\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat~1isoDate\/title","value":"isoDate","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"isoDate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat~1isoDate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat~1gender\/title","value":"gender"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat~1gender\/fragments","value":[{"text":"gender","kind":"identifier"}]},{"value":"isoCountryName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat~1isoCountryName\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat~1isoCountryName\/fragments","value":[{"kind":"identifier","text":"isoCountryName"}],"op":"replace"},{"value":"rawValue","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat~1rawValue\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat~1rawValue\/fragments","op":"replace","value":[{"text":"rawValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat~1isoCountryAlpha2\/title","value":"isoCountryAlpha2"},{"value":[{"text":"isoCountryAlpha2","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat~1isoCountryAlpha2\/fragments"},{"value":"enumValueFrom:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat~1enumValue(from:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDataFormat~1enumValue(from:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"enumValueFrom:"}]}]}]}