{"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpathloadmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpathloadmode"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Image Ref Path Load Mode."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKPathLoadMode) "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPathLoadMode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKPathLoadMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPathLoadMode"}],"navigatorTitle":[{"text":"SBSDKPathLoadMode","kind":"identifier"}],"symbolKind":"enum","role":"symbol","title":"SBSDKPathLoadMode","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Enumeration"},"topicSections":[{"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/eager","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/lazy","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/lazyWithCopy"]},{"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/init(rawValue:)"],"generated":true,"title":"Initializers"},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/RawRepresentable-Implementations"],"generated":true}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPathLoadMode/init(rawValue:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/init(rawValue:)","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpathloadmode\/init(rawvalue:)","title":"init(rawValue:)","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPathLoadMode/Equatable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/Equatable-Implementations","role":"collectionGroup","abstract":[],"kind":"article","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpathloadmode\/equatable-implementations","title":"Equatable Implementations"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPathLoadMode/lazyWithCopy":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/lazyWithCopy","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKPathLoadModeLazyWithCopy"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"lazyWithCopy","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Image is loaded into memory the first time it’s requested. Specified path is copied into internal directory and"},{"type":"text","text":" "},{"text":"so isn’t required to exist at the time of loading.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpathloadmode\/lazywithcopy","title":"SBSDKPathLoadMode.lazyWithCopy"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPathLoadMode/eager":{"url":"\/documentation\/scanbotsdk\/sbsdkpathloadmode\/eager","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"eager","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Image is immediately loaded into memory."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKPathLoadModeEager","kind":"identifier"}],"title":"SBSDKPathLoadMode.eager","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/eager"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPathLoadMode/lazy":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/lazy","url":"\/documentation\/scanbotsdk\/sbsdkpathloadmode\/lazy","abstract":[{"text":"Image is loaded into memory the first time it’s requested. Specified path must exist at the time of loading.","type":"text"}],"navigatorTitle":[{"text":"SBSDKPathLoadModeLazy","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"lazy","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SBSDKPathLoadMode.lazy"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPathLoadMode":{"title":"SBSDKPathLoadMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKPathLoadMode","kind":"identifier"}],"type":"topic","abstract":[{"text":"Image Ref Path Load Mode.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpathloadmode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPathLoadMode"}]},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPathLoadMode/RawRepresentable-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpathloadmode\/rawrepresentable-implementations","role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/RawRepresentable-Implementations"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"SBSDKPathLoadMode","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKPathLoadMode"}]},{"value":[{"text":"SBSDKPathLoadMode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/eager","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/lazy","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/lazyWithCopy"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKPathLoadMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode~1lazyWithCopy\/title","value":"SBSDKPathLoadModeLazyWithCopy"},{"value":[{"kind":"identifier","text":"SBSDKPathLoadModeLazyWithCopy"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode~1lazyWithCopy\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode~1eager\/title","value":"SBSDKPathLoadModeEager"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode~1eager\/fragments","op":"replace","value":[{"text":"SBSDKPathLoadModeEager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode~1lazy\/title","op":"replace","value":"SBSDKPathLoadModeLazy"},{"op":"replace","value":[{"text":"SBSDKPathLoadModeLazy","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode~1lazy\/fragments"},{"value":"SBSDKPathLoadMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode\/fragments","op":"replace","value":[{"text":"SBSDKPathLoadMode","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKPathLoadMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}