{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"The accessibility hint for the ‘enable’ button of the camera permission dialog.","type":"text"},{"type":"text","text":" "},{"text":"Default is “Tap to grant camera permission”","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/accessibilityDescriptionCameraPermissionEnableCameraButton","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionEnableCameraButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization(py)accessibilityDescriptionCameraPermissionEnableCameraButton","navigatorTitle":[{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton","kind":"identifier"}],"title":"accessibilityDescriptionCameraPermissionEnableCameraButton","symbolKind":"property"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/accessibilitydescriptioncamerapermissionenablecamerabutton"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/accessibilitydescriptioncamerapermissionenablecamerabutton"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization/accessibilityDescriptionCameraPermissionEnableCameraButton":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/accessibilityDescriptionCameraPermissionEnableCameraButton","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/accessibilitydescriptioncamerapermissionenablecamerabutton","abstract":[{"text":"The accessibility hint for the ‘enable’ button of the camera permission dialog.","type":"text"},{"text":" ","type":"text"},{"text":"Default is “Tap to grant camera permission”","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionEnableCameraButton"}],"title":"accessibilityDescriptionCameraPermissionEnableCameraButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionEnableCameraButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization":{"title":"SBSDKUI2DocumentScannerTextLocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration of all the strings for the standalone cropping screen."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"accessibilityDescriptionCameraPermissionEnableCameraButton","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization~1accessibilityDescriptionCameraPermissionEnableCameraButton\/title","value":"accessibilityDescriptionCameraPermissionEnableCameraButton","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization~1accessibilityDescriptionCameraPermissionEnableCameraButton\/fragments","op":"replace","value":[{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/title","value":"SBSDKUI2DocumentScannerTextLocalization","op":"replace"},{"value":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments"}]}]}