{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/cameraimportbuttontitle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/cameraimportbuttontitle"]}],"kind":"symbol","abstract":[{"text":"The ‘import image’ button title, located in the bottom bar of the camera screen.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is “Import”"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraImportButtonTitle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/cameraImportButtonTitle","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraImportButtonTitle","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"cameraImportButtonTitle","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization(py)cameraImportButtonTitle","navigatorTitle":[{"kind":"identifier","text":"cameraImportButtonTitle"}],"modules":[{"name":"ScanbotSDK"}]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization":{"title":"SBSDKUI2DocumentScannerTextLocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"abstract":[{"text":"Configuration of all the strings for the standalone cropping screen.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization/cameraImportButtonTitle":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The ‘import image’ button title, located in the bottom bar of the camera screen."},{"type":"text","text":" "},{"type":"text","text":"Default is “Import”"}],"navigatorTitle":[{"text":"cameraImportButtonTitle","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/cameraimportbuttontitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraImportButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/cameraImportButtonTitle","title":"cameraImportButtonTitle"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"cameraImportButtonTitle","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"cameraImportButtonTitle","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"cameraImportButtonTitle"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKUI2DocumentScannerTextLocalization","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/title"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments"},{"value":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization~1cameraImportButtonTitle\/title","value":"cameraImportButtonTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization~1cameraImportButtonTitle\/fragments","op":"replace","value":[{"text":"cameraImportButtonTitle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}