{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/reviewdeletepagealertdeleteretakebuttontitle"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/reviewdeletepagealertdeleteretakebuttontitle"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/reviewDeletePageAlertDeleteRetakeButtonTitle"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization(py)reviewDeletePageAlertDeleteRetakeButtonTitle","title":"reviewDeletePageAlertDeleteRetakeButtonTitle","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewDeletePageAlertDeleteRetakeButtonTitle"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"reviewDeletePageAlertDeleteRetakeButtonTitle","kind":"identifier"}]},"abstract":[{"type":"text","text":"The ‘delete and retake’ button title of the delete page alert dialog for the review screen."},{"type":"text","text":" "},{"type":"text","text":"Default is “Delete and Retake”"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewDeletePageAlertDeleteRetakeButtonTitle"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"title":"SBSDKUI2DocumentScannerTextLocalization","type":"topic","abstract":[{"type":"text","text":"Configuration of all the strings for the standalone cropping screen."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization/reviewDeletePageAlertDeleteRetakeButtonTitle":{"navigatorTitle":[{"kind":"identifier","text":"reviewDeletePageAlertDeleteRetakeButtonTitle"}],"title":"reviewDeletePageAlertDeleteRetakeButtonTitle","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/reviewDeletePageAlertDeleteRetakeButtonTitle","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/reviewdeletepagealertdeleteretakebuttontitle","abstract":[{"type":"text","text":"The ‘delete and retake’ button title of the delete page alert dialog for the review screen."},{"type":"text","text":" "},{"type":"text","text":"Default is “Delete and Retake”"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewDeletePageAlertDeleteRetakeButtonTitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"reviewDeletePageAlertDeleteRetakeButtonTitle","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"reviewDeletePageAlertDeleteRetakeButtonTitle"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"reviewDeletePageAlertDeleteRetakeButtonTitle","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/title","op":"replace","value":"SBSDKUI2DocumentScannerTextLocalization"},{"value":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments"},{"value":"reviewDeletePageAlertDeleteRetakeButtonTitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization~1reviewDeletePageAlertDeleteRetakeButtonTitle\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization~1reviewDeletePageAlertDeleteRetakeButtonTitle\/fragments","value":[{"text":"reviewDeletePageAlertDeleteRetakeButtonTitle","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}