{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorType\/componentUnavailable"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"A required SDK component is unavailable or not properly initialized."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"componentUnavailable","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorType"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkerrortype\/componentunavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkerrortype\/componentunavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKErrorType@SBSDKErrorTypeComponentUnavailable","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeComponentUnavailable"}],"title":"SBSDKErrorType.componentUnavailable","roleHeading":"Case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"componentUnavailable"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorType":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An Objective-C compatible enum representing the types of errors that can occur within the Scanbot SDK."},{"type":"text","text":" "},{"type":"text","text":"Each case corresponds to a specific error code."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKErrorType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorType","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrortype","title":"SBSDKErrorType","navigatorTitle":[{"text":"SBSDKErrorType","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKErrorType/componentUnavailable":{"type":"topic","abstract":[{"text":"A required SDK component is unavailable or not properly initialized.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKErrorTypeComponentUnavailable","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkerrortype\/componentunavailable","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"componentUnavailable","kind":"identifier"}],"title":"SBSDKErrorType.componentUnavailable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKErrorType\/componentUnavailable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKErrorTypeComponentUnavailable","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKErrorTypeComponentUnavailable","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKErrorTypeComponentUnavailable","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorType\/title","value":"SBSDKErrorType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorType\/fragments","value":[{"text":"SBSDKErrorType","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKErrorType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorType\/navigatorTitle","op":"replace"},{"value":"SBSDKErrorTypeComponentUnavailable","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorType~1componentUnavailable\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKErrorTypeComponentUnavailable"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKErrorType~1componentUnavailable\/fragments","op":"replace"}]}]}