{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCanvasColor\/black","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","title":"SBSDKCanvasColor.black","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"black","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKCanvasColor@SBSDKCanvasColorBlack","navigatorTitle":[{"text":"SBSDKCanvasColorBlack","kind":"identifier"}],"symbolKind":"case","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCanvasColor"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"black"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Black canvas color.","type":"text"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcanvascolor\/black"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcanvascolor\/black"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCanvasColor":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCanvasColor"}],"title":"SBSDKCanvasColor","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcanvascolor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCanvasColor","type":"topic","abstract":[{"type":"text","text":"Canvas color to use when converting images with alpha channel to images without alpha channel."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCanvasColor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCanvasColor/black":{"abstract":[{"text":"Black canvas color.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCanvasColorBlack"}],"url":"\/documentation\/scanbotsdk\/sbsdkcanvascolor\/black","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCanvasColor\/black","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"black"}],"title":"SBSDKCanvasColor.black","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKCanvasColorBlack","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCanvasColorBlack"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKCanvasColorBlack"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCanvasColor\/title","value":"SBSDKCanvasColor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCanvasColor\/fragments","value":[{"kind":"identifier","text":"SBSDKCanvasColor"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCanvasColor\/navigatorTitle","value":[{"text":"SBSDKCanvasColor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCanvasColor~1black\/title","value":"SBSDKCanvasColorBlack","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCanvasColor~1black\/fragments","value":[{"text":"SBSDKCanvasColorBlack","kind":"identifier"}],"op":"replace"}]}]}