{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/scanbotOCR","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The new machine-learning based mode made by Scanbot SDK GmbH. Faster, less errors, but currently only"},{"text":" ","type":"text"},{"type":"text","text":"supports languages with latin letters."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanbotOCR","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode"]]},"metadata":{"title":"SBSDKOpticalCharacterRecognitionMode.scanbotOCR","role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKOpticalCharacterRecognitionMode@SBSDKOpticalCharacterRecognitionModeScanbotOCR","roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scanbotOCR"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognitionModeScanbotOCR"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/scanbotocr"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/scanbotocr"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode":{"abstract":[{"text":"An enum describing the modes of the optical character recognition.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKOpticalCharacterRecognitionMode","kind":"identifier"}],"title":"SBSDKOpticalCharacterRecognitionMode","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode","navigatorTitle":[{"text":"SBSDKOpticalCharacterRecognitionMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode/scanbotOCR":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"scanbotOCR","kind":"identifier"}],"title":"SBSDKOpticalCharacterRecognitionMode.scanbotOCR","navigatorTitle":[{"text":"SBSDKOpticalCharacterRecognitionModeScanbotOCR","kind":"identifier"}],"abstract":[{"type":"text","text":"The new machine-learning based mode made by Scanbot SDK GmbH. Faster, less errors, but currently only"},{"text":" ","type":"text"},{"text":"supports languages with latin letters.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/scanbotOCR","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/scanbotocr","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKOpticalCharacterRecognitionModeScanbotOCR"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKOpticalCharacterRecognitionModeScanbotOCR","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKOpticalCharacterRecognitionModeScanbotOCR","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKOpticalCharacterRecognitionMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognitionMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1scanbotOCR\/title","value":"SBSDKOpticalCharacterRecognitionModeScanbotOCR"},{"value":[{"text":"SBSDKOpticalCharacterRecognitionModeScanbotOCR","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1scanbotOCR\/fragments","op":"replace"}]}]}