{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/tesseract","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/tesseract"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/tesseract"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"tesseract","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"The legacy OCR mode using Tesseract. Slower, more error prone, but it supports more languages."}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"tesseract","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKOpticalCharacterRecognitionMode@SBSDKOpticalCharacterRecognitionModeTesseract","roleHeading":"Case","role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"SBSDKOpticalCharacterRecognitionModeTesseract","kind":"identifier"}],"title":"SBSDKOpticalCharacterRecognitionMode.tesseract"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode","type":"topic","title":"SBSDKOpticalCharacterRecognitionMode","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode","navigatorTitle":[{"text":"SBSDKOpticalCharacterRecognitionMode","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"An enum describing the modes of the optical character recognition."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKOpticalCharacterRecognitionMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode/tesseract":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKOpticalCharacterRecognitionModeTesseract","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tesseract"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/tesseract","abstract":[{"text":"The legacy OCR mode using Tesseract. Slower, more error prone, but it supports more languages.","type":"text"}],"title":"SBSDKOpticalCharacterRecognitionMode.tesseract","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/tesseract"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKOpticalCharacterRecognitionModeTesseract","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"SBSDKOpticalCharacterRecognitionModeTesseract","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKOpticalCharacterRecognitionModeTesseract","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode\/title","value":"SBSDKOpticalCharacterRecognitionMode"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognitionMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1tesseract\/title","value":"SBSDKOpticalCharacterRecognitionModeTesseract","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1tesseract\/fragments","value":[{"text":"SBSDKOpticalCharacterRecognitionModeTesseract","kind":"identifier"}]}]}]}