{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2findandpickaroverlaypolygonconfiguration\/initwithvisible:partiallyscanned:rejected:completed:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickArOverlayPolygonConfiguration"]]},"metadata":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithVisible:partiallyScanned:rejected:completed:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FindAndPickArOverlayPolygonConfiguration(im)initWithVisible:partiallyScanned:rejected:completed:","title":"initWithVisible:partiallyScanned:rejected:completed:","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithVisible:partiallyScanned:rejected:completed:","kind":"identifier"}],"symbolKind":"method"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"visible","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"partiallyScanned:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle","text":"SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"partiallyScanned","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"rejected:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle","text":"SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"rejected","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completed:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle","text":"SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"completed","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/initWithVisible:partiallyScanned:rejected:completed:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickArOverlayPolygonConfiguration/initWithVisible:partiallyScanned:rejected:completed:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/initWithVisible:partiallyScanned:rejected:completed:","abstract":[],"title":"initWithVisible:partiallyScanned:rejected:completed:","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickaroverlaypolygonconfiguration\/initwithvisible:partiallyscanned:rejected:completed:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithVisible:partiallyScanned:rejected:completed:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithVisible:partiallyScanned:rejected:completed:","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickArOverlayPolygonConfiguration":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickArOverlayPolygonConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickaroverlaypolygonconfiguration","abstract":[{"text":"Configuration of the overlay polygon displayed on top of a barcode in the camera preview.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration"}],"title":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PolygonStyle":{"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","url":"\/documentation\/scanbotsdk\/sbsdkui2polygonstyle","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the polygon appearance."}],"title":"SBSDKUI2PolygonStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2PolygonStyle"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PolygonStyle"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/title","value":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/title","value":"SBSDKUI2PolygonStyle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2PolygonStyle"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/navigatorTitle","value":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}],"op":"replace"}]}]}