{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"beginStreamingEncrypt","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter\/beginStreamingEncrypt()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SBSDKStorageCrypting.beginStreamingEncrypt()"},{"type":"text","text":"."}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter"]]},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"beginStreamingEncrypt"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAESEncrypter(im)beginStreamingEncrypt","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"beginStreamingEncrypt"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"beginStreamingEncrypt()"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkaesencrypter\/beginstreamingencrypt()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkaesencrypter\/beginstreamingencrypt()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypter/beginStreamingEncrypt()":{"type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"beginStreamingEncrypt"}],"url":"\/documentation\/scanbotsdk\/sbsdkaesencrypter\/beginstreamingencrypt()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter\/beginStreamingEncrypt()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"beginStreamingEncrypt","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"beginStreamingEncrypt()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypter":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkaesencrypter","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAESEncrypter"}],"navigatorTitle":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"ScanbotSDK’s default data encrypter. Provides AES128 and AES 256 encryption to your data."}],"kind":"symbol","title":"SBSDKAESEncrypter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"beginStreamingEncrypt","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"beginStreamingEncrypt"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"beginStreamingEncrypt","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"beginStreamingEncrypt","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter~1beginStreamingEncrypt()\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter~1beginStreamingEncrypt()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"beginStreamingEncrypt"}]},{"value":"SBSDKAESEncrypter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/title","op":"replace"},{"value":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}