{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter"]]},"metadata":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"encryptData:context:error:"}],"role":"symbol","navigatorTitle":[{"text":"encryptData:context:error:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAESEncrypter(im)encryptData:context:error:","title":"encryptData:context:error:","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":" *) "},{"text":"encryptData:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"data"},{"kind":"text","text":" "},{"kind":"identifier","text":"context:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"context"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkaesencrypter\/encryptdata:context:error:"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter\/encryptData:context:error:"},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypter/encryptData:context:error:":{"title":"encryptData:context:error:","url":"\/documentation\/scanbotsdk\/sbsdkaesencrypter\/encryptdata:context:error:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter\/encryptData:context:error:","type":"topic","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"encryptData:context:error:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"encryptData:context:error:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypter":{"title":"SBSDKAESEncrypter","url":"\/documentation\/scanbotsdk\/sbsdkaesencrypter","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKAESEncrypter"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAESEncrypter","kind":"identifier"}],"abstract":[{"type":"text","text":"ScanbotSDK’s default data encrypter. Provides AES128 and AES 256 encryption to your data."},{"type":"text","text":" "},{"text":"All data is encrypted and decrypted with the same key.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The context being passed to the encrypt\/decrypt methods is ignored."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/title","value":"SBSDKAESEncrypter","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/fragments","value":[{"text":"SBSDKAESEncrypter","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAESEncrypter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}