{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@_NSZone","text":"_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldInvalidDataVerificationReport(im)copyWithZone:","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","title":"copyWithZone:","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldInvalidDataVerificationReport"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldInvalidDataVerificationReport\/copyWithZone:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkfieldinvaliddataverificationreport\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldInvalidDataVerificationReport/copyWithZone:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldInvalidDataVerificationReport\/copyWithZone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"type":"topic","role":"symbol","title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkfieldinvaliddataverificationreport\/copywithzone:","kind":"symbol","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldInvalidDataVerificationReport":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFieldInvalidDataVerificationReport","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKFieldInvalidDataVerificationReport","kind":"identifier"}],"abstract":[{"type":"text","text":"Report which shows whether the data in the field that can be validated is valid."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldInvalidDataVerificationReport","url":"\/documentation\/scanbotsdk\/sbsdkfieldinvaliddataverificationreport","title":"SBSDKFieldInvalidDataVerificationReport"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldInvalidDataVerificationReport\/title","value":"SBSDKFieldInvalidDataVerificationReport","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldInvalidDataVerificationReport\/fragments","value":[{"kind":"identifier","text":"SBSDKFieldInvalidDataVerificationReport"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldInvalidDataVerificationReport\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFieldInvalidDataVerificationReport"}],"op":"replace"}]}]}