{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeitem\/rawbytes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeitem\/rawbytes"]}],"abstract":[{"text":"Raw bytes of barcode contents.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Some barcode formats are able to encode binary data. If a barcode contains binary data, it’s provided as a list"},{"type":"text","text":" "},{"text":"of bytes in the rawBytes field.","type":"text"},{"type":"text","text":" "},{"text":"Some barcode formats additionally allow pieces of the data within to have different encodings - UTF-8, ASCII,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"binary, etc."},{"type":"text","text":" "},{"type":"text","text":"The rawBytesEncodings field lists the encoding of each range in the rawBytes array."},{"text":" ","type":"text"},{"text":"For barcode formats that contain a GS1 message (e.g. GS1 Composite), we recommend to use a GS1Handling and","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"extract the GS1 message from the text."}],"metadata":{"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"rawBytes","roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem(py)rawBytes","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBytes"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"navigatorTitle":[{"text":"rawBytes","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"rawBytes","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem\/rawBytes"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeItem/rawBytes":{"abstract":[{"text":"Raw bytes of barcode contents.","type":"text"},{"type":"text","text":" "},{"text":"Some barcode formats are able to encode binary data. If a barcode contains binary data, it’s provided as a list","type":"text"},{"type":"text","text":" "},{"text":"of bytes in the rawBytes field.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Some barcode formats additionally allow pieces of the data within to have different encodings - UTF-8, ASCII,"},{"text":" ","type":"text"},{"text":"binary, etc.","type":"text"},{"type":"text","text":" "},{"text":"The rawBytesEncodings field lists the encoding of each range in the rawBytes array.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"For barcode formats that contain a GS1 message (e.g. GS1 Composite), we recommend to use a GS1Handling and"},{"type":"text","text":" "},{"type":"text","text":"extract the GS1 message from the text."}],"role":"symbol","type":"topic","title":"rawBytes","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBytes","kind":"identifier"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem\/rawBytes","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeitem\/rawbytes","navigatorTitle":[{"text":"rawBytes","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeItem":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeItem","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeItem","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A single barcode found in the input image. Barcodes with the same content but different locations in the image are"},{"type":"text","text":" "},{"text":"considered separate barcodes.","type":"text"}],"title":"SBSDKBarcodeItem","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeitem","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"rawBytes","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"rawBytes"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" * "},{"kind":"identifier","text":"rawBytes"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem~1rawBytes\/title","value":"rawBytes","op":"replace"},{"value":[{"text":"rawBytes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem~1rawBytes\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/title","value":"SBSDKBarcodeItem"},{"value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/navigatorTitle","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]}]}]}