{"sections":[],"abstract":[{"type":"text","text":"Asks the delegate for a "},{"code":"UIBarButtonItem","type":"codeVoice"},{"type":"text","text":" to for rotating the image counter-clockwise."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"editingViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIBarButtonItem","kind":"typeIdentifier","text":"UIBarButtonItem"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"editingViewController","content":[{"type":"paragraph","inlineContent":[{"text":"The calling ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","type":"reference","isActive":true},{"type":"text","text":"."}]}]}]},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UIBarButtonItem"},{"text":" for rotating the image counter-clockwise.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerrotatecounterclockwisetoolbaritem(_:)"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerrotatecounterclockwisetoolbaritem(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController","kind":"typeIdentifier","text":"SBSDKImageEditingViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBarButtonItem","text":"UIBarButtonItem"},{"kind":"text","text":"?"}],"title":"imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKImageEditingViewControllerDelegate(im)imageEditingViewControllerRotateCounterClockwiseToolbarItem:","navigatorTitle":[{"text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:","kind":"identifier"}],"required":true},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerrotatecounterclockwisetoolbaritem(_:)","title":"imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)","type":"topic","required":true,"abstract":[{"text":"Asks the delegate for a ","type":"text"},{"type":"codeVoice","code":"UIBarButtonItem"},{"type":"text","text":" to for rotating the image counter-clockwise."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem"},{"kind":"text","text":"("},{"text":"SBSDKImageEditingViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBarButtonItem","text":"UIBarButtonItem"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"abstract":[{"text":"A delegate protocol to inform an object about changes in ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate","title":"SBSDKImageEditingViewControllerDelegate","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewController":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontroller","title":"SBSDKImageEditingViewController","abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to show and edit an image.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBarButtonItem","text":"UIBarButtonItem","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController"},{"text":" *) ","kind":"text"},{"text":"editingViewController","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The calling ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"editingViewController"}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UIBarButtonItem"},{"type":"text","text":" for rotating the image counter-clockwise."}]}],"kind":"content"}},{"value":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate\/title","op":"replace","value":"SBSDKImageEditingViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/title","value":"SBSDKImageEditingViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/navigatorTitle","value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}]}]}]}