{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerIntroScreenConfiguration\/showAutomatically"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerIntroScreenConfiguration"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerIntroScreenConfiguration(py)showAutomatically","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showAutomatically","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"showAutomatically","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"showAutomatically","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAutomatically"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Default is false"}],"type":"paragraph"}]}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerintroscreenconfiguration\/showautomatically"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerintroscreenconfiguration\/showautomatically"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Determines whether the introduction screen should automatically be shown or not when the scanning session","type":"text"},{"text":" ","type":"text"},{"text":"starts.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerIntroScreenConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MRZScannerIntroScreenConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerIntroScreenConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerintroscreenconfiguration","title":"SBSDKUI2MRZScannerIntroScreenConfiguration","abstract":[{"text":"Configuration of the introduction screen for the MRZ scanner.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2MRZScannerIntroScreenConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerIntroScreenConfiguration/showAutomatically":{"role":"symbol","abstract":[{"text":"Determines whether the introduction screen should automatically be shown or not when the scanning session","type":"text"},{"text":" ","type":"text"},{"text":"starts.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAutomatically"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerIntroScreenConfiguration\/showAutomatically","title":"showAutomatically","navigatorTitle":[{"kind":"identifier","text":"showAutomatically"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerintroscreenconfiguration\/showautomatically"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"showAutomatically"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"showAutomatically","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAutomatically"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerIntroScreenConfiguration\/title","value":"SBSDKUI2MRZScannerIntroScreenConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerIntroScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerIntroScreenConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerIntroScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerIntroScreenConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerIntroScreenConfiguration~1showAutomatically\/title","value":"showAutomatically"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerIntroScreenConfiguration~1showAutomatically\/fragments","value":[{"text":"showAutomatically","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}