{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration"]]},"metadata":{"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentFlowAppearanceConfiguration(cm)fromJsonWithJson:","symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentFlowAppearanceConfiguration","kind":"typeIdentifier","text":"SBSDKUI2DocumentFlowAppearanceConfiguration"},{"kind":"text","text":" *) "},{"text":"fromJsonWithJson:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/fromJsonWithJson:"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration/fromJsonWithJson:":{"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"fragments":[{"kind":"text","text":"+ "},{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/fromJsonWithJson:","title":"fromJsonWithJson:","abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration\/fromjsonwithjson:","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration","role":"symbol","kind":"symbol","type":"topic","title":"SBSDKUI2DocumentFlowAppearanceConfiguration","abstract":[{"text":"Configuration of the general appearance.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentFlowAppearanceConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2DocumentFlowAppearanceConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2DocumentFlowAppearanceConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentFlowAppearanceConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2DocumentFlowAppearanceConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration\/navigatorTitle"}]}]}