{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parsedSuccessful"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalCertificateDocumentField","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2MedicalCertificateDocumentField","text":"SBSDKUI2MedicalCertificateDocumentField"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalcertificatedocumentformat\/init(parsedsuccessful:fields:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalcertificatedocumentformat\/init(parsedsuccessful:fields:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalCertificateDocumentFormat\/init(parsedSuccessful:fields:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Designated initializer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parsedSuccessful"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2MedicalCertificateDocumentField","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2MedicalCertificateDocumentField"},{"kind":"text","text":"])"}],"title":"init(parsedSuccessful:fields:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2MedicalCertificateDocumentFormat(im)initWithParsedSuccessful:fields:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithParsedSuccessful:fields:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalCertificateDocumentFormat"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalCertificateDocumentFormat":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFormat"}],"abstract":[{"type":"text","text":"Medical Certificate Document Format"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalCertificateDocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFormat"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalcertificatedocumentformat"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.2"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalCertificateDocumentFormat/init(parsedSuccessful:fields:)":{"role":"symbol","title":"init(parsedSuccessful:fields:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parsedSuccessful"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2MedicalCertificateDocumentField","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2MedicalCertificateDocumentField"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Designated initializer."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalCertificateDocumentFormat\/init(parsedSuccessful:fields:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithParsedSuccessful:fields:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalcertificatedocumentformat\/init(parsedsuccessful:fields:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalCertificateDocumentField":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentField"}],"abstract":[{"type":"text","text":"Medical Certificate Document Field"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalCertificateDocumentField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentField"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalcertificatedocumentfield"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithParsedSuccessful:fields:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParsedSuccessful:fields:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithParsedSuccessful:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"parsedSuccessful"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKUI2MedicalCertificateDocumentField *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fields"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalCertificateDocumentFormat\/title","value":"SBSDKUI2MedicalCertificateDocumentFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalCertificateDocumentFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalCertificateDocumentFormat~1init(parsedSuccessful:fields:)\/title","value":"initWithParsedSuccessful:fields:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalCertificateDocumentFormat~1init(parsedSuccessful:fields:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParsedSuccessful:fields:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalCertificateDocumentField\/title","value":"SBSDKUI2MedicalCertificateDocumentField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalCertificateDocumentField\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}