{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerUIConfiguration"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescanneruiconfiguration\/userguidancebackgroundcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescanneruiconfiguration\/userguidancebackgroundcolor"]}],"abstract":[{"type":"text","text":"The background color of the user guidance label."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"userGuidanceBackgroundColor","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userGuidanceBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"kind":"identifier","text":"userGuidanceBackgroundColor"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerUIConfiguration(py)userGuidanceBackgroundColor"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerUIConfiguration\/userGuidanceBackgroundColor","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userGuidanceBackgroundColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerUIConfiguration/userGuidanceBackgroundColor":{"title":"userGuidanceBackgroundColor","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescanneruiconfiguration\/userguidancebackgroundcolor","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"userGuidanceBackgroundColor"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userGuidanceBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"abstract":[{"text":"The background color of the user guidance label.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerUIConfiguration\/userGuidanceBackgroundColor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerUIConfiguration":{"role":"symbol","title":"SBSDKUIMedicalCertificateScannerUIConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIMedicalCertificateScannerUIConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescanneruiconfiguration","abstract":[{"type":"text","text":"Configuration for the user interface of the RTU-UI medical certificate scanner."}],"type":"topic","navigatorTitle":[{"text":"SBSDKUIMedicalCertificateScannerUIConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerUIConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"userGuidanceBackgroundColor","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"userGuidanceBackgroundColor","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"userGuidanceBackgroundColor","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"userGuidanceBackgroundColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration~1userGuidanceBackgroundColor\/title"},{"value":[{"text":"userGuidanceBackgroundColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration~1userGuidanceBackgroundColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration\/title","value":"SBSDKUIMedicalCertificateScannerUIConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerUIConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIMedicalCertificateScannerUIConfiguration","kind":"identifier"}]}]}]}