{"kind":"symbol","abstract":[{"type":"text","text":"Creates a configuration object from a JSON file located at the specified URL."}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/configurationwithjsonfrom(url:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/configurationwithjsonfrom(url:)"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration\/configurationWithJSONFrom(URL:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationWithJSONFrom"},{"kind":"text","text":"("},{"text":"URL","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)ScanbotSDKConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration","kind":"typeIdentifier","text":"ScanbotSDKConfiguration"},{"text":"?","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The URL of the JSON file containing configuration settings."}],"type":"paragraph"}],"name":"URL"}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A configured "},{"code":"ScanbotSDKConfiguration","type":"codeVoice"},{"type":"text","text":" instance if the JSON file is successfully loaded and parsed,"},{"type":"text","text":" "},{"type":"text","text":"or "},{"code":"nil","type":"codeVoice"},{"text":" if the file is not found or there was an issue with parsing.","type":"text"}]}],"kind":"content"}],"metadata":{"roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationWithJSONFrom"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"URL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)ScanbotSDKConfiguration","text":"ScanbotSDKConfiguration"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"configurationWithJSONFromURL:"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)ScanbotSDKConfiguration(cm)configurationWithJSONFromURL:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"configurationWithJSONFrom(URL:)","symbolKind":"method","role":"symbol"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotSDKConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ScanbotSDKConfiguration"}],"title":"ScanbotSDKConfiguration","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration","navigatorTitle":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration","type":"topic","abstract":[{"code":"ScanbotSDKConfiguration","type":"codeVoice"},{"text":" is a configuration class that allows you to customize various settings and behavior of the Scanbot SDK.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotSDKConfiguration/configurationWithJSONFrom(URL:)":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationWithJSONFrom"},{"kind":"text","text":"("},{"text":"URL","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)ScanbotSDKConfiguration","text":"ScanbotSDKConfiguration","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"configurationWithJSONFromURL:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/configurationwithjsonfrom(url:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration\/configurationWithJSONFrom(URL:)","type":"topic","abstract":[{"type":"text","text":"Creates a configuration object from a JSON file located at the specified URL."}],"title":"configurationWithJSONFrom(URL:)","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"configurationWithJSONFromURL:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configurationWithJSONFromURL:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)ScanbotSDKConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration","kind":"typeIdentifier","text":"ScanbotSDKConfiguration"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"configurationWithJSONFromURL:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"text":" *) ","kind":"text"},{"text":"URL","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"URL","content":[{"type":"paragraph","inlineContent":[{"text":"The URL of the JSON file containing configuration settings.","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A configured "},{"type":"codeVoice","code":"ScanbotSDKConfiguration"},{"text":" instance if the JSON file is successfully loaded and parsed,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the file is not found or there was an issue with parsing."}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/title","value":"ScanbotSDKConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/fragments","op":"replace","value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/navigatorTitle","value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}]},{"value":"configurationWithJSONFromURL:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration~1configurationWithJSONFrom(URL:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration~1configurationWithJSONFrom(URL:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configurationWithJSONFromURL:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}