{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CheckIntroImage\/fromJsonWithJson:","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CheckIntroImage"]]},"metadata":{"symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CheckIntroImage(cm)fromJsonWithJson:","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","roleHeading":"Type Method"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CheckIntroImage","text":"SBSDKUI2CheckIntroImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CheckIntroImage"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2checkintroimage\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CheckIntroImage":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CheckIntroImage","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2checkintroimage","title":"SBSDKUI2CheckIntroImage","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckIntroImage"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CheckIntroImage"}],"kind":"symbol","abstract":[{"type":"text","text":"The image for the introduction screen with a check template."}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CheckIntroImage/fromJsonWithJson:":{"title":"fromJsonWithJson:","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2checkintroimage\/fromjsonwithjson:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CheckIntroImage\/fromJsonWithJson:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CheckIntroImage\/title","value":"SBSDKUI2CheckIntroImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CheckIntroImage\/fragments","value":[{"text":"SBSDKUI2CheckIntroImage","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUI2CheckIntroImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CheckIntroImage\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}