{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusFailure","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"}],"role":"symbol","title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus.failure","externalID":"c:@M@ScanbotSDK@E@SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus@SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusFailure","symbolKind":"case","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"text":"Field is not valid.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/failure","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/failure"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/failure"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus/failure":{"navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusFailure","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/failure","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/failure","title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus.failure","type":"topic","role":"symbol","abstract":[{"text":"Field is not valid.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus","role":"symbol","title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Health insurance card field validation status."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusFailure","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusFailure","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusFailure","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusFailure","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus~1failure\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus~1failure\/fragments","op":"replace","value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusFailure","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/title","op":"replace","value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/fragments","op":"replace","value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/navigatorTitle","op":"replace","value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}