{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar\/initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithImportButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"importButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSnappingModeButton:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"autoSnappingModeButton"},{"text":" ","kind":"text"},{"text":"manualSnappingModeButton:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","text":"SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"manualSnappingModeButton"},{"text":" ","kind":"text"},{"text":"shutterButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2ShutterButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ShutterButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ShutterButton"},{"text":" *) ","kind":"text"},{"text":"shutterButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"torchOnButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"torchOnButton"},{"kind":"text","text":" "},{"text":"torchOffButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"torchOffButton"},{"text":" ","kind":"text"},{"kind":"identifier","text":"previewButton:"},{"kind":"text","text":"("},{"text":"SBSDKUI2PreviewButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PreviewButton","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton"},{"kind":"text","text":" *) "},{"text":"previewButton","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerabottombar\/initwithimportbutton:autosnappingmodebutton:manualsnappingmodebutton:shutterbutton:torchonbutton:torchoffbutton:previewbutton:"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraBottomBar(im)initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","navigatorTitle":[{"text":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PreviewButton":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2PreviewButton","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2previewbutton","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PreviewButton"}],"type":"topic","abstract":[{"text":"Configuration of the ‘preview’ button.","type":"text"}],"title":"SBSDKUI2PreviewButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraBottomBar":{"title":"SBSDKUI2CameraBottomBar","role":"symbol","abstract":[{"text":"Configuration of the bottom bar for the camera screen.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerabottombar"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarButtonConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","navigatorTitle":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}],"type":"topic","title":"SBSDKUI2BarButtonConfiguration","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barbuttonconfiguration","abstract":[{"type":"text","text":"Configuration of the button located on a bar."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraBottomBar/initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar\/initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","abstract":[],"navigatorTitle":[{"text":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerabottombar\/initwithimportbutton:autosnappingmodebutton:manualsnappingmodebutton:shutterbutton:torchonbutton:torchoffbutton:previewbutton:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ShutterButton":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ShutterButton","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ShutterButton"}],"type":"topic","abstract":[{"type":"text","text":"Configuration of the ‘shutter’ button."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2ShutterButton","kind":"identifier"}],"title":"SBSDKUI2ShutterButton","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2shutterbutton"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2PreviewButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton\/title"},{"value":[{"text":"SBSDKUI2PreviewButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2PreviewButton"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton\/navigatorTitle"},{"value":"SBSDKUI2CameraBottomBar","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/fragments","value":[{"text":"SBSDKUI2CameraBottomBar","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/navigatorTitle"},{"value":"SBSDKUI2BarButtonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/fragments","value":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}]},{"op":"replace","value":"SBSDKUI2ShutterButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ShutterButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ShutterButton\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ShutterButton"}]},{"value":[{"text":"SBSDKUI2ShutterButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ShutterButton\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}