{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanner\/clearFrameAccumulator()","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearFrameAccumulator","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"clearFrameAccumulator","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScanner(im)clearFrameAccumulator","role":"symbol","title":"clearFrameAccumulator()"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanner"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Cleans the video frame accumulator."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanner\/clearframeaccumulator()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanner\/clearframeaccumulator()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearFrameAccumulator"},{"kind":"text","text":"()"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"This basically resets the scanner to start a new scan session."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanner/clearFrameAccumulator()":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanner\/clearFrameAccumulator()","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanner\/clearframeaccumulator()","role":"symbol","title":"clearFrameAccumulator()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearFrameAccumulator","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"clearFrameAccumulator","kind":"identifier"}],"abstract":[{"type":"text","text":"Cleans the video frame accumulator."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanner":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanner","title":"SBSDKCreditCardScanner","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanner","role":"symbol","navigatorTitle":[{"text":"SBSDKCreditCardScanner","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardScanner","kind":"identifier"}],"abstract":[{"text":"A class to scan credit cards on various image sources.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"clearFrameAccumulator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"clearFrameAccumulator","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"clearFrameAccumulator"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner~1clearFrameAccumulator()\/title","value":"clearFrameAccumulator"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner~1clearFrameAccumulator()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"clearFrameAccumulator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner\/title","value":"SBSDKCreditCardScanner"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner\/fragments","value":[{"text":"SBSDKCreditCardScanner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCreditCardScanner"}]}]}]}