{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/aamvadliddriverlicenserestrictioncodefieldnormalizedname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/aamvadliddriverlicenserestrictioncodefieldnormalizedname"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName"},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelConstants(cpy)aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName","title":"aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName","roleHeading":"Type Property","role":"symbol"},"abstract":[{"text":"Normalized full name of the “DriverLicenseRestrictionCode” field type in document type “AAMVA.DLID”.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelConstants":{"title":"SBSDKBarcodeDocumentModelConstants","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelConstants/aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName":{"abstract":[{"type":"text","text":"Normalized full name of the “DriverLicenseRestrictionCode” field type in document type “AAMVA.DLID”."}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/aamvadliddriverlicenserestrictioncodefieldnormalizedname","navigatorTitle":[{"kind":"identifier","text":"aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName"}],"title":"aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKBarcodeDocumentModelConstants","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"op":"replace"},{"value":"aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName\/fragments","op":"replace","value":[{"kind":"identifier","text":"aamvaDLIDDriverLicenseRestrictionCodeFieldNormalizedName"}]}]}]}