{"abstract":[{"type":"text","text":"Normalized full name of the “DrugName” field type in document type “DEMedicalPlan.Subheading.Medicine”."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","title":"deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName","symbolKind":"property","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelConstants(cpy)deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants\/deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/demedicalplansubheadingmedicinedrugnamefieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/demedicalplansubheadingmedicinedrugnamefieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelConstants/deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName":{"abstract":[{"type":"text","text":"Normalized full name of the “DrugName” field type in document type “DEMedicalPlan.Subheading.Medicine”."}],"kind":"symbol","type":"topic","role":"symbol","title":"deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants\/deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/demedicalplansubheadingmedicinedrugnamefieldnormalizedname","navigatorTitle":[{"text":"deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelConstants":{"abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"title":"SBSDKBarcodeDocumentModelConstants","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants~1deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName\/title","value":"deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants~1deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName\/fragments","op":"replace","value":[{"text":"deMedicalPlanSubheadingMedicineDrugNameFieldNormalizedName","kind":"identifier"}]},{"op":"replace","value":"SBSDKBarcodeDocumentModelConstants","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/fragments","value":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}]}]}]}