{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/swissqradditionalinfotrailerfieldname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/swissqradditionalinfotrailerfieldname"]}],"abstract":[{"text":"Name of the “AdditionalInfoTrailer” field type in document type “SwissQR”.","type":"text"}],"metadata":{"roleHeading":"Type Property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelConstants(cpy)swissQRAdditionalInfoTrailerFieldName","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property","title":"swissQRAdditionalInfoTrailerFieldName","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"swissQRAdditionalInfoTrailerFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"swissQRAdditionalInfoTrailerFieldName","kind":"identifier"}]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"swissQRAdditionalInfoTrailerFieldName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants\/swissQRAdditionalInfoTrailerFieldName","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelConstants":{"abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"title":"SBSDKBarcodeDocumentModelConstants","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelConstants/swissQRAdditionalInfoTrailerFieldName":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"swissQRAdditionalInfoTrailerFieldName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"swissQRAdditionalInfoTrailerFieldName"}],"type":"topic","abstract":[{"text":"Name of the “AdditionalInfoTrailer” field type in document type “SwissQR”.","type":"text"}],"title":"swissQRAdditionalInfoTrailerFieldName","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/swissqradditionalinfotrailerfieldname","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants\/swissQRAdditionalInfoTrailerFieldName"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"swissQRAdditionalInfoTrailerFieldName","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"swissQRAdditionalInfoTrailerFieldName"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"swissQRAdditionalInfoTrailerFieldName","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/title","value":"SBSDKBarcodeDocumentModelConstants"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/navigatorTitle"},{"value":"swissQRAdditionalInfoTrailerFieldName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants~1swissQRAdditionalInfoTrailerFieldName\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants~1swissQRAdditionalInfoTrailerFieldName\/fragments","value":[{"kind":"identifier","text":"swissQRAdditionalInfoTrailerFieldName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}