{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeFromDisk","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","title":"removeFromDisk()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeFromDisk","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"symbolKind":"method","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKStorageLocation(im)removeFromDiskAndReturnError:","roleHeading":"Instance Method","navigatorTitle":[{"text":"removeFromDiskAndReturnError:","kind":"identifier"}]},"sections":[],"abstract":[{"type":"text","text":"Removes the receivers folder from the disk."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageLocation"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragelocation\/removefromdisk()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragelocation\/removefromdisk()"]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageLocation\/removeFromDisk()","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageLocation/removeFromDisk()":{"navigatorTitle":[{"text":"removeFromDiskAndReturnError:","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageLocation\/removeFromDisk()","title":"removeFromDisk()","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragelocation\/removefromdisk()","abstract":[{"type":"text","text":"Removes the receivers folder from the disk."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeFromDisk","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageLocation":{"title":"SBSDKStorageLocation","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageLocation","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragelocation","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageLocation"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStorageLocation"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Descriptor and helper class for describing and creating a directory on the file system."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.2","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeFromDiskAndReturnError:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeFromDiskAndReturnError:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"removeFromDiskAndReturnError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"removeFromDiskAndReturnError:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageLocation~1removeFromDisk()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageLocation~1removeFromDisk()\/fragments","value":[{"kind":"text","text":"- "},{"text":"removeFromDiskAndReturnError:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageLocation\/title","op":"replace","value":"SBSDKStorageLocation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageLocation\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageLocation"}]},{"value":[{"text":"SBSDKStorageLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageLocation\/navigatorTitle"}]}]}