{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier","text":"_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroScreenConfiguration"]]},"metadata":{"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorIntroScreenConfiguration(im)copyWithZone:","symbolKind":"method"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroscreenconfiguration\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroScreenConfiguration\/copyWithZone:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroScreenConfiguration":{"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroscreenconfiguration","type":"topic","abstract":[{"text":"Configuration of the introduction screen for the document data extractor.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorIntroScreenConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroScreenConfiguration","title":"SBSDKUI2DocumentDataExtractorIntroScreenConfiguration","navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorIntroScreenConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroScreenConfiguration/copyWithZone:":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroScreenConfiguration\/copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroscreenconfiguration\/copywithzone:","type":"topic","title":"copyWithZone:","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2DocumentDataExtractorIntroScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroScreenConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentDataExtractorIntroScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroScreenConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentDataExtractorIntroScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroScreenConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}