{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"counting","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleBarcodesScanningMode"]]},"abstract":[{"type":"text","text":"Scan barcodes even if they have the same value and count the number of repeated barcodes."}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplebarcodesscanningmode\/counting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplebarcodesscanningmode\/counting"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningModeCounting"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"counting","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2MultipleBarcodesScanningMode@SBSDKUI2MultipleBarcodesScanningModeCounting","title":"SBSDKUI2MultipleBarcodesScanningMode.counting"},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleBarcodesScanningMode\/counting","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleBarcodesScanningMode/counting":{"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplebarcodesscanningmode\/counting","kind":"symbol","title":"SBSDKUI2MultipleBarcodesScanningMode.counting","type":"topic","abstract":[{"type":"text","text":"Scan barcodes even if they have the same value and count the number of repeated barcodes."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleBarcodesScanningMode\/counting","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"counting","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningModeCounting"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleBarcodesScanningMode":{"type":"topic","title":"SBSDKUI2MultipleBarcodesScanningMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleBarcodesScanningMode","navigatorTitle":[{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Configuration of the mode used for scanning multiple barcodes.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplebarcodesscanningmode"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2MultipleBarcodesScanningModeCounting"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKUI2MultipleBarcodesScanningModeCounting","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKUI2MultipleBarcodesScanningModeCounting","kind":"identifier"}]}]},"op":"replace"},{"value":"SBSDKUI2MultipleBarcodesScanningModeCounting","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode~1counting\/title"},{"op":"replace","value":[{"text":"SBSDKUI2MultipleBarcodesScanningModeCounting","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode~1counting\/fragments"},{"op":"replace","value":"SBSDKUI2MultipleBarcodesScanningMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode\/fragments","value":[{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}