{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleBarcodesScanningMode\/unique","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unique"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleBarcodesScanningMode"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplebarcodesscanningmode\/unique"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplebarcodesscanningmode\/unique"]}],"abstract":[{"text":"Only scan barcodes with unique values. Subsequent barcodes with the same values will be ignored.","type":"text"}],"sections":[],"metadata":{"role":"symbol","roleHeading":"Case","title":"SBSDKUI2MultipleBarcodesScanningMode.unique","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningModeUnique"}],"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2MultipleBarcodesScanningMode@SBSDKUI2MultipleBarcodesScanningModeUnique","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unique","kind":"identifier"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleBarcodesScanningMode/unique":{"navigatorTitle":[{"text":"SBSDKUI2MultipleBarcodesScanningModeUnique","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"SBSDKUI2MultipleBarcodesScanningMode.unique","abstract":[{"text":"Only scan barcodes with unique values. Subsequent barcodes with the same values will be ignored.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplebarcodesscanningmode\/unique","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleBarcodesScanningMode\/unique","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unique","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleBarcodesScanningMode":{"type":"topic","title":"SBSDKUI2MultipleBarcodesScanningMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleBarcodesScanningMode","navigatorTitle":[{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Configuration of the mode used for scanning multiple barcodes.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplebarcodesscanningmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2MultipleBarcodesScanningModeUnique"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2MultipleBarcodesScanningModeUnique","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningModeUnique"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SBSDKUI2MultipleBarcodesScanningModeUnique","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode~1unique\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode~1unique\/fragments","op":"replace","value":[{"text":"SBSDKUI2MultipleBarcodesScanningModeUnique","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode\/title","op":"replace","value":"SBSDKUI2MultipleBarcodesScanningMode"},{"value":[{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode\/navigatorTitle","value":[{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}