{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/enablecamerauiconfiguration"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraUIConfiguration","text":"SBSDKUIEnableCameraUIConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIEnableCameraUIConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"enableCameraUIConfiguration"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/enableCameraUIConfiguration","interfaceLanguage":"occ"},"metadata":{"title":"enableCameraUIConfiguration","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"enableCameraUIConfiguration","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeScannerViewController(py)enableCameraUIConfiguration","fragments":[{"text":"enableCameraUIConfiguration","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller","navigatorTitle":[{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to scan QR and barcodes."}],"title":"SBSDKUIBarcodeScannerViewController","kind":"symbol","type":"topic","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.3"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/enableCameraUIConfiguration":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/enablecamerauiconfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/enableCameraUIConfiguration","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"enableCameraUIConfiguration","kind":"identifier"}],"type":"topic","title":"enableCameraUIConfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIEnableCameraUIConfiguration":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuienablecamerauiconfiguration","kind":"symbol","role":"symbol","abstract":[{"text":"Configuration for the user interface of camera based view controllers.","type":"text"}],"title":"SBSDKUIEnableCameraUIConfiguration","navigatorTitle":[{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraUIConfiguration"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController\/title","value":"SBSDKUIBarcodeScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraUIConfiguration\/title","value":"SBSDKUIEnableCameraUIConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraUIConfiguration\/fragments","value":[{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}