{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReorderPagesScreenConfiguration"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReorderPagesScreenConfiguration(im)initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:","title":"init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:)","symbolKind":"init","roleHeading":"Initializer","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"topBarBackButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":", "},{"text":"topBarTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topBarConfirmButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":", "},{"text":"backgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"guidance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration"},{"kind":"text","text":", "},{"text":"pageTextStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"topBarBackButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" = SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                            text: \"?reorderTopBarCancelButtonTitle\",\n                                                                                            accessibilityDescription: \"?accessibilityDescriptionReorderTopBarCancelButton\",\n                                                                                            background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                           isArgb: false),\n                                                                                                                                fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                                strokeWidth: 0.0),\n                                                                                            foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                                color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                                useShadow: false)), "},{"text":"topBarTitle","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText"},{"text":" = SBSDKUI2StyledText(text: \"?reorderPageTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)), ","kind":"text"},{"text":"topBarConfirmButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" = SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                               text: \"?reorderTopBarConfirmButtonTitle\",\n                                                                                               accessibilityDescription: \"?accessibilityDescriptionReorderTopBarConfirmButton\",\n                                                                                               background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                              isArgb: false),\n                                                                                                                                   fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                            isArgb: false),\n                                                                                                                                   strokeWidth: 0.0),\n                                                                                               foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                                   color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                        isArgb: false),\n                                                                                                                                   useShadow: false)), "},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" = SBSDKUI2Color(colorString: \"?sbColorOutline\", isArgb: false), ","kind":"text"},{"kind":"externalParam","text":"guidance"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","text":"SBSDKUI2UserGuidanceConfiguration"},{"text":" = SBSDKUI2UserGuidanceConfiguration(title: SBSDKUI2StyledText(text: \"?reorderPageGuidanceTitle\",\n                                                                                color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                     isArgb: false)),\n                                                      background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                     isArgb: false),\n                                                                                          fillColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceLow\",\n                                                                                                                   isArgb: false),\n                                                                                          strokeWidth: 0.0)), ","kind":"text"},{"text":"pageTextStyle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"text":" = SBSDKUI2StyledText(text: \"?reorderPageText\",\n                                                                       color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                            isArgb: false)))","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reorderpagesscreenconfiguration\/init(topbarbackbutton:topbartitle:topbarconfirmbutton:backgroundcolor:guidance:pagetextstyle:)"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reorderpagesscreenconfiguration\/init(topbarbackbutton:topbartitle:topbarconfirmbutton:backgroundcolor:guidance:pagetextstyle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReorderPagesScreenConfiguration\/init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:)"},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2StyledText":{"abstract":[{"text":"Configuration of the text field appearance.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"type":"topic","title":"SBSDKUI2StyledText","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2styledtext"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReorderPagesScreenConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}],"kind":"symbol","title":"SBSDKUI2ReorderPagesScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReorderPagesScreenConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reorderpagesscreenconfiguration","abstract":[{"type":"text","text":"Configuration of the screen for reordering the scanned pages."}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2UserGuidanceConfiguration":{"title":"SBSDKUI2UserGuidanceConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the hint guiding users through the scanning process."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidanceconfiguration","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReorderPagesScreenConfiguration/init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReorderPagesScreenConfiguration\/init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:)","title":"init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topBarBackButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":", "},{"text":"topBarTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":", "},{"text":"topBarConfirmButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"guidance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageTextStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reorderpagesscreenconfiguration\/init(topbarbackbutton:topbartitle:topbarconfirmbutton:backgroundcolor:guidance:pagetextstyle:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Color":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2Color"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2color","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}],"title":"SBSDKUI2Color","type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ButtonConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"abstract":[{"text":"Configuration of the button.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"role":"symbol","title":"SBSDKUI2ButtonConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2buttonconfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithTopBarBackButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" *) "},{"text":"topBarBackButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarTitle:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topBarTitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topBarConfirmButton:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"topBarConfirmButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"backgroundColor:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"backgroundColor"},{"kind":"text","text":" "},{"text":"guidance:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration"},{"kind":"text","text":" *) "},{"text":"guidance","kind":"internalParam"},{"kind":"text","text":" "},{"text":"pageTextStyle:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"pageTextStyle","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","value":"SBSDKUI2StyledText","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/title"},{"value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}]},{"op":"replace","value":"SBSDKUI2ReorderPagesScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2ReorderPagesScreenConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceConfiguration\/title","value":"SBSDKUI2UserGuidanceConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}]},{"value":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReorderPagesScreenConfiguration~1init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReorderPagesScreenConfiguration~1init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/navigatorTitle","value":[{"text":"SBSDKUI2Color","kind":"identifier"}]},{"op":"replace","value":"SBSDKUI2ButtonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}