{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroScreenConfiguration\/showAutomatically"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroScreenConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Determines whether the introduction screen should automatically be shown or not when the scanning session"},{"text":" ","type":"text"},{"type":"text","text":"starts."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"showAutomatically","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}]},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"Default is false","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroscreenconfiguration\/showautomatically"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroscreenconfiguration\/showautomatically"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showAutomatically"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","title":"showAutomatically","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerIntroScreenConfiguration(py)showAutomatically","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"showAutomatically"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerIntroScreenConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroScreenConfiguration","abstract":[{"text":"Configuration of the introduction screen for the generic text scanner.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroscreenconfiguration","role":"symbol","title":"SBSDKUI2TextPatternScannerIntroScreenConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerIntroScreenConfiguration/showAutomatically":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showAutomatically"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"Determines whether the introduction screen should automatically be shown or not when the scanning session","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"starts."}],"title":"showAutomatically","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroscreenconfiguration\/showautomatically","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroScreenConfiguration\/showAutomatically","role":"symbol","type":"topic","navigatorTitle":[{"text":"showAutomatically","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"showAutomatically","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"showAutomatically","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showAutomatically"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUI2TextPatternScannerIntroScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroScreenConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroScreenConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroScreenConfiguration~1showAutomatically\/title","value":"showAutomatically","op":"replace"},{"value":[{"text":"showAutomatically","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroScreenConfiguration~1showAutomatically\/fragments"}]}]}