{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzScanningViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIMRZScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerViewController"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","isActive":true,"type":"reference"},{"type":"text","text":" that did dismiss."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Optional.","type":"text"}]}],"style":"note","name":"Note","type":"aside"}]}],"metadata":{"title":"mrzScanningViewControllerDidCancel(_:)","navigatorTitle":[{"text":"mrzScanningViewControllerDidCancel:","kind":"identifier"}],"platforms":[],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIMRZScannerViewControllerDelegate(im)mrzScanningViewControllerDidCancel:","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzScanningViewControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIMRZScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewControllerDelegate"]]},"sections":[],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2MRZScannerViewController instead."}],"type":"paragraph"}],"abstract":[{"text":"informs the delegate that the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","type":"reference","isActive":true},{"text":" has been cancelled and dismissed.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewControllerDelegate\/mrzScanningViewControllerDidCancel(_:)"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontrollerdelegate\/mrzscanningviewcontrollerdidcancel(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontrollerdelegate\/mrzscanningviewcontrollerdidcancel(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","abstract":[{"text":"A highly customizable camera-based view controller to detect machine readable zones.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}],"title":"SBSDKUIMRZScannerViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}],"deprecated":true,"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewControllerDelegate/mrzScanningViewControllerDidCancel(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewControllerDelegate\/mrzScanningViewControllerDidCancel(_:)","abstract":[{"text":"informs the delegate that the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","type":"reference","isActive":true},{"type":"text","text":" has been cancelled and dismissed."}],"url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontrollerdelegate\/mrzscanningviewcontrollerdidcancel(_:)","navigatorTitle":[{"kind":"identifier","text":"mrzScanningViewControllerDidCancel:"}],"title":"mrzScanningViewControllerDidCancel(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzScanningViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUIMRZScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerViewController"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewControllerDelegate":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewControllerDelegate","deprecated":true,"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIMRZScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIMRZScannerViewControllerDelegate","kind":"identifier"}],"abstract":[{"text":"Delegate protocol for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController"},{"text":".","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontrollerdelegate","title":"SBSDKUIMRZScannerViewControllerDelegate","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"mrzScanningViewControllerDidCancel:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mrzScanningViewControllerDidCancel:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"mrzScanningViewControllerDidCancel:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIMRZScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","isActive":true},{"type":"text","text":" that did dismiss."}]}],"name":"viewController"}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/title","value":"SBSDKUIMRZScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/fragments","value":[{"text":"SBSDKUIMRZScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUIMRZScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewControllerDelegate~1mrzScanningViewControllerDidCancel(_:)\/title","value":"mrzScanningViewControllerDidCancel:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewControllerDelegate~1mrzScanningViewControllerDidCancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mrzScanningViewControllerDidCancel:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewControllerDelegate\/title","value":"SBSDKUIMRZScannerViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewControllerDelegate\/fragments","value":[{"text":"SBSDKUIMRZScannerViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKUIMRZScannerViewControllerDelegate","kind":"identifier"}]}]}]}