{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKUpcEanExtensionBehavior.allowAny","role":"symbol","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKUpcEanExtensionBehavior@SBSDKUpcEanExtensionBehaviorAllowAny","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehaviorAllowAny"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowAny"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior\/allowany"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior\/allowany"]}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowAny"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior\/allowAny"},"abstract":[{"type":"text","text":"Return any detected extension if present, but do not require it."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUpcEanExtensionBehavior/allowAny":{"type":"topic","abstract":[{"type":"text","text":"Return any detected extension if present, but do not require it."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"allowAny","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior\/allowany","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior\/allowAny","navigatorTitle":[{"text":"SBSDKUpcEanExtensionBehaviorAllowAny","kind":"identifier"}],"title":"SBSDKUpcEanExtensionBehavior.allowAny"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUpcEanExtensionBehavior":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior","abstract":[{"type":"text","text":"Behavior when scanning UPC\/EAN barcodes with EAN-2 or EAN-5 extensions."}],"url":"\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior","role":"symbol","title":"SBSDKUpcEanExtensionBehavior","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"SBSDKUpcEanExtensionBehaviorAllowAny","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehaviorAllowAny"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehaviorAllowAny"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior~1allowAny\/title","value":"SBSDKUpcEanExtensionBehaviorAllowAny","op":"replace"},{"value":[{"text":"SBSDKUpcEanExtensionBehaviorAllowAny","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior~1allowAny\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/title","value":"SBSDKUpcEanExtensionBehavior","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/fragments","value":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/navigatorTitle","value":[{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"op":"replace"}]}]}