{"abstract":[{"text":"The encryption mode for stored files. Defaults to ","type":"text"},{"type":"codeVoice","code":".AES128"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/fileencryptionmode"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/fileencryptionmode"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"fileEncryptionMode","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)ScanbotSDKConfiguration(py)fileEncryptionMode","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fileEncryptionMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKAESEncrypterMode","text":"SBSDKAESEncrypterMode"}],"symbolKind":"property","navigatorTitle":[{"text":"fileEncryptionMode","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileEncryptionMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKAESEncrypterMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESEncrypterMode","text":"SBSDKAESEncrypterMode","kind":"typeIdentifier"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration\/fileEncryptionMode"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAESEncrypter":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESEncrypter","title":"SBSDKAESEncrypter","kind":"symbol","abstract":[{"text":"ScanbotSDK’s default data encrypter. Provides AES128 and AES 256 encryption to your data.","type":"text"},{"text":" ","type":"text"},{"text":"All data is encrypted and decrypted with the same key.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The context being passed to the encrypt\/decrypt methods is ignored."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAESEncrypter","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaesencrypter","navigatorTitle":[{"text":"SBSDKAESEncrypter","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotSDKConfiguration/fileEncryptionMode":{"title":"fileEncryptionMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration\/fileEncryptionMode","navigatorTitle":[{"kind":"identifier","text":"fileEncryptionMode"}],"url":"\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/fileencryptionmode","kind":"symbol","abstract":[{"type":"text","text":"The encryption mode for stored files. Defaults to "},{"code":".AES128","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileEncryptionMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKAESEncrypterMode","text":"SBSDKAESEncrypterMode"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotSDKConfiguration":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanbotSDKConfiguration"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration","title":"ScanbotSDKConfiguration","navigatorTitle":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"ScanbotSDKConfiguration"},{"type":"text","text":" is a configuration class that allows you to customize various settings and behavior of the Scanbot SDK."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAESEncrypterMode":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaesencryptermode","navigatorTitle":[{"text":"SBSDKAESEncrypterMode","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum containing the available encryption modes for the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESEncrypter","isActive":true},{"type":"text","text":"."}],"title":"SBSDKAESEncrypterMode","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESEncrypterMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAESEncrypterMode","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"fileEncryptionMode"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"fileEncryptionMode"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKAESEncrypterMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESEncrypterMode","text":"SBSDKAESEncrypterMode","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"fileEncryptionMode","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKAESEncrypter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESEncrypter\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESEncrypter\/fragments","value":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESEncrypter\/navigatorTitle","op":"replace"},{"value":"fileEncryptionMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration~1fileEncryptionMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"fileEncryptionMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration~1fileEncryptionMode\/fragments"},{"value":"ScanbotSDKConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/fragments"},{"value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESEncrypterMode\/title","op":"replace","value":"SBSDKAESEncrypterMode"},{"value":[{"kind":"identifier","text":"SBSDKAESEncrypterMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESEncrypterMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAESEncrypterMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESEncrypterMode\/navigatorTitle"}]}]}