{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"deleteKeyForContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"context"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"keyLength","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKStorageCryptingKeyLength","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"context","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The context to generate or load the key for. For most applications in Scanbot SDK the context is derived from the URL of the file to encrypted or decrypted by calling the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/Foundation\/URL\/sbsdk_encryptionContext"},{"text":" property on the URL.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"The length of the key to be deleted.","type":"text"}],"type":"paragraph"}],"name":"keyLength"}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"true"},{"text":" if a key was found and deleted, ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" otherwise.","type":"text"}]}],"kind":"content"}],"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKVolatileKeyProvider(im)deleteKeyForContext:keyLength:","navigatorTitle":[{"text":"deleteKeyForContext:keyLength:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteKeyForContext","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"keyLength","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKStorageCryptingKeyLength","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKStorageCryptingKeyLength"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Method","title":"deleteKeyForContext(_:keyLength:)"},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVolatileKeyProvider\/deleteKeyForContext(_:keyLength:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVolatileKeyProvider"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvolatilekeyprovider\/deletekeyforcontext(_:keylength:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvolatilekeyprovider\/deletekeyforcontext(_:keylength:)"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Deletes the key for the given context and key length."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVolatileKeyProvider/deleteKeyForContext(_:keyLength:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVolatileKeyProvider\/deleteKeyForContext(_:keyLength:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvolatilekeyprovider\/deletekeyforcontext(_:keylength:)","kind":"symbol","abstract":[{"type":"text","text":"Deletes the key for the given context and key length."}],"type":"topic","title":"deleteKeyForContext(_:keyLength:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"deleteKeyForContext:keyLength:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteKeyForContext"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"keyLength","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/Foundation/URL/sbsdk_encryptionContext":{"abstract":[{"text":"The encryption context of the URL.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/foundation\/url\/sbsdk_encryptioncontext","role":"symbol","title":"sbsdk_encryptionContext","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sbsdk_encryptionContext"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/Foundation\/URL\/sbsdk_encryptionContext"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVolatileKeyProvider":{"abstract":[{"text":"A volatile key provider that generates and stores keys in memory.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvolatilekeyprovider","role":"symbol","navigatorTitle":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"title":"SBSDKVolatileKeyProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVolatileKeyProvider"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingKeyLength":{"role":"symbol","abstract":[{"text":"The length of the encryption key.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeylength","title":"SBSDKStorageCryptingKeyLength","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"deleteKeyForContext:keyLength:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteKeyForContext:keyLength:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"deleteKeyForContext:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"context"},{"kind":"text","text":" "},{"text":"keyLength:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength"},{"text":") ","kind":"text"},{"text":"keyLength","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"context","content":[{"type":"paragraph","inlineContent":[{"text":"The context to generate or load the key for. For most applications in Scanbot SDK the context is derived from the URL of the file to encrypted or decrypted by calling the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/Foundation\/URL\/sbsdk_encryptionContext"},{"type":"text","text":" property on the URL."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The length of the key to be deleted."}]}],"name":"keyLength"}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":""},{"code":"true","type":"codeVoice"},{"text":" if a key was found and deleted, ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" otherwise.","type":"text"}],"type":"paragraph"}]}},{"value":"deleteKeyForContext:keyLength:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVolatileKeyProvider~1deleteKeyForContext(_:keyLength:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVolatileKeyProvider~1deleteKeyForContext(_:keyLength:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"deleteKeyForContext:keyLength:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVolatileKeyProvider\/title","op":"replace","value":"SBSDKVolatileKeyProvider"},{"op":"replace","value":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVolatileKeyProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVolatileKeyProvider\/navigatorTitle","value":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength\/title","value":"SBSDKStorageCryptingKeyLength","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}]}]}]}