{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvolatilekeyprovider\/keygenerator"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvolatilekeyprovider\/keygenerator"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVolatileKeyProvider"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVolatileKeyProvider\/keyGenerator"},"metadata":{"role":"symbol","title":"keyGenerator","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"keyGenerator","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKStorageCryptingKeyGenerator","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCryptingKeyGenerator"}],"symbolKind":"property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKVolatileKeyProvider(py)keyGenerator","navigatorTitle":[{"kind":"identifier","text":"keyGenerator"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"abstract":[{"type":"text","text":"The key generator that generates an encryption key for a context if no key is available yet."}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"keyGenerator","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyGenerator","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCryptingKeyGenerator","kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyGenerator"}]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingKeyGenerator":{"abstract":[{"text":"Protocol for generating encryption keys.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyGenerator","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeygenerator","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"title":"SBSDKStorageCryptingKeyGenerator"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVolatileKeyProvider":{"abstract":[{"text":"A volatile key provider that generates and stores keys in memory.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvolatilekeyprovider","role":"symbol","navigatorTitle":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"title":"SBSDKVolatileKeyProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVolatileKeyProvider"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVolatileKeyProvider/keyGenerator":{"kind":"symbol","abstract":[{"type":"text","text":"The key generator that generates an encryption key for a context if no key is available yet."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvolatilekeyprovider\/keygenerator","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVolatileKeyProvider\/keyGenerator","navigatorTitle":[{"text":"keyGenerator","kind":"identifier"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyGenerator","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCryptingKeyGenerator","kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyGenerator"}],"role":"symbol","title":"keyGenerator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"keyGenerator","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"keyGenerator","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"id<SBSDKStorageCryptingKeyGenerator>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCryptingKeyGenerator"},{"text":" ","kind":"text"},{"text":"keyGenerator","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyGenerator\/title","value":"SBSDKStorageCryptingKeyGenerator","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyGenerator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyGenerator\/fragments"},{"value":[{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyGenerator\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVolatileKeyProvider\/title","value":"SBSDKVolatileKeyProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVolatileKeyProvider\/fragments","value":[{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVolatileKeyProvider\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}]},{"value":"keyGenerator","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVolatileKeyProvider~1keyGenerator\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVolatileKeyProvider~1keyGenerator\/fragments","value":[{"text":"keyGenerator","kind":"identifier"}]}]}]}