{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignoreOrientationMismatch"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerBehaviorConfiguration\/ignoreOrientationMismatch","interfaceLanguage":"swift"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerbehaviorconfiguration\/ignoreorientationmismatch"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerbehaviorconfiguration\/ignoreorientationmismatch"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"ignoreOrientationMismatch","roleHeading":"Instance Property","platforms":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ignoreOrientationMismatch","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"symbolKind":"property","navigatorTitle":[{"text":"ignoreOrientationMismatch","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerBehaviorConfiguration(py)ignoreOrientationMismatch"},"sections":[],"abstract":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"true"},{"text":", ignores the orientation mismatch warning.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerBehaviorConfiguration"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerBehaviorConfiguration":{"type":"topic","kind":"symbol","title":"SBSDKUIDocumentScannerBehaviorConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}],"deprecated":true,"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerbehaviorconfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerBehaviorConfiguration","navigatorTitle":[{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration for the behavior of the document scanning screen.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerBehaviorConfiguration/ignoreOrientationMismatch":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerbehaviorconfiguration\/ignoreorientationmismatch","navigatorTitle":[{"text":"ignoreOrientationMismatch","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerBehaviorConfiguration\/ignoreOrientationMismatch","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ignoreOrientationMismatch"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"ignoreOrientationMismatch","deprecated":true,"abstract":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"true"},{"text":", ignores the orientation mismatch warning.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"ignoreOrientationMismatch","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"ignoreOrientationMismatch","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ignoreOrientationMismatch"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/title","value":"SBSDKUIDocumentScannerBehaviorConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration~1ignoreOrientationMismatch\/title","value":"ignoreOrientationMismatch","op":"replace"},{"value":[{"kind":"identifier","text":"ignoreOrientationMismatch"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration~1ignoreOrientationMismatch\/fragments"}]}]}