{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","title":"hash","symbolKind":"property","fragments":[{"text":"hash","kind":"identifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"hash"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2AspectRatio(py)hash","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AspectRatio"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aspectratio\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AspectRatio\/hash","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2AspectRatio/hash":{"abstract":[],"role":"symbol","title":"hash","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AspectRatio\/hash","kind":"symbol","type":"topic","fragments":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aspectratio\/hash"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2AspectRatio":{"title":"SBSDKUI2AspectRatio","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aspectratio","abstract":[{"text":"Configuration of the finder’s aspect ratio.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AspectRatio","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AspectRatio"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AspectRatio"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","kind":"symbol","title":"ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2AspectRatio","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AspectRatio\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2AspectRatio"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AspectRatio\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2AspectRatio","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AspectRatio\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}