{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport\/hash","interfaceLanguage":"occ"},"metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSuspiciousDataVerificationReport(py)hash","roleHeading":"Instance Property","fragments":[{"text":"hash","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdksuspiciousdataverificationreport\/hash"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSuspiciousDataVerificationReport":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdksuspiciousdataverificationreport","title":"SBSDKSuspiciousDataVerificationReport","abstract":[{"type":"text","text":"Report of the suspicious data document verification."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSuspiciousDataVerificationReport","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKSuspiciousDataVerificationReport","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSuspiciousDataVerificationReport/hash":{"abstract":[],"type":"topic","title":"hash","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdksuspiciousdataverificationreport\/hash","fragments":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport\/hash","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKSuspiciousDataVerificationReport","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport\/title"},{"value":[{"text":"SBSDKSuspiciousDataVerificationReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport\/fragments"},{"value":[{"text":"SBSDKSuspiciousDataVerificationReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport\/navigatorTitle"}]}]}