{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScanner"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScanner\/scan(from:)-42p03","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"scanTextLineFromFrame:"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"title":"scan(from:)","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScanner(im)scanTextLineFromFrame:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBaseScannerFrame","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerFrame","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKTextPatternScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Scans text information on the given ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame","isActive":true,"type":"reference"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(scanTextLineFromFrame:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"frame","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBaseScannerFrame","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerFrame"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","text":"SBSDKTextPatternScannerResult"},{"kind":"text","text":"?"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"frame","content":[{"type":"paragraph","inlineContent":[{"text":"The frame to be scanned.","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The result of the scan.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscanner\/scan(from:)-42p03"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscanner\/scan(from:)-42p03"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScanner/scan(from:)-42p03":{"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscanner\/scan(from:)-42p03","kind":"symbol","abstract":[{"text":"Scans text information on the given ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame"},{"text":".","type":"text"}],"role":"symbol","title":"scan(from:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBaseScannerFrame","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerFrame"},{"text":") -> ","kind":"text"},{"text":"SBSDKTextPatternScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"scanTextLineFromFrame:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScanner\/scan(from:)-42p03"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerResult":{"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"title":"SBSDKTextPatternScannerResult","abstract":[{"text":"The result of the text line recognition.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScanner":{"type":"topic","abstract":[{"text":"A class to scan one line of text on various image sources in a small area and run a validation on the result.","type":"text"},{"text":" ","type":"text"},{"text":"The validation is configurable and ranges from string pattern validation, preset based validation (e.g. vehicle identification numbers) to custom validation using functions.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextPatternScanner","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscanner","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScanner","title":"SBSDKTextPatternScanner","navigatorTitle":[{"text":"SBSDKTextPatternScanner","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerFrame":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerFrame","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBaseScannerFrame","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A wrapper class for video frames."}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerframe","title":"SBSDKBaseScannerFrame"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"scanTextLineFromFrame:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"scanTextLineFromFrame:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","text":"SBSDKTextPatternScannerResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"scanTextLineFromFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerFrame","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame","text":"SBSDKBaseScannerFrame","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"frame","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"The frame to be scanned.","type":"text"}],"type":"paragraph"}],"name":"frame"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The result of the scan.","type":"text"}]}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner~1scan(from:)-42p03\/title","value":"scanTextLineFromFrame:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner~1scan(from:)-42p03\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scanTextLineFromFrame:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/title","value":"SBSDKTextPatternScannerResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/fragments","value":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/navigatorTitle","value":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner\/title","value":"SBSDKTextPatternScanner","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner\/fragments","value":[{"text":"SBSDKTextPatternScanner","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner\/navigatorTitle","value":[{"text":"SBSDKTextPatternScanner","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerFrame\/title","value":"SBSDKBaseScannerFrame","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerFrame\/fragments","value":[{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerFrame\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}