{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatRoyalMailConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatRoyalMailConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatRoyalMailConfiguration"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatRoyalMailConfiguration"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatRoyalMailConfiguration","kind":"typeIdentifier","text":"SBSDKBarcodeFormatRoyalMailConfiguration"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"s:10ScanbotSDK35SBSDKBarcodeFormatConfigurationBaseC07barcoded9RoyalMailE0AA0cdhiE0CyFZ","title":"barcodeFormatRoyalMailConfiguration()","roleHeading":"Type Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatRoyalMailConfiguration()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatroyalmailconfiguration()"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatRoyalMailConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatroyalmailconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalMailConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration","kind":"symbol","role":"symbol","title":"SBSDKBarcodeFormatRoyalMailConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalMailConfiguration"}],"type":"topic","abstract":[{"type":"text","text":"Royal Mail barcode configuration. Add to scanner configuration to scan Royal Mail (a.k.a. RM4SCC, CBC, BPO 4-State) barcodes."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"abstract":[{"type":"text","text":"Base class for all barcode configurations."}],"title":"SBSDKBarcodeFormatConfigurationBase","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatRoyalMailConfiguration()":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatroyalmailconfiguration()","title":"barcodeFormatRoyalMailConfiguration()","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatRoyalMailConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatRoyalMailConfiguration","text":"SBSDKBarcodeFormatRoyalMailConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatRoyalMailConfiguration()","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalMailConfiguration\/title","value":"SBSDKBarcodeFormatRoyalMailConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalMailConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalMailConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalMailConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormatRoyalMailConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/title","op":"replace","value":"SBSDKBarcodeFormatConfigurationBase"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}]}]}]}