{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization(py)croppingTopBarConfirmButtonTitle","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"croppingTopBarConfirmButtonTitle","navigatorTitle":[{"text":"croppingTopBarConfirmButtonTitle","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"croppingTopBarConfirmButtonTitle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"abstract":[{"text":"The ‘confirm’ button title, located in the top bar of the cropping screen.","type":"text"},{"type":"text","text":" "},{"text":"Default is “Done”","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/croppingtopbarconfirmbuttontitle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/croppingtopbarconfirmbuttontitle"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingTopBarConfirmButtonTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/croppingTopBarConfirmButtonTitle","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of all the strings for the standalone cropping screen."}],"title":"SBSDKUI2DocumentScannerTextLocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization/croppingTopBarConfirmButtonTitle":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"croppingTopBarConfirmButtonTitle","kind":"identifier"}],"abstract":[{"text":"The ‘confirm’ button title, located in the top bar of the cropping screen.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is “Done”"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"croppingTopBarConfirmButtonTitle"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/croppingTopBarConfirmButtonTitle","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/croppingtopbarconfirmbuttontitle","title":"croppingTopBarConfirmButtonTitle","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"croppingTopBarConfirmButtonTitle","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"croppingTopBarConfirmButtonTitle"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"croppingTopBarConfirmButtonTitle","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/title","value":"SBSDKUI2DocumentScannerTextLocalization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments","value":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization~1croppingTopBarConfirmButtonTitle\/title","value":"croppingTopBarConfirmButtonTitle"},{"op":"replace","value":[{"kind":"identifier","text":"croppingTopBarConfirmButtonTitle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization~1croppingTopBarConfirmButtonTitle\/fragments"}]}]}