{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/init(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"barcodeFormats","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat","text":"SBSDKBarcodeFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormat"},{"text":"], ","kind":"text"},{"text":"extractedDocumentFormats","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKBarcodeDocumentFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentFormat"},{"text":"] = [], ","kind":"text"},{"kind":"externalParam","text":"onlyAcceptDocuments"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"barcodeFormats","content":[{"inlineContent":[{"type":"text","text":"The barcode formats to be scanned."}],"type":"paragraph"}]},{"name":"extractedDocumentFormats","content":[{"type":"paragraph","inlineContent":[{"text":"List of document formats to be extracted.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"If true and extractedDocumentFormats is not empty, then barcodes that don’t decode to one of the extracted document formats will be ignored.","type":"text"}],"type":"paragraph"}],"name":"onlyAcceptDocuments"}]}],"metadata":{"externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKBarcodeScannerConfiguration(im)initWithBarcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"barcodeFormats","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKBarcodeFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat"},{"text":"], ","kind":"text"},{"text":"extractedDocumentFormats","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKBarcodeDocumentFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat"},{"text":"], ","kind":"text"},{"text":"onlyAcceptDocuments","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)","roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"role":"symbol","extendedModule":"ScanbotSDK","navigatorTitle":[{"text":"initWithBarcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:","kind":"identifier"}],"symbolKind":"init"},"sections":[],"abstract":[{"type":"text","text":"Convenience initializer."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/init(barcodeformats:extracteddocumentformats:onlyacceptdocuments:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/init(barcodeformats:extracteddocumentformats:onlyacceptdocuments:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormat":{"title":"SBSDKBarcodeFormat","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformat","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormat","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormat"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"Enumerates barcode formats."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration":{"title":"SBSDKBarcodeScannerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"navigatorTitle":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration","abstract":[{"text":"Configuration for the barcode scanner.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentFormat":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentFormat","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentFormat","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentFormat","title":"SBSDKBarcodeDocumentFormat","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentformat","abstract":[{"text":"Type of barcode document format used.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/init(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"barcodeFormats","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat","text":"SBSDKBarcodeFormat"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"extractedDocumentFormats"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat","text":"SBSDKBarcodeDocumentFormat"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"onlyAcceptDocuments"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"type":"text","text":"Convenience initializer."}],"type":"topic","title":"init(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/init(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/init(barcodeformats:extracteddocumentformats:onlyacceptdocuments:)","navigatorTitle":[{"text":"initWithBarcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithBarcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithBarcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithBarcodeFormats:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKBarcodeFormat *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"barcodeFormats"},{"kind":"text","text":" "},{"text":"extractedDocumentFormats:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBarcodeDocumentFormat *>"},{"text":" *) ","kind":"text"},{"text":"extractedDocumentFormats","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"onlyAcceptDocuments:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onlyAcceptDocuments","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The barcode formats to be scanned."}]}],"name":"barcodeFormats"},{"content":[{"inlineContent":[{"type":"text","text":"List of document formats to be extracted."}],"type":"paragraph"}],"name":"extractedDocumentFormats"},{"content":[{"inlineContent":[{"text":"If true and extractedDocumentFormats is not empty, then barcodes that don’t decode to one of the extracted document formats will be ignored.","type":"text"}],"type":"paragraph"}],"name":"onlyAcceptDocuments"}]}},{"op":"replace","value":"SBSDKBarcodeFormat","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/title"},{"value":[{"text":"SBSDKBarcodeFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormat"}]},{"op":"replace","value":"SBSDKBarcodeScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentFormat\/title","value":"SBSDKBarcodeDocumentFormat"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentFormat\/fragments","value":[{"text":"SBSDKBarcodeDocumentFormat","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentFormat"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentFormat\/navigatorTitle"},{"op":"replace","value":"initWithBarcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1init(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1init(barcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithBarcodeFormats:extractedDocumentFormats:onlyAcceptDocuments:","kind":"identifier"}]}]}]}