{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StatusBarMode"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StatusBarMode\/light","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"text":"Display all icons in the status bar in white.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2statusbarmode\/light"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2statusbarmode\/light"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"light"}],"navigatorTitle":[{"text":"SBSDKUI2StatusBarModeLight","kind":"identifier"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2StatusBarMode@SBSDKUI2StatusBarModeLight","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKUI2StatusBarMode.light"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"light"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StatusBarMode/light":{"navigatorTitle":[{"text":"SBSDKUI2StatusBarModeLight","kind":"identifier"}],"abstract":[{"text":"Display all icons in the status bar in white.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2statusbarmode\/light","kind":"symbol","role":"symbol","type":"topic","title":"SBSDKUI2StatusBarMode.light","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"light","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StatusBarMode\/light"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StatusBarMode":{"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StatusBarMode","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2StatusBarMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2statusbarmode","title":"SBSDKUI2StatusBarMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StatusBarMode","abstract":[{"type":"text","text":"The visual mode used for the status bar icons."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKUI2StatusBarModeLight","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2StatusBarModeLight"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKUI2StatusBarModeLight","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StatusBarMode~1light\/title","value":"SBSDKUI2StatusBarModeLight","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StatusBarMode~1light\/fragments","value":[{"text":"SBSDKUI2StatusBarModeLight","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StatusBarMode\/title","op":"replace","value":"SBSDKUI2StatusBarMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StatusBarMode\/fragments","op":"replace","value":[{"text":"SBSDKUI2StatusBarMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StatusBarMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2StatusBarMode"}]}]}]}