{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"issueDateSemantics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics","text":"SBSDKCompositeFieldValueSemantics","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompositeFieldValueSemantics"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Status of the issue date semantics verification. Shows whether the issue date in the document is in the past.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/issuedatesemantics"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/issuedatesemantics"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSemanticsVerificationReport(py)issueDateSemantics","title":"issueDateSemantics","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"issueDateSemantics"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issueDateSemantics","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCompositeFieldValueSemantics","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompositeFieldValueSemantics"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/issueDateSemantics"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport":{"navigatorTitle":[{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport","role":"symbol","abstract":[{"type":"text","text":"Report of the document value semantics verification."}],"url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport","type":"topic","kind":"symbol","title":"SBSDKSemanticsVerificationReport"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCompositeFieldValueSemantics":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Report of a logical field value semantics verification. If some logical field, e.g. expiry date is present in multiple places in the document, it can occur that some entries are semantically correct and some are semantically incorrect. This report shows the overall status of the logical field value semantics verification and details for each field that was verified."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKCompositeFieldValueSemantics","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcompositefieldvaluesemantics","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCompositeFieldValueSemantics","kind":"identifier"}],"title":"SBSDKCompositeFieldValueSemantics","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/issueDateSemantics":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/issueDateSemantics","navigatorTitle":[{"kind":"identifier","text":"issueDateSemantics"}],"abstract":[{"text":"Status of the issue date semantics verification. Shows whether the issue date in the document is in the past.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/issuedatesemantics","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"issueDateSemantics"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompositeFieldValueSemantics","kind":"typeIdentifier","text":"SBSDKCompositeFieldValueSemantics"}],"kind":"symbol","role":"symbol","title":"issueDateSemantics"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"issueDateSemantics"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"issueDateSemantics"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompositeFieldValueSemantics","text":"SBSDKCompositeFieldValueSemantics","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics"},{"kind":"text","text":" * "},{"kind":"identifier","text":"issueDateSemantics"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/title","value":"SBSDKSemanticsVerificationReport"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/fragments","value":[{"kind":"identifier","text":"SBSDKSemanticsVerificationReport"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKSemanticsVerificationReport"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompositeFieldValueSemantics\/title","value":"SBSDKCompositeFieldValueSemantics"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompositeFieldValueSemantics\/fragments","value":[{"text":"SBSDKCompositeFieldValueSemantics","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompositeFieldValueSemantics\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCompositeFieldValueSemantics"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1issueDateSemantics\/title","value":"issueDateSemantics"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1issueDateSemantics\/fragments","value":[{"kind":"identifier","text":"issueDateSemantics"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}