{"metadata":{"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"title":"scan(from:orientation:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"scanFromSampleBuffer:orientation:"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScanner(im)scanFromSampleBuffer:orientation:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scan"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"kind":"text","text":", "},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation"},{"text":") -> ","kind":"text"},{"text":"SBSDKTextPatternScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult"},{"kind":"text","text":"?"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScanner"]]},"abstract":[{"text":"Scans text information on the given ","type":"text"},{"code":"CMSampleBuffer","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(scanFromSampleBuffer:orientation:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scan"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sampleBuffer","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation","text":"SBSDKVideoOrientation","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","text":"SBSDKTextPatternScannerResult"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The sample buffer to be scanned.","type":"text"}]}],"name":"sampleBuffer"},{"name":"orientation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The orientation of the sample buffer."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the scan."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscanner\/scan(from:orientation:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscanner\/scan(from:orientation:)"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScanner\/scan(from:orientation:)"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScanner":{"role":"symbol","navigatorTitle":[{"text":"SBSDKTextPatternScanner","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKTextPatternScanner","kind":"identifier"}],"type":"topic","title":"SBSDKTextPatternScanner","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscanner","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScanner","abstract":[{"text":"A class to scan one line of text on various image sources in a small area and run a validation on the result.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The validation is configurable and ranges from string pattern validation, preset based validation (e.g. vehicle identification numbers) to custom validation using functions."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScanner/scan(from:orientation:)":{"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscanner\/scan(from:orientation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation","text":"SBSDKVideoOrientation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","text":"SBSDKTextPatternScannerResult"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScanner\/scan(from:orientation:)","title":"scan(from:orientation:)","abstract":[{"type":"text","text":"Scans text information on the given "},{"type":"codeVoice","code":"CMSampleBuffer"},{"text":".","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"scanFromSampleBuffer:orientation:"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerResult":{"type":"topic","abstract":[{"type":"text","text":"The result of the text line recognition."}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"title":"SBSDKTextPatternScannerResult","navigatorTitle":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation":{"type":"topic","title":"SBSDKVideoOrientation","abstract":[{"text":"An enum describing the orientation of a video frame.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKVideoOrientation"}],"navigatorTitle":[{"text":"SBSDKVideoOrientation","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"scanFromSampleBuffer:orientation:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scanFromSampleBuffer:orientation:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","text":"SBSDKTextPatternScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"scanFromSampleBuffer:"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"opaqueCMSampleBuffer","preciseIdentifier":"c:@S@opaqueCMSampleBuffer"},{"kind":"text","text":" *) "},{"text":"sampleBuffer","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientation:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation","text":"SBSDKVideoOrientation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation"},{"text":") ","kind":"text"},{"text":"orientation","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":{"parameters":[{"name":"sampleBuffer","content":[{"type":"paragraph","inlineContent":[{"text":"The sample buffer to be scanned.","type":"text"}]}]},{"name":"orientation","content":[{"type":"paragraph","inlineContent":[{"text":"The orientation of the sample buffer.","type":"text"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the scan."}]}]},"op":"replace","path":"\/primaryContentSections\/2"},{"op":"replace","value":"SBSDKTextPatternScanner","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner\/title"},{"op":"replace","value":[{"text":"SBSDKTextPatternScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKTextPatternScanner"}]},{"value":"scanFromSampleBuffer:orientation:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner~1scan(from:orientation:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScanner~1scan(from:orientation:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"scanFromSampleBuffer:orientation:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/title","value":"SBSDKTextPatternScannerResult"},{"value":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/navigatorTitle","op":"replace","value":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/title","op":"replace","value":"SBSDKVideoOrientation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/fragments","op":"replace","value":[{"text":"SBSDKVideoOrientation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}],"op":"replace"}]}]}