{"abstract":[{"type":"text","text":"Normalized full name of the “FirstOwnerLastName” field type in document type “AAMVA.VehicleOwnerData”."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelConstants(cpy)aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName","title":"aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName","navigatorTitle":[{"kind":"identifier","text":"aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName"}],"symbolKind":"property","roleHeading":"Type Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvavehicleownerdatafirstownerlastnamefieldnormalizedname"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvavehicleownerdatafirstownerlastnamefieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants/aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName":{"abstract":[{"type":"text","text":"Normalized full name of the “FirstOwnerLastName” field type in document type “AAMVA.VehicleOwnerData”."}],"navigatorTitle":[{"text":"aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvavehicleownerdatafirstownerlastnamefieldnormalizedname","type":"topic","role":"symbol","title":"aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants":{"title":"SBSDKBarcodeDocumentModelConstants","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName\/title","value":"aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName"},{"value":[{"kind":"identifier","text":"aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaVehicleOwnerDataFirstOwnerLastNameFieldNormalizedName\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/title","value":"SBSDKBarcodeDocumentModelConstants","op":"replace"},{"value":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/navigatorTitle"}]}]}