{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalInfoTrailer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkswissqrcodefieldtype\/additionalinfotrailer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkswissqrcodefieldtype\/additionalinfotrailer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSwissQRCodeFieldType\/additionalInfoTrailer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The additional info trailer. V2 only."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalInfoTrailer"}],"title":"SBSDKSwissQRCodeFieldType.additionalInfoTrailer","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKSwissQRCodeFieldType@SBSDKSwissQRCodeFieldTypeAdditionalInfoTrailer","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKSwissQRCodeFieldTypeAdditionalInfoTrailer"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSwissQRCodeFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSwissQRCodeFieldType":{"role":"symbol","title":"SBSDKSwissQRCodeFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSwissQRCodeFieldType"}],"abstract":[{"type":"text","text":"The type of one Swiss QR code field."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSwissQRCodeFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSwissQRCodeFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkswissqrcodefieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSwissQRCodeFieldType/additionalInfoTrailer":{"role":"symbol","title":"SBSDKSwissQRCodeFieldType.additionalInfoTrailer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalInfoTrailer"}],"abstract":[{"type":"text","text":"The additional info trailer. V2 only."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSwissQRCodeFieldType\/additionalInfoTrailer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSwissQRCodeFieldTypeAdditionalInfoTrailer"}],"url":"\/documentation\/scanbotsdk\/sbsdkswissqrcodefieldtype\/additionalinfotrailer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKSwissQRCodeFieldTypeAdditionalInfoTrailer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKSwissQRCodeFieldTypeAdditionalInfoTrailer"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKSwissQRCodeFieldTypeAdditionalInfoTrailer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSwissQRCodeFieldType\/title","value":"SBSDKSwissQRCodeFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSwissQRCodeFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKSwissQRCodeFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSwissQRCodeFieldType~1additionalInfoTrailer\/title","value":"SBSDKSwissQRCodeFieldTypeAdditionalInfoTrailer"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSwissQRCodeFieldType~1additionalInfoTrailer\/fragments","value":[{"kind":"identifier","text":"SBSDKSwissQRCodeFieldTypeAdditionalInfoTrailer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}