{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKStructuredAppendInfo(py)hash","fragments":[{"kind":"identifier","text":"hash"}],"title":"hash","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"hash","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/hash","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo\/hash"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo/hash":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo\/hash","title":"hash","fragments":[{"kind":"identifier","text":"hash"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/hash","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo","title":"SBSDKStructuredAppendInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo","abstract":[{"type":"text","text":"The structured append mode can be used to split a message across multiple barcodes."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKStructuredAppendInfo","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/title"},{"value":[{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/navigatorTitle","value":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}