{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isInterrupted","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"text":", if the camera session is currently interrupted, ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise. On simulators always returns "},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasession\/isinterrupted"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasession\/isinterrupted"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession(py)isInterrupted","navigatorTitle":[{"text":"isInterrupted","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInterrupted"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isInterrupted","symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isInterrupted"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession":{"type":"topic","title":"SBSDKCameraSession","navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCameraSession"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/isInterrupted":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/isInterrupted","title":"isInterrupted","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInterrupted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isInterrupted","kind":"identifier"}],"abstract":[{"text":"Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":", if the camera session is currently interrupted, "},{"code":"false","type":"codeVoice"},{"type":"text","text":" otherwise. On simulators always returns "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/isinterrupted","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"isInterrupted","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"isInterrupted","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInterrupted"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/title","op":"replace","value":"SBSDKCameraSession"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraSession"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/navigatorTitle","value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"op":"replace"},{"value":"isInterrupted","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isInterrupted\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1isInterrupted\/fragments","value":[{"text":"isInterrupted","kind":"identifier"}]}]}]}