{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerZoomConfiguration"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPinchToZoomEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerZoomConfiguration\/isPinchToZoomEnabled"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"When this property is set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":", the camera zoom can be controlled by a pinch gesture anywhere in the base scannner view controllers view."},{"type":"text","text":" "},{"type":"text","text":"If set to "},{"code":"false","type":"codeVoice"},{"type":"text","text":", zooming by pinching will be disabled."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerzoomconfiguration\/ispinchtozoomenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerzoomconfiguration\/ispinchtozoomenabled"]}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"isPinchToZoomEnabled","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPinchToZoomEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerZoomConfiguration(py)isPinchToZoomEnabled","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"isPinchToZoomEnabled","kind":"identifier"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerZoomConfiguration/isPinchToZoomEnabled":{"abstract":[{"type":"text","text":"When this property is set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":", the camera zoom can be controlled by a pinch gesture anywhere in the base scannner view controllers view."},{"type":"text","text":" "},{"type":"text","text":"If set to "},{"type":"codeVoice","code":"false"},{"type":"text","text":", zooming by pinching will be disabled."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"isPinchToZoomEnabled","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerzoomconfiguration\/ispinchtozoomenabled","title":"isPinchToZoomEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPinchToZoomEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerZoomConfiguration\/isPinchToZoomEnabled","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerZoomConfiguration":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerZoomConfiguration"}],"title":"SBSDKBaseScannerZoomConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerzoomconfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerZoomConfiguration","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The zoom configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"type":"text","text":" "},{"type":"text","text":"‘SBSDKBaseScannerViewController’ and subclasses allow the user to zoom the camera."},{"type":"text","text":" "},{"type":"text","text":"This class lets you customize the zooming user experience."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerZoomConfiguration"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"isPinchToZoomEnabled"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"isPinchToZoomEnabled","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPinchToZoomEnabled"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerZoomConfiguration~1isPinchToZoomEnabled\/title","op":"replace","value":"isPinchToZoomEnabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerZoomConfiguration~1isPinchToZoomEnabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"isPinchToZoomEnabled"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerZoomConfiguration\/title","value":"SBSDKBaseScannerZoomConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerZoomConfiguration\/fragments","value":[{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerZoomConfiguration\/navigatorTitle","value":[{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"op":"replace"}]}]}