{"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeyprovider\/providekeyforcontext(_:keylength:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeyprovider\/providekeyforcontext(_:keylength:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider\/provideKeyForContext(_:keyLength:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(provideKeyForContext:keyLength:error:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provideKeyForContext"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"keyLength","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"context","content":[{"inlineContent":[{"type":"text","text":"The context to generate or load the key for. For most applications in Scanbot SDK the context is derived from the URL of the file to encrypted or decrypted by calling the "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Foundation\/URL\/sbsdk_encryptionContext","type":"reference"},{"type":"text","text":" property on the URL."}],"type":"paragraph"}]},{"name":"keyLength","content":[{"type":"paragraph","inlineContent":[{"text":"The length of the key to be provided.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The encryption\/decryption key for the given context.","type":"text"}]}],"kind":"content"}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"provideKeyForContext:keyLength:error:","kind":"identifier"}],"required":true,"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider(im)provideKeyForContext:keyLength:error:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provideKeyForContext","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"keyLength","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"title":"provideKeyForContext(_:keyLength:)"},"abstract":[{"type":"text","text":"Tries to load the encryption key for the given context and key length."},{"type":"text","text":" "},{"type":"text","text":"If no key is available yet, a new key is generated by the receivers key generator and stored under the given context."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyLength":{"role":"symbol","abstract":[{"type":"text","text":"The length of the encryption key."}],"kind":"symbol","title":"SBSDKStorageCryptingKeyLength","type":"topic","navigatorTitle":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyLength","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeylength"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyProvider":{"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"abstract":[{"text":"Protocol for loading, storing and providing encryption keys.","type":"text"},{"text":" ","type":"text"},{"text":"The context parameter is used to distinguish between different encryption contexts.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeyprovider","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider","role":"symbol","title":"SBSDKStorageCryptingKeyProvider"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Foundation/URL/sbsdk_encryptionContext":{"title":"sbsdk_encryptionContext","abstract":[{"text":"The encryption context of the URL.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Foundation\/URL\/sbsdk_encryptionContext","url":"\/documentation\/scanbotsdk\/foundation\/url\/sbsdk_encryptioncontext","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbsdk_encryptionContext","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyProvider/provideKeyForContext(_:keyLength:)":{"title":"provideKeyForContext(_:keyLength:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provideKeyForContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"keyLength","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"abstract":[{"text":"Tries to load the encryption key for the given context and key length.","type":"text"},{"text":" ","type":"text"},{"text":"If no key is available yet, a new key is generated by the receivers key generator and stored under the given context.","type":"text"}],"navigatorTitle":[{"text":"provideKeyForContext:keyLength:error:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider\/provideKeyForContext(_:keyLength:)","url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeyprovider\/providekeyforcontext(_:keylength:)","kind":"symbol","required":true,"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"provideKeyForContext:keyLength:error:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"provideKeyForContext:keyLength:error:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"provideKeyForContext:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"context"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyLength:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyLength"},{"kind":"text","text":") "},{"kind":"internalParam","text":"keyLength"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The context to generate or load the key for. For most applications in Scanbot SDK the context is derived from the URL of the file to encrypted or decrypted by calling the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Foundation\/URL\/sbsdk_encryptionContext","type":"reference","isActive":true},{"text":" property on the URL.","type":"text"}]}],"name":"context"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The length of the key to be provided.","type":"text"}]}],"name":"keyLength"},{"content":[{"inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" for this parameter."}],"type":"paragraph"}],"name":"error"}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The encryption\/decryption key for the given context."},{"type":"text","text":" On failure, this method returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}]}]}},{"op":"replace","value":"SBSDKStorageCryptingKeyLength","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength\/title"},{"op":"replace","value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength\/navigatorTitle"},{"op":"replace","value":"SBSDKStorageCryptingKeyProvider","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/title"},{"op":"replace","value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/fragments"},{"op":"replace","value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/navigatorTitle"},{"op":"replace","value":"provideKeyForContext:keyLength:error:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider~1provideKeyForContext(_:keyLength:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"provideKeyForContext:keyLength:error:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider~1provideKeyForContext(_:keyLength:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}