{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdklinesegment\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Method","title":"copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKLineSegment(im)copyWithZone:","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLineSegment"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier","text":"_NSZone"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"zone"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLineSegment\/copyWithZone:"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKLineSegment/copyWithZone:":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdklinesegment\/copywithzone:","title":"copyWithZone:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLineSegment\/copyWithZone:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKLineSegment":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdklinesegment","title":"SBSDKLineSegment","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLineSegment","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKLineSegment","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegment"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Helper class that encapsulates a line segment and provides geometric helper methods."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLineSegment\/title","op":"replace","value":"SBSDKLineSegment"},{"value":[{"text":"SBSDKLineSegment","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLineSegment\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLineSegment"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLineSegment\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}