{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDisplacement\/left"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdisplacement\/left"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdisplacement\/left"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDisplacement@SBSDKDocumentDisplacementLeft","title":"SBSDKDocumentDisplacement.left","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDisplacementLeft"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDisplacement"]]},"abstract":[{"type":"text","text":"The document is partially visible. Move the camera to the left to capture the full document."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDisplacement":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDisplacement","title":"SBSDKDocumentDisplacement","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdisplacement","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDisplacement","kind":"identifier"}],"abstract":[{"text":"The direction towards the center of the document if the document is partially visible.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDisplacement","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDisplacement/left":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDisplacement\/left","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdisplacement\/left","title":"SBSDKDocumentDisplacement.left","navigatorTitle":[{"text":"SBSDKDocumentDisplacementLeft","kind":"identifier"}],"abstract":[{"type":"text","text":"The document is partially visible. Move the camera to the left to capture the full document."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKDocumentDisplacementLeft","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKDocumentDisplacementLeft","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKDocumentDisplacementLeft"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDisplacement\/title","value":"SBSDKDocumentDisplacement","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDisplacement\/fragments","value":[{"text":"SBSDKDocumentDisplacement","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKDocumentDisplacement","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDisplacement\/navigatorTitle","op":"replace"},{"value":"SBSDKDocumentDisplacementLeft","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDisplacement~1left\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentDisplacementLeft","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDisplacement~1left\/fragments","op":"replace"}]}]}