{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDisplacement\/lowerLeft"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"The document is partially visible. Move the camera down and to the left to capture the full document.","type":"text"}],"metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lowerLeft","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDisplacementLowerLeft","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDisplacement@SBSDKDocumentDisplacementLowerLeft","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","roleHeading":"Case","title":"SBSDKDocumentDisplacement.lowerLeft"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowerLeft"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdisplacement\/lowerleft"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdisplacement\/lowerleft"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDisplacement"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDisplacement/lowerLeft":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowerLeft"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDisplacementLowerLeft"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdisplacement\/lowerleft","kind":"symbol","abstract":[{"type":"text","text":"The document is partially visible. Move the camera down and to the left to capture the full document."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDisplacement\/lowerLeft","role":"symbol","title":"SBSDKDocumentDisplacement.lowerLeft"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDisplacement":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDisplacement","title":"SBSDKDocumentDisplacement","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdisplacement","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDisplacement","kind":"identifier"}],"abstract":[{"text":"The direction towards the center of the document if the document is partially visible.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDisplacement","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKDocumentDisplacementLowerLeft"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDisplacementLowerLeft"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"SBSDKDocumentDisplacementLowerLeft","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDisplacement~1lowerLeft\/title","op":"replace","value":"SBSDKDocumentDisplacementLowerLeft"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDisplacement~1lowerLeft\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDisplacementLowerLeft"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDisplacement\/title","op":"replace","value":"SBSDKDocumentDisplacement"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDisplacement\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDisplacement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDisplacement\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentDisplacement","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}