{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterParameters"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterParameters\/defaultParametersForBinaryImages"},"metadata":{"title":"defaultParametersForBinaryImages","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultParametersForBinaryImages","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriterParameters","text":"SBSDKTIFFImageWriterParameters","kind":"typeIdentifier"}],"roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"defaultParametersForBinaryImages"}],"symbolKind":"property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriterParameters(cpy)defaultParametersForBinaryImages","role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriterparameters\/defaultparametersforbinaryimages"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriterparameters\/defaultparametersforbinaryimages"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultParametersForBinaryImages"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriterParameters","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterParameters","kind":"typeIdentifier","text":"SBSDKTIFFImageWriterParameters"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"Generates the default parameters for binarized TIFF images.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterParameters/defaultParametersForBinaryImages":{"title":"defaultParametersForBinaryImages","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterParameters\/defaultParametersForBinaryImages","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultParametersForBinaryImages","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriterParameters","text":"SBSDKTIFFImageWriterParameters","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriterparameters\/defaultparametersforbinaryimages","abstract":[{"text":"Generates the default parameters for binarized TIFF images.","type":"text"}],"navigatorTitle":[{"text":"defaultParametersForBinaryImages","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterParameters":{"title":"SBSDKTIFFImageWriterParameters","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriterparameters","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterParameters","type":"topic","role":"symbol","abstract":[{"text":"Class used to define the parameters for the TIFF image writer.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFImageWriterParameters"}],"navigatorTitle":[{"text":"SBSDKTIFFImageWriterParameters","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 5.0.2","type":"text"}],"role":"collection","type":"topic","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"defaultParametersForBinaryImages","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultParametersForBinaryImages"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKTIFFImageWriterParameters","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterParameters","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriterParameters"},{"text":" * ","kind":"text"},{"text":"defaultParametersForBinaryImages","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterParameters~1defaultParametersForBinaryImages\/title","value":"defaultParametersForBinaryImages","op":"replace"},{"value":[{"text":"defaultParametersForBinaryImages","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterParameters~1defaultParametersForBinaryImages\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterParameters\/title","value":"SBSDKTIFFImageWriterParameters"},{"op":"replace","value":[{"text":"SBSDKTIFFImageWriterParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterParameters\/fragments"}]}]}