{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvaregistrantandvehicledata\/basejurisdictionregisteredweight"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvaregistrantandvehicledata\/basejurisdictionregisteredweight"]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Data element ID “RAU”. The declared base jurisdiction registration weight."}],"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"baseJurisdictionRegisteredWeight","kind":"identifier"}],"title":"baseJurisdictionRegisteredWeight","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData(py)baseJurisdictionRegisteredWeight","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"baseJurisdictionRegisteredWeight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"baseJurisdictionRegisteredWeight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData\/baseJurisdictionRegisteredWeight"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 6.1.0"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData","kind":"identifier"}],"abstract":[{"text":"Registrant And Vehicle Data. File type “IR”.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData","title":"SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvaregistrantandvehicledata","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentField":{"abstract":[{"text":"A generic document field.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentfield","title":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentField","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData/baseJurisdictionRegisteredWeight":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"baseJurisdictionRegisteredWeight"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"abstract":[{"text":"Data element ID “RAU”. The declared base jurisdiction registration weight.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData\/baseJurisdictionRegisteredWeight","title":"baseJurisdictionRegisteredWeight","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"baseJurisdictionRegisteredWeight"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvaregistrantandvehicledata\/basejurisdictionregisteredweight","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"baseJurisdictionRegisteredWeight"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"baseJurisdictionRegisteredWeight"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"kind":"text","text":" * "},{"text":"baseJurisdictionRegisteredWeight","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData\/title","value":"SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData\/fragments","value":[{"text":"SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData\/navigatorTitle"},{"value":"SBSDKGenericDocumentField","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentField\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentField\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentField\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},{"value":"baseJurisdictionRegisteredWeight","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData~1baseJurisdictionRegisteredWeight\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVARegistrantAndVehicleData~1baseJurisdictionRegisteredWeight\/fragments","value":[{"text":"baseJurisdictionRegisteredWeight","kind":"identifier"}],"op":"replace"}]}]}