{"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/languages"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/languages"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"languages","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"languages","kind":"identifier"}],"symbolKind":"property","title":"languages","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration(py)languages"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"languages"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Is ignored if ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/recognitionMode"},{"type":"text","text":" is set to "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/scanbotOCR","isActive":true},{"type":"text","text":"."}]},{"inlineContent":[{"text":"Readonly.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to an empty array."}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/languages","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"An array of two-letter ISO 639-1 language code strings that are being used by the character recognizer."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration/recognitionMode":{"navigatorTitle":[{"text":"recognitionMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/recognitionmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/recognitionMode","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognitionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOpticalCharacterRecognitionMode","text":"SBSDKOpticalCharacterRecognitionMode"}],"abstract":[{"text":"The recognition mode.","type":"text"}],"kind":"symbol","title":"recognitionMode","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration/languages":{"navigatorTitle":[{"kind":"identifier","text":"languages"}],"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/languages","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/languages","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"languages","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"An array of two-letter ISO 639-1 language code strings that are being used by the character recognizer."}],"kind":"symbol","title":"languages","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration","title":"SBSDKOpticalCharacterRecognizerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"abstract":[{"text":"A class describing the configuration of the optical character recognizer (OCR).","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode/scanbotOCR":{"navigatorTitle":[{"text":"SBSDKOpticalCharacterRecognitionModeScanbotOCR","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/scanbotocr","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/scanbotOCR","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"scanbotOCR","kind":"identifier"}],"abstract":[{"type":"text","text":"The new machine-learning based mode made by Scanbot SDK GmbH. Faster, less errors, but currently only"},{"text":" ","type":"text"},{"type":"text","text":"supports languages with latin letters."}],"kind":"symbol","title":"SBSDKOpticalCharacterRecognitionMode.scanbotOCR","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"languages"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"languages"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"languages"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"recognitionMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1recognitionMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1recognitionMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"recognitionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1languages\/title","value":"languages"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1languages\/fragments","op":"replace","value":[{"kind":"identifier","text":"languages"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration\/title","op":"replace","value":"SBSDKOpticalCharacterRecognizerConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1scanbotOCR\/title","value":"SBSDKOpticalCharacterRecognitionModeScanbotOCR","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1scanbotOCR\/fragments","value":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognitionModeScanbotOCR"}]}]}]}