{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"recognitionMode","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOpticalCharacterRecognitionMode","text":"SBSDKOpticalCharacterRecognitionMode","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Readonly.","type":"text"}]},{"inlineContent":[{"text":"Defaults to ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/scanbotOCR","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/recognitionMode","interfaceLanguage":"swift"},"abstract":[{"text":"The recognition mode.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/recognitionmode"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/recognitionmode"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"recognitionMode","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"recognitionMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKOpticalCharacterRecognitionMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOpticalCharacterRecognitionMode"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration(py)recognitionMode","symbolKind":"property","navigatorTitle":[{"text":"recognitionMode","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode/scanbotOCR":{"title":"SBSDKOpticalCharacterRecognitionMode.scanbotOCR","abstract":[{"text":"The new machine-learning based mode made by Scanbot SDK GmbH. Faster, less errors, but currently only","type":"text"},{"type":"text","text":" "},{"type":"text","text":"supports languages with latin letters."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/scanbotocr","navigatorTitle":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognitionModeScanbotOCR"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scanbotOCR"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/scanbotOCR"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration/recognitionMode":{"title":"recognitionMode","abstract":[{"type":"text","text":"The recognition mode."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/recognitionmode","navigatorTitle":[{"kind":"identifier","text":"recognitionMode"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognitionMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOpticalCharacterRecognitionMode","text":"SBSDKOpticalCharacterRecognitionMode","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/recognitionMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode":{"title":"SBSDKOpticalCharacterRecognitionMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKOpticalCharacterRecognitionMode","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode","type":"topic","abstract":[{"text":"An enum describing the modes of the optical character recognition.","type":"text"}],"navigatorTitle":[{"text":"SBSDKOpticalCharacterRecognitionMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration":{"title":"SBSDKOpticalCharacterRecognizerConfiguration","abstract":[{"type":"text","text":"A class describing the configuration of the optical character recognizer (OCR)."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKOpticalCharacterRecognizerConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"recognitionMode","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"recognitionMode"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOpticalCharacterRecognitionMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode","text":"SBSDKOpticalCharacterRecognitionMode"},{"kind":"text","text":" "},{"text":"recognitionMode","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1scanbotOCR\/title","op":"replace","value":"SBSDKOpticalCharacterRecognitionModeScanbotOCR"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1scanbotOCR\/fragments","value":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognitionModeScanbotOCR"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1recognitionMode\/title","value":"recognitionMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1recognitionMode\/fragments","op":"replace","value":[{"text":"recognitionMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode\/title","value":"SBSDKOpticalCharacterRecognitionMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode\/fragments","value":[{"text":"SBSDKOpticalCharacterRecognitionMode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration\/title","value":"SBSDKOpticalCharacterRecognizerConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration\/fragments","op":"replace"}]}]}