{"abstract":[{"type":"text","text":"Creates an OCR configuration using the mode "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/tesseract"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/tesseract(withLanguageString:)"},"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"text":"tesseractWithLanguageString:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration(cm)tesseractWithLanguageString:","roleHeading":"Type Method","title":"tesseract(withLanguageString:)","symbolKind":"method","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tesseract","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withLanguageString"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKOpticalCharacterRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration"}],"modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tesseract"},{"text":"(","kind":"text"},{"text":"withLanguageString","kind":"externalParam"},{"kind":"text","text":" "},{"text":"languageString","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"SBSDKOpticalCharacterRecognizerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration"}]}],"kind":"declarations"},{"parameters":[{"name":"languageString","content":[{"inlineContent":[{"text":"A string with two-character-language strings, separated by a plus or comma sign, for example “de+en”.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The new OCR configuration object."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/tesseract(withlanguagestring:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/tesseract(withlanguagestring:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode/tesseract":{"title":"SBSDKOpticalCharacterRecognitionMode.tesseract","abstract":[{"text":"The legacy OCR mode using Tesseract. Slower, more error prone, but it supports more languages.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/tesseract","navigatorTitle":[{"text":"SBSDKOpticalCharacterRecognitionModeTesseract","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"tesseract","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/tesseract"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration":{"title":"SBSDKOpticalCharacterRecognizerConfiguration","abstract":[{"type":"text","text":"A class describing the configuration of the optical character recognizer (OCR)."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKOpticalCharacterRecognizerConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration/tesseract(withLanguageString:)":{"title":"tesseract(withLanguageString:)","abstract":[{"text":"Creates an OCR configuration using the mode ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/tesseract","isActive":true},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/tesseract(withlanguagestring:)","navigatorTitle":[{"text":"tesseractWithLanguageString:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tesseract","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLanguageString","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/tesseract(withLanguageString:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"tesseractWithLanguageString:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"text":"tesseractWithLanguageString:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration","text":"SBSDKOpticalCharacterRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration"},{"kind":"text","text":" *) "},{"text":"tesseractWithLanguageString:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"languageString","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKOpticalCharacterRecognitionModeTesseract","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1tesseract\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1tesseract\/fragments","value":[{"text":"SBSDKOpticalCharacterRecognitionModeTesseract","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration\/title","value":"SBSDKOpticalCharacterRecognizerConfiguration","op":"replace"},{"value":[{"text":"SBSDKOpticalCharacterRecognizerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1tesseract(withLanguageString:)\/title","value":"tesseractWithLanguageString:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"tesseractWithLanguageString:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1tesseract(withLanguageString:)\/fragments"}]}]}