{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The image for the introduction screen."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerintroscreenconfiguration\/image"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerintroscreenconfiguration\/image"]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerIntroImage","text":"SBSDKUI2CheckScannerIntroImage","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"image","kind":"identifier"}],"title":"image","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerIntroScreenConfiguration(py)image","role":"symbol","symbolKind":"property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerIntroScreenConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerIntroImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerIntroImage","text":"SBSDKUI2CheckScannerIntroImage"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerIntroScreenConfiguration\/image","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerIntroScreenConfiguration/image":{"abstract":[{"type":"text","text":"The image for the introduction screen."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerintroscreenconfiguration\/image","title":"image","navigatorTitle":[{"kind":"identifier","text":"image"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerIntroScreenConfiguration\/image","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CheckScannerIntroImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerIntroImage"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerIntroImage":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CheckScannerIntroImage"}],"abstract":[{"text":"The image for the introduction screen of a check scanner screen.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckScannerIntroImage"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerIntroImage","title":"SBSDKUI2CheckScannerIntroImage","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerintroimage","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerIntroScreenConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerIntroScreenConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerintroscreenconfiguration","title":"SBSDKUI2CheckScannerIntroScreenConfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CheckScannerIntroScreenConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CheckScannerIntroScreenConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the introduction screen for the check scanner."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"image","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"image"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerIntroImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerIntroImage","text":"SBSDKUI2CheckScannerIntroImage"},{"kind":"text","text":" * "},{"kind":"identifier","text":"image"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"image","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerIntroScreenConfiguration~1image\/title"},{"value":[{"kind":"identifier","text":"image"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerIntroScreenConfiguration~1image\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerIntroImage\/title","op":"replace","value":"SBSDKUI2CheckScannerIntroImage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerIntroImage\/fragments","op":"replace","value":[{"text":"SBSDKUI2CheckScannerIntroImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerIntroImage\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CheckScannerIntroImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerIntroScreenConfiguration\/title","op":"replace","value":"SBSDKUI2CheckScannerIntroScreenConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerIntroScreenConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerIntroScreenConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerIntroScreenConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CheckScannerIntroScreenConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}