{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithStyle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2FinderStyle","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2FinderStyle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2FinderStyle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"style","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"overlayColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"overlayColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"aspectRatio:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"aspectRatio","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumInsets:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2EdgeInsets","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2EdgeInsets","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2EdgeInsets","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"minimumInsets","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"preferredHeight:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"preferredHeight","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"visible:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"visible","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ViewFinderConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2viewfinderconfiguration\/initwithstyle:overlaycolor:aspectratio:minimuminsets:preferredheight:visible:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ViewFinderConfiguration\/initWithStyle:overlayColor:aspectRatio:minimumInsets:preferredHeight:visible:"},"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithStyle:overlayColor:aspectRatio:minimumInsets:preferredHeight:visible:"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ViewFinderConfiguration(im)initWithStyle:overlayColor:aspectRatio:minimumInsets:preferredHeight:visible:","title":"initWithStyle:overlayColor:aspectRatio:minimumInsets:preferredHeight:visible:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithStyle:overlayColor:aspectRatio:minimumInsets:preferredHeight:visible:","kind":"identifier"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ViewFinderConfiguration/initWithStyle:overlayColor:aspectRatio:minimumInsets:preferredHeight:visible:":{"navigatorTitle":[{"text":"initWithStyle:overlayColor:aspectRatio:minimumInsets:preferredHeight:visible:","kind":"identifier"}],"type":"topic","title":"initWithStyle:overlayColor:aspectRatio:minimumInsets:preferredHeight:visible:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2viewfinderconfiguration\/initwithstyle:overlaycolor:aspectratio:minimuminsets:preferredheight:visible:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ViewFinderConfiguration\/initWithStyle:overlayColor:aspectRatio:minimumInsets:preferredHeight:visible:","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithStyle:overlayColor:aspectRatio:minimumInsets:preferredHeight:visible:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAspectRatio":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAspectRatio"}],"title":"SBSDKAspectRatio","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaspectratio","navigatorTitle":[{"kind":"identifier","text":"SBSDKAspectRatio"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio","abstract":[{"text":"Aspect ratio is the ratio of the width to the height of an image or screen.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ViewFinderConfiguration":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2viewfinderconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ViewFinderConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the scanning interface’s viewfinder, allowing it to be shown or hidden as guidance to the user."}],"type":"topic","title":"SBSDKUI2ViewFinderConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ViewFinderConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ViewFinderConfiguration"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2FinderStyle":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2FinderStyle","title":"SBSDKUI2FinderStyle","abstract":[{"type":"text","text":"The visual appearance of the viewfinder."}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2finderstyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2FinderStyle"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FinderStyle"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Color":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","role":"symbol","title":"SBSDKUI2Color","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2color","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Color"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2EdgeInsets":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2EdgeInsets","title":"SBSDKUI2EdgeInsets","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2EdgeInsets"}],"role":"symbol","abstract":[{"type":"text","text":"Represents the insets of a rectangle."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2edgeinsets","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2EdgeInsets"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio\/title","value":"SBSDKAspectRatio","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio\/fragments","value":[{"text":"SBSDKAspectRatio","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAspectRatio"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ViewFinderConfiguration\/title","value":"SBSDKUI2ViewFinderConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ViewFinderConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ViewFinderConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ViewFinderConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2FinderStyle\/title","value":"SBSDKUI2FinderStyle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2FinderStyle\/fragments","value":[{"text":"SBSDKUI2FinderStyle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2FinderStyle\/navigatorTitle","value":[{"text":"SBSDKUI2FinderStyle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/fragments","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/navigatorTitle","value":[{"text":"SBSDKUI2Color","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2EdgeInsets\/title","value":"SBSDKUI2EdgeInsets"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2EdgeInsets\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2EdgeInsets"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2EdgeInsets\/navigatorTitle","value":[{"text":"SBSDKUI2EdgeInsets","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}