{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deIdCardFrontDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelConstants(cpy)deIdCardFrontDocumentType","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"deIdCardFrontDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"deIdCardFrontDocumentType"}],"title":"deIdCardFrontDocumentType","symbolKind":"property","roleHeading":"Type Property","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Document type name of the “DeIdCardFront” document type."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/deidcardfrontdocumenttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/deidcardfrontdocumenttype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/deIdCardFrontDocumentType"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants/deIdCardFrontDocumentType":{"navigatorTitle":[{"kind":"identifier","text":"deIdCardFrontDocumentType"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/deIdCardFrontDocumentType","title":"deIdCardFrontDocumentType","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/deidcardfrontdocumenttype","abstract":[{"type":"text","text":"Document type name of the “DeIdCardFront” document type."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"deIdCardFrontDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants":{"title":"SBSDKDocumentsModelConstants","navigatorTitle":[{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants","type":"topic","kind":"symbol","role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"deIdCardFrontDocumentType","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"deIdCardFrontDocumentType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"deIdCardFrontDocumentType","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"deIdCardFrontDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1deIdCardFrontDocumentType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"deIdCardFrontDocumentType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1deIdCardFrontDocumentType\/fragments","op":"replace"},{"value":"SBSDKDocumentsModelConstants","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/navigatorTitle","op":"replace"}]}]}