{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/europeandriverlicensebackcategoryvaliduntilfieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/europeandriverlicensebackcategoryvaliduntilfieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelConstants(cpy)europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName","kind":"identifier"}],"symbolKind":"property","role":"symbol","title":"europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}],"kind":"declarations"}],"abstract":[{"text":"Normalized full name of the “ValidUntil” field type in document type “EuropeanDriverLicenseBack.Category”.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants/europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName":{"abstract":[{"text":"Normalized full name of the “ValidUntil” field type in document type “EuropeanDriverLicenseBack.Category”.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/europeandriverlicensebackcategoryvaliduntilfieldnormalizedname","title":"europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants":{"title":"SBSDKDocumentsModelConstants","navigatorTitle":[{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants","type":"topic","kind":"symbol","role":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName\/title","op":"replace","value":"europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName\/fragments","op":"replace","value":[{"text":"europeanDriverLicenseBackCategoryValidUntilFieldNormalizedName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/title","op":"replace","value":"SBSDKDocumentsModelConstants"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}