{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement\/mrzFallbackConfiguration()"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mrzFallbackConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorMRZFallbackConfiguration","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"method","role":"symbol","externalID":"s:10ScanbotSDK46SBSDKDocumentDataExtractorConfigurationElementC011mrzFallbackF0AA0cde11MRZFallbackF0CyFZ","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzFallbackConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorMRZFallbackConfiguration"}],"modules":[{"name":"ScanbotSDK"}],"title":"mrzFallbackConfiguration()"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationelement\/mrzfallbackconfiguration()"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationElement/mrzFallbackConfiguration()":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mrzFallbackConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorMRZFallbackConfiguration","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement\/mrzFallbackConfiguration()","title":"mrzFallbackConfiguration()","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationelement\/mrzfallbackconfiguration()","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationElement":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement","abstract":[{"text":"Base class for all generic document configuration elements.","type":"text"}],"title":"SBSDKDocumentDataExtractorConfigurationElement","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationelement","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorMRZFallbackConfiguration":{"title":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"symbol","abstract":[{"type":"text","text":"MRZ fallback configuration element."},{"type":"text","text":" "},{"type":"text","text":"This configuration element does not enable the scanning of any document types by itself."},{"type":"text","text":" "},{"type":"text","text":"Add to extractor configuration to enable recognizing the MRZ only, specifically for documents that are otherwise not"},{"text":" ","type":"text"},{"type":"text","text":"supported."},{"type":"text","text":" "},{"type":"text","text":"Note that this may enable scanning of documents that were not enabled through the accepted document types."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/title","op":"replace","value":"SBSDKDocumentDataExtractorConfigurationElement"},{"value":[{"text":"SBSDKDocumentDataExtractorConfigurationElement","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentDataExtractorConfigurationElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/navigatorTitle"},{"value":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}