{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningParameters"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningparameters\/initwithshouldcropdocument:recognizepatientinfobox:recognizebarcode:extractcroppedimage:preprocessinput:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithShouldCropDocument:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"shouldCropDocument"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognizePatientInfoBox:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"recognizePatientInfoBox"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognizeBarcode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"recognizeBarcode"},{"kind":"text","text":" "},{"kind":"identifier","text":"extractCroppedImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"extractCroppedImage"},{"kind":"text","text":" "},{"kind":"identifier","text":"preprocessInput:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"preprocessInput"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningParameters(im)initWithShouldCropDocument:recognizePatientInfoBox:recognizeBarcode:extractCroppedImage:preprocessInput:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"initWithShouldCropDocument:recognizePatientInfoBox:recognizeBarcode:extractCroppedImage:preprocessInput:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithShouldCropDocument:recognizePatientInfoBox:recognizeBarcode:extractCroppedImage:preprocessInput:"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"initWithShouldCropDocument:recognizePatientInfoBox:recognizeBarcode:extractCroppedImage:preprocessInput:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningParameters\/initWithShouldCropDocument:recognizePatientInfoBox:recognizeBarcode:extractCroppedImage:preprocessInput:","interfaceLanguage":"occ"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanningParameters/initWithShouldCropDocument:recognizePatientInfoBox:recognizeBarcode:extractCroppedImage:preprocessInput:":{"role":"symbol","title":"initWithShouldCropDocument:recognizePatientInfoBox:recognizeBarcode:extractCroppedImage:preprocessInput:","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningparameters\/initwithshouldcropdocument:recognizepatientinfobox:recognizebarcode:extractcroppedimage:preprocessinput:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningParameters\/initWithShouldCropDocument:recognizePatientInfoBox:recognizeBarcode:extractCroppedImage:preprocessInput:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithShouldCropDocument:recognizePatientInfoBox:recognizeBarcode:extractCroppedImage:preprocessInput:","kind":"identifier"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"initWithShouldCropDocument:recognizePatientInfoBox:recognizeBarcode:extractCroppedImage:preprocessInput:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanningParameters":{"navigatorTitle":[{"text":"SBSDKMedicalCertificateScanningParameters","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningParameters","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningparameters","role":"symbol","title":"SBSDKMedicalCertificateScanningParameters","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateScanningParameters","kind":"identifier"}],"abstract":[{"type":"text","text":"Parameters for the medical certificate scanning. The scanner supports"},{"type":"text","text":" "},{"type":"text","text":"Form 1 (Arbeitsunfähigkeitsbescheinigung) and"},{"type":"text","text":" "},{"type":"text","text":"Form 21a (Ärztliche Bescheinigung für den Bezug von Krankengeld bei Erkrankung eines Kindes)"},{"type":"text","text":" "},{"type":"text","text":"from the KBV (Kassenärztliche Bundesvereinigung) list of forms."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKMedicalCertificateScanningParameters","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningParameters\/title"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScanningParameters"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningParameters\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScanningParameters"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningParameters\/navigatorTitle"}]}]}