{"metadata":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithQuad:value:rawString:type:recognitionConfidence:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"title":"initWithQuad:value:rawString:type:recognitionConfidence:","navigatorTitle":[{"text":"initWithQuad:value:rawString:type:recognitionConfidence:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateDateRecord(im)initWithQuad:value:rawString:type:recognitionConfidence:","symbolKind":"method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/initWithQuad:value:rawString:type:recognitionConfidence:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord\/initwithquad:value:rawstring:type:recognitionconfidence:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithQuad:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSValue *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"quad"},{"kind":"text","text":" "},{"kind":"identifier","text":"value:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"value"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawString:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rawString"},{"kind":"text","text":" "},{"kind":"identifier","text":"type:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateDateRecordType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType","text":"SBSDKMedicalCertificateDateRecordType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognitionConfidence:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"recognitionConfidence"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord/initWithQuad:value:rawString:type:recognitionConfidence:":{"navigatorTitle":[{"text":"initWithQuad:value:rawString:type:recognitionConfidence:","kind":"identifier"}],"type":"topic","title":"initWithQuad:value:rawString:type:recognitionConfidence:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/initWithQuad:value:rawString:type:recognitionConfidence:","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord\/initwithquad:value:rawstring:type:recognitionconfidence:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithQuad:value:rawString:type:recognitionConfidence:","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord","navigatorTitle":[{"text":"SBSDKMedicalCertificateDateRecord","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateDateRecord","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Structure to contain date record information.","type":"text"}],"title":"SBSDKMedicalCertificateDateRecord","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecordType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateDateRecordType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateDateRecordType","kind":"identifier"}],"kind":"symbol","title":"SBSDKMedicalCertificateDateRecordType","abstract":[{"text":"Type of a date record.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType","type":"topic"}},"variantOverrides":[{"patch":[{"value":"SBSDKMedicalCertificateDateRecord","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord\/title"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecord"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecord"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord\/navigatorTitle"},{"value":"SBSDKMedicalCertificateDateRecordType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/title"},{"value":[{"text":"SBSDKMedicalCertificateDateRecordType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}