{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/enabled","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"abstract":[{"type":"text","text":"Binarize the image. Image will be stored as a compressed black-and-white image. This will result in a"},{"type":"text","text":" "},{"type":"text","text":"very small file size. If binarizationFilter is set, this binarization filter will be applied."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, a simple thresholding binarization will be applied."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpagebinarization\/enabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpagebinarization\/enabled"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"}],"title":"SBSDKPageBinarization.enabled","externalID":"c:@M@ScanbotSDK@E@SBSDKPageBinarization@SBSDKPageBinarizationEnabled","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageBinarizationEnabled"}],"roleHeading":"Case"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageBinarization":{"abstract":[{"text":"Binarization behavior to apply when adding a page to a PDF\/TIFF.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagebinarization","role":"symbol","navigatorTitle":[{"text":"SBSDKPageBinarization","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageBinarization"}],"title":"SBSDKPageBinarization","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageBinarization/enabled":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/enabled","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpagebinarization\/enabled","role":"symbol","title":"SBSDKPageBinarization.enabled","kind":"symbol","abstract":[{"type":"text","text":"Binarize the image. Image will be stored as a compressed black-and-white image. This will result in a"},{"type":"text","text":" "},{"type":"text","text":"very small file size. If binarizationFilter is set, this binarization filter will be applied."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, a simple thresholding binarization will be applied."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageBinarizationEnabled"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKPageBinarizationEnabled","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKPageBinarizationEnabled","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKPageBinarizationEnabled"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization\/title","op":"replace","value":"SBSDKPageBinarization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPageBinarization"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization\/navigatorTitle","value":[{"text":"SBSDKPageBinarization","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization~1enabled\/title","value":"SBSDKPageBinarizationEnabled","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization~1enabled\/fragments","value":[{"text":"SBSDKPageBinarizationEnabled","kind":"identifier"}],"op":"replace"}]}]}