{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithVisible:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"visible"},{"kind":"text","text":";"}]}]}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2NoButtonMode(im)initWithVisible:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithVisible:","kind":"identifier"}],"title":"initWithVisible:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"initWithVisible:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoButtonMode\/initWithVisible:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoButtonMode"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2nobuttonmode\/initwithvisible:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2NoButtonMode":{"type":"topic","title":"SBSDKUI2NoButtonMode","abstract":[{"type":"text","text":"Configuration of the ‘preview’ button in ‘no button mode’."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoButtonMode","url":"\/documentation\/scanbotsdk\/sbsdkui2nobuttonmode","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2NoButtonMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2NoButtonMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2NoButtonMode/initWithVisible:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoButtonMode\/initWithVisible:","title":"initWithVisible:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithVisible:","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"initWithVisible:","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2nobuttonmode\/initwithvisible:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoButtonMode\/title","value":"SBSDKUI2NoButtonMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoButtonMode\/fragments","value":[{"text":"SBSDKUI2NoButtonMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoButtonMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2NoButtonMode"}],"op":"replace"}]}]}