{"sections":[],"kind":"symbol","abstract":[{"text":"Use the back camera with the widest available angle.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2cameramodule\/backwidest"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2cameramodule\/backwidest"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"backWidest","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule"]]},"metadata":{"title":"SBSDKUI2CameraModule.backWidest","navigatorTitle":[{"text":"SBSDKUI2CameraModuleBackWidest","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule@SBSDKUI2CameraModuleBackWidest","role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"backWidest","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/backWidest"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraModule/backWidest":{"kind":"symbol","title":"SBSDKUI2CameraModule.backWidest","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"backWidest","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraModuleBackWidest"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2cameramodule\/backwidest","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/backWidest","abstract":[{"type":"text","text":"Use the back camera with the widest available angle."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraModule":{"abstract":[{"text":"Determine which camera module to use on start-up.","type":"text"}],"title":"SBSDKUI2CameraModule","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule","url":"\/documentation\/scanbotsdk\/sbsdkui2cameramodule","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2CameraModuleBackWidest"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKUI2CameraModuleBackWidest","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKUI2CameraModuleBackWidest"}],"languages":["occ"]}]}},{"value":"SBSDKUI2CameraModuleBackWidest","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule~1backWidest\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule~1backWidest\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraModuleBackWidest"}]},{"op":"replace","value":"SBSDKUI2CameraModule","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2CameraModule"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}