{"sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode\/!=(_:_:)"],"title":"Operators","anchor":"Operators","generated":true}],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode\/Equatable-Implementations","interfaceLanguage":"swift"},"kind":"article","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplebarcodesscanningmode\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 6.1.0"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MultipleBarcodesScanningMode":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode","abstract":[{"type":"text","text":"Configuration of the mode used for scanning multiple barcodes."}],"title":"SBSDKUI2MultipleBarcodesScanningMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplebarcodesscanningmode","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MultipleBarcodesScanningMode/!=(_:_:)":{"abstract":[],"role":"symbol","title":"!=(_:_:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode\/!=(_:_:)","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplebarcodesscanningmode\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleBarcodesScanningMode\/title","value":"SBSDKUI2MultipleBarcodesScanningMode"},{"op":"replace","value":[{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleBarcodesScanningMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleBarcodesScanningMode\/navigatorTitle","value":[{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}]}]}]}