{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerUserGuidance\/initWithVisibility:title:background:statesTitles:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerUserGuidance"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithVisibility:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceVisibility","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2UserGuidanceVisibility","text":"SBSDKUI2UserGuidanceVisibility"},{"kind":"text","text":") "},{"kind":"internalParam","text":"visibility"},{"kind":"text","text":" "},{"kind":"identifier","text":"title:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"title"},{"kind":"text","text":" "},{"kind":"identifier","text":"background:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BackgroundStyle","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BackgroundStyle","text":"SBSDKUI2BackgroundStyle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"background"},{"kind":"text","text":" "},{"kind":"identifier","text":"statesTitles:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceStates","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2UserGuidanceStates","text":"SBSDKUI2UserGuidanceStates"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"statesTitles"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneruserguidance\/initwithvisibility:title:background:statestitles:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"initWithVisibility:title:background:statesTitles:","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerUserGuidance(im)initWithVisibility:title:background:statesTitles:","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithVisibility:title:background:statesTitles:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithVisibility:title:background:statesTitles:","kind":"identifier"}],"symbolKind":"method"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2StyledText":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2styledtext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"title":"SBSDKUI2StyledText","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","abstract":[{"text":"Configuration of the text field appearance.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2UserGuidanceStates":{"navigatorTitle":[{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}],"title":"SBSDKUI2UserGuidanceStates","abstract":[{"text":"Configure the titles of the user guidance hints for different states.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidancestates","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceStates","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerUserGuidance":{"abstract":[{"type":"text","text":"Configuration of the hints guiding users through the scanning process."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerUserGuidance","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneruserguidance","title":"SBSDKUI2DocumentScannerUserGuidance","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerUserGuidance","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerUserGuidance"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2UserGuidanceVisibility":{"role":"symbol","type":"topic","title":"SBSDKUI2UserGuidanceVisibility","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceVisibility","abstract":[{"text":"Determines the visibility mode for the document capturing user guidance labels.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidancevisibility","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibility"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibility"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2BackgroundStyle":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BackgroundStyle","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2backgroundstyle","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}],"kind":"symbol","title":"SBSDKUI2BackgroundStyle","abstract":[{"text":"Configuration of the background appearance for buttons and hints.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerUserGuidance/initWithVisibility:title:background:statesTitles:":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneruserguidance\/initwithvisibility:title:background:statestitles:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVisibility:title:background:statesTitles:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithVisibility:title:background:statesTitles:"}],"title":"initWithVisibility:title:background:statesTitles:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerUserGuidance\/initWithVisibility:title:background:statesTitles:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/title","value":"SBSDKUI2StyledText"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/navigatorTitle","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceStates\/title","value":"SBSDKUI2UserGuidanceStates"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceStates\/fragments","value":[{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceStates\/navigatorTitle","value":[{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerUserGuidance\/title","value":"SBSDKUI2DocumentScannerUserGuidance"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerUserGuidance\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerUserGuidance"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerUserGuidance\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentScannerUserGuidance","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceVisibility\/title","value":"SBSDKUI2UserGuidanceVisibility"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceVisibility\/fragments","value":[{"text":"SBSDKUI2UserGuidanceVisibility","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceVisibility\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibility"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BackgroundStyle\/title","value":"SBSDKUI2BackgroundStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BackgroundStyle\/fragments","value":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BackgroundStyle\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BackgroundStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}