{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController"]]},"metadata":{"role":"symbol","title":"acceptedDocumentTypes","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerViewController(py)acceptedDocumentTypes","navigatorTitle":[{"text":"acceptedDocumentTypes","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acceptedDocumentTypes","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRootType","text":"SBSDKGenericDocumentRootType"},{"text":"]","kind":"text"}],"modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontroller\/accepteddocumenttypes"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontroller\/accepteddocumenttypes"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"An array of recognizable document types."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptedDocumentTypes"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRootType","text":"SBSDKGenericDocumentRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRootType","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"By default all document types will be recognized."}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController\/acceptedDocumentTypes"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRootType":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentroottype","abstract":[{"type":"text","text":"Root document type."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentRootType","kind":"identifier"}],"title":"SBSDKGenericDocumentRootType","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentRootType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRootType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewController":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentRecognizerViewController","kind":"identifier"}],"title":"SBSDKGenericDocumentRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerViewController"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to recognize documents, e.g. German passports, ID cards and driver’s licenses on video frames."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewController/acceptedDocumentTypes":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontroller\/accepteddocumenttypes","kind":"symbol","abstract":[{"text":"An array of recognizable document types.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"acceptedDocumentTypes"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedDocumentTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRootType"},{"kind":"text","text":"]"}],"title":"acceptedDocumentTypes","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController\/acceptedDocumentTypes"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"acceptedDocumentTypes"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"acceptedDocumentTypes","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKGenericDocumentRootType *>"},{"text":" * ","kind":"text"},{"text":"acceptedDocumentTypes","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRootType\/title","value":"SBSDKGenericDocumentRootType"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentRootType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRootType\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController\/title","value":"SBSDKGenericDocumentRecognizerViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController\/fragments","value":[{"text":"SBSDKGenericDocumentRecognizerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController~1acceptedDocumentTypes\/title","value":"acceptedDocumentTypes"},{"value":[{"text":"acceptedDocumentTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController~1acceptedDocumentTypes\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}