{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController\/init(acceptedDocumentTypes:excludedFieldTypes:delegate:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"acceptedDocumentTypes"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRootType","kind":"typeIdentifier","text":"SBSDKGenericDocumentRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRootType"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"excludedFieldTypes"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?, ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKGenericDocumentRecognizerViewControllerDelegate","text":"SBSDKGenericDocumentRecognizerViewControllerDelegate","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}]},{"parameters":[{"name":"acceptedDocumentTypes","content":[{"inlineContent":[{"text":"Array of document types to be recognized. If ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" or empty, all document types will be recognized."}],"type":"paragraph"}]},{"name":"excludedFieldTypes","content":[{"inlineContent":[{"type":"text","text":"An array of normalized names for the document field types that should not be recognized."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate of the receiver."}]}],"name":"delegate"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController"]]},"abstract":[{"text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontroller\/init(accepteddocumenttypes:excludedfieldtypes:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontroller\/init(accepteddocumenttypes:excludedfieldtypes:delegate:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"acceptedDocumentTypes","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SBSDKGenericDocumentRootType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRootType"},{"kind":"text","text":"]?, "},{"text":"excludedFieldTypes","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKGenericDocumentRecognizerViewControllerDelegate","text":"SBSDKGenericDocumentRecognizerViewControllerDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAcceptedDocumentTypes:excludedFieldTypes:delegate:"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerViewController(im)initWithAcceptedDocumentTypes:excludedFieldTypes:delegate:","title":"init(acceptedDocumentTypes:excludedFieldTypes:delegate:)","symbolKind":"init","roleHeading":"Initializer"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRootType":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentroottype","kind":"symbol","abstract":[{"type":"text","text":"Root document type."}],"title":"SBSDKGenericDocumentRootType","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentRootType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentRootType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRootType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewController/init(acceptedDocumentTypes:excludedFieldTypes:delegate:)":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController\/init(acceptedDocumentTypes:excludedFieldTypes:delegate:)","abstract":[{"text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area.","type":"text"}],"title":"init(acceptedDocumentTypes:excludedFieldTypes:delegate:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"initWithAcceptedDocumentTypes:excludedFieldTypes:delegate:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontroller\/init(accepteddocumenttypes:excludedfieldtypes:delegate:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"acceptedDocumentTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRootType"},{"kind":"text","text":"]?, "},{"text":"excludedFieldTypes","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentRecognizerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKGenericDocumentRecognizerViewControllerDelegate"},{"kind":"text","text":"?)"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewController":{"role":"symbol","title":"SBSDKGenericDocumentRecognizerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerViewController"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController","type":"topic","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to recognize documents, e.g. German passports, ID cards and driver’s licenses on video frames."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewControllerDelegate":{"title":"SBSDKGenericDocumentRecognizerViewControllerDelegate","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontrollerdelegate","role":"symbol","abstract":[{"type":"text","text":"The delegate protocol for the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerViewControllerDelegate"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithAcceptedDocumentTypes:excludedFieldTypes:delegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAcceptedDocumentTypes:excludedFieldTypes:delegate:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithAcceptedDocumentTypes:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<SBSDKGenericDocumentRootType *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"acceptedDocumentTypes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"excludedFieldTypes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"excludedFieldTypes","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKGenericDocumentRecognizerViewControllerDelegate","text":"id<SBSDKGenericDocumentRecognizerViewControllerDelegate>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRootType\/title","value":"SBSDKGenericDocumentRootType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRootType\/fragments","value":[{"text":"SBSDKGenericDocumentRootType","kind":"identifier"}]},{"value":"initWithAcceptedDocumentTypes:excludedFieldTypes:delegate:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController~1init(acceptedDocumentTypes:excludedFieldTypes:delegate:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController~1init(acceptedDocumentTypes:excludedFieldTypes:delegate:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAcceptedDocumentTypes:excludedFieldTypes:delegate:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController\/title","value":"SBSDKGenericDocumentRecognizerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController\/fragments","value":[{"text":"SBSDKGenericDocumentRecognizerViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewControllerDelegate\/title","value":"SBSDKGenericDocumentRecognizerViewControllerDelegate"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewControllerDelegate\/fragments"}]}]}