{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzScannerIntroImage\/mrzIntroCustomImage(uri:)"},"metadata":{"role":"symbol","title":"mrzIntroCustomImage(uri:)","roleHeading":"Type Method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"mrzIntroCustomImageWithUri:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MrzScannerIntroImage(cm)mrzIntroCustomImageWithUri:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"mrzIntroCustomImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uri","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"SBSDKUI2MrzIntroCustomImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MrzIntroCustomImage"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"mrzIntroCustomImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uri","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroCustomImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MrzIntroCustomImage","kind":"typeIdentifier","text":"SBSDKUI2MrzIntroCustomImage"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzScannerIntroImage"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerintroimage\/mrzintrocustomimage(uri:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerintroimage\/mrzintrocustomimage(uri:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MrzScannerIntroImage/mrzIntroCustomImage(uri:)":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerintroimage\/mrzintrocustomimage(uri:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzScannerIntroImage\/mrzIntroCustomImage(uri:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzIntroCustomImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"uri","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2MrzIntroCustomImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MrzIntroCustomImage"}],"role":"symbol","title":"mrzIntroCustomImage(uri:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"mrzIntroCustomImageWithUri:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MrzIntroCustomImage":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2MrzIntroCustomImage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroCustomImage","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A custom image for the introduction screen."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzintrocustomimage","title":"SBSDKUI2MrzIntroCustomImage","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MrzIntroCustomImage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MrzScannerIntroImage":{"abstract":[{"type":"text","text":"Determines the image for the introduction screen."}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2MrzScannerIntroImage","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerintroimage","title":"SBSDKUI2MrzScannerIntroImage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MrzScannerIntroImage"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzScannerIntroImage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"mrzIntroCustomImageWithUri:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"mrzIntroCustomImageWithUri:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2MrzIntroCustomImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MrzIntroCustomImage","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroCustomImage"},{"text":" *) ","kind":"text"},{"text":"mrzIntroCustomImageWithUri:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"uri"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"mrzIntroCustomImageWithUri:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzScannerIntroImage~1mrzIntroCustomImage(uri:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"mrzIntroCustomImageWithUri:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzScannerIntroImage~1mrzIntroCustomImage(uri:)\/fragments"},{"op":"replace","value":"SBSDKUI2MrzIntroCustomImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzIntroCustomImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzIntroCustomImage\/fragments","value":[{"text":"SBSDKUI2MrzIntroCustomImage","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUI2MrzIntroCustomImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzIntroCustomImage\/navigatorTitle"},{"value":"SBSDKUI2MrzScannerIntroImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzScannerIntroImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzScannerIntroImage\/fragments","value":[{"text":"SBSDKUI2MrzScannerIntroImage","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MrzScannerIntroImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzScannerIntroImage\/navigatorTitle"}]}]}