{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateHandler"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProgessUpdateHandler","text":"SBSDKProgessUpdateHandler","kind":"typeIdentifier","preciseIdentifier":"s:24ScanbotBarcodeScannerSDK25SBSDKProgessUpdateHandlera"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"text":"The standard process for observing a ","type":"text"},{"type":"codeVoice","code":"Progress"},{"text":" progressing is to use KVO on the ","type":"text"},{"type":"codeVoice","code":"Progress"},{"type":"text","text":" instance."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"SBSDKProgressUpdateHandler","type":"codeVoice"},{"text":" simplifies observing the progress largely.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"It is called on main thread whenever the progress changes. Usually here you update your UI, e.g. "},{"code":"UIProgressView","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkprogress\/updatehandler"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkprogress\/updatehandler"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProgress"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProgress\/updateHandler"},"metadata":{"role":"symbol","title":"updateHandler","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKProgress(py)updateHandler","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"updateHandler","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKProgessUpdateHandler","preciseIdentifier":"s:24ScanbotBarcodeScannerSDK25SBSDKProgessUpdateHandlera"},{"kind":"text","text":"?"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"updateHandler","kind":"identifier"}],"symbolKind":"property"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKProgessUpdateHandler":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProgessUpdateHandler","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkprogessupdatehandler","title":"SBSDKProgessUpdateHandler","abstract":[{"text":"A closure typealias used on informing observers about progress updating.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProgessUpdateHandler","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKProgessUpdateHandler"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKProgress/updateHandler":{"navigatorTitle":[{"text":"updateHandler","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The standard process for observing a ","type":"text"},{"code":"Progress","type":"codeVoice"},{"text":" progressing is to use KVO on the ","type":"text"},{"type":"codeVoice","code":"Progress"},{"text":" instance.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"SBSDKProgressUpdateHandler","type":"codeVoice"},{"type":"text","text":" simplifies observing the progress largely."},{"type":"text","text":" "},{"text":"It is called on main thread whenever the progress changes. Usually here you update your UI, e.g. ","type":"text"},{"type":"codeVoice","code":"UIProgressView"},{"type":"text","text":"."}],"title":"updateHandler","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"updateHandler","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKProgessUpdateHandler","kind":"typeIdentifier","preciseIdentifier":"s:24ScanbotBarcodeScannerSDK25SBSDKProgessUpdateHandlera"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProgress\/updateHandler","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkprogress\/updatehandler"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKProgress":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProgress","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkprogress","title":"SBSDKProgress","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKProgress","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKProgress","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"updateHandler"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"updateHandler"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":" (^","kind":"text"},{"kind":"identifier","text":"updateHandler"},{"text":")(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProgress","text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKProgress"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":");","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProgress~1updateHandler\/title","value":"updateHandler"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProgress~1updateHandler\/fragments","op":"replace","value":[{"kind":"identifier","text":"updateHandler"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProgress\/title","op":"replace","value":"SBSDKProgress"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProgress\/fragments","op":"replace","value":[{"text":"SBSDKProgress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProgress\/navigatorTitle","op":"replace","value":[{"text":"SBSDKProgress","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}