{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/barcodeinfomappingloadingmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/barcodeinfomappingloadingmessage"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Loading message for barcode info mapping."},{"type":"text","text":" "},{"text":"Default is “Loading details…”","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingLoadingMessage","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeInfoMappingLoadingMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"roleHeading":"Instance Property","title":"barcodeInfoMappingLoadingMessage","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeTextLocalization(py)barcodeInfoMappingLoadingMessage","navigatorTitle":[{"kind":"identifier","text":"barcodeInfoMappingLoadingMessage"}],"role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeInfoMappingLoadingMessage"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/barcodeInfoMappingLoadingMessage":{"navigatorTitle":[{"kind":"identifier","text":"barcodeInfoMappingLoadingMessage"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/barcodeinfomappingloadingmessage","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"barcodeInfoMappingLoadingMessage","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"text":"Loading message for barcode info mapping.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is “Loading details…”"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingLoadingMessage","kind":"symbol","title":"barcodeInfoMappingLoadingMessage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization":{"role":"symbol","title":"SBSDKUI2BarcodeTextLocalization","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the all strings for barcode scanner."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"barcodeInfoMappingLoadingMessage"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"barcodeInfoMappingLoadingMessage","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"barcodeInfoMappingLoadingMessage","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"barcodeInfoMappingLoadingMessage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1barcodeInfoMappingLoadingMessage\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1barcodeInfoMappingLoadingMessage\/fragments","value":[{"kind":"identifier","text":"barcodeInfoMappingLoadingMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/title","value":"SBSDKUI2BarcodeTextLocalization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/fragments","value":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}