{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"cameraPermissionEnableCameraTitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"Camera permission denied!\", "},{"text":"cameraPermissionEnableCameraExplanation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" = \"Please allow the usage of the camera to start the scanning process.\", "},{"kind":"externalParam","text":"cameraPermissionEnableCameraButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"Grant permission\", ","kind":"text"},{"text":"cameraPermissionCloseButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"Close\", "},{"text":"topBarCancelButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" = \"Cancel\", "},{"kind":"externalParam","text":"topBarTitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"Scan Item\", "},{"kind":"externalParam","text":"userGuidance"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" = \"Move the finder over a barcode\", ","kind":"text"},{"kind":"externalParam","text":"barcodeInfoMappingLoadingMessage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"Loading details...\", "},{"kind":"externalParam","text":"barcodeInfoMappingErrorStateTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"Connection Error!\", "},{"text":"barcodeInfoMappingErrorStateSubtitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" = \"There was an issue and the data requested was not fetched. You could try again or discard this result to start a new scan.\", "},{"kind":"externalParam","text":"barcodeInfoMappingErrorStateRetryButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"Retry\", "},{"kind":"externalParam","text":"barcodeInfoMappingErrorStateCancelButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" = \"Cancel\", ","kind":"text"},{"kind":"externalParam","text":"manualCountEditDialogTitle"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"Update count\", "},{"text":"manualCountEditDialogInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" = \"Adjust the number of items you scanned.\", "},{"kind":"externalParam","text":"manualCountEditDialogUpdateButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" = \"Update\", "},{"text":"manualCountEditDialogCancelButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"Cancel\", "},{"kind":"externalParam","text":"sheetResetButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" = \"Reset\", ","kind":"text"},{"text":"sheetClearAllButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" = \"Clear all\", ","kind":"text"},{"kind":"externalParam","text":"sheetSubmitButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" = \"Submit\", "},{"kind":"externalParam","text":"sheetStartScanningButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"Start scanning\", "},{"text":"sheetPlaceholderTitle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" = \"No barcodes here!\", "},{"text":"sheetPlaceholderSubtitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"The barcode list is currently empty. Close this sheet and scan your items to add them.\", ","kind":"text"},{"text":"singleModeConfirmationCancelButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" = \"Close\", ","kind":"text"},{"text":"multipleModeSheetTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" = \"%d items\", ","kind":"text"},{"text":"findAndPickSheetTitle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" = \"%d\/%d scanned\", ","kind":"text"},{"text":"findAndPickSheetBarcodeItemSubtitle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" = \"%d\/%d added\", ","kind":"text"},{"text":"findAndPickPartialAlertTitle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" = \"Incomplete scan!\", ","kind":"text"},{"kind":"externalParam","text":"findAndPickPartialAlertSubtitle"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"Some codes are yet to be scanned. Proceed with submission anyway?\", "},{"text":"findAndPickPartialAlertCancelButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"Cancel\", "},{"text":"findAndPickPartialAlertSubmitButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" = \"Yes, Submit\", ","kind":"text"},{"text":"findAndPickCompleteAlertTitle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" = \"All codes found!\", "},{"text":"findAndPickCompleteAlertSubtitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" = \"You have successfully scanned all codes. Proceed with submission?\", "},{"text":"findAndPickCompleteAlertCancelButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" = \"Dismiss\", ","kind":"text"},{"text":"findAndPickCompleteAlertSubmitButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" = \"Submit\", "},{"kind":"externalParam","text":"accessibilityDescriptionFlashButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" = \"Toggle flash\", "},{"text":"accessibilityDescriptionZoomButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" = \"Toggle camera zoom\", ","kind":"text"},{"kind":"externalParam","text":"accessibilityDescriptionFlipCameraButton"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"Flip camera\")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/init(camerapermissionenablecameratitle:camerapermissionenablecameraexplanation:camerapermissionenablecamerabutton:camerapermissionclosebutton:topbarcancelbutton:topbartitle:userguidance:barcodeinfomappingloadingmessage:barcodeinfomappingerr-5aao0"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/init(camerapermissionenablecameratitle:camerapermissionenablecameraexplanation:camerapermissionenablecamerabutton:camerapermissionclosebutton:topbarcancelbutton:topbartitle:userguidance:barcodeinfomappingloadingmessage:barcodeinfomappingerr-5aao0"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","roleHeading":"Initializer","symbolKind":"init","navigatorTitle":[{"text":"initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cameraPermissionEnableCameraTitle"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPermissionEnableCameraExplanation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraPermissionEnableCameraButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"cameraPermissionCloseButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"topBarCancelButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topBarTitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userGuidance"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodeInfoMappingLoadingMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"barcodeInfoMappingErrorStateTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodeInfoMappingErrorStateSubtitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"barcodeInfoMappingErrorStateRetryButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodeInfoMappingErrorStateCancelButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"manualCountEditDialogTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"manualCountEditDialogInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"manualCountEditDialogUpdateButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"manualCountEditDialogCancelButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"sheetResetButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sheetClearAllButton"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sheetSubmitButton"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sheetStartScanningButton"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sheetPlaceholderTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"sheetPlaceholderSubtitle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"singleModeConfirmationCancelButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"multipleModeSheetTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"findAndPickSheetTitle"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"findAndPickSheetBarcodeItemSubtitle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"findAndPickPartialAlertTitle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"findAndPickPartialAlertSubtitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"findAndPickPartialAlertCancelButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"findAndPickPartialAlertSubmitButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"findAndPickCompleteAlertTitle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"findAndPickCompleteAlertSubtitle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"findAndPickCompleteAlertCancelButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"findAndPickCompleteAlertSubmitButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"accessibilityDescriptionFlashButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"accessibilityDescriptionZoomButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessibilityDescriptionFlipCameraButton"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeTextLocalization(im)initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:","modules":[{"name":"ScanbotSDK"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization":{"role":"symbol","title":"SBSDKUI2BarcodeTextLocalization","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the all strings for barcode scanner."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:)","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"cameraPermissionEnableCameraTitle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraPermissionEnableCameraButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"cameraPermissionCloseButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"topBarCancelButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"topBarTitle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"userGuidance","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"barcodeInfoMappingLoadingMessage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"barcodeInfoMappingErrorStateTitle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barcodeInfoMappingErrorStateSubtitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"barcodeInfoMappingErrorStateRetryButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodeInfoMappingErrorStateCancelButton"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"manualCountEditDialogTitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"manualCountEditDialogInfo","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"manualCountEditDialogUpdateButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"manualCountEditDialogCancelButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sheetResetButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sheetClearAllButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"sheetSubmitButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"sheetStartScanningButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sheetPlaceholderTitle"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"sheetPlaceholderSubtitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"singleModeConfirmationCancelButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"multipleModeSheetTitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"findAndPickSheetTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"findAndPickSheetBarcodeItemSubtitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"findAndPickPartialAlertTitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"findAndPickPartialAlertSubtitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"findAndPickPartialAlertCancelButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"findAndPickPartialAlertSubmitButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"findAndPickCompleteAlertTitle"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"findAndPickCompleteAlertSubtitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"findAndPickCompleteAlertCancelButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"findAndPickCompleteAlertSubmitButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"accessibilityDescriptionFlashButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"accessibilityDescriptionZoomButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"accessibilityDescriptionFlipCameraButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"title":"init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/init(camerapermissionenablecameratitle:camerapermissionenablecameraexplanation:camerapermissionenablecamerabutton:camerapermissionclosebutton:topbarcancelbutton:topbartitle:userguidance:barcodeinfomappingloadingmessage:barcodeinfomappingerr-5aao0"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCameraPermissionEnableCameraTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionEnableCameraTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermissionEnableCameraExplanation"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPermissionEnableCameraButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"cameraPermissionEnableCameraButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionCloseButton:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionCloseButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"topBarCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"topBarCancelButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"topBarTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"topBarTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"userGuidance:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userGuidance"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeInfoMappingLoadingMessage:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"barcodeInfoMappingLoadingMessage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeInfoMappingErrorStateTitle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"barcodeInfoMappingErrorStateTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeInfoMappingErrorStateSubtitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"barcodeInfoMappingErrorStateSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeInfoMappingErrorStateRetryButton:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"barcodeInfoMappingErrorStateRetryButton"},{"text":" ","kind":"text"},{"text":"barcodeInfoMappingErrorStateCancelButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"barcodeInfoMappingErrorStateCancelButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"manualCountEditDialogTitle:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"manualCountEditDialogTitle"},{"kind":"text","text":" "},{"text":"manualCountEditDialogInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"manualCountEditDialogInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"manualCountEditDialogUpdateButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"manualCountEditDialogUpdateButton"},{"text":" ","kind":"text"},{"kind":"identifier","text":"manualCountEditDialogCancelButton:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"manualCountEditDialogCancelButton"},{"text":" ","kind":"text"},{"text":"sheetResetButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sheetResetButton"},{"kind":"text","text":" "},{"text":"sheetClearAllButton:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"sheetClearAllButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sheetSubmitButton:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"sheetSubmitButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"sheetStartScanningButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"sheetStartScanningButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sheetPlaceholderTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sheetPlaceholderTitle"},{"text":" ","kind":"text"},{"text":"sheetPlaceholderSubtitle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sheetPlaceholderSubtitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"singleModeConfirmationCancelButton:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"singleModeConfirmationCancelButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"multipleModeSheetTitle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"multipleModeSheetTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"findAndPickSheetTitle:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"findAndPickSheetTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"findAndPickSheetBarcodeItemSubtitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"findAndPickSheetBarcodeItemSubtitle"},{"kind":"text","text":" "},{"text":"findAndPickPartialAlertTitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"findAndPickPartialAlertTitle"},{"text":" ","kind":"text"},{"text":"findAndPickPartialAlertSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"findAndPickPartialAlertSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"findAndPickPartialAlertCancelButton:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"findAndPickPartialAlertCancelButton"},{"kind":"text","text":" "},{"text":"findAndPickPartialAlertSubmitButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"findAndPickPartialAlertSubmitButton"},{"text":" ","kind":"text"},{"text":"findAndPickCompleteAlertTitle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"findAndPickCompleteAlertTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"findAndPickCompleteAlertSubtitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"findAndPickCompleteAlertSubtitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"findAndPickCompleteAlertCancelButton:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"findAndPickCompleteAlertCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"findAndPickCompleteAlertSubmitButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"findAndPickCompleteAlertSubmitButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionFlashButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionFlashButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionZoomButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionZoomButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionFlipCameraButton:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionFlipCameraButton"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/title","op":"replace","value":"SBSDKUI2BarcodeTextLocalization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:)\/title","value":"initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:)\/fragments"}]}]}