{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataIntroCustomImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"uri"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataIntroCustomImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataIntroCustomImage","kind":"typeIdentifier","text":"SBSDKUI2DocumentDataIntroCustomImage"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/documentDataIntroCustomImage(uri:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage\/documentdataintrocustomimage(uri:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage\/documentdataintrocustomimage(uri:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","title":"documentDataIntroCustomImage(uri:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDataIntroCustomImage"},{"kind":"text","text":"("},{"text":"uri","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"SBSDKUI2DocumentDataIntroCustomImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataIntroCustomImage"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentDataIntroCustomImageWithUri:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorIntroImage(cm)documentDataIntroCustomImageWithUri:"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataIntroCustomImage":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataIntroCustomImage"}],"abstract":[{"text":"A custom image for the introduction screen.","type":"text"}],"role":"symbol","title":"SBSDKUI2DocumentDataIntroCustomImage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataIntroCustomImage","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataintrocustomimage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataIntroCustomImage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroImage":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentDataExtractorIntroImage","kind":"identifier"}],"abstract":[{"text":"The image for the introduction screen of a document data extractor screen.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage","title":"SBSDKUI2DocumentDataExtractorIntroImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorIntroImage","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroImage/documentDataIntroCustomImage(uri:)":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/documentDataIntroCustomImage(uri:)","kind":"symbol","title":"documentDataIntroCustomImage(uri:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentDataIntroCustomImage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"uri"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2DocumentDataIntroCustomImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataIntroCustomImage"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentDataIntroCustomImageWithUri:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage\/documentdataintrocustomimage(uri:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"documentDataIntroCustomImageWithUri:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"documentDataIntroCustomImageWithUri:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"SBSDKUI2DocumentDataIntroCustomImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataIntroCustomImage","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataIntroCustomImage"},{"text":" *) ","kind":"text"},{"text":"documentDataIntroCustomImageWithUri:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"uri"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataIntroCustomImage\/title","value":"SBSDKUI2DocumentDataIntroCustomImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataIntroCustomImage\/fragments","value":[{"text":"SBSDKUI2DocumentDataIntroCustomImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataIntroCustomImage\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentDataIntroCustomImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage\/title","value":"SBSDKUI2DocumentDataExtractorIntroImage"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorIntroImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentDataExtractorIntroImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage\/navigatorTitle"},{"value":"documentDataIntroCustomImageWithUri:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage~1documentDataIntroCustomImage(uri:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage~1documentDataIntroCustomImage(uri:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"documentDataIntroCustomImageWithUri:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}