{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BadgedButton"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BadgedButton\/badgeForegroundColor"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2badgedbutton\/badgeforegroundcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2badgedbutton\/badgeforegroundcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"badgeForegroundColor","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BadgedButton(py)badgeForegroundColor","symbolKind":"property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badgeForegroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"}],"title":"badgeForegroundColor","roleHeading":"Instance Property","role":"symbol"},"abstract":[{"type":"text","text":"The color of the badge’s foreground (icon, text)."},{"type":"text","text":" "},{"type":"text","text":"Default is “#C8193C”"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badgeForegroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Color":{"type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"title":"SBSDKUI2Color","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2color","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BadgedButton/badgeForegroundColor":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2badgedbutton\/badgeforegroundcolor","navigatorTitle":[{"kind":"identifier","text":"badgeForegroundColor"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"badgeForegroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"}],"title":"badgeForegroundColor","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BadgedButton\/badgeForegroundColor","abstract":[{"type":"text","text":"The color of the badge’s foreground (icon, text)."},{"type":"text","text":" "},{"type":"text","text":"Default is “#C8193C”"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BadgedButton":{"title":"SBSDKUI2BadgedButton","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BadgedButton"}],"role":"symbol","abstract":[{"type":"text","text":"Configuration of the button with a badge."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BadgedButton"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2badgedbutton","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BadgedButton"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"badgeForegroundColor","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"badgeForegroundColor"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" * "},{"kind":"identifier","text":"badgeForegroundColor"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/title"},{"op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/navigatorTitle"},{"value":"badgeForegroundColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BadgedButton~1badgeForegroundColor\/title"},{"value":[{"text":"badgeForegroundColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BadgedButton~1badgeForegroundColor\/fragments"},{"value":"SBSDKUI2BadgedButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BadgedButton\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2BadgedButton"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BadgedButton\/fragments"},{"value":[{"text":"SBSDKUI2BadgedButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BadgedButton\/navigatorTitle"}]}]}