{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult\/displacementvector"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult\/displacementvector"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult\/displacementVector","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"displacementVector"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult(py)displacementVector","navigatorTitle":[{"kind":"identifier","text":"displacementVector"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"displacementVector"},"abstract":[{"type":"text","text":"The direction vector towards the center of the document if the document is partially visible"},{"type":"text","text":" "},{"type":"text","text":"in normalized coordinates."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displacementVector","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionResult/displacementVector":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult\/displacementVector","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult\/displacementvector","abstract":[{"type":"text","text":"The direction vector towards the center of the document if the document is partially visible"},{"type":"text","text":" "},{"type":"text","text":"in normalized coordinates."}],"title":"displacementVector","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"displacementVector"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"displacementVector"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionResult":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult","title":"SBSDKDocumentDetectionResult","role":"symbol","abstract":[{"text":"Result of the document contour detection.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"displacementVector"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"displacementVector","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":" "},{"kind":"identifier","text":"displacementVector"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult~1displacementVector\/title","value":"displacementVector"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult~1displacementVector\/fragments","value":[{"text":"displacementVector","kind":"identifier"}]},{"value":"SBSDKDocumentDetectionResult","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}