{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/UIScrollViewDelegate-Implementations"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"article","metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"collectionGroup","title":"UIScrollViewDelegate Implementations","roleHeading":"API Collection"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView"]]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/scrollViewDidZoom(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/viewForZooming(in:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKZoomingImageScrollView/viewForZooming(in:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewForZooming"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"viewForZoomingInScrollView:"}],"title":"viewForZooming(in:)","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/viewForZooming(in:)","url":"\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview\/viewforzooming(in:)","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKZoomingImageScrollView":{"role":"symbol","navigatorTitle":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView","url":"\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview","type":"topic","abstract":[{"type":"text","text":"A scrollable and zoomable "},{"type":"codeVoice","code":"UIScrollView"},{"type":"text","text":" subclass that displays images and an overlay view."}],"title":"SBSDKZoomingImageScrollView","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKZoomingImageScrollView/scrollViewDidZoom(_:)":{"title":"scrollViewDidZoom(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollViewDidZoom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIScrollView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview\/scrollviewdidzoom(_:)","abstract":[],"navigatorTitle":[{"text":"scrollViewDidZoom:","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/scrollViewDidZoom(_:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/scrollViewDidZoom(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/viewForZooming(in:)"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView~1viewForZooming(in:)\/title","value":"viewForZoomingInScrollView:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView~1viewForZooming(in:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewForZoomingInScrollView:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView\/title","value":"SBSDKZoomingImageScrollView","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView\/fragments","value":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView~1scrollViewDidZoom(_:)\/title","value":"scrollViewDidZoom:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView~1scrollViewDidZoom(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidZoom:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}