{"metadata":{"roleHeading":"Initializer","title":"init(storageLocation:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKKeyedImageStorage(im)initWithStorageLocation:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"initWithStorageLocation:","kind":"identifier"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"storageLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation","text":"SBSDKStorageLocation"},{"text":"?)","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"storageLocation"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation","kind":"typeIdentifier","text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation"},{"text":"? = SBSDKStorageLocation())","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"storageLocation","content":[{"inlineContent":[{"type":"text","text":"The storage location at which the new storage should reside."}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Initializes a new ","type":"text"},{"code":"SBSDKKeyedImageStorage","type":"codeVoice"},{"type":"text","text":" at the given storage location."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage\/init(storagelocation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage\/init(storagelocation:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage\/init(storageLocation:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageLocation":{"url":"\/documentation\/scanbotsdk\/sbsdkstoragelocation","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation","abstract":[{"text":"Descriptor and helper class for describing and creating a directory on the file system.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKStorageLocation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageLocation"}],"role":"symbol","title":"SBSDKStorageLocation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKKeyedImageStorage":{"url":"\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage","navigatorTitle":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A simple thread-safe multiple-reader-single-writer key-value fashioned disk image cache class."},{"text":" ","type":"text"},{"type":"text","text":"Manages images in a dictionary-like fashion."}],"title":"SBSDKKeyedImageStorage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKKeyedImageStorage/init(storageLocation:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"storageLocation"},{"text":": ","kind":"text"},{"text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage\/init(storagelocation:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage\/init(storageLocation:)","navigatorTitle":[{"kind":"identifier","text":"initWithStorageLocation:"}],"type":"topic","abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"SBSDKKeyedImageStorage"},{"type":"text","text":" at the given storage location."}],"title":"init(storageLocation:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithStorageLocation:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithStorageLocation:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithStorageLocation:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation","kind":"typeIdentifier","text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"storageLocation"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The storage location at which the new storage should reside.","type":"text"}]}],"name":"storageLocation"}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/title","op":"replace","value":"SBSDKStorageLocation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageLocation"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKStorageLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage\/title","value":"SBSDKKeyedImageStorage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage\/fragments","value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKKeyedImageStorage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage~1init(storageLocation:)\/title","value":"initWithStorageLocation:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage~1init(storageLocation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStorageLocation:"}]}]}]}