{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage\/init(storageLocation:fileFormat:encrypter:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"initWithStorageLocation:fileFormat:encrypter:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKKeyedImageStorage(im)initWithStorageLocation:fileFormat:encrypter:","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Initializer","role":"symbol","symbolKind":"init","title":"init(storageLocation:fileFormat:encrypter:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"storageLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation","text":"SBSDKStorageLocation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fileFormat"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat","kind":"typeIdentifier","text":"SBSDKImageFileFormat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"encrypter"},{"kind":"text","text":": "},{"text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"storageLocation"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation","text":"SBSDKStorageLocation"},{"text":"?, ","kind":"text"},{"text":"fileFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCrypting","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"storageLocation","content":[{"type":"paragraph","inlineContent":[{"text":"The storage location at which the new storage should reside.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The file format that should be used to store the images."}],"type":"paragraph"}],"name":"fileFormat"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The encrypter used to encrypt\/decrypt image data. If ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":", no encryption is used."}]}],"name":"encrypter"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Initializes a new "},{"code":"SBSDKKeyedImageStorage","type":"codeVoice"},{"type":"text","text":" at the given storage location with given image file format."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage\/init(storagelocation:fileformat:encrypter:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage\/init(storagelocation:fileformat:encrypter:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKKeyedImageStorage":{"url":"\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage","navigatorTitle":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A simple thread-safe multiple-reader-single-writer key-value fashioned disk image cache class."},{"text":" ","type":"text"},{"type":"text","text":"Manages images in a dictionary-like fashion."}],"title":"SBSDKKeyedImageStorage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageLocation":{"url":"\/documentation\/scanbotsdk\/sbsdkstoragelocation","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation","abstract":[{"text":"Descriptor and helper class for describing and creating a directory on the file system.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKStorageLocation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageLocation"}],"role":"symbol","title":"SBSDKStorageLocation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCrypting":{"role":"symbol","abstract":[{"text":"Protocol for implementing encryption and decryption of (streamed) data.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","url":"\/documentation\/scanbotsdk\/sbsdkstoragecrypting","title":"SBSDKStorageCrypting","navigatorTitle":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKKeyedImageStorage/init(storageLocation:fileFormat:encrypter:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithStorageLocation:fileFormat:encrypter:"}],"url":"\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage\/init(storagelocation:fileformat:encrypter:)","abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"SBSDKKeyedImageStorage"},{"type":"text","text":" at the given storage location with given image file format."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage\/init(storageLocation:fileFormat:encrypter:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"storageLocation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation","text":"SBSDKStorageLocation"},{"kind":"text","text":"?, "},{"text":"fileFormat","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat","text":"SBSDKImageFileFormat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKStorageCrypting","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?)"}],"role":"symbol","title":"init(storageLocation:fileFormat:encrypter:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFileFormat":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagefileformat","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKImageFileFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"Enumeration of supported image file types."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFileFormat"}],"title":"SBSDKImageFileFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithStorageLocation:fileFormat:encrypter:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithStorageLocation:fileFormat:encrypter:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithStorageLocation:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation","text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"storageLocation"},{"kind":"text","text":" "},{"text":"fileFormat:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat","text":"SBSDKImageFileFormat"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"fileFormat"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encrypter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SBSDKStorageCrypting>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting"},{"text":") ","kind":"text"},{"text":"encrypter","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The storage location at which the new storage should reside.","type":"text"}]}],"name":"storageLocation"},{"name":"fileFormat","content":[{"type":"paragraph","inlineContent":[{"text":"The file format that should be used to store the images.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The encrypter used to encrypt\/decrypt image data. If "},{"type":"codeVoice","code":"nil"},{"text":", no encryption is used.","type":"text"}]}],"name":"encrypter"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage\/title","value":"SBSDKKeyedImageStorage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage\/fragments","value":[{"kind":"identifier","text":"SBSDKKeyedImageStorage"}]},{"value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/title","value":"SBSDKStorageLocation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/fragments","op":"replace","value":[{"text":"SBSDKStorageLocation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/navigatorTitle","value":[{"text":"SBSDKStorageLocation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/title","op":"replace","value":"SBSDKStorageCrypting"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/fragments","value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/navigatorTitle","value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}]},{"value":"initWithStorageLocation:fileFormat:encrypter:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage~1init(storageLocation:fileFormat:encrypter:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage~1init(storageLocation:fileFormat:encrypter:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithStorageLocation:fileFormat:encrypter:","kind":"identifier"}]},{"op":"replace","value":"SBSDKImageFileFormat","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/title"},{"value":[{"text":"SBSDKImageFileFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/navigatorTitle","value":[{"text":"SBSDKImageFileFormat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}