{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon\/bezierPath(with:for:orientation:isFrontCamera:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","title":"bezierPath(with:for:orientation:isFrontCamera:)","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bezierPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","text":"AVCaptureVideoPreviewLayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIDeviceOrientation","text":"UIDeviceOrientation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isFrontCamera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath"}],"navigatorTitle":[{"kind":"identifier","text":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:"}],"symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon(im)bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:"},"sections":[],"abstract":[{"text":"Creates a UIBezierPath instance of the receiver for drawing purposes.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bezierPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"previewLayer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureVideoPreviewLayer","preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIDeviceOrientation","preciseIdentifier":"c:@E@UIDeviceOrientation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isFrontCamera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"}]}],"kind":"declarations"},{"parameters":[{"name":"cornerRadius","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The radius to use when drawing rounded corners."}]}]},{"name":"previewLayer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The preview layer the path is going to be presented on."}]}]},{"name":"orientation","content":[{"type":"paragraph","inlineContent":[{"text":"The device orientation. Used to calculate starting point.","type":"text"}]}]},{"name":"isFrontCamera","content":[{"type":"paragraph","inlineContent":[{"text":"Currently used camera - front camera. Used to calculate starting point.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An UIBezierPath instance representing the polygon.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon\/bezierpath(with:for:orientation:isfrontcamera:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon\/bezierpath(with:for:orientation:isfrontcamera:)"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygon":{"title":"SBSDKPolygon","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKPolygon","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon","kind":"symbol","abstract":[{"text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygon/bezierPath(with:for:orientation:isFrontCamera:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bezierPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVCaptureVideoPreviewLayer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIDeviceOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIDeviceOrientation"},{"text":", ","kind":"text"},{"text":"isFrontCamera","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"UIBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath"}],"navigatorTitle":[{"text":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:","kind":"identifier"}],"abstract":[{"type":"text","text":"Creates a UIBezierPath instance of the receiver for drawing purposes."}],"role":"symbol","title":"bezierPath(with:for:orientation:isFrontCamera:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon\/bezierpath(with:for:orientation:isfrontcamera:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon\/bezierPath(with:for:orientation:isFrontCamera:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"bezierPathWithCornerRadius:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cornerRadius","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forPreviewLayer:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","text":"AVCaptureVideoPreviewLayer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"previewLayer"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIDeviceOrientation","text":"UIDeviceOrientation"},{"kind":"text","text":") "},{"kind":"internalParam","text":"orientation"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFrontCamera:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isFrontCamera"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The radius to use when drawing rounded corners."}]}],"name":"cornerRadius"},{"content":[{"inlineContent":[{"text":"The preview layer the path is going to be presented on.","type":"text"}],"type":"paragraph"}],"name":"previewLayer"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The device orientation. Used to calculate starting point.","type":"text"}]}],"name":"orientation"},{"content":[{"inlineContent":[{"text":"Currently used camera - front camera. Used to calculate starting point.","type":"text"}],"type":"paragraph"}],"name":"isFrontCamera"}],"kind":"parameters"}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An UIBezierPath instance representing the polygon."}]}],"kind":"content"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/title","value":"SBSDKPolygon","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/fragments","value":[{"text":"SBSDKPolygon","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPolygon"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon~1bezierPath(with:for:orientation:isFrontCamera:)\/title","value":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon~1bezierPath(with:for:orientation:isFrontCamera:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}