{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentverificationreport\/initwithoverallverificationstatus:consistencyverificationreport:semanticsverificationreport:suspiciousdataverificationreport:invaliddataverificationreport:"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithOverallVerificationStatus:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentVerificationStatus","kind":"typeIdentifier","text":"SBSDKDocumentVerificationStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationStatus"},{"kind":"text","text":") "},{"kind":"internalParam","text":"overallVerificationStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"consistencyVerificationReport:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKConsistencyVerificationReport","kind":"typeIdentifier","text":"SBSDKConsistencyVerificationReport","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"consistencyVerificationReport"},{"kind":"text","text":" "},{"kind":"identifier","text":"semanticsVerificationReport:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSemanticsVerificationReport","kind":"typeIdentifier","text":"SBSDKSemanticsVerificationReport","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"semanticsVerificationReport"},{"kind":"text","text":" "},{"kind":"identifier","text":"suspiciousDataVerificationReport:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSuspiciousDataVerificationReport","kind":"typeIdentifier","text":"SBSDKSuspiciousDataVerificationReport","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"suspiciousDataVerificationReport"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidDataVerificationReport:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKInvalidDataVerificationReport","kind":"typeIdentifier","text":"SBSDKInvalidDataVerificationReport","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"invalidDataVerificationReport"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationReport\/initWithOverallVerificationStatus:consistencyVerificationReport:semanticsVerificationReport:suspiciousDataVerificationReport:invalidDataVerificationReport:","interfaceLanguage":"occ"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationReport"]]},"metadata":{"title":"initWithOverallVerificationStatus:consistencyVerificationReport:semanticsVerificationReport:suspiciousDataVerificationReport:invalidDataVerificationReport:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithOverallVerificationStatus:consistencyVerificationReport:semanticsVerificationReport:suspiciousDataVerificationReport:invalidDataVerificationReport:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentVerificationReport(im)initWithOverallVerificationStatus:consistencyVerificationReport:semanticsVerificationReport:suspiciousDataVerificationReport:invalidDataVerificationReport:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"initWithOverallVerificationStatus:consistencyVerificationReport:semanticsVerificationReport:suspiciousDataVerificationReport:invalidDataVerificationReport:","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKInvalidDataVerificationReport":{"type":"topic","navigatorTitle":[{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport","title":"SBSDKInvalidDataVerificationReport","abstract":[{"type":"text","text":"Report of the field validation verification."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentVerificationStatus":{"kind":"symbol","type":"topic","title":"SBSDKDocumentVerificationStatus","abstract":[{"text":"Overall status of the document verification.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentverificationstatus","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationStatus","navigatorTitle":[{"text":"SBSDKDocumentVerificationStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentVerificationStatus","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentVerificationReport":{"title":"SBSDKDocumentVerificationReport","kind":"symbol","abstract":[{"text":"Report of the document verification.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationReport","url":"\/documentation\/scanbotsdk\/sbsdkdocumentverificationreport","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentVerificationReport","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentVerificationReport","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConsistencyVerificationReport":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport","abstract":[{"text":"Report of the document consistency verification. Shows whether information in the fields that correspond to the same","type":"text"},{"text":" ","type":"text"},{"text":"logical field is consistent.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport","navigatorTitle":[{"text":"SBSDKConsistencyVerificationReport","kind":"identifier"}],"type":"topic","title":"SBSDKConsistencyVerificationReport","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKConsistencyVerificationReport","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSuspiciousDataVerificationReport":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSuspiciousDataVerificationReport","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKSuspiciousDataVerificationReport","kind":"identifier"}],"title":"SBSDKSuspiciousDataVerificationReport","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport","kind":"symbol","abstract":[{"type":"text","text":"Report of the suspicious data document verification."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdksuspiciousdataverificationreport","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentVerificationReport/initWithOverallVerificationStatus:consistencyVerificationReport:semanticsVerificationReport:suspiciousDataVerificationReport:invalidDataVerificationReport:":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithOverallVerificationStatus:consistencyVerificationReport:semanticsVerificationReport:suspiciousDataVerificationReport:invalidDataVerificationReport:"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentverificationreport\/initwithoverallverificationstatus:consistencyverificationreport:semanticsverificationreport:suspiciousdataverificationreport:invaliddataverificationreport:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationReport\/initWithOverallVerificationStatus:consistencyVerificationReport:semanticsVerificationReport:suspiciousDataVerificationReport:invalidDataVerificationReport:","title":"initWithOverallVerificationStatus:consistencyVerificationReport:semanticsVerificationReport:suspiciousDataVerificationReport:invalidDataVerificationReport:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOverallVerificationStatus:consistencyVerificationReport:semanticsVerificationReport:suspiciousDataVerificationReport:invalidDataVerificationReport:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport","title":"SBSDKSemanticsVerificationReport","abstract":[{"type":"text","text":"Report of the document value semantics verification."}],"navigatorTitle":[{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKInvalidDataVerificationReport","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport\/title"},{"value":[{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKInvalidDataVerificationReport"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport\/navigatorTitle"},{"value":"SBSDKDocumentVerificationStatus","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationStatus\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentVerificationStatus"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationStatus\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentVerificationStatus"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationStatus\/navigatorTitle"},{"value":"SBSDKDocumentVerificationReport","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationReport\/title"},{"value":[{"text":"SBSDKDocumentVerificationReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationReport\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentVerificationReport"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationReport\/navigatorTitle"},{"value":"SBSDKConsistencyVerificationReport","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/title"},{"value":[{"text":"SBSDKConsistencyVerificationReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/fragments"},{"value":[{"text":"SBSDKConsistencyVerificationReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/navigatorTitle"},{"value":"SBSDKSuspiciousDataVerificationReport","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport\/title"},{"value":[{"text":"SBSDKSuspiciousDataVerificationReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKSuspiciousDataVerificationReport"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport\/navigatorTitle"},{"value":"SBSDKSemanticsVerificationReport","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/title"},{"value":[{"kind":"identifier","text":"SBSDKSemanticsVerificationReport"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/fragments"},{"value":[{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/navigatorTitle"}]}]}