{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationReport"]]},"abstract":[{"type":"text","text":"Some fields in the documents allow validation, for example, MRZ contains check digits to verify the data. This"},{"type":"text","text":" "},{"type":"text","text":"report shows whether there are any invalid fields in the document."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationReport\/invalidDataVerificationReport"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"invalidDataVerificationReport","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentVerificationReport(py)invalidDataVerificationReport","role":"symbol","navigatorTitle":[{"text":"invalidDataVerificationReport","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidDataVerificationReport"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKInvalidDataVerificationReport","text":"SBSDKInvalidDataVerificationReport"}]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidDataVerificationReport","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKInvalidDataVerificationReport","text":"SBSDKInvalidDataVerificationReport","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentverificationreport\/invaliddataverificationreport"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentverificationreport\/invaliddataverificationreport"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKInvalidDataVerificationReport":{"type":"topic","navigatorTitle":[{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport","title":"SBSDKInvalidDataVerificationReport","abstract":[{"type":"text","text":"Report of the field validation verification."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentVerificationReport":{"title":"SBSDKDocumentVerificationReport","kind":"symbol","abstract":[{"text":"Report of the document verification.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationReport","url":"\/documentation\/scanbotsdk\/sbsdkdocumentverificationreport","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentVerificationReport","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentVerificationReport","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentVerificationReport/invalidDataVerificationReport":{"navigatorTitle":[{"text":"invalidDataVerificationReport","kind":"identifier"}],"type":"topic","title":"invalidDataVerificationReport","abstract":[{"type":"text","text":"Some fields in the documents allow validation, for example, MRZ contains check digits to verify the data. This"},{"type":"text","text":" "},{"type":"text","text":"report shows whether there are any invalid fields in the document."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationReport\/invalidDataVerificationReport","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidDataVerificationReport","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKInvalidDataVerificationReport","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKInvalidDataVerificationReport","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentverificationreport\/invaliddataverificationreport"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"invalidDataVerificationReport"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"invalidDataVerificationReport","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKInvalidDataVerificationReport","text":"SBSDKInvalidDataVerificationReport","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport"},{"text":" * ","kind":"text"},{"text":"invalidDataVerificationReport","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport\/title","value":"SBSDKInvalidDataVerificationReport"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport\/fragments","value":[{"kind":"identifier","text":"SBSDKInvalidDataVerificationReport"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport\/navigatorTitle","value":[{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationReport\/title","value":"SBSDKDocumentVerificationReport"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationReport\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentVerificationReport"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationReport\/navigatorTitle","value":[{"text":"SBSDKDocumentVerificationReport","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationReport~1invalidDataVerificationReport\/title","value":"invalidDataVerificationReport"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationReport~1invalidDataVerificationReport\/fragments","value":[{"text":"invalidDataVerificationReport","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}