{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionConfirmationSubmitButton"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Default is “Submit VIN scan result”"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"accessibilityDescriptionConfirmationSubmitButton"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"accessibilityDescriptionConfirmationSubmitButton","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerScreenTextLocalization(py)accessibilityDescriptionConfirmationSubmitButton","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionConfirmationSubmitButton"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"abstract":[{"type":"text","text":"Accessibility description for the submit button in the text pattern confirmation alert."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptionconfirmationsubmitbutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptionconfirmationsubmitbutton"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionConfirmationSubmitButton","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the all strings for generic text scanner screen."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VINScannerScreenTextLocalization"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2VINScannerScreenTextLocalization","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization","title":"SBSDKUI2VINScannerScreenTextLocalization","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/accessibilityDescriptionConfirmationSubmitButton":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionConfirmationSubmitButton","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"text":"Accessibility description for the submit button in the text pattern confirmation alert.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionConfirmationSubmitButton","type":"topic","title":"accessibilityDescriptionConfirmationSubmitButton","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptionconfirmationsubmitbutton","kind":"symbol","navigatorTitle":[{"text":"accessibilityDescriptionConfirmationSubmitButton","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"accessibilityDescriptionConfirmationSubmitButton","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"accessibilityDescriptionConfirmationSubmitButton"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"accessibilityDescriptionConfirmationSubmitButton","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization\/title","op":"replace","value":"SBSDKUI2VINScannerScreenTextLocalization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerScreenTextLocalization"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2VINScannerScreenTextLocalization","kind":"identifier"}]},{"value":"accessibilityDescriptionConfirmationSubmitButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionConfirmationSubmitButton\/title"},{"value":[{"text":"accessibilityDescriptionConfirmationSubmitButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionConfirmationSubmitButton\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}