{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Palette(py)sbColorSurfaceHigh","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbColorSurfaceHigh","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"sbColorSurfaceHigh","kind":"identifier"}],"title":"sbColorSurfaceHigh"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Palette\/sbColorSurfaceHigh","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbColorSurfaceHigh","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is “#0000007A”","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"The color with a high alpha (transparency) value used for certain surfaces."}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2palette\/sbcolorsurfacehigh"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2palette\/sbcolorsurfacehigh"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Palette"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Palette/sbColorSurfaceHigh":{"type":"topic","kind":"symbol","abstract":[{"text":"The color with a high alpha (transparency) value used for certain surfaces.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2palette\/sbcolorsurfacehigh","title":"sbColorSurfaceHigh","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbColorSurfaceHigh","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Palette\/sbColorSurfaceHigh","navigatorTitle":[{"text":"sbColorSurfaceHigh","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"url":"\/documentation\/scanbotsdk\/sbsdkui2color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"type":"topic","title":"SBSDKUI2Color","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Palette":{"type":"topic","abstract":[{"type":"text","text":"Value palette describing the colors of the scanner screens."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Palette","title":"SBSDKUI2Palette","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Palette"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2palette","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Palette"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"sbColorSurfaceHigh","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"sbColorSurfaceHigh"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":" * ","kind":"text"},{"text":"sbColorSurfaceHigh","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"sbColorSurfaceHigh","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette~1sbColorSurfaceHigh\/title"},{"value":[{"kind":"identifier","text":"sbColorSurfaceHigh"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette~1sbColorSurfaceHigh\/fragments"},{"value":"SBSDKUI2Color","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle"},{"value":"SBSDKUI2Palette","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette\/title"},{"value":[{"text":"SBSDKUI2Palette","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2Palette"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}