{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicleSafetyInspectionData"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData","text":"SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelAAMVA\/vehicleSafetyInspectionData","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vehicleSafetyInspectionData","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData","text":"SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData"},{"kind":"text","text":"?"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"vehicleSafetyInspectionData","navigatorTitle":[{"kind":"identifier","text":"vehicleSafetyInspectionData"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelAAMVA(py)vehicleSafetyInspectionData","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"text":"The child document of type “VehicleSafetyInspectionData”.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelaamva\/vehiclesafetyinspectiondata"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelaamva\/vehiclesafetyinspectiondata"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelAAMVA"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelAAMVA/vehicleSafetyInspectionData":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"vehicleSafetyInspectionData","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelaamva\/vehiclesafetyinspectiondata","abstract":[{"type":"text","text":"The child document of type “VehicleSafetyInspectionData”."}],"title":"vehicleSafetyInspectionData","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelAAMVA\/vehicleSafetyInspectionData","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"vehicleSafetyInspectionData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelaamvavehiclesafetyinspectiondata","kind":"symbol","abstract":[{"text":"Vehicle Safety Inspection Data. File type “VS”.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData","kind":"identifier"}],"title":"SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelAAMVA":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelAAMVA","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"AAMVA"}],"title":"SBSDKBarcodeDocumentModelAAMVA","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelAAMVA","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelaamva","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelAAMVA"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"vehicleSafetyInspectionData"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"vehicleSafetyInspectionData"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData","text":"SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData"},{"kind":"text","text":" * "},{"kind":"identifier","text":"vehicleSafetyInspectionData"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"vehicleSafetyInspectionData","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelAAMVA~1vehicleSafetyInspectionData\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"vehicleSafetyInspectionData"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelAAMVA~1vehicleSafetyInspectionData\/fragments"},{"op":"replace","value":"SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData\/fragments","value":[{"text":"SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelAAMVAVehicleSafetyInspectionData\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelAAMVA\/title","value":"SBSDKBarcodeDocumentModelAAMVA"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelAAMVA\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeDocumentModelAAMVA","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelAAMVA\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeDocumentModelAAMVA","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}