{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/fillIn","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/fillin"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/fillin"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"SBSDKPDFRendererPageFitMode.fillIn","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fillIn"}],"navigatorTitle":[{"text":"SBSDKPDFRendererPageFitModeFillIn","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode@SBSDKPDFRendererPageFitModeFillIn","role":"symbol","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"fillIn","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode":{"abstract":[{"type":"text","text":"An enum describing the mode of how images are fitted into a PDF page."}],"title":"SBSDKPDFRendererPageFitMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode/fillIn":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/fillIn","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fillIn"}],"navigatorTitle":[{"text":"SBSDKPDFRendererPageFitModeFillIn","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/fillin","kind":"symbol","type":"topic","role":"symbol","title":"SBSDKPDFRendererPageFitMode.fillIn"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKPDFRendererPageFitModeFillIn"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKPDFRendererPageFitModeFillIn","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitModeFillIn"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode\/title","value":"SBSDKPDFRendererPageFitMode"},{"value":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1fillIn\/title","op":"replace","value":"SBSDKPDFRendererPageFitModeFillIn"},{"value":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitModeFillIn"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1fillIn\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}