{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/none"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/none"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitModeNone"}],"symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKPDFRendererPageFitMode.none","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode@SBSDKPDFRendererPageFitModeNone"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/none"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode/none":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/none","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/none","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"title":"SBSDKPDFRendererPageFitMode.none","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitModeNone"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode","abstract":[{"type":"text","text":"An enum describing the mode of how images are fitted into a PDF page."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}],"title":"SBSDKPDFRendererPageFitMode","navigatorTitle":[{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKPDFRendererPageFitModeNone"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitModeNone"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitModeNone"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1none\/title","value":"SBSDKPDFRendererPageFitModeNone"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1none\/fragments","value":[{"text":"SBSDKPDFRendererPageFitModeNone","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode\/title","value":"SBSDKPDFRendererPageFitMode","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode\/fragments"}]}]}