{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/rawrepresentable-implementations"]}],"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/hashValue"],"anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/hash(into:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/RawRepresentable-Implementations"},"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode"]]},"metadata":{"roleHeading":"API Collection","title":"RawRepresentable Implementations","role":"collectionGroup","modules":[{"name":"ScanbotSDK"}]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum describing the mode of how images are fitted into a PDF page."}],"title":"SBSDKPDFRendererPageFitMode","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode","navigatorTitle":[{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode/hashValue":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"role":"symbol","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"title":"hashValue","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/hashValue","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/hashvalue","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode/hash(into:)":{"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/hash(into:)","role":"symbol","title":"hash(into:)","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/hash(into:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"inout"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKPDFRendererPageFitMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode\/title"},{"value":[{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode\/navigatorTitle"}]}]}