{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroDefaultImage"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"fragments":[{"kind":"identifier","text":"hash"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"hash","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MrzIntroDefaultImage(py)hash"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzintrodefaultimage\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroDefaultImage\/hash","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MrzIntroDefaultImage":{"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzintrodefaultimage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroDefaultImage","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2MrzIntroDefaultImage"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MrzIntroDefaultImage"}],"abstract":[{"type":"text","text":"No image for the introduction screen."}],"role":"symbol","title":"SBSDKUI2MrzIntroDefaultImage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MrzIntroDefaultImage/hash":{"kind":"symbol","title":"hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroDefaultImage\/hash","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzintrodefaultimage\/hash","fragments":[{"kind":"identifier","text":"hash"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2MrzIntroDefaultImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzIntroDefaultImage\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MrzIntroDefaultImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzIntroDefaultImage\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzIntroDefaultImage\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MrzIntroDefaultImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}