{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewMorePopupMenu\/reorderPages"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"reorderPages","navigatorTitle":[{"text":"reorderPages","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReviewMorePopupMenu(py)reorderPages","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reorderPages"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PopupMenuItem","kind":"typeIdentifier","text":"SBSDKUI2PopupMenuItem"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewMorePopupMenu"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reorderPages","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PopupMenuItem","text":"SBSDKUI2PopupMenuItem","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PopupMenuItem"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewmorepopupmenu\/reorderpages"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewmorepopupmenu\/reorderpages"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"Configuration of the ‘reorder pages’ button.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PopupMenuItem":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Configuration for the popup menu items."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PopupMenuItem","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2popupmenuitem","title":"SBSDKUI2PopupMenuItem"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewMorePopupMenu/reorderPages":{"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reorderPages","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2PopupMenuItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PopupMenuItem"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewMorePopupMenu\/reorderPages","abstract":[{"text":"Configuration of the ‘reorder pages’ button.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewmorepopupmenu\/reorderpages","navigatorTitle":[{"text":"reorderPages","kind":"identifier"}],"title":"reorderPages","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewMorePopupMenu":{"title":"SBSDKUI2ReviewMorePopupMenu","type":"topic","abstract":[{"text":"Configuration of the ‘more’ popup menu for the review screen.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2ReviewMorePopupMenu","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewmorepopupmenu","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewMorePopupMenu","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ReviewMorePopupMenu","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"reorderPages"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"reorderPages"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PopupMenuItem","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PopupMenuItem","text":"SBSDKUI2PopupMenuItem"},{"kind":"text","text":" * "},{"kind":"identifier","text":"reorderPages"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PopupMenuItem\/title","value":"SBSDKUI2PopupMenuItem"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PopupMenuItem\/fragments","value":[{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PopupMenuItem\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2PopupMenuItem"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewMorePopupMenu~1reorderPages\/title","value":"reorderPages"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewMorePopupMenu~1reorderPages\/fragments","value":[{"text":"reorderPages","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewMorePopupMenu\/title","value":"SBSDKUI2ReviewMorePopupMenu"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewMorePopupMenu\/fragments","value":[{"text":"SBSDKUI2ReviewMorePopupMenu","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewMorePopupMenu\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ReviewMorePopupMenu"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}