{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextorientation\/notrecognized"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdktextorientation\/notrecognized"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","metadata":{"title":"SBSDKTextOrientation.notRecognized","role":"symbol","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKTextOrientation@SBSDKTextOrientationNotRecognized","navigatorTitle":[{"text":"SBSDKTextOrientationNotRecognized","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notRecognized"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notRecognized","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation\/notRecognized","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The text orientation has not been recognized (bad image quality, etc)."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextOrientation/notRecognized":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation\/notRecognized","title":"SBSDKTextOrientation.notRecognized","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notRecognized","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktextorientation\/notrecognized","role":"symbol","abstract":[{"text":"The text orientation has not been recognized (bad image quality, etc).","type":"text"}],"type":"topic","navigatorTitle":[{"text":"SBSDKTextOrientationNotRecognized","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextOrientation":{"navigatorTitle":[{"text":"SBSDKTextOrientation","kind":"identifier"}],"type":"topic","title":"SBSDKTextOrientation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation","abstract":[{"text":"An enum to describes the detected orientation of text in an image.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextorientation","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextOrientation","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKTextOrientationNotRecognized"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKTextOrientationNotRecognized","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKTextOrientationNotRecognized"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextOrientation~1notRecognized\/title","value":"SBSDKTextOrientationNotRecognized"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextOrientation~1notRecognized\/fragments","value":[{"kind":"identifier","text":"SBSDKTextOrientationNotRecognized"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextOrientation\/title","value":"SBSDKTextOrientation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextOrientation\/fragments","value":[{"text":"SBSDKTextOrientation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextOrientation\/navigatorTitle","value":[{"text":"SBSDKTextOrientation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}