{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerConfiguration","kind":"typeIdentifier","text":"SBSDKBarcodeScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerConfiguration"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The new configuration.","type":"text"}]}],"name":"configuration"}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Sets the configuration of the receiver."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner\/setConfiguration(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner\/setconfiguration(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner\/setconfiguration(_:)"]}],"metadata":{"navigatorTitle":[{"text":"setConfiguration:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanner(im)setConfiguration:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConfiguration"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerConfiguration","text":"SBSDKBarcodeScannerConfiguration","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"setConfiguration(_:)","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Method","role":"symbol"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanner":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScanner"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner","abstract":[{"text":"A class to scan most types of barcodes and QR codes, data matrices etc. on various image sources.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScanner"}],"title":"SBSDKBarcodeScanner","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanner/setConfiguration(_:)":{"role":"symbol","navigatorTitle":[{"text":"setConfiguration:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner\/setConfiguration(_:)","abstract":[{"type":"text","text":"Sets the configuration of the receiver."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConfiguration"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerConfiguration","text":"SBSDKBarcodeScannerConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"setConfiguration(_:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner\/setconfiguration(_:)","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerConfiguration":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"abstract":[{"type":"text","text":"Configuration for the barcode scanner."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerconfiguration","navigatorTitle":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"title":"SBSDKBarcodeScannerConfiguration","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setConfiguration:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setConfiguration:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setConfiguration:"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"configuration","content":[{"inlineContent":[{"type":"text","text":"The new configuration."}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner\/title","op":"replace","value":"SBSDKBarcodeScanner"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner\/fragments","value":[{"text":"SBSDKBarcodeScanner","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKBarcodeScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner~1setConfiguration(_:)\/title","value":"setConfiguration:"},{"value":[{"text":"- ","kind":"text"},{"text":"setConfiguration:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner~1setConfiguration(_:)\/fragments","op":"replace"},{"value":"SBSDKBarcodeScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerConfiguration\/title"},{"value":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerConfiguration\/fragments"},{"value":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}