{"abstract":[{"type":"text","text":"Initialize the VIN scanner."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKVINScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration"},{"text":" = SBSDKVINScannerConfiguration(  )) ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"inlineContent":[{"text":"The configuration to use for the VIN scanner.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"style":"note","name":"Throws","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKError"},{"text":" in case of an error.","type":"text"}]}],"type":"aside"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"init(configuration:)","roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"symbolKind":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScanner(im)initWithConfiguration:error:","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerConfiguration","text":"SBSDKVINScannerConfiguration"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:error:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScanner"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinscanner\/init(configuration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinscanner\/init(configuration:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScanner\/init(configuration:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScanner/init(configuration:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScanner\/init(configuration:)","abstract":[{"type":"text","text":"Initialize the VIN scanner."}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerConfiguration","text":"SBSDKVINScannerConfiguration","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"initWithConfiguration:error:","kind":"identifier"}],"title":"init(configuration:)","url":"\/documentation\/scanbotsdk\/sbsdkvinscanner\/init(configuration:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScanner":{"title":"SBSDKVINScanner","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScanner","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinscanner","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINScanner","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKVINScanner","kind":"identifier"}],"abstract":[{"type":"text","text":"API for VIN scanning."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKError":{"abstract":[{"type":"text","text":"Represents errors that can occur within the Scanbot SDK."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKError","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkerror","title":"SBSDKError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKError","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKError","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINScannerConfiguration","kind":"identifier"}],"kind":"symbol","title":"SBSDKVINScannerConfiguration","abstract":[{"type":"text","text":"Configuration for the VIN scanner."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKVINScannerConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithConfiguration:error:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:error:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKVINScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The configuration to use for the VIN scanner."}],"type":"paragraph"}],"name":"configuration"},{"content":[{"inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}],"type":"paragraph"}],"name":"error"}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScanner~1init(configuration:)\/title","op":"replace","value":"initWithConfiguration:error:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScanner~1init(configuration:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScanner\/title","op":"replace","value":"SBSDKVINScanner"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScanner\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVINScanner"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScanner\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKVINScanner"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/title","op":"replace","value":"SBSDKVINScannerConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKVINScannerConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKVINScannerConfiguration","kind":"identifier"}]}]}]}