{"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","title":"isEqual:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BackgroundStyle(im)isEqual:"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2backgroundstyle\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BackgroundStyle"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BackgroundStyle\/isEqual:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BackgroundStyle/isEqual:":{"title":"isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2backgroundstyle\/isequal:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BackgroundStyle\/isEqual:","role":"symbol","kind":"symbol","type":"topic","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BackgroundStyle":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2backgroundstyle","title":"SBSDKUI2BackgroundStyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BackgroundStyle","navigatorTitle":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}],"type":"topic","abstract":[{"text":"Configuration of the background appearance for buttons and hints.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BackgroundStyle\/title","value":"SBSDKUI2BackgroundStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BackgroundStyle\/fragments","value":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BackgroundStyle\/navigatorTitle","value":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}