{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDefaultContentValidator\/initWithAllowedCharacters:"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdefaultcontentvalidator\/initwithallowedcharacters:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithAllowedCharacters:"}],"title":"initWithAllowedCharacters:","symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDefaultContentValidator(im)initWithAllowedCharacters:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAllowedCharacters:"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAllowedCharacters:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"allowedCharacters"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDefaultContentValidator"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDefaultContentValidator/initWithAllowedCharacters:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDefaultContentValidator\/initWithAllowedCharacters:","navigatorTitle":[{"text":"initWithAllowedCharacters:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdefaultcontentvalidator\/initwithallowedcharacters:","kind":"symbol","title":"initWithAllowedCharacters:","role":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithAllowedCharacters:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDefaultContentValidator":{"kind":"symbol","title":"SBSDKDefaultContentValidator","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Default content validator. Accepts only non-empty strings."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDefaultContentValidator"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDefaultContentValidator","url":"\/documentation\/scanbotsdk\/sbsdkdefaultcontentvalidator","navigatorTitle":[{"kind":"identifier","text":"SBSDKDefaultContentValidator"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDefaultContentValidator\/title","op":"replace","value":"SBSDKDefaultContentValidator"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDefaultContentValidator\/fragments","op":"replace","value":[{"text":"SBSDKDefaultContentValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDefaultContentValidator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDefaultContentValidator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}