{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/enableCameraTextConfiguration","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"SBSDKUIEnableCameraTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraTextConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"enableCameraTextConfiguration"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorViewController(py)enableCameraTextConfiguration","title":"enableCameraTextConfiguration","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","fragments":[{"text":"enableCameraTextConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"enableCameraTextConfiguration"}],"role":"symbol","roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/enablecameratextconfiguration"]}],"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraTextConfiguration":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"title":"SBSDKUIEnableCameraTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuienablecameratextconfiguration","abstract":[{"text":"Configuration for the textual contents of camera based view controllers.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController/enableCameraTextConfiguration":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/enablecameratextconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/enableCameraTextConfiguration","kind":"symbol","role":"symbol","fragments":[{"text":"enableCameraTextConfiguration","kind":"identifier"}],"title":"enableCameraTextConfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController":{"navigatorTitle":[{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","title":"SBSDKUIDocumentDataExtractorViewController","abstract":[{"text":"A highly customizable camera-based view controller to extract generic documents data.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUIEnableCameraTextConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}]},{"value":"SBSDKUIDocumentDataExtractorViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/navigatorTitle","value":[{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}]}]}]}