{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/updateflashbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"updateFlashButton","kind":"identifier"},{"kind":"text","text":";"}]}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"updateFlashButton"}],"title":"updateFlashButton","symbolKind":"method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"updateFlashButton","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorViewController(im)updateFlashButton"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/updateFlashButton"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController/updateFlashButton":{"navigatorTitle":[{"text":"updateFlashButton","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/updateflashbutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/updateFlashButton","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"updateFlashButton","kind":"identifier"}],"title":"updateFlashButton","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController":{"navigatorTitle":[{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","title":"SBSDKUIDocumentDataExtractorViewController","abstract":[{"text":"A highly customizable camera-based view controller to extract generic documents data.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUIDocumentDataExtractorViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}],"op":"replace"},{"value":[{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/navigatorTitle"}]}]}