{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"didHideEnableCameraView","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraViewController(im)didHideEnableCameraView","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didHideEnableCameraView"},{"kind":"text","text":"()"}],"title":"didHideEnableCameraView()","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didHideEnableCameraView","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Override to perform custom actions after disappearing of the enable-camera-view.","type":"text"},{"text":" ","type":"text"},{"text":"For example: hide the container or show some buttons.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller\/didhideenablecameraview()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller\/didhideenablecameraview()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A method for subclassing."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController\/didHideEnableCameraView()","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraViewController":{"navigatorTitle":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","type":"reference","isActive":true},{"text":" subclass which adds support for enabled and disabled camera permission.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICameraViewController"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller","kind":"symbol","title":"SBSDKUICameraViewController","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraViewController/didHideEnableCameraView()":{"abstract":[{"type":"text","text":"A method for subclassing."}],"navigatorTitle":[{"text":"didHideEnableCameraView","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didHideEnableCameraView"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController\/didHideEnableCameraView()","title":"didHideEnableCameraView()","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller\/didhideenablecameraview()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewController":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontroller","abstract":[{"text":"An abstract base class for RTU-UI view controllers.","type":"text"}],"title":"SBSDKUIViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"didHideEnableCameraView","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"didHideEnableCameraView","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didHideEnableCameraView"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/title","value":"SBSDKUICameraViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUICameraViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController~1didHideEnableCameraView()\/title","value":"didHideEnableCameraView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController~1didHideEnableCameraView()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didHideEnableCameraView"}]},{"value":"SBSDKUIViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/fragments","value":[{"text":"SBSDKUIViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}