{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"A UI configuration, used for the enable-camera-view.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller\/enablecamerauiconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller\/enablecamerauiconfiguration"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController\/enableCameraUIConfiguration","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"enableCameraUIConfiguration","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraViewController(py)enableCameraUIConfiguration","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableCameraUIConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIEnableCameraUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraUIConfiguration"}],"navigatorTitle":[{"text":"enableCameraUIConfiguration","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableCameraUIConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraUIConfiguration"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraViewController/enableCameraUIConfiguration":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableCameraUIConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraUIConfiguration","text":"SBSDKUIEnableCameraUIConfiguration","kind":"typeIdentifier"}],"abstract":[{"text":"A UI configuration, used for the enable-camera-view.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController\/enableCameraUIConfiguration","kind":"symbol","title":"enableCameraUIConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller\/enablecamerauiconfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"enableCameraUIConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraUIConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraUIConfiguration","title":"SBSDKUIEnableCameraUIConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuienablecamerauiconfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIEnableCameraUIConfiguration"}],"abstract":[{"type":"text","text":"Configuration for the user interface of camera based view controllers."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIEnableCameraUIConfiguration"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","abstract":[{"type":"text","text":"An abstract base class for RTU-UI view controllers."}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontroller","title":"SBSDKUIViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraViewController":{"title":"SBSDKUICameraViewController","navigatorTitle":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICameraViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller","abstract":[{"text":"A ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController"},{"type":"text","text":" subclass which adds support for enabled and disabled camera permission."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"enableCameraUIConfiguration"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"enableCameraUIConfiguration"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraUIConfiguration"},{"kind":"text","text":" * "},{"text":"enableCameraUIConfiguration","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":"enableCameraUIConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController~1enableCameraUIConfiguration\/title"},{"value":[{"kind":"identifier","text":"enableCameraUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController~1enableCameraUIConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraUIConfiguration\/title","op":"replace","value":"SBSDKUIEnableCameraUIConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraUIConfiguration\/fragments","value":[{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/title","op":"replace","value":"SBSDKUIViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/fragments","value":[{"text":"SBSDKUIViewController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKUIViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/title","value":"SBSDKUICameraViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUICameraViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/navigatorTitle","value":[{"text":"SBSDKUICameraViewController","kind":"identifier"}]}]}]}