{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesExtensionFilter"]]},"abstract":[{"text":"Only EAN and UPC barcoded without extensions will be returned.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyWithoutExtensions"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesextensionfilter\/onlywithoutextensions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesextensionfilter\/onlywithoutextensions"]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyWithoutExtensions"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKUIBarcodesExtensionFilter@SBSDKUIBarcodesExtensionFilterOnlyWithoutExtensions","title":"SBSDKUIBarcodesExtensionFilter.onlyWithoutExtensions","navigatorTitle":[{"text":"SBSDKUIBarcodesExtensionFilterOnlyWithoutExtensions","kind":"identifier"}],"symbolKind":"case","role":"symbol","roleHeading":"Case"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesExtensionFilter\/onlyWithoutExtensions","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesExtensionFilter":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesExtensionFilter","abstract":[{"type":"text","text":"Filter for extended EAN and UPC barcodes."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilter"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilter"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesextensionfilter","type":"topic","title":"SBSDKUIBarcodesExtensionFilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesExtensionFilter/onlyWithoutExtensions":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesextensionfilter\/onlywithoutextensions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesExtensionFilter\/onlyWithoutExtensions","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilterOnlyWithoutExtensions"}],"abstract":[{"text":"Only EAN and UPC barcoded without extensions will be returned.","type":"text"}],"title":"SBSDKUIBarcodesExtensionFilter.onlyWithoutExtensions","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyWithoutExtensions"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKUIBarcodesExtensionFilterOnlyWithoutExtensions","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilterOnlyWithoutExtensions"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilterOnlyWithoutExtensions"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUIBarcodesExtensionFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesExtensionFilter\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesExtensionFilter\/fragments"},{"value":[{"text":"SBSDKUIBarcodesExtensionFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesExtensionFilter\/navigatorTitle"},{"value":"SBSDKUIBarcodesExtensionFilterOnlyWithoutExtensions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesExtensionFilter~1onlyWithoutExtensions\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilterOnlyWithoutExtensions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesExtensionFilter~1onlyWithoutExtensions\/fragments"}]}]}