{"abstract":[{"text":"GS1 message handling options.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatmicropdf417configuration\/gs1handling"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatmicropdf417configuration\/gs1handling"]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/gs1Handling","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gs1Handling"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1Handling","kind":"typeIdentifier","text":"SBSDKGS1Handling"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is PARSE"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatMicroPDF417Configuration"]]},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"gs1Handling"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1Handling","text":"SBSDKGS1Handling","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatMicroPDF417Configuration(py)gs1Handling","title":"gs1Handling","navigatorTitle":[{"text":"gs1Handling","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","symbolKind":"property"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling":{"navigatorTitle":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling","abstract":[{"type":"text","text":"GS1 message handling options."},{"text":" ","type":"text"},{"text":"The GS1 standard defines a key-value format for business-centric data that can be encoded into many 1D and 2D","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"barcode types."},{"type":"text","text":" "},{"type":"text","text":"https:\/\/ref.gs1.org\/standards\/genspecs\/"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGS1Handling"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling","kind":"symbol","title":"SBSDKGS1Handling"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatMicroPDF417Configuration/gs1Handling":{"abstract":[{"type":"text","text":"GS1 message handling options."}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatmicropdf417configuration\/gs1handling","type":"topic","title":"gs1Handling","navigatorTitle":[{"text":"gs1Handling","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"gs1Handling","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1Handling","text":"SBSDKGS1Handling"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/gs1Handling"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatMicroPDF417Configuration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatMicroPDF417Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatMicroPDF417Configuration","kind":"identifier"}],"title":"SBSDKBarcodeFormatMicroPDF417Configuration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatmicropdf417configuration","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeFormatMicroPDF417Configuration","kind":"identifier"}],"abstract":[{"text":"MicroPDF417 configuration. Add to scanner configuration to scan MicroPDF417 codes.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"gs1Handling"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"gs1Handling","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1Handling","kind":"typeIdentifier","text":"SBSDKGS1Handling"},{"kind":"text","text":" "},{"text":"gs1Handling","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/title","value":"SBSDKGS1Handling"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/fragments","value":[{"text":"SBSDKGS1Handling","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/navigatorTitle"},{"value":"gs1Handling","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatMicroPDF417Configuration~1gs1Handling\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatMicroPDF417Configuration~1gs1Handling\/fragments","value":[{"kind":"identifier","text":"gs1Handling"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatMicroPDF417Configuration\/title","op":"replace","value":"SBSDKBarcodeFormatMicroPDF417Configuration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatMicroPDF417Configuration\/fragments","value":[{"text":"SBSDKBarcodeFormatMicroPDF417Configuration","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKBarcodeFormatMicroPDF417Configuration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatMicroPDF417Configuration\/navigatorTitle"}]}]}