{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/horizontal"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKPolygonEdgeOrientation@SBSDKPolygonEdgeOrientationHorizontal","navigatorTitle":[{"text":"SBSDKPolygonEdgeOrientationHorizontal","kind":"identifier"}],"role":"symbol","title":"SBSDKPolygonEdgeOrientation.horizontal","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"horizontal","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation"]]},"abstract":[{"text":"The edge is oriented horizontally.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"horizontal","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation\/horizontal"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation\/horizontal"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygonEdgeOrientation/horizontal":{"kind":"symbol","type":"topic","abstract":[{"text":"The edge is oriented horizontally.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"horizontal","kind":"identifier"}],"title":"SBSDKPolygonEdgeOrientation.horizontal","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/horizontal","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation\/horizontal","navigatorTitle":[{"text":"SBSDKPolygonEdgeOrientationHorizontal","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygonEdgeOrientation":{"type":"topic","abstract":[{"type":"text","text":"An enum describing the orientation of a polygon edge."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}],"title":"SBSDKPolygonEdgeOrientation","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation","navigatorTitle":[{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 6.2.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKPolygonEdgeOrientationHorizontal"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKPolygonEdgeOrientationHorizontal","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"SBSDKPolygonEdgeOrientationHorizontal","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKPolygonEdgeOrientationHorizontal","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation~1horizontal\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation~1horizontal\/fragments","op":"replace","value":[{"text":"SBSDKPolygonEdgeOrientationHorizontal","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation\/title","value":"SBSDKPolygonEdgeOrientation","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPolygonEdgeOrientation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation\/fragments","op":"replace"},{"value":[{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation\/navigatorTitle"}]}]}