{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vertical"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/vertical"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation\/vertical"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation\/vertical"]}],"abstract":[{"text":"The edge is oriented vertically.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation"]]},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vertical"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKPolygonEdgeOrientationVertical","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"SBSDKPolygonEdgeOrientation.vertical","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKPolygonEdgeOrientation@SBSDKPolygonEdgeOrientationVertical","roleHeading":"Case","symbolKind":"case"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygonEdgeOrientation/vertical":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"vertical","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation\/vertical","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygonEdgeOrientationVertical"}],"title":"SBSDKPolygonEdgeOrientation.vertical","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/vertical","kind":"symbol","abstract":[{"type":"text","text":"The edge is oriented vertically."}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygonEdgeOrientation":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPolygonEdgeOrientation"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation","role":"symbol","navigatorTitle":[{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}],"title":"SBSDKPolygonEdgeOrientation","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation","abstract":[{"type":"text","text":"An enum describing the orientation of a polygon edge."}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 5.2.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKPolygonEdgeOrientationVertical","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKPolygonEdgeOrientationVertical"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKPolygonEdgeOrientationVertical"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation~1vertical\/title","value":"SBSDKPolygonEdgeOrientationVertical","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation~1vertical\/fragments","op":"replace","value":[{"text":"SBSDKPolygonEdgeOrientationVertical","kind":"identifier"}]},{"value":"SBSDKPolygonEdgeOrientation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation\/fragments","value":[{"kind":"identifier","text":"SBSDKPolygonEdgeOrientation"}]}]}]}