{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode"]]},"metadata":{"title":"SBSDKVideoFlipMode.horizontal","externalID":"c:@M@ScanbotSDK@E@SBSDKVideoFlipMode@SBSDKVideoFlipModeHorizontal","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"horizontal","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFlipModeHorizontal"}],"symbolKind":"case","roleHeading":"Case"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"horizontal"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Flip the image horizontally.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoflipmode\/horizontal"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoflipmode\/horizontal"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode\/horizontal"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFlipMode/horizontal":{"title":"SBSDKVideoFlipMode.horizontal","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode\/horizontal","url":"\/documentation\/scanbotsdk\/sbsdkvideoflipmode\/horizontal","role":"symbol","abstract":[{"type":"text","text":"Flip the image horizontally."}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"horizontal","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFlipModeHorizontal"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFlipMode":{"abstract":[{"text":"An enum describing how images can be flipped.","type":"text"}],"type":"topic","kind":"symbol","title":"SBSDKVideoFlipMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKVideoFlipMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKVideoFlipMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkvideoflipmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKVideoFlipModeHorizontal","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKVideoFlipModeHorizontal"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKVideoFlipModeHorizontal","kind":"identifier"}]}],"kind":"declarations"}},{"value":"SBSDKVideoFlipModeHorizontal","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode~1horizontal\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode~1horizontal\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFlipModeHorizontal"}]},{"op":"replace","value":"SBSDKVideoFlipMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode\/title"},{"value":[{"text":"SBSDKVideoFlipMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode\/navigatorTitle","value":[{"text":"SBSDKVideoFlipMode","kind":"identifier"}]}]}]}