{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vertical","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode\/vertical","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoflipmode\/vertical"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoflipmode\/vertical"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode"]]},"metadata":{"symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"SBSDKVideoFlipMode.vertical","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKVideoFlipMode@SBSDKVideoFlipModeVertical","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"vertical"}],"navigatorTitle":[{"text":"SBSDKVideoFlipModeVertical","kind":"identifier"}]},"abstract":[{"type":"text","text":"Flip the image vertically."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFlipMode/vertical":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvideoflipmode\/vertical","abstract":[{"type":"text","text":"Flip the image vertically."}],"role":"symbol","title":"SBSDKVideoFlipMode.vertical","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"vertical"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode\/vertical","navigatorTitle":[{"text":"SBSDKVideoFlipModeVertical","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFlipMode":{"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoFlipMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkvideoflipmode","title":"SBSDKVideoFlipMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFlipMode"}],"kind":"symbol","abstract":[{"text":"An enum describing how images can be flipped.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKVideoFlipModeVertical","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFlipModeVertical"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKVideoFlipModeVertical"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode~1vertical\/title","value":"SBSDKVideoFlipModeVertical","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode~1vertical\/fragments","op":"replace","value":[{"text":"SBSDKVideoFlipModeVertical","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode\/title","value":"SBSDKVideoFlipMode","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFlipMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode\/fragments"}]}]}