{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm\/rawValue","interfaceLanguage":"swift"},"abstract":[{"text":"The raw value integer of the current ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm","isActive":true,"type":"reference"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmsiplesseychecksumalgorithm\/rawvalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmsiplesseychecksumalgorithm\/rawvalue"]}],"metadata":{"navigatorTitle":[{"text":"rawValue","kind":"identifier"}],"title":"rawValue","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm(py)rawValue"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMSIPlesseyChecksumAlgorithm":{"abstract":[{"type":"text","text":"Checksum algorithm for MSI_PLESSEY."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMSIPlesseyChecksumAlgorithm"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMSIPlesseyChecksumAlgorithm"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmsiplesseychecksumalgorithm","title":"SBSDKMSIPlesseyChecksumAlgorithm"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMSIPlesseyChecksumAlgorithm/rawValue":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[{"text":"The raw value integer of the current ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm","isActive":true,"type":"reference"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkmsiplesseychecksumalgorithm\/rawvalue","title":"rawValue","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm\/rawValue","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rawValue"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"rawValue","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"rawValue","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/title","op":"replace","value":"SBSDKMSIPlesseyChecksumAlgorithm"},{"op":"replace","value":[{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/navigatorTitle","op":"replace","value":[{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}]},{"value":"rawValue","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm~1rawValue\/title"},{"value":[{"kind":"identifier","text":"rawValue"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm~1rawValue\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}