{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearFrameAccumulator"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This should be called after retrieving a result and initiating a new scan."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscanner\/clearframeaccumulator()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscanner\/clearframeaccumulator()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner\/clearFrameAccumulator()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Clears the frame accumulator of the scanner."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearFrameAccumulator"},{"kind":"text","text":"()"}],"title":"clearFrameAccumulator()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScanner(im)clearFrameAccumulator","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"clearFrameAccumulator"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScanner/clearFrameAccumulator()":{"role":"symbol","title":"clearFrameAccumulator()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearFrameAccumulator"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Clears the frame accumulator of the scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner\/clearFrameAccumulator()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearFrameAccumulator"}],"url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscanner\/clearframeaccumulator()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScanner":{"role":"symbol","title":"SBSDKVehicleIdentificationNumberScanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScanner"}],"abstract":[{"type":"text","text":"A class to scan video frames or still images for vehicle identification numbers and validate it."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScanner"}],"url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscanner"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"clearFrameAccumulator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearFrameAccumulator"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"clearFrameAccumulator"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner~1clearFrameAccumulator()\/title","value":"clearFrameAccumulator"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner~1clearFrameAccumulator()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearFrameAccumulator"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner\/title","value":"SBSDKVehicleIdentificationNumberScanner"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner\/fragments","value":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScanner"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}