{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner\/recognize(on:videoOrientation:in:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"recognize(on:videoOrientation:in:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"recognize","kind":"identifier"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier","text":"CMSampleBuffer"},{"text":", ","kind":"text"},{"text":"videoOrientation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerResult","text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScanner(im)recognizeOnSampleBuffer:orientation:inRect:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"recognizeOnSampleBuffer:orientation:inRect:","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(recognizeOnSampleBuffer:orientation:inRect:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":" "},{"text":"sampleBuffer","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"videoOrientation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"in","kind":"externalParam"},{"kind":"text","text":" "},{"text":"rect","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"SBSDKVehicleIdentificationNumberScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerResult"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"sampleBuffer","content":[{"inlineContent":[{"type":"text","text":"The sample buffer reference."}],"type":"paragraph"}]},{"name":"videoOrientation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The video frame orientation. Should be the orientation that the device currently has, not the actual image orientation."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The rectangle in image coordinates in which to search for vehicle identification numbers.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Must be inside the image."}]}],"name":"rect"}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"The result of the scan. Or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no vehicle identification number was found or an error occured."}],"type":"paragraph"}],"kind":"content"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Intended for usage with live detection.","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Scans the given image in the given area for vehicle identification number information."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscanner\/recognize(on:videoorientation:in:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscanner\/recognize(on:videoorientation:in:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScanner/recognize(on:videoOrientation:in:)":{"title":"recognize(on:videoOrientation:in:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner\/recognize(on:videoOrientation:in:)","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscanner\/recognize(on:videoorientation:in:)","kind":"symbol","abstract":[{"type":"text","text":"Scans the given image in the given area for vehicle identification number information."}],"navigatorTitle":[{"kind":"identifier","text":"recognizeOnSampleBuffer:orientation:inRect:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recognize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":", "},{"text":"videoOrientation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation"},{"kind":"text","text":", "},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKVehicleIdentificationNumberScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerResult"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScanner":{"title":"SBSDKVehicleIdentificationNumberScanner","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner","navigatorTitle":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScanner"}],"url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscanner","type":"topic","abstract":[{"type":"text","text":"A class to scan video frames or still images for vehicle identification numbers and validate it."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScanner"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerResult":{"title":"SBSDKVehicleIdentificationNumberScannerResult","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScannerResult"}],"url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerresult","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScannerResult"}],"abstract":[{"type":"text","text":"A class describing the result of the vehicle identification number scanner."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"recognizeOnSampleBuffer:orientation:inRect:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"recognizeOnSampleBuffer:orientation:inRect:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerResult","text":"SBSDKVehicleIdentificationNumberScannerResult"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"recognizeOnSampleBuffer:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"opaqueCMSampleBuffer","preciseIdentifier":"c:@S@opaqueCMSampleBuffer"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sampleBuffer"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientation:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@AVCaptureVideoOrientation","kind":"typeIdentifier","text":"AVCaptureVideoOrientation"},{"text":") ","kind":"text"},{"text":"videoOrientation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"inRect:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":") "},{"text":"rect","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"recognizeOnSampleBuffer:orientation:inRect:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner~1recognize(on:videoOrientation:in:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner~1recognize(on:videoOrientation:in:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"recognizeOnSampleBuffer:orientation:inRect:","kind":"identifier"}]},{"value":"SBSDKVehicleIdentificationNumberScanner","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner\/title"},{"op":"replace","value":[{"text":"SBSDKVehicleIdentificationNumberScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult\/title","value":"SBSDKVehicleIdentificationNumberScannerResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult\/fragments","value":[{"text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"identifier"}],"op":"replace"}]}]}