{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSharingActivity\/shareFiles(at:presenter:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(shareFilesAtURLs:presenter:) ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shareFiles","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"urls","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"presenter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"urls","content":[{"inlineContent":[{"type":"text","text":"An array of file URLs to share."}],"type":"paragraph"}]},{"name":"presenter","content":[{"inlineContent":[{"text":"The view controller that will present the ","type":"text"},{"code":"UIActivityController","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdksharingactivity\/sharefiles(at:presenter:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdksharingactivity\/sharefiles(at:presenter:)"]}],"abstract":[{"type":"text","text":"Shares the files at the specified file URLs using the "},{"code":"UIActivityController","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shareFiles","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"], ","kind":"text"},{"text":"presenter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":")","kind":"text"}],"title":"shareFiles(at:presenter:)","navigatorTitle":[{"kind":"identifier","text":"shareFilesAtURLs:presenter:"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSharingActivity(cm)shareFilesAtURLs:presenter:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSharingActivity"]]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSharingActivity":{"url":"\/documentation\/scanbotsdk\/sbsdksharingactivity","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSharingActivity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSharingActivity"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSharingActivity"}],"role":"symbol","kind":"symbol","title":"SBSDKSharingActivity","abstract":[{"type":"text","text":"Shares files at the specified URLs using the "},{"type":"codeVoice","code":"UIActivityController"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Mainly for debugging and testing purposes."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSharingActivity/shareFiles(at:presenter:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shareFiles"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"presenter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"shareFilesAtURLs:presenter:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdksharingactivity\/sharefiles(at:presenter:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSharingActivity\/shareFiles(at:presenter:)","abstract":[{"type":"text","text":"Shares the files at the specified file URLs using the "},{"type":"codeVoice","code":"UIActivityController"},{"type":"text","text":"."}],"title":"shareFiles(at:presenter:)","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"shareFilesAtURLs:presenter:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"shareFilesAtURLs:presenter:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"shareFilesAtURLs:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSURL *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"urls","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"presenter:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"presenter","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of file URLs to share."}]}],"name":"urls"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller that will present the "},{"type":"codeVoice","code":"UIActivityController"},{"type":"text","text":"."}]}],"name":"presenter"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SBSDKSharingActivity","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSharingActivity\/title"},{"value":[{"kind":"identifier","text":"SBSDKSharingActivity"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSharingActivity\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKSharingActivity"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSharingActivity\/navigatorTitle"},{"value":"shareFilesAtURLs:presenter:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSharingActivity~1shareFiles(at:presenter:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"shareFilesAtURLs:presenter:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSharingActivity~1shareFiles(at:presenter:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}