{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerviewcontrollerdelegate\/healthinsurancecarddetectionviewcontrollerdidcancel(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerviewcontrollerdelegate\/healthinsurancecarddetectionviewcontrollerdidcancel(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Please consider using SBSDKUIGenericDocumentRecognizerViewController."}],"type":"paragraph"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewControllerDelegate"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewControllerDelegate\/healthInsuranceCardDetectionViewControllerDidCancel(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Informs the delegate that the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController","type":"reference","isActive":true},{"text":" has been canceled and dismissed. Optional.","type":"text"}],"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"healthInsuranceCardDetectionViewControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIHealthInsuranceCardScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardScannerViewController"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"healthInsuranceCardDetectionViewControllerDidCancel:","kind":"identifier"}],"required":true,"title":"healthInsuranceCardDetectionViewControllerDidCancel(_:)","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIHealthInsuranceCardScannerViewControllerDelegate(im)healthInsuranceCardDetectionViewControllerDidCancel:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","platforms":[]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"healthInsuranceCardDetectionViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController","text":"SBSDKUIHealthInsuranceCardScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardScannerViewController"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController"},{"text":" that did dismiss.","type":"text"}],"type":"paragraph"}],"name":"viewController"}],"kind":"parameters"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerViewControllerDelegate":{"title":"SBSDKUIHealthInsuranceCardScannerViewControllerDelegate","deprecated":true,"abstract":[{"text":"Delegate protocol for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController","type":"reference"},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerviewcontrollerdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKUIHealthInsuranceCardScannerViewControllerDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerViewControllerDelegate"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewControllerDelegate","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerViewController":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerviewcontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController","abstract":[{"type":"text","text":"A view controller for camera-based detection of health insurance cards."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerViewController"}],"title":"SBSDKUIHealthInsuranceCardScannerViewController","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerViewControllerDelegate/healthInsuranceCardDetectionViewControllerDidCancel(_:)":{"abstract":[{"type":"text","text":"Informs the delegate that the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController","isActive":true,"type":"reference"},{"type":"text","text":" has been canceled and dismissed. Optional."}],"role":"symbol","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"healthInsuranceCardDetectionViewControllerDidCancel:"}],"title":"healthInsuranceCardDetectionViewControllerDidCancel(_:)","deprecated":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"healthInsuranceCardDetectionViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardScannerViewController","text":"SBSDKUIHealthInsuranceCardScannerViewController"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewControllerDelegate\/healthInsuranceCardDetectionViewControllerDidCancel(_:)","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerviewcontrollerdelegate\/healthinsurancecarddetectionviewcontrollerdidcancel(_:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"healthInsuranceCardDetectionViewControllerDidCancel:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"healthInsuranceCardDetectionViewControllerDidCancel:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"healthInsuranceCardDetectionViewControllerDidCancel:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardScannerViewController","text":"SBSDKUIHealthInsuranceCardScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController","isActive":true},{"type":"text","text":" that did dismiss."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SBSDKUIHealthInsuranceCardScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewControllerDelegate\/title"},{"value":[{"text":"SBSDKUIHealthInsuranceCardScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewControllerDelegate\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewControllerDelegate\/navigatorTitle"},{"value":"SBSDKUIHealthInsuranceCardScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewController\/title"},{"value":[{"text":"SBSDKUIHealthInsuranceCardScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewController\/navigatorTitle"},{"value":"healthInsuranceCardDetectionViewControllerDidCancel:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewControllerDelegate~1healthInsuranceCardDetectionViewControllerDidCancel(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"healthInsuranceCardDetectionViewControllerDidCancel:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewControllerDelegate~1healthInsuranceCardDetectionViewControllerDidCancel(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}