{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeinfomapping\/barcodeitemmapper"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeinfomapping\/barcodeitemmapper"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping\/barcodeItemMapper","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeItemMapper","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeItemMapper","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemMapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUI2BarcodeItemMapper"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeItemMapper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUI2BarcodeItemMapper","text":"SBSDKUI2BarcodeItemMapper"},{"kind":"text","text":"?"}],"title":"barcodeItemMapper","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"barcodeItemMapper"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping(py)barcodeItemMapper","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"type":"text","text":"Callback to map the barcode data to the data of the corresponding product."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeInfoMapping":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeinfomapping","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeInfoMapping","kind":"identifier"}],"title":"SBSDKUI2BarcodeInfoMapping","navigatorTitle":[{"text":"SBSDKUI2BarcodeInfoMapping","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the barcode data mapping."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeInfoMapping/barcodeItemMapper":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeinfomapping\/barcodeitemmapper","navigatorTitle":[{"text":"barcodeItemMapper","kind":"identifier"}],"type":"topic","title":"barcodeItemMapper","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeItemMapper","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeItemMapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUI2BarcodeItemMapper"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping\/barcodeItemMapper","abstract":[{"text":"Callback to map the barcode data to the data of the corresponding product.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemMapper":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeItemMapper"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitemmapper","role":"symbol","abstract":[{"text":"Barcode item mapper.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemMapper"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemMapper","title":"SBSDKUI2BarcodeItemMapper"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"barcodeItemMapper","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"barcodeItemMapper","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<SBSDKUI2BarcodeItemMapper>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKUI2BarcodeItemMapper"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeItemMapper"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/title","value":"SBSDKUI2BarcodeInfoMapping","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeInfoMapping","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/navigatorTitle"},{"op":"replace","value":"barcodeItemMapper","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping~1barcodeItemMapper\/title"},{"op":"replace","value":[{"text":"barcodeItemMapper","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping~1barcodeItemMapper\/fragments"},{"op":"replace","value":"SBSDKUI2BarcodeItemMapper","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemMapper\/title"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeItemMapper","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemMapper\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeItemMapper","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemMapper\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}