{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerConfiguration\/behaviorConfiguration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerConfiguration"]]},"kind":"symbol","abstract":[{"type":"text","text":"The configuration for behavior."}],"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2TextPatternScannerViewController instead.","type":"text"}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerconfiguration\/behaviorconfiguration"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerconfiguration\/behaviorconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"behaviorConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerBehaviorConfiguration","text":"SBSDKUITextPatternScannerBehaviorConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextPatternScannerBehaviorConfiguration"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"behaviorConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUITextPatternScannerBehaviorConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextPatternScannerBehaviorConfiguration"}],"platforms":[],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextPatternScannerConfiguration(py)behaviorConfiguration","navigatorTitle":[{"kind":"identifier","text":"behaviorConfiguration"}],"symbolKind":"property","role":"symbol","title":"behaviorConfiguration","roleHeading":"Instance Property"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerConfiguration/behaviorConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"behaviorConfiguration"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerconfiguration\/behaviorconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"behaviorConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUITextPatternScannerBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextPatternScannerBehaviorConfiguration"}],"deprecated":true,"abstract":[{"text":"The configuration for behavior.","type":"text"}],"title":"behaviorConfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerConfiguration\/behaviorConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerConfiguration":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKUITextPatternScannerConfiguration","kind":"identifier"}],"title":"SBSDKUITextPatternScannerConfiguration","abstract":[{"type":"text","text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI text pattern scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextPatternScannerConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerConfiguration","deprecated":true,"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerBehaviorConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextPatternScannerBehaviorConfiguration"}],"type":"topic","abstract":[{"type":"text","text":"Configuration for the behavior of RTU-UI text pattern scanner."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextPatternScannerBehaviorConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerBehaviorConfiguration","deprecated":true,"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerbehaviorconfiguration","title":"SBSDKUITextPatternScannerBehaviorConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"behaviorConfiguration"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"behaviorConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUITextPatternScannerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextPatternScannerBehaviorConfiguration"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"behaviorConfiguration"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerConfiguration~1behaviorConfiguration\/title","value":"behaviorConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerConfiguration~1behaviorConfiguration\/fragments","value":[{"text":"behaviorConfiguration","kind":"identifier"}]},{"value":"SBSDKUITextPatternScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerConfiguration\/title"},{"value":[{"text":"SBSDKUITextPatternScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerConfiguration\/navigatorTitle","value":[{"text":"SBSDKUITextPatternScannerConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerBehaviorConfiguration\/title","op":"replace","value":"SBSDKUITextPatternScannerBehaviorConfiguration"},{"value":[{"text":"SBSDKUITextPatternScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerBehaviorConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUITextPatternScannerBehaviorConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerBehaviorConfiguration\/navigatorTitle"}]}]}