{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}]}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation"}],"symbolKind":"property","title":"cameraPermissionEnableCameraExplanation","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization(py)cameraPermissionEnableCameraExplanation","role":"symbol","roleHeading":"Instance Property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization\/camerapermissionenablecameraexplanation"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization\/camerapermissionenablecameraexplanation"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization\/cameraPermissionEnableCameraExplanation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The explanation text of the camera permission dialog."},{"type":"text","text":" "},{"type":"text","text":"Default is “Please allow the usage of the camera to start the scanning process.”"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerTextLocalization/cameraPermissionEnableCameraExplanation":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation"}],"abstract":[{"type":"text","text":"The explanation text of the camera permission dialog."},{"text":" ","type":"text"},{"type":"text","text":"Default is “Please allow the usage of the camera to start the scanning process.”"}],"type":"topic","title":"cameraPermissionEnableCameraExplanation","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization\/camerapermissionenablecameraexplanation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization\/cameraPermissionEnableCameraExplanation","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerTextLocalization":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization","title":"SBSDKUI2DocumentScannerTextLocalization","abstract":[{"type":"text","text":"Configuration of all the strings for the standalone cropping screen."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"cameraPermissionEnableCameraExplanation"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization~1cameraPermissionEnableCameraExplanation\/title","op":"replace","value":"cameraPermissionEnableCameraExplanation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization~1cameraPermissionEnableCameraExplanation\/fragments","value":[{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/title","value":"SBSDKUI2DocumentScannerTextLocalization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"op":"replace"}]}]}