{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization\/cameraintroitem3"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization\/cameraintroitem3"]}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"cameraIntroItem3"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization(py)cameraIntroItem3","title":"cameraIntroItem3","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraIntroItem3"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization\/cameraIntroItem3","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization"]]},"abstract":[{"text":"The third scanning step text of the introduction screen.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cameraIntroItem3","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"text":"Default is “3. Follow the on-screen guidance to find the optimal position.”","type":"text"}],"type":"paragraph"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerTextLocalization/cameraIntroItem3":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cameraIntroItem3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization\/cameraIntroItem3","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraIntroItem3"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","abstract":[{"text":"The third scanning step text of the introduction screen.","type":"text"}],"title":"cameraIntroItem3","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization\/cameraintroitem3"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerTextLocalization":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"role":"symbol","abstract":[{"text":"Configuration of all the strings for the standalone cropping screen.","type":"text"}],"title":"SBSDKUI2DocumentScannerTextLocalization","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"cameraIntroItem3","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cameraIntroItem3"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cameraIntroItem3"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization~1cameraIntroItem3\/title","value":"cameraIntroItem3"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization~1cameraIntroItem3\/fragments","value":[{"text":"cameraIntroItem3","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2DocumentScannerTextLocalization","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/navigatorTitle"}]}]}