{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"background","kind":"identifier"},{"text":"<","kind":"text"},{"text":"S","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"style","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"S","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ignoresSafeAreaEdges","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"edges","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4EdgeO","text":"Edge","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4EdgeO3SetV","text":"Set","kind":"typeIdentifier"},{"text":" = .all) -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"S","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI10ShapeStyleP","text":"ShapeStyle","kind":"typeIdentifier"},{"text":"\n","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannerview\/background(_:ignoressafeareaedges:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView\/background(_:ignoresSafeAreaEdges:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView\/View-Implementations"]]},"metadata":{"title":"background(_:ignoresSafeAreaEdges:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"S"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"S"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ignoresSafeAreaEdges"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI4EdgeO","kind":"typeIdentifier","text":"Edge"},{"kind":"text","text":"."},{"preciseIdentifier":"s:7SwiftUI4EdgeO3SetV","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier","text":"View"}],"platforms":[{"unavailable":false,"introducedAt":"15.0","deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"introducedAt":"15.0","deprecated":false,"beta":false,"name":"iPadOS"},{"unavailable":false,"introducedAt":"15.0","deprecated":false,"beta":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"12.0","deprecated":false,"beta":false,"name":"macOS"},{"unavailable":false,"introducedAt":"15.0","deprecated":false,"beta":false,"name":"tvOS"},{"unavailable":false,"introducedAt":"8.0","deprecated":false,"beta":false,"name":"watchOS"}],"extendedModule":"SwiftUICore","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}],"symbolKind":"method","externalID":"s:7SwiftUI4ViewPAAE10background_20ignoresSafeAreaEdgesQrqd___AA4EdgeO3SetVtAA10ShapeStyleRd__lF::SYNTHESIZED::s:10ScanbotSDK27SBSDKUI2DocumentScannerViewV","role":"symbol"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"View.background(_:ignoresSafeAreaEdges:)","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerController":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannercontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerController","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerController"}],"abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI controller to scan documents."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerController"}],"title":"SBSDKUI2DocumentScannerController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerView":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerView","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView","abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerController","type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2DocumentScannerView","kind":"identifier"}],"title":"SBSDKUI2DocumentScannerView","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannerview"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerView/background(_:ignoresSafeAreaEdges:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannerview\/background(_:ignoressafeareaedges:)","title":"background(_:ignoresSafeAreaEdges:)","role":"symbol","kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"background","kind":"identifier"},{"text":"<","kind":"text"},{"text":"S","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"S","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ignoresSafeAreaEdges","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Edge","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4EdgeO"},{"text":".","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4EdgeO3SetV"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView\/background(_:ignoresSafeAreaEdges:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerView/View-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannerview\/view-implementations","title":"View Implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView\/View-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerController\/title","value":"SBSDKUI2DocumentScannerController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerController\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerController"}],"op":"replace"}]}]}