{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerView\/accessibilityLinkedGroup(id:in:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.accessibilityLinkedGroup(id:in:)"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerView","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerView\/View-Implementations"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"accessibilityLinkedGroup","kind":"identifier"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"ID"},{"text":">(","kind":"text"},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"text":"ID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"namespace","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI9NamespaceV","text":"Namespace","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:7SwiftUI9NamespaceV2IDV","kind":"typeIdentifier","text":"ID"},{"kind":"text","text":") -> "},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ID","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SH","text":"Hashable","kind":"typeIdentifier"},{"kind":"text","text":"\n"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"accessibilityLinkedGroup","kind":"identifier"},{"kind":"text","text":"<"},{"text":"ID","kind":"genericParameter"},{"kind":"text","text":">("},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ID","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"text":"Namespace","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI9NamespaceV"},{"kind":"text","text":"."},{"text":"ID","preciseIdentifier":"s:7SwiftUI9NamespaceV2IDV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotBarcodeScannerSDK"}],"title":"accessibilityLinkedGroup(id:in:)","extendedModule":"SwiftUICore","platforms":[{"deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false,"name":"iOS"},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0"},{"unavailable":false,"name":"macOS","introducedAt":"11.0","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"14.0","deprecated":false,"beta":false,"name":"tvOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"watchOS","introducedAt":"7.0"}],"externalID":"s:7SwiftUI4ViewPAAE24accessibilityLinkedGroup2id2inQrqd___AA9NamespaceV2IDVtSHRd__lF::SYNTHESIZED::s:24ScanbotBarcodeScannerSDK08SBSDKUI2bC4ViewV"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerview\/accessibilitylinkedgroup(id:in:)"]}],"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeScannerView/accessibilityLinkedGroup(id:in:)":{"title":"accessibilityLinkedGroup(id:in:)","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityLinkedGroup"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"ID"},{"kind":"text","text":">("},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI9NamespaceV","text":"Namespace","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:7SwiftUI9NamespaceV2IDV","text":"ID","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerView\/accessibilityLinkedGroup(id:in:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerview\/accessibilitylinkedgroup(id:in:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeScannerViewController":{"abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to detect QR and barcodes.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerViewController"}],"kind":"symbol","title":"SBSDKUI2BarcodeScannerViewController","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerviewcontroller","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeScannerViewController"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeScannerView":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeScannerView"}],"kind":"symbol","abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerViewController","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerView","navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerView","kind":"identifier"}],"type":"topic","title":"SBSDKUI2BarcodeScannerView","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerview","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeScannerView/View-Implementations":{"kind":"article","abstract":[],"type":"topic","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerView\/View-Implementations","title":"View Implementations","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerview\/view-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerViewController\/title","op":"replace","value":"SBSDKUI2BarcodeScannerViewController"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUI2BarcodeScannerViewController","kind":"identifier"}]}]}]}