{"metadata":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"healthInsuranceCardRecognizerViewController","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognizerViewController","text":"SBSDKHealthInsuranceCardRecognizerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didScanHealthInsuranceCard"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognitionResult","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"healthInsuranceCardRecognizerViewController:didScanHealthInsuranceCard:"}],"platforms":[],"title":"healthInsuranceCardRecognizerViewController(_:didScanHealthInsuranceCard:)","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKHealthInsuranceCardRecognizerViewControllerDelegate(im)healthInsuranceCardRecognizerViewController:didScanHealthInsuranceCard:"},"abstract":[{"type":"text","text":"Informs the delegate that a health insurance card has been scanned."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewControllerDelegate\/healthInsuranceCardRecognizerViewController(_:didScanHealthInsuranceCard:)","interfaceLanguage":"swift"},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Please consider using SBSDKDocumentDataExtractorViewController."}],"type":"paragraph"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerviewcontrollerdelegate\/healthinsurancecardrecognizerviewcontroller(_:didscanhealthinsurancecard:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerviewcontrollerdelegate\/healthinsurancecardrecognizerviewcontroller(_:didscanhealthinsurancecard:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewControllerDelegate"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"healthInsuranceCardRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognizerViewController","text":"SBSDKHealthInsuranceCardRecognizerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didScanHealthInsuranceCard","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"card","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"typeIdentifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResult"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController"},{"text":" instance that scanned the health insurance card.","type":"text"}]}],"name":"viewController"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the scan."}]}],"name":"card"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerViewController":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController","type":"topic","title":"SBSDKHealthInsuranceCardRecognizerViewController","abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to scan health insurance cards with the camera."}],"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardRecognizerViewController","kind":"identifier"}],"deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerViewControllerDelegate/healthInsuranceCardRecognizerViewController(_:didScanHealthInsuranceCard:)":{"kind":"symbol","required":true,"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerviewcontrollerdelegate\/healthinsurancecardrecognizerviewcontroller(_:didscanhealthinsurancecard:)","navigatorTitle":[{"text":"healthInsuranceCardRecognizerViewController:didScanHealthInsuranceCard:","kind":"identifier"}],"title":"healthInsuranceCardRecognizerViewController(_:didScanHealthInsuranceCard:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"healthInsuranceCardRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognizerViewController","text":"SBSDKHealthInsuranceCardRecognizerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didScanHealthInsuranceCard"},{"text":": ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognitionResult"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewControllerDelegate\/healthInsuranceCardRecognizerViewController(_:didScanHealthInsuranceCard:)","deprecated":true,"abstract":[{"type":"text","text":"Informs the delegate that a health insurance card has been scanned."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResult":{"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresult","kind":"symbol","type":"topic","title":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","abstract":[{"type":"text","text":"The result of the health insurance card recognition."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResult","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerViewControllerDelegate":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerviewcontrollerdelegate","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","kind":"identifier"}],"title":"SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","deprecated":true,"abstract":[{"type":"text","text":"The delegation protocol for the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController"},{"text":" class.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"healthInsuranceCardRecognizerViewController:didScanHealthInsuranceCard:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"healthInsuranceCardRecognizerViewController:didScanHealthInsuranceCard:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"healthInsuranceCardRecognizerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognizerViewController","text":"SBSDKHealthInsuranceCardRecognizerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"text":"didScanHealthInsuranceCard:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"typeIdentifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResult"},{"kind":"text","text":" *) "},{"text":"card","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"viewController","content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController","isActive":true},{"text":" instance that scanned the health insurance card.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the scan."}]}],"name":"card"}]}},{"op":"replace","value":"SBSDKHealthInsuranceCardRecognizerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewController\/fragments","value":[{"text":"SBSDKHealthInsuranceCardRecognizerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerViewController"}],"op":"replace"},{"value":"healthInsuranceCardRecognizerViewController:didScanHealthInsuranceCard:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewControllerDelegate~1healthInsuranceCardRecognizerViewController(_:didScanHealthInsuranceCard:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewControllerDelegate~1healthInsuranceCardRecognizerViewController(_:didScanHealthInsuranceCard:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"healthInsuranceCardRecognizerViewController:didScanHealthInsuranceCard:","kind":"identifier"}]},{"value":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResult\/title"},{"op":"replace","value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResult\/fragments"},{"op":"replace","value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResult\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewControllerDelegate\/title","value":"SBSDKHealthInsuranceCardRecognizerViewControllerDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerViewControllerDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerViewControllerDelegate"}]}]}]}