{"kind":"symbol","metadata":{"navigatorTitle":[{"text":"setConfigurationWithConfiguration:error:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScanner(im)setConfigurationWithConfiguration:error:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCreditCardScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerConfiguration","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","title":"setConfiguration(configuration:)","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCreditCardScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerConfiguration"},{"text":" = SBSDKCreditCardScannerConfiguration(  )) ","kind":"text"},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"inlineContent":[{"type":"text","text":"The configuration to use for the scanner."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"name":"Throws","type":"aside","content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKError","isActive":true,"type":"reference"},{"text":" in case of an error.","type":"text"}],"type":"paragraph"}],"style":"note"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanner\/setConfiguration(configuration:)"},"sections":[],"abstract":[{"type":"text","text":"Inplace reconfigures the API instance with new settings."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanner\/setconfiguration(configuration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanner\/setconfiguration(configuration:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanner"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKError":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKError"}],"title":"SBSDKError","url":"\/documentation\/scanbotsdk\/sbsdkerror","abstract":[{"type":"text","text":"Represents errors that can occur within the Scanbot SDK."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKError","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKError"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanner":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanner","abstract":[{"text":"API for credit card scanning.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanner","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCreditCardScanner"}],"type":"topic","title":"SBSDKCreditCardScanner","navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardScanner"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerConfiguration":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration","abstract":[{"type":"text","text":"Configuration for the credit card scanner."}],"navigatorTitle":[{"text":"SBSDKCreditCardScannerConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardScannerConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerconfiguration","title":"SBSDKCreditCardScannerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanner/setConfiguration(configuration:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanner\/setConfiguration(configuration:)","abstract":[{"type":"text","text":"Inplace reconfigures the API instance with new settings."}],"title":"setConfiguration(configuration:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConfiguration"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerConfiguration","text":"SBSDKCreditCardScannerConfiguration"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"setConfigurationWithConfiguration:error:"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanner\/setconfiguration(configuration:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setConfigurationWithConfiguration:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setConfigurationWithConfiguration:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"setConfigurationWithConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKCreditCardScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The configuration to use for the scanner.","type":"text"}]}],"name":"configuration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}]}],"name":"error"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"code":"YES","type":"codeVoice"},{"type":"text","text":" if the method succeeded, otherwise "},{"code":"NO","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"},"op":"add","path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner\/title","value":"SBSDKCreditCardScanner"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner\/fragments","value":[{"kind":"identifier","text":"SBSDKCreditCardScanner"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner\/navigatorTitle","value":[{"text":"SBSDKCreditCardScanner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/title","value":"SBSDKCreditCardScannerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/navigatorTitle","value":[{"text":"SBSDKCreditCardScannerConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner~1setConfiguration(configuration:)\/title","value":"setConfigurationWithConfiguration:error:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner~1setConfiguration(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setConfigurationWithConfiguration:error:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}