{"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeAdditionalParameters(py)minimumTextLength","symbolKind":"property","title":"minimumTextLength","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"minimumTextLength","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"navigatorTitle":[{"text":"minimumTextLength","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodeadditionalparameters\/minimumtextlength"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodeadditionalparameters\/minimumtextlength"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"minimumTextLength","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Defaults to 0.","type":"text"}]},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Currently works for ITF and MSI Plessey barcodes only!","type":"text"}]}],"style":"note","name":"Note"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeAdditionalParameters"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeAdditionalParameters\/minimumTextLength","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Minimum required text length of the scanned barcode."}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeAdditionalParameters/minimumTextLength":{"title":"minimumTextLength","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeAdditionalParameters\/minimumTextLength","navigatorTitle":[{"kind":"identifier","text":"minimumTextLength"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeadditionalparameters\/minimumtextlength","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"minimumTextLength","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Minimum required text length of the scanned barcode."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeAdditionalParameters":{"navigatorTitle":[{"text":"SBSDKUIBarcodeAdditionalParameters","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodeAdditionalParameters"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeAdditionalParameters","title":"SBSDKUIBarcodeAdditionalParameters","abstract":[{"text":"A class that contains additional parameters for barcodes scanning and filtering.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeadditionalparameters","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"minimumTextLength","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"minimumTextLength"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"text":"minimumTextLength","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"minimumTextLength","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeAdditionalParameters~1minimumTextLength\/title"},{"value":[{"text":"minimumTextLength","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeAdditionalParameters~1minimumTextLength\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeAdditionalParameters\/title","value":"SBSDKUIBarcodeAdditionalParameters"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeAdditionalParameters\/fragments","op":"replace","value":[{"text":"SBSDKUIBarcodeAdditionalParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeAdditionalParameters\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIBarcodeAdditionalParameters"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}