{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2SoundType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2SoundType\/modernBeep"},"abstract":[{"type":"text","text":"A modern beep sound."}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2soundtype\/modernbeep"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2soundtype\/modernbeep"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modernBeep","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2SoundType@SBSDKUI2SoundTypeModernBeep","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modernBeep"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SoundTypeModernBeep"}],"title":"SBSDKUI2SoundType.modernBeep","role":"symbol"},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2SoundType":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2soundtype","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2SoundType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SoundType"}],"abstract":[{"type":"text","text":"Determines the successful detection sound."}],"title":"SBSDKUI2SoundType","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2SoundType"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2SoundType/modernBeep":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2soundtype\/modernbeep","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modernBeep"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2SoundType\/modernBeep","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2SoundTypeModernBeep","kind":"identifier"}],"type":"topic","title":"SBSDKUI2SoundType.modernBeep","abstract":[{"text":"A modern beep sound.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKUI2SoundTypeModernBeep","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKUI2SoundTypeModernBeep","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKUI2SoundTypeModernBeep","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKUI2SoundType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2SoundType\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2SoundType\/fragments","value":[{"text":"SBSDKUI2SoundType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2SoundType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2SoundType"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2SoundType~1modernBeep\/title","value":"SBSDKUI2SoundTypeModernBeep","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2SoundTypeModernBeep","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2SoundType~1modernBeep\/fragments"}]}]}