{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceScanningProgress","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentuserguidancescanningprogress"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentuserguidancescanningprogress"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The user guidance text displayed when a document presence was detected.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentUserGuidanceScanningProgress","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is “Scanning the document…”"}]}],"kind":"content"}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentUserGuidanceScanningProgress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"documentUserGuidanceScanningProgress","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorScreenTextLocalization(py)documentUserGuidanceScanningProgress","navigatorTitle":[{"text":"documentUserGuidanceScanningProgress","kind":"identifier"}],"symbolKind":"property","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentUserGuidanceScanningProgress":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentuserguidancescanningprogress","navigatorTitle":[{"text":"documentUserGuidanceScanningProgress","kind":"identifier"}],"abstract":[{"type":"text","text":"The user guidance text displayed when a document presence was detected."}],"title":"documentUserGuidanceScanningProgress","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceScanningProgress","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentUserGuidanceScanningProgress","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization":{"title":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization","type":"topic","abstract":[{"text":"Configuration of the all strings for document data extractor screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"documentUserGuidanceScanningProgress","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"documentUserGuidanceScanningProgress","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"documentUserGuidanceScanningProgress","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentUserGuidanceScanningProgress\/title","value":"documentUserGuidanceScanningProgress","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentUserGuidanceScanningProgress\/fragments","value":[{"kind":"identifier","text":"documentUserGuidanceScanningProgress"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/title","value":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"}],"op":"replace"}]}]}