{"metadata":{"role":"symbol","title":"medicalCertificateScannerViewController(_:didScanMedicalCertificate:)","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"medicalCertificateScannerViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController","text":"SBSDKMedicalCertificateScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanMedicalCertificate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult","text":"SBSDKMedicalCertificateScanningResult"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"medicalCertificateScannerViewController:didScanMedicalCertificate:"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerViewController(im)medicalCertificateScannerViewController:didScanMedicalCertificate:","extendedModule":"ScanbotSDK"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/medicalcertificatescannerviewcontroller(_:didscanmedicalcertificate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/medicalcertificatescannerviewcontroller(_:didscanmedicalcertificate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/medicalCertificateScannerViewController(_:didScanMedicalCertificate:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/SBSDKMedicalCertificateScannerViewControllerDelegate-Implementations"]]},"abstract":[{"type":"text","text":"Informs the delegate, that the medical certificate scanner has successfully detected and scanned a medical certificate."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"medicalCertificateScannerViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKMedicalCertificateScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanMedicalCertificate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKMedicalCertificateScanningResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"controller","content":[{"inlineContent":[{"text":"The medical certificate scanner view controller which scanned the medical certificate.","type":"text"}],"type":"paragraph"}]},{"name":"result","content":[{"inlineContent":[{"type":"text","text":"The medical certificate scanner result that have been scanned."}],"type":"paragraph"}]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/SBSDKMedicalCertificateScannerViewControllerDelegate-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/SBSDKMedicalCertificateScannerViewControllerDelegate-Implementations","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/sbsdkmedicalcertificatescannerviewcontrollerdelegate-implementations","title":"SBSDKMedicalCertificateScannerViewControllerDelegate Implementations","role":"collectionGroup"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanningResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateScanningResult"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult","abstract":[{"type":"text","text":"The result of the medical certificate scanning."}],"title":"SBSDKMedicalCertificateScanningResult","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateScanningResult"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController":{"role":"symbol","abstract":[{"text":"A Ready-To-Use viewController to scan medical certificates.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller","title":"SBSDKUIMedicalCertificateScannerViewController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/medicalCertificateScannerViewController(_:didScanMedicalCertificate:)":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/medicalcertificatescannerviewcontroller(_:didscanmedicalcertificate:)","abstract":[{"type":"text","text":"Informs the delegate, that the medical certificate scanner has successfully detected and scanned a medical certificate."}],"kind":"symbol","title":"medicalCertificateScannerViewController(_:didScanMedicalCertificate:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"medicalCertificateScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMedicalCertificateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didScanMedicalCertificate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKMedicalCertificateScanningResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/medicalCertificateScannerViewController(_:didScanMedicalCertificate:)","navigatorTitle":[{"text":"medicalCertificateScannerViewController:didScanMedicalCertificate:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController":{"abstract":[{"type":"text","text":"The classic UI view controller that can be used to detect and scan medical certificates. Can be configured to scan on video frames or,"},{"type":"text","text":" "},{"type":"text","text":"for better accuracy, on high-res photos that are automatically captured."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}],"title":"SBSDKMedicalCertificateScannerViewController","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"medicalCertificateScannerViewController:didScanMedicalCertificate:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"medicalCertificateScannerViewController:didScanMedicalCertificate:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"medicalCertificateScannerViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKMedicalCertificateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"didScanMedicalCertificate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKMedicalCertificateScanningResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"result"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKMedicalCertificateScanningResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScanningResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScanningResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/title","value":"SBSDKUIMedicalCertificateScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/fragments","value":[{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1medicalCertificateScannerViewController(_:didScanMedicalCertificate:)\/title","value":"medicalCertificateScannerViewController:didScanMedicalCertificate:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1medicalCertificateScannerViewController(_:didScanMedicalCertificate:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"medicalCertificateScannerViewController:didScanMedicalCertificate:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/title","value":"SBSDKMedicalCertificateScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/fragments","value":[{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}