{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcameradevicetype\/dual"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcameradevicetype\/dual"]}],"abstract":[{"text":"The dual lens\/device (wide + tele).","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraDeviceType\/dual"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dual"}]}]}],"metadata":{"navigatorTitle":[{"text":"SBSDKCameraDeviceTypeDual","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKCameraDeviceType@SBSDKCameraDeviceTypeDual","roleHeading":"Case","title":"SBSDKCameraDeviceType.dual","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dual","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraDeviceType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraDeviceType/dual":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKCameraDeviceTypeDual","kind":"identifier"}],"abstract":[{"type":"text","text":"The dual lens\/device (wide + tele)."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraDeviceType\/dual","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dual","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameradevicetype\/dual","type":"topic","title":"SBSDKCameraDeviceType.dual"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraDeviceType":{"title":"SBSDKCameraDeviceType","abstract":[{"type":"text","text":"An enum to describe the different types of camera lenses\/devices."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraDeviceType","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameradevicetype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKCameraDeviceTypeDual","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeDual"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKCameraDeviceTypeDual","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKCameraDeviceTypeDual","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraDeviceType~1dual\/title","op":"replace"},{"value":[{"text":"SBSDKCameraDeviceTypeDual","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraDeviceType~1dual\/fragments","op":"replace"},{"value":"SBSDKCameraDeviceType","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraDeviceType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraDeviceType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraDeviceType\/navigatorTitle","op":"replace"}]}]}