{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcameralivescannerresolution\/fullhd"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcameralivescannerresolution\/fullhd"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullHd"}]}],"kind":"declarations"}],"kind":"symbol","metadata":{"roleHeading":"Case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCameraLiveScannerResolution@SBSDKCameraLiveScannerResolutionFullHd","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullHd"}],"title":"SBSDKCameraLiveScannerResolution.fullHd","symbolKind":"case","navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolutionFullHd","kind":"identifier"}]},"abstract":[{"type":"text","text":"The image is in Full HD resolution. 1920x1080 pixels or close to it."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/fullHd","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraLiveScannerResolution/fullHd":{"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullHd","kind":"identifier"}],"abstract":[{"type":"text","text":"The image is in Full HD resolution. 1920x1080 pixels or close to it."}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameralivescannerresolution\/fullhd","title":"SBSDKCameraLiveScannerResolution.fullHd","navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolutionFullHd","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/fullHd"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraLiveScannerResolution":{"navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameralivescannerresolution","title":"SBSDKCameraLiveScannerResolution","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"abstract":[{"text":"The size of the image from camera which would be sent to the scanner for live scanning.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKCameraLiveScannerResolutionFullHd","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKCameraLiveScannerResolutionFullHd","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKCameraLiveScannerResolutionFullHd","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKCameraLiveScannerResolutionFullHd","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution~1fullHd\/title"},{"value":[{"text":"SBSDKCameraLiveScannerResolutionFullHd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution~1fullHd\/fragments"},{"value":"SBSDKCameraLiveScannerResolution","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution\/title"},{"value":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution\/fragments"},{"value":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}