{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(SBSDKUI2ReviewBottomBarConfiguration) "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/init()"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/addButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/cropButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/deleteButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/retakeButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/rotateButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/submitButton"],"anchor":"Instance-Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/toJson(configuration:)"]}],"abstract":[{"text":"Configuration of the bottom bar for the review screen.","type":"text"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Node"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration","interfaceLanguage":"swift"},"metadata":{"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReviewBottomBarConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"identifier"}],"title":"SBSDKUI2ReviewBottomBarConfiguration","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration/toJson(configuration:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/toJson(configuration:)","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/tojson(configuration:)","type":"topic","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"title":"toJson(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration/cropButton":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"cropButton"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/cropButton","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cropButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/cropbutton","kind":"symbol","role":"symbol","title":"cropButton","abstract":[{"text":"Configuration of the ‘crop’ button, located in the bottom bar.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration/submitButton":{"navigatorTitle":[{"text":"submitButton","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/submitButton","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/submitbutton","abstract":[{"type":"text","text":"Configuration of the ‘submit’ button, located in the bottom bar."}],"type":"topic","title":"submitButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration/addButton":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/addButton","abstract":[{"text":"Configuration of the ‘add’ button, located in the bottom bar.","type":"text"}],"navigatorTitle":[{"text":"addButton","kind":"identifier"}],"role":"symbol","title":"addButton","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/addbutton"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration/initWithAddButton:retakeButton:cropButton:rotateButton:deleteButton:submitButton:":{"type":"topic","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithAddButton:retakeButton:cropButton:rotateButton:deleteButton:submitButton:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/initWithAddButton:retakeButton:cropButton:rotateButton:deleteButton:submitButton:","role":"symbol","navigatorTitle":[{"text":"initWithAddButton:retakeButton:cropButton:rotateButton:deleteButton:submitButton:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/initwithaddbutton:retakebutton:cropbutton:rotatebutton:deletebutton:submitbutton:","title":"initWithAddButton:retakeButton:cropButton:rotateButton:deleteButton:submitButton:","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Node":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2Node"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2node","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Node","role":"symbol","abstract":[{"text":"Abstract class for all the configurations.","type":"text"}],"title":"SBSDKUI2Node","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Node"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration/hash":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/hash","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/hash","abstract":[],"kind":"symbol","title":"hash","type":"topic","fragments":[{"text":"hash","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration/deleteButton":{"abstract":[{"text":"Configuration of the ‘delete’ button, located in the bottom bar.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deleteButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"deleteButton"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/deleteButton","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/deletebutton","kind":"symbol","role":"symbol","title":"deleteButton"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration/copyWithZone:":{"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/copyWithZone:","abstract":[],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol","title":"copyWithZone:","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/copywithzone:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration","kind":"symbol","abstract":[{"text":"Configuration of the bottom bar for the review screen.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration","title":"SBSDKUI2ReviewBottomBarConfiguration","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration/init()":{"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"title":"init()","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/init()"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration/isEqual:":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/isequal:","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration/retakeButton":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"retakeButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","text":"SBSDKUI2BarButtonConfiguration"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/retakeButton","type":"topic","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/retakebutton","navigatorTitle":[{"text":"retakeButton","kind":"identifier"}],"title":"retakeButton","abstract":[{"text":"Configuration of the ‘retake’ button, located in the bottom bar.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration/fromJsonWithJson:":{"role":"symbol","abstract":[],"fragments":[{"kind":"text","text":"+ "},{"text":"fromJsonWithJson:","kind":"identifier"}],"kind":"symbol","title":"fromJsonWithJson:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/fromjsonwithjson:","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration/rotateButton":{"navigatorTitle":[{"text":"rotateButton","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/rotatebutton","abstract":[{"type":"text","text":"Configuration of the ‘rotate’ button, located in the bottom bar."}],"role":"symbol","type":"topic","title":"rotateButton","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rotateButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","text":"SBSDKUI2BarButtonConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/rotateButton"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"SBSDKUI2ReviewBottomBarConfiguration","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"}]},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/addButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/cropButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/deleteButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/hash","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/retakeButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/rotateButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/submitButton"],"anchor":"Instance-Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/init()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/initWithAddButton:retakeButton:cropButton:rotateButton:deleteButton:submitButton:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/toJson(configuration:)"]},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/fromJsonWithJson:"],"anchor":"Type-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Node"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying"],"kind":"relationships","title":"Conforms To"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Node","text":"SBSDKUI2Node","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Node"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1toJson(configuration:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1toJson(configuration:)\/fragments"},{"value":"cropButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1cropButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1cropButton\/fragments","value":[{"kind":"identifier","text":"cropButton"}]},{"op":"replace","value":"submitButton","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1submitButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1submitButton\/fragments","value":[{"kind":"identifier","text":"submitButton"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1addButton\/title","value":"addButton","op":"replace"},{"op":"replace","value":[{"text":"addButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1addButton\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Node\/title","value":"SBSDKUI2Node","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Node\/fragments","value":[{"text":"SBSDKUI2Node","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2Node","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Node\/navigatorTitle","op":"replace"},{"value":"deleteButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1deleteButton\/title"},{"op":"replace","value":[{"text":"deleteButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1deleteButton\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration\/title","op":"replace","value":"SBSDKUI2ReviewBottomBarConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"}]},{"op":"replace","value":[{"text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration\/navigatorTitle"},{"value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1init()\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1init()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1retakeButton\/title","value":"retakeButton","op":"replace"},{"value":[{"kind":"identifier","text":"retakeButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1retakeButton\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1rotateButton\/title","value":"rotateButton","op":"replace"},{"value":[{"text":"rotateButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1rotateButton\/fragments","op":"replace"}]}]}