{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"A class to store and restore images of different types in a memory-efficient way."}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/init(imageFormat:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/init(imageFormat:quality:location:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/init(withJPEGAndCompressionQuality:)"]},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/allPageFileIDs","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/writingImageFileFormat","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/writingJpegImageCompressionQuality"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/add(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/existsPageFileID(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/image(withPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/imageURL(withPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/previewImage(withPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/previewImageURL(withPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/removeAll()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/removeAllExcept(pageFileIDs:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/removeImage(forExistingPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/removePageFileID(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/set(_:forExistingPageFileID:pageFileType:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/defaultStorage"]},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/setDefaultStorage(_:)"],"title":"Type Methods"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"class","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentPageFileStorage","navigatorTitle":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"title":"SBSDKDocumentPageFileStorage","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"inlineContent":[{"type":"text","text":"Think of it as a 2-dimensional (page file identifier, page file type) disk-backed, dictionary-style image storage."},{"type":"text","text":" "},{"type":"text","text":"The default instance serves as backing storage for all "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage"},{"text":" objects.","type":"text"},{"text":" ","type":"text"},{"text":"Can generate preview images of optimal resolution for the devices screen.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Manages two types of images: original images (as from camera or photo library)"},{"type":"text","text":" "},{"type":"text","text":"and document images (cropped and perspective-corrected)."},{"type":"text","text":" "},{"type":"text","text":"Helps you efficiently managing and persisting larger images without keeping them in memory."}],"type":"paragraph"},{"style":"warning","name":"Warning","content":[{"type":"paragraph","inlineContent":[{"text":"Since all images stored here are being persisted to the disk forever, you are responsible for removing","type":"text"},{"text":" ","type":"text"},{"text":"unused images.","type":"text"}]}],"type":"aside"}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage"]}],"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPage":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPage","kind":"identifier"}],"type":"topic","role":"symbol","title":"SBSDKDocumentPage","abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpage"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/removeAll()":{"title":"removeAll()","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/removeAll()","abstract":[{"type":"text","text":"Removes all images from the receiver."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeAll"},{"text":"()","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"removeAll","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/removeall()"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/image(withPageFileID:pageFileType:)":{"navigatorTitle":[{"kind":"identifier","text":"imageWithPageFileID:pageFileType:"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/image(withPageFileID:pageFileType:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/image(withpagefileid:pagefiletype:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPageFileID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageFileType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentPageFileType","text":"SBSDKDocumentPageFileType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Returns the image with the given page file identifier and page file type."}],"title":"image(withPageFileID:pageFileType:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/existsPageFileID(_:)":{"title":"existsPageFileID(_:)","type":"topic","abstract":[{"text":"Checks if a page file identifier exists in the receiver.","type":"text"}],"navigatorTitle":[{"text":"existsPageFileID:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/existspagefileid(_:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/existsPageFileID(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"existsPageFileID","kind":"identifier"},{"kind":"text","text":"("},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/removeAllExcept(pageFileIDs:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/removeallexcept(pagefileids:)","type":"topic","title":"removeAllExcept(pageFileIDs:)","abstract":[{"type":"text","text":"Removes all images from the receiver, except those from the exception list."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeAllExcept","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pageFileIDs","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":"])"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"removeAllExceptWithPageFileIDs:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/removeAllExcept(pageFileIDs:)","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage":{"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage","title":"SBSDKDocumentPageFileStorage","abstract":[{"type":"text","text":"A class to store and restore images of different types in a memory-efficient way."}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/init(imageFormat:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageFormat"},{"text":": ","kind":"text"},{"text":"SBSDKImageFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/init(imageformat:)","kind":"symbol","title":"init(imageFormat:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/init(imageFormat:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithImageFormat:"}],"type":"topic","abstract":[{"type":"text","text":"Initializes a storage with compression quality set to 80 at the default storage location."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/setDefaultStorage(_:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/setdefaultstorage(_:)","type":"topic","role":"symbol","abstract":[{"text":"Sets the default instance of this class.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDefaultStorage","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKDocumentPageFileStorage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentPageFileStorage"},{"text":")","kind":"text"}],"title":"setDefaultStorage(_:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/setDefaultStorage(_:)","navigatorTitle":[{"text":"setDefaultStorage:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/allPageFileIDs":{"navigatorTitle":[{"text":"allPageFileIDs","kind":"identifier"}],"abstract":[{"text":"A list of all stored page file identifiers.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allPageFileIDs","kind":"identifier"},{"text":": [","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"allPageFileIDs","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/allPageFileIDs","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/allpagefileids","role":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/removePageFileID(_:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/removePageFileID(_:)","type":"topic","title":"removePageFileID(_:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/removepagefileid(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removePageFileID","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"removePageFileID:"}],"abstract":[{"type":"text","text":"Removes all images with the given page file identifier."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/init(withJPEGAndCompressionQuality:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"withJPEGAndCompressionQuality","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithJPEGAndCompressionQuality:","kind":"identifier"}],"type":"topic","title":"init(withJPEGAndCompressionQuality:)","abstract":[{"text":"Initializes a storage with JPEG image format at the default storage location.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/init(withjpegandcompressionquality:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/init(withJPEGAndCompressionQuality:)","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/writingJpegImageCompressionQuality":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"writingJpegImageCompressionQuality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"writingJpegImageCompressionQuality","kind":"identifier"}],"type":"topic","title":"writingJpegImageCompressionQuality","abstract":[{"text":"If file format is set to JPEG, this property holds the compression quality of the stored images.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/writingJpegImageCompressionQuality","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/writingjpegimagecompressionquality","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/add(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":") -> "},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","title":"add(_:)","abstract":[{"text":"Adds an image of page file type original to the receiver, generates a page file identifier and returns it.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"add:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/add(_:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/add(_:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/previewImageURL(withPageFileID:pageFileType:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/previewimageurl(withpagefileid:pagefiletype:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/previewImageURL(withPageFileID:pageFileType:)","role":"symbol","title":"previewImageURL(withPageFileID:pageFileType:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewImageURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPageFileID","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"},{"text":", ","kind":"text"},{"text":"pageFileType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentPageFileType","text":"SBSDKDocumentPageFileType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Returns the file URL of a screen-size preview of the image with the given page file identifier and page file type."}],"navigatorTitle":[{"kind":"identifier","text":"previewImageURLWithPageFileID:pageFileType:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/removeImage(forExistingPageFileID:pageFileType:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/removeimage(forexistingpagefileid:pagefiletype:)","kind":"symbol","title":"removeImage(forExistingPageFileID:pageFileType:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"forExistingPageFileID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pageFileType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentPageFileType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"removeImageForExistingPageFileID:pageFileType:","kind":"identifier"}],"abstract":[{"text":"Removes the image with the given page file identifier and page file type.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/removeImage(forExistingPageFileID:pageFileType:)"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/writingImageFileFormat":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/writingimagefileformat","abstract":[{"type":"text","text":"File format of the stored images. Read-only. Defaults to JPEG."}],"title":"writingImageFileFormat","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"writingImageFileFormat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKImageFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat"}],"kind":"symbol","navigatorTitle":[{"text":"writingImageFileFormat","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/writingImageFileFormat","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/defaultStorage":{"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/defaultStorage","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultStorage"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentPageFileStorage","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentPageFileStorage","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"defaultStorage"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/defaultstorage","abstract":[{"type":"text","text":"The default instance of this class."}],"kind":"symbol","title":"defaultStorage"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/imageURL(withPageFileID:pageFileType:)":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/imageURL(withPageFileID:pageFileType:)","type":"topic","title":"imageURL(withPageFileID:pageFileType:)","navigatorTitle":[{"text":"imageURLWithPageFileID:pageFileType:","kind":"identifier"}],"abstract":[{"text":"Returns the file URL of the image with the given page file identifier and page file type.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPageFileID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"text":"pageFileType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentPageFileType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentPageFileType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/imageurl(withpagefileid:pagefiletype:)","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/init(imageFormat:quality:location:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/init(imageFormat:quality:location:)","type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/init(imageformat:quality:location:)","role":"symbol","title":"init(imageFormat:quality:location:)","navigatorTitle":[{"text":"initWithImageFormat:quality:location:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageFormat"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat","text":"SBSDKImageFileFormat","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"quality","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"text":"SBSDKStorageLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation"},{"text":"?)","kind":"text"}],"abstract":[{"text":"Initializes a storage.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/previewImage(withPageFileID:pageFileType:)":{"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewImage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPageFileID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageFileType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentPageFileType"},{"text":") -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Returns the screen-size preview image with the given page file identifier and page file type."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/previewimage(withpagefileid:pagefiletype:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/previewImage(withPageFileID:pageFileType:)","navigatorTitle":[{"text":"previewImageWithPageFileID:pageFileType:","kind":"identifier"}],"title":"previewImage(withPageFileID:pageFileType:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/set(_:forExistingPageFileID:pageFileType:)":{"role":"symbol","title":"set(_:forExistingPageFileID:pageFileType:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forExistingPageFileID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageFileType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentPageFileType","text":"SBSDKDocumentPageFileType"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"set:forExistingPageFileID:pageFileType:"}],"kind":"symbol","abstract":[{"type":"text","text":"Sets the image of the given page file type and page file type to the receiver."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/set(_:forExistingPageFileID:pageFileType:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/set(_:forexistingpagefileid:pagefiletype:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"SBSDKDocumentPageFileStorage","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/allPageFileIDs","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/writingImageFileFormat","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/writingJpegImageCompressionQuality"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/add(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/existsPageFileID(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/image(withPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/imageURL(withPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/init(imageFormat:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/init(imageFormat:quality:location:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/init(withJPEGAndCompressionQuality:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/previewImage(withPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/previewImageURL(withPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/removeAll()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/removeAllExcept(pageFileIDs:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/removeImage(forExistingPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/removePageFileID(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/set(_:forExistingPageFileID:pageFileType:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/defaultStorage"],"title":"Type Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/setDefaultStorage(_:)"],"title":"Type Methods"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/title","value":"SBSDKDocumentPage","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1removeAll()\/title","op":"replace","value":"removeAll"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1removeAll()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeAll","kind":"identifier"}],"op":"replace"},{"value":"imageWithPageFileID:pageFileType:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1image(withPageFileID:pageFileType:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1image(withPageFileID:pageFileType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageWithPageFileID:pageFileType:"}]},{"op":"replace","value":"existsPageFileID:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1existsPageFileID(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"existsPageFileID:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1existsPageFileID(_:)\/fragments"},{"value":"removeAllExceptWithPageFileIDs:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1removeAllExcept(pageFileIDs:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1removeAllExcept(pageFileIDs:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeAllExceptWithPageFileIDs:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage\/title","value":"SBSDKDocumentPageFileStorage","op":"replace"},{"value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1init(imageFormat:)\/title","value":"initWithImageFormat:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1init(imageFormat:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithImageFormat:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1setDefaultStorage(_:)\/title","value":"setDefaultStorage:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1setDefaultStorage(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"setDefaultStorage:","kind":"identifier"}]},{"value":"allPageFileIDs","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1allPageFileIDs\/title"},{"value":[{"text":"allPageFileIDs","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1allPageFileIDs\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1removePageFileID(_:)\/title","op":"replace","value":"removePageFileID:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1removePageFileID(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"removePageFileID:","kind":"identifier"}]},{"value":"initWithJPEGAndCompressionQuality:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1init(withJPEGAndCompressionQuality:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1init(withJPEGAndCompressionQuality:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithJPEGAndCompressionQuality:"}]},{"op":"replace","value":"writingJpegImageCompressionQuality","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1writingJpegImageCompressionQuality\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1writingJpegImageCompressionQuality\/fragments","value":[{"kind":"identifier","text":"writingJpegImageCompressionQuality"}],"op":"replace"},{"value":"add:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1add(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"add:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1add(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1previewImageURL(withPageFileID:pageFileType:)\/title","value":"previewImageURLWithPageFileID:pageFileType:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1previewImageURL(withPageFileID:pageFileType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previewImageURLWithPageFileID:pageFileType:"}]},{"value":"removeImageForExistingPageFileID:pageFileType:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1removeImage(forExistingPageFileID:pageFileType:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeImageForExistingPageFileID:pageFileType:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1removeImage(forExistingPageFileID:pageFileType:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1writingImageFileFormat\/title","value":"writingImageFileFormat","op":"replace"},{"value":[{"text":"writingImageFileFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1writingImageFileFormat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1defaultStorage\/title","value":"defaultStorage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1defaultStorage\/fragments","op":"replace","value":[{"kind":"identifier","text":"defaultStorage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1imageURL(withPageFileID:pageFileType:)\/title","value":"imageURLWithPageFileID:pageFileType:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1imageURL(withPageFileID:pageFileType:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageURLWithPageFileID:pageFileType:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1init(imageFormat:quality:location:)\/title","value":"initWithImageFormat:quality:location:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1init(imageFormat:quality:location:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageFormat:quality:location:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1previewImage(withPageFileID:pageFileType:)\/title","op":"replace","value":"previewImageWithPageFileID:pageFileType:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1previewImage(withPageFileID:pageFileType:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"previewImageWithPageFileID:pageFileType:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1set(_:forExistingPageFileID:pageFileType:)\/title","value":"set:forExistingPageFileID:pageFileType:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1set(_:forExistingPageFileID:pageFileType:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"set:forExistingPageFileID:pageFileType:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}