{"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/aspectRatio","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/backgroundColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/backgroundEffect","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/finderSafeArea","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/ignoresSafeAreaInsets","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/isAnimatingChanges","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/isViewFinderEnabled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/lineColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/lineCornerRadius","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/lineWidth","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/minimumInset","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/preferredHeight","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/secondaryAspectRatio","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/secondaryMinimumInset","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/style"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/defaultConfiguration"],"title":"Type Properties"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration"},"kind":"symbol","abstract":[{"text":"The view finder configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Sometimes it is necessary to limit a live video frame detection or recognition to a certain rectangular area with"},{"type":"text","text":" "},{"text":"a specific aspect ratio: the region or rectangle of interest. This is where a view finder comes in.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It crops the video frame to that region of interest before passing it to any detector or recognizer. Usually"},{"type":"text","text":" "},{"type":"text","text":"the performance of detectors\/recognizers gain a benefit from it because less pixels must be processed."},{"type":"text","text":" "},{"type":"text","text":"Additionally, to guide the user, the view finder visualizes the region of interest by drawing a rectangle around"},{"type":"text","text":" "},{"text":"on the user interface.","type":"text"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"]}],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration","symbolKind":"class","navigatorTitle":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}],"title":"SBSDKBaseScannerViewFinderConfiguration","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Since the display resp. the camera view size differs from device to device specifying the region of interest","type":"text"},{"text":" ","type":"text"},{"text":"in absolute screen points would require some additional calculations and therefore be inconvenient.","type":"text"},{"type":"text","text":" "},{"text":"Instead a combination of aspect ratio and minimum distances to the view(screen) edges is used.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 5.0.2","type":"text"}],"role":"collection","type":"topic","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/defaultConfiguration":{"title":"defaultConfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/defaultConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/defaultconfiguration","type":"topic","abstract":[{"text":"This is the default configuration with the properties initialized as mentioned in their description.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultConfiguration"},{"text":": ","kind":"text"},{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration"}],"navigatorTitle":[{"text":"defaultConfiguration","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/lineCornerRadius":{"title":"lineCornerRadius","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/lineCornerRadius","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/linecornerradius","type":"topic","abstract":[{"text":"The corner radius of the view finders outline.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to 8 points.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"lineCornerRadius","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"navigatorTitle":[{"text":"lineCornerRadius","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/style":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/style","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/style","navigatorTitle":[{"text":"style","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKFinderView","text":"SBSDKFinderView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:25ScanbotDocumentScannerSDK15SBSDKFinderViewC5StyleO","kind":"typeIdentifier","text":"Style"}],"title":"style","abstract":[{"type":"text","text":"The drawing style of the finder view."}]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/finderSafeArea":{"title":"finderSafeArea","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/finderSafeArea","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/findersafearea","type":"topic","abstract":[{"text":"The area where the finder should be placed in the coordinate system of the receiver.","type":"text"},{"text":" ","type":"text"},{"text":"Is ignored if finder safe area is empty (zero height or width).","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finderSafeArea"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"navigatorTitle":[{"text":"finderSafeArea","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/ignoresSafeAreaInsets":{"title":"ignoresSafeAreaInsets","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/ignoresSafeAreaInsets","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/ignoressafeareainsets","type":"topic","abstract":[{"text":"If set to ","type":"text"},{"code":"False","type":"codeVoice"},{"text":", the finder is inset by the safe area insets. Otherwise the safe area inset is ignored.","type":"text"},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"False"},{"text":";","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ignoresSafeAreaInsets","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"ignoresSafeAreaInsets","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/isAnimatingChanges":{"navigatorTitle":[{"text":"isAnimatingChanges","kind":"identifier"}],"abstract":[{"type":"text","text":"Set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":" to animate the view finder when changing the aspect ratio or minimum insets, to "},{"type":"codeVoice","code":"False"},{"text":" if changes should not be animated.","type":"text"},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":"."}],"title":"isAnimatingChanges","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/isAnimatingChanges","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isAnimatingChanges","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/isanimatingchanges"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/secondaryAspectRatio":{"title":"secondaryAspectRatio","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/secondaryAspectRatio","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/secondaryaspectratio","abstract":[{"type":"text","text":"The aspect ratio of the secondary view finder that is displayed with dashed lines."},{"text":" ","type":"text"},{"type":"text","text":"If set to "},{"code":"nil","type":"codeVoice"},{"text":" no secondary view finder is drawn.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"secondaryAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio","text":"SBSDKAspectRatio","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"secondaryAspectRatio"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration","title":"SBSDKBaseScannerViewFinderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"The view finder configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"text":" ","type":"text"},{"type":"text","text":"Sometimes it is necessary to limit a live video frame detection or recognition to a certain rectangular area with"},{"type":"text","text":" "},{"text":"a specific aspect ratio: the region or rectangle of interest. This is where a view finder comes in.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It crops the video frame to that region of interest before passing it to any detector or recognizer. Usually"},{"text":" ","type":"text"},{"text":"the performance of detectors\/recognizers gain a benefit from it because less pixels must be processed.","type":"text"},{"text":" ","type":"text"},{"text":"Additionally, to guide the user, the view finder visualizes the region of interest by drawing a rectangle around","type":"text"},{"type":"text","text":" "},{"type":"text","text":"on the user interface."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/secondaryMinimumInset":{"title":"secondaryMinimumInset","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/secondaryMinimumInset","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/secondaryminimuminset","type":"topic","abstract":[{"text":"The minimum space from the primary view finder to the secondary view finder for each edge.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to {10, 10, 10, 10}.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"secondaryMinimumInset","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"secondaryMinimumInset","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/isViewFinderEnabled":{"role":"symbol","title":"isViewFinderEnabled","kind":"symbol","navigatorTitle":[{"text":"isViewFinderEnabled","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/isviewfinderenabled","abstract":[{"text":"Set to ","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":" to enable and display the region of interest, to "},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"False"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/isViewFinderEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isViewFinderEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/lineWidth":{"abstract":[{"text":"The line width of the view finders outline.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to 2 points."}],"title":"lineWidth","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/linewidth","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/lineWidth","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lineWidth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"navigatorTitle":[{"text":"lineWidth","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/backgroundColor":{"abstract":[{"type":"text","text":"The color of the background outside the view finders outline. Use this color to mask the region"},{"text":" ","type":"text"},{"text":"that is not of interest.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to a black color with an opacity of 0.66, slightly darkening the non-interest area of the screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/backgroundColor","navigatorTitle":[{"text":"backgroundColor","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/backgroundcolor","title":"backgroundColor","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/backgroundEffect":{"title":"backgroundEffect","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/backgroundEffect","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/backgroundeffect","abstract":[{"type":"text","text":"The visual effect applied to the area outside the view finder. If "},{"code":"nil","type":"codeVoice"},{"type":"text","text":", no effect is applied."},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"backgroundEffect","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIVisualEffect","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIVisualEffect"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"backgroundEffect","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/init":{"abstract":[],"title":"init","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/init","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/preferredHeight":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/preferredHeight","navigatorTitle":[{"kind":"identifier","text":"preferredHeight"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/preferredheight","title":"preferredHeight","abstract":[{"type":"text","text":"If positive, the receiver will try to maintain the preferred height and the aspect ratio for the finder by dynamically"},{"type":"text","text":" "},{"text":"changing the inset. If negative this property will be ignored.","type":"text"},{"type":"text","text":" "},{"text":"Defaults to -1;","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/lineColor":{"title":"lineColor","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/lineColor","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/linecolor","type":"topic","abstract":[{"type":"text","text":"The line color of the view finders outline. Can be "},{"code":"nil","type":"codeVoice"},{"text":" to not display the outline.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to a fully opaque white color.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"lineColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"text":"lineColor","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/aspectRatio":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/aspectRatio","title":"aspectRatio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"aspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKAspectRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio"}],"abstract":[{"text":"The aspect ratio of the region of interest. Defaults to 4:3.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/aspectratio","role":"symbol","navigatorTitle":[{"text":"aspectRatio","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/minimumInset":{"role":"symbol","title":"minimumInset","abstract":[{"text":"The minimum space from view finders outer edges to the view\/screen edges.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to {20, 20, 20, 20}."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimumInset"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"minimumInset","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/minimuminset","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/minimumInset"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"SBSDKBaseScannerViewFinderConfiguration","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/aspectRatio","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/backgroundColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/backgroundEffect","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/finderSafeArea","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/ignoresSafeAreaInsets","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/isAnimatingChanges","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/isViewFinderEnabled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/lineColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/lineCornerRadius","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/lineWidth","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/minimumInset","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/preferredHeight","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/secondaryAspectRatio","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/secondaryMinimumInset","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/style"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/init"]},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/defaultConfiguration"],"title":"Type Properties"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"defaultConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1defaultConfiguration\/title","op":"replace"},{"value":[{"text":"defaultConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1defaultConfiguration\/fragments","op":"replace"},{"op":"replace","value":"lineCornerRadius","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1lineCornerRadius\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1lineCornerRadius\/fragments","value":[{"text":"lineCornerRadius","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1style\/title","value":"style"},{"value":[{"text":"style","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1style\/fragments"},{"value":"finderSafeArea","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1finderSafeArea\/title"},{"op":"replace","value":[{"text":"finderSafeArea","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1finderSafeArea\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1ignoresSafeAreaInsets\/title","value":"ignoresSafeAreaInsets"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1ignoresSafeAreaInsets\/fragments","value":[{"text":"ignoresSafeAreaInsets","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1isAnimatingChanges\/title","op":"replace","value":"isAnimatingChanges"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1isAnimatingChanges\/fragments","value":[{"kind":"identifier","text":"isAnimatingChanges"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1secondaryAspectRatio\/title","value":"secondaryAspectRatio","op":"replace"},{"value":[{"text":"secondaryAspectRatio","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1secondaryAspectRatio\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/title","value":"SBSDKBaseScannerViewFinderConfiguration"},{"value":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1secondaryMinimumInset\/title","op":"replace","value":"secondaryMinimumInset"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1secondaryMinimumInset\/fragments","value":[{"kind":"identifier","text":"secondaryMinimumInset"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1isViewFinderEnabled\/title","value":"isViewFinderEnabled","op":"replace"},{"op":"replace","value":[{"text":"isViewFinderEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1isViewFinderEnabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1lineWidth\/title","value":"lineWidth"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1lineWidth\/fragments","value":[{"text":"lineWidth","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1backgroundColor\/title","op":"replace","value":"backgroundColor"},{"value":[{"text":"backgroundColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1backgroundColor\/fragments"},{"value":"backgroundEffect","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1backgroundEffect\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1backgroundEffect\/fragments","op":"replace","value":[{"kind":"identifier","text":"backgroundEffect"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1preferredHeight\/title","op":"replace","value":"preferredHeight"},{"op":"replace","value":[{"kind":"identifier","text":"preferredHeight"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1preferredHeight\/fragments"},{"value":"lineColor","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1lineColor\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"lineColor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1lineColor\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1aspectRatio\/title","value":"aspectRatio","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1aspectRatio\/fragments","value":[{"text":"aspectRatio","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1minimumInset\/title","op":"replace","value":"minimumInset"},{"op":"replace","value":[{"text":"minimumInset","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1minimumInset\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}