{"metadata":{"roleHeading":"Class","title":"SBSDKUIFinderDocumentScannerTextConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerTextConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIFinderDocumentScannerTextConfiguration","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerTextConfiguration","symbolKind":"class"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIEnableCameraTextConfiguration"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/accessibilityConfiguration","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/cameraUnavailableExplanationText","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/cancelButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintBadAngles","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintBadAspectRatio","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintEnergySavingActive","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintFontSize","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintNothingDetected","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintOK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintOffCenter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintTooDark","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintTooNoisy","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintTooSmall"],"title":"Instance Properties"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerTextConfiguration"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration"},"kind":"symbol","abstract":[{"type":"text","text":"Configuration for the textual contents of the document scanning screen."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIEnableCameraTextConfiguration":{"type":"topic","title":"SBSDKUIEnableCameraTextConfiguration","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuienablecameratextconfiguration","abstract":[{"text":"Configuration for the textual contents of camera based view controllers.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIEnableCameraTextConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration/textHintEnergySavingActive":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/texthintenergysavingactive","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintEnergySavingActive","type":"topic","navigatorTitle":[{"text":"textHintEnergySavingActive","kind":"identifier"}],"abstract":[{"type":"text","text":"The text being displayed on the user-guidance label, when the scanners energy saver is activated."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textHintEnergySavingActive"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"textHintEnergySavingActive"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration/textHintNothingDetected":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/texthintnothingdetected","kind":"symbol","title":"textHintNothingDetected","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintNothingDetected","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textHintNothingDetected"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textHintNothingDetected","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The text being displayed on the user-guidance label, when no document was detected."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration/textHintBadAngles":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/texthintbadangles","kind":"symbol","title":"textHintBadAngles","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintBadAngles","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textHintBadAngles"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textHintBadAngles"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The text being displayed on the user-guidance label, when a document was detected, but the perspective distortion is too strong."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration/textHintTooSmall":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/texthinttoosmall","kind":"symbol","title":"textHintTooSmall","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintTooSmall","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textHintTooSmall"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textHintTooSmall","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The text being displayed on the user-guidance label, when a document was detected, but the documents area is too small compared to the image area."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration/textHintTooDark":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintTooDark","role":"symbol","navigatorTitle":[{"text":"textHintTooDark","kind":"identifier"}],"kind":"symbol","title":"textHintTooDark","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/texthinttoodark","abstract":[{"text":"The text being displayed on the user-guidance label, when no document was detected because the image is too dark.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"textHintTooDark","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration/textHintTooNoisy":{"kind":"symbol","abstract":[{"type":"text","text":"The text being displayed on the user-guidance label, when no document was detected because of image noise."}],"title":"textHintTooNoisy","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textHintTooNoisy"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/texthinttoonoisy","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintTooNoisy","navigatorTitle":[{"kind":"identifier","text":"textHintTooNoisy"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration/textHintFontSize":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/texthintfontsize","kind":"symbol","title":"textHintFontSize","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintFontSize","role":"symbol","type":"topic","navigatorTitle":[{"text":"textHintFontSize","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textHintFontSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The font size for the user guidance label in points."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration/cameraUnavailableExplanationText":{"role":"symbol","title":"cameraUnavailableExplanationText","kind":"symbol","navigatorTitle":[{"text":"cameraUnavailableExplanationText","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/cameraunavailableexplanationtext","abstract":[{"text":"String being displayed on the label describing that the app is in split mode and needs to go fullscreen to work with camera.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/cameraUnavailableExplanationText","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cameraUnavailableExplanationText","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration/cancelButtonTitle":{"kind":"symbol","title":"cancelButtonTitle","navigatorTitle":[{"kind":"identifier","text":"cancelButtonTitle"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/cancelButtonTitle","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/cancelbuttontitle","abstract":[{"type":"text","text":"String being displayed on the cancel button."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelButtonTitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 5.0.2","type":"text"}],"role":"collection","type":"topic","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration/accessibilityConfiguration":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/accessibilityconfiguration","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityConfiguration"},{"text":": ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerAccessibilityConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/accessibilityConfiguration","abstract":[{"type":"text","text":"A configuration with accessibility texts settings."}],"navigatorTitle":[{"text":"accessibilityConfiguration","kind":"identifier"}],"kind":"symbol","title":"accessibilityConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration/textHintBadAspectRatio":{"kind":"symbol","title":"textHintBadAspectRatio","navigatorTitle":[{"text":"textHintBadAspectRatio","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintBadAspectRatio","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/texthintbadaspectratio","abstract":[{"text":"The text being displayed on the user-guidance label, when a document was detected,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"but the aspect ratio of the document is inverse to the cameras aspect ratio."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textHintBadAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration/textHintOffCenter":{"kind":"symbol","title":"textHintOffCenter","navigatorTitle":[{"text":"textHintOffCenter","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintOffCenter","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/texthintoffcenter","abstract":[{"text":"The text being displayed on the user-guidance label, when a document was detected, but its center is too far away from the image center.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textHintOffCenter","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration/init":{"kind":"symbol","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/init","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/init","abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration","title":"SBSDKUIFinderDocumentScannerTextConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerTextConfiguration"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerTextConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for the textual contents of the document scanning screen."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration/textHintOK":{"kind":"symbol","title":"textHintOK","navigatorTitle":[{"text":"textHintOK","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintOK","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/texthintok","abstract":[{"type":"text","text":"The text being displayed on the user-guidance label, when a document was detected with good conditions."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textHintOK","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"SBSDKUIFinderDocumentScannerTextConfiguration","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerTextConfiguration"}],"op":"replace"},{"value":[{"text":"SBSDKUIFinderDocumentScannerTextConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/accessibilityConfiguration","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/cameraUnavailableExplanationText","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/cancelButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintBadAngles","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintBadAspectRatio","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintEnergySavingActive","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintFontSize","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintNothingDetected","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintOK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintOffCenter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintTooDark","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintTooNoisy","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintTooSmall"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/init"],"title":"Instance Methods"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIEnableCameraTextConfiguration"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerTextConfiguration"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIEnableCameraTextConfiguration","kind":"typeIdentifier","text":"SBSDKUIEnableCameraTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIEnableCameraTextConfiguration"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIEnableCameraTextConfiguration\/title","op":"replace","value":"SBSDKUIEnableCameraTextConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIEnableCameraTextConfiguration\/fragments","value":[{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintEnergySavingActive\/title","op":"replace","value":"textHintEnergySavingActive"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintEnergySavingActive\/fragments","op":"replace","value":[{"kind":"identifier","text":"textHintEnergySavingActive"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintNothingDetected\/title","op":"replace","value":"textHintNothingDetected"},{"op":"replace","value":[{"text":"textHintNothingDetected","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintNothingDetected\/fragments"},{"value":"textHintBadAngles","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintBadAngles\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintBadAngles\/fragments","value":[{"text":"textHintBadAngles","kind":"identifier"}]},{"value":"textHintTooSmall","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintTooSmall\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintTooSmall\/fragments","op":"replace","value":[{"text":"textHintTooSmall","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintTooDark\/title","value":"textHintTooDark"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintTooDark\/fragments","value":[{"kind":"identifier","text":"textHintTooDark"}],"op":"replace"},{"op":"replace","value":"textHintTooNoisy","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintTooNoisy\/title"},{"value":[{"kind":"identifier","text":"textHintTooNoisy"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintTooNoisy\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintFontSize\/title","op":"replace","value":"textHintFontSize"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintFontSize\/fragments","value":[{"text":"textHintFontSize","kind":"identifier"}]},{"op":"replace","value":"cameraUnavailableExplanationText","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1cameraUnavailableExplanationText\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1cameraUnavailableExplanationText\/fragments","value":[{"text":"cameraUnavailableExplanationText","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1cancelButtonTitle\/title","value":"cancelButtonTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1cancelButtonTitle\/fragments","value":[{"kind":"identifier","text":"cancelButtonTitle"}],"op":"replace"},{"value":"accessibilityConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1accessibilityConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1accessibilityConfiguration\/fragments","value":[{"kind":"identifier","text":"accessibilityConfiguration"}],"op":"replace"},{"value":"textHintBadAspectRatio","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintBadAspectRatio\/title","op":"replace"},{"value":[{"text":"textHintBadAspectRatio","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintBadAspectRatio\/fragments"},{"op":"replace","value":"textHintOffCenter","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintOffCenter\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintOffCenter\/fragments","value":[{"text":"textHintOffCenter","kind":"identifier"}]},{"op":"replace","value":"SBSDKUIFinderDocumentScannerTextConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUIFinderDocumentScannerTextConfiguration","kind":"identifier"}]},{"value":"textHintOK","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintOK\/title"},{"value":[{"kind":"identifier","text":"textHintOK"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintOK\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}