{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}],"platforms":["iOS"]}]}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/displayedAspectRatio","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/finderDelegate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/finderRect","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/finderSafeArea","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/ignoresSafeAreaInsets","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/isAnimatingChanges","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/lineColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/lineCornerRadius","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/lineWidth","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/minimumInset","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/preferredHeight","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/secondaryAspectRatio","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/secondaryFinderRect","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/secondaryMinimumInset","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/style-swift.property"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/bezierPathConvertedToView(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:)"]},{"title":"Enumerations","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/Style-swift.enum"]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"SBSDKFinderView","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKFinderView","title":"SBSDKFinderView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKFinderView","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview"]}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIView"},{"text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio.","type":"text"}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)UIView"],"title":"Inherits From","kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)CALayerDelegate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s8SendableP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAppearance","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UICoordinateSpace","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIDynamicItem","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIFocusItem","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIFocusItemContainer","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","type":"conformsTo"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView","title":"SBSDKFinderView","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview","navigatorTitle":[{"text":"SBSDKFinderView","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio."}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/secondaryFinderRect":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/secondaryfinderrect","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"secondaryFinderRect"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"secondaryFinderRect"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"abstract":[{"text":"The current rect of the finders secondary viewport in the local coordinate system.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/secondaryFinderRect","title":"secondaryFinderRect","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/potentialviewfinderrectwithbounds(_:findersafearea:aspectratio:minimuminsets:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:)","role":"symbol","title":"potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:)","navigatorTitle":[{"kind":"identifier","text":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:"}],"abstract":[{"text":"A function, that returns a rect of a finder, if it will be placed in view with certain bounds, with given aspect ratio and insets. Useful for pre-calculations in some animation cases","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"potentialViewFinderRectWithBounds"},{"kind":"text","text":"("},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"finderSafeArea","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"aspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minimumInsets"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/secondaryMinimumInset":{"type":"topic","role":"symbol","title":"secondaryMinimumInset","abstract":[{"type":"text","text":"Minimum inset of the secondary viewport, related to the primary viewport."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"secondaryMinimumInset","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/secondaryminimuminset","navigatorTitle":[{"kind":"identifier","text":"secondaryMinimumInset"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/secondaryMinimumInset"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/ignoresSafeAreaInsets":{"type":"topic","role":"symbol","title":"ignoresSafeAreaInsets","abstract":[{"type":"text","text":"If set to "},{"code":"False","type":"codeVoice"},{"type":"text","text":", the finder is inset by the safe area insets."},{"type":"text","text":" "},{"text":"Otherwise the safe area inset is ignored.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ignoresSafeAreaInsets","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/ignoressafeareainsets","navigatorTitle":[{"text":"ignoresSafeAreaInsets","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/ignoresSafeAreaInsets"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/lineCornerRadius":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/linecornerradius","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/lineCornerRadius","role":"symbol","title":"lineCornerRadius","navigatorTitle":[{"text":"lineCornerRadius","kind":"identifier"}],"abstract":[{"type":"text","text":"The corner radius of the receivers border line."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"lineCornerRadius","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/finderRect":{"title":"finderRect","role":"symbol","navigatorTitle":[{"text":"finderRect","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/finderRect","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/finderrect","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderRect","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"abstract":[{"text":"The current rect of the finders viewport in the local coordinate system.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/isAnimatingChanges":{"title":"isAnimatingChanges","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isAnimatingChanges"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/isAnimatingChanges","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/isanimatingchanges","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAnimatingChanges","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":" finder changes will be animated, otherwise no animations will happen."}]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UICoordinateSpace"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/bezierPathConvertedToView(_:)":{"abstract":[{"type":"text","text":"Creates a bezier path describing the view finders rectangle in the specified views coordinate system."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/bezierPathConvertedToView(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"bezierPathConvertedToView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?) -> ","kind":"text"},{"text":"UIBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/bezierpathconvertedtoview(_:)","role":"symbol","title":"bezierPathConvertedToView(_:)","navigatorTitle":[{"kind":"identifier","text":"bezierPathConvertedToView:"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/layoutSubviews":{"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/layoutSubviews","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/layoutsubviews","role":"symbol","title":"layoutSubviews","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/lineWidth":{"abstract":[{"text":"The line width of the receivers border line.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/lineWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"lineWidth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/linewidth","role":"symbol","title":"lineWidth","navigatorTitle":[{"text":"lineWidth","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/secondaryAspectRatio":{"abstract":[{"type":"text","text":"The secondary aspect ratio of the viewport (cutout), if set to -1.0, no cutout is drawn."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/secondaryAspectRatio","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"secondaryAspectRatio","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/secondaryaspectratio","role":"symbol","title":"secondaryAspectRatio","navigatorTitle":[{"text":"secondaryAspectRatio","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIFocusItem":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/finderDelegate":{"abstract":[{"text":"The receivers delegate.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/finderDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"finderDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKFinderViewDelegate","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKFinderViewDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/finderdelegate","role":"symbol","title":"finderDelegate","navigatorTitle":[{"kind":"identifier","text":"finderDelegate"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/displayedAspectRatio":{"abstract":[{"text":"The aspect ratio of the viewport (cutout), if set to -1.0, no cutout is drawn.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/displayedAspectRatio","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayedAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/displayedaspectratio","role":"symbol","title":"displayedAspectRatio","navigatorTitle":[{"kind":"identifier","text":"displayedAspectRatio"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/Style-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"abstract":[{"type":"text","text":"The enum that defines the drawing styles of the finder view."}],"title":"SBSDKFinderView.Style","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/Style-swift.enum","navigatorTitle":[{"kind":"identifier","text":"Style"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/style-swift.enum"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)UIView"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/minimumInset":{"abstract":[{"type":"text","text":"Parameter that defines minimum inset of viewport from edge of the screen."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/minimumInset","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"minimumInset","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/minimuminset","role":"symbol","title":"minimumInset","navigatorTitle":[{"kind":"identifier","text":"minimumInset"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/s8SendableP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/preferredHeight":{"abstract":[{"text":"If positive, the receiver will try to maintain the preferred height and the aspect ratio for the finder by dynamically","type":"text"},{"type":"text","text":" "},{"text":"changing the inset. If negative this property will be ignored.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/preferredHeight","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredHeight"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/preferredheight","role":"symbol","title":"preferredHeight","navigatorTitle":[{"kind":"identifier","text":"preferredHeight"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIFocusEnvironment"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/drawRect:":{"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/drawRect:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"drawRect:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/drawrect:","role":"symbol","title":"drawRect:","navigatorTitle":[{"kind":"identifier","text":"drawRect:"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UILargeContentViewerItem"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIFocusItemContainer"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/5UIKit23UITraitChangeObservableP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/style-swift.property":{"abstract":[{"type":"text","text":"The drawing style of the finder view."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/style-swift.property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"style"},{"text":": ","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:25ScanbotDocumentScannerSDK15SBSDKFinderViewC5StyleO"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/style-swift.property","role":"symbol","title":"style","navigatorTitle":[{"text":"style","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/init":{"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/init","role":"symbol","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/finderSafeArea":{"abstract":[{"type":"text","text":"The area where the finder should be placed in the coordinate system of the receiver."},{"type":"text","text":" "},{"text":"Is ignored if finder safe area is empty (zero height or width).","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/finderSafeArea","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finderSafeArea"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/findersafearea","role":"symbol","title":"finderSafeArea","navigatorTitle":[{"kind":"identifier","text":"finderSafeArea"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/initWithCoder:":{"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/initWithCoder:","fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/initwithcoder:","role":"symbol","title":"initWithCoder:","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIUserActivityRestoring"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/safeAreaInsetsDidChange":{"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/safeAreaInsetsDidChange","fragments":[{"kind":"text","text":"- "},{"text":"safeAreaInsetsDidChange","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/safeareainsetsdidchange","role":"symbol","title":"safeAreaInsetsDidChange","navigatorTitle":[{"kind":"identifier","text":"safeAreaInsetsDidChange"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 5.0.2","type":"text"}],"role":"collection","type":"topic","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/lineColor":{"abstract":[{"text":"The color of the receivers border line.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/lineColor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/linecolor","role":"symbol","title":"lineColor","navigatorTitle":[{"text":"lineColor","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/initWithFrame:":{"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/initWithFrame:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/initwithframe:","role":"symbol","title":"initWithFrame:","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKFinderView"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKFinderView","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKFinderView","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/displayedAspectRatio","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/finderDelegate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/finderRect","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/finderSafeArea","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/ignoresSafeAreaInsets","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/isAnimatingChanges","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/lineColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/lineCornerRadius","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/lineWidth","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/minimumInset","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/preferredHeight","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/secondaryAspectRatio","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/secondaryFinderRect","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/secondaryMinimumInset","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/style-swift.property"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/bezierPathConvertedToView(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/drawRect:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/init","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/initWithCoder:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/initWithFrame:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/layoutSubviews","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/safeAreaInsetsDidChange"]},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:)"],"title":"Type Methods"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)UIView"],"title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKFinderView","kind":"identifier"},{"kind":"text","text":" : "},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"value":"SBSDKFinderView","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView\/fragments","value":[{"kind":"identifier","text":"SBSDKFinderView"}]},{"value":"secondaryFinderRect","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1secondaryFinderRect\/title"},{"value":[{"text":"secondaryFinderRect","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1secondaryFinderRect\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:)\/title","value":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1secondaryMinimumInset\/title","value":"secondaryMinimumInset","op":"replace"},{"value":[{"kind":"identifier","text":"secondaryMinimumInset"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1secondaryMinimumInset\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1ignoresSafeAreaInsets\/title","value":"ignoresSafeAreaInsets"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1ignoresSafeAreaInsets\/fragments","op":"replace","value":[{"text":"ignoresSafeAreaInsets","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1lineCornerRadius\/title","value":"lineCornerRadius"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1lineCornerRadius\/fragments","value":[{"kind":"identifier","text":"lineCornerRadius"}]},{"value":"finderRect","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1finderRect\/title"},{"value":[{"kind":"identifier","text":"finderRect"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1finderRect\/fragments"},{"op":"replace","value":"isAnimatingChanges","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1isAnimatingChanges\/title"},{"op":"replace","value":[{"text":"isAnimatingChanges","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1isAnimatingChanges\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1bezierPathConvertedToView(_:)\/title","value":"bezierPathConvertedToView:"},{"value":[{"kind":"text","text":"- "},{"text":"bezierPathConvertedToView:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1bezierPathConvertedToView(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1lineWidth\/title","value":"lineWidth"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1lineWidth\/fragments","value":[{"text":"lineWidth","kind":"identifier"}],"op":"replace"},{"value":"secondaryAspectRatio","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1secondaryAspectRatio\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1secondaryAspectRatio\/fragments","op":"replace","value":[{"text":"secondaryAspectRatio","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1finderDelegate\/title","value":"finderDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"finderDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1finderDelegate\/fragments"},{"value":"displayedAspectRatio","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1displayedAspectRatio\/title","op":"replace"},{"value":[{"kind":"identifier","text":"displayedAspectRatio"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1displayedAspectRatio\/fragments"},{"value":"minimumInset","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1minimumInset\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1minimumInset\/fragments","value":[{"kind":"identifier","text":"minimumInset"}]},{"value":"preferredHeight","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1preferredHeight\/title"},{"op":"replace","value":[{"kind":"identifier","text":"preferredHeight"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1preferredHeight\/fragments"},{"value":"style","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1style-swift.property\/title"},{"value":[{"kind":"identifier","text":"style"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1style-swift.property\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1finderSafeArea\/title","value":"finderSafeArea"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1finderSafeArea\/fragments","value":[{"kind":"identifier","text":"finderSafeArea"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1lineColor\/title","value":"lineColor","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"lineColor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1lineColor\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}