{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdksimulatedcameramockdata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdksimulatedcameramockdata"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageName:capturedImageName:refreshOnEachFrame:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData\/label","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData\/refreshOnEachFrame"],"anchor":"Instance-Properties"}],"metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"title":"SBSDKSimulatedCameraMockData","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKSimulatedCameraMockData","roleHeading":"Class","role":"symbol"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"A simulated camera device loops a single image and provides the frames to the ScanbotSDK scanner UI components.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Along with the frame image you can optionally specify an image that is passed to the ScanbotSDK scanner UI components when capturing a still image."}]},{"inlineContent":[{"text":"Intended to be used with UI tests.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"text":"A class to describe the mocking data that is fed to a simulated camera device.","type":"text"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSimulatedCameraMockData":{"role":"symbol","type":"topic","title":"SBSDKSimulatedCameraMockData","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"abstract":[{"text":"A class to describe the mocking data that is fed to a simulated camera device.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksimulatedcameramockdata","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSimulatedCameraMockData/refreshOnEachFrame":{"type":"topic","kind":"symbol","role":"symbol","title":"refreshOnEachFrame","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshOnEachFrame"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"text":"If set to ","type":"text"},{"code":"True","type":"codeVoice"},{"text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksimulatedcameramockdata\/refreshoneachframe","navigatorTitle":[{"kind":"identifier","text":"refreshOnEachFrame"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData\/refreshOnEachFrame"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSimulatedCameraMockData/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)":{"abstract":[{"text":"Initializes mock data for a simulated camera device from URLs.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksimulatedcameramockdata\/init(label:imageurl:capturedimageurl:refreshoneachframe:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"imageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"capturedImageURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"refreshOnEachFrame"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"init(label:imageURL:capturedImageURL:refreshOnEachFrame:)","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSimulatedCameraMockData/label":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData\/label","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"label"}],"abstract":[{"text":"The label of the mock data. Can be used to identify the mock data.","type":"text"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksimulatedcameramockdata\/label","title":"label"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSimulatedCameraMockData/init(label:imageName:capturedImageName:refreshOnEachFrame:)":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageName:capturedImageName:refreshOnEachFrame:)","abstract":[{"text":"Initializes mock data for a simulated camera device from ressource names of the application bundle.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksimulatedcameramockdata\/init(label:imagename:capturedimagename:refreshoneachframe:)","title":"init(label:imageName:capturedImageName:refreshOnEachFrame:)","kind":"symbol","navigatorTitle":[{"text":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","kind":"identifier"}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"capturedImageName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"refreshOnEachFrame","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"SBSDKSimulatedCameraMockData","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData\/label","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData\/refreshOnEachFrame"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageName:capturedImageName:refreshOnEachFrame:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"title":"Inherits From"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData\/title","value":"SBSDKSimulatedCameraMockData"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData\/fragments","value":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}]},{"value":"refreshOnEachFrame","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData~1refreshOnEachFrame\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData~1refreshOnEachFrame\/fragments","value":[{"kind":"identifier","text":"refreshOnEachFrame"}],"op":"replace"},{"value":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData~1init(label:imageURL:capturedImageURL:refreshOnEachFrame:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData~1init(label:imageURL:capturedImageURL:refreshOnEachFrame:)\/fragments"},{"value":"label","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData~1label\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData~1label\/fragments","op":"replace","value":[{"text":"label","kind":"identifier"}]},{"op":"replace","value":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData~1init(label:imageName:capturedImageName:refreshOnEachFrame:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData~1init(label:imageName:capturedImageName:refreshOnEachFrame:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}