{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectionMetrics"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The metrics and additional properties returned by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Can be used to make decisions on polygon acceptance, automatic capturing and user guidance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectionMetrics"}],"title":"SBSDKDocumentDetectionMetrics","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionMetrics","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionMetrics"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/angleScore","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/averageBrightness","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/distanceScore","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/heightScore","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/sizeScore","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/totalScore","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/unwarpedAspectRatio","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/widthScore"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/copy(with:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/indexMatchingAspectRatios(of:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/matches(aspectRatio:)"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetector":{"role":"symbol","title":"SBSDKDocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetector"}],"abstract":[{"type":"text","text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics/unwarpedAspectRatio":{"role":"symbol","title":"unwarpedAspectRatio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unwarpedAspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The unwarped aspect ratio of the detected polygon or -1, if no polygon was detected."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/unwarpedAspectRatio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unwarpedAspectRatio"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/unwarpedaspectratio"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics/widthScore":{"role":"symbol","title":"widthScore","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The width score of the detected polygon (0 - 100). Part of the size score."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/widthScore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"widthScore"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/widthscore"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics/heightScore":{"role":"symbol","title":"heightScore","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"heightScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The height score of the detected polygon (0 - 100). Part of the size score."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/heightScore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"heightScore"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/heightscore"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics/sizeScore":{"role":"symbol","title":"sizeScore","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The size score of the detected polygon (0 - 100). Part of the total score."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/sizeScore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sizeScore"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/sizescore"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics/angleScore":{"role":"symbol","title":"angleScore","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"angleScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The angles score of the detected polygon (0 - 100). Part of the total score."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/angleScore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"angleScore"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/anglescore"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics/indexMatchingAspectRatios(of:)":{"role":"symbol","title":"indexMatchingAspectRatios(of:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexMatchingAspectRatios"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Checks if an array given aspect ratios matches."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/indexMatchingAspectRatios(of:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"indexMatchingAspectRatiosOf:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/indexmatchingaspectratios(of:)"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics/distanceScore":{"role":"symbol","title":"distanceScore","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distanceScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The distance-from-center score of the detected polygon (0 - 100). Part of the total score."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/distanceScore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"distanceScore"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/distancescore"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics":{"role":"symbol","title":"SBSDKDocumentDetectionMetrics","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectionMetrics"}],"abstract":[{"type":"text","text":"The metrics and additional properties returned by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Can be used to make decisions on polygon acceptance, automatic capturing and user guidance."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionMetrics"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics/averageBrightness":{"role":"symbol","title":"averageBrightness","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"averageBrightness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The average brightness of the detectors input image (0-255)."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/averageBrightness","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"averageBrightness"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/averagebrightness"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":"Creates a deep copy of the "},{"type":"codeVoice","code":"SBSDKDocumentDetectionMetrics"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/copy(with:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics/totalScore":{"role":"symbol","title":"totalScore","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The total score of the detected polygon (0 - 100)."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/totalScore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"totalScore"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/totalscore"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.1.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics/matches(aspectRatio:)":{"role":"symbol","title":"matches(aspectRatio:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"matches"},{"kind":"text","text":"("},{"kind":"externalParam","text":"aspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Checks if the passed aspect ratio matches the "},{"type":"codeVoice","code":"unwarpedAspectRatio"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/matches(aspectRatio:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"matchesWithAspectRatio:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/matches(aspectratio:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/init"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKDocumentDetectionMetrics"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionMetrics"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionMetrics"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/angleScore","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/averageBrightness","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/distanceScore","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/heightScore","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/sizeScore","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/totalScore","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/unwarpedAspectRatio","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/widthScore"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/copy(with:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/indexMatchingAspectRatios(of:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/init","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/matches(aspectRatio:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectionMetrics"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/title","value":"SBSDKDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1unwarpedAspectRatio\/title","value":"unwarpedAspectRatio"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1unwarpedAspectRatio\/fragments","value":[{"kind":"identifier","text":"unwarpedAspectRatio"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1widthScore\/title","value":"widthScore"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1widthScore\/fragments","value":[{"kind":"identifier","text":"widthScore"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1heightScore\/title","value":"heightScore"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1heightScore\/fragments","value":[{"kind":"identifier","text":"heightScore"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1sizeScore\/title","value":"sizeScore"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1sizeScore\/fragments","value":[{"kind":"identifier","text":"sizeScore"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1angleScore\/title","value":"angleScore"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1angleScore\/fragments","value":[{"kind":"identifier","text":"angleScore"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1indexMatchingAspectRatios(of:)\/title","value":"indexMatchingAspectRatiosOf:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1indexMatchingAspectRatios(of:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexMatchingAspectRatiosOf:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1distanceScore\/title","value":"distanceScore"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1distanceScore\/fragments","value":[{"kind":"identifier","text":"distanceScore"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics\/title","value":"SBSDKDocumentDetectionMetrics"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionMetrics"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1averageBrightness\/title","value":"averageBrightness"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1averageBrightness\/fragments","value":[{"kind":"identifier","text":"averageBrightness"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1totalScore\/title","value":"totalScore"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1totalScore\/fragments","value":[{"kind":"identifier","text":"totalScore"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1matches(aspectRatio:)\/title","value":"matchesWithAspectRatio:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1matches(aspectRatio:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"matchesWithAspectRatio:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}