{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeylength"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeylength"]}],"abstract":[{"text":"The length of the encryption key.","type":"text"}],"sections":[],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"symbolKind":"enum","title":"SBSDKStorageCryptingKeyLength","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKStorageCryptingKeyLength"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength\/bits128","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength\/bits256"],"title":"Enumeration Cases"},{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength\/init(rawValue:)"]},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}]}]}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"],"title":"Conforms To","kind":"relationships"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyLength/init(rawValue:)":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeylength\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength\/init(rawValue:)","abstract":[],"title":"init(rawValue:)"},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyLength":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"role":"symbol","title":"SBSDKStorageCryptingKeyLength","abstract":[{"text":"The length of the encryption key.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeylength","navigatorTitle":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/s12CaseIterableP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s12CaseIterableP","title":"Swift.CaseIterable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyLength/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength\/RawRepresentable-Implementations","kind":"article","type":"topic","abstract":[],"role":"collectionGroup","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeylength\/rawrepresentable-implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyLength/bits256":{"title":"SBSDKStorageCryptingKeyLength.bits256","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLengthBits256"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"bits256","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeylength\/bits256","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength\/bits256","abstract":[{"type":"text","text":"A key length of 256 bits (32 bytes)."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyLength/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeylength\/equatable-implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyLength/bits128":{"title":"SBSDKStorageCryptingKeyLength.bits128","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength\/bits128","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeylength\/bits128","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"bits128","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A key length of 128 bits (16 bytes) ."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLengthBits128"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKStorageCryptingKeyLength","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength\/bits128","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyLength\/bits256"],"anchor":"Enumeration-Cases","generated":true}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKStorageCryptingKeyLength","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyLength\/title","op":"replace"},{"value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyLength\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyLength\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"op":"replace"},{"value":"SBSDKStorageCryptingKeyLengthBits256","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyLength~1bits256\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyLength~1bits256\/fragments","value":[{"text":"SBSDKStorageCryptingKeyLengthBits256","kind":"identifier"}]},{"value":"SBSDKStorageCryptingKeyLengthBits128","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyLength~1bits128\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyLength~1bits128\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLengthBits128"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}