{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource","interfaceLanguage":"swift"},"abstract":[{"text":"The source from where the image of the page originated from.","type":"text"}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"symbolKind":"enum","title":"SBSDKDocumentPageImageSource","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPageImageSource"}],"roleHeading":"Enumeration","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentPageImageSource"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/autoSnap","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/imported","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/manualSnap","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/undefined","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/videoFrame"]},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"],"title":"Conforms To","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageImageSource/init(rawValue:)":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource\/init(rawvalue:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","title":"init(rawValue:)","role":"symbol","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.2.1"}],"type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageImageSource/videoFrame":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource\/videoframe","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/videoFrame","abstract":[{"text":"If the source image was taken from the video frame.","type":"text"}],"kind":"symbol","role":"symbol","title":"SBSDKDocumentPageImageSource.videoFrame","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"videoFrame","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentPageImageSourceVideoFrame","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageImageSource/RawRepresentable-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource\/rawrepresentable-implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageImageSource/manualSnap":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource\/manualsnap","kind":"symbol","abstract":[{"text":"If the source image was captured manually. For example, when the user pressed a snap button.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"manualSnap"}],"title":"SBSDKDocumentPageImageSource.manualSnap","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/manualSnap","navigatorTitle":[{"text":"SBSDKDocumentPageImageSourceManualSnap","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageImageSource/Equatable-Implementations":{"kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource\/equatable-implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageImageSource/autoSnap":{"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoSnap"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource\/autosnap","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/autoSnap","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceAutoSnap"}],"abstract":[{"type":"text","text":"If the source image was captured automatically. For example, by auto snapping functions."}],"title":"SBSDKDocumentPageImageSource.autoSnap","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageImageSource":{"kind":"symbol","abstract":[{"type":"text","text":"The source from where the image of the page originated from."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentPageImageSource"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"title":"SBSDKDocumentPageImageSource","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageImageSource/imported":{"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imported"}],"navigatorTitle":[{"text":"SBSDKDocumentPageImageSourceImported","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource\/imported","title":"SBSDKDocumentPageImageSource.imported","abstract":[{"type":"text","text":"If the source image was imported from external source."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/imported","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageImageSource/undefined":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpageimagesource\/undefined","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/undefined","abstract":[{"type":"text","text":"Used by default. If the source is not defined."}],"kind":"symbol","role":"symbol","title":"SBSDKDocumentPageImageSource.undefined","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"undefined"}],"navigatorTitle":[{"text":"SBSDKDocumentPageImageSourceUndefined","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"SBSDKDocumentPageImageSource","op":"replace","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}]},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/autoSnap","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/imported","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/manualSnap","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/undefined","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageImageSource\/videoFrame"]}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKDocumentPageImageSource","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKDocumentPageImageSourceVideoFrame","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource~1videoFrame\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource~1videoFrame\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceVideoFrame"}],"op":"replace"},{"value":"SBSDKDocumentPageImageSourceManualSnap","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource~1manualSnap\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource~1manualSnap\/fragments","op":"replace","value":[{"text":"SBSDKDocumentPageImageSourceManualSnap","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource~1autoSnap\/title","value":"SBSDKDocumentPageImageSourceAutoSnap"},{"value":[{"text":"SBSDKDocumentPageImageSourceAutoSnap","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource~1autoSnap\/fragments"},{"value":"SBSDKDocumentPageImageSource","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource\/fragments","op":"replace","value":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}]},{"op":"replace","value":"SBSDKDocumentPageImageSourceImported","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource~1imported\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource~1imported\/fragments","value":[{"text":"SBSDKDocumentPageImageSourceImported","kind":"identifier"}]},{"value":"SBSDKDocumentPageImageSourceUndefined","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource~1undefined\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageImageSource~1undefined\/fragments","value":[{"text":"SBSDKDocumentPageImageSourceUndefined","kind":"identifier"}],"op":"replace"}]}]}