{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFeature"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The features that are activated in the ScanbotSDK license."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFeature"}],"title":"SBSDKFeature","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKFeature","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKFeature"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/EHICRecognition","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/IDCardRecognition","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/MRZRecognition","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/NFCScanning","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/OCR","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/PDFCreation","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/barcodeDetection","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/checkRecognition","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/cloudUpload","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/creditCardRecognition","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/dataIntelligence","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/driverLicenseRecognition","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/edgeDetection","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/edgeDetectionUI","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/imageProcessing","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/invoiceDetection","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/licensePlateScanning","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/medicalCertRecognition","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/multipleObjectsDetection","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/payformDetection","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/textLineRecognition","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/textOrientationDetection","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/w2Detection"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/multipleObjectsDetection":{"role":"symbol","title":"SBSDKFeature.multipleObjectsDetection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"multipleObjectsDetection"}],"abstract":[{"type":"text","text":"Multiple objects detection is enabled in the licence. Currently unused."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/multipleObjectsDetection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureMultipleObjectsDetection"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/multipleobjectsdetection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/PDFCreation":{"role":"symbol","title":"SBSDKFeature.PDFCreation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDFCreation"}],"abstract":[{"type":"text","text":"PDF creation is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/PDFCreation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeaturePDFCreation"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/pdfcreation"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/dataIntelligence":{"role":"symbol","title":"SBSDKFeature.dataIntelligence","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataIntelligence"}],"abstract":[{"type":"text","text":"Data intelligence is enabled in the licence. Currently unused."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/dataIntelligence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureDataIntelligence"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/dataintelligence"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/cloudUpload":{"role":"symbol","title":"SBSDKFeature.cloudUpload","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudUpload"}],"abstract":[{"type":"text","text":"Cloud upload is enabled in the licence. Currently unused."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/cloudUpload","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureCloudUpload"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/cloudupload"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/rawrepresentable-implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/OCR":{"role":"symbol","title":"SBSDKFeature.OCR","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCR"}],"abstract":[{"type":"text","text":"Optical character recognition is enabled in the license."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/OCR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureOCR"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/ocr"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/NFCScanning":{"role":"symbol","title":"SBSDKFeature.NFCScanning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NFCScanning"}],"abstract":[{"type":"text","text":"NFC scanning is enabled in the license. Currently unused."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/NFCScanning","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureNFCScanning"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/nfcscanning"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/textOrientationDetection":{"role":"symbol","title":"SBSDKFeature.textOrientationDetection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"textOrientationDetection"}],"abstract":[{"type":"text","text":"Text layout recognition is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/textOrientationDetection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureTextOrientationDetection"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/textorientationdetection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/driverLicenseRecognition":{"role":"symbol","title":"SBSDKFeature.driverLicenseRecognition","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"driverLicenseRecognition"}],"abstract":[{"type":"text","text":"Driver license recognition is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/driverLicenseRecognition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureDriverLicenseRecognition"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/driverlicenserecognition"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/equatable-implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/barcodeDetection":{"role":"symbol","title":"SBSDKFeature.barcodeDetection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeDetection"}],"abstract":[{"type":"text","text":"Barcode detection is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/barcodeDetection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureBarcodeDetection"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/barcodedetection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/MRZRecognition":{"role":"symbol","title":"SBSDKFeature.MRZRecognition","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MRZRecognition"}],"abstract":[{"type":"text","text":"Machine-readable-zone detection is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/MRZRecognition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureMRZRecognition"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/mrzrecognition"},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/textLineRecognition":{"role":"symbol","title":"SBSDKFeature.textLineRecognition","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"textLineRecognition"}],"abstract":[{"type":"text","text":"Text line recognition is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/textLineRecognition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureTextLineRecognition"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/textlinerecognition"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/imageProcessing":{"role":"symbol","title":"SBSDKFeature.imageProcessing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageProcessing"}],"abstract":[{"type":"text","text":"Image processing is enabled in the license."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/imageProcessing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureImageProcessing"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/imageprocessing"},"doc://net.doo.ScanbotDocumentScannerSDK/s12CaseIterableP":{"type":"unresolvable","title":"Swift.CaseIterable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s12CaseIterableP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature":{"role":"symbol","title":"SBSDKFeature","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFeature"}],"abstract":[{"type":"text","text":"The features that are activated in the ScanbotSDK license."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeature"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/SBSDKFeatureNone":{"role":"symbol","title":"SBSDKFeatureNone","fragments":[{"kind":"identifier","text":"SBSDKFeatureNone"}],"abstract":[{"type":"text","text":"Driver license recognition is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/SBSDKFeatureNone","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/sbsdkfeaturenone"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/creditCardRecognition":{"role":"symbol","title":"SBSDKFeature.creditCardRecognition","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"creditCardRecognition"}],"abstract":[{"type":"text","text":"Credit card recognition is enabled in the licence. Currently unused."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/creditCardRecognition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureCreditCardRecognition"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/creditcardrecognition"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/payformDetection":{"role":"symbol","title":"SBSDKFeature.payformDetection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"payformDetection"}],"abstract":[{"type":"text","text":"Payform detection is enabled in the license. Currently unused."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/payformDetection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeaturePayformDetection"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/payformdetection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/w2Detection":{"role":"symbol","title":"SBSDKFeature.w2Detection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"w2Detection"}],"abstract":[{"type":"text","text":"W2 document detection is enabled in the licence. Currently unused."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/w2Detection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureW2Detection"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/w2detection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/init(rawvalue:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/IDCardRecognition":{"role":"symbol","title":"SBSDKFeature.IDCardRecognition","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCardRecognition"}],"abstract":[{"type":"text","text":"ID card and passport recognition is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/IDCardRecognition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureIDCardRecognition"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/idcardrecognition"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/licensePlateScanning":{"role":"symbol","title":"SBSDKFeature.licensePlateScanning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"licensePlateScanning"}],"abstract":[{"type":"text","text":"License plate scanning is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/licensePlateScanning","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureLicensePlateScanning"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/licenseplatescanning"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/checkRecognition":{"role":"symbol","title":"SBSDKFeature.checkRecognition","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkRecognition"}],"abstract":[{"type":"text","text":"Check recognition is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/checkRecognition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureCheckRecognition"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/checkrecognition"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/EHICRecognition":{"role":"symbol","title":"SBSDKFeature.EHICRecognition","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"EHICRecognition"}],"abstract":[{"type":"text","text":"European health insurance card recognition is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/EHICRecognition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureEHICRecognition"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/ehicrecognition"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/invoiceDetection":{"role":"symbol","title":"SBSDKFeature.invoiceDetection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invoiceDetection"}],"abstract":[{"type":"text","text":"Invoice recognition is enabled in the licence. Currently unused."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/invoiceDetection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureInvoiceDetection"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/invoicedetection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/medicalCertRecognition":{"role":"symbol","title":"SBSDKFeature.medicalCertRecognition","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"medicalCertRecognition"}],"abstract":[{"type":"text","text":"Medical certificate recognition is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/medicalCertRecognition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureMedicalCertRecognition"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/medicalcertrecognition"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/edgeDetection":{"role":"symbol","title":"SBSDKFeature.edgeDetection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"edgeDetection"}],"abstract":[{"type":"text","text":"Document detection is enabled in the license."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/edgeDetection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureEdgeDetection"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/edgedetection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/edgeDetectionUI":{"role":"symbol","title":"SBSDKFeature.edgeDetectionUI","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"edgeDetectionUI"}],"abstract":[{"type":"text","text":"Document detection user interface is enabled in the license."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/edgeDetectionUI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureEdgeDetectionUI"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/edgedetectionui"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKFeature"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKFeature"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFeature"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/EHICRecognition","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/IDCardRecognition","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/MRZRecognition","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/NFCScanning","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/OCR","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/PDFCreation","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/SBSDKFeatureNone","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/barcodeDetection","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/checkRecognition","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/cloudUpload","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/creditCardRecognition","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/dataIntelligence","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/driverLicenseRecognition","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/edgeDetection","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/edgeDetectionUI","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/imageProcessing","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/invoiceDetection","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/licensePlateScanning","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/medicalCertRecognition","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/multipleObjectsDetection","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/payformDetection","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/textLineRecognition","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/textOrientationDetection","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/w2Detection"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFeature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1multipleObjectsDetection\/title","value":"SBSDKFeatureMultipleObjectsDetection"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1multipleObjectsDetection\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureMultipleObjectsDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1PDFCreation\/title","value":"SBSDKFeaturePDFCreation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1PDFCreation\/fragments","value":[{"kind":"identifier","text":"SBSDKFeaturePDFCreation"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1dataIntelligence\/title","value":"SBSDKFeatureDataIntelligence"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1dataIntelligence\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureDataIntelligence"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1cloudUpload\/title","value":"SBSDKFeatureCloudUpload"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1cloudUpload\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureCloudUpload"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1OCR\/title","value":"SBSDKFeatureOCR"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1OCR\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureOCR"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1NFCScanning\/title","value":"SBSDKFeatureNFCScanning"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1NFCScanning\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureNFCScanning"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1textOrientationDetection\/title","value":"SBSDKFeatureTextOrientationDetection"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1textOrientationDetection\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureTextOrientationDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1driverLicenseRecognition\/title","value":"SBSDKFeatureDriverLicenseRecognition"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1driverLicenseRecognition\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureDriverLicenseRecognition"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1barcodeDetection\/title","value":"SBSDKFeatureBarcodeDetection"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1barcodeDetection\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureBarcodeDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1MRZRecognition\/title","value":"SBSDKFeatureMRZRecognition"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1MRZRecognition\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureMRZRecognition"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1textLineRecognition\/title","value":"SBSDKFeatureTextLineRecognition"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1textLineRecognition\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureTextLineRecognition"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1imageProcessing\/title","value":"SBSDKFeatureImageProcessing"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1imageProcessing\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureImageProcessing"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature\/title","value":"SBSDKFeature"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature\/fragments","value":[{"kind":"identifier","text":"SBSDKFeature"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1creditCardRecognition\/title","value":"SBSDKFeatureCreditCardRecognition"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1creditCardRecognition\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureCreditCardRecognition"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1payformDetection\/title","value":"SBSDKFeaturePayformDetection"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1payformDetection\/fragments","value":[{"kind":"identifier","text":"SBSDKFeaturePayformDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1w2Detection\/title","value":"SBSDKFeatureW2Detection"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1w2Detection\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureW2Detection"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1IDCardRecognition\/title","value":"SBSDKFeatureIDCardRecognition"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1IDCardRecognition\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureIDCardRecognition"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1licensePlateScanning\/title","value":"SBSDKFeatureLicensePlateScanning"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1licensePlateScanning\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureLicensePlateScanning"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1checkRecognition\/title","value":"SBSDKFeatureCheckRecognition"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1checkRecognition\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureCheckRecognition"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1EHICRecognition\/title","value":"SBSDKFeatureEHICRecognition"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1EHICRecognition\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureEHICRecognition"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1invoiceDetection\/title","value":"SBSDKFeatureInvoiceDetection"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1invoiceDetection\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureInvoiceDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1medicalCertRecognition\/title","value":"SBSDKFeatureMedicalCertRecognition"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1medicalCertRecognition\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureMedicalCertRecognition"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1edgeDetection\/title","value":"SBSDKFeatureEdgeDetection"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1edgeDetection\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureEdgeDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1edgeDetectionUI\/title","value":"SBSDKFeatureEdgeDetectionUI"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1edgeDetectionUI\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureEdgeDetectionUI"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}