{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/adobe_deflate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccitt_t4","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccitt_t6","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittfax3","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittfax4","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittrle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittrlew","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/deflate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/lzw","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/none","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/packbits"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The TIFF compression algorithms."}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKTIFFImageWriterCompressionOptions","symbolKind":"enum","navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"title":"SBSDKTIFFImageWriterCompressionOptions","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}]},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/ccittrlew":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ccittrlew"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittrlew","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"For binarized images only."}],"title":"SBSDKTIFFImageWriterCompressionOptions.ccittrlew","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/ccittrlew","navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcittrlew","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/ccitt_t6":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ccitt_t6"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccitt_t6","role":"symbol","kind":"symbol","abstract":[{"text":"For binarized images only.","type":"text"}],"title":"SBSDKTIFFImageWriterCompressionOptions.ccitt_t6","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/ccitt_t6","navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcitt_t6","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/ccittrle":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ccittrle"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittrle","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"For binarized images only."}],"title":"SBSDKTIFFImageWriterCompressionOptions.ccittrle","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/ccittrle","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsCcittrle"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/deflate":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deflate"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/deflate","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"For both colored and binarized images."}],"title":"SBSDKTIFFImageWriterCompressionOptions.deflate","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/deflate","navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsDeflate","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/none":{"navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsNone","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"For both colored and binarized images.","type":"text"}],"title":"SBSDKTIFFImageWriterCompressionOptions.none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/none","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/none"},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/Equatable-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/Equatable-Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/equatable-implementations","title":"Equatable Implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/RawRepresentable-Implementations":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/RawRepresentable-Implementations","role":"collectionGroup","kind":"article","abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/rawrepresentable-implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/ccittfax4":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittfax4","kind":"symbol","type":"topic","title":"SBSDKTIFFImageWriterCompressionOptions.ccittfax4","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/ccittfax4","abstract":[{"type":"text","text":"For binarized images only."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ccittfax4","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsCcittfax4"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/ccittfax3":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ccittfax3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittfax3","role":"symbol","kind":"symbol","abstract":[{"text":"For binarized images only.","type":"text"}],"title":"SBSDKTIFFImageWriterCompressionOptions.ccittfax3","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/ccittfax3","navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcittfax3","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions":{"navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The TIFF compression algorithms."}],"title":"SBSDKTIFFImageWriterCompressionOptions","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/lzw":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lzw"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/lzw","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"For both colored and binarized images."}],"title":"SBSDKTIFFImageWriterCompressionOptions.lzw","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/lzw","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsLzw"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/adobe_deflate":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adobe_deflate"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/adobe_deflate","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"For both colored and binarized images."}],"title":"SBSDKTIFFImageWriterCompressionOptions.adobe_deflate","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/adobe_deflate","navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsAdobe_deflate","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/init(rawValue:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/init(rawValue:)","role":"symbol","kind":"symbol","abstract":[],"title":"init(rawValue:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/init(rawvalue:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/ccitt_t4":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccitt_t4","kind":"symbol","abstract":[{"type":"text","text":"For binarized images only."}],"title":"SBSDKTIFFImageWriterCompressionOptions.ccitt_t4","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ccitt_t4","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcitt_t4","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/ccitt_t4","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/packbits":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"packbits"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/packbits","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"For both colored and binarized images."}],"title":"SBSDKTIFFImageWriterCompressionOptions.packbits","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/packbits","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsPackbits"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKTIFFImageWriterCompressionOptions","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/adobe_deflate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccitt_t4","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccitt_t6","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittfax3","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittfax4","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittrle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittrlew","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/deflate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/lzw","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/none","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/packbits"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccittrlew\/title","value":"SBSDKTIFFImageWriterCompressionOptionsCcittrlew"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccittrlew\/fragments","value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcittrlew","kind":"identifier"}],"op":"replace"},{"value":"SBSDKTIFFImageWriterCompressionOptionsCcitt_t6","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccitt_t6\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsCcitt_t6"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccitt_t6\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccittrle\/title","op":"replace","value":"SBSDKTIFFImageWriterCompressionOptionsCcittrle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccittrle\/fragments","value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcittrle","kind":"identifier"}]},{"value":"SBSDKTIFFImageWriterCompressionOptionsDeflate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1deflate\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1deflate\/fragments","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsDeflate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1none\/title","value":"SBSDKTIFFImageWriterCompressionOptionsNone","op":"replace"},{"value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsNone","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1none\/fragments","op":"replace"},{"op":"replace","value":"SBSDKTIFFImageWriterCompressionOptionsCcittfax4","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccittfax4\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccittfax4\/fragments","value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcittfax4","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccittfax3\/title","value":"SBSDKTIFFImageWriterCompressionOptionsCcittfax3"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccittfax3\/fragments","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsCcittfax3"}]},{"value":"SBSDKTIFFImageWriterCompressionOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions\/title"},{"op":"replace","value":[{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1lzw\/title","value":"SBSDKTIFFImageWriterCompressionOptionsLzw"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsLzw"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1lzw\/fragments"},{"value":"SBSDKTIFFImageWriterCompressionOptionsAdobe_deflate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1adobe_deflate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1adobe_deflate\/fragments","value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsAdobe_deflate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccitt_t4\/title","op":"replace","value":"SBSDKTIFFImageWriterCompressionOptionsCcitt_t4"},{"value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcitt_t4","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccitt_t4\/fragments"},{"value":"SBSDKTIFFImageWriterCompressionOptionsPackbits","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1packbits\/title"},{"op":"replace","value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsPackbits","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1packbits\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}