{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A delegate protocol to inform an object about changes in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"title":"SBSDKImageEditingViewControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKImageEditingViewControllerDelegate","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewController(_:didApplyChangesWith:croppedImage:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerApplyButtonItem(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerCancelButtonItem(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerDidCancelChanges(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerDidChangePolygon(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerRotateClockwiseToolbarItem(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarItemTintColor(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarStyle(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarTintColor(_:)"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerDidCancelChanges(_:)":{"role":"symbol","title":"imageEditingViewControllerDidCancelChanges(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerDidCancelChanges"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Informs the delegate that the image editing view controllers cancel button was hit."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerDidCancelChanges(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerDidCancelChanges:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerdidcancelchanges(_:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewController(_:didApplyChangesWith:croppedImage:)":{"role":"symbol","title":"imageEditingViewController(_:didApplyChangesWith:croppedImage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didApplyChangesWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon"},{"kind":"text","text":", "},{"kind":"externalParam","text":"croppedImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Informs the delegate that the image editing view controllers apply button was hit."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewController(_:didApplyChangesWith:croppedImage:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewController:didApplyChangesWith:croppedImage:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontroller(_:didapplychangeswith:croppedimage:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerToolbarStyle(_:)":{"role":"symbol","title":"imageEditingViewControllerToolbarStyle(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerToolbarStyle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBarStyle","preciseIdentifier":"c:@E@UIBarStyle"}],"abstract":[{"type":"text","text":"Asks the delegate for a "},{"type":"codeVoice","code":"UIBarStyle"},{"type":"text","text":" for the bottom toolbar."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarStyle(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerToolbarStyle:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollertoolbarstyle(_:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewController":{"role":"symbol","title":"SBSDKImageEditingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show and edit an image."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontroller"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerCancelButtonItem(_:)":{"role":"symbol","title":"imageEditingViewControllerCancelButtonItem(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerCancelButtonItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Asks the delegate for a "},{"type":"codeVoice","code":"UIBarButtonItem"},{"type":"text","text":" to cancel the actual editing."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerCancelButtonItem(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerCancelButtonItem:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollercancelbuttonitem(_:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerToolbarTintColor(_:)":{"role":"symbol","title":"imageEditingViewControllerToolbarTintColor(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerToolbarTintColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Asks the delegate for the background tint color of the bottom toolbar."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarTintColor(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerToolbarTintColor:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollertoolbartintcolor(_:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerToolbarItemTintColor(_:)":{"role":"symbol","title":"imageEditingViewControllerToolbarItemTintColor(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerToolbarItemTintColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Asks the delegate for the item tint color of the bottom toolbar."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarItemTintColor(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerToolbarItemTintColor:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollertoolbaritemtintcolor(_:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerRotateClockwiseToolbarItem(_:)":{"navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerRotateClockwiseToolbarItem:"}],"role":"symbol","title":"imageEditingViewControllerRotateClockwiseToolbarItem(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerRotateClockwiseToolbarItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Asks the delegate for a "},{"type":"codeVoice","code":"UIBarButtonItem"},{"type":"text","text":" to for rotating the image clockwise."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerRotateClockwiseToolbarItem(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerrotateclockwisetoolbaritem(_:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate":{"role":"symbol","title":"SBSDKImageEditingViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"abstract":[{"type":"text","text":"A delegate protocol to inform an object about changes in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.1.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerApplyButtonItem(_:)":{"navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerApplyButtonItem:"}],"role":"symbol","title":"imageEditingViewControllerApplyButtonItem(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerApplyButtonItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Asks the delegate for a `UIBarButtonItem to apply the actual editing."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerApplyButtonItem(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerapplybuttonitem(_:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerDidChangePolygon(_:)":{"role":"symbol","title":"imageEditingViewControllerDidChangePolygon(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Informs the delegate that the image editing view controllers polygon was changed by user interaction."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerDidChangePolygon(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerdidchangepolygon(_:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)":{"navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:"}],"role":"symbol","title":"imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Asks the delegate for a "},{"type":"codeVoice","code":"UIBarButtonItem"},{"type":"text","text":" to for rotating the image counter-clockwise."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerrotatecounterclockwisetoolbaritem(_:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingViewController":{"role":"symbol","title":"SBSDKUICroppingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICroppingViewController"}],"abstract":[{"type":"text","text":"A highly customizable view controller to edit a pages polygon or the page’s orientation."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingViewController"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKImageEditingViewControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewController(_:didApplyChangesWith:croppedImage:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerApplyButtonItem(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerCancelButtonItem(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerDidCancelChanges(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerDidChangePolygon(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerRotateClockwiseToolbarItem(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarItemTintColor(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarStyle(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarTintColor(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerDidCancelChanges(_:)\/title","value":"imageEditingViewControllerDidCancelChanges:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerDidCancelChanges(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerDidCancelChanges:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewController(_:didApplyChangesWith:croppedImage:)\/title","value":"imageEditingViewController:didApplyChangesWith:croppedImage:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewController(_:didApplyChangesWith:croppedImage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewController:didApplyChangesWith:croppedImage:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerToolbarStyle(_:)\/title","value":"imageEditingViewControllerToolbarStyle:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerToolbarStyle(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerToolbarStyle:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/title","value":"SBSDKImageEditingViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerCancelButtonItem(_:)\/title","value":"imageEditingViewControllerCancelButtonItem:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerCancelButtonItem(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerCancelButtonItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerToolbarTintColor(_:)\/title","value":"imageEditingViewControllerToolbarTintColor:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerToolbarTintColor(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerToolbarTintColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerToolbarItemTintColor(_:)\/title","value":"imageEditingViewControllerToolbarItemTintColor:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerToolbarItemTintColor(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerToolbarItemTintColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerRotateClockwiseToolbarItem(_:)\/title","value":"imageEditingViewControllerRotateClockwiseToolbarItem:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerRotateClockwiseToolbarItem(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerRotateClockwiseToolbarItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate\/title","value":"SBSDKImageEditingViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerApplyButtonItem(_:)\/title","value":"imageEditingViewControllerApplyButtonItem:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerApplyButtonItem(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerApplyButtonItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerDidChangePolygon(_:)\/title","value":"imageEditingViewControllerDidChangePolygon:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerDidChangePolygon(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)\/title","value":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingViewController\/title","value":"SBSDKUICroppingViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUICroppingViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}