{"metadata":{"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageMetadata"}],"navigatorTitle":[{"text":"SBSDKImageMetadata","kind":"identifier"}],"title":"SBSDKImageMetadata","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageMetadata","symbolKind":"class","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"type":"conformsTo"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/init(with:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/ISOValue","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/altitude","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/aperture","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/digitalizationDate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/exposureTime","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/focalLength","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/focalLength35mm","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/imageHeight","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/imageWidth","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/latitude","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/lensMaker","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/lensModel","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/longitude","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/metadataDictionary","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/orientation","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/originalDate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/title"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageMetadata","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","abstract":[{"text":"Encapsulates image metadata, e.g. EXIF, TIFF, JFIF in a convenient way.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Use "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadataProcessor"},{"type":"text","text":" to extract metadata from and inject changed metadata into image data."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/altitude":{"title":"altitude","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/altitude","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"altitude","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/altitude","type":"topic","abstract":[{"type":"text","text":"The altitude of the location where the image was captured."}],"navigatorTitle":[{"kind":"identifier","text":"altitude"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/focalLength":{"navigatorTitle":[{"text":"focalLength","kind":"identifier"}],"kind":"symbol","title":"focalLength","type":"topic","abstract":[{"text":"The real focal length of the lens used to capture the image. Measured in millimeters. Readonly.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/focalLength","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/focallength","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"focalLength"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata":{"role":"symbol","title":"SBSDKImageMetadata","abstract":[{"text":"Encapsulates image metadata, e.g. EXIF, TIFF, JFIF in a convenient way.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Use "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadataProcessor"},{"type":"text","text":" to extract metadata from and inject changed metadata into image data."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKImageMetadata","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageMetadata","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/orientation":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/orientation","abstract":[{"text":"The orientation flag of the image.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"orientation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"orientation"}],"kind":"symbol","title":"orientation","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/orientation"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/title":{"type":"topic","title":"title","navigatorTitle":[{"text":"title","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/title","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"text":"The title of the image.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/title","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/imageHeight":{"title":"imageHeight","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageHeight"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"imageHeight"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The height of the image in pixels."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/imageHeight","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/imageheight"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/aperture":{"abstract":[{"text":"The f-stop number or aperture of the lens used to capture the image. Readonly.","type":"text"}],"navigatorTitle":[{"text":"aperture","kind":"identifier"}],"title":"aperture","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/aperture","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/aperture","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aperture","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/exposureTime":{"navigatorTitle":[{"text":"exposureTime","kind":"identifier"}],"kind":"symbol","title":"exposureTime","type":"topic","abstract":[{"type":"text","text":"The duration the sensor was exposed during capturing the image. Equals to 1.0 \/ shutter speed. Readonly."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/exposureTime","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/exposuretime","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"exposureTime"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/longitude":{"navigatorTitle":[{"text":"longitude","kind":"identifier"}],"kind":"symbol","title":"longitude","type":"topic","abstract":[{"text":"The longitude of the location where the image was captured.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/longitude","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/longitude","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"longitude"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/focalLength35mm":{"abstract":[{"text":"The 35mm equivalent focal length of the lens used to capture the image. Measured in millimeters. Readonly.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"focalLength35mm","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/focallength35mm","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"focalLength35mm","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"focalLength35mm","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/focalLength35mm","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","title":"init","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/init","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/init","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/originalDate":{"title":"originalDate","type":"topic","kind":"symbol","abstract":[{"text":"The date of when the image was captured.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/originaldate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"originalDate"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/originalDate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"originalDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/lensModel":{"type":"topic","abstract":[{"type":"text","text":"The model of the lens used to capture the image. Readonly."}],"title":"lensModel","navigatorTitle":[{"text":"lensModel","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/lensModel","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/lensmodel","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"lensModel","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/ISOValue":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/ISOValue","abstract":[{"text":"The ISO value used to capture the image. Readonly.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ISOValue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"ISOValue"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/isovalue","title":"ISOValue","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/init(with:)":{"navigatorTitle":[{"text":"initWithMetadataDictionary:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"abstract":[{"type":"text","text":"Creates a new  "},{"code":"SBSDKImageMetadata","type":"codeVoice"},{"text":" object or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":", if the metadata dictionary does not contain valid metadata."}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/init(with:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/init(with:)","title":"init(with:)","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/latitude":{"navigatorTitle":[{"text":"latitude","kind":"identifier"}],"kind":"symbol","title":"latitude","type":"topic","abstract":[{"type":"text","text":"The latitude of the location where the image was captured."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/latitude","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/latitude","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"latitude"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadataProcessor":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageMetadataProcessor"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadataProcessor","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}],"title":"SBSDKImageMetadataProcessor","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadataprocessor","kind":"symbol","abstract":[{"text":"Helper class to extract or inject image metadata, e.g. EXIF, TIFF, JFIF from  image data.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/digitalizationDate":{"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"digitalizationDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/digitalizationdate","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/digitalizationDate","navigatorTitle":[{"kind":"identifier","text":"digitalizationDate"}],"abstract":[{"text":"The date of when the image was digitized.","type":"text"}],"title":"digitalizationDate","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/metadataDictionary":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"metadataDictionary","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/metadatadictionary","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/metadataDictionary","abstract":[{"type":"text","text":"The raw metadata dictionary as it gets extracted from CGImageSourceCopyPropertiesAtIndex. Readonly."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"metadataDictionary"}],"title":"metadataDictionary"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.2.1"}],"type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/imageWidth":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/imagewidth","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/imageWidth","abstract":[{"text":"The width of the image in pixels.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"imageWidth","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"imageWidth"}],"title":"imageWidth"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/lensMaker":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/lensmaker","abstract":[{"type":"text","text":"The manufacturer of the lens used to capture the image. Readonly."}],"navigatorTitle":[{"text":"lensMaker","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/lensMaker","title":"lensMaker","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"lensMaker","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKImageMetadata","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"SBSDKImageMetadata"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKImageMetadata","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/ISOValue","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/altitude","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/aperture","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/digitalizationDate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/exposureTime","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/focalLength","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/focalLength35mm","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/imageHeight","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/imageWidth","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/latitude","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/lensMaker","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/lensModel","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/longitude","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/metadataDictionary","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/orientation","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/originalDate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/title"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/init","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/init(with:)"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageMetadata"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"altitude","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1altitude\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1altitude\/fragments","op":"replace","value":[{"text":"altitude","kind":"identifier"}]},{"value":"focalLength","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1focalLength\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1focalLength\/fragments","value":[{"text":"focalLength","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata\/title","value":"SBSDKImageMetadata"},{"value":[{"text":"SBSDKImageMetadata","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata\/fragments","op":"replace"},{"op":"replace","value":"orientation","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1orientation\/title"},{"value":[{"text":"orientation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1orientation\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1title\/title","value":"title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1title\/fragments","op":"replace","value":[{"kind":"identifier","text":"title"}]},{"value":"imageHeight","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1imageHeight\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1imageHeight\/fragments","value":[{"text":"imageHeight","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"aperture","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1aperture\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1aperture\/fragments","value":[{"kind":"identifier","text":"aperture"}]},{"value":"exposureTime","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1exposureTime\/title","op":"replace"},{"op":"replace","value":[{"text":"exposureTime","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1exposureTime\/fragments"},{"value":"longitude","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1longitude\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1longitude\/fragments","value":[{"kind":"identifier","text":"longitude"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1focalLength35mm\/title","value":"focalLength35mm"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1focalLength35mm\/fragments","op":"replace","value":[{"kind":"identifier","text":"focalLength35mm"}]},{"op":"replace","value":"originalDate","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1originalDate\/title"},{"value":[{"kind":"identifier","text":"originalDate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1originalDate\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1lensModel\/title","op":"replace","value":"lensModel"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1lensModel\/fragments","value":[{"kind":"identifier","text":"lensModel"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1ISOValue\/title","value":"ISOValue"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1ISOValue\/fragments","op":"replace","value":[{"text":"ISOValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1init(with:)\/title","value":"initWithMetadataDictionary:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithMetadataDictionary:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1init(with:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1latitude\/title","value":"latitude","op":"replace"},{"op":"replace","value":[{"text":"latitude","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1latitude\/fragments"},{"op":"replace","value":"SBSDKImageMetadataProcessor","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadataProcessor\/title"},{"value":[{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadataProcessor\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1digitalizationDate\/title","value":"digitalizationDate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1digitalizationDate\/fragments","value":[{"kind":"identifier","text":"digitalizationDate"}],"op":"replace"},{"op":"replace","value":"metadataDictionary","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1metadataDictionary\/title"},{"value":[{"text":"metadataDictionary","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1metadataDictionary\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1imageWidth\/title","value":"imageWidth","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1imageWidth\/fragments","op":"replace","value":[{"text":"imageWidth","kind":"identifier"}]},{"op":"replace","value":"lensMaker","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1lensMaker\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1lensMaker\/fragments","op":"replace","value":[{"text":"lensMaker","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}