{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewControllerDelegate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewControllerDelegate"],"type":"inheritedBy","title":"Inherited By"}],"metadata":{"navigatorTitle":[{"text":"SBSDKUIViewControllerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIViewControllerDelegate","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKUIViewControllerDelegate","symbolKind":"protocol","title":"SBSDKUIViewControllerDelegate","roleHeading":"Protocol"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewControllerDelegate\/viewControllerShouldCancel(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewControllerDelegate\/viewControllerShouldFinish(_:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontrollerdelegate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewControllerDelegate"},"abstract":[{"text":"The general delegate protocol for ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController","isActive":true},{"text":"-based classes.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIViewControllerDelegate"}]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingViewControllerDelegate":{"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewControllerDelegate","abstract":[{"type":"text","text":"Delegate protocol for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewController"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingViewControllerDelegate"}],"title":"SBSDKUICroppingViewControllerDelegate"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIViewControllerDelegate":{"abstract":[{"type":"text","text":"The general delegate protocol for "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController","isActive":true},{"text":"-based classes.","type":"text"}],"title":"SBSDKUIViewControllerDelegate","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontrollerdelegate","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKUIViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIViewControllerDelegate"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewControllerDelegate","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIViewControllerDelegate/viewControllerShouldFinish(_:)":{"required":true,"role":"symbol","abstract":[{"text":"Informs the delegate, that the ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController","isActive":true},{"text":" wants to finish.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewControllerShouldFinish","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIViewController","text":"SBSDKUIViewController","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"viewControllerShouldFinish(_:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewControllerDelegate\/viewControllerShouldFinish(_:)","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontrollerdelegate\/viewcontrollershouldfinish(_:)","navigatorTitle":[{"text":"viewControllerShouldFinish:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIViewController":{"navigatorTitle":[{"text":"SBSDKUIViewController","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontroller","title":"SBSDKUIViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController","abstract":[{"type":"text","text":"An abstract base class for RTU-UI view controllers."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIViewController","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.2.1"}],"type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIViewControllerDelegate/viewControllerShouldCancel(_:)":{"abstract":[{"type":"text","text":"Informs the delegate, that the "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController","type":"reference","isActive":true},{"text":" wants to cancel.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontrollerdelegate\/viewcontrollershouldcancel(_:)","title":"viewControllerShouldCancel(_:)","kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewControllerShouldCancel","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIViewController","text":"SBSDKUIViewController"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewControllerDelegate\/viewControllerShouldCancel(_:)","navigatorTitle":[{"kind":"identifier","text":"viewControllerShouldCancel:"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerViewController":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController","abstract":[],"kind":"symbol","title":"SBSDKUIDocumentScannerViewController","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerViewController":{"kind":"symbol","title":"SBSDKUIFinderDocumentScannerViewController","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"abstract":[{"text":"A highly customizable camera-based view controller to scan a single documents of a certain aspect ratio.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerViewControllerDelegate":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontrollerdelegate","kind":"symbol","role":"symbol","title":"SBSDKUIDocumentScannerViewControllerDelegate","abstract":[{"type":"text","text":"Delegate protocol for "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIDocumentScannerViewControllerDelegate","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingViewController":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingviewcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUICroppingViewController","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A highly customizable view controller to edit a pages polygon or the page’s orientation."}],"type":"topic","title":"SBSDKUICroppingViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewController"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerViewControllerDelegate":{"title":"SBSDKUIFinderDocumentScannerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewControllerDelegate"}],"navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerViewControllerDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Delegate protocol for "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewControllerDelegate","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerviewcontrollerdelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKUIViewControllerDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUIViewControllerDelegate"}]},{"op":"replace","value":[{"text":"SBSDKUIViewControllerDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewControllerDelegate\/viewControllerShouldCancel(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewControllerDelegate\/viewControllerShouldFinish(_:)"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewControllerDelegate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewControllerDelegate"],"type":"inheritedBy","title":"Inherited By"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIViewControllerDelegate","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"SBSDKUICroppingViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUICroppingViewControllerDelegate"}]},{"value":"SBSDKUIViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUIViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewControllerDelegate~1viewControllerShouldFinish(_:)\/title","value":"viewControllerShouldFinish:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewControllerDelegate~1viewControllerShouldFinish(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewControllerShouldFinish:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewController\/title","value":"SBSDKUIViewController","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUIViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewControllerDelegate~1viewControllerShouldCancel(_:)\/title","op":"replace","value":"viewControllerShouldCancel:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewControllerDelegate~1viewControllerShouldCancel(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewControllerShouldCancel:"}]},{"op":"replace","value":"SBSDKUIDocumentScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewController\/fragments","value":[{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerViewController\/title","value":"SBSDKUIFinderDocumentScannerViewController","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerViewController\/fragments"},{"value":"SBSDKUIDocumentScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewControllerDelegate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewControllerDelegate\/fragments","value":[{"text":"SBSDKUIDocumentScannerViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUICroppingViewController","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingViewController\/fragments","value":[{"text":"SBSDKUICroppingViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerViewControllerDelegate\/title","value":"SBSDKUIFinderDocumentScannerViewControllerDelegate"},{"value":[{"text":"SBSDKUIFinderDocumentScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerViewControllerDelegate\/fragments"}]}]}