{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"title":"SBSDKTIFFImageWriter","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriter","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"abstract":[{"text":"A class that converts images to (multipage) TIFF images.","type":"text"},{"text":" ","type":"text"},{"text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"When passing an encrypter the generated TIFF images will be encrypted."}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/init()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/init(parameters:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/init(parameters:encrypter:)"]},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/encrypter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/parameters"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/tiffData(from:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/tiffData(from:completion:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(document:toFile:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(document:toFile:completion:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(from:imageDecrypter:toFile:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(from:imageDecrypter:toFile:completion:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(scannedDocument:toFile:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(scannedDocument:toFile:completion:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(with:toFile:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(with:toFile:completion:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(document:toFile:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(from:imageDecrypter:toFile:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(scannedDocument:toFile:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(with:toFile:)"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter":{"role":"symbol","navigatorTitle":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter","title":"SBSDKTIFFImageWriter","abstract":[{"text":"A class that converts images to (multipage) TIFF images.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc."},{"type":"text","text":" "},{"text":"When passing an encrypter the generated TIFF images will be encrypted.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTIFFImageWriter"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/encrypter":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"encrypter","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/encrypter","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/encrypter","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"encrypter","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The encrypter used to write TIFF images. Readonly, optional."}],"title":"encrypter"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFF(scannedDocument:toFile:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiff(scanneddocument:tofile:)","role":"symbol","title":"writeTIFF(scannedDocument:toFile:)","navigatorTitle":[{"text":"writeTIFFWithScannedDocument:toFile:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(scannedDocument:toFile:)","abstract":[{"type":"text","text":"Synchronously converts the scanned document to a multipage-TIFF file and writes it to the specified URL."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"writeTIFF","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"scannedDocument"},{"text":": ","kind":"text"},{"text":"SBSDKScannedDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedDocument"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"toFile"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/parameters":{"abstract":[{"text":"The TIFF writing parameters used to write TIFF images. Readonly.","type":"text"}],"title":"parameters","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parameters"},{"kind":"text","text":": "},{"text":"SBSDKTIFFImageWriterParameters","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriterParameters","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"parameters"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/parameters","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/parameters","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFF(scannedDocument:toFile:completion:)":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"writeTIFFWithScannedDocument:toFile:completion:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiff(scanneddocument:tofile:completion:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(scannedDocument:toFile:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"writeTIFF","kind":"identifier"},{"kind":"text","text":"("},{"text":"scannedDocument","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKScannedDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedDocument"},{"kind":"text","text":", "},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?) -> ())"}],"abstract":[{"type":"text","text":"Asynchronously converts the scanned document to a multipage-TIFF file and writes it to the specified URL."}],"title":"writeTIFF(scannedDocument:toFile:completion:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFF(from:imageDecrypter:toFile:completion:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiff(from:imagedecrypter:tofile:completion:)","role":"symbol","title":"writeTIFF(from:imageDecrypter:toFile:completion:)","navigatorTitle":[{"text":"writeTIFFFrom:imageDecrypter:toFile:completion:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(from:imageDecrypter:toFile:completion:)","abstract":[{"type":"text","text":"Asynchronously converts the images at the given image URLs to a multipage-TIFF file and writes it to the specified URL."}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"writeTIFF","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"imageDecrypter"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"toFile"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?) -> ())","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFF(with:toFile:)":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"writeTIFFWith:toFile:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiff(with:tofile:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(with:toFile:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeTIFF"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"], ","kind":"text"},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"Synchronously converts the given images to a multipage-TIFF file and writes it to the specified URL.","type":"text"}],"title":"writeTIFF(with:toFile:)"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFF(from:imageDecrypter:toFile:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiff(from:imagedecrypter:tofile:)","role":"symbol","title":"writeTIFF(from:imageDecrypter:toFile:)","navigatorTitle":[{"text":"writeTIFFFrom:imageDecrypter:toFile:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(from:imageDecrypter:toFile:)","abstract":[{"text":"Synchronously converts the images at the given image URLs to a multipage-TIFF file and writes it to the specified URL.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"writeTIFF"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"imageDecrypter"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier","text":"SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"toFile"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/init(parameters:encrypter:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/init(parameters:encrypter:)","kind":"symbol","type":"topic","title":"init(parameters:encrypter:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parameters","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriterParameters","text":"SBSDKTIFFImageWriterParameters"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initializes a new TIFF image writer with the specified parameters and encrypter."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/init(parameters:encrypter:)","role":"symbol","navigatorTitle":[{"text":"initWithParameters:encrypter:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFF(document:toFile:completion:)":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"writeTIFFWithDocument:toFile:completion:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiff(document:tofile:completion:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(document:toFile:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"writeTIFF"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"toFile","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?) -> ())","kind":"text"}],"abstract":[{"text":"Asynchronously converts the document to a multipage-TIFF file and writes it to the specified URL.","type":"text"}],"title":"writeTIFF(document:toFile:completion:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.1.1","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/init(parameters:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/init(parameters:)","role":"symbol","title":"init(parameters:)","navigatorTitle":[{"kind":"identifier","text":"initWithParameters:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/init(parameters:)","abstract":[{"text":"Initializes a new TIFF image writer with the specified parameters and no encrypter.","type":"text"}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parameters"},{"text":": ","kind":"text"},{"text":"SBSDKTIFFImageWriterParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriterParameters"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/init()":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/init()","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Initializes a new TIFF image writer with no encrypter, using the default parameters for binarized images."}],"title":"init()"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFFAsync(from:imageDecrypter:toFile:)":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"writeTIFFAsyncFrom:imageDecrypter:toFile:completionHandler:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiffasync(from:imagedecrypter:tofile:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(from:imageDecrypter:toFile:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"writeTIFFAsync"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"imageDecrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"toFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Asynchronously converts the images at the given image URLs to a multipage-TIFF file and writes it to the specified URL."}],"title":"writeTIFFAsync(from:imageDecrypter:toFile:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFF(with:toFile:completion:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"writeTIFFWith:toFile:completion:"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiff(with:tofile:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeTIFF"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"], ","kind":"text"},{"text":"toFile","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?) -> ())","kind":"text"}],"title":"writeTIFF(with:toFile:completion:)","abstract":[{"type":"text","text":"Asynchronously converts the given images to a multipage-TIFF file and writes it to the specified URL."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(with:toFile:completion:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFFAsync(scannedDocument:toFile:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"writeTIFFAsync","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scannedDocument"},{"kind":"text","text":": "},{"text":"SBSDKScannedDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedDocument"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"toFile"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?) "},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiffasync(scanneddocument:tofile:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(scannedDocument:toFile:)","kind":"symbol","abstract":[{"text":"Asynchronously converts the scanned document to a multipage-TIFF file and writes it to the specified URL.","type":"text"}],"navigatorTitle":[{"text":"writeTIFFAsyncWithScannedDocument:toFile:completionHandler:","kind":"identifier"}],"title":"writeTIFFAsync(scannedDocument:toFile:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFFAsync(document:toFile:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"writeTIFFAsync","kind":"identifier"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKDocument","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocument","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"toFile"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(document:toFile:)","role":"symbol","abstract":[{"text":"Asynchronously converts the document to a multipage-TIFF file and writes it to the specified URL.","type":"text"}],"title":"writeTIFFAsync(document:toFile:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiffasync(document:tofile:)","navigatorTitle":[{"kind":"identifier","text":"writeTIFFAsyncWithDocument:toFile:completionHandler:"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/tiffData(from:)":{"abstract":[{"type":"text","text":"Synchronously converts the given images into multipage-TIFF data and returns it."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/tiffdata(from:)","navigatorTitle":[{"text":"tiffDataFrom:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/tiffData(from:)","kind":"symbol","role":"symbol","title":"tiffData(from:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tiffData"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFFAsync(with:toFile:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"writeTIFFAsync","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"], ","kind":"text"},{"text":"toFile","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"writeTIFFAsyncWith:toFile:completionHandler:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Asynchronously converts the given images to a multipage-TIFF file and writes it to the specified URL.","type":"text"}],"title":"writeTIFFAsync(with:toFile:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(with:toFile:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiffasync(with:tofile:)","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFF(document:toFile:)":{"role":"symbol","abstract":[{"type":"text","text":"Synchronously converts the document to a multipage-TIFF file and writes it to the specified URL."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"writeTIFF","kind":"identifier"},{"kind":"text","text":"("},{"text":"document","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocument","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocument"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"toFile"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(document:toFile:)","title":"writeTIFF(document:toFile:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiff(document:tofile:)","type":"topic","navigatorTitle":[{"text":"writeTIFFWithDocument:toFile:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/tiffData(from:completion:)":{"abstract":[{"type":"text","text":"Asynchronously converts the given images into multipage-TIFF data and returns it."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/tiffdata(from:completion:)","navigatorTitle":[{"kind":"identifier","text":"tiffDataFrom:completion:"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/tiffData(from:completion:)","kind":"symbol","role":"symbol","title":"tiffData(from:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tiffData","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"], "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?) -> ())"}]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKTIFFImageWriter"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKTIFFImageWriter"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/encrypter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/parameters"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/init()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/init(parameters:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/init(parameters:encrypter:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/tiffData(from:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/tiffData(from:completion:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(document:toFile:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(document:toFile:completion:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(from:imageDecrypter:toFile:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(from:imageDecrypter:toFile:completion:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(scannedDocument:toFile:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(scannedDocument:toFile:completion:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(with:toFile:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFF(with:toFile:completion:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(document:toFile:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(from:imageDecrypter:toFile:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(scannedDocument:toFile:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(with:toFile:)"]}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTIFFImageWriter"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKTIFFImageWriter","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriter"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/navigatorTitle","op":"replace","value":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1encrypter\/title","value":"encrypter"},{"value":[{"kind":"identifier","text":"encrypter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1encrypter\/fragments","op":"replace"},{"op":"replace","value":"writeTIFFWithScannedDocument:toFile:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(scannedDocument:toFile:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(scannedDocument:toFile:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"writeTIFFWithScannedDocument:toFile:","kind":"identifier"}]},{"value":"parameters","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1parameters\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1parameters\/fragments","value":[{"text":"parameters","kind":"identifier"}],"op":"replace"},{"value":"writeTIFFWithScannedDocument:toFile:completion:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(scannedDocument:toFile:completion:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"writeTIFFWithScannedDocument:toFile:completion:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(scannedDocument:toFile:completion:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(from:imageDecrypter:toFile:completion:)\/title","value":"writeTIFFFrom:imageDecrypter:toFile:completion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(from:imageDecrypter:toFile:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writeTIFFFrom:imageDecrypter:toFile:completion:"}]},{"value":"writeTIFFWith:toFile:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(with:toFile:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writeTIFFWith:toFile:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(with:toFile:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(from:imageDecrypter:toFile:)\/title","op":"replace","value":"writeTIFFFrom:imageDecrypter:toFile:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(from:imageDecrypter:toFile:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"writeTIFFFrom:imageDecrypter:toFile:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1init(parameters:encrypter:)\/title","value":"initWithParameters:encrypter:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithParameters:encrypter:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1init(parameters:encrypter:)\/fragments"},{"value":"writeTIFFWithDocument:toFile:completion:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(document:toFile:completion:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"writeTIFFWithDocument:toFile:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(document:toFile:completion:)\/fragments","op":"replace"},{"value":"initWithParameters:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1init(parameters:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1init(parameters:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithParameters:","kind":"identifier"}]},{"value":"init","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1init()\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(from:imageDecrypter:toFile:)\/title","value":"writeTIFFAsyncFrom:imageDecrypter:toFile:completionHandler:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writeTIFFAsyncFrom:imageDecrypter:toFile:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(from:imageDecrypter:toFile:)\/fragments"},{"value":"writeTIFFWith:toFile:completion:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(with:toFile:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"writeTIFFWith:toFile:completion:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(with:toFile:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(scannedDocument:toFile:)\/title","value":"writeTIFFAsyncWithScannedDocument:toFile:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(scannedDocument:toFile:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"writeTIFFAsyncWithScannedDocument:toFile:completionHandler:","kind":"identifier"}]},{"value":"writeTIFFAsyncWithDocument:toFile:completionHandler:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(document:toFile:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(document:toFile:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"writeTIFFAsyncWithDocument:toFile:completionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1tiffData(from:)\/title","value":"tiffDataFrom:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tiffDataFrom:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1tiffData(from:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(with:toFile:)\/title","op":"replace","value":"writeTIFFAsyncWith:toFile:completionHandler:"},{"value":[{"text":"- ","kind":"text"},{"text":"writeTIFFAsyncWith:toFile:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(with:toFile:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(document:toFile:)\/title","op":"replace","value":"writeTIFFWithDocument:toFile:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"writeTIFFWithDocument:toFile:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFF(document:toFile:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1tiffData(from:completion:)\/title","value":"tiffDataFrom:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tiffDataFrom:completion:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1tiffData(from:completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}