{"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)UIViewController"],"kind":"relationships"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICameraViewController","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewController"],"title":"Inherited By","kind":"relationships","type":"inheritedBy"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s8SendableP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIContentContainer","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIStateRestoring","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIUserActivityRestoring"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController"},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIViewController"}],"role":"symbol","symbolKind":"class","title":"SBSDKUIViewController","roleHeading":"Class","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIViewController"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"An abstract base class for RTU-UI view controllers.","type":"text"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/shouldHideHomeIndicator","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/shouldShowStatusBar","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/statusBarStyle"]},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/dismiss(cancelled:)"],"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIViewController","kind":"identifier"}]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"text":"Overview","type":"heading"},{"type":"aside","name":"Important","style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Do not use or subclass."}]}]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCoding","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIViewController/prefersStatusBarHidden":{"type":"topic","abstract":[],"title":"prefersStatusBarHidden","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontroller\/prefersstatusbarhidden","kind":"symbol","role":"symbol","fragments":[{"text":"prefersStatusBarHidden","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/prefersStatusBarHidden"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIViewController/initWithCoder:":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontroller\/initwithcoder:","title":"initWithCoder:","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/initWithCoder:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIViewController/shouldHideHomeIndicator":{"navigatorTitle":[{"text":"shouldHideHomeIndicator","kind":"identifier"}],"type":"topic","title":"shouldHideHomeIndicator","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/shouldHideHomeIndicator","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontroller\/shouldhidehomeindicator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldHideHomeIndicator"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","abstract":[{"text":"If set to ","type":"text"},{"code":"True","type":"codeVoice"},{"text":", the receiver automatically hides the home indicator.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIContentContainer","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIViewController/shouldShowStatusBar":{"navigatorTitle":[{"text":"shouldShowStatusBar","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":", the receiver shows the status bar. Otherwise the status bar is hidden."}],"title":"shouldShowStatusBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldShowStatusBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontroller\/shouldshowstatusbar","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/shouldShowStatusBar"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIViewController/dismiss(cancelled:)":{"title":"dismiss(cancelled:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dismiss","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cancelled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/dismiss(cancelled:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontroller\/dismiss(cancelled:)","navigatorTitle":[{"kind":"identifier","text":"dismiss:"}],"kind":"symbol","abstract":[{"type":"text","text":"Dismisses the receiver if possible. Subclasses should override here and call its delegates."}]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAppearanceContainer"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICameraViewController":{"title":"SBSDKUICameraViewController","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICameraViewController"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICameraViewController","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicameraviewcontroller","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICameraViewController"}],"kind":"symbol","abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController"},{"type":"text","text":" subclass which adds support for enabled and disabled camera permission."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingViewController":{"title":"SBSDKUICroppingViewController","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingViewController","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingviewcontroller","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingViewController"}],"kind":"symbol","abstract":[{"type":"text","text":"A highly customizable view controller to edit a pages polygon or the page’s orientation."}]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIViewController/prefersHomeIndicatorAutoHidden":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/prefersHomeIndicatorAutoHidden","role":"symbol","title":"prefersHomeIndicatorAutoHidden","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontroller\/prefershomeindicatorautohidden","fragments":[{"kind":"identifier","text":"prefersHomeIndicatorAutoHidden"}],"abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIViewController":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController","role":"symbol","title":"SBSDKUIViewController","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"An abstract base class for RTU-UI view controllers."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIViewController/supportedInterfaceOrientations":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/supportedInterfaceOrientations","role":"symbol","title":"supportedInterfaceOrientations","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontroller\/supportedinterfaceorientations","fragments":[{"kind":"identifier","text":"supportedInterfaceOrientations"}],"abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIViewController/preferredStatusBarStyle":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/preferredStatusBarStyle","role":"symbol","title":"preferredStatusBarStyle","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontroller\/preferredstatusbarstyle","fragments":[{"kind":"identifier","text":"preferredStatusBarStyle"}],"abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIViewController/shouldAutorotate":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/shouldAutorotate","role":"symbol","title":"shouldAutorotate","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontroller\/shouldautorotate","fragments":[{"kind":"identifier","text":"shouldAutorotate"}],"abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s8SendableP","title":"Swift.Sendable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)UIViewController":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)UIViewController","title":"UIViewController"},"doc://net.doo.ScanbotDocumentScannerSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIViewController/statusBarStyle":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/statusBarStyle","role":"symbol","title":"statusBarStyle","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontroller\/statusbarstyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statusBarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle","text":"UIStatusBarStyle"}],"navigatorTitle":[{"text":"statusBarStyle","kind":"identifier"}],"abstract":[{"type":"text","text":"The style of the status bar."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"SBSDKUIViewController","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKUIViewController","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIViewController"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/preferredStatusBarStyle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/prefersHomeIndicatorAutoHidden","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/prefersStatusBarHidden","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/shouldAutorotate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/shouldHideHomeIndicator","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/shouldShowStatusBar","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/statusBarStyle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/supportedInterfaceOrientations"]},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/dismiss(cancelled:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController\/initWithCoder:"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)UIViewController"]},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICameraViewController","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKUIViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewController~1shouldHideHomeIndicator\/title","value":"shouldHideHomeIndicator"},{"value":[{"text":"shouldHideHomeIndicator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewController~1shouldHideHomeIndicator\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewController~1shouldShowStatusBar\/title","op":"replace","value":"shouldShowStatusBar"},{"value":[{"kind":"identifier","text":"shouldShowStatusBar"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewController~1shouldShowStatusBar\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewController~1dismiss(cancelled:)\/title","op":"replace","value":"dismiss:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dismiss:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewController~1dismiss(cancelled:)\/fragments"},{"value":"SBSDKUICameraViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICameraViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICameraViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUICameraViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingViewController\/title","value":"SBSDKUICroppingViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUICroppingViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewController\/title","value":"SBSDKUIViewController","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewController\/fragments"},{"value":"statusBarStyle","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewController~1statusBarStyle\/title","op":"replace"},{"value":[{"text":"statusBarStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewController~1statusBarStyle\/fragments","op":"replace"}]}]}