{"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum\/hashValue"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum\/hash(into:)"]}],"metadata":{"title":"RawRepresentable Implementations","roleHeading":"API Collection","modules":[{"name":"ScanbotSDK"}],"role":"collectionGroup"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum"]]},"kind":"article","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfinderview\/style-swift.enum\/rawrepresentable-implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView":{"navigatorTitle":[{"text":"SBSDKFinderView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfinderview","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","abstract":[{"text":"A ","type":"text"},{"code":"UIView","type":"codeVoice"},{"text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio.","type":"text"}],"title":"SBSDKFinderView","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/Style-swift.enum":{"kind":"symbol","abstract":[{"type":"text","text":"The enum that defines the drawing styles of the finder view."}],"title":"SBSDKFinderView.Style","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum","url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/style-swift.enum","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Style"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/Style-swift.enum/hashValue":{"kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/style-swift.enum\/hashvalue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"hashValue","type":"topic","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum\/hashValue"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/Style-swift.enum/hash(into:)":{"kind":"symbol","role":"symbol","title":"hash(into:)","url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/style-swift.enum\/hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"abstract":[],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum\/hash(into:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/title","value":"SBSDKFinderView","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/fragments","value":[{"kind":"identifier","text":"SBSDKFinderView"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFinderView"}],"op":"replace"}]}]}