{"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultParametricPageFilter"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter"},{"kind":"text","text":"]?"}]}]},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Defaults to ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration\/defaultparametricpagefilter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration\/defaultparametricpagefilter"]}],"abstract":[{"type":"text","text":"The default parametric filters for new documents pages."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"defaultParametricPageFilter"}],"title":"defaultParametricPageFilter","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultParametricPageFilter"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"text":"]?","kind":"text"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerBehaviorConfiguration(py)defaultParametricPageFilter","platforms":[]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration\/defaultParametricPageFilter","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKParametricFilter","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"title":"SBSDKParametricFilter","abstract":[{"type":"text","text":"Base class for all parametric filters."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerBehaviorConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}],"deprecated":true,"kind":"symbol","title":"SBSDKUIDocumentScannerBehaviorConfiguration","abstract":[{"type":"text","text":"Configuration for the behavior of the document scanning screen."}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerBehaviorConfiguration/defaultParametricPageFilter":{"role":"symbol","type":"topic","deprecated":true,"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration\/defaultParametricPageFilter","abstract":[{"type":"text","text":"The default parametric filters for new documents pages."}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration\/defaultparametricpagefilter","navigatorTitle":[{"text":"defaultParametricPageFilter","kind":"identifier"}],"title":"defaultParametricPageFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultParametricPageFilter"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter"},{"kind":"text","text":"]?"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"defaultParametricPageFilter","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultParametricPageFilter"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKParametricFilter *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"defaultParametricPageFilter"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title","value":"SBSDKParametricFilter","op":"replace"},{"op":"replace","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/title","op":"replace","value":"SBSDKUIDocumentScannerBehaviorConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration~1defaultParametricPageFilter\/title","value":"defaultParametricPageFilter"},{"op":"replace","value":[{"text":"defaultParametricPageFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration~1defaultParametricPageFilter\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}