{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult\/verticalLinesNormalized","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult"]]},"sections":[],"kind":"symbol","abstract":[{"text":"Normalized vertical lines in image space.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"verticalLinesNormalized","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult(py)verticalLinesNormalized","symbolKind":"property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","title":"verticalLinesNormalized","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verticalLinesNormalized","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKLineSegmentFloat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentFloat"},{"text":"]","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult\/verticallinesnormalized"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult\/verticallinesnormalized"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"verticalLinesNormalized","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegmentFloat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentFloat","text":"SBSDKLineSegmentFloat"},{"kind":"text","text":"]"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionResult/verticalLinesNormalized":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult\/verticalLinesNormalized","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult\/verticallinesnormalized","type":"topic","navigatorTitle":[{"kind":"identifier","text":"verticalLinesNormalized"}],"abstract":[{"type":"text","text":"Normalized vertical lines in image space."}],"kind":"symbol","role":"symbol","title":"verticalLinesNormalized","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalLinesNormalized"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKLineSegmentFloat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentFloat"},{"text":"]","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionResult":{"navigatorTitle":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult","title":"SBSDKDocumentDetectionResult","abstract":[{"text":"Result of the document contour detection.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegmentFloat":{"type":"topic","title":"SBSDKLineSegmentFloat","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegmentfloat","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegmentFloat","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLineSegmentFloat"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegmentFloat"}],"abstract":[{"text":"Represents a line segment in 2D space.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"verticalLinesNormalized","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"verticalLinesNormalized"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSArray<SBSDKLineSegmentFloat *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"verticalLinesNormalized","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"verticalLinesNormalized","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult~1verticalLinesNormalized\/title","op":"replace"},{"op":"replace","value":[{"text":"verticalLinesNormalized","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult~1verticalLinesNormalized\/fragments"},{"op":"replace","value":"SBSDKDocumentDetectionResult","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}]},{"op":"replace","value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentFloat\/title","value":"SBSDKLineSegmentFloat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentFloat\/fragments","value":[{"text":"SBSDKLineSegmentFloat","kind":"identifier"}]},{"value":[{"text":"SBSDKLineSegmentFloat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentFloat\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}