{"sections":[],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method","title":"initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Palette(im)initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithSbColorPrimary:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sbColorPrimary","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorPrimaryDisabled:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sbColorPrimaryDisabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorNegative:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sbColorNegative","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorPositive:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sbColorPositive","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorWarning:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sbColorWarning","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorSecondary:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sbColorSecondary","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorSecondaryDisabled:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sbColorSecondaryDisabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorOnPrimary:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sbColorOnPrimary","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorOnSecondary:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sbColorOnSecondary","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorSurface:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sbColorSurface","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorOutline:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sbColorOutline","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorOnSurfaceVariant:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sbColorOnSurfaceVariant","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorOnSurface:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sbColorOnSurface","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorSurfaceLow:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sbColorSurfaceLow","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorSurfaceHigh:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sbColorSurfaceHigh","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorModalOverlay:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sbColorModalOverlay","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:","interfaceLanguage":"occ"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/initwithsbcolorprimary:sbcolorprimarydisabled:sbcolornegative:sbcolorpositive:sbcolorwarning:sbcolorsecondary:sbcolorsecondarydisabled:sbcoloronprimary:sbcoloronsecondary:sbcolorsurface:sbcoloroutline:sbcoloronsurfacevariant:sbcoloronsurfac-8ll73"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:"}],"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:","title":"initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/initwithsbcolorprimary:sbcolorprimarydisabled:sbcolornegative:sbcolorpositive:sbcolorwarning:sbcolorsecondary:sbcolorsecondarydisabled:sbcoloronprimary:sbcoloronsecondary:sbcolorsurface:sbcoloroutline:sbcoloronsurfacevariant:sbcoloronsurfac-8ll73","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette":{"title":"SBSDKUI2Palette","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2Palette","kind":"identifier"}],"abstract":[{"type":"text","text":"Value palette describing the colors of the scanner screens."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Palette","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Color":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","type":"topic","role":"symbol","title":"SBSDKUI2Color","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2color"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2Palette","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette\/title","op":"replace"},{"value":[{"text":"SBSDKUI2Palette","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Palette"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/title","op":"replace"},{"value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/navigatorTitle","op":"replace"}]}]}