{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarization"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarization\/enabled","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbinarization\/enabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbinarization\/enabled"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabled","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKBinarization.enabled","role":"symbol","roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarizationEnabled"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabled","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKBinarization@SBSDKBinarizationEnabled"},"abstract":[{"type":"text","text":"Binarize the image. Image will be stored as a 1-bit TIFF. If the input image is not black-and-white, a simple"},{"text":" ","type":"text"},{"type":"text","text":"thresholding is applied."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBinarization":{"role":"symbol","abstract":[{"type":"text","text":"Binarization behavior to apply when adding pages to a TIFF."}],"title":"SBSDKBinarization","navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarization"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarization","url":"\/documentation\/scanbotsdk\/sbsdkbinarization","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBinarization"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBinarization/enabled":{"url":"\/documentation\/scanbotsdk\/sbsdkbinarization\/enabled","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabled","kind":"identifier"}],"kind":"symbol","title":"SBSDKBinarization.enabled","abstract":[{"type":"text","text":"Binarize the image. Image will be stored as a 1-bit TIFF. If the input image is not black-and-white, a simple"},{"text":" ","type":"text"},{"text":"thresholding is applied.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarizationEnabled"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarization\/enabled"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKBinarizationEnabled","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"SBSDKBinarizationEnabled","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKBinarizationEnabled"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarization\/title","value":"SBSDKBinarization","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBinarization"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarization\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarization\/navigatorTitle","value":[{"text":"SBSDKBinarization","kind":"identifier"}],"op":"replace"},{"value":"SBSDKBinarizationEnabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarization~1enabled\/title"},{"value":[{"text":"SBSDKBinarizationEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarization~1enabled\/fragments","op":"replace"}]}]}