{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"finderTextHintColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Defaults to white color.","type":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerUIConfiguration"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2MRZScannerViewController instead.","type":"text"}],"type":"paragraph"}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerUIConfiguration(py)finderTextHintColor","navigatorTitle":[{"kind":"identifier","text":"finderTextHintColor"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"finderTextHintColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"finderTextHintColor","role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"platforms":[],"roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerUIConfiguration\/finderTextHintColor","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscanneruiconfiguration\/findertexthintcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscanneruiconfiguration\/findertexthintcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Foreground color of the description label.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerUIConfiguration/finderTextHintColor":{"title":"finderTextHintColor","type":"topic","navigatorTitle":[{"kind":"identifier","text":"finderTextHintColor"}],"deprecated":true,"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerUIConfiguration\/finderTextHintColor","abstract":[{"text":"Foreground color of the description label.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finderTextHintColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimrzscanneruiconfiguration\/findertexthintcolor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerUIConfiguration":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMRZScannerUIConfiguration"}],"title":"SBSDKUIMRZScannerUIConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIMRZScannerUIConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerUIConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscanneruiconfiguration","deprecated":true,"abstract":[{"type":"text","text":"Configuration for user interface of the scanner screens for machine-readable zones."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"finderTextHintColor"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"finderTextHintColor","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" * ","kind":"text"},{"text":"finderTextHintColor","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"finderTextHintColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerUIConfiguration~1finderTextHintColor\/title"},{"value":[{"text":"finderTextHintColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerUIConfiguration~1finderTextHintColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerUIConfiguration\/title","value":"SBSDKUIMRZScannerUIConfiguration"},{"value":[{"text":"SBSDKUIMRZScannerUIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerUIConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIMRZScannerUIConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerUIConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}