{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"beginStreamingDecryptWithContext:error:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAESGCMEncrypter(im)beginStreamingDecryptWithContext:error:","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"beginStreamingDecryptWithContext:error:"}],"title":"beginStreamingDecryptWithContext:error:","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter\/beginStreamingDecryptWithContext:error:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"beginStreamingDecryptWithContext:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"context"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter\/beginstreamingdecryptwithcontext:error:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESGCMEncrypter":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter","title":"SBSDKAESGCMEncrypter","type":"topic","navigatorTitle":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"abstract":[{"type":"text","text":"A data encrypter implementing the AES128-GCM and AES256-GCM standards, with a configurable encryption key provider."},{"type":"text","text":" "},{"type":"text","text":"Supports encryption and decryption of single data blocks as well as streaming data."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESGCMEncrypter/beginStreamingDecryptWithContext:error:":{"role":"symbol","type":"topic","title":"beginStreamingDecryptWithContext:error:","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter\/beginstreamingdecryptwithcontext:error:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"beginStreamingDecryptWithContext:error:"}],"navigatorTitle":[{"kind":"identifier","text":"beginStreamingDecryptWithContext:error:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter\/beginStreamingDecryptWithContext:error:","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter\/title","value":"SBSDKAESGCMEncrypter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter\/fragments","value":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter\/navigatorTitle","value":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}