{"abstract":[{"type":"text","text":"Informs the delegate, that the finder view has changed its finder rectangle."},{"type":"text","text":" "},{"type":"text","text":"Optional."}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderViewDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderViewDelegate\/finderView(_:didChangeRect:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderviewdelegate\/finderview(_:didchangerect:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderviewdelegate\/finderview(_:didchangerect:)"]}],"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finderView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKFinderView","kind":"typeIdentifier","text":"SBSDKFinderView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeRect"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":")"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKFinderViewDelegate(im)finderView:didChangeRect:","navigatorTitle":[{"kind":"identifier","text":"finderView:didChangeRect:"}],"role":"symbol","required":true,"symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"finderView(_:didChangeRect:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finderView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKFinderView","kind":"typeIdentifier","text":"SBSDKFinderView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeRect"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rect"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":")"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The finder view that changed its finder viewport rectangle. Can be "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", if it has been removed."}]}],"name":"view"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The new rectangle of the finder viewport.","type":"text"}]}],"name":"rect"}],"kind":"parameters"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderViewDelegate/finderView(_:didChangeRect:)":{"required":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderViewDelegate\/finderView(_:didChangeRect:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKFinderView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKFinderView"},{"text":", ","kind":"text"},{"text":"didChangeRect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"finderView:didChangeRect:","kind":"identifier"}],"abstract":[{"text":"Informs the delegate, that the finder view has changed its finder rectangle.","type":"text"},{"text":" ","type":"text"},{"text":"Optional.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderviewdelegate\/finderview(_:didchangerect:)","role":"symbol","type":"topic","title":"finderView(_:didChangeRect:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderViewDelegate":{"abstract":[{"text":"The delegate protocol for the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView","type":"reference"},{"text":" class.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"title":"SBSDKFinderViewDelegate","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderviewdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderViewDelegate","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView":{"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview","role":"symbol","title":"SBSDKFinderView","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFinderView"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKFinderView"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"finderView:didChangeRect:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"finderView:didChangeRect:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"finderView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKFinderView","text":"SBSDKFinderView","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"view"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeRect:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rect"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"view","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The finder view that changed its finder viewport rectangle. Can be "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", if it has been removed."}]}]},{"name":"rect","content":[{"inlineContent":[{"type":"text","text":"The new rectangle of the finder viewport."}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderViewDelegate~1finderView(_:didChangeRect:)\/title","op":"replace","value":"finderView:didChangeRect:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderViewDelegate~1finderView(_:didChangeRect:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"finderView:didChangeRect:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderViewDelegate\/title","op":"replace","value":"SBSDKFinderViewDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderViewDelegate\/fragments","op":"replace","value":[{"text":"SBSDKFinderViewDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderViewDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView\/title","op":"replace","value":"SBSDKFinderView"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView\/fragments","op":"replace","value":[{"text":"SBSDKFinderView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKFinderView"}]}]}]}