{"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"mode","navigatorTitle":[{"text":"mode","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2SheetMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2SheetMode"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet(py)mode"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2sheet\/mode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2sheet\/mode"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet\/mode","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet"]]},"abstract":[{"text":"Mode used for the preview for scanning multiple barcodes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is COLLAPSED_SHEET"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2SheetMode","text":"SBSDKUI2SheetMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetMode"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sheet":{"abstract":[{"text":"Configuration of the preview mode for scanning multiple barcodes.","type":"text"}],"title":"SBSDKUI2Sheet","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Sheet","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sheet","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Sheet"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sheet/mode":{"abstract":[{"type":"text","text":"Mode used for the preview for scanning multiple barcodes."},{"type":"text","text":" "},{"text":"Default is COLLAPSED_SHEET","type":"text"}],"title":"mode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet\/mode","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"mode"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2SheetMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2SheetMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sheet\/mode","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetMode":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the barcode result sheet’s default visibility state."}],"title":"SBSDKUI2SheetMode","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetmode","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2SheetMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetMode","navigatorTitle":[{"text":"SBSDKUI2SheetMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"mode","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"mode"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetMode","text":"SBSDKUI2SheetMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2SheetMode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mode"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/title","value":"SBSDKUI2Sheet"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/fragments","value":[{"text":"SBSDKUI2Sheet","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2Sheet"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet~1mode\/title","value":"mode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet~1mode\/fragments","value":[{"text":"mode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetMode\/title","op":"replace","value":"SBSDKUI2SheetMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetMode\/fragments","value":[{"text":"SBSDKUI2SheetMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetMode\/navigatorTitle","value":[{"text":"SBSDKUI2SheetMode","kind":"identifier"}],"op":"replace"}]}]}