{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerabottombar\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraBottomBar","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar","text":"SBSDKUI2CameraBottomBar"},{"kind":"text","text":" *) "},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"json"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar\/fromJsonWithJson:","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","title":"fromJsonWithJson:","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraBottomBar(cm)fromJsonWithJson:","symbolKind":"method","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraBottomBar/fromJsonWithJson:":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar\/fromJsonWithJson:","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkui2camerabottombar\/fromjsonwithjson:","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraBottomBar":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar","url":"\/documentation\/scanbotsdk\/sbsdkui2camerabottombar","role":"symbol","abstract":[{"type":"text","text":"Configuration of the bottom bar for the camera screen."}],"title":"SBSDKUI2CameraBottomBar"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2CameraBottomBar","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/fragments","value":[{"text":"SBSDKUI2CameraBottomBar","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUI2CameraBottomBar","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}