{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerabottombar\/init(importbutton:autosnappingmodebutton:manualsnappingmodebutton:shutterbutton:torchonbutton:torchoffbutton:previewbutton:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerabottombar\/init(importbutton:autosnappingmodebutton:manualsnappingmodebutton:shutterbutton:torchonbutton:torchoffbutton:previewbutton:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"importButton"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"text":" = SBSDKUI2BarButtonConfiguration(title: SBSDKUI2StyledText(visible: false, text: \"?cameraImportButtonTitle\",\n                                                                 color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                      isArgb: false)),\n                                       accessibilityDescription: \"?accessibilityDescriptionCameraImportButton\",\n                                       background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                      isArgb: false),\n                                                                           fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                    isArgb: false),\n                                                                           strokeWidth: 0.0),\n                                       icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                    isArgb: false))), ","kind":"text"},{"kind":"externalParam","text":"autoSnappingModeButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" = SBSDKUI2BarButtonConfiguration(title: SBSDKUI2StyledText(visible: false, text: \"?cameraAutoSnapButtonTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)),\n                                           accessibilityDescription: \"?accessibilityDescriptionCameraAutoSnapButton\",\n                                           background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                          isArgb: false),\n                                                                               fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                        isArgb: false),\n                                                                               strokeWidth: 0.0),\n                                           icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                        isArgb: false))), ","kind":"text"},{"text":"manualSnappingModeButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":" = SBSDKUI2BarButtonConfiguration(title: SBSDKUI2StyledText(visible: false,\n                                                                     text: \"?cameraManualSnapButtonTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)),\n                                           accessibilityDescription: \"?accessibilityDescriptionCameraManualSnapButton\",\n                                           background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                          isArgb: false),\n                                                                               fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                        isArgb: false),\n                                                                               strokeWidth: 0.0),\n                                           icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                        isArgb: false))), "},{"text":"shutterButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ShutterButton","text":"SBSDKUI2ShutterButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ShutterButton"},{"kind":"text","text":" = SBSDKUI2ShutterButton(accessibilityDescription: \"?accessibilityDescriptionCameraShutterButton\"), "},{"text":"torchOnButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration"},{"text":" = SBSDKUI2BarButtonConfiguration(title: SBSDKUI2StyledText(visible: false, text: \"?cameraTorchOnButtonTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)),\n                                           accessibilityDescription: \"?accessibilityDescriptionCameraTorchOnButton\",\n                                           background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                          isArgb: false),\n                                                                               fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                        isArgb: false),\n                                                                               strokeWidth: 0.0),\n                                           icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                        isArgb: false))), ","kind":"text"},{"kind":"externalParam","text":"torchOffButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":" = SBSDKUI2BarButtonConfiguration(title: SBSDKUI2StyledText(visible: false, text: \"?cameraTorchOffButtonTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)),\n                                           accessibilityDescription: \"?accessibilityDescriptionCameraTorchOffButton\",\n                                           background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                          isArgb: false),\n                                                                               fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                        isArgb: false),\n                                                                               strokeWidth: 0.0),\n                                           icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                        isArgb: false))), "},{"kind":"externalParam","text":"previewButton"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PreviewButton","text":"SBSDKUI2PreviewButton"},{"text":" = SBSDKUI2PagePreviewMode())","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"importButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":", ","kind":"text"},{"text":"autoSnappingModeButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"manualSnappingModeButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shutterButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ShutterButton","text":"SBSDKUI2ShutterButton","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"torchOnButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration"},{"text":", ","kind":"text"},{"text":"torchOffButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":", "},{"text":"previewButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PreviewButton","text":"SBSDKUI2PreviewButton","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"init","title":"init(importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:)","role":"symbol","navigatorTitle":[{"text":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraBottomBar(im)initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar\/init(importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarButtonConfiguration":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"role":"symbol","abstract":[{"text":"Configuration of the button located on a bar.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barbuttonconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"title":"SBSDKUI2BarButtonConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PreviewButton":{"navigatorTitle":[{"text":"SBSDKUI2PreviewButton","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the ‘preview’ button."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2previewbutton","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PreviewButton","kind":"identifier"}],"title":"SBSDKUI2PreviewButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraBottomBar":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar","url":"\/documentation\/scanbotsdk\/sbsdkui2camerabottombar","role":"symbol","abstract":[{"type":"text","text":"Configuration of the bottom bar for the camera screen."}],"title":"SBSDKUI2CameraBottomBar"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ShutterButton":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2shutterbutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ShutterButton","abstract":[{"type":"text","text":"Configuration of the ‘shutter’ button."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ShutterButton","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ShutterButton"}],"role":"symbol","title":"SBSDKUI2ShutterButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraBottomBar/init(importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar\/init(importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:)","abstract":[],"title":"init(importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2camerabottombar\/init(importbutton:autosnappingmodebutton:manualsnappingmodebutton:shutterbutton:torchonbutton:torchoffbutton:previewbutton:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"importButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":", "},{"text":"autoSnappingModeButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"manualSnappingModeButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration"},{"text":", ","kind":"text"},{"text":"shutterButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2ShutterButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ShutterButton"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"torchOnButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"torchOffButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"previewButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2PreviewButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PreviewButton"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithImportButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"importButton"},{"kind":"text","text":" "},{"text":"autoSnappingModeButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"autoSnappingModeButton"},{"kind":"text","text":" "},{"text":"manualSnappingModeButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"manualSnappingModeButton"},{"text":" ","kind":"text"},{"text":"shutterButton:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ShutterButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ShutterButton","text":"SBSDKUI2ShutterButton","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"shutterButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"torchOnButton:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":" *) "},{"text":"torchOnButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"torchOffButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","text":"SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"torchOffButton"},{"text":" ","kind":"text"},{"text":"previewButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PreviewButton","kind":"typeIdentifier","text":"SBSDKUI2PreviewButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton"},{"text":" *) ","kind":"text"},{"text":"previewButton","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/title","value":"SBSDKUI2BarButtonConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton\/title","value":"SBSDKUI2PreviewButton","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2PreviewButton"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2PreviewButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/title","value":"SBSDKUI2CameraBottomBar","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/fragments"},{"value":[{"text":"SBSDKUI2CameraBottomBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2ShutterButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ShutterButton\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ShutterButton\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ShutterButton"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ShutterButton\/navigatorTitle","value":[{"text":"SBSDKUI2ShutterButton","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar~1init(importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar~1init(importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","kind":"identifier"}]}]}]}