{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithOcrResolutionLimit:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"ocrResolutionLimit","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maximumNumberOfAccumulatedFrames:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maximumNumberOfAccumulatedFrames"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"},{"kind":"text","text":" "},{"kind":"identifier","text":"optimizeSingleLine:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"optimizeSingleLine"},{"kind":"text","text":" "},{"kind":"identifier","text":"validator:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKContentValidator","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator","text":"SBSDKContentValidator"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"validator"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration\/initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:optimizeSingleLine:validator:"},"metadata":{"roleHeading":"Instance Method","title":"initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:optimizeSingleLine:validator:","symbolKind":"method","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:optimizeSingleLine:validator:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration(im)initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:optimizeSingleLine:validator:","navigatorTitle":[{"kind":"identifier","text":"initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:optimizeSingleLine:validator:"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration\/initwithocrresolutionlimit:maximumnumberofaccumulatedframes:minimumnumberofrequiredframeswithequalscanningresult:optimizesingleline:validator:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator":{"url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator","role":"symbol","title":"SBSDKContentValidator","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator","abstract":[{"type":"text","text":"Base class for content validators."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKContentValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKContentValidator","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerConfiguration/initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:optimizeSingleLine:validator:":{"title":"initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:optimizeSingleLine:validator:","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration\/initwithocrresolutionlimit:maximumnumberofaccumulatedframes:minimumnumberofrequiredframeswithequalscanningresult:optimizesingleline:validator:","type":"topic","kind":"symbol","navigatorTitle":[{"text":"initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:optimizeSingleLine:validator:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:optimizeSingleLine:validator:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration\/initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:optimizeSingleLine:validator:","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerConfiguration":{"abstract":[{"text":"Configuration for the text pattern scanner.","type":"text"}],"role":"symbol","title":"SBSDKTextPatternScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration"}},"variantOverrides":[{"patch":[{"value":"SBSDKContentValidator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/title","op":"replace"},{"value":[{"text":"SBSDKContentValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/fragments","op":"replace"},{"value":[{"text":"SBSDKContentValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/navigatorTitle","op":"replace"},{"value":"SBSDKTextPatternScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}