{"metadata":{"title":"scanningCompletedColor","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"scanningCompletedColor"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FindAndPickScanningMode(py)scanningCompletedColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanningCompletedColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"scanningCompletedColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/scanningcompletedcolor"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/scanningcompletedcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/scanningCompletedColor","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode"]]},"abstract":[{"text":"Color of the selected barcode.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is “?sbColorPositive”"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2color","title":"SBSDKUI2Color","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode":{"abstract":[{"type":"text","text":"Configuration of the Find and Pick barcode scanning mode."}],"kind":"symbol","title":"SBSDKUI2FindAndPickScanningMode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FindAndPickScanningMode"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2FindAndPickScanningMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/scanningCompletedColor":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"scanningCompletedColor","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/scanningcompletedcolor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/scanningCompletedColor","title":"scanningCompletedColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanningCompletedColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"}],"abstract":[{"text":"Color of the selected barcode.","type":"text"},{"type":"text","text":" "},{"text":"Default is “?sbColorPositive”","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"scanningCompletedColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"scanningCompletedColor"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":" * ","kind":"text"},{"text":"scanningCompletedColor","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2Color","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments"},{"value":"SBSDKUI2FindAndPickScanningMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickScanningMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1scanningCompletedColor\/title","value":"scanningCompletedColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1scanningCompletedColor\/fragments","op":"replace","value":[{"kind":"identifier","text":"scanningCompletedColor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}