{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Palette\/sbColorOnPrimary"},"metadata":{"title":"sbColorOnPrimary","role":"symbol","navigatorTitle":[{"text":"sbColorOnPrimary","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sbColorOnPrimary"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Palette(py)sbColorOnPrimary"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2palette\/sbcoloronprimary"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2palette\/sbcoloronprimary"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Palette"]]},"sections":[],"abstract":[{"type":"text","text":"Color used for displaying elements on top of the primary color."},{"text":" ","type":"text"},{"text":"Default is “#FFFFFF”","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbColorOnPrimary","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2Color","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2color","title":"SBSDKUI2Color","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Palette":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Palette","kind":"symbol","abstract":[{"type":"text","text":"Value palette describing the colors of the scanner screens."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Palette","kind":"identifier"}],"title":"SBSDKUI2Palette","navigatorTitle":[{"text":"SBSDKUI2Palette","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2palette","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Palette/sbColorOnPrimary":{"title":"sbColorOnPrimary","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Palette\/sbColorOnPrimary","role":"symbol","navigatorTitle":[{"text":"sbColorOnPrimary","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"sbColorOnPrimary","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"}],"abstract":[{"type":"text","text":"Color used for displaying elements on top of the primary color."},{"text":" ","type":"text"},{"text":"Default is “#FFFFFF”","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2palette\/sbcoloronprimary"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"sbColorOnPrimary","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"sbColorOnPrimary","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"sbColorOnPrimary"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace"},{"value":"SBSDKUI2Palette","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Palette"}]},{"value":[{"text":"SBSDKUI2Palette","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette\/navigatorTitle","op":"replace"},{"value":"sbColorOnPrimary","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette~1sbColorOnPrimary\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"sbColorOnPrimary"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette~1sbColorOnPrimary\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}