{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickBadgeConfiguration"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithPartiallyScanned:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgeStyle","text":"SBSDKUI2BadgeStyle"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"partiallyScanned"},{"kind":"text","text":" "},{"text":"rejected:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgeStyle","text":"SBSDKUI2BadgeStyle","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rejected"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completed:"},{"kind":"text","text":"("},{"text":"SBSDKUI2BadgeStyle","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgeStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle"},{"text":" *) ","kind":"text"},{"text":"completed","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPartiallyScanned:rejected:completed:"}],"title":"initWithPartiallyScanned:rejected:completed:","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FindAndPickBadgeConfiguration(im)initWithPartiallyScanned:rejected:completed:","navigatorTitle":[{"text":"initWithPartiallyScanned:rejected:completed:","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/initWithPartiallyScanned:rejected:completed:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2findandpickbadgeconfiguration\/initwithpartiallyscanned:rejected:completed:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickBadgeConfiguration/initWithPartiallyScanned:rejected:completed:":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickbadgeconfiguration\/initwithpartiallyscanned:rejected:completed:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithPartiallyScanned:rejected:completed:","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"initWithPartiallyScanned:rejected:completed:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/initWithPartiallyScanned:rejected:completed:","type":"topic","navigatorTitle":[{"text":"initWithPartiallyScanned:rejected:completed:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BadgeStyle":{"title":"SBSDKUI2BadgeStyle","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BadgeStyle"}],"role":"symbol","abstract":[{"type":"text","text":"Configuration of the badge."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2badgestyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BadgeStyle","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgeStyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickBadgeConfiguration":{"type":"topic","title":"SBSDKUI2FindAndPickBadgeConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2FindAndPickBadgeConfiguration"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickbadgeconfiguration","abstract":[{"text":"Configuration of the round badge on find and pick ar layer.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickBadgeConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FindAndPickBadgeConfiguration"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgeStyle\/title","value":"SBSDKUI2BadgeStyle","op":"replace"},{"value":[{"text":"SBSDKUI2BadgeStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgeStyle\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2BadgeStyle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgeStyle\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/title","value":"SBSDKUI2FindAndPickBadgeConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/fragments","value":[{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}