{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeTextLocalization\/initWithTopBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:"},"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeTextLocalization(im)initWithTopBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","role":"symbol","navigatorTitle":[{"text":"initWithTopBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"title":"initWithTopBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTopBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTopBarCancelButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topBarCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topBarTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"userGuidance:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userGuidance"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeInfoMappingLoadingMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcodeInfoMappingLoadingMessage"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeInfoMappingErrorStateTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcodeInfoMappingErrorStateTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeInfoMappingErrorStateSubtitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcodeInfoMappingErrorStateSubtitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeInfoMappingErrorStateRetryButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcodeInfoMappingErrorStateRetryButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeInfoMappingErrorStateCancelButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcodeInfoMappingErrorStateCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"manualCountEditDialogTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"manualCountEditDialogTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"manualCountEditDialogInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"manualCountEditDialogInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"manualCountEditDialogUpdateButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"manualCountEditDialogUpdateButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"manualCountEditDialogCancelButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"manualCountEditDialogCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheetResetButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sheetResetButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheetClearAllButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sheetClearAllButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheetSubmitButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sheetSubmitButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheetStartScanningButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sheetStartScanningButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheetPlaceholderTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sheetPlaceholderTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheetPlaceholderSubtitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sheetPlaceholderSubtitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"singleModeConfirmationCancelButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"singleModeConfirmationCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"multipleModeSheetTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"multipleModeSheetTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"findAndPickSheetTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"findAndPickSheetTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"findAndPickSheetBarcodeItemSubtitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"findAndPickSheetBarcodeItemSubtitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"findAndPickPartialAlertTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"findAndPickPartialAlertTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"findAndPickPartialAlertSubtitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"findAndPickPartialAlertSubtitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"findAndPickPartialAlertCancelButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"findAndPickPartialAlertCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"findAndPickPartialAlertSubmitButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"findAndPickPartialAlertSubmitButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"findAndPickCompleteAlertTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"findAndPickCompleteAlertTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"findAndPickCompleteAlertSubtitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"findAndPickCompleteAlertSubtitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"findAndPickCompleteAlertCancelButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"findAndPickCompleteAlertCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"findAndPickCompleteAlertSubmitButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"findAndPickCompleteAlertSubmitButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCancelButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionFlashButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionFlashButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionZoomButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionZoomButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionFlipCameraButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionFlipCameraButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionEnableCameraTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermissionEnableCameraTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermissionEnableCameraExplanation"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionEnableCameraButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermissionEnableCameraButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionCloseButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermissionCloseButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionEnableCameraButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraPermissionEnableCameraButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionCloseButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraPermissionCloseButton"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeTextLocalization"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodetextlocalization\/initwithtopbarcancelbutton:topbartitle:userguidance:barcodeinfomappingloadingmessage:barcodeinfomappingerrorstatetitle:barcodeinfomappingerrorstatesubtitle:barcodeinfomappingerrorstateretrybutton:barcodeinfomappingerrorstatecancelbutton:man-3j8ai"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeTextLocalization/initWithTopBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeTextLocalization\/initWithTopBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTopBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithTopBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"title":"initWithTopBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodetextlocalization\/initwithtopbarcancelbutton:topbartitle:userguidance:barcodeinfomappingloadingmessage:barcodeinfomappingerrorstatetitle:barcodeinfomappingerrorstatesubtitle:barcodeinfomappingerrorstateretrybutton:barcodeinfomappingerrorstatecancelbutton:man-3j8ai","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeTextLocalization":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodetextlocalization","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeTextLocalization","abstract":[{"text":"Configuration of the all strings for barcode scanner.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"type":"topic","title":"SBSDKUI2BarcodeTextLocalization"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeTextLocalization\/title","value":"SBSDKUI2BarcodeTextLocalization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeTextLocalization\/fragments","value":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeTextLocalization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}