{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult\/init(detectionscores:points:horizontallines:verticallines:pointsnormalized:horizontallinesnormalized:verticallinesnormalized:aspectratio:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult\/init(detectionscores:points:horizontallines:verticallines:pointsnormalized:horizontallinesnormalized:verticallinesnormalized:aspectratio:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult\/init(detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"detectionScores","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionScores","text":"SBSDKDocumentDetectionScores","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionScores"},{"kind":"text","text":", "},{"kind":"externalParam","text":"points"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"horizontalLines"},{"text":": [","kind":"text"},{"text":"SBSDKLineSegmentInt","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentInt","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentInt"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"verticalLines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKLineSegmentInt","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentInt","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentInt"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"pointsNormalized"},{"kind":"text","text":": ["},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"horizontalLinesNormalized"},{"text":": [","kind":"text"},{"text":"SBSDKLineSegmentFloat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentFloat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentFloat","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"verticalLinesNormalized"},{"text":": [","kind":"text"},{"text":"SBSDKLineSegmentFloat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentFloat","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentFloat"},{"kind":"text","text":"], "},{"text":"aspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult(im)initWithDetectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detectionScores"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionScores","text":"SBSDKDocumentDetectionScores"},{"kind":"text","text":", "},{"kind":"externalParam","text":"points"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"], "},{"text":"horizontalLines","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKLineSegmentInt","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentInt"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"verticalLines"},{"text":": [","kind":"text"},{"text":"SBSDKLineSegmentInt","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentInt"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"pointsNormalized"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":"], "},{"text":"horizontalLinesNormalized","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentFloat","text":"SBSDKLineSegmentFloat","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"verticalLinesNormalized"},{"text":": [","kind":"text"},{"text":"SBSDKLineSegmentFloat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentFloat"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"aspectRatio"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":")","kind":"text"}],"title":"init(detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:)","role":"symbol","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithDetectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:"}]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionResult":{"title":"SBSDKDocumentDetectionResult","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult","role":"symbol","abstract":[{"text":"Result of the document contour detection.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentInt":{"title":"SBSDKLineSegmentInt","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklinesegmentint","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLineSegmentInt"}],"navigatorTitle":[{"text":"SBSDKLineSegmentInt","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentInt","abstract":[{"text":"Represents a line segment in 2D space.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionScores":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectionScores","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionscores","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionScores","title":"SBSDKDocumentDetectionScores","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionScores","kind":"identifier"}],"type":"topic","abstract":[{"text":"The total and partial scores for the detected document contour.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentFloat":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLineSegmentFloat","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdklinesegmentfloat","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKLineSegmentFloat","kind":"identifier"}],"abstract":[{"text":"Represents a line segment in 2D space.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentFloat","kind":"symbol","title":"SBSDKLineSegmentFloat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionResult/init(detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detectionScores","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionScores","text":"SBSDKDocumentDetectionScores","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"points"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"horizontalLines"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKLineSegmentInt","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentInt"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"verticalLines"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentInt","text":"SBSDKLineSegmentInt","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"pointsNormalized","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"], "},{"text":"horizontalLinesNormalized","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKLineSegmentFloat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentFloat"},{"text":"], ","kind":"text"},{"text":"verticalLinesNormalized","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKLineSegmentFloat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentFloat","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"aspectRatio"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"title":"init(detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:)","navigatorTitle":[{"text":"initWithDetectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult\/init(detectionscores:points:horizontallines:verticallines:pointsnormalized:horizontallinesnormalized:verticallinesnormalized:aspectratio:)","type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult\/init(detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithDetectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDetectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithDetectionScores:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectionScores","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionScores","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionScores"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detectionScores"},{"text":" ","kind":"text"},{"text":"points:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"points","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontalLines:"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKLineSegmentInt *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"horizontalLines","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalLines:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<SBSDKLineSegmentInt *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"verticalLines","kind":"internalParam"},{"kind":"text","text":" "},{"text":"pointsNormalized:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSValue *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"pointsNormalized","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"horizontalLinesNormalized:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKLineSegmentFloat *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"horizontalLinesNormalized"},{"text":" ","kind":"text"},{"text":"verticalLinesNormalized:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKLineSegmentFloat *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"verticalLinesNormalized","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aspectRatio:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"aspectRatio","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/title","value":"SBSDKDocumentDetectionResult","op":"replace"},{"value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/fragments"},{"value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentInt\/title","op":"replace","value":"SBSDKLineSegmentInt"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentInt\/fragments","value":[{"kind":"identifier","text":"SBSDKLineSegmentInt"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentInt\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKLineSegmentInt"}],"op":"replace"},{"op":"replace","value":"SBSDKDocumentDetectionScores","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionScores\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionScores\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionScores"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionScores\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionScores"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentFloat\/title","value":"SBSDKLineSegmentFloat","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentFloat\/fragments","value":[{"text":"SBSDKLineSegmentFloat","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKLineSegmentFloat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentFloat\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult~1init(detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:)\/title","value":"initWithDetectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithDetectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult~1init(detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:)\/fragments","op":"replace"}]}]}