{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"hash","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLine(py)hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"symbolKind":"property","role":"symbol","fragments":[{"kind":"identifier","text":"hash"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLine"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkline\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLine\/hash"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLine":{"abstract":[{"type":"text","text":"Represents a single line. A line is made up of words."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLine","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKLine","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLine","title":"SBSDKLine","url":"\/documentation\/scanbotsdk\/sbsdkline"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLine/hash":{"role":"symbol","fragments":[{"text":"hash","kind":"identifier"}],"title":"hash","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkline\/hash","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLine\/hash"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLine\/title","value":"SBSDKLine"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLine\/fragments","value":[{"kind":"identifier","text":"SBSDKLine"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLine\/navigatorTitle","value":[{"text":"SBSDKLine","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}