{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"provideContextFor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"url"},{"kind":"text","text":";"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter\/providecontextfor:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter\/provideContextFor:","interfaceLanguage":"occ"},"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"provideContextFor:"}],"navigatorTitle":[{"kind":"identifier","text":"provideContextFor:"}],"role":"symbol","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAESGCMEncrypter(im)provideContextFor:","roleHeading":"Instance Method","title":"provideContextFor:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESGCMEncrypter":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter","url":"\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter","abstract":[{"type":"text","text":"A data encrypter implementing the AES128-GCM and AES256-GCM standards, with a configurable encryption key provider."},{"type":"text","text":" "},{"type":"text","text":"Supports encryption and decryption of single data blocks as well as streaming data."}],"type":"topic","title":"SBSDKAESGCMEncrypter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESGCMEncrypter/provideContextFor:":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter\/providecontextfor:","type":"topic","abstract":[],"title":"provideContextFor:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter\/provideContextFor:","role":"symbol","navigatorTitle":[{"text":"provideContextFor:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"provideContextFor:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"SBSDKAESGCMEncrypter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter\/fragments","op":"replace"},{"value":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}