{"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannerview\/toolbarrole(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"View.toolbarRole(_:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerView","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerView\/View-Implementations"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerView\/toolbarRole(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toolbarRole","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"role","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"ToolbarRole","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI11ToolbarRoleV"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"},{"kind":"text","text":"\n"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toolbarRole"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ToolbarRole","preciseIdentifier":"s:7SwiftUI11ToolbarRoleV"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"title":"toolbarRole(_:)","extendedModule":"SwiftUICore","externalID":"s:7SwiftUI4ViewPAAE11toolbarRoleyQrAA07ToolbarE0VF::SYNTHESIZED::s:25ScanbotDocumentScannerSDK08SBSDKUI2bC4ViewV","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ScanbotDocumentScannerSDK","relatedModules":["SwiftUICore"]}],"platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"16.0","beta":false},{"introducedAt":"16.0","name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","unavailable":false,"introducedAt":"16.0","deprecated":false,"beta":false},{"introducedAt":"13.0","unavailable":false,"name":"macOS","beta":false,"deprecated":false},{"unavailable":false,"beta":false,"deprecated":false,"name":"tvOS","introducedAt":"16.0"},{"deprecated":false,"name":"watchOS","unavailable":false,"beta":false,"introducedAt":"9.0"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerController":{"kind":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI controller to scan documents."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerController"}],"navigatorTitle":[{"text":"SBSDKUI2DocumentScannerController","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercontroller","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerController","role":"symbol","title":"SBSDKUI2DocumentScannerController"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerView/View-Implementations":{"kind":"article","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerView\/View-Implementations","title":"View Implementations","role":"collectionGroup","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannerview\/view-implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerView/toolbarRole(_:)":{"title":"toolbarRole(_:)","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannerview\/toolbarrole(_:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerView\/toolbarRole(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toolbarRole","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:7SwiftUI11ToolbarRoleV","kind":"typeIdentifier","text":"ToolbarRole"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerView":{"kind":"symbol","abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerController"},{"text":".","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2DocumentScannerView"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerView"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannerview","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerView","role":"symbol","title":"SBSDKUI2DocumentScannerView"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerController\/title","value":"SBSDKUI2DocumentScannerController"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}