{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat","text":"SBSDKImageFileFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation","text":"SBSDKStorageLocation"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"imageFormat","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image file format."}]}]},{"name":"quality","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Sets the JPEG compression quality of the stored images if the image format is JPEG."}]}]},{"name":"location","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The storage location where image files are saved to. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", the default location is chosen."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/init(imageformat:quality:location:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/init(imageformat:quality:location:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/init(imageFormat:quality:location:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a storage."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation"},{"kind":"text","text":"?)"}],"title":"init(imageFormat:quality:location:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPageFileStorage(im)initWithImageFormat:quality:location:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImageFormat:quality:location:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage":{"role":"symbol","title":"SBSDKDocumentPageFileStorage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"abstract":[{"type":"text","text":"A class to store and restore images of different types in a memory-efficient way."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFileFormat":{"role":"symbol","title":"SBSDKImageFileFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFileFormat"}],"abstract":[{"type":"text","text":"Enumeration of supported image file types."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFileFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefileformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/init(imageFormat:quality:location:)":{"role":"symbol","title":"init(imageFormat:quality:location:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initializes a storage."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/init(imageFormat:quality:location:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithImageFormat:quality:location:"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/init(imageformat:quality:location:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageLocation":{"role":"symbol","title":"SBSDKStorageLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageLocation"}],"abstract":[{"type":"text","text":"Descriptor and helper class for describing and creating a directory on the file system."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageLocation"}],"url":"\/documentation\/scanbotsdk\/sbsdkstoragelocation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithImageFormat:quality:location:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageFormat:quality:location:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithImageFormat:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat","text":"SBSDKImageFileFormat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"imageFormat"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"quality"},{"kind":"text","text":" "},{"kind":"identifier","text":"location:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation","text":"SBSDKStorageLocation"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"location"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/title","value":"SBSDKDocumentPageFileStorage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/title","value":"SBSDKImageFileFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFileFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1init(imageFormat:quality:location:)\/title","value":"initWithImageFormat:quality:location:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1init(imageFormat:quality:location:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageFormat:quality:location:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/title","value":"SBSDKStorageLocation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageLocation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}