{"abstract":[{"type":"text","text":"Removes all images from the receiver, except those from the exception list."}],"metadata":{"navigatorTitle":[{"text":"removeAllExceptWithPageFileIDs:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPageFileStorage(im)removeAllExceptWithPageFileIDs:","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"removeAllExcept(pageFileIDs:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAllExcept","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"pageFileIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":"])","kind":"text"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/removeAllExcept(pageFileIDs:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/removeallexcept(pagefileids:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/removeallexcept(pagefileids:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeAllExcept","kind":"identifier"},{"kind":"text","text":"("},{"text":"pageFileIDs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"pageFileIDs","content":[{"type":"paragraph","inlineContent":[{"text":"The page file identifiers that should NOT be removed from the storage.","type":"text"}]}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/removeAllExcept(pageFileIDs:)":{"navigatorTitle":[{"kind":"identifier","text":"removeAllExceptWithPageFileIDs:"}],"title":"removeAllExcept(pageFileIDs:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllExcept"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pageFileIDs"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":"])","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Removes all images from the receiver, except those from the exception list."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/removeAllExcept(pageFileIDs:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/removeallexcept(pagefileids:)","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage":{"navigatorTitle":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A class to store and restore images of different types in a memory-efficient way.","type":"text"}],"role":"symbol","title":"SBSDKDocumentPageFileStorage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"removeAllExceptWithPageFileIDs:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"removeAllExceptWithPageFileIDs:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"removeAllExceptWithPageFileIDs:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<NSUUID *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"pageFileIDs","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The page file identifiers that should NOT be removed from the storage."}]}],"name":"pageFileIDs"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1removeAllExcept(pageFileIDs:)\/title","value":"removeAllExceptWithPageFileIDs:"},{"value":[{"text":"- ","kind":"text"},{"text":"removeAllExceptWithPageFileIDs:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1removeAllExcept(pageFileIDs:)\/fragments"},{"value":"SBSDKDocumentPageFileStorage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/fragments","op":"replace","value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}]},{"value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/navigatorTitle","op":"replace"}]}]}