{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forExistingPageFileID"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pageFileID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":", "},{"text":"pageFileType","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType","text":"SBSDKDocumentPageFileType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}],"kind":"declarations"},{"parameters":[{"name":"pageFileID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The page file identifier of the image to be removed."}]}]},{"name":"type","content":[{"inlineContent":[{"type":"text","text":"The page file type of the image to be removed."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"True"},{"type":"text","text":" if the image was successfully removed, "},{"code":"False","type":"codeVoice"},{"text":" otherwise.","type":"text"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/removeImage(forExistingPageFileID:pageFileType:)","interfaceLanguage":"swift"},"abstract":[{"text":"Removes the image with the given page file identifier and page file type.","type":"text"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/removeimage(forexistingpagefileid:pagefiletype:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/removeimage(forexistingpagefileid:pagefiletype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","roleHeading":"Instance Method","title":"removeImage(forExistingPageFileID:pageFileType:)","navigatorTitle":[{"text":"removeImageForExistingPageFileID:pageFileType:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPageFileStorage(im)removeImageForExistingPageFileID:pageFileType:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forExistingPageFileID","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"text":"pageFileType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage","type":"topic","abstract":[{"type":"text","text":"A class to store and restore images of different types in a memory-efficient way."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"role":"symbol","title":"SBSDKDocumentPageFileStorage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileType":{"title":"SBSDKDocumentPageFileType","kind":"symbol","abstract":[{"text":"Enumeration of image type classifiers.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefiletype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentPageFileType"}],"navigatorTitle":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/removeImage(forExistingPageFileID:pageFileType:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"removeImageForExistingPageFileID:pageFileType:"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/removeimage(forexistingpagefileid:pagefiletype:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/removeImage(forExistingPageFileID:pageFileType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeImage"},{"text":"(","kind":"text"},{"text":"forExistingPageFileID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"text":"pageFileType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType","kind":"typeIdentifier","text":"SBSDKDocumentPageFileType"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Removes the image with the given page file identifier and page file type.","type":"text"}],"title":"removeImage(forExistingPageFileID:pageFileType:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"removeImageForExistingPageFileID:pageFileType:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"removeImageForExistingPageFileID:pageFileType:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"removeImageForExistingPageFileID:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSUUID","text":"NSUUID"},{"kind":"text","text":" *) "},{"text":"pageFileID","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pageFileType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"pageFileID","content":[{"type":"paragraph","inlineContent":[{"text":"The page file identifier of the image to be removed.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"The page file type of the image to be removed.","type":"text"}],"type":"paragraph"}],"name":"type"}],"kind":"parameters"}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"True"},{"type":"text","text":" if the image was successfully removed, "},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise."}]}]}},{"value":"SBSDKDocumentPageFileStorage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/fragments"},{"value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/navigatorTitle"},{"value":"SBSDKDocumentPageFileType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/fragments","op":"replace","value":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1removeImage(forExistingPageFileID:pageFileType:)\/title","value":"removeImageForExistingPageFileID:pageFileType:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeImageForExistingPageFileID:pageFileType:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1removeImage(forExistingPageFileID:pageFileType:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}