{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"text":"writingJpegImageCompressionQuality","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"writingJpegImageCompressionQuality"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPageFileStorage(py)writingJpegImageCompressionQuality","modules":[{"name":"ScanbotSDK"}],"title":"writingJpegImageCompressionQuality","role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/writingJpegImageCompressionQuality","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"writingJpegImageCompressionQuality"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":" { get }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Values must be between 0 (high compression, small file size, bad quality) and 100 (no compression, huge file size, good image quality).","type":"text"}]},{"inlineContent":[{"type":"text","text":"Read-only. Defaults to 80."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"abstract":[{"text":"If file format is set to JPEG, this property holds the compression quality of the stored images.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/writingjpegimagecompressionquality"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/writingjpegimagecompressionquality"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/writingJpegImageCompressionQuality":{"abstract":[{"text":"If file format is set to JPEG, this property holds the compression quality of the stored images.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"writingJpegImageCompressionQuality","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/writingJpegImageCompressionQuality","title":"writingJpegImageCompressionQuality","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/writingjpegimagecompressionquality","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"writingJpegImageCompressionQuality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage","navigatorTitle":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"title":"SBSDKDocumentPageFileStorage","type":"topic","abstract":[{"type":"text","text":"A class to store and restore images of different types in a memory-efficient way."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"writingJpegImageCompressionQuality","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"writingJpegImageCompressionQuality","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"writingJpegImageCompressionQuality","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1writingJpegImageCompressionQuality\/title","value":"writingJpegImageCompressionQuality","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1writingJpegImageCompressionQuality\/fragments","value":[{"text":"writingJpegImageCompressionQuality","kind":"identifier"}],"op":"replace"},{"value":"SBSDKDocumentPageFileStorage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/fragments","value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}]}]}]}