{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gradient","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2BottomBarMode@SBSDKUI2BottomBarModeGradient","navigatorTitle":[{"text":"SBSDKUI2BottomBarModeGradient","kind":"identifier"}],"symbolKind":"case","title":"SBSDKUI2BottomBarMode.gradient","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BottomBarMode\/gradient","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BottomBarMode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gradient","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"abstract":[{"type":"text","text":"Display the bottom bar with a gradient background color or a gradient with transparency. The buttons will still be visible."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2bottombarmode\/gradient"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2bottombarmode\/gradient"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BottomBarMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BottomBarMode","type":"topic","title":"SBSDKUI2BottomBarMode","role":"symbol","abstract":[{"text":"The visual mode used for the bottom bar.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2BottomBarMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2bottombarmode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BottomBarMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BottomBarMode/gradient":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BottomBarModeGradient"}],"abstract":[{"type":"text","text":"Display the bottom bar with a gradient background color or a gradient with transparency. The buttons will still be visible."}],"title":"SBSDKUI2BottomBarMode.gradient","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2bottombarmode\/gradient","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BottomBarMode\/gradient","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gradient"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUI2BottomBarModeGradient"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKUI2BottomBarModeGradient","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKUI2BottomBarModeGradient","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BottomBarMode\/title","op":"replace","value":"SBSDKUI2BottomBarMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BottomBarMode\/fragments","value":[{"text":"SBSDKUI2BottomBarMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BottomBarMode\/navigatorTitle","value":[{"text":"SBSDKUI2BottomBarMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BottomBarMode~1gradient\/title","value":"SBSDKUI2BottomBarModeGradient","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BottomBarMode~1gradient\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BottomBarModeGradient"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}