{"kind":"symbol","metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationLockMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKOrientationLock","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock"}],"title":"orientationLockMode","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardRecognizerUIConfiguration(py)orientationLockMode","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"orientationLockMode"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration\/orientationLockMode","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizeruiconfiguration\/orientationlockmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizeruiconfiguration\/orientationlockmode"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationLockMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKOrientationLock","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration"]]},"abstract":[{"text":"Allowed orientations for automatic interface rotations.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizeruiconfiguration","title":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration","role":"symbol","kind":"symbol","abstract":[{"text":"Configuration for user interface of the detector RTU-UI screen for Health Insurance Card scanner.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOrientationLock":{"kind":"symbol","abstract":[{"text":"This enum describes the available orientation lock modes for the user interface.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOrientationLock"}],"title":"SBSDKOrientationLock","url":"\/documentation\/scanbotsdk\/sbsdkorientationlock","navigatorTitle":[{"kind":"identifier","text":"SBSDKOrientationLock"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration/orientationLockMode":{"kind":"symbol","navigatorTitle":[{"text":"orientationLockMode","kind":"identifier"}],"title":"orientationLockMode","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orientationLockMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKOrientationLock","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration\/orientationLockMode","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizeruiconfiguration\/orientationlockmode","abstract":[{"type":"text","text":"Allowed orientations for automatic interface rotations."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"orientationLockMode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"orientationLockMode"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock","text":"SBSDKOrientationLock"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationLockMode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerUIConfiguration\/title","value":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerUIConfiguration\/fragments","value":[{"text":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerUIConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/title","op":"replace","value":"SBSDKOrientationLock"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKOrientationLock"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/navigatorTitle","op":"replace","value":[{"text":"SBSDKOrientationLock","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerUIConfiguration~1orientationLockMode\/title","op":"replace","value":"orientationLockMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerUIConfiguration~1orientationLockMode\/fragments","op":"replace","value":[{"text":"orientationLockMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}