{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode93configuration\/maximumtextlength"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode93configuration\/maximumtextlength"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCode93Configuration(py)maximumTextLength","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"maximumTextLength","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumTextLength","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"title":"maximumTextLength","role":"symbol"},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode93Configuration\/maximumTextLength"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode93Configuration"]]},"abstract":[{"text":"Maximum text length. 0 implies no maximum. Applied only to linear barcode formats that allow variable length.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maximumTextLength"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is 0"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode93Configuration/maximumTextLength":{"title":"maximumTextLength","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"maximumTextLength","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"role":"symbol","abstract":[{"type":"text","text":"Maximum text length. 0 implies no maximum. Applied only to linear barcode formats that allow variable length."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode93Configuration\/maximumTextLength","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode93configuration\/maximumtextlength","navigatorTitle":[{"text":"maximumTextLength","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode93Configuration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode93Configuration","role":"symbol","title":"SBSDKBarcodeFormatCode93Configuration","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Code 93 barcode configuration. Add to scanner configuration to scan Code 93 barcodes."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCode93Configuration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode93configuration","navigatorTitle":[{"text":"SBSDKBarcodeFormatCode93Configuration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"maximumTextLength"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"maximumTextLength","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":" ","kind":"text"},{"text":"maximumTextLength","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"maximumTextLength","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode93Configuration~1maximumTextLength\/title"},{"op":"replace","value":[{"kind":"identifier","text":"maximumTextLength"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode93Configuration~1maximumTextLength\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode93Configuration\/title","value":"SBSDKBarcodeFormatCode93Configuration","op":"replace"},{"value":[{"text":"SBSDKBarcodeFormatCode93Configuration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode93Configuration\/fragments","op":"replace"},{"value":[{"text":"SBSDKBarcodeFormatCode93Configuration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode93Configuration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}