{"kind":"symbol","abstract":[{"type":"text","text":"Compares the receiver to another instance of SBSDKPolygon."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon\/isSimilar(to:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(isSimilarToPolygon:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSimilar","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"text":"polygon","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The polygon instance the receiver is compared to.","type":"text"}]}],"name":"polygon"}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"true"},{"text":", if the points of polygon are similar to the points of the receiver, ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" otherwise.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Similar here means the distance of the normalized corresponding points is less than 0.023.","type":"text"}]}]}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"isSimilar(to:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isSimilar"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isSimilarToPolygon:"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon(im)isSimilarToPolygon:","symbolKind":"method","roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon\/issimilar(to:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon\/issimilar(to:)"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygon":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"title":"SBSDKPolygon","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon","abstract":[{"text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygon/isSimilar(to:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSimilar"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"isSimilarToPolygon:"}],"abstract":[{"type":"text","text":"Compares the receiver to another instance of SBSDKPolygon."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon\/isSimilar(to:)","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon\/issimilar(to:)","type":"topic","title":"isSimilar(to:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"isSimilarToPolygon:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isSimilarToPolygon:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isSimilarToPolygon:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon"},{"kind":"text","text":" *) "},{"text":"polygon","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"polygon","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The polygon instance the receiver is compared to."}]}]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"true","type":"codeVoice"},{"text":", if the points of polygon are similar to the points of the receiver, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" otherwise.","type":"text"}]}]}},{"op":"replace","value":"SBSDKPolygon","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/fragments","value":[{"text":"SBSDKPolygon","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPolygon"}],"op":"replace"},{"value":"isSimilarToPolygon:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon~1isSimilar(to:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon~1isSimilar(to:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isSimilarToPolygon:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}