{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okDeburred"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"All values that correspond to the same logical field are equal after punctuation is removed, all characters are","type":"text"},{"text":" ","type":"text"},{"text":"converted to upper case and diacritics are replaced with their base characters.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/okdeburred"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/okdeburred"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okDeburred","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKValueConsistency.okDeburred","symbolKind":"case","navigatorTitle":[{"text":"SBSDKValueConsistencyOkDeburred","kind":"identifier"}],"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"okDeburred","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKValueConsistency@SBSDKValueConsistencyOkDeburred"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency","navigatorTitle":[{"kind":"identifier","text":"SBSDKValueConsistency"}],"abstract":[{"text":"The status of the consistency verification.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKValueConsistency"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency","title":"SBSDKValueConsistency"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency/okDeburred":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKValueConsistencyOkDeburred","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"okDeburred","kind":"identifier"}],"role":"symbol","title":"SBSDKValueConsistency.okDeburred","abstract":[{"text":"All values that correspond to the same logical field are equal after punctuation is removed, all characters are","type":"text"},{"text":" ","type":"text"},{"text":"converted to upper case and diacritics are replaced with their base characters.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/okdeburred","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okDeburred","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKValueConsistencyOkDeburred"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKValueConsistencyOkDeburred"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKValueConsistencyOkDeburred","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/title","op":"replace","value":"SBSDKValueConsistency"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/fragments","op":"replace","value":[{"text":"SBSDKValueConsistency","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKValueConsistency"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1okDeburred\/title","op":"replace","value":"SBSDKValueConsistencyOkDeburred"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1okDeburred\/fragments","op":"replace","value":[{"text":"SBSDKValueConsistencyOkDeburred","kind":"identifier"}]}]}]}