{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/finalcertificate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/finalcertificate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/finalCertificate"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finalCertificate","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"(Form 1) Final certificate (Endbescheinigung) checkbox.","type":"text"}],"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finalCertificate","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKMedicalCertificateCheckBoxType.finalCertificate","navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxTypeFinalCertificate","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateCheckBoxType@SBSDKMedicalCertificateCheckBoxTypeFinalCertificate"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType":{"abstract":[{"type":"text","text":"Type of the checkbox."}],"title":"SBSDKMedicalCertificateCheckBoxType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxType"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxType"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/finalCertificate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/finalCertificate","kind":"symbol","type":"topic","title":"SBSDKMedicalCertificateCheckBoxType.finalCertificate","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/finalcertificate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeFinalCertificate"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalCertificate"}],"abstract":[{"type":"text","text":"(Form 1) Final certificate (Endbescheinigung) checkbox."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKMedicalCertificateCheckBoxTypeFinalCertificate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKMedicalCertificateCheckBoxTypeFinalCertificate","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKMedicalCertificateCheckBoxTypeFinalCertificate","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/title","op":"replace","value":"SBSDKMedicalCertificateCheckBoxType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxType"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxType"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1finalCertificate\/title","op":"replace","value":"SBSDKMedicalCertificateCheckBoxTypeFinalCertificate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1finalCertificate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeFinalCertificate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}