{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Creates a UIBezierPath instance of the receiver for drawing purposes."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon\/bezierpath(for:)-gke8"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon\/bezierpath(for:)-gke8"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(bezierPathForPreviewLayer:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bezierPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"previewLayer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","text":"AVCaptureVideoPreviewLayer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The preview layer the path is going to be presented on.","type":"text"}],"type":"paragraph"}],"name":"previewLayer"}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An UIBezierPath instance representing the polygon."}]}]}],"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon(im)bezierPathForPreviewLayer:","roleHeading":"Instance Method","title":"bezierPath(for:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bezierPathForPreviewLayer:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bezierPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","kind":"typeIdentifier","text":"AVCaptureVideoPreviewLayer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier","text":"UIBezierPath"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(for:)-gke8","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"kind":"symbol","role":"symbol","type":"topic","title":"SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","url":"\/documentation\/scanbotsdk\/sbsdkpolygon","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/bezierPath(for:)-gke8":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bezierPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureVideoPreviewLayer","preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(for:)-gke8","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/bezierpath(for:)-gke8","title":"bezierPath(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bezierPathForPreviewLayer:"}],"abstract":[{"text":"Creates a UIBezierPath instance of the receiver for drawing purposes.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"bezierPathForPreviewLayer:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bezierPathForPreviewLayer:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"bezierPathForPreviewLayer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCaptureVideoPreviewLayer","preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"previewLayer","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"The preview layer the path is going to be presented on.","type":"text"}],"type":"paragraph"}],"name":"previewLayer"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An UIBezierPath instance representing the polygon."}]}]},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"SBSDKPolygon","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPolygon"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPolygon"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/navigatorTitle","op":"replace"},{"value":"bezierPathForPreviewLayer:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1bezierPath(for:)-gke8\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"bezierPathForPreviewLayer:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1bezierPath(for:)-gke8\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}