{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalid","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"SBSDKDocumentVerificationStatus.invalid","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentVerificationStatus@SBSDKDocumentVerificationStatusInvalid","role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"SBSDKDocumentVerificationStatusInvalid","kind":"identifier"}]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationStatus\/invalid","interfaceLanguage":"swift"},"abstract":[{"text":"At least one verification failed.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationStatus"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentverificationstatus\/invalid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentverificationstatus\/invalid"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentVerificationStatus":{"abstract":[{"type":"text","text":"Overall status of the document verification."}],"title":"SBSDKDocumentVerificationStatus","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentVerificationStatus"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationStatus","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentVerificationStatus"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentverificationstatus","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentVerificationStatus/invalid":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentverificationstatus\/invalid","kind":"symbol","role":"symbol","title":"SBSDKDocumentVerificationStatus.invalid","abstract":[{"type":"text","text":"At least one verification failed."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentVerificationStatusInvalid"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationStatus\/invalid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKDocumentVerificationStatusInvalid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKDocumentVerificationStatusInvalid","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKDocumentVerificationStatusInvalid","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationStatus\/title","op":"replace","value":"SBSDKDocumentVerificationStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentVerificationStatus"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationStatus\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentVerificationStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationStatus~1invalid\/title","op":"replace","value":"SBSDKDocumentVerificationStatusInvalid"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationStatus~1invalid\/fragments","op":"replace","value":[{"text":"SBSDKDocumentVerificationStatusInvalid","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}