{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter\/copyWithZone:","interfaceLanguage":"occ"},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"role":"symbol","title":"copyWithZone:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCustomBinarizationFilter(im)copyWithZone:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCustomBinarizationFilter/copyWithZone:":{"url":"\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter\/copywithzone:","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter\/copyWithZone:","type":"topic","kind":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCustomBinarizationFilter":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter","role":"symbol","abstract":[{"text":"Automatic binarization filter. This filter is a good starting point for most use cases.","type":"text"}],"navigatorTitle":[{"text":"SBSDKCustomBinarizationFilter","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter","title":"SBSDKCustomBinarizationFilter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCustomBinarizationFilter","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKCustomBinarizationFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCustomBinarizationFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter\/fragments"},{"op":"replace","value":[{"text":"SBSDKCustomBinarizationFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter\/navigatorTitle"}]}]}