{"abstract":[{"text":"Configuration of the top bar on the generic text scanner screen.","type":"text"}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"topBar","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerScreenConfiguration(py)topBar","navigatorTitle":[{"text":"topBar","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TopBarConfiguration","text":"SBSDKUI2TopBarConfiguration"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TopBarConfiguration","text":"SBSDKUI2TopBarConfiguration"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenConfiguration\/topBar","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreenconfiguration\/topbar"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreenconfiguration\/topbar"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenConfiguration"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TopBarConfiguration":{"type":"topic","title":"SBSDKUI2TopBarConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2topbarconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the top bar’s appearance."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerScreenConfiguration":{"title":"SBSDKUI2TextPatternScannerScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenConfiguration"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the screen for detecting generic text data."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenConfiguration"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreenconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerScreenConfiguration/topBar":{"navigatorTitle":[{"kind":"identifier","text":"topBar"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBar"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TopBarConfiguration","kind":"typeIdentifier","text":"SBSDKUI2TopBarConfiguration"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenConfiguration\/topBar","title":"topBar","abstract":[{"type":"text","text":"Configuration of the top bar on the generic text scanner screen."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreenconfiguration\/topbar"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"topBar","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"topBar","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKUI2TopBarConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TopBarConfiguration"},{"text":" * ","kind":"text"},{"text":"topBar","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration\/title","value":"SBSDKUI2TopBarConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration\/fragments","value":[{"text":"SBSDKUI2TopBarConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenConfiguration\/title","value":"SBSDKUI2TextPatternScannerScreenConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenConfiguration~1topBar\/title","value":"topBar"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenConfiguration~1topBar\/fragments","value":[{"text":"topBar","kind":"identifier"}]}]}]}