{"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forExistingPageFileID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageFileType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType","text":"SBSDKDocumentPageFileType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"set(_:forExistingPageFileID:pageFileType:)","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPageFileStorage(im)set:forExistingPageFileID:pageFileType:","role":"symbol","navigatorTitle":[{"text":"set:forExistingPageFileID:pageFileType:","kind":"identifier"}],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/set(_:forExistingPageFileID:pageFileType:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forExistingPageFileID"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pageFileID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageFileType"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType","text":"SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The UIImage instance to add."}],"type":"paragraph"}],"name":"image"},{"content":[{"inlineContent":[{"type":"text","text":"An existing page file identifier."}],"type":"paragraph"}],"name":"pageFileID"},{"content":[{"inlineContent":[{"text":"The page file type of the image to be added.","type":"text"}],"type":"paragraph"}],"name":"type"}]},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"True"},{"text":" if the image was successfully added, ","type":"text"},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Sets the image of the given page file type and page file type to the receiver."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/set(_:forexistingpagefileid:pagefiletype:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/set(_:forexistingpagefileid:pagefiletype:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/set(_:forExistingPageFileID:pageFileType:)":{"kind":"symbol","abstract":[{"type":"text","text":"Sets the image of the given page file type and page file type to the receiver."}],"title":"set(_:forExistingPageFileID:pageFileType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forExistingPageFileID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageFileType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType","kind":"typeIdentifier","text":"SBSDKDocumentPageFileType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","navigatorTitle":[{"text":"set:forExistingPageFileID:pageFileType:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/set(_:forExistingPageFileID:pageFileType:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/set(_:forexistingpagefileid:pagefiletype:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage","title":"SBSDKDocumentPageFileStorage","kind":"symbol","abstract":[{"text":"A class to store and restore images of different types in a memory-efficient way.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType","navigatorTitle":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"abstract":[{"type":"text","text":"Enumeration of image type classifiers."}],"title":"SBSDKDocumentPageFileType","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefiletype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"set:forExistingPageFileID:pageFileType:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"set:forExistingPageFileID:pageFileType:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"set:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forExistingPageFileID:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUUID","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSUUID"},{"text":" *) ","kind":"text"},{"text":"pageFileID","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pageFileType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageFileType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The UIImage instance to add."}],"type":"paragraph"}],"name":"image"},{"content":[{"inlineContent":[{"text":"An existing page file identifier.","type":"text"}],"type":"paragraph"}],"name":"pageFileID"},{"content":[{"inlineContent":[{"text":"The page file type of the image to be added.","type":"text"}],"type":"paragraph"}],"name":"type"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":""},{"code":"True","type":"codeVoice"},{"type":"text","text":" if the image was successfully added, "},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"set:forExistingPageFileID:pageFileType:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1set(_:forExistingPageFileID:pageFileType:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"set:forExistingPageFileID:pageFileType:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1set(_:forExistingPageFileID:pageFileType:)\/fragments","op":"replace"},{"value":"SBSDKDocumentPageFileStorage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/navigatorTitle","op":"replace"},{"value":"SBSDKDocumentPageFileType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentPageFileType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentPageFileType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}