{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/accessibilitydescriptioncroppingrotatebutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/accessibilitydescriptioncroppingrotatebutton"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization"]]},"kind":"symbol","abstract":[{"text":"The accessibility hint for the ‘rotate page’ button, located in the bottom bar of the cropping screen.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/accessibilityDescriptionCroppingRotateButton"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingRotateButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"text":"Default is “Tap to rotate document”","type":"text"}],"type":"paragraph"}]}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"accessibilityDescriptionCroppingRotateButton"}],"title":"accessibilityDescriptionCroppingRotateButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingRotateButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization(py)accessibilityDescriptionCroppingRotateButton"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization/accessibilityDescriptionCroppingRotateButton":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/accessibilityDescriptionCroppingRotateButton","abstract":[{"text":"The accessibility hint for the ‘rotate page’ button, located in the bottom bar of the cropping screen.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"accessibilityDescriptionCroppingRotateButton"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/accessibilitydescriptioncroppingrotatebutton","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingRotateButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"accessibilityDescriptionCroppingRotateButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"abstract":[{"text":"Configuration of all the strings for the standalone cropping screen.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"title":"SBSDKUI2DocumentScannerTextLocalization"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"accessibilityDescriptionCroppingRotateButton"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"accessibilityDescriptionCroppingRotateButton","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"accessibilityDescriptionCroppingRotateButton","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization~1accessibilityDescriptionCroppingRotateButton\/title","value":"accessibilityDescriptionCroppingRotateButton"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization~1accessibilityDescriptionCroppingRotateButton\/fragments","value":[{"text":"accessibilityDescriptionCroppingRotateButton","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/title","value":"SBSDKUI2DocumentScannerTextLocalization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}