{"metadata":{"roleHeading":"Type Method","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatGS1CompositeConfiguration(cm)fromJsonWithJson:","modules":[{"name":"ScanbotSDK"}],"title":"fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration\/fromJsonWithJson:"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatgs1compositeconfiguration\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatGS1CompositeConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatGS1CompositeConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration","title":"SBSDKBarcodeFormatGS1CompositeConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatgs1compositeconfiguration","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"GS1 Composite configuration. Add to scanner configuration to scan GS1 Composite barcodes."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatGS1CompositeConfiguration/fromJsonWithJson:":{"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration\/fromJsonWithJson:","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatgs1compositeconfiguration\/fromjsonwithjson:","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/title","value":"SBSDKBarcodeFormatGS1CompositeConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}]}]}]}