{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","text":"SBSDKGenericDocument","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E\/initWithGenericDocument:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategoriesd1e\/initwithgenericdocument:"]}],"sections":[],"metadata":{"title":"initWithGenericDocument:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E(im)initWithGenericDocument:","symbolKind":"method","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E":{"abstract":[{"type":"text","text":"DeDriverLicenseBack.Categories.D1E"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategoriesd1e","kind":"symbol","title":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E/initWithGenericDocument:":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E\/initWithGenericDocument:","role":"symbol","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"title":"initWithGenericDocument:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategoriesd1e\/initwithgenericdocument:","abstract":[],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","title":"SBSDKGenericDocument","kind":"symbol","abstract":[{"text":"Generic document.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E\/title"},{"value":[{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E\/fragments"},{"value":[{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E\/navigatorTitle"},{"value":"SBSDKGenericDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title"},{"value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments"},{"value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}