{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2ViewFinderConfiguration) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"title":"SBSDKUI2ViewFinderConfiguration","symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ViewFinderConfiguration","navigatorTitle":[{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2viewfinderconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2viewfinderconfiguration"]}],"abstract":[{"text":"Configuration of the scanning interface’s viewfinder, allowing it to be shown or hidden as guidance to the user.","type":"text"}],"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/init()"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/visible"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/toJson(configuration:)"]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ViewFinderConfiguration/toJson(configuration:)":{"navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"kind":"symbol","title":"toJson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/toJson(configuration:)","url":"\/documentation\/scanbotsdk\/sbsdkui2viewfinderconfiguration\/tojson(configuration:)","role":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ViewFinderConfiguration/new":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/new","url":"\/documentation\/scanbotsdk\/sbsdkui2viewfinderconfiguration\/new","title":"new","type":"topic","fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"new","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration":{"kind":"symbol","title":"SBSDKUI2BaseViewFinderConfiguration","abstract":[{"text":"Base configuration of the scanning interface’s viewfinder, serving as guidance to the user.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ViewFinderConfiguration/init()":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2viewfinderconfiguration\/init()","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ViewFinderConfiguration/initWithStyle:overlayColor:aspectRatio:minimumInsets:preferredHeight:visible:":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/initWithStyle:overlayColor:aspectRatio:minimumInsets:preferredHeight:visible:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithStyle:overlayColor:aspectRatio:minimumInsets:preferredHeight:visible:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithStyle:overlayColor:aspectRatio:minimumInsets:preferredHeight:visible:","kind":"identifier"}],"title":"initWithStyle:overlayColor:aspectRatio:minimumInsets:preferredHeight:visible:","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2viewfinderconfiguration\/initwithstyle:overlaycolor:aspectratio:minimuminsets:preferredheight:visible:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ViewFinderConfiguration/hash":{"title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkui2viewfinderconfiguration\/hash","role":"symbol","abstract":[],"fragments":[{"text":"hash","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/hash","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ViewFinderConfiguration/copyWithZone:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2viewfinderconfiguration\/copywithzone:","title":"copyWithZone:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/copyWithZone:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ViewFinderConfiguration/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2viewfinderconfiguration\/fromjsonwithjson:","title":"fromJsonWithJson:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/fromJsonWithJson:","role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ViewFinderConfiguration/visible":{"title":"visible","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/visible","abstract":[{"type":"text","text":"Whether the viewfinder is visible."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"visible"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2viewfinderconfiguration\/visible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ViewFinderConfiguration/isEqual:":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2viewfinderconfiguration\/isequal:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ViewFinderConfiguration":{"abstract":[{"text":"Configuration of the scanning interface’s viewfinder, allowing it to be shown or hidden as guidance to the user.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"title":"SBSDKUI2ViewFinderConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2viewfinderconfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"Foundation.NSCopying","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKUI2ViewFinderConfiguration","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2ViewFinderConfiguration"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/visible"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/initWithStyle:overlayColor:aspectRatio:minimumInsets:preferredHeight:visible:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/toJson(configuration:)"],"generated":true},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/fromJsonWithJson:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration\/new"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BaseViewFinderConfiguration"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration~1toJson(configuration:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration~1toJson(configuration:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration\/title","value":"SBSDKUI2BaseViewFinderConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BaseViewFinderConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration~1visible\/title","value":"visible","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration~1visible\/fragments","value":[{"text":"visible","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration\/title","value":"SBSDKUI2ViewFinderConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration\/fragments","value":[{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2ViewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration\/navigatorTitle","op":"replace"}]}]}