{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractorViewControllerDelegate"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"title":"SBSDKDocumentDataExtractorViewControllerDelegate","roleHeading":"Protocol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorViewControllerDelegate","kind":"identifier"}],"role":"symbol","symbolKind":"protocol","navigatorTitle":[{"text":"SBSDKDocumentDataExtractorViewControllerDelegate","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKDocumentDataExtractorViewControllerDelegate"},"abstract":[{"text":"The delegate protocol for the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController","type":"reference"},{"text":".","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewControllerDelegate","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewControllerDelegate\/documentDataExtractorViewController(_:didExtract:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewControllerDelegate\/documentDataExtractorViewControllerShouldExtract(_:)"],"anchor":"Instance-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontrollerdelegate"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorViewControllerDelegate":{"abstract":[{"text":"The delegate protocol for the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractorViewControllerDelegate"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontrollerdelegate","title":"SBSDKDocumentDataExtractorViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorViewControllerDelegate"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorViewControllerDelegate/documentDataExtractorViewController(_:didExtract:on:)":{"title":"documentDataExtractorViewController(_:didExtract:on:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontrollerdelegate\/documentdataextractorviewcontroller(_:didextract:on:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentDataExtractorViewController:didExtractResult:onImage:"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataExtractorViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentDataExtractorViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didExtract","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDataExtractionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractionResult","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"Informs the delegate that a document has been extracted successfully."}],"required":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewControllerDelegate\/documentDataExtractorViewController(_:didExtract:on:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorViewControllerDelegate/documentDataExtractorViewControllerShouldExtract(_:)":{"abstract":[{"text":"Asks the delegate if the document data extractor should extract the next video frame.","type":"text"}],"required":true,"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontrollerdelegate\/documentdataextractorviewcontrollershouldextract(_:)","title":"documentDataExtractorViewControllerShouldExtract(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewControllerDelegate\/documentDataExtractorViewControllerShouldExtract(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDataExtractorViewControllerShouldExtract"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKDocumentDataExtractorViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"documentDataExtractorViewControllerShouldExtract:"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorViewController":{"title":"SBSDKDocumentDataExtractorViewController","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractorViewController"}],"abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to extract documents data, e.g. German passports, ID cards and driver’s licenses on video frames."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKDocumentDataExtractorViewControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKDocumentDataExtractorViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorViewControllerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewControllerDelegate\/documentDataExtractorViewController(_:didExtract:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewControllerDelegate\/documentDataExtractorViewControllerShouldExtract(_:)"],"anchor":"Instance-Methods"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractorViewControllerDelegate"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewControllerDelegate\/title","value":"SBSDKDocumentDataExtractorViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewControllerDelegate\/fragments","value":[{"text":"SBSDKDocumentDataExtractorViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKDocumentDataExtractorViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewControllerDelegate~1documentDataExtractorViewController(_:didExtract:on:)\/title","value":"documentDataExtractorViewController:didExtractResult:onImage:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewControllerDelegate~1documentDataExtractorViewController(_:didExtract:on:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentDataExtractorViewController:didExtractResult:onImage:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewControllerDelegate~1documentDataExtractorViewControllerShouldExtract(_:)\/title","value":"documentDataExtractorViewControllerShouldExtract:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewControllerDelegate~1documentDataExtractorViewControllerShouldExtract(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentDataExtractorViewControllerShouldExtract:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController\/title","value":"SBSDKDocumentDataExtractorViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}