{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKUI2MRZFinderLayoutPreset) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}]}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}],"title":"SBSDKUI2MRZFinderLayoutPreset","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZFinderLayoutPreset"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Source of the text for the MRZ finder example overlay."}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/toJson(configuration:)"],"anchor":"Instance-Methods","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/noLayoutPreset()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/threeLineMrzFinderLayoutPreset()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/twoLineMrzFinderLayoutPreset()"],"anchor":"Type-Methods","generated":true}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"kind":"relationships","type":"inheritsFrom"},{"title":"Inherited By","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoLayoutPreset","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset"],"kind":"relationships","type":"inheritedBy"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset/twoLineMrzFinderLayoutPreset()":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"twoLineMrzFinderLayoutPreset"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"typeIdentifier","text":"SBSDKUI2TwoLineMRZFinderLayoutPreset"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/twoLineMrzFinderLayoutPreset()","navigatorTitle":[{"kind":"identifier","text":"twoLineMrzFinderLayoutPreset"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/twolinemrzfinderlayoutpreset()","title":"twoLineMrzFinderLayoutPreset()","kind":"symbol","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset/copyWithZone:":{"title":"copyWithZone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/copyWithZone:","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/copywithzone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TwoLineMRZFinderLayoutPreset":{"navigatorTitle":[{"text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2twolinemrzfinderlayoutpreset","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset","title":"SBSDKUI2TwoLineMRZFinderLayoutPreset","abstract":[{"type":"text","text":"A ready-to-use preset 2-line text to be displayed."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","type":"unresolvable","title":"NSCopying"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}],"title":"SBSDKUI2MRZFinderLayoutPreset","abstract":[{"type":"text","text":"Source of the text for the MRZ finder example overlay."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset/fromJsonWithJson:":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/fromJsonWithJson:","title":"fromJsonWithJson:","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/fromjsonwithjson:","kind":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset/noLayoutPreset()":{"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"noLayoutPreset"}],"kind":"symbol","title":"noLayoutPreset()","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/nolayoutpreset()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"noLayoutPreset"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2NoLayoutPreset","kind":"typeIdentifier","text":"SBSDKUI2NoLayoutPreset"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/noLayoutPreset()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset/toJson(configuration:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/toJson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/tojson(configuration:)","role":"symbol","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"title":"toJson(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"type":"topic","title":"SBSDKUI2Node","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","abstract":[{"text":"Abstract class for all the configurations.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2node","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Node","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset/isEqual:":{"title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/isEqual:","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/isequal:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset/threeLineMrzFinderLayoutPreset()":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"threeLineMrzFinderLayoutPreset"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ThreeLineMRZFinderLayoutPreset","kind":"typeIdentifier","text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/threeLineMrzFinderLayoutPreset()","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"threeLineMrzFinderLayoutPreset"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/threelinemrzfinderlayoutpreset()","type":"topic","title":"threeLineMrzFinderLayoutPreset()","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset/hash":{"type":"topic","abstract":[],"title":"hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/hash","fragments":[{"kind":"identifier","text":"hash"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/hash"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2NoLayoutPreset":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoLayoutPreset","url":"\/documentation\/scanbotsdk\/sbsdkui2nolayoutpreset","role":"symbol","title":"SBSDKUI2NoLayoutPreset","kind":"symbol","abstract":[{"type":"text","text":"No layout preset."}],"navigatorTitle":[{"text":"SBSDKUI2NoLayoutPreset","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2NoLayoutPreset","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ThreeLineMRZFinderLayoutPreset":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset","kind":"symbol","role":"symbol","title":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2threelinemrzfinderlayoutpreset","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset"}],"abstract":[{"text":"A ready-to-use preset 3-line text to be displayed.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUI2MRZFinderLayoutPreset"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKUI2MRZFinderLayoutPreset","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/hash"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/toJson(configuration:)"]},{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/fromJsonWithJson:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/noLayoutPreset()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/threeLineMrzFinderLayoutPreset()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/twoLineMrzFinderLayoutPreset()"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"title":"Inherits From"},{"type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoLayoutPreset","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset"],"title":"Inherited By"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"title":"Conforms To"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MRZFinderLayoutPreset","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset~1twoLineMrzFinderLayoutPreset()\/title","op":"replace","value":"twoLineMrzFinderLayoutPreset"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset~1twoLineMrzFinderLayoutPreset()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"twoLineMrzFinderLayoutPreset"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TwoLineMRZFinderLayoutPreset\/title","value":"SBSDKUI2TwoLineMRZFinderLayoutPreset","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TwoLineMRZFinderLayoutPreset\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2TwoLineMRZFinderLayoutPreset"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TwoLineMRZFinderLayoutPreset\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2TwoLineMRZFinderLayoutPreset"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/title","value":"SBSDKUI2MRZFinderLayoutPreset","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/fragments","value":[{"text":"SBSDKUI2MRZFinderLayoutPreset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset~1noLayoutPreset()\/title","value":"noLayoutPreset","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset~1noLayoutPreset()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"noLayoutPreset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset~1toJson(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title","value":"SBSDKUI2Node","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Node"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/navigatorTitle","value":[{"text":"SBSDKUI2Node","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset~1threeLineMrzFinderLayoutPreset()\/title","value":"threeLineMrzFinderLayoutPreset","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset~1threeLineMrzFinderLayoutPreset()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"threeLineMrzFinderLayoutPreset"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoLayoutPreset\/title","value":"SBSDKUI2NoLayoutPreset","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoLayoutPreset\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2NoLayoutPreset"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoLayoutPreset\/navigatorTitle","value":[{"text":"SBSDKUI2NoLayoutPreset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset\/title","value":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset\/fragments","value":[{"text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset"}],"op":"replace"}]}]}