{"sections":[],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/confirmed","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/failure","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/notValidated","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/success"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/init(rawValue:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"type":"conformsTo"}],"abstract":[{"type":"text","text":"Health insurance card field validation status."}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"}],"title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","roleHeading":"Enumeration","symbolKind":"enum","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus/failure":{"navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusFailure","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/failure","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/failure","title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus.failure","type":"topic","role":"symbol","abstract":[{"text":"Field is not valid.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus/confirmed":{"title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus.confirmed","navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusConfirmed"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Field is valid and confirmed across multiple frames."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmed"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/confirmed","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/confirmed"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/rawrepresentable-implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus/init(rawValue:)":{"role":"symbol","type":"topic","kind":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/init(rawvalue:)","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus","role":"symbol","title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Health insurance card field validation status."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus/notValidated":{"role":"symbol","type":"topic","kind":"symbol","title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus.notValidated","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/notValidated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notValidated"}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/notvalidated","abstract":[{"text":"Field shouldn’t be validated.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusNotValidated"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus/Equatable-Implementations":{"title":"Equatable Implementations","role":"collectionGroup","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/equatable-implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/Equatable-Implementations","kind":"article"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus/success":{"role":"symbol","abstract":[{"text":"Field is valid.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusSuccess"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/success","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}],"title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus.success","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/success","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/confirmed","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/failure","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/notValidated","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/success"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusFailure","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus~1failure\/title"},{"value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusFailure"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus~1failure\/fragments","op":"replace"},{"value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusConfirmed","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus~1confirmed\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusConfirmed"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus~1confirmed\/fragments","op":"replace"},{"value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/navigatorTitle","op":"replace"},{"value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusNotValidated","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus~1notValidated\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusNotValidated"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus~1notValidated\/fragments","op":"replace"},{"value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusSuccess","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus~1success\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusSuccess"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus~1success\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}