{"kind":"symbol","abstract":[{"text":"Configuration of the all strings for document data extractor screen.","type":"text"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKUI2DocumentDataExtractorScreenTextLocalization) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorScreenTextLocalization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}],"symbolKind":"class","role":"symbol","title":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","roleHeading":"Class","modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/init()"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionCameraPermissionCloseButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionCameraPermissionEnableCameraButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionCloseScannerButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionFlashButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionFlipCameraButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionIntroScreenDoneButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionOpenIntroScreenButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionRetryButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionZoomButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/cameraPermissionCloseButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/cameraPermissionEnableCameraButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/cameraPermissionEnableCameraExplanation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/cameraPermissionEnableCameraTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/completionOverlaySuccessMessage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorAlertCloseScannerButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorAlertRetryButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorCantProcessDocumentAlertSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorCantProcessDocumentAlertTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorNoDocumentDetectedAlertSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorNoDocumentDetectedAlertTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorScanningTooLongAlertSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorScanningTooLongAlertTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorUnsupportedDocumentAlertSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorUnsupportedDocumentAlertTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceBadPerspective","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceNoDocumentFound","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceScanningProgress","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceTooDark","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceTooSmall","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/introScreenDoneButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/introScreenText","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/introScreenTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/topBarCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/topBarTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/topUserGuidance"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/init()":{"title":"init()","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/init()","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/init()","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/hash":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/hash","title":"hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/hash","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentDataExtractorNoDocumentDetectedAlertSubtitle":{"title":"documentDataExtractorNoDocumentDetectedAlertSubtitle","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentdataextractornodocumentdetectedalertsubtitle","navigatorTitle":[{"kind":"identifier","text":"documentDataExtractorNoDocumentDetectedAlertSubtitle"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorNoDocumentDetectedAlertSubtitle","abstract":[{"text":"Subtitle for the alert when no document is detected.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDataExtractorNoDocumentDetectedAlertSubtitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/cameraPermissionEnableCameraExplanation":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/camerapermissionenablecameraexplanation","navigatorTitle":[{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation"}],"role":"symbol","title":"cameraPermissionEnableCameraExplanation","abstract":[{"type":"text","text":"The explanation text of the camera permission dialog."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/cameraPermissionEnableCameraExplanation"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/cameraPermissionEnableCameraButton":{"abstract":[{"type":"text","text":"The ‘enable’ button title of the camera permission dialog."}],"title":"cameraPermissionEnableCameraButton","navigatorTitle":[{"kind":"identifier","text":"cameraPermissionEnableCameraButton"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/camerapermissionenablecamerabutton","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/cameraPermissionEnableCameraButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionEnableCameraButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentDataExtractorScanningTooLongAlertTitle":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataExtractorScanningTooLongAlertTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"documentDataExtractorScanningTooLongAlertTitle","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentdataextractorscanningtoolongalerttitle","navigatorTitle":[{"text":"documentDataExtractorScanningTooLongAlertTitle","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Title for the alert when scanning takes too long."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorScanningTooLongAlertTitle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentDataExtractorNoDocumentDetectedAlertTitle":{"navigatorTitle":[{"text":"documentDataExtractorNoDocumentDetectedAlertTitle","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentdataextractornodocumentdetectedalerttitle","role":"symbol","title":"documentDataExtractorNoDocumentDetectedAlertTitle","abstract":[{"text":"Title for the alert when no document is detected.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataExtractorNoDocumentDetectedAlertTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorNoDocumentDetectedAlertTitle","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/accessibilityDescriptionFlipCameraButton":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/accessibilitydescriptionflipcamerabutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionFlipCameraButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accessibilityDescriptionFlipCameraButton"}],"abstract":[{"type":"text","text":"Accessibility description for the flip camera button."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionFlipCameraButton"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"accessibilityDescriptionFlipCameraButton","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/cameraPermissionEnableCameraTitle":{"navigatorTitle":[{"text":"cameraPermissionEnableCameraTitle","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/camerapermissionenablecameratitle","abstract":[{"text":"The title of the camera permission dialog.","type":"text"}],"type":"topic","title":"cameraPermissionEnableCameraTitle","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/cameraPermissionEnableCameraTitle","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/isEqual:":{"abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/isequal:","kind":"symbol","title":"isEqual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"type":"topic","title":"SBSDKUI2Node","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","abstract":[{"text":"Abstract class for all the configurations.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2node","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Node","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentDataExtractorScanningTooLongAlertSubtitle":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentdataextractorscanningtoolongalertsubtitle","abstract":[{"type":"text","text":"Subtitle for the alert when scanning takes too long."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDataExtractorScanningTooLongAlertSubtitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorScanningTooLongAlertSubtitle","title":"documentDataExtractorScanningTooLongAlertSubtitle","navigatorTitle":[{"kind":"identifier","text":"documentDataExtractorScanningTooLongAlertSubtitle"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization":{"type":"topic","abstract":[{"type":"text","text":"Configuration of the all strings for document data extractor screen."}],"title":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/accessibilityDescriptionOpenIntroScreenButton":{"navigatorTitle":[{"text":"accessibilityDescriptionOpenIntroScreenButton","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Accessibility description for the ‘open introduction screen’ button in top bar.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/accessibilitydescriptionopenintroscreenbutton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionOpenIntroScreenButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"accessibilityDescriptionOpenIntroScreenButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionOpenIntroScreenButton","kind":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/accessibilityDescriptionCameraPermissionCloseButton":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionCameraPermissionCloseButton","navigatorTitle":[{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/accessibilitydescriptioncamerapermissionclosebutton","type":"topic","abstract":[{"text":"The accessibility hint for the ‘close’ button of the camera permission dialog.","type":"text"}],"title":"accessibilityDescriptionCameraPermissionCloseButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentUserGuidanceBadPerspective":{"abstract":[{"text":"The user guidance text displayed when the detected document is not in a good perspective (device tilted).","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceBadPerspective","type":"topic","title":"documentUserGuidanceBadPerspective","navigatorTitle":[{"text":"documentUserGuidanceBadPerspective","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentuserguidancebadperspective","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentUserGuidanceBadPerspective","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentUserGuidanceNoDocumentFound":{"abstract":[{"text":"The user guidance text displayed when no document is found.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceNoDocumentFound","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentuserguidancenodocumentfound","navigatorTitle":[{"text":"documentUserGuidanceNoDocumentFound","kind":"identifier"}],"kind":"symbol","type":"topic","title":"documentUserGuidanceNoDocumentFound","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentUserGuidanceNoDocumentFound","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/fromJsonWithJson:":{"role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/fromJsonWithJson:","kind":"symbol","title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/fromjsonwithjson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/accessibilityDescriptionZoomButton":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/accessibilitydescriptionzoombutton","title":"accessibilityDescriptionZoomButton","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionZoomButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionZoomButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"accessibilityDescriptionZoomButton","kind":"identifier"}],"abstract":[{"text":"Accessibility description for the zoom button.","type":"text"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentUserGuidanceTooSmall":{"abstract":[{"text":"The user guidance text displayed when the detected document is too far away and appears too small.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentuserguidancetoosmall","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceTooSmall","title":"documentUserGuidanceTooSmall","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentUserGuidanceTooSmall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"documentUserGuidanceTooSmall"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/toJson(configuration:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/tojson(configuration:)","type":"topic","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"title":"toJson(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/toJson(configuration:)","role":"symbol","kind":"symbol","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/cameraPermissionCloseButton":{"abstract":[{"text":"The ‘close’ button title of the camera permission dialog.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPermissionCloseButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"cameraPermissionCloseButton","kind":"symbol","navigatorTitle":[{"text":"cameraPermissionCloseButton","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/cameraPermissionCloseButton","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/camerapermissionclosebutton"},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/topBarCancelButton":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/topbarcancelbutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/topBarCancelButton","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarCancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"text":"Cancel button text for the top bar.","type":"text"}],"title":"topBarCancelButton","navigatorTitle":[{"text":"topBarCancelButton","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/accessibilityDescriptionCancelButton":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionCancelButton","abstract":[{"text":"Accessibility description for the ‘cancel’ button in the top bar.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"accessibilityDescriptionCancelButton","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/accessibilitydescriptioncancelbutton","title":"accessibilityDescriptionCancelButton","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/accessibilityDescriptionFlashButton":{"abstract":[{"text":"Accessibility description for the flash button.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionFlashButton","kind":"symbol","title":"accessibilityDescriptionFlashButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionFlashButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"accessibilityDescriptionFlashButton","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/accessibilitydescriptionflashbutton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/accessibilityDescriptionCloseScannerButton":{"navigatorTitle":[{"text":"accessibilityDescriptionCloseScannerButton","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Accessibility description for the ‘close scanner’ button in the alerts.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionCloseScannerButton","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/accessibilitydescriptionclosescannerbutton","title":"accessibilityDescriptionCloseScannerButton","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCloseScannerButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentDataExtractorCantProcessDocumentAlertSubtitle":{"abstract":[{"type":"text","text":"Subtitle for the alert when document cannot be processed."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorCantProcessDocumentAlertSubtitle","kind":"symbol","title":"documentDataExtractorCantProcessDocumentAlertSubtitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataExtractorCantProcessDocumentAlertSubtitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"documentDataExtractorCantProcessDocumentAlertSubtitle","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentdataextractorcantprocessdocumentalertsubtitle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/accessibilityDescriptionIntroScreenDoneButton":{"navigatorTitle":[{"text":"accessibilityDescriptionIntroScreenDoneButton","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Accessibility description for the ‘done’\/‘start scanning’ button in the introduction screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionIntroScreenDoneButton","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/accessibilitydescriptionintroscreendonebutton","title":"accessibilityDescriptionIntroScreenDoneButton","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionIntroScreenDoneButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentDataExtractorUnsupportedDocumentAlertTitle":{"abstract":[{"type":"text","text":"Title for the alert when document is not supported."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorUnsupportedDocumentAlertTitle","kind":"symbol","title":"documentDataExtractorUnsupportedDocumentAlertTitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataExtractorUnsupportedDocumentAlertTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"documentDataExtractorUnsupportedDocumentAlertTitle","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentdataextractorunsupporteddocumentalerttitle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/introScreenDoneButton":{"abstract":[{"text":"Start scanning button text for the introduction screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/introScreenDoneButton","kind":"symbol","title":"introScreenDoneButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"introScreenDoneButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"introScreenDoneButton","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/introscreendonebutton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/introScreenTitle":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/introScreenTitle","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/introscreentitle","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"introScreenTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"introScreenTitle","navigatorTitle":[{"text":"introScreenTitle","kind":"identifier"}],"abstract":[{"type":"text","text":"Title for the introduction screen."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/accessibilityDescriptionRetryButton":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/accessibilitydescriptionretrybutton","navigatorTitle":[{"text":"accessibilityDescriptionRetryButton","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionRetryButton","abstract":[{"text":"Accessibility description for the retry button in the alerts.","type":"text"}],"title":"accessibilityDescriptionRetryButton","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionRetryButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/topUserGuidance":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topUserGuidance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"topUserGuidance","abstract":[{"text":"Text for the top user guidance caption.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/topuserguidance","navigatorTitle":[{"text":"topUserGuidance","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/topUserGuidance","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentDataExtractorAlertCloseScannerButton":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorAlertCloseScannerButton","role":"symbol","type":"topic","abstract":[{"text":"Close Scanner button text for the alert.","type":"text"}],"navigatorTitle":[{"text":"documentDataExtractorAlertCloseScannerButton","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataExtractorAlertCloseScannerButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentdataextractoralertclosescannerbutton","title":"documentDataExtractorAlertCloseScannerButton","kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/completionOverlaySuccessMessage":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/completionOverlaySuccessMessage","kind":"symbol","navigatorTitle":[{"text":"completionOverlaySuccessMessage","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completionOverlaySuccessMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"completionOverlaySuccessMessage","type":"topic","abstract":[{"text":"Caption for the success overlay.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/completionoverlaysuccessmessage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/topBarTitle":{"type":"topic","abstract":[{"text":"Title for the top bar.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"topBarTitle","kind":"identifier"}],"kind":"symbol","title":"topBarTitle","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/topbartitle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/topBarTitle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentDataExtractorAlertRetryButton":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataExtractorAlertRetryButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"documentDataExtractorAlertRetryButton","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentdataextractoralertretrybutton","abstract":[{"text":"Try again button text for the alert.","type":"text"}],"role":"symbol","title":"documentDataExtractorAlertRetryButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorAlertRetryButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/accessibilityDescriptionCameraPermissionEnableCameraButton":{"role":"symbol","title":"accessibilityDescriptionCameraPermissionEnableCameraButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionCameraPermissionEnableCameraButton","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/accessibilitydescriptioncamerapermissionenablecamerabutton","kind":"symbol","type":"topic","navigatorTitle":[{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton","kind":"identifier"}],"abstract":[{"text":"The accessibility hint for the ‘enable’ button of the camera permission dialog.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/copyWithZone:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/copyWithZone:","kind":"symbol","abstract":[],"title":"copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/copywithzone:","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentDataExtractorUnsupportedDocumentAlertSubtitle":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorUnsupportedDocumentAlertSubtitle","kind":"symbol","abstract":[{"text":"Subtitle for the alert when document is not supported.","type":"text"}],"title":"documentDataExtractorUnsupportedDocumentAlertSubtitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataExtractorUnsupportedDocumentAlertSubtitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"documentDataExtractorUnsupportedDocumentAlertSubtitle","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentdataextractorunsupporteddocumentalertsubtitle","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/initWithTopBarTitle:topBarCancelButton:topUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:documentDataExtractorAlertRetryButton:documentDataExtractorAlertCloseScannerButton:documentDataExtractorNoDocumentDetectedAlertTitle:documentDataExtractorNoDocumentDetectedAlertSubtitle:documentDataExtractorCantProcessDocumentAlertTitle:documentDataExtractorCantProcessDocumentAlertSubtitle:documentDataExtractorUnsupportedDocumentAlertTitle:documentDataExtractorUnsupportedDocumentAlertSubtitle:documentDataExtractorScanningTooLongAlertTitle:documentDataExtractorScanningTooLongAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:documentUserGuidanceNoDocumentFound:documentUserGuidanceScanningProgress:documentUserGuidanceTooDark:documentUserGuidanceTooSmall:documentUserGuidanceBadPerspective:":{"navigatorTitle":[{"text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:documentDataExtractorAlertRetryButton:documentDataExtractorAlertCloseScannerButton:documentDataExtractorNoDocumentDetectedAlertTitle:documentDataExtractorNoDocumentDetectedAlertSubtitle:documentDataExtractorCantProcessDocumentAlertTitle:documentDataExtractorCantProcessDocumentAlertSubtitle:documentDataExtractorUnsupportedDocumentAlertTitle:documentDataExtractorUnsupportedDocumentAlertSubtitle:documentDataExtractorScanningTooLongAlertTitle:documentDataExtractorScanningTooLongAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:documentUserGuidanceNoDocumentFound:documentUserGuidanceScanningProgress:documentUserGuidanceTooDark:documentUserGuidanceTooSmall:documentUserGuidanceBadPerspective:","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/initWithTopBarTitle:topBarCancelButton:topUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:documentDataExtractorAlertRetryButton:documentDataExtractorAlertCloseScannerButton:documentDataExtractorNoDocumentDetectedAlertTitle:documentDataExtractorNoDocumentDetectedAlertSubtitle:documentDataExtractorCantProcessDocumentAlertTitle:documentDataExtractorCantProcessDocumentAlertSubtitle:documentDataExtractorUnsupportedDocumentAlertTitle:documentDataExtractorUnsupportedDocumentAlertSubtitle:documentDataExtractorScanningTooLongAlertTitle:documentDataExtractorScanningTooLongAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:documentUserGuidanceNoDocumentFound:documentUserGuidanceScanningProgress:documentUserGuidanceTooDark:documentUserGuidanceTooSmall:documentUserGuidanceBadPerspective:","title":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:documentDataExtractorAlertRetryButton:documentDataExtractorAlertCloseScannerButton:documentDataExtractorNoDocumentDetectedAlertTitle:documentDataExtractorNoDocumentDetectedAlertSubtitle:documentDataExtractorCantProcessDocumentAlertTitle:documentDataExtractorCantProcessDocumentAlertSubtitle:documentDataExtractorUnsupportedDocumentAlertTitle:documentDataExtractorUnsupportedDocumentAlertSubtitle:documentDataExtractorScanningTooLongAlertTitle:documentDataExtractorScanningTooLongAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:documentUserGuidanceNoDocumentFound:documentUserGuidanceScanningProgress:documentUserGuidanceTooDark:documentUserGuidanceTooSmall:documentUserGuidanceBadPerspective:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:documentDataExtractorAlertRetryButton:documentDataExtractorAlertCloseScannerButton:documentDataExtractorNoDocumentDetectedAlertTitle:documentDataExtractorNoDocumentDetectedAlertSubtitle:documentDataExtractorCantProcessDocumentAlertTitle:documentDataExtractorCantProcessDocumentAlertSubtitle:documentDataExtractorUnsupportedDocumentAlertTitle:documentDataExtractorUnsupportedDocumentAlertSubtitle:documentDataExtractorScanningTooLongAlertTitle:documentDataExtractorScanningTooLongAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:documentUserGuidanceNoDocumentFound:documentUserGuidanceScanningProgress:documentUserGuidanceTooDark:documentUserGuidanceTooSmall:documentUserGuidanceBadPerspective:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/initwithtopbartitle:topbarcancelbutton:topuserguidance:introscreentitle:introscreendonebutton:introscreentext:completionoverlaysuccessmessage:accessibilitydescriptionopenintroscreenbutton:accessibilitydescriptionintroscreendonebutton:access-9kl9b","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentUserGuidanceTooDark":{"navigatorTitle":[{"text":"documentUserGuidanceTooDark","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceTooDark","title":"documentUserGuidanceTooDark","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentUserGuidanceTooDark","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"text":"The user guidance text displayed when it is too dark to capture an adequate image.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentuserguidancetoodark","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentUserGuidanceScanningProgress":{"kind":"symbol","abstract":[{"text":"The user guidance text displayed when a document presence was detected.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentUserGuidanceScanningProgress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"documentUserGuidanceScanningProgress","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentuserguidancescanningprogress","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceScanningProgress","type":"topic","title":"documentUserGuidanceScanningProgress","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/introScreenText":{"abstract":[{"text":"The text explanation for the introduction screen.","type":"text"}],"title":"introScreenText","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/introscreentext","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/introScreenText","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"introScreenText","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"introScreenText","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentDataExtractorCantProcessDocumentAlertTitle":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentdataextractorcantprocessdocumentalerttitle","abstract":[{"text":"Title for the alert when document cannot be processed.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorCantProcessDocumentAlertTitle","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataExtractorCantProcessDocumentAlertTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","title":"documentDataExtractorCantProcessDocumentAlertTitle","type":"topic","navigatorTitle":[{"text":"documentDataExtractorCantProcessDocumentAlertTitle","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionCameraPermissionCloseButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionCameraPermissionEnableCameraButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionCloseScannerButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionFlashButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionFlipCameraButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionIntroScreenDoneButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionOpenIntroScreenButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionRetryButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionZoomButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/cameraPermissionCloseButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/cameraPermissionEnableCameraButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/cameraPermissionEnableCameraExplanation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/cameraPermissionEnableCameraTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/completionOverlaySuccessMessage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorAlertCloseScannerButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorAlertRetryButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorCantProcessDocumentAlertSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorCantProcessDocumentAlertTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorNoDocumentDetectedAlertSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorNoDocumentDetectedAlertTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorScanningTooLongAlertSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorScanningTooLongAlertTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorUnsupportedDocumentAlertSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorUnsupportedDocumentAlertTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceBadPerspective","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceNoDocumentFound","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceScanningProgress","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceTooDark","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentUserGuidanceTooSmall","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/introScreenDoneButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/introScreenText","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/introScreenTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/topBarCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/topBarTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/topUserGuidance"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/initWithTopBarTitle:topBarCancelButton:topUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:documentDataExtractorAlertRetryButton:documentDataExtractorAlertCloseScannerButton:documentDataExtractorNoDocumentDetectedAlertTitle:documentDataExtractorNoDocumentDetectedAlertSubtitle:documentDataExtractorCantProcessDocumentAlertTitle:documentDataExtractorCantProcessDocumentAlertSubtitle:documentDataExtractorUnsupportedDocumentAlertTitle:documentDataExtractorUnsupportedDocumentAlertSubtitle:documentDataExtractorScanningTooLongAlertTitle:documentDataExtractorScanningTooLongAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:documentUserGuidanceNoDocumentFound:documentUserGuidanceScanningProgress:documentUserGuidanceTooDark:documentUserGuidanceTooSmall:documentUserGuidanceBadPerspective:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/toJson(configuration:)"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/fromJsonWithJson:"],"anchor":"Type-Methods","title":"Type Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","text":"SBSDKUI2Node","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1init()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1init()\/fragments"},{"op":"replace","value":"documentDataExtractorNoDocumentDetectedAlertSubtitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorNoDocumentDetectedAlertSubtitle\/title"},{"op":"replace","value":[{"kind":"identifier","text":"documentDataExtractorNoDocumentDetectedAlertSubtitle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorNoDocumentDetectedAlertSubtitle\/fragments"},{"op":"replace","value":"cameraPermissionEnableCameraExplanation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1cameraPermissionEnableCameraExplanation\/title"},{"op":"replace","value":[{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1cameraPermissionEnableCameraExplanation\/fragments"},{"op":"replace","value":"cameraPermissionEnableCameraButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1cameraPermissionEnableCameraButton\/title"},{"op":"replace","value":[{"text":"cameraPermissionEnableCameraButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1cameraPermissionEnableCameraButton\/fragments"},{"op":"replace","value":"documentDataExtractorScanningTooLongAlertTitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorScanningTooLongAlertTitle\/title"},{"op":"replace","value":[{"kind":"identifier","text":"documentDataExtractorScanningTooLongAlertTitle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorScanningTooLongAlertTitle\/fragments"},{"op":"replace","value":"documentDataExtractorNoDocumentDetectedAlertTitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorNoDocumentDetectedAlertTitle\/title"},{"op":"replace","value":[{"text":"documentDataExtractorNoDocumentDetectedAlertTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorNoDocumentDetectedAlertTitle\/fragments"},{"op":"replace","value":"accessibilityDescriptionFlipCameraButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionFlipCameraButton\/title"},{"op":"replace","value":[{"text":"accessibilityDescriptionFlipCameraButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionFlipCameraButton\/fragments"},{"op":"replace","value":"cameraPermissionEnableCameraTitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1cameraPermissionEnableCameraTitle\/title"},{"op":"replace","value":[{"kind":"identifier","text":"cameraPermissionEnableCameraTitle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1cameraPermissionEnableCameraTitle\/fragments"},{"op":"replace","value":"SBSDKUI2Node","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title"},{"op":"replace","value":[{"text":"SBSDKUI2Node","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2Node","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/navigatorTitle"},{"op":"replace","value":"documentDataExtractorScanningTooLongAlertSubtitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorScanningTooLongAlertSubtitle\/title"},{"op":"replace","value":[{"text":"documentDataExtractorScanningTooLongAlertSubtitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorScanningTooLongAlertSubtitle\/fragments"},{"op":"replace","value":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/title"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/navigatorTitle"},{"op":"replace","value":"accessibilityDescriptionOpenIntroScreenButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionOpenIntroScreenButton\/title"},{"op":"replace","value":[{"kind":"identifier","text":"accessibilityDescriptionOpenIntroScreenButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionOpenIntroScreenButton\/fragments"},{"op":"replace","value":"accessibilityDescriptionCameraPermissionCloseButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionCameraPermissionCloseButton\/title"},{"op":"replace","value":[{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionCloseButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionCameraPermissionCloseButton\/fragments"},{"op":"replace","value":"documentUserGuidanceBadPerspective","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentUserGuidanceBadPerspective\/title"},{"op":"replace","value":[{"text":"documentUserGuidanceBadPerspective","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentUserGuidanceBadPerspective\/fragments"},{"op":"replace","value":"documentUserGuidanceNoDocumentFound","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentUserGuidanceNoDocumentFound\/title"},{"op":"replace","value":[{"kind":"identifier","text":"documentUserGuidanceNoDocumentFound"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentUserGuidanceNoDocumentFound\/fragments"},{"op":"replace","value":"accessibilityDescriptionZoomButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionZoomButton\/title"},{"op":"replace","value":[{"kind":"identifier","text":"accessibilityDescriptionZoomButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionZoomButton\/fragments"},{"op":"replace","value":"documentUserGuidanceTooSmall","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentUserGuidanceTooSmall\/title"},{"op":"replace","value":[{"kind":"identifier","text":"documentUserGuidanceTooSmall"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentUserGuidanceTooSmall\/fragments"},{"op":"replace","value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1toJson(configuration:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1toJson(configuration:)\/fragments"},{"op":"replace","value":"cameraPermissionCloseButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1cameraPermissionCloseButton\/title"},{"op":"replace","value":[{"text":"cameraPermissionCloseButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1cameraPermissionCloseButton\/fragments"},{"op":"replace","value":"topBarCancelButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1topBarCancelButton\/title"},{"op":"replace","value":[{"text":"topBarCancelButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1topBarCancelButton\/fragments"},{"op":"replace","value":"accessibilityDescriptionCancelButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionCancelButton\/title"},{"op":"replace","value":[{"text":"accessibilityDescriptionCancelButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionCancelButton\/fragments"},{"op":"replace","value":"accessibilityDescriptionFlashButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionFlashButton\/title"},{"op":"replace","value":[{"text":"accessibilityDescriptionFlashButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionFlashButton\/fragments"},{"op":"replace","value":"accessibilityDescriptionCloseScannerButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionCloseScannerButton\/title"},{"op":"replace","value":[{"text":"accessibilityDescriptionCloseScannerButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionCloseScannerButton\/fragments"},{"op":"replace","value":"documentDataExtractorCantProcessDocumentAlertSubtitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorCantProcessDocumentAlertSubtitle\/title"},{"op":"replace","value":[{"kind":"identifier","text":"documentDataExtractorCantProcessDocumentAlertSubtitle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorCantProcessDocumentAlertSubtitle\/fragments"},{"op":"replace","value":"accessibilityDescriptionIntroScreenDoneButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionIntroScreenDoneButton\/title"},{"op":"replace","value":[{"kind":"identifier","text":"accessibilityDescriptionIntroScreenDoneButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionIntroScreenDoneButton\/fragments"},{"op":"replace","value":"documentDataExtractorUnsupportedDocumentAlertTitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorUnsupportedDocumentAlertTitle\/title"},{"op":"replace","value":[{"kind":"identifier","text":"documentDataExtractorUnsupportedDocumentAlertTitle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorUnsupportedDocumentAlertTitle\/fragments"},{"op":"replace","value":"introScreenDoneButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1introScreenDoneButton\/title"},{"op":"replace","value":[{"text":"introScreenDoneButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1introScreenDoneButton\/fragments"},{"op":"replace","value":"introScreenTitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1introScreenTitle\/title"},{"op":"replace","value":[{"text":"introScreenTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1introScreenTitle\/fragments"},{"op":"replace","value":"accessibilityDescriptionRetryButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionRetryButton\/title"},{"op":"replace","value":[{"kind":"identifier","text":"accessibilityDescriptionRetryButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionRetryButton\/fragments"},{"op":"replace","value":"topUserGuidance","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1topUserGuidance\/title"},{"op":"replace","value":[{"text":"topUserGuidance","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1topUserGuidance\/fragments"},{"op":"replace","value":"documentDataExtractorAlertCloseScannerButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorAlertCloseScannerButton\/title"},{"op":"replace","value":[{"text":"documentDataExtractorAlertCloseScannerButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorAlertCloseScannerButton\/fragments"},{"op":"replace","value":"completionOverlaySuccessMessage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1completionOverlaySuccessMessage\/title"},{"op":"replace","value":[{"text":"completionOverlaySuccessMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1completionOverlaySuccessMessage\/fragments"},{"op":"replace","value":"topBarTitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1topBarTitle\/title"},{"op":"replace","value":[{"kind":"identifier","text":"topBarTitle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1topBarTitle\/fragments"},{"op":"replace","value":"documentDataExtractorAlertRetryButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorAlertRetryButton\/title"},{"op":"replace","value":[{"text":"documentDataExtractorAlertRetryButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorAlertRetryButton\/fragments"},{"op":"replace","value":"accessibilityDescriptionCameraPermissionEnableCameraButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionCameraPermissionEnableCameraButton\/title"},{"op":"replace","value":[{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionEnableCameraButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionCameraPermissionEnableCameraButton\/fragments"},{"op":"replace","value":"documentDataExtractorUnsupportedDocumentAlertSubtitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorUnsupportedDocumentAlertSubtitle\/title"},{"op":"replace","value":[{"text":"documentDataExtractorUnsupportedDocumentAlertSubtitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorUnsupportedDocumentAlertSubtitle\/fragments"},{"op":"replace","value":"documentUserGuidanceTooDark","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentUserGuidanceTooDark\/title"},{"op":"replace","value":[{"text":"documentUserGuidanceTooDark","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentUserGuidanceTooDark\/fragments"},{"op":"replace","value":"documentUserGuidanceScanningProgress","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentUserGuidanceScanningProgress\/title"},{"op":"replace","value":[{"text":"documentUserGuidanceScanningProgress","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentUserGuidanceScanningProgress\/fragments"},{"op":"replace","value":"introScreenText","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1introScreenText\/title"},{"op":"replace","value":[{"text":"introScreenText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1introScreenText\/fragments"},{"op":"replace","value":"documentDataExtractorCantProcessDocumentAlertTitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorCantProcessDocumentAlertTitle\/title"},{"op":"replace","value":[{"text":"documentDataExtractorCantProcessDocumentAlertTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorCantProcessDocumentAlertTitle\/fragments"}]}]}