{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewControllerDelegate"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIMedicalCertificateScannerViewControllerDelegate","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Protocol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate"}],"symbolKind":"protocol","title":"SBSDKUIMedicalCertificateScannerViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"The delegation protocol for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewControllerDelegate\/medicalScannerViewController(_:didFinishWith:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewControllerDelegate\/medicalScannerViewControllerDidCancel(_:)"],"title":"Instance Methods","generated":true}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewControllerDelegate/medicalScannerViewControllerDidCancel(_:)":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontrollerdelegate\/medicalscannerviewcontrollerdidcancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"medicalScannerViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUIMedicalCertificateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerViewController"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"medicalScannerViewControllerDidCancel:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewControllerDelegate\/medicalScannerViewControllerDidCancel(_:)","title":"medicalScannerViewControllerDidCancel(_:)","required":true,"abstract":[{"text":"Informs the delegate that the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","type":"reference"},{"text":" has been cancelled.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewControllerDelegate/medicalScannerViewController(_:didFinishWith:)":{"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontrollerdelegate\/medicalscannerviewcontroller(_:didfinishwith:)","required":true,"type":"topic","navigatorTitle":[{"text":"medicalScannerViewController:didFinishWithResult:","kind":"identifier"}],"title":"medicalScannerViewController(_:didFinishWith:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"medicalScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerViewController","text":"SBSDKUIMedicalCertificateScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult","text":"SBSDKMedicalCertificateScanningResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"Informs the delegate that the ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","isActive":true},{"type":"text","text":" has finished with a valid result."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewControllerDelegate\/medicalScannerViewController(_:didFinishWith:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewControllerDelegate":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontrollerdelegate","abstract":[{"text":"The delegation protocol for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate","kind":"identifier"}],"title":"SBSDKUIMedicalCertificateScannerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController":{"role":"symbol","abstract":[{"text":"A Ready-To-Use viewController to scan medical certificates.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller","title":"SBSDKUIMedicalCertificateScannerViewController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUIMedicalCertificateScannerViewControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewControllerDelegate\/medicalScannerViewController(_:didFinishWith:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewControllerDelegate\/medicalScannerViewControllerDidCancel(_:)"],"title":"Instance Methods","generated":true}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewControllerDelegate~1medicalScannerViewControllerDidCancel(_:)\/title","value":"medicalScannerViewControllerDidCancel:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewControllerDelegate~1medicalScannerViewControllerDidCancel(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"medicalScannerViewControllerDidCancel:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewControllerDelegate~1medicalScannerViewController(_:didFinishWith:)\/title","value":"medicalScannerViewController:didFinishWithResult:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewControllerDelegate~1medicalScannerViewController(_:didFinishWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"medicalScannerViewController:didFinishWithResult:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewControllerDelegate\/title","value":"SBSDKUIMedicalCertificateScannerViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewControllerDelegate\/fragments","value":[{"text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/title","value":"SBSDKUIMedicalCertificateScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/fragments","value":[{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}