{"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeMappedResult\/init(barcode:)"],"generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeMappedResult\/barcode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeMappedResult\/mappedData"],"generated":true}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeMappedResult","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"abstract":[{"type":"text","text":"Class that contains barcode result and mapped data."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeMappedResult","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class","platforms":[],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeMappedResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeMappedResult","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIBarcodeMappedResult","kind":"identifier"}],"symbolKind":"class","title":"SBSDKUIBarcodeMappedResult","role":"symbol"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodemappedresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodemappedresult"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeMappedResult/barcode":{"title":"barcode","type":"topic","deprecated":true,"role":"symbol","abstract":[{"text":"Barcode result.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"barcode","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeMappedResult\/barcode","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodemappedresult\/barcode"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeMappedResult/init(barcode:)":{"kind":"symbol","deprecated":true,"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"barcode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithBarcode:","kind":"identifier"}],"abstract":[{"text":"The initializer.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeMappedResult\/init(barcode:)","title":"init(barcode:)","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodemappedresult\/init(barcode:)"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeMappedResult":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeMappedResult","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIBarcodeMappedResult","kind":"identifier"}],"kind":"symbol","deprecated":true,"title":"SBSDKUIBarcodeMappedResult","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodemappedresult","type":"topic","abstract":[{"type":"text","text":"Class that contains barcode result and mapped data."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeMappedResult","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerMapping":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannermapping","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerMapping","type":"topic","deprecated":true,"abstract":[{"text":"Protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","isActive":true,"type":"reference"},{"text":" barcode results mapping.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerMapping"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerMapping"}],"title":"SBSDKUIBarcodesBatchScannerMapping"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeMappedResult/mappedData":{"deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mappedData","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeMappedData","text":"SBSDKUIBarcodeMappedData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"mappedData","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Mapped info about barcode. Is filled via "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerMapping"},{"type":"text","text":" protocol."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeMappedResult\/mappedData","title":"mappedData","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodemappedresult\/mappeddata"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUIBarcodeMappedResult"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodeMappedResult"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodeMappedResult"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeMappedResult\/barcode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeMappedResult\/mappedData"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeMappedResult\/init(barcode:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeMappedResult","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeMappedResult~1barcode\/title","op":"replace","value":"barcode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeMappedResult~1barcode\/fragments","op":"replace","value":[{"text":"barcode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeMappedResult~1init(barcode:)\/title","op":"replace","value":"initWithBarcode:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeMappedResult~1init(barcode:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithBarcode:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeMappedResult\/title","op":"replace","value":"SBSDKUIBarcodeMappedResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeMappedResult\/fragments","op":"replace","value":[{"text":"SBSDKUIBarcodeMappedResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeMappedResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodeMappedResult"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerMapping\/title","op":"replace","value":"SBSDKUIBarcodesBatchScannerMapping"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerMapping\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerMapping"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerMapping\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIBarcodesBatchScannerMapping","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeMappedResult~1mappedData\/title","op":"replace","value":"mappedData"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeMappedResult~1mappedData\/fragments","op":"replace","value":[{"text":"mappedData","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}