{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Convenience configuration element for enabling the scanning of multiple document types with a common configuration."},{"type":"text","text":" "},{"type":"text","text":"Add to extractor configuration to enable the scanning of multiple document types."}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKDocumentDataExtractorCommonConfiguration) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractorCommonConfiguration"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorcommonconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorcommonconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorCommonConfiguration"}],"title":"SBSDKDocumentDataExtractorCommonConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractorCommonConfiguration"}],"roleHeading":"Class","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorCommonConfiguration","symbolKind":"class","modules":[{"name":"ScanbotSDK"}]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/init()"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/acceptedDocumentTypes"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationElement":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement","title":"SBSDKDocumentDataExtractorConfigurationElement","abstract":[{"type":"text","text":"Base class for all generic document configuration elements."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationelement","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorCommonConfiguration/fromJsonWithJson:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorcommonconfiguration\/fromjsonwithjson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","abstract":[],"type":"topic","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorCommonConfiguration/toJson(configuration:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","title":"toJson(configuration:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorcommonconfiguration\/tojson(configuration:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/toJson(configuration:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"kind":"symbol","abstract":[{"type":"text","text":"Returns a JSON string representation format."}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorCommonConfiguration":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorcommonconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractorCommonConfiguration"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Convenience configuration element for enabling the scanning of multiple document types with a common configuration."},{"type":"text","text":" "},{"text":"Add to extractor configuration to enable the scanning of multiple document types.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorCommonConfiguration"}],"title":"SBSDKDocumentDataExtractorCommonConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorCommonConfiguration/copyWithZone:":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorcommonconfiguration\/copywithzone:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/copyWithZone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"title":"copyWithZone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorCommonConfiguration/init()":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","title":"init()","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/init()","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorcommonconfiguration\/init()"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorCommonConfiguration/acceptedDocumentTypes":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorcommonconfiguration\/accepteddocumenttypes","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptedDocumentTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/acceptedDocumentTypes","title":"acceptedDocumentTypes","navigatorTitle":[{"kind":"identifier","text":"acceptedDocumentTypes"}],"abstract":[{"text":"List of document types to scan. By default, the list is empty.","type":"text"}]},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorCommonConfiguration/initWithAcceptedDocumentTypes:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAcceptedDocumentTypes:"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithAcceptedDocumentTypes:"}],"type":"topic","title":"initWithAcceptedDocumentTypes:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/initWithAcceptedDocumentTypes:","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorcommonconfiguration\/initwithaccepteddocumenttypes:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorCommonConfiguration/hash":{"title":"hash","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorcommonconfiguration\/hash","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/hash","abstract":[],"fragments":[{"kind":"identifier","text":"hash"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorCommonConfiguration/isEqual:":{"title":"isEqual:","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorcommonconfiguration\/isequal:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/isEqual:","type":"topic","abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"Foundation.NSCopying","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKDocumentDataExtractorCommonConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorCommonConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKDocumentDataExtractorCommonConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/acceptedDocumentTypes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/hash"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/initWithAcceptedDocumentTypes:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/toJson(configuration:)"],"title":"Instance Methods"},{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorCommonConfiguration\/fromJsonWithJson:"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractorCommonConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfigurationElement","text":"SBSDKDocumentDataExtractorConfigurationElement","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentDataExtractorConfigurationElement","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/title"},{"value":[{"text":"SBSDKDocumentDataExtractorConfigurationElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/navigatorTitle"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorCommonConfiguration~1toJson(configuration:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorCommonConfiguration~1toJson(configuration:)\/fragments"},{"value":"SBSDKDocumentDataExtractorCommonConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorCommonConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorCommonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorCommonConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorCommonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorCommonConfiguration\/navigatorTitle"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorCommonConfiguration~1init()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorCommonConfiguration~1init()\/fragments"},{"value":"acceptedDocumentTypes","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorCommonConfiguration~1acceptedDocumentTypes\/title"},{"value":[{"text":"acceptedDocumentTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorCommonConfiguration~1acceptedDocumentTypes\/fragments"}]}]}