{"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/init(json:partial:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/behaviorConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/textConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/uiConfiguration"],"anchor":"Instance-Properties"},{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/defaultConfiguration"],"anchor":"Type-Properties"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscannerconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscannerconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"type":"text","text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI vehicle identification number scanner."}],"metadata":{"symbolKind":"class","title":"SBSDKUIVINScannerConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIVINScannerConfiguration"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIVINScannerConfiguration"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerConfiguration","roleHeading":"Class"},"sections":[],"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIConfiguration"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIVINScannerConfiguration"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Use the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/defaultConfiguration"},{"type":"text","text":" class property to retrieve an instance and modify it as needed."}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerConfiguration/defaultConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerConfiguration","kind":"typeIdentifier","text":"SBSDKUIVINScannerConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"defaultConfiguration"}],"title":"defaultConfiguration","abstract":[{"type":"text","text":"The default configuration."}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerconfiguration\/defaultconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/defaultConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuiconfiguration","abstract":[{"type":"text","text":"The general configuration class for all RTU-UI components."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIConfiguration"}],"title":"SBSDKUIConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIConfiguration"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerConfiguration/textConfiguration":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/textConfiguration","title":"textConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerconfiguration\/textconfiguration","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerTextConfiguration","kind":"typeIdentifier","text":"SBSDKUIVINScannerTextConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"textConfiguration"}],"abstract":[{"type":"text","text":"The configuration for displayed texts."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerConfiguration":{"type":"topic","title":"SBSDKUIVINScannerConfiguration","abstract":[{"text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI vehicle identification number scanner.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIVINScannerConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIVINScannerConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerConfiguration/uiConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"uiConfiguration"}],"kind":"symbol","role":"symbol","title":"uiConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerconfiguration\/uiconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/uiConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uiConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerUIConfiguration","kind":"typeIdentifier","text":"SBSDKUIVINScannerUIConfiguration"}],"type":"topic","abstract":[{"text":"The user interface subconfiguration.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerConfiguration/init":{"abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerconfiguration\/init","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/init"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerConfiguration/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)":{"title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"uiConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerUIConfiguration","kind":"typeIdentifier","text":"SBSDKUIVINScannerUIConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerTextConfiguration","kind":"typeIdentifier","text":"SBSDKUIVINScannerTextConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"behaviorConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerBehaviorConfiguration","kind":"typeIdentifier","text":"SBSDKUIVINScannerBehaviorConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","kind":"typeIdentifier","text":"SBSDKUICameraConfiguration"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"}],"abstract":[{"type":"text","text":"Designated initializer."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerConfiguration/behaviorConfiguration":{"abstract":[{"type":"text","text":"The configuration for behavior."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerconfiguration\/behaviorconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"behaviorConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIVINScannerBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerBehaviorConfiguration"}],"title":"behaviorConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"behaviorConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/behaviorConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerConfiguration/init(json:partial:)":{"kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"json"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"partial"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"init(json:partial:)","navigatorTitle":[{"kind":"identifier","text":"initWithJson:partial:"}],"url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerconfiguration\/init(json:partial:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/init(json:partial:)","type":"topic"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUIVINScannerConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUIVINScannerConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIVINScannerConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/behaviorConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/textConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/uiConfiguration"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/init","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/init(json:partial:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerConfiguration\/defaultConfiguration"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIConfiguration"],"kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIVINScannerConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIConfiguration","text":"SBSDKUIConfiguration","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration~1defaultConfiguration\/title","value":"defaultConfiguration"},{"value":[{"kind":"identifier","text":"defaultConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration~1defaultConfiguration\/fragments","op":"replace"},{"value":"SBSDKUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIConfiguration\/navigatorTitle","op":"replace"},{"value":"textConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration~1textConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"textConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration~1textConfiguration\/fragments","op":"replace"},{"value":"SBSDKUIVINScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUIVINScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIVINScannerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration\/navigatorTitle","op":"replace"},{"value":"uiConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration~1uiConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"uiConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration~1uiConfiguration\/fragments","op":"replace"},{"value":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)\/fragments","op":"replace"},{"value":"behaviorConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration~1behaviorConfiguration\/title","op":"replace"},{"value":[{"text":"behaviorConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration~1behaviorConfiguration\/fragments","op":"replace"},{"value":"initWithJson:partial:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration~1init(json:partial:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithJson:partial:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerConfiguration~1init(json:partial:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}