{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerTextConfiguration"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerTextConfiguration\/init","interfaceLanguage":"occ"},"metadata":{"title":"init","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardScannerTextConfiguration(im)init","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannertextconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerTextConfiguration/init":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","title":"init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerTextConfiguration\/init","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannertextconfiguration\/init","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerTextConfiguration":{"type":"topic","abstract":[{"text":"Configuration for the textual contents of the detector RTU-UI screen for Health Insurance Card scanner.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerTextConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerTextConfiguration","title":"SBSDKUIHealthInsuranceCardScannerTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannertextconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIHealthInsuranceCardScannerTextConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUIHealthInsuranceCardScannerTextConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerTextConfiguration\/title"},{"value":[{"text":"SBSDKUIHealthInsuranceCardScannerTextConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerTextConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerTextConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerTextConfiguration\/navigatorTitle","op":"replace"}]}]}