{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(scannedDocument:toFile:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeTIFFAsync"},{"kind":"text","text":"("},{"text":"scannedDocument","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","text":"SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"toFile","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"fileURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"? = nil) "},{"kind":"keyword","text":"async"},{"text":" -> ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The scanned document to convert to a TIFF file.","type":"text"}]}],"name":"scannedDocument"},{"content":[{"inlineContent":[{"type":"text","text":"The file URL to save the TIFF file at. If "},{"code":"nil","type":"codeVoice"},{"text":"the default TIFF location of the scanned document will be used.","type":"text"}],"type":"paragraph"}],"name":"fileURL"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL the TIFF file has been written to or "},{"type":"codeVoice","code":"nil"},{"text":" if the operation failed.","type":"text"}]}]},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"In Swift language it is used with structured concurrency (async\/await).","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Asynchronously converts the scanned document to a multipage-TIFF file and writes it to the specified URL."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"writeTIFFAsyncWithScannedDocument:toFile:completionHandler:"}],"role":"symbol","title":"writeTIFFAsync(scannedDocument:toFile:)","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriter(im)writeTIFFAsyncWithScannedDocument:toFile:completionHandler:","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"writeTIFFAsync","kind":"identifier"},{"text":"(","kind":"text"},{"text":"scannedDocument","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","text":"SBSDKScannedDocument","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"toFile","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/writetiffasync(scanneddocument:tofile:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/writetiffasync(scanneddocument:tofile:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/writeTIFFAsync(scannedDocument:toFile:)":{"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/writetiffasync(scanneddocument:tofile:)","abstract":[{"text":"Asynchronously converts the scanned document to a multipage-TIFF file and writes it to the specified URL.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"writeTIFFAsync"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"scannedDocument"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","text":"SBSDKScannedDocument"},{"kind":"text","text":", "},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(scannedDocument:toFile:)","navigatorTitle":[{"text":"writeTIFFAsyncWithScannedDocument:toFile:completionHandler:","kind":"identifier"}],"title":"writeTIFFAsync(scannedDocument:toFile:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument":{"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument","type":"topic","title":"SBSDKScannedDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKScannedDocument"}],"navigatorTitle":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","abstract":[{"type":"text","text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter","navigatorTitle":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"abstract":[{"type":"text","text":"A class that converts images to (multipage) TIFF images."},{"type":"text","text":" "},{"type":"text","text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc."},{"type":"text","text":" "},{"text":"When passing an encrypter the generated TIFF images will be encrypted.","type":"text"}],"kind":"symbol","title":"SBSDKTIFFImageWriter","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKTIFFImageWriter","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"writeTIFFAsyncWithScannedDocument:toFile:completionHandler:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"writeTIFFAsyncWithScannedDocument:toFile:completionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"writeTIFFAsyncWithScannedDocument:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","text":"SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"scannedDocument"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toFile:"},{"text":"(","kind":"text"},{"text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fileURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The scanned document to convert to a TIFF file.","type":"text"}]}],"name":"scannedDocument"},{"name":"fileURL","content":[{"inlineContent":[{"type":"text","text":"The file URL to save the TIFF file at. If "},{"code":"nil","type":"codeVoice"},{"text":"the default TIFF location of the scanned document will be used.","type":"text"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","value":null,"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(scannedDocument:toFile:)\/title","value":"writeTIFFAsyncWithScannedDocument:toFile:completionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(scannedDocument:toFile:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"writeTIFFAsyncWithScannedDocument:toFile:completionHandler:"}],"op":"replace"},{"value":"SBSDKScannedDocument","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/title","op":"replace"},{"value":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKScannedDocument"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter\/title","value":"SBSDKTIFFImageWriter"},{"value":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKTIFFImageWriter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}