{"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerDateValidationConfiguration(py)fieldTypeName","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"fieldTypeName","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fieldTypeName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"fieldTypeName","symbolKind":"property","roleHeading":"Instance Property"},"sections":[],"abstract":[{"text":"Name, FullName, or NormalizedName of field type for which the year bounds should be applied.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/fieldTypeName"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldTypeName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/fieldtypename"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/fieldtypename"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration":{"navigatorTitle":[{"text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"identifier"}],"abstract":[{"text":"Date validation configuration.","type":"text"},{"text":" ","type":"text"},{"text":"This configuration element does not enable the scanning of any document types by itself.","type":"text"},{"text":" ","type":"text"},{"text":"Add to recognizer configuration to require date validation checks for specific document types.","type":"text"}],"title":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration/fieldTypeName":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fieldTypeName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Name, FullName, or NormalizedName of field type for which the year bounds should be applied."}],"role":"symbol","type":"topic","title":"fieldTypeName","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/fieldTypeName","navigatorTitle":[{"text":"fieldTypeName","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/fieldtypename"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"fieldTypeName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"fieldTypeName"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"fieldTypeName","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration\/title","value":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration~1fieldTypeName\/title","value":"fieldTypeName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration~1fieldTypeName\/fragments","value":[{"text":"fieldTypeName","kind":"identifier"}]}]}]}