{"sections":[],"metadata":{"role":"symbol","roleHeading":"Case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentDetectionStatus@SBSDKDocumentDetectionStatusOkButTooDark","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"okButTooDark","kind":"identifier"}],"title":"SBSDKDocumentDetectionStatus.okButTooDark","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButTooDark"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/okButTooDark","interfaceLanguage":"swift"},"abstract":[{"text":"A document was detected, but it is too dark.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"okButTooDark","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/okbuttoodark"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/okbuttoodark"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionStatus":{"title":"SBSDKDocumentDetectionStatus","role":"symbol","abstract":[{"type":"text","text":"Status of the document detection."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionStatus/okButTooDark":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okButTooDark"}],"navigatorTitle":[{"text":"SBSDKDocumentDetectionStatusOkButTooDark","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/okButTooDark","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/okbuttoodark","abstract":[{"text":"A document was detected, but it is too dark.","type":"text"}],"title":"SBSDKDocumentDetectionStatus.okButTooDark","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKDocumentDetectionStatusOkButTooDark"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKDocumentDetectionStatusOkButTooDark","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButTooDark"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus\/title","op":"replace","value":"SBSDKDocumentDetectionStatus"},{"value":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus~1okButTooDark\/title","value":"SBSDKDocumentDetectionStatusOkButTooDark"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus~1okButTooDark\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButTooDark"}]}]}]}