{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"binarizationFilter","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier","text":"SBSDKParametricFilter"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterParameters(py)binarizationFilter","title":"binarizationFilter","navigatorTitle":[{"kind":"identifier","text":"binarizationFilter"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"binarizationFilter","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"SBSDKScanbotBinarizationFilter"},{"type":"text","text":"."}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Setting this property to a non-binarizing filter will throw a fatal error.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Valid binarizing filters are "},{"code":"SBSDKScanbotBinarizationFilter","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"SBSDKCustomBinarizationFilter","type":"codeVoice"},{"text":".","type":"text"}]}],"type":"aside","style":"warning","name":"Warning"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters\/binarizationfilter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters\/binarizationfilter"]}],"abstract":[{"type":"text","text":"The filter that should be applied for binarization, if the binarize flag is set to "},{"code":"True","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters\/binarizationFilter","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKParametricFilter","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter","title":"SBSDKParametricFilter","abstract":[{"type":"text","text":"Base class for all parametric filters."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterParameters/binarizationFilter":{"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters\/binarizationfilter","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The filter that should be applied for binarization, if the binarize flag is set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":"."}],"title":"binarizationFilter","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"binarizationFilter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"}],"navigatorTitle":[{"kind":"identifier","text":"binarizationFilter"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters\/binarizationFilter","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterParameters":{"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTIFFImageWriterParameters"}],"kind":"symbol","type":"topic","title":"SBSDKTIFFImageWriterParameters","role":"symbol","abstract":[{"text":"Class used to define the parameters for the TIFF image writer.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterParameters"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"binarizationFilter"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"binarizationFilter","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKParametricFilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"kind":"text","text":" * "},{"kind":"identifier","text":"binarizationFilter"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"SBSDKParametricFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}]},{"op":"replace","value":"binarizationFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters~1binarizationFilter\/title"},{"op":"replace","value":[{"text":"binarizationFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters~1binarizationFilter\/fragments"},{"op":"replace","value":"SBSDKTIFFImageWriterParameters","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters\/fragments","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterParameters"}]}]}]}