{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters"]]},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterParameters(py)binarize","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"binarize"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"binarize","symbolKind":"property","navigatorTitle":[{"text":"binarize","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters\/binarize","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"binarize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Defines if the TIFF image should be binarized.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters\/binarize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters\/binarize"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterParameters":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFImageWriterParameters"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters","navigatorTitle":[{"text":"SBSDKTIFFImageWriterParameters","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters","abstract":[{"type":"text","text":"Class used to define the parameters for the TIFF image writer."}],"role":"symbol","title":"SBSDKTIFFImageWriterParameters","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterParameters/binarize":{"navigatorTitle":[{"text":"binarize","kind":"identifier"}],"type":"topic","title":"binarize","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters\/binarize","abstract":[{"type":"text","text":"Defines if the TIFF image should be binarized."}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters\/binarize","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"binarize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"binarize","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"binarize"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"binarize","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters\/title","value":"SBSDKTIFFImageWriterParameters"},{"value":[{"text":"SBSDKTIFFImageWriterParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters\/navigatorTitle","value":[{"text":"SBSDKTIFFImageWriterParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters~1binarize\/title","value":"binarize","op":"replace"},{"value":[{"text":"binarize","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters~1binarize\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}