{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters\/defaultparameters"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters\/defaultparameters"]}],"metadata":{"title":"defaultParameters","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterParameters(cpy)defaultParameters","roleHeading":"Type Property","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"defaultParameters","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKTIFFImageWriterParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterParameters"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"defaultParameters"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Generates the default parameters for colored TIFF images."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultParameters"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters","text":"SBSDKTIFFImageWriterParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterParameters","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters\/defaultParameters","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterParameters/defaultParameters":{"title":"defaultParameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters\/defaultParameters","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters\/defaultparameters","abstract":[{"type":"text","text":"Generates the default parameters for colored TIFF images."}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKTIFFImageWriterParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterParameters"}],"navigatorTitle":[{"text":"defaultParameters","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterParameters":{"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters","type":"topic","role":"symbol","title":"SBSDKTIFFImageWriterParameters","kind":"symbol","abstract":[{"type":"text","text":"Class used to define the parameters for the TIFF image writer."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFImageWriterParameters"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterParameters"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"defaultParameters","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultParameters"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterParameters","text":"SBSDKTIFFImageWriterParameters","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"defaultParameters","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":"defaultParameters","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters~1defaultParameters\/title"},{"value":[{"text":"defaultParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters~1defaultParameters\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters\/title","value":"SBSDKTIFFImageWriterParameters","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterParameters"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters\/fragments"}]}]}