{"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"userDefinedFields","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterParameters(py)userDefinedFields","navigatorTitle":[{"text":"userDefinedFields","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDefinedFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterUserDefinedField","text":"SBSDKTIFFImageWriterUserDefinedField"},{"kind":"text","text":"]"}],"roleHeading":"Instance Property"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters\/userdefinedfields"]},{"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters\/userdefinedfields"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"An array of user-defined TIFF fields that should be written into the TIFF image."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userDefinedFields","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterUserDefinedField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedField","kind":"typeIdentifier","text":"SBSDKTIFFImageWriterUserDefinedField"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters\/userDefinedFields","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterParameters":{"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters","type":"topic","role":"symbol","title":"SBSDKTIFFImageWriterParameters","kind":"symbol","abstract":[{"type":"text","text":"Class used to define the parameters for the TIFF image writer."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFImageWriterParameters"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterParameters"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterParameters/userDefinedFields":{"type":"topic","kind":"symbol","abstract":[{"text":"An array of user-defined TIFF fields that should be written into the TIFF image.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters\/userDefinedFields","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters\/userdefinedfields","title":"userDefinedFields","navigatorTitle":[{"text":"userDefinedFields","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userDefinedFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKTIFFImageWriterUserDefinedField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterUserDefinedField"},{"text":"]","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterUserDefinedField":{"abstract":[{"type":"text","text":"A class used to describe a user-defined TIFF field."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKTIFFImageWriterUserDefinedField","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedField","title":"SBSDKTIFFImageWriterUserDefinedField","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfield","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterUserDefinedField"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"userDefinedFields"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"userDefinedFields","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKTIFFImageWriterUserDefinedField *>"},{"text":" * ","kind":"text"},{"text":"userDefinedFields","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKTIFFImageWriterParameters","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters\/title","op":"replace"},{"value":[{"text":"SBSDKTIFFImageWriterParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters\/fragments"},{"value":"userDefinedFields","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters~1userDefinedFields\/title","op":"replace"},{"op":"replace","value":[{"text":"userDefinedFields","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters~1userDefinedFields\/fragments"},{"value":"SBSDKTIFFImageWriterUserDefinedField","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedField\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedField\/fragments","value":[{"text":"SBSDKTIFFImageWriterUserDefinedField","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}