{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKApplicationState\/inactive"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkapplicationstate\/inactive"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkapplicationstate\/inactive"]}],"abstract":[{"type":"text","text":"The app is inactive and in background."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKApplicationState"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKApplicationState@SBSDKApplicationStateInactive","roleHeading":"Case","role":"symbol","title":"SBSDKApplicationState.inactive","navigatorTitle":[{"text":"SBSDKApplicationStateInactive","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inactive"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"case"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inactive"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKApplicationState/inactive":{"navigatorTitle":[{"text":"SBSDKApplicationStateInactive","kind":"identifier"}],"type":"topic","title":"SBSDKApplicationState.inactive","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"inactive","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKApplicationState\/inactive","role":"symbol","abstract":[{"type":"text","text":"The app is inactive and in background."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkapplicationstate\/inactive"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKApplicationState":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKApplicationState"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkapplicationstate","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An enum describing the current state of the app."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKApplicationState","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKApplicationState"}],"title":"SBSDKApplicationState"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKApplicationStateInactive"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKApplicationStateInactive","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKApplicationStateInactive"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SBSDKApplicationStateInactive","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKApplicationState~1inactive\/title"},{"value":[{"text":"SBSDKApplicationStateInactive","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKApplicationState~1inactive\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKApplicationState\/title","op":"replace","value":"SBSDKApplicationState"},{"value":[{"kind":"identifier","text":"SBSDKApplicationState"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKApplicationState\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKApplicationState\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKApplicationState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}