{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"hash","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKRangeEncoding(py)hash","symbolKind":"property","fragments":[{"kind":"identifier","text":"hash"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkrangeencoding\/hash"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRangeEncoding"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRangeEncoding\/hash","interfaceLanguage":"occ"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRangeEncoding/hash":{"fragments":[{"kind":"identifier","text":"hash"}],"title":"hash","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkrangeencoding\/hash","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRangeEncoding\/hash","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRangeEncoding":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRangeEncoding","navigatorTitle":[{"text":"SBSDKRangeEncoding","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkrangeencoding","type":"topic","kind":"symbol","title":"SBSDKRangeEncoding","abstract":[{"text":"A character encoding for a given range of bytes.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKRangeEncoding","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRangeEncoding\/title","value":"SBSDKRangeEncoding","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRangeEncoding\/fragments","value":[{"text":"SBSDKRangeEncoding","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRangeEncoding\/navigatorTitle","value":[{"text":"SBSDKRangeEncoding","kind":"identifier"}],"op":"replace"}]}]}