{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCRLanguageMissing"}]}]}],"metadata":{"symbolKind":"case","title":"SBSDKErrorCode.OCRLanguageMissing","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodeOCRLanguageMissing"}],"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCRLanguageMissing"}],"roleHeading":"Case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKErrorCode@SBSDKErrorCodeOCRLanguageMissing"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkerrorcode\/ocrlanguagemissing"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkerrorcode\/ocrlanguagemissing"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorCode"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorCode\/OCRLanguageMissing","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Language data for text recognition is missing."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorCode":{"title":"SBSDKErrorCode","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrorcode","abstract":[{"text":"The error codes in the SBSDKErrorDomain.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorCode","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKErrorCode","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKErrorCode","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorCode/OCRLanguageMissing":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodeOCRLanguageMissing"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorCode\/OCRLanguageMissing","title":"SBSDKErrorCode.OCRLanguageMissing","abstract":[{"type":"text","text":"Language data for text recognition is missing."}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"OCRLanguageMissing","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrorcode\/ocrlanguagemissing"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKErrorCodeOCRLanguageMissing","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorCodeOCRLanguageMissing"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKErrorCodeOCRLanguageMissing","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKErrorCode","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorCode\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorCode\/fragments","value":[{"text":"SBSDKErrorCode","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorCode\/navigatorTitle"},{"value":"SBSDKErrorCodeOCRLanguageMissing","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorCode~1OCRLanguageMissing\/title"},{"value":[{"text":"SBSDKErrorCodeOCRLanguageMissing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorCode~1OCRLanguageMissing\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}