{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/copyWithZone:","interfaceLanguage":"occ"},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerDateValidationConfiguration(im)copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/copywithzone:"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration":{"type":"topic","kind":"symbol","title":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","abstract":[{"type":"text","text":"Date validation configuration."},{"type":"text","text":" "},{"type":"text","text":"This configuration element does not enable the scanning of any document types by itself."},{"type":"text","text":" "},{"type":"text","text":"Add to recognizer configuration to require date validation checks for specific document types."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration/copyWithZone:":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/copywithzone:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration\/title","value":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"identifier"}],"op":"replace"}]}]}