{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/initWithMinYear:maxYear:fieldTypeName:"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/initwithminyear:maxyear:fieldtypename:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMinYear:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minYear"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxYear:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maxYear"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldTypeName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fieldTypeName"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerDateValidationConfiguration(im)initWithMinYear:maxYear:fieldTypeName:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinYear:maxYear:fieldTypeName:"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithMinYear:maxYear:fieldTypeName:"}],"title":"initWithMinYear:maxYear:fieldTypeName:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration/initWithMinYear:maxYear:fieldTypeName:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/initWithMinYear:maxYear:fieldTypeName:","title":"initWithMinYear:maxYear:fieldTypeName:","navigatorTitle":[{"text":"initWithMinYear:maxYear:fieldTypeName:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/initwithminyear:maxyear:fieldtypename:","type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithMinYear:maxYear:fieldTypeName:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration":{"type":"topic","kind":"symbol","title":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","abstract":[{"type":"text","text":"Date validation configuration."},{"type":"text","text":" "},{"type":"text","text":"This configuration element does not enable the scanning of any document types by itself."},{"type":"text","text":" "},{"type":"text","text":"Add to recognizer configuration to require date validation checks for specific document types."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration\/title","value":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"}],"op":"replace"}]}]}