{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1handling\/decodestructure"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1handling\/decodestructure"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodeStructure"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Same as VALIDATE_STRUCTURE, except that GS1 strings are converted to the human-readable format, instead (with"},{"text":" ","type":"text"},{"type":"text","text":"parentheses used to wrap AI keys, e.g. (01)123456789). The \\x1D character is never used in this representation."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Gs1Handling\/decodeStructure"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Gs1Handling"]]},"metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"decodeStructure","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"SBSDKUI2Gs1HandlingDecodeStructure","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2Gs1Handling@SBSDKUI2Gs1HandlingDecodeStructure","title":"SBSDKUI2Gs1Handling.decodeStructure","symbolKind":"case","roleHeading":"Case"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Gs1Handling":{"role":"symbol","abstract":[{"type":"text","text":"GS1_COMPOSITE barcode type handling"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1handling","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Gs1Handling","title":"SBSDKUI2Gs1Handling","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 5.2.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Gs1Handling/decodeStructure":{"abstract":[{"type":"text","text":"Same as VALIDATE_STRUCTURE, except that GS1 strings are converted to the human-readable format, instead (with"},{"type":"text","text":" "},{"text":"parentheses used to wrap AI keys, e.g. (01)123456789). The \\x1D character is never used in this representation.","type":"text"}],"role":"symbol","title":"SBSDKUI2Gs1Handling.decodeStructure","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Gs1Handling\/decodeStructure","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1handling\/decodestructure","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodeStructure"}],"navigatorTitle":[{"text":"SBSDKUI2Gs1HandlingDecodeStructure","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"SBSDKUI2Gs1HandlingDecodeStructure","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingDecodeStructure"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingDecodeStructure"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2Gs1Handling","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Gs1Handling\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Gs1Handling\/fragments","op":"replace","value":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Gs1Handling~1decodeStructure\/title","op":"replace","value":"SBSDKUI2Gs1HandlingDecodeStructure"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Gs1Handling~1decodeStructure\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingDecodeStructure"}]}]}]}