{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1handling\/validatestructure"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1handling\/validatestructure"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"SBSDKUI2Gs1Handling.validateStructure","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2Gs1Handling@SBSDKUI2Gs1HandlingValidateStructure","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validateStructure"}],"navigatorTitle":[{"text":"SBSDKUI2Gs1HandlingValidateStructure","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Gs1Handling\/validateStructure","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Gs1Handling"]]},"abstract":[{"type":"text","text":"Same as PARSE. Additionally, messages containing unknown AI keys, or containing values of incorrect format for"},{"text":" ","type":"text"},{"text":"known keys, are not returned.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"validateStructure","kind":"identifier"}]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Gs1Handling":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}],"abstract":[{"text":"GS1_COMPOSITE barcode type handling","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Gs1Handling","title":"SBSDKUI2Gs1Handling","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1handling"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Gs1Handling/validateStructure":{"title":"SBSDKUI2Gs1Handling.validateStructure","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Gs1Handling\/validateStructure","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1handling\/validatestructure","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validateStructure"}],"abstract":[{"text":"Same as PARSE. Additionally, messages containing unknown AI keys, or containing values of incorrect format for","type":"text"},{"type":"text","text":" "},{"text":"known keys, are not returned.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingValidateStructure"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 6.1.0"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2Gs1HandlingValidateStructure"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingValidateStructure"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKUI2Gs1HandlingValidateStructure","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Gs1Handling\/title","op":"replace","value":"SBSDKUI2Gs1Handling"},{"value":[{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Gs1Handling\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Gs1Handling\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Gs1Handling~1validateStructure\/title","value":"SBSDKUI2Gs1HandlingValidateStructure"},{"value":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingValidateStructure"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Gs1Handling~1validateStructure\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}