{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/initwithextractvinfrombarcode:ocrresolutionlimit:maximumnumberofaccumulatedframes:minimumnumberofrequiredframeswithequalscanningresult:"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/initWithExtractVINFromBarcode:ocrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration"]]},"metadata":{"navigatorTitle":[{"text":"initWithExtractVINFromBarcode:ocrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerConfiguration(im)initWithExtractVINFromBarcode:ocrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithExtractVINFromBarcode:ocrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","kind":"identifier"}],"role":"symbol","symbolKind":"method","title":"initWithExtractVINFromBarcode:ocrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithExtractVINFromBarcode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"extractVINFromBarcode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ocrResolutionLimit:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"ocrResolutionLimit"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"maximumNumberOfAccumulatedFrames"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"minimumNumberOfRequiredFramesWithEqualScanningResult","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Configuration for the VIN scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration","title":"SBSDKVINScannerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVINScannerConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVINScannerConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration/initWithExtractVINFromBarcode:ocrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:":{"abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/initWithExtractVINFromBarcode:ocrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","navigatorTitle":[{"kind":"identifier","text":"initWithExtractVINFromBarcode:ocrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:"}],"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/initwithextractvinfrombarcode:ocrresolutionlimit:maximumnumberofaccumulatedframes:minimumnumberofrequiredframeswithequalscanningresult:","title":"initWithExtractVINFromBarcode:ocrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","fragments":[{"kind":"text","text":"- "},{"text":"initWithExtractVINFromBarcode:ocrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/title","value":"SBSDKVINScannerConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVINScannerConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVINScannerConfiguration"}],"op":"replace"}]}]}