{"metadata":{"title":"initWithTextResult:barcodeResult:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerResult(im)initWithTextResult:barcodeResult:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTextResult:barcodeResult:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithTextResult:barcodeResult:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithTextResult:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","text":"SBSDKTextPatternScannerResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"textResult","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeResult:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult","text":"SBSDKVINBarcodeResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINBarcodeResult"},{"text":" *) ","kind":"text"},{"text":"barcodeResult","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerresult\/initwithtextresult:barcoderesult:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerResult\/initWithTextResult:barcodeResult:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerResult"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerResult/initWithTextResult:barcodeResult:":{"abstract":[],"title":"initWithTextResult:barcodeResult:","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerresult\/initwithtextresult:barcoderesult:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTextResult:barcodeResult:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerResult\/initWithTextResult:barcodeResult:","kind":"symbol","navigatorTitle":[{"text":"initWithTextResult:barcodeResult:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerResult":{"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerresult","type":"topic","navigatorTitle":[{"text":"SBSDKVINScannerResult","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Result of the VIN scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerResult","title":"SBSDKVINScannerResult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINScannerResult","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerResult":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTextPatternScannerResult"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The result of the text line recognition."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerResult"}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult","title":"SBSDKTextPatternScannerResult","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeResult":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVINBarcodeResult"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinbarcoderesult","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVINBarcodeResult"}],"abstract":[{"type":"text","text":"Result of the barcode scanner."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult","title":"SBSDKVINBarcodeResult"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerResult\/title","value":"SBSDKVINScannerResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKVINScannerResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVINScannerResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/title","value":"SBSDKTextPatternScannerResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/navigatorTitle","value":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/title","value":"SBSDKVINBarcodeResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/fragments","value":[{"kind":"identifier","text":"SBSDKVINBarcodeResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/navigatorTitle","value":[{"text":"SBSDKVINBarcodeResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}