{"abstract":[{"text":"Informs the delegate that scanning has failed with an error.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(vinScannerViewController:didFailScanningWithError:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"vinScannerViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","kind":"typeIdentifier","text":"SBSDKVINScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailScanning"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The scanner controller that has failed scanning.","type":"text"}]}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error that occurred during scanning."}]}],"name":"error"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate\/vinscannerviewcontroller(_:didfailscanning:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate\/vinscannerviewcontroller(_:didfailscanning:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate\/vinScannerViewController(_:didFailScanning:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"navigatorTitle":[{"text":"vinScannerViewController:didFailScanningWithError:","kind":"identifier"}],"role":"symbol","title":"vinScannerViewController(_:didFailScanning:)","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKVINScannerViewControllerDelegate(im)vinScannerViewController:didFailScanningWithError:","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","required":true,"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vinScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKVINScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerViewController"},{"text":", ","kind":"text"},{"text":"didFailScanning","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewControllerDelegate/vinScannerViewController(_:didFailScanning:)":{"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate\/vinscannerviewcontroller(_:didfailscanning:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"vinScannerViewController:didFailScanningWithError:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate\/vinScannerViewController(_:didFailScanning:)","kind":"symbol","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"vinScannerViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerViewController","text":"SBSDKVINScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailScanning"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"title":"vinScannerViewController(_:didFailScanning:)","abstract":[{"text":"Informs the delegate that scanning has failed with an error.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller","type":"topic","kind":"symbol","title":"SBSDKVINScannerViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the vehicle identification number scanner."}],"navigatorTitle":[{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewControllerDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVINScannerViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVINScannerViewControllerDelegate"}],"title":"SBSDKVINScannerViewControllerDelegate","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The delegation protocol for "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"vinScannerViewController:didFailScanningWithError:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"vinScannerViewController:didFailScanningWithError:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"vinScannerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","text":"SBSDKVINScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didFailScanningWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The scanner controller that has failed scanning."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error that occurred during scanning."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"vinScannerViewController:didFailScanningWithError:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate~1vinScannerViewController(_:didFailScanning:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"vinScannerViewController:didFailScanningWithError:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate~1vinScannerViewController(_:didFailScanning:)\/fragments"},{"value":"SBSDKVINScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKVINScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/fragments"},{"value":[{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/navigatorTitle"},{"value":"SBSDKVINScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate\/title"},{"value":[{"text":"SBSDKVINScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate\/fragments"},{"value":[{"text":"SBSDKVINScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}