{"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s8CopyableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s8SendableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIContentContainer","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIStateRestoring","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIUserActivityRestoring"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"metadata":{"roleHeading":"Class","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeScannerViewController","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","platforms":[],"title":"SBSDKUIBarcodeScannerViewController","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}]},"kind":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to scan QR and barcodes."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/delegate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/isScanningEnabled"],"generated":true,"anchor":"Instance-Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/freezeCamera()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/unfreezeCamera()"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/create(configuration:delegate:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/present(on:configuration:delegate:)"],"generated":true,"anchor":"Type-Methods"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}],"type":"paragraph"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/barcodeScannerController:filterBarcodes:":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/barcodeScannerController:filterBarcodes:","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/barcodescannercontroller:filterbarcodes:","type":"topic","title":"barcodeScannerController:filterBarcodes:","role":"symbol","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"barcodeScannerController:filterBarcodes:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"barcodeScannerController:filterBarcodes:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/enableCameraTextConfiguration":{"type":"topic","kind":"symbol","fragments":[{"text":"enableCameraTextConfiguration","kind":"identifier"}],"title":"enableCameraTextConfiguration","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/enableCameraTextConfiguration","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/enablecameratextconfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/create(configuration:delegate:)":{"type":"topic","kind":"symbol","deprecated":true,"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeScannerConfiguration","text":"SBSDKUIBarcodeScannerConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKUIBarcodeScannerViewControllerDelegate","text":"SBSDKUIBarcodeScannerViewControllerDelegate"},{"text":"?) -> ","kind":"text"},{"text":"SBSDKUIBarcodeScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeScannerViewController"}],"title":"create(configuration:delegate:)","abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/create(configuration:delegate:)","navigatorTitle":[{"text":"createWithConfiguration:delegate:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/create(configuration:delegate:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/enableCameraUIConfiguration":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/enableCameraUIConfiguration","role":"symbol","title":"enableCameraUIConfiguration","fragments":[{"text":"enableCameraUIConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/enablecamerauiconfiguration","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/supportedInterfaceOrientations":{"type":"topic","kind":"symbol","fragments":[{"text":"supportedInterfaceOrientations","kind":"identifier"}],"title":"supportedInterfaceOrientations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/supportedInterfaceOrientations","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/supportedinterfaceorientations"},"doc://net.doo.ScanbotBarcodeScannerSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s8SendableP"},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/viewDidLoad":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/viewDidLoad","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/viewdidload","kind":"symbol","title":"viewDidLoad","role":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIStateRestoring"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/freezeCamera()":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/freezeCamera()","abstract":[{"type":"text","text":"Freezes the cameras preview layer by stopping the camera session."}],"role":"symbol","navigatorTitle":[{"text":"freezeCamera","kind":"identifier"}],"title":"freezeCamera()","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/freezecamera()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"freezeCamera","kind":"identifier"},{"kind":"text","text":"()"}],"deprecated":true,"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIAppearanceContainer"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSExtensionRequestHandling"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIViewController":{"navigatorTitle":[{"text":"SBSDKUIViewController","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIViewController"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewController","abstract":[{"type":"text","text":"An abstract base class for RTU-UI view controllers."}],"role":"symbol","title":"SBSDKUIViewController","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuiviewcontroller"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIContentContainer"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/didCancel":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/didCancel","navigatorTitle":[{"text":"didCancel","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/didcancel","kind":"symbol","title":"didCancel","role":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didCancel"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/didHideEnableCameraView":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/didHideEnableCameraView","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didHideEnableCameraView"}],"type":"topic","navigatorTitle":[{"text":"didHideEnableCameraView","kind":"identifier"}],"abstract":[],"title":"didHideEnableCameraView","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/didhideenablecameraview"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/isScanningEnabled":{"type":"topic","kind":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isScanningEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isScanningEnabled","abstract":[{"type":"text","text":"Enables or disables the barcode scanning."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/isScanningEnabled","navigatorTitle":[{"kind":"identifier","text":"isScanningEnabled"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/isscanningenabled"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/willShowEnableCameraView":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/willShowEnableCameraView","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willShowEnableCameraView"}],"type":"topic","navigatorTitle":[{"text":"willShowEnableCameraView","kind":"identifier"}],"abstract":[],"title":"willShowEnableCameraView","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/willshowenablecameraview"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/viewWillDisappear:":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/viewWillDisappear:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillDisappear:"}],"type":"topic","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"abstract":[],"title":"viewWillDisappear:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/viewwilldisappear:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/unfreezeCamera()":{"type":"topic","kind":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unfreezeCamera","kind":"identifier"},{"text":"()","kind":"text"}],"title":"unfreezeCamera()","abstract":[{"type":"text","text":"Unfreezes the previously frozen cameras preview layer by restarting the camera session."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/unfreezeCamera()","navigatorTitle":[{"kind":"identifier","text":"unfreezeCamera"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/unfreezecamera()"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/updateFlashButton":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/updateFlashButton","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateFlashButton"}],"type":"topic","navigatorTitle":[{"text":"updateFlashButton","kind":"identifier"}],"abstract":[],"title":"updateFlashButton","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/updateflashbutton"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/present(on:configuration:delegate:)":{"type":"topic","kind":"symbol","deprecated":true,"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeScannerConfiguration","text":"SBSDKUIBarcodeScannerConfiguration"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKUIBarcodeScannerViewControllerDelegate","text":"SBSDKUIBarcodeScannerViewControllerDelegate"},{"text":"?) -> ","kind":"text"},{"text":"SBSDKUIBarcodeScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeScannerViewController"}],"title":"present(on:configuration:delegate:)","abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController","type":"reference","isActive":true},{"type":"text","text":" and presents it modally."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/present(on:configuration:delegate:)","navigatorTitle":[{"kind":"identifier","text":"presentOn:configuration:delegate:"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/present(on:configuration:delegate:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/viewDidAppear:":{"role":"symbol","title":"viewDidAppear:","kind":"symbol","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/viewDidAppear:","fragments":[{"kind":"text","text":"- "},{"text":"viewDidAppear:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/viewdidappear:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/didFinish":{"type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didFinish"}],"title":"didFinish","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/didFinish","navigatorTitle":[{"text":"didFinish","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/didfinish"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UITraitEnvironment"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIFocusEnvironment"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/barcodeTrackingOverlay:textStyleFor:":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/barcodeTrackingOverlay:textStyleFor:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"barcodeTrackingOverlay:textStyleFor:"}],"type":"topic","navigatorTitle":[{"text":"barcodeTrackingOverlay:textStyleFor:","kind":"identifier"}],"abstract":[],"title":"barcodeTrackingOverlay:textStyleFor:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/barcodetrackingoverlay:textstylefor:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewControllerDelegate":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewControllerDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontrollerdelegate","title":"SBSDKBarcodeScannerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The delegate protocol of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController"},{"type":"text","text":" that provides methods for"},{"type":"text","text":" "},{"text":"enabling\/disabling scanning and managing scanned barcodes.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/delegate":{"type":"topic","kind":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKUIBarcodeScannerViewControllerDelegate","text":"SBSDKUIBarcodeScannerViewControllerDelegate"},{"kind":"text","text":"?"}],"title":"delegate","abstract":[{"type":"text","text":"The receivers delegate."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/delegate"},"doc://net.doo.ScanbotBarcodeScannerSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/5UIKit23UITraitChangeObservableP"},"doc://net.doo.ScanbotBarcodeScannerSDK/s8CopyableP":{"type":"unresolvable","title":"Swift.Copyable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s8CopyableP"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIUserActivityRestoring"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayControllerDelegate":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate","title":"SBSDKBarcodeTrackingOverlayControllerDelegate","abstract":[{"text":"The delegation protocol for the barcode tracking overlay controller.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/barcodeTrackingOverlay:didTapOnBarcode:":{"type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"barcodeTrackingOverlay:didTapOnBarcode:"}],"title":"barcodeTrackingOverlay:didTapOnBarcode:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/barcodeTrackingOverlay:didTapOnBarcode:","navigatorTitle":[{"text":"barcodeTrackingOverlay:didTapOnBarcode:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/barcodetrackingoverlay:didtaponbarcode:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller","title":"SBSDKUIBarcodeScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to scan QR and barcodes."}],"deprecated":true},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/barcodeScannerControllerShouldScanBarcodes:":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/barcodeScannerControllerShouldScanBarcodes:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"barcodeScannerControllerShouldScanBarcodes:"}],"type":"topic","navigatorTitle":[{"text":"barcodeScannerControllerShouldScanBarcodes:","kind":"identifier"}],"title":"barcodeScannerControllerShouldScanBarcodes:","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/barcodescannercontrollershouldscanbarcodes:"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCoding"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIResponderStandardEditActions"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/barcodeScannerController:didScanBarcodes:":{"type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"barcodeScannerController:didScanBarcodes:"}],"title":"barcodeScannerController:didScanBarcodes:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/barcodeScannerController:didScanBarcodes:","navigatorTitle":[{"text":"barcodeScannerController:didScanBarcodes:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/barcodescannercontroller:didscanbarcodes:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/initWithCoder:":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/initWithCoder:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"type":"topic","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/initwithcoder:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewController":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller","title":"SBSDKBarcodeScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show a camera screen with the barcode scanner.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/barcodeTrackingOverlay:polygonStyleFor:":{"type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"barcodeTrackingOverlay:polygonStyleFor:"}],"title":"barcodeTrackingOverlay:polygonStyleFor:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/barcodeTrackingOverlay:polygonStyleFor:","navigatorTitle":[{"text":"barcodeTrackingOverlay:polygonStyleFor:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/barcodetrackingoverlay:polygonstylefor:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/barcodeTrackingOverlay:didChangeSelectedBarcodes:":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/barcodeTrackingOverlay:didChangeSelectedBarcodes:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"barcodeTrackingOverlay:didChangeSelectedBarcodes:","kind":"identifier"}],"navigatorTitle":[{"text":"barcodeTrackingOverlay:didChangeSelectedBarcodes:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/barcodetrackingoverlay:didchangeselectedbarcodes:","title":"barcodeTrackingOverlay:didChangeSelectedBarcodes:","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUICameraViewController":{"title":"SBSDKUICameraViewController","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuicameraviewcontroller","navigatorTitle":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewController"},{"type":"text","text":" subclass which adds support for enabled and disabled camera permission."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUICameraViewController","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController/containerForEnableCameraView":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/containerForEnableCameraView","role":"symbol","fragments":[{"text":"containerForEnableCameraView","kind":"identifier"}],"type":"topic","title":"containerForEnableCameraView","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller\/containerforenablecameraview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUIBarcodeScannerViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}]},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/containerForEnableCameraView","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/delegate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/enableCameraTextConfiguration","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/enableCameraUIConfiguration","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/isScanningEnabled","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/supportedInterfaceOrientations"],"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/barcodeScannerController:didScanBarcodes:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/barcodeScannerController:filterBarcodes:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/barcodeScannerControllerShouldScanBarcodes:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/barcodeTrackingOverlay:didChangeSelectedBarcodes:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/barcodeTrackingOverlay:didTapOnBarcode:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/barcodeTrackingOverlay:polygonStyleFor:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/barcodeTrackingOverlay:textStyleFor:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/didCancel","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/didFinish","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/didHideEnableCameraView","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/freezeCamera()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/initWithCoder:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/unfreezeCamera()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/updateFlashButton","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/viewDidAppear:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/viewDidLoad","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/viewWillDisappear:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/willShowEnableCameraView"]},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/create(configuration:delegate:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController\/present(on:configuration:delegate:)"],"anchor":"Type-Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate"]}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"},{"text":" : ","kind":"text"},{"text":"SBSDKUICameraViewController","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUICameraViewController"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"createWithConfiguration:delegate:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController~1create(configuration:delegate:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithConfiguration:delegate:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController~1create(configuration:delegate:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController~1freezeCamera()\/title","value":"freezeCamera","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"freezeCamera"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController~1freezeCamera()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/title","value":"SBSDKUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/fragments","value":[{"text":"SBSDKUIViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/navigatorTitle","value":[{"text":"SBSDKUIViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController~1isScanningEnabled\/title","value":"isScanningEnabled","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController~1isScanningEnabled\/fragments","op":"replace","value":[{"text":"isScanningEnabled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController~1unfreezeCamera()\/title","op":"replace","value":"unfreezeCamera"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unfreezeCamera"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController~1unfreezeCamera()\/fragments"},{"value":"presentOn:configuration:delegate:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController~1present(on:configuration:delegate:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"presentOn:configuration:delegate:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController~1present(on:configuration:delegate:)\/fragments"},{"value":"SBSDKBarcodeScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewControllerDelegate\/title","op":"replace"},{"value":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController~1delegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/title","value":"SBSDKBarcodeTrackingOverlayControllerDelegate"},{"op":"replace","value":[{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/fragments"},{"value":[{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/navigatorTitle"},{"value":"SBSDKUIBarcodeScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/title","op":"replace","value":"SBSDKBarcodeScannerViewController"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController\/title","op":"replace","value":"SBSDKUICameraViewController"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUICameraViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUICameraViewController"}],"op":"replace"}]}]}