{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"title":"Conforms To","type":"conformsTo"}],"abstract":[{"text":"The length of the encryption key.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength\/bits128","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength\/bits256"],"title":"Enumeration Cases","generated":true},{"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength\/init(rawValue:)"],"title":"Initializers","generated":true},{"anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"metadata":{"roleHeading":"Enumeration","role":"symbol","title":"SBSDKStorageCryptingKeyLength","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKStorageCryptingKeyLength"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeylength"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeylength"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingKeyLength/bits256":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeylength\/bits256","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength\/bits256","title":"SBSDKStorageCryptingKeyLength.bits256","abstract":[{"type":"text","text":"A key length of 256 bits (32 bytes)."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKStorageCryptingKeyLengthBits256","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bits256","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingKeyLength/bits128":{"title":"SBSDKStorageCryptingKeyLength.bits128","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeylength\/bits128","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bits128"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLengthBits128"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength\/bits128","abstract":[{"text":"A key length of 128 bits (16 bytes) .","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingKeyLength/init(rawValue:)":{"type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(rawValue:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength\/init(rawValue:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeylength\/init(rawvalue:)","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingKeyLength/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeylength\/rawrepresentable-implementations","abstract":[],"role":"collectionGroup"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingKeyLength/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeylength\/equatable-implementations","kind":"article","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength\/Equatable-Implementations","title":"Equatable Implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/s12CaseIterableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s12CaseIterableP","title":"Swift.CaseIterable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingKeyLength":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeylength","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"abstract":[{"text":"The length of the encryption key.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength","title":"SBSDKStorageCryptingKeyLength","navigatorTitle":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKStorageCryptingKeyLength","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength\/bits128","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength\/bits256"],"generated":true,"anchor":"Enumeration-Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength~1bits256\/title","value":"SBSDKStorageCryptingKeyLengthBits256","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength~1bits256\/fragments","value":[{"text":"SBSDKStorageCryptingKeyLengthBits256","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength~1bits128\/title","value":"SBSDKStorageCryptingKeyLengthBits128","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength~1bits128\/fragments","value":[{"text":"SBSDKStorageCryptingKeyLengthBits128","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength\/title","value":"SBSDKStorageCryptingKeyLength","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength\/fragments","value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}