{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickbadgeconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickbadgeconfiguration"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2FindAndPickBadgeConfiguration) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"Configuration of the round badge on find and pick ar layer.","type":"text"}],"metadata":{"roleHeading":"Class","role":"symbol","title":"SBSDKUI2FindAndPickBadgeConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickBadgeConfiguration"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/init()"],"title":"Initializers","anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/completed","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/partiallyScanned","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/rejected"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/toJson(configuration:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Node"],"kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickBadgeConfiguration/fromJsonWithJson:":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickbadgeconfiguration\/fromjsonwithjson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/fromJsonWithJson:","abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickBadgeConfiguration/initWithPartiallyScanned:rejected:completed:":{"type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/initWithPartiallyScanned:rejected:completed:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickbadgeconfiguration\/initwithpartiallyscanned:rejected:completed:","title":"initWithPartiallyScanned:rejected:completed:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithPartiallyScanned:rejected:completed:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPartiallyScanned:rejected:completed:"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying","type":"unresolvable","title":"NSCopying"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickBadgeConfiguration/hash":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/hash","role":"symbol","fragments":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickbadgeconfiguration\/hash","kind":"symbol","title":"hash","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickBadgeConfiguration/init()":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickbadgeconfiguration\/init()","title":"init()","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/init()","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Node":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Node","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Node"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Node","kind":"identifier"}],"type":"topic","abstract":[{"text":"Abstract class for all the configurations.","type":"text"}],"kind":"symbol","role":"symbol","title":"SBSDKUI2Node","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2node"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickBadgeConfiguration/completed":{"type":"topic","navigatorTitle":[{"text":"completed","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Appearance of the badge when a barcode is completed.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickbadgeconfiguration\/completed","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/completed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BadgeStyle","text":"SBSDKUI2BadgeStyle"}],"title":"completed"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickBadgeConfiguration/copyWithZone:":{"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/copyWithZone:","kind":"symbol","title":"copyWithZone:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickbadgeconfiguration\/copywithzone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickBadgeConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration","title":"SBSDKUI2FindAndPickBadgeConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickbadgeconfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration of the round badge on find and pick ar layer."}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickBadgeConfiguration/partiallyScanned":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"partiallyScanned","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2BadgeStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BadgeStyle"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/partiallyScanned","title":"partiallyScanned","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"partiallyScanned"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickbadgeconfiguration\/partiallyscanned","kind":"symbol","abstract":[{"type":"text","text":"Appearance of the badge when a barcode is partially scanned."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickBadgeConfiguration/rejected":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickbadgeconfiguration\/rejected","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/rejected","kind":"symbol","type":"topic","role":"symbol","title":"rejected","navigatorTitle":[{"text":"rejected","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rejected"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BadgeStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BadgeStyle"}],"abstract":[{"type":"text","text":"Appearance of the badge when a barcode is rejected."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickBadgeConfiguration/isEqual:":{"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/isEqual:","title":"isEqual:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickbadgeconfiguration\/isequal:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickBadgeConfiguration/toJson(configuration:)":{"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"title":"toJson(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickbadgeconfiguration\/tojson(configuration:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/toJson(configuration:)","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"SBSDKUI2FindAndPickBadgeConfiguration","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickBadgeConfiguration"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickBadgeConfiguration"}],"op":"replace"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/completed","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/hash","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/partiallyScanned","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/rejected"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/init()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/initWithPartiallyScanned:rejected:completed:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/toJson(configuration:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/fromJsonWithJson:"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Node"]},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying"],"title":"Conforms To","type":"conformsTo"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2FindAndPickBadgeConfiguration"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Node","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Node"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration~1init()\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Node\/title","value":"SBSDKUI2Node"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Node\/fragments","value":[{"text":"SBSDKUI2Node","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Node\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Node"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration~1completed\/title","op":"replace","value":"completed"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration~1completed\/fragments","value":[{"kind":"identifier","text":"completed"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/title","value":"SBSDKUI2FindAndPickBadgeConfiguration"},{"op":"replace","value":[{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickBadgeConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration~1partiallyScanned\/title","value":"partiallyScanned"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration~1partiallyScanned\/fragments","value":[{"kind":"identifier","text":"partiallyScanned"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration~1rejected\/title","op":"replace","value":"rejected"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration~1rejected\/fragments","value":[{"kind":"identifier","text":"rejected"}]},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration~1toJson(configuration:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration~1toJson(configuration:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"op":"replace"}]}]}