{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"title":"SBSDKVideoFrameResolution","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKVideoFrameResolution","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"roleHeading":"Enumeration","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"enum","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"abstract":[{"type":"text","text":"An enum describing the resolution of a video or camera stream."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/UHD","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/auto","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/fullHD","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/photo"]},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/init(rawValue:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"type":"conformsTo","title":"Conforms To"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFrameResolution/fullHD":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullHD","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/fullHD","abstract":[{"type":"text","text":"Select a full HD (1920x1080) video resolution."}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/fullhd","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionFullHD"}],"type":"topic","title":"SBSDKVideoFrameResolution.fullHD"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFrameResolution/init(rawValue:)":{"title":"init(rawValue:)","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/init(rawValue:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/init(rawvalue:)","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFrameResolution/UHD":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/UHD","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/uhd","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UHD"}],"kind":"symbol","title":"SBSDKVideoFrameResolution.UHD","type":"topic","abstract":[{"type":"text","text":"Select a 4k UHD (3840x2160) video resolution."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKVideoFrameResolutionUHD","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFrameResolution/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/rawrepresentable-implementations","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/RawRepresentable-Implementations","type":"topic","abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFrameResolution/photo":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"photo","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/photo","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/photo","title":"SBSDKVideoFrameResolution.photo","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionPhoto"}],"abstract":[{"text":"Select the photo preset for best quality when capturing images.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFrameResolution":{"type":"topic","abstract":[{"type":"text","text":"An enum describing the resolution of a video or camera stream."}],"title":"SBSDKVideoFrameResolution","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFrameResolution/auto":{"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKVideoFrameResolutionAuto","kind":"identifier"}],"abstract":[{"type":"text","text":"Select the video resolution automatically based on device specifics."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/auto","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/auto","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"auto"}],"title":"SBSDKVideoFrameResolution.auto"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFrameResolution/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/Equatable-Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/equatable-implementations","type":"topic","title":"Equatable Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"SBSDKVideoFrameResolution","op":"replace","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/UHD","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/auto","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/fullHD","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/photo"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoFrameResolution","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}]}},{"value":"SBSDKVideoFrameResolutionFullHD","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution~1fullHD\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution~1fullHD\/fragments","value":[{"text":"SBSDKVideoFrameResolutionFullHD","kind":"identifier"}]},{"value":"SBSDKVideoFrameResolutionUHD","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution~1UHD\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution~1UHD\/fragments","value":[{"text":"SBSDKVideoFrameResolutionUHD","kind":"identifier"}],"op":"replace"},{"value":"SBSDKVideoFrameResolutionPhoto","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution~1photo\/title"},{"value":[{"text":"SBSDKVideoFrameResolutionPhoto","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution~1photo\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution\/title","op":"replace","value":"SBSDKVideoFrameResolution"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution\/fragments","value":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution~1auto\/title","value":"SBSDKVideoFrameResolutionAuto"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution~1auto\/fragments","op":"replace","value":[{"text":"SBSDKVideoFrameResolutionAuto","kind":"identifier"}]}]}]}