{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/enableCameraButton","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/enableCameraDescriptionLabel","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/enableCameraImageView"]},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/enableCameraTapped(_:)"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/make()"],"anchor":"Type-Methods","title":"Type Methods"}],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIEnableCameraViewController","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIEnableCameraViewController","navigatorTitle":[{"text":"SBSDKUIEnableCameraViewController","kind":"identifier"}],"roleHeading":"Class","role":"symbol","title":"SBSDKUIEnableCameraViewController","symbolKind":"class"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIEnableCameraViewController","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuienablecameraviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuienablecameraviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)UIViewController"],"type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s8SendableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIContentContainer","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIStateRestoring","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIFocusEnvironment"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIEnableCameraViewController/enableCameraButton":{"abstract":[],"type":"topic","title":"enableCameraButton","navigatorTitle":[{"text":"enableCameraButton","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuienablecameraviewcontroller\/enablecamerabutton","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/enableCameraButton","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableCameraButton"},{"kind":"text","text":": "},{"text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIEnableCameraViewController/enableCameraTapped(_:)":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuienablecameraviewcontroller\/enablecameratapped(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableCameraTapped","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIButton","kind":"typeIdentifier","text":"UIButton"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/enableCameraTapped(_:)","type":"topic","navigatorTitle":[{"text":"enableCameraTapped:","kind":"identifier"}],"abstract":[],"role":"symbol","title":"enableCameraTapped(_:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSExtensionRequestHandling"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIEnableCameraViewController/make()":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/make()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"make","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"SBSDKUIEnableCameraViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIEnableCameraViewController"}],"type":"topic","navigatorTitle":[{"text":"make","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuienablecameraviewcontroller\/make()","kind":"symbol","role":"symbol","title":"make()"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIEnableCameraViewController/initWithCoder:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/initWithCoder:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuienablecameraviewcontroller\/initwithcoder:","kind":"symbol","role":"symbol","title":"initWithCoder:"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCoding"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIResponderStandardEditActions"},"doc://net.doo.ScanbotBarcodeScannerSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/5UIKit23UITraitChangeObservableP"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIEnableCameraViewController":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIEnableCameraViewController"}],"abstract":[],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuienablecameraviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIEnableCameraViewController"}],"title":"SBSDKUIEnableCameraViewController"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s8SendableP","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIStateRestoring","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIContentContainer","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(cs)UIViewController":{"title":"UIViewController","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)UIViewController","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIEnableCameraViewController/enableCameraDescriptionLabel":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/enableCameraDescriptionLabel","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableCameraDescriptionLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"type":"topic","navigatorTitle":[{"text":"enableCameraDescriptionLabel","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuienablecameraviewcontroller\/enablecameradescriptionlabel","kind":"symbol","role":"symbol","title":"enableCameraDescriptionLabel"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIEnableCameraViewController/initWithNibName:bundle:":{"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/initWithNibName:bundle:","abstract":[],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuienablecameraviewcontroller\/initwithnibname:bundle:","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"type":"topic","title":"initWithNibName:bundle:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIEnableCameraViewController/enableCameraImageView":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuienablecameraviewcontroller\/enablecameraimageview","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableCameraImageView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIImageView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/enableCameraImageView","type":"topic","navigatorTitle":[{"text":"enableCameraImageView","kind":"identifier"}],"abstract":[],"role":"symbol","title":"enableCameraImageView"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"SBSDKUIEnableCameraViewController","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKUIEnableCameraViewController"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUIEnableCameraViewController","kind":"identifier"}]},{"value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/enableCameraButton","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/enableCameraDescriptionLabel","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/enableCameraImageView"]},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/enableCameraTapped(_:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/initWithCoder:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/initWithNibName:bundle:"],"anchor":"Instance-Methods"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraViewController\/make()"],"anchor":"Type-Methods","title":"Type Methods"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIEnableCameraViewController","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"enableCameraButton","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraViewController~1enableCameraButton\/title"},{"value":[{"text":"enableCameraButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraViewController~1enableCameraButton\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraViewController~1enableCameraTapped(_:)\/title","value":"enableCameraTapped:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraViewController~1enableCameraTapped(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableCameraTapped:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraViewController~1make()\/title","value":"make","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"make"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraViewController~1make()\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraViewController\/title","op":"replace","value":"SBSDKUIEnableCameraViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIEnableCameraViewController"}]},{"value":[{"text":"SBSDKUIEnableCameraViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraViewController\/navigatorTitle","op":"replace"},{"value":"enableCameraDescriptionLabel","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraViewController~1enableCameraDescriptionLabel\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraViewController~1enableCameraDescriptionLabel\/fragments","value":[{"text":"enableCameraDescriptionLabel","kind":"identifier"}],"op":"replace"},{"value":"enableCameraImageView","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraViewController~1enableCameraImageView\/title"},{"value":[{"text":"enableCameraImageView","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraViewController~1enableCameraImageView\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}