{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefprofile\/initwithrefinfo:imageinfo:imagesource:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefProfile"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefProfile\/initWithRefInfo:imageInfo:imageSource:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRefInfo:imageInfo:imageSource:","kind":"identifier"}],"role":"symbol","title":"initWithRefInfo:imageInfo:imageSource:","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefProfile(im)initWithRefInfo:imageInfo:imageSource:","navigatorTitle":[{"kind":"identifier","text":"initWithRefInfo:imageInfo:imageSource:"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRefInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKRefCountedObjectProfile","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKRefCountedObjectProfile","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRefCountedObjectProfile"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"refInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageProfile","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageProfile","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageProfile"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"imageInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSource:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageSource","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageSource","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageSource"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"imageSource"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKRefCountedObjectProfile":{"abstract":[{"text":"Profile info of a reference-counted stored object.","type":"text"}],"navigatorTitle":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRefCountedObjectProfile","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkrefcountedobjectprofile","type":"topic","role":"symbol","title":"SBSDKRefCountedObjectProfile","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageSource":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagesource","title":"SBSDKImageSource","abstract":[{"type":"text","text":"Description of source from which the ImageRef was created."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageSource"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSource"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageSource","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageProfile":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageProfile"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageProfile"}],"title":"SBSDKImageProfile","abstract":[{"text":"ImageRef profile part specific to image information.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageProfile","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimageprofile","role":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRefProfile/initWithRefInfo:imageInfo:imageSource:":{"title":"initWithRefInfo:imageInfo:imageSource:","navigatorTitle":[{"kind":"identifier","text":"initWithRefInfo:imageInfo:imageSource:"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefProfile\/initWithRefInfo:imageInfo:imageSource:","role":"symbol","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRefInfo:imageInfo:imageSource:"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefprofile\/initwithrefinfo:imageinfo:imagesource:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRefProfile":{"title":"SBSDKImageRefProfile","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefProfile","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefProfile","navigatorTitle":[{"text":"SBSDKImageRefProfile","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"ImageRef profile which provides detailed information about stored object.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefprofile","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRefCountedObjectProfile\/title","value":"SBSDKRefCountedObjectProfile"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRefCountedObjectProfile\/fragments","value":[{"kind":"identifier","text":"SBSDKRefCountedObjectProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRefCountedObjectProfile\/navigatorTitle","value":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageSource\/title","value":"SBSDKImageSource"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageSource\/fragments","value":[{"text":"SBSDKImageSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageSource\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageSource"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageProfile\/title","value":"SBSDKImageProfile"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageProfile\/fragments","value":[{"text":"SBSDKImageProfile","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageProfile\/navigatorTitle","value":[{"text":"SBSDKImageProfile","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefProfile\/title","value":"SBSDKImageRefProfile"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefProfile\/fragments","value":[{"kind":"identifier","text":"SBSDKImageRefProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefProfile\/navigatorTitle","value":[{"text":"SBSDKImageRefProfile","kind":"identifier"}]}]}]}