{"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Operators","generated":true,"anchor":"Operators","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemInfoPosition\/!=(_:_:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemInfoPosition"]]},"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"collectionGroup","title":"Equatable Implementations","roleHeading":"API Collection"},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemInfoPosition\/Equatable-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeiteminfoposition\/equatable-implementations"]}],"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeItemInfoPosition/!=(_:_:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"!=(_:_:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemInfoPosition\/!=(_:_:)","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeiteminfoposition\/!=(_:_:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeItemInfoPosition":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemInfoPosition","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPosition"}],"title":"SBSDKUI2BarcodeItemInfoPosition","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeiteminfoposition","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}],"abstract":[{"type":"text","text":"Where to display the barcode info box in the camera preview."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemInfoPosition\/title","value":"SBSDKUI2BarcodeItemInfoPosition"},{"value":[{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemInfoPosition\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPosition"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemInfoPosition\/navigatorTitle"}]}]}