{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkfieldinvaliddataverificationreport\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldInvalidDataVerificationReport"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldInvalidDataVerificationReport\/hash"},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldInvalidDataVerificationReport(py)hash","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"hash","fragments":[{"text":"hash","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}]},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldInvalidDataVerificationReport/hash":{"fragments":[{"text":"hash","kind":"identifier"}],"title":"hash","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldInvalidDataVerificationReport\/hash","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkfieldinvaliddataverificationreport\/hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldInvalidDataVerificationReport":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldInvalidDataVerificationReport","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKFieldInvalidDataVerificationReport"}],"title":"SBSDKFieldInvalidDataVerificationReport","abstract":[{"text":"Report which shows whether the data in the field that can be validated is valid.","type":"text"}],"navigatorTitle":[{"text":"SBSDKFieldInvalidDataVerificationReport","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfieldinvaliddataverificationreport"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKFieldInvalidDataVerificationReport","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldInvalidDataVerificationReport\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldInvalidDataVerificationReport\/fragments","value":[{"kind":"identifier","text":"SBSDKFieldInvalidDataVerificationReport"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldInvalidDataVerificationReport\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFieldInvalidDataVerificationReport"}],"op":"replace"}]}]}