{"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTag:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tag"},{"kind":"text","text":" "},{"kind":"identifier","text":"name:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"name"},{"kind":"text","text":" "},{"kind":"identifier","text":"value:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldValue","kind":"typeIdentifier","text":"SBSDKUserFieldValue","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUserFieldValue"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserField"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuserfield\/initwithtag:name:value:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserField\/initWithTag:name:value:"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUserField(im)initWithTag:name:value:","roleHeading":"Instance Method","role":"symbol","title":"initWithTag:name:value:","symbolKind":"method","navigatorTitle":[{"text":"initWithTag:name:value:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithTag:name:value:","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUserField":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUserField","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUserField","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuserfield","abstract":[{"type":"text","text":"User-defined TIFF field."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserField","type":"topic","title":"SBSDKUserField","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUserFieldValue":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldValue","role":"symbol","navigatorTitle":[{"text":"SBSDKUserFieldValue","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuserfieldvalue","title":"SBSDKUserFieldValue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUserFieldValue","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"User-defined TIFF field value."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUserField/initWithTag:name:value:":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuserfield\/initwithtag:name:value:","kind":"symbol","title":"initWithTag:name:value:","role":"symbol","type":"topic","navigatorTitle":[{"text":"initWithTag:name:value:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithTag:name:value:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserField\/initWithTag:name:value:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUserField","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserField\/title"},{"op":"replace","value":[{"text":"SBSDKUserField","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserField\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserField\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUserField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldValue\/title","value":"SBSDKUserFieldValue"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldValue\/fragments","value":[{"kind":"identifier","text":"SBSDKUserFieldValue"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldValue\/navigatorTitle","value":[{"text":"SBSDKUserFieldValue","kind":"identifier"}]}]}]}