{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult\/isScanningStatusOK"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isScanningStatusOK","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isScanningStatusOK"}],"role":"symbol","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult(py)isScanningStatusOK","extendedModule":"ScanbotSDK","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"isScanningStatusOK","roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult\/isscanningstatusok"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult\/isscanningstatusok"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isScanningStatusOK"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Returns "},{"code":"true","type":"codeVoice"},{"text":" if the status of the scanning is any of the OK-statuses, ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionResult":{"title":"SBSDKDocumentDetectionResult","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","abstract":[{"type":"text","text":"Result of the document contour detection."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionResult/isScanningStatusOK":{"title":"isScanningStatusOK","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isScanningStatusOK"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isScanningStatusOK","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"text":" if the status of the scanning is any of the OK-statuses, ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" otherwise."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult\/isscanningstatusok","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult\/isScanningStatusOK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"isScanningStatusOK"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"isScanningStatusOK","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"isScanningStatusOK","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":"SBSDKDocumentDetectionResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/fragments","value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}]},{"value":"isScanningStatusOK","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult~1isScanningStatusOK\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"isScanningStatusOK"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult~1isScanningStatusOK\/fragments"}]}]}