{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(polygon:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyCrop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"polygon","content":[{"inlineContent":[{"type":"text","text":"The polygon to be applied."}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Crops the input image by the given polygon and performs perspective correction.","type":"text"}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"method","title":"applyCrop(polygon:)","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageProcessor(im)applyCropWithPolygon:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyCrop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"applyCropWithPolygon:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applycrop(polygon:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applycrop(polygon:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"kind":"symbol","role":"symbol","type":"topic","title":"SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","url":"\/documentation\/scanbotsdk\/sbsdkpolygon","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/applyCrop(polygon:)":{"abstract":[{"text":"Crops the input image by the given polygon and performs perspective correction.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(polygon:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applycrop(polygon:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyCrop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"text":"?)","kind":"text"}],"title":"applyCrop(polygon:)","navigatorTitle":[{"text":"applyCropWithPolygon:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor":{"url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor","abstract":[{"type":"text","text":"A class to process images."}],"type":"topic","title":"SBSDKImageProcessor","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageProcessor"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageProcessor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"applyCropWithPolygon:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"applyCropWithPolygon:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"applyCropWithPolygon:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"polygon","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"The polygon to be applied.","type":"text"}],"type":"paragraph"}],"name":"polygon"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SBSDKPolygon","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title"},{"value":[{"text":"SBSDKPolygon","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments"},{"value":[{"text":"SBSDKPolygon","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/navigatorTitle"},{"value":"applyCropWithPolygon:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyCrop(polygon:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"applyCropWithPolygon:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyCrop(polygon:)\/fragments"},{"value":"SBSDKImageProcessor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/title"},{"value":[{"text":"SBSDKImageProcessor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKImageProcessor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/navigatorTitle"}]}]}