{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithRegexFilter:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"regexFilter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumSizeScore:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimumSizeScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"addAdditionalQuietZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"addAdditionalQuietZone","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimum1DQuietZoneSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimum1DQuietZoneSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"gs1Handling:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling","text":"SBSDKGS1Handling","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1Handling","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"gs1Handling","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumTextLength:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimumTextLength","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maximumTextLength:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"maximumTextLength","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode128Configuration"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode128Configuration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:gs1Handling:minimumTextLength:maximumTextLength:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcode128configuration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:minimumnumberofrequiredframeswithequalrecognitionresult:gs1handling:minimumtextlength:maximumtextlength:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:gs1Handling:minimumTextLength:maximumTextLength:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:gs1Handling:minimumTextLength:maximumTextLength:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:gs1Handling:minimumTextLength:maximumTextLength:"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatCode128Configuration(im)initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:gs1Handling:minimumTextLength:maximumTextLength:","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling":{"title":"SBSDKGS1Handling","abstract":[{"type":"text","text":"GS1 message handling options."},{"type":"text","text":" "},{"type":"text","text":"The GS1 standard defines a key-value format for business-centric data that can be encoded into many 1D and 2D"},{"type":"text","text":" "},{"type":"text","text":"barcode types."},{"type":"text","text":" "},{"type":"text","text":"https:\/\/ref.gs1.org\/standards\/genspecs\/"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGS1Handling","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatCode128Configuration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCode128Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatCode128Configuration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcode128configuration","title":"SBSDKBarcodeFormatCode128Configuration","abstract":[{"type":"text","text":"Code 128 barcode configuration. Add to scanner configuration to scan Code 128 barcodes."}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode128Configuration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatCode128Configuration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:gs1Handling:minimumTextLength:maximumTextLength:":{"navigatorTitle":[{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:gs1Handling:minimumTextLength:maximumTextLength:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode128Configuration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:gs1Handling:minimumTextLength:maximumTextLength:","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcode128configuration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:minimumnumberofrequiredframeswithequalrecognitionresult:gs1handling:minimumtextlength:maximumtextlength:","abstract":[],"kind":"symbol","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:gs1Handling:minimumTextLength:maximumTextLength:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:gs1Handling:minimumTextLength:maximumTextLength:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/title","value":"SBSDKGS1Handling","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/fragments","value":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode128Configuration\/title","value":"SBSDKBarcodeFormatCode128Configuration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode128Configuration\/fragments","value":[{"text":"SBSDKBarcodeFormatCode128Configuration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode128Configuration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatCode128Configuration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}