{"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientationMask","text":"UIInterfaceOrientationMask"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedInterfaceOrientations"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewController"]]},"sections":[],"metadata":{"roleHeading":"Instance Property","title":"supportedInterfaceOrientations","symbolKind":"property","fragments":[{"kind":"identifier","text":"supportedInterfaceOrientations"}],"navigatorTitle":[{"kind":"identifier","text":"supportedInterfaceOrientations"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerViewController(py)supportedInterfaceOrientations"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontroller\/supportedinterfaceorientations"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewController\/supportedInterfaceOrientations"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerViewController":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontroller","abstract":[{"text":"A highly customizable camera-based view controller to recognize and validate vehicle identification numbers in realtime.","type":"text"}],"role":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIVINScannerViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIVINScannerViewController"}],"title":"SBSDKUIVINScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewController","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerViewController/supportedInterfaceOrientations":{"type":"topic","fragments":[{"kind":"identifier","text":"supportedInterfaceOrientations"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewController\/supportedInterfaceOrientations","title":"supportedInterfaceOrientations","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontroller\/supportedinterfaceorientations","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewController\/title","op":"replace","value":"SBSDKUIVINScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKUIVINScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIVINScannerViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}