{"metadata":{"symbolKind":"init","title":"init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:)","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingScreenConfiguration(im)initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topBarBackButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topBarTitle"},{"text":": ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText"},{"text":", ","kind":"text"},{"text":"topBarConfirmButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"text":", ","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"croppingHandlerColor"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"text":"croppingPolygonColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"croppingPolygonMagneticLineColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingBottomBar","text":"SBSDKUI2CroppingBottomBar"},{"kind":"text","text":")"}],"role":"symbol","roleHeading":"Initializer","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:","kind":"identifier"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingScreenConfiguration\/init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingScreenConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"topBarBackButton"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"text":" = SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                            text: \"?croppingTopBarCancelButtonTitle\",\n                                                                                            accessibilityDescription: \"?accessibilityDescriptionCroppingTopBarCancelButton\",\n                                                                                            background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                           isArgb: false),\n                                                                                                                                fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                                strokeWidth: 0.0),\n                                                                                            foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                                color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                                useShadow: false)), ","kind":"text"},{"text":"topBarTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText"},{"text":" = SBSDKUI2StyledText(text: \"?croppingScreenTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)), ","kind":"text"},{"text":"topBarConfirmButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" = SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                               text: \"?croppingTopBarConfirmButtonTitle\",\n                                                                                               accessibilityDescription: \"?accessibilityDescriptionCroppingTopBarConfirmButton\",\n                                                                                               background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                              isArgb: false),\n                                                                                                                                   fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                            isArgb: false),\n                                                                                                                                   strokeWidth: 0.0),\n                                                                                               foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                                   color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                        isArgb: false),\n                                                                                                                                   useShadow: false)), "},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" = SBSDKUI2Color(colorString: \"?sbColorOutline\", isArgb: false), ","kind":"text"},{"kind":"externalParam","text":"croppingHandlerColor"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" = SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false), ","kind":"text"},{"text":"croppingPolygonColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" = SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false), "},{"text":"croppingPolygonMagneticLineColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" = SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                isArgb: false), "},{"text":"bottomBar","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingBottomBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingBottomBar","text":"SBSDKUI2CroppingBottomBar"},{"text":" = SBSDKUI2CroppingBottomBar())","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingscreenconfiguration\/init(topbarbackbutton:topbartitle:topbarconfirmbutton:backgroundcolor:croppinghandlercolor:croppingpolygoncolor:croppingpolygonmagneticlinecolor:bottombar:)"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingscreenconfiguration\/init(topbarbackbutton:topbartitle:topbarconfirmbutton:backgroundcolor:croppinghandlercolor:croppingpolygoncolor:croppingpolygonmagneticlinecolor:bottombar:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingScreenConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingscreenconfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingScreenConfiguration","title":"SBSDKUI2CroppingScreenConfiguration","navigatorTitle":[{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the screen for cropping the scanned pages."}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingScreenConfiguration/init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"topBarBackButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"topBarTitle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topBarConfirmButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"backgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"croppingHandlerColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"croppingPolygonColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"croppingPolygonMagneticLineColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottomBar"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CroppingBottomBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingBottomBar"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:","kind":"identifier"}],"type":"topic","title":"init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:)","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingScreenConfiguration\/init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:)","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingscreenconfiguration\/init(topbarbackbutton:topbartitle:topbarconfirmbutton:backgroundcolor:croppinghandlercolor:croppingpolygoncolor:croppingpolygonmagneticlinecolor:bottombar:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ButtonConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"abstract":[{"text":"Configuration of the button.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"role":"symbol","title":"SBSDKUI2ButtonConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2buttonconfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2StyledText":{"abstract":[{"text":"Configuration of the text field appearance.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"type":"topic","title":"SBSDKUI2StyledText","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2styledtext"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Color":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2Color"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2color","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}],"title":"SBSDKUI2Color","type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingBottomBar":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CroppingBottomBar"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingbottombar","type":"topic","abstract":[{"type":"text","text":"Configuration of the bottom bar for the cropping screen."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingBottomBar"}],"title":"SBSDKUI2CroppingBottomBar","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingBottomBar","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithTopBarBackButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" *) "},{"text":"topBarBackButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topBarTitle:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"topBarTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarConfirmButton:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topBarConfirmButton"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundColor:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"kind":"text","text":" *) "},{"text":"backgroundColor","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingHandlerColor:"},{"kind":"text","text":"("},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"croppingHandlerColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"croppingPolygonColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"croppingPolygonColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"croppingPolygonMagneticLineColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"croppingPolygonMagneticLineColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBar:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2CroppingBottomBar","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingBottomBar","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingBottomBar"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bottomBar"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingScreenConfiguration\/title","value":"SBSDKUI2CroppingScreenConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CroppingScreenConfiguration"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2CroppingScreenConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingScreenConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingScreenConfiguration~1init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:)\/title","value":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingScreenConfiguration~1init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/title","value":"SBSDKUI2ButtonConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/title","value":"SBSDKUI2StyledText","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}]},{"value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/title","op":"replace","value":"SBSDKUI2Color"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/navigatorTitle","value":[{"text":"SBSDKUI2Color","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingBottomBar\/title","value":"SBSDKUI2CroppingBottomBar","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingBottomBar\/fragments","value":[{"text":"SBSDKUI2CroppingBottomBar","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKUI2CroppingBottomBar","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingBottomBar\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}