{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingScreenConfiguration\/init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:bottomBar:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topBarBackButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration"},{"text":" = SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                            text: \"?croppingTopBarCancelButtonTitle\",\n                                                                                            accessibilityDescription: \"?accessibilityDescriptionCroppingTopBarCancelButton\",\n                                                                                            background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                           isArgb: false),\n                                                                                                                                fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                                strokeWidth: 0.0),\n                                                                                            foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                                color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                                useShadow: false)), ","kind":"text"},{"kind":"externalParam","text":"topBarTitle"},{"kind":"text","text":": "},{"text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText"},{"text":" = SBSDKUI2StyledText(text: \"?croppingScreenTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)), ","kind":"text"},{"kind":"externalParam","text":"topBarConfirmButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"text":" = SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                               text: \"?croppingTopBarConfirmButtonTitle\",\n                                                                                               accessibilityDescription: \"?accessibilityDescriptionCroppingTopBarConfirmButton\",\n                                                                                               background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                              isArgb: false),\n                                                                                                                                   fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                            isArgb: false),\n                                                                                                                                   strokeWidth: 0.0),\n                                                                                               foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                                   color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                        isArgb: false),\n                                                                                                                                   useShadow: false)), ","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" = SBSDKUI2Color(colorString: \"?sbColorOutline\", isArgb: false), ","kind":"text"},{"kind":"externalParam","text":"croppingHandlerColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"text":" = SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false), ","kind":"text"},{"kind":"externalParam","text":"croppingPolygonColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"text":" = SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false), ","kind":"text"},{"text":"bottomBar","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2CroppingBottomBar","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingBottomBar","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingBottomBar","kind":"typeIdentifier"},{"text":" = SBSDKUI2CroppingBottomBar())","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingscreenconfiguration\/init(topbarbackbutton:topbartitle:topbarconfirmbutton:backgroundcolor:croppinghandlercolor:croppingpolygoncolor:bottombar:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingscreenconfiguration\/init(topbarbackbutton:topbartitle:topbarconfirmbutton:backgroundcolor:croppinghandlercolor:croppingpolygoncolor:bottombar:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingScreenConfiguration"]]},"metadata":{"title":"init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:bottomBar:)","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingScreenConfiguration(im)initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:bottomBar:","roleHeading":"Initializer","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"topBarBackButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topBarTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"kind":"text","text":", "},{"text":"topBarConfirmButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"backgroundColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"croppingHandlerColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"croppingPolygonColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingBottomBar","text":"SBSDKUI2CroppingBottomBar"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:bottomBar:"}]},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingBottomBar":{"abstract":[{"type":"text","text":"Configuration of the bottom bar for the cropping screen."}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingbottombar","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CroppingBottomBar"}],"title":"SBSDKUI2CroppingBottomBar","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingBottomBar","navigatorTitle":[{"text":"SBSDKUI2CroppingBottomBar","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ButtonConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","title":"SBSDKUI2ButtonConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2buttonconfiguration","abstract":[{"type":"text","text":"Button configuration."}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2StyledText":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","title":"SBSDKUI2StyledText","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2styledtext","kind":"symbol","type":"topic","abstract":[{"text":"Configuration of the text field appearance.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingScreenConfiguration":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration of the screen for cropping the scanned pages.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingScreenConfiguration","title":"SBSDKUI2CroppingScreenConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingscreenconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingScreenConfiguration/init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:bottomBar:)":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:bottomBar:"}],"title":"init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:bottomBar:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingScreenConfiguration\/init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:bottomBar:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"topBarBackButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topBarTitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"topBarConfirmButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"croppingHandlerColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"croppingPolygonColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bottomBar","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CroppingBottomBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingBottomBar"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingscreenconfiguration\/init(topbarbackbutton:topbartitle:topbarconfirmbutton:backgroundcolor:croppinghandlercolor:croppingpolygoncolor:bottombar:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Color":{"role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2Color"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2color","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","title":"SBSDKUI2Color","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:bottomBar:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:bottomBar:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithTopBarBackButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topBarBackButton"},{"text":" ","kind":"text"},{"text":"topBarTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"topBarTitle"},{"kind":"text","text":" "},{"text":"topBarConfirmButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"topBarConfirmButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"backgroundColor:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"backgroundColor"},{"kind":"text","text":" "},{"text":"croppingHandlerColor:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" *) "},{"text":"croppingHandlerColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"croppingPolygonColor:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"croppingPolygonColor","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBar:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingBottomBar","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingBottomBar","text":"SBSDKUI2CroppingBottomBar","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bottomBar"},{"kind":"text","text":";"}]}]}},{"value":"SBSDKUI2CroppingBottomBar","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingBottomBar\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingBottomBar\/fragments","value":[{"text":"SBSDKUI2CroppingBottomBar","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingBottomBar\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CroppingBottomBar"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/title","value":"SBSDKUI2ButtonConfiguration","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/title","value":"SBSDKUI2StyledText","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/fragments","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingScreenConfiguration\/title","value":"SBSDKUI2CroppingScreenConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CroppingScreenConfiguration"}],"op":"replace"},{"value":[{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingScreenConfiguration\/navigatorTitle","op":"replace"},{"value":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:bottomBar:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingScreenConfiguration~1init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:bottomBar:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingScreenConfiguration~1init(topBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:bottomBar:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:bottomBar:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/title","op":"replace","value":"SBSDKUI2Color"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Color"}]},{"op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}