{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeHumanReadableString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkidcardpdf417documentfield\/typehumanreadablestring"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkidcardpdf417documentfield\/typehumanreadablestring"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIDCardPDF417DocumentField\/typeHumanReadableString","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Human-readable field type name."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeHumanReadableString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"typeHumanReadableString","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKIDCardPDF417DocumentField(py)typeHumanReadableString","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"typeHumanReadableString"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIDCardPDF417DocumentField"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIDCardPDF417DocumentField":{"role":"symbol","title":"SBSDKIDCardPDF417DocumentField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentField"}],"abstract":[{"type":"text","text":"The ID card field description."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIDCardPDF417DocumentField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentField"}],"url":"\/documentation\/scanbotsdk\/sbsdkidcardpdf417documentfield"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIDCardPDF417DocumentField/typeHumanReadableString":{"role":"symbol","title":"typeHumanReadableString","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeHumanReadableString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Human-readable field type name."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIDCardPDF417DocumentField\/typeHumanReadableString","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"typeHumanReadableString"}],"url":"\/documentation\/scanbotsdk\/sbsdkidcardpdf417documentfield\/typehumanreadablestring"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"typeHumanReadableString"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"typeHumanReadableString"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"typeHumanReadableString"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIDCardPDF417DocumentField\/title","value":"SBSDKIDCardPDF417DocumentField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIDCardPDF417DocumentField\/fragments","value":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentField"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIDCardPDF417DocumentField~1typeHumanReadableString\/title","value":"typeHumanReadableString"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIDCardPDF417DocumentField~1typeHumanReadableString\/fragments","value":[{"kind":"identifier","text":"typeHumanReadableString"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}