{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hospitalId"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplandoctorfieldtype\/hospitalid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplandoctorfieldtype\/hospitalid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanDoctorFieldType\/hospitalId","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Hospital ID"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hospitalId"}],"title":"SBSDKUI2MedicalPlanDoctorFieldType.hospitalId","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MedicalPlanDoctorFieldType@SBSDKUI2MedicalPlanDoctorFieldTypeHospitalId","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanDoctorFieldTypeHospitalId"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanDoctorFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanDoctorFieldType":{"role":"symbol","title":"SBSDKUI2MedicalPlanDoctorFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanDoctorFieldType"}],"abstract":[{"type":"text","text":"Medical Plan Doctor Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanDoctorFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanDoctorFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplandoctorfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.2"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanDoctorFieldType/hospitalId":{"role":"symbol","title":"SBSDKUI2MedicalPlanDoctorFieldType.hospitalId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hospitalId"}],"abstract":[{"type":"text","text":"Hospital ID"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanDoctorFieldType\/hospitalId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanDoctorFieldTypeHospitalId"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplandoctorfieldtype\/hospitalid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2MedicalPlanDoctorFieldTypeHospitalId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanDoctorFieldTypeHospitalId"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanDoctorFieldTypeHospitalId"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanDoctorFieldType\/title","value":"SBSDKUI2MedicalPlanDoctorFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanDoctorFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanDoctorFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanDoctorFieldType~1hospitalId\/title","value":"SBSDKUI2MedicalPlanDoctorFieldTypeHospitalId"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanDoctorFieldType~1hospitalId\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanDoctorFieldTypeHospitalId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}