{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentquality\/reasonable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentquality\/reasonable"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Reasonable quality.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality\/reasonable"},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"reasonable","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQuality(cpy)reasonable","role":"symbol","title":"reasonable","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"reasonable","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQuality"}],"roleHeading":"Type Property"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"reasonable","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQuality","text":"SBSDKDocumentQuality","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQuality/reasonable":{"abstract":[{"text":"Reasonable quality.","type":"text"}],"kind":"symbol","title":"reasonable","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality\/reasonable","url":"\/documentation\/scanbotsdk\/sbsdkdocumentquality\/reasonable","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reasonable","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKDocumentQuality","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQuality","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"reasonable","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQuality":{"role":"symbol","title":"SBSDKDocumentQuality","navigatorTitle":[{"text":"SBSDKDocumentQuality","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentQuality"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality","url":"\/documentation\/scanbotsdk\/sbsdkdocumentquality","abstract":[{"text":"Result of document quality analysis.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"reasonable"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"reasonable","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQuality","text":"SBSDKDocumentQuality"},{"kind":"text","text":" * "},{"text":"reasonable","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality~1reasonable\/title","value":"reasonable"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality~1reasonable\/fragments","value":[{"kind":"identifier","text":"reasonable"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/title","value":"SBSDKDocumentQuality"},{"op":"replace","value":[{"text":"SBSDKDocumentQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentQuality"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/navigatorTitle"}]}]}