{"abstract":[{"text":"A preview ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" of the document image including applied rotations, polygon and the given filter in a resolution matching the devices screen."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage\/documentPreviewImage(usingParametricFilters:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPreviewImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"usingParametricFilters","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"filters","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter"},{"text":"]?) -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The array of parametric filters the preview image should be generated with or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}],"name":"filters"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The generated preview image or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the image could not be generated.","type":"text"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"documentPreviewImage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"usingParametricFilters"},{"text":": [","kind":"text"},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentPage(im)documentPreviewImageUsingParametricFilters:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","title":"documentPreviewImage(usingParametricFilters:)","navigatorTitle":[{"text":"documentPreviewImageUsingParametricFilters:","kind":"identifier"}],"symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpage\/documentpreviewimage(usingparametricfilters:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpage\/documentpreviewimage(usingparametricfilters:)"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPage/documentPreviewImage(usingParametricFilters:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage\/documentPreviewImage(usingParametricFilters:)","type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpage\/documentpreviewimage(usingparametricfilters:)","role":"symbol","title":"documentPreviewImage(usingParametricFilters:)","navigatorTitle":[{"kind":"identifier","text":"documentPreviewImageUsingParametricFilters:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPreviewImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"usingParametricFilters","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"text":"A preview ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"text":" of the document image including applied rotations, polygon and the given filter in a resolution matching the devices screen.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPage":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPage","kind":"identifier"}],"type":"topic","role":"symbol","title":"SBSDKDocumentPage","abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpage"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter","type":"topic","navigatorTitle":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","abstract":[{"text":"The abstract class of each parametric filter.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKParametricFilter","kind":"identifier"}],"title":"SBSDKParametricFilter","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"documentPreviewImageUsingParametricFilters:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"documentPreviewImageUsingParametricFilters:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":" *) ","kind":"text"},{"text":"documentPreviewImageUsingParametricFilters:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<SBSDKParametricFilter *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"filters","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","value":"documentPreviewImageUsingParametricFilters:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage~1documentPreviewImage(usingParametricFilters:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"documentPreviewImageUsingParametricFilters:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage~1documentPreviewImage(usingParametricFilters:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/title","value":"SBSDKDocumentPage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/fragments","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/title","value":"SBSDKParametricFilter","op":"replace"},{"value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/fragments"}]}]}