{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentpolygonconfiguration\/initwithvisibility:documentok:documentnotok:autosnapprogress:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithVisibility:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceVisibility","text":"SBSDKUI2UserGuidanceVisibility","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2UserGuidanceVisibility"},{"kind":"text","text":") "},{"kind":"internalParam","text":"visibility"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentOk:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","kind":"typeIdentifier","text":"SBSDKUI2PolygonStyle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentOk"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentNotOk:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","kind":"typeIdentifier","text":"SBSDKUI2PolygonStyle"},{"kind":"text","text":" *) "},{"text":"documentNotOk","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"autoSnapProgress:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle"},{"text":" *) ","kind":"text"},{"text":"autoSnapProgress","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVisibility:documentOk:documentNotOk:autoSnapProgress:"}],"title":"initWithVisibility:documentOk:documentNotOk:autoSnapProgress:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentPolygonConfiguration(im)initWithVisibility:documentOk:documentNotOk:autoSnapProgress:","navigatorTitle":[{"text":"initWithVisibility:documentOk:documentNotOk:autoSnapProgress:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","symbolKind":"method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration\/initWithVisibility:documentOk:documentNotOk:autoSnapProgress:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentPolygonConfiguration/initWithVisibility:documentOk:documentNotOk:autoSnapProgress:":{"abstract":[],"title":"initWithVisibility:documentOk:documentNotOk:autoSnapProgress:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithVisibility:documentOk:documentNotOk:autoSnapProgress:"}],"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVisibility:documentOk:documentNotOk:autoSnapProgress:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentpolygonconfiguration\/initwithvisibility:documentok:documentnotok:autosnapprogress:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration\/initWithVisibility:documentOk:documentNotOk:autoSnapProgress:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentPolygonConfiguration":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentPolygonConfiguration"}],"title":"SBSDKUI2DocumentPolygonConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentpolygonconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentPolygonConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the document contour detection polygon."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PolygonStyle":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the polygon appearance."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","url":"\/documentation\/scanbotsdk\/sbsdkui2polygonstyle","title":"SBSDKUI2PolygonStyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceVisibility":{"title":"SBSDKUI2UserGuidanceVisibility","type":"topic","abstract":[{"text":"Determines the visibility mode for the document capturing user guidance labels.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibility"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancevisibility","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibility"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceVisibility","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentPolygonConfiguration\/title","op":"replace","value":"SBSDKUI2DocumentPolygonConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentPolygonConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2DocumentPolygonConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentPolygonConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentPolygonConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/title","op":"replace","value":"SBSDKUI2PolygonStyle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/fragments","op":"replace","value":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility\/title","op":"replace","value":"SBSDKUI2UserGuidanceVisibility"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibility"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibility"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}