{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"No license has been installed. The trial mode ended.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/notSet","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notSet","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus\/notset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus\/notset"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notSet","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKLicenseStatusNotSet","kind":"identifier"}],"title":"SBSDKLicenseStatus.notSet","symbolKind":"case","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKLicenseStatus@SBSDKLicenseStatusNotSet","roleHeading":"Case","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus":{"title":"SBSDKLicenseStatus","type":"topic","abstract":[{"type":"text","text":"The status of the ScanbotSDK license."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus","navigatorTitle":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseStatus","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus/notSet":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus\/notset","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/notSet","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notSet","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKLicenseStatusNotSet","kind":"identifier"}],"title":"SBSDKLicenseStatus.notSet","role":"symbol","type":"topic","abstract":[{"text":"No license has been installed. The trial mode ended.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKLicenseStatusNotSet"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatusNotSet"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKLicenseStatusNotSet"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus\/title","op":"replace","value":"SBSDKLicenseStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus\/fragments","op":"replace","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus\/navigatorTitle","op":"replace","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1notSet\/title","op":"replace","value":"SBSDKLicenseStatusNotSet"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1notSet\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatusNotSet"}]}]}]}