{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageImageSource"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageImageSource\/init(rawValue:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpageimagesource\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"metadata":{"role":"symbol","externalID":"s:10ScanbotSDK20SBSDKPageImageSourceO8rawValueACSgSi_tcfc","roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"title":"init(rawValue:)","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageImageSource/init(rawValue:)":{"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageImageSource\/init(rawValue:)","url":"\/documentation\/scanbotsdk\/sbsdkpageimagesource\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageImageSource":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPageImageSource","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpageimagesource","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageImageSource"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageImageSource","abstract":[{"text":"The source of an image.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","title":"SBSDKPageImageSource"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageImageSource\/title","value":"SBSDKPageImageSource","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPageImageSource"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageImageSource\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageImageSource\/navigatorTitle","value":[{"text":"SBSDKPageImageSource","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}