{"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKPageImageSource@SBSDKPageImageSourceUndefined","navigatorTitle":[{"text":"SBSDKPageImageSourceUndefined","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"undefined","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKPageImageSource.undefined","role":"symbol","symbolKind":"case","roleHeading":"Case"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"undefined","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageImageSource"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The source of the image is not known."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpageimagesource\/undefined"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpageimagesource\/undefined"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageImageSource\/undefined"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageImageSource/undefined":{"navigatorTitle":[{"text":"SBSDKPageImageSourceUndefined","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"undefined"}],"title":"SBSDKPageImageSource.undefined","url":"\/documentation\/scanbotsdk\/sbsdkpageimagesource\/undefined","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageImageSource\/undefined","abstract":[{"type":"text","text":"The source of the image is not known."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageImageSource":{"title":"SBSDKPageImageSource","url":"\/documentation\/scanbotsdk\/sbsdkpageimagesource","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageImageSource","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"The source of an image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageImageSource"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageImageSource"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"SBSDKPageImageSourceUndefined","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKPageImageSourceUndefined","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKPageImageSourceUndefined","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"SBSDKPageImageSourceUndefined","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageImageSource~1undefined\/title"},{"value":[{"text":"SBSDKPageImageSourceUndefined","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageImageSource~1undefined\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageImageSource\/title","value":"SBSDKPageImageSource"},{"value":[{"text":"SBSDKPageImageSource","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageImageSource\/fragments","op":"replace"}]}]}