{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanningMode\/live"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"live"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanningMode"]]},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZScanningModeLive"}],"roleHeading":"Case","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKMRZScanningMode@SBSDKMRZScanningModeLive","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"live"}],"symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKMRZScanningMode.live"},"abstract":[{"type":"text","text":"The scanner will merge all information from multiple frames to provide the best possible result."},{"text":" ","type":"text"},{"text":"Use this mode when the input is a video or camera stream.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscanningmode\/live"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscanningmode\/live"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScanningMode/live":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanningMode\/live","title":"SBSDKMRZScanningMode.live","navigatorTitle":[{"text":"SBSDKMRZScanningModeLive","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"live"}],"abstract":[{"type":"text","text":"The scanner will merge all information from multiple frames to provide the best possible result."},{"text":" ","type":"text"},{"text":"Use this mode when the input is a video or camera stream.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzscanningmode\/live"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScanningMode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMRZScanningMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZScanningMode"}],"role":"symbol","title":"SBSDKMRZScanningMode","url":"\/documentation\/scanbotsdk\/sbsdkmrzscanningmode","kind":"symbol","abstract":[{"type":"text","text":"The scanning mode."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanningMode","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKMRZScanningModeLive"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKMRZScanningModeLive","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKMRZScanningModeLive","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanningMode~1live\/title","value":"SBSDKMRZScanningModeLive"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanningMode~1live\/fragments","value":[{"text":"SBSDKMRZScanningModeLive","kind":"identifier"}]},{"value":"SBSDKMRZScanningMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanningMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMRZScanningMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanningMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanningMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKMRZScanningMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}