{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardintrocustomimage\/isequal:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroCustomImage"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardIntroCustomImage(im)isEqual:","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"isEqual:"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"isEqual:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroCustomImage\/isEqual:"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroCustomImage/isEqual:":{"title":"isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroCustomImage\/isEqual:","abstract":[],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintrocustomimage\/isequal:","fragments":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroCustomImage":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintrocustomimage","title":"SBSDKUI2CreditCardIntroCustomImage","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2CreditCardIntroCustomImage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroCustomImage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardIntroCustomImage","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A custom image for the introduction screen.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroCustomImage\/title","value":"SBSDKUI2CreditCardIntroCustomImage"},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardIntroCustomImage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroCustomImage\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroCustomImage\/navigatorTitle","value":[{"text":"SBSDKUI2CreditCardIntroCustomImage","kind":"identifier"}],"op":"replace"}]}]}