{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkencryptionmode\/disabled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkencryptionmode\/disabled"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionModeDisabled"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKEncryptionMode@SBSDKEncryptionModeDisabled","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disabled"}],"role":"symbol","roleHeading":"Case","symbolKind":"case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"SBSDKEncryptionMode.disabled"},"abstract":[{"text":"Encryption\/Decryption is not used when loading\/saving an image.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disabled"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode\/disabled","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncryptionMode/disabled":{"title":"SBSDKEncryptionMode.disabled","abstract":[{"type":"text","text":"Encryption\/Decryption is not used when loading\/saving an image."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"disabled","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionModeDisabled"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencryptionmode\/disabled","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode\/disabled"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncryptionMode":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"abstract":[{"type":"text","text":"Encryption\/Decryption mode to be used when an image is loaded\/saved."}],"title":"SBSDKEncryptionMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencryptionmode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKEncryptionMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKEncryptionModeDisabled","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKEncryptionModeDisabled"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKEncryptionModeDisabled"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKEncryptionModeDisabled","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode~1disabled\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode~1disabled\/fragments","op":"replace","value":[{"text":"SBSDKEncryptionModeDisabled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode\/title","value":"SBSDKEncryptionMode"},{"value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode\/fragments"},{"value":[{"text":"SBSDKEncryptionMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode\/navigatorTitle"}]}]}