{"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"title":"initWithGenericDocument:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelEuropeanHealthInsuranceCard(im)initWithGenericDocument:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeanhealthinsurancecard\/initwithgenericdocument:"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithGenericDocument:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","text":"SBSDKGenericDocument"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"document"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanHealthInsuranceCard"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanHealthInsuranceCard\/initWithGenericDocument:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanHealthInsuranceCard/initWithGenericDocument:":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeanhealthinsurancecard\/initwithgenericdocument:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanHealthInsuranceCard\/initWithGenericDocument:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGenericDocument:"}],"title":"initWithGenericDocument:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithGenericDocument:"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"title":"SBSDKGenericDocument","abstract":[{"type":"text","text":"Generic document."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocument"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanHealthInsuranceCard":{"type":"topic","title":"SBSDKDocumentsModelEuropeanHealthInsuranceCard","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelEuropeanHealthInsuranceCard"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanHealthInsuranceCard","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelEuropeanHealthInsuranceCard"}],"abstract":[{"text":"European Health Insurance Card (EHIC). Supports formats with both four and five lines of data.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeanhealthinsurancecard","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","op":"replace","value":"SBSDKGenericDocument"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanHealthInsuranceCard\/title","op":"replace","value":"SBSDKDocumentsModelEuropeanHealthInsuranceCard"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanHealthInsuranceCard\/fragments","op":"replace","value":[{"text":"SBSDKDocumentsModelEuropeanHealthInsuranceCard","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanHealthInsuranceCard\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentsModelEuropeanHealthInsuranceCard"}]}]}]}