{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrenginemanager\/recognize(from:)-54e9j"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:)-54e9j","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Asynchronously recognizes characters on the image given by a file URL and returns the result, or throws an error otherwise."}],"metadata":{"externalID":"s:10ScanbotSDK21SBSDKOCREngineManagerC9recognize4fromAA14SBSDKOCRResultC10Foundation3URLV_tYaKF","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","kind":"typeIdentifier","text":"SBSDKOCRResult"}],"role":"symbol","title":"recognize(from:)"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@nonobjc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imageURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","text":"SBSDKOCRResult"}]}]},{"parameters":[{"name":"imageURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The file URL of the image to run the optical character recognition on."}]}]}],"kind":"parameters"},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"The OCR result object."}],"type":"paragraph"}],"kind":"content"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"In Swift language it is used with structured concurrency (async\/await)."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResult":{"url":"\/documentation\/scanbotsdk\/sbsdkocrresult","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKOCRResult","kind":"identifier"}],"title":"SBSDKOCRResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCRResult","kind":"identifier"}],"abstract":[{"text":"The result of an optical character recognition.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineManager/recognize(from:)-54e9j":{"url":"\/documentation\/scanbotsdk\/sbsdkocrenginemanager\/recognize(from:)-54e9j","role":"symbol","title":"recognize(from:)","type":"topic","abstract":[{"type":"text","text":"Asynchronously recognizes characters on the image given by a file URL and returns the result, or throws an error otherwise."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"SBSDKOCRResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:)-54e9j"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineManager":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCREngineManager","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKOCREngineManager","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrenginemanager","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager","type":"topic","title":"SBSDKOCREngineManager","abstract":[{"type":"text","text":"A class to perform optical character recognition (text) on an image (OCR)."}]}},"variantOverrides":[{"patch":[{"value":"SBSDKOCRResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/title"},{"value":[{"text":"SBSDKOCRResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKOCRResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/navigatorTitle"},{"value":"SBSDKOCREngineManager","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager\/title"},{"value":[{"text":"SBSDKOCREngineManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager\/fragments"},{"value":[{"text":"SBSDKOCREngineManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}