{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeFilter"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"text":"Accepts or rejects a scanned barcode in the context of already accepted barcodes.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(shouldAdd:toBarcodes:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldAdd","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"barcode"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem"},{"text":", ","kind":"text"},{"text":"toBarcodes","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"codes"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKBarcodeItem","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"barcode","content":[{"inlineContent":[{"text":"The barcode item to be accepted or rejected by the filter.","type":"text"}],"type":"paragraph"}]},{"name":"codes","content":[{"inlineContent":[{"text":"List of current already accepted barcodes.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the given barcode should be added, "},{"code":"false","type":"codeVoice"},{"type":"text","text":" otherwise."}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Accepts a barcodes, if it is not yet contained in the given array of accepted barcodes. Prevents duplicate barcodes."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodefilter\/shouldadd(_:tobarcodes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodefilter\/shouldadd(_:tobarcodes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"shouldAdd(_:toBarcodes:)","roleHeading":"Instance Method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeFilter(im)shouldAdd:toBarcodes:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shouldAdd"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"toBarcodes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem","text":"SBSDKBarcodeItem"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"shouldAdd:toBarcodes:"}],"platforms":[],"role":"symbol","symbolKind":"method"},"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}],"type":"paragraph"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeFilter\/shouldAdd(_:toBarcodes:)"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeFilter":{"role":"symbol","abstract":[{"type":"text","text":"A class for a barcode filtering that can be used in barcode scanning RTU-UI components."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeFilter","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeFilter"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodeFilter"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodefilter","kind":"symbol","type":"topic","title":"SBSDKUIBarcodeFilter","deprecated":true},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeFilter/shouldAdd(_:toBarcodes:)":{"abstract":[{"text":"Accepts or rejects a scanned barcode in the context of already accepted barcodes.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodefilter\/shouldadd(_:tobarcodes:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"shouldAdd","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"toBarcodes","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem","kind":"typeIdentifier","text":"SBSDKBarcodeItem"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeFilter\/shouldAdd(_:toBarcodes:)","navigatorTitle":[{"kind":"identifier","text":"shouldAdd:toBarcodes:"}],"deprecated":true,"title":"shouldAdd(_:toBarcodes:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeItem":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeItem"}],"abstract":[{"text":"A single barcode found in the input image. Barcodes with the same content but different locations in the image are","type":"text"},{"type":"text","text":" "},{"type":"text","text":"considered separate barcodes."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeitem","title":"SBSDKBarcodeItem","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeItem"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"shouldAdd:toBarcodes:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"shouldAdd:toBarcodes:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"shouldAdd:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcode"},{"text":" ","kind":"text"},{"text":"toBarcodes:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKBarcodeItem *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"codes","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"barcode","content":[{"inlineContent":[{"text":"The barcode item to be accepted or rejected by the filter.","type":"text"}],"type":"paragraph"}]},{"name":"codes","content":[{"inlineContent":[{"type":"text","text":"List of current already accepted barcodes."}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":""},{"code":"true","type":"codeVoice"},{"type":"text","text":" if the given barcode should be added, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise."}],"type":"paragraph"}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeFilter\/title","op":"replace","value":"SBSDKUIBarcodeFilter"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodeFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeFilter\/fragments"},{"op":"replace","value":[{"text":"SBSDKUIBarcodeFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeFilter\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeFilter~1shouldAdd(_:toBarcodes:)\/title","value":"shouldAdd:toBarcodes:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeFilter~1shouldAdd(_:toBarcodes:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"shouldAdd:toBarcodes:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/title","value":"SBSDKBarcodeItem"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeItem"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/navigatorTitle","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}