{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/documentscannerviewcontroller(_:didsnapdocumentimage:on:with:autosnapped:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/documentscannerviewcontroller(_:didsnapdocumentimage:on:with:autosnapped:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/SBSDKDocumentScannerViewControllerDelegate-Implementations"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentScannerViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"text":"SBSDKDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController"},{"kind":"text","text":", "},{"text":"didSnapDocumentImage","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"documentImage","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"originalImage"},{"kind":"text","text":": "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"autoSnapped"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"text":"The document scanner controller that called this function.","type":"text"}]}]},{"name":"documentImage","content":[{"inlineContent":[{"text":"The image of the document: cropped, filtered and perspective corrected.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The original image the document was scanned on.","type":"text"}]}],"name":"originalImage"},{"name":"result","content":[{"inlineContent":[{"type":"text","text":"The result of the document scanning."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"True","type":"codeVoice"},{"text":", if the result was automatically snapped, ","type":"text"},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"}]}],"name":"autoSnapped"}],"kind":"parameters"}],"metadata":{"title":"documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)","extendedModule":"ScanbotSDK","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerViewController(im)documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:","navigatorTitle":[{"kind":"identifier","text":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentScannerViewController"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSnapDocumentImage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"autoSnapped"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}]},"sections":[],"abstract":[{"text":"Informs the delegate that the document scanner scanned and captured a document and provides the original image, the cropped document image","type":"text"},{"text":" ","type":"text"},{"text":"and the result of the scanning.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewController/documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"documentScannerViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController"},{"text":", ","kind":"text"},{"text":"didSnapDocumentImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult"},{"text":"?, ","kind":"text"},{"text":"autoSnapped","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"title":"documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)","navigatorTitle":[{"kind":"identifier","text":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/documentscannerviewcontroller(_:didsnapdocumentimage:on:with:autosnapped:)","type":"topic","abstract":[{"text":"Informs the delegate that the document scanner scanned and captured a document and provides the original image, the cropped document image","type":"text"},{"text":" ","type":"text"},{"text":"and the result of the scanning.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A UIViewController subclass to show a camera screen and run a user guiding document scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","type":"topic","kind":"symbol","title":"SBSDKDocumentScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionResult":{"title":"SBSDKDocumentDetectionResult","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult","role":"symbol","abstract":[{"text":"Result of the document contour detection.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewController/SBSDKDocumentScannerViewControllerDelegate-Implementations":{"title":"SBSDKDocumentScannerViewControllerDelegate Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/SBSDKDocumentScannerViewControllerDelegate-Implementations","kind":"article","type":"topic","role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/sbsdkdocumentscannerviewcontrollerdelegate-implementations","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController","navigatorTitle":[{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}],"deprecated":true,"kind":"symbol","title":"SBSDKUIDocumentScannerViewController","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"documentScannerViewController:"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController"},{"kind":"text","text":" *) "},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didSnapDocumentImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"text":"documentImage","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"onImage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"originalImage","kind":"internalParam"},{"kind":"text","text":" "},{"text":"withResult:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"result"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoSnapped:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"autoSnapped"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController~1documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)\/title","value":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController~1documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:","kind":"identifier"}],"op":"replace"},{"value":"SBSDKDocumentScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/navigatorTitle"},{"value":"SBSDKDocumentDetectionResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/title"},{"value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController\/title","value":"SBSDKUIDocumentScannerViewController","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}