{"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Decodable.init(from:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ForegroundStyle"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2foregroundstyle\/init(from:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ForegroundStyle\/init(from:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"decoder"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"init(from:)","roleHeading":"Initializer","externalID":"s:25ScanbotDocumentScannerSDK23SBSDKUI2ForegroundStyleC4fromACs7Decoder_p_tKcfc","symbolKind":"init"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.1.1","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ForegroundStyle/init(from:)":{"kind":"symbol","title":"init(from:)","abstract":[],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2foregroundstyle\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ForegroundStyle\/init(from:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ForegroundStyle":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ForegroundStyle","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the appearance of foreground elements (e.g. text and\/or icons on buttons, etc)."}],"navigatorTitle":[{"text":"SBSDKUI2ForegroundStyle","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2foregroundstyle","title":"SBSDKUI2ForegroundStyle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ForegroundStyle","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ForegroundStyle\/title","value":"SBSDKUI2ForegroundStyle","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ForegroundStyle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ForegroundStyle\/fragments"},{"value":[{"text":"SBSDKUI2ForegroundStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ForegroundStyle\/navigatorTitle","op":"replace"}]}]}