{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ForegroundStyle\/toJson()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ForegroundStyle"]]},"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2foregroundstyle\/tojson()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2foregroundstyle\/tojson()"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"toJson"}],"symbolKind":"method","title":"toJson()","roleHeading":"Instance Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ForegroundStyle(im)toJson","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ForegroundStyle/toJson()":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"toJson"}],"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"title":"toJson()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2foregroundstyle\/tojson()","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ForegroundStyle\/toJson()"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ForegroundStyle":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ForegroundStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ForegroundStyle"}],"navigatorTitle":[{"text":"SBSDKUI2ForegroundStyle","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2foregroundstyle","title":"SBSDKUI2ForegroundStyle","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the appearance of foreground elements (e.g. text and\/or icons on buttons, etc)."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"toJson","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"toJson","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"toJson","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"toJson","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ForegroundStyle~1toJson()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ForegroundStyle~1toJson()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJson"}]},{"op":"replace","value":"SBSDKUI2ForegroundStyle","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ForegroundStyle\/title"},{"op":"replace","value":[{"text":"SBSDKUI2ForegroundStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ForegroundStyle\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}