{"metadata":{"title":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalCertificateIntroImage(im)init","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"init"}],"symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalcertificateintroimage\/init"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateIntroImage"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateIntroImage\/init"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateIntroImage":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificateintroimage","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateIntroImage"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalCertificateIntroImage"}],"abstract":[{"type":"text","text":"The image for the introduction screen with a medical certificate template."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateIntroImage","role":"symbol","title":"SBSDKUI2MedicalCertificateIntroImage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateIntroImage/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificateintroimage\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","title":"init","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateIntroImage\/init","abstract":[],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2MedicalCertificateIntroImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateIntroImage\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateIntroImage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateIntroImage\/fragments"},{"value":[{"text":"SBSDKUI2MedicalCertificateIntroImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateIntroImage\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}