{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarExpandedConfiguration\/fromJsonWithJson:"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarExpandedConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatDataBarExpandedConfiguration","text":"SBSDKBarcodeFormatDataBarExpandedConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarExpandedConfiguration"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatdatabarexpandedconfiguration\/fromjsonwithjson:"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatDataBarExpandedConfiguration(cm)fromJsonWithJson:","title":"fromJsonWithJson:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"kind":"text","text":"+ "},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol","roleHeading":"Type Method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatDataBarExpandedConfiguration/fromJsonWithJson:":{"fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatdatabarexpandedconfiguration\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarExpandedConfiguration\/fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatDataBarExpandedConfiguration":{"title":"SBSDKBarcodeFormatDataBarExpandedConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormatDataBarExpandedConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"GS1 DataBar Expanded barcode configuration. Add to scanner configuration to scan GS1 DataBar Expanded and GS1","type":"text"},{"type":"text","text":" "},{"text":"DataBar Expanded Stacked barcodes.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarExpandedConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatdatabarexpandedconfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatDataBarExpandedConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatDataBarExpandedConfiguration\/title","value":"SBSDKBarcodeFormatDataBarExpandedConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatDataBarExpandedConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatDataBarExpandedConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatDataBarExpandedConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatDataBarExpandedConfiguration","kind":"identifier"}],"op":"replace"}]}]}