{"abstract":[{"type":"text","text":"Inherited from "},{"code":"View.focusedSceneObject(_:)","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerview\/focusedsceneobject(_:)-ogiv"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/View-Implementations"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusedSceneObject"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"},{"kind":"text","text":" "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine16ObservableObjectP","text":"ObservableObject"},{"kind":"text","text":"\n"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/focusedSceneObject(_:)-ogiv"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"extendedModule":"SwiftUICore","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusedSceneObject"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier","text":"View"}],"platforms":[{"introducedAt":"16.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"16.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"16.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"13.0","name":"macOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"16.0","name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"9.0","name":"watchOS","deprecated":false,"unavailable":false,"beta":false}],"roleHeading":"Instance Method","title":"focusedSceneObject(_:)","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}],"role":"symbol","externalID":"s:7SwiftUI4ViewPAAE18focusedSceneObjectyQrqd__7Combine010ObservableF0Rd__lF::SYNTHESIZED::s:10ScanbotSDK24SBSDKUI2CheckScannerViewV","symbolKind":"method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerviewcontroller","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan check data.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"title":"SBSDKUI2CheckScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerView":{"type":"topic","kind":"symbol","abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController","type":"reference","isActive":true},{"text":".","type":"text"}],"title":"SBSDKUI2CheckScannerView","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CheckScannerView","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerview","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CheckScannerView","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerView/View-Implementations":{"role":"collectionGroup","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/View-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerview\/view-implementations","abstract":[],"kind":"article","title":"View Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerView/focusedSceneObject(_:)-ogiv":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/focusedSceneObject(_:)-ogiv","abstract":[],"type":"topic","kind":"symbol","title":"focusedSceneObject(_:)","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerview\/focusedsceneobject(_:)-ogiv","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusedSceneObject"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2CheckScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/navigatorTitle"}]}]}