{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"Equatable Implementations","roleHeading":"API Collection","role":"collectionGroup"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkocrenginemode\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/!=(_:_:)"],"anchor":"Operators","title":"Operators"}],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/Equatable-Implementations"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineMode/!=(_:_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/!=(_:_:)","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkocrenginemode\/!=(_:_:)","title":"!=(_:_:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineMode":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkocrenginemode","title":"SBSDKOCREngineMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCREngineMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKOCREngineMode"}],"abstract":[{"type":"text","text":"An enum describing the modes of the optical character recognition engine."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKOCREngineMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOCREngineMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode\/fragments"},{"op":"replace","value":[{"text":"SBSDKOCREngineMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}