{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementscreenconfiguration\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementScreenConfiguration(im)isEqual:"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration\/isEqual:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementScreenConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementscreenconfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration of the acknowledgement screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration","kind":"symbol","role":"symbol","title":"SBSDKUI2AcknowledgementScreenConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementScreenConfiguration/isEqual:":{"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration\/isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementscreenconfiguration\/isequal:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/title","value":"SBSDKUI2AcknowledgementScreenConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/fragments","value":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"op":"replace"}]}]}