{"abstract":[{"text":"Data element ID “ISC”. An indicator that specifies whether or not the vehicle has a current smog certificate.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"inspectionSmogCertificateIndicator","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"inspectionSmogCertificateIndicator"}],"title":"inspectionSmogCertificateIndicator","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData(py)inspectionSmogCertificateIndicator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inspectionSmogCertificateIndicator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/inspectionsmogcertificateindicator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/inspectionsmogcertificateindicator"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionSmogCertificateIndicator","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData/inspectionSmogCertificateIndicator":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/inspectionsmogcertificateindicator","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionSmogCertificateIndicator","title":"inspectionSmogCertificateIndicator","navigatorTitle":[{"text":"inspectionSmogCertificateIndicator","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Data element ID “ISC”. An indicator that specifies whether or not the vehicle has a current smog certificate.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inspectionSmogCertificateIndicator","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentField":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"title":"SBSDKGenericDocumentField","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentfield","abstract":[{"type":"text","text":"A generic document field."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentField"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData":{"type":"topic","title":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","abstract":[{"text":"Vehicle Safety Inspection Data. File type “VS”.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"inspectionSmogCertificateIndicator"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"inspectionSmogCertificateIndicator","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"kind":"text","text":" * "},{"kind":"identifier","text":"inspectionSmogCertificateIndicator"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectionSmogCertificateIndicator\/title","op":"replace","value":"inspectionSmogCertificateIndicator"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectionSmogCertificateIndicator\/fragments","op":"replace","value":[{"text":"inspectionSmogCertificateIndicator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentField\/title","op":"replace","value":"SBSDKGenericDocumentField"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentField\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentField\/navigatorTitle","op":"replace","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/title","op":"replace","value":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"identifier"}]}]}]}