{"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"generateErrorWithCode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKErrorType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKErrorType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType"},{"text":") ","kind":"text"},{"text":"code","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"desc:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"desc","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrorgenerator\/generateerrorwithcode:desc:"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorGenerator\/generateErrorWithCode:desc:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorGenerator"]]},"metadata":{"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"title":"generateErrorWithCode:desc:","navigatorTitle":[{"text":"generateErrorWithCode:desc:","kind":"identifier"}],"roleHeading":"Type Method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKErrorGenerator(cm)generateErrorWithCode:desc:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"generateErrorWithCode:desc:"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorGenerator":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorGenerator","url":"\/documentation\/scanbotsdk\/sbsdkerrorgenerator","fragments":[{"text":"SBSDKErrorGenerator","kind":"identifier"}],"abstract":[],"type":"topic","title":"SBSDKErrorGenerator","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorGenerator/generateErrorWithCode:desc:":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"generateErrorWithCode:desc:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorGenerator\/generateErrorWithCode:desc:","url":"\/documentation\/scanbotsdk\/sbsdkerrorgenerator\/generateerrorwithcode:desc:","fragments":[{"text":"+ ","kind":"text"},{"text":"generateErrorWithCode:desc:","kind":"identifier"}],"abstract":[],"type":"topic","title":"generateErrorWithCode:desc:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKErrorType"}],"role":"symbol","abstract":[{"type":"text","text":"An Objective-C compatible enum representing the types of errors that can occur within the Scanbot SDK."},{"type":"text","text":" "},{"type":"text","text":"Each case corresponds to a specific error code."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkerrortype","title":"SBSDKErrorType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKErrorType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/title","op":"replace"},{"value":[{"text":"SBSDKErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKErrorType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/navigatorTitle","op":"replace"}]}]}