{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(absolutePointFromNormalizedPoint:withSize:) "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"absolutePoint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromNormalizedPoint","kind":"externalParam"},{"kind":"text","text":" "},{"text":"point","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"size"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The normalized point to convert into absolute space."}]}],"name":"point"},{"content":[{"inlineContent":[{"type":"text","text":"The size of the absolute coordinate system."}],"type":"paragraph"}],"name":"size"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The converted point.","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/absolutePoint(fromNormalizedPoint:with:)"},"metadata":{"title":"absolutePoint(fromNormalizedPoint:with:)","role":"symbol","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"absolutePoint","kind":"identifier"},{"kind":"text","text":"("},{"text":"fromNormalizedPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"absolutePointFromNormalizedPoint:withSize:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon(cm)absolutePointFromNormalizedPoint:withSize:","roleHeading":"Type Method"},"abstract":[{"text":"Helper method to transform an absolute point to the normalized unit coordinate system with given size.","type":"text"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon\/absolutepoint(fromnormalizedpoint:with:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon\/absolutepoint(fromnormalizedpoint:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/absolutePoint(fromNormalizedPoint:with:)":{"type":"topic","title":"absolutePoint(fromNormalizedPoint:with:)","abstract":[{"text":"Helper method to transform an absolute point to the normalized unit coordinate system with given size.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"absolutePointFromNormalizedPoint:withSize:"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/absolutepoint(fromnormalizedpoint:with:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/absolutePoint(fromNormalizedPoint:with:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"absolutePoint"},{"text":"(","kind":"text"},{"text":"fromNormalizedPoint","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":") -> ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","title":"SBSDKPolygon","url":"\/documentation\/scanbotsdk\/sbsdkpolygon","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPolygon"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"absolutePointFromNormalizedPoint:withSize:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"absolutePointFromNormalizedPoint:withSize:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") "},{"text":"absolutePointFromNormalizedPoint:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"point","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withSize:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"size"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1absolutePoint(fromNormalizedPoint:with:)\/title","value":"absolutePointFromNormalizedPoint:withSize:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"absolutePointFromNormalizedPoint:withSize:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1absolutePoint(fromNormalizedPoint:with:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","op":"replace","value":"SBSDKPolygon"},{"op":"replace","value":[{"text":"SBSDKPolygon","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments"}]}]}