{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon\/init(normalizeddoublevalues:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon\/init(normalizeddoublevalues:)"]}],"kind":"symbol","metadata":{"symbolKind":"init","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"initWithNormalizedDoubleValues:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon(im)initWithNormalizedDoubleValues:","title":"init(normalizedDoubleValues:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"normalizedDoubleValues","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"roleHeading":"Initializer"},"abstract":[{"type":"text","text":"One of the designated initializer methods."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithNormalizedDoubleValues:) ","kind":"text"},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"normalizedDoubleValues","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"values","kind":"internalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"])","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"values","content":[{"inlineContent":[{"text":"An array of 8 NSNumber double values containing the normalized coordinates in the form [x1, y1, x2, y2, x3, y3, x4, y4].","type":"text"}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(normalizedDoubleValues:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPolygon","kind":"identifier"}],"role":"symbol","title":"SBSDKPolygon","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"abstract":[{"text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/init(normalizedDoubleValues:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(normalizedDoubleValues:)","type":"topic","abstract":[{"type":"text","text":"One of the designated initializer methods."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/init(normalizeddoublevalues:)","navigatorTitle":[{"text":"initWithNormalizedDoubleValues:","kind":"identifier"}],"title":"init(normalizedDoubleValues:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"normalizedDoubleValues","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"])","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithNormalizedDoubleValues:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithNormalizedDoubleValues:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithNormalizedDoubleValues:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"values","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKPolygon","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","value":[{"text":"SBSDKPolygon","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1init(normalizedDoubleValues:)\/title","value":"initWithNormalizedDoubleValues:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1init(normalizedDoubleValues:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithNormalizedDoubleValues:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}